import Formalization.Books.Algebra.Unit37.NormalRings
import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import Mathlib.RingTheory.IntegralClosure.Algebra.Ideal
import Mathlib.RingTheory.IntegralClosure.GoingDown

/-!
# Commutative Algebra, Chapter 38: Going down for integral over normal

This file records the definitions and theorem interfaces in the section on
integrality over ideals and going down for integral extensions of normal
domains.  Mathlib's canonical polynomial, minimal-polynomial, ideal-over, and
going-down APIs are reused wherever they express the source statements.
-/

namespace Formalization.Books.Algebra.Unit38

universe u v w

noncomputable section

open Set
open scoped Polynomial

/-! ## Elements integral over an ideal -/

/-- An element is integral over an ideal when it satisfies a monic equation
whose coefficient of degree `i` lies in the `d - i`-th power of the ideal,
where `d` is the degree of the monic polynomial. -/
def IsIntegralOverIdeal
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) (s : S) : Prop :=
  ∃ p : R[X], p.Monic ∧ Polynomial.eval₂ f s p = 0 ∧
    ∀ i, i < p.natDegree → p.coeff i ∈ I ^ (p.natDegree - i)

/-- The set called the integral closure of an ideal in the source. -/
def integralClosureOfIdeal
    {R : Type*} [CommRing R] (I : Ideal R) : Set R :=
  {s | IsIntegralOverIdeal (RingHom.id R) I s}

/-- The polynomial subalgebra generated by `R` and the elements `r * X` for
`r` in the ideal.  This is the canonical algebraic form of the source's
`∑ I^n t^n` subring. -/
def integralOverIdealPolynomialSubalgebra
    {R : Type*} [CommRing R] (I : Ideal R) : Subalgebra R R[X] :=
  Algebra.adjoin R {Polynomial.C r * Polynomial.X | r ∈ I}

/-- The coefficientwise polynomial map restricted to the subalgebra used in
`integralOverIdealPolynomialSubalgebra`. -/
def integralOverIdealPolynomialMap
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) :
    integralOverIdealPolynomialSubalgebra I →+* S[X] :=
  (Polynomial.mapRingHom f).comp
    (integralOverIdealPolynomialSubalgebra I).val.toRingHom

/-- The original ideal is contained in its integral closure. -/
theorem ideal_subset_integralClosureOfIdeal
    {R : Type*} [CommRing R] (I : Ideal R) :
    (I : Set R) ⊆ integralClosureOfIdeal I := by
  sorry

/-! ## Polynomial characterization -/

/-- Integrality over an ideal is equivalent to integrality of `s * X` over
`R[I X]` in the polynomial ring. -/
theorem integralOverIdeal_iff
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) (s : S) :
    IsIntegralOverIdeal f I s ↔
      (integralOverIdealPolynomialMap f I).IsIntegralElem
        (Polynomial.C s * Polynomial.X) := by
  sorry

/-! ## Closure properties -/

/-- The elements integral over an ideal form an `R`-submodule after restricting
scalars along the defining ring map. -/
theorem integralOverIdeal_isSubmodule
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) :
    letI : Module R S := Module.compHom S f
    ∃ M : Submodule R S,
      ∀ s : S, s ∈ M ↔ IsIntegralOverIdeal f I s := by
  sorry

/-- The preceding submodule is an ideal for the identity map. -/
theorem integralClosureOfIdeal_isIdeal
    {R : Type*} [CommRing R] (I : Ideal R) :
    ∃ J : Ideal R, (J : Set R) = integralClosureOfIdeal I := by
  sorry

/-- Multiplication by an element integral over the base ring preserves
integrality over the ideal. -/
theorem isIntegral_mul_integralOverIdeal
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) {s s' : S}
    (hs : f.IsIntegralElem s)
    (hs' : IsIntegralOverIdeal f I s') :
    IsIntegralOverIdeal f I (s * s') := by
  sorry

/-- If a ring map is integral, every element of the extended ideal is
integral over the original ideal. -/
theorem isIntegralOverIdeal_of_mem_map
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (hf : f.IsIntegral) (I : Ideal R) {s : S}
    (hs : s ∈ I.map f) :
    IsIntegralOverIdeal f I s := by
  sorry

/-! ## Divisibility of monic polynomials -/

/-- If a monic polynomial divides a monic polynomial over a field, then the
coefficients of the divisor are integral over every subring containing the
non-leading coefficients of the dividend. -/
theorem polynomial_divisor_coeff_isIntegral
    {K : Type*} [Field K] (p q : K[X])
    (hp : p.Monic) (hq : q.Monic) (hdiv : p ∣ q)
    (T : Subring K)
    (hT : ∀ i, i < q.natDegree → q.coeff i ∈ (T : Set K)) :
    ∀ i, i < p.natDegree → IsIntegral T (p.coeff i) := by
  sorry

/- The second conclusion of the source lemma is stated over a subring of the
   field containing both sets of coefficients.  The coefficient set below is
   the corresponding finite generating set, written without choosing an
   enumeration of the coefficients. -/
theorem polynomial_divisor_coeff_mem_radical
    {K : Type*} [Field K] (p q : K[X])
    (hp : p.Monic) (hq : q.Monic) (hdiv : p ∣ q)
    (T : Subring K)
    (hpT : ∀ i, i < p.natDegree → p.coeff i ∈ (T : Set K))
    (hqT : ∀ i, i < q.natDegree → q.coeff i ∈ (T : Set K)) :
    ∀ (i : ℕ) (hi : i < p.natDegree),
      (⟨p.coeff i, hpT i hi⟩ : T) ∈
        Ideal.radical (Ideal.span
          {b : T | ∃ j, j < q.natDegree ∧ (b : K) = q.coeff j}) := by
  sorry

/-! ## Minimal polynomials over a normal domain -/

/-- For a normal domain `R`, the coefficients of the minimal polynomial over a
fraction field `K` of an element integral over `R` come from `R`. -/
theorem minpoly_coeff_mem_range_of_isNormalDomain
    {R S K : Type*} [CommRing R] [CommRing S] [Field K]
    [IsDomain S] [Algebra R S] [Algebra R K] [IsFractionRing R K]
    [Algebra K S] [IsScalarTower R K S]
    (hR : Formalization.Books.Algebra.Unit37.IsNormalDomain R)
    (g : S) (hg : IsIntegral R g) :
    ∀ i, (minpoly K g).coeff i ∈ Set.range (algebraMap R K) := by
  sorry

/-! ## Going down -/

/-- An integral extension of domains with normal base satisfies going down.
This is the source-facing ideal formulation of `Algebra.HasGoingDown`. -/
theorem goingDown_normal_integral
    {R S : Type*} [CommRing R] [CommRing S] [IsDomain S]
    [Algebra R S] [FaithfulSMul R S] [Algebra.IsIntegral R S]
    (hR : Formalization.Books.Algebra.Unit37.IsNormalDomain R)
    {p p' : Ideal R} [p.IsPrime] [p'.IsPrime] (hpp : p ≤ p')
    (Q : Ideal S) [Q.IsPrime] [Q.LiesOver p'] :
    ∃ P : Ideal S, P ≤ Q ∧ P.IsPrime ∧ P.LiesOver p := by
  sorry

end

end Formalization.Books.Algebra.Unit38
