import Formalization.Books.Algebra.Unit03.BasicNotions
import Formalization.Books.Algebra.Unit54.EssentiallyFiniteType
import Formalization.Books.Algebra.Unit82.UniversallyInjective
import Mathlib.Algebra.GroupWithZero.NonZeroDivisors
import Mathlib.LinearAlgebra.TensorProduct.Map
import Mathlib.RingTheory.Ideal.AssociatedPrime.Basic
import Mathlib.RingTheory.Localization.Module
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.Spectrum.Prime.RingHom

/-!
# More on Flatness, Chapter 7: Localization and universally injective maps

The source's homothety quotient is represented by the ideal induced from the
maximal ideal of the local base ring.  Its tensor products are written in the
canonically symmetric orientation `S' ⊗[S] N`, so that the first factor carries
the scalar action used by Mathlib's tensor-product API.
-/

namespace Formalization.Books.Flat.Unit07

open Formalization.Books.Algebra.Unit82
open scoped TensorProduct

universe u

noncomputable section

/-! ## Homotheties and the special fibre -/

/-- The ideal of `S` generated by the maximal ideal of a local base ring. -/
def homothetyIdeal
    {R S : Type u} [CommRing R] [CommRing S] [IsLocalRing R]
    (f : R →+* S) : Ideal S :=
  Ideal.map f (IsLocalRing.maximalIdeal R)

/-- The special-fibre quotient of an `S`-module for the homothety ideal. -/
abbrev homothetyReduction
    {R S N : Type u} [CommRing R] [CommRing S]
    [AddCommGroup N] [Module S N] [IsLocalRing R]
    (f : R →+* S) : Type u :=
  N ⧸ (homothetyIdeal f • (⊤ : Submodule S N))

/-- The elements acting regularly on the homothety reduction. -/
def homothetySigma
    {R S N : Type u} [CommRing R] [CommRing S]
    [AddCommGroup N] [Module S N] [IsLocalRing R]
    (f : R →+* S) : Submonoid S :=
  nonZeroSMulDivisors S (homothetyReduction (N := N) f)

/--
The spectrum description attached to the homothety reduction.  The first
conjunct is the semilocality assertion; the second records the associated-
prime criterion for primes disjoint from the regular-element submonoid and the
correspondence for maximal ideals after localization.
-/
theorem homothety_spectrum
    {R S N : Type u} [CommRing R] [CommRing S]
    [AddCommGroup N] [Module S N] [IsLocalRing R]
    (f : R →+* S)
    [IsNoetherianRing (S ⧸ homothetyIdeal (R := R) f)]
    [Module.Finite (S ⧸ homothetyIdeal (R := R) f)
      (homothetyReduction (N := N) f)] :
    Formalization.Books.Algebra.Unit03.IsSemilocalRing
        (Localization (homothetySigma (N := N) f)) ∧
      (∀ (q : Ideal S) [q.IsPrime],
        Disjoint (q : Set S) (homothetySigma (N := N) f : Set S) ↔
          ∃ p : Ideal S,
            p ∈ _root_.associatedPrimes S (homothetyReduction (N := N) f) ∧
              q ≤ p) ∧
      (∀ (P : Ideal (Localization (homothetySigma (N := N) f))) [P.IsMaximal],
        ∃ p : Ideal (S ⧸ homothetyIdeal f),
          p ∈ _root_.associatedPrimes (S ⧸ homothetyIdeal f)
              (homothetyReduction (N := N) f) ∧
            P.comap (algebraMap S (Localization (homothetySigma (N := N) f))) =
              p.comap (Ideal.Quotient.mk (homothetyIdeal f))) := by
  sorry

/-! ## Localization of a flat module -/

/-
The exact sequence `0 → N → N → N/sN → 0` and the directed-colimit diagram
in the source are proof scaffolding for the following interface.  They are
not separate chapter declarations: the theorem records their mathematical
conclusion, namely universal injectivity of each homothety and of the map to
the localized module.
-/
theorem homothety_universally_injective
    {R S N : Type u} [CommRing R] [CommRing S]
    [AddCommGroup N] [Module S N] [IsLocalRing R] [IsLocalRing S]
    (f : R →+* S)
    [IsNoetherianRing (S ⧸ homothetyIdeal (R := R) f)]
    [Module.Finite (S ⧸ homothetyIdeal (R := R) f)
      (homothetyReduction (N := N) f)] :
    letI : Algebra R S := f.toAlgebra
    letI : Module R N := Module.restrictScalars R S N
    letI : IsScalarTower R S N := IsScalarTower.restrictScalars R S N
    letI : SMul R (LocalizedModule (homothetySigma (N := N) f) N) :=
      SMul.comp (LocalizedModule (homothetySigma (N := N) f) N) f
    letI : Module R (LocalizedModule (homothetySigma (N := N) f) N) :=
      Module.compHom (LocalizedModule (homothetySigma (N := N) f) N) f
    letI : IsScalarTower R S (LocalizedModule (homothetySigma (N := N) f) N) :=
      IsScalarTower.of_algebraMap_smul (R := R) (A := S)
        (M := LocalizedModule (homothetySigma (N := N) f) N)
        (fun r x => by
          rw [RingHom.algebraMap_toAlgebra]
          change f r • x = f r • x
          rfl)
    IsLocalHom f →
      Formalization.Books.Algebra.Unit54.RingHom.EssFinitePresentation f →
        Module.FinitePresentation S N →
          Module.Flat R N →
            (∀ s : homothetySigma (N := N) f,
              universallyInjectiveOver (R := R) (A := S)
                (LinearMap.lsmul S N (s : S))) ∧
              universallyInjectiveOver (R := R) (A := S)
                (LocalizedModule.mkLinearMap (homothetySigma (N := N) f) N) := by
  sorry

/-! ## Base change -/

/--
The canonical base-change map, with the source's `N ⊗_S S'` written as the
symmetric tensor `S' ⊗[S] N` so its `S'`-module structure is canonical.
-/
def scalarBaseChangeMap
    {R S T N : Type u} [CommRing R] [CommRing S] [CommRing T]
    [AddCommGroup N] [Module S N]
    (f : R →+* S) (g : S →+* T) :
    letI : Algebra R S := f.toAlgebra
    letI : Algebra S T := g.toAlgebra
    letI : Module S T := Algebra.toModule
    letI : Module R N := Module.restrictScalars R S N
    letI : IsScalarTower R S N := IsScalarTower.restrictScalars R S N
    letI : Module T (T ⊗[S] N) := TensorProduct.leftModule
    letI : Module R (T ⊗[S] N) := Module.restrictScalars R S (T ⊗[S] N)
    letI : IsScalarTower R S (T ⊗[S] N) :=
      IsScalarTower.restrictScalars R S (T ⊗[S] N)
    N →ₗ[R] T ⊗[S] N := by
  letI : Algebra R S := f.toAlgebra
  letI : Algebra S T := g.toAlgebra
  letI : Module S T := Algebra.toModule
  letI : Module R N := Module.restrictScalars R S N
  letI : IsScalarTower R S N := IsScalarTower.restrictScalars R S N
  letI : Module T (T ⊗[S] N) := TensorProduct.leftModule
  letI : Module R (T ⊗[S] N) := Module.restrictScalars R S (T ⊗[S] N)
  letI : IsScalarTower R S (T ⊗[S] N) :=
    IsScalarTower.restrictScalars R S (T ⊗[S] N)
  exact ((TensorProduct.mk S T N) (1 : T)).restrictScalars R

/-
The source writes `N' = N ⊗_R S'` in the proof of the local base-change
lemma, while the statement and the comparison diagram use `N ⊗_S S'`.
The source also omits the Noetherian and finite-special-fibre hypotheses from
the displayed assumption list even though its proof invokes the preceding
homothety-spectrum lemma.  They are retained below as the necessary inherited
hypotheses.  The declaration follows the statement and uses
`scalarBaseChangeMap`; the square of localization maps and the faithful-flat
comparison in the proof are proof scaffolding rather than separate interfaces.
-/
theorem base_change_universally_injective_local
    {R S T N : Type u} [CommRing R] [CommRing S] [CommRing T]
    [AddCommGroup N] [Module S N] [IsLocalRing R] [IsLocalRing S]
    (f : R →+* S)
    [IsNoetherianRing (S ⧸ homothetyIdeal (R := R) f)]
    [Module.Finite (S ⧸ homothetyIdeal (R := R) f)
      (homothetyReduction (N := N) f)]
    (g : S →+* T) :
    letI : Algebra R S := f.toAlgebra
    letI : Algebra S T := g.toAlgebra
    letI : Module S T := Algebra.toModule
    letI : Module R N := Module.restrictScalars R S N
    letI : IsScalarTower R S N := IsScalarTower.restrictScalars R S N
    letI : Module T (T ⊗[S] N) := TensorProduct.leftModule
    letI : Module R (T ⊗[S] N) := Module.restrictScalars R S (T ⊗[S] N)
    letI : IsScalarTower R S (T ⊗[S] N) :=
      IsScalarTower.restrictScalars R S (T ⊗[S] N)
    IsLocalHom f →
      Formalization.Books.Algebra.Unit54.RingHom.EssFinitePresentation f →
        Module.FinitePresentation S N →
          Module.Flat R N →
            RingHom.Flat g →
              (∀ (q : PrimeSpectrum S),
                q.asIdeal.comap f = IsLocalRing.maximalIdeal R →
                q.asIdeal ∈ _root_.associatedPrimes S
                    (homothetyReduction (N := N) f) →
                  q ∈ Set.range (PrimeSpectrum.comap g)) →
                universallyInjective (scalarBaseChangeMap (N := N) f g) := by
  sorry

theorem base_change_universally_injective
    {R S T N : Type u} [CommRing R] [CommRing S] [CommRing T]
    [AddCommGroup N] [Module S N]
    (f : R →+* S) (g : S →+* T) :
    letI : Algebra R S := f.toAlgebra
    letI : Algebra S T := g.toAlgebra
    letI : Module S T := Algebra.toModule
    letI : Module R N := Module.restrictScalars R S N
    letI : IsScalarTower R S N := IsScalarTower.restrictScalars R S N
    letI : Module T (T ⊗[S] N) := TensorProduct.leftModule
    letI : Module R (T ⊗[S] N) := Module.restrictScalars R S (T ⊗[S] N)
    letI : IsScalarTower R S (T ⊗[S] N) :=
      IsScalarTower.restrictScalars R S (T ⊗[S] N)
    RingHom.FinitePresentation f →
      Module.FinitePresentation S N →
        Module.Flat R N →
          RingHom.Flat g →
            (∀ (q : PrimeSpectrum S),
              letI : Module S
                  (N ⊗[R] (q.asIdeal.comap f).ResidueField) :=
                TensorProduct.leftModule
              q.asIdeal ∈ _root_.associatedPrimes S
                  (N ⊗[R] (q.asIdeal.comap f).ResidueField) →
                q ∈ Set.range (PrimeSpectrum.comap g)) →
              universallyInjective (scalarBaseChangeMap (N := N) f g) := by
  sorry

/-! ## The local criterion -/

/-
The comparison warning in the source points back to the earlier
flat-cokernel criteria; it introduces no additional interface.  The induced
map modulo the maximal ideal is represented by the existing
`quotientMapByIdeal` construction.
-/
theorem universally_injective_local
    {R M N : Type u} [CommRing R] [IsLocalRing R]
    [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
    [Module.Projective R M] [Module.Flat R N]
    (u : M →ₗ[R] N)
    (hu : Function.Injective
      (quotientMapByIdeal (IsLocalRing.maximalIdeal R) u)) :
    universallyInjective u := by
  sorry

/-! ## Projective modules -/

theorem invert_universally_injective
    {R S N : Type u} [CommRing R] [CommRing S]
    [AddCommGroup N] [Module S N] [IsLocalRing R]
    (f : R →+* S)
    [IsNoetherianRing (S ⧸ homothetyIdeal (R := R) f)]
    [Module.Finite (S ⧸ homothetyIdeal (R := R) f)
      (homothetyReduction (N := N) f)] :
    letI : Algebra R S := f.toAlgebra
    letI : Module R N := Module.restrictScalars R S N
    letI : IsScalarTower R S N := IsScalarTower.restrictScalars R S N
    letI : SMul R (LocalizedModule (homothetySigma (N := N) f) N) :=
      SMul.comp (LocalizedModule (homothetySigma (N := N) f) N) f
    letI : Module R (LocalizedModule (homothetySigma (N := N) f) N) :=
      Module.compHom (LocalizedModule (homothetySigma (N := N) f) N) f
    letI : IsScalarTower R S (LocalizedModule (homothetySigma (N := N) f) N) :=
      IsScalarTower.of_algebraMap_smul (R := R) (A := S)
        (M := LocalizedModule (homothetySigma (N := N) f) N)
        (fun r x => by
          rw [RingHom.algebraMap_toAlgebra]
          change f r • x = f r • x
          rfl)
    Module.Projective R N →
      (∀ s : homothetySigma (N := N) f,
        universallyInjectiveOver (R := R) (A := S)
          (LinearMap.lsmul S N (s : S))) ∧
        universallyInjectiveOver (R := R) (A := S)
          (LocalizedModule.mkLinearMap (homothetySigma (N := N) f) N) := by
  sorry

end

end Formalization.Books.Flat.Unit07
