import Formalization.Books.Brauer.Unit01.Wedderburn
import Mathlib.Algebra.Field.IsField
import Mathlib.Algebra.Field.ULift
import Mathlib.Algebra.Azumaya.Defs
import Mathlib.Algebra.Algebra.Subalgebra.Centralizer
import Mathlib.Algebra.Central.Matrix
import Mathlib.Algebra.Central.End
import Mathlib.Algebra.Central.TensorProduct
import Mathlib.Algebra.Module.LinearMap.Basic
import Mathlib.Data.Matrix.Basis
import Mathlib.LinearAlgebra.Matrix.Ideal
import Mathlib.LinearAlgebra.Matrix.Action
import Mathlib.LinearAlgebra.Matrix.FiniteDimensional
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.LinearAlgebra.TensorProduct.Quotient
import Mathlib.LinearAlgebra.TensorProduct.RightExactness
import Mathlib.RingTheory.Morita.Matrix
import Mathlib.RingTheory.MatrixAlgebra
import Mathlib.RingTheory.Artinian.Instances
import Mathlib.RingTheory.HopkinsLevitzki
import Mathlib.RingTheory.SimpleRing.Field
import Mathlib.RingTheory.SimpleModule.Isotypic
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.RingTheory.TensorProduct.Nontrivial
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Lemmas on algebras

This file records the centralizer, tensor-product, matrix-module, and
endomorphism-ring interfaces used in Section 4 of the source.
-/

namespace Formalization.Books.Brauer

universe u_k u_A u_N u_V u_K

open scoped TensorProduct Matrix.Module

section TensorSubspaces

variable (k V K : Type*)

/-- Left multiplication by an element of the second tensor factor. -/
def tensorLeftMultiply [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [SMulCommClass k K K]
    (c : K) : V ⊗[k] K →ₗ[k] V ⊗[k] K :=
  TensorProduct.map (LinearMap.id : V →ₗ[k] V) (LinearMap.mulLeft k c)

/-- Right multiplication by an element of the second tensor factor. -/
def tensorRightMultiply [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [IsScalarTower k K K]
    (c : K) : V ⊗[k] K →ₗ[k] V ⊗[k] K :=
  TensorProduct.map (LinearMap.id : V →ₗ[k] V) (LinearMap.mulRight k c)

/-- The source's notion of a two-sided `K`-subspace. -/
def TwoSidedKSubspace [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [SMulCommClass k K K] [IsScalarTower k K K]
    (W : Submodule k (V ⊗[k] K)) : Prop :=
  (∀ c x, x ∈ W → tensorLeftMultiply k V K c x ∈ W) ∧
    ∀ c x, x ∈ W → tensorRightMultiply k V K c x ∈ W

/-- The left `K`-span of a set in a tensor product. -/
def leftKSpan [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [SMulCommClass k K K]
    (s : Set (V ⊗[k] K)) : Submodule k (V ⊗[k] K) :=
  Submodule.span k {z | ∃ c : K, ∃ x ∈ s, z = tensorLeftMultiply k V K c x}

end TensorSubspaces

section TensorIdeals

variable (k A K : Type*)

/-- The two-sided ideal generated by pure tensors from a two-sided ideal. -/
def tensorTwoSidedIdeal [CommRing k] [Ring A] [Algebra k A]
    [DivisionRing K] [Algebra k K] (J : TwoSidedIdeal A) :
    TwoSidedIdeal (A ⊗[k] K) :=
  TwoSidedIdeal.span {z | ∃ a : A, a ∈ J ∧ ∃ c : K, z = a ⊗ₜ[k] c}

end TensorIdeals

section Centralizers

theorem centralizer_tensor_product (k A A' : Type*) [Field k]
    [Ring A] [Algebra k A] [Ring A'] [Algebra k A']
    (B : Subalgebra k A) (B' : Subalgebra k A') :
    Subalgebra.centralizer k
        (Algebra.TensorProduct.map B.val B'.val).range =
      (Algebra.TensorProduct.map
        (Subalgebra.centralizer k (B : Set A)).val
        (Subalgebra.centralizer k (B' : Set A')).val).range := by
  classical
  have h_inter (P : Submodule k A) (Q : Submodule k A') :
      LinearMap.range (TensorProduct.map P.subtype (LinearMap.id : A' →ₗ[k] A')) ⊓
          LinearMap.range (TensorProduct.map (LinearMap.id : A →ₗ[k] A) Q.subtype) =
        LinearMap.range (TensorProduct.map P.subtype Q.subtype) := by
    apply le_antisymm
    · rintro x ⟨hxP, hxQ⟩
      obtain ⟨z, hz⟩ := hxQ
      have hx0 : (LinearMap.rTensor A' P.mkQ) x = 0 := by
        obtain ⟨y, hy⟩ := hxP
        rw [← hy]
        change (LinearMap.rTensor A' P.mkQ)
            ((LinearMap.rTensor A' P.subtype) y) = 0
        have hzero : P.mkQ.comp P.subtype = 0 := by
          ext y
          simp
        have h := congrArg (fun f => f y)
          (LinearMap.rTensor_comp (M := A') P.mkQ P.subtype)
        rw [LinearMap.comp_apply, hzero] at h
        simpa using h.symm
      have hy0 : (LinearMap.rTensor Q P.mkQ) z = 0 := by
        have hmap := hx0
        rw [← hz] at hmap
        change (LinearMap.rTensor A' P.mkQ)
            ((LinearMap.lTensor A Q.subtype) z) = 0 at hmap
        have hmap' : (TensorProduct.map P.mkQ Q.subtype) z = 0 := by
          have h := congrArg (fun f => f z)
            (LinearMap.rTensor_comp_lTensor A P.mkQ Q.subtype)
          rw [LinearMap.comp_apply, hmap] at h
          exact h.symm
        have hcomp :
            (LinearMap.lTensor (A ⧸ P) Q.subtype)
                ((LinearMap.rTensor Q P.mkQ) z) = 0 := by
          have h := congrArg (fun f => f z)
            (LinearMap.lTensor_comp_rTensor A P.mkQ Q.subtype)
          rw [LinearMap.comp_apply, hmap'] at h
          exact h
        have hinj : Function.Injective (LinearMap.lTensor (A ⧸ P) Q.subtype) :=
          Module.Flat.lTensor_preserves_injective_linearMap (M := A ⧸ P)
            Q.subtype Q.subtype_injective
        apply hinj
        simpa using hcomp
      have hzrange : z ∈ LinearMap.range (LinearMap.rTensor Q P.subtype) := by
        rw [← rTensor_mkQ Q P]
        exact hy0
      obtain ⟨w, hw⟩ := hzrange
      refine ⟨w, ?_⟩
      calc
        (TensorProduct.map P.subtype Q.subtype) w =
            (LinearMap.lTensor A Q.subtype)
              ((LinearMap.rTensor (↥Q) P.subtype) w) := by
                have h := congrArg (fun f => f w)
                  (LinearMap.lTensor_comp_rTensor (↥P) P.subtype Q.subtype)
                exact h.symm
        _ = (LinearMap.lTensor A Q.subtype) z := by rw [hw]
        _ = x := hz
    · rintro x ⟨z, rfl⟩
      constructor
      · refine ⟨LinearMap.lTensor (↥P) Q.subtype z, ?_⟩
        exact congrArg (fun f => f z)
          (LinearMap.rTensor_comp_lTensor (↥P) P.subtype Q.subtype)
      · refine ⟨LinearMap.rTensor (↥Q) P.subtype z, ?_⟩
        exact congrArg (fun f => f z)
          (LinearMap.lTensor_comp_rTensor (↥P) P.subtype Q.subtype)
  rw [Algebra.TensorProduct.map_range, Subalgebra.centralizer_coe_sup,
    Subalgebra.range_comp_val, Subalgebra.range_comp_val,
    Subalgebra.centralizer_coe_map_includeLeft_eq_center_tensorProduct,
    Subalgebra.centralizer_coe_map_includeRight_eq_center_tensorProduct]
  apply Subalgebra.toSubmodule_injective
  exact h_inter
    (Subalgebra.centralizer k (B : Set A)).toSubmodule
    (Subalgebra.centralizer k (B' : Set A')).toSubmodule

theorem center_finite_simple_is_finite_field_extension (k A : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A] :
    IsField (Subalgebra.center k A) ∧
      FiniteDimensional k (Subalgebra.center k A) := by
  exact ⟨IsSimpleRing.isField_center A, inferInstance⟩

end Centralizers

section GeneratedSubspaces

private theorem exists_unit_pure_tensor_of_nonzero_two_sided
    (k : Type u_k) (V : Type u_V) (K : Type u_K) [Field k]
    [AddCommGroup V] [Module k V] [DivisionRing K] [Algebra k K]
    [Algebra.IsCentral k K] (W : Submodule k (V ⊗[k] K))
    (hW : TwoSidedKSubspace k V K W) (hW0 : W ≠ ⊥) :
    ∃ v : V, v ≠ 0 ∧ v ⊗ₜ[k] (1 : K) ∈ W := by
  classical
  let b := Module.Free.chooseBasis k V
  let E : V ⊗[k] K ≃ₗ[k]
      (Module.Free.ChooseBasisIndex k V →₀ K) :=
    TensorProduct.equivFinsuppOfBasisLeft b
  have hE_left (a : K) (z : V ⊗[k] K) :
      E (tensorLeftMultiply k V K a z) =
        (E z).mapRange (fun d => a * d) (by simp) := by
    apply Finsupp.ext
    intro i
    induction z using TensorProduct.induction_on with
    | zero => simp
    | tmul v d =>
        simp [E, tensorLeftMultiply]
    | add z₁ z₂ ih₁ ih₂ =>
        simp [ih₁, ih₂, mul_add]
  have hE_right (a : K) (z : V ⊗[k] K) :
      E (tensorRightMultiply k V K a z) =
        (E z).mapRange (fun d => d * a) (by simp) := by
    apply Finsupp.ext
    intro i
    induction z using TensorProduct.induction_on with
    | zero => simp
    | tmul v d =>
        simp [E, tensorRightMultiply]
    | add z₁ z₂ ih₁ ih₂ =>
        simp [ih₁, ih₂, add_mul]
  let P : ℕ → Prop := fun n =>
    ∃ x, x ∈ W ∧ x ≠ 0 ∧ (E x).support.card = n
  have hP : ∃ n, P n := by
    have hWmem : ∃ x, x ∈ W ∧ x ≠ 0 := by
      by_contra h
      apply hW0
      ext x
      constructor
      · intro hx
        by_contra hx0
        exact h ⟨x, hx, hx0⟩
      · intro hx
        have hx' : x = 0 := by simpa using hx
        simp [hx']
    obtain ⟨x, hxW, hx0⟩ := hWmem
    refine ⟨(E x).support.card, x, hxW, hx0, rfl⟩
  let n := Nat.find hP
  obtain ⟨x, hxW, hx0, hxcard⟩ := Nat.find_spec hP
  have hcx : E x ≠ 0 := by
    intro h
    apply hx0
    apply E.injective
    simpa using h
  obtain ⟨i, hi⟩ := Finsupp.support_nonempty_iff.mpr hcx
  have hic : E x i ≠ 0 := Finsupp.mem_support_iff.mp hi
  let a := (E x i)⁻¹
  let c := (E x).mapRange (fun d => a * d) (by simp)
  have hainj : Function.Injective (fun d : K => a * d) := by
    intro p q hpq
    exact mul_left_cancel₀ (inv_ne_zero hic) hpq
  have hcsupp : c.support = (E x).support := by
    exact Finsupp.support_mapRange_of_injective (by simp) _ hainj
  have hci : c i = 1 := by
    simp [c, a, hic]
  have hc0 : c ≠ 0 := by
    intro h
    have hi' := congrArg (fun f => f i) h
    simp [hci] at hi'
  let y := tensorLeftMultiply k V K a x
  have hcy : E y = c := by
    exact hE_left a x
  have hy0 : y ≠ 0 := by
    intro h
    apply hc0
    rw [← hcy, h]
    simp
  have hyW : y ∈ W := hW.1 a x hxW
  have hycard : (E y).support.card = n := by
    rw [hcy, hcsupp]
    exact hxcard
  have hiy : i ∈ (E y).support := by
    rw [hcy, hcsupp]
    exact hi
  have hcomm (d : K) :
      tensorLeftMultiply k V K d y =
        tensorRightMultiply k V K d y := by
    by_contra hne
    let z := tensorLeftMultiply k V K d y -
      tensorRightMultiply k V K d y
    have hzW : z ∈ W :=
      W.sub_mem (hW.1 d y hyW) (hW.2 d y hyW)
    have hEz :
        E z =
          (E y).mapRange (fun q => d * q) (by simp) -
            (E y).mapRange (fun q => q * d) (by simp) := by
      have hEz' := congrArg₂ (fun p q => p - q)
        (hE_left d y) (hE_right d y)
      simpa [z] using hEz'
    have hsubset : (E z).support ⊆ (E y).support.erase i := by
      intro j hj
      have hjbase : j ∈ (E y).support := by
        by_contra hjnot
        have hyj : E y j = 0 := Finsupp.notMem_support_iff.mp hjnot
        have hzj : E z j = 0 := by
          rw [hEz]
          simp [hyj]
        exact (Finsupp.mem_support_iff.mp hj) hzj
      have hji : j ≠ i := by
        intro hji
        subst j
        have hzj : E z i = 0 := by
          rw [hEz]
          simp [hcy, hci]
        exact (Finsupp.mem_support_iff.mp hj) hzj
      exact Finset.mem_erase.mpr ⟨hji, hjbase⟩
    have hcardle := Finset.card_le_card hsubset
    rw [Finset.card_erase_of_mem hiy] at hcardle
    have hpos : 0 < (E y).support.card := Finset.card_pos.mpr ⟨i, hiy⟩
    have hlt_y : (E z).support.card < (E y).support.card := by omega
    have hlt : (E z).support.card < n := by simpa [hycard] using hlt_y
    exact (Nat.find_min hP (by simpa [n] using hlt))
      ⟨z, hzW, sub_ne_zero.mpr hne, rfl⟩
  have hscalar (j : Module.Free.ChooseBasisIndex k V) :
      ∃ r : k, E y j = algebraMap k K r := by
    have hjcenter : E y j ∈ Subalgebra.center k K := by
      rw [Subalgebra.mem_center_iff]
      intro d
      have hh := congrArg (fun q => E q j) (hcomm d)
      rw [hE_left, hE_right] at hh
      simpa using hh
    exact (Algebra.IsCentral.mem_center_iff (K := k) (D := K)).mp hjcenter
  choose r hr using hscalar
  let d : Module.Free.ChooseBasisIndex k V →₀ k :=
    Finsupp.onFinset (E y).support r (by
      intro j hj
      apply Finsupp.mem_support_iff.mpr
      intro hyj
      apply hj
      apply FaithfulSMul.algebraMap_injective k K
      rw [← hr j, hyj]
      simp)
  have hdr (j : Module.Free.ChooseBasisIndex k V) :
      algebraMap k K (d j) = E y j := by
    by_cases hj : j ∈ (E y).support
    · simpa [d, hj] using (hr j).symm
    · have hyj : E y j = 0 := Finsupp.notMem_support_iff.mp hj
      have hr0 : r j = 0 := by
        apply FaithfulSMul.algebraMap_injective k K
        rw [← hr j, hyj]
        simp
      simp [d, hr0, hyj]
  let v : V := b.repr.symm d
  have hvy : v ⊗ₜ[k] (1 : K) = y := by
    apply E.injective
    apply Finsupp.ext
    intro j
    simpa [E, v, Algebra.smul_def] using hdr j
  have hv0 : v ≠ 0 := by
    intro hv
    apply hy0
    rw [← hvy, hv]
    simp
  exact ⟨v, hv0, hvy ▸ hyW⟩

theorem two_sided_subspace_generated (k V K : Type*) [Field k]
    [AddCommGroup V] [Module k V] [DivisionRing K] [Algebra k K]
    [Algebra.IsCentral k K] (W : Submodule k (V ⊗[k] K))
    (hW : TwoSidedKSubspace k V K W) :
    W = leftKSpan k V K
      {z | ∃ v : V, z = v ⊗ₜ[k] (1 : K) ∧ z ∈ W} := by
  classical
  let tmulOne : V →ₗ[k] V ⊗[k] K := (TensorProduct.mk k V K).flip 1
  let U : Submodule k V := W.comap tmulOne
  let Q : Submodule k (V ⊗[k] K) :=
    LinearMap.range (TensorProduct.map U.subtype (LinearMap.id : K →ₗ[k] K))
  let R : Submodule k (V ⊗[k] K) := leftKSpan k V K
    {z | ∃ v : V, z = v ⊗ₜ[k] (1 : K) ∧ z ∈ W}
  have hQR : Q ≤ R := by
    rintro z ⟨y, rfl⟩
    induction y using TensorProduct.induction_on with
    | zero => exact R.zero_mem
    | tmul u c =>
        apply Submodule.subset_span
        refine ⟨c, (u : V) ⊗ₜ[k] (1 : K), ?_, ?_⟩
        · refine ⟨u, rfl, ?_⟩
          exact u.property
        · simp [tensorLeftMultiply]
    | add y₁ y₂ ih₁ ih₂ => simpa using R.add_mem ih₁ ih₂
  let e : (V ⧸ U) ⊗[k] K ≃ₗ[k] (V ⊗[k] K) ⧸ Q :=
    TensorProduct.quotientTensorEquiv K U
  have e_left (c : K) (x : V ⊗[k] K) :
      e (tensorLeftMultiply k (V ⧸ U) K c (e.symm (Q.mkQ x))) =
        Q.mkQ (tensorLeftMultiply k V K c x) := by
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul v d =>
        simp [e, Q, tensorLeftMultiply,
          TensorProduct.quotientTensorEquiv_symm_apply_mk_tmul]
    | add x y ihx ihy =>
        simp only [e.symm.map_add, map_add]
        rw [ihx, ihy]
  have e_right (c : K) (x : V ⊗[k] K) :
      e (tensorRightMultiply k (V ⧸ U) K c (e.symm (Q.mkQ x))) =
        Q.mkQ (tensorRightMultiply k V K c x) := by
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul v d =>
        simp [e, Q, tensorRightMultiply,
          TensorProduct.quotientTensorEquiv_symm_apply_mk_tmul]
    | add x y ihx ihy =>
        simp only [e.symm.map_add, map_add]
        rw [ihx, ihy]
  let Wq0 : Submodule k ((V ⊗[k] K) ⧸ Q) := Submodule.map Q.mkQ W
  let Wq : Submodule k ((V ⧸ U) ⊗[k] K) := Wq0.comap e.toLinearMap
  have hWq : TwoSidedKSubspace k (V ⧸ U) K Wq := by
    constructor
    · intro c z hz
      change e z ∈ Wq0 at hz
      change e (tensorLeftMultiply k (V ⧸ U) K c z) ∈ Wq0
      rcases Submodule.mem_map.mp hz with ⟨x, hx, hxeq⟩
      refine ⟨tensorLeftMultiply k V K c x, hW.1 c x hx, ?_⟩
      have hz' : z = e.symm (Q.mkQ x) := by
        apply e.injective
        simpa using hxeq.symm
      rw [hz']
      exact (e_left c x).symm
    · intro c z hz
      change e z ∈ Wq0 at hz
      change e (tensorRightMultiply k (V ⧸ U) K c z) ∈ Wq0
      rcases Submodule.mem_map.mp hz with ⟨x, hx, hxeq⟩
      refine ⟨tensorRightMultiply k V K c x, hW.2 c x hx, ?_⟩
      have hz' : z = e.symm (Q.mkQ x) := by
        apply e.injective
        simpa using hxeq.symm
      rw [hz']
      exact (e_right c x).symm
  have hRW : R ≤ W := by
    unfold R leftKSpan
    intro z hz
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hz
    · rintro z ⟨c, x, hx, rfl⟩
      obtain ⟨v, rfl, hv⟩ := hx
      exact hW.1 c _ hv
    · exact W.zero_mem
    · intro x y hx hy hpx hpy
      exact W.add_mem hpx hpy
    · intro a x hx hpx
      exact W.smul_mem a hpx
  have hQW : Q ≤ W := hQR.trans hRW
  have hWleQ : W ≤ Q := by
    by_contra hnot
    have hWqne : Wq ≠ ⊥ := by
      intro hbot
      apply hnot
      intro x hx
      have hz : e.symm (Q.mkQ x) ∈ Wq := by
        change e (e.symm (Q.mkQ x)) ∈ Wq0
        have hm : Q.mkQ x ∈
            Submodule.map
              (Q.mkQ : (V ⊗[k] K) →ₗ[k] (V ⊗[k] K) ⧸ Q) W :=
          Submodule.mem_map_of_mem hx
        simpa [Wq0] using hm
      rw [hbot] at hz
      have hz0 : e.symm (Q.mkQ x) = 0 := by simpa using hz
      have hq0 : Q.mkQ x = 0 := by
        calc
          Q.mkQ x = e (e.symm (Q.mkQ x)) := (e.apply_symm_apply _).symm
          _ = e 0 := by rw [hz0]
          _ = 0 := e.map_zero
      exact (Submodule.Quotient.mk_eq_zero Q).mp hq0
    obtain ⟨v, hv0, hvWq⟩ :=
      exists_unit_pure_tensor_of_nonzero_two_sided k (V ⧸ U) K Wq hWq hWqne
    obtain ⟨w, hwv⟩ := Submodule.mkQ_surjective U v
    change e (v ⊗ₜ[k] (1 : K)) ∈ Wq0 at hvWq
    rcases Submodule.mem_map.mp hvWq with ⟨x, hx, hxeq⟩
    have hepure : e (v ⊗ₜ[k] (1 : K)) = Q.mkQ (w ⊗ₜ[k] (1 : K)) := by
      rw [← hwv]
      simp [e, Q]
    have hqeq : Q.mkQ x = Q.mkQ (w ⊗ₜ[k] (1 : K)) := hxeq.trans hepure
    have hdiffQ : x - w ⊗ₜ[k] (1 : K) ∈ Q := by
      apply (Submodule.Quotient.mk_eq_zero Q).mp
      change Q.mkQ (x - w ⊗ₜ[k] (1 : K)) = 0
      rw [map_sub, hqeq, sub_self]
    have hdiffW : x - w ⊗ₜ[k] (1 : K) ∈ W := hQW hdiffQ
    have hpureW : w ⊗ₜ[k] (1 : K) ∈ W := by
      have h := W.sub_mem hx hdiffW
      simpa [sub_sub_cancel] using h
    have hwU : w ∈ U := by
      change tmulOne w ∈ W
      simpa [tmulOne] using hpureW
    apply hv0
    rw [← hwv]
    exact (Submodule.Quotient.mk_eq_zero U).mpr hwU
  change W = R
  exact le_antisymm (hWleQ.trans hQR) hRW

theorem two_sided_ideal_tensor (k A K : Type*) [Field k] [Ring A]
    [Algebra k A] [DivisionRing K] [Algebra k K] [Algebra.IsCentral k K] :
    ∀ I : TwoSidedIdeal (A ⊗[k] K),
      ∃ J : TwoSidedIdeal A, I = tensorTwoSidedIdeal k A K J := by
  intro I
  let iL : A →+* A ⊗[k] K :=
    Algebra.TensorProduct.includeLeftRingHom (R := k) (A := A) (B := K)
  let J : TwoSidedIdeal A := I.comap iL
  let T : TwoSidedIdeal (A ⊗[k] K) := tensorTwoSidedIdeal k A K J
  let W : Submodule k (A ⊗[k] K) :=
    { carrier := I
      zero_mem' := I.zero_mem
      add_mem' := I.add_mem
      smul_mem' := by
        intro r x hx
        rw [Algebra.smul_def]
        exact I.mul_mem_left _ _ hx }
  have hleft (c : K) (x : A ⊗[k] K) :
      tensorLeftMultiply k A K c x =
        (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := K) c) * x := by
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul a d => simp [tensorLeftMultiply]
    | add x y ihx ihy =>
        rw [map_add, ihx, ihy, mul_add]
  have hright (c : K) (x : A ⊗[k] K) :
      tensorRightMultiply k A K c x =
        x * (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := K) c) := by
    induction x using TensorProduct.induction_on with
    | zero => simp
    | tmul a d => simp [tensorRightMultiply]
    | add x y ihx ihy =>
        rw [map_add, ihx, ihy, add_mul]
  have hW : TwoSidedKSubspace k A K W := by
    constructor
    · intro c x hx
      change tensorLeftMultiply k A K c x ∈ I
      rw [hleft]
      exact I.mul_mem_left _ _ hx
    · intro c x hx
      change tensorRightMultiply k A K c x ∈ I
      rw [hright]
      exact I.mul_mem_right _ _ hx
  have hgen := two_sided_subspace_generated k A K W hW
  refine ⟨J, ?_⟩
  apply le_antisymm
  · intro x hx
    have hx' : x ∈ leftKSpan k A K
        {z | ∃ v : A, z = v ⊗ₜ[k] (1 : K) ∧ z ∈ W} := by
      rw [← hgen]
      exact hx
    unfold leftKSpan at hx'
    refine Submodule.span_induction ?_ ?_ ?_ ?_ hx'
    · rintro z ⟨c, y, hy, rfl⟩
      obtain ⟨a, rfl, ha⟩ := hy
      apply TwoSidedIdeal.subset_span
      refine ⟨a, ?_, c, ?_⟩
      · simpa [J, TwoSidedIdeal.mem_comap, iL, W] using ha
      · simp [tensorLeftMultiply]
    · exact T.zero_mem
    · intro x y hx hy htx hty
      exact T.add_mem htx hty
    · intro r x hx htx
      rw [Algebra.smul_def]
      exact T.mul_mem_left _ _ htx
  · apply TwoSidedIdeal.span_le.mpr
    rintro z ⟨a, ha, c, rfl⟩
    have haI : a ⊗ₜ[k] (1 : K) ∈ I := by
      have ha' : iL a ∈ I := by
        simpa [J, TwoSidedIdeal.mem_comap] using ha
      simpa [iL] using ha'
    have hmul : (a ⊗ₜ[k] (1 : K)) *
        (Algebra.TensorProduct.includeRight (R := k) (A := A) (B := K) c) ∈ I :=
      I.mul_mem_right _ _ haI
    simpa using hmul

theorem tensor_product_simple_of_simple (k A K : Type*) [Field k] [Ring A]
    [Algebra k A] [IsSimpleRing A] [DivisionRing K] [Algebra k K]
    [Algebra.IsCentral k K] : IsSimpleRing (A ⊗[k] K) := by
  let _ : Nontrivial (A ⊗[k] K) :=
    Algebra.TensorProduct.nontrivial_of_algebraMap_injective_of_flat_left k A K
      (FaithfulSMul.algebraMap_injective k K)
  refine IsSimpleRing.of_eq_bot_or_eq_top ?_
  intro I
  obtain ⟨J, hJ⟩ := two_sided_ideal_tensor k A K I
  rw [hJ]
  rcases eq_bot_or_eq_top J with hJbot | hJtop
  · left
    apply le_antisymm
    · apply TwoSidedIdeal.span_le.mpr
      rintro z ⟨a, ha, c, rfl⟩
      have ha0 : a = 0 := by simpa [hJbot] using ha
      subst a
      simp
    · exact bot_le
  · right
    apply le_antisymm le_top
    intro x hx
    induction x using TensorProduct.induction_on with
    | zero => exact (tensorTwoSidedIdeal k A K J).zero_mem
    | tmul a c =>
        apply TwoSidedIdeal.subset_span
        exact ⟨a, by simp [hJtop], c, rfl⟩
    | add x y ihx ihy =>
        exact (tensorTwoSidedIdeal k A K J).add_mem (ihx trivial) (ihy trivial)

theorem tensor_product_simple_of_simple_algebras (k A A' : Type*) [Field k]
    [Ring A] [Algebra k A] [IsSimpleRing A]
    [Ring A'] [Algebra k A'] [IsSimpleRing A']
    [FiniteDimensional k A'] [Algebra.IsCentral k A'] :
    IsSimpleRing (A ⊗[k] A') := by
  obtain ⟨n, hn, D, hD, hDalg, hDfinite, ⟨e⟩⟩ :=
    wedderburn_artin_finite k A'
  let _ : NeZero n := hn
  let _ : Nonempty (Fin n) := ⟨⟨0, Nat.pos_of_ne_zero hn.out⟩⟩
  let _ : Algebra.IsCentral k D :=
    { out := by
        intro x hx
        have hxcomm : ∀ y : D, Commute x y := by
          intro y
          exact (Subalgebra.mem_center_iff.mp hx y).symm
        have hxmat : Matrix.scalar (Fin n) x ∈ Set.center
            (Matrix (Fin n) (Fin n) D) := by
          rw [Semigroup.mem_center_iff]
          intro M
          exact (Matrix.scalar_commute x hxcomm M).eq.symm
        obtain ⟨a, ha⟩ := e.surjective (Matrix.scalar (Fin n) x)
        have hacenter : a ∈ Subalgebra.center k A' := by
          rw [Subalgebra.mem_center_iff]
          intro b
          have h := (Semigroup.mem_center_iff.mp hxmat) (e b)
          have h' := congrArg e.symm h
          rw [← ha] at h'
          simpa using h'
        obtain ⟨r, hr⟩ := Algebra.mem_bot.mp (‹Algebra.IsCentral k A'›.out hacenter)
        apply Algebra.mem_bot.mpr
        refine ⟨r, ?_⟩
        apply (Matrix.scalar_inj (n := Fin n)).mp
        calc
          Matrix.scalar (Fin n) (algebraMap k D r) =
              algebraMap k (Matrix (Fin n) (Fin n) D) r := by rfl
          _ = e (algebraMap k A' r) := by simp
          _ = e a := by rw [hr]
          _ = Matrix.scalar (Fin n) x := ha }
  let _ : IsSimpleRing (A ⊗[k] D) :=
    tensor_product_simple_of_simple k A D
  let f : A ⊗[k] A' →ₐ[k] A ⊗[k] Matrix (Fin n) (Fin n) D :=
    Algebra.TensorProduct.map (AlgHom.id k A) e.toAlgHom
  let fe : A ⊗[k] A' ≃ₐ[k] A ⊗[k] Matrix (Fin n) (Fin n) D :=
    AlgEquiv.ofBijective f
      (Algebra.TensorProduct.map_bijective Function.bijective_id e.bijective)
  let me : A ⊗[k] Matrix (Fin n) (Fin n) D ≃ₐ[k]
      Matrix (Fin n) (Fin n) (A ⊗[k] D) :=
    (Algebra.TensorProduct.congr (AlgEquiv.refl : A ≃ₐ[k] A)
        (matrixEquivTensor (Fin n) k D)).trans
      ((Algebra.TensorProduct.assoc k k k A D
          (Matrix (Fin n) (Fin n) k)).symm.trans
        (matrixEquivTensor (Fin n) k (A ⊗[k] D)).symm)
  exact IsSimpleRing.of_ringEquiv (fe.trans me).symm.toRingEquiv inferInstance

theorem tensor_product_simple_of_simple_algebras_left (k A A' : Type*)
    [Field k] [Ring A] [Algebra k A] [IsSimpleRing A]
    [FiniteDimensional k A] [Algebra.IsCentral k A]
    [Ring A'] [Algebra k A'] [IsSimpleRing A'] :
    IsSimpleRing (A ⊗[k] A') := by
  let _ : IsSimpleRing (A' ⊗[k] A) :=
    tensor_product_simple_of_simple_algebras k A' A
  exact IsSimpleRing.of_ringEquiv
    (Algebra.TensorProduct.comm k A A').symm.toRingEquiv inferInstance

end GeneratedSubspaces

section MatrixAlgebras

def matrix_module_category_equivalence (R : Type*) (n : ℕ) [Ring R]
    (i : Fin n) :
    ModuleCat R ≌ ModuleCat (Matrix (Fin n) (Fin n) R) := by
  classical
  exact ModuleCat.matrixEquivalence R i

def matrix_two_sided_ideal_order_iso (R : Type*) (n : ℕ) [Ring R]
    [NeZero n] :
    TwoSidedIdeal R ≃o TwoSidedIdeal (Matrix (Fin n) (Fin n) R) := by
  classical
  exact TwoSidedIdeal.orderIsoMatrix (R := R) (n := Fin n)

theorem matrix_center_eq_scalar_image (R : Type*) (n : ℕ) [Semiring R]
    : Set.center (Matrix (Fin n) (Fin n) R) =
      Matrix.scalar (Fin n) '' Set.center R := by
  exact Matrix.center_eq_scalar_image

theorem matrix_standard_module_is_simple (K : Type*) (n : ℕ) [DivisionRing K]
    [NeZero n] :
    IsSimpleModule (Matrix (Fin n) (Fin n) K) (Fin n → K) := by
  classical
  rw [isSimpleModule_iff_toSpanSingleton_surjective]
  refine ⟨by infer_instance, ?_⟩
  intro v hv w
  obtain ⟨j, hj⟩ : ∃ j, v j ≠ 0 := by
    by_contra h
    apply hv
    funext i
    by_contra hi
    exact h ⟨i, hi⟩
  refine ⟨Matrix.vecMulVec w (Pi.single j (v j)⁻¹), ?_⟩
  change Matrix.mulVec (Matrix.vecMulVec w (Pi.single j (v j)⁻¹)) v = w
  rw [Matrix.vecMulVec_mulVec]
  simp [hj]

theorem matrix_standard_module_end (K : Type*) (n : ℕ) [DivisionRing K]
    [NeZero n] :
    Nonempty
      (Module.End (Matrix (Fin n) (Fin n) K) (Fin n → K) ≃+* Kᵐᵒᵖ) := by
  classical
  let e := ModuleCat.matrixEquivalence K (i := Classical.arbitrary (Fin n))
  let f : Module.End K K →+* Module.End (Matrix (Fin n) (Fin n) K) (Fin n → K) :=
    { toFun := fun x => (e.functor.map (ModuleCat.ofHom x)).hom
      map_zero' := by
        ext
        rfl
      map_add' := by
        intro x y
        ext v
        rfl
      map_one' := by
        rfl
      map_mul' := by
        intro x y
        rfl }
  let ef : Module.End K K ≃+* Module.End (Matrix (Fin n) (Fin n) K) (Fin n → K) :=
    RingEquiv.ofBijective f (by
      constructor
      · intro x y h
        have h' : e.functor.map (ModuleCat.ofHom x) =
            e.functor.map (ModuleCat.ofHom y) := by
          apply ModuleCat.hom_ext
          exact h
        have hxy := e.functor.map_injective h'
        exact congrArg ModuleCat.Hom.hom hxy
      · intro y
        obtain ⟨x, hx⟩ := e.functor.map_surjective
          (ModuleCat.ofHom (X := e.functor.obj (ModuleCat.of K K))
            (Y := e.functor.obj (ModuleCat.of K K)) y)
        refine ⟨x.hom, ?_⟩
        have hx' : x = ModuleCat.ofHom x.hom := by
          apply ModuleCat.hom_ext
          rfl
        rw [hx'] at hx
        have hxy := congrArg ModuleCat.Hom.hom hx
        change (e.functor.map (ModuleCat.ofHom x.hom)).hom = y at hxy
        exact hxy)
  exact ⟨ef.symm.trans (RingEquiv.moduleEndSelf K).symm⟩

end MatrixAlgebras

section SimpleModules

theorem finite_simple_algebra_unique_simple_modules (k A M N : Type*)
    [Field k] [Ring A] [Algebra k A] [FiniteDimensional k A]
    [IsSimpleRing A] [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [AddCommGroup N] [Module A N] [IsSimpleModule A N] :
    Nonempty (M ≃ₗ[A] N) := by
  classical
  let : IsArtinianRing A := IsArtinianRing.of_finite k A
  obtain ⟨I, ⟨eM⟩⟩ :=
    IsSemisimpleRing.exists_linearEquiv_ideal_of_isSimpleModule A M
  obtain ⟨J, ⟨eN⟩⟩ :=
    IsSemisimpleRing.exists_linearEquiv_ideal_of_isSimpleModule A N
  let : IsSimpleModule A I := IsSimpleModule.congr eM.symm
  let : IsSimpleModule A J := IsSimpleModule.congr eN.symm
  have h := IsSimpleRing.isIsotypic A A
  exact ⟨eM.trans (h I J).some.symm |>.trans eN.symm⟩

theorem finite_simple_algebra_module_isotypic (k A M : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [Module k M] [IsScalarTower k A M]
    [Module.Finite A M] :
    IsSemisimpleModule A M ∧ IsIsotypic A M := by
  let : IsArtinianRing A := IsArtinianRing.of_finite k A
  exact ⟨inferInstance, IsSimpleRing.isIsotypic A M⟩

theorem finite_module_is_direct_sum_of_simple (k A M S : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [Module.Finite A M]
    [AddCommGroup S] [Module A S]
    [IsSimpleModule A S] :
    ∃ n : ℕ, Nonempty (M ≃ₗ[A] (Fin n → S)) := by
  classical
  let : IsArtinianRing A := IsArtinianRing.of_finite k A
  by_cases hM : Nontrivial M
  · let : Nontrivial M := hM
    have h := IsSimpleRing.isIsotypic A M
    obtain ⟨n, hn, T, hT, ⟨e⟩⟩ := h.linearEquiv_fun
    let : IsSimpleModule A T := hT
    obtain ⟨eTS⟩ := finite_simple_algebra_unique_simple_modules k A T S
    exact ⟨n, ⟨e.trans (LinearEquiv.piCongrRight fun _ => eTS)⟩⟩
  · let : Subsingleton M := not_nontrivial_iff_subsingleton.mp hM
    refine ⟨0, ⟨LinearEquiv.ofBijective (0 : M →ₗ[A] (Fin 0 → S)) ?_⟩⟩
    exact ⟨fun x y _ => Subsingleton.elim _ _, fun y => ⟨0, Subsingleton.elim _ _⟩⟩

theorem finite_simple_algebra_modules_classified_by_dimension
    (k A M N : Type*) [Field k] [Ring A] [Algebra k A]
    [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [Module k M] [IsScalarTower k A M]
    [Module.Finite A M] [AddCommGroup N] [Module A N] [Module k N]
    [IsScalarTower k A N] [Module.Finite A N] :
    Nonempty (M ≃ₗ[A] N) ↔ Module.finrank k M = Module.finrank k N := by
  classical
  let : Module.Finite k M := Module.Finite.trans A M
  let : Module.Finite k N := Module.Finite.trans A N
  obtain ⟨S, hS⟩ := finite_algebra_has_simple_submodule k A
  let : IsSimpleModule A S := hS
  let : Nontrivial S := IsSimpleModule.nontrivial A S
  obtain ⟨s, hs⟩ := exists_ne (0 : S)
  let : Module.Finite A S :=
    Module.Finite.of_surjective (LinearMap.toSpanSingleton A S s)
      (IsSimpleModule.toSpanSingleton_surjective A hs)
  let : Module.Finite k S := Module.Finite.trans A S
  constructor
  · rintro ⟨e⟩
    exact (e.restrictScalars k).finrank_eq
  · intro h
    obtain ⟨m, ⟨eM⟩⟩ := finite_module_is_direct_sum_of_simple k A M S
    obtain ⟨n, ⟨eN⟩⟩ := finite_module_is_direct_sum_of_simple k A N S
    have hM : Module.finrank k M = m * Module.finrank k S := by
      calc
        Module.finrank k M = Module.finrank k (Fin m → S) :=
          (eM.restrictScalars k).finrank_eq
        _ = m * Module.finrank k S := by simp [Module.finrank_pi_fintype]
    have hN : Module.finrank k N = n * Module.finrank k S := by
      calc
        Module.finrank k N = Module.finrank k (Fin n → S) :=
          (eN.restrictScalars k).finrank_eq
        _ = n * Module.finrank k S := by simp [Module.finrank_pi_fintype]
    have h' : m * Module.finrank k S = n * Module.finrank k S := by omega
    have hmn : m = n :=
      (Nat.mul_right_cancel (Module.finrank_pos (R := k) (M := S))) h'
    subst n
    exact ⟨eM.trans eN.symm⟩

theorem simple_module_double_commutant (k A M : Type*) [Field k] [Ring A]
    [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [Module k M] [IsScalarTower k A M] :
    Nonempty (A ≃ₐ[k] Module.End (Module.End A M) M) := by
  classical
  let : Nontrivial M := IsSimpleModule.nontrivial A M
  let : Module.Finite k M := simple_module_over_finite_algebra_is_finite_dimensional k A M
  let : Module.Finite (Module.End A M) M :=
    Module.Finite.of_restrictScalars_finite k (Module.End A M) M
  have hAnn : Module.annihilator A M = ⊥ := by
    have h := (isSimpleRing_iff_isTwoSided_imp.mp (inferInstance : IsSimpleRing A)).2
      (Module.annihilator A M) inferInstance
    exact h.resolve_right (by
      intro htop
      exact (not_subsingleton M) (Module.annihilator_eq_top_iff.mp htop))
  let : FaithfulSMul A M := Module.annihilator_eq_bot.mp hAnn
  let f : A →ₐ[k] Module.End (Module.End A M) M :=
    { toRingHom := Module.toModuleEnd (Module.End A M) (S := A) M
      commutes' := by
        intro r
        ext x
        change (algebraMap k A r) • x = r • x
        exact IsScalarTower.algebraMap_smul A r x }
  have hbij : Function.Bijective f := by
    constructor
    · exact (Module.toModuleEnd (Module.End A M) (S := A) M).injective
    · exact Module.Finite.toModuleEnd_moduleEnd_surjective
  exact ⟨AlgEquiv.ofBijective f hbij⟩

theorem simple_module_center_and_dimension (k A M : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [Module k M] [IsScalarTower k A M] :
    Nonempty (Subalgebra.center k A ≃ₐ[k] Subalgebra.center k (Module.End A M)) ∧
      FiniteDimensional k (Module.End A M) ∧
      Module.finrank k A * Module.finrank k (Module.End A M) =
        Module.finrank k M ^ 2 := by
  classical
  let : Nontrivial M := IsSimpleModule.nontrivial A M
  let : Module.Finite k M :=
    simple_module_over_finite_algebra_is_finite_dimensional k A M
  let : Module (Module.End A M) M :=
    { smul := fun f m => f m
      smul_zero := by intro f; exact f.map_zero
      smul_add := by intro f x y; exact f.map_add x y
      one_smul := by intro m; rfl
      mul_smul := by intro f g m; rfl
      zero_smul := by intro m; rfl
      add_smul := by intro f g m; rfl }
  let : IsArtinianRing (Module.End A M) := inferInstance
  let : Module.Finite (Module.End A M) M :=
    Module.Finite.of_restrictScalars_finite k (Module.End A M) M
  let : Module.Free (Module.End A M) M :=
    Module.Free.of_divisionRing (Module.End A M) M
  let : ∀ n : ℕ, IsArtinian (Module.End A M) (Fin n → Module.End A M) := by
    intro n
    apply ((IsArtinianRing.tfae (Module.End A M) (Fin n → Module.End A M)).out 0 2).mp
    infer_instance
  let : StrongRankCondition (Module.End A M) :=
    StrongRankCondition.of_isArtinian (Module.End A M)
  let f : Module.End A M →ₗ[k] Module.End k M :=
    { toFun := fun d => d.restrictScalars k
      map_add' := by
        intro x y
        ext m
        rfl
      map_smul' := by
        intro r d
        ext m
        rfl }
  let : FiniteDimensional k (Module.End A M) :=
    FiniteDimensional.of_injective f (by
      intro x y h
      exact LinearMap.restrictScalars_injective k h)
  let e : A ≃ₐ[k] Module.End (Module.End A M) M :=
    Classical.choice (simple_module_double_commutant k A M)
  let φ : Subalgebra.center k (Module.End A M) →ₐ[k]
      Subalgebra.center k (Module.End (Module.End A M) M) :=
    { toFun := fun c =>
        ⟨Module.End.smulLeft (c : Module.End A M) c.property, by
          rw [Subalgebra.mem_center_iff]
          intro g
          ext m
          change g ((c : Module.End A M) • m) =
            (c : Module.End A M) • g m
          exact g.map_smul (c : Module.End A M) m⟩
      map_one' := by
        apply Subtype.ext
        ext m
        simp [Module.End.smulLeft]
      map_mul' := by
        intro c d
        apply Subtype.ext
        ext m
        simp [Module.End.smulLeft, Module.End.mul_eq_comp]
      map_zero' := by
        apply Subtype.ext
        ext m
        simp [Module.End.smulLeft]
      map_add' := by
        intro c d
        apply Subtype.ext
        ext m
        simp [Module.End.smulLeft]
      commutes' := by
        intro r
        apply Subtype.ext
        ext m
        simp [Module.End.smulLeft] }
  let ψ : Subalgebra.center k A →ₐ[k]
      Subalgebra.center k (Module.End (Module.End A M) M) :=
    { toFun := fun a =>
        ⟨e (a : A), by
          rw [Subalgebra.mem_center_iff]
          intro g
          obtain ⟨b, rfl⟩ := e.surjective g
          have h := (Subalgebra.mem_center_iff.mp a.property) b
          simpa using congrArg e h⟩
      map_one' := by
        apply Subtype.ext
        simp
      map_mul' := by
        intro a b
        apply Subtype.ext
        simp
      map_zero' := by
        apply Subtype.ext
        simp
      map_add' := by
        intro a b
        apply Subtype.ext
        simp
      commutes' := by
        intro r
        apply Subtype.ext
        exact e.commutes r }
  have hφ : Function.Bijective φ := by
    constructor
    · intro c d h
      apply Subtype.ext
      have hcd : (c : Module.End A M) = (d : Module.End A M) :=
        FaithfulSMul.eq_of_smul_eq_smul (M := Module.End A M) (α := M) (by
          intro m
          have hm := congrArg (fun g : Module.End (Module.End A M) M => g m)
            (congrArg Subtype.val h)
          simpa [φ, Module.End.smulLeft] using hm)
      exact hcd
    · intro z
      obtain ⟨a, ha, hza⟩ :=
        (Module.End.mem_subalgebraCenter_iff (R := Module.End A M) (S := k)
          (M := M)).mp z.property
      let c : Subalgebra.center k (Module.End A M) := ⟨a, ha⟩
      refine ⟨c, ?_⟩
      apply Subtype.ext
      simpa [φ, c] using hza.symm
  have hψ : Function.Bijective ψ := by
    constructor
    · intro a b h
      apply Subtype.ext
      have h' : e (a : A) = e (b : A) := by
        simpa [ψ] using congrArg Subtype.val h
      exact e.injective h'
    · intro z
      have hpre : e.symm (z : Module.End (Module.End A M) M) ∈
          Subalgebra.center k A := by
        rw [Subalgebra.mem_center_iff]
        intro b
        obtain ⟨bE, hbE⟩ := e.symm.surjective b
        have hz := (Subalgebra.mem_center_iff.mp z.property) bE
        have hz' := congrArg e.symm hz
        simpa [hbE] using hz'
      let a : Subalgebra.center k A :=
        ⟨e.symm (z : Module.End (Module.End A M) M), hpre⟩
      refine ⟨a, ?_⟩
      apply Subtype.ext
      change e (e.symm (z : Module.End (Module.End A M) M)) =
        (z : Module.End (Module.End A M) M)
      exact e.apply_symm_apply _
  let φe := AlgEquiv.ofBijective φ hφ
  let ψe := AlgEquiv.ofBijective ψ hψ
  have heq : Module.finrank k A =
      Module.finrank k (Module.End (Module.End A M) M) :=
    e.toLinearEquiv.finrank_eq
  have hdim : Module.finrank k (Module.End (Module.End A M) M) =
      Module.finrank (Module.End A M) M * Module.finrank k M := by
    rw [Module.finrank_linearMap]
  have htower : Module.finrank k (Module.End A M) *
      Module.finrank (Module.End A M) M = Module.finrank k M :=
    Module.finrank_mul_finrank k (Module.End A M) M
  refine ⟨⟨ψe.trans φe.symm⟩, inferInstance, ?_⟩
  calc
    Module.finrank k A * Module.finrank k (Module.End A M) =
        Module.finrank k (Module.End (Module.End A M) M) *
          Module.finrank k (Module.End A M) := by rw [heq]
    _ = (Module.finrank (Module.End A M) M * Module.finrank k M) *
          Module.finrank k (Module.End A M) := by rw [hdim]
    _ = Module.finrank k M *
          (Module.finrank k (Module.End A M) *
            Module.finrank (Module.End A M) M) := by ring
    _ = Module.finrank k M ^ 2 := by rw [htower]; ring

theorem simple_module_end_is_finite (k A M : Type*) [Field k] [Ring A]
    [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [Module k M] [IsScalarTower k A M] :
    Nonempty (DivisionRing (Module.End A M)) ∧
      FiniteDimensional k (Module.End A M) := by
  classical
  constructor
  · exact ⟨inferInstance⟩
  · let : FiniteDimensional k M :=
      simple_module_over_finite_algebra_is_finite_dimensional k A M
    infer_instance

theorem finite_module_end_is_matrix_and_double_commutant
    (k : Type u_k) (A : Type u_A) (N : Type u_N) [Field k] [Ring A] [Algebra k A]
    [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup N] [Nontrivial N] [Module A N] [Module k N] [IsScalarTower k A N]
    [Module.Finite A N] :
    ∃ (n : ℕ) (_ : NeZero n) (L : Type (max u_A u_N)) (_ : DivisionRing L)
      (_ : Algebra k L)
      (_ : FiniteDimensional k L),
      Nonempty (Module.End A N ≃ₐ[k] Matrix (Fin n) (Fin n) L) ∧
        Nonempty (Module.End (Module.End A N) N ≃ₐ[k] A) := by
  classical
  obtain ⟨S, hS⟩ := finite_algebra_nonzero_module_has_simple_submodule k A N
  let _ : IsSimpleModule A S := hS
  obtain ⟨n, ⟨e⟩⟩ := finite_module_is_direct_sum_of_simple k A N S
  have hn0 : n ≠ 0 := by
    intro hn
    subst n
    have hnontriv : Nontrivial (Fin 0 → S) :=
      e.injective.nontrivial
    exact (not_nontrivial (Fin 0 → S)) hnontriv
  let _ : NeZero n := ⟨hn0⟩
  let L0 := Module.End A S
  let _ : DivisionRing L0 := inferInstance
  let _ : Algebra k L0 := inferInstance
  let _ : FiniteDimensional k L0 := (simple_module_end_is_finite k A S).2
  let L : Type (max u_A u_N) := ULift.{u_A} L0
  let _ : DivisionRing L := inferInstance
  let _ : Algebra k L := inferInstance
  let _ : Module.Finite k L :=
    Module.Finite.equiv (ULift.moduleEquiv (R := k) (M := L0)).symm
  have hEnd : Nonempty (Module.End A N ≃ₐ[k] Matrix (Fin n) (Fin n) L) := by
    exact ⟨(e.conjAlgEquiv k).trans
      ((endVecAlgEquivMatrixEnd (R := k) (A := A) (ι := Fin n) (M := S)).trans
        (ULift.algEquiv (R := k)).symm.mapMatrix)⟩
  let : Module (Module.End A N) N :=
    { smul := fun f m => f m
      smul_zero := by intro f; exact f.map_zero
      smul_add := by intro f x y; exact f.map_add x y
      one_smul := by intro m; rfl
      mul_smul := by intro f g m; rfl
      zero_smul := by intro m; rfl
      add_smul := by intro f g m; rfl }
  let : Module.Finite k N := Module.Finite.trans A N
  let : Module.Finite (Module.End A N) N :=
    Module.Finite.of_restrictScalars_finite k (Module.End A N) N
  let : IsSemisimpleModule A N := (finite_simple_algebra_module_isotypic k A N).1
  let f : A →ₐ[k] Module.End (Module.End A N) N :=
    { toRingHom := Module.toModuleEnd (Module.End A N) (S := A) N
      commutes' := by
        intro r
        ext x
        change (algebraMap k A r) • x = r • x
        exact IsScalarTower.algebraMap_smul A r x }
  have hAnn : Module.annihilator A N = ⊥ := by
    have h := (isSimpleRing_iff_isTwoSided_imp.mp (inferInstance : IsSimpleRing A)).2
      (Module.annihilator A N) inferInstance
    exact h.resolve_right (by
      intro htop
      exact (not_subsingleton N) (Module.annihilator_eq_top_iff.mp htop))
  let _ : FaithfulSMul A N := Module.annihilator_eq_bot.mp hAnn
  have hbij : Function.Bijective f := by
    constructor
    · exact (Module.toModuleEnd (Module.End A N) (S := A) N).injective
    · exact Module.Finite.toModuleEnd_moduleEnd_surjective
  refine ⟨n, inferInstance, L, inferInstance, inferInstance, inferInstance, hEnd, ?_⟩
  exact ⟨(AlgEquiv.ofBijective f hbij).symm⟩

end SimpleModules

section TensorProducts

theorem tensor_product_finite_central_simple (k A B : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [Algebra.IsCentral k A]
    [IsSimpleRing A] [Ring B] [Algebra k B] [FiniteDimensional k B]
    [Algebra.IsCentral k B] [IsSimpleRing B] :
    FiniteDimensional k (A ⊗[k] B) ∧
      Algebra.IsCentral k (A ⊗[k] B) ∧ IsSimpleRing (A ⊗[k] B) := by
  refine ⟨inferInstance, ?_, ?_⟩
  · refine { out := ?_ }
    intro z hz
    let e : (⊥ : Subalgebra k A) ⊗[k] B ≃ₐ[k] B :=
      (Algebra.TensorProduct.congr (Algebra.botEquiv k A)
        (AlgEquiv.refl : B ≃ₐ[k] B)).trans
        (Algebra.TensorProduct.lid k B)
    have he :
        Algebra.TensorProduct.map (⊥ : Subalgebra k A).val (AlgHom.id k B) =
          (Algebra.TensorProduct.includeRight : B →ₐ[k] A ⊗[k] B).comp e.toAlgHom := by
      apply AlgHom.ext
      intro x
      induction x using TensorProduct.induction_on with
      | zero => simp
      | add x y hx hy => rw [map_add, hx, hy, map_add]
      | tmul a b =>
        obtain ⟨r, hr⟩ := Algebra.mem_bot.mp a.property
        have ha : (Algebra.botEquiv k A).symm r = a := by
          apply Subtype.ext
          simpa using hr
        have har : Algebra.botEquiv k A a = r := by
          rw [← ha]
          simp
        simp only [Algebra.TensorProduct.map_tmul, AlgHom.id_apply, AlgHom.comp_apply,
          AlgEquiv.coe_toAlgHom, Algebra.TensorProduct.includeRight_apply]
        change (a : A) ⊗ₜ[k] b =
          1 ⊗ₜ[k] ((Algebra.botEquiv k A) a • b)
        rw [← hr, Algebra.algebraMap_eq_smul_one, TensorProduct.smul_tmul, har]
    have hzL : z ∈ Subalgebra.centralizer k
        (Algebra.TensorProduct.includeLeft : A →ₐ[k] A ⊗[k] B).range := by
      rw [Subalgebra.mem_centralizer_iff]
      intro x hx
      exact (Subalgebra.mem_center_iff.mp hz) x
    rw [Subalgebra.centralizer_coe_range_includeLeft_eq_center_tensorProduct] at hzL
    rw [Algebra.IsCentral.center_eq_bot k A] at hzL
    obtain ⟨x, hx⟩ := hzL
    have hz_eq : z = Algebra.TensorProduct.map (⊥ : Subalgebra k A).val
        (AlgHom.id k B) x := hx.symm
    have hz_eq' : z =
        (Algebra.TensorProduct.includeRight : B →ₐ[k] A ⊗[k] B) (e x) := by
      rw [hz_eq, he]
      change (Algebra.TensorProduct.includeRight : B →ₐ[k] A ⊗[k] B) (e x) =
        (Algebra.TensorProduct.includeRight : B →ₐ[k] A ⊗[k] B) (e x)
      rfl
    rw [hz_eq'] at hz
    have hxb : e x ∈ Subalgebra.center k B := by
      rw [Subalgebra.mem_center_iff]
      intro c
      apply (Algebra.TensorProduct.includeRight : B →ₐ[k] A ⊗[k] B).injective
      simpa using (Subalgebra.mem_center_iff.mp hz)
        ((Algebra.TensorProduct.includeRight : B →ₐ[k] A ⊗[k] B) c)
    have hxb0 : e x ∈ (⊥ : Subalgebra k B) := Algebra.IsCentral.out hxb
    obtain ⟨r, hr⟩ := Algebra.mem_bot.mp hxb0
    rw [hz_eq', ← hr]
    simpa using (Subalgebra.algebraMap_mem (⊥ : Subalgebra k (A ⊗[k] B)) r)
  · exact tensor_product_simple_of_simple_algebras k A B

theorem base_change_finite_central_simple (k A k' : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [Algebra.IsCentral k A]
    [IsSimpleRing A] [Field k'] [Algebra k k'] :
    letI : Algebra k' (A ⊗[k] k') :=
      Algebra.TensorProduct.rightAlgebra
    FiniteDimensional k' (A ⊗[k] k') ∧
      Algebra.IsCentral k' (A ⊗[k] k') ∧ IsSimpleRing (A ⊗[k] k') := by
  let _ : Algebra k' (A ⊗[k] k') := Algebra.TensorProduct.rightAlgebra
  let _ : Algebra k' (k' ⊗[k] A) := Algebra.TensorProduct.leftAlgebra
  have hfin : Module.Finite k' (k' ⊗[k] A) :=
    Module.Finite.base_change (R := k) (A := k') (M := A)
  let f : (k' ⊗[k] A) →ₗ[k'] (A ⊗[k] k') :=
    { toFun := Algebra.TensorProduct.comm k k' A
      map_add' := by simp
      map_smul' := by
        intro r x
        rw [Algebra.smul_def, Algebra.smul_def]
        calc
          (Algebra.TensorProduct.comm k k' A)
                (algebraMap k' (k' ⊗[k] A) r * x) =
              (Algebra.TensorProduct.comm k k' A)
                  (algebraMap k' (k' ⊗[k] A) r) *
                (Algebra.TensorProduct.comm k k' A) x :=
            (Algebra.TensorProduct.comm k k' A).map_mul _ _
          _ = algebraMap k' (A ⊗[k] k') r *
                (Algebra.TensorProduct.comm k k' A) x := by
            simp [Algebra.TensorProduct.algebraMap_def,
              Algebra.TensorProduct.right_algebraMap_apply] }
  let e : (k' ⊗[k] A) ≃ₗ[k'] (A ⊗[k] k') :=
    LinearEquiv.ofBijective f
      ⟨(Algebra.TensorProduct.comm k k' A).injective,
        (Algebra.TensorProduct.comm k k' A).surjective⟩
  let _ : Module.Finite k' (k' ⊗[k] A) := hfin
  let _ : Module.Finite k' (A ⊗[k] k') := Module.Finite.equiv e
  refine ⟨inferInstance, ?_, ?_⟩
  · refine { out := ?_ }
    intro z hz
    let eBot : (⊥ : Subalgebra k A) ⊗[k] k' ≃ₐ[k] k' :=
      (Algebra.TensorProduct.congr (Algebra.botEquiv k A)
        (AlgEquiv.refl : k' ≃ₐ[k] k')).trans
        (Algebra.TensorProduct.lid k k')
    have he :
        Algebra.TensorProduct.map (⊥ : Subalgebra k A).val (AlgHom.id k k') =
          (Algebra.TensorProduct.includeRight : k' →ₐ[k] A ⊗[k] k').comp
            eBot.toAlgHom := by
      apply AlgHom.ext
      intro x
      induction x using TensorProduct.induction_on with
      | zero => simp
      | add x y hx hy => rw [map_add, hx, hy, map_add]
      | tmul a b =>
        obtain ⟨r, hr⟩ := Algebra.mem_bot.mp a.property
        have ha : (Algebra.botEquiv k A).symm r = a := by
          apply Subtype.ext
          simpa using hr
        have har : Algebra.botEquiv k A a = r := by
          rw [← ha]
          simp
        simp only [Algebra.TensorProduct.map_tmul, AlgHom.id_apply, AlgHom.comp_apply,
          AlgEquiv.coe_toAlgHom, Algebra.TensorProduct.includeRight_apply]
        change (a : A) ⊗ₜ[k] b =
          1 ⊗ₜ[k] ((Algebra.botEquiv k A) a • b)
        rw [← hr, Algebra.algebraMap_eq_smul_one, TensorProduct.smul_tmul, har]
    have hzL : z ∈ Subalgebra.centralizer k
        (Algebra.TensorProduct.includeLeft : A →ₐ[k] A ⊗[k] k').range := by
      rw [Subalgebra.mem_centralizer_iff]
      intro x hx
      exact (Subalgebra.mem_center_iff.mp hz) x
    rw [Subalgebra.centralizer_coe_range_includeLeft_eq_center_tensorProduct] at hzL
    rw [Algebra.IsCentral.center_eq_bot k A] at hzL
    obtain ⟨x, hx⟩ := hzL
    have hz_eq : z = Algebra.TensorProduct.map (⊥ : Subalgebra k A).val
        (AlgHom.id k k') x := hx.symm
    have hz_eq' : z =
        (Algebra.TensorProduct.includeRight : k' →ₐ[k] A ⊗[k] k') (eBot x) := by
      rw [hz_eq, he]
      change (Algebra.TensorProduct.includeRight : k' →ₐ[k] A ⊗[k] k') (eBot x) =
        (Algebra.TensorProduct.includeRight : k' →ₐ[k] A ⊗[k] k') (eBot x)
      rfl
    rw [hz_eq']
    simpa [Algebra.TensorProduct.algebraMap_eq_includeRight] using
      (Subalgebra.algebraMap_mem (⊥ : Subalgebra k' (A ⊗[k] k')) (eBot x))
  · exact tensor_product_simple_of_simple_algebras_left k A k'

theorem inverse_of_finite_central_simple (k A : Type*) [Field k] [Ring A]
    [Algebra k A] [FiniteDimensional k A] [Algebra.IsCentral k A]
    [IsSimpleRing A] :
    Nonempty
      ((A ⊗[k] Aᵐᵒᵖ) ≃ₐ[k]
        Matrix (Fin (Module.finrank k A)) (Fin (Module.finrank k A)) k) := by
  let _ : IsSimpleRing (A ⊗[k] Aᵐᵒᵖ) :=
    (tensor_product_finite_central_simple k A Aᵐᵒᵖ).2.2
  let f : (A ⊗[k] Aᵐᵒᵖ) →ₐ[k] Module.End k A :=
    AlgHom.mulLeftRight k A
  have hf : Function.Injective f := RingHom.injective f.toRingHom
  have hdim : Module.finrank k (A ⊗[k] Aᵐᵒᵖ) =
      Module.finrank k (Module.End k A) := by
    rw [Module.finrank_tensorProduct, Module.finrank_linearMap]
    have hop : Module.finrank k A = Module.finrank k (Aᵐᵒᵖ) :=
      (MulOpposite.opLinearEquiv k : A ≃ₗ[k] Aᵐᵒᵖ).finrank_eq
    rw [← hop]
  have hsurj : Function.Surjective f.toLinearMap :=
    (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hdim).mp hf
  have hbij : Function.Bijective f := ⟨hf, hsurj⟩
  exact ⟨(AlgEquiv.ofBijective f hbij).trans
    (algEquivMatrix (Module.finBasis k A))⟩

end TensorProducts

end Formalization.Books.Brauer
