import Mathlib.Algebra.Category.ModuleCat.Abelian
import Mathlib.Algebra.Category.ModuleCat.Colimits
import Mathlib.Algebra.Colimit.Finiteness
import Mathlib.Algebra.Colimit.Ring
import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.LinearAlgebra.TensorProduct.DirectLimit
import Mathlib.Order.Directed
import Mathlib.RingTheory.IntegralClosure.IsIntegral.Basic
import Mathlib.RingTheory.Spectrum.Prime.RingHom

/-!
# Exercises, Chapter 2: Colimits

This file contains the source-facing constructions used by the colimit
exercises.  Directed systems and their colimits use Mathlib's
`DirectedSystem`, `Ring.DirectLimit`, and `Module.DirectLimit` APIs.
-/

noncomputable section

universe u v w

open CategoryTheory
open CategoryTheory.Limits
open scoped TensorProduct

namespace Formalization.Books.Exercises.Unit02

/-! ## Directed sets and systems of rings -/

/-- A directed set is a nonempty preorder in which every pair has a common
upper bound.  The order-theoretic part is Mathlib's `IsDirectedOrder`. -/
def IsDirectedSet (I : Type u) [Preorder I] : Prop :=
  Nonempty I ∧ IsDirectedOrder I

/-- The transition maps in a system of rings.  The identity and composition
laws are recorded by Mathlib's `DirectedSystem` typeclass. -/
abbrev RingSystem (I : Type u) [Preorder I] (A : I → Type v)
    [∀ i, CommRing (A i)] :=
  ∀ i j, i ≤ j → A i →+* A j

/-! ## The canonical directed ring colimit -/

/-- The ring colimit of a system of commutative rings. -/
abbrev ringColimit {I : Type u} [Preorder I]
    {A : I → Type v} [∀ i, CommRing (A i)]
    (φ : RingSystem I A) [DirectedSystem A (φ · · ·)] : Type max u v :=
  Ring.DirectLimit A (φ · · ·)

/-- The canonical map from a stage of a ring system to its colimit. -/
def ringColimitMap {I : Type u} [Preorder I]
    {A : I → Type v} [∀ i, CommRing (A i)]
    (φ : RingSystem I A) [DirectedSystem A (φ · · ·)] (i : I) :
    A i →+* ringColimit φ :=
  Ring.DirectLimit.of A (φ · · ·) i

/-- The canonical maps into the ring colimit satisfy the system relations. -/
@[simp]
theorem ringColimitMap_compatibility
    {I : Type u} [Preorder I]
    {A : I → Type v} [∀ i, CommRing (A i)]
    (φ : RingSystem I A) [DirectedSystem A (φ · · ·)]
    {i j : I} (hij : i ≤ j) (x : A i) :
    ringColimitMap φ j (φ i j hij x) = ringColimitMap φ i x :=
  Ring.DirectLimit.of_f (G := A) (f := fun i j h => φ i j h) hij x

/-- The map out of a ring colimit induced by compatible maps from its stages. -/
noncomputable def ringColimitLift
    {I : Type u} [Preorder I]
    {A : I → Type v} [∀ i, CommRing (A i)]
    (φ : RingSystem I A) [DirectedSystem A (φ · · ·)]
    {B : Type w} [CommRing B] (ψ : ∀ i, A i →+* B)
    (hψ : ∀ i j (hij : i ≤ j) (x : A i),
      ψ j (φ i j hij x) = ψ i x) :
    ringColimit φ →+* B :=
  Ring.DirectLimit.lift A (φ · · ·) B ψ hψ

@[simp]
theorem ringColimitLift_map
    {I : Type u} [Preorder I]
    {A : I → Type v} [∀ i, CommRing (A i)]
    (φ : RingSystem I A) [DirectedSystem A (φ · · ·)]
    {B : Type w} [CommRing B] (ψ : ∀ i, A i →+* B)
    (hψ : ∀ i j (hij : i ≤ j) (x : A i),
      ψ j (φ i j hij x) = ψ i x) (i : I) (x : A i) :
    ringColimitLift φ ψ hψ (ringColimitMap φ i x) = ψ i x := by
  exact Ring.DirectLimit.lift_of B ψ hψ i x

/-! ## Prime spectra of a directed ring colimit -/

/-- The compatible families of prime ideals in the stages of a ring system. -/
def compatiblePrimeSpectrumFamily
    {I : Type u} [Preorder I]
    {A : I → Type v} [∀ i, CommRing (A i)]
    (φ : RingSystem I A) : Set (∀ i, PrimeSpectrum (A i)) :=
  {p | ∀ i j (hij : i ≤ j),
      (p i).asIdeal = (p j).asIdeal.comap (φ i j hij)}

/-- Pull a prime of the colimit back to every stage. -/
def primeSpectrumColimitMap
    {I : Type u} [Preorder I]
    {A : I → Type v} [∀ i, CommRing (A i)]
    (φ : RingSystem I A) [DirectedSystem A (φ · · ·)] :
    PrimeSpectrum (ringColimit φ) →
      {p : ∀ i, PrimeSpectrum (A i) // p ∈ compatiblePrimeSpectrumFamily φ} := by
  intro p
  refine ⟨fun i => PrimeSpectrum.comap (ringColimitMap φ i) p, ?_⟩
  intro i j hij
  have hmap : (ringColimitMap φ j).comp (φ i j hij) = ringColimitMap φ i := by
    ext x
    exact ringColimitMap_compatibility φ hij x
  change (PrimeSpectrum.comap (ringColimitMap φ i) p).asIdeal =
    (PrimeSpectrum.comap (φ i j hij)
      (PrimeSpectrum.comap (ringColimitMap φ j) p)).asIdeal
  rw [← PrimeSpectrum.comap_comp_apply, hmap]

/-! ## Finite subextensions in an integral extension -/

/-- The finite subalgebra generated by a finite subset of an `A`-algebra. -/
def finiteSubalgebra {A B : Type u} [CommRing A] [CommRing B]
    [Algebra A B] (s : Finset B) : Subalgebra A B :=
  Algebra.adjoin A (s : Set B)

/-- The inclusion between the finite subalgebras generated by nested finite
subsets. -/
def finiteSubalgebraInclusion {A B : Type u} [CommRing A] [CommRing B]
    [Algebra A B] {s t : Finset B} (hst : s ≤ t) :
    finiteSubalgebra (A := A) (B := B) s →ₐ[A]
      finiteSubalgebra (A := A) (B := B) t :=
  Subalgebra.inclusion (Algebra.adjoin_mono (by
    intro x hx
    exact hst hx))

def finiteSubalgebraRingMap {A B : Type u} [CommRing A] [CommRing B]
    [Algebra A B] {s t : Finset B} (hst : s ≤ t) :
    finiteSubalgebra (A := A) (B := B) s →+*
      finiteSubalgebra (A := A) (B := B) t :=
  (finiteSubalgebraInclusion hst).toRingHom

/-- The directed colimit of the finite subalgebras generated inside `B`. -/
abbrev finiteSubalgebraColimit {A B : Type u} [CommRing A] [CommRing B]
    [Algebra A B] : Type u :=
  Ring.DirectLimit
    (fun s : Finset B => finiteSubalgebra (A := A) (B := B) s)
    (fun s t hst =>
      finiteSubalgebraRingMap (A := A) (B := B) (s := s) (t := t) hst)

/-- The canonical map from the colimit of the finite subalgebras to `B`. -/
noncomputable def finiteSubalgebraColimitMap {A B : Type u} [CommRing A] [CommRing B]
    [Algebra A B] : finiteSubalgebraColimit (A := A) (B := B) →+* B := by
  let ψ : ∀ s : Finset B, finiteSubalgebra (A := A) (B := B) s →+* B :=
    fun s => (finiteSubalgebra (A := A) (B := B) s).val.toRingHom
  refine Ring.DirectLimit.lift
    (fun s : Finset B => finiteSubalgebra (A := A) (B := B) s)
    (fun s t hst =>
      finiteSubalgebraRingMap (A := A) (B := B) (s := s) (t := t) hst)
    B ψ ?_
  intro s t hst x
  change ((finiteSubalgebraInclusion (A := A) (B := B)
    (s := s) (t := t) hst x : B)) = (x : B)
  rfl

/-! ## Tensor products and module colimits -/

/-- The canonical equivalence expressing that tensor product commutes with a
directed colimit of modules. -/
noncomputable def tensorProductDirectedColimitEquiv
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    {I : Type u} [Preorder I]
    {N : I → Type u} [∀ i, AddCommGroup (N i)] [∀ i, Module R (N i)]
    (f : ∀ i j, i ≤ j → N i →ₗ[R] N j)
    [DirectedSystem N (f · · ·)] (_hI : IsDirectedSet I) :
    (letI : DecidableEq I := Classical.decEq I
     Module.DirectLimit (fun i => M ⊗[R] N i)
       (fun i j h => LinearMap.lTensor M (f i j h))) ≃ₗ[R]
      (letI : DecidableEq I := Classical.decEq I
       M ⊗[R] Module.DirectLimit N f) := by
  letI : DecidableEq I := Classical.decEq I
  exact (TensorProduct.directLimitRight f M).symm

/-! ## Finitely presented module colimits -/

/-- A directed colimit presentation whose stages are finitely presented
modules.  This gives a precise directed-colimit reading of the source's
phrase “in some way a colimit of finitely presented modules”. -/
structure DirectedFinitelyPresentedModuleColimit
    {R : Type u} [CommRing R] (M : ModuleCat.{u} R) where
  index : Type u
  [indexPreorder : Preorder index]
  [indexNonempty : Nonempty index]
  [indexDirected : IsDirectedOrder index]
  diagram : index ⥤ ModuleCat.{u} R
  finitelyPresented : ∀ i, Module.FinitePresentation R (diagram.obj i)
  comparison : Nonempty (colimit diagram ≅ M)

end Formalization.Books.Exercises.Unit02
