import Formalization.Books.MoreAlgebra.Unit36.TopologicalRings
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Polynomial.Quotient

/-!
# Formal Algebraic Spaces, Chapter 28: Restricted power series

The source defines restricted power series as the inverse limit of the
polynomial rings over a fundamental system of open ideal quotients.  The
inverse system below is the corresponding Mathlib `CommRingCat` diagram.
The completion and topological statements are recorded as theorem interfaces;
the inverse-limit and coefficient conditions are concrete definitions.
-/

namespace Formalization.Books.FormalSpaces.Unit28

open CategoryTheory
open CategoryTheory.Limits
open Filter Set
open Formalization.Books.MoreAlgebra.Unit36

universe u v

noncomputable section

/-! ## The complete linearly topologized input -/

/-- A commutative topological ring complete and separated for a linear topology. -/
def IsCompleteLinearlyTopologizedRing (A : Type u) [CommRing A]
    [TopologicalSpace A] [IsTopologicalRing A] : Prop :=
  IsLinearTopology A A ∧ IsCompleteTopologicalAddGroup A

/-- A directed fundamental system of open ideals in a topological ring.

The antitone condition fixes the direction of the inverse system: if `i ≤ j`,
then the `j`-th quotient maps to the `i`-th quotient. -/
structure OpenIdealBasis (A : Type u) [CommRing A] [TopologicalSpace A] where
  Index : Type u
  [preorder : Preorder Index]
  I : Index → Ideal A
  directed : ∀ i j : Index, ∃ k : Index, i ≤ k ∧ j ≤ k
  antitone : Antitone I
  fundamental :
    (nhds (0 : A)).HasBasis (fun _ : Index => True)
      (fun i => (I i : Set A))
  isOpen : ∀ i, IsOpen (I i : Set A)

instance (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) : Preorder B.Index := B.preorder

/-- The ideal generated by an ideal of the coefficient ring in its polynomial
ring. -/
def polynomialExtensionIdeal (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Ideal (MvPolynomial (Fin r) A) :=
  Ideal.map (algebraMap A (MvPolynomial (Fin r) A)) I

/-- Quotienting coefficients commutes with forming the polynomial ring. -/
noncomputable def polynomialQuotientEquiv (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    MvPolynomial (Fin r) (A ⧸ I) ≃ₐ[A]
      (MvPolynomial (Fin r) A) ⧸ polynomialExtensionIdeal A I r :=
  MvPolynomial.quotientEquivQuotientMvPolynomial I

/-! ## The polynomial quotient inverse system and its limit -/

/-- The inverse-system term at `i` is the polynomial ring over `A ⧸ I i`. -/
def restrictedPowerSeriesDiagram (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    B.Indexᵒᵖ ⥤ CommRingCat.{u} where
  obj i := CommRingCat.of (MvPolynomial (Fin r) (A ⧸ B.I i.unop))
  map f :=
    CommRingCat.ofHom <|
      MvPolynomial.map
        (Ideal.Quotient.factor (B.antitone (CategoryTheory.le_of_op_hom f)))
  map_id i := by
    apply CommRingCat.hom_ext
    apply RingHom.ext
    intro p
    simp [Ideal.Quotient.factor_eq, MvPolynomial.map_id]
  map_comp f g := by
    apply CommRingCat.hom_ext
    apply RingHom.ext
    intro p
    simp [MvPolynomial.map_map, Ideal.Quotient.factor_comp]

/-- The restricted power series ring associated to an open ideal basis. -/
noncomputable abbrev restrictedPowerSeries (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) : Type u :=
  ((limit (restrictedPowerSeriesDiagram A B r) : CommRingCat.{u}) : Type u)

/-- The limit topology on the restricted power series ring.

Every quotient polynomial ring is given the discrete topology, and the limit
topology is the infimum of the topologies induced by the limit projections. -/
@[instance_reducible]
def restrictedPowerSeriesLimitTopology (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    TopologicalSpace (restrictedPowerSeries A B r) :=
  ⨅ i : B.Indexᵒᵖ, TopologicalSpace.induced
    ((limit.π (restrictedPowerSeriesDiagram A B r) i).hom)
    (⊥ : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ B.I i.unop)))

/-- The projection to one polynomial quotient in the inverse system. -/
noncomputable def restrictedPowerSeriesProjection (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) (i : B.Index) :
    restrictedPowerSeries A B r →+* MvPolynomial (Fin r) (A ⧸ B.I i) :=
  (limit.π (restrictedPowerSeriesDiagram A B r) (Opposite.op i)).hom

/-! ## Coefficients tending to zero -/

/-- A coefficient family is restricted when all but finitely many coefficients
are in every member of the chosen fundamental system. -/
def IsRestrictedCoefficientFamily (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ)
    (a : (Fin r →₀ ℕ) → A) : Prop :=
  ∀ i : B.Index, {E | a E ∉ B.I i}.Finite

/-- The coefficient of a limit element modulo one open ideal. -/
noncomputable def restrictedPowerSeriesCoefficient (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ)
    (_x : restrictedPowerSeries A B r) (i : B.Index) (E : Fin r →₀ ℕ) :
    A ⧸ B.I i :=
  MvPolynomial.coeff E (restrictedPowerSeriesProjection A B r i _x)

/-! ## The polynomial map into the completion -/

/-- The canonical map from the polynomial ring into the inverse limit. -/
noncomputable def restrictedPowerSeriesPolynomialMap (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    MvPolynomial (Fin r) A →+* restrictedPowerSeries A B r := by
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (MvPolynomial (Fin r) A)
      π :=
        { app := fun i =>
            CommRingCat.ofHom
              (MvPolynomial.map (Ideal.Quotient.mk (B.I i.unop)))
          naturality := by
            intro i j f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro p
            change
              MvPolynomial.map (Ideal.Quotient.mk (B.I j.unop)) p =
                MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone (CategoryTheory.le_of_op_hom f)))
                  (MvPolynomial.map (Ideal.Quotient.mk (B.I i.unop)) p)
            rw [MvPolynomial.map_map, Ideal.Quotient.factor_comp_mk] } }
  exact ((limit.isLimit D).lift c).hom

@[simp]
theorem restrictedPowerSeriesProjection_polynomialMap
    (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) (r : ℕ) (i : B.Index)
    (p : MvPolynomial (Fin r) A) :
    restrictedPowerSeriesProjection A B r i
        (restrictedPowerSeriesPolynomialMap A B r p) =
      MvPolynomial.map (Ideal.Quotient.mk (B.I i)) p := by
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (MvPolynomial (Fin r) A)
      π :=
        { app := fun j =>
            CommRingCat.ofHom
              (MvPolynomial.map (Ideal.Quotient.mk (B.I j.unop)))
          naturality := by
            intro j k f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro q
            change
              MvPolynomial.map (Ideal.Quotient.mk (B.I k.unop)) q =
                MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone (CategoryTheory.le_of_op_hom f)))
                  (MvPolynomial.map (Ideal.Quotient.mk (B.I j.unop)) q)
            rw [MvPolynomial.map_map, Ideal.Quotient.factor_comp_mk] } }
  have h := limit.lift_π c (Opposite.op i)
  have h' := congrArg (fun g => g.hom p) h
  change ((limit.lift D c ≫ limit.π D (Opposite.op i)).hom p) =
    (MvPolynomial.map (Ideal.Quotient.mk (B.I i))) p
  exact h'

/-! ## Assertions in the source -/

/-- The coefficient description of restricted power series.

For a complete separated input, every compatible limit element has a unique
coefficient family whose coefficients tend to zero, and whose reductions are
the coefficients of all quotient polynomials. -/
theorem restrictedPowerSeries_exists_unique_coefficients
    (A : Type u) [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (hA : IsCompleteLinearlyTopologizedRing A)
    (B : OpenIdealBasis A) (r : ℕ)
    (x : restrictedPowerSeries A B r) :
    ∃! a : (Fin r →₀ ℕ) → A,
      IsRestrictedCoefficientFamily A B r a ∧
        ∀ (i : B.Index) (E : Fin r →₀ ℕ),
          Ideal.Quotient.mk (B.I i) (a E) =
            restrictedPowerSeriesCoefficient A B r x i E := by
  classical
  let q : ∀ i : B.Index, (Fin r →₀ ℕ) → A ⧸ B.I i := fun i =>
    fun E => restrictedPowerSeriesCoefficient A B r x i E
  have hq : ∀ (i j : B.Index) (hij : i ≤ j) (E : Fin r →₀ ℕ),
      Ideal.Quotient.factor (B.antitone hij) (q j E) = q i E := by
    intro i j hij E
    have hlim := limit.w (restrictedPowerSeriesDiagram A B r) ((homOfLE hij).op)
    have hlim' := congrArg (fun q => q.hom x) hlim
    have hlim2 := hlim'
    change (MvPolynomial.map (Ideal.Quotient.factor (B.antitone hij)))
        (restrictedPowerSeriesProjection A B r j x) =
      restrictedPowerSeriesProjection A B r i x at hlim2
    have hcoeff := congrArg (fun p => MvPolynomial.coeff E p) hlim2
    rw [MvPolynomial.coeff_map] at hcoeff
    simpa [q, restrictedPowerSeriesCoefficient] using hcoeff
  have hIndex : Nonempty B.Index := by
    rcases B.fundamental.mem_iff.mp (univ_mem : (Set.univ : Set A) ∈ nhds 0) with
      ⟨i, -, hi⟩
    exact ⟨i⟩
  have hupper : ∀ (s : Set B.Index), s.Finite → ∃ k, ∀ i ∈ s, i ≤ k := by
    intro s hs
    induction s, hs using Set.Finite.induction_on with
    | empty =>
        exact ⟨Classical.choice hIndex, by simp⟩
    | @insert a s ha hs ih =>
        obtain ⟨k, hk⟩ := ih
        obtain ⟨l, hal, hkl⟩ := B.directed a k
        refine ⟨l, ?_⟩
        intro i hi
        rcases Set.mem_insert_iff.mp hi with rfl | hi
        · exact hal
        · exact (hk i hi).trans hkl
  have hfinite : ∀ (E : Fin r →₀ ℕ) (s : Set B.Index), s.Finite →
      (⋂ i ∈ s, (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}).Nonempty := by
    intro E s hs
    obtain ⟨k, hk⟩ := hupper s hs
    obtain ⟨a, ha⟩ := Ideal.Quotient.mk_surjective (q k E)
    refine ⟨a, ?_⟩
    simp only [Set.mem_iInter]
    intro i hi
    change Ideal.Quotient.mk (B.I i) a = q i E
    rw [← hq i k (hk i hi) E, ← ha]
    have hmk := congrArg (fun f : A →+* A ⧸ B.I i => f a)
      (Ideal.Quotient.factor_comp_mk (B.antitone (hk i hi)))
    exact hmk.symm
  have hAE : ∀ E : Fin r →₀ ℕ, ∃ a : A, ∀ i : B.Index,
      Ideal.Quotient.mk (B.I i) a = q i E := by
    intro E
    let F : Filter A := ⨅ i : B.Index,
      Filter.principal ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E})
    have hF : NeBot F := by
      change NeBot (⨅ i : B.Index,
        Filter.principal ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}))
      apply (Filter.hasBasis_iInf_principal_finite
        (fun i : B.Index => (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E})).neBot_iff.mpr
      intro s hs
      exact hfinite E s hs
    let : UniformSpace A := IsTopologicalAddGroup.rightUniformSpace A
    let : IsUniformAddGroup A := isUniformAddGroup_of_addCommGroup
    let : CompleteSpace A := hA.2.1
    have hC : Cauchy F := by
      refine (IsUniformAddGroup.cauchy_iff_tendsto F).2 ⟨hF, ?_⟩
      refine (B.fundamental.tendsto_right_iff).2 ?_
      intro i hi
      have hmem : (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈ F := by
        change (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈
          (⨅ j : B.Index, Filter.principal
            ((Ideal.Quotient.mk (B.I j)) ⁻¹' {q j E}))
        exact mem_iInf_of_mem i (by simp)
      have hprod :
          ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}) ×ˢ
            ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}) ∈ F ×ˢ F := by
        exact prod_mem_prod hmem hmem
      filter_upwards [hprod] with p hp
      rcases hp with ⟨hp₁, hp₂⟩
      apply Ideal.Quotient.eq_zero_iff_mem.mp
      rw [map_sub, hp₂, hp₁, sub_self]
    let : NeBot F := hF
    obtain ⟨a, ha⟩ := (cauchy_iff_exists_le_nhds (l := F)).mp hC
    refine ⟨a, ?_⟩
    intro i
    have hmem : (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈ F := by
      change (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈
        (⨅ j : B.Index, Filter.principal
          ((Ideal.Quotient.mk (B.I j)) ⁻¹' {q j E}))
      exact mem_iInf_of_mem i (by simp)
    have hclosed : IsClosed ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}) := by
      have hIclosed : IsClosed (B.I i : Set A) :=
        AddSubgroup.isClosed_of_isOpen (B.I i).toAddSubgroup (B.isOpen i)
      let : IsClosed ((B.I i).toAddSubgroup : Set A) := hIclosed
      exact isClosed_singleton.preimage QuotientAddGroup.continuous_mk
    have ha' : a ∈ (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} :=
      hclosed.mem_of_tendsto (f := id) (b := F) ha hmem
    exact ha'
  choose a ha using hAE
  have hcoef : ∀ (i : B.Index) (E : Fin r →₀ ℕ),
      Ideal.Quotient.mk (B.I i) (a E) =
        restrictedPowerSeriesCoefficient A B r x i E := by
    intro i E
    exact ha E i
  have hrestricted : IsRestrictedCoefficientFamily A B r a := by
    intro i
    let p := restrictedPowerSeriesProjection A B r i x
    apply p.support.finite_toSet.subset
    intro E hE
    apply MvPolynomial.mem_support_iff.mpr
    intro hzero
    apply hE
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    rw [hcoef i E]
    simpa [restrictedPowerSeriesCoefficient, p] using hzero
  refine ⟨a, ⟨hrestricted, hcoef⟩, ?_⟩
  intro b hb
  let : T2Space A := hA.2.2
  have hzero : ∀ z : A, (∀ i : B.Index, z ∈ B.I i) → z = 0 := by
    intro z hz
    by_contra hne
    have hcomp : ({z} : Set A)ᶜ ∈ nhds (0 : A) := by
      apply isClosed_singleton.isOpen_compl.mem_nhds
      exact Ne.symm hne
    rcases B.fundamental.mem_iff.mp hcomp with ⟨i, -, hi⟩
    exact (by simpa [hne] using hi (hz i))
  funext E
  apply sub_eq_zero.mp
  apply hzero (b E - a E)
  intro i
  apply Ideal.Quotient.eq_zero_iff_mem.mp
  rw [map_sub, hb.2 i E, hcoef i E, sub_self]

/-- The inverse-limit topology is complete and separated. -/
theorem restrictedPowerSeries_complete_for_limit_topology
    (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) (r : ℕ) :
    IsCompleteSeparatedTopologicalAddGroupFor
      (restrictedPowerSeries A B r)
      (restrictedPowerSeriesLimitTopology A B r) := by
  classical
  let D := restrictedPowerSeriesDiagram A B r
  let M := restrictedPowerSeries A B r
  let Q : B.Indexᵒᵖ → Type u := fun i => D.obj i
  let g : M →+ ∀ i : B.Indexᵒᵖ, Q i :=
    { toFun := fun x i => (limit.π D i).hom x
      map_zero' := by
        ext i
        exact map_zero _
      map_add' := by
        intro x y
        ext i
        exact map_add _ _ _ }
  let : ∀ i : B.Indexᵒᵖ, TopologicalSpace (Q i) := fun _ => ⊥
  let : ∀ i : B.Indexᵒᵖ, UniformSpace (Q i) := fun _ => ⊥
  let : ∀ i : B.Indexᵒᵖ, DiscreteTopology (Q i) :=
    fun _ => discreteTopology_bot _
  let u : UniformSpace M := UniformSpace.comap g (inferInstance : UniformSpace (∀ i, Q i))
  let : UniformSpace M := u
  have hu : IsUniformAddGroup M := by
    refine ⟨?_⟩
    apply uniformContinuous_comap' (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))
    convert
      (uniformContinuous_sub.comp
        (((uniformContinuous_comap (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))).comp
            uniformContinuous_fst).prodMk
          ((uniformContinuous_comap (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))).comp
            uniformContinuous_snd))) using 1
    ext p
    simp [map_sub]
  let : IsUniformAddGroup M := hu
  have htop : u.toTopologicalSpace = restrictedPowerSeriesLimitTopology A B r := by
    change TopologicalSpace.induced g Pi.topologicalSpace = _
    rw [induced_to_pi]
    rfl
  have hD : IsLimit ((forget CommRingCat).mapCone (limit.cone D)) :=
    isLimitOfPreserves (forget CommRingCat) (limit.isLimit D)
  have hinj : Function.Injective g := by
    intro x y hxy
    apply (Types.isLimitEquivSections hD).injective
    ext i
    exact congrFun hxy i
  let S : Set (∀ i : B.Indexᵒᵖ, Q i) :=
    ⋂ (i : B.Indexᵒᵖ) (j : B.Indexᵒᵖ) (f : i ⟶ j),
      {z | (D.map f).hom (z i) = z j}
  have hgrange : Set.range g = S := by
    ext z
    constructor
    · rintro ⟨x, rfl⟩
      simp only [S, Set.mem_iInter]
      intro i j f
      exact congrArg (fun q => q.hom x) (limit.w D f)
    · intro hz
      simp only [S, Set.mem_iInter] at hz
      have hz' : ∀ (i j : B.Indexᵒᵖ) (f : i ⟶ j),
          (D.map f).hom (z i) = z j := by
        intro i j f
        exact hz i j f
      let c : Cone (D ⋙ forget CommRingCat) :=
        { pt := PUnit.{u + 1}
          π := { app := fun i => TypeCat.ofHom (fun _ : PUnit.{u + 1} => z i)
                 naturality := by
                   intro i j f
                   ext x
                   exact (hz' i j f).symm } }
      refine ⟨hD.lift c (PUnit.unit : PUnit.{u + 1}), ?_⟩
      funext i
      simpa [g, c] using congrArg (fun q => q (PUnit.unit : PUnit.{u + 1})) (hD.fac c i)
  have hSclosed : IsClosed S := by
    apply isClosed_iInter
    intro i
    apply isClosed_iInter
    intro j
    apply isClosed_iInter
    intro f
    let : ∀ i : B.Indexᵒᵖ, T2Space (D.obj i) := fun _ => by
      infer_instance
    apply isClosed_eq
    · exact (continuous_of_discreteTopology :
        Continuous ((D.map f).hom : Q i → Q j)).comp (continuous_apply i)
    · exact continuous_apply j
  have hprod : CompleteSpace (∀ i : B.Indexᵒᵖ, Q i) := by
    infer_instance
  let : CompleteSpace (∀ i : B.Indexᵒᵖ, Q i) := hprod
  have hrange : IsComplete (Set.range g) := by
    rw [hgrange]
    exact hSclosed.isComplete
  have hcomplete : @CompleteSpace M u :=
    (completeSpace_iff_isComplete_range ⟨rfl⟩).2 hrange
  let : TopologicalSpace M := u.toTopologicalSpace
  have hT2 : @T2Space M (restrictedPowerSeriesLimitTopology A B r) := by
    rw [← htop]
    exact T2Space.of_injective_continuous hinj
      (uniformContinuous_comap (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))).continuous
  refine ⟨u, htop, hu, hcomplete, hT2⟩

/-- The universal property: an algebra map from the polynomial ring to a
complete linearly topologized target extends uniquely to a continuous ring map
on restricted power series. -/
theorem restrictedPowerSeries_universal_property
    (A C : Type u) [CommRing A] [CommRing C]
    [Algebra A C]
    [TopologicalSpace A] [TopologicalSpace C]
    [IsTopologicalRing A] [IsTopologicalRing C]
    (hA : IsCompleteLinearlyTopologizedRing A)
    (hC : IsCompleteLinearlyTopologizedRing C)
    (hAC : Continuous (algebraMap A C))
    (B : OpenIdealBasis A) (r : ℕ)
    (f : MvPolynomial (Fin r) A →ₐ[A] C) :
    ∃! F : restrictedPowerSeries A B r →+* C,
      (@Continuous (restrictedPowerSeries A B r) C
        (restrictedPowerSeriesLimitTopology A B r) inferInstance F) ∧
        F.comp (restrictedPowerSeriesPolynomialMap A B r) = f.toRingHom := by
  /-
  Proof roadmap (dense uniform extension).

  * Abbreviate `P := MvPolynomial (Fin r) A`,
    `M := restrictedPowerSeries A B r`, and
    `ι := restrictedPowerSeriesPolynomialMap A B r`.  Destructure
    `restrictedPowerSeries_complete_for_limit_topology A B r` to obtain a
    uniformity `uM` on `M`; install `uM`, its `IsUniformAddGroup`,
    `CompleteSpace`, and `T2Space` witnesses locally, rewriting its induced
    topology with the returned equality.  On `C`, install
    `IsTopologicalAddGroup.rightUniformSpace C`; the two components of
    `hC.2` are exactly the required `CompleteSpace` and `T2Space` instances.
    Install `hC.1 : IsLinearTopology C C` locally as well.

  * Give `P` the pulled-back uniformity `UniformSpace.comap ι uM`.  Then
    `ι` is an `IsUniformInducing` by reflexivity.  Construct the associated
    `IsUniformAddGroup P` by `uniformContinuous_comap'`, using
    `ι.map_sub`; similarly record that addition, negation, and multiplication
    on `M` are continuous by unfolding
    `restrictedPowerSeriesLimitTopology` and testing every coordinate with
    `continuous_iff_le_induced`.  Each coordinate is a ring homomorphism into
    a discrete ring, so `continuous_of_discreteTopology` closes the coordinate
    goals.  This supplies the `IsTopologicalSemiring M` instance needed by
    `IsDenseInducing.extendRingHom` from
    `Mathlib/Topology/Algebra/UniformRing.lean`.

  * Prove `hι_dense : DenseRange ι`.  First derive a neighbourhood basis at
    `x : M` consisting of finite intersections
    `⋂ i ∈ s, (restrictedPowerSeriesProjection A B r i) ⁻¹'
      {restrictedPowerSeriesProjection A B r i x}`; use `nhds_iInf`,
    `nhds_induced`, discreteness, and
    `Filter.hasBasis_iInf_principal_finite`.  For finite `s`, repeatedly use
    `B.directed` to choose `k : B.Index` above every member of `s`.  Lift the
    polynomial `restrictedPowerSeriesProjection A B r k x` to `p : P` via
    `MvPolynomial.map_surjective Ideal.Quotient.mk_surjective`.  The limit
    compatibility `limit.w (restrictedPowerSeriesDiagram A B r)` and
    `restrictedPowerSeriesProjection_polynomialMap` then show that `ι p`
    agrees with `x` at every index in `s`, hence lies in the prescribed
    neighbourhood.

  * Prove `hf0 : ContinuousAt f.toRingHom 0` for the pulled-back topology on
    `P`.  Given a neighbourhood of `0` in `C`, refine it to an open ideal
    `J` using `linearlyTopologizedRing_hasBasis_open_ideal C`.  Apply
    `hAC.continuousAt` and `B.fundamental` to choose `i` such that
    `B.I i ⊆ (algebraMap A C) ⁻¹' J`.  The preimage under `ι` of the kernel
    of the `i`-th projection is a neighbourhood of zero.  If `p` is in it,
    `restrictedPowerSeriesProjection_polynomialMap` says that
    `MvPolynomial.map (Ideal.Quotient.mk (B.I i)) p = 0`.
    Apply `polynomialQuotientEquiv A (B.I i) r` and
    `Ideal.Quotient.eq_zero_iff_mem` to get
    `p ∈ polynomialExtensionIdeal A (B.I i) r`.  Unfold that ideal and use
    `Ideal.map_le_iff_le_comap`, `f.commutes`, and the choice of `i` to obtain
    `f p ∈ J`.  Upgrade `hf0` first with
    `continuous_of_continuousAt_zero f.toRingHom`, then with
    `uniformContinuous_addMonoidHom_of_continuous` from
    `Mathlib/Topology/Algebra/IsUniformGroup/Defs.lean`.

  * Define `F` with
    `IsDenseInducing.extendRingHom hι_uniform hι_dense hf_uniform`.  Its
    continuity is
    `(uniformContinuous_uniformly_extend hι_uniform hι_dense hf_uniform).continuous`.
    The extension equation follows pointwise from
    `uniformly_extend_of_ind hι_uniform hι_dense hf_uniform`; finish the
    bundled equality with `RingHom.ext` (or `rfl` after extensionality).

  * For uniqueness, if `G` is another continuous extension, compare `F` and
    `G` on `Set.univ`.  Their equality on `Set.range ι` is the two extension
    equations, this range is dense by `hι_dense`, and `hC.2.2` makes the
    equalizer closed.  Apply `Continuous.ext_on` (equivalently
    `DenseRange.induction_on`) to get `F = G`.
  -/
  classical
  let _ : IsLinearTopology A A := hA.1
  let M := restrictedPowerSeries A B r
  let P := MvPolynomial (Fin r) A
  let ι : P →+* M := restrictedPowerSeriesPolynomialMap A B r
  obtain ⟨u, htop, hu, _, _⟩ :=
    restrictedPowerSeries_complete_for_limit_topology A B r
  let _ : UniformSpace M := u
  let _ : TopologicalSpace M := u.toTopologicalSpace
  let _ : IsRightUniformAddGroup M := hu.isRightUniformAddGroup
  let _ : IsTopologicalAddGroup M := inferInstance
  let _ : IsTopologicalAddGroup C := by infer_instance
  let _ : UniformSpace C := IsTopologicalAddGroup.rightUniformSpace C
  let _ : CompleteSpace C := hC.2.1
  let _ : T2Space C := hC.2.2
  let _ : IsLinearTopology C C := hC.1
  let _ : IsUniformAddGroup C := isUniformAddGroup_of_addCommGroup
  let _ : UniformSpace P := UniformSpace.comap ι u
  let _ : TopologicalSpace P := (inferInstance : UniformSpace P).toTopologicalSpace
  have hι_uniform : IsUniformInducing ι := ⟨by rfl⟩
  have hι_group : IsUniformAddGroup P := by
    refine ⟨?_⟩
    apply uniformContinuous_comap' (f := (ι : P → M))
    convert (hu.uniformContinuous_sub.comp
      (((uniformContinuous_comap (f := (ι : P → M))).comp uniformContinuous_fst).prodMk
        ((uniformContinuous_comap (f := (ι : P → M))).comp uniformContinuous_snd))) using 1
    ext p
    simp [map_sub]
  let _ : IsUniformAddGroup P := hι_group
  let _ : IsTopologicalAddGroup P := inferInstance
  have hcoord : ∀ i : B.Index,
      @Continuous M (MvPolynomial (Fin r) (A ⧸ B.I i)) u.toTopologicalSpace ⊥
        (restrictedPowerSeriesProjection A B r i) := by
    intro i
    apply continuous_iff_le_induced.mpr
    rw [htop]
    change restrictedPowerSeriesLimitTopology A B r ≤
      TopologicalSpace.induced (restrictedPowerSeriesProjection A B r i) ⊥
    rw [restrictedPowerSeriesLimitTopology]
    exact iInf_le _ (Opposite.op i)
  have hmulcoord : ∀ i : B.Index,
      @Continuous (M × M) (MvPolynomial (Fin r) (A ⧸ B.I i))
        (@instTopologicalSpaceProd M M u.toTopologicalSpace u.toTopologicalSpace) ⊥
        (fun p => (restrictedPowerSeriesProjection A B r i p.1) *
          (restrictedPowerSeriesProjection A B r i p.2)) := by
    intro i
    let _ : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ B.I i)) := ⊥
    let _ : DiscreteTopology (MvPolynomial (Fin r) (A ⧸ B.I i)) :=
      discreteTopology_bot _
    have hp : @Continuous (M × M)
        ((MvPolynomial (Fin r) (A ⧸ B.I i)) ×
          (MvPolynomial (Fin r) (A ⧸ B.I i)))
        (@instTopologicalSpaceProd M M u.toTopologicalSpace u.toTopologicalSpace)
        (@instTopologicalSpaceProd
          (MvPolynomial (Fin r) (A ⧸ B.I i))
          (MvPolynomial (Fin r) (A ⧸ B.I i)) ⊥ ⊥)
        (fun p => (restrictedPowerSeriesProjection A B r i p.1,
          restrictedPowerSeriesProjection A B r i p.2)) :=
      (hcoord i).prodMap (hcoord i)
    have hm : @Continuous
        ((MvPolynomial (Fin r) (A ⧸ B.I i)) ×
          (MvPolynomial (Fin r) (A ⧸ B.I i)))
        (MvPolynomial (Fin r) (A ⧸ B.I i))
        (@instTopologicalSpaceProd
          (MvPolynomial (Fin r) (A ⧸ B.I i))
          (MvPolynomial (Fin r) (A ⧸ B.I i)) ⊥ ⊥) ⊥
        (fun p => p.1 * p.2) := by
      exact continuous_of_discreteTopology
    simpa only [Function.comp_def] using hm.comp hp
  have hmul_target : @Continuous (M × M) M
      (@instTopologicalSpaceProd M M u.toTopologicalSpace u.toTopologicalSpace)
        (restrictedPowerSeriesLimitTopology A B r)
      (fun p => p.1 * p.2) := by
    change @Continuous (M × M) M
      (@instTopologicalSpaceProd M M u.toTopologicalSpace u.toTopologicalSpace)
      (⨅ i : B.Indexᵒᵖ,
        TopologicalSpace.induced
          (restrictedPowerSeriesProjection A B r i.unop) ⊥)
      (fun p => p.1 * p.2)
    refine (continuous_iInf_rng (f := fun p : M × M => p.1 * p.2)).mpr ?_
    intro i
    rw [continuous_iff_le_induced]
    simpa only [induced_compose, Function.comp_def, map_mul] using
      (continuous_iff_le_induced.mp (hmulcoord i.unop))
  have hmul : @Continuous (M × M) M
      (@instTopologicalSpaceProd M M u.toTopologicalSpace u.toTopologicalSpace)
        u.toTopologicalSpace
      (fun p => p.1 * p.2) := by
    convert hmul_target using 1
  let _ : ContinuousMul M := ⟨hmul⟩
  let _ : IsTopologicalSemiring M :=
    { toContinuousAdd := inferInstance
      toContinuousMul := inferInstance }
  have hupper : ∀ s : Set B.Index, s.Finite → ∃ k, ∀ i ∈ s, i ≤ k := by
    intro s hs
    induction s, hs using Set.Finite.induction_on with
    | empty =>
        have hne : Nonempty B.Index := by
          rcases B.fundamental.mem_iff.mp
              (univ_mem : (Set.univ : Set A) ∈ nhds 0) with ⟨i, -, hi⟩
          exact ⟨i⟩
        exact ⟨Classical.choice hne, by simp⟩
    | @insert a s ha hs ih =>
        obtain ⟨k, hk⟩ := ih
        obtain ⟨l, hal, hkl⟩ := B.directed a k
        refine ⟨l, ?_⟩
        intro i hi
        rcases Set.mem_insert_iff.mp hi with rfl | hi
        · exact hal
        · exact (hk i hi).trans hkl
  have hnhds (x : M) :
      @nhds M u.toTopologicalSpace x =
        ⨅ i : B.Indexᵒᵖ,
          Filter.principal
            ((restrictedPowerSeriesProjection A B r i.unop) ⁻¹'
              {restrictedPowerSeriesProjection A B r i.unop x}) := by
    let : ∀ i : B.Indexᵒᵖ,
        TopologicalSpace (MvPolynomial (Fin r) (A ⧸ B.I i.unop)) := fun _ => ⊥
    let : ∀ i : B.Indexᵒᵖ,
        DiscreteTopology (MvPolynomial (Fin r) (A ⧸ B.I i.unop)) :=
      fun _ => discreteTopology_bot _
    rw [htop, restrictedPowerSeriesLimitTopology, nhds_iInf]
    change (⨅ i : B.Indexᵒᵖ,
      @nhds M
        (TopologicalSpace.induced (restrictedPowerSeriesProjection A B r i.unop)
          (⊥ : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ B.I i.unop)))) x) = _
    simp only [nhds_induced]
    change (⨅ i : B.Indexᵒᵖ,
      Filter.comap (restrictedPowerSeriesProjection A B r i.unop)
        (@nhds (MvPolynomial (Fin r) (A ⧸ B.I i.unop)) ⊥
          (restrictedPowerSeriesProjection A B r i.unop x))) = _
    simp only [nhds_discrete, comap_pure]
  have hι_dense : DenseRange ι := by
    rw [DenseRange, dense_iff_inter_open]
    intro U hU hU_nonempty
    rcases hU_nonempty with ⟨x, hx⟩
    have hUx : U ∈ @nhds M u.toTopologicalSpace x := hU.mem_nhds hx
    rw [hnhds x] at hUx
    obtain ⟨s, hs, hsU⟩ :=
      (Filter.hasBasis_iInf_principal_finite
        (fun i : B.Indexᵒᵖ =>
          (restrictedPowerSeriesProjection A B r i.unop) ⁻¹'
            {restrictedPowerSeriesProjection A B r i.unop x})).mem_iff.mp hUx
    obtain ⟨k, hk⟩ := hupper (Opposite.unop '' s) (hs.image _)
    obtain ⟨p, hp⟩ :=
      (MvPolynomial.map_surjective (Ideal.Quotient.mk (B.I k))
        Ideal.Quotient.mk_surjective)
        (restrictedPowerSeriesProjection A B r k x)
    refine ⟨ι p, hsU ?_, ⟨p, rfl⟩⟩
    simp only [Set.mem_iInter]
    intro i hi
    have hik : i.unop ≤ k := hk i.unop ⟨i, hi, rfl⟩
    have hlim := limit.w (restrictedPowerSeriesDiagram A B r)
      ((homOfLE hik).op)
    have hlim' := congrArg (fun q => q.hom x) hlim
    change MvPolynomial.map (Ideal.Quotient.factor (B.antitone hik))
        (restrictedPowerSeriesProjection A B r k x) =
      restrictedPowerSeriesProjection A B r i.unop x at hlim'
    change restrictedPowerSeriesProjection A B r i.unop (ι p) =
      restrictedPowerSeriesProjection A B r i.unop x
    rw [restrictedPowerSeriesProjection_polynomialMap]
    rw [← hp] at hlim'
    simpa [MvPolynomial.map_map, Ideal.Quotient.factor_comp_mk] using hlim'
  have hf0 : ContinuousAt f.toRingHom 0 := by
    rw [ContinuousAt]
    rw [map_zero]
    refine (linearlyTopologizedRing_hasBasis_open_ideal C).tendsto_right_iff.2 ?_
    intro J hJ
    have hJmem : (J : Set C) ∈ nhds (0 : C) :=
      (linearlyTopologizedRing_hasBasis_open_ideal C).mem_iff.mpr
        ⟨J, hJ, Subset.rfl⟩
    have hpre : (algebraMap A C) ⁻¹' (J : Set C) ∈ nhds (0 : A) := by
      apply hAC.continuousAt.preimage_mem_nhds
      simpa using hJmem
    rcases B.fundamental.mem_iff.mp hpre with ⟨i, -, hi⟩
    let _ : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ B.I i)) := ⊥
    let _ : DiscreteTopology (MvPolynomial (Fin r) (A ⧸ B.I i)) :=
      discreteTopology_bot _
    let V : Set M :=
      (restrictedPowerSeriesProjection A B r i) ⁻¹' ({0} : Set _)
    have hV : V ∈ @nhds M u.toTopologicalSpace 0 := by
      apply (hcoord i).continuousAt.preimage_mem_nhds
      simp only [nhds_discrete, mem_pure]
      simp
    have hVP : ι ⁻¹' V ∈ @nhds P (inferInstance : TopologicalSpace P) 0 := by
      change ι ⁻¹' V ∈
        @nhds P (TopologicalSpace.induced ι u.toTopologicalSpace) 0
      apply (mem_nhds_induced ι 0 (ι ⁻¹' V)).2
      exact ⟨V, by simpa using hV, Subset.rfl⟩
    apply Filter.mem_of_superset hVP
    intro p hp
    have hmapzero :
        MvPolynomial.map (Ideal.Quotient.mk (B.I i)) p = 0 := by
      change restrictedPowerSeriesProjection A B r i (ι p) = 0 at hp
      rw [restrictedPowerSeriesProjection_polynomialMap] at hp
      exact hp
    have hpolyzero :
        Ideal.Quotient.mk (polynomialExtensionIdeal A (B.I i) r) p = 0 := by
      have heval : ∀ q : P,
          (polynomialQuotientEquiv A (B.I i) r).symm
              (Ideal.Quotient.mk (polynomialExtensionIdeal A (B.I i) r) q) =
            MvPolynomial.map (Ideal.Quotient.mk (B.I i)) q := by
        intro q
        induction q using MvPolynomial.induction_on' with
        | monomial d a =>
            change MvPolynomial.eval₂Hom
                (MvPolynomial.C.comp (Ideal.Quotient.mk (B.I i))) MvPolynomial.X
                (MvPolynomial.monomial d a) = _
            simp [MvPolynomial.map_monomial]
            rw [MvPolynomial.monomial_eq]
            symm
            rw [Finsupp.prod_fintype]
            simp
        | add p q hp hq =>
            simp only [map_add]
            rw [hp, hq]
      apply (polynomialQuotientEquiv A (B.I i) r).symm.injective
      rw [heval, hmapzero]
      simp
    have hpideal : p ∈ polynomialExtensionIdeal A (B.I i) r :=
      Ideal.Quotient.eq_zero_iff_mem.mp hpolyzero
    have hmaple :
        Ideal.map f.toRingHom (polynomialExtensionIdeal A (B.I i) r) ≤ J := by
      rw [polynomialExtensionIdeal, Ideal.map_map]
      rw [Ideal.map_le_iff_le_comap]
      intro a ha
      simpa [RingHom.comp_apply, f.commutes] using hi ha
    exact hmaple (Ideal.mem_map_of_mem f.toRingHom hpideal)
  have hf_uniform : UniformContinuous f.toRingHom :=
    uniformContinuous_of_continuousAt_zero f.toRingHom hf0
  let F : M →+* C :=
    IsDenseInducing.extendRingHom hι_uniform hι_dense hf_uniform
  have hFcont : @Continuous M C u.toTopologicalSpace _ F :=
    (uniformContinuous_uniformly_extend hι_uniform hι_dense hf_uniform).continuous
  have hFext : F.comp ι = f.toRingHom := by
    apply RingHom.ext
    intro p
    exact uniformly_extend_of_ind hι_uniform hι_dense hf_uniform p
  refine ⟨F, ?_, ?_⟩
  · constructor
    · change @Continuous (restrictedPowerSeries A B r) C
        (restrictedPowerSeriesLimitTopology A B r) _ F
      rw [← htop]
      exact hFcont
    · exact hFext
  · intro G hG
    have hGcont : @Continuous M C u.toTopologicalSpace _ G := by
      change @Continuous (restrictedPowerSeries A B r) C u.toTopologicalSpace _ G
      rw [htop]
      exact hG.1
    have hFGfun : (F : M → C) = G := by
      apply Continuous.ext_on hι_dense hFcont hGcont
      intro x hx
      rcases hx with ⟨p, rfl⟩
      have hFp : F (ι p) = f.toRingHom p :=
        congrArg (fun q : P →+* C => q p) hFext
      have hGp : G (ι p) = f.toRingHom p :=
        congrArg (fun q : P →+* C => q p) hG.2
      exact hFp.trans hGp.symm
    apply RingHom.ext
    intro x
    exact (congrFun hFGfun x).symm

/-! ## The I-adic comparison and its warnings -/

/-- The canonical I-adic completion of the polynomial ring. -/
noncomputable abbrev iAdicPolynomialCompletion (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Type u :=
  AdicCompletion (polynomialExtensionIdeal A I r) (MvPolynomial (Fin r) A)

/-- The I-adic topology on the polynomial completion. -/
@[instance_reducible]
def iAdicPolynomialCompletionTopology (A : Type u) [CommRing A]
  (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicPolynomialCompletion A I r) :=
  IAdicModuleTopology
    (MvPolynomial (Fin r) A) (polynomialExtensionIdeal A I r)
    (iAdicPolynomialCompletion A I r)

/-- The chosen I-adic open-ideal basis on `A`. -/
def iAdicOpenIdealBasis (A : Type u) [CommRing A] (I : Ideal A) :
    @OpenIdealBasis A _ I.adicTopology :=
  let : TopologicalSpace A := I.adicTopology
  { Index := ULift.{u} ℕ
    I := fun n => I ^ n.down
    directed := fun m n =>
      ⟨ULift.up (max m.down n.down), by
        simp, by
        simp⟩
    antitone := fun m n hmn => by
      apply Ideal.pow_le_pow_right
      exact hmn
    fundamental := by
      simpa [Function.comp_def] using
        (I.hasBasis_nhds_zero_adic.comp_equiv
          (Equiv.ulift : ULift.{u} ℕ ≃ ℕ))
    isOpen := fun n => by
      have hmem : ((I ^ n.down : Ideal A) : Set A) ∈
          @nhds A I.adicTopology (0 : A) := by
        exact I.hasBasis_nhds_zero_adic.mem_iff.mpr
          ⟨n.down, trivial, Subset.rfl⟩
      exact (I ^ n.down).toAddSubgroup.isOpen_of_mem_nhds hmem }

/-- The inverse-limit topology on the I-adic completion. -/
@[instance_reducible]
def iAdicPolynomialCompletionLimitTopology (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicPolynomialCompletion A I r) :=
  AdicCompletionLimitTopology
    (MvPolynomial (Fin r) A) (polynomialExtensionIdeal A I r)
    (MvPolynomial (Fin r) A)

/-- The I-adic specialization of the restricted power series type, with the
adic topology on the coefficient ring made explicit. -/
noncomputable abbrev iAdicRestrictedPowerSeries (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Type u :=
  @restrictedPowerSeries A _ I.adicTopology (iAdicOpenIdealBasis A I) r

@[instance_reducible]
def iAdicRestrictedPowerSeriesLimitTopology (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicRestrictedPowerSeries A I r) :=
  @restrictedPowerSeriesLimitTopology A _ I.adicTopology
    (iAdicOpenIdealBasis A I) r

/-- In the I-adically complete case, the I-adic completion of the polynomial
ring is the restricted power series ring as a ring. -/
theorem iAdicPolynomialCompletion_is_restrictedPowerSeries_as_ring
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ)
    (_hA : IsAdicComplete I A) :
    Nonempty
      (iAdicPolynomialCompletion A I r ≃+*
        iAdicRestrictedPowerSeries A I r) := by
  classical
  let P := MvPolynomial (Fin r) A
  let J := polynomialExtensionIdeal A I r
  have hpow : ∀ n : ℕ, J ^ n =
      Ideal.map (MvPolynomial.C : A →+* P) (I ^ n) := by
    intro n
    simp [J, polynomialExtensionIdeal, Ideal.map_pow]
  let q : ∀ n : ℕ, (P ⧸ J ^ n) ≃+*
      MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n =>
    ((MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).toRingEquiv.trans
      (Ideal.quotientEquivAlgOfEq P (hpow n).symm).toRingEquiv).symm
  let e : ∀ n : ℕ, (P ⧸ J ^ n) ≃+*
      MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n => q n
  have heC : ∀ (n : ℕ) (a : A),
      e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a)) =
        MvPolynomial.C (Ideal.Quotient.mk (I ^ n) a) := by
    intro n a
    apply (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).injective
    change (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n))
        (e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a))) = _
    simp [q, e, MvPolynomial.quotientEquivQuotientMvPolynomial,
      MvPolynomial.eval₂_C]
  have heX : ∀ (n : ℕ) (i : Fin r),
      e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i)) =
        MvPolynomial.X i := by
    intro n i
    apply (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).injective
    change (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n))
        (e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i))) = _
    simp [q, e, MvPolynomial.quotientEquivQuotientMvPolynomial,
      MvPolynomial.eval₂_X]
  have hcompat : ∀ {m n : ℕ} (hmn : m ≤ n),
      (MvPolynomial.map (Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn))).comp
          (e n).toRingHom =
        (e m).toRingHom.comp (Ideal.Quotient.factorPow J hmn) := by
    intro m n hmn
    apply RingHom.ext
    intro x
    obtain ⟨y, rfl⟩ := (e n).symm.surjective x
    apply MvPolynomial.induction_on y
    · intro a
      obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a
      have h_invC :
          (e n).symm (MvPolynomial.C (Ideal.Quotient.mk (I ^ n) a)) =
            Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a) := by
        rw [← heC n a]
        exact (e n).symm_apply_apply _
      rw [h_invC]
      simp [heC]
    · intro p q hp hq
      simpa only [map_add] using congrArg₂ (· + ·) hp hq
    · intro p i hp
      have hxi :
          ((MvPolynomial.map (Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn))).comp
            (e n).toRingHom) ((e n).symm (MvPolynomial.X i)) =
          ((e m).toRingHom.comp
            (Ideal.Quotient.factorPow J hmn)) ((e n).symm (MvPolynomial.X i)) := by
        have h_invX :
            (e n).symm (MvPolynomial.X i) =
              Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i) := by
          rw [← heX n i]
          exact (e n).symm_apply_apply _
        rw [h_invX]
        simp [heX]
      simpa only [map_mul] using congrArg₂ (· * ·) hp hxi
  have heval : ∀ {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion J P),
      Ideal.Quotient.factorPow J hmn (AdicCompletion.evalₐ J n x) =
        AdicCompletion.evalₐ J m x := by
    intro m n hmn x
    let hn : (J ^ n • ⊤ : Submodule P P) ≤ J ^ n :=
      le_of_eq (Ideal.mul_top _)
    let hm : (J ^ m • ⊤ : Submodule P P) ≤ J ^ m :=
      le_of_eq (Ideal.mul_top _)
    have hfac : ∀ (y : P ⧸ (J ^ n • ⊤ : Submodule P P)),
        Ideal.Quotient.factorPow J hmn (Submodule.factor hn y) =
          Submodule.factor hm (AdicCompletion.transitionMap J P hmn y) := by
      intro y
      induction y using Quotient.inductionOn' with
      | _ p => rfl
    rw [← AdicCompletion.factor_eval_eq_evalₐ J x hn]
    rw [← AdicCompletion.factor_eval_eq_evalₐ J x hm]
    rw [hfac]
    exact congrArg (fun z => Submodule.factor hm z)
      (AdicCompletion.transitionMap_comp_eval_apply J P hmn x)
  let : TopologicalSpace A := I.adicTopology
  let B := iAdicOpenIdealBasis A I
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (AdicCompletion J P)
      π :=
        { app := fun i =>
            CommRingCat.ofHom
              ((e i.unop.down).toRingHom.comp
                (AdicCompletion.evalₐ J i.unop.down))
          naturality := by
            intro i j f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro x
            have hmn : j.unop.down ≤ i.unop.down := by
              exact CategoryTheory.le_of_op_hom f
            change
              e j.unop.down (AdicCompletion.evalₐ J j.unop.down x) =
              MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone
                      (CategoryTheory.le_of_op_hom f)))
                (e i.unop.down (AdicCompletion.evalₐ J i.unop.down x))
            have hh := congrArg
              (fun g : P ⧸ J ^ i.unop.down →+*
                  MvPolynomial (Fin r) (A ⧸ I ^ j.unop.down) =>
                g (AdicCompletion.evalₐ J i.unop.down x))
              (hcompat (m := j.unop.down) (n := i.unop.down) hmn)
            change
              MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone
                      (CategoryTheory.le_of_op_hom f)))
                (e i.unop.down (AdicCompletion.evalₐ J i.unop.down x)) =
              e j.unop.down
                (Ideal.Quotient.factorPow J hmn
                  (AdicCompletion.evalₐ J i.unop.down x)) at hh
            have hh' := hh
            rw [heval hmn x] at hh'
            exact hh'.symm } }
  let φ : AdicCompletion J P →+*
      iAdicRestrictedPowerSeries A I r :=
    (limit.lift D c).hom
  let p : ∀ n : ℕ,
      iAdicRestrictedPowerSeries A I r →+*
        MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n =>
    restrictedPowerSeriesProjection A B r (ULift.up n)
  let g : ∀ n : ℕ,
      iAdicRestrictedPowerSeries A I r →+* P ⧸ J ^ n := fun n =>
    (e n).symm.toRingHom.comp
      (p n)
  have hg : ∀ {m n : ℕ} (hmn : m ≤ n),
      (Ideal.Quotient.factorPow J hmn).comp (g n) = g m := by
    intro m n hmn
    apply RingHom.ext
    intro x
    apply (e m).injective
    have hlim := limit.w D
      ((homOfLE (show (ULift.up m : B.Index) ≤ ULift.up n by simpa using hmn)).op)
    have hlim' := congrArg (fun q => q.hom x) hlim
    change
      MvPolynomial.map
          (Ideal.Quotient.factor
            (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
              simpa using hmn)))
        (restrictedPowerSeriesProjection A B r (ULift.up n) x) =
      restrictedPowerSeriesProjection A B r (ULift.up m) x at hlim'
    have hlim'' :
        MvPolynomial.map
            (Ideal.Quotient.factor
              (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                simpa using hmn)))
          (p n x) = p m x := by
      change MvPolynomial.map
          (Ideal.Quotient.factor
            (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
              simpa using hmn)))
          (p n x) = p m x at hlim'
      exact hlim'
    have hh := congrArg
      (fun q : P ⧸ J ^ n →+* MvPolynomial (Fin r) (A ⧸ I ^ m) =>
        q ((e n).symm
          (p n x)))
      (hcompat hmn)
    have hh' :
        MvPolynomial.map
            (Ideal.Quotient.factor
              (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                simpa using hmn)))
          (p n x) =
          e m (Ideal.Quotient.factorPow J hmn ((e n).symm (p n x))) := by
      have heq :
          MvPolynomial.map
              (Ideal.Quotient.factor
                (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                  simpa using hmn)))
            (p n x) =
          MvPolynomial.map
              (Ideal.Quotient.factor
                (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                  simpa using hmn)))
            ((e n) ((e n).symm (p n x))) := by
        congr 1
        exact ((e n).apply_symm_apply _).symm
      change MvPolynomial.map
          (Ideal.Quotient.factor
            (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
              simpa using hmn)))
          ((e n) ((e n).symm (p n x))) =
        e m (Ideal.Quotient.factorPow J hmn ((e n).symm (p n x))) at hh
      exact heq.trans hh
    change e m (Ideal.Quotient.factorPow J hmn ((e n).symm (p n x))) =
      e m ((e m).symm (p m x))
    exact hh'.symm.trans (hlim''.trans ((e m).apply_symm_apply _).symm)
  let ψ : iAdicRestrictedPowerSeries A I r →+*
      AdicCompletion J P :=
    AdicCompletion.liftRingHom J g hg
  have hφ : ∀ (n : ℕ) (x : AdicCompletion J P),
      p n (φ x) =
        e n (AdicCompletion.evalₐ J n x) := by
    intro n x
    have hπ := limit.lift_π c (Opposite.op (ULift.up n))
    have hπ' := congrArg (fun q => q.hom x) hπ
    change
      p n (φ x) =
        e n (AdicCompletion.evalₐ J n x)
    exact hπ'
  have hψφ : ψ.comp φ = RingHom.id _ := by
    apply RingHom.ext
    intro x
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ J n (ψ (φ x)) =
      AdicCompletion.evalₐ J n x
    rw [AdicCompletion.evalₐ_liftRingHom]
    change (e n).symm
        (p n (φ x)) =
      AdicCompletion.evalₐ J n x
    simpa only [RingEquiv.symm_apply_apply] using congrArg (e n).symm (hφ n x)
  have hφψ : φ.comp ψ = RingHom.id _ := by
    have hD : IsLimit ((forget CommRingCat).mapCone (limit.cone D)) :=
      isLimitOfPreserves (forget CommRingCat) (limit.isLimit D)
    apply RingHom.ext
    intro x
    apply (Types.isLimitEquivSections hD).injective
    ext i
    cases i with
    | op i =>
      cases i with
      | up n =>
        have hπ := congrArg (fun q => q.hom (ψ x))
          (limit.lift_π c (Opposite.op (ULift.up n)))
        change
          p n (φ (ψ x)) =
            e n (AdicCompletion.evalₐ J n (ψ x)) at hπ
        change
          p n (φ (ψ x)) = p n x
        rw [hπ]
        rw [AdicCompletion.evalₐ_liftRingHom]
        change e n ((e n).symm
          (p n x)) = p n x
        exact (e n).apply_symm_apply _
  refine ⟨RingEquiv.ofBijective φ ?_⟩
  refine ⟨?_, ?_⟩
  · intro x y hxy
    calc
      x = (ψ.comp φ) x := by rw [hψφ]; rfl
      _ = (ψ.comp φ) y := congrArg ψ hxy
      _ = y := by rw [hψφ]; rfl
  · intro y
    exact ⟨ψ y, by
      change (φ.comp ψ) y = y
      rw [hφψ]
      rfl⟩

private theorem iAdicPolynomialCompletion_canonical_equiv_with_coordinates
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ)
    (_hA : IsAdicComplete I A) :
    ∃ (e : iAdicPolynomialCompletion A I r ≃+*
        iAdicRestrictedPowerSeries A I r),
      ∃ q : ∀ n : ℕ,
          (MvPolynomial (Fin r) A ⧸ (polynomialExtensionIdeal A I r) ^ n) ≃+*
            MvPolynomial (Fin r) (A ⧸ I ^ n),
        ∀ (n : ℕ) (x : iAdicPolynomialCompletion A I r),
          @restrictedPowerSeriesProjection A _ I.adicTopology
              (iAdicOpenIdealBasis A I) r (ULift.up n) (e x) =
            q n (AdicCompletion.evalₐ (polynomialExtensionIdeal A I r) n x) := by
  classical
  let P := MvPolynomial (Fin r) A
  let J := polynomialExtensionIdeal A I r
  have hpow : ∀ n : ℕ, J ^ n =
      Ideal.map (MvPolynomial.C : A →+* P) (I ^ n) := by
    intro n
    simp [J, polynomialExtensionIdeal, Ideal.map_pow]
  let q : ∀ n : ℕ, (P ⧸ J ^ n) ≃+*
      MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n =>
    ((MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).toRingEquiv.trans
      (Ideal.quotientEquivAlgOfEq P (hpow n).symm).toRingEquiv).symm
  let e : ∀ n : ℕ, (P ⧸ J ^ n) ≃+*
      MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n => q n
  have heC : ∀ (n : ℕ) (a : A),
      e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a)) =
        MvPolynomial.C (Ideal.Quotient.mk (I ^ n) a) := by
    intro n a
    apply (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).injective
    change (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n))
        (e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a))) = _
    simp [q, e, MvPolynomial.quotientEquivQuotientMvPolynomial,
      MvPolynomial.eval₂_C]
  have heX : ∀ (n : ℕ) (i : Fin r),
      e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i)) =
        MvPolynomial.X i := by
    intro n i
    apply (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).injective
    change (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n))
        (e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i))) = _
    simp [q, e, MvPolynomial.quotientEquivQuotientMvPolynomial,
      MvPolynomial.eval₂_X]
  have hcompat : ∀ {m n : ℕ} (hmn : m ≤ n),
      (MvPolynomial.map (Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn))).comp
          (e n).toRingHom =
        (e m).toRingHom.comp (Ideal.Quotient.factorPow J hmn) := by
    intro m n hmn
    apply RingHom.ext
    intro x
    obtain ⟨y, rfl⟩ := (e n).symm.surjective x
    apply MvPolynomial.induction_on y
    · intro a
      obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a
      have h_invC :
          (e n).symm (MvPolynomial.C (Ideal.Quotient.mk (I ^ n) a)) =
            Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a) := by
        rw [← heC n a]
        exact (e n).symm_apply_apply _
      rw [h_invC]
      simp [heC]
    · intro p q hp hq
      simpa only [map_add] using congrArg₂ (· + ·) hp hq
    · intro p i hp
      have hxi :
          ((MvPolynomial.map (Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn))).comp
            (e n).toRingHom) ((e n).symm (MvPolynomial.X i)) =
          ((e m).toRingHom.comp
            (Ideal.Quotient.factorPow J hmn)) ((e n).symm (MvPolynomial.X i)) := by
        have h_invX :
            (e n).symm (MvPolynomial.X i) =
              Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i) := by
          rw [← heX n i]
          exact (e n).symm_apply_apply _
        rw [h_invX]
        simp [heX]
      simpa only [map_mul] using congrArg₂ (· * ·) hp hxi
  have heval : ∀ {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion J P),
      Ideal.Quotient.factorPow J hmn (AdicCompletion.evalₐ J n x) =
        AdicCompletion.evalₐ J m x := by
    intro m n hmn x
    let hn : (J ^ n • ⊤ : Submodule P P) ≤ J ^ n :=
      le_of_eq (Ideal.mul_top _)
    let hm : (J ^ m • ⊤ : Submodule P P) ≤ J ^ m :=
      le_of_eq (Ideal.mul_top _)
    have hfac : ∀ (y : P ⧸ (J ^ n • ⊤ : Submodule P P)),
        Ideal.Quotient.factorPow J hmn (Submodule.factor hn y) =
          Submodule.factor hm (AdicCompletion.transitionMap J P hmn y) := by
      intro y
      induction y using Quotient.inductionOn' with
      | _ p => rfl
    rw [← AdicCompletion.factor_eval_eq_evalₐ J x hn]
    rw [← AdicCompletion.factor_eval_eq_evalₐ J x hm]
    rw [hfac]
    exact congrArg (fun z => Submodule.factor hm z)
      (AdicCompletion.transitionMap_comp_eval_apply J P hmn x)
  let : TopologicalSpace A := I.adicTopology
  let B := iAdicOpenIdealBasis A I
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (AdicCompletion J P)
      π :=
        { app := fun i =>
            CommRingCat.ofHom
              ((e i.unop.down).toRingHom.comp
                (AdicCompletion.evalₐ J i.unop.down))
          naturality := by
            intro i j f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro x
            have hmn : j.unop.down ≤ i.unop.down := by
              exact CategoryTheory.le_of_op_hom f
            change
              e j.unop.down (AdicCompletion.evalₐ J j.unop.down x) =
              MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone
                      (CategoryTheory.le_of_op_hom f)))
                (e i.unop.down (AdicCompletion.evalₐ J i.unop.down x))
            have hh := congrArg
              (fun g : P ⧸ J ^ i.unop.down →+*
                  MvPolynomial (Fin r) (A ⧸ I ^ j.unop.down) =>
                g (AdicCompletion.evalₐ J i.unop.down x))
              (hcompat (m := j.unop.down) (n := i.unop.down) hmn)
            change
              MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone
                      (CategoryTheory.le_of_op_hom f)))
                (e i.unop.down (AdicCompletion.evalₐ J i.unop.down x)) =
              e j.unop.down
                (Ideal.Quotient.factorPow J hmn
                  (AdicCompletion.evalₐ J i.unop.down x)) at hh
            have hh' := hh
            rw [heval hmn x] at hh'
            exact hh'.symm } }
  let φ : AdicCompletion J P →+*
      iAdicRestrictedPowerSeries A I r :=
    (limit.lift D c).hom
  let p : ∀ n : ℕ,
      iAdicRestrictedPowerSeries A I r →+*
        MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n =>
    restrictedPowerSeriesProjection A B r (ULift.up n)
  let g : ∀ n : ℕ,
      iAdicRestrictedPowerSeries A I r →+* P ⧸ J ^ n := fun n =>
    (e n).symm.toRingHom.comp
      (p n)
  have hg : ∀ {m n : ℕ} (hmn : m ≤ n),
      (Ideal.Quotient.factorPow J hmn).comp (g n) = g m := by
    intro m n hmn
    apply RingHom.ext
    intro x
    apply (e m).injective
    have hlim := limit.w D
      ((homOfLE (show (ULift.up m : B.Index) ≤ ULift.up n by simpa using hmn)).op)
    have hlim' := congrArg (fun q => q.hom x) hlim
    change
      MvPolynomial.map
          (Ideal.Quotient.factor
            (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
              simpa using hmn)))
        (restrictedPowerSeriesProjection A B r (ULift.up n) x) =
      restrictedPowerSeriesProjection A B r (ULift.up m) x at hlim'
    have hlim'' :
        MvPolynomial.map
            (Ideal.Quotient.factor
              (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                simpa using hmn)))
          (p n x) = p m x := by
      change MvPolynomial.map
          (Ideal.Quotient.factor
            (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
              simpa using hmn)))
          (p n x) = p m x at hlim'
      exact hlim'
    have hh := congrArg
      (fun q : P ⧸ J ^ n →+* MvPolynomial (Fin r) (A ⧸ I ^ m) =>
        q ((e n).symm (p n x)))
      (hcompat hmn)
    have hh' :
        MvPolynomial.map
            (Ideal.Quotient.factor
              (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                simpa using hmn)))
          (p n x) =
          e m (Ideal.Quotient.factorPow J hmn ((e n).symm (p n x))) := by
      have heq :
          MvPolynomial.map
              (Ideal.Quotient.factor
                (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                  simpa using hmn)))
            (p n x) =
          MvPolynomial.map
              (Ideal.Quotient.factor
                (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
                  simpa using hmn)))
            ((e n) ((e n).symm (p n x))) := by
        congr 1
        exact ((e n).apply_symm_apply _).symm
      change MvPolynomial.map
          (Ideal.Quotient.factor
            (B.antitone (show (ULift.up m : B.Index) ≤ ULift.up n by
              simpa using hmn)))
          ((e n) ((e n).symm (p n x))) =
        e m (Ideal.Quotient.factorPow J hmn ((e n).symm (p n x))) at hh
      exact heq.trans hh
    change e m (Ideal.Quotient.factorPow J hmn ((e n).symm (p n x))) =
      e m ((e m).symm (p m x))
    exact hh'.symm.trans (hlim''.trans ((e m).apply_symm_apply _).symm)
  let ψ : iAdicRestrictedPowerSeries A I r →+*
      AdicCompletion J P :=
    AdicCompletion.liftRingHom J g hg
  have hφ : ∀ (n : ℕ) (x : AdicCompletion J P),
      p n (φ x) = e n (AdicCompletion.evalₐ J n x) := by
    intro n x
    have hπ := limit.lift_π c (Opposite.op (ULift.up n))
    have hπ' := congrArg (fun q => q.hom x) hπ
    change p n (φ x) = e n (AdicCompletion.evalₐ J n x)
    exact hπ'
  have hψφ : ψ.comp φ = RingHom.id _ := by
    apply RingHom.ext
    intro x
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ J n (ψ (φ x)) = AdicCompletion.evalₐ J n x
    rw [AdicCompletion.evalₐ_liftRingHom]
    change (e n).symm (p n (φ x)) = AdicCompletion.evalₐ J n x
    simpa only [RingEquiv.symm_apply_apply] using congrArg (e n).symm (hφ n x)
  have hφψ : φ.comp ψ = RingHom.id _ := by
    have hD : IsLimit ((forget CommRingCat).mapCone (limit.cone D)) :=
      isLimitOfPreserves (forget CommRingCat) (limit.isLimit D)
    apply RingHom.ext
    intro x
    apply (Types.isLimitEquivSections hD).injective
    ext i
    cases i with
    | op i =>
      cases i with
      | up n =>
        have hπ := congrArg (fun q => q.hom (ψ x))
          (limit.lift_π c (Opposite.op (ULift.up n)))
        change p n (φ (ψ x)) = e n (AdicCompletion.evalₐ J n (ψ x)) at hπ
        change p n (φ (ψ x)) = p n x
        rw [hπ]
        rw [AdicCompletion.evalₐ_liftRingHom]
        change e n ((e n).symm (p n x)) = p n x
        exact (e n).apply_symm_apply _
  refine ⟨RingEquiv.ofBijective φ ?_, q, hφ⟩
  refine ⟨?_, ?_⟩
  · intro x y hxy
    calc
      x = (ψ.comp φ) x := by rw [hψφ]; rfl
      _ = (ψ.comp φ) y := congrArg ψ hxy
      _ = y := by rw [hψφ]; rfl
  · intro y
    exact ⟨ψ y, by
      change (φ.comp ψ) y = y
      rw [hφψ]
      rfl⟩

/-- The limit topology on the restricted power series side is always complete. -/
theorem iAdicRestrictedPowerSeries_complete_for_limit_topology
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ) :
    IsCompleteSeparatedTopologicalAddGroupFor
      (iAdicRestrictedPowerSeries A I r)
      (iAdicRestrictedPowerSeriesLimitTopology A I r) := by
  exact @restrictedPowerSeries_complete_for_limit_topology A _ I.adicTopology
    (iAdicOpenIdealBasis A I) r

/-- If the defining ideal is finitely generated, the polynomial completion is
complete for its I-adic topology.

Without finite generation the source only warns that completeness is not
automatic; it does not assert a counterexample with an I-adically complete
coefficient ring. -/
theorem iAdicPolynomialCompletion_iAdically_complete_of_fg
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ) (hI : I.FG) :
    IsAdicComplete (polynomialExtensionIdeal A I r)
      (iAdicPolynomialCompletion A I r) := by
  /-
  Proof roadmap.

  * Put `P := MvPolynomial (Fin r) A` and
    `J := polynomialExtensionIdeal A I r`.
  * Obtain `hJ : J.FG` from
    `hI.map (algebraMap A P)` in
    `Mathlib/RingTheory/Finiteness/Ideal.lean`; after unfolding
    `polynomialExtensionIdeal`, this is definitionally the required ideal.
  * The goal unfolds to `IsAdicComplete J (AdicCompletion J P)`.  Close it
    with `AdicCompletion.isAdicComplete hJ` from
    `Mathlib/RingTheory/AdicCompletion/Completeness.lean`.

  Do not use
  `Formalization.Books.MoreAlgebra.Unit36.adicCompletion_not_always_iAdically_complete`:
  that theorem quantifies over arbitrary modules `M` and supplies neither a
  polynomial module specialization nor an I-adically complete coefficient
  ring, so it cannot prove the former negative interface.
  -/
  sorry

/-- If the defining ideal is finitely generated, the ring identification is
also an identification of the I-adic and limit topologies. -/
theorem iAdicPolynomialCompletion_is_restrictedPowerSeries_as_topologicalRing_of_fg
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ)
    (hA : IsAdicComplete I A) (hI : I.FG) :
    ∃ e : iAdicPolynomialCompletion A I r ≃+*
        iAdicRestrictedPowerSeries A I r,
      (@Continuous (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletionTopology A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r) e) ∧
      (@Continuous (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r)
        (iAdicPolynomialCompletionTopology A I r) e.symm) := by
  classical
  let _ : TopologicalSpace A := I.adicTopology
  let P := MvPolynomial (Fin r) A
  let J := polynomialExtensionIdeal A I r
  let B := iAdicOpenIdealBasis A I
  obtain ⟨e, q, hcoord⟩ :=
    iAdicPolynomialCompletion_canonical_equiv_with_coordinates A I r hA
  have hJ : J.FG := by
    simpa [J, polynomialExtensionIdeal, P] using
      hI.map (algebraMap A P)
  have htop :
      iAdicPolynomialCompletionTopology A I r =
        AdicCompletionLimitTopology P J P := by
    simpa [iAdicPolynomialCompletionTopology, iAdicPolynomialCompletion, P, J,
      polynomialExtensionIdeal] using
      Formalization.Books.MoreAlgebra.Unit36.adicCompletion_iAdicTopology_eq_limitTopology_of_fg
        P J hJ P
  have hval : ∀ n : ℕ,
      @Continuous (AdicCompletion J P)
        (P ⧸ (J ^ n • (⊤ : Submodule P P)))
        (AdicCompletionLimitTopology P J P) ⊥
        (fun x : AdicCompletion J P => x.val n) := by
    intro n
    rw [continuous_iff_le_induced]
    exact iInf_le _ n
  have hφcont :
      @Continuous (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletionTopology A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r) e := by
    rw [htop]
    change @Continuous (AdicCompletion J P)
      (iAdicRestrictedPowerSeries A I r)
      (AdicCompletionLimitTopology P J P)
      (⨅ i : B.Indexᵒᵖ,
        TopologicalSpace.induced
          ((limit.π (restrictedPowerSeriesDiagram A B r) i).hom)
          (⊥ : TopologicalSpace
            (MvPolynomial (Fin r) (A ⧸ B.I i.unop)))) e
    rw [continuous_iInf_rng]
    intro i
    change (ULift ℕ)ᵒᵖ at i
    cases i with
    | op i =>
      cases i with
      | up n =>
        dsimp [B, iAdicOpenIdealBasis] at *
        let : TopologicalSpace (AdicCompletion J P) :=
          AdicCompletionLimitTopology P J P
        let : TopologicalSpace (P ⧸ (J ^ n • (⊤ : Submodule P P))) := ⊥
        let : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ I ^ n)) := ⊥
        change @Continuous (AdicCompletion J P)
          (iAdicRestrictedPowerSeries A I r)
          (AdicCompletionLimitTopology P J P)
          (TopologicalSpace.induced
            (restrictedPowerSeriesProjection A (iAdicOpenIdealBasis A I) r
              (ULift.up n)) ⊥) e
        refine continuous_induced_rng.mpr ?_
        have hn : (J ^ n • (⊤ : Submodule P P)) ≤ J ^ n :=
          le_of_eq (Ideal.mul_top _)
        have hqn : @Continuous
            (P ⧸ (J ^ n • (⊤ : Submodule P P)))
            (MvPolynomial (Fin r) (A ⧸ I ^ n)) ⊥ ⊥
            ((q n).toRingHom.comp
              (Ideal.Quotient.factor hn)) :=
          continuous_bot
        have hcomp := hqn.comp (hval n)
        have hcomp' :
            @Continuous (AdicCompletion J P)
              (MvPolynomial (Fin r) (A ⧸ I ^ n))
              (AdicCompletionLimitTopology P J P) ⊥
              (fun x : AdicCompletion J P =>
                q n (AdicCompletion.evalₐ J n x)) := by
          convert hcomp using 1
          funext x
          change q n (AdicCompletion.evalₐ J n x) =
            q n (Ideal.Quotient.factor hn (AdicCompletion.eval J P n x))
          exact congrArg (q n)
            (AdicCompletion.factor_eval_eq_evalₐ J x hn).symm
        convert hcomp' using 1
        · rfl
        · rfl
        · apply heq_of_eq
          funext x
          exact hcoord n x
  have hψcont :
      @Continuous (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r)
        (iAdicPolynomialCompletionTopology A I r) e.symm := by
    rw [htop]
    change @Continuous (iAdicRestrictedPowerSeries A I r)
      (AdicCompletion J P)
      (⨅ i : B.Indexᵒᵖ,
        TopologicalSpace.induced
          ((limit.π (restrictedPowerSeriesDiagram A B r) i).hom)
          (⊥ : TopologicalSpace
            (MvPolynomial (Fin r) (A ⧸ B.I i.unop))))
      (⨅ n : ℕ, TopologicalSpace.induced
        (fun x : AdicCompletion J P => x.val n)
        (⊥ : TopologicalSpace
          (P ⧸ (J ^ n • (⊤ : Submodule P P))))) e.symm
    rw [continuous_iInf_rng]
    intro n
    rw [continuous_induced_rng]
    dsimp [B, iAdicOpenIdealBasis] at *
    let : TopologicalSpace (iAdicRestrictedPowerSeries A I r) :=
      ⨅ i : B.Indexᵒᵖ,
        TopologicalSpace.induced
          ((limit.π (restrictedPowerSeriesDiagram A B r) i).hom)
          (⊥ : TopologicalSpace
            (MvPolynomial (Fin r) (A ⧸ B.I i.unop)))
    let : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ I ^ n)) := ⊥
    let : TopologicalSpace (P ⧸ (J ^ n • (⊤ : Submodule P P))) := ⊥
    have hpn : @Continuous (iAdicRestrictedPowerSeries A I r)
        (MvPolynomial (Fin r) (A ⧸ I ^ n))
        (⨅ i : B.Indexᵒᵖ,
          TopologicalSpace.induced
            ((limit.π (restrictedPowerSeriesDiagram A B r) i).hom)
            (⊥ : TopologicalSpace
              (MvPolynomial (Fin r) (A ⧸ B.I i.unop))))
        ⊥
        (restrictedPowerSeriesProjection A B r
          (ULift.up n)) := by
      refine continuous_iff_le_induced.mpr ?_
      exact iInf_le _ (Opposite.op (ULift.up n))
    have hEq : (J ^ n • (⊤ : Ideal P)) = J ^ n := by
      ext z
      simp [J]
    let v := (Ideal.quotientEquivAlgOfEq P hEq).toRingEquiv
    have hqn : @Continuous
        (MvPolynomial (Fin r) (A ⧸ I ^ n))
          (P ⧸ (J ^ n • (⊤ : Submodule P P))) ⊥ ⊥
          (v.symm.toRingHom.comp (q n).symm.toRingHom) :=
      continuous_bot
    have hcomp := hqn.comp hpn
    have hinvcoord :
        (fun y : iAdicRestrictedPowerSeries A I r =>
          (e.symm y).val n) =
          (fun y : iAdicRestrictedPowerSeries A I r =>
            v.symm
              ((q n).symm
                (restrictedPowerSeriesProjection A (iAdicOpenIdealBasis A I) r
                  (ULift.up n) y))) := by
      funext y
      have hh := congrArg (q n).symm (hcoord n (e.symm y))
      apply v.injective
      have hn : (J ^ n • (⊤ : Submodule P P)) ≤ J ^ n :=
        le_of_eq (Ideal.mul_top _)
      have hv := AdicCompletion.factor_eval_eq_evalₐ J (e.symm y) hn
      have hh' : AdicCompletion.evalₐ J n (e.symm y) =
          (q n).symm
            (restrictedPowerSeriesProjection A (iAdicOpenIdealBasis A I) r
              (ULift.up n) y) := by
        simpa [RingEquiv.symm_apply_apply, RingEquiv.apply_symm_apply,
          B, iAdicOpenIdealBasis] using hh.symm
      calc
        v ((e.symm y).val n) = AdicCompletion.evalₐ J n (e.symm y) := by
          change (Ideal.quotientEquivAlgOfEq P hEq)
              ((e.symm y).val n) = AdicCompletion.evalₐ J n (e.symm y)
          rfl
        _ = (q n).symm
              (restrictedPowerSeriesProjection A (iAdicOpenIdealBasis A I) r
                (ULift.up n) y) := hh'
        _ = v (v.symm ((q n).symm
              (restrictedPowerSeriesProjection A (iAdicOpenIdealBasis A I) r
                (ULift.up n) y))) := by
          rw [v.apply_symm_apply]
    change @Continuous (iAdicRestrictedPowerSeries A I r)
      (P ⧸ (J ^ n • (⊤ : Submodule P P))) _ _
      (fun y => (e.symm y).val n)
    rw [hinvcoord]
    exact hcomp
  exact ⟨e, hφcont, hψcont⟩

end

end Formalization.Books.FormalSpaces.Unit28
