import Formalization.Books.MoreAlgebra.Unit36.TopologicalRings
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Polynomial.Quotient

/-!
# Formal Algebraic Spaces, Chapter 28: Restricted power series

The source defines restricted power series as the inverse limit of the
polynomial rings over a fundamental system of open ideal quotients.  The
inverse system below is the corresponding Mathlib `CommRingCat` diagram.
The completion and topological statements are recorded as theorem interfaces;
the inverse-limit and coefficient conditions are concrete definitions.
-/

namespace Formalization.Books.FormalSpaces.Unit28

open CategoryTheory
open CategoryTheory.Limits
open Filter Set
open Formalization.Books.MoreAlgebra.Unit36

universe u v

noncomputable section

/-! ## The complete linearly topologized input -/

/-- A commutative topological ring complete and separated for a linear topology. -/
def IsCompleteLinearlyTopologizedRing (A : Type u) [CommRing A]
    [TopologicalSpace A] [IsTopologicalRing A] : Prop :=
  IsLinearTopology A A ∧ IsCompleteTopologicalAddGroup A

/-- A directed fundamental system of open ideals in a topological ring.

The antitone condition fixes the direction of the inverse system: if `i ≤ j`,
then the `j`-th quotient maps to the `i`-th quotient. -/
structure OpenIdealBasis (A : Type u) [CommRing A] [TopologicalSpace A] where
  Index : Type u
  [preorder : Preorder Index]
  I : Index → Ideal A
  directed : ∀ i j : Index, ∃ k : Index, i ≤ k ∧ j ≤ k
  antitone : Antitone I
  fundamental :
    (nhds (0 : A)).HasBasis (fun _ : Index => True)
      (fun i => (I i : Set A))
  isOpen : ∀ i, IsOpen (I i : Set A)

instance (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) : Preorder B.Index := B.preorder

/-- The ideal generated by an ideal of the coefficient ring in its polynomial
ring. -/
def polynomialExtensionIdeal (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Ideal (MvPolynomial (Fin r) A) :=
  Ideal.map (algebraMap A (MvPolynomial (Fin r) A)) I

/-- Quotienting coefficients commutes with forming the polynomial ring. -/
noncomputable def polynomialQuotientEquiv (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    MvPolynomial (Fin r) (A ⧸ I) ≃ₐ[A]
      (MvPolynomial (Fin r) A) ⧸ polynomialExtensionIdeal A I r :=
  MvPolynomial.quotientEquivQuotientMvPolynomial I

/-! ## The polynomial quotient inverse system and its limit -/

/-- The inverse-system term at `i` is the polynomial ring over `A ⧸ I i`. -/
def restrictedPowerSeriesDiagram (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    B.Indexᵒᵖ ⥤ CommRingCat.{u} where
  obj i := CommRingCat.of (MvPolynomial (Fin r) (A ⧸ B.I i.unop))
  map f :=
    CommRingCat.ofHom <|
      MvPolynomial.map
        (Ideal.Quotient.factor (B.antitone (CategoryTheory.le_of_op_hom f)))
  map_id i := by
    apply CommRingCat.hom_ext
    apply RingHom.ext
    intro p
    simp [Ideal.Quotient.factor_eq, MvPolynomial.map_id]
  map_comp f g := by
    apply CommRingCat.hom_ext
    apply RingHom.ext
    intro p
    simp [MvPolynomial.map_map, Ideal.Quotient.factor_comp]

/-- The restricted power series ring associated to an open ideal basis. -/
noncomputable abbrev restrictedPowerSeries (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) : Type u :=
  ((limit (restrictedPowerSeriesDiagram A B r) : CommRingCat.{u}) : Type u)

/-- The limit topology on the restricted power series ring.

Every quotient polynomial ring is given the discrete topology, and the limit
topology is the infimum of the topologies induced by the limit projections. -/
@[instance_reducible]
def restrictedPowerSeriesLimitTopology (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    TopologicalSpace (restrictedPowerSeries A B r) :=
  ⨅ i : B.Indexᵒᵖ, TopologicalSpace.induced
    ((limit.π (restrictedPowerSeriesDiagram A B r) i).hom)
    (⊥ : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ B.I i.unop)))

/-- The projection to one polynomial quotient in the inverse system. -/
noncomputable def restrictedPowerSeriesProjection (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) (i : B.Index) :
    restrictedPowerSeries A B r →+* MvPolynomial (Fin r) (A ⧸ B.I i) :=
  (limit.π (restrictedPowerSeriesDiagram A B r) (Opposite.op i)).hom

/-! ## Coefficients tending to zero -/

/-- A coefficient family is restricted when all but finitely many coefficients
are in every member of the chosen fundamental system. -/
def IsRestrictedCoefficientFamily (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ)
    (a : (Fin r →₀ ℕ) → A) : Prop :=
  ∀ i : B.Index, {E | a E ∉ B.I i}.Finite

/-- The coefficient of a limit element modulo one open ideal. -/
noncomputable def restrictedPowerSeriesCoefficient (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ)
    (_x : restrictedPowerSeries A B r) (i : B.Index) (E : Fin r →₀ ℕ) :
    A ⧸ B.I i :=
  MvPolynomial.coeff E (restrictedPowerSeriesProjection A B r i _x)

/-! ## The polynomial map into the completion -/

/-- The canonical map from the polynomial ring into the inverse limit. -/
noncomputable def restrictedPowerSeriesPolynomialMap (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    MvPolynomial (Fin r) A →+* restrictedPowerSeries A B r := by
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (MvPolynomial (Fin r) A)
      π :=
        { app := fun i =>
            CommRingCat.ofHom
              (MvPolynomial.map (Ideal.Quotient.mk (B.I i.unop)))
          naturality := by
            intro i j f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro p
            change
              MvPolynomial.map (Ideal.Quotient.mk (B.I j.unop)) p =
                MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone (CategoryTheory.le_of_op_hom f)))
                  (MvPolynomial.map (Ideal.Quotient.mk (B.I i.unop)) p)
            rw [MvPolynomial.map_map, Ideal.Quotient.factor_comp_mk] } }
  exact ((limit.isLimit D).lift c).hom

@[simp]
theorem restrictedPowerSeriesProjection_polynomialMap
    (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) (r : ℕ) (i : B.Index)
    (p : MvPolynomial (Fin r) A) :
    restrictedPowerSeriesProjection A B r i
        (restrictedPowerSeriesPolynomialMap A B r p) =
      MvPolynomial.map (Ideal.Quotient.mk (B.I i)) p := by
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (MvPolynomial (Fin r) A)
      π :=
        { app := fun j =>
            CommRingCat.ofHom
              (MvPolynomial.map (Ideal.Quotient.mk (B.I j.unop)))
          naturality := by
            intro j k f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro q
            change
              MvPolynomial.map (Ideal.Quotient.mk (B.I k.unop)) q =
                MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone (CategoryTheory.le_of_op_hom f)))
                  (MvPolynomial.map (Ideal.Quotient.mk (B.I j.unop)) q)
            rw [MvPolynomial.map_map, Ideal.Quotient.factor_comp_mk] } }
  have h := limit.lift_π c (Opposite.op i)
  have h' := congrArg (fun g => g.hom p) h
  change ((limit.lift D c ≫ limit.π D (Opposite.op i)).hom p) =
    (MvPolynomial.map (Ideal.Quotient.mk (B.I i))) p
  exact h'

/-! ## Assertions in the source -/

/-- The coefficient description of restricted power series.

For a complete separated input, every compatible limit element has a unique
coefficient family whose coefficients tend to zero, and whose reductions are
the coefficients of all quotient polynomials. -/
theorem restrictedPowerSeries_exists_unique_coefficients
    (A : Type u) [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (hA : IsCompleteLinearlyTopologizedRing A)
    (B : OpenIdealBasis A) (r : ℕ)
    (x : restrictedPowerSeries A B r) :
    ∃! a : (Fin r →₀ ℕ) → A,
      IsRestrictedCoefficientFamily A B r a ∧
        ∀ (i : B.Index) (E : Fin r →₀ ℕ),
          Ideal.Quotient.mk (B.I i) (a E) =
            restrictedPowerSeriesCoefficient A B r x i E := by
  classical
  let q : ∀ i : B.Index, (Fin r →₀ ℕ) → A ⧸ B.I i := fun i =>
    fun E => restrictedPowerSeriesCoefficient A B r x i E
  have hq : ∀ (i j : B.Index) (hij : i ≤ j) (E : Fin r →₀ ℕ),
      Ideal.Quotient.factor (B.antitone hij) (q j E) = q i E := by
    intro i j hij E
    have hlim := limit.w (restrictedPowerSeriesDiagram A B r) ((homOfLE hij).op)
    have hlim' := congrArg (fun q => q.hom x) hlim
    have hlim2 := hlim'
    change (MvPolynomial.map (Ideal.Quotient.factor (B.antitone hij)))
        (restrictedPowerSeriesProjection A B r j x) =
      restrictedPowerSeriesProjection A B r i x at hlim2
    have hcoeff := congrArg (fun p => MvPolynomial.coeff E p) hlim2
    rw [MvPolynomial.coeff_map] at hcoeff
    simpa [q, restrictedPowerSeriesCoefficient] using hcoeff
  have hIndex : Nonempty B.Index := by
    rcases B.fundamental.mem_iff.mp (univ_mem : (Set.univ : Set A) ∈ nhds 0) with
      ⟨i, -, hi⟩
    exact ⟨i⟩
  have hupper : ∀ (s : Set B.Index), s.Finite → ∃ k, ∀ i ∈ s, i ≤ k := by
    intro s hs
    induction s, hs using Set.Finite.induction_on with
    | empty =>
        exact ⟨Classical.choice hIndex, by simp⟩
    | @insert a s ha hs ih =>
        obtain ⟨k, hk⟩ := ih
        obtain ⟨l, hal, hkl⟩ := B.directed a k
        refine ⟨l, ?_⟩
        intro i hi
        rcases Set.mem_insert_iff.mp hi with rfl | hi
        · exact hal
        · exact (hk i hi).trans hkl
  have hfinite : ∀ (E : Fin r →₀ ℕ) (s : Set B.Index), s.Finite →
      (⋂ i ∈ s, (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}).Nonempty := by
    intro E s hs
    obtain ⟨k, hk⟩ := hupper s hs
    obtain ⟨a, ha⟩ := Ideal.Quotient.mk_surjective (q k E)
    refine ⟨a, ?_⟩
    simp only [Set.mem_iInter]
    intro i hi
    change Ideal.Quotient.mk (B.I i) a = q i E
    rw [← hq i k (hk i hi) E, ← ha]
    have hmk := congrArg (fun f : A →+* A ⧸ B.I i => f a)
      (Ideal.Quotient.factor_comp_mk (B.antitone (hk i hi)))
    exact hmk.symm
  have hAE : ∀ E : Fin r →₀ ℕ, ∃ a : A, ∀ i : B.Index,
      Ideal.Quotient.mk (B.I i) a = q i E := by
    intro E
    let F : Filter A := ⨅ i : B.Index,
      Filter.principal ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E})
    have hF : NeBot F := by
      change NeBot (⨅ i : B.Index,
        Filter.principal ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}))
      apply (Filter.hasBasis_iInf_principal_finite
        (fun i : B.Index => (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E})).neBot_iff.mpr
      intro s hs
      exact hfinite E s hs
    letI : UniformSpace A := IsTopologicalAddGroup.rightUniformSpace A
    letI : IsUniformAddGroup A := isUniformAddGroup_of_addCommGroup
    letI : CompleteSpace A := hA.2.1
    have hC : Cauchy F := by
      refine (IsUniformAddGroup.cauchy_iff_tendsto F).2 ⟨hF, ?_⟩
      refine (B.fundamental.tendsto_right_iff).2 ?_
      intro i hi
      have hmem : (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈ F := by
        change (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈
          (⨅ j : B.Index, Filter.principal
            ((Ideal.Quotient.mk (B.I j)) ⁻¹' {q j E}))
        exact mem_iInf_of_mem i (by simp)
      have hprod :
          ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}) ×ˢ
            ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}) ∈ F ×ˢ F := by
        exact prod_mem_prod hmem hmem
      filter_upwards [hprod] with p hp
      rcases hp with ⟨hp₁, hp₂⟩
      apply Ideal.Quotient.eq_zero_iff_mem.mp
      rw [map_sub, hp₂, hp₁, sub_self]
    letI : NeBot F := hF
    obtain ⟨a, ha⟩ := (cauchy_iff_exists_le_nhds (l := F)).mp hC
    refine ⟨a, ?_⟩
    intro i
    have hmem : (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈ F := by
      change (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} ∈
        (⨅ j : B.Index, Filter.principal
          ((Ideal.Quotient.mk (B.I j)) ⁻¹' {q j E}))
      exact mem_iInf_of_mem i (by simp)
    have hclosed : IsClosed ((Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E}) := by
      have hIclosed : IsClosed (B.I i : Set A) :=
        AddSubgroup.isClosed_of_isOpen (B.I i).toAddSubgroup (B.isOpen i)
      letI : IsClosed ((B.I i).toAddSubgroup : Set A) := hIclosed
      exact isClosed_singleton.preimage QuotientAddGroup.continuous_mk
    have ha' : a ∈ (Ideal.Quotient.mk (B.I i)) ⁻¹' {q i E} :=
      hclosed.mem_of_tendsto (f := id) (b := F) ha hmem
    exact ha'
  choose a ha using hAE
  have hcoef : ∀ (i : B.Index) (E : Fin r →₀ ℕ),
      Ideal.Quotient.mk (B.I i) (a E) =
        restrictedPowerSeriesCoefficient A B r x i E := by
    intro i E
    exact ha E i
  have hrestricted : IsRestrictedCoefficientFamily A B r a := by
    intro i
    let p := restrictedPowerSeriesProjection A B r i x
    apply p.support.finite_toSet.subset
    intro E hE
    apply MvPolynomial.mem_support_iff.mpr
    intro hzero
    apply hE
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    rw [hcoef i E]
    simpa [restrictedPowerSeriesCoefficient, p] using hzero
  refine ⟨a, ⟨hrestricted, hcoef⟩, ?_⟩
  intro b hb
  letI : T2Space A := hA.2.2
  have hzero : ∀ z : A, (∀ i : B.Index, z ∈ B.I i) → z = 0 := by
    intro z hz
    by_contra hne
    have hcomp : ({z} : Set A)ᶜ ∈ nhds (0 : A) := by
      apply isClosed_singleton.isOpen_compl.mem_nhds
      exact Ne.symm hne
    rcases B.fundamental.mem_iff.mp hcomp with ⟨i, -, hi⟩
    exact (by simpa [hne] using hi (hz i))
  funext E
  apply sub_eq_zero.mp
  apply hzero (b E - a E)
  intro i
  apply Ideal.Quotient.eq_zero_iff_mem.mp
  rw [map_sub, hb.2 i E, hcoef i E, sub_self]

/-- The inverse-limit topology is complete and separated. -/
theorem restrictedPowerSeries_complete_for_limit_topology
    (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) (r : ℕ) :
    IsCompleteSeparatedTopologicalAddGroupFor
      (restrictedPowerSeries A B r)
      (restrictedPowerSeriesLimitTopology A B r) := by
  classical
  let D := restrictedPowerSeriesDiagram A B r
  let M := restrictedPowerSeries A B r
  let Q : B.Indexᵒᵖ → Type u := fun i => D.obj i
  let g : M →+ ∀ i : B.Indexᵒᵖ, Q i :=
    { toFun := fun x i => (limit.π D i).hom x
      map_zero' := by
        ext i
        exact map_zero _
      map_add' := by
        intro x y
        ext i
        exact map_add _ _ _ }
  letI : ∀ i : B.Indexᵒᵖ, TopologicalSpace (Q i) := fun _ => ⊥
  letI : ∀ i : B.Indexᵒᵖ, UniformSpace (Q i) := fun _ => ⊥
  letI : ∀ i : B.Indexᵒᵖ, DiscreteTopology (Q i) :=
    fun _ => discreteTopology_bot _
  let u : UniformSpace M := UniformSpace.comap g (inferInstance : UniformSpace (∀ i, Q i))
  letI : UniformSpace M := u
  have hu : IsUniformAddGroup M := by
    refine ⟨?_⟩
    apply uniformContinuous_comap' (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))
    convert
      (uniformContinuous_sub.comp
        (((uniformContinuous_comap (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))).comp
            uniformContinuous_fst).prodMk
          ((uniformContinuous_comap (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))).comp
            uniformContinuous_snd))) using 1
    ext p
    simp [Function.comp_def]
  letI : IsUniformAddGroup M := hu
  have htop : u.toTopologicalSpace = restrictedPowerSeriesLimitTopology A B r := by
    change TopologicalSpace.induced g Pi.topologicalSpace = _
    rw [induced_to_pi]
    rfl
  have hD : IsLimit ((forget CommRingCat).mapCone (limit.cone D)) :=
    isLimitOfPreserves (forget CommRingCat) (limit.isLimit D)
  have hinj : Function.Injective g := by
    intro x y hxy
    apply (Types.isLimitEquivSections hD).injective
    ext i
    exact congrFun hxy i
  let S : Set (∀ i : B.Indexᵒᵖ, Q i) :=
    ⋂ (i : B.Indexᵒᵖ) (j : B.Indexᵒᵖ) (f : i ⟶ j),
      {z | (D.map f).hom (z i) = z j}
  have hgrange : Set.range g = S := by
    ext z
    constructor
    · rintro ⟨x, rfl⟩
      simp only [S, Set.mem_iInter]
      intro i j f
      exact congrArg (fun q => q.hom x) (limit.w D f)
    · intro hz
      simp only [S, Set.mem_iInter] at hz
      have hz' : ∀ (i j : B.Indexᵒᵖ) (f : i ⟶ j),
          (D.map f).hom (z i) = z j := by
        intro i j f
        exact hz i j f
      let c : Cone (D ⋙ forget CommRingCat) :=
        { pt := PUnit.{u + 1}
          π := { app := fun i => TypeCat.ofHom (fun _ : PUnit.{u + 1} => z i)
                 naturality := by
                   intro i j f
                   ext x
                   exact (hz' i j f).symm } }
      refine ⟨hD.lift c (PUnit.unit : PUnit.{u + 1}), ?_⟩
      funext i
      simpa [g, c] using congrArg (fun q => q (PUnit.unit : PUnit.{u + 1})) (hD.fac c i)
  have hSclosed : IsClosed S := by
    apply isClosed_iInter
    intro i
    apply isClosed_iInter
    intro j
    apply isClosed_iInter
    intro f
    letI : ∀ i : B.Indexᵒᵖ, T2Space (D.obj i) := fun _ => by
      infer_instance
    apply isClosed_eq
    · exact (continuous_of_discreteTopology :
        Continuous ((D.map f).hom : Q i → Q j)).comp (continuous_apply i)
    · exact continuous_apply j
  have hprod : CompleteSpace (∀ i : B.Indexᵒᵖ, Q i) := by
    infer_instance
  letI : CompleteSpace (∀ i : B.Indexᵒᵖ, Q i) := hprod
  have hrange : IsComplete (Set.range g) := by
    rw [hgrange]
    exact hSclosed.isComplete
  have hcomplete : @CompleteSpace M u :=
    (completeSpace_iff_isComplete_range ⟨rfl⟩).2 hrange
  letI : TopologicalSpace M := u.toTopologicalSpace
  have hT2 : @T2Space M (restrictedPowerSeriesLimitTopology A B r) := by
    rw [← htop]
    exact T2Space.of_injective_continuous hinj
      (uniformContinuous_comap (f := (g : M → ∀ i : B.Indexᵒᵖ, Q i))).continuous
  refine ⟨u, htop, hu, hcomplete, hT2⟩

/-- The universal property: an algebra map from the polynomial ring to a
complete linearly topologized target extends uniquely to a continuous ring map
on restricted power series. -/
theorem restrictedPowerSeries_universal_property
    (A C : Type u) [CommRing A] [CommRing C]
    [Algebra A C]
    [TopologicalSpace A] [TopologicalSpace C]
    [IsTopologicalRing A] [IsTopologicalRing C]
    (hA : IsCompleteLinearlyTopologizedRing A)
    (hC : IsCompleteLinearlyTopologizedRing C)
    (hAC : Continuous (algebraMap A C))
    (B : OpenIdealBasis A) (r : ℕ)
    (f : MvPolynomial (Fin r) A →ₐ[A] C) :
    ∃! F : restrictedPowerSeries A B r →+* C,
      (@Continuous (restrictedPowerSeries A B r) C
        (restrictedPowerSeriesLimitTopology A B r) inferInstance F) ∧
        F.comp (restrictedPowerSeriesPolynomialMap A B r) = f.toRingHom := by
  sorry

/-! ## The I-adic comparison and its warnings -/

/-- The canonical I-adic completion of the polynomial ring. -/
noncomputable abbrev iAdicPolynomialCompletion (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Type u :=
  AdicCompletion (polynomialExtensionIdeal A I r) (MvPolynomial (Fin r) A)

/-- The I-adic topology on the polynomial completion. -/
@[instance_reducible]
def iAdicPolynomialCompletionTopology (A : Type u) [CommRing A]
  (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicPolynomialCompletion A I r) :=
  IAdicModuleTopology
    (MvPolynomial (Fin r) A) (polynomialExtensionIdeal A I r)
    (iAdicPolynomialCompletion A I r)

/-- The chosen I-adic open-ideal basis on `A`. -/
def iAdicOpenIdealBasis (A : Type u) [CommRing A] (I : Ideal A) :
    @OpenIdealBasis A _ I.adicTopology :=
  letI : TopologicalSpace A := I.adicTopology
  { Index := ULift.{u} ℕ
    I := fun n => I ^ n.down
    directed := fun m n =>
      ⟨ULift.up (max m.down n.down), by
        simp, by
        simp⟩
    antitone := fun m n hmn => by
      apply Ideal.pow_le_pow_right
      exact hmn
    fundamental := by
      simpa [Function.comp_def] using
        (I.hasBasis_nhds_zero_adic.comp_equiv
          (Equiv.ulift : ULift.{u} ℕ ≃ ℕ))
    isOpen := fun n => by
      have hmem : ((I ^ n.down : Ideal A) : Set A) ∈
          @nhds A I.adicTopology (0 : A) := by
        exact I.hasBasis_nhds_zero_adic.mem_iff.mpr
          ⟨n.down, trivial, Subset.rfl⟩
      exact (I ^ n.down).toAddSubgroup.isOpen_of_mem_nhds hmem }

/-- The inverse-limit topology on the I-adic completion. -/
@[instance_reducible]
def iAdicPolynomialCompletionLimitTopology (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicPolynomialCompletion A I r) :=
  AdicCompletionLimitTopology
    (MvPolynomial (Fin r) A) (polynomialExtensionIdeal A I r)
    (MvPolynomial (Fin r) A)

/-- The I-adic specialization of the restricted power series type, with the
adic topology on the coefficient ring made explicit. -/
noncomputable abbrev iAdicRestrictedPowerSeries (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Type u :=
  @restrictedPowerSeries A _ I.adicTopology (iAdicOpenIdealBasis A I) r

@[instance_reducible]
def iAdicRestrictedPowerSeriesLimitTopology (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicRestrictedPowerSeries A I r) :=
  @restrictedPowerSeriesLimitTopology A _ I.adicTopology
    (iAdicOpenIdealBasis A I) r

/-- In the I-adically complete case, the I-adic completion of the polynomial
ring is the restricted power series ring as a ring. -/
theorem iAdicPolynomialCompletion_is_restrictedPowerSeries_as_ring
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ)
    (hA : IsAdicComplete I A) :
    Nonempty
      (iAdicPolynomialCompletion A I r ≃+*
        iAdicRestrictedPowerSeries A I r) := by
  classical
  let P := MvPolynomial (Fin r) A
  let J := polynomialExtensionIdeal A I r
  have hpow : ∀ n : ℕ, J ^ n =
      Ideal.map (MvPolynomial.C : A →+* P) (I ^ n) := by
    intro n
    simp [J, polynomialExtensionIdeal, Ideal.map_pow]
  let q : ∀ n : ℕ, (P ⧸ J ^ n) ≃+*
      MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n =>
    ((MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).toRingEquiv.trans
      (Ideal.quotientEquivAlgOfEq P (hpow n).symm).toRingEquiv).symm
  let e : ∀ n : ℕ, (P ⧸ J ^ n) ≃+*
      MvPolynomial (Fin r) (A ⧸ I ^ n) := fun n => q n
  have heC : ∀ (n : ℕ) (a : A),
      e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a)) =
        MvPolynomial.C (Ideal.Quotient.mk (I ^ n) a) := by
    intro n a
    apply (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).injective
    change (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n))
        (e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a))) = _
    simp [q, e, MvPolynomial.quotientEquivQuotientMvPolynomial,
      MvPolynomial.eval₂_C]
  have heX : ∀ (n : ℕ) (i : Fin r),
      e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i)) =
        MvPolynomial.X i := by
    intro n i
    apply (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n)).injective
    change (MvPolynomial.quotientEquivQuotientMvPolynomial (I ^ n))
        (e n (Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i))) = _
    simp [q, e, MvPolynomial.quotientEquivQuotientMvPolynomial,
      MvPolynomial.eval₂_X]
  have hcompat : ∀ {m n : ℕ} (hmn : m ≤ n),
      (MvPolynomial.map (Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn))).comp
          (e n).toRingHom =
        (e m).toRingHom.comp (Ideal.Quotient.factorPow J hmn) := by
    intro m n hmn
    apply RingHom.ext
    intro x
    obtain ⟨y, rfl⟩ := (e n).symm.surjective x
    apply MvPolynomial.induction_on y
    · intro a
      obtain ⟨a, rfl⟩ := Ideal.Quotient.mk_surjective a
      have h_invC :
          (e n).symm (MvPolynomial.C (Ideal.Quotient.mk (I ^ n) a)) =
            Ideal.Quotient.mk (J ^ n) (MvPolynomial.C a) := by
        rw [← heC n a]
        exact (e n).symm_apply_apply _
      rw [h_invC]
      simp [heC]
    · intro p q hp hq
      simpa only [map_add] using congrArg₂ (· + ·) hp hq
    · intro p i hp
      have hxi :
          ((MvPolynomial.map (Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn))).comp
            (e n).toRingHom) ((e n).symm (MvPolynomial.X i)) =
          ((e m).toRingHom.comp
            (Ideal.Quotient.factorPow J hmn)) ((e n).symm (MvPolynomial.X i)) := by
        have h_invX :
            (e n).symm (MvPolynomial.X i) =
              Ideal.Quotient.mk (J ^ n) (MvPolynomial.X i) := by
          rw [← heX n i]
          exact (e n).symm_apply_apply _
        rw [h_invX]
        simp [heX]
      simpa only [map_mul] using congrArg₂ (· * ·) hp hxi
  have heval : ∀ {m n : ℕ} (hmn : m ≤ n)
      (x : AdicCompletion J P),
      Ideal.Quotient.factorPow J hmn (AdicCompletion.evalₐ J n x) =
        AdicCompletion.evalₐ J m x := by
    intro m n hmn x
    let hn : (J ^ n • ⊤ : Submodule P P) ≤ J ^ n :=
      le_of_eq (Ideal.mul_top _)
    let hm : (J ^ m • ⊤ : Submodule P P) ≤ J ^ m :=
      le_of_eq (Ideal.mul_top _)
    have hfac : ∀ (y : P ⧸ (J ^ n • ⊤ : Submodule P P)),
        Ideal.Quotient.factorPow J hmn (Submodule.factor hn y) =
          Submodule.factor hm (AdicCompletion.transitionMap J P hmn y) := by
      intro y
      induction y using Quotient.inductionOn' with
      | _ p => rfl
    rw [← AdicCompletion.factor_eval_eq_evalₐ J x hn]
    rw [← AdicCompletion.factor_eval_eq_evalₐ J x hm]
    rw [hfac]
    exact congrArg (fun z => Submodule.factor hm z)
      (AdicCompletion.transitionMap_comp_eval_apply J P hmn x)
  letI : TopologicalSpace A := I.adicTopology
  let B := iAdicOpenIdealBasis A I
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (AdicCompletion J P)
      π :=
        { app := fun i =>
            CommRingCat.ofHom
              ((e i.unop.down).toRingHom.comp
                (AdicCompletion.evalₐ J i.unop.down))
          naturality := by
            intro i j f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro x
            have hmn : j.unop.down ≤ i.unop.down := by
              exact CategoryTheory.le_of_op_hom f
            change
              e j.unop.down (AdicCompletion.evalₐ J j.unop.down x) =
              MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone
                      (CategoryTheory.le_of_op_hom f)))
                (e i.unop.down (AdicCompletion.evalₐ J i.unop.down x))
            have hh := congrArg
              (fun g : P ⧸ J ^ i.unop.down →+*
                  MvPolynomial (Fin r) (A ⧸ I ^ j.unop.down) =>
                g (AdicCompletion.evalₐ J i.unop.down x))
              (hcompat (m := j.unop.down) (n := i.unop.down) hmn)
            change
              MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone
                      (CategoryTheory.le_of_op_hom f)))
                (e i.unop.down (AdicCompletion.evalₐ J i.unop.down x)) =
              e j.unop.down
                (Ideal.Quotient.factorPow J hmn
                  (AdicCompletion.evalₐ J i.unop.down x)) at hh
            have hh' := hh
            rw [heval hmn x] at hh'
            exact hh'.symm } }
  let φ : AdicCompletion J P →+*
      iAdicRestrictedPowerSeries A I r :=
    (limit.lift D c).hom
  sorry

/-- The limit topology on the restricted power series side is always complete. -/
theorem iAdicRestrictedPowerSeries_complete_for_limit_topology
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ) :
    IsCompleteSeparatedTopologicalAddGroupFor
      (iAdicRestrictedPowerSeries A I r)
      (iAdicRestrictedPowerSeriesLimitTopology A I r) := by
  exact @restrictedPowerSeries_complete_for_limit_topology A _ I.adicTopology
    (iAdicOpenIdealBasis A I) r

/-- The I-adic topology on the polynomial completion need not be complete. -/
theorem iAdicPolynomialCompletion_not_always_iAdically_complete :
    ¬ ∀ (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ),
      IsAdicComplete I A →
        IsAdicComplete (polynomialExtensionIdeal A I r)
          (iAdicPolynomialCompletion A I r) := by
  sorry

/-- If the defining ideal is finitely generated, the ring identification is
also an identification of the I-adic and limit topologies. -/
theorem iAdicPolynomialCompletion_is_restrictedPowerSeries_as_topologicalRing_of_fg
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ)
    (hA : IsAdicComplete I A) (hI : I.FG) :
    ∃ e : iAdicPolynomialCompletion A I r ≃+*
        iAdicRestrictedPowerSeries A I r,
      (@Continuous (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletionTopology A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r) e) ∧
      (@Continuous (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r)
        (iAdicPolynomialCompletionTopology A I r) e.symm) := by
  sorry

end

end Formalization.Books.FormalSpaces.Unit28
