import Formalization.Books.MoreAlgebra.Unit36.TopologicalRings
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Polynomial.Quotient

/-!
# Formal Algebraic Spaces, Chapter 28: Restricted power series

The source defines restricted power series as the inverse limit of the
polynomial rings over a fundamental system of open ideal quotients.  The
inverse system below is the corresponding Mathlib `CommRingCat` diagram.
The completion and topological statements are recorded as theorem interfaces;
the inverse-limit and coefficient conditions are concrete definitions.
-/

namespace Formalization.Books.FormalSpaces.Unit28

open CategoryTheory
open CategoryTheory.Limits
open Filter Set
open Formalization.Books.MoreAlgebra.Unit36

universe u v

noncomputable section

/-! ## The complete linearly topologized input -/

/-- A commutative topological ring complete and separated for a linear topology. -/
def IsCompleteLinearlyTopologizedRing (A : Type u) [CommRing A]
    [TopologicalSpace A] [IsTopologicalRing A] : Prop :=
  IsLinearTopology A A ∧ IsCompleteTopologicalAddGroup A

/-- A directed fundamental system of open ideals in a topological ring.

The antitone condition fixes the direction of the inverse system: if `i ≤ j`,
then the `j`-th quotient maps to the `i`-th quotient. -/
structure OpenIdealBasis (A : Type u) [CommRing A] [TopologicalSpace A] where
  Index : Type u
  [preorder : Preorder Index]
  I : Index → Ideal A
  directed : ∀ i j : Index, ∃ k : Index, i ≤ k ∧ j ≤ k
  antitone : Antitone I
  fundamental :
    (nhds (0 : A)).HasBasis (fun _ : Index => True)
      (fun i => (I i : Set A))
  isOpen : ∀ i, IsOpen (I i : Set A)

instance (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) : Preorder B.Index := B.preorder

/-- The ideal generated by an ideal of the coefficient ring in its polynomial
ring. -/
def polynomialExtensionIdeal (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Ideal (MvPolynomial (Fin r) A) :=
  Ideal.map (algebraMap A (MvPolynomial (Fin r) A)) I

/-- Quotienting coefficients commutes with forming the polynomial ring. -/
noncomputable def polynomialQuotientEquiv (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    MvPolynomial (Fin r) (A ⧸ I) ≃ₐ[A]
      (MvPolynomial (Fin r) A) ⧸ polynomialExtensionIdeal A I r :=
  MvPolynomial.quotientEquivQuotientMvPolynomial I

/-! ## The polynomial quotient inverse system and its limit -/

/-- The inverse-system term at `i` is the polynomial ring over `A ⧸ I i`. -/
def restrictedPowerSeriesDiagram (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    B.Indexᵒᵖ ⥤ CommRingCat.{u} where
  obj i := CommRingCat.of (MvPolynomial (Fin r) (A ⧸ B.I i.unop))
  map f :=
    CommRingCat.ofHom <|
      MvPolynomial.map
        (Ideal.Quotient.factor (B.antitone (CategoryTheory.le_of_op_hom f)))
  map_id i := by
    apply CommRingCat.hom_ext
    apply RingHom.ext
    intro p
    simp [Ideal.Quotient.factor_eq, MvPolynomial.map_id]
  map_comp f g := by
    apply CommRingCat.hom_ext
    apply RingHom.ext
    intro p
    simp [MvPolynomial.map_map, Ideal.Quotient.factor_comp]

/-- The restricted power series ring associated to an open ideal basis. -/
noncomputable abbrev restrictedPowerSeries (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) : Type u :=
  ((limit (restrictedPowerSeriesDiagram A B r) : CommRingCat.{u}) : Type u)

/-- The limit topology on the restricted power series ring.

Every quotient polynomial ring is given the discrete topology, and the limit
topology is the infimum of the topologies induced by the limit projections. -/
@[instance_reducible]
def restrictedPowerSeriesLimitTopology (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    TopologicalSpace (restrictedPowerSeries A B r) :=
  ⨅ i : B.Indexᵒᵖ, TopologicalSpace.induced
    ((limit.π (restrictedPowerSeriesDiagram A B r) i).hom)
    (⊥ : TopologicalSpace (MvPolynomial (Fin r) (A ⧸ B.I i.unop)))

/-- The projection to one polynomial quotient in the inverse system. -/
noncomputable def restrictedPowerSeriesProjection (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) (i : B.Index) :
    restrictedPowerSeries A B r →+* MvPolynomial (Fin r) (A ⧸ B.I i) :=
  (limit.π (restrictedPowerSeriesDiagram A B r) (Opposite.op i)).hom

/-! ## Coefficients tending to zero -/

/-- A coefficient family is restricted when all but finitely many coefficients
are in every member of the chosen fundamental system. -/
def IsRestrictedCoefficientFamily (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ)
    (a : (Fin r →₀ ℕ) → A) : Prop :=
  ∀ i : B.Index, {E | a E ∉ B.I i}.Finite

/-- The coefficient of a limit element modulo one open ideal. -/
noncomputable def restrictedPowerSeriesCoefficient (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ)
    (_x : restrictedPowerSeries A B r) (i : B.Index) (E : Fin r →₀ ℕ) :
    A ⧸ B.I i :=
  MvPolynomial.coeff E (restrictedPowerSeriesProjection A B r i _x)

/-! ## The polynomial map into the completion -/

/-- The canonical map from the polynomial ring into the inverse limit. -/
noncomputable def restrictedPowerSeriesPolynomialMap (A : Type u) [CommRing A]
    [TopologicalSpace A] (B : OpenIdealBasis A) (r : ℕ) :
    MvPolynomial (Fin r) A →+* restrictedPowerSeries A B r := by
  let D := restrictedPowerSeriesDiagram A B r
  let c : Cone D :=
    { pt := CommRingCat.of (MvPolynomial (Fin r) A)
      π :=
        { app := fun i =>
            CommRingCat.ofHom
              (MvPolynomial.map (Ideal.Quotient.mk (B.I i.unop)))
          naturality := by
            intro i j f
            apply CommRingCat.hom_ext
            apply RingHom.ext
            intro p
            change
              MvPolynomial.map (Ideal.Quotient.mk (B.I j.unop)) p =
                MvPolynomial.map
                  (Ideal.Quotient.factor
                    (B.antitone (CategoryTheory.le_of_op_hom f)))
                  (MvPolynomial.map (Ideal.Quotient.mk (B.I i.unop)) p)
            rw [MvPolynomial.map_map, Ideal.Quotient.factor_comp_mk] } }
  exact ((limit.isLimit D).lift c).hom

@[simp]
theorem restrictedPowerSeriesProjection_polynomialMap
    (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) (r : ℕ) (i : B.Index)
    (p : MvPolynomial (Fin r) A) :
    restrictedPowerSeriesProjection A B r i
        (restrictedPowerSeriesPolynomialMap A B r p) =
      MvPolynomial.map (Ideal.Quotient.mk (B.I i)) p := by
  sorry

/-! ## Assertions in the source -/

/-- The coefficient description of restricted power series.

For a complete separated input, every compatible limit element has a unique
coefficient family whose coefficients tend to zero, and whose reductions are
the coefficients of all quotient polynomials. -/
theorem restrictedPowerSeries_exists_unique_coefficients
    (A : Type u) [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
    (hA : IsCompleteLinearlyTopologizedRing A)
    (B : OpenIdealBasis A) (r : ℕ)
    (x : restrictedPowerSeries A B r) :
    ∃! a : (Fin r →₀ ℕ) → A,
      IsRestrictedCoefficientFamily A B r a ∧
        ∀ (i : B.Index) (E : Fin r →₀ ℕ),
          Ideal.Quotient.mk (B.I i) (a E) =
            restrictedPowerSeriesCoefficient A B r x i E := by
  sorry

/-- The inverse-limit topology is complete and separated. -/
theorem restrictedPowerSeries_complete_for_limit_topology
    (A : Type u) [CommRing A] [TopologicalSpace A]
    (B : OpenIdealBasis A) (r : ℕ) :
    IsCompleteSeparatedTopologicalAddGroupFor
      (restrictedPowerSeries A B r)
      (restrictedPowerSeriesLimitTopology A B r) := by
  sorry

/-- The universal property: an algebra map from the polynomial ring to a
complete linearly topologized target extends uniquely to a continuous ring map
on restricted power series. -/
theorem restrictedPowerSeries_universal_property
    (A C : Type u) [CommRing A] [CommRing C]
    [Algebra A C]
    [TopologicalSpace A] [TopologicalSpace C]
    [IsTopologicalRing A] [IsTopologicalRing C]
    (hA : IsCompleteLinearlyTopologizedRing A)
    (hC : IsCompleteLinearlyTopologizedRing C)
    (hAC : Continuous (algebraMap A C))
    (B : OpenIdealBasis A) (r : ℕ)
    (f : MvPolynomial (Fin r) A →ₐ[A] C) :
    ∃! F : restrictedPowerSeries A B r →+* C,
      (@Continuous (restrictedPowerSeries A B r) C
        (restrictedPowerSeriesLimitTopology A B r) inferInstance F) ∧
        F.comp (restrictedPowerSeriesPolynomialMap A B r) = f.toRingHom := by
  sorry

/-! ## The I-adic comparison and its warnings -/

/-- The canonical I-adic completion of the polynomial ring. -/
noncomputable abbrev iAdicPolynomialCompletion (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Type u :=
  AdicCompletion (polynomialExtensionIdeal A I r) (MvPolynomial (Fin r) A)

/-- The I-adic topology on the polynomial completion. -/
@[instance_reducible]
def iAdicPolynomialCompletionTopology (A : Type u) [CommRing A]
  (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicPolynomialCompletion A I r) :=
  IAdicModuleTopology
    (MvPolynomial (Fin r) A) (polynomialExtensionIdeal A I r)
    (iAdicPolynomialCompletion A I r)

/-- The chosen I-adic open-ideal basis on `A`. -/
def iAdicOpenIdealBasis (A : Type u) [CommRing A] (I : Ideal A) :
    @OpenIdealBasis A _ I.adicTopology :=
  letI : TopologicalSpace A := I.adicTopology
  { Index := ULift.{u} ℕ
    I := fun n => I ^ n.down
    directed := fun m n =>
      ⟨ULift.up (max m.down n.down), by
        simp, by
        simp⟩
    antitone := fun m n hmn => by
      apply Ideal.pow_le_pow_right
      exact hmn
    fundamental := by
      simpa [Function.comp_def] using
        (I.hasBasis_nhds_zero_adic.comp_equiv
          (Equiv.ulift : ULift.{u} ℕ ≃ ℕ))
    isOpen := fun n => by
      have hmem : ((I ^ n.down : Ideal A) : Set A) ∈
          @nhds A I.adicTopology (0 : A) := by
        exact I.hasBasis_nhds_zero_adic.mem_iff.mpr
          ⟨n.down, trivial, Subset.rfl⟩
      exact (I ^ n.down).toAddSubgroup.isOpen_of_mem_nhds hmem }

/-- The inverse-limit topology on the I-adic completion. -/
@[instance_reducible]
def iAdicPolynomialCompletionLimitTopology (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicPolynomialCompletion A I r) :=
  AdicCompletionLimitTopology
    (MvPolynomial (Fin r) A) (polynomialExtensionIdeal A I r)
    (MvPolynomial (Fin r) A)

/-- The I-adic specialization of the restricted power series type, with the
adic topology on the coefficient ring made explicit. -/
noncomputable abbrev iAdicRestrictedPowerSeries (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) : Type u :=
  @restrictedPowerSeries A _ I.adicTopology (iAdicOpenIdealBasis A I) r

@[instance_reducible]
def iAdicRestrictedPowerSeriesLimitTopology (A : Type u) [CommRing A]
    (I : Ideal A) (r : ℕ) :
    TopologicalSpace (iAdicRestrictedPowerSeries A I r) :=
  @restrictedPowerSeriesLimitTopology A _ I.adicTopology
    (iAdicOpenIdealBasis A I) r

/-- In the I-adically complete case, the I-adic completion of the polynomial
ring is the restricted power series ring as a ring. -/
theorem iAdicPolynomialCompletion_is_restrictedPowerSeries_as_ring
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ)
    (hA : IsAdicComplete I A) :
    Nonempty
      (iAdicPolynomialCompletion A I r ≃+*
        iAdicRestrictedPowerSeries A I r) := by
  sorry

/-- The limit topology on the restricted power series side is always complete. -/
theorem iAdicRestrictedPowerSeries_complete_for_limit_topology
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ) :
    IsCompleteSeparatedTopologicalAddGroupFor
      (iAdicRestrictedPowerSeries A I r)
      (iAdicRestrictedPowerSeriesLimitTopology A I r) := by
  exact @restrictedPowerSeries_complete_for_limit_topology A _ I.adicTopology
    (iAdicOpenIdealBasis A I) r

/-- The I-adic topology on the polynomial completion need not be complete. -/
theorem iAdicPolynomialCompletion_not_always_iAdically_complete :
    ¬ ∀ (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ),
      IsAdicComplete I A →
        IsAdicComplete (polynomialExtensionIdeal A I r)
          (iAdicPolynomialCompletion A I r) := by
  sorry

/-- If the defining ideal is finitely generated, the ring identification is
also an identification of the I-adic and limit topologies. -/
theorem iAdicPolynomialCompletion_is_restrictedPowerSeries_as_topologicalRing_of_fg
    (A : Type u) [CommRing A] (I : Ideal A) (r : ℕ)
    (hA : IsAdicComplete I A) (hI : I.FG) :
    ∃ e : iAdicPolynomialCompletion A I r ≃+*
        iAdicRestrictedPowerSeries A I r,
      (@Continuous (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletionTopology A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r) e) ∧
      (@Continuous (iAdicRestrictedPowerSeries A I r)
        (iAdicPolynomialCompletion A I r)
        (iAdicRestrictedPowerSeriesLimitTopology A I r)
        (iAdicPolynomialCompletionTopology A I r) e.symm) := by
  sorry

end

end Formalization.Books.FormalSpaces.Unit28
