import Mathlib.CategoryTheory.Limits.Types.Limits
import Mathlib.CategoryTheory.Limits.Types.Colimits

/-!
# Categories, Chapter 15: Limits and colimits in the category of sets

For a diagram `M : I ⥤ Type u`, the source's compatible families are exactly
Mathlib's `Functor.sections M`.  The concrete quotient model for the colimit is
exactly `Functor.ColimitType M`: its underlying type is the quotient of the
dependent sum `Σ i, M.obj i` by the relation generated by the diagram maps.

The final paragraph of the source is a forward reference to the next chapter:
it observes that the quotient description is more convenient for filtered
diagrams, but gives no precise assertion to formalize here.
-/

namespace Formalization.Books.Categories.Unit15

open CategoryTheory
open CategoryTheory.Limits

universe u v w

noncomputable section

variable {I : Type v} [Category.{w} I]

/-! ## Existence and the concrete limit -/

/-- Small diagrams of `u`-types have both limits and colimits in `Type u`.

This is the chapter's existence assertion for `Sets`, in the universe-aware
form used by Lean.  The two component instances are supplied by Mathlib's
canonical constructions for types.
-/
theorem has_limit_and_colimit_in_types [Small.{u} I] (M : I ⥤ Type u) :
    HasLimit M ∧ HasColimit M := by
  exact ⟨inferInstance, inferInstance⟩

/-- The displayed set of compatible tuples is Mathlib's `Functor.sections`.

`Types.limitEquivSections` identifies the chosen categorical limit with this
set, whose elements are functions `m` satisfying
`M.map φ (m i) = m i'` for every `φ : i ⟶ i'`.
-/
noncomputable def limit_equiv_compatible_families (M : I ⥤ Type u) [HasLimit M] :
    limit M ≃ M.sections :=
  Types.limitEquivSections M

/-- Under this equivalence, the `i`th coordinate is the canonical limit
projection. -/
@[simp] theorem limit_equiv_compatible_families_apply
    (M : I ⥤ Type u) [HasLimit M] (x : limit M) (i : I) :
    (limit_equiv_compatible_families M x).1 i = limit.π M i x := by
  exact Types.limitEquivSections_apply M x i

/-- The compatibility equation carried by a family in `M.sections`. -/
theorem compatible_family_condition (M : I ⥤ Type u) (m : M.sections)
    {i i' : I} (φ : i ⟶ i') :
    M.map φ (m.1 i) = m.1 i' :=
  Functor.sections_property m φ

/-! ## The concrete colimit and its generated relation -/

/-- The chosen categorical colimit is equivalent to the quotient model from
the source.

The target `M.ColimitType` is the quotient of `Σ i, M.obj i` by the relation
`M.ColimitTypeRel`; when the index and object universes differ, Mathlib keeps
this explicit quotient in its natural universe and supplies the equivalence.
-/
noncomputable def colimit_equiv_quotient (M : I ⥤ Type u) [HasColimit M] :
    colimit M ≃ M.ColimitType :=
  Types.colimitEquivColimitType M

/-- The generating relation identifies elements related by one diagram map. -/
theorem colimit_generating_relation_iff (M : I ⥤ Type u)
    {i i' : I} (x : M.obj i) (y : M.obj i') :
    M.ColimitTypeRel ⟨i, x⟩ ⟨i', y⟩ ↔
      ∃ φ : i ⟶ i', M.map φ x = y := by
  constructor
  · rintro ⟨φ, hφ⟩
    exact ⟨φ, hφ.symm⟩
  · rintro ⟨φ, hφ⟩
    exact ⟨φ, hφ.symm⟩

/-- Equality of quotient representatives is exactly the equivalence relation
generated by the one-map identifications.

`Relation.EqvGen` is the reflexive, symmetric, transitive chain closure, so
this is the Lean form of the source's displayed zigzag characterization.
-/
theorem colimit_quotient_eq_iff_generated (M : I ⥤ Type u)
    {i i' : I} (x : M.obj i) (y : M.obj i') :
    M.ιColimitType i x = M.ιColimitType i' y ↔
      Relation.EqvGen M.ColimitTypeRel ⟨i, x⟩ ⟨i', y⟩ := by
  exact Functor.ιColimitType_eq_iff (F := M) x y

/-- A single diagram map gives one of the quotient identifications. -/
theorem colimit_quotient_sound (M : I ⥤ Type u)
    {i i' : I} {x : M.obj i} {y : M.obj i'}
    (φ : i ⟶ i') (h : M.map φ x = y) :
    M.ιColimitType i x = M.ιColimitType i' y :=
  by
    rw [← h]
    exact (Functor.ιColimitType_map M φ x).symm

end

end Formalization.Books.Categories.Unit15
