import Mathlib.Algebra.Exact.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.LinearAlgebra.QuadraticForm.Radical
import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.LocalRing.Defs
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Mathlib.RingTheory.MvPowerSeries.Basic
import Mathlib.RingTheory.MvPowerSeries.Order

/-!
# Exercises, Chapter 14: Singularities

This file records the source-facing definitions and theorem interfaces for
the exercises and remark in the chapter on singularities.
-/

namespace Formalization.Books.Exercises.Unit14

universe u v w

noncomputable section

/-! ## The node and its cubic perturbations -/

/-- The formal power-series ring in the two variables used for a node. -/
abbrev twoVariablePowerSeries (k : Type u) [Field k] :=
  MvPowerSeries (Fin 2) k

/-- The ideal generated by the two formal variables. -/
def twoVariableMaximalIdeal (k : Type u) [Field k] :
    Ideal (twoVariablePowerSeries k) :=
  Ideal.span (Set.range (fun i : Fin 2 => MvPowerSeries.X i))

/-- The equation `xy` for the ordinary node. -/
def nodeEquation (k : Type u) [Field k] : twoVariablePowerSeries k :=
  MvPowerSeries.X (0 : Fin 2) * MvPowerSeries.X (1 : Fin 2)

/-- The equation `uv + δ` in the perturbed presentation. -/
def perturbedNodeEquation (k : Type u) [Field k]
    (δ : twoVariablePowerSeries k) : twoVariablePowerSeries k :=
  nodeEquation k + δ

/-- The quotient ring `k[[x,y]]/(xy)`. -/
abbrev nodeRing (k : Type u) [Field k] :=
  twoVariablePowerSeries k ⧸ Ideal.span {nodeEquation k}

/-- The quotient ring `k[[u,v]]/(uv + δ)`. -/
abbrev perturbedNodeRing (k : Type u) [Field k]
    (δ : twoVariablePowerSeries k) :=
  twoVariablePowerSeries k ⧸ Ideal.span {perturbedNodeEquation k δ}

/-- A cubic perturbation of the node has the same quotient ring up to isomorphism. -/
theorem nodeRing_equiv_perturbedNodeRing
    {k : Type u} [Field k] (δ : twoVariablePowerSeries k)
    (hδ : δ ∈ twoVariableMaximalIdeal k ^ 3) :
    Nonempty (nodeRing k ≃+* perturbedNodeRing k δ) := by
  sorry

/-! ## Ordinary double points -/

/-- A binary quadratic form written in the coordinates used by the source. -/
def binaryQuadraticFormOfCoefficients
    {K : Type v} [Field K] (a b c : K) :
    QuadraticForm K (Fin 2 → K) :=
  a • QuadraticMap.proj (R := K) (A := K) (0 : Fin 2) 0 +
      b • QuadraticMap.proj (R := K) (A := K) (0 : Fin 2) 1 +
      c • QuadraticMap.proj (R := K) (A := K) (1 : Fin 2) 1

/-- The same quadratic expression regarded as a power series. -/
def binaryQuadraticPowerSeries
    {K : Type v} [Field K] (a b c : K) : MvPowerSeries (Fin 2) K :=
  a • (MvPowerSeries.X (0 : Fin 2)) ^ 2 +
      b • (MvPowerSeries.X (0 : Fin 2) * MvPowerSeries.X (1 : Fin 2)) +
      c • (MvPowerSeries.X (1 : Fin 2)) ^ 2

/-- The precise initial-term condition for a power series to define a node. -/
def HasBinaryQuadraticInitialTerm
    {K : Type v} [Field K] (f : MvPowerSeries (Fin 2) K)
    (a b c : K) : Prop :=
  f.order = 2 ∧
    f.homogeneousComponent 2 = binaryQuadraticPowerSeries a b c

/-- In characteristic two, the binary form is nondegenerate exactly when its
mixed coefficient is nonzero. -/
theorem binaryQuadraticForm_nondegenerate_iff_charTwo
    {K : Type v} [Field K] [CharP K 2] {a b c : K} :
    (binaryQuadraticFormOfCoefficients a b c).Nondegenerate ↔ b ≠ 0 := by
  sorry

/-- A finite separable coefficient-field extension together with a
nondegenerate binary quadratic form. -/
structure BinaryQuadraticPair (k : Type u) [Field k] where
  K : Type v
  [fieldK : Field K]
  [algebraK : Algebra k K]
  [finiteK : Module.Finite k K]
  [separableK : Algebra.IsSeparable k K]
  coeffA : K
  coeffB : K
  coeffC : K
  coefficients_nonzero : coeffA ≠ 0 ∨ coeffB ≠ 0 ∨ coeffC ≠ 0
  nondegenerate :
    (binaryQuadraticFormOfCoefficients coeffA coeffB coeffC).Nondegenerate

attribute [instance] BinaryQuadraticPair.fieldK BinaryQuadraticPair.algebraK
  BinaryQuadraticPair.finiteK BinaryQuadraticPair.separableK

/-- The nondegeneracy condition on the quadratic form in a pair. -/
def binaryQuadraticPairIsNondegenerate
    {k : Type u} [Field k] (P : BinaryQuadraticPair k) : Prop :=
  (binaryQuadraticFormOfCoefficients P.coeffA P.coeffB P.coeffC).Nondegenerate

/-- Equivalence of the pairs `(k', q)`, allowing a scalar multiple of the
equation as well as a linear change of variables. -/
def binaryQuadraticPairEquivalent
    {k : Type u} [Field k]
    (P Q : BinaryQuadraticPair k) : Prop :=
  ∃ e : P.K ≃ₐ[k] Q.K, ∃ u : P.Kˣ,
    ∃ ℓ : (Fin 2 → P.K) ≃ₗ[P.K] (Fin 2 → P.K),
      ∀ x : Fin 2 → P.K,
        e (binaryQuadraticFormOfCoefficients P.coeffA P.coeffB P.coeffC x) =
          e (u : P.K) *
            binaryQuadraticFormOfCoefficients Q.coeffA Q.coeffB Q.coeffC
              (fun i => e (ℓ x i))

/-- The complete-local model attached to a pair `(k',q)`. -/
abbrev ordinaryDoublePointNormalForm
    {k : Type u} [Field k] (P : BinaryQuadraticPair k) :=
  MvPowerSeries (Fin 2) P.K ⧸
    Ideal.span {binaryQuadraticPowerSeries P.coeffA P.coeffB P.coeffC}

/-- A ring is complete and local in the adic sense used for complete local
rings. -/
def IsCompleteLocalRing (A : Type v) [CommRing A] : Prop :=
  ∃ hA : IsLocalRing A,
    letI : IsLocalRing A := hA
    IsAdicComplete (IsLocalRing.maximalIdeal A) A

/-- A source-facing presentation of an ordinary double point. -/
structure OrdinaryDoublePointPresentation
    (k : Type u) [Field k] (A : Type w) [CommRing A] [Algebra k A] where
  complete_local : IsCompleteLocalRing A
  pair : BinaryQuadraticPair.{u, v} k
  pair_nondegenerate : binaryQuadraticPairIsNondegenerate pair
  definingSeries : MvPowerSeries (Fin 2) pair.K
  order_eq_two : definingSeries.order = 2
  initial_term :
    definingSeries.homogeneousComponent 2 =
      binaryQuadraticPowerSeries pair.coeffA pair.coeffB pair.coeffC
  ringEquiv :
    A ≃ₐ[k] (MvPowerSeries (Fin 2) pair.K ⧸ Ideal.span {definingSeries})

/-- The predicate that a complete local ring is an ordinary double point. -/
def IsOrdinaryDoublePoint
    (k : Type u) [Field k] (A : Type w) [CommRing A] [Algebra k A] : Prop :=
  Nonempty (OrdinaryDoublePointPresentation.{u, v, w} k A)

/-- The defining series of an ordinary double point can be replaced by its
nondegenerate quadratic initial term. -/
theorem ordinaryDoublePoint_isomorphic_to_normalForm
    {k : Type u} [Field k] {A : Type w} [CommRing A] [Algebra k A]
    (D : OrdinaryDoublePointPresentation k A) :
    Nonempty (A ≃ₐ[k] ordinaryDoublePointNormalForm D.pair) := by
  sorry

/-- The normal forms are classified by the isomorphism classes of their
finite separable coefficient fields and nondegenerate quadratic forms. -/
theorem ordinaryDoublePoint_normalForm_isomorphic_iff
    {k : Type u} [Field k] (P Q : BinaryQuadraticPair k) :
    Nonempty
        (ordinaryDoublePointNormalForm P ≃ₐ[k]
          ordinaryDoublePointNormalForm Q) ↔
      binaryQuadraticPairEquivalent P Q := by
  sorry

/-! ## The periodic matrix resolution -/

/-- The quotient of a commutative ring by the principal ideal generated by `f`. -/
abbrev principalQuotient (R : Type u) [CommRing R] (f : R) :=
  R ⧸ Ideal.span {f}

/-- Reduce a square matrix modulo the principal ideal `(f)`. -/
def quotientMatrix
    {R : Type u} [CommRing R] {n : ℕ} (f : R)
    (M : Matrix (Fin n) (Fin n) R) :
    Matrix (Fin n) (Fin n) (principalQuotient R f) :=
  M.map (Ideal.Quotient.mk (Ideal.span {f}))

/-- Exactness at both alternating terms of a bi-infinite two-periodic
sequence with matrices `B` and `A`. -/
def periodicResolutionExact
    {S : Type u} [CommRing S] {n : ℕ}
    (A B : Matrix (Fin n) (Fin n) S) : Prop :=
  Function.Exact B.mulVecLin A.mulVecLin ∧
    Function.Exact A.mulVecLin B.mulVecLin

/-- A matrix factorization by a nonzerodivisor gives the exact alternating
resolution over the quotient by that nonzerodivisor. -/
theorem periodicMatrixResolution_exact
    {R : Type u} [CommRing R] {n : ℕ} (hn : 1 ≤ n)
    (A B : Matrix (Fin n) (Fin n) R) (f : R)
    (hAB : A * B = f • (1 : Matrix (Fin n) (Fin n) R))
    (hf : IsRegular f) :
    periodicResolutionExact (quotientMatrix f A) (quotientMatrix f B) := by
  sorry

end

end Formalization.Books.Exercises.Unit14
