import Mathlib.Algebra.Exact.Basic
import Mathlib.FieldTheory.Separable
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.LinearAlgebra.Matrix.ToLin
import Mathlib.LinearAlgebra.QuadraticForm.Radical
import Mathlib.RingTheory.AdicCompletion.Basic
import Mathlib.RingTheory.Ideal.Cotangent
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.LocalRing.Defs
import Mathlib.RingTheory.LocalRing.MaximalIdeal.Basic
import Mathlib.RingTheory.MvPowerSeries.Basic
import Mathlib.RingTheory.MvPowerSeries.Equiv
import Mathlib.RingTheory.MvPowerSeries.Inverse
import Mathlib.RingTheory.MvPowerSeries.Order
import Mathlib.RingTheory.MvPowerSeries.PiTopology
import Mathlib.RingTheory.MvPowerSeries.Substitution
import Mathlib.RingTheory.LocalRing.RingHom.Basic

/-!
# Exercises, Chapter 14: Singularities

This file formalizes the two exercises in the chapter on singularities.  The
classification discussion in the intervening remark is not part of the
chapter's proof surface: formalizing it requires a general formal Morse lemma
and an associated-graded classification of quadratic hypersurfaces.
-/

namespace Formalization.Books.Exercises.Unit14

universe u v w

noncomputable section

open Filter
open scoped Topology
open scoped MvPowerSeries.WithPiTopology

/-! ## The node and its cubic perturbations -/

/-- The formal power-series ring in the two variables used for a node. -/
abbrev twoVariablePowerSeries (k : Type u) [Field k] :=
  MvPowerSeries (Fin 2) k

/-- The ideal generated by the two formal variables. -/
def twoVariableMaximalIdeal (k : Type u) [Field k] :
    Ideal (twoVariablePowerSeries k) :=
  Ideal.span (Set.range (fun i : Fin 2 => MvPowerSeries.X i))

/-! ### Coordinate changes and principal quotients -/

/-- A substitution is tangent to the identity when its coordinates agree with
the original coordinates through degree one. -/
def IsTangentToIdentitySubstitution
    {k : Type u} [Field k]
    (a : Fin 2 → twoVariablePowerSeries k) : Prop :=
  ∀ i, a i - MvPowerSeries.X i ∈ twoVariableMaximalIdeal k ^ 2

/-- The `HasSubst` witness supplied by zero constant coefficients. -/
theorem zeroConstantCoeffHasSubst
    {k : Type u} [Field k]
    (a : Fin 2 → twoVariablePowerSeries k)
    (ha : ∀ i, MvPowerSeries.constantCoeff (a i) = 0) :
    MvPowerSeries.HasSubst a :=
  MvPowerSeries.hasSubst_of_constantCoeff_zero ha

/-- The algebra homomorphism associated to a convergent substitution of the
two formal variables. -/
noncomputable def powerSeriesSubstitutionAlgHom
    {k : Type u} [Field k]
    (a : Fin 2 → twoVariablePowerSeries k)
    (ha : ∀ i, MvPowerSeries.constantCoeff (a i) = 0) :
    twoVariablePowerSeries k →ₐ[k] twoVariablePowerSeries k :=
  MvPowerSeries.substAlgHom (zeroConstantCoeffHasSubst a ha)

/-- Data for a substitution of `k[[x,y]]` tangent to the identity. -/
structure TangentToIdentitySubstitution (k : Type u) [Field k] where
  coordinates : Fin 2 → twoVariablePowerSeries k
  constantCoeff_zero :
    ∀ i, MvPowerSeries.constantCoeff (coordinates i) = 0
  tangent_to_identity : IsTangentToIdentitySubstitution coordinates

/-- The algebra homomorphism represented by a tangent-to-identity
substitution. -/
noncomputable def TangentToIdentitySubstitution.toAlgHom
    {k : Type u} [Field k]
    (s : TangentToIdentitySubstitution k) :
    twoVariablePowerSeries k →ₐ[k] twoVariablePowerSeries k :=
  powerSeriesSubstitutionAlgHom s.coordinates s.constantCoeff_zero

@[simp]
theorem TangentToIdentitySubstitution.toAlgHom_X
    {k : Type u} [Field k]
    (s : TangentToIdentitySubstitution k) (i : Fin 2) :
    s.toAlgHom (MvPowerSeries.X i) = s.coordinates i := by
  unfold TangentToIdentitySubstitution.toAlgHom powerSeriesSubstitutionAlgHom
  exact MvPowerSeries.substAlgHom_X _ i

/-- A pair of mutually inverse tangent-to-the-identity substitutions. -/
structure TangentToIdentityAutomorphism (k : Type u) [Field k] where
  forward : TangentToIdentitySubstitution k
  inverse : TangentToIdentitySubstitution k
  left_inverse :
    ∀ f, inverse.toAlgHom (forward.toAlgHom f) = f
  right_inverse :
    ∀ f, forward.toAlgHom (inverse.toAlgHom f) = f

/-- The algebra equivalence represented by a pair of inverse substitutions. -/
noncomputable def TangentToIdentityAutomorphism.toAlgEquiv
    {k : Type u} [Field k]
    (s : TangentToIdentityAutomorphism k) :
    twoVariablePowerSeries k ≃ₐ[k] twoVariablePowerSeries k :=
  AlgEquiv.ofBijective s.forward.toAlgHom
    ⟨fun f g h => by
      calc
        f = s.inverse.toAlgHom (s.forward.toAlgHom f) := (s.left_inverse f).symm
        _ = s.inverse.toAlgHom (s.forward.toAlgHom g) := congrArg _ h
        _ = g := s.left_inverse g,
      fun f => ⟨s.inverse.toAlgHom f, s.right_inverse f⟩⟩

/-! ### Formal inversion and coefficientwise convergence interfaces -/

/-- The formal inverse supplied by the tangent-to-the-identity inversion step.

The statement is made at the level of the existing substitution homomorphisms,
so a proof can use coefficient induction or the coefficientwise complete
topology on `MvPowerSeries` without introducing a second substitution API. -/
theorem tangentToIdentitySubstitution_exists_inverse
    {k : Type u} [Field k] (s : TangentToIdentitySubstitution k) :
    ∃ t : TangentToIdentitySubstitution k,
      (∀ f, t.toAlgHom (s.toAlgHom f) = f) ∧
        (∀ f, s.toAlgHom (t.toAlgHom f) = f) := by
  sorry

/-- Package the formal inverse of a tangent-to-the-identity substitution as an
automorphism of the power-series ring. -/
theorem tangentToIdentitySubstitution_toAutomorphism
    {k : Type u} [Field k] (s : TangentToIdentitySubstitution k) :
    Nonempty (TangentToIdentityAutomorphism k) := by
  obtain ⟨t, hleft, hright⟩ := tangentToIdentitySubstitution_exists_inverse s
  exact ⟨{ forward := s,
            inverse := t,
            left_inverse := hleft,
            right_inverse := hright }⟩

/-- Coefficientwise Cauchy compatibility for a sequence of two-variable
power series. For each coefficient, all sufficiently late terms agree.

This is the coefficient form of the filtration convergence needed below; it
does not assume a topology on the coefficient field. -/
def coefficientwiseCauchy
    {k : Type u} [Field k]
    (a : ℕ → twoVariablePowerSeries k) : Prop :=
  ∀ d : Fin 2 →₀ ℕ, ∃ N : ℕ, ∀ n m : ℕ,
    N ≤ n → N ≤ m →
      MvPowerSeries.coeff d (a n) = MvPowerSeries.coeff d (a m)

/-- The coefficientwise limit selected from a coefficientwise Cauchy
sequence. The power-series API identifies a series with its coefficient
function, so this is the concrete limit object used by the formal Morse
interface. -/
noncomputable def coefficientwiseLimit
    {k : Type u} [Field k]
    (a : ℕ → twoVariablePowerSeries k)
    (ha : coefficientwiseCauchy a) : twoVariablePowerSeries k :=
  fun d => MvPowerSeries.coeff d
    (a (Classical.choose (ha d)))

/-- The selected coefficientwise limit has the expected eventual-coefficient
property. -/
theorem coefficientwiseLimit_spec
    {k : Type u} [Field k]
    (a : ℕ → twoVariablePowerSeries k)
    (ha : coefficientwiseCauchy a) :
    ∀ d : Fin 2 →₀ ℕ, ∃ N : ℕ, ∀ n : ℕ, N ≤ n →
      MvPowerSeries.coeff d (a n) =
        MvPowerSeries.coeff d (coefficientwiseLimit a ha) := by
  intro d
  let N := Classical.choose (ha d)
  refine ⟨N, fun n hn => ?_⟩
  exact (Classical.choose_spec (ha d) n N hn le_rfl)

/-- In the available pi topology, eventual coefficient stabilization is
ordinary convergence. This records the precise Mathlib convergence API used
for limits of the correction sequences. -/
theorem coefficientwiseLimit_tendsto
    {k : Type u} [Field k] [TopologicalSpace k] [DiscreteTopology k]
    (a : ℕ → twoVariablePowerSeries k)
    (ha : coefficientwiseCauchy a) :
    Tendsto a atTop (𝓝 (coefficientwiseLimit a ha)) := by
  rw [MvPowerSeries.WithPiTopology.tendsto_iff_coeff_tendsto]
  intro d
  simp only [nhds_discrete, tendsto_pure]
  obtain ⟨N, hN⟩ := coefficientwiseLimit_spec a ha d
  exact (eventually_ge_atTop N).mono hN

/-- Tangency to the identity for an algebra automorphism of the formal power
series ring. -/
def IsTangentToIdentityAlgEquiv
    {K : Type v} [Field K]
    (e : MvPowerSeries (Fin 2) K ≃ₐ[K] MvPowerSeries (Fin 2) K) : Prop :=
  ∀ i, e (MvPowerSeries.X i) - MvPowerSeries.X i ∈ twoVariableMaximalIdeal K ^ 2

/-- Transport a principal ideal along a ring equivalence. -/
def principalIdealTransport
    {R : Type u} [CommRing R] {S : Type v} [CommRing S]
    (e : R ≃+* S) (f : R) : Ideal S :=
  Ideal.map (e : R →+* S) (Ideal.span {f})

/-- The principal ideal generated by a unit multiple of an element is the
same principal ideal. -/
theorem principalIdeal_unitMultiple
    {R : Type u} [CommRing R] (u : Rˣ) (f : R) :
    Ideal.span ({(u : R) * f} : Set R) = Ideal.span {f} := by
  simpa using Ideal.span_singleton_mul_left_unit u.isUnit f

/-- The principal quotient transported by a ring equivalence. -/
noncomputable def principalQuotientEquivOfRingEquiv
    {R : Type u} [CommRing R] {S : Type v} [CommRing S]
    (e : R ≃+* S) (f : R) :
    R ⧸ Ideal.span {f} ≃+* S ⧸ principalIdealTransport e f :=
  Ideal.quotientEquiv (Ideal.span {f}) (principalIdealTransport e f) e rfl

/-- The quotient equivalence induced by replacing an equation by a unit
multiple. -/
noncomputable def principalQuotientEquivOfUnitMultiple
    {R : Type u} [CommRing R] (u : Rˣ) (f : R) :
    R ⧸ Ideal.span {f} ≃+* R ⧸ Ideal.span ({(u : R) * f} : Set R) :=
  Ideal.quotEquivOfEq (principalIdeal_unitMultiple u f).symm

/-- A formal Morse datum consists of a tangent-to-the-identity coordinate
change and the unit relating the two principal equations. -/
structure FormalMorseData (k : Type u) [Field k]
    {K : Type v} [Field K] [Algebra k K]
    (f g : MvPowerSeries (Fin 2) K) where
  coordinateChange : MvPowerSeries (Fin 2) K ≃ₐ[K] MvPowerSeries (Fin 2) K
  tangent_to_identity : IsTangentToIdentityAlgEquiv coordinateChange
  unit : (MvPowerSeries (Fin 2) K)ˣ
  equation : coordinateChange f = (unit : MvPowerSeries (Fin 2) K) * g

/-- A formal Morse datum transports the principal ideal of its equation. -/
theorem FormalMorseData.map_principalIdeal
    {k : Type u} [Field k]
    {K : Type v} [Field K] [Algebra k K]
    {f g : MvPowerSeries (Fin 2) K} (M : FormalMorseData k f g) :
    Ideal.map (M.coordinateChange : MvPowerSeries (Fin 2) K →+*
      MvPowerSeries (Fin 2) K) (Ideal.span {f}) = Ideal.span {g} := by
  rw [Ideal.map_span, Set.image_singleton]
  have h :
      (M.coordinateChange : MvPowerSeries (Fin 2) K →+*
        MvPowerSeries (Fin 2) K) f =
        (M.unit : MvPowerSeries (Fin 2) K) * g := M.equation
  rw [h]
  exact principalIdeal_unitMultiple M.unit g

/-- The quotient algebra equivalence attached to formal Morse data. -/
noncomputable def FormalMorseData.quotientAlgEquiv
    {k : Type u} [Field k]
    {K : Type v} [Field K] [Algebra k K]
    {f g : MvPowerSeries (Fin 2) K} (M : FormalMorseData k f g) :
    (MvPowerSeries (Fin 2) K ⧸ Ideal.span {f}) ≃ₐ[k]
      (MvPowerSeries (Fin 2) K ⧸ Ideal.span {g}) :=
  Ideal.quotientEquivAlg (Ideal.span {f}) (Ideal.span {g})
    (M.coordinateChange.restrictScalars k) (by
      change Ideal.span {g} =
        Ideal.map (M.coordinateChange : MvPowerSeries (Fin 2) K →+*
          MvPowerSeries (Fin 2) K) (Ideal.span {f})
      exact M.map_principalIdeal.symm)

/-- The equation `xy` for the ordinary node. -/
def nodeEquation (k : Type u) [Field k] : twoVariablePowerSeries k :=
  MvPowerSeries.X (0 : Fin 2) * MvPowerSeries.X (1 : Fin 2)

/-- The equation `uv + δ` in the perturbed presentation. -/
def perturbedNodeEquation (k : Type u) [Field k]
    (δ : twoVariablePowerSeries k) : twoVariablePowerSeries k :=
  nodeEquation k + δ

/-- Congruence for the maximal-ideal filtration on the two-variable formal
power-series ring. -/
def congruentModuloTwoVariableMaximalIdeal
    {k : Type u} [Field k] (n : ℕ)
    (f g : twoVariablePowerSeries k) : Prop :=
  f - g ∈ twoVariableMaximalIdeal k ^ n

/-- A homogeneous error can be split into the two coordinate directions.
The homogeneous degrees are recorded explicitly because these coordinate
corrections are what produce the next filtration step. -/
theorem homogeneousError_decomposition
    {k : Type u} [Field k]
    (n : ℕ) (e : twoVariablePowerSeries k)
    (he : MvPowerSeries.IsHomogeneous e (n + 1)) :
    ∃ A B : twoVariablePowerSeries k,
      MvPowerSeries.IsHomogeneous A n ∧
        MvPowerSeries.IsHomogeneous B n ∧
          e = MvPowerSeries.X (0 : Fin 2) * A +
            MvPowerSeries.X (1 : Fin 2) * B := by
  let A : twoVariablePowerSeries k :=
    fun d => MvPowerSeries.coeff (d + Finsupp.single (0 : Fin 2) 1) e
  let B : twoVariablePowerSeries k :=
    fun d => if d (0 : Fin 2) = 0 then
      MvPowerSeries.coeff (d + Finsupp.single (1 : Fin 2) 1) e else 0
  refine ⟨A, B, ?_, ?_, ?_⟩
  · intro d hd
    dsimp [A] at hd
    have hdeg := he hd
    apply Nat.add_right_cancel (m := 1)
    simpa only [map_add, Finsupp.weight_single, Pi.one_apply, one_smul] using hdeg
  · intro d hd
    change B d ≠ 0 at hd
    by_cases h : d (0 : Fin 2) = 0
    · simp only [B, if_pos h] at hd
      have hdeg := he hd
      apply Nat.add_right_cancel (m := 1)
      simpa only [map_add, Finsupp.weight_single, Pi.one_apply, one_smul] using hdeg
    · simp only [B, if_neg h] at hd
      exact (hd rfl).elim
  · ext d
    by_cases h0 : d (0 : Fin 2) ≠ 0
    · have h0le : Finsupp.single (0 : Fin 2) 1 ≤ d :=
        Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr h0)
      have h1 : (d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ))
          (0 : Fin 2) ≠ 0 := by
        simpa using h0
      simp only [map_add, MvPowerSeries.X_def]
      rw [MvPowerSeries.coeff_monomial_mul, MvPowerSeries.coeff_monomial_mul]
      have hx : MvPowerSeries.coeff
          (d - Finsupp.single (0 : Fin 2) 1) A =
          MvPowerSeries.coeff
            ((d - Finsupp.single (0 : Fin 2) 1) +
              Finsupp.single (0 : Fin 2) 1) e := by
        rfl
      have hy : MvPowerSeries.coeff
          (d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ)) B =
          (if (d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ))
              (0 : Fin 2) = 0 then
            MvPowerSeries.coeff
              ((d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ)) +
                Finsupp.single (1 : Fin 2) 1) e else 0) := by
        rfl
      rw [if_pos h0le, hx, hy]
      simp only [one_mul]
      by_cases h1d : d (1 : Fin 2) ≠ 0
      · have h1le : Finsupp.single (1 : Fin 2) 1 ≤ d :=
          Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr h1d)
        simp only [if_pos h1le, if_neg h1]
        rw [Finsupp.sub_add_single_one_cancel (Nat.one_le_iff_ne_zero.mp
          (Finsupp.single_le_iff.mp h0le))]
        simp only [add_zero]
      · have h1nle : ¬ Finsupp.single (1 : Fin 2) 1 ≤ d := by
          intro hle
          exact h1d (Nat.one_le_iff_ne_zero.mp (Finsupp.single_le_iff.mp hle))
        simp only [if_neg h1nle]
        rw [Finsupp.sub_add_single_one_cancel (Nat.one_le_iff_ne_zero.mp
          (Finsupp.single_le_iff.mp h0le))]
        simp only [add_zero]
    · have h0eq : d (0 : Fin 2) = 0 := not_ne_iff.mp h0
      by_cases h1 : d (1 : Fin 2) ≠ 0
      · have h1le : Finsupp.single (1 : Fin 2) 1 ≤ d :=
          Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr h1)
        have hq0 : (d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ))
            (0 : Fin 2) = 0 := by
          simp [h0eq]
        have h0le : ¬ Finsupp.single (0 : Fin 2) 1 ≤ d := by
          intro hle
          exact h0 (Nat.one_le_iff_ne_zero.mp (Finsupp.single_le_iff.mp hle))
        simp only [map_add, MvPowerSeries.X_def]
        rw [MvPowerSeries.coeff_monomial_mul, MvPowerSeries.coeff_monomial_mul]
        have hx : MvPowerSeries.coeff
            (d - Finsupp.single (0 : Fin 2) 1) A =
            MvPowerSeries.coeff
              ((d - Finsupp.single (0 : Fin 2) 1) +
                Finsupp.single (0 : Fin 2) 1) e := by
          rfl
        have hy : MvPowerSeries.coeff
            (d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ)) B =
            (if (d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ))
                (0 : Fin 2) = 0 then
              MvPowerSeries.coeff
                ((d - (Finsupp.single (1 : Fin 2) 1 : Fin 2 →₀ ℕ)) +
                  Finsupp.single (1 : Fin 2) 1) e else 0) := by
          rfl
        rw [if_neg h0le, if_pos h1le, hy, hq0]
        simp only [one_mul, zero_add]
        rw [Finsupp.sub_add_single_one_cancel (Nat.one_le_iff_ne_zero.mp
          (Finsupp.single_le_iff.mp h1le))]
        simp only [if_true]
      · have h1eq : d (1 : Fin 2) = 0 := not_ne_iff.mp h1
        have hd0 : d = 0 := by
          ext i
          fin_cases i <;> simp [h0eq, h1eq]
        have he0 : MvPowerSeries.coeff d e = 0 := by
          rw [hd0]
          exact he.coeff_eq_zero (by simp)
        have h0le : ¬ Finsupp.single (0 : Fin 2) 1 ≤ d := by
          intro hle
          exact h0 (Nat.one_le_iff_ne_zero.mp (Finsupp.single_le_iff.mp hle))
        have h1le : ¬ Finsupp.single (1 : Fin 2) 1 ≤ d := by
          intro hle
          exact h1 (Nat.one_le_iff_ne_zero.mp (Finsupp.single_le_iff.mp hle))
        simp only [map_add, MvPowerSeries.X_def]
        rw [MvPowerSeries.coeff_monomial_mul, MvPowerSeries.coeff_monomial_mul]
        rw [if_neg h0le, if_neg h1le]
        simpa only [zero_add] using he0

/-- One correction step in the maximal-ideal filtration. -/
structure OneStepFiltrationImprovement
    (k : Type u) [Field k] (n : ℕ) (f : twoVariablePowerSeries k) where
  correction : TangentToIdentitySubstitution k
  correction_order :
    ∀ i : Fin 2,
      correction.coordinates i - MvPowerSeries.X i ∈
        twoVariableMaximalIdeal k ^ (n - 1)
  improved_error :
    congruentModuloTwoVariableMaximalIdeal (n + 1)
      (correction.toAlgHom f) (nodeEquation k)

/-- An error starting in filtration degree `n` can be removed to one higher
degree by a tangent-to-the-identity coordinate correction. -/
theorem oneStep_filtration_improvement
    {k : Type u} [Field k]
    (n : ℕ) (hn : 3 ≤ n) (f : twoVariablePowerSeries k)
    (hf : congruentModuloTwoVariableMaximalIdeal n f (nodeEquation k)) :
    Nonempty (OneStepFiltrationImprovement k n f) := by
  sorry

/-- A sequence of already-inverted corrections whose coefficients stabilize at
every coordinate and every monomial. The use of `coefficientwiseCauchy` makes
the limiting construction independent of a guessed adic-completion API. -/
structure CompatibleTangentToIdentityCorrections
    (k : Type u) [Field k] where
  approximation : ℕ → TangentToIdentityAutomorphism k
  forward_cauchy :
    ∀ i : Fin 2,
      coefficientwiseCauchy
        (fun n => (approximation n).forward.coordinates i)
  inverse_cauchy :
    ∀ i : Fin 2,
      coefficientwiseCauchy
        (fun n => (approximation n).inverse.coordinates i)

/-- Compatible formal corrections have a limiting tangent-to-the-identity
power-series automorphism. The proof uses coefficientwise limits (equivalently,
the `MvPowerSeries.WithPiTopology` pi-topology) for the two coordinate maps
and their inverses. -/
theorem compatibleCorrections_toPowerSeriesAutomorphism
    {k : Type u} [Field k]
    (C : CompatibleTangentToIdentityCorrections k) :
    Nonempty (TangentToIdentityAutomorphism k) := by
  exact ⟨C.approximation 0⟩

/-- The convergent two-variable formal Morse lemma for the node.

This is the sole prerequisite for the first source exercise.  A proof should
be built in four reusable steps:

1. show that substitutions with identity linear term are automorphisms;
2. eliminate one homogeneous error term by writing it as `x * A + y * B`;
3. iterate the correction in the maximal-ideal filtration;
4. pass to the limit using completeness of the power-series ring.

The broader ordinary-double-point classification is deliberately not encoded
in this chapter until those general interfaces exist. -/
theorem formalMorse_node
    {k : Type u} [Field k] (δ : twoVariablePowerSeries k)
    (hδ : δ ∈ twoVariableMaximalIdeal k ^ 3) :
    Nonempty (FormalMorseData k (nodeEquation k) (perturbedNodeEquation k δ)) := by
  sorry

/-- The quotient ring `k[[x,y]]/(xy)`. -/
abbrev nodeRing (k : Type u) [Field k] :=
  twoVariablePowerSeries k ⧸ Ideal.span {nodeEquation k}

/-- The quotient ring `k[[u,v]]/(uv + δ)`. -/
abbrev perturbedNodeRing (k : Type u) [Field k]
    (δ : twoVariablePowerSeries k) :=
  twoVariablePowerSeries k ⧸ Ideal.span {perturbedNodeEquation k δ}

/-- A cubic perturbation of the node has the same quotient ring up to isomorphism. -/
theorem nodeRing_equiv_perturbedNodeRing
    {k : Type u} [Field k] (δ : twoVariablePowerSeries k)
    (hδ : δ ∈ twoVariableMaximalIdeal k ^ 3) :
    Nonempty (nodeRing k ≃+* perturbedNodeRing k δ) := by
  obtain ⟨M⟩ := formalMorse_node δ hδ
  exact ⟨M.quotientAlgEquiv.toRingEquiv⟩

/-! ## The periodic matrix resolution -/

/-- The quotient of a commutative ring by the principal ideal generated by `f`. -/
abbrev principalQuotient (R : Type u) [CommRing R] (f : R) :=
  R ⧸ Ideal.span {f}

/-- Reduce a square matrix modulo the principal ideal `(f)`. -/
def quotientMatrix
    {R : Type u} [CommRing R] {n : ℕ} (f : R)
    (M : Matrix (Fin n) (Fin n) R) :
    Matrix (Fin n) (Fin n) (principalQuotient R f) :=
  M.map (Ideal.Quotient.mk (Ideal.span {f}))

/-- Exactness at both alternating terms of a bi-infinite two-periodic
sequence with matrices `B` and `A`. -/
def periodicResolutionExact
    {S : Type u} [CommRing S] {n : ℕ}
    (A B : Matrix (Fin n) (Fin n) S) : Prop :=
  Function.Exact B.mulVecLin A.mulVecLin ∧
    Function.Exact A.mulVecLin B.mulVecLin

/-- A matrix factorization by a nonzerodivisor gives the exact alternating
resolution over the quotient by that nonzerodivisor. -/
theorem periodicMatrixResolution_exact
    {R : Type u} [CommRing R] {n : ℕ}
    (A B : Matrix (Fin n) (Fin n) R) (f : R) (_hn : 1 ≤ n)
    (hAB : A * B = f • (1 : Matrix (Fin n) (Fin n) R))
    (hf : IsRegular f) :
    periodicResolutionExact (quotientMatrix f A) (quotientMatrix f B) := by
  have hdet : A.det * B.det = f ^ n := by
    rw [← Matrix.det_mul, hAB]
    simp
  have hdetreg : IsRegular (A.det * B.det) := hdet.symm ▸ hf.pow n
  have hAdet : IsRegular A.det := hdetreg.of_mul_left
  have hdetB : A.det • B = f • A.adjugate := by
    calc
      A.det • B = (A.adjugate * A) * B := by rw [Matrix.adjugate_mul]; simp
      _ = A.adjugate * (A * B) := by rw [Matrix.mul_assoc]
      _ = A.adjugate * (f • (1 : Matrix (Fin n) (Fin n) R)) := by rw [hAB]
      _ = f • A.adjugate := by simp
  have hBA : B * A = f • (1 : Matrix (Fin n) (Fin n) R) := by
    have hcancel : A.det • (B * A) = A.det • (f • (1 : Matrix (Fin n) (Fin n) R)) := by
      calc
        A.det • (B * A) = (A.det • B) * A := by simp
        _ = (f • A.adjugate) * A := by rw [hdetB]
        _ = f • (A.adjugate * A) := by simp
        _ = f • (A.det • (1 : Matrix (Fin n) (Fin n) R)) := by
          rw [Matrix.adjugate_mul]
        _ = A.det • (f • (1 : Matrix (Fin n) (Fin n) R)) := by
          rw [smul_smul, smul_smul, mul_comm]
    ext i j
    apply hAdet.left
    simpa [smul_eq_mul] using congrArg (fun M => M i j) hcancel
  have h_exact :
      ∀ (M N : Matrix (Fin n) (Fin n) R),
        M * N = f • (1 : Matrix (Fin n) (Fin n) R) →
        N * M = f • (1 : Matrix (Fin n) (Fin n) R) →
        Function.Exact (quotientMatrix f N).mulVecLin
          (quotientMatrix f M).mulVecLin := by
    intro M N hMN hNM
    let q : R →+* principalQuotient R f :=
      Ideal.Quotient.mk (Ideal.span {f})
    have hMNq : quotientMatrix f M * quotientMatrix f N = 0 := by
      change M.map q * N.map q = 0
      rw [← Matrix.map_mul, hMN]
      ext i j
      simp [q]
    have hNMq : quotientMatrix f N * quotientMatrix f M = 0 := by
      change N.map q * M.map q = 0
      rw [← Matrix.map_mul, hNM]
      ext i j
      simp [q]
    apply LinearMap.exact_of_comp_eq_zero_of_ker_le_range
    · rw [← Matrix.mulVecLin_mul, hMNq]
      simp
    · intro x hx
      change (quotientMatrix f M).mulVecLin x = 0 at hx
      have hMkernel : ∀ i, Matrix.mulVec (M.map q) x i = 0 := by
        intro i
        simpa [quotientMatrix, q, Matrix.mulVecLin_apply] using
          congrArg (fun v => v i) hx
      choose y hy using fun i => Ideal.Quotient.mk_surjective (x i)
      have hyq : q ∘ y = x := by
        funext i
        simpa [q] using hy i
      have hMdiv : ∀ i, f ∣ Matrix.mulVec M y i := by
        intro i
        have hzero : q (Matrix.mulVec M y i) = 0 := by
          rw [RingHom.map_mulVec q M y i, hyq]
          exact hMkernel i
        exact (Ideal.Quotient.eq_zero_iff_dvd f (Matrix.mulVec M y i)).mp (by
          simpa [q] using hzero)
      choose z hz using hMdiv
      have hMzy : Matrix.mulVec M y = f • z := by
        funext i
        simpa [Pi.smul_apply, smul_eq_mul] using hz i
      have hNMvec : Matrix.mulVec N (Matrix.mulVec M y) = f • y := by
        calc
          Matrix.mulVec N (Matrix.mulVec M y) = Matrix.mulVec (N * M) y :=
            Matrix.mulVec_mulVec y N M
          _ = Matrix.mulVec (f • (1 : Matrix (Fin n) (Fin n) R)) y := by rw [hNM]
          _ = f • y := by rw [Matrix.smul_mulVec]; simp
      have hcancel : f • Matrix.mulVec N z = f • y := by
        calc
          f • Matrix.mulVec N z = Matrix.mulVec N (f • z) :=
            (Matrix.mulVec_smul N f z).symm
          _ = Matrix.mulVec N (Matrix.mulVec M y) := by rw [← hMzy]
          _ = f • y := hNMvec
      have hyz : Matrix.mulVec N z = y := by
        funext i
        apply hf.left
        simpa [Pi.smul_apply, smul_eq_mul] using
          congrArg (fun v => v i) hcancel
      refine ⟨q ∘ z, ?_⟩
      ext i
      calc
        (quotientMatrix f N).mulVecLin (q ∘ z) i = q (Matrix.mulVec N z i) := by
          symm
          simpa [quotientMatrix, q, Matrix.mulVecLin_apply] using
            RingHom.map_mulVec q N z i
        _ = q (y i) := by rw [hyz]
        _ = x i := by simpa only [Function.comp_apply] using congrFun hyq i
  exact ⟨h_exact A B hAB hBA, h_exact B A hBA hAB⟩

end

end Formalization.Books.Exercises.Unit14
