import Formalization.Books.Algebra.Unit21.OpenAndClosed
import Formalization.Books.Topology.Unit12.QuasiCompactSpacesAndMaps
import Mathlib.RingTheory.Ideal.Quotient.Basic

/-!
# Commutative Algebra, Chapter 22: Connected components of spectra

The topological predicates for intersections of clopens and unions of
connected components are reused from Topology, Chapter 12.  The remaining
ring-theoretic phrase “generated by idempotents” is recorded as a predicate
on ideals, while spectra and their connected components use Mathlib's
canonical `PrimeSpectrum` and `connectedComponent` constructions.
-/

namespace Formalization.Books.Algebra.Unit22

universe u

noncomputable section

/-! ## Ideals generated by idempotents -/

/-- An ideal is generated by idempotents if it is the span of a set of
idempotent elements. -/
def Ideal.IsGeneratedByIdempotents {R : Type u} [CommRing R] (I : Ideal R) : Prop :=
  ∃ S : Set R, (∀ e ∈ S, IsIdempotentElem e) ∧ I = Ideal.span S

/-! ## Closed unions of connected components -/

/-- Closed unions of connected components, intersections of clopens, and
vanishing loci of ideals generated by idempotents are equivalent conditions. -/
theorem closed_union_connected_components_tfae
    {R : Type u} [CommRing R] (T : Set (PrimeSpectrum R)) :
    List.TFAE
      [ IsClosed T ∧
          Formalization.Books.Topology.Unit12.IsUnionOfConnectedComponents T,
        Formalization.Books.Topology.Unit12.IsIntersectionOfClopens T,
    ∃ I : Ideal R,
          Ideal.IsGeneratedByIdempotents I ∧
            T = PrimeSpectrum.zeroLocus (I : Set R) ] := by
  tfae_have 1 ↔ 2 :=
    (Formalization.Books.Topology.Unit12.isIntersectionOfClopens_iff_isClosed_isUnionOfConnectedComponents
      (X := PrimeSpectrum R)).symm
  tfae_have 2 ↔ 3 := by
    constructor
    · intro hT
      rcases hT with ⟨S, hTS, hS⟩
      let A : Set R :=
        {e | IsIdempotentElem e ∧ T ⊆ PrimeSpectrum.zeroLocus ({e} : Set R)}
      refine ⟨Ideal.span A, ?_, ?_⟩
      · exact ⟨A, fun e he => he.1, rfl⟩
      · rw [PrimeSpectrum.zeroLocus_span]
        apply Set.Subset.antisymm
        · intro x hx
          exact (PrimeSpectrum.mem_zeroLocus x A).2 fun e he =>
            (PrimeSpectrum.mem_zeroLocus x ({e} : Set R)).1 (he.2 hx) (by simp)
        · intro x hx
          rw [hTS] at ⊢
          apply Set.mem_sInter.2
          intro U hU
          obtain ⟨e, he, hUe⟩ :=
            PrimeSpectrum.isClopen_iff_zeroLocus.mp (hS U hU)
          have hTU : T ⊆ U := by
            rw [hTS]
            exact fun y hy => Set.mem_sInter.1 hy U hU
          have heA : e ∈ A := ⟨he, by rw [← hUe]; exact hTU⟩
          have hxe : x ∈ PrimeSpectrum.zeroLocus ({e} : Set R) := by
            rw [PrimeSpectrum.mem_zeroLocus]
            exact Set.singleton_subset_iff.mpr
              ((PrimeSpectrum.mem_zeroLocus x A).1 hx heA)
          exact hUe ▸ hxe
    · intro hT
      rcases hT with ⟨I, ⟨S, hS, hI⟩, hTI⟩
      let V : Set (Set (PrimeSpectrum R)) :=
        {U | ∃ e ∈ S, U = PrimeSpectrum.zeroLocus ({e} : Set R)}
      refine ⟨V, ?_, ?_⟩
      · rw [hTI, hI, PrimeSpectrum.zeroLocus_span]
        ext x
        constructor
        · intro hx U hU
          rcases hU with ⟨e, he, rfl⟩
          exact Set.singleton_subset_iff.mpr
            ((PrimeSpectrum.mem_zeroLocus x S).1 hx he)
        · intro hx e he
          exact (PrimeSpectrum.mem_zeroLocus x ({e} : Set R)).1
            (hx _ ⟨e, he, rfl⟩) (by simp)
      · intro U hU
        rcases hU with ⟨e, he, rfl⟩
        exact PrimeSpectrum.isClopen_iff_zeroLocus.mpr ⟨e, hS e he, rfl⟩
  tfae_finish

/-- An ideal generated by idempotents which defines a given vanishing locus is
unique. -/
theorem idempotent_generated_ideal_unique
    {R : Type u} [CommRing R] {T : Set (PrimeSpectrum R)}
    {I J : Ideal R}
    (hI : Ideal.IsGeneratedByIdempotents I)
    (hJ : Ideal.IsGeneratedByIdempotents J)
    (hTI : T = PrimeSpectrum.zeroLocus (I : Set R))
    (hTJ : T = PrimeSpectrum.zeroLocus (J : Set R)) :
    I = J := by
  rcases hI with ⟨S, hS, hSI⟩
  rcases hJ with ⟨U, hU, hUJ⟩
  apply le_antisymm
  · rw [hSI]
    apply Ideal.span_le.2
    intro e he
    by_contra heJ
    obtain ⟨p, hp, hpJ, hpe⟩ :=
      Ideal.exists_le_prime_notMem_of_isIdempotentElem J e (hS e he) heJ
    let q : PrimeSpectrum R := ⟨p, hp⟩
    have hqT : q ∈ T := by
      rw [hTJ]
      exact (PrimeSpectrum.mem_zeroLocus q (J : Set R)).2 hpJ
    have hqI : q ∈ PrimeSpectrum.zeroLocus (I : Set R) := by
      rw [← hTI]
      exact hqT
    have heI : e ∈ I := by
      rw [hSI]
      exact Ideal.subset_span he
    have hqe : e ∈ q.asIdeal := by
      exact (PrimeSpectrum.mem_zeroLocus q (I : Set R)).1 hqI heI
    exact hpe hqe
  · rw [hUJ]
    apply Ideal.span_le.2
    intro e he
    by_contra heI
    obtain ⟨p, hp, hpI, hpe⟩ :=
      Ideal.exists_le_prime_notMem_of_isIdempotentElem I e (hU e he) heI
    let q : PrimeSpectrum R := ⟨p, hp⟩
    have hqT : q ∈ T := by
      rw [hTI]
      exact (PrimeSpectrum.mem_zeroLocus q (I : Set R)).2 hpI
    have hqJ : q ∈ PrimeSpectrum.zeroLocus (J : Set R) := by
      rw [← hTJ]
      exact hqT
    have heJ : e ∈ J := by
      rw [hUJ]
      exact Ideal.subset_span he
    have hqe : e ∈ q.asIdeal := by
      exact (PrimeSpectrum.mem_zeroLocus q (J : Set R)).1 hqJ heJ
    exact hpe hqe

/-! ## Connected components -/

/-- Every connected component of a spectrum is the vanishing locus of an
ideal generated by idempotents, and every idempotent becomes zero or one in
the corresponding quotient. -/
theorem connected_component_eq_zeroLocus_of_idempotent_generated_ideal
    {R : Type u} [CommRing R] (p : PrimeSpectrum R) :
    ∃ I : Ideal R,
      Ideal.IsGeneratedByIdempotents I ∧
        connectedComponent p = PrimeSpectrum.zeroLocus (I : Set R) ∧
          ∀ e : R, IsIdempotentElem e →
            Ideal.Quotient.mk I e = 0 ∨ Ideal.Quotient.mk I e = 1 := by
  let A : Set R :=
    {e | IsIdempotentElem e ∧ p ∈ PrimeSpectrum.zeroLocus ({e} : Set R)}
  refine ⟨Ideal.span A, ⟨A, fun e he => he.1, rfl⟩, ?_, ?_⟩
  · rw [PrimeSpectrum.zeroLocus_span,
      Formalization.Books.Topology.Unit12.connectedComponent_eq_iInter_isClopen_of_compact_prespectral]
    apply Set.Subset.antisymm
    · intro x hx
      apply (PrimeSpectrum.mem_zeroLocus x A).2
      intro e he
      have hcl : IsClopen (PrimeSpectrum.zeroLocus ({e} : Set R)) :=
        PrimeSpectrum.isClopen_iff_zeroLocus.mpr ⟨e, he.1, rfl⟩
      have hxcomp : x ∈ connectedComponent p := by
        rw [Formalization.Books.Topology.Unit12.connectedComponent_eq_iInter_isClopen_of_compact_prespectral]
        exact hx
      have hxe : x ∈ PrimeSpectrum.zeroLocus ({e} : Set R) :=
        hcl.connectedComponent_subset he.2 hxcomp
      exact (PrimeSpectrum.mem_zeroLocus x ({e} : Set R)).1 hxe (by simp)
    · intro x hx
      apply Set.mem_iInter.2
      intro s
      obtain ⟨e, he, hse⟩ :=
        PrimeSpectrum.isClopen_iff_zeroLocus.mp s.2.1
      have heA : e ∈ A := ⟨he, by rw [← hse]; exact s.2.2⟩
      have hxe : x ∈ PrimeSpectrum.zeroLocus ({e} : Set R) := by
        apply (PrimeSpectrum.mem_zeroLocus x ({e} : Set R)).2
        exact Set.singleton_subset_iff.mpr
          ((PrimeSpectrum.mem_zeroLocus x A).1 hx heA)
      exact hse ▸ hxe
  · intro e he
    by_cases heA : e ∈ A
    · left
      exact Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span heA)
    · right
      have hep : e ∉ p.asIdeal := by
        intro hep
        apply heA
        refine ⟨he, ?_⟩
        apply (PrimeSpectrum.mem_zeroLocus p ({e} : Set R)).2
        exact Set.singleton_subset_iff.mpr hep
      have hpe : 1 - e ∈ p.asIdeal := by
        apply (p.2.mem_or_mem_of_mul_eq_zero ?_).resolve_left hep
        rw [mul_sub, mul_one, he.eq, sub_self]
      have h1eA : 1 - e ∈ A := by
        refine ⟨he.one_sub, ?_⟩
        apply (PrimeSpectrum.mem_zeroLocus p ({1 - e} : Set R)).2
        exact Set.singleton_subset_iff.mpr hpe
      have hz : Ideal.Quotient.mk (Ideal.span A) (1 - e) = 0 :=
        Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span h1eA)
      calc
        Ideal.Quotient.mk (Ideal.span A) e =
            Ideal.Quotient.mk (Ideal.span A) e +
              Ideal.Quotient.mk (Ideal.span A) (1 - e) := by rw [hz, add_zero]
        _ = Ideal.Quotient.mk (Ideal.span A) (e + (1 - e)) := by rw [map_add]
        _ = Ideal.Quotient.mk (Ideal.span A) 1 := by simp

end

end Formalization.Books.Algebra.Unit22
