import Formalization.Books.Fields.Unit08.AlgebraicExtensions
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.RingTheory.AlgebraicIndependent.Adjoin
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis

/-!
# Fields, Chapter 26: Transcendence

The source's algebraic independence, transcendence bases, and transcendence
degree are Mathlib's `AlgebraicIndependent`, `IsTranscendenceBasis`, and
`Algebra.trdeg`.  This file adds the source-facing purely transcendental and
algebraically-closed-in predicates and the induced fraction-field extension
interface; fraction fields, generated fields, and relative algebraic closures
otherwise use Mathlib's canonical constructions.

The source's Riemann-surface example needs analytic Riemann surfaces,
meromorphic function fields, and the corresponding categories.  Those
interfaces are not present in this project, so the missing analytic and
categorical claims are explicitly recorded below while their field-side
finitely-generated/transcendence-degree condition is formalized.
-/

namespace Formalization.Books.Fields.Unit26

noncomputable section

open Set

universe u v w z

/-! ## Basic definitions -/

/- The source's `k[X_i; i ∈ I]` is `MvPolynomial I k`, and its field of
   fractions is the canonical `FractionRing` construction. -/
abbrev rationalFunctionField (k : Type u) (ι : Type v) [CommRing k] :=
  FractionRing (MvPolynomial ι k)

/- Mathlib's `AlgebraicIndependent` is the injectivity of multivariate
   polynomial evaluation, so no parallel algebraic-independence predicate is
   introduced here. -/

/- The source's purely transcendental extension is an algebra equivalence to
   a rational function field in some family of indeterminates. -/
def IsPurelyTranscendental (k : Type u) (K : Type v)
    [Field k] [Field K] [Algebra k K] : Prop :=
  ∃ ι : Type w, Nonempty (rationalFunctionField k ι ≃ₐ[k] K)

/- Mathlib's `IsTranscendenceBasis` is the canonical maximal algebraically
   independent family.  Its theorem
   `isTranscendenceBasis_iff_algebraicIndependent_isAlgebraic` gives the
   source's condition that the extension over the generated field is
   algebraic, so no parallel chapter-local interface is needed. -/

/-! ## The first example and transcendence bases -/

def piComplex : ℂ := (Real.pi : ℝ)

abbrev piField : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ ({piComplex} : Set ℂ)

/-- The textbook's transcendence assertion for `π` over `ℚ`. -/
theorem pi_transcendental_over_rationals : Transcendental ℚ piComplex := by
  change ¬ IsAlgebraic ℚ ((Real.pi : ℝ) : ℂ)
  exact Formalization.Books.Fields.Unit08.pi_is_not_algebraic_number

/-- The simple field generated by `π` is a rational function field in one variable. -/
theorem pi_field_isomorphic_to_rational_function_field :
    Nonempty (@AlgEquiv ℚ (RatFunc ℚ)
      (IntermediateField.adjoin ℚ ({piComplex} : Set ℂ))
      _ _ _ (RatFunc.instAlgebraOfPolynomial ℚ ℚ)
        (IntermediateField.adjoin ℚ ({piComplex} : Set ℂ)).algebra') := by
  exact ⟨Formalization.Books.Fields.Unit08.simple_extension_ratFunc_equiv
    pi_transcendental_over_rationals⟩

/-- `ℚ(π)` is purely transcendental over `ℚ`. -/
theorem pi_field_is_purely_transcendental :
    letI : Algebra ℚ piField := piField.algebra'
    IsPurelyTranscendental ℚ piField := by
  sorry

/-- A transcendence basis exists for every field extension. -/
theorem transcendence_basis_exists
    (F : Type u) (E : Type v) [Field F] [Field E] [Algebra F E] :
    ∃ (ι : Type v) (x : ι → E), IsTranscendenceBasis F x := by
  let _ : FaithfulSMul F E :=
    (faithfulSMul_iff_algebraMap_injective F E).mpr
      Formalization.Books.Fields.Unit06.field_extension_algebraMap_injective
  exact exists_isTranscendenceBasis' F E

/-- Any two transcendence bases of a field extension have the same cardinality. -/
theorem transcendence_basis_cardinality
    {F : Type u} {E : Type v} [Field F] [Field E] [Algebra F E]
    {ι : Type w} {ι' : Type z} {x : ι → E} {y : ι' → E}
    (hx : IsTranscendenceBasis F x) (hy : IsTranscendenceBasis F y) :
    Cardinal.lift.{z} (Cardinal.mk ι) = Cardinal.lift.{w} (Cardinal.mk ι') := by
  exact hx.lift_cardinalMk_eq hy

/-! ## Transcendence degree -/

/- The source's cardinality definition is Mathlib's `Algebra.trdeg`; a basis
   computes it by the canonical `cardinalMk_eq_trdeg` theorem. -/
theorem transcendence_degree_eq_basis_cardinality_lifted
    {F : Type u} {E : Type v} [Field F] [Field E] [Algebra F E]
    {ι : Type w} {x : ι → E} (hx : IsTranscendenceBasis F x) :
    Cardinal.lift.{v} (Cardinal.mk ι) =
      Cardinal.lift.{w} (Algebra.trdeg F E) := by
  exact hx.lift_cardinalMk_eq_trdeg

theorem transcendence_degree_eq_basis_cardinality
    {F : Type u} {E : Type v} [Field F] [Field E] [Algebra F E]
    {ι : Type v} {x : ι → E} (hx : IsTranscendenceBasis F x) :
    Algebra.trdeg F E = Cardinal.mk ι := by
  exact hx.cardinalMk_eq_trdeg.symm

/-- The transcendence-degree tower formula. -/
theorem transcendence_degree_tower
    {k K L : Type u} [Field k] [Field K] [Field L]
    [Algebra k K] [Algebra K L] [Algebra k L] [IsScalarTower k K L] :
    Algebra.trdeg k L = Algebra.trdeg K L + Algebra.trdeg k K := by
  rw [add_comm (Algebra.trdeg K L) (Algebra.trdeg k K)]
  exact (trdeg_add_eq k K (A := L)).symm

/-! ## The `e` and `π` example -/

def eulerNumber : ℂ := (Real.exp 1 : ℝ)

abbrev eulerPiField : IntermediateField ℚ ℂ :=
  IntermediateField.adjoin ℚ
    ({eulerNumber, piComplex} : Set ℂ)

/-- Euler's number is transcendental over the rationals. -/
theorem euler_number_transcendental_over_rationals :
    Transcendental ℚ eulerNumber := by
  sorry

/-- The field generated by `e` and `π` has transcendence degree at least one. -/
theorem euler_pi_transcendence_degree_at_least_one :
    letI : Algebra ℚ eulerPiField := eulerPiField.algebra'
    1 ≤ Algebra.trdeg ℚ eulerPiField := by
  sorry

/-- Algebraic independence of `e` and `π` gives transcendence degree two. -/
theorem euler_pi_transcendence_degree_eq_two_of_algebraically_independent
    (h : AlgebraicIndependent ℚ ![eulerNumber, piComplex]) :
    letI : Algebra ℚ eulerPiField := eulerPiField.algebra'
    Algebra.trdeg ℚ eulerPiField = 2 := by
  sorry

/- The source records that the algebraic independence of `e` and `π` is an
   open problem; no declaration asserting either side of that open question
   is introduced. -/

/-! ## Non-uniqueness of transcendence bases -/

/-- The rational function field has the displayed transcendence basis `{t}`. -/
theorem rational_function_t_is_transcendence_basis
    (F : Type u) [Field F] :
    letI : Algebra F (RatFunc F) := RatFunc.instAlgebraOfPolynomial F F
    IsTranscendenceBasis F (fun _ : Fin 1 => (RatFunc.X : RatFunc F)) := by
  sorry

/-- The rational function field has the displayed transcendence basis `{t²}`. -/
theorem rational_function_t_sq_is_transcendence_basis
    (F : Type u) [Field F] :
    letI : Algebra F (RatFunc F) := RatFunc.instAlgebraOfPolynomial F F
    IsTranscendenceBasis F (fun _ : Fin 1 => (RatFunc.X : RatFunc F) ^ 2) := by
  sorry

/-- The extension `F(t) / F(t²)` is algebraic. -/
theorem rational_function_is_algebraic_over_square_subfield
    (F : Type u) [Field F] :
    letI : Algebra F (RatFunc F) := RatFunc.instAlgebraOfPolynomial F F
    Algebra.IsAlgebraic
      (IntermediateField.adjoin F ({(RatFunc.X : RatFunc F) ^ 2} : Set (RatFunc F)))
      (RatFunc F) := by
  sorry

/-- The two displayed transcendence bases are genuinely different. -/
theorem rational_function_transcendence_basis_not_unique
    (F : Type u) [Field F] :
    letI : Algebra F (RatFunc F) := RatFunc.instAlgebraOfPolynomial F F
    IsTranscendenceBasis F (fun _ : Fin 1 => (RatFunc.X : RatFunc F)) ∧
      IsTranscendenceBasis F (fun _ : Fin 1 => (RatFunc.X : RatFunc F) ^ 2) ∧
      Set.range (fun _ : Fin 1 => (RatFunc.X : RatFunc F)) ≠
        Set.range (fun _ : Fin 1 => (RatFunc.X : RatFunc F) ^ 2) := by
  sorry

/-- Every field extension has an algebraic-over-purely-transcendental
    intermediate field, after choosing a transcendence basis. -/
theorem exists_purely_transcendental_intermediateField_with_algebraic_top
    {F : Type u} {E : Type v} [Field F] [Field E] [Algebra F E] :
    ∃ K : IntermediateField F E,
      (letI : Algebra F K := K.algebra'
       IsPurelyTranscendental F K) ∧ Algebra.IsAlgebraic K E := by
  sorry

/-! ## Function fields of curves -/

/- The source's Riemann-surface assertions concern compact Riemann surfaces,
   meromorphic function fields, holomorphic maps, and an anti-equivalence of
   categories.  This project has no corresponding analytic or categorical
   interfaces, so those assertions are accounted for here without inventing
   an unsupported model. -/

/- The field-side object class in both the analytic and algebraic statements
   is exactly the conjunction of finite generation and transcendence degree
   one. -/
def IsFinitelyGeneratedTranscendenceDegreeOne
    (k : Type u) (K : Type v) [Field k] [Field K] [Algebra k K] : Prop :=
  Algebra.EssFiniteType k K ∧ Algebra.trdeg k K = 1

/-! ## Algebraic closure in a field extension -/

/- Mathlib's `IntermediateField.algebraicClosure` is precisely the source's
   algebraic closure of `k` in `K`. -/
theorem mem_relative_algebraic_closure_iff
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K] (x : K) :
    x ∈ algebraicClosure k K ↔ IsAlgebraic k x := by
  exact mem_algebraicClosure_iff

/- The elementwise condition in the source is not otherwise packaged in the
   imported API, so it is defined directly. -/
def AlgebraicallyClosedIn
    (k : Type u) (K : Type v) [Field k] [Field K] [Algebra k K] : Prop :=
  ∀ x : K, IsAlgebraic k x → ∃ y : k, algebraMap k K y = x

/-- The source's elementwise condition is equivalent to trivial relative
    algebraic closure. -/
theorem algebraicallyClosedIn_iff_relative_algebraic_closure_eq_bot
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K] :
    AlgebraicallyClosedIn k K ↔
      algebraicClosure k K = (⊥ : IntermediateField k K) := by
  sorry

/-! ## Finite extensions of purely transcendental fields -/

/- The coefficient extension on multivariate polynomial rings, followed by
   localization at nonzero elements, is the induced extension in the source. -/
noncomputable def rationalFunctionFieldExtensionMap
    (k : Type u) (k' : Type v) [Field k] [Field k'] [Algebra k k'] (ι : Type w) :
    rationalFunctionField k ι →+* rationalFunctionField k' ι :=
  IsFractionRing.map
    (j := (MvPolynomial.map (algebraMap k k') :
      MvPolynomial ι k →+* MvPolynomial ι k'))
    (MvPolynomial.map_injective _
      Formalization.Books.Fields.Unit06.field_extension_algebraMap_injective)

@[instance_reducible] noncomputable def rationalFunctionFieldExtensionAlgebra
    (k : Type u) (k' : Type v) [Field k] [Field k'] [Algebra k k'] (ι : Type w) :
    Algebra (rationalFunctionField k ι) (rationalFunctionField k' ι) :=
  RingHom.toAlgebra (rationalFunctionFieldExtensionMap k k' ι)

/-- A finite coefficient extension remains finite after adjoining any finite family
    of indeterminates and passing to fraction fields, with the same degree. -/
theorem finite_purely_transcendental_extension_degree
    (k k' : Type u) [Field k] [Field k'] [Algebra k k']
    [FiniteDimensional k k'] (ι : Type u) [Finite ι] :
    letI : Algebra (rationalFunctionField k ι) (rationalFunctionField k' ι) :=
      rationalFunctionFieldExtensionAlgebra k k' ι
    Formalization.Books.Fields.Unit07.fieldExtensionDegree
          (rationalFunctionField k ι) (rationalFunctionField k' ι) =
        Formalization.Books.Fields.Unit07.fieldExtensionDegree k k' ∧
      Formalization.Books.Fields.Unit07.fieldExtensionDegree
          (rationalFunctionField k ι) (rationalFunctionField k' ι) <
        Cardinal.aleph0 := by
  sorry

/-- The relative algebraic closure of the base field in a finitely generated
    field extension is finite over the base. -/
theorem relative_algebraic_closure_finite_of_finitely_generated
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    [Algebra.EssFiniteType k K] :
    Module.Finite k (algebraicClosure k K) := by
  sorry

end

end Formalization.Books.Fields.Unit26
