import Formalization.Books.Algebra.Unit69.QuasiRegularSequences
import Formalization.Books.Algebra.Unit103.CohenMacaulayModules
import Mathlib.Algebra.Colimit.DirectLimit
import Mathlib.RingTheory.LocalRing.RingHom.Basic
import Mathlib.RingTheory.Regular.Free
import Mathlib.RingTheory.RegularLocalRing.Defs

/-!
# Commutative Algebra, Chapter 106: Regular local rings

The source's regular-local property is Mathlib's `IsRegularLocalRing`.  The
associated graded ring is represented by the associated graded target from
Chapter 69; in particular, its polynomial description is stated as the
corresponding linear equivalence over the residue quotient.
-/

namespace Formalization.Books.Algebra.Unit106

open Formalization.Books.Algebra.Unit103
open IsLocalRing

universe u v

noncomputable section

/-! ## Generators and the associated graded ring -/

/-- A list is a minimal generating list for an ideal when no entry is generated
by the remaining entries. -/
def IsMinimalIdealGeneratingList
    {R : Type u} [CommRing R] (I : Ideal R) (xs : List R) : Prop :=
  Ideal.ofList xs = I ∧
    ∀ i : Fin xs.length,
      xs.get i ∉ Ideal.ofList (xs.eraseIdx i.1)

/-- The associated graded ring of a regular local ring is polynomial over its
residue field.  Chapter 69's `quasiRegularTarget` is the established
degreewise direct-sum representation of the associated graded object. -/
theorem regular_graded
    {R : Type u} [CommRing R] [IsRegularLocalRing R]
    (d : ℕ) (hd : ringKrullDim R = d)
    (xs : List R)
    (hxs : IsMinimalIdealGeneratingList (maximalIdeal R) xs)
    (hxd : xs.length = d) :
    Nonempty
      (MvPolynomial (Fin d) (R ⧸ maximalIdeal R) ≃ₗ[R ⧸ maximalIdeal R]
        Formalization.Books.Algebra.Unit69.quasiRegularTarget R R
          (maximalIdeal R)) := by
  sorry

/-! ## Basic properties -/

/-- A regular local ring is a domain. -/
theorem regular_domain
    {R : Type u} [CommRing R] [IsRegularLocalRing R] :
    IsDomain R := by
  sorry

/-- A minimal generating list of the maximal ideal is a regular sequence; all
successive quotients are regular local of the expected dimension, so the ring
is Cohen--Macaulay. -/
theorem regular_ring_CM
    {R : Type u} [CommRing R] [IsRegularLocalRing R]
    (xs : List R)
    (hxs : IsMinimalIdealGeneratingList (maximalIdeal R) xs) :
    RingTheory.Sequence.IsRegular R xs ∧
      (∀ c : ℕ, c ≤ xs.length →
        IsRegularLocalRing (R ⧸ Ideal.ofList (xs.take c)) ∧
          ringKrullDim (R ⧸ Ideal.ofList (xs.take c)) = xs.length - c) ∧
      IsCohenMacaulay R R := by
  sorry

/-- If both a regular local ring and one of its quotients are regular local,
the quotient ideal is generated by an initial segment of a minimal generating
list of the maximal ideal. -/
theorem regular_quotient_regular
    {R : Type u} [CommRing R] [IsRegularLocalRing R]
    (I : Ideal R) (hI : IsRegularLocalRing (R ⧸ I)) :
    ∃ xs : List R, ∃ c : ℕ,
      IsMinimalIdealGeneratingList (maximalIdeal R) xs ∧
        c ≤ xs.length ∧ I = Ideal.ofList (xs.take c) := by
  sorry

/-! ## Freeness and Cohen--Macaulay modules -/

/-- A finite module that is regular in `x` is free when its quotient by `x` is
free over the quotient ring. -/
theorem free_mod_x
    {R M : Type u} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (x : R) (hx : x ∈ maximalIdeal R)
    (hreg : IsSMulRegular M x)
    (hfree : Module.Free (R ⧸ Ideal.span ({x} : Set R)) (QuotSMulTop x M)) :
    Module.Free R M := by
  sorry

/-- Every maximal Cohen--Macaulay module over a regular local ring is free. -/
theorem regular_mcm_free
    {R M : Type u} [CommRing R] [IsRegularLocalRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (hM : IsMaximalCohenMacaulay R M) :
    Module.Free R M := by
  sorry

/-! ## Cutting by regular sequences -/

/-- A nonzerodivisor whose quotient is regular local lifts regularity to the
original Noetherian local ring. -/
theorem regular_local_of_regular_element
    {R : Type u} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    (x : R) (hx : x ∈ maximalIdeal R)
    (hreg : IsSMulRegular R x)
    (hquot : IsRegularLocalRing (R ⧸ Ideal.span ({x} : Set R))) :
    IsRegularLocalRing R := by
  sorry

/-- The preceding lifting statement for a regular sequence and its quotient. -/
theorem regular_local_of_regular_sequence
    {R : Type u} [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    (xs : List R) (hxs : RingTheory.Sequence.IsRegular R xs)
    (hquot : IsRegularLocalRing (R ⧸ Ideal.ofList xs)) :
    IsRegularLocalRing R := by
  sorry

/-! ## Directed colimits -/

/-- A Noetherian directed colimit of regular local rings along local maps is
regular local. -/
theorem colimit_regular
    {ι : Type u} [Preorder ι] [Nonempty ι] [IsDirectedOrder ι]
    {A : ι → Type v} [∀ i, CommRing (A i)]
    (f : ∀ i j, i ≤ j → A i →+* A j)
    [DirectedSystem A (f · · ·)]
    (hlocal : ∀ i j (hij : i ≤ j), IsLocalHom (f i j hij))
    (hregular : ∀ i, IsRegularLocalRing (A i))
    (hnoetherian : IsNoetherianRing (DirectLimit A f)) :
    IsRegularLocalRing (DirectLimit A f) := by
  sorry

end

end Formalization.Books.Algebra.Unit106
