import Formalization.Books.Algebra.Unit25.ZerodivisorsAndTotalRingsOfFractions
import Formalization.Books.Algebra.Unit50.ValuationRings
import Formalization.Books.Algebra.Unit57.Proj
import Mathlib.Algebra.Colimit.DirectLimit
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.BaseChange
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.ReesAlgebra
import Mathlib.RingTheory.Spectrum.Prime.RingHom

/-!
# Commutative Algebra, Chapter 70: Blow up algebras

The Rees algebra uses Mathlib's canonical subalgebra model of
`R[It] = ⨁ₙ Iⁿtⁿ`.  An affine chart is represented by the canonical subalgebra
of the localization generated by the fractions `x/a` with `x ∈ I`.  This is
the standard ring-theoretic presentation of the degree-zero chart and exposes
the localization and torsion APIs used by the statements below.
-/

namespace Formalization.Books.Algebra.Unit70

open Formalization.Books.Algebra.Unit25
open Formalization.Books.Algebra.Unit50
open Set
open scoped BigOperators DirectSum Pointwise Polynomial TensorProduct

universe u v w

noncomputable section

/-! ## The Rees algebra and affine charts -/

/- Mathlib's `reesAlgebra I` is the canonical subalgebra of `R[X]` used for
   the source's Rees algebra. -/

/-- The element represented by `x` in degree `n` of the Rees algebra. -/
def reesElement {R : Type u} [CommRing R] (I : Ideal R) (n : ℕ) (x : R)
    (hx : x ∈ I ^ n) : _root_.reesAlgebra I :=
  ⟨Polynomial.monomial n x, _root_.reesAlgebra.monomial_mem.mpr hx⟩

/-- The degree-one Rees element attached to an element of the ideal. -/
def reesDegreeOneElement {R : Type u} [CommRing R] (I : Ideal R) (a : I) :
    _root_.reesAlgebra I :=
  reesElement I 1 a.1 (by rw [pow_one]; exact a.2)

/-- The set of fractions `x/a` used to generate an affine blowup chart. -/
def affineBlowupGeneratorSet {R : Type u} [CommRing R] (I : Ideal R) (a : R) :
    Set (Localization.Away a) :=
  {z | ∃ x : R, x ∈ I ∧
    z = algebraMap R (Localization.Away a) x *
      IsLocalization.Away.invSelf a}

/-- The affine blowup algebra `R[I/a]`, realized as a subalgebra of `R_a`. -/
def affineBlowup {R : Type u} [CommRing R] (I : Ideal R) (a : R) :
    Subalgebra R (Localization.Away a) :=
  Algebra.adjoin R (affineBlowupGeneratorSet I a)

/-- The canonical generator `x/a` as an element of the affine blowup algebra. -/
def affineBlowupGenerator {R : Type u} [CommRing R] (I : Ideal R) (a : R)
    (x : I) : affineBlowup I a :=
  ⟨algebraMap R (Localization.Away a) x.1 *
      IsLocalization.Away.invSelf a,
    Algebra.subset_adjoin ⟨x.1, x.2, rfl⟩⟩

/-- The localization representative `x/a^n` in `R_a`. -/
def affineBlowupRepresentative {R : Type u} [CommRing R] (a : R)
    (n : ℕ) (x : R) : Localization.Away a :=
  Localization.mk x ⟨a ^ n, (Submonoid.mem_powers_iff _ _).2 ⟨n, rfl⟩⟩

/-- The equality relation on the representatives used for an affine chart. -/
theorem affineBlowupRepresentative_eq_iff
    {R : Type u} [CommRing R] (I : Ideal R) (a : R)
    {n m : ℕ} {x y : R} (_ : x ∈ I ^ n) (_ : y ∈ I ^ m) :
    affineBlowupRepresentative a n x = affineBlowupRepresentative a m y ↔
      ∃ k : ℕ, a ^ k * (a ^ m * x - a ^ n * y) = 0 := by
  simp only [affineBlowupRepresentative]
  rw [Localization.mk_eq_mk']
  rw [IsLocalization.eq]
  constructor
  · rintro ⟨c, hc⟩
    obtain ⟨k, hk⟩ := (Submonoid.mem_powers_iff _ _).1 c.2
    refine ⟨k, ?_⟩
    rw [mul_sub, sub_eq_zero]
    rw [← hk] at hc
    exact hc
  · rintro ⟨k, hk⟩
    refine ⟨⟨a ^ k, (Submonoid.mem_powers_iff _ _).2 ⟨k, rfl⟩⟩, ?_⟩
    rw [mul_sub, sub_eq_zero] at hk
    exact hk

/-- Every valid numerator-denominator representative belongs to the chart. -/
theorem affineBlowupRepresentative_mem
    {R : Type u} [CommRing R] (I : Ideal R) (a : R)
    {n : ℕ} {x : R} (hx : x ∈ I ^ n) :
    affineBlowupRepresentative a n x ∈ affineBlowup I a := by
  have hrep (n : ℕ) (x : R) :
      affineBlowupRepresentative a n x =
          algebraMap R (Localization.Away a) x *
          IsLocalization.Away.invSelf a ^ n := by
    rw [affineBlowupRepresentative, Localization.mk_eq_mk',
      IsLocalization.mk'_eq_mul_mk'_one]
    simp [IsLocalization.Away.invSelf, ← IsLocalization.mk'_pow]
  induction hx using Submodule.pow_induction_on_left' with
  | algebraMap r =>
      simp [hrep]
  | add x y i hx hy ihx ihy =>
      have h := (affineBlowup I a).add_mem ihx ihy
      simp [hrep, add_mul] at h ⊢
      exact h
  | mem_mul m hm i x hx ih =>
      have hgen := (affineBlowupGenerator I a ⟨m, hm⟩).property
      have hprod := (affineBlowup I a).mul_mem hgen ih
      simp [hrep, affineBlowupGenerator, pow_succ, mul_assoc, mul_left_comm, mul_comm] at hprod ⊢
      exact hprod

/-- The ideal of elements killed by a power of `b`, represented canonically as
the kernel of the localization map. -/
def powerTorsionIdeal (R : Type u) [CommRing R] (b : R) : Ideal R :=
  RingHom.ker (algebraMap R (Localization.Away b))

/-- Membership in the kernel presentation of power torsion. -/
theorem mem_powerTorsionIdeal_iff
    {R : Type u} [CommRing R] (b x : R) :
    x ∈ powerTorsionIdeal R b ↔ ∃ n : ℕ, b ^ n * x = 0 := by
  rw [powerTorsionIdeal, RingHom.mem_ker]
  constructor
  · intro hx
    obtain ⟨s, hs⟩ :=
      (IsLocalization.map_eq_zero_iff (Submonoid.powers b)
        (Localization.Away b) x).mp hx
    obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff _ _).mp s.2
    exact ⟨n, by simpa [hn] using hs⟩
  · rintro ⟨n, hn⟩
    apply (IsLocalization.map_eq_zero_iff (Submonoid.powers b)
      (Localization.Away b) x).mpr
    refine ⟨⟨b ^ n, (Submonoid.mem_powers_iff _ _).2 ⟨n, rfl⟩⟩, ?_⟩
    simpa using hn

/-- The chosen denominator is regular in an affine blowup chart. -/
theorem affineBlowup_isRegular
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (_ : a ∈ I) :
    IsRegular (algebraMap R (affineBlowup I a) a) := by
  rw [isRegular_iff]
  constructor
  · intro x y hxy
    apply Subtype.ext
    apply (IsUnit.mul_right_inj (IsLocalization.Away.algebraMap_isUnit a)).mp
    simpa [Subalgebra.coe_algebraMap, IsScalarTower.algebraMap_apply] using
      congrArg (fun z : affineBlowup I a => (z : Localization.Away a)) hxy
  · intro x y hxy
    apply Subtype.ext
    apply (IsUnit.mul_left_inj (IsLocalization.Away.algebraMap_isUnit a)).mp
    simpa [Subalgebra.coe_algebraMap, IsScalarTower.algebraMap_apply] using
      congrArg (fun z : affineBlowup I a => (z : Localization.Away a)) hxy

theorem affineBlowup_map_ideal_eq_span
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (ha : a ∈ I) :
    Ideal.map (algebraMap R (affineBlowup I a)) I =
      Ideal.span {algebraMap R (affineBlowup I a) a} := by
  apply le_antisymm
  · apply Ideal.map_le_of_le_comap
    intro x hx
    rw [Ideal.mem_comap]
    have hdiv :
        algebraMap R (affineBlowup I a) x =
          algebraMap R (affineBlowup I a) a *
            affineBlowupGenerator I a ⟨x, hx⟩ := by
      apply Subtype.ext
      change algebraMap R (Localization.Away a) x =
        algebraMap R (Localization.Away a) a *
          (algebraMap R (Localization.Away a) x *
            IsLocalization.Away.invSelf a)
      calc
        algebraMap R (Localization.Away a) x =
            1 * algebraMap R (Localization.Away a) x := by rw [one_mul]
        _ = (algebraMap R (Localization.Away a) a *
            IsLocalization.Away.invSelf a) *
              algebraMap R (Localization.Away a) x := by
          rw [IsLocalization.Away.mul_invSelf]
        _ = algebraMap R (Localization.Away a) a *
            (algebraMap R (Localization.Away a) x *
              IsLocalization.Away.invSelf a) := by ring
    rw [hdiv]
    simpa [mul_comm] using
      (Ideal.mul_mem_left (Ideal.span {algebraMap R (affineBlowup I a) a})
        (affineBlowupGenerator I a ⟨x, hx⟩)
        (Ideal.subset_span (Set.mem_singleton _)))
  · apply Ideal.span_le.2
    intro x hx
    rw [Set.mem_singleton_iff.mp hx]
    exact Ideal.mem_map_of_mem _ ha

theorem affineBlowup_localization_equiv
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (ha : a ∈ I) :
    Nonempty
      (Localization.Away (algebraMap R (affineBlowup I a) a) ≃+*
        Localization.Away a) := by
  let A := affineBlowup I a
  let L := Localization.Away a
  let haA := algebraMap R A a
  have hunit : IsUnit (algebraMap A L haA) := by
    rw [← IsScalarTower.algebraMap_apply R A L a]
    exact IsLocalization.Away.algebraMap_isUnit a
  haveI : IsLocalization.Away haA L :=
    IsLocalization.Away.mk haA hunit
      (fun z => by
        obtain ⟨n, r, hzr⟩ := IsLocalization.Away.surj a z
        refine ⟨n, algebraMap R A r, ?_⟩
        change z * (algebraMap A L (algebraMap R A a)) ^ n =
          algebraMap A L (algebraMap R A r)
        rw [← IsScalarTower.algebraMap_apply R A L a,
          ← IsScalarTower.algebraMap_apply R A L r]
        exact hzr)
      (fun x y hxy => by
        have hxy' : (x : L) = (y : L) := by simpa using hxy
        have hxy'' : x = y := by
          apply Subtype.ext
          exact hxy'
        exact ⟨0, by simp [hxy'']⟩)
  exact ⟨(IsLocalization.algEquiv (Submonoid.powers haA)
    (Localization.Away haA) L).toRingEquiv⟩

/-! ## Base change -/

/-- The torsion ideal occurring in the base-change description. -/
def baseChangeTorsionIdeal
    {R : Type u} {S : Type v} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) (a : R) :
    letI : Algebra R S := f.toAlgebra
    Ideal (S ⊗[R] affineBlowup I a) :=
  letI : Algebra R S := f.toAlgebra
  powerTorsionIdeal _ (algebraMap S (S ⊗[R] affineBlowup I a) (f a))

/-- Affine blowup commutes with base change after quotienting by the new
denominator's power torsion. -/
theorem affineBlowup_baseChange
    {R : Type u} {S : Type v} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) {a : R} (ha : a ∈ I) :
    letI : Algebra R S := f.toAlgebra
    Nonempty
      ((S ⊗[R] affineBlowup I a) ⧸ baseChangeTorsionIdeal f I a ≃+*
        affineBlowup (Ideal.map f I) (f a)) := by
  letI : Algebra R S := f.toAlgebra
  let A := affineBlowup I a
  let L := Localization.Away a
  let C := affineBlowup (Ideal.map f I) (f a)
  let hA : A →ₐ[R] L :=
    { toFun := fun x => x.1
      map_one' := rfl
      map_mul' := by intro x y; rfl
      map_zero' := rfl
      map_add' := by intro x y; rfl
      commutes' := by
        intro r; rfl }
  let haA := algebraMap R A a
  have hunit : IsUnit (algebraMap A L haA) := by
    rw [← IsScalarTower.algebraMap_apply R A L a]
    exact IsLocalization.Away.algebraMap_isUnit a
  haveI : IsLocalization.Away haA L :=
    IsLocalization.Away.mk haA hunit
      (fun z => by
        obtain ⟨n, r, hzr⟩ := IsLocalization.Away.surj a z
        refine ⟨n, algebraMap R A r, ?_⟩
        change z * (algebraMap A L (algebraMap R A a)) ^ n =
          algebraMap A L (algebraMap R A r)
        rw [← IsScalarTower.algebraMap_apply R A L a,
          ← IsScalarTower.algebraMap_apply R A L r]
        exact hzr)
      (fun x y hxy => by
        have hxy' : (x : L) = (y : L) := by simpa using hxy
        have hxy'' : x = y := by
          apply Subtype.ext
          exact hxy'
        exact ⟨0, by simp [hxy'']⟩)
  let M' := Algebra.algebraMapSubmonoid S (Submonoid.powers a)
  let L' := Localization M'
  let e1 : (S ⊗[R] L) ≃ₐ[S] L' :=
    Localization.tensorLeftAlgEquiv (Submonoid.powers a) S
  haveI : IsLocalization M' (Localization.Away (f a)) := by
    rw [show M' = Submonoid.powers (f a) by
      ext z
      constructor
      · rintro ⟨x, ⟨n, rfl⟩, rfl⟩
        exact ⟨n, by simp [RingHom.algebraMap_toAlgebra]⟩
      · rintro ⟨n, rfl⟩
        exact ⟨a ^ n, ⟨n, rfl⟩, by simp [RingHom.algebraMap_toAlgebra]⟩]
    infer_instance
  let e2 : L' ≃ₐ[S] Localization.Away (f a) :=
    IsLocalization.algEquiv M' L' (Localization.Away (f a))
  let e : (S ⊗[R] L) ≃ₐ[S] Localization.Away (f a) := e1.trans e2
  let hAL : A →ₐ[R] (S ⊗[R] L) :=
    (Algebra.TensorProduct.includeRight (R := R) (A := S)).comp hA
  let h0 : (S ⊗[R] A) →ₐ[S] (S ⊗[R] L) :=
    Algebra.TensorProduct.lift
      (Algebra.TensorProduct.includeLeft (R := R) (A := S) (B := L))
      hAL (fun _ _ => Commute.all _ _)
  let h : (S ⊗[R] A) →ₐ[S] Localization.Away (f a) :=
    e.toAlgHom.comp h0
  let q : R →+* Localization.Away (f a) :=
    (algebraMap S (Localization.Away (f a))).comp f
  have hq : IsUnit (q a) := by
    change IsUnit (algebraMap S (Localization.Away (f a)) (f a))
    exact IsLocalization.Away.algebraMap_isUnit (f a)
  let gL : L →+* Localization.Away (f a) :=
    IsLocalization.Away.lift (x := a) (S := L)
      (P := Localization.Away (f a)) (g := q) hq
  let j : L →+* Localization.Away (f a) :=
    e.toRingEquiv.toRingHom.comp
      (Algebra.TensorProduct.includeRight (R := R) (A := S)).toRingHom
  have hj : j = gL := by
    apply IsLocalization.ringHom_ext (Submonoid.powers a)
    ext r
    have hgr : gL (algebraMap R L r) = q r := by
      dsimp [gL]
      exact IsLocalization.Away.lift_eq a hq r
    change j (algebraMap R L r) = gL (algebraMap R L r)
    rw [hgr]
    dsimp [j]
    have hr : (1 : S) ⊗ₜ[R] (algebraMap R L r) =
        algebraMap R S r ⊗ₜ[R] (1 : L) :=
      (Algebra.TensorProduct.tmul_one_eq_one_tmul (R := R) (A := S) (B := L) r).symm
    rw [hr]
    simp only [RingHom.algebraMap_toAlgebra]
    change e2 (e1 (algebraMap S (S ⊗[R] L) (f r))) = q r
    rw [e1.commutes, e2.commutes]
    change algebraMap S (Localization.Away (f a)) (f r) =
      algebraMap S (Localization.Away (f a)) (f r)
    rfl
  have hinv : gL (IsLocalization.Away.invSelf a) =
      IsLocalization.Away.invSelf (f a) := by
    apply hq.mul_left_cancel
    calc
      q a * gL (IsLocalization.Away.invSelf a) =
          gL (algebraMap R L a) * gL (IsLocalization.Away.invSelf a) := by
            rw [IsLocalization.Away.lift_eq a hq a]
      _ = gL (algebraMap R L a * IsLocalization.Away.invSelf a) := by
            rw [map_mul]
      _ = 1 := by rw [IsLocalization.Away.mul_invSelf, map_one]
      _ = q a * IsLocalization.Away.invSelf (f a) := by
            rw [show q a = algebraMap S (Localization.Away (f a)) (f a) by rfl,
              IsLocalization.Away.mul_invSelf]
  let jAlg : L →ₐ[R] Localization.Away (f a) :=
    { toRingHom := j
      commutes' := by
        intro r
        change j (algebraMap R L r) = _
        rw [hj]
        dsimp [gL]
        rw [IsLocalization.Away.lift_eq a hq r]
        rfl }
  let kA : A →ₐ[R] Localization.Away (f a) := jAlg.comp hA
  have hkA_mem (x : A) : kA x ∈ C := by
    have hclosure : ∀ z : L, z ∈ A → jAlg z ∈ C := by
      intro z hz
      induction hz using Algebra.adjoin_induction with
      | mem z hz =>
          rcases hz with ⟨y, hy, rfl⟩
          change j (algebraMap R L y * IsLocalization.Away.invSelf a) ∈ C
          rw [map_mul, hj, IsLocalization.Away.lift_eq a hq y, hinv]
          exact (affineBlowupGenerator (Ideal.map f I) (f a)
            ⟨f y, Ideal.mem_map_of_mem f hy⟩).property
      | algebraMap r =>
          change j (algebraMap R L r) ∈ C
          rw [hj, IsLocalization.Away.lift_eq a hq r]
          exact C.algebraMap_mem (f r)
      | add x y hx hy ihx ihy =>
          simpa only [map_add] using C.add_mem ihx ihy
      | mul x y hx hy ihx ihy =>
          simpa only [map_mul] using C.mul_mem ihx ihy
    exact hclosure (x : L) x.property
  let gA : A →ₐ[R] C :=
    { toFun := fun x => ⟨kA x, hkA_mem x⟩
      map_one' := by apply Subtype.ext; exact kA.map_one
      map_mul' := by intro x y; apply Subtype.ext; exact kA.map_mul _ _
      map_zero' := by apply Subtype.ext; exact kA.map_zero
      map_add' := by intro x y; apply Subtype.ext; exact kA.map_add _ _
      commutes' := by
        intro r
        apply Subtype.ext
        exact kA.commutes r }
  let g : (S ⊗[R] A) →ₐ[S] C :=
    Algebra.TensorProduct.lift (Algebra.ofId S C) gA
      (fun _ _ => Commute.all _ _)
  let cval : C →ₐ[S] Localization.Away (f a) := C.val
  have h_eq : cval.comp g = h := by
    apply Algebra.TensorProduct.ext
    · rw [AlgHom.comp_assoc, Algebra.TensorProduct.lift_comp_includeLeft,
        AlgHom.comp_assoc, Algebra.TensorProduct.lift_comp_includeLeft]
      ext s <;>
        change algebraMap S (Localization.Away (f a)) s =
          e (algebraMap S (S ⊗[R] L) s) <;>
        exact (e.commutes s).symm
    ·
      ext x
      change cval (g (Algebra.TensorProduct.includeRight x)) =
        h (Algebra.TensorProduct.includeRight x)
      simp [g, h, h0, cval]
      change kA x = e (1 ⊗ₜ[R] 1) * e (hAL x)
      rw [← Algebra.TensorProduct.one_def, map_one, one_mul]
      rfl
  let J : Ideal S :=
    { carrier := {y | ∃ x : S ⊗[R] A,
          h x = algebraMap S (Localization.Away (f a)) y *
            IsLocalization.Away.invSelf (f a)}
      zero_mem' := by
        refine ⟨0, ?_⟩
        simp
      add_mem' := by
        rintro y z ⟨x, hx⟩ ⟨x', hx'⟩
        refine ⟨x + x', ?_⟩
        simp only [map_add, hx, hx']
        ring
      smul_mem' := by
        intro s y ⟨x, hx⟩
        change ∃ z : S ⊗[R] A,
          h z = algebraMap S (Localization.Away (f a)) (s * y) *
            IsLocalization.Away.invSelf (f a)
        refine ⟨(Algebra.TensorProduct.includeLeft (R := R) (S := S) (A := S) (B := A)) s * x, ?_⟩
        simp only [map_mul]
        have hs : (Algebra.TensorProduct.includeLeft (R := R) (S := S) (A := S) (B := A)) s =
            algebraMap S (S ⊗[R] A) s := by
          change s ⊗ₜ[R] (1 : A) = (algebraMap S S s) ⊗ₜ[R] (1 : A)
          rw [show algebraMap S S s = s by simp]
        rw [hs, h.commutes, hx]
        ring }
  have hJ : Ideal.map f I ≤ J := by
    rw [Ideal.map_le_iff_le_comap]
    intro r hr
    refine ⟨Algebra.TensorProduct.includeRight
      (affineBlowupGenerator I a ⟨r, hr⟩), ?_⟩
    rw [← h_eq]
    simp [g, cval, gA, kA, jAlg, hAL, hA, j, hj, hinv]
    change gL (algebraMap R L r * IsLocalization.Away.invSelf a) = _
    rw [map_mul, IsLocalization.Away.lift_eq a hq r, hinv]
    rfl
  have hg_surj : Function.Surjective g := by
    intro z
    rcases z with ⟨z, hz⟩
    induction hz using Algebra.adjoin_induction with
    | mem y hy =>
        rcases hy with ⟨r, hr, rfl⟩
        rcases hJ hr with ⟨x, hx⟩
        refine ⟨x, ?_⟩
        apply Subtype.ext
        change cval (g x) =
          algebraMap S (Localization.Away (f a)) r *
            IsLocalization.Away.invSelf (f a)
        change (cval.comp g) x = _
        rw [h_eq, hx]
    | algebraMap s =>
        refine ⟨Algebra.TensorProduct.includeLeft (R := R) (S := S)
          (A := S) (B := A) s, ?_⟩
        apply Subtype.ext
        simp [g]
    | add x y hx hy ihx ihy =>
        rcases ihx with ⟨u, hu⟩
        rcases ihy with ⟨v, hv⟩
        refine ⟨u + v, ?_⟩
        apply Subtype.ext
        simp only [map_add, hu, hv]
        rfl
    | mul x y hx hy ihx ihy =>
        rcases ihx with ⟨u, hu⟩
        rcases ihy with ⟨v, hv⟩
        refine ⟨u * v, ?_⟩
        apply Subtype.ext
        simp only [map_mul, hu, hv]
        rfl
  letI : Algebra (S ⊗[R] A) (S ⊗[R] L) := h0.toRingHom.toAlgebra
  letI : IsScalarTower S (S ⊗[R] A) (S ⊗[R] L) :=
    IsScalarTower.of_algebraMap_eq' (R := S) (S := S ⊗[R] A)
      (A := S ⊗[R] L) (by
      ext s
      change algebraMap S (S ⊗[R] L) s =
        h0 (algebraMap S (S ⊗[R] A) s)
      exact (h0.commutes s).symm)
  have hloc : IsLocalization
      ((Submonoid.powers haA).map
        (Algebra.TensorProduct.includeRight (R := R) (A := S)))
      (S ⊗[R] L) := by
    apply IsLocalization.tensorProduct_tensorProduct_right R S
      (Submonoid.powers haA) L
    ext x
    simp [h0, hAL, hA, RingHom.algebraMap_toAlgebra]
    rw [show (x : L) = algebraMap A L x by rfl]
  haveI : IsLocalization.Away
      (algebraMap S (S ⊗[R] A) (f a)) (S ⊗[R] L) := by
    change IsLocalization (Submonoid.powers
      (algebraMap S (S ⊗[R] A) (f a))) (S ⊗[R] L)
    convert hloc using 1
    ext z
    have hb : f a ⊗ₜ[R] (1 : A) = (1 : S) ⊗ₜ[R] haA := by
      simpa [RingHom.algebraMap_toAlgebra] using
        (Algebra.TensorProduct.tmul_one_eq_one_tmul (R := R) (A := S) (B := A) a)
    simp only [Submonoid.map_powers, Algebra.TensorProduct.includeRight_apply]
    rw [Algebra.TensorProduct.algebraMap_apply,
      show (algebraMap S S) (f a) = f a by simp, hb]
  letI : Algebra (S ⊗[R] A) (Localization.Away (f a)) := h.toRingHom.toAlgebra
  let eB : (S ⊗[R] L) ≃ₐ[S ⊗[R] A] Localization.Away (f a) :=
    { toRingEquiv := e.toRingEquiv
      commutes' := by
        intro x
        rfl }
  haveI : IsLocalization.Away
      (algebraMap S (S ⊗[R] A) (f a)) (Localization.Away (f a)) :=
    IsLocalization.isLocalization_of_algEquiv
      (Submonoid.powers (algebraMap S (S ⊗[R] A) (f a))) eB
  have hker : RingHom.ker g.toRingHom =
      baseChangeTorsionIdeal f I a := by
    change RingHom.ker g.toRingHom =
      powerTorsionIdeal (S ⊗[R] A)
        (algebraMap S (S ⊗[R] A) (f a))
    ext x
    constructor
    · intro hx
      rw [mem_powerTorsionIdeal_iff]
      change g x = 0 at hx
      have he : cval (g x) = h x := by
        exact congrArg (fun φ => φ x) h_eq
      have hx' : h x = 0 := by
        rw [← he, hx]
        rfl
      have hx'' :
          algebraMap (S ⊗[R] A) (Localization.Away (f a)) x =
            algebraMap (S ⊗[R] A) (Localization.Away (f a)) 0 := by
        simpa [RingHom.algebraMap_toAlgebra] using hx'
      obtain ⟨n, hn⟩ := IsLocalization.Away.exists_of_eq
        (S := Localization.Away (f a))
        (algebraMap S (S ⊗[R] A) (f a)) hx''
      exact ⟨n, by simpa using hn⟩
    · rw [mem_powerTorsionIdeal_iff]
      rintro ⟨n, hn⟩
      apply Subtype.ext
      change cval (g x) = 0
      have hxmap :
          algebraMap (S ⊗[R] A) (Localization.Away (f a)) x = 0 := by
        apply (IsUnit.pow n
          (IsLocalization.Away.algebraMap_isUnit
            (algebraMap S (S ⊗[R] A) (f a)))).mul_left_cancel
        have hb : algebraMap S (S ⊗[R] A) (f a) =
            f a ⊗ₜ[R] (1 : A) := by
          rw [Algebra.TensorProduct.algebraMap_apply]
          simp
        rw [← map_pow, hb, Algebra.TensorProduct.tmul_pow]
        simpa [map_mul] using
          congrArg (algebraMap (S ⊗[R] A) (Localization.Away (f a))) hn
      have he : cval (g x) = h x := by
        exact congrArg (fun φ => φ x) h_eq
      have hx' : h x = 0 := by
        change algebraMap (S ⊗[R] A) (Localization.Away (f a)) x = 0
        exact hxmap
      calc
        cval (g x) = h x := he
        _ = 0 := hx'
        _ = cval 0 := by simp
  let eQ :
      (S ⊗[R] A) ⧸ RingHom.ker g.toRingHom ≃+* C :=
    RingHom.quotientKerEquivOfSurjective hg_surj
  exact ⟨(Ideal.quotEquivOfEq hker.symm).trans eQ⟩

/-! ## Polynomial Rees algebra -/

/-- The multivariable polynomial ring used for the polynomial examples. -/
abbrev polynomialRing (R : Type u) [CommRing R] (n : ℕ) := MvPolynomial (Fin n) R

/-- The ideal generated by the polynomial variables. -/
def polynomialVariableIdeal (R : Type u) [CommRing R] (n : ℕ) :
    Ideal (polynomialRing R n) :=
  Ideal.span (Set.range (MvPolynomial.X (R := R) : Fin n → polynomialRing R n))

/-- The quadratic relations `t_i T_j - t_j T_i` in the polynomial Rees
presentation. -/
def polynomialReesRelationIdeal (R : Type u) [CommRing R] (n : ℕ) :
    Ideal (MvPolynomial (Fin n) (polynomialRing R n)) :=
  Ideal.span (Set.range (fun ij : Fin n × Fin n =>
    MvPolynomial.C (R := polynomialRing R n) (MvPolynomial.X (R := R) ij.1) *
        MvPolynomial.X (R := polynomialRing R n) ij.2 -
      MvPolynomial.C (R := polynomialRing R n) (MvPolynomial.X (R := R) ij.2) *
        MvPolynomial.X (R := polynomialRing R n) ij.1))

/-- The image of a variable in degree one of the polynomial Rees algebra. -/
def polynomialReesVariable (R : Type u) [CommRing R] (n : ℕ) (i : Fin n) :
    _root_.reesAlgebra (polynomialVariableIdeal R n) :=
  reesDegreeOneElement (polynomialVariableIdeal R n)
    ⟨MvPolynomial.X (R := R) i, Ideal.subset_span ⟨i, rfl⟩⟩

/-- The polynomial Rees presentation, including the images of the variables. -/
structure PolynomialReesPresentation (R : Type u) [CommRing R] (n : ℕ) where
  equivalence :
    (MvPolynomial (Fin n) (polynomialRing R n) ⧸ polynomialReesRelationIdeal R n) ≃ₐ[
      polynomialRing R n] _root_.reesAlgebra (polynomialVariableIdeal R n)
  sends_variable : ∀ i : Fin n,
    equivalence (Ideal.Quotient.mk (polynomialReesRelationIdeal R n)
      (MvPolynomial.X i)) = polynomialReesVariable R n i

/-- The polynomial Rees algebra is presented by the `2 × 2` relations. -/
theorem polynomial_rees_presentation
    (R : Type u) [CommRing R] (n : ℕ) :
    Nonempty (PolynomialReesPresentation R n) := by sorry

/-- A multi-index and its total degree. -/
abbrev multiIndex (n : ℕ) := Fin n →₀ ℕ

def multiIndexDegree {n : ℕ} (E : multiIndex n) : ℕ :=
  E.support.sum (fun i => E i)

/-- Multi-indices of a fixed total degree. -/
abbrev degreeIndex (n e : ℕ) := {E : multiIndex n // multiIndexDegree E = e}

/-- The monomial map from the free module on degree-`e` multi-indices. -/
def polynomialPowerMonomialMap
    (R : Type u) [CommRing R] (n e : ℕ) :
    (degreeIndex n e →₀ polynomialRing R n) →ₗ[polynomialRing R n]
      polynomialRing R n :=
  Finsupp.linearCombination (polynomialRing R n)
    (fun E : degreeIndex n e => MvPolynomial.monomial E.1 1)

/-- The elementary exchange relation between two degree-`e` monomials. -/
def polynomialPowerRelationVector
    (R : Type u) [CommRing R] (n e : ℕ) (E E' : degreeIndex n e)
    (i j : Fin n) : degreeIndex n e →₀ polynomialRing R n :=
  Finsupp.single E (MvPolynomial.X i) - Finsupp.single E' (MvPolynomial.X j)

/-- The submodule generated by the relations described in the polynomial
example. -/
def polynomialPowerRelationSubmodule
    (R : Type u) [CommRing R] (n e : ℕ) :
    Submodule (polynomialRing R n) (degreeIndex n e →₀ polynomialRing R n) :=
  Submodule.span _ {v | ∃ E E' : degreeIndex n e, ∃ i j : Fin n,
    E.1 + Finsupp.single i 1 = E'.1 + Finsupp.single j 1 ∧
      v = polynomialPowerRelationVector R n e E E' i j}

/-- Degree-`e` monomials generate the power of the variable ideal, and the
elementary exchange relations generate all relations. -/
theorem polynomial_power_monomial_presentation
    (R : Type u) [CommRing R] (n e : ℕ) (he : 0 < e) :
    LinearMap.range (polynomialPowerMonomialMap R n e) =
        (polynomialVariableIdeal R n) ^ e ∧
      LinearMap.ker (polynomialPowerMonomialMap R n e) =
        polynomialPowerRelationSubmodule R n e := by
  sorry

/-! ## Polynomial affine chart and the general quotient presentation -/

/- The parameter `n` below counts the variables `x_2, ..., x_{n+1}`; the
base polynomial ring therefore has `n + 1` variables. -/

def affinePolynomialRelationIdeal
    (R : Type u) [CommRing R] (n : ℕ) :
    Ideal (MvPolynomial (Fin n) (polynomialRing R (n + 1))) :=
  Ideal.span (Set.range (fun i : Fin n =>
    MvPolynomial.C (R := polynomialRing R (n + 1))
        (MvPolynomial.X (R := R) (0 : Fin (n + 1))) *
        MvPolynomial.X (R := polynomialRing R (n + 1)) i -
      MvPolynomial.C (R := polynomialRing R (n + 1))
        (MvPolynomial.X (R := R) i.succ)))

/-- The variables `t_i/t_1` in the affine polynomial chart. -/
def affinePolynomialChartVariable
    (R : Type u) [CommRing R] (n : ℕ) (i : Fin n) :
    affineBlowup (polynomialVariableIdeal R (n + 1))
      (MvPolynomial.X (R := R) (0 : Fin (n + 1))) :=
  affineBlowupGenerator (polynomialVariableIdeal R (n + 1))
    (MvPolynomial.X (R := R) (0 : Fin (n + 1)))
    ⟨MvPolynomial.X (R := R) i.succ, Ideal.subset_span ⟨i.succ, rfl⟩⟩

/-- The polynomial affine chart presentation. -/
structure AffinePolynomialPresentation (R : Type u) [CommRing R] (n : ℕ) where
  equivalence :
    (MvPolynomial (Fin n) (polynomialRing R (n + 1)) ⧸
        affinePolynomialRelationIdeal R n) ≃ₐ[polynomialRing R (n + 1)]
      affineBlowup (polynomialVariableIdeal R (n + 1))
        (MvPolynomial.X (R := R) (0 : Fin (n + 1)))
  sends_variable : ∀ i : Fin n,
    equivalence (Ideal.Quotient.mk (affinePolynomialRelationIdeal R n)
      (MvPolynomial.X (R := polynomialRing R (n + 1)) i)) =
        affinePolynomialChartVariable R n i

/-- The polynomial affine chart has the expected relations
`t_1 x_i - t_i`. -/
theorem affine_polynomial_presentation
    (R : Type u) [CommRing R] (n : ℕ) :
    Nonempty (AffinePolynomialPresentation R n) := by
  sorry

/-- The ideal generated by a finite list of elements. -/
def finiteGeneratorIdeal {R : Type u} [CommRing R] (n : ℕ)
    (a : Fin (n + 1) → R) : Ideal R :=
  Ideal.span (Set.range a)

/-- The relation ideal for a finitely generated affine blowup chart. -/
def finiteGeneratorRelationIdeal
    {R : Type u} [CommRing R] (n : ℕ) (a : Fin (n + 1) → R) :
    Ideal (MvPolynomial (Fin n) R) :=
  Ideal.span (Set.range (fun i : Fin n =>
    MvPolynomial.C (R := R) (a 0) * MvPolynomial.X (R := R) i -
      MvPolynomial.C (R := R) (a i.succ)))

/-- The source, target, and kernel assertion in the general finite-generator
quotient description. -/
structure AffineBlowupQuotientPresentation
    {R : Type u} [CommRing R] (n : ℕ) (a : Fin (n + 1) → R) where
  hom :
    (MvPolynomial (Fin n) R ⧸ finiteGeneratorRelationIdeal n a) →ₐ[R]
      affineBlowup (finiteGeneratorIdeal n a) (a 0)
  surjective : Function.Surjective hom
  kernel_eq_power_torsion :
    RingHom.ker hom.toRingHom =
      powerTorsionIdeal _ (algebraMap R
        (MvPolynomial (Fin n) R ⧸ finiteGeneratorRelationIdeal n a) (a 0))

/-- The quotient presentation of an affine blowup has power-torsion kernel. -/
theorem affineBlowup_quotient_presentation
    {R : Type u} [CommRing R] (n : ℕ) (a : Fin (n + 1) → R) :
    Nonempty (AffineBlowupQuotientPresentation n a) := by
  sorry

/-! ## Principal comparisons and permanence properties -/

/-- Equality of the vanishing locus of an element and an ideal. -/
def SameVanishingLocus {R : Type u} [CommRing R] (f : R) (I : Ideal R) : Prop :=
  PrimeSpectrum.zeroLocus ({f} : Set R) = PrimeSpectrum.zeroLocus (I : Set R)

/-- If `V(f) = V(I)`, localizing the affine blowup at `f`, at `a`, or at the
original ring gives the same ring. -/
theorem affineBlowup_in_principal
    {R : Type u} [CommRing R] (I : Ideal R) {a f : R} (ha : a ∈ I)
    (hf : SameVanishingLocus f I) :
    IsRegular (algebraMap R (affineBlowup I a) f) ∧
      Nonempty
        (Localization.Away (algebraMap R (affineBlowup I a) f) ≃+*
          Localization.Away (algebraMap R (affineBlowup I a) a)) ∧
      Nonempty
        (Localization.Away (algebraMap R (affineBlowup I a) a) ≃+*
          Localization.Away a) := by
  sorry

/-- The ideal `fI` occurring in the add-principal comparison. -/
def principalMultiplyIdeal {R : Type u} [CommRing R] (f : R) (I : Ideal R) :
    Ideal R :=
  Ideal.span {f} * I

/-- The affine blowup after multiplying both the ideal and its chosen
generator by `f`. -/
abbrev addPrincipalBlowup {R : Type u} [CommRing R] (f : R) (I : Ideal R) (a : R) :=
  affineBlowup (principalMultiplyIdeal f I) (f * a)

/-- The surjection and torsion-kernel statement for adding a principal factor. -/
structure AddPrincipalBlowupPresentation
    {R : Type u} [CommRing R] (f : R) (I : Ideal R) (a : R) where
  hom : affineBlowup I a →ₐ[R] addPrincipalBlowup f I a
  surjective : Function.Surjective hom
  kernel_eq_power_torsion :
    RingHom.ker hom.toRingHom =
      powerTorsionIdeal _ (algebraMap R (affineBlowup I a) f)

/-- Adding a principal factor produces a surjective algebra map with the
expected power-torsion kernel. -/
theorem affineBlowup_add_principal
    {R : Type u} [CommRing R] (f : R) (I : Ideal R) {a : R} (ha : a ∈ I) :
    Nonempty (AddPrincipalBlowupPresentation f I a) := by
  sorry

/-- The two affine charts at `a` and `b` map into the chart at `ab` for the
product ideal.  This is the algebra-map form of the inclusions
`R[I/a] ∪ R[J/b] ⊆ R[IJ/(ab)]` used in the directed-colimit argument. -/
structure AffineBlowupProductComparison
    {R : Type u} [CommRing R] (I J : Ideal R) (a b : R) where
  left : affineBlowup I a →ₐ[R] affineBlowup (I * J) (a * b)
  right : affineBlowup J b →ₐ[R] affineBlowup (I * J) (a * b)

/-- The product-ideal affine chart receives both of the original charts. -/
theorem affineBlowup_product_comparison
    {R : Type u} [CommRing R] (I J : Ideal R) (a b : R)
    (_ha : a ∈ I) (_hb : b ∈ J) :
    Nonempty (AffineBlowupProductComparison I J a b) := by
  sorry

/-- Reducedness is preserved by every affine blowup. -/
theorem affineBlowup_isReduced
    {R : Type u} [CommRing R] [IsReduced R]
    (I : Ideal R) (a : R) (_ha : a ∈ I) :
    IsReduced (affineBlowup I a) := by
  sorry

/-- A blowup chart at a nonzero element of an ideal in a domain is a domain. -/
theorem affineBlowup_isDomain
    {R : Type u} [CommRing R] [IsDomain R]
    (I : Ideal R) {a : R} (ha : a ∈ I) (ha0 : a ≠ 0) :
    IsDomain (affineBlowup I a) := by
  sorry

/-- The blowup map is dominant when the chosen denominator avoids every
minimal prime. -/
theorem affineBlowup_denseRange
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (ha : a ∈ I)
    (hmin : ∀ p : MinimalPrimeSpectrum R, a ∉ p.1.asIdeal) :
    DenseRange (PrimeSpectrum.comap (algebraMap R (affineBlowup I a))) := by
  sorry

/-! ## Valuation rings as directed colimits of affine blowups -/

/-- The fibre of an `R`-algebra at an ideal `m`. -/
abbrev fibreRingAtIdeal
    (R : Type u) [CommRing R] (B : Type v) [CommRing B] [Algebra R B]
    (m : Ideal R) : Type v :=
  B ⧸ Ideal.map (algebraMap R B) m

/-- A valuation subring dominates a local ring when the induced map is local.
This records the domination hypothesis from the source without confusing it
with mere containment of the image in the valuation subring. -/
def DominatesValuationSubring
    {R K : Type u} [CommRing R] [IsLocalRing R] [Field K] [Algebra R K]
    (A : ValuationSubring K) : Prop :=
  ∃ f : R →+* (A : Type u),
    (∀ r : R, (f r : K) = algebraMap R K r) ∧ IsLocalHom f

/-- A directed family of affine blowups, indexed by finite subsets of its
target valuation ring, together with the colimit equivalence.  The finite-set
index is a canonical directed indexing of the finite-subset argument in the
source proof. -/
structure ValuationBlowupColimitData
    {R K : Type u} [CommRing R] [IsLocalRing R] [Field K] [Algebra R K]
    (A : ValuationSubring K) where
  ideal : Finset (A : Type u) → Ideal R
  center : Finset (A : Type u) → R
  center_mem : ∀ E, center E ∈ ideal E
  ideal_below_maximal : ∀ E, ideal E ≤ IsLocalRing.maximalIdeal R
  ideal_finite : ∀ E, Module.Finite R (ideal E)
  fibre_nontrivial : ∀ E,
    (0 : fibreRingAtIdeal R (affineBlowup (ideal E) (center E))
      (IsLocalRing.maximalIdeal R)) ≠
      (1 : fibreRingAtIdeal R (affineBlowup (ideal E) (center E))
        (IsLocalRing.maximalIdeal R))
  transition : ∀ {E F : Finset (A : Type u)}, E ⊆ F →
    affineBlowup (ideal E) (center E) →+*
      affineBlowup (ideal F) (center F)
  transition_injective : ∀ {E F : Finset (A : Type u)} (h : E ⊆ F),
    Function.Injective (transition h)
  [directedSystem :
    DirectedSystem
      (fun E : Finset (A : Type u) => affineBlowup (ideal E) (center E))
      (fun {E F : Finset (A : Type u)} (h : E ⊆ F) => transition h)]
  mapToA : ∀ E, affineBlowup (ideal E) (center E) →+* (A : Type u)
  mapToA_injective : ∀ E, Function.Injective (mapToA E)
  mapToA_comp_algebraMap : ∀ E r,
    (mapToA E (algebraMap R (affineBlowup (ideal E) (center E)) r) : K) =
      algebraMap R K r
  map_compat : ∀ {E F : Finset (A : Type u)} (h : E ⊆ F) (x),
    mapToA F (transition h x) = mapToA E x
  colimitEquiv :
    DirectLimit
        (fun E : Finset (A : Type u) => affineBlowup (ideal E) (center E))
        (fun _E _F h => transition h) ≃+* A

/-- A local valuation domain dominating `R` is the directed colimit of the
finite, nontrivial-fibre affine blowups described in the source. -/
theorem valuationRing_directedColimit_affineBlowups
    {R K : Type u} [CommRing R] [IsDomain R] [IsLocalRing R]
    [Field K] [Algebra R K] [IsFractionRing R K]
    (A : ValuationSubring K)
    (hA : DominatesValuationSubring (R := R) (K := K) A) :
    Nonempty (ValuationBlowupColimitData (R := R) (K := K) A) := by
  sorry

end
end Formalization.Books.Algebra.Unit70
