import Formalization.Books.Algebra.Unit25.ZerodivisorsAndTotalRingsOfFractions
import Formalization.Books.Algebra.Unit50.ValuationRings
import Formalization.Books.Algebra.Unit57.Proj
import Mathlib.Algebra.Colimit.DirectLimit
import Mathlib.LinearAlgebra.Finsupp.LinearCombination
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.BaseChange
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.RingTheory.ReesAlgebra
import Mathlib.RingTheory.Spectrum.Prime.RingHom

/-!
# Commutative Algebra, Chapter 70: Blow up algebras

The Rees algebra uses Mathlib's canonical subalgebra model of
`R[It] = ⨁ₙ Iⁿtⁿ`.  An affine chart is represented by the canonical subalgebra
of the localization generated by the fractions `x/a` with `x ∈ I`.  This is
the standard ring-theoretic presentation of the degree-zero chart and exposes
the localization and torsion APIs used by the statements below.
-/

namespace Formalization.Books.Algebra.Unit70

open Formalization.Books.Algebra.Unit25
open Formalization.Books.Algebra.Unit50
open Set
open scoped BigOperators DirectSum Pointwise Polynomial TensorProduct

universe u v w

noncomputable section

/-! ## The Rees algebra and affine charts -/

/- Mathlib's `reesAlgebra I` is the canonical subalgebra of `R[X]` used for
   the source's Rees algebra. -/

/-- The element represented by `x` in degree `n` of the Rees algebra. -/
def reesElement {R : Type u} [CommRing R] (I : Ideal R) (n : ℕ) (x : R)
    (hx : x ∈ I ^ n) : _root_.reesAlgebra I :=
  ⟨Polynomial.monomial n x, _root_.reesAlgebra.monomial_mem.mpr hx⟩

/-- The degree-one Rees element attached to an element of the ideal. -/
def reesDegreeOneElement {R : Type u} [CommRing R] (I : Ideal R) (a : I) :
    _root_.reesAlgebra I :=
  reesElement I 1 a.1 (by rw [pow_one]; exact a.2)

/-- The set of fractions `x/a` used to generate an affine blowup chart. -/
def affineBlowupGeneratorSet {R : Type u} [CommRing R] (I : Ideal R) (a : R) :
    Set (Localization.Away a) :=
  {z | ∃ x : R, x ∈ I ∧
    z = algebraMap R (Localization.Away a) x *
      IsLocalization.Away.invSelf a}

/-- The affine blowup algebra `R[I/a]`, realized as a subalgebra of `R_a`. -/
def affineBlowup {R : Type u} [CommRing R] (I : Ideal R) (a : R) :
    Subalgebra R (Localization.Away a) :=
  Algebra.adjoin R (affineBlowupGeneratorSet I a)

/-- The canonical generator `x/a` as an element of the affine blowup algebra. -/
def affineBlowupGenerator {R : Type u} [CommRing R] (I : Ideal R) (a : R)
    (x : I) : affineBlowup I a :=
  ⟨algebraMap R (Localization.Away a) x.1 *
      IsLocalization.Away.invSelf a,
    Algebra.subset_adjoin ⟨x.1, x.2, rfl⟩⟩

/-- The localization representative `x/a^n` in `R_a`. -/
def affineBlowupRepresentative {R : Type u} [CommRing R] (a : R)
    (n : ℕ) (x : R) : Localization.Away a :=
  Localization.mk x ⟨a ^ n, (Submonoid.mem_powers_iff _ _).2 ⟨n, rfl⟩⟩

/-- The equality relation on the representatives used for an affine chart. -/
theorem affineBlowupRepresentative_eq_iff
    {R : Type u} [CommRing R] (I : Ideal R) (a : R)
    {n m : ℕ} {x y : R} (hx : x ∈ I ^ n) (hy : y ∈ I ^ m) :
    affineBlowupRepresentative a n x = affineBlowupRepresentative a m y ↔
      ∃ k : ℕ, a ^ k * (a ^ m * x - a ^ n * y) = 0 := by
  rw [Localization.mk_eq_mk']
  rw [IsLocalization.eq]
  constructor
  · rintro ⟨c, hc⟩
    obtain ⟨k, rfl⟩ := (Submonoid.mem_powers_iff _ _).1 c.2
    refine ⟨k, ?_⟩
    rw [mul_sub, sub_eq_zero]
    exact hc
  · rintro ⟨k, hk⟩
    refine ⟨⟨a ^ k, (Submonoid.mem_powers_iff _ _).2 ⟨k, rfl⟩⟩, ?_⟩
    rw [mul_sub, sub_eq_zero] at hk
    exact hk

/-- Every valid numerator-denominator representative belongs to the chart. -/
theorem affineBlowupRepresentative_mem
    {R : Type u} [CommRing R] (I : Ideal R) (a : R)
    {n : ℕ} {x : R} (hx : x ∈ I ^ n) :
    affineBlowupRepresentative a n x ∈ affineBlowup I a := by
  have hrep (n : ℕ) (x : R) :
      affineBlowupRepresentative a n x =
          algebraMap R (Localization.Away a) x *
          IsLocalization.Away.invSelf a ^ n := by
    rw [affineBlowupRepresentative, Localization.mk_eq_mk',
      IsLocalization.mk'_eq_mul_mk'_one]
    simp [IsLocalization.Away.invSelf, ← IsLocalization.mk'_pow]
  induction hx using Submodule.pow_induction_on_left' with
  | algebraMap r =>
      simpa [hrep] using (affineBlowup I a).algebraMap_mem r
  | add x y i hx hy ihx ihy =>
      simpa [hrep, add_mul] using (affineBlowup I a).add_mem ihx ihy
  | mem_mul m hm i x hx ih =>
      have hgen := (affineBlowupGenerator I a ⟨m, hm⟩).property
      have hprod := (affineBlowup I a).mul_mem hgen ih
      simpa [hrep, pow_succ, mul_assoc, mul_left_comm, mul_comm] using hprod

/-- The ideal of elements killed by a power of `b`, represented canonically as
the kernel of the localization map. -/
def powerTorsionIdeal (R : Type u) [CommRing R] (b : R) : Ideal R :=
  RingHom.ker (algebraMap R (Localization.Away b))

/-- Membership in the kernel presentation of power torsion. -/
theorem mem_powerTorsionIdeal_iff
    {R : Type u} [CommRing R] (b x : R) :
    x ∈ powerTorsionIdeal R b ↔ ∃ n : ℕ, b ^ n * x = 0 := by
  rw [powerTorsionIdeal, RingHom.mem_ker]
  constructor
  · intro hx
    obtain ⟨s, hs⟩ :=
      (IsLocalization.map_eq_zero_iff (Submonoid.powers b)
        (Localization.Away b) x).mp hx
    obtain ⟨n, hn⟩ := (Submonoid.mem_powers_iff _ _).mp s.2
    exact ⟨n, by simpa [hn] using hs⟩
  · rintro ⟨n, hn⟩
    apply (IsLocalization.map_eq_zero_iff (Submonoid.powers b)
      (Localization.Away b) x).mpr
    refine ⟨⟨b ^ n, (Submonoid.mem_powers_iff _ _).2 ⟨n, rfl⟩⟩, ?_⟩
    simpa using hn

/-- The chosen denominator is regular in an affine blowup chart. -/
theorem affineBlowup_isRegular
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (ha : a ∈ I) :
    IsRegular (algebraMap R (affineBlowup I a) a) := by
  rw [isRegular_iff]
  constructor
  · intro x y hxy
    apply Subtype.ext
    apply (IsUnit.mul_right_inj (IsLocalization.Away.algebraMap_isUnit a)).mp
    simpa only [Subalgebra.coe_algebraMap, IsScalarTower.algebraMap_apply] using
      congrArg (fun z : affineBlowup I a => (z : Localization.Away a)) hxy
  · intro x y hxy
    apply Subtype.ext
    apply (IsUnit.mul_left_inj (IsLocalization.Away.algebraMap_isUnit a)).mp
    simpa only [Subalgebra.coe_algebraMap, IsScalarTower.algebraMap_apply] using
      congrArg (fun z : affineBlowup I a => (z : Localization.Away a)) hxy

theorem affineBlowup_map_ideal_eq_span
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (ha : a ∈ I) :
    Ideal.map (algebraMap R (affineBlowup I a)) I =
      Ideal.span {algebraMap R (affineBlowup I a) a} := by
  sorry

theorem affineBlowup_localization_equiv
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (ha : a ∈ I) :
    Nonempty
      (Localization.Away (algebraMap R (affineBlowup I a) a) ≃+*
        Localization.Away a) := by
  sorry

/-! ## Base change -/

/-- The torsion ideal occurring in the base-change description. -/
def baseChangeTorsionIdeal
    {R : Type u} {S : Type v} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) (a : R) :
    letI : Algebra R S := f.toAlgebra
    Ideal (S ⊗[R] affineBlowup I a) :=
  letI : Algebra R S := f.toAlgebra
  powerTorsionIdeal _ (algebraMap S (S ⊗[R] affineBlowup I a) (f a))

/-- Affine blowup commutes with base change after quotienting by the new
denominator's power torsion. -/
theorem affineBlowup_baseChange
    {R : Type u} {S : Type v} [CommRing R] [CommRing S]
    (f : R →+* S) (I : Ideal R) {a : R} (ha : a ∈ I) :
    letI : Algebra R S := f.toAlgebra
    Nonempty
      ((S ⊗[R] affineBlowup I a) ⧸ baseChangeTorsionIdeal f I a ≃+*
        affineBlowup (Ideal.map f I) (f a)) := by
  sorry

/-! ## Polynomial Rees algebra -/

/-- The multivariable polynomial ring used for the polynomial examples. -/
abbrev polynomialRing (R : Type u) [CommRing R] (n : ℕ) := MvPolynomial (Fin n) R

/-- The ideal generated by the polynomial variables. -/
def polynomialVariableIdeal (R : Type u) [CommRing R] (n : ℕ) :
    Ideal (polynomialRing R n) :=
  Ideal.span (Set.range (MvPolynomial.X (R := R) : Fin n → polynomialRing R n))

/-- The quadratic relations `t_i T_j - t_j T_i` in the polynomial Rees
presentation. -/
def polynomialReesRelationIdeal (R : Type u) [CommRing R] (n : ℕ) :
    Ideal (MvPolynomial (Fin n) (polynomialRing R n)) :=
  Ideal.span (Set.range (fun ij : Fin n × Fin n =>
    MvPolynomial.C (R := polynomialRing R n) (MvPolynomial.X (R := R) ij.1) *
        MvPolynomial.X (R := polynomialRing R n) ij.2 -
      MvPolynomial.C (R := polynomialRing R n) (MvPolynomial.X (R := R) ij.2) *
        MvPolynomial.X (R := polynomialRing R n) ij.1))

/-- The image of a variable in degree one of the polynomial Rees algebra. -/
def polynomialReesVariable (R : Type u) [CommRing R] (n : ℕ) (i : Fin n) :
    _root_.reesAlgebra (polynomialVariableIdeal R n) :=
  reesDegreeOneElement (polynomialVariableIdeal R n)
    ⟨MvPolynomial.X (R := R) i, Ideal.subset_span ⟨i, rfl⟩⟩

/-- The polynomial Rees presentation, including the images of the variables. -/
structure PolynomialReesPresentation (R : Type u) [CommRing R] (n : ℕ) where
  equivalence :
    (MvPolynomial (Fin n) (polynomialRing R n) ⧸ polynomialReesRelationIdeal R n) ≃ₐ[
      polynomialRing R n] _root_.reesAlgebra (polynomialVariableIdeal R n)
  sends_variable : ∀ i : Fin n,
    equivalence (Ideal.Quotient.mk (polynomialReesRelationIdeal R n)
      (MvPolynomial.X i)) = polynomialReesVariable R n i

/-- The polynomial Rees algebra is presented by the `2 × 2` relations. -/
theorem polynomial_rees_presentation
    (R : Type u) [CommRing R] (n : ℕ) :
    Nonempty (PolynomialReesPresentation R n) := by
  sorry

/-- A multi-index and its total degree. -/
abbrev multiIndex (n : ℕ) := Fin n →₀ ℕ

def multiIndexDegree {n : ℕ} (E : multiIndex n) : ℕ :=
  E.support.sum (fun i => E i)

/-- Multi-indices of a fixed total degree. -/
abbrev degreeIndex (n e : ℕ) := {E : multiIndex n // multiIndexDegree E = e}

/-- The monomial map from the free module on degree-`e` multi-indices. -/
def polynomialPowerMonomialMap
    (R : Type u) [CommRing R] (n e : ℕ) :
    (degreeIndex n e →₀ polynomialRing R n) →ₗ[polynomialRing R n]
      polynomialRing R n :=
  Finsupp.linearCombination (polynomialRing R n)
    (fun E : degreeIndex n e => MvPolynomial.monomial E.1 1)

/-- The elementary exchange relation between two degree-`e` monomials. -/
def polynomialPowerRelationVector
    (R : Type u) [CommRing R] (n e : ℕ) (E E' : degreeIndex n e)
    (i j : Fin n) : degreeIndex n e →₀ polynomialRing R n :=
  Finsupp.single E (MvPolynomial.X i) - Finsupp.single E' (MvPolynomial.X j)

/-- The submodule generated by the relations described in the polynomial
example. -/
def polynomialPowerRelationSubmodule
    (R : Type u) [CommRing R] (n e : ℕ) :
    Submodule (polynomialRing R n) (degreeIndex n e →₀ polynomialRing R n) :=
  Submodule.span _ {v | ∃ E E' : degreeIndex n e, ∃ i j : Fin n,
    E.1 + Finsupp.single i 1 = E'.1 + Finsupp.single j 1 ∧
      v = polynomialPowerRelationVector R n e E E' i j}

/-- Degree-`e` monomials generate the power of the variable ideal, and the
elementary exchange relations generate all relations. -/
theorem polynomial_power_monomial_presentation
    (R : Type u) [CommRing R] (n e : ℕ) (he : 0 < e) :
    LinearMap.range (polynomialPowerMonomialMap R n e) =
        (polynomialVariableIdeal R n) ^ e ∧
      LinearMap.ker (polynomialPowerMonomialMap R n e) =
        polynomialPowerRelationSubmodule R n e := by
  sorry

/-! ## Polynomial affine chart and the general quotient presentation -/

/- The parameter `n` below counts the variables `x_2, ..., x_{n+1}`; the
base polynomial ring therefore has `n + 1` variables. -/

def affinePolynomialRelationIdeal
    (R : Type u) [CommRing R] (n : ℕ) :
    Ideal (MvPolynomial (Fin n) (polynomialRing R (n + 1))) :=
  Ideal.span (Set.range (fun i : Fin n =>
    MvPolynomial.C (R := polynomialRing R (n + 1))
        (MvPolynomial.X (R := R) (0 : Fin (n + 1))) *
        MvPolynomial.X (R := polynomialRing R (n + 1)) i -
      MvPolynomial.C (R := polynomialRing R (n + 1))
        (MvPolynomial.X (R := R) i.succ)))

/-- The variables `t_i/t_1` in the affine polynomial chart. -/
def affinePolynomialChartVariable
    (R : Type u) [CommRing R] (n : ℕ) (i : Fin n) :
    affineBlowup (polynomialVariableIdeal R (n + 1))
      (MvPolynomial.X (R := R) (0 : Fin (n + 1))) :=
  affineBlowupGenerator (polynomialVariableIdeal R (n + 1))
    (MvPolynomial.X (R := R) (0 : Fin (n + 1)))
    ⟨MvPolynomial.X (R := R) i.succ, Ideal.subset_span ⟨i.succ, rfl⟩⟩

/-- The polynomial affine chart presentation. -/
structure AffinePolynomialPresentation (R : Type u) [CommRing R] (n : ℕ) where
  equivalence :
    (MvPolynomial (Fin n) (polynomialRing R (n + 1)) ⧸
        affinePolynomialRelationIdeal R n) ≃ₐ[polynomialRing R (n + 1)]
      affineBlowup (polynomialVariableIdeal R (n + 1))
        (MvPolynomial.X (R := R) (0 : Fin (n + 1)))
  sends_variable : ∀ i : Fin n,
    equivalence (Ideal.Quotient.mk (affinePolynomialRelationIdeal R n)
      (MvPolynomial.X (R := polynomialRing R (n + 1)) i)) =
        affinePolynomialChartVariable R n i

/-- The polynomial affine chart has the expected relations
`t_1 x_i - t_i`. -/
theorem affine_polynomial_presentation
    (R : Type u) [CommRing R] (n : ℕ) :
    Nonempty (AffinePolynomialPresentation R n) := by
  sorry

/-- The ideal generated by a finite list of elements. -/
def finiteGeneratorIdeal {R : Type u} [CommRing R] (n : ℕ)
    (a : Fin (n + 1) → R) : Ideal R :=
  Ideal.span (Set.range a)

/-- The relation ideal for a finitely generated affine blowup chart. -/
def finiteGeneratorRelationIdeal
    {R : Type u} [CommRing R] (n : ℕ) (a : Fin (n + 1) → R) :
    Ideal (MvPolynomial (Fin n) R) :=
  Ideal.span (Set.range (fun i : Fin n =>
    MvPolynomial.C (R := R) (a 0) * MvPolynomial.X (R := R) i -
      MvPolynomial.C (R := R) (a i.succ)))

/-- The source, target, and kernel assertion in the general finite-generator
quotient description. -/
structure AffineBlowupQuotientPresentation
    {R : Type u} [CommRing R] (n : ℕ) (a : Fin (n + 1) → R) where
  hom :
    (MvPolynomial (Fin n) R ⧸ finiteGeneratorRelationIdeal n a) →ₐ[R]
      affineBlowup (finiteGeneratorIdeal n a) (a 0)
  surjective : Function.Surjective hom
  kernel_eq_power_torsion :
    RingHom.ker hom.toRingHom =
      powerTorsionIdeal _ (algebraMap R
        (MvPolynomial (Fin n) R ⧸ finiteGeneratorRelationIdeal n a) (a 0))

/-- The quotient presentation of an affine blowup has power-torsion kernel. -/
theorem affineBlowup_quotient_presentation
    {R : Type u} [CommRing R] (n : ℕ) (a : Fin (n + 1) → R) :
    Nonempty (AffineBlowupQuotientPresentation n a) := by
  sorry

/-! ## Principal comparisons and permanence properties -/

/-- Equality of the vanishing locus of an element and an ideal. -/
def SameVanishingLocus {R : Type u} [CommRing R] (f : R) (I : Ideal R) : Prop :=
  PrimeSpectrum.zeroLocus ({f} : Set R) = PrimeSpectrum.zeroLocus (I : Set R)

/-- If `V(f) = V(I)`, localizing the affine blowup at `f`, at `a`, or at the
original ring gives the same ring. -/
theorem affineBlowup_in_principal
    {R : Type u} [CommRing R] (I : Ideal R) {a f : R} (ha : a ∈ I)
    (hf : SameVanishingLocus f I) :
    IsRegular (algebraMap R (affineBlowup I a) f) ∧
      Nonempty
        (Localization.Away (algebraMap R (affineBlowup I a) f) ≃+*
          Localization.Away (algebraMap R (affineBlowup I a) a)) ∧
      Nonempty
        (Localization.Away (algebraMap R (affineBlowup I a) a) ≃+*
          Localization.Away a) := by
  sorry

/-- The ideal `fI` occurring in the add-principal comparison. -/
def principalMultiplyIdeal {R : Type u} [CommRing R] (f : R) (I : Ideal R) :
    Ideal R :=
  Ideal.span {f} * I

/-- The affine blowup after multiplying both the ideal and its chosen
generator by `f`. -/
abbrev addPrincipalBlowup {R : Type u} [CommRing R] (f : R) (I : Ideal R) (a : R) :=
  affineBlowup (principalMultiplyIdeal f I) (f * a)

/-- The surjection and torsion-kernel statement for adding a principal factor. -/
structure AddPrincipalBlowupPresentation
    {R : Type u} [CommRing R] (f : R) (I : Ideal R) (a : R) where
  hom : affineBlowup I a →ₐ[R] addPrincipalBlowup f I a
  surjective : Function.Surjective hom
  kernel_eq_power_torsion :
    RingHom.ker hom.toRingHom =
      powerTorsionIdeal _ (algebraMap R (affineBlowup I a) f)

/-- Adding a principal factor produces a surjective algebra map with the
expected power-torsion kernel. -/
theorem affineBlowup_add_principal
    {R : Type u} [CommRing R] (f : R) (I : Ideal R) {a : R} (ha : a ∈ I) :
    Nonempty (AddPrincipalBlowupPresentation f I a) := by
  sorry

/-- The two affine charts at `a` and `b` map into the chart at `ab` for the
product ideal.  This is the algebra-map form of the inclusions
`R[I/a] ∪ R[J/b] ⊆ R[IJ/(ab)]` used in the directed-colimit argument. -/
structure AffineBlowupProductComparison
    {R : Type u} [CommRing R] (I J : Ideal R) (a b : R) where
  left : affineBlowup I a →ₐ[R] affineBlowup (I * J) (a * b)
  right : affineBlowup J b →ₐ[R] affineBlowup (I * J) (a * b)

/-- The product-ideal affine chart receives both of the original charts. -/
theorem affineBlowup_product_comparison
    {R : Type u} [CommRing R] (I J : Ideal R) (a b : R)
    (_ha : a ∈ I) (_hb : b ∈ J) :
    Nonempty (AffineBlowupProductComparison I J a b) := by
  sorry

/-- Reducedness is preserved by every affine blowup. -/
theorem affineBlowup_isReduced
    {R : Type u} [CommRing R] [IsReduced R]
    (I : Ideal R) (a : R) (_ha : a ∈ I) :
    IsReduced (affineBlowup I a) := by
  sorry

/-- A blowup chart at a nonzero element of an ideal in a domain is a domain. -/
theorem affineBlowup_isDomain
    {R : Type u} [CommRing R] [IsDomain R]
    (I : Ideal R) {a : R} (ha : a ∈ I) (ha0 : a ≠ 0) :
    IsDomain (affineBlowup I a) := by
  sorry

/-- The blowup map is dominant when the chosen denominator avoids every
minimal prime. -/
theorem affineBlowup_denseRange
    {R : Type u} [CommRing R] (I : Ideal R) {a : R} (ha : a ∈ I)
    (hmin : ∀ p : MinimalPrimeSpectrum R, a ∉ p.1.asIdeal) :
    DenseRange (PrimeSpectrum.comap (algebraMap R (affineBlowup I a))) := by
  sorry

/-! ## Valuation rings as directed colimits of affine blowups -/

/-- The fibre of an `R`-algebra at an ideal `m`. -/
abbrev fibreRingAtIdeal
    (R : Type u) [CommRing R] (B : Type v) [CommRing B] [Algebra R B]
    (m : Ideal R) : Type v :=
  B ⧸ Ideal.map (algebraMap R B) m

/-- A valuation subring dominates a local ring when the induced map is local.
This records the domination hypothesis from the source without confusing it
with mere containment of the image in the valuation subring. -/
def DominatesValuationSubring
    {R K : Type u} [CommRing R] [IsLocalRing R] [Field K] [Algebra R K]
    (A : ValuationSubring K) : Prop :=
  ∃ f : R →+* (A : Type u),
    (∀ r : R, (f r : K) = algebraMap R K r) ∧ IsLocalHom f

/-- A directed family of affine blowups, indexed by finite subsets of its
target valuation ring, together with the colimit equivalence.  The finite-set
index is a canonical directed indexing of the finite-subset argument in the
source proof. -/
structure ValuationBlowupColimitData
    {R K : Type u} [CommRing R] [IsLocalRing R] [Field K] [Algebra R K]
    (A : ValuationSubring K) where
  ideal : Finset (A : Type u) → Ideal R
  center : Finset (A : Type u) → R
  center_mem : ∀ E, center E ∈ ideal E
  ideal_below_maximal : ∀ E, ideal E ≤ IsLocalRing.maximalIdeal R
  ideal_finite : ∀ E, Module.Finite R (ideal E)
  fibre_nontrivial : ∀ E,
    (0 : fibreRingAtIdeal R (affineBlowup (ideal E) (center E))
      (IsLocalRing.maximalIdeal R)) ≠
      (1 : fibreRingAtIdeal R (affineBlowup (ideal E) (center E))
        (IsLocalRing.maximalIdeal R))
  transition : ∀ {E F : Finset (A : Type u)}, E ⊆ F →
    affineBlowup (ideal E) (center E) →+*
      affineBlowup (ideal F) (center F)
  transition_injective : ∀ {E F : Finset (A : Type u)} (h : E ⊆ F),
    Function.Injective (transition h)
  [directedSystem :
    DirectedSystem
      (fun E : Finset (A : Type u) => affineBlowup (ideal E) (center E))
      (fun {E F : Finset (A : Type u)} (h : E ⊆ F) => transition h)]
  mapToA : ∀ E, affineBlowup (ideal E) (center E) →+* (A : Type u)
  mapToA_injective : ∀ E, Function.Injective (mapToA E)
  mapToA_comp_algebraMap : ∀ E r,
    (mapToA E (algebraMap R (affineBlowup (ideal E) (center E)) r) : K) =
      algebraMap R K r
  map_compat : ∀ {E F : Finset (A : Type u)} (h : E ⊆ F) (x),
    mapToA F (transition h x) = mapToA E x
  colimitEquiv :
    DirectLimit
        (fun E : Finset (A : Type u) => affineBlowup (ideal E) (center E))
        (fun _E _F h => transition h) ≃+* A

/-- A local valuation domain dominating `R` is the directed colimit of the
finite, nontrivial-fibre affine blowups described in the source. -/
theorem valuationRing_directedColimit_affineBlowups
    {R K : Type u} [CommRing R] [IsDomain R] [IsLocalRing R]
    [Field K] [Algebra R K] [IsFractionRing R K]
    (A : ValuationSubring K)
    (hA : DominatesValuationSubring (R := R) (K := K) A) :
    Nonempty (ValuationBlowupColimitData (R := R) (K := K) A) := by
  sorry

end
end Formalization.Books.Algebra.Unit70
