import Formalization.Books.MoreAlgebra.Unit90.FormalGlueing
import Mathlib.Algebra.Homology.ShortComplex.ModuleCat
import Mathlib.Algebra.Module.Projective
import Mathlib.RingTheory.Localization.Module

/-!
# More on Algebra, Chapter 91: The Beauville--Laszlo theorem

This file records the definitions and theorem interfaces in the section on
Beauville--Laszlo glueing.  The completion, ideal-power torsion, localization,
tensor product, Tor, and module-category constructions are the canonical ones
from Mathlib and the preceding formalization chapters.
-/

noncomputable section

open CategoryTheory
open CategoryTheory.Limits
open Formalization.Books.MoreAlgebra.Unit53
open Formalization.Books.MoreAlgebra.Unit05
open Formalization.Books.MoreAlgebra.Unit89
open Formalization.Books.MoreAlgebra.Unit90
open scoped TensorProduct

universe u

namespace Formalization.Books.MoreAlgebra.Unit91

/-! ## Basic completion and torsion notation -/

/-- The `f`-adic completion `R^` from the source, using Mathlib's canonical
adic completion for the principal ideal generated by `f`. -/
abbrev fAdicCompletion (R : Type u) [CommRing R] (f : R) :=
  AdicCompletion (Ideal.span ({f} : Set R)) R

/-- The canonical map from a ring to its `f`-adic completion. -/
abbrev fAdicCompletionMap (R : Type u) [CommRing R] (f : R) :
    R →+* fAdicCompletion R f :=
  algebraMap R (fAdicCompletion R f)

/-- The map on the `n`-th principal quotients induced by a ring map. -/
abbrev powerQuotientMap {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (n : ℕ) :
    R ⧸ Ideal.span ({f ^ n} : Set R) →+*
      S ⧸ Ideal.map φ (Ideal.span ({f ^ n} : Set R)) :=
  idealQuotientMap φ (Ideal.span ({f ^ n} : Set R))

/-- The quotient-isomorphism hypothesis used for a Beauville--Laszlo pair. -/
def SamePowerQuotients {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ n : ℕ, 0 < n → Function.Bijective (powerQuotientMap φ f n)

/-- The canonical `f`-power torsion submodule, in the notation of the source.
This is the principal-ideal specialization of Chapter 89's canonical
`idealPowerTorsionSubmoduleInfinity`. -/
abbrev fPowerTorsionSubmodule {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) : Submodule R M :=
  idealPowerTorsionSubmoduleInfinity (Ideal.span ({f} : Set R))

/-- The source's finite-level notation `M[f^n]`. -/
abbrev fPowerTorsionSubmoduleAt {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) (n : ℕ) : Submodule R M :=
  idealPowerTorsionSubmodule (Ideal.span ({f} : Set R)) n

theorem mem_fPowerTorsionSubmoduleAt_iff
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) (n : ℕ) (x : M) :
    x ∈ fPowerTorsionSubmoduleAt f n ↔
      ∀ a : R, a ∈ Ideal.span ({f} : Set R) ^ n → a • x = 0 := by
  exact mem_idealPowerTorsionSubmodule_iff (Ideal.span ({f} : Set R)) n x

theorem fPowerTorsionSubmoduleInfinity_eq_iUnion
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) :
    ((fPowerTorsionSubmodule (M := M) f : Submodule R M) : Set M) =
      ⋃ n : ℕ, ((fPowerTorsionSubmoduleAt (M := M) f (n + 1)) : Set M) := by
  exact idealPowerTorsionSubmoduleInfinity_coe_eq_iUnion (Ideal.span ({f} : Set R))

theorem fPowerTorsionSubmodule_eq_kernel_localizedMap
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) :
    fPowerTorsionSubmodule f =
      LinearMap.ker (LocalizedModule.mkLinearMap (Submonoid.powers f) M) := by
  sorry

/-- The source's assertion that a module is `f`-power torsion. -/
abbrev IsFPowerTorsion {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) : Prop :=
  IsIPowerTorsion (Ideal.span ({f} : Set R)) M

theorem isFPowerTorsion_iff
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) :
    IsFPowerTorsion (M := M) f ↔
      ∀ x : M, ∃ n : ℕ, 0 < n ∧ f ^ n • x = 0 := by
  exact principal_isIPowerTorsion_iff f

/-- The map on `f`-power torsion elements, expressed without introducing a
parallel submodule map between differently-scalared modules. -/
def MapsFPowerTorsion {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ x : R, x ∈ fPowerTorsionSubmodule f →
    φ x ∈ fPowerTorsionSubmodule (M := S) (φ f)

def InjectiveOnFPowerTorsion {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ ⦃x y : R⦄, x ∈ fPowerTorsionSubmodule f →
    y ∈ fPowerTorsionSubmodule f → φ x = φ y → x = y

def SurjectiveOnFPowerTorsion {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ y : S, y ∈ fPowerTorsionSubmodule (M := S) (φ f) →
    ∃ x : R, x ∈ fPowerTorsionSubmodule f ∧ φ x = y

def BijectiveOnFPowerTorsion {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  MapsFPowerTorsion φ f ∧ InjectiveOnFPowerTorsion φ f ∧
    SurjectiveOnFPowerTorsion φ f

/-! ## The Cech sequence and glueing pairs -/

/- The source's four-term Cech sequence is the compatible-pair pullback for
the principal ring square.  Chapter 5 provides that pullback and Chapter 90
provides the canonical square and module base-change functor. -/

abbrev blRingSquare {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :=
  principalGlueingRingSquare φ f

abbrev blGlueingCategory {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :=
  ModuleGluingCategory (blRingSquare φ f)

noncomputable abbrev blCanFunctor {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    ModuleCat.{u} R ⥤ blGlueingCategory φ f :=
  moduleBaseChangeFunctor (blRingSquare φ f)

noncomputable abbrev blH0Functor {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    blGlueingCategory φ f ⥤ ModuleCat.{u} R :=
  moduleFiberProductRightAdjointCanonical (blRingSquare φ f)

noncomputable abbrev blCanH0Unit {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (M : ModuleCat.{u} R) :
    M ⟶ (blH0Functor φ f).obj ((blCanFunctor φ f).obj M) :=
  (moduleFiberProductAdjunctionData (blRingSquare φ f)).adjunction.unit.app M

def blRingCechLeft {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : R → S × Localization.Away f :=
  fun r => (φ r, algebraMap R (Localization.Away f) r)

def blRingCechRight {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    S × Localization.Away f → Localization.Away (φ f) :=
  fun x => algebraMap S (Localization.Away (φ f)) x.1 -
    Localization.awayMap φ f x.2

def CechExactOnRight {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  Function.Surjective (blRingCechRight φ f)

def CechExactOnLeft {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  Function.Injective (blRingCechLeft φ f)

def CechExactInMiddle {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  Function.Exact (blRingCechLeft φ f) (blRingCechRight φ f)

def RingCechSequenceExact {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  CechExactOnLeft φ f ∧ CechExactInMiddle φ f ∧ CechExactOnRight φ f

def IsGlueingPair {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  SamePowerQuotients φ f ∧ RingCechSequenceExact φ f

/-- The principal-specialized notion `GlueingPair (R,f)` in the source. -/
def IsSelfGlueingPair {R : Type u} [CommRing R] (f : R) : Prop :=
  IsGlueingPair (fAdicCompletionMap R f) f

theorem same_quotients_for_fAdicCompletion
    {R : Type u} [CommRing R] (f : R) :
    SamePowerQuotients (fAdicCompletionMap R f) f := by
  sorry

theorem fAdicCompletion_is_self_glueing_pair
    {R : Type u} [CommRing R] (f : R)
    (h : BijectiveOnFPowerTorsion (fAdicCompletionMap R f) f) :
    IsSelfGlueingPair f := by
  sorry

theorem cech_exact_on_right
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hquot : SamePowerQuotients φ f) :
    CechExactOnRight φ f := by
  sorry

theorem cech_exact_on_left_iff
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hquot : SamePowerQuotients φ f) :
    CechExactOnLeft φ f ↔ InjectiveOnFPowerTorsion φ f := by
  sorry

theorem cech_exact_in_middle_iff
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hquot : SamePowerQuotients φ f) :
    CechExactInMiddle φ f ↔ SurjectiveOnFPowerTorsion φ f := by
  sorry

theorem isGlueingPair_iff_fPowerTorsion_bijective
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    IsGlueingPair φ f ↔ BijectiveOnFPowerTorsion φ f := by
  sorry

theorem isSelfGlueingPair_iff_fPowerTorsion_bijective
    {R : Type u} [CommRing R] (f : R) :
    IsSelfGlueingPair f ↔
      BijectiveOnFPowerTorsion (fAdicCompletionMap R f) f := by
  sorry

def IsFRegularOnModule {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) : Prop :=
  Function.Injective (fun x : M => f • x)

theorem selfGlueingPair_of_isRegular
    {R : Type u} [CommRing R] (f : R) (hf : IsRegular f) :
    IsSelfGlueingPair f := by
  sorry

theorem selfGlueingPair_of_flat_completion
    {R : Type u} [CommRing R] (f : R)
    (hflat : RingHom.Flat (fAdicCompletionMap R f)) :
    IsSelfGlueingPair f := by
  sorry

theorem selfGlueingPair_of_noetherian
    {R : Type u} [CommRing R] [IsNoetherianRing R] (f : R) :
    IsSelfGlueingPair f := by
  sorry

/-! ## The two explicit non-glueing examples -/

open MvPolynomial

def firstBlRelationIdeal (k : Type u) [Field k] :
    Ideal (MvPolynomial (Option ℕ) k) :=
  Ideal.span
    ((Set.range (fun n : ℕ => X none * X (some n))) ∪
      (Set.range (fun n : ℕ =>
        X none * X (some (n + 1)) - X (some n))))

abbrev firstBlPresentedRing (k : Type u) [Field k] :=
  MvPolynomial (Option ℕ) k ⧸ firstBlRelationIdeal k

def firstBlF (k : Type u) [Field k] : firstBlPresentedRing k :=
  Ideal.Quotient.mk (firstBlRelationIdeal k) (X none)

def secondBlRelationIdeal (k : Type u) [Field k] :
    Ideal (MvPolynomial (Option ℕ) k) :=
  Ideal.span (Set.range (fun n : ℕ =>
    (X none) ^ (n + 1) * X (some n)))

abbrev secondBlPresentedRing (k : Type u) [Field k] :=
  MvPolynomial (Option ℕ) k ⧸ secondBlRelationIdeal k

def secondBlF (k : Type u) [Field k] : secondBlPresentedRing k :=
  Ideal.Quotient.mk (secondBlRelationIdeal k) (X none)

theorem first_presented_ring_is_not_a_glueing_pair
    (k : Type u) [Field k] :
    ¬ IsSelfGlueingPair (firstBlF k) := by
  sorry

theorem first_presented_ring_torsion_map_not_injective
    (k : Type u) [Field k] :
    ¬ InjectiveOnFPowerTorsion
      (fAdicCompletionMap (firstBlPresentedRing k) (firstBlF k))
      (firstBlF k) := by
  sorry

theorem second_presented_ring_torsion_map_not_surjective
    (k : Type u) [Field k] :
    ¬ SurjectiveOnFPowerTorsion
      (fAdicCompletionMap (secondBlPresentedRing k) (secondBlF k))
      (secondBlF k) := by
  sorry

/-! ## Faithfulness, finite generation, and spectra -/

def faithfulBaseChangePair {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ (M : ModuleCat.{u} R), Nontrivial (M : Type u) →
    Nontrivial (((ModuleCat.extendScalars φ).obj M : ModuleCat.{u} S) : Type u) ∨
      Nontrivial (((ModuleCat.extendScalars
        (algebraMap R (Localization.Away f))).obj M :
          ModuleCat.{u} (Localization.Away f)) : Type u)

theorem faithfulBaseChangePair_of_same_quotients
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hquot : SamePowerQuotients φ f) :
    faithfulBaseChangePair φ f := by
  sorry

theorem faithfulBaseChangePair_for_fAdicCompletion
    {R : Type u} [CommRing R] (f : R) :
    faithfulBaseChangePair (fAdicCompletionMap R f) f := by
  apply faithfulBaseChangePair_of_same_quotients
  exact same_quotients_for_fAdicCompletion f

def spectrumCoverSurjective {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ p : PrimeSpectrum R,
    (∃ q : PrimeSpectrum S, PrimeSpectrum.comap φ q = p) ∨
      (∃ q : PrimeSpectrum (Localization.Away f),
        PrimeSpectrum.comap (algebraMap R (Localization.Away f)) q = p)

theorem spectrum_cover_surjective_of_mod_f_isomorphism
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R)
    (hquot : Function.Bijective (powerQuotientMap φ f 1)) :
    spectrumCoverSurjective φ f := by
  sorry

theorem spectrum_cover_surjective_for_fAdicCompletion
    {R : Type u} [CommRing R] (f : R) :
    spectrumCoverSurjective (fAdicCompletionMap R f) f := by
  apply spectrum_cover_surjective_of_mod_f_isomorphism
  simpa using (same_quotients_for_fAdicCompletion f 1 (Nat.zero_lt_succ 0))

theorem finite_generation_descends_along_bl_cover
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hquot : SamePowerQuotients φ f)
    (M : ModuleCat.{u} R) :
    Module.Finite R (M : Type u) ↔
      (Module.Finite S
          (((ModuleCat.extendScalars φ).obj M : ModuleCat.{u} S) : Type u) ∧
        Module.Finite (Localization.Away f)
          (((ModuleCat.extendScalars (algebraMap R (Localization.Away f))).obj M :
            ModuleCat.{u} (Localization.Away f)) : Type u)) := by
  sorry

theorem finite_generation_descends_for_fAdicCompletion
    {R : Type u} [CommRing R] (f : R) (M : ModuleCat.{u} R) :
    Module.Finite R (M : Type u) ↔
      (Module.Finite (fAdicCompletion R f)
          (((ModuleCat.extendScalars (fAdicCompletionMap R f)).obj M :
            ModuleCat.{u} (fAdicCompletion R f)) : Type u) ∧
        Module.Finite (Localization.Away f)
          (((ModuleCat.extendScalars (algebraMap R (Localization.Away f))).obj M :
            ModuleCat.{u} (Localization.Away f)) : Type u)) := by
  sorry

/-! ## Glueable modules -/

def moduleCechLeftMap {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R) :
    M →
      (((blCanFunctor φ f).obj (ModuleCat.of R M)).obj.left : Type u) ×
        (((blCanFunctor φ f).obj (ModuleCat.of R M)).obj.right : Type u) :=
  fun x => moduleFiberProductPair (blRingSquare φ f)
    ((blCanFunctor φ f).obj (ModuleCat.of R M))
    ((blCanH0Unit φ f (ModuleCat.of R M)).hom x)

def moduleCechRightMap {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R) :
    (((blCanFunctor φ f).obj (ModuleCat.of R M)).obj.left : Type u) ×
        (((blCanFunctor φ f).obj (ModuleCat.of R M)).obj.right : Type u) →
      (moduleFiberCommonTarget (blRingSquare φ f)
        ((blCanFunctor φ f).obj (ModuleCat.of R M)) : Type u) :=
  fun x =>
    (moduleFiberLeftMap (blRingSquare φ f)
      ((blCanFunctor φ f).obj (ModuleCat.of R M))).hom x.1 -
      (moduleFiberRightMap (blRingSquare φ f)
        ((blCanFunctor φ f).obj (ModuleCat.of R M))).hom x.2

def ModuleCechExactOnRight {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R) : Prop :=
  Function.Surjective (moduleCechRightMap (M := M) φ f)

def ModuleCechExactOnLeft {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R) : Prop :=
  Function.Injective (moduleCechLeftMap (M := M) φ f)

def ModuleCechExactInMiddle {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R) : Prop :=
  Function.Exact (moduleCechLeftMap (M := M) φ f)
    (moduleCechRightMap (M := M) φ f)

def ModuleCechSequenceExact {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R) : Prop :=
  ModuleCechExactOnLeft (M := M) φ f ∧
    ModuleCechExactInMiddle (M := M) φ f ∧
      ModuleCechExactOnRight (M := M) φ f

def IsGlueable {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R) : Prop :=
  ModuleCechSequenceExact (M := M) φ f

def IsSelfGlueable {R M : Type u} [CommRing R] [AddCommGroup M]
    [Module R M] (f : R) : Prop :=
  IsGlueable (M := M) (fAdicCompletionMap R f) f

structure NonGlueableModuleWitness {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) : Prop where
  regular : IsRegular f
  pair : IsSelfGlueingPair f
  torsionWitness : ∃ x : M, x ≠ 0 ∧
    x ∈ fPowerTorsionSubmoduleAt f 1 ∧
      tensorUnitMapOfRingHom (M := M) (fAdicCompletionMap R f) x = 0
  notGlueable : ¬ IsSelfGlueable (M := M) f

theorem exists_nonGlueableModuleWitness :
    ∃ (R M : Type u) (_ : CommRing R) (_ : AddCommGroup M) (_ : Module R M)
      (f : R), NonGlueableModuleWitness (M := M) f := by
  sorry

def InjectiveOnModuleFPowerTorsion {R S M : Type u}
    [CommRing R] [CommRing S] [AddCommGroup M] [Module R M]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ ⦃x y : M⦄,
    x ∈ fPowerTorsionSubmodule f → y ∈ fPowerTorsionSubmodule f →
      tensorUnitMapOfRingHom (M := M) φ x =
        tensorUnitMapOfRingHom (M := M) φ y → x = y

/- The two optimized hypotheses highlighted in the introduction: bijectivity
on ring `f`-power torsion and injectivity on the torsion of a module after
base change. -/
def BeauvilleLaszloHypotheses {R S M : Type u}
    [CommRing R] [CommRing S] [AddCommGroup M] [Module R M]
    (φ : R →+* S) (f : R) : Prop :=
  BijectiveOnFPowerTorsion φ f ∧
    InjectiveOnModuleFPowerTorsion (M := M) φ f

noncomputable def moduleBaseChangeUnit {R S M : Type u}
    [CommRing R] [CommRing S] [AddCommGroup M] [Module R M]
    (φ : R →+* S) (x : M) :
    ((ModuleCat.extendScalars φ).obj (ModuleCat.of R M) : Type u) :=
  ((ModuleCat.extendRestrictScalarsAdj φ).unit.app
    (ModuleCat.of R M)).hom x

def SurjectiveOnModuleFPowerTorsion {R S M : Type u}
    [CommRing R] [CommRing S] [AddCommGroup M] [Module R M]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ y : ((ModuleCat.extendScalars φ).obj (ModuleCat.of R M) : Type u),
    (∃ n : ℕ, 0 < n ∧ (φ f) ^ n • y = 0) →
      ∃ x : M, x ∈ fPowerTorsionSubmodule f ∧
        moduleBaseChangeUnit φ x = y

theorem beauvilleLaszloHypotheses_of_nonzerodivisors
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) (hR : IsRegular f) (hM : IsFRegularOnModule (M := M) f) :
    BeauvilleLaszloHypotheses (M := M) (fAdicCompletionMap R f) f := by
  sorry

theorem module_cech_exact_on_right
    {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R)
    (hquot : SamePowerQuotients φ f) :
    ModuleCechExactOnRight (M := M) φ f := by
  sorry

theorem module_cech_exact_on_left_iff
    {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R)
    (hquot : SamePowerQuotients φ f) :
    ModuleCechExactOnLeft (M := M) φ f ↔
      InjectiveOnModuleFPowerTorsion (M := M) φ f := by
  sorry

theorem module_cech_exact_in_middle_iff
    {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R)
    (hquot : SamePowerQuotients φ f) :
    ModuleCechExactInMiddle (M := M) φ f ↔
      SurjectiveOnModuleFPowerTorsion (M := M) φ f := by
  sorry

theorem glueable_iff_module_fPowerTorsion_bijective
    {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R)
    (hquot : SamePowerQuotients φ f) :
    IsGlueable (M := M) φ f ↔
      InjectiveOnModuleFPowerTorsion (M := M) φ f ∧
        SurjectiveOnModuleFPowerTorsion (M := M) φ f := by
  sorry

theorem glueable_iff_injective_when_pair_is_glueing
    {R S M : Type u} [CommRing R] [CommRing S]
    [AddCommGroup M] [Module R M] (φ : R →+* S) (f : R)
    (hpair : IsGlueingPair φ f) :
    IsGlueable (M := M) φ f ↔
      InjectiveOnModuleFPowerTorsion (M := M) φ f := by
  sorry

theorem selfGlueable_iff_completion_torsion_injective
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) (hpair : IsSelfGlueingPair f) :
    IsSelfGlueable (R := R) (M := M) f ↔
      InjectiveOnModuleFPowerTorsion (R := R) (M := M)
        (fAdicCompletionMap R f) f := by
  sorry

def TorsionToCompletionInjective {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) : Prop :=
  InjectiveOnModuleFPowerTorsion (M := M) (fAdicCompletionMap R f) f

def FirstTorsionToCompletionInjective {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) : Prop :=
  ∀ ⦃x y : M⦄,
    x ∈ idealPowerTorsionSubmodule (Ideal.span ({f} : Set R)) 1 →
    y ∈ idealPowerTorsionSubmodule (Ideal.span ({f} : Set R)) 1 →
    tensorUnitMapOfRingHom (M := M) (fAdicCompletionMap R f) x =
      tensorUnitMapOfRingHom (M := M) (fAdicCompletionMap R f) y → x = y

def FPowerTorsionIntersectionVanishing {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) : Prop :=
  ∀ x : M,
    x ∈ idealPowerTorsionSubmodule (Ideal.span ({f} : Set R)) 1 →
      (∀ n : ℕ, ∃ y : M, f ^ (n + 1) • y = x) → x = 0

theorem first_torsion_injective_iff_intersection_vanishing
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) :
    FirstTorsionToCompletionInjective (M := M) f ↔
      FPowerTorsionIntersectionVanishing (M := M) f := by
  sorry

theorem glueable_of_torsion_to_completion_injective
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) (hpair : IsSelfGlueingPair f)
    (hinj : TorsionToCompletionInjective (M := M) f) :
    IsSelfGlueable (M := M) f := by
  sorry

theorem first_torsion_injective_implies_glueable
    {R M : Type u} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) (hpair : IsSelfGlueingPair f)
    (hinj : FirstTorsionToCompletionInjective (M := M) f) :
    IsSelfGlueable (M := M) f := by
  sorry

def RestrictedLocalizationTarget
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : ModuleCat.{u} R :=
  (ModuleCat.restrictScalars
    ((Localization.awayMap φ f).comp (algebraMap R (Localization.Away f)))).obj
    (ModuleCat.of (Localization.Away (φ f)) (Localization.Away (φ f)))

def TorOneWithRestrictedTarget
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (M : ModuleCat.{u} R) : ModuleCat.{u} R :=
  Formalization.Books.Algebra.Unit75.Tor M (RestrictedLocalizationTarget φ f) 1

theorem glueable_of_tor_one_localization_vanishing
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f)
    (M : ModuleCat.{u} R)
    (hTor : IsZero (TorOneWithRestrictedTarget φ f M)) :
    IsGlueable φ f (M := (M : Type u)) := by
  sorry

theorem tor_one_localization_vanishing_iff_tor_one_power_torsion
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (M : ModuleCat.{u} R) :
    IsZero (TorOneWithRestrictedTarget φ f M) ↔
      IsFPowerTorsion (R := R)
        (M := (Formalization.Books.Algebra.Unit75.Tor M
          (RestrictedLocalizationTarget φ f) 1 : Type u)) f := by
  sorry

theorem flat_module_is_glueable_for_pair
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f)
    (M : ModuleCat.{u} R) (hflat : Module.Flat R (M : Type u)) :
    IsGlueable φ f (M := (M : Type u)) := by
  sorry

theorem all_modules_are_glueable_of_flat_ring_map
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f)
    (hflat : RingHom.Flat φ) (M : ModuleCat.{u} R) :
    IsGlueable φ f (M := (M : Type u)) := by
  sorry

/-! ## Tor interfaces used in the proof -/

def TorOneVanishing {R : Type u} [CommRing R]
    (M N : ModuleCat.{u} R) : Prop :=
  IsZero (Formalization.Books.Algebra.Unit75.Tor M N 1)

noncomputable abbrev restrictedTargetModule
    {R S : Type u} [CommRing R] [CommRing S] (φ : R →+* S) :
    ModuleCat.{u} R :=
  (ModuleCat.restrictScalars φ).obj (ModuleCat.of S S)

noncomputable abbrev principalIdealModule
    {R : Type u} [CommRing R] (f : R) (n : ℕ) : ModuleCat.{u} R :=
  ModuleCat.of R (Ideal.span ({f ^ n} : Set R))

noncomputable def localizedModuleMap
    {R : Type u} [CommRing R]
    (f : R) (N : ModuleCat.{u} R) :
    N ⟶ ModuleCat.of R (LocalizedModule (Submonoid.powers f) (N : Type u)) :=
  ModuleCat.ofHom (LocalizedModule.mkLinearMap (Submonoid.powers f) (N : Type u))

def TorOneVanishingOnPrincipalIdeal
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (n : ℕ) : Prop :=
  TorOneVanishing (restrictedTargetModule φ) (principalIdealModule f n)

theorem tor_one_vanishes_on_principal_ideal
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f) (n : ℕ) (hn : 0 < n) :
    TorOneVanishingOnPrincipalIdeal φ f n := by
  sorry

noncomputable abbrev torsionFreeQuotientModule
    {R : Type u} [CommRing R] (f : R) : ModuleCat.{u} R :=
  ModuleCat.of R (R ⧸ fPowerTorsionSubmodule (R := R) (M := R) f)

theorem tor_one_vanishes_on_torsion_free_quotient
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f) :
    TorOneVanishing (restrictedTargetModule φ) (torsionFreeQuotientModule f) := by
  sorry

theorem tor_one_vanishes_on_localization_cokernel
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f)
    (M : ModuleCat.{u} R) :
    TorOneVanishing (restrictedTargetModule φ)
      (cokernel (localizedModuleMap f M : M ⟶
        ModuleCat.of R (LocalizedModule (Submonoid.powers f) (M : Type u)))) := by
  sorry

def TorOneVanishingOnAllLocalizationCokernels {R S : Type u}
    [CommRing R] [CommRing S] (φ : R →+* S) (f : R) : Prop :=
  ∀ M : ModuleCat.{u} R,
    TorOneVanishing (restrictedTargetModule φ)
      (cokernel (localizedModuleMap f M : M ⟶
        ModuleCat.of R (LocalizedModule (Submonoid.powers f) (M : Type u))))

theorem tor_one_vanishes_on_all_localization_cokernels
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f) :
    TorOneVanishingOnAllLocalizationCokernels φ f := by
  sorry

/-! ## Glueing data and the Beauville--Laszlo equivalence -/

/- `blGlueingCategory` is the source's category `Glue(R → R', f)`: its
objects are an `S`-module, an `R_f`-module, and the canonical overlap
isomorphism.  The implementation is Mathlib's `IsoComma` module category,
already used by Chapters 5 and 90. -/

abbrev GlueingDataCategory {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :=
  blGlueingCategory φ f

noncomputable abbrev Can {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    ModuleCat.{u} R ⥤ GlueingDataCategory φ f :=
  blCanFunctor φ f

noncomputable abbrev H0 {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    GlueingDataCategory φ f ⥤ ModuleCat.{u} R :=
  blH0Functor φ f

noncomputable abbrev H0CompatiblePairEquiv
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (X : GlueingDataCategory φ f) :
    ((H0 φ f).obj X : Type u) ≃
      {p // p ∈ moduleFiberCompatiblePairs (blRingSquare φ f) X} :=
  moduleFiberProduct_compatiblePairEquiv (blRingSquare φ f) X

def H0IsKernelStatement {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : Prop :=
  ∀ X : GlueingDataCategory φ f,
    Nonempty (((H0 φ f).obj X : Type u) ≃
      {p // p ∈ moduleFiberCompatiblePairs (blRingSquare φ f) X})

theorem H0_is_kernel_of_glueing_difference
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) : H0IsKernelStatement φ f := by
  intro X
  exact ⟨H0CompatiblePairEquiv φ f X⟩

def GlueableModuleProperty {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :
    ObjectProperty (ModuleCat.{u} R) :=
  fun M => IsGlueable φ f (M := (M : Type u))

abbrev GlueableModuleCategory {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) :=
  (GlueableModuleProperty φ f).FullSubcategory

theorem beauville_laszlo_equivalence
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f) :
    Nonempty (GlueableModuleCategory φ f ≌ GlueingDataCategory φ f) := by
  sorry

structure CanonicalizationData {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (M : ModuleCat.{u} R) where
  module : ModuleCat.{u} R
  canonicalMap : M ⟶ module
  glueable : IsGlueable φ f (M := (module : Type u))
  surjective : Function.Surjective canonicalMap.hom
  formalIso : (ModuleCat.extendScalars φ).obj M ≅
    (ModuleCat.extendScalars φ).obj module
  openIso : (ModuleCat.extendScalars (algebraMap R (Localization.Away f))).obj M ≅
    (ModuleCat.extendScalars (algebraMap R (Localization.Away f))).obj module

theorem canonicalization_of_any_module
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f)
    (M : ModuleCat.{u} R) :
    Nonempty (CanonicalizationData φ f M) := by
  sorry

/-! ## Flatness and finite projectivity -/

theorem flatness_descends_along_bl_pair
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f)
    (M : ModuleCat.{u} R) :
    Module.Flat R (M : Type u) ↔
      (Module.Flat S ((ModuleCat.extendScalars φ).obj M : Type u) ∧
        Module.Flat (Localization.Away f)
          ((ModuleCat.extendScalars (algebraMap R (Localization.Away f))).obj M : Type u)) := by
  sorry

def FiniteProjectiveModule {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] : Prop :=
  Module.Finite R M ∧ Module.Projective R M

theorem finite_projectivity_descends_along_bl_pair
    {R S : Type u} [CommRing R] [CommRing S]
    (φ : R →+* S) (f : R) (hpair : IsGlueingPair φ f)
    (M : ModuleCat.{u} R) :
    FiniteProjectiveModule (R := R) (M := (M : Type u)) ↔
      (FiniteProjectiveModule
          (R := S) (M := ((ModuleCat.extendScalars φ).obj M : Type u)) ∧
        FiniteProjectiveModule
          (R := Localization.Away f)
          (M := ((ModuleCat.extendScalars (algebraMap R (Localization.Away f))).obj M : Type u))) := by
  sorry

theorem finite_projectivity_descends_for_noetherian_completion
    {R : Type u} [CommRing R] [IsNoetherianRing R]
    (f : R) (M : ModuleCat.{u} R) :
    FiniteProjectiveModule (R := R) (M := (M : Type u)) ↔
      (FiniteProjectiveModule
          (R := fAdicCompletion R f)
          (M := (((ModuleCat.extendScalars (fAdicCompletionMap R f)).obj M :
            ModuleCat.{u} (fAdicCompletion R f)) : Type u)) ∧
        FiniteProjectiveModule
          (R := Localization.Away f)
          (M := (((ModuleCat.extendScalars (algebraMap R (Localization.Away f))).obj M :
            ModuleCat.{u} (Localization.Away f)) : Type u))) := by
  sorry

end Formalization.Books.MoreAlgebra.Unit91
