import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.AdicCompletion.Completeness
import Mathlib.RingTheory.Ideal.IsPrincipal
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Data.PNat.Notation

/-!
# Examples, Chapter 8: Noncomplete quotient

This file formalizes the explicit example in the source section
“Noncomplete quotient”.  The normal-form and non-completeness arguments are
recorded as theorem interfaces; the ring, ideals, completion, and the
distinguished Cauchy element use Mathlib's concrete constructions.  The
completion is kept as Mathlib's `AdicCompletion`, so the final quotient
statement uses the canonical image of `(x)` in the completed ring.
-/

noncomputable section

universe u

open scoped BigOperators

namespace Formalization.Books.Examples.Unit08

/-- The countable family of variables used in the quotient-ring example. -/
inductive NoncompleteQuotientVariable where
  | t
  | z (i : ℕ+)
  | w (i : ℕ+)
  | x
deriving DecidableEq

/-- The polynomial ring before imposing the relations from the source. -/
abbrev NoncompleteQuotientPolynomial (k : Type u) [Field k] :=
  MvPolynomial NoncompleteQuotientVariable k

/-- The two families of relations defining the quotient ring. -/
def noncompleteQuotientRelationSet (k : Type u) [Field k] :
    Set (NoncompleteQuotientPolynomial k) :=
  Set.range (fun i : ℕ+ =>
    MvPolynomial.X (.z i) * MvPolynomial.X .t -
      MvPolynomial.X .x ^ (i : ℕ) * MvPolynomial.X (.w i)) ∪
    Set.range (fun ij : ℕ+ × ℕ+ =>
      MvPolynomial.X (.z ij.1) * MvPolynomial.X (.w ij.2))

/-- The ideal generated by `zᵢ t - xⁱ wᵢ` and `zᵢ wⱼ`. -/
def noncompleteQuotientRelationIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientPolynomial k) :=
  Ideal.span (noncompleteQuotientRelationSet k)

/-- The ring `k[t,z₁,z₂,…,w₁,w₂,…,x]/(zᵢt-xⁱwᵢ,zᵢwⱼ)`. -/
abbrev NoncompleteQuotientRing (k : Type u) [Field k] :=
  NoncompleteQuotientPolynomial k ⧸ noncompleteQuotientRelationIdeal k

/-- The quotient map on polynomials. -/
def quotientOfPolynomial {k : Type u} [Field k]
    (p : NoncompleteQuotientPolynomial k) : NoncompleteQuotientRing k :=
  Ideal.Quotient.mk (noncompleteQuotientRelationIdeal k) p

/-- The image in the quotient ring of a polynomial variable. -/
def quotientVariable {k : Type u} [Field k]
    (v : NoncompleteQuotientVariable) : NoncompleteQuotientRing k :=
  quotientOfPolynomial (MvPolynomial.X v)

def tElement (k : Type u) [Field k] : NoncompleteQuotientRing k :=
  quotientVariable (.t : NoncompleteQuotientVariable)

def xElement (k : Type u) [Field k] : NoncompleteQuotientRing k :=
  quotientVariable (.x : NoncompleteQuotientVariable)

def zElement (k : Type u) [Field k] (i : ℕ+) : NoncompleteQuotientRing k :=
  quotientVariable (.z i)

def wElement (k : Type u) [Field k] (i : ℕ+) : NoncompleteQuotientRing k :=
  quotientVariable (.w i)

/-- The defining relation `zᵢt = xⁱwᵢ` in the quotient. -/
theorem zElement_mul_tElement (k : Type u) [Field k] (i : ℕ+) :
    zElement k i * tElement k = xElement k ^ (i : ℕ) * wElement k i := by
  change Ideal.Quotient.mk (noncompleteQuotientRelationIdeal k)
      (MvPolynomial.X (.z i) * MvPolynomial.X .t) =
    Ideal.Quotient.mk (noncompleteQuotientRelationIdeal k)
      (MvPolynomial.X .x ^ (i : ℕ) * MvPolynomial.X (.w i))
  apply (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).2
  exact Ideal.subset_span (Set.mem_union_left _ ⟨i, rfl⟩)

/-- The defining relation `zᵢwⱼ = 0` in the quotient. -/
theorem zElement_mul_wElement (k : Type u) [Field k] (i j : ℕ+) :
    zElement k i * wElement k j = 0 := by
  change Ideal.Quotient.mk (noncompleteQuotientRelationIdeal k)
      (MvPolynomial.X (.z i) * MvPolynomial.X (.w j)) = 0
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  apply Ideal.subset_span
  exact Set.mem_union_right _ ⟨(i, j), rfl⟩

/-- The further relation `zᵢzⱼt = 0` noted in the source. -/
theorem zElement_mul_zElement_mul_tElement (k : Type u) [Field k] (i j : ℕ+) :
    zElement k i * zElement k j * tElement k = 0 := by
  calc
    zElement k i * zElement k j * tElement k =
        zElement k i * (xElement k ^ (j : ℕ) * wElement k j) := by
      rw [mul_assoc, zElement_mul_tElement]
    _ = xElement k ^ (j : ℕ) * (zElement k i * wElement k j) := by
      ac_rfl
    _ = 0 := by
      rw [zElement_mul_wElement, mul_zero]

/-- A reduced coefficient monomial has no `x`, `zᵢt`, or `zᵢwⱼ` factor. -/
def IsReducedNoncompleteQuotientMonomial
    (m : NoncompleteQuotientVariable →₀ ℕ) : Prop :=
  m .x = 0 ∧
    (m .t = 0 ∨ ∀ i, m (.z i) = 0) ∧
    ∀ i, m (.z i) = 0 ∨ ∀ j, m (.w j) = 0

/-- The source's local coefficient restriction before degree-sensitive zero terms
are removed. -/
def IsReducedNoncompleteQuotientCoefficient
    {k : Type u} [Field k] (p : NoncompleteQuotientPolynomial k) : Prop :=
  ∀ m ∈ p.support, IsReducedNoncompleteQuotientMonomial m

/-- A coefficient at degree `i` with no term killed by a defining relation.

The relations imply `xⁱwᵢwⱼ = 0`; the index-sensitive side condition keeps
such terms out of the coefficient at degree `i` while still allowing their
nonzero degree-zero representatives when all `w` indices are larger. -/
def IsCanonicalNoncompleteQuotientCoefficient
    (i : ℕ) {k : Type u} [Field k] (p : NoncompleteQuotientPolynomial k) : Prop :=
  ∀ m ∈ p.support,
    IsReducedNoncompleteQuotientMonomial m ∧
      ∀ j : ℕ+, (i < (j : ℕ)) ∨ m (.w j) = 0 ∨
        (m (.w j) = 1 ∧ ∀ l : ℕ+, l ≠ j → m (.w l) = 0)

/-- The value of a finite coefficient expansion in the quotient ring. -/
def noncompleteQuotientFiniteExpansionValue
    {k : Type u} [Field k] (coeff : ℕ → NoncompleteQuotientPolynomial k)
    (s : Finset ℕ) : NoncompleteQuotientRing k :=
  ∑ i ∈ s, quotientOfPolynomial (coeff i) * xElement k ^ i

/-- The source's canonical finite expansion predicate. -/
def HasCanonicalNoncompleteQuotientFiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientRing k)
    (coeff : ℕ → NoncompleteQuotientPolynomial k) : Prop :=
  (∀ i, IsCanonicalNoncompleteQuotientCoefficient i (coeff i)) ∧
    ∃ s : Finset ℕ,
      (∀ i, coeff i ≠ 0 ↔ i ∈ s) ∧
        f = noncompleteQuotientFiniteExpansionValue coeff s

/-- Every element has a unique finite expansion in the source's normal form. -/
theorem existsUnique_canonicalNoncompleteQuotientFiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientRing k) :
    ∃! coeff : ℕ → NoncompleteQuotientPolynomial k,
      HasCanonicalNoncompleteQuotientFiniteExpansion f coeff := by
  sorry

/-- The principal ideal `(x)` and its powers in the quotient ring. -/
def noncompleteQuotientXIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientRing k) :=
  Ideal.span {xElement k}

def noncompleteQuotientXIdealPow (k : Type u) [Field k] (n : ℕ) :
    Ideal (NoncompleteQuotientRing k) :=
  noncompleteQuotientXIdeal k ^ n

/-- The principal ideal `(t)` in the quotient ring. -/
def noncompleteQuotientTIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientRing k) :=
  Ideal.span {tElement k}

/-- Membership in `(xⁿ)` is detected by the first `n` canonical coefficients. -/
theorem mem_noncompleteQuotientXIdealPow_iff
    {k : Type u} [Field k] {f : NoncompleteQuotientRing k}
    {coeff : ℕ → NoncompleteQuotientPolynomial k}
    (hcoeff : HasCanonicalNoncompleteQuotientFiniteExpansion f coeff) (n : ℕ) :
    f ∈ noncompleteQuotientXIdealPow k n ↔ ∀ i < n, coeff i = 0 := by
  sorry

private theorem canonicalNoncompleteQuotientFiniteExpansion_sub
    {k : Type u} [Field k] {f g : NoncompleteQuotientRing k}
    {p q : ℕ → NoncompleteQuotientPolynomial k}
    (hp : HasCanonicalNoncompleteQuotientFiniteExpansion f p)
    (hq : HasCanonicalNoncompleteQuotientFiniteExpansion g q) :
    HasCanonicalNoncompleteQuotientFiniteExpansion (f - g) (fun i => p i - q i) := by
  classical
  rcases hp with ⟨hp, ⟨sp, hsp, hvp⟩⟩
  rcases hq with ⟨hq, ⟨sq, hsq, hvq⟩⟩
  have hred : ∀ i, IsCanonicalNoncompleteQuotientCoefficient i (p i - q i) := by
    intro i m hm
    have hcoeff : MvPolynomial.coeff m (p i - q i) ≠ 0 :=
      MvPolynomial.mem_support_iff.mp hm
    have hor : MvPolynomial.coeff m (p i) ≠ 0 ∨
        MvPolynomial.coeff m (q i) ≠ 0 := by
      by_contra h
      have hp0 : MvPolynomial.coeff m (p i) = 0 := by
        by_contra hp0
        exact h (Or.inl hp0)
      have hq0 : MvPolynomial.coeff m (q i) = 0 := by
        by_contra hq0
        exact h (Or.inr hq0)
      apply hcoeff
      simp [MvPolynomial.coeff_sub, hp0, hq0]
    rcases hor with hp0 | hq0
    · exact hp i m ((MvPolynomial.mem_support_iff).mpr hp0)
    · exact hq i m ((MvPolynomial.mem_support_iff).mpr hq0)
  let d : ℕ → NoncompleteQuotientPolynomial k := fun i => p i - q i
  let u : Finset ℕ := sp ∪ sq
  let sd : Finset ℕ := u.filter (fun i => d i ≠ 0)
  refine ⟨hred, ⟨sd, ?_, ?_⟩⟩
  · intro i
    constructor
    · intro hdi
      change i ∈ u.filter (fun i => d i ≠ 0)
      apply Finset.mem_filter.mpr
      refine ⟨?_, hdi⟩
      have hor : p i ≠ 0 ∨ q i ≠ 0 := by
        by_contra h
        have hp0 : p i = 0 := by
          by_contra hp0
          exact h (Or.inl hp0)
        have hq0 : q i = 0 := by
          by_contra hq0
          exact h (Or.inr hq0)
        exact hdi (by simp [hp0, hq0])
      rcases hor with hp0 | hq0
      · exact Finset.mem_union_left _ ((hsp i).mp hp0)
      · exact Finset.mem_union_right _ ((hsq i).mp hq0)
    · intro hi
      change i ∈ u.filter (fun i => d i ≠ 0) at hi
      exact (Finset.mem_filter.mp hi).2
  · rcases hvp with rfl
    rcases hvq with rfl
    let P : ℕ → NoncompleteQuotientRing k :=
      fun i => quotientOfPolynomial (p i) * xElement k ^ i
    let Q : ℕ → NoncompleteQuotientRing k :=
      fun i => quotientOfPolynomial (q i) * xElement k ^ i
    let D : ℕ → NoncompleteQuotientRing k :=
      fun i => quotientOfPolynomial (d i) * xElement k ^ i
    let u : Finset ℕ := sp ∪ sq
    have hpu : ∑ i ∈ u, P i = ∑ i ∈ sp, P i := by
      symm
      apply Finset.sum_subset Finset.subset_union_left
      intro i hi hnot
      have hp0 : p i = 0 := by
        apply Classical.byContradiction
        intro hp0
        exact hnot ((hsp i).mp hp0)
      simp [P, quotientOfPolynomial, hp0]
    have hqu : ∑ i ∈ u, Q i = ∑ i ∈ sq, Q i := by
      symm
      apply Finset.sum_subset Finset.subset_union_right
      intro i hi hnot
      have hq0 : q i = 0 := by
        apply Classical.byContradiction
        intro hq0
        exact hnot ((hsq i).mp hq0)
      simp [Q, quotientOfPolynomial, hq0]
    have hdu : sd ⊆ u := by
      change u.filter (fun i => d i ≠ 0) ⊆ u
      exact Finset.filter_subset _ _
    have hdu' : ∑ i ∈ u, D i = ∑ i ∈ sd, D i := by
      symm
      apply Finset.sum_subset hdu
      intro i hi hnot
      have hdi : d i = 0 := by
        by_contra hdi
        exact hnot (Finset.mem_filter.mpr ⟨hi, hdi⟩)
      simp [D, quotientOfPolynomial, hdi]
    simp only [noncompleteQuotientFiniteExpansionValue]
    symm
    change (∑ i ∈ sd, D i) = (∑ i ∈ sp, P i) - ∑ i ∈ sq, Q i
    have hD : ∀ i, D i = P i - Q i := by
      intro i
      simp only [D, P, Q, quotientOfPolynomial]
      rw [map_sub]
      ring
    rw [← hdu']
    calc
      (∑ i ∈ u, D i) = ∑ i ∈ u, (P i - Q i) := by
        apply Finset.sum_congr rfl
        intro i hi
        exact hD i
      _ = (∑ i ∈ u, P i) - ∑ i ∈ u, Q i := by rw [Finset.sum_sub_distrib]
      _ = (∑ i ∈ sp, P i) - ∑ i ∈ sq, Q i := by rw [hpu, hqu]

/-- The element `x` is a zerodivisor: `xⁱwᵢwⱼ = 0`, while `wᵢwⱼ` survives. -/
theorem noncompleteQuotientX_isNotRegular (k : Type u) [Field k] :
    ¬ IsRegular (xElement k) := by
  sorry

/-- The quotient ring is `(x)`-adically separated. -/
theorem iInf_noncompleteQuotientXIdealPow_eq_bot (k : Type u) [Field k] :
    (⨅ n : ℕ, noncompleteQuotientXIdealPow k n) = ⊥ := by
  sorry

/-- The `(x)`-adic completion of the quotient ring. -/
abbrev NoncompleteQuotientCompletion (k : Type u) [Field k] :=
  AdicCompletion (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k)

/-- The image of a base-ring element in its adic completion. -/
def noncompleteQuotientCompletionOf {k : Type u} [Field k]
    (r : NoncompleteQuotientRing k) : NoncompleteQuotientCompletion k :=
  AdicCompletion.of (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k) r

/-- The `(x)` ideal of the completed ring. -/
def noncompleteQuotientCompletionXIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientCompletion k) :=
  (noncompleteQuotientXIdeal k).map
    (algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k))

/-- The image of `(t)` in the completed ring. -/
def noncompleteQuotientCompletionTIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientCompletion k) :=
  (noncompleteQuotientTIdeal k).map
    (algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k))

/-- The completion is complete as a module over the original quotient ring. -/
theorem noncompleteQuotientCompletion_isAdicComplete_over_base
    (k : Type u) [Field k] :
    IsAdicComplete (noncompleteQuotientXIdeal k)
      (NoncompleteQuotientCompletion k) := by
  exact AdicCompletion.isAdicComplete
    (I := noncompleteQuotientXIdeal k)
    (M := NoncompleteQuotientRing k)
    (show Submodule.IsPrincipal
        (noncompleteQuotientXIdeal k :
          Submodule (NoncompleteQuotientRing k) (NoncompleteQuotientRing k)) from
      ⟨xElement k, rfl⟩).fg

/-- The completion is complete for the image of `(x)`. -/
theorem noncompleteQuotientCompletion_isAdicComplete
    (k : Type u) [Field k] :
    IsAdicComplete (noncompleteQuotientCompletionXIdeal k)
      (NoncompleteQuotientCompletion k) := by
  change IsAdicComplete
    ((noncompleteQuotientXIdeal k).map
      (algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k)))
    (NoncompleteQuotientCompletion k)
  exact (IsAdicComplete.map_algebraMap_iff
      (I := noncompleteQuotientXIdeal k)
      (M := NoncompleteQuotientCompletion k)).mpr
    (noncompleteQuotientCompletion_isAdicComplete_over_base k)

/-- A finite partial sum of the source's infinite expansion. -/
def noncompleteQuotientFinitePartialSum
    {k : Type u} [Field k] (coeff : ℕ → NoncompleteQuotientPolynomial k)
    (n : ℕ) : NoncompleteQuotientRing k :=
  ∑ i ∈ Finset.range n, quotientOfPolynomial (coeff i) * xElement k ^ i

/-- An element of the completion is represented by a compatible infinite expansion. -/
def HasCanonicalNoncompleteQuotientInfiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientCompletion k)
    (coeff : ℕ → NoncompleteQuotientPolynomial k) : Prop :=
  (∀ i, IsCanonicalNoncompleteQuotientCoefficient i (coeff i)) ∧
    ∀ n,
      AdicCompletion.evalₐ (noncompleteQuotientXIdeal k) n f =
        Ideal.Quotient.mk (noncompleteQuotientXIdeal k ^ n)
          (noncompleteQuotientFinitePartialSum coeff n)

private theorem canonicalNoncompleteQuotientFiniteExpansion_partialSum
    {k : Type u} [Field k]
    (coeff : ℕ → NoncompleteQuotientPolynomial k)
    (hcoeff : ∀ i, IsCanonicalNoncompleteQuotientCoefficient i (coeff i))
    (n : ℕ) :
    HasCanonicalNoncompleteQuotientFiniteExpansion
      (noncompleteQuotientFinitePartialSum coeff n)
      (fun i => if i < n then coeff i else 0) := by
  classical
  let r : ℕ → NoncompleteQuotientPolynomial k := fun i =>
    if i < n then coeff i else 0
  let s : Finset ℕ := (Finset.range n).filter (fun i => coeff i ≠ 0)
  have hred : ∀ i, IsCanonicalNoncompleteQuotientCoefficient i (r i) := by
    intro i
    by_cases hi : i < n
    · simpa [r, hi] using hcoeff i
    · simp [r, hi, IsCanonicalNoncompleteQuotientCoefficient]
  refine ⟨hred, ⟨s, ?_, ?_⟩⟩
  · intro i
    constructor
    · intro hi
      have hin : i < n := by
        by_contra hin
        exact hi (by simp [hin])
      apply Finset.mem_filter.mpr
      exact ⟨Finset.mem_range.mpr hin, by simpa [r, hin] using hi⟩
    · intro hi
      have hi' := Finset.mem_filter.mp hi
      have hin : i < n := Finset.mem_range.mp hi'.1
      simpa [r, hin] using hi'.2
  · simp only [noncompleteQuotientFiniteExpansionValue,
      noncompleteQuotientFinitePartialSum]
    let T : ℕ → NoncompleteQuotientRing k :=
      fun i => quotientOfPolynomial (coeff i) * xElement k ^ i
    have hs : s ⊆ Finset.range n := Finset.filter_subset _ _
    have hsum : (∑ i ∈ s, quotientOfPolynomial (r i) * xElement k ^ i) =
        ∑ i ∈ Finset.range n, T i := by
      calc
        (∑ i ∈ s, quotientOfPolynomial (r i) * xElement k ^ i) =
            ∑ i ∈ s, T i := by
              apply Finset.sum_congr rfl
              intro i hi
              have hi' := Finset.mem_filter.mp hi
              have hin : i < n := Finset.mem_range.mp hi'.1
              simp [T, r, hin]
        _ = ∑ i ∈ Finset.range n, T i := by
          apply Finset.sum_subset hs
          intro i hi hnot
          have hi0 : coeff i = 0 := by
            by_contra hi0
            exact hnot (Finset.mem_filter.mpr ⟨hi, hi0⟩)
          simp [T, quotientOfPolynomial, hi0]
    simpa [T] using hsum.symm

/-- Every completed element has a unique infinite expansion in canonical form. -/
theorem existsUnique_canonicalNoncompleteQuotientInfiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientCompletion k) :
    ∃! coeff : ℕ → NoncompleteQuotientPolynomial k,
      HasCanonicalNoncompleteQuotientInfiniteExpansion f coeff := by
  classical
  refine AdicCompletion.induction_on (I := noncompleteQuotientXIdeal k)
    (M := NoncompleteQuotientRing k)
    (p := fun f => ∃! coeff, HasCanonicalNoncompleteQuotientInfiniteExpansion f coeff)
    f ?_
  intro a
  let cAt : ℕ → ℕ → NoncompleteQuotientPolynomial k := fun n =>
    (existsUnique_canonicalNoncompleteQuotientFiniteExpansion (a n)).choose
  have hcAt (n : ℕ) :
      HasCanonicalNoncompleteQuotientFiniteExpansion (a n) (cAt n) := by
    exact (existsUnique_canonicalNoncompleteQuotientFiniteExpansion (a n)).choose_spec.1
  have smulTop_le (I : Ideal (NoncompleteQuotientRing k)) :
      (I • (⊤ : Submodule (NoncompleteQuotientRing k) (NoncompleteQuotientRing k))) ≤
        (I : Submodule (NoncompleteQuotientRing k) (NoncompleteQuotientRing k)) := by
    refine Submodule.smul_le.2 ?_
    intro r hr x hx
    simpa [smul_eq_mul] using I.mul_mem_right x hr
  have hcoeffEq {m n : ℕ} (hmn : m ≤ n) (i : ℕ) (hi : i < m) :
      cAt m i = cAt n i := by
    have hs : a m ≡ a n [SMOD
        noncompleteQuotientXIdeal k ^ m •
          (⊤ : Submodule (NoncompleteQuotientRing k) (NoncompleteQuotientRing k))] :=
      a.property hmn
    have hmem : a m - a n ∈ noncompleteQuotientXIdeal k ^ m :=
      smulTop_le _ (SModEq.sub_mem.mp hs)
    have hdiff := canonicalNoncompleteQuotientFiniteExpansion_sub (hcAt m) (hcAt n)
    have hz := (mem_noncompleteQuotientXIdealPow_iff hdiff m).mp hmem i hi
    exact sub_eq_zero.mp hz
  let coeff : ℕ → NoncompleteQuotientPolynomial k := fun i => cAt (i + 1) i
  have hcoeff (i : ℕ) :
      IsCanonicalNoncompleteQuotientCoefficient i (coeff i) := by
    exact (hcAt (i + 1)).1 i
  have hcanonical :
      HasCanonicalNoncompleteQuotientInfiniteExpansion
        (AdicCompletion.mk (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k) a)
        coeff := by
    refine ⟨hcoeff, ?_⟩
    intro n
    rw [AdicCompletion.evalₐ_mk]
    have hpart := canonicalNoncompleteQuotientFiniteExpansion_partialSum coeff hcoeff n
    have hdiff := canonicalNoncompleteQuotientFiniteExpansion_sub (hcAt n) hpart
    have hmem : a n - noncompleteQuotientFinitePartialSum coeff n ∈
        noncompleteQuotientXIdeal k ^ n := by
      have hz := (mem_noncompleteQuotientXIdealPow_iff hdiff n).2
      apply hz
      intro i hi
      dsimp [coeff]
      rw [if_pos hi]
      exact sub_eq_zero.mpr
        (hcoeffEq (Nat.succ_le_of_lt hi) i (Nat.lt_succ_self i)).symm
    exact (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).2 hmem
  refine ⟨coeff, hcanonical, ?_⟩
  intro q hq
  funext i
  let n := i + 1
  have hpart := canonicalNoncompleteQuotientFiniteExpansion_partialSum q hq.1 n
  have hdiff := canonicalNoncompleteQuotientFiniteExpansion_sub (hcAt n) hpart
  have hmem : a n - noncompleteQuotientFinitePartialSum q n ∈
      noncompleteQuotientXIdeal k ^ n := by
    apply (Ideal.Quotient.mk_eq_mk_iff_sub_mem _ _).mp
    simpa only [AdicCompletion.evalₐ_mk] using hq.2 n
  have hz := (mem_noncompleteQuotientXIdealPow_iff hdiff n).mp hmem i (by
    dsimp [n]
    omega)
  dsimp [n] at hz
  rw [if_pos (by omega)] at hz
  dsimp [coeff] at ⊢
  exact (sub_eq_zero.mp hz).symm

/-- The finite partial sums defining `Σ i≥1, xⁱwᵢ`. -/
def noncompleteQuotientBadPartialSum (k : Type u) [Field k] (n : ℕ) :
    NoncompleteQuotientRing k :=
  ∑ i ∈ Finset.range n,
    xElement k ^ (i + 1) * wElement k ⟨i + 1, Nat.succ_pos i⟩

/-- The partial sums form an `x`-adic Cauchy sequence. -/
theorem noncompleteQuotientBadPartialSum_isAdicCauchy
    (k : Type u) [Field k] :
    AdicCompletion.IsAdicCauchy (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k)
      (noncompleteQuotientBadPartialSum k) := by
  rw [AdicCompletion.isAdicCauchy_iff]
  intro n
  rw [show noncompleteQuotientBadPartialSum k (n + 1) =
      noncompleteQuotientBadPartialSum k n +
        xElement k ^ (n + 1) * wElement k ⟨n + 1, Nat.succ_pos n⟩ by
    simp [noncompleteQuotientBadPartialSum, Finset.sum_range_succ]]
  rw [SModEq.sub_mem]
  have hpow : xElement k ^ n ∈ noncompleteQuotientXIdeal k ^ n :=
    Ideal.pow_mem_pow (Ideal.mem_span_singleton_self _) n
  have hterm : xElement k ^ (n + 1) * wElement k ⟨n + 1, Nat.succ_pos n⟩ ∈
      noncompleteQuotientXIdeal k ^ n • (⊤ : Submodule (NoncompleteQuotientRing k)
        (NoncompleteQuotientRing k)) := by
    rw [show xElement k ^ (n + 1) * wElement k ⟨n + 1, Nat.succ_pos n⟩ =
        xElement k ^ n • (xElement k * wElement k ⟨n + 1, Nat.succ_pos n⟩) by
      simp [pow_succ, mul_assoc]]
    exact Submodule.smul_mem_smul hpow Submodule.mem_top
  have hneg := (noncompleteQuotientXIdeal k ^ n •
    (⊤ : Submodule (NoncompleteQuotientRing k) (NoncompleteQuotientRing k))).neg_mem hterm
  simpa [sub_eq_add_neg, neg_add, add_assoc] using hneg

/-- The Cauchy sequence of partial sums as a Mathlib adic Cauchy sequence. -/
def noncompleteQuotientBadCauchySequence (k : Type u) [Field k] :
    AdicCompletion.AdicCauchySequence (noncompleteQuotientXIdeal k)
      (NoncompleteQuotientRing k) :=
  ⟨noncompleteQuotientBadPartialSum k,
    noncompleteQuotientBadPartialSum_isAdicCauchy k⟩

/-- The completed element `f = xw₁ + x²w₂ + x³w₃ + ⋯`. -/
def noncompleteQuotientBadElement (k : Type u) [Field k] :
    NoncompleteQuotientCompletion k :=
  AdicCompletion.mk (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k)
    (noncompleteQuotientBadCauchySequence k)

/-- The coefficients `f₀ = 0` and `fₙ = wₙ` for `n ≥ 1`. -/
def noncompleteQuotientBadCoefficient (k : Type u) [Field k] (n : ℕ) :
    NoncompleteQuotientPolynomial k :=
  if h : n = 0 then 0 else MvPolynomial.X (.w ⟨n, Nat.pos_of_ne_zero h⟩)

/-- The displayed infinite sum has the expected canonical coefficients. -/
theorem noncompleteQuotientBadElement_has_infinite_expansion
    (k : Type u) [Field k] :
    HasCanonicalNoncompleteQuotientInfiniteExpansion
      (noncompleteQuotientBadElement k) (noncompleteQuotientBadCoefficient k) := by
  refine ⟨?_, ?_⟩
  · intro i
    by_cases hi : i = 0
    · simp [noncompleteQuotientBadCoefficient, hi,
        IsCanonicalNoncompleteQuotientCoefficient]
    · rw [noncompleteQuotientBadCoefficient, dif_neg hi]
      rw [IsCanonicalNoncompleteQuotientCoefficient, MvPolynomial.support_X]
      intro m hm
      simp only [Finset.mem_singleton] at hm
      subst m
      constructor
      · simp [IsReducedNoncompleteQuotientMonomial]
      · intro j
        by_cases hj : j = ⟨i, Nat.pos_of_ne_zero hi⟩
        · subst j
          right
          right
          constructor
          · simp
          · intro l hl
            simp only [Finsupp.single_apply]
            split
            · rename_i hwl
              exfalso
              apply hl
              cases hwl
              rfl
            · rfl
        · have hne :
              NoncompleteQuotientVariable.w ⟨i, Nat.pos_of_ne_zero hi⟩ ≠
                NoncompleteQuotientVariable.w j := by
            intro hwl
            apply hj
            cases hwl
            rfl
          right
          left
          simp [hne]
  · intro n
    rw [noncompleteQuotientBadElement, AdicCompletion.evalₐ_mk]
    simp only [noncompleteQuotientBadCauchySequence]
    rw [Ideal.Quotient.mk_eq_mk_iff_sub_mem]
    classical
    have hsum : ∀ m : ℕ,
        noncompleteQuotientBadPartialSum k m =
          noncompleteQuotientFinitePartialSum (noncompleteQuotientBadCoefficient k) m +
            if h : m = 0 then 0
            else xElement k ^ m * wElement k ⟨m, Nat.pos_of_ne_zero h⟩ := by
      intro m
      induction m with
      | zero =>
          simp [noncompleteQuotientBadPartialSum, noncompleteQuotientFinitePartialSum]
      | succ m ih =>
          by_cases hm : m = 0
          · subst m
            simp [noncompleteQuotientBadPartialSum, noncompleteQuotientFinitePartialSum,
              noncompleteQuotientBadCoefficient, quotientOfPolynomial,
              xElement, wElement, quotientVariable]
          · have hbad : noncompleteQuotientBadPartialSum k (m + 1) =
                noncompleteQuotientBadPartialSum k m +
                  xElement k ^ (m + 1) * wElement k ⟨m + 1, Nat.succ_pos m⟩ := by
                simp [noncompleteQuotientBadPartialSum, Finset.sum_range_succ]
            have hfin : noncompleteQuotientFinitePartialSum
                (noncompleteQuotientBadCoefficient k) (m + 1) =
                noncompleteQuotientFinitePartialSum
                    (noncompleteQuotientBadCoefficient k) m +
                  quotientOfPolynomial (noncompleteQuotientBadCoefficient k m) *
                    xElement k ^ m := by
              simp [noncompleteQuotientFinitePartialSum, Finset.sum_range_succ]
            rw [hbad, hfin, ih, dif_neg hm, dif_neg (Nat.succ_ne_zero m),
              noncompleteQuotientBadCoefficient, dif_neg hm]
            rw [show quotientOfPolynomial
                (MvPolynomial.X (.w ⟨m, Nat.pos_of_ne_zero hm⟩)) =
                  wElement k ⟨m, Nat.pos_of_ne_zero hm⟩ by rfl]
            ac_rfl
    rw [hsum n]
    by_cases hn : n = 0
    · simp [hn]
    · rw [dif_neg hn]
      simp only [sub_eq_add_neg, add_assoc]
      have hpow : xElement k ^ n ∈ noncompleteQuotientXIdeal k ^ n :=
        Ideal.pow_mem_pow (Ideal.mem_span_singleton_self _) n
      have hmem : xElement k ^ n * wElement k ⟨n, Nat.pos_of_ne_zero hn⟩ ∈
          noncompleteQuotientXIdeal k ^ n := by
        have h := (noncompleteQuotientXIdeal k ^ n).mul_mem_left
          (wElement k ⟨n, Nat.pos_of_ne_zero hn⟩) hpow
        simpa [mul_comm] using h
      convert hmem using 1
      all_goals ring

/-- Each summand `xⁱwᵢ` belongs to `(t)`, by the relation `zᵢt = xⁱwᵢ`. -/
theorem noncompleteQuotientX_pow_mul_w_mem_t (k : Type u) [Field k] (i : ℕ+) :
    xElement k ^ (i : ℕ) * wElement k i ∈ noncompleteQuotientTIdeal k := by
  sorry

/-- The bad element lies in `(t, xⁿ)` for every `n`. -/
def noncompleteQuotientCompletionMixedIdeal (k : Type u) [Field k] (n : ℕ) :
    Ideal (NoncompleteQuotientCompletion k) :=
  noncompleteQuotientCompletionTIdeal k ⊔
    noncompleteQuotientCompletionXIdeal k ^ n

theorem noncompleteQuotientBadElement_mem_completionMixedIdeal
    (k : Type u) [Field k] (n : ℕ) :
    noncompleteQuotientBadElement k ∈ noncompleteQuotientCompletionMixedIdeal k n := by
  sorry

/-- The bad element is not in `(t)` in the completed ring. -/
theorem noncompleteQuotientBadElement_not_mem_completionTIdeal
    (k : Type u) [Field k] :
    noncompleteQuotientBadElement k ∉ noncompleteQuotientCompletionTIdeal k := by
  sorry

/-- The quotient by `(t)` is not complete for the image of `(x)`. -/
theorem noncompleteQuotientCompletion_quotient_not_isAdicComplete
    (k : Type u) [Field k] :
    ¬ IsAdicComplete (noncompleteQuotientCompletionXIdeal k)
      (NoncompleteQuotientCompletion k ⧸ noncompleteQuotientCompletionTIdeal k) := by
  sorry

theorem noncompleteQuotientCompletionXIdeal_isPrincipal
    (k : Type u) [Field k] :
    Submodule.IsPrincipal
      (noncompleteQuotientCompletionXIdeal k :
        Submodule (NoncompleteQuotientCompletion k) (NoncompleteQuotientCompletion k)) := by
  refine ⟨algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k)
      (xElement k), ?_⟩
  simp [noncompleteQuotientCompletionXIdeal, noncompleteQuotientXIdeal, Ideal.map_span]

theorem noncompleteQuotientCompletionTIdeal_isPrincipal
    (k : Type u) [Field k] :
    Submodule.IsPrincipal
      (noncompleteQuotientCompletionTIdeal k :
        Submodule (NoncompleteQuotientCompletion k) (NoncompleteQuotientCompletion k)) := by
  refine ⟨algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k)
      (tElement k), ?_⟩
  simp [noncompleteQuotientCompletionTIdeal, noncompleteQuotientTIdeal, Ideal.map_span]

/-- A reusable witness for the final existential statement of the source. -/
structure PrincipalNoncompleteQuotientExample (R : Type u) [CommRing R] where
  ideal : Ideal R
  quotientIdeal : Ideal R
  ideal_principal : Submodule.IsPrincipal (ideal : Submodule R R)
  quotientIdeal_principal : Submodule.IsPrincipal (quotientIdeal : Submodule R R)
  complete : IsAdicComplete ideal R
  quotient_not_complete : ¬ IsAdicComplete ideal (R ⧸ quotientIdeal)

/-- There is a complete ring with principal `I` and `J` whose quotient is not complete.

This is the source's final existential statement, with the completed ring from
the construction above retained as an explicit reusable witness. -/
theorem exists_principal_noncomplete_quotient_example
    (k : Type u) [Field k] :
    Nonempty (PrincipalNoncompleteQuotientExample (NoncompleteQuotientCompletion k)) := by
  refine ⟨{
    ideal := noncompleteQuotientCompletionXIdeal k
    quotientIdeal := noncompleteQuotientCompletionTIdeal k
    ideal_principal := noncompleteQuotientCompletionXIdeal_isPrincipal k
    quotientIdeal_principal := noncompleteQuotientCompletionTIdeal_isPrincipal k
    complete := noncompleteQuotientCompletion_isAdicComplete k
    quotient_not_complete := noncompleteQuotientCompletion_quotient_not_isAdicComplete k
  }⟩

end Formalization.Books.Examples.Unit08
