import Mathlib.Data.Complex.Basic
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Exercises, Chapter 17: Dimension

This file contains the canonical ring, polynomial, ideal, and localization
objects used by the three exercises in the source section.
-/

noncomputable section

universe u

namespace Formalization.Books.Exercises.Unit17

/-! ## Exercise `dimension-bigger-one-finite-nr-primes` -/

/- The source asks for a ring with finite prime spectrum and dimension greater
than one.  `PrimeSpectrum` and `ringKrullDim` are Mathlib's canonical
representations of those two notions. -/
def HasFinitePrimeSpectrumAndDimensionAboveOne
    (R : Type u) [CommRing R] : Prop :=
  Finite (PrimeSpectrum R) ∧ 1 < ringKrullDim R

/-! ## Exercise `hypersurface-in-A2-dimension-one` -/

/- The source's `ℂ[x, y]` is represented by `MvPolynomial` on `Fin 2`. -/
abbrev complexBivariatePolynomialRing := MvPolynomial (Fin 2) ℂ

/- A bivariate polynomial is nonconstant exactly when it is not a scalar
polynomial `C c`. -/
def IsNonconstantComplexBivariatePolynomial
    (f : complexBivariatePolynomialRing) : Prop :=
  ∀ c : ℂ,
    f ≠ MvPolynomial.C (R := ℂ) (σ := Fin 2) c

/- The quotient by the principal ideal `(f)`. -/
abbrev complexBivariateHypersurfaceRing
    (f : complexBivariatePolynomialRing) : Type :=
  complexBivariatePolynomialRing ⧸ Ideal.span {f}

/-! ## Exercise `dimension-polynomial-ring` -/

/- The finite-variable polynomial ring `R[x₁, ..., xₙ]`. -/
abbrev polynomialRing (R : Type u) [CommRing R] (n : ℕ) :=
  MvPolynomial (Fin n) R

/- The ideal `(𝔪, x₁, ..., xₙ)` in the polynomial ring.  The first summand
extends the canonical maximal ideal of the local ring and the second is the
canonical ideal generated by all variables. -/
def polynomialMaximalIdeal
    (R : Type u) [CommRing R] [IsLocalRing R] (n : ℕ) :
    Ideal (polynomialRing R n) :=
  Ideal.map (algebraMap R (polynomialRing R n))
      (IsLocalRing.maximalIdeal R) ⊔
    MvPolynomial.idealOfVars (Fin n) R

end Formalization.Books.Exercises.Unit17
