import Formalization.Books.Fields.Unit01.IntroductionStatements
import Formalization.Books.Fields.Unit02.BasicDefinitions
import Mathlib.Algebra.Field.Rat
import Mathlib.Algebra.Field.ZMod
import Mathlib.Algebra.Ring.Pi
import Mathlib.Analysis.Meromorphic.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.Data.ZMod.QuotientRing
import Mathlib.FieldTheory.RatFunc.Basic
import Mathlib.FieldTheory.KummerPolynomial
import Mathlib.LinearAlgebra.Complex.Module
import Mathlib.RingTheory.Ideal.Int
import Mathlib.RingTheory.Polynomial.Quotient

/-!
# Fields, Chapter 3: Examples of fields

This file formalizes the precise assertions in the source section `Examples of fields`.
The chapter uses Mathlib's quotient rings, `ZMod`, `FractionRing`, `RatFunc`, and
`Meromorphic` interfaces directly.
-/

namespace Formalization.Books.Fields.Unit03

open scoped nonZeroDivisors

/-! ## Quotients by maximal ideals -/

/-- A quotient of a commutative ring is a field exactly when its ideal is maximal. -/
theorem quotient_isField_iff_ideal_isMaximal {R : Type*} [CommRing R] (I : Ideal R) :
    IsField (R ⧸ I) ↔ I.IsMaximal := by
  exact (Ideal.Quotient.maximal_ideal_iff_isField_quotient I).symm

/-! ## Rational and prime fields -/

/-- The rational numbers form a field. -/
theorem rationalNumbers_isField : IsField ℚ :=
  Field.toIsField _

/-- The ideal generated by a prime integer is maximal. -/
theorem primeInteger_ideal_isMaximal (p : ℕ) (hp : Nat.Prime p) :
    (Ideal.span {(p : ℤ)}).IsMaximal := by
  exact @Int.ideal_span_isMaximal_of_prime p ⟨hp⟩

/-- The quotient by the ideal generated by a prime integer is a field. -/
theorem primeInteger_quotient_isField (p : ℕ) (hp : Nat.Prime p) :
    IsField (ℤ ⧸ Ideal.span {(p : ℤ)}) := by
  exact (Ideal.Quotient.maximal_ideal_iff_isField_quotient
    (Ideal.span {(p : ℤ)})).mp (@Int.ideal_span_isMaximal_of_prime p ⟨hp⟩)

/-- The prime quotient is canonically the usual finite field `ZMod p`. -/
def primeInteger_quotient_equiv_zmod (p : ℕ) :
    ℤ ⧸ Ideal.span {(p : ℤ)} ≃+* ZMod p :=
  Int.quotientSpanNatEquivZMod p

/-- The prime quotient has exactly `p` elements. -/
theorem primeInteger_quotient_card (p : ℕ) (_hp : Nat.Prime p) :
    Nat.card (ℤ ⧸ Ideal.span {(p : ℤ)}) = p :=
  Int.card_ideal_quot p

/-- The canonical prime field `ZMod p` has exactly `p` elements. -/
theorem zmod_prime_card (p : ℕ) (_hp : Nat.Prime p) : Nat.card (ZMod p) = p :=
  Nat.card_zmod p

/-! ## Polynomial quotients -/

/-- A polynomial ring over a field is a principal ideal domain. -/
theorem polynomial_ring_is_pid (k : Type*) [Field k] :
    IsDomain (Polynomial k) ∧ IsPrincipalIdealRing (Polynomial k) := by
  exact ⟨inferInstance, inferInstance⟩

/-- An ideal generated by an irreducible polynomial is maximal. -/
theorem irreducible_polynomial_ideal_isMaximal {k : Type*} [Field k]
    {P : Polynomial k} (hP : Irreducible P) :
    (Ideal.span {P} : Ideal (Polynomial k)).IsMaximal :=
  PrincipalIdealRing.isMaximal_of_irreducible hP

/-- The quotient by an irreducible polynomial over a field is a field. -/
theorem irreducible_polynomial_quotient_isField {k : Type*} [Field k]
    {P : Polynomial k} (hP : Irreducible P) :
    IsField (Polynomial k ⧸ Ideal.span {P}) := by
  exact (Ideal.Quotient.maximal_ideal_iff_isField_quotient
    (Ideal.span {P} : Ideal (Polynomial k))).mp
    (irreducible_polynomial_ideal_isMaximal hP)

/-- The scalar map gives the natural copy of the base field in an irreducible quotient. -/
theorem irreducible_polynomial_quotient_contains_base_field {k : Type*} [Field k]
    {P : Polynomial k} (hP : Irreducible P) :
    Function.Injective (algebraMap k (Polynomial k ⧸ Ideal.span {P})) := by
  let hQ := irreducible_polynomial_quotient_isField hP
  exact @RingHom.injective k (Polynomial k ⧸ Ideal.span {P})
    _ inferInstance _ hQ.nontrivial (algebraMap k (Polynomial k ⧸ Ideal.span {P}))

/-- The complex numbers admit the standard quotient presentation by `X^2 + 1`. -/
theorem complex_is_quotient_of_real_polynomial :
    Nonempty ((Polynomial ℝ ⧸
      Ideal.span ({Polynomial.X ^ 2 + 1} : Set (Polynomial ℝ))) ≃+* ℂ) := by
  let p : Polynomial ℝ := Polynomial.X ^ 2 + 1
  have hp : Irreducible p := by
    simpa [p, sub_eq_add_neg] using
      (X_pow_sub_C_irreducible_of_prime (K := ℝ) (p := 2) Nat.prime_two
        (a := (-1 : ℝ)) (by
          intro b hb
          have hnonneg : (0 : ℝ) ≤ b ^ 2 := sq_nonneg b
          rw [hb] at hnonneg
          exact (not_lt_of_ge hnonneg) neg_one_lt_zero))
  let f : Polynomial ℝ →ₐ[ℝ] ℂ := Polynomial.aeval Complex.I
  have hf : Function.Surjective f := by
    intro z
    refine ⟨Polynomial.C z.re + Polynomial.C z.im * Polynomial.X, ?_⟩
    apply Complex.ext <;> simp [f, Polynomial.aeval_def]
  have hroot : Polynomial.aeval Complex.I p = 0 := by
    simp [p, Polynomial.aeval_def, Complex.I_sq]
  have hker : RingHom.ker f.toRingHom = Ideal.span {p} := by
    ext q
    rw [RingHom.mem_ker, Ideal.mem_span_singleton]
    exact hp.dvd_iff_aeval_eq_zero hroot
  have e : (Polynomial ℝ ⧸ Ideal.span {p}) ≃ₐ[ℝ] ℂ :=
    (Ideal.quotientEquivAlgOfEq ℝ hker).symm.trans
      (Ideal.quotientKerAlgEquivOfSurjective hf)
  exact ⟨e.toRingEquiv⟩

/-! ## Quotient fields and their universal property -/

/-- The canonical fraction ring of a domain is a field. -/
theorem fractionRing_isField {A : Type*} [CommRing A] [IsDomain A] :
    IsField (FractionRing A) :=
  Field.toIsField _

/-- Every element of a domain's canonical fraction ring is a quotient with nonzero denominator. -/
theorem fractionRing_exists_fraction {A : Type*} [CommRing A] [IsDomain A]
    (x : FractionRing A) :
    ∃ a b : A, b ≠ 0 ∧
      algebraMap A (FractionRing A) a / algebraMap A (FractionRing A) b = x := by
  obtain ⟨a, b, hb, h⟩ := IsFractionRing.div_surjective A x
  exact ⟨a, b, mem_nonZeroDivisors_iff_ne_zero.mp hb, h⟩

/-- Cross multiplication characterizes equality of fraction representatives. -/
theorem fractionRing_mk_eq_mk_iff {A : Type*} [CommRing A] [IsDomain A]
    (a c : A) (b d : A⁰) :
    IsLocalization.mk' (FractionRing A) a b = IsLocalization.mk' (FractionRing A) c d ↔
      a * (d : A) = c * (b : A) := by
  rw [IsLocalization.mk'_eq_iff_eq',
    (IsFractionRing.injective A (FractionRing A)).eq_iff]

/-- The unique extension of an injective map from a domain to a field. -/
noncomputable def fractionRingLift {A K : Type*} [CommRing A] [IsDomain A] [Field K]
    (φ : A →+* K) (hφ : Function.Injective φ) : FractionRing A →+* K :=
  IsFractionRing.lift hφ

/-- The fraction-ring lift agrees with the original map on the domain. -/
theorem fractionRingLift_apply_algebraMap {A K : Type*} [CommRing A] [IsDomain A] [Field K]
    (φ : A →+* K) (hφ : Function.Injective φ) (a : A) :
    fractionRingLift φ hφ (algebraMap A (FractionRing A) a) = φ a := by
  exact IsFractionRing.lift_algebraMap hφ a

/-- The fraction-ring lift sends a representative `a / b` to `φ a / φ b`. -/
theorem fractionRingLift_apply_mk' {A K : Type*} [CommRing A] [IsDomain A] [Field K]
    (φ : A →+* K) (hφ : Function.Injective φ) (a : A) (b : A⁰) :
    fractionRingLift φ hφ (IsLocalization.mk' (FractionRing A) a b) = φ a / φ b := by
  exact IsFractionRing.lift_mk' hφ a b

/-- The fraction-ring lift makes the expected diagram commute. -/
theorem fractionRingLift_comp_algebraMap {A K : Type*} [CommRing A] [IsDomain A] [Field K]
    (φ : A →+* K) (hφ : Function.Injective φ) :
    (fractionRingLift φ hφ).comp (algebraMap A (FractionRing A)) = φ := by
  ext a
  exact fractionRingLift_apply_algebraMap φ hφ a

/-- The extension from a domain to a field is unique. -/
theorem fractionRing_universal_property {A K : Type*} [CommRing A] [IsDomain A] [Field K]
    (φ : A →+* K) (hφ : Function.Injective φ) :
    ∃! ψ : FractionRing A →+* K,
      ∀ a, ψ (algebraMap A (FractionRing A) a) = φ a := by
  refine ⟨fractionRingLift φ hφ, ?_, ?_⟩
  · intro a
    exact fractionRingLift_apply_algebraMap φ hφ a
  · intro ψ hψ
    simpa [fractionRingLift] using (IsFractionRing.lift_unique hφ hψ).symm

/-! ## Rational functions -/

/-- Rational functions over a field are Mathlib's field of fractions of the polynomial ring. -/
theorem rationalFunction_is_fractionRing (k : Type*) [Field k] :
    IsFractionRing (Polynomial k) (RatFunc k) := by
  infer_instance

/-- Rational functions over a field form a field. -/
theorem rationalFunction_isField (k : Type*) [Field k] : IsField (RatFunc k) :=
  Field.toIsField _

/-- Equality of nonzero rational-function representatives is exactly cross multiplication. -/
theorem rationalFunction_mk_eq_mk_iff {k : Type*} [Field k]
    {F G F' G' : Polynomial k} (hG : G ≠ 0) (hG' : G' ≠ 0) :
    RatFunc.mk F G = RatFunc.mk F' G' ↔ F * G' = F' * G :=
  RatFunc.mk_eq_mk hG hG'

/-- Every rational function has a polynomial numerator and a nonzero polynomial denominator. -/
theorem rationalFunction_exists_fraction {k : Type*} [Field k] (f : RatFunc k) :
    ∃ F G : Polynomial k, G ≠ 0 ∧ f = RatFunc.mk F G := by
  induction f using RatFunc.induction_on with
  | f F G hG =>
      exact ⟨F, G, hG, (RatFunc.mk_eq_div F G).symm⟩

/-! ## Meromorphic functions -/

/-- Meromorphic functions in one coordinate form a canonical subring of the function ring. -/
def meromorphicFunctionSubring (𝕜 : Type*) [NontriviallyNormedField 𝕜] :
    Subring (𝕜 → 𝕜) where
  carrier := {f | Meromorphic f}
  zero_mem' := by
    change Meromorphic (fun _ : 𝕜 => (0 : 𝕜))
    exact Meromorphic.const 0
  one_mem' := by
    change Meromorphic (fun _ : 𝕜 => (1 : 𝕜))
    exact Meromorphic.const 1
  add_mem' := by
    intro f g hf hg
    change Meromorphic f at hf
    change Meromorphic g at hg
    change Meromorphic (f + g)
    exact Meromorphic.add hf hg
  neg_mem' := by
    intro f hf
    change Meromorphic f at hf
    change Meromorphic (-f)
    exact Meromorphic.neg hf
  mul_mem' := by
    intro f g hf hg
    change Meromorphic f at hf
    change Meromorphic g at hg
    change Meromorphic (f * g)
    exact Meromorphic.mul hf hg
/-- The inverse of a meromorphic function is meromorphic. -/
theorem meromorphic_inverse_is_meromorphic {𝕜 : Type*} [NontriviallyNormedField 𝕜]
    {f : 𝕜 → 𝕜} (hf : Meromorphic f) : Meromorphic f⁻¹ :=
  Meromorphic.inv hf

/-- In particular, inversion preserves membership in the meromorphic-function subring. -/
theorem meromorphicFunctionSubring_inv_mem {𝕜 : Type*} [NontriviallyNormedField 𝕜]
    {f : 𝕜 → 𝕜} (hf : f ∈ meromorphicFunctionSubring 𝕜) :
    f⁻¹ ∈ meromorphicFunctionSubring 𝕜 := by
  change Meromorphic f at hf
  change Meromorphic f⁻¹
  exact meromorphic_inverse_is_meromorphic hf

end Formalization.Books.Fields.Unit03
