import Mathlib.RingTheory.Algebraic.Basic
import Mathlib.RingTheory.AlgebraicIndependent.Basic
import Mathlib.RingTheory.DiscreteValuationRing.TFAE
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Jacobson.Radical
import Mathlib.RingTheory.KrullDimension.Polynomial
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Localization.Ideal
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.RingTheory.PowerSeries.NoZeroDivisors
import Mathlib.RingTheory.RegularLocalRing.Defs

/-!
# Examples, Chapter 19: A non catenary Noetherian local ring

This file formalizes the precise constructions and assertions in the source
section.  The source's ring-theoretic verifications are theorem interfaces at
this stage; the power-series, generated-subalgebra, ideal, localization, and
scalar-plus-Jacobson-radical constructions themselves use Mathlib's canonical
objects.
-/

noncomputable section

namespace Formalization.«Books.Examples».Unit19

open scoped BigOperators Polynomial

universe u v

section PowerSeriesConstruction

variable (k : Type u) [Field k]

/-- The formal series `z = ∑ i ≥ 1, a i X^i` from the source. -/
noncomputable def zPowerSeries (a : ℕ → k) : PowerSeries k :=
  PowerSeries.mk a

/-- The tail `z_j = ∑ i ≥ j, a i X^(i-j)`. -/
noncomputable def zTail (a : ℕ → k) (j : ℕ) : PowerSeries k :=
  PowerSeries.mk (fun n ↦ a (n + j))

/- The finite initial part subtracted in the source's Laurent-series formula
   for `z_j`.  The range `j - 1` indexes `a₁, ..., a_{j-1}`. -/
def zPrefix (a : ℕ → k) (j : ℕ) : PowerSeries k :=
  Finset.sum (Finset.range (j - 1))
    (fun i ↦ PowerSeries.C (a (i + 1)) * PowerSeries.X ^ (i + 1))

/-- The fraction field of `k⟦X⟧`, used for the source's Laurent series field
`k((x)) = k⟦x⟧[1/x]`. -/
abbrev LaurentSeriesField := FractionRing (PowerSeries k)

/-- The canonical map from the rational function field `k(x)` into the
fraction field of `k⟦x⟧`. -/
noncomputable def rationalFunctionToLaurentSeries :
    FractionRing (Polynomial k) →+* LaurentSeriesField k :=
  IsFractionRing.map
    (j := (Polynomial.coeToPowerSeries.ringHom : Polynomial k →+* PowerSeries k))
    (Polynomial.coe_injective k)

/-- The rational-function-field algebra structure on the Laurent series field. -/
@[instance_reducible] noncomputable def rationalFunctionAlgebra :
    Algebra (FractionRing (Polynomial k)) (LaurentSeriesField k) :=
  RingHom.toAlgebra (rationalFunctionToLaurentSeries k)

/-- A coefficient sequence satisfying the source's zero constant coefficient
and transcendence hypotheses. -/
structure PowerSeriesData where
  coefficients : ℕ → k
  constantCoeff_zero : coefficients 0 = 0
  transcendental :
    letI := rationalFunctionAlgebra k
    Transcendental (FractionRing (Polynomial k))
      (algebraMap (PowerSeries k) (LaurentSeriesField k)
        (zPowerSeries (k := k) coefficients))

variable {k}

/- The displayed definition of `z_j` as a Laurent-series quotient. -/
theorem zTail_eq_inv_X_pow_mul_sub_prefix
    (d : PowerSeriesData k) {j : ℕ} (hj : 1 ≤ j) :
    algebraMap (PowerSeries k) (LaurentSeriesField k)
        (zTail (k := k) d.coefficients j) =
      (algebraMap (PowerSeries k) (LaurentSeriesField k) PowerSeries.X)⁻¹ ^ j *
        (algebraMap (PowerSeries k) (LaurentSeriesField k)
            (zPowerSeries (k := k) d.coefficients) -
          algebraMap (PowerSeries k) (LaurentSeriesField k)
            (zPrefix (k := k) d.coefficients j)) := by
  sorry

/-- The source identity `z = x z₁`. -/
theorem z_eq_X_mul_zTail_one (d : PowerSeriesData k) :
    zPowerSeries (k := k) d.coefficients = PowerSeries.X *
      zTail (k := k) d.coefficients 1 := by
  sorry

/-- The source recursion `x z_(j+1) + a_j = z_j` for `j ≥ 1`. -/
theorem X_mul_zTail_succ_add_coeff_eq_zTail
    (d : PowerSeriesData k) {j : ℕ} (hj : 1 ≤ j) :
    PowerSeries.X * zTail (k := k) d.coefficients (j + 1) +
        PowerSeries.C (d.coefficients j) =
      zTail (k := k) d.coefficients j := by
  sorry

/-- The `k`-subalgebra generated by `x`, `z`, and all the `z_j` (`j ≥ 1`). -/
noncomputable def generatedRing (d : PowerSeriesData k) : Subalgebra k (PowerSeries k) :=
  Algebra.adjoin k
    (insert PowerSeries.X
      (insert (zPowerSeries (k := k) d.coefficients)
        (Set.range (fun j : ℕ ↦ zTail (k := k) d.coefficients (j + 1)))))

/-- The distinguished element `x` in the generated ring. -/
noncomputable def xInGeneratedRing (d : PowerSeriesData k) : generatedRing d :=
  ⟨PowerSeries.X, Algebra.subset_adjoin (by simp)⟩

/-- The distinguished element `z` in the generated ring. -/
noncomputable def zInGeneratedRing (d : PowerSeriesData k) : generatedRing d :=
  ⟨zPowerSeries (k := k) d.coefficients, Algebra.subset_adjoin (by simp)⟩

/-- The element `z_(j+1)` in the generated ring. -/
noncomputable def zSuccInGeneratedRing (d : PowerSeriesData k) (j : ℕ) : generatedRing d :=
  ⟨zTail (k := k) d.coefficients (j + 1),
    Algebra.subset_adjoin (by
      exact Or.inr (Or.inr (Set.mem_range.2 ⟨j, rfl⟩)))⟩

end PowerSeriesConstruction

section TheTwoLocalizations

variable {k : Type u} [Field k]

/-- The ring `R = k[x, z₁, z₂, ...] ⊂ k⟦x⟧`. -/
noncomputable abbrev R (d : PowerSeriesData k) := generatedRing d

/-- The canonical inclusion of the generated ring into the power-series ring. -/
noncomputable def generatedRingInclusion (d : PowerSeriesData k) : R d →+* PowerSeries k :=
  (generatedRing d).val.toRingHom

/- The scalar structure used to state the transcendence degree of the
   fraction field of `R`.  Mathlib deliberately does not make this tower
   algebra an unconditional instance because of possible instance diamonds. -/
@[instance_reducible] noncomputable def fractionFieldRAlgebra (d : PowerSeriesData k) :
    Algebra k (FractionRing (R d)) :=
  RingHom.toAlgebra
    ((algebraMap (R d) (FractionRing (R d))).comp (algebraMap k (R d)))

/- The source's assertion that the fraction field of `R` has transcendence
   degree two over `k`. -/
theorem fractionField_R_transcendence_degree_two (d : PowerSeriesData k) :
    @Algebra.trdeg k (FractionRing (R d)) _ _ (fractionFieldRAlgebra d) = 2 := by
  sorry

/-- The coefficient sum `a₁ + ⋯ + a_j` occurring in the generators of `𝔫`. -/
def initialCoefficientSum (d : PowerSeriesData k) (j : ℕ) : k :=
  Finset.sum (Finset.range j) (fun i ↦ d.coefficients (i + 1))

/-- The `j`th generator `z_(j+1) + a₁ + ⋯ + a_j` of `𝔫`. -/
noncomputable def nGenerator (d : PowerSeriesData k) (j : ℕ) : R d :=
  zSuccInGeneratedRing d j +
    algebraMap k (R d) (initialCoefficientSum d j)

/-- The maximal ideal `𝔪 = (x)`. -/
noncomputable def mIdeal (d : PowerSeriesData k) : Ideal (R d) :=
  Ideal.span {xInGeneratedRing d}

/-- The ideal `𝔫 = (x - 1, z₁, z₂ + a₁, z₃ + a₁ + a₂, ...)`. -/
noncomputable def nIdeal (d : PowerSeriesData k) : Ideal (R d) :=
  Ideal.span (insert (xInGeneratedRing d - 1) (Set.range (nGenerator d)))

/-- The principal ideal `(x - 1)` used in the intermediate quotient. -/
noncomputable def xSubOneIdeal (d : PowerSeriesData k) : Ideal (R d) :=
  Ideal.span {xInGeneratedRing d - 1}

/-- The quotient by `𝔪` is the coefficient field. -/
theorem quotient_mIdeal_equiv (d : PowerSeriesData k) :
    Nonempty (R d ⧸ mIdeal d ≃+* k) := by
  sorry

/-- The ideal `𝔪` is maximal. -/
theorem mIdeal_isMaximal (d : PowerSeriesData k) :
    (mIdeal d).IsMaximal := by
  sorry

/-- The quotient by `(x - 1)` is the polynomial ring `k[z]`. -/
theorem quotient_xSubOneIdeal_equiv (d : PowerSeriesData k) :
    Nonempty (R d ⧸ xSubOneIdeal d ≃+* Polynomial k) := by
  sorry

theorem nIdeal_eq_span_xSubOne_z (d : PowerSeriesData k) :
    nIdeal d = Ideal.span {xInGeneratedRing d - 1, zInGeneratedRing d} := by
  sorry

/-- The ideal `𝔫` is maximal. -/
theorem nIdeal_isMaximal (d : PowerSeriesData k) :
    (nIdeal d).IsMaximal := by
  sorry

theorem mIdeal_isPrime (d : PowerSeriesData k) :
    (mIdeal d).IsPrime :=
  (mIdeal_isMaximal d).isPrime

theorem nIdeal_isPrime (d : PowerSeriesData k) :
    (nIdeal d).IsPrime :=
  (nIdeal_isMaximal d).isPrime

instance mIdeal_isPrime_instance (d : PowerSeriesData k) :
    (mIdeal d).IsPrime := mIdeal_isPrime d

instance nIdeal_isPrime_instance (d : PowerSeriesData k) :
    (nIdeal d).IsPrime := nIdeal_isPrime d

theorem non_m_maps_to_powerSeries_unit (d : PowerSeriesData k) :
    ∀ r : R d, r ∉ mIdeal d → IsUnit (generatedRingInclusion d r) := by
  sorry

/-- The localization `R_𝔪` embeds in `k⟦x⟧`. -/
theorem localization_m_embeds_in_powerSeries (d : PowerSeriesData k) :
    ∃ f : Localization.AtPrime (mIdeal d) →+* PowerSeries k,
      Function.Injective f ∧
        f.comp (algebraMap (R d) (Localization.AtPrime (mIdeal d))) =
          generatedRingInclusion d := by
  sorry

/-- `R_𝔪` is a discrete valuation ring with residue field `k`. -/
theorem localization_m_is_dvr (d : PowerSeriesData k) :
    IsDiscreteValuationRing (Localization.AtPrime (mIdeal d)) := by
  sorry

theorem localization_m_is_noetherian_regular (d : PowerSeriesData k) :
    IsNoetherianRing (Localization.AtPrime (mIdeal d)) ∧
      IsRegularLocalRing (Localization.AtPrime (mIdeal d)) := by
  sorry

theorem localization_m_has_dimension_one (d : PowerSeriesData k) :
    ringKrullDim (Localization.AtPrime (mIdeal d)) = 1 := by
  sorry

theorem localization_m_has_residue_field_k (d : PowerSeriesData k) :
    Nonempty (IsLocalRing.ResidueField (Localization.AtPrime (mIdeal d)) ≃+* k) := by
  sorry

/-- The residue field at `𝔫` is also `k`. -/
theorem quotient_nIdeal_equiv (d : PowerSeriesData k) :
    Nonempty (R d ⧸ nIdeal d ≃+* k) := by
  sorry

/-- The Laurent polynomial ring `k[x, x⁻¹]`. -/
abbrev LaurentPolynomialRing (k : Type u) [Field k] :=
  Localization.Away (Polynomial.X : Polynomial k)

/-- The polynomial ring `k[x, x⁻¹, z]` used in the presentation of `R_𝔫`. -/
abbrev nPresentationRing (k : Type u) [Field k] := Polynomial (LaurentPolynomialRing k)

/-- The image of `x` in `k[x, x⁻¹]`. -/
noncomputable def xInLaurentPolynomialRing (k : Type u) [Field k] : LaurentPolynomialRing k :=
  algebraMap (Polynomial k) (LaurentPolynomialRing k) Polynomial.X

/-- The maximal ideal `(x - 1, z)` in `k[x, x⁻¹, z]`. -/
noncomputable def nPresentationIdeal (k : Type u) [Field k] : Ideal (nPresentationRing k) :=
  Ideal.span {algebraMap (LaurentPolynomialRing k) (nPresentationRing k)
      (xInLaurentPolynomialRing k) - 1, Polynomial.X}

/-- The presentation ideal is maximal. -/
theorem nPresentationIdeal_isMaximal (k : Type u) [Field k] :
    (nPresentationIdeal k).IsMaximal := by
  sorry

instance nPresentationIdeal_isPrime_instance :
    (nPresentationIdeal k).IsPrime :=
  (nPresentationIdeal_isMaximal k).isPrime

/-- The source's presentation of `R_𝔫` by the localization of
`k[x, x⁻¹, z]` at `(x - 1, z)`. -/
theorem localization_n_presentation (d : PowerSeriesData k) :
    Nonempty (Localization.AtPrime (nPresentationIdeal k) ≃+*
      Localization.AtPrime (nIdeal d)) := by
  sorry

/-- `R_𝔫` is a regular local ring of dimension `2` and residue field `k`. -/
theorem localization_n_is_regular_local_dim_two (d : PowerSeriesData k) :
    IsNoetherianRing (Localization.AtPrime (nIdeal d)) ∧
      IsRegularLocalRing (Localization.AtPrime (nIdeal d)) ∧
      ringKrullDim (Localization.AtPrime (nIdeal d)) = 2 ∧
      Nonempty (IsLocalRing.ResidueField (Localization.AtPrime (nIdeal d)) ≃+* k) := by
  sorry

/-- The source's multiplicative subset `S = (R - 𝔪) ∩ (R - 𝔫)`. -/
def multiplicativeSet (d : PowerSeriesData k) : Set (R d) :=
  ((Set.univ : Set (R d)) \ (mIdeal d : Set (R d))) ∩
    ((Set.univ : Set (R d)) \ (nIdeal d : Set (R d)))

theorem multiplicativeSet_eq_complement_union (d : PowerSeriesData k) :
    multiplicativeSet d =
      (Set.univ : Set (R d)) \ ((mIdeal d : Set (R d)) ∪ (nIdeal d : Set (R d))) := by
  ext r
  simp [multiplicativeSet]

theorem multiplicativeSet_isMultiplicative (d : PowerSeriesData k) :
    1 ∈ multiplicativeSet d ∧
      ∀ {r s : R d}, r ∈ multiplicativeSet d → s ∈ multiplicativeSet d →
        r * s ∈ multiplicativeSet d := by
  sorry

/- The displayed multiplicative subset, bundled as Mathlib's canonical
submonoid structure. -/
noncomputable def multiplicativeSubmonoid (d : PowerSeriesData k) : Submonoid (R d) :=
  { carrier := multiplicativeSet d
    one_mem' := (multiplicativeSet_isMultiplicative d).1
    mul_mem' := by
      intro r s hr hs
      exact (multiplicativeSet_isMultiplicative d).2 hr hs }

/-- The ring `B = S⁻¹R`. -/
noncomputable abbrev B (d : PowerSeriesData k) := Localization (multiplicativeSubmonoid d)

noncomputable instance b_commRing_instance (d : PowerSeriesData k) : CommRing (B d) :=
  inferInstance

theorem b_isDomain (d : PowerSeriesData k) :
    IsDomain (B d) := by
  sorry

instance b_isDomain_instance (d : PowerSeriesData k) : IsDomain (B d) := b_isDomain d

/-- Extension of `𝔪` to `B`. -/
noncomputable def mBIdeal (d : PowerSeriesData k) : Ideal (B d) :=
  Ideal.map (algebraMap (R d) (B d)) (mIdeal d)

/-- Extension of `𝔫` to `B`. -/
noncomputable def nBIdeal (d : PowerSeriesData k) : Ideal (B d) :=
  Ideal.map (algebraMap (R d) (B d)) (nIdeal d)

theorem b_is_k_algebra (d : PowerSeriesData k) :
    Nonempty (Algebra k (B d)) := by
  exact ⟨inferInstance⟩

/-- The two displayed ideals remain maximal after passing from `R` to `B`. -/
theorem mBIdeal_isMaximal (d : PowerSeriesData k) :
    (mBIdeal d).IsMaximal := by
  sorry

theorem nBIdeal_isMaximal (d : PowerSeriesData k) :
    (nBIdeal d).IsMaximal := by
  sorry

theorem mBIdeal_isPrime (d : PowerSeriesData k) :
    (mBIdeal d).IsPrime :=
  (mBIdeal_isMaximal d).isPrime

theorem nBIdeal_isPrime (d : PowerSeriesData k) :
    (nBIdeal d).IsPrime :=
  (nBIdeal_isMaximal d).isPrime

instance mBIdeal_isPrime_instance (d : PowerSeriesData k) :
    (mBIdeal d).IsPrime := mBIdeal_isPrime d

instance nBIdeal_isPrime_instance (d : PowerSeriesData k) :
    (nBIdeal d).IsPrime := nBIdeal_isPrime d

theorem b_maximal_ideals (d : PowerSeriesData k) :
    mBIdeal d ≠ nBIdeal d ∧
      ∀ I : Ideal (B d), I.IsMaximal ↔ I = mBIdeal d ∨ I = nBIdeal d := by
  sorry

theorem b_residue_fields (d : PowerSeriesData k) :
    Nonempty (B d ⧸ mBIdeal d ≃+* k) ∧
      Nonempty (B d ⧸ nBIdeal d ≃+* k) := by
  sorry

theorem b_localization_m_equiv (d : PowerSeriesData k) :
    Nonempty (Localization.AtPrime (mBIdeal d) ≃+*
      Localization.AtPrime (mIdeal d)) := by
  sorry

theorem b_localization_n_equiv (d : PowerSeriesData k) :
    Nonempty (Localization.AtPrime (nBIdeal d) ≃+*
      Localization.AtPrime (nIdeal d)) := by
  sorry

theorem b_localization_m_properties (d : PowerSeriesData k) :
    IsNoetherianRing (Localization.AtPrime (mBIdeal d)) ∧
      IsRegularLocalRing (Localization.AtPrime (mBIdeal d)) ∧
      IsDiscreteValuationRing (Localization.AtPrime (mBIdeal d)) ∧
      ringKrullDim (Localization.AtPrime (mBIdeal d)) = 1 ∧
      Nonempty (IsLocalRing.ResidueField (Localization.AtPrime (mBIdeal d)) ≃+* k) := by
  sorry

theorem b_localization_n_properties (d : PowerSeriesData k) :
    IsNoetherianRing (Localization.AtPrime (nBIdeal d)) ∧
      IsRegularLocalRing (Localization.AtPrime (nBIdeal d)) ∧
      ringKrullDim (Localization.AtPrime (nBIdeal d)) = 2 ∧
      Nonempty (IsLocalRing.ResidueField (Localization.AtPrime (nBIdeal d)) ≃+* k) := by
  sorry

theorem b_isNoetherian (d : PowerSeriesData k) :
    IsNoetherianRing (B d) := by
  sorry

theorem b_dimension_two (d : PowerSeriesData k) :
    ringKrullDim (B d) = 2 := by
  sorry

end TheTwoLocalizations

section ScalarPlusRadical

variable {k : Type u} [Field k]

/- The Jacobson radical is the intersection of the two maximal ideals. -/
noncomputable def jacobsonRadical (d : PowerSeriesData k) : Ideal (B d) :=
  Ring.jacobson (B d)

theorem jacobsonRadical_eq_inf (d : PowerSeriesData k) :
    jacobsonRadical d = mBIdeal d ⊓ nBIdeal d := by
  sorry

/- The canonical subalgebra implementation of `A = k + rad(B)`. -/
noncomputable def A (d : PowerSeriesData k) : Subalgebra k (B d) :=
  Algebra.adjoin k (jacobsonRadical d : Set (B d))

/- The source's scalar-plus-Jacobson-radical carrier description. -/
def scalarPlusJacobianSet (d : PowerSeriesData k) : Set (B d) :=
  {b | ∃ c : k, ∃ r : B d, r ∈ jacobsonRadical d ∧
    b = algebraMap k (B d) c + r}

theorem a_carrier_eq_scalarPlusJacobianSet (d : PowerSeriesData k) :
    (A d : Set (B d)) = scalarPlusJacobianSet d := by
  sorry

noncomputable instance a_commRing_instance (d : PowerSeriesData k) : CommRing (A d) :=
  inferInstance

/- The maximal ideal of `A`, obtained by pulling back the Jacobson radical. -/
noncomputable def aMaximalIdeal (d : PowerSeriesData k) : Ideal (A d) :=
  Ideal.comap (A d).val.toRingHom (jacobsonRadical d)

theorem b_finite_over_a (d : PowerSeriesData k) :
    Module.Finite (A d) (B d) := by
  sorry

theorem b_finite_type_over_a (d : PowerSeriesData k) :
    Algebra.FiniteType (A d) (B d) := by
  sorry

theorem eakin_noetherian_descent (d : PowerSeriesData k)
    (hB : IsNoetherianRing (B d)) (hfinite : Module.Finite (A d) (B d)) :
    IsNoetherianRing (A d) := by
  sorry

theorem a_isNoetherian (d : PowerSeriesData k) :
    IsNoetherianRing (A d) := by
  sorry

theorem a_isDomain (d : PowerSeriesData k) :
    IsDomain (A d) := by
  sorry

theorem a_isLocal (d : PowerSeriesData k) :
    IsLocalRing (A d) := by
  sorry

instance a_isDomain_instance (d : PowerSeriesData k) : IsDomain (A d) := a_isDomain d

instance a_isLocal_instance (d : PowerSeriesData k) : IsLocalRing (A d) := a_isLocal d

theorem aMaximalIdeal_isMaximal (d : PowerSeriesData k) :
    (aMaximalIdeal d).IsMaximal := by
  sorry

theorem a_residue_field (d : PowerSeriesData k) :
    Nonempty (A d ⧸ aMaximalIdeal d ≃+* k) := by
  sorry

theorem a_same_fraction_field (d : PowerSeriesData k) :
    Nonempty (FractionRing (A d) ≃+* FractionRing (B d)) := by
  sorry

theorem a_dimension_two (d : PowerSeriesData k) :
    ringKrullDim (A d) = 2 := by
  sorry

/-- The image of the original generator `x` in `B`. -/
noncomputable def xInB (d : PowerSeriesData k) : B d :=
  algebraMap (R d) (B d) (xInGeneratedRing d)

/-- The assertion that `B = A[x]`. -/
theorem b_generated_by_x_over_a (d : PowerSeriesData k) :
    Algebra.adjoin (A d) ({xInB d} : Set (B d)) = ⊤ := by
  sorry

/-- Evaluation at `x` gives the polynomial presentation of `B` over `A`. -/
noncomputable def bPolynomialEvaluation (d : PowerSeriesData k) :
    Polynomial (A d) →+* B d :=
  (Polynomial.aeval (R := A d) (xInB d)).toRingHom

noncomputable def bPresentationPrime (d : PowerSeriesData k) :
    Ideal (Polynomial (A d)) :=
  RingHom.ker (bPolynomialEvaluation d)

theorem bPresentationPrime_isPrime (d : PowerSeriesData k) :
    (bPresentationPrime d).IsPrime := by
  sorry

theorem b_polynomial_presentation (d : PowerSeriesData k) :
    Nonempty (Polynomial (A d) ⧸ bPresentationPrime d ≃+* B d) := by
  sorry

/-- The maximal ideal `m'` of `A[x]` lying over `mB`. -/
noncomputable def mPrime (d : PowerSeriesData k) : Ideal (Polynomial (A d)) :=
  Ideal.comap (bPolynomialEvaluation d) (mBIdeal d)

theorem mPrime_isMaximal (d : PowerSeriesData k) :
    (mPrime d).IsMaximal := by
  sorry

theorem mPrime_isPrime (d : PowerSeriesData k) :
    (mPrime d).IsPrime :=
  (mPrime_isMaximal d).isPrime

instance mPrime_isPrime_instance (d : PowerSeriesData k) :
    (mPrime d).IsPrime := mPrime_isPrime d

/-- The localization of `A[x]` at the maximal ideal `m'`. -/
abbrev mPrimeLocalization (d : PowerSeriesData k) :=
  Localization.AtPrime (mPrime d)

noncomputable instance mPrimeLocalization_commRing_instance (d : PowerSeriesData k) :
    CommRing (mPrimeLocalization d) := inferInstance

/-- The localization of the prime `p` in the displayed chain. -/
noncomputable def pLocalizedIdeal (d : PowerSeriesData k) :
    Ideal (mPrimeLocalization d) :=
  Ideal.map (algebraMap (Polynomial (A d)) (mPrimeLocalization d))
    (bPresentationPrime d)

/-- The maximal ideal in the local ring at `m'`. -/
noncomputable def mPrimeLocalizedIdeal (d : PowerSeriesData k) :
    Ideal (mPrimeLocalization d) :=
  IsLocalRing.maximalIdeal (mPrimeLocalization d)

theorem displayed_prime_chain_strict (d : PowerSeriesData k) :
    (⊥ : Ideal (mPrimeLocalization d)) < pLocalizedIdeal d ∧
      pLocalizedIdeal d < mPrimeLocalizedIdeal d := by
  sorry

theorem mPrime_local_isNoetherian (d : PowerSeriesData k) :
    IsNoetherianRing (mPrimeLocalization d) := by
  sorry

theorem mPrime_local_dimension_three (d : PowerSeriesData k) :
    ringKrullDim (mPrimeLocalization d) = 3 := by
  sorry

end ScalarPlusRadical

section Catenarity

variable {k : Type u} [Field k]

/-- A finite totally ordered set of prime ideals between two fixed endpoints. -/
structure PrimeChainBetween (R : Type*) [CommRing R] (p q : Ideal R) where
  ideals : Set (Ideal R)
  finite : ideals.Finite
  contains_left : p ∈ ideals
  contains_right : q ∈ ideals
  lower_bound : ∀ I ∈ ideals, p ≤ I
  upper_bound : ∀ I ∈ ideals, I ≤ q
  prime : ∀ I ∈ ideals, I.IsPrime
  comparable : ∀ ⦃I J : Ideal R⦄, I ∈ ideals → J ∈ ideals → I ≤ J ∨ J ≤ I

namespace PrimeChainBetween

def length {R : Type*} [CommRing R] {p q : Ideal R}
    (c : PrimeChainBetween R p q) : ℕ :=
  c.ideals.ncard - 1

/-- No prime ideal can be inserted between two members of a saturated chain. -/
def IsSaturated {R : Type*} [CommRing R] {p q : Ideal R}
    (c : PrimeChainBetween R p q) : Prop :=
  ¬ ∃ r : Ideal R, r.IsPrime ∧ r ∉ c.ideals ∧
    ∃ I ∈ c.ideals, ∃ J ∈ c.ideals, I < r ∧ r < J

end PrimeChainBetween

/-- Catenarity expressed by bounded finite chains and equal lengths of finite
    saturated prime chains. -/
def IsCatenaryRing (R : Type*) [CommRing R] : Prop :=
  ∀ (p q : Ideal R), p.IsPrime → q.IsPrime → p ≤ q →
    ∃ n : ℕ, (∀ c : PrimeChainBetween R p q, c.length ≤ n) ∧
      ∀ c d : PrimeChainBetween R p q,
        c.IsSaturated → d.IsSaturated → c.length = d.length

/-- Universal catenarity for a Noetherian ring and all its finite-type
    algebras. -/
def IsUniversallyCatenary (R : Type*) [CommRing R] : Prop :=
  IsNoetherianRing R ∧
    ∀ (S : Type*) [CommRing S] [Algebra R S] [Algebra.FiniteType R S],
      IsCatenaryRing S

def IsNonCatenaryRing (R : Type*) [CommRing R] : Prop :=
  ¬ IsCatenaryRing R

theorem a_isCatenary (d : PowerSeriesData k) :
    IsCatenaryRing (A d) := by
  sorry

theorem universal_catenary_implies_b_m_dimension_two (d : PowerSeriesData k)
    (hA : IsUniversallyCatenary (A d)) :
    ringKrullDim (Localization.AtPrime (mBIdeal d)) = 2 := by
  sorry

theorem b_m_dimension_one (d : PowerSeriesData k) :
    ringKrullDim (Localization.AtPrime (mBIdeal d)) = 1 := by
  sorry

theorem a_not_universally_catenary (d : PowerSeriesData k) :
    ¬ IsUniversallyCatenary (A d) := by
  sorry

noncomputable def displayedPrimeChainIdeals (d : PowerSeriesData k) :
    Set (Ideal (mPrimeLocalization d)) :=
  {⊥, pLocalizedIdeal d, mPrimeLocalizedIdeal d}

theorem exists_displayed_maximal_prime_chain (d : PowerSeriesData k) :
    ∃ c : PrimeChainBetween (mPrimeLocalization d) ⊥ (mPrimeLocalizedIdeal d),
      c.ideals = displayedPrimeChainIdeals d ∧
        c.IsSaturated ∧ c.length = 2 := by
  sorry

theorem polynomial_localization_is_nonCatenary_noetherian_local
    (d : PowerSeriesData k) :
    IsNoetherianRing (mPrimeLocalization d) ∧
      IsLocalRing (mPrimeLocalization d) ∧
      IsNonCatenaryRing (mPrimeLocalization d) := by
  sorry

end Catenarity

section FinalExample

variable {k : Type u} [Field k]

theorem exists_powerSeriesData (k : Type u) [Field k] :
    Nonempty (PowerSeriesData k) := by
  sorry

theorem constructed_A_properties (d : PowerSeriesData k) :
    IsNoetherianRing (A d) ∧ IsLocalRing (A d) ∧ IsDomain (A d) ∧
      ringKrullDim (A d) = 2 ∧ ¬ IsUniversallyCatenary (A d) := by
  sorry

theorem exists_nonCatenaryNoetherianLocalRing (k : Type u) [Field k] :
    ∃ d : PowerSeriesData k,
      IsNoetherianRing (mPrimeLocalization d) ∧
        IsLocalRing (mPrimeLocalization d) ∧
          IsNonCatenaryRing (mPrimeLocalization d) := by
  sorry

end FinalExample

end Formalization.«Books.Examples».Unit19
