import Formalization.Books.Algebra.Unit60
import Formalization.Books.Algebra.Unit67
import Formalization.Books.Algebra.Unit72
import Mathlib.Order.KrullDimension
import Mathlib.RingTheory.KrullDimension.Module
import Mathlib.RingTheory.KrullDimension.Regular
import Mathlib.RingTheory.MvPolynomial
import Mathlib.RingTheory.Localization.AtPrime.Basic

/-!
# Commutative Algebra, Chapter 103: Cohen-Macaulay modules

The local Cohen-Macaulay condition is expressed using the support dimension
and the local depth from the preceding chapters.  Quotients by finite lists
of elements use `Ideal.ofList`, and regular sequences use Mathlib's canonical
`RingTheory.Sequence.IsRegular` predicate.
-/

namespace Formalization.Books.Algebra.Unit103

open Set
open Formalization.Books.Algebra.Unit72
open scoped TensorProduct

universe u v

noncomputable section

/-! ## Quotients, dimensions, and regular sequences -/

/- The quotient by the ideal generated by a finite list of elements. -/
abbrev quotientByList
    {R : Type u} (M : Type v) [CommRing R]
    [AddCommGroup M] [Module R M] (xs : List R) : Type v :=
  M ⧸ (Ideal.ofList xs • (⊤ : Submodule R M))

/- The dimension of the support after cutting by a finite list.  A subset is
   viewed as its canonical subtype, as in the definition of `Order.krullDim`. -/
def supportCutDim
    (R : Type u) (M : Type v) [CommRing R]
    [AddCommGroup M] [Module R M] (xs : List R) : WithBot ℕ∞ :=
  Order.krullDim
    (Module.support R M ∩
      PrimeSpectrum.zeroLocus (Ideal.ofList xs : Set R) : Set (PrimeSpectrum R))

/- A regular sequence is maximal when its length realizes local depth. -/
def IsMaximalRegularSequence
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (xs : List R) : Prop :=
  RingTheory.Sequence.IsRegular M xs ∧
    localDepth R M = (xs.length : ℕ∞)

/-! ## Cohen-Macaulay modules over local rings -/

/- The definition from the source, with both invariants in
   `WithBot ℕ∞`, the value type used by `Module.supportDim`. -/
def IsCohenMacaulay
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] : Prop :=
  ((localDepth R M : ℕ∞) : WithBot ℕ∞) = Module.supportDim R M

/- The source's ``good element'' notation.  The equivalent quotient
   formulation is recorded below using `Module.support_quotient`. -/
def IsGoodElement
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (fs : List R) (g : R) : Prop :=
  g ∈ IsLocalRing.maximalIdeal R ∧
    ∀ i : Fin fs.length,
      supportCutDim R M (g :: fs.take i.1) =
        (((fs.length - i.1 - 1 : ℕ) : ℕ∞) : WithBot ℕ∞)

theorem support_quotientByList
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (xs : List R) :
    Module.support R (quotientByList M xs) =
      Module.support R M ∩
        PrimeSpectrum.zeroLocus (Ideal.ofList xs : Set R) := by
  exact Module.support_quotient (Ideal.ofList xs)

theorem supportCutDim_eq_supportDim_quotientByList
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (xs : List R) :
    supportCutDim R M xs = Module.supportDim R (quotientByList M xs) := by
  unfold supportCutDim Module.supportDim
  rw [support_quotientByList]

/- The displayed equivalence in the source: the dimension condition can be
   read either on the support intersection or on the corresponding quotient. -/
theorem isGoodElement_iff_quotient_supportDim
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (fs : List R) (g : R) :
    IsGoodElement R M fs g ↔
      g ∈ IsLocalRing.maximalIdeal R ∧
        ∀ i : Fin fs.length,
          Module.supportDim R (quotientByList M (g :: fs.take i.1)) =
            (((fs.length - i.1 - 1 : ℕ) : ℕ∞) : WithBot ℕ∞) := by
  simp only [IsGoodElement, supportCutDim_eq_supportDim_quotientByList]

private theorem supportDim_quotSMulTop_eq_supportCutDim_singleton
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M] (g : R) :
    Module.supportDim R (QuotSMulTop g M) = supportCutDim R M [g] := by
  unfold Module.supportDim supportCutDim
  rw [Module.support_quotSMulTop]
  rw [Ideal.ofList_singleton, PrimeSpectrum.zeroLocus_span]

private theorem goodElement_length_one
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (f g : R)
    (hM : IsCohenMacaulay R M)
    (hfs : RingTheory.Sequence.IsRegular M [f])
    (hdim : Module.supportDim R M =
      (((1 : ℕ∞) : WithBot ℕ∞)))
    (hg : g ∈ IsLocalRing.maximalIdeal R)
    (hcut : Module.supportDim R (QuotSMulTop g M) = 0) :
    IsSMulRegular M g ∧
      IsCohenMacaulay R (QuotSMulTop g M) ∧
      IsMaximalRegularSequence R (QuotSMulTop g M) [] := by
  have hMdim : ((localDepth R M : ℕ∞) : WithBot ℕ∞) =
      (((1 : ℕ∞) : WithBot ℕ∞)) := by
    unfold IsCohenMacaulay at hM
    exact hM.trans hdim
  let : Nontrivial M := by
    rw [← Module.supportDim_ne_bot_iff_nontrivial R, hdim]
    simp
  have hfreg : IsSMulRegular M f :=
    (RingTheory.Sequence.isRegular_cons_iff M f []).mp hfs |>.1
  have hreg : IsSMulRegular M g := by
    by_contra hreg
    change ¬ Function.Injective ((g • ·) : M → M) at hreg
    rw [Function.not_injective_iff] at hreg
    rcases hreg with ⟨a, b, hzero, hab⟩
    let K : Submodule R M := LinearMap.ker (LinearMap.lsmul R M g)
    let k : K := ⟨a - b, by
      change g • (a - b) = 0
      rw [smul_sub]
      exact sub_eq_zero.mpr hzero⟩
    have hk_ne : k ≠ 0 := by
      intro hk
      apply hab
      have hk' : (a - b : M) = 0 := congrArg Subtype.val hk
      exact sub_eq_zero.mp hk'
    let : Nontrivial K := ⟨⟨k, 0, hk_ne⟩⟩
    have hgK : g ∈ Module.annihilator R K := by
      rw [Module.mem_annihilator]
      intro z
      have hz := z.property
      change g • (z : M) = 0 at hz
      apply Subtype.ext
      exact hz
    have hKsub : Module.support R K ⊆
        Module.support R (QuotSMulTop g M) := by
      intro p hp
      rw [Module.support_quotSMulTop]
      refine ⟨Module.support_subset_of_injective K.subtype
        K.subtype_injective hp, ?_⟩
      rw [PrimeSpectrum.mem_zeroLocus]
      intro r hr
      have hr' : r = g := by simpa using hr
      rw [hr']
      exact (Module.annihilator_le_of_mem_support hp) hgK
    have hQsupport : Module.support R (QuotSMulTop g M) =
        {IsLocalRing.closedPoint R} := by
      have hQ := support_of_supportDim_eq_zero
        (R := R) (N := QuotSMulTop g M) hcut
      rw [PrimeSpectrum.zeroLocus_eq_singleton] at hQ
      exact hQ
    have hKsupport_sub : Module.support R K ⊆
        {IsLocalRing.closedPoint R} := by
      intro p hp
      rw [← hQsupport]
      exact hKsub hp
    have hclosed : IsLocalRing.closedPoint R ∈ Module.support R K :=
      IsLocalRing.closedPoint_mem_support R K
    have hKsupport : Module.support R K =
        {IsLocalRing.closedPoint R} := by
      apply (Set.subsingleton_iff_singleton hclosed).mp
      intro p hp q hq
      have hp' : p = IsLocalRing.closedPoint R := by
        simpa using hKsupport_sub hp
      have hq' : q = IsLocalRing.closedPoint R := by
        simpa using hKsupport_sub hq
      exact hp'.trans hq'.symm
    have hfinite : IsFiniteLength R K :=
      Formalization.Books.Algebra.Unit62.support_eq_singleton_closedPoint_iff_finiteLength.mp
        hKsupport
    let : IsNoetherian R K :=
      (isFiniteLength_iff_isNoetherian_isArtinian.mp hfinite).1
    let : IsArtinian R K :=
      (isFiniteLength_iff_isNoetherian_isArtinian.mp hfinite).2
    let φ : K →ₗ[R] K :=
      (LinearMap.lsmul R M f).domRestrict K |>.codRestrict K (by
        intro z
        change g • (f • (z : M)) = 0
        have hz := z.property
        change g • (z : M) = 0 at hz
        rw [smul_comm, hz, smul_zero])
    have hφinj : Function.Injective φ := by
      intro x y hxy
      apply Subtype.ext
      apply hfreg
      exact congrArg Subtype.val hxy
    have hφsurj : Function.Surjective φ :=
      IsArtinian.surjective_of_injective_endomorphism φ hφinj
    have hfmax : f ∈ IsLocalRing.maximalIdeal R := by
      by_contra hf
      have hfunit : IsUnit f := (IsLocalRing.notMem_maximalIdeal.mp hf)
      apply hfs.top_ne_smul
      rw [Ideal.ofList_singleton, Ideal.span_singleton_eq_top.mpr hfunit]
      simp
    have hsmul : IsLocalRing.maximalIdeal R •
        (⊤ : Submodule R K) = ⊤ := by
      apply top_unique
      intro z hz
      obtain ⟨z', rfl⟩ := hφsurj z
      exact Submodule.smul_mem_smul hfmax Submodule.mem_top
    have hbot : (⊥ : Submodule R K) = ⊤ := by
      symm
      exact Submodule.eq_bot_of_le_smul_of_le_jacobson_bot
        (IsLocalRing.maximalIdeal R) (⊤ : Submodule R K) Module.Finite.fg_top
        hsmul.symm.le
        (IsLocalRing.maximalIdeal_le_jacobson (⊥ : Ideal R))
    have hKsubsingleton : Subsingleton K := by
      constructor
      intro x y
      have hx : (x : K) ∈ (⊥ : Submodule R K) := by
        rw [hbot]
        exact Submodule.mem_top
      have hy : (y : K) ∈ (⊥ : Submodule R K) := by
        rw [hbot]
        exact Submodule.mem_top
      have hx0 : (x : K) = 0 := by simpa using hx
      have hy0 : (y : K) = 0 := by simpa using hy
      exact hx0.trans hy0.symm
    exact (not_nontrivial_iff_subsingleton.mpr hKsubsingleton)
      (inferInstance : Nontrivial K)
  have hdepth : localDepth R M = 1 := by
    exact WithBot.coe_injective hMdim
  let : Nontrivial (QuotSMulTop g M) := by
    rw [← Module.supportDim_ne_bot_iff_nontrivial R, hcut]
    simp
  have hno : ¬ ∃ q : R, q ∈ IsLocalRing.maximalIdeal R ∧
      IsSMulRegular (QuotSMulTop g M) q := by
    rintro ⟨q, hq, hqreg⟩
    have hle : (2 : ℕ∞) ≤ localDepth R M := by
      rw [localDepth, depth_eq_sSup_weaklyRegular]
      apply le_sSup
      refine ⟨[g, q], by simp, ?_, ?_⟩
      · intro r hr
        rcases List.mem_cons.mp hr with (rfl | hr)
        · exact hg
        · simp only [List.mem_singleton] at hr
          exact hr ▸ hq
      exact RingTheory.Sequence.IsWeaklyRegular.cons hreg
        (RingTheory.Sequence.IsWeaklyRegular.cons hqreg
          (RingTheory.Sequence.IsWeaklyRegular.nil R _))
    rw [hdepth] at hle
    norm_num at hle
  have hdepthQ : localDepth R (QuotSMulTop g M) = 0 := by
    change depth (IsLocalRing.maximalIdeal R) (QuotSMulTop g M) = 0
    exact (depth_eq_zero_iff (IsLocalRing.maximalIdeal R)
      (QuotSMulTop g M)).2 ⟨inferInstance, hno⟩
  have hCMQ : IsCohenMacaulay R (QuotSMulTop g M) := by
    unfold IsCohenMacaulay
    rw [hdepthQ, hcut]
    simp
  refine ⟨hreg, hCMQ, ?_⟩
  unfold IsMaximalRegularSequence
  refine ⟨RingTheory.Sequence.IsRegular.nil R _, ?_⟩
  simpa using hdepthQ

private theorem isRegular_mem_maximalIdeal
    {R : Type u} {N : Type v} [CommRing R] [IsLocalRing R]
    [AddCommGroup N] [Module R N] {xs : List R}
    [Module.Finite R N] (hreg : RingTheory.Sequence.IsRegular N xs)
    {r : R} (hr : r ∈ xs) : r ∈ IsLocalRing.maximalIdeal R := by
  by_contra hrmax
  have hunit : IsUnit r := IsLocalRing.notMem_maximalIdeal.mp hrmax
  have htop : Ideal.ofList xs = (⊤ : Ideal R) := by
    apply top_unique
    rw [← Ideal.span_singleton_eq_top.mpr hunit]
    exact Ideal.span_le.2 (fun x hx => by
      rcases Set.mem_singleton_iff.mp hx with rfl
      exact Ideal.subset_span hr)
  apply hreg.top_ne_smul
  rw [htop]
  simp

private theorem supportDim_eq_cast_of_add_one_eq
    {R : Type u} {N : Type v} [CommRing R]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    (d : ℕ) (x : WithBot ℕ∞)
    (hx : x ≠ ⊥) (h : x + 1 = (((d + 1 : ℕ∞) : WithBot ℕ∞))) :
    x = (((d : ℕ∞) : WithBot ℕ∞)) := by
  obtain ⟨x, rfl⟩ := WithBot.ne_bot_iff_exists.mp hx
  cases hxt : x with
  | top =>
      exfalso
      have h' : (⊤ : WithBot ℕ∞) =
          (((d : ℕ∞) : WithBot ℕ∞)) := by
        simpa [hxt] using h
      have h'' : (⊤ : ℕ∞) = (d : ℕ∞) :=
        WithBot.coe_injective h'
      exact (WithTop.coe_ne_top : (d : ℕ∞) ≠ ⊤) h''.symm
  | coe x =>
      have h' : ((x : ℕ∞) + 1 : WithBot ℕ∞) =
          ((d + 1 : ℕ∞) : WithBot ℕ∞) := by
        simpa [hxt] using h
      have h'' : (x : ℕ∞) + 1 = (d + 1 : ℕ∞) :=
        WithBot.coe_injective h'
      have h''' : x + 1 = d + 1 := by exact_mod_cast h''
      have h'''' : x = d := Nat.succ.inj (by
        simpa [Nat.succ_eq_add_one] using h''')
      simp [h'''']

private theorem isCohenMacaulay_of_isRegular_of_supportDim_eq
    {R : Type u} {N : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup N] [Module R N]
    [Module.Finite R N] (d : ℕ) (xs : List R)
    (hreg : RingTheory.Sequence.IsRegular N xs)
    (hlen : xs.length = d)
    (hdim : Module.supportDim R N =
      (((d : ℕ∞) : WithBot ℕ∞))) :
    IsCohenMacaulay R N := by
  let : Nontrivial N := hreg.nontrivial
  have hdepthge : (d : ℕ∞) ≤ localDepth R N := by
    rw [localDepth, depth_eq_sSup_weaklyRegular]
    apply le_sSup
    refine ⟨xs, by simp [hlen], ?_, hreg.toIsWeaklyRegular⟩
    intro r hr
    exact isRegular_mem_maximalIdeal hreg hr
  have hdepthle : ((localDepth R N : ℕ∞) : WithBot ℕ∞) ≤
      Module.supportDim R N := supportDim_ge_localDepth
  unfold IsCohenMacaulay
  apply le_antisymm hdepthle
  rw [hdim]
  exact_mod_cast hdepthge

private theorem supportCutDim_of_perm
    {R : Type u} {N : Type v} [CommRing R]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    {xs ys : List R} (hperm : List.Perm xs ys) :
    supportCutDim R N xs = supportCutDim R N ys := by
  have hideal : Ideal.ofList xs = Ideal.ofList ys := by
    apply congrArg Ideal.span
    ext r
    exact hperm.mem_iff
  unfold supportCutDim
  rw [hideal]

private theorem supportCutDim_quotSMulTop_eq_cons
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (f : R) (xs : List R) :
    supportCutDim R (QuotSMulTop f M) xs =
      supportCutDim R M (f :: xs) := by
  rw [supportCutDim_eq_supportDim_quotientByList,
    supportCutDim_eq_supportDim_quotientByList]
  exact (Module.supportDim_eq_of_equiv
    (Submodule.quotOfListConsSMulTopEquivQuotSMulTopInner M f xs)).symm

/-! ## The good-element induction -/

theorem goodElement_isSMulRegular_and_quotient_isCohenMacaulay
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (fs : List R) (g : R)
    (hM : IsCohenMacaulay R M)
    (hfs : RingTheory.Sequence.IsRegular M fs)
    (hdim : Module.supportDim R M =
      (((fs.length : ℕ∞) : WithBot ℕ∞)))
    (hgood : IsGoodElement R M fs g)
    /- The source's d = 0 discussion says that no good-element case occurs;
       this positivity hypothesis makes that implicit restriction explicit. -/
    (hpositive : 0 < fs.length) :
    IsSMulRegular M g ∧
      IsCohenMacaulay R (QuotSMulTop g M) ∧
      IsMaximalRegularSequence R (QuotSMulTop g M) fs.dropLast := by
  induction fs generalizing M with
  | nil => simp at hpositive
  | cons f fs ih =>
      obtain ⟨hfreg, hrest⟩ :=
        (RingTheory.Sequence.isRegular_cons_iff M f fs).mp hfs
      obtain ⟨hg, hgooddim⟩ := hgood
      have hfmax : f ∈ IsLocalRing.maximalIdeal R :=
        isRegular_mem_maximalIdeal hfs (by simp)
      by_cases htail : fs = []
      · subst fs
        have hcut : Module.supportDim R (QuotSMulTop g M) = 0 := by
          rw [supportDim_quotSMulTop_eq_supportCutDim_singleton]
          simpa using hgooddim ⟨0, by simp⟩
        exact goodElement_length_one f g hM (by simpa using hfs)
          (by simpa using hdim) hg hcut
      · have htailpos : 0 < fs.length := by
          apply Nat.pos_of_ne_zero
          intro hzero
          apply htail
          cases fs with
          | nil => rfl
          | cons a fs => simp at hzero
        let : Nontrivial (QuotSMulTop f M) := hrest.nontrivial
        have hdimdrop : Module.supportDim R (QuotSMulTop f M) + 1 =
            Module.supportDim R M :=
          Module.supportDim_quotSMulTop_succ_eq_supportDim hfreg hfmax
        have hdimtail : Module.supportDim R (QuotSMulTop f M) =
            (((fs.length : ℕ∞) : WithBot ℕ∞)) := by
          apply supportDim_eq_cast_of_add_one_eq (R := R)
            (N := QuotSMulTop f M) fs.length
            (Module.supportDim R (QuotSMulTop f M))
            ((Module.supportDim_ne_bot_iff_nontrivial R (QuotSMulTop f M)).mpr
              inferInstance)
          simpa [List.length_cons] using hdimdrop.trans hdim
        have hCMtail := isCohenMacaulay_of_isRegular_of_supportDim_eq
          fs.length fs hrest rfl hdimtail
        have hgoodtail : IsGoodElement R (QuotSMulTop f M) fs g := by
          refine ⟨hg, ?_⟩
          intro i
          have hi : i.1 + 1 < (f :: fs).length := by
            simp [List.length_cons]
          have hiNat : i.1 < fs.length := i.isLt
          calc
            supportCutDim R (QuotSMulTop f M) (g :: fs.take i.1) =
                supportCutDim R M (f :: (g :: fs.take i.1)) :=
              supportCutDim_quotSMulTop_eq_cons f _
            _ = supportCutDim R M (g :: (f :: fs.take i.1)) :=
              supportCutDim_of_perm (List.Perm.swap f g (fs.take i.1)).symm
            _ = supportCutDim R M (g :: (f :: fs).take (i.1 + 1)) := by
              simp [List.take]
            _ = (((((f :: fs).length - (i.1 + 1) - 1 : ℕ) : ℕ∞) :
                WithBot ℕ∞)) := hgooddim ⟨i.1 + 1, hi⟩
            _ = (((fs.length - i.1 - 1 : ℕ) : ℕ∞) : WithBot ℕ∞) := by
              simp only [List.length_cons]
              congr 2
              omega
        obtain ⟨hgTail, hCMquot, hmaxquot⟩ := ih hCMtail hrest
          hdimtail hgoodtail htailpos
        let : Nontrivial (QuotSMulTop g (QuotSMulTop f M)) :=
          hmaxquot.1.nontrivial
        have hregTailG : RingTheory.Sequence.IsRegular
            (QuotSMulTop f M) [g] :=
          RingTheory.Sequence.IsRegular.cons hgTail
            (RingTheory.Sequence.IsRegular.nil R _)
        have hregFG : RingTheory.Sequence.IsRegular M [f, g] :=
          RingTheory.Sequence.IsRegular.cons hfreg hregTailG
        have hregGF : RingTheory.Sequence.IsRegular M [g, f] :=
          IsLocalRing.isRegular_of_perm hregFG (List.Perm.swap f g []).symm
        have hgM : IsSMulRegular M g :=
          (RingTheory.Sequence.isRegular_cons_iff M g [f]).mp hregGF |>.1
        let efg : (M ⧸ (Ideal.ofList [f, g] • (⊤ : Submodule R M))) ≃ₗ[R]
            (M ⧸ (Ideal.ofList [g, f] • (⊤ : Submodule R M))) :=
          Submodule.quotEquivOfEq _ _ (by
            congr 1
            apply congrArg Ideal.span
            ext r
            simp [or_comm])
        let qg : QuotSMulTop g M ≃ₗ[R]
            (M ⧸ (Ideal.ofList [g] • (⊤ : Submodule R M))) :=
          Submodule.quotEquivOfEq _ _ (by
            rw [Ideal.ofList_singleton, Submodule.ideal_span_singleton_smul])
        let qf : QuotSMulTop f M ≃ₗ[R]
            (M ⧸ (Ideal.ofList [f] • (⊤ : Submodule R M))) :=
          Submodule.quotEquivOfEq _ _ (by
            rw [Ideal.ofList_singleton, Submodule.ideal_span_singleton_smul])
        let e : QuotSMulTop f (QuotSMulTop g M) ≃ₗ[R]
            QuotSMulTop g (QuotSMulTop f M) :=
          QuotSMulTop.congr f qg ≪≫ₗ
            (Submodule.quotOfListConsSMulTopEquivQuotSMulTopOuter M f [g]).symm
              ≪≫ₗ efg ≪≫ₗ
                Submodule.quotOfListConsSMulTopEquivQuotSMulTopOuter M g [f]
              ≪≫ₗ (QuotSMulTop.congr g qf).symm
        have htailQ : RingTheory.Sequence.IsRegular
            (QuotSMulTop f (QuotSMulTop g M)) fs.dropLast :=
          (e.isRegular_congr fs.dropLast).mpr hmaxquot.1
        have hfQ : IsSMulRegular (QuotSMulTop g M) f :=
          (RingTheory.Sequence.isRegular_cons_iff M g [f]).mp hregGF |>.2 |>
            (RingTheory.Sequence.isRegular_cons_iff (QuotSMulTop g M) f []).mp |>.1
        have hregQ : RingTheory.Sequence.IsRegular
            (QuotSMulTop g M) (f :: fs.dropLast) :=
          RingTheory.Sequence.IsRegular.cons hfQ htailQ
        have hQdim : Module.supportDim R (QuotSMulTop g M) =
            (((fs.length : ℕ∞) : WithBot ℕ∞)) := by
          rw [supportDim_quotSMulTop_eq_supportCutDim_singleton]
          simpa [List.length_cons] using hgooddim ⟨0, by simp⟩
        have hlenQ : (f :: fs.dropLast).length = fs.length := by
          simp [List.length_dropLast]
          omega
        have hCMQ := isCohenMacaulay_of_isRegular_of_supportDim_eq
          fs.length (f :: fs.dropLast) hregQ hlenQ hQdim
        have hdepthQ : localDepth R (QuotSMulTop g M) = fs.length := by
          unfold IsCohenMacaulay at hCMQ
          exact WithBot.coe_injective (hCMQ.trans hQdim)
        refine ⟨hgM, hCMQ, ?_⟩
        have hmaxQ : IsMaximalRegularSequence R (QuotSMulTop g M)
            (f :: fs.dropLast) := ⟨hregQ, by simpa [hlenQ] using hdepthQ⟩
        simpa [List.dropLast, htail] using hmaxQ

/-! ## Cutting by one element -/

/- Proof roadmap for the normal prove stage.

   Universe/interface audit: the previously reported obstruction is stale.
   In `Formalization/Books/Algebra/Unit72/Depth.lean`, both
   `localDepth_le_dim_of_associatedPrime` and `localDepth_drops_by_one` now
   quantify `{R : Type u} {M : Type v}`.  The latter discharges its former
   smallness obstruction internally by comparing `M` and its quotient with
   `ULift.{u} M` and `ULift.{u} (QuotSMulTop g M)` through
   `ULift.moduleEquiv`; do not lift either consumer type here.  Likewise,
   `associatedPrimes`, `ass_subset_support`, and
   `iUnion_associatedPrimes_eq_module_zeroDivisors` in
   `Formalization/Books/Algebra/Unit63/AssociatedPrimes.lean` all accept the
   same independent universes.  Tactic trials at this hole elaborate the
   explicit instantiations `(R := R) (M := M)` for both Unit63 and Unit72.

   1. Unfold `IsCohenMacaulay` at a copy of `hM`.  Its left side is a
      `WithBot` coercion, so `Module.supportDim_ne_bot_iff_nontrivial` gives
      `Nontrivial M`.  Use
      `smul_top_ne_top_of_le_ring_jacobson` and
      `IsLocalRing.maximalIdeal_le_jacobson` to supply the properness
      hypothesis to Unit72's `depth_lt_top_of_noetherian`; hence
      `localDepth R M < top`.
   2. Case-split `localDepth R M`.  The `top` case contradicts that strict
      bound.  Let `Q := QuotSMulTop g M`; Mathlib's
      `nontrivial_quotSMulTop_of_mem_maximalIdeal M hg` and
      `Module.supportDim_ne_bot_iff_nontrivial` show
      `Module.supportDim R Q != bottom`.  In the finite `0` case, rewrite
      `hcut` with `hM` and
      `supportDim_quotSMulTop_eq_supportCutDim_singleton`; then
      `WithBot.add_one_le_zero_iff` contradicts this non-bottom result.  In
      the finite successor case, the same rewrites make `hcut` have shape
      `Module.supportDim R Q + 1 = ((n + 1 : ENat) : WithBot ENat)`; apply
      the local helper `supportDim_eq_cast_of_add_one_eq n` to record
      `hQdim : Module.supportDim R Q = ((n : ENat) : WithBot ENat)`.
   3. Prove regularity by contradiction.  Expand `IsSMulRegular` and use
      `Function.not_injective_iff` to obtain a nonzero `m : M` killed by
      `g` (take the difference of the two witnesses).  Rewrite this
      zero-divisor witness with Unit63's
      `iUnion_associatedPrimes_eq_module_zeroDivisors` and
      `Set.mem_iUnion` to obtain `p : PrimeSpectrum R`,
      `hp : p in Unit63.associatedPrimes R M`, and `g in p.asIdeal`.
      Unit63's `ass_subset_support hp`, followed by
      `Module.support_quotSMulTop` (simp with `Set.mem_inter_iff`,
      `PrimeSpectrum.mem_zeroLocus`, and `Set.singleton_subset_iff`), puts
      `p` in `Module.support R Q`.
   4. At the unchanged universe instantiations `R : Type u` and
      `M : Type v`, chain
      `Unit72.localDepth_le_dim_of_associatedPrime (R := R) (M := M) p hp`
      with Unit72's
      `dim_quotient_le_supportDim_of_mem_support (M := Q) p hpQ`.
      Rewriting the endpoints by the successor depth case and `hQdim`
      gives `n + 1 <= n`; `exact_mod_cast` and
      `Nat.not_succ_le_self` close the contradiction.
   5. Install the `Nontrivial M` proof as an instance and apply
      `Unit72.localDepth_drops_by_one (R := R) (M := M) g hg hreg`.
      In the retained successor case it simplifies to
      `localDepth R Q = n`.  Unfold `IsCohenMacaulay`, rewrite with this
      equality and `hQdim`, and return regularity, quotient
      Cohen--Macaulayness, and the depth-drop equality.
-/
theorem isCohenMacaulay_quotient_by_element
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M) (g : R)
    (hg : g ∈ IsLocalRing.maximalIdeal R)
    (hcut : supportCutDim R M [g] +
      (((1 : ℕ∞) : WithBot ℕ∞)) = Module.supportDim R M) :
      IsSMulRegular M g ∧
      IsCohenMacaulay R (QuotSMulTop g M) ∧
      localDepth R (QuotSMulTop g M) = localDepth R M - 1 := by
  have hMdim : ((localDepth R M : ℕ∞) : WithBot ℕ∞) =
      Module.supportDim R M := by
    exact hM
  let : Nontrivial M := by
    rw [← Module.supportDim_ne_bot_iff_nontrivial R, ← hMdim]
    exact WithBot.coe_ne_bot
  have hmax : IsLocalRing.maximalIdeal R • (⊤ : Submodule R M) ≠ ⊤ :=
    smul_top_ne_top_of_le_ring_jacobson (IsLocalRing.maximalIdeal R) M
      (IsLocalRing.maximalIdeal_le_jacobson (⊥ : Ideal R))
  have hlt : localDepth R M < ⊤ :=
    depth_lt_top_of_noetherian (IsLocalRing.maximalIdeal R) M hmax
  let : Nontrivial (QuotSMulTop g M) :=
    nontrivial_quotSMulTop_of_mem_maximalIdeal M hg
  cases hdepth : localDepth R M with
  | top =>
      rw [hdepth] at hlt
      exact (lt_irrefl _ hlt).elim
  | coe n =>
      cases n with
      | zero =>
          have hcut0 := hcut
          rw [← hMdim, hdepth] at hcut0
          rw [← supportDim_quotSMulTop_eq_supportCutDim_singleton] at hcut0
          have hbot : Module.supportDim R (QuotSMulTop g M) = ⊥ :=
            (ENat.WithBot.add_one_le_zero_iff _).mp (le_of_eq hcut0)
          have hne : Module.supportDim R (QuotSMulTop g M) ≠ ⊥ :=
            (Module.supportDim_ne_bot_iff_nontrivial R
              (QuotSMulTop g M)).mpr inferInstance
          exact (hne hbot).elim
      | succ n =>
          have hcut' := hcut
          rw [← hMdim, hdepth] at hcut'
          rw [← supportDim_quotSMulTop_eq_supportCutDim_singleton] at hcut'
          have hQdim : Module.supportDim R (QuotSMulTop g M) =
              (((n : ℕ∞) : WithBot ℕ∞)) :=
            supportDim_eq_cast_of_add_one_eq (R := R)
              (N := QuotSMulTop g M) n
              (Module.supportDim R (QuotSMulTop g M))
              ((Module.supportDim_ne_bot_iff_nontrivial R
                (QuotSMulTop g M)).mpr inferInstance) hcut'
          have hreg : IsSMulRegular M g := by
            by_contra hreg
            change ¬ Function.Injective ((g • ·) : M → M) at hreg
            rw [Function.not_injective_iff] at hreg
            rcases hreg with ⟨a, b, hzero, hab⟩
            have hne : a - b ≠ 0 := sub_ne_zero.mpr hab
            have hkill : g • (a - b) = 0 := by
              rw [smul_sub, hzero, sub_self]
            have hmem : g ∈
                (⋃ p : {p : PrimeSpectrum R // p ∈
                  Formalization.Books.Algebra.Unit63.associatedPrimes R M},
                  (p.1.asIdeal : Set R)) := by
              rw [Formalization.Books.Algebra.Unit63.iUnion_associatedPrimes_eq_module_zeroDivisors]
              exact ⟨a - b, hne, hkill⟩
            obtain ⟨p, hp⟩ := Set.mem_iUnion.mp hmem
            have hpQ : p.1 ∈ Module.support R (QuotSMulTop g M) := by
              rw [Module.support_quotSMulTop]
              refine ⟨Formalization.Books.Algebra.Unit63.ass_subset_support
                p.2, ?_⟩
              rw [PrimeSpectrum.mem_zeroLocus]
              intro r hr
              have hr' : r = g := by simpa using hr
              rw [hr']
              exact hp
            have hdepthle :=
              localDepth_le_dim_of_associatedPrime (R := R) (M := M)
                p.1 p.2
            have hdimle :=
              dim_quotient_le_supportDim_of_mem_support
                (R := R) (M := QuotSMulTop g M) p.1 hpQ
            have hchain : (((n + 1 : ℕ∞) : WithBot ℕ∞)) ≤
                Module.supportDim R (QuotSMulTop g M) := by
              rw [hdepth] at hdepthle
              exact hdepthle.trans hdimle
            rw [hQdim] at hchain
            have hnat : n + 1 ≤ n := by
              exact_mod_cast hchain
            exact (Nat.not_succ_le_self n hnat).elim
          have hdrop := localDepth_drops_by_one
            (R := R) (M := M) g hg hreg
          have hdropQ : localDepth R (QuotSMulTop g M) = (n : ℕ∞) := by
            calc
              localDepth R (QuotSMulTop g M) =
                  (↑(n + 1) : ℕ∞) - 1 := by
                simpa [hdepth] using hdrop
              _ = (n : ℕ∞) := by
                rw [ENat.natCast_add]
                exact (ENat.addLECancellable_of_ne_top ENat.one_ne_top).add_tsub_cancel_right
          have hCMQ : IsCohenMacaulay R (QuotSMulTop g M) := by
            unfold IsCohenMacaulay
            rw [hdropQ, hQdim]
          exact ⟨hreg, hCMQ, by simpa [hdepth] using hdrop⟩

/-! ## Regular sequences cut out by the expected dimension -/

/- Proof roadmap for the normal prove stage.

   The statement is sound: `hc : c <= d` is exactly what makes the natural
   subtraction in `hquot` meaningful.  The repaired Unit72 depth APIs accept
   `R : Type u`, `M : Type v`; however, the otherwise reusable
   `Unit72.regular_sequence_extend_to_localDepth` still has
   `{R M : Type u}`.  A direct application here reproduces that narrower
   mismatch.  Before proving this theorem, add a private local helper with
   the same conclusion but parameters `{R : Type u} {N : Type v}`.  Copy the
   constructive induction from
   `Formalization/Books/Algebra/Unit72/Depth.lean`:
   in the empty case use `depth_lt_top_of_noetherian` and
   `ENat.sSup_mem_of_nonempty_of_lt_top`; in the cons case use
   `RingTheory.Sequence.isRegular_cons_iff`, recurse on
   `QuotSMulTop x N`, and use the now-polymorphic
   `localDepth_drops_by_one`.  No `ULift` is needed in this local helper.

   1. Also prove a private/local iterated cut bound, for `N : Type v`:
      if every member of `xs : List R` lies in the maximal ideal, then
      `Module.supportDim R N <= supportCutDim R N xs + xs.length`.
      Induct on `xs`; the step is
      `Module.supportDim_le_supportDim_quotSMulTop_succ`, followed by the
      induction hypothesis on `QuotSMulTop x N`, and the existing local
      identity `supportCutDim_quotSMulTop_eq_cons`.  The empty case uses
      `supportCutDim_eq_supportDim_quotientByList` and
      `Submodule.quotEquivOfEqBot` (or the corresponding `simp`).
   2. Induct on `c`.  When `c = 0`, `List.ofFn g = []`; use
      `RingTheory.Sequence.IsRegular.nil` and the universe-polymorphic local
      extension helper.  Obtain `Nontrivial M` from `hM` and `hMdim` via
      `Module.supportDim_ne_bot_iff_nontrivial`, and package the helper's two
      conclusions as `IsMaximalRegularSequence`.
   3. For `c = n + 1`, write `x := g 0`, `gt := Fin.tail g`, and
      `Q := QuotSMulTop x M`; normalize the list with `List.ofFn_cons`.
      From `hc`, record `n <= d - 1`.  The one-element inequality
      `Module.supportDim_le_supportDim_quotSMulTop_succ (hg 0)` gives the
      lower bound `((d - 1 : ENat) : WithBot ENat) <= supportDim R Q`.
      Apply the iterated cut bound to `Q` and `List.ofFn gt` for the upper
      bound.  Transport its final cut through
      `supportCutDim_quotSMulTop_eq_cons`, rewrite `List.ofFn_cons`, and use
      `hquot`; `omega` handles
      `(d - (n + 1)) + n = d - 1`.  Eliminate `bottom`/`top` before casting
      to naturals, or use `supportDim_eq_cast_of_add_one_eq`, to conclude
      `hQdim : Module.supportDim R Q =
        (((d - 1 : Nat) : ENat) : WithBot ENat)`.
   4. Rewrite `supportCutDim R M [x]` using
      `supportDim_quotSMulTop_eq_supportCutDim_singleton`; `hMdim` and
      `hQdim` now supply the cut equality required by
      `isCohenMacaulay_quotient_by_element hM x (hg 0)`.  Retain its three
      outputs `hxreg`, `hQCM`, and `hdrop`.
   5. Apply the induction hypothesis to parameters `d - 1`, `n`, module
      `Q`, and function `gt`.  Its final-quotient hypothesis is `hquot`
      transported by
      `Submodule.quotOfListConsSMulTopEquivQuotSMulTopInner M x
        (List.ofFn gt)` and `Module.supportDim_eq_of_equiv`; normalize
      `(d - 1) - n = d - (n + 1)` using `omega` and `hc`.
   6. Assemble regularity using
      `RingTheory.Sequence.IsRegular.cons hxreg htailreg` and
      `List.ofFn_cons`.  Use the same `ys` returned by the induction
      hypothesis.  Unfold `IsMaximalRegularSequence`; its regularity field
      is the same cons assembly, and its depth field follows from `hdrop`,
      `1 <= localDepth R M` (witness the regular singleton `[x]`),
      `tsub_add_cancel_of_le`, and the induction hypothesis's maximal-depth
      equality, followed by list-length arithmetic.
-/
theorem regularSequence_of_supportDim_quotient_eq
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (d c : ℕ) (hM : IsCohenMacaulay R M)
    (g : Fin c → R)
    /- This keeps the natural subtraction `d - c` faithful to the source's
       dimension difference. -/
    (hc : c ≤ d)
    (hMdim : Module.supportDim R M =
      (((d : ℕ∞) : WithBot ℕ∞)))
    (hg : ∀ i, g i ∈ IsLocalRing.maximalIdeal R)
    (hquot : Module.supportDim R (quotientByList M (List.ofFn g)) =
      (((d - c : ℕ) : ℕ∞) : WithBot ℕ∞)) :
    RingTheory.Sequence.IsRegular M (List.ofFn g) ∧
      ∃ ys : List R,
        IsMaximalRegularSequence R M (List.ofFn g ++ ys) := by
  sorry

/-! ## Standard consequences -/

/- Proof roadmap for the normal prove stage.

   The statement needs no extra nontriviality hypothesis.  If either
   Cohen--Macaulay assumption is available, its equality with a coerced
   local depth forces the relevant support dimension away from `bottom` and
   hence supplies nontriviality.  The universe obstruction is stale:
   `localDepth_drops_by_one` in
   `Formalization/Books/Algebra/Unit72/Depth.lean` has independent
   `{R : Type u} {M : Type v}`, while
   `Module.supportDim_quotSMulTop_succ_eq_supportDim` is in
   `Mathlib/RingTheory/KrullDimension/Regular.lean` and is already
   universe-polymorphic.

   1. Set `Q := QuotSMulTop x M` and record
      `hdim : Module.supportDim R Q + 1 = Module.supportDim R M` using
      `Module.supportDim_quotSMulTop_succ_eq_supportDim hreg hx`.
   2. Forward implication: rewrite
      `supportCutDim R M [x]` with
      `supportDim_quotSMulTop_eq_supportCutDim_singleton`; `hdim` is exactly
      the cut hypothesis of `isCohenMacaulay_quotient_by_element`.  Its
      middle conjunct is the desired Cohen--Macaulay result for `Q`.
   3. Reverse implication: from `hQ : IsCohenMacaulay R Q`, unfold a copy
      and use `Module.supportDim_ne_bot_iff_nontrivial` to install
      `Nontrivial Q`.  Pull this instance back to `M` along
      `Submodule.mkQ_surjective (x • (top : Submodule R M))` via
      `Function.Surjective.nontrivial`; this is a surjectivity transition,
      not a universe lift.
   4. Apply
      `Unit72.localDepth_drops_by_one (R := R) (M := M) x hx hreg`.
      Prove `1 <= localDepth R M` by unfolding `localDepth` and using
      `depth_eq_sSup_weaklyRegular` (or the defining supremum) with the
      singleton regular sequence: combine `hreg`, `hx`,
      `RingTheory.Sequence.IsRegular.nil R Q`, and
      `RingTheory.Sequence.IsRegular.cons`.  Thus
      `tsub_add_cancel_of_le` converts the depth-drop equality into
      `localDepth R M = localDepth R Q + 1`.
   5. Unfold `IsCohenMacaulay` in the goal and in `hQ`, coerce that last
      `ENat` equality to `WithBot ENat`, then calculate
      `coe (localDepth R M) = coe (localDepth R Q) + 1
        = Module.supportDim R Q + 1 = Module.supportDim R M`
      using `hQ` and `hdim`.
-/
theorem isCohenMacaulay_iff_of_isSMulRegular
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (x : R)
    (hx : x ∈ IsLocalRing.maximalIdeal R)
    (hreg : IsSMulRegular M x) :
    IsCohenMacaulay R M ↔ IsCohenMacaulay R (QuotSMulTop x M) := by
  sorry

theorem moduleFinite_of_surjective_ringHom
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S)
    (hf : Function.Surjective f) :
    (letI : Module R S := Module.compHom S f
     Module.Finite R S) := by
  exact RingHom.Finite.of_surjective f hf

theorem isCohenMacaulay_iff_of_surjective_localRingHom
    {R S : Type u} {N : Type v} [CommRing R] [CommRing S]
    [IsLocalRing R] [IsNoetherianRing R] [IsLocalRing S]
    [IsNoetherianRing S] [AddCommGroup N] [Module S N]
    [Module.Finite S N] (f : R →+* S) (hf : Function.Surjective f) :
    IsCohenMacaulay S N ↔
      (letI : Module R N := Module.compHom N f
       letI : Module R S := Module.compHom S f
       letI : Module.Finite R S := moduleFinite_of_surjective_ringHom f hf
       letI : IsScalarTower R S N := SMul.comp.isScalarTower f
       letI : Module.Finite R N := Module.Finite.trans S N
       IsCohenMacaulay R N) := by
  sorry

/-! ## Associated primes and minimal support -/

theorem associatedPrime_is_minimal_support_of_isCohenMacaulay
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (p : PrimeSpectrum R)
    (hp : p ∈ Formalization.Books.Algebra.Unit63.associatedPrimes R M) :
    ringKrullDim (R ⧸ p.asIdeal) = Module.supportDim R M ∧
      Minimal (fun q : PrimeSpectrum R => q ∈ Module.support R M) p := by
  sorry

theorem no_embeddedAssociatedPrimes_of_isCohenMacaulay
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M) :
    Formalization.Books.Algebra.Unit67.embeddedAssociatedPrimes
        (R := R) (M := M) = ∅ := by
  sorry

/-! ## Maximal Cohen-Macaulay modules -/

def IsMaximalCohenMacaulay
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] : Prop :=
  ((localDepth R M : ℕ∞) : WithBot ℕ∞) = ringKrullDim R

theorem isMaximalCohenMacaulay_iff
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    IsMaximalCohenMacaulay R M ↔
      IsCohenMacaulay R M ∧ Module.supportDim R M = ringKrullDim R := by
  sorry

theorem isMaximalCohenMacaulay_of_support_eq_univ
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (hsupp : Module.support R M = Set.univ) :
    IsMaximalCohenMacaulay R M := by
  sorry

/-! ## Maximal prime chains -/

/- A finite strict prime chain is maximal when it cannot be extended at an
   endpoint or by inserting a prime between two adjacent terms. -/
def IsMaximalPrimeChain {R : Type u} [CommRing R]
    (C : Formalization.Books.Algebra.Unit60.PrimeIdealChain R) : Prop :=
  (∀ q : PrimeSpectrum R, q < C.head → False) ∧
    (∀ q : PrimeSpectrum R, C.last < q → False) ∧
    (∀ i : Fin C.length, ¬ ∃ q : PrimeSpectrum R,
      C (Fin.castSucc i) < q ∧ q < C i.succ)

theorem maximalPrimeChain_length_eq_ringKrullDim
    {R : Type u} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] {M : Type v} [AddCommGroup M]
    [Module R M] [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (hsupp : Module.support R M = Set.univ)
    (C : Formalization.Books.Algebra.Unit60.PrimeIdealChain R)
    (hC : IsMaximalPrimeChain C) :
    (((C.length : ℕ∞) : WithBot ℕ∞)) = ringKrullDim R := by
  sorry

theorem ringKrullDim_eq_localization_add_quotientDim
    {R : Type u} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] {M : Type v} [AddCommGroup M]
    [Module R M] [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (hsupp : Module.support R M = Set.univ) (p : PrimeSpectrum R) :
    ringKrullDim R =
      ringKrullDim (Localization.AtPrime p.asIdeal) +
        ringKrullDim (R ⧸ p.asIdeal) := by
  sorry

/-! ## Localization and the global module condition -/

theorem isCohenMacaulay_localize
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (p : PrimeSpectrum R) :
    IsCohenMacaulay (Localization.AtPrime p.asIdeal)
      (LocalizedModule.AtPrime p.asIdeal M) := by
  sorry

/-- Localizing a finite module of full support again gives a module of full
support.  This is the support half of the localization step used in maximal
chain arguments; it is intentionally independent of Cohen--Macaulayness. -/
theorem support_localizedModuleAtPrime_eq_univ_of_support_eq_univ
    {R : Type u} {M : Type v} [CommRing R] [IsNoetherianRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (hsupp : Module.support R M = Set.univ) (p : PrimeSpectrum R) :
    Module.support (Localization.AtPrime p.asIdeal)
      (LocalizedModule.AtPrime p.asIdeal M) = Set.univ := by
  /-
  Roadmap.  A prime of `R_p` corresponds to a prime `q ⊆ p` of `R`.
  Membership of `q` in `support R M` is equivalent to nonvanishing of
  `M_q`; transitivity of localization identifies this with the localization
  at the corresponding prime of `R_p` of `M_p`.  Package that equivalence as
  a general `Module.mem_support_localizedModule_iff` lemma near the existing
  support/localization API, then this theorem is `simpa [hsupp]`.
  -/
  sorry

def IsCohenMacaulayModule
    (R : Type u) (M : Type v) [CommRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] : Prop :=
  ∀ p : PrimeSpectrum R,
    IsCohenMacaulay (Localization.AtPrime p.asIdeal)
      (LocalizedModule.AtPrime p.asIdeal M)

theorem isCohenMacaulayModule_iff_forall_maximal
    {R : Type u} {M : Type v} [CommRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    IsCohenMacaulayModule R M ↔
      ∀ m : MaximalSpectrum R,
        IsCohenMacaulay (Localization.AtPrime m.asIdeal)
          (LocalizedModule.AtPrime m.asIdeal M) := by
  sorry

/-! ## Polynomial extensions -/

abbrev polynomialModuleExtension
    (R : Type u) (M : Type v) [CommRing R]
    [AddCommGroup M] [Module R M] (n : ℕ) : Type max u v :=
  MvPolynomial (Fin n) R ⊗[R] M

/-- Full support is preserved by polynomial extension.  Keeping this next to
`polynomialModuleExtension` isolates the support calculation from the depth
argument in `isCohenMacaulayModule_polynomialModuleExtension`. -/
theorem support_polynomialModuleExtension_eq_univ
    {R : Type u} {M : Type v} [CommRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hsupp : Module.support R M = Set.univ) (n : ℕ) :
    (letI : Module (MvPolynomial (Fin n) R)
        (polynomialModuleExtension R M n) := TensorProduct.leftModule
     Module.support (MvPolynomial (Fin n) R)
       (polynomialModuleExtension R M n) = Set.univ) := by
  /-
  Roadmap.  It is enough to prove that the localization at every prime `q`
  of the polynomial ring is nonzero.  Put `p := q.comap (algebraMap R _)`.
  The hypothesis says `M_p ≠ 0`.  Identify the localization of
  `R[X] ⊗[R] M` at `q` with

      (R[X]_q) ⊗[R_p] M_p.

  The local map `R_p → R[X]_q` is faithfully flat, so the latter tensor
  product is nonzero.  The reusable missing pieces should be stated for an
  arbitrary flat algebra: localization commutes with scalar extension, and
  faithful scalar extension reflects a zero finite module.  Neither piece
  is specific to Cohen--Macaulay modules.
  -/
  sorry

theorem isCohenMacaulayModule_polynomialModuleExtension
    {R : Type u} {M : Type v} [CommRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulayModule R M) (n : ℕ) :
    (letI : Module (MvPolynomial (Fin n) R)
        (polynomialModuleExtension R M n) := TensorProduct.leftModule
     IsCohenMacaulayModule (MvPolynomial (Fin n) R)
      (polynomialModuleExtension R M n)) := by
  sorry

end

end Formalization.Books.Algebra.Unit103
