import Formalization.Books.Algebra.Unit60
import Formalization.Books.Algebra.Unit67
import Formalization.Books.Algebra.Unit72
import Mathlib.Order.KrullDimension
import Mathlib.RingTheory.KrullDimension.Module
import Mathlib.RingTheory.MvPolynomial
import Mathlib.RingTheory.Localization.AtPrime.Basic

/-!
# Commutative Algebra, Chapter 103: Cohen-Macaulay modules

The local Cohen-Macaulay condition is expressed using the support dimension
and the local depth from the preceding chapters.  Quotients by finite lists
of elements use `Ideal.ofList`, and regular sequences use Mathlib's canonical
`RingTheory.Sequence.IsRegular` predicate.
-/

namespace Formalization.Books.Algebra.Unit103

open Set
open Formalization.Books.Algebra.Unit72
open scoped TensorProduct

universe u v

noncomputable section

/-! ## Quotients, dimensions, and regular sequences -/

/- The quotient by the ideal generated by a finite list of elements. -/
abbrev quotientByList
    {R : Type u} (M : Type v) [CommRing R]
    [AddCommGroup M] [Module R M] (xs : List R) : Type v :=
  M ⧸ (Ideal.ofList xs • (⊤ : Submodule R M))

/- The dimension of the support after cutting by a finite list.  A subset is
   viewed as its canonical subtype, as in the definition of `Order.krullDim`. -/
def supportCutDim
    (R : Type u) (M : Type v) [CommRing R]
    [AddCommGroup M] [Module R M] (xs : List R) : WithBot ℕ∞ :=
  Order.krullDim
    (Module.support R M ∩
      PrimeSpectrum.zeroLocus (Ideal.ofList xs : Set R) : Set (PrimeSpectrum R))

/- A regular sequence is maximal when its length realizes local depth. -/
def IsMaximalRegularSequence
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (xs : List R) : Prop :=
  RingTheory.Sequence.IsRegular M xs ∧
    localDepth R M = (xs.length : ℕ∞)

/-! ## Cohen-Macaulay modules over local rings -/

/- The definition from the source, with both invariants in
   `WithBot ℕ∞`, the value type used by `Module.supportDim`. -/
def IsCohenMacaulay
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] : Prop :=
  ((localDepth R M : ℕ∞) : WithBot ℕ∞) = Module.supportDim R M

/- The source's ``good element'' notation.  The equivalent quotient
   formulation is recorded below using `Module.support_quotient`. -/
def IsGoodElement
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (fs : List R) (g : R) : Prop :=
  g ∈ IsLocalRing.maximalIdeal R ∧
    ∀ i : Fin fs.length,
      supportCutDim R M (g :: fs.take i.1) =
        (((fs.length - i.1 - 1 : ℕ) : ℕ∞) : WithBot ℕ∞)

theorem support_quotientByList
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (xs : List R) :
    Module.support R (quotientByList M xs) =
      Module.support R M ∩
        PrimeSpectrum.zeroLocus (Ideal.ofList xs : Set R) := by
  exact Module.support_quotient (Ideal.ofList xs)

theorem supportCutDim_eq_supportDim_quotientByList
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (xs : List R) :
    supportCutDim R M xs = Module.supportDim R (quotientByList M xs) := by
  unfold supportCutDim Module.supportDim
  rw [support_quotientByList]

/- The displayed equivalence in the source: the dimension condition can be
   read either on the support intersection or on the corresponding quotient. -/
theorem isGoodElement_iff_quotient_supportDim
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (fs : List R) (g : R) :
    IsGoodElement R M fs g ↔
      g ∈ IsLocalRing.maximalIdeal R ∧
        ∀ i : Fin fs.length,
          Module.supportDim R (quotientByList M (g :: fs.take i.1)) =
            (((fs.length - i.1 - 1 : ℕ) : ℕ∞) : WithBot ℕ∞) := by
  simp only [IsGoodElement, supportCutDim_eq_supportDim_quotientByList]

/-! ## The good-element induction -/

theorem goodElement_isSMulRegular_and_quotient_isCohenMacaulay
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (fs : List R) (g : R)
    (hM : IsCohenMacaulay R M)
    (hfs : RingTheory.Sequence.IsRegular M fs)
    (hdim : Module.supportDim R M =
      (((fs.length : ℕ∞) : WithBot ℕ∞)))
    (hgood : IsGoodElement R M fs g)
    /- The source's d = 0 discussion says that no good-element case occurs;
       this positivity hypothesis makes that implicit restriction explicit. -/
    (hpositive : 0 < fs.length) :
    IsSMulRegular M g ∧
      IsCohenMacaulay R (QuotSMulTop g M) ∧
      IsMaximalRegularSequence R (QuotSMulTop g M) fs.dropLast := by
  sorry

/-! ## Cutting by one element -/

theorem isCohenMacaulay_quotient_by_element
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (d : ℕ) (hM : IsCohenMacaulay R M) (g : R)
    (hg : g ∈ IsLocalRing.maximalIdeal R)
    (hdim : Module.supportDim R M =
      (((d + 1 : ℕ) : ℕ∞) : WithBot ℕ∞))
    (hcut : supportCutDim R M [g] =
      (((d : ℕ∞) : WithBot ℕ∞))) :
      IsSMulRegular M g ∧
      IsCohenMacaulay R (QuotSMulTop g M) ∧
      localDepth R (QuotSMulTop g M) = localDepth R M - 1 := by
  sorry

/-! ## Regular sequences cut out by the expected dimension -/

theorem regularSequence_of_supportDim_quotient_eq
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (d c : ℕ) (hM : IsCohenMacaulay R M)
    (g : Fin c → R)
    /- This keeps the natural subtraction `d - c` faithful to the source's
       dimension difference. -/
    (hc : c ≤ d)
    (hMdim : Module.supportDim R M =
      (((d : ℕ∞) : WithBot ℕ∞)))
    (hg : ∀ i, g i ∈ IsLocalRing.maximalIdeal R)
    (hquot : Module.supportDim R (quotientByList M (List.ofFn g)) =
      (((d - c : ℕ) : ℕ∞) : WithBot ℕ∞)) :
    RingTheory.Sequence.IsRegular M (List.ofFn g) ∧
      ∃ ys : List R,
        IsMaximalRegularSequence R M (List.ofFn g ++ ys) := by
  sorry

/-! ## Standard consequences -/

theorem isCohenMacaulay_iff_of_isSMulRegular
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (x : R)
    (hx : x ∈ IsLocalRing.maximalIdeal R)
    (hreg : IsSMulRegular M x) :
    IsCohenMacaulay R M ↔ IsCohenMacaulay R (QuotSMulTop x M) := by
  sorry

theorem moduleFinite_of_surjective_ringHom
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S)
    (hf : Function.Surjective f) :
    (letI : Module R S := Module.compHom S f
     Module.Finite R S) := by
  exact RingHom.Finite.of_surjective f hf

theorem isCohenMacaulay_iff_of_surjective_localRingHom
    {R S : Type u} {N : Type v} [CommRing R] [CommRing S]
    [IsLocalRing R] [IsNoetherianRing R] [IsLocalRing S]
    [IsNoetherianRing S] [AddCommGroup N] [Module S N]
    [Module.Finite S N] (f : R →+* S) (hf : Function.Surjective f) :
    IsCohenMacaulay S N ↔
      (letI : Module R N := Module.compHom N f
       letI : Module R S := Module.compHom S f
       letI : Module.Finite R S := moduleFinite_of_surjective_ringHom f hf
       letI : IsScalarTower R S N := SMul.comp.isScalarTower f
       letI : Module.Finite R N := Module.Finite.trans S N
       IsCohenMacaulay R N) := by
  sorry

/-! ## Associated primes and minimal support -/

theorem associatedPrime_is_minimal_support_of_isCohenMacaulay
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (p : PrimeSpectrum R)
    (hp : p ∈ Formalization.Books.Algebra.Unit63.associatedPrimes R M) :
    ringKrullDim (R ⧸ p.asIdeal) = Module.supportDim R M ∧
      Minimal (fun q : PrimeSpectrum R => q ∈ Module.support R M) p := by
  sorry

theorem no_embeddedAssociatedPrimes_of_isCohenMacaulay
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M) :
    Formalization.Books.Algebra.Unit67.embeddedAssociatedPrimes
        (R := R) (M := M) = ∅ := by
  sorry

/-! ## Maximal Cohen-Macaulay modules -/

def IsMaximalCohenMacaulay
    (R : Type u) (M : Type v) [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] : Prop :=
  ((localDepth R M : ℕ∞) : WithBot ℕ∞) = ringKrullDim R

theorem isMaximalCohenMacaulay_iff
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    IsMaximalCohenMacaulay R M ↔
      IsCohenMacaulay R M ∧ Module.supportDim R M = ringKrullDim R := by
  sorry

theorem isMaximalCohenMacaulay_of_support_eq_univ
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (hsupp : Module.support R M = Set.univ) :
    IsMaximalCohenMacaulay R M := by
  sorry

/-! ## Maximal prime chains -/

/- A finite strict prime chain is maximal when it cannot be extended at an
   endpoint or by inserting a prime between two adjacent terms. -/
def IsMaximalPrimeChain {R : Type u} [CommRing R]
    (C : Formalization.Books.Algebra.Unit60.PrimeIdealChain R) : Prop :=
  (∀ q : PrimeSpectrum R, q < C.head → False) ∧
    (∀ q : PrimeSpectrum R, C.last < q → False) ∧
    (∀ i : Fin C.length, ¬ ∃ q : PrimeSpectrum R,
      C (Fin.castSucc i) < q ∧ q < C i.succ)

theorem maximalPrimeChain_length_eq_ringKrullDim
    {R : Type u} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] {M : Type v} [AddCommGroup M]
    [Module R M] [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (hsupp : Module.support R M = Set.univ)
    (C : Formalization.Books.Algebra.Unit60.PrimeIdealChain R)
    (hC : IsMaximalPrimeChain C) :
    (((C.length : ℕ∞) : WithBot ℕ∞)) = ringKrullDim R := by
  sorry

theorem ringKrullDim_eq_localization_add_quotientDim
    {R : Type u} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] {M : Type v} [AddCommGroup M]
    [Module R M] [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (hsupp : Module.support R M = Set.univ) (p : PrimeSpectrum R) :
    ringKrullDim R =
      ringKrullDim (Localization.AtPrime p.asIdeal) +
        ringKrullDim (R ⧸ p.asIdeal) := by
  sorry

/-! ## Localization and the global module condition -/

theorem isCohenMacaulay_localize
    {R : Type u} {M : Type v} [CommRing R] [IsLocalRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulay R M)
    (p : PrimeSpectrum R) :
    IsCohenMacaulay (Localization.AtPrime p.asIdeal)
      (LocalizedModule.AtPrime p.asIdeal M) := by
  sorry

def IsCohenMacaulayModule
    (R : Type u) (M : Type v) [CommRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] : Prop :=
  ∀ p : PrimeSpectrum R,
    IsCohenMacaulay (Localization.AtPrime p.asIdeal)
      (LocalizedModule.AtPrime p.asIdeal M)

theorem isCohenMacaulayModule_iff_forall_maximal
    {R : Type u} {M : Type v} [CommRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    IsCohenMacaulayModule R M ↔
      ∀ m : MaximalSpectrum R,
        IsCohenMacaulay (Localization.AtPrime m.asIdeal)
          (LocalizedModule.AtPrime m.asIdeal M) := by
  sorry

/-! ## Polynomial extensions -/

abbrev polynomialModuleExtension
    (R : Type u) (M : Type v) [CommRing R]
    [AddCommGroup M] [Module R M] (n : ℕ) : Type max u v :=
  MvPolynomial (Fin n) R ⊗[R] M

theorem isCohenMacaulayModule_polynomialModuleExtension
    {R : Type u} {M : Type v} [CommRing R]
    [IsNoetherianRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (hM : IsCohenMacaulayModule R M) (n : ℕ) :
    IsCohenMacaulayModule (MvPolynomial (Fin n) R)
      (polynomialModuleExtension R M n) := by
  sorry

end

end Formalization.Books.Algebra.Unit103
