import Formalization.Books.Fields.Unit10.AlgebraicClosure
import Mathlib.Algebra.Polynomial.Splits
import Mathlib.FieldTheory.IsAlgClosed.Basic

/-!
# Fields, Chapter 11: Relatively prime polynomials

The source's phrase “relatively prime” is Mathlib's canonical `IsCoprime`
predicate on two elements of a commutative semiring.  The unit-ideal
formulation is recorded below as an equivalent source-facing statement.
Polynomial factorization is represented by `Polynomial.Splits`, and roots in
an extension are represented by `Polynomial.aeval` (or, equivalently, roots of
   the mapped polynomial).  The final theorem uses Mathlib's `IsAlgClosure`
   interface; the canonical `AlgebraicClosure` from the preceding chapter is
   one standard instance.
-/

namespace Formalization.Books.Fields.Unit11

noncomputable section

universe u

open Polynomial

/-! ## Factorization over an algebraically closed field -/

/- The source's displayed finite factorization is exactly Mathlib's `Splits`
   predicate, with the scalar written canonically as the leading coefficient.
   The source calls this scalar the constant term; that wording is corrected
   in the formal statement and recorded as a source issue in the report. -/

/- The source's assertion that every polynomial factors into linear factors is
   already the defining field-wide property of `IsAlgClosed`. -/
/-- Every polynomial over an algebraically closed field splits into linear
    factors. -/
theorem algebraically_closed_polynomial_splits
    (K : Type u) [Field K] [IsAlgClosed K] (P : Polynomial K) :
    P.Splits :=
  IsAlgClosed.splits P

/-- A polynomial over an algebraically closed field is a scalar times a finite
    product of its linear factors, counted with multiplicity. -/
theorem algebraically_closed_polynomial_factorization
    (K : Type u) [Field K] [IsAlgClosed K] (P : Polynomial K) :
    P = C P.leadingCoeff * (P.roots.map (fun α => X - C α)).prod :=
  (algebraically_closed_polynomial_splits K P).eq_prod_roots

/- The degree-one form is the canonical Mathlib formulation of “linear”. -/
/-- Every irreducible polynomial over an algebraically closed field has degree
    one. -/
theorem algebraically_closed_irreducible_polynomial_is_linear
    (K : Type u) [Field K] [IsAlgClosed K] {P : Polynomial K}
    (hP : Irreducible P) :
    P.degree = 1 :=
  IsAlgClosed.degree_eq_one_of_irreducible K hP

/-- The irreducible polynomials over an algebraically closed field are exactly
    the nonzero scalar multiples of linear factors. -/
theorem algebraically_closed_irreducible_polynomial_iff_linear_factor
    (K : Type u) [Field K] [IsAlgClosed K] (P : Polynomial K) :
    Irreducible P ↔
      ∃ c α : K, c ≠ 0 ∧ P = C c * (X - C α) := by
  sorry

/- The source explains the root criterion using the maximal ideals of K[X].
   This is the corresponding ideal classification, stated independently of
   the later coprimality theorem. -/
/-- The maximal ideals of a polynomial ring over an algebraically closed field
    are the ideals generated by `X - C α`. -/
theorem algebraically_closed_polynomial_maximal_ideal_iff
    (K : Type u) [Field K] [IsAlgClosed K] (I : Ideal (Polynomial K)) :
    I.IsMaximal ↔
      ∃ α : K, I = Ideal.span ({X - C α} : Set (Polynomial K)) := by
  sorry

/-! ## Relative primeness and common roots -/

/- The source definition is Mathlib's `IsCoprime`; the following theorem
   makes its equivalence with “generate the unit ideal” explicit without
   introducing a parallel predicate. -/
/-- Two polynomials are relatively prime exactly when their generated ideals
    sum to the unit ideal. -/
theorem relatively_prime_iff_unit_ideal
    {k : Type u} [Field k] (P Q : Polynomial k) :
    IsCoprime P Q ↔
      Ideal.span ({P} : Set (Polynomial k)) +
          Ideal.span ({Q} : Set (Polynomial k)) =
        (1 : Ideal (Polynomial k)) := by
  rw [← Ideal.isCoprime_span_singleton_iff P Q, Ideal.isCoprime_iff_add]

/- Mathlib's theorem is the source-faithful algebraically closed criterion;
   its disjunction says that no element is simultaneously a root of P and Q. -/
/-- Over an algebraically closed field, two polynomials are relatively prime
    exactly when they have no common root. -/
theorem relatively_prime_iff_no_common_root
    (K : Type u) [Field K] [IsAlgClosed K] (P Q : Polynomial K) :
    IsCoprime P Q ↔
      ∀ α : K,
        Polynomial.aeval α P ≠ 0 ∨ Polynomial.aeval α Q ≠ 0 :=
  Polynomial.isCoprime_iff_aeval_ne_zero_of_isAlgClosed K K P Q

/- The source's algebraic-closure lemma is exactly Mathlib's criterion for
   evaluating base-field polynomials in an algebraically closed extension.
   The `IsAlgClosure` hypothesis supplies the target's algebraic closedness. -/
/-- Over an arbitrary field, two polynomials are relatively prime exactly when
    they have no common root in an algebraic closure. -/
theorem relatively_prime_iff_no_common_root_in_algebraic_closure
    {k L : Type*} [Field k] [Field L] [Algebra k L] [IsAlgClosure k L]
    (P Q : Polynomial k) :
    IsCoprime P Q ↔
      ∀ α : L,
        Polynomial.aeval α P ≠ 0 ∨ Polynomial.aeval α Q ≠ 0 := by
  let hAlgClosed : IsAlgClosed L := IsAlgClosure.isAlgClosed k
  exact @Polynomial.isCoprime_iff_aeval_ne_zero_of_isAlgClosed
    k inferInstance L inferInstance hAlgClosed inferInstance P Q

end

end Formalization.Books.Fields.Unit11
