import Formalization.Books.Algebra.Unit56.GradedRings
import Mathlib.Algebra.Module.LocalizedModule.AtPrime
import Mathlib.Algebra.Module.LocalizedModule.Away
import Mathlib.AlgebraicGeometry.ProjectiveSpectrum.Topology
import Mathlib.RingTheory.GradedAlgebra.HomogeneousLocalization
import Mathlib.RingTheory.GradedAlgebra.Radical
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.RingTheory.Polynomial.Basic
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.Spectrum.Prime.Topology

/-!
# Commutative Algebra, Chapter 57: Proj of a graded ring

This file uses Mathlib's `ProjectiveSpectrum` and `HomogeneousLocalization` as the
canonical implementations of Proj and its affine charts.  The declarations below
record the interfaces and precise statements in the source chapter; proposition
proofs are intentionally deferred to the prove stage.
-/

namespace Formalization.Books.Algebra.Unit57

open Formalization.Books.Algebra.Unit56
open DirectSum SetLike
open scoped DirectSum Pointwise Polynomial

universe u v w a

noncomputable section

variable {R : Type u} {S : Type v} [CommRing R] [CommRing S]
variable {M : Type w} [AddCommGroup M] [Module S M]

/-! ## Homogeneous ideals and Proj -/

/-- The canonical homogeneous spectrum, i.e. Mathlib's projective spectrum. -/
abbrev projectiveSpectrum (G : GradedRingData S) :=
  ProjectiveSpectrum G.component

/-- The irrelevant ideal in the ideal API used by `ProjectiveSpectrum`. -/
abbrev projIrrelevantIdeal (G : GradedRingData S) : Ideal S :=
  (HomogeneousIdeal.irrelevant G.component).toIdeal

/-! `Proj(S)` is the relevant homogeneous-prime subspace of `Spec(S)`. -/

/-- The inclusion of Proj into the ordinary prime spectrum. -/
def projToSpectrum (G : GradedRingData S) :
    projectiveSpectrum G → PrimeSpectrum S :=
  fun p => ⟨p.asHomogeneousIdeal.toIdeal, p.isPrime⟩

/-- The topology on Proj is induced by its inclusion into `Spec(S)`. -/
theorem projectiveSpectrum_induced_topology (G : GradedRingData S) :
    Topology.IsInducing (projToSpectrum G) := by
  refine ⟨TopologicalSpace.ext_isClosed fun Z ↦ ?_⟩
  rw [isClosed_induced_iff, ProjectiveSpectrum.isClosed_iff_zeroLocus]
  constructor
  · rintro ⟨s, rfl⟩
    refine ⟨PrimeSpectrum.zeroLocus s, ?_, ?_⟩
    · exact (PrimeSpectrum.isClosed_iff_zeroLocus _).2 ⟨s, rfl⟩
    rfl
  · rintro ⟨t, ht, h⟩
    obtain ⟨s, rfl⟩ := (PrimeSpectrum.isClosed_iff_zeroLocus _).1 ht
    exact ⟨s, h.symm⟩

/-- Homogeneity as closure under all homogeneous components. -/
theorem homogeneous_ideal_iff_components (G : GradedRingData S) (I : Ideal S) :
    I.IsHomogeneous G.component ↔
      ∀ x ∈ I, ∀ d : ℕ, (GradedRing.proj G.component d x : S) ∈ I := by
  constructor
  · intro h x hx d
    exact (h.mem_iff.mp hx d)
  · intro h
    rw [Ideal.isHomogeneous_iff_forall_subset]
    intro d x hx
    exact h x hx d

/-- Homogeneous ideals are precisely ideals generated by homogeneous elements. -/
theorem homogeneous_ideal_iff_generated_by_homogeneous (G : GradedRingData S) (I : Ideal S) :
    I.IsHomogeneous G.component ↔
      ∃ T : Set (homogeneousSubmonoid G.component),
        I = Ideal.span ((↑) '' T) := by
  simpa using (Ideal.IsHomogeneous.iff_exists (𝒜 := G.component) (I := I))

/-- The ideal and graded-submodule formulations of homogeneity agree definitionally. -/
theorem homogeneous_ideal_iff_graded_submodule (G : GradedRingData S) (I : Ideal S) :
    I.IsHomogeneous G.component ↔
      (I : Submodule S S).IsHomogeneous G.component :=
  Iff.rfl

/-- On homogeneous elements, primality can be checked componentwise. -/
theorem homogeneous_prime_iff_homogeneous_products (G : GradedRingData S) (I : Ideal S)
    (hI : I.IsHomogeneous G.component) :
    I.IsPrime ↔
      I ≠ ⊤ ∧ ∀ {a b : S},
        SetLike.IsHomogeneousElem G.component a →
        SetLike.IsHomogeneousElem G.component b →
        a * b ∈ I → a ∈ I ∨ b ∈ I := by
  exact hI.isPrime_iff

/-- The map from Proj to the spectrum of the degree-zero component. -/
def projToDegreeZero (G : GradedRingData S) :
    projectiveSpectrum G → PrimeSpectrum (degreeZeroSubring G) :=
  fun p => PrimeSpectrum.comap (SubringClass.subtype (degreeZeroSubring G))
    ⟨p.asHomogeneousIdeal.toIdeal, p.isPrime⟩

theorem continuous_projToDegreeZero (G : GradedRingData S) :
    Continuous (projToDegreeZero G) := by
  change Continuous (PrimeSpectrum.comap (SubringClass.subtype (degreeZeroSubring G)) ∘
    projToSpectrum G)
  exact (PrimeSpectrum.continuous_comap _).comp
    (projectiveSpectrum_induced_topology G).continuous

/-! ## A general Z-graded prime-spectrum lemma -/

/-- A ring with an internal `ℤ`-grading. -/
structure ZGradedRingData (A : Type u) [CommRing A] where
  component : ℤ → AddSubgroup A
  graded : GradedRing component

instance {A : Type u} [CommRing A] (H : ZGradedRingData A) : GradedRing H.component := H.graded

variable {A : Type u} [CommRing A]

/-- The degree-zero subring of a `ℤ`-graded ring. -/
abbrev zDegreeZeroSubring {A : Type u} [CommRing A] (H : ZGradedRingData A) :=
  SetLike.GradeZero.subring H.component

/-- A grading has the positive homogeneous unit required by the source lemma. -/
def HasPositiveHomogeneousUnit (H : ZGradedRingData A) : Prop :=
  ∃ (d : ℤ) (f : A), 0 < d ∧ f ∈ H.component d ∧ IsUnit f

/-- Homogeneous primes for a `ℤ`-graded ring. -/
abbrev zGradedPrimeSpectrum (H : ZGradedRingData A) :=
  {p : PrimeSpectrum A // p.asIdeal.IsHomogeneous H.component}

/-- Restriction of a homogeneous prime to the degree-zero subring. -/
def zGradedPrimeToDegreeZero (H : ZGradedRingData A) :
    zGradedPrimeSpectrum H → PrimeSpectrum (zDegreeZeroSubring H) :=
  fun p => PrimeSpectrum.comap (SubringClass.subtype (zDegreeZeroSubring H))
    ⟨p.1.asIdeal, p.1.isPrime⟩

private lemma zgraded_map_isHomogeneous (H : ZGradedRingData A)
    (q : Ideal (zDegreeZeroSubring H)) :
    (Ideal.map (SubringClass.subtype (zDegreeZeroSubring H)) q).IsHomogeneous H.component := by
  rw [← Ideal.span_eq q, Ideal.map_span]
  apply Ideal.homogeneous_span
  rintro x ⟨y, hy, rfl⟩
  exact ⟨0, y.2⟩

private lemma zgraded_comap_map (H : ZGradedRingData A)
    (q : Ideal (zDegreeZeroSubring H)) :
    (Ideal.map (SubringClass.subtype (zDegreeZeroSubring H)) q).comap
        (SubringClass.subtype (zDegreeZeroSubring H)) = q := by
  classical
  let e : zDegreeZeroSubring H →+* A := SubringClass.subtype _
  let π : A →+ A := GradedRing.proj H.component 0
  have hπ_mul {a : A} {z : zDegreeZeroSubring H} :
      π (a * (z : A)) = π a * (z : A) := by
    exact DirectSum.coe_decompose_mul_of_right_mem_zero H.component z.2
  have hπ_coe (z : zDegreeZeroSubring H) : π (e z) = e z := by
    change (DirectSum.decompose H.component (e z) 0 : A) = e z
    exact DirectSum.decompose_of_mem_same H.component z.2
  have hterm (a : A) (z : zDegreeZeroSubring H) (hz : z ∈ q) :
      (⟨π (a * (z : A)), SetLike.coe_mem _⟩ : zDegreeZeroSubring H) ∈ q := by
    have hsub :
        (⟨π (a * (z : A)), SetLike.coe_mem _⟩ : zDegreeZeroSubring H) =
          ⟨π a * (z : A), SetLike.coe_mem _⟩ := by
      apply Subtype.ext
      exact hπ_mul
    rw [hsub]
    change (⟨π a, SetLike.coe_mem _⟩ : zDegreeZeroSubring H) * z ∈ q
    exact Ideal.mul_mem_left q _ hz
  apply le_antisymm
  · intro x hx
    change e x ∈ Ideal.map e q at hx
    rw [← Ideal.span_eq q, Ideal.map_span] at hx
    obtain ⟨l, hl⟩ :=
      (Finsupp.mem_span_iff_linearCombination A
        (e '' (↑q : Set (zDegreeZeroSubring H))) (e x)).mp hx
    simp only [Finsupp.linearCombination, Finsupp.coe_lsum, Finsupp.sum,
      LinearMap.coe_smulRight, LinearMap.id_coe, id_eq, smul_eq_mul] at hl
    have hsum :
        (∑ y in l.support,
            (⟨π (l y * (y : A)), SetLike.coe_mem _⟩ : zDegreeZeroSubring H)) ∈ q := by
      exact q.sum_mem (fun y hy => by
        rcases y.2 with ⟨z, hz, hyz⟩
        simpa [hyz] using hterm (l y) z hz)
    have heq :
        (∑ y in l.support,
            (⟨π (l y * (y : A)), SetLike.coe_mem _⟩ : zDegreeZeroSubring H)) = x := by
      apply Subtype.ext
      calc
        (↑(∑ y in l.support,
            (⟨π (l y * (y : A)), SetLike.coe_mem _⟩ : zDegreeZeroSubring H)) : A) =
            ∑ y in l.support, π (l y * (y : A)) := by simp
        _ = π (∑ y in l.support, l y * (y : A)) := by
          simp only [map_sum]
        _ = π (e x) := congrArg π hl
        _ = e x := hπ_coe x
        _ = x := rfl
    exact heq ▸ hsum
  · exact Ideal.le_comap_map

private lemma zgraded_unit_inv_mem (H : ZGradedRingData A) {f : A} {d : ℤ}
    (hf : f ∈ H.component d) (hunit : IsUnit f) :
    ∃ g : A, f * g = 1 ∧ g ∈ H.component (-d) := by
  classical
  obtain ⟨u, rfl⟩ := hunit
  let g : A := (↑(u⁻¹) : A)
  have hfg : (↑u : A) * g = 1 := by
    simp [g]
  have hproj (j : ℤ) (hj : j ≠ -d) :
      GradedRing.proj H.component j g = 0 := by
    have hne : d + j ≠ 0 := by
      intro h
      apply hj
      linarith
    have hzero : (DirectSum.decompose H.component ((↑u : A) * g) (d + j) : A) = 0 := by
      rw [hfg]
      exact DirectSum.decompose_of_mem_ne H.component (SetLike.one_mem_graded H.component) hne.symm
    have hmul : (↑u : A) * GradedRing.proj H.component j g = 0 := by
      rw [GradedRing.proj_apply]
      rw [← DirectSum.coe_decompose_mul_add_of_left_mem H.component hf]
      exact hzero
    exact u.isUnit.mul_left_cancel (hmul.trans (mul_zero _).symm)
  have hdecomp : g = GradedRing.proj H.component (-d) g := by
    have hx : GradedRing.proj H.component (-d) g ∈ H.component (-d) := SetLike.coe_mem _
    apply (DirectSum.decompose H.component).injective
    ext j
    by_cases hj : j = -d
    · subst j
      change GradedRing.proj H.component (-d) g =
        (DirectSum.decompose H.component (GradedRing.proj H.component (-d) g) (-d) : A)
      exact (DirectSum.decompose_of_mem_same H.component hx).symm
    · change GradedRing.proj H.component j g =
        (DirectSum.decompose H.component (GradedRing.proj H.component (-d) g) j : A)
      rw [hproj j hj, DirectSum.decompose_of_mem_ne H.component hx (Ne.symm hj)]
  refine ⟨g, hfg, ?_⟩
  rw [hdecomp]
  exact SetLike.coe_mem _

private lemma zgraded_unit_zpow_mem (H : ZGradedRingData A) (u : Aˣ) {k : ℤ}
    (hu : (u : A) ∈ H.component k) (n : ℤ) :
    (↑(u ^ n) : A) ∈ H.component (n * k) := by
  obtain ⟨g, hgu, hg⟩ := zgraded_unit_inv_mem H hu u.isUnit
  have hgeq : g = (↑(u⁻¹) : A) := by
    apply u.isUnit.mul_left_cancel
    rw [hgu]
    simp
  cases n with
  | ofNat n =>
      simpa [nsmul_eq_mul] using SetLike.pow_mem_graded n hu
  | negSucc n =>
      have hv : (↑(u⁻¹) : A) ∈ H.component (-k) := hgeq ▸ hg
      have hn : Int.negSucc n = -((n + 1 : ℕ) : ℤ) := by
        simpa using Int.negSucc_eq n
      rw [hn, zpow_neg, zpow_natCast]
      have hpow : (↑((u ^ (n + 1))⁻¹) : A) = (↑(u⁻¹) : A) ^ (n + 1) := by
        simp [← inv_pow]
      rw [hpow]
      simpa [add_mul, mul_neg, neg_mul] using SetLike.pow_mem_graded (n + 1) hv

private lemma zgraded_radical_map_isPrime (H : ZGradedRingData A) (u : Aˣ) {d : ℤ}
    (hd : 0 < d) (hu : (u : A) ∈ H.component d)
    (q : PrimeSpectrum (zDegreeZeroSubring H)) :
    (Ideal.map (SubringClass.subtype (zDegreeZeroSubring H)) q.asIdeal).radical.IsPrime := by
  let B := zDegreeZeroSubring H
  let e : B →+* A := SubringClass.subtype B
  let I : Ideal A := Ideal.map e q.asIdeal
  have hIhom : I.IsHomogeneous H.component := zgraded_map_isHomogeneous H q.asIdeal
  have hcomap : I.comap e = q.asIdeal := by
    exact zgraded_comap_map H q.asIdeal
  have hD : (d.toNat : ℤ) = d := Int.toNat_of_nonneg (le_of_lt hd)
  have hDpos : 0 < d.toNat := by omega
  have hpow_mem {x : A} (hx : x ∈ I) :
      ∀ n : ℕ, 0 < n → x ^ n ∈ I := by
    intro n hn
    cases n with
    | zero => omega
    | succ n =>
      induction n with
      | zero => simpa using hx
      | succ n ih =>
        rw [pow_succ]
        exact Ideal.mul_mem_right x I (ih (by omega))
  have hmap_prod : ∀ {a b : A} {i j : ℤ},
      a ∈ H.component i → b ∈ H.component j → a * b ∈ I →
        a ∈ I.radical ∨ b ∈ I.radical := by
    intro a b i j hai hjb hab
    obtain ⟨gi, hgi_unit, hgi⟩ := zgraded_unit_inv_mem H
      (zgraded_unit_zpow_mem H u hu i) (u ^ i).isUnit
    obtain ⟨gj, hgj_unit, hgj⟩ := zgraded_unit_inv_mem H
      (zgraded_unit_zpow_mem H u hu j) (u ^ j).isUnit
    have hgi_zero : a ^ d.toNat * gi ∈ H.component 0 := by
      have hidx : d * i + -(i * d) = 0 := by
        ring
      have hmem := SetLike.mul_mem_graded (SetLike.pow_mem_graded d.toNat hai) hgi
      rw [nsmul_eq_mul, hD] at hmem
      simpa [hidx] using hmem
    have hgj_zero : b ^ d.toNat * gj ∈ H.component 0 := by
      have hidx : d * j + -(j * d) = 0 := by
        ring
      have hmem := SetLike.mul_mem_graded (SetLike.pow_mem_graded d.toNat hjb) hgj
      rw [nsmul_eq_mul, hD] at hmem
      simpa [hidx] using hmem
    have hp := hpow_mem hab d.toNat hDpos
    have hprod : (a ^ d.toNat * gi) * (b ^ d.toNat * gj) ∈ I := by
      have hmem := Ideal.mul_mem_right (gi * gj) I hp
      simpa [mul_pow, mul_assoc, mul_left_comm, mul_comm] using hmem
    have hprod_q :
        (⟨a ^ d.toNat * gi, hgi_zero⟩ : B) *
          (⟨b ^ d.toNat * gj, hgj_zero⟩ : B) ∈ q.asIdeal := by
      rw [← hcomap]
      exact hprod
    rcases q.isPrime.mem_or_mem hprod_q with hqa | hqb
    · left
      have hmem : a ^ d.toNat * gi ∈ I := Ideal.mem_map_of_mem e hqa
      have hmem' := Ideal.mul_mem_left I (↑(u ^ i) : A) hmem
      have hpow : a ^ d.toNat ∈ I := by
        have heq : (↑(u ^ i) : A) * (a ^ d.toNat * gi) = a ^ d.toNat := by
          calc
            (↑(u ^ i) : A) * (a ^ d.toNat * gi) =
                a ^ d.toNat * ((↑(u ^ i) : A) * gi) := by ac_rfl
            _ = a ^ d.toNat := by rw [hgi_unit, mul_one]
        rw [← heq]
        exact hmem'
      exact Ideal.mem_radical_iff.mpr ⟨d.toNat, hpow⟩
    · right
      have hmem : b ^ d.toNat * gj ∈ I := Ideal.mem_map_of_mem e hqb
      have hmem' := Ideal.mul_mem_left I (↑(u ^ j) : A) hmem
      have hpow : b ^ d.toNat ∈ I := by
        have heq : (↑(u ^ j) : A) * (b ^ d.toNat * gj) = b ^ d.toNat := by
          calc
            (↑(u ^ j) : A) * (b ^ d.toNat * gj) =
                b ^ d.toNat * ((↑(u ^ j) : A) * gj) := by ac_rfl
            _ = b ^ d.toNat := by rw [hgj_unit, mul_one]
        rw [← heq]
        exact hmem'
      exact Ideal.mem_radical_iff.mpr ⟨d.toNat, hpow⟩
  apply hIhom.radical.isPrime_of_homogeneous_mem_or_mem
  · intro htop
    have hone : (1 : A) ∈ I.radical := by rw [htop]; trivial
    obtain ⟨n, hn⟩ := Ideal.mem_radical_iff.mp hone
    have honeI : (1 : A) ∈ I := by simpa using hn
    have honeq : (1 : B) ∈ q.asIdeal := by
      rw [← hcomap]
      exact honeI
    exact q.isPrime.ne_top (q.asIdeal.eq_top_iff_one.mpr honeq)
  · intro a b ha hb hab
    obtain ⟨i, hai⟩ := ha
    obtain ⟨j, hjb⟩ := hb
    obtain ⟨n, hn⟩ := Ideal.mem_radical_iff.mp hab
    rcases hmap_prod (a := a ^ n) (b := b ^ n) (i := n • i) (j := n • j)
        (SetLike.pow_mem_graded n hai) (SetLike.pow_mem_graded n hjb) (by
          simpa [mul_pow] using hn) with h | h
    · exact Or.inl ((Ideal.radical_isRadical I) ⟨n, h⟩)
    · exact Or.inr ((Ideal.radical_isRadical I) ⟨n, h⟩)

/-- The source's Z-graded-prime homeomorphism. -/
theorem zGradedPrime_homeomorph_degree_zero
    (H : ZGradedRingData A) {f : A} {d : ℤ}
    (hf : f ∈ H.component d) (hd : 0 < d) (hunit : IsUnit f) :
    IsHomeomorph (zGradedPrimeToDegreeZero H) := by
  obtain ⟨u, rfl⟩ := hunit
  let B := zDegreeZeroSubring H
  let e : B →+* A := SubringClass.subtype B
  let inv : PrimeSpectrum B → zGradedPrimeSpectrum H := fun q =>
    ⟨⟨(Ideal.map e q.asIdeal).radical,
        zgraded_radical_map_isPrime H u hd hf q⟩,
      (zgraded_map_isHomogeneous H q.asIdeal).radical⟩
  have hright (q : PrimeSpectrum B) :
      zGradedPrimeToDegreeZero H (inv q) = q := by
    apply PrimeSpectrum.ext
    change Ideal.comap e (Ideal.map e q.asIdeal).radical = q.asIdeal
    calc
      Ideal.comap e (Ideal.map e q.asIdeal).radical =
          (Ideal.comap e (Ideal.map e q.asIdeal)).radical :=
        Ideal.comap_radical (f := e) (K := Ideal.map e q.asIdeal)
      _ = q.asIdeal := by
        rw [zgraded_comap_map H q.asIdeal, q.isPrime.radical]
  have hleft (p : zGradedPrimeSpectrum H) : inv (zGradedPrimeToDegreeZero H p) = p := by
    have hradhom :
        (Ideal.map e (Ideal.comap e p.1.asIdeal)).radical.IsHomogeneous H.component :=
      (zgraded_map_isHomogeneous H (Ideal.comap e p.1.asIdeal)).radical
    have hle :
        (Ideal.map e (Ideal.comap e p.1.asIdeal)).radical ≤ p.1.asIdeal := by
      apply p.1.isPrime.isRadical.radical_le_iff.mpr
      exact Ideal.map_le_iff_le_comap.mpr le_rfl
    have hmem : p.1.asIdeal ≤
        (Ideal.map e (Ideal.comap e p.1.asIdeal)).radical := by
      intro x hx
      rw [hradhom.mem_iff]
      intro k
      obtain ⟨g, hgu, hg⟩ := zgraded_unit_inv_mem H
        (zgraded_unit_zpow_mem H u hf k) (u ^ k).isUnit
      have hidx : d * k + -(k * d) = 0 := by
        have hD : (d.toNat : ℤ) = d := Int.toNat_of_nonneg (le_of_lt hd)
        ring
      have hdeg : (GradedRing.proj H.component k x) ^ d.toNat * g ∈ H.component 0 := by
        have hproj : GradedRing.proj H.component k x ∈ H.component k :=
          p.2.mem_iff.mp hx k
        have hmem := SetLike.mul_mem_graded
          (SetLike.pow_mem_graded d.toNat hproj) hg
        rw [nsmul_eq_mul, Int.toNat_of_nonneg (le_of_lt hd)] at hmem
        simpa [hidx] using hmem
      have hpow : (GradedRing.proj H.component k x) ^ d.toNat ∈ p.1.asIdeal :=
        Ideal.pow_mem_of_mem p.1.asIdeal (p.2.mem_iff.mp hx k) d.toNat
          (by omega)
      have hpg : (GradedRing.proj H.component k x) ^ d.toNat * g ∈ p.1.asIdeal :=
        Ideal.mul_mem_right g p.1.asIdeal hpow
      have hq : (⟨(GradedRing.proj H.component k x) ^ d.toNat * g, hdeg⟩ : B) ∈
          Ideal.comap e p.1.asIdeal := hpg
      have hmap : (GradedRing.proj H.component k x) ^ d.toNat * g ∈
          Ideal.map e (Ideal.comap e p.1.asIdeal) := Ideal.mem_map_of_mem e hq
      have hmap' := Ideal.mul_mem_left (Ideal.map e (Ideal.comap e p.1.asIdeal))
        (↑(u ^ k) : A) hmap
      have hpow' : (GradedRing.proj H.component k x) ^ d.toNat ∈
          Ideal.map e (Ideal.comap e p.1.asIdeal) := by
        have heq : (↑(u ^ k) : A) *
            ((GradedRing.proj H.component k x) ^ d.toNat * g) =
              (GradedRing.proj H.component k x) ^ d.toNat := by
          calc
            (↑(u ^ k) : A) *
                ((GradedRing.proj H.component k x) ^ d.toNat * g) =
                (GradedRing.proj H.component k x) ^ d.toNat *
                  ((↑(u ^ k) : A) * g) := by ac_rfl
            _ = (GradedRing.proj H.component k x) ^ d.toNat := by rw [hgu, mul_one]
        rw [← heq]
        exact hmap'
      exact Ideal.mem_radical_iff.mpr ⟨d.toNat, hpow'⟩
    apply Subtype.ext
    apply PrimeSpectrum.ext
    exact le_antisymm hle hmem
  have hbij : Function.Bijective (zGradedPrimeToDegreeZero H) := by
    refine ⟨?_, ?_⟩
    · intro p p' hpp'
      calc
        p = inv (zGradedPrimeToDegreeZero H p) := (hleft p).symm
        _ = inv (zGradedPrimeToDegreeZero H p') := by rw [hpp']
        _ = p' := hleft p'
    · intro q
      exact ⟨inv q, hright q⟩
  have hcont : Continuous (zGradedPrimeToDegreeZero H) := by
    change Continuous (PrimeSpectrum.comap e ∘ (fun p : zGradedPrimeSpectrum H => p.1))
    exact (PrimeSpectrum.continuous_comap e).comp continuous_subtype_val
  refine ⟨hcont, ?_, hbij⟩
  classical
  refine (PrimeSpectrum.isTopologicalBasis_basic_opens.isInducing
    Topology.IsInducing.subtypeVal).isOpenMap_iff.2 ?_
  rintro U ⟨V, ⟨a, rfl⟩, rfl⟩
  have hD : (d.toNat : ℤ) = d := Int.toNat_of_nonneg (le_of_lt hd)
  have hDpos : 0 < d.toNat := by omega
  choose g hgu hg using fun i : ℤ =>
    zgraded_unit_inv_mem H (zgraded_unit_zpow_mem H u hf i) (u ^ i).isUnit
  have hdeg (i : ℤ) :
      (GradedRing.proj H.component i a) ^ d.toNat * g i ∈ H.component 0 := by
    have hidx : d * i + -(i * d) = 0 := by ring
    have hmem := SetLike.mul_mem_graded
      (SetLike.pow_mem_graded d.toNat (SetLike.coe_mem _)) (hg i)
    rw [nsmul_eq_mul, hD] at hmem
    simpa [hidx] using hmem
  let b : ℤ → B := fun i =>
    ⟨(GradedRing.proj H.component i a) ^ d.toNat * g i, hdeg i⟩
  have hcomap_rad (q : PrimeSpectrum B) :
      (Ideal.map e q.asIdeal).radical.comap e = q.asIdeal := by
    calc
      (Ideal.map e q.asIdeal).radical.comap e =
          (Ideal.comap e (Ideal.map e q.asIdeal)).radical :=
        Ideal.comap_radical (f := e) (K := Ideal.map e q.asIdeal)
      _ = q.asIdeal := by
        rw [zgraded_comap_map H q.asIdeal, q.isPrime.radical]
  have hcomp (q : PrimeSpectrum B) (i : ℤ) :
      GradedRing.proj H.component i a ∈ (Ideal.map e q.asIdeal).radical ↔
        b i ∈ q.asIdeal := by
    have hradprime : (Ideal.map e q.asIdeal).radical.IsPrime :=
      zgraded_radical_map_isPrime H u hd hf q
    constructor
    · intro hi
      have hpow := Ideal.pow_mem_of_mem (Ideal.map e q.asIdeal).radical hi d.toNat hDpos
      have hmul := Ideal.mul_mem_right (g i) (Ideal.map e q.asIdeal).radical hpow
      have hq : b i ∈ q.asIdeal := by
        have hq' : b i ∈ (Ideal.map e q.asIdeal).radical.comap e := by
          change (b i : A) ∈ (Ideal.map e q.asIdeal).radical
          simpa [b] using hmul
        rw [hcomap_rad q] at hq'
        exact hq'
      exact hq
    · intro hi
      have hrad : (b i : A) ∈ (Ideal.map e q.asIdeal).radical := by
        have hrad' : b i ∈ (Ideal.map e q.asIdeal).radical.comap e := by
          rw [hcomap_rad q]
          exact hi
        exact hrad'
      have hmul := Ideal.mul_mem_left (Ideal.map e q.asIdeal).radical
        (↑(u ^ i) : A) hrad
      have hpow : (GradedRing.proj H.component i a) ^ d.toNat ∈
          (Ideal.map e q.asIdeal).radical := by
        have heq : (↑(u ^ i) : A) *
            ((GradedRing.proj H.component i a) ^ d.toNat * g i) =
              (GradedRing.proj H.component i a) ^ d.toNat := by
          calc
            (↑(u ^ i) : A) *
                ((GradedRing.proj H.component i a) ^ d.toNat * g i) =
                (GradedRing.proj H.component i a) ^ d.toNat *
                  ((↑(u ^ i) : A) * g i) := by ac_rfl
            _ = (GradedRing.proj H.component i a) ^ d.toNat := by rw [hgu i, mul_one]
        rw [← heq]
        exact hmul
      exact hradprime.mem_of_pow_mem d.toNat hpow
  have hnot (q : PrimeSpectrum B) :
      a ∉ (inv q).1.asIdeal ↔ ∃ i : ℤ, b i ∉ q.asIdeal := by
    change a ∉ (Ideal.map e q.asIdeal).radical ↔ ∃ i : ℤ, b i ∉ q.asIdeal
    constructor
    · intro ha
      by_contra hnone
      apply ha
      rw [(zgraded_map_isHomogeneous H q.asIdeal).radical.mem_iff]
      intro i
      apply (hcomp q i).2
      by_contra hbi
      exact hnone ⟨i, hbi⟩
    · rintro ⟨i, hi⟩ ha
      exact hi ((hcomp q i).1
        ((zgraded_map_isHomogeneous H q.asIdeal).radical.mem_iff.mp ha i))
  have himage :
      zGradedPrimeToDegreeZero H ''
          ((fun p : zGradedPrimeSpectrum H => p.1) ⁻¹'
            (PrimeSpectrum.basicOpen a : Set (PrimeSpectrum A))) =
        ⋃ i : ℤ, (PrimeSpectrum.basicOpen (b i) : Set (PrimeSpectrum B)) := by
    ext q
    constructor
    · rintro ⟨p, hpa, hp⟩
      change a ∉ p.1.asIdeal at hpa
      have hpa' : a ∉ (inv (zGradedPrimeToDegreeZero H p)).1.asIdeal := by
        rw [hleft p]
        exact hpa
      obtain ⟨i, hi⟩ := (hnot (zGradedPrimeToDegreeZero H p)).mp hpa'
      apply Set.mem_iUnion.2
      refine ⟨i, ?_⟩
      change b i ∉ q.asIdeal
      simpa [hp] using hi
    · intro hq
      obtain ⟨i, hi⟩ := Set.mem_iUnion.1 hq
      refine ⟨inv q, ?_, hright q⟩
      change a ∉ (inv q).1.asIdeal
      apply (hnot q).2
      refine ⟨i, ?_⟩
      change b i ∉ q.asIdeal at hi
      exact hi
  change IsOpen
    (zGradedPrimeToDegreeZero H ''
      ((fun p : zGradedPrimeSpectrum H => p.1) ⁻¹'
        (PrimeSpectrum.basicOpen a : Set (PrimeSpectrum A))))
  rw [himage]
  exact isOpen_iUnion fun i => PrimeSpectrum.isOpen_basicOpen

/-! ## Homogeneous localization and localized modules -/

/-- The homogeneous localization `S_(f)`. -/
abbrev homogeneousLocalizationAway (G : GradedRingData S) (f : S) :=
  HomogeneousLocalization.Away G.component f

/-- The homogeneous localization `S_(p)` at a homogeneous prime. -/
abbrev homogeneousLocalizationAtPrime (G : GradedRingData S)
    (p : projectiveSpectrum G) :=
  HomogeneousLocalization.AtPrime G.component p.asHomogeneousIdeal.toIdeal

/-- The ordinary localized module in the chart at a homogeneous element. -/
abbrev localizedModuleAway (f : S) :=
  LocalizedModule (Submonoid.powers f) M

instance homogeneousLocalizedModuleAwayScalars (G : GradedRingData S)
    (f : S) :
    Module (homogeneousLocalizationAway G f) (localizedModuleAway (M := M) f) :=
  Module.compHom _ (algebraMap (homogeneousLocalizationAway G f)
    (Localization (Submonoid.powers f)))

/-- Fractions in a graded module with numerator and denominator of matching degree.

The ambient localized module is Mathlib's `LocalizedModule`; taking the span gives the
canonical homogeneous submodule because Mathlib does not package this module analogue
of `HomogeneousLocalization` separately.
-/
def homogeneousModuleAway (G : GradedRingData S)
    (𝓜 : GradedModuleData G M) (f : S) (d : ℕ) (_hf : f ∈ G.component d)
    (_hd : 0 < d) :
    Submodule (homogeneousLocalizationAway G f) (localizedModuleAway (M := M) f) :=
  Submodule.span _ {z |
    ∃ (n : ℕ) (x : M) (_hx : x ∈ 𝓜.component (n • (d : ℤ))),
      z = LocalizedModule.mk x
        ⟨f ^ n, (Submonoid.mem_powers_iff _ _).2 ⟨n, rfl⟩⟩}

theorem homogeneousModuleAway_mem_iff (G : GradedRingData S)
    (𝓜 : GradedModuleData G M) (f : S) (d : ℕ) (hf : f ∈ G.component d)
    (hd : 0 < d)
    (z : localizedModuleAway (M := M) f) :
    z ∈ homogeneousModuleAway G 𝓜 f d hf hd ↔
      z ∈ Submodule.span (homogeneousLocalizationAway G f) {z |
        ∃ (n : ℕ) (x : M) (_hx : x ∈ 𝓜.component (n • (d : ℤ))),
          z = LocalizedModule.mk x
            ⟨f ^ n, (Submonoid.mem_powers_iff _ _).2 ⟨n, rfl⟩⟩} :=
  Iff.rfl

/-- The ordinary localized module at a homogeneous prime. -/
abbrev localizedModuleAtPrime (G : GradedRingData S)
    (p : projectiveSpectrum G) :=
  LocalizedModule p.asHomogeneousIdeal.toIdeal.primeCompl M

instance homogeneousLocalizedModuleAtPrimeScalars (G : GradedRingData S)
    (p : projectiveSpectrum G) :
    Module (homogeneousLocalizationAtPrime G p)
      (localizedModuleAtPrime (M := M) G p) :=
  Module.compHom (localizedModuleAtPrime (M := M) G p)
    (algebraMap (homogeneousLocalizationAtPrime G p)
    (Localization p.asHomogeneousIdeal.toIdeal.primeCompl))

/-- Fractions in a graded module at a homogeneous prime. -/
def homogeneousModuleAtPrime (G : GradedRingData S)
    (𝓜 : GradedModuleData G M) (p : projectiveSpectrum G) :
    Submodule (homogeneousLocalizationAtPrime G p)
      (localizedModuleAtPrime (M := M) G p) :=
  Submodule.span _ {z |
    ∃ (d : ℕ) (x : M) (_hx : x ∈ 𝓜.component (d : ℤ))
      (y : S) (_hy : y ∈ G.component d) (hnot : y ∉ p.asHomogeneousIdeal.toIdeal),
      z = LocalizedModule.mk x ⟨y, hnot⟩}

theorem homogeneousLocalizationAway_exists_fraction (G : GradedRingData S)
    {f : S} {d : ℕ} (hf : f ∈ G.component d)
    (z : homogeneousLocalizationAway G f) :
    ∃ n : ℕ, ∃ x : S, ∃ hx : x ∈ G.component (n • d),
      z = HomogeneousLocalization.Away.mk G.component hf n x hx := by
  obtain ⟨n, x, hx, h⟩ := HomogeneousLocalization.Away.mk_surjective G.component hf z
  exact ⟨n, x, hx, h.symm⟩

theorem homogeneousLocalizationAtPrime_exists_fraction (G : GradedRingData S)
    (p : projectiveSpectrum G) (z : homogeneousLocalizationAtPrime G p) :
    ∃ c : HomogeneousLocalization.NumDenSameDeg G.component
        p.asHomogeneousIdeal.toIdeal.primeCompl,
      z = HomogeneousLocalization.mk c ∧
        (c.num : S) ∈ G.component c.deg ∧
        (c.den : S) ∈ G.component c.deg ∧
        (c.den : S) ∉ p.asHomogeneousIdeal.toIdeal := by
  obtain ⟨c, rfl⟩ := HomogeneousLocalization.mk_surjective z
  exact ⟨c, rfl, c.num.2, c.den.2, c.den_mem⟩

/-- The prime of `S_(f)` induced by a homogeneous prime not containing `f`. -/
def homogeneousAwayPrimeIdeal (G : GradedRingData S)
    (p : projectiveSpectrum G) {f : S} (_hf : f ∉ p.asHomogeneousIdeal.toIdeal) :
    Ideal (homogeneousLocalizationAway G f) :=
  Ideal.comap (algebraMap (homogeneousLocalizationAway G f)
      (Localization (Submonoid.powers f)))
    (Ideal.map (algebraMap S (Localization (Submonoid.powers f)))
      p.asHomogeneousIdeal.toIdeal)

instance homogeneousAwayPrimeIdeal_isPrime (G : GradedRingData S)
    (p : projectiveSpectrum G) {f : S} (hf : f ∉ p.asHomogeneousIdeal.toIdeal) :
    (homogeneousAwayPrimeIdeal G p hf).IsPrime := by
  unfold homogeneousAwayPrimeIdeal
  letI : (Ideal.map (algebraMap S (Localization (Submonoid.powers f)))
      p.asHomogeneousIdeal.toIdeal).IsPrime :=
    IsLocalization.isPrime_of_isPrime_disjoint (Submonoid.powers f)
      (Localization (Submonoid.powers f)) _ p.isPrime
      (Ideal.disjoint_powers_iff_notMem_of_isPrime f |>.2 hf)
  exact Ideal.IsPrime.comap _

noncomputable def homogeneousAwayPrime (G : GradedRingData S)
    (p : projectiveSpectrum G) {f : S} (hf : f ∉ p.asHomogeneousIdeal.toIdeal) :
  PrimeSpectrum (homogeneousLocalizationAway G f) :=
  ⟨homogeneousAwayPrimeIdeal G p hf, inferInstance⟩

/-- Compatibility of the two ways of localizing a graded module at a chart and a point. -/
structure CompatibleModuleEquiv {R₁ R₂ M₁ M₂ : Type*}
    [Semiring R₁] [Semiring R₂] [AddCommMonoid M₁] [AddCommMonoid M₂]
    [Module R₁ M₁] [Module R₂ M₂] (e : R₁ ≃+* R₂) where
  toAddEquiv : M₁ ≃+ M₂
  map_smul' : ∀ (r : R₁) (x : M₁), toAddEquiv (r • x) = e r • toAddEquiv x

theorem proj_prime_localization_comparison (G : GradedRingData S)
    (𝓜 : GradedModuleData G M) (p : projectiveSpectrum G)
    {f : S} {d : ℕ} (hf : f ∈ G.component d) (hd : 0 < d)
    (hfp : f ∉ p.asHomogeneousIdeal.toIdeal) :
    ∃ eR : homogeneousLocalizationAtPrime G p ≃+*
        Localization.AtPrime (homogeneousAwayPrimeIdeal G p hfp),
      Nonempty (CompatibleModuleEquiv (M₁ := homogeneousModuleAtPrime G 𝓜 p)
        (M₂ := LocalizedModule.AtPrime (homogeneousAwayPrimeIdeal G p hfp)
          (homogeneousModuleAway G 𝓜 f d hf hd)) eR) := by
  sorry

/-! ## The topology on Proj -/

/-- The basic open `D_+(f)`. -/
def DPlus (G : GradedRingData S) (f : S) : Set (projectiveSpectrum G) :=
  (ProjectiveSpectrum.basicOpen G.component f : Set (projectiveSpectrum G))

/-- The projective zero locus of an ideal. -/
def VPlus (G : GradedRingData S) (I : HomogeneousIdeal G.component) :
    Set (projectiveSpectrum G) :=
  ProjectiveSpectrum.zeroLocus G.component I

/-- The projective zero locus of a set of homogeneous elements. -/
def VPlusSet (G : GradedRingData S) (E : Set S) : Set (projectiveSpectrum G) :=
  ProjectiveSpectrum.zeroLocus G.component E

@[simp] theorem mem_DPlus (G : GradedRingData S) {f : S}
    (p : projectiveSpectrum G) :
    p ∈ DPlus G f ↔ f ∉ p.asHomogeneousIdeal :=
  Iff.rfl

@[simp] theorem mem_VPlus (G : GradedRingData S)
    (I : HomogeneousIdeal G.component) (p : projectiveSpectrum G) :
    p ∈ VPlus G I ↔ I ≤ p.asHomogeneousIdeal :=
  Iff.rfl

@[simp] theorem mem_VPlusSet (G : GradedRingData S) (E : Set S)
    (p : projectiveSpectrum G) :
    p ∈ VPlusSet G E ↔ E ⊆ p.asHomogeneousIdeal :=
  Iff.rfl

/-- The ordinary basic open on Spec, restricted to Proj. -/
def DOnProj (G : GradedRingData S) (g : S) : Set (projectiveSpectrum G) :=
  {p | g ∉ p.asHomogeneousIdeal.toIdeal}

/-- Positive homogeneous elements, used to index the standard-open basis. -/
abbrev positiveHomogeneousElements (G : GradedRingData S) :=
  Σ d : {d : ℕ // 0 < d}, G.component d.1

theorem isOpen_DPlus (G : GradedRingData S) {f : S}
    (_hf : ∃ d : ℕ, 0 < d ∧ f ∈ G.component d) :
    IsOpen (DPlus G f) := by
  exact ProjectiveSpectrum.isOpen_basicOpen _

theorem DPlus_mul (G : GradedRingData S) (f g : S)
    (hf : ∃ d : ℕ, 0 < d ∧ f ∈ G.component d)
    (hg : ∃ d : ℕ, 0 < d ∧ g ∈ G.component d) :
    DPlus G (f * g) = DPlus G f ∩ DPlus G g := by
  sorry

theorem DOnProj_eq_DPlus_union_components (G : GradedRingData S) (g : S) :
    DOnProj G g =
      DOnProj G (GradedRing.proj G.component 0 g) ∪
        ⋃ d : {d : ℕ // 0 < d},
          DPlus G (GradedRing.proj G.component d.1 g) := by
  sorry

theorem DOnProj_degree_zero_eq_iUnion_DPlus (G : GradedRingData S) (g₀ : S)
    (hg₀ : g₀ ∈ G.component 0) :
    DOnProj G g₀ =
      ⋃ x : positiveHomogeneousElements G, DPlus G (g₀ * (x.2 : S)) := by
  sorry

theorem isTopologicalBasis_DPlus (G : GradedRingData S) :
    TopologicalSpace.IsTopologicalBasis
      (Set.range (fun x : positiveHomogeneousElements G => DPlus G (x.2 : S))) := by
  sorry

/-- The natural Z-grading of the ordinary localization in a projective chart. -/
theorem exists_natural_localization_z_grading (G : GradedRingData S)
    {f : S} {d : ℕ} (hf : f ∈ G.component d) (hd : 0 < d) :
    ∃ H : ZGradedRingData (Localization (Submonoid.powers f)),
      HasPositiveHomogeneousUnit H ∧
        Nonempty (H.component 0 ≃+* homogeneousLocalizationAway G f) := by
  sorry

/-- The two homeomorphisms in the affine-chart description of `D_+(f)`. -/
theorem DPlus_chart_homeomorphisms (G : GradedRingData S)
    {f : S} {d : ℕ} (hf : f ∈ G.component d) (hd : 0 < d)
    : ∃ (H : ZGradedRingData (Localization (Submonoid.powers f))),
      HasPositiveHomogeneousUnit H ∧
        Nonempty (H.component 0 ≃+* homogeneousLocalizationAway G f) ∧
        IsHomeomorph (zGradedPrimeToDegreeZero H) ∧
        Nonempty (DPlus G f ≃ₜ zGradedPrimeSpectrum H) ∧
          Nonempty (zGradedPrimeSpectrum H ≃ₜ
            PrimeSpectrum (homogeneousLocalizationAway G f)) := by
  sorry

theorem isClosed_VPlus (G : GradedRingData S)
    (I : HomogeneousIdeal G.component) :
    IsClosed (VPlus G I) := by
  exact ProjectiveSpectrum.isClosed_zeroLocus G.component I

theorem isClosed_VPlusSet (G : GradedRingData S) (E : Set S) :
    IsClosed (VPlusSet G E) := by
  exact ProjectiveSpectrum.isClosed_zeroLocus G.component E

theorem closed_subset_eq_VPlus (G : GradedRingData S)
    {T : Set (projectiveSpectrum G)} (hT : IsClosed T) :
    ∃ I : HomogeneousIdeal G.component, T = VPlus G I := by
  sorry

theorem VPlus_empty_iff (G : GradedRingData S)
    (I : HomogeneousIdeal G.component) :
    VPlus G I = ∅ ↔ projIrrelevantIdeal G ≤ I.toIdeal.radical := by
  sorry

/-- The polynomial-ring example proving that Proj need not be quasi-compact. -/
def IsStandardPolynomialGrading (G : GradedRingData (MvPolynomial ℕ R)) : Prop :=
  ∀ n (p : MvPolynomial ℕ R),
    p ∈ G.component n ↔ MvPolynomial.IsHomogeneous p n

theorem infinite_polynomial_proj_cover
    (G : GradedRingData (MvPolynomial ℕ R))
    (hG : IsStandardPolynomialGrading G) :
    (Set.univ : Set (projectiveSpectrum G)) =
      ⋃ i : ℕ, DPlus G (MvPolynomial.X i) := by
  sorry

theorem infinite_polynomial_proj_not_quasi_compact :
    ∃ G : GradedRingData (MvPolynomial ℕ ℤ),
      IsStandardPolynomialGrading G ∧
        ¬ IsCompact (Set.univ : Set (projectiveSpectrum G)) := by
  sorry

theorem infinite_polynomial_proj_no_finite_refinement
    (G : GradedRingData (MvPolynomial ℕ ℤ))
    (hG : IsStandardPolynomialGrading G) :
    ¬ ∃ t : Finset ℕ,
      (Set.univ : Set (projectiveSpectrum G)) ⊆
        ⋃ i ∈ t, DPlus G (MvPolynomial.X i) := by
  sorry

/-! ## The one-variable polynomial example and stalks -/

def IsStandardOneVariablePolynomialGrading (G : GradedRingData R[X]) : Prop :=
  ∀ n (p : R[X]), p ∈ G.component n ↔ ∃ a : R, p = Polynomial.C a * Polynomial.X ^ n

def oneVariableProjToSpec (G : GradedRingData R[X]) :
    projectiveSpectrum G → PrimeSpectrum R :=
  fun p => PrimeSpectrum.comap (Polynomial.C : R →+* R[X])
    ⟨p.asHomogeneousIdeal.toIdeal, p.isPrime⟩

theorem one_variable_X_not_mem (G : GradedRingData R[X])
    (p : projectiveSpectrum G) (hG : IsStandardOneVariablePolynomialGrading G) :
    Polynomial.X ∉ p.asHomogeneousIdeal.toIdeal := by
  sorry

theorem one_variable_polynomial_proj_homeomorph
    (G : GradedRingData R[X])
    (hG : IsStandardOneVariablePolynomialGrading G) :
    IsHomeomorph (oneVariableProjToSpec G) := by
  sorry

/-- The degree-zero prime of a point of `Proj(R[X])` is the contraction to `R`. -/
theorem one_variable_polynomial_prime_description
    (G : GradedRingData R[X]) (p : projectiveSpectrum G)
    (hG : IsStandardOneVariablePolynomialGrading G) :
    p.asHomogeneousIdeal.toIdeal =
      Ideal.map (Polynomial.C : R →+* R[X])
        (Ideal.comap (Polynomial.C : R →+* R[X]) p.asHomogeneousIdeal.toIdeal) := by
  sorry

/-! ## Prime avoidance and homogeneous minimal primes -/

theorem homogeneous_prime_avoidance (G : GradedRingData S) {n : ℕ}
    (hn : 0 < n) (p : Fin n → Ideal S)
    (hp : ∀ i, (p i).IsHomogeneous G.component ∧ (p i).IsPrime)
    (I : Ideal S) (hI : I.IsHomogeneous G.component)
    (hIplus : I ≤ projIrrelevantIdeal G)
    (havoid : ∀ i, ¬ I ≤ p i) :
    ∃ d : ℕ, 0 < d ∧ ∃ x : S,
      x ∈ G.component d ∧ x ∈ I ∧ ∀ i, x ∉ p i := by
  sorry

/-- The homogeneous core of an ideal. -/
abbrev homogeneousCore (G : GradedRingData S) (I : Ideal S) :
    HomogeneousIdeal G.component :=
  I.homogeneousCore G.component

theorem homogeneousCore_le (G : GradedRingData S) (I : Ideal S) :
    (homogeneousCore G I).toIdeal ≤ I :=
  Ideal.toIdeal_homogeneousCore_le G.component I

theorem homogeneousCore_isPrime (G : GradedRingData S) (p : Ideal S)
    (hp : p.IsPrime) :
    (homogeneousCore G p).toIdeal.IsPrime :=
  hp.homogeneousCore

theorem minimal_prime_is_homogeneous (G : GradedRingData S) (p : Ideal S)
    (hp : p ∈ minimalPrimes S) : p.IsHomogeneous G.component := by
  sorry

theorem minimal_prime_over_homogeneous_is_homogeneous (G : GradedRingData S)
    (I p : Ideal S) (hI : I.IsHomogeneous G.component)
    (hp : p ∈ I.minimalPrimes) : p.IsHomogeneous G.component := by
  sorry

/-! ## Finite type and homogenization -/

theorem dehomogenization_finite_type (G : GradedRingData S)
    {f : S} {d : ℕ} (hf : f ∈ G.component d) (_hd : 0 < d)
    [Algebra.FiniteType (G.component 0) S] :
    Algebra.FiniteType (G.component 0) (homogeneousLocalizationAway G f) := by
  exact HomogeneousLocalization.Away.finiteType f d hf

theorem dehomogenization_finite_module (G : GradedRingData S)
    (𝓜 : GradedModuleData G M) {f : S} {d : ℕ}
    (hf : f ∈ G.component d) (hd : 0 < d) [Module.Finite S M] :
    Module.Finite (homogeneousLocalizationAway G f)
      (homogeneousModuleAway G 𝓜 f d hf hd) := by
  sorry

/-- A graded algebra and a graded module with the data produced by homogenization. -/
structure GradedAlgebraOver (R : Type u) [CommRing R] where
  carrier : Type v
  [commRing : CommRing carrier]
  [algebra : Algebra R carrier]
  grading : GradedRingData carrier

attribute [instance] GradedAlgebraOver.commRing GradedAlgebraOver.algebra

structure GradedModuleOver (A : GradedAlgebraOver.{u, v} R) where
  carrier : Type w
  [addCommGroup : AddCommGroup carrier]
  [module : Module A.carrier carrier]
  grading : GradedModuleData A.grading carrier

attribute [instance] GradedModuleOver.addCommGroup GradedModuleOver.module

/-- The full conclusion of the finite-type homogenization theorem. -/
structure HomogenizationWitness (R : Type u) (R' : Type a) (M : Type w)
    [CommRing R] [CommRing R'] [AddCommGroup M]
    [Algebra R R'] [Module R' M] where
  gradedAlgebra : GradedAlgebraOver.{u, v} R
  gradedModule : GradedModuleOver.{u, v, w} gradedAlgebra
  f : gradedAlgebra.carrier
  f_degree_one : f ∈ gradedAlgebra.grading.component 1
  ring_equiv : R' ≃+* homogeneousLocalizationAway gradedAlgebra.grading f
  module_equiv : Nonempty (CompatibleModuleEquiv (M₁ := M)
    (M₂ := homogeneousModuleAway gradedAlgebra.grading gradedModule.grading f 1
      f_degree_one (by norm_num)) ring_equiv)
  degree_zero_equiv : R ≃+* gradedAlgebra.grading.component 0
  degree_zero_equiv_compatible :
    ∀ r : R,
      ((degree_zero_equiv r :
          gradedAlgebra.grading.component 0) : gradedAlgebra.carrier) =
        algebraMap R gradedAlgebra.carrier r
  generated_in_degree_one :
    ∃ n : ℕ, ∃ x : Fin n → gradedAlgebra.carrier,
      (∀ i, x i ∈ gradedAlgebra.grading.component 1) ∧
        Algebra.adjoin R (Set.range x) = ⊤
  module_finite : Module.Finite gradedAlgebra.carrier gradedModule.carrier

theorem exists_homogenization (R : Type u) (R' : Type a) (M : Type w)
    [CommRing R] [CommRing R'] [AddCommGroup M]
    [Algebra R R'] [Module R' M]
    [Algebra.FiniteType R R'] [Module.Finite R' M] :
    Nonempty (HomogenizationWitness R R' M) := by
  sorry

end

end Formalization.Books.Algebra.Unit57
