import Mathlib.Algebra.Polynomial.Laurent

/-!
# Exercises, Chapter 63: Units

The Laurent polynomial ring is the standard `LaurentPolynomial` construction.
-/

namespace Formalization.Books.Exercises.Unit63

/-! ## Units of `ℤ[x, 1/x]` -/

/-- The Laurent polynomial ring in one invertible variable over `ℤ`. -/
abbrev IntegerLaurentPolynomial := LaurentPolynomial ℤ

/-- The group of units is the product of the units of `ℤ` and the infinite
cyclic group generated by the Laurent variable. -/
theorem integer_laurent_units_structure :
    Nonempty (IntegerLaurentPolynomialˣ ≃* Units ℤ × Multiplicative ℤ) := by
  sorry

end Formalization.Books.Exercises.Unit63
