import Mathlib.Algebra.Module.LocalizedModule.Basic
import Mathlib.Algebra.Module.Torsion.PrimaryComponent
import Mathlib.Algebra.Homology.ShortComplex.ModuleCat
import Mathlib.Algebra.Category.ModuleCat.Localization
import Mathlib.AlgebraicGeometry.EffectiveEpi
import Mathlib.AlgebraicGeometry.Limits
import Mathlib.AlgebraicGeometry.Scheme
import Mathlib.AlgebraicGeometry.Sites.MorphismProperty
import Mathlib.CategoryTheory.MorphismProperty.Limits
import Mathlib.CategoryTheory.Sites.Canonical
import Mathlib.CategoryTheory.Sites.EffectiveEpimorphic
import Mathlib.Data.Nat.PrimeFin
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.LinearAlgebra.TensorProduct.Map
import Mathlib.RingTheory.Localization.BaseChange
import Mathlib.RingTheory.Flat.Localization
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.LocalRing.Pullback
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.Defs
import Mathlib.RingTheory.Spectrum.Prime.RingHom
import Mathlib.RingTheory.Spectrum.Prime.Topology

/-!
# Examples, Chapter 82: The spectrum of the integers is not quasi-compact

This file records the ultrafilter/localization construction and the interfaces
for the two module and closed-subset descent arguments in the source section.
The substantive descent proofs are intentionally left for the proof stage.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits
open Filter Set
open AlgebraicGeometry
open DirectSum
open scoped TensorProduct

universe u v

namespace Formalization.«Books.Examples».Unit82

/-! ## The nonprincipal ultrafilter and the localizations -/

abbrev primeNumber := Nat.Primes

/-- A usable predicate for the source's phrase “nonprincipal ultrafilter”. -/
def IsNonprincipalUltrafilter {α : Type u} (U : Ultrafilter α) : Prop :=
  ∀ s : Set α, s ∈ U → ¬s.Finite

/-- The ultrafilter extending the cofinite filter on the infinite set of primes. -/
noncomputable def primeUltrafilter : Ultrafilter primeNumber :=
  Filter.hyperfilter primeNumber

theorem primeUltrafilter_isNonprincipal :
    IsNonprincipalUltrafilter primeUltrafilter := by
  intro s hs hfin
  exact hfin.notMem_hyperfilter (by simpa [primeUltrafilter] using hs)

theorem exists_nonprincipal_primeUltrafilter :
    ∃ U : Ultrafilter primeNumber, IsNonprincipalUltrafilter U := by
  exact ⟨primeUltrafilter, primeUltrafilter_isNonprincipal⟩

/-- The complement notation used throughout the construction. -/
def primeComplement (T : Set primeNumber) : Set primeNumber := Tᶜ

abbrev primeUltrafilterMember (U : Ultrafilter primeNumber) :=
  {A : Set primeNumber // A ∈ U}

theorem ultrafilter_inter_mem (U : Ultrafilter primeNumber)
    {A B : Set primeNumber} (hA : A ∈ U) (hB : B ∈ U) : A ∩ B ∈ U := by
  exact inter_mem hA hB

theorem ultrafilter_union_mem (U : Ultrafilter primeNumber)
    {A B : Set primeNumber} (hA : A ∈ U) (_hB : B ∈ U) : A ∪ B ∈ U := by
  exact U.union_mem_iff.mpr (Or.inl hA)

theorem ultrafilter_complement_mem_of_not_mem (U : Ultrafilter primeNumber)
    {A : Set primeNumber} (hA : A ∉ U) : Aᶜ ∈ U := by
  exact U.compl_mem_iff_notMem.mpr hA

theorem prime_complement_singleton_mem (U : Ultrafilter primeNumber)
    (hU : IsNonprincipalUltrafilter U) (p : primeNumber) :
    ({p} : Set primeNumber)ᶜ ∈ U := by
  apply U.compl_mem_iff_notMem.mpr
  exact fun hp => hU {p} hp (Set.finite_singleton p)

theorem exists_ultrafilter_member_eq_complement
    (U : Ultrafilter primeNumber) {T : Set primeNumber} (hT : T ∉ U) :
    ∃ A : Set primeNumber, A ∈ U ∧ T = Aᶜ := by
  refine ⟨Tᶜ, ultrafilter_complement_mem_of_not_mem U hT, ?_⟩
  simp

theorem ultrafilter_partition_not_both_mem (U : Ultrafilter primeNumber)
    {T T' : Set primeNumber} (hdisj : Disjoint T T') :
    ¬(T ∈ U ∧ T' ∈ U) := by
  sorry

theorem ultrafilter_one_of_partition_mem (U : Ultrafilter primeNumber)
    {T T' : Set primeNumber} (hunion : T ∪ T' = Set.univ) :
    T ∈ U ∨ T' ∈ U := by
  sorry

/-- The multiplicative subset generated by the rational primes in `A`. -/
def generatedPrimeSubmonoid (A : Set primeNumber) : Submonoid ℤ :=
  Submonoid.closure ((fun p : primeNumber => (p.1 : ℤ)) '' A)

theorem generatedPrimeSubmonoid_mono {A B : Set primeNumber} (hAB : A ⊆ B) :
    generatedPrimeSubmonoid A ≤ generatedPrimeSubmonoid B := by
  exact Submonoid.closure_mono (Set.image_mono hAB)

/-- The ring `Z_A = S_A⁻¹ Z`. -/
abbrev integerLocalization (A : Set primeNumber) :=
  Localization (generatedPrimeSubmonoid A)

/-- The canonical localization map when `A ⊆ B`. -/
noncomputable def integerLocalizationMap {A B : Set primeNumber} (hAB : A ⊆ B) :
    integerLocalization A →+* integerLocalization B :=
  IsLocalization.map (M := generatedPrimeSubmonoid A) (T := generatedPrimeSubmonoid B)
    (integerLocalization B) (RingHom.id ℤ) (by
      intro x hx
      exact generatedPrimeSubmonoid_mono hAB hx)

theorem integerLocalizationMap_comp_algebraMap {A B : Set primeNumber} (hAB : A ⊆ B) :
    (integerLocalizationMap hAB).comp (algebraMap ℤ (integerLocalization A)) =
      algebraMap ℤ (integerLocalization B) := by
  sorry

/-! ## The spectrum and the fiber-product identity -/

abbrev integerSpectrum : Type := PrimeSpectrum ℤ

theorem integerSpectrum_isCompact_usualTopology :
    IsCompact (Set.univ : Set integerSpectrum) := by
  exact CompactSpace.isCompact_univ

abbrev integerLocalizationSpectrum (A : Set primeNumber) : Type :=
  PrimeSpectrum (integerLocalization A)

abbrev integerSpectrumScheme : Scheme := Spec (CommRingCat.of ℤ)

abbrev integerLocalizationScheme (A : Set primeNumber) : Scheme :=
  Spec (CommRingCat.of (integerLocalization A))

noncomputable def integerLocalizationToIntegerSpectrum (A : Set primeNumber) :
    integerLocalizationScheme A ⟶ integerSpectrumScheme :=
  Spec.map (CommRingCat.ofHom (algebraMap ℤ (integerLocalization A)))

def integerLocalizationSpectrumRange (A : Set primeNumber) : Set (PrimeSpectrum ℤ) :=
  {q | q.asIdeal = ⊥ ∨
    ∃ p : primeNumber, p ∉ A ∧ q.asIdeal = Ideal.span {(p.1 : ℤ)}}

theorem integerLocalization_spectrum_eq_zero_union_complement (A : Set primeNumber) :
    Set.range (PrimeSpectrum.comap (algebraMap ℤ (integerLocalization A))) =
      integerLocalizationSpectrumRange A := by
  sorry

abbrev integerLocalizationFiberProduct (A B : Set primeNumber) : Type :=
  RingHom.pullback
    (integerLocalizationMap (Set.subset_union_left : A ⊆ A ∪ B))
    (integerLocalizationMap (Set.subset_union_right : B ⊆ A ∪ B))

theorem integerLocalization_fiberProduct_identity
    {A B : Set primeNumber} :
    Nonempty (integerLocalization (A ∩ B) ≃+*
      integerLocalizationFiberProduct A B) := by
  sorry

/-! ## The finite-family obstruction -/

abbrev integerAway (p : primeNumber) : Type :=
  Localization.Away (p.1 : ℤ)

abbrev integerAwayScheme (p : primeNumber) : Scheme :=
  Spec (CommRingCat.of (integerAway p))

noncomputable def integerAwayToSpectrum (p : primeNumber) :
    integerAwayScheme p ⟶ integerSpectrumScheme :=
  Spec.map (CommRingCat.ofHom (algebraMap ℤ (integerAway p)))

noncomputable def integerAwayToLocalization {A : Set primeNumber}
    (p : primeNumber) (hp : p ∈ A) : integerAway p →+* integerLocalization A :=
  IsLocalization.map (M := Submonoid.powers (p.1 : ℤ))
    (T := generatedPrimeSubmonoid A) (integerLocalization A) (RingHom.id ℤ) (by
    change Submonoid.powers (p.1 : ℤ) ≤ generatedPrimeSubmonoid A
    exact Submonoid.powers_le.mpr (Submonoid.subset_closure ⟨p, hp, rfl⟩))

noncomputable def integerLocalizationToAwayScheme {A : Set primeNumber}
    (p : primeNumber) (hp : p ∈ A) :
    integerLocalizationScheme A ⟶ integerAwayScheme p :=
  Spec.map (CommRingCat.ofHom (integerAwayToLocalization p hp))

theorem integerLocalization_factor_through_away {A : Set primeNumber}
    {p : primeNumber} (hp : p ∈ A) :
    integerLocalizationToAwayScheme p hp ≫ integerAwayToSpectrum p =
      integerLocalizationToIntegerSpectrum A := by
  sorry

theorem integerLocalization_ringHom_isFlat (A : Set primeNumber) :
    RingHom.Flat (algebraMap ℤ (integerLocalization A)) := by
  rw [RingHom.flat_algebraMap_iff]
  infer_instance

theorem integerLocalization_scheme_map_isFlat (A : Set primeNumber) :
    AlgebraicGeometry.Flat (integerLocalizationToIntegerSpectrum A) := by
  change AlgebraicGeometry.Flat
    (Spec.map (CommRingCat.ofHom (algebraMap ℤ (integerLocalization A))))
  rw [AlgebraicGeometry.Flat.SpecMap_iff]
  exact integerLocalization_ringHom_isFlat A

theorem finite_integerLocalization_family_factors_through_away
    (U : Ultrafilter primeNumber) {ι : Type v} [Fintype ι]
    (A : ι → Set primeNumber) (hA : ∀ i, A i ∈ U) :
    ∃ p : primeNumber, (∀ i, p ∈ A i) ∧
      ∀ i, ∃ f : integerLocalizationScheme (A i) ⟶ integerAwayScheme p,
        f ≫ integerAwayToSpectrum p = integerLocalizationToIntegerSpectrum (A i) := by
  sorry

def IsFlatRingLocalizationFamily (U : Ultrafilter primeNumber) : Prop :=
  ∀ A : primeUltrafilterMember U,
    RingHom.Flat (algebraMap ℤ (integerLocalization A.1))

def IsJointlySurjectiveIntegerLocalizationFamily (U : Ultrafilter primeNumber) : Prop :=
  Presieve.ofArrows (fun A : primeUltrafilterMember U => integerLocalizationScheme A.1)
      (fun A => integerLocalizationToIntegerSpectrum A.1) ∈
    Scheme.jointlySurjectivePrecoverage integerSpectrumScheme

def HasNoFiniteJointlySurjectiveSubfamily (U : Ultrafilter primeNumber) : Prop :=
  ∀ {ι : Type v} [Fintype ι] (j : ι → primeUltrafilterMember U),
    ¬Presieve.ofArrows (fun i => integerLocalizationScheme (j i).1)
      (fun i => integerLocalizationToIntegerSpectrum (j i).1) ∈
      Scheme.jointlySurjectivePrecoverage integerSpectrumScheme

theorem integerLocalization_family_isFlat (U : Ultrafilter primeNumber) :
    IsFlatRingLocalizationFamily U := by
  intro A
  exact integerLocalization_ringHom_isFlat A.1

theorem integerLocalization_family_isJointlySurjective
    (U : Ultrafilter primeNumber) (hU : IsNonprincipalUltrafilter U) :
    IsJointlySurjectiveIntegerLocalizationFamily U := by
  sorry

theorem integerLocalization_family_hasNoFiniteSubfamily (U : Ultrafilter primeNumber) :
    HasNoFiniteJointlySurjectiveSubfamily U := by
  sorry

theorem integerLocalization_family_flat_jointlySurjective_not_finite
    (U : Ultrafilter primeNumber) (hU : IsNonprincipalUltrafilter U) :
    IsFlatRingLocalizationFamily U ∧
      IsJointlySurjectiveIntegerLocalizationFamily U ∧
        HasNoFiniteJointlySurjectiveSubfamily U := by
  exact ⟨integerLocalization_family_isFlat U,
    integerLocalization_family_isJointlySurjective U hU,
    integerLocalization_family_hasNoFiniteSubfamily U⟩

/-! ## Claim I: the module equalizer -/

abbrev integerLocalizedModule (M : Type u) [AddCommGroup M] [Module ℤ M]
    (A : Set primeNumber) : Type _ :=
  LocalizedModule (generatedPrimeSubmonoid A) M

noncomputable def integerLocalizedModuleTensorEquiv
    (M : Type u) [AddCommGroup M] [Module ℤ M] (A : Set primeNumber) :=
  LocalizedModule.equivTensorProduct (generatedPrimeSubmonoid A) M

theorem integerLocalizedModule_localizationTensor_model
    (M : Type u) [AddCommGroup M] [Module ℤ M] (A : Set primeNumber) :
    Nonempty (integerLocalizedModule M A ≃ₗ[integerLocalization A]
      integerLocalization A ⊗[ℤ] M) := by
  sorry

theorem integerLocalizedModule_tensorProduct_model
    (M : Type u) [AddCommGroup M] [Module ℤ M] (A : Set primeNumber) :
    Nonempty (integerLocalizedModule M A ≃+
      M ⊗[ℤ] integerLocalization A) := by
  sorry

noncomputable def integerLocalizedModuleMap
    {M : Type u} [AddCommGroup M] [Module ℤ M]
    {A B : Set primeNumber} (hAB : A ⊆ B) :=
  LocalizedModule.liftOfLE (M := M) (generatedPrimeSubmonoid A) (generatedPrimeSubmonoid B)
    (generatedPrimeSubmonoid_mono hAB)

noncomputable def integerModuleLocalizationDiagonal
    (U : Ultrafilter primeNumber) (M : Type u) [AddCommGroup M] [Module ℤ M]
    (m : M) : (A : primeUltrafilterMember U) → integerLocalizedModule M A.1 :=
  fun A => LocalizedModule.mkLinearMap (generatedPrimeSubmonoid A.1) M m

def integerModuleEqualizerSet (U : Ultrafilter primeNumber)
    (M : Type u) [AddCommGroup M] [Module ℤ M] :
    Set ((A : primeUltrafilterMember U) → integerLocalizedModule M A.1) :=
  {x | ∀ A B : primeUltrafilterMember U,
      integerLocalizedModuleMap (Set.subset_union_left : A.1 ⊆ A.1 ∪ B.1) (x A) =
        integerLocalizedModuleMap (Set.subset_union_right : B.1 ⊆ A.1 ∪ B.1) (x B)}

theorem claimI_module_equalizer (U : Ultrafilter primeNumber)
    (hU : IsNonprincipalUltrafilter U)
    (M : Type u) [AddCommGroup M] [Module ℤ M] :
    Set.range (integerModuleLocalizationDiagonal U M) = integerModuleEqualizerSet U M := by
  sorry

abbrev integerModuleFractionLocalization (M : Type u) [AddCommGroup M] [Module ℤ M] :=
  integerLocalizedModule M Set.univ

theorem integerLocalization_univ_fractionRing_model :
    Nonempty (integerLocalization Set.univ ≃+* FractionRing ℤ) := by
  sorry

theorem integerLocalization_univ_rational_model :
    Nonempty (integerLocalization Set.univ ≃+* ℚ) := by
  sorry

theorem integerModuleFractionLocalization_rational_model
    (M : Type u) [AddCommGroup M] [Module ℤ M] :
    Nonempty (integerModuleFractionLocalization M ≃+
      M ⊗[ℤ] ℚ) := by
  sorry

instance integerPrimeIdeal_isPrime (p : primeNumber) :
    (Ideal.span {(p.1 : ℤ)}).IsPrime := by
  simpa using Ideal.isPrime_span_singleton_of_prime (Nat.prime_iff_prime_int.mp p.2)

abbrev integerAtPrimeModule (M : Type u) [AddCommGroup M] [Module ℤ M]
    (p : primeNumber) : Type _ :=
  LocalizedModule (Ideal.span {(p.1 : ℤ)}).primeCompl M

theorem integerLocalizedModule_complement_singleton_atPrime_model
    (M : Type u) [AddCommGroup M] [Module ℤ M] (p : primeNumber) :
    Nonempty (integerLocalizedModule M ({q : primeNumber | q ≠ p}) ≃+
      integerAtPrimeModule M p) := by
  sorry

def integerModuleIntersection (U : Ultrafilter primeNumber)
    (M : Type u) [AddCommGroup M] [Module ℤ M] :
    Set (integerModuleFractionLocalization M) :=
  {x | ∀ A : primeUltrafilterMember U, ∃ y : integerLocalizedModule M A.1,
    integerLocalizedModuleMap (show A.1 ⊆ Set.univ from subset_univ _) y = x}

noncomputable def integerModuleFractionDiagonal
    (M : Type u) [AddCommGroup M] [Module ℤ M] (m : M) :
    integerModuleFractionLocalization M :=
  LocalizedModule.mkLinearMap (generatedPrimeSubmonoid Set.univ) M m

theorem claimI_torsionFree_intersection
    (U : Ultrafilter primeNumber) (hU : IsNonprincipalUltrafilter U)
    (M : Type u) [AddCommGroup M] [Module ℤ M]
    [Module.IsTorsionFree ℤ M] :
    (∀ A : primeUltrafilterMember U,
      Function.Injective
        (integerLocalizedModuleMap (M := M)
          (show A.1 ⊆ Set.univ from subset_univ _))) ∧
      Set.range (integerModuleFractionDiagonal M) = integerModuleIntersection U M := by
  sorry

/-- The two-prime shortcut is valid after the natural finite-generation
assumption; the unrestricted shortcut in the source is false. -/
theorem claimI_two_three_intersection (M : Type u) [AddCommGroup M] [Module ℤ M]
    [Module.IsTorsionFree ℤ M] [Module.Finite ℤ M] :
    Set.range (integerModuleFractionDiagonal M) =
      {x | ∃ y₂ : integerLocalizedModule M ({p : primeNumber | p ≠ ⟨2, by decide⟩}),
        ∃ y₃ : integerLocalizedModule M ({p : primeNumber | p ≠ ⟨3, by decide⟩}),
          integerLocalizedModuleMap (subset_univ _) y₂ = x ∧
          integerLocalizedModuleMap (subset_univ _) y₃ = x} := by
  sorry

abbrev IsIntegerTorsionModule (M : Type u) [AddCommGroup M] : Prop :=
  Module.IsTorsion ℤ M

def integerTorsionSubmodule (M : Type u) [AddCommGroup M] : Submodule ℤ M :=
  Submodule.torsion ℤ M

def integerPrimaryComponent (M : Type u) [AddCommGroup M] [Module ℤ M]
    (p : primeNumber) : Submodule ℤ M :=
  Ideal.primaryComponent M (Ideal.span {(p.1 : ℤ)})

theorem integerPrimaryComponent_mem_iff
    (M : Type u) [AddCommGroup M] [Module ℤ M] (p : primeNumber) (x : M) :
    x ∈ integerPrimaryComponent M p ↔
      ∃ n : ℕ, x ∈ Submodule.torsionBySet ℤ M
        (↑((Ideal.span {(p.1 : ℤ)}) ^ n) : Set ℤ) := by
  sorry

theorem integerTorsion_eq_iSup_primaryComponents
    (M : Type u) [AddCommGroup M] (hM : IsIntegerTorsionModule M) :
    ⨆ p : primeNumber, integerPrimaryComponent M p = integerTorsionSubmodule M := by
  sorry

theorem integerTorsion_directSum_decomposition
    (M : Type u) [AddCommGroup M] (hM : IsIntegerTorsionModule M) :
    Nonempty ((Π₀ p : primeNumber, integerPrimaryComponent M p) ≃ₗ[ℤ] M) := by
  sorry

abbrev integerLocalizedPrimaryDirectSum (M : Type u) [AddCommGroup M] [Module ℤ M]
    (A : Set primeNumber) :=
  Π₀ p : {p : primeNumber // p ∉ A}, integerPrimaryComponent M p.1

theorem integerLocalizedModule_primary_decomposition
    (M : Type u) [AddCommGroup M] [Module ℤ M] (A : Set primeNumber)
    (hM : IsIntegerTorsionModule M) :
    Nonempty (integerLocalizedModule M A ≃+
      integerLocalizedPrimaryDirectSum M A) := by
  sorry

theorem integerPrimaryComponents_iSupIndep
    (M : Type u) [AddCommGroup M] [Module ℤ M] :
    iSupIndep (fun p : primeNumber => integerPrimaryComponent M p) := by
  sorry

def integerPrimaryFamily (M : Type u) [AddCommGroup M] [Module ℤ M] :=
  ∀ p : primeNumber, integerPrimaryComponent M p

def integerPrimaryFamilyFiniteOutside
    (M : Type u) [AddCommGroup M] [Module ℤ M]
    (x : integerPrimaryFamily M) (A : Set primeNumber) : Prop :=
  Set.Finite {p : primeNumber | p ∉ A ∧ x p ≠ 0}

theorem integerPrimaryFamily_finite_support_of_ultrafilter_compatibility
    (U : Ultrafilter primeNumber) {M : Type u} [AddCommGroup M] [Module ℤ M]
    (x : integerPrimaryFamily M)
    (hx : ∀ A : primeUltrafilterMember U,
      integerPrimaryFamilyFiniteOutside M x A.1) :
    Set.Finite {p : primeNumber | x p ≠ 0} := by
  sorry

theorem ultrafilter_partition_support_obstruction
    (U : Ultrafilter primeNumber) {T T' : Set primeNumber}
    (hT : T.Infinite) (hT' : T'.Infinite) (hdisj : Disjoint T T')
    (hcover : T ∪ T' = Set.univ) :
    T ∉ U ∨ T' ∉ U := by
  sorry

def integerTorsionInclusion (M : Type u) [AddCommGroup M] :
    integerTorsionSubmodule M →ₗ[ℤ] M :=
  (integerTorsionSubmodule M).subtype

def integerTorsionQuotientMap (M : Type u) [AddCommGroup M] :
    M →ₗ[ℤ] M ⧸ integerTorsionSubmodule M :=
  (integerTorsionSubmodule M).mkQ

noncomputable def integerTorsionShortComplex
    (M : Type u) [AddCommGroup M] :
    CategoryTheory.ShortComplex (ModuleCat.{u} ℤ) :=
  CategoryTheory.ShortComplex.moduleCatMk
    (R := ℤ)
    (X₁ := integerTorsionSubmodule M)
    (X₂ := M)
    (X₃ := M ⧸ integerTorsionSubmodule M)
    (integerTorsionInclusion M)
    (integerTorsionQuotientMap M)
    (by
      ext x
      simp [integerTorsionInclusion, integerTorsionQuotientMap])

theorem integerTorsion_short_exact (M : Type u) [AddCommGroup M] :
    (integerTorsionShortComplex M).ShortExact := by
  sorry

/-- Localizing the torsion/free short exact sequence gives each exact column in
the source's diagram. -/
noncomputable def integerTorsionLocalizedShortComplex
    (M : Type u) [AddCommGroup M] (A : Set primeNumber) :
  CategoryTheory.ShortComplex (ModuleCat.{u} (integerLocalization A)) :=
  (integerTorsionShortComplex M).map
    (ModuleCat.localizedModuleFunctor.{u} (generatedPrimeSubmonoid A))

theorem integerTorsionLocalizedShortComplex_short_exact
    (M : Type u) [AddCommGroup M] (A : Set primeNumber) :
    (integerTorsionLocalizedShortComplex M A).ShortExact := by
  exact integerTorsion_short_exact M |>.map_of_exact
    (ModuleCat.localizedModuleFunctor.{u} (generatedPrimeSubmonoid A))

theorem claimI_general_module (U : Ultrafilter primeNumber)
    (hU : IsNonprincipalUltrafilter U)
    (M : Type u) [AddCommGroup M] [Module ℤ M] :
    Set.range (integerModuleLocalizationDiagonal U M) = integerModuleEqualizerSet U M := by
  exact claimI_module_equalizer U hU M

/-! ## The module descent lemma -/

structure RingMapFamily where
  base : CommRingCat
  index : Type v
  target : index → CommRingCat
  map : ∀ i, base ⟶ target i

def RingMapFamily.restrict (F : RingMapFamily) {κ : Type v} (j : κ → F.index) :
    RingMapFamily where
  base := F.base
  index := κ
  target := fun i => F.target (j i)
  map := fun i => F.map (j i)

abbrev familyBaseChange (F : RingMapFamily) (M : Type u) [AddCommGroup M]
    [Module F.base M] (i : F.index) : Type u :=
  letI : Algebra F.base (F.target i) := (F.map i).hom.toAlgebra
  M ⊗[F.base] F.target i

abbrev familyDoubleBaseChange (F : RingMapFamily) (M : Type u) [AddCommGroup M]
    [Module F.base M] (i j : F.index) : Type u :=
  letI : Algebra F.base (F.target i) := (F.map i).hom.toAlgebra
  letI : Algebra F.base (F.target j) := (F.map j).hom.toAlgebra
  (M ⊗[F.base] F.target i) ⊗[F.base] F.target j

def familyModuleDiagonal (F : RingMapFamily) (M : Type u) [AddCommGroup M]
    [Module F.base M] (m : M) (i : F.index) : familyBaseChange F M i :=
  letI : Algebra F.base (F.target i) := (F.map i).hom.toAlgebra
  TensorProduct.mk F.base M (F.target i) m 1

def familyModuleLeftMap (F : RingMapFamily) (M : Type u) [AddCommGroup M]
    [Module F.base M] (i j : F.index) (x : familyBaseChange F M i) :
    familyDoubleBaseChange F M i j :=
  letI : Algebra F.base (F.target i) := (F.map i).hom.toAlgebra
  letI : Algebra F.base (F.target j) := (F.map j).hom.toAlgebra
  (TensorProduct.mk F.base (familyBaseChange F M i) (F.target j)).flip 1 x

def familyModuleRightMap (F : RingMapFamily) (M : Type u) [AddCommGroup M]
    [Module F.base M] (i j : F.index) (y : familyBaseChange F M j) :
    familyDoubleBaseChange F M i j :=
  letI : Algebra F.base (F.target i) := (F.map i).hom.toAlgebra
  letI : Algebra F.base (F.target j) := (F.map j).hom.toAlgebra
  TensorProduct.map
    ((TensorProduct.mk F.base M (F.target i)).flip 1)
    (LinearMap.id : F.target j →ₗ[F.base] F.target j) y

def familyModuleEqualizerSet (F : RingMapFamily) (M : Type u) [AddCommGroup M]
    [Module F.base M] : Set ((i : F.index) → familyBaseChange F M i) :=
  {x | ∀ i j, familyModuleLeftMap F M i j (x i) =
    familyModuleRightMap F M i j (x j)}

def IsModuleEqualizerFamily (F : RingMapFamily) : Prop :=
  ∀ (M : Type u) [AddCommGroup M] [Module F.base M],
    Set.range (familyModuleDiagonal F M) = familyModuleEqualizerSet F M

def IsFlatRingMapFamily (F : RingMapFamily) : Prop :=
  ∀ i, RingHom.Flat (F.map i).hom

def HasNoFiniteModuleEqualizerSubfamily (F : RingMapFamily) : Prop :=
  ∀ {κ : Type v} [Fintype κ] (j : κ → F.index),
    ¬IsModuleEqualizerFamily (F.restrict j)

theorem lemma_non_fpqc_descent :
    ∃ F : RingMapFamily, Infinite F.index ∧
      IsFlatRingMapFamily F ∧ IsModuleEqualizerFamily F ∧
        HasNoFiniteModuleEqualizerSubfamily F := by
  sorry

/-! ## Claim II: compatible closed subsets -/

def ringLocalizationSubmonoid (R : Type u) [CommRing R]
    (A : Set primeNumber) : Submonoid R :=
  (generatedPrimeSubmonoid A).map (algebraMap ℤ R)

abbrev ringLocalization (R : Type u) [CommRing R] (A : Set primeNumber) :=
  Localization (ringLocalizationSubmonoid R A)

theorem ringLocalization_tensorProduct_model
    (R : Type u) [CommRing R] (A : Set primeNumber) :
    Nonempty (ringLocalization R A ≃+* R ⊗[ℤ] integerLocalization A) := by
  sorry

noncomputable def ringLocalizationMap {R : Type u} [CommRing R]
    {A B : Set primeNumber} (hAB : A ⊆ B) :
    ringLocalization R A →+* ringLocalization R B :=
  IsLocalization.map (M := ringLocalizationSubmonoid R A)
    (T := ringLocalizationSubmonoid R B) (ringLocalization R B) (RingHom.id R)
    (by
      change ∀ x, x ∈ ringLocalizationSubmonoid R A →
        x ∈ ringLocalizationSubmonoid R B
      intro x hx
      rcases hx with ⟨y, hy, rfl⟩
      exact ⟨y, generatedPrimeSubmonoid_mono hAB hy, rfl⟩)

noncomputable def ringLocalizationSpectrumMap {R : Type u} [CommRing R]
    {A B : Set primeNumber} (hAB : A ⊆ B) :
    PrimeSpectrum (ringLocalization R B) → PrimeSpectrum (ringLocalization R A) :=
  PrimeSpectrum.comap (ringLocalizationMap hAB)

abbrev ringLocalizedModule (R : Type u) [CommRing R] (M : Type u)
    [AddCommGroup M] [Module R M] (A : Set primeNumber) :=
  LocalizedModule (ringLocalizationSubmonoid R A) M

abbrev IsIntegerTorsionRingModule (R : Type u) [CommRing R] (M : Type u)
    [AddCommGroup M] [Module R M] : Prop :=
  Module.IsTorsion ℤ M

def ringPrimaryComponent (R : Type u) [CommRing R] (M : Type u)
    [AddCommGroup M] [Module R M] (p : primeNumber) : Submodule R M :=
  ⨆ n : ℕ, Submodule.torsionBy R M ((p.1 : R) ^ n)

theorem ringPrimaryComponent_mem_iff
    (R : Type u) [CommRing R] (M : Type u) [AddCommGroup M] [Module R M]
    (p : primeNumber) (x : M) :
    x ∈ ringPrimaryComponent R M p ↔
      ∃ n : ℕ, ((p.1 : R) ^ n) • x = 0 := by
  sorry

theorem ringPrimaryComponents_decompose
    (R : Type u) [CommRing R] (M : Type u) [AddCommGroup M] [Module R M]
    (hM : IsIntegerTorsionRingModule R M) :
    (⨆ p : primeNumber, ringPrimaryComponent R M p = ⊤) ∧
      iSupIndep (fun p : primeNumber => ringPrimaryComponent R M p) := by
  sorry

abbrev ringLocalizedPrimaryDirectSum (R : Type u) [CommRing R] (M : Type u)
    [AddCommGroup M] [Module R M] (A : Set primeNumber) :=
  Π₀ p : {p : primeNumber // p ∉ A}, ringPrimaryComponent R M p.1

theorem ringLocalizedModule_primary_decomposition
    (R : Type u) [CommRing R] (M : Type u) [AddCommGroup M] [Module R M]
    (A : Set primeNumber) (hM : IsIntegerTorsionRingModule R M) :
    Nonempty (ringLocalizedModule R M A ≃+
      ringLocalizedPrimaryDirectSum R M A) := by
  sorry

structure ClosedSubsetGlueData (R : Type u) [CommRing R]
    (U : Ultrafilter primeNumber) where
  carrier : ∀ A : primeUltrafilterMember U,
    Set (PrimeSpectrum (ringLocalization R A.1))
  isClosed : ∀ A, IsClosed (carrier A)
  compatible : ∀ A B : primeUltrafilterMember U,
    (ringLocalizationSpectrumMap (R := R)
      (show A.1 ⊆ A.1 ∪ B.1 from subset_union_left)) ⁻¹' carrier A =
      (ringLocalizationSpectrumMap (R := R)
      (show B.1 ⊆ A.1 ∪ B.1 from subset_union_right)) ⁻¹' carrier B

def closedSubsetIdeal (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U)
    (A : primeUltrafilterMember U) : Ideal (ringLocalization R A.1) :=
  PrimeSpectrum.vanishingIdeal (d.carrier A)

theorem closedSubsetIdeal_isRadical (R : Type u) [CommRing R]
    (U : Ultrafilter primeNumber) (d : ClosedSubsetGlueData R U)
    (A : primeUltrafilterMember U) :
    (closedSubsetIdeal R U d A).IsRadical := by
  exact PrimeSpectrum.isRadical_vanishingIdeal (d.carrier A)

def closedSubsetIdealAfterBaseChange (R : Type u) [CommRing R]
    (U : Ultrafilter primeNumber) (d : ClosedSubsetGlueData R U)
    (A B : primeUltrafilterMember U) :
    Ideal (ringLocalization R (A.1 ∪ B.1)) :=
  Ideal.map
    (ringLocalizationMap (R := R)
      (show A.1 ⊆ A.1 ∪ B.1 from subset_union_left))
    (closedSubsetIdeal R U d A)

theorem closedSubsetIdeal_baseChange_compatible
    (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) (A B : primeUltrafilterMember U) :
    closedSubsetIdealAfterBaseChange R U d A B =
      Ideal.map
        (ringLocalizationMap (R := R)
          (show B.1 ⊆ A.1 ∪ B.1 from subset_union_right))
        (closedSubsetIdeal R U d B) := by
  sorry

theorem closedSubsetIdealAfterBaseChange_isRadical
    (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) (A B : primeUltrafilterMember U) :
    (closedSubsetIdealAfterBaseChange R U d A B).IsRadical := by
  sorry

def radicalIdealOfClosedSubset {R : Type u} [CommRing R]
    (T : Set (PrimeSpectrum R)) : Ideal R :=
  PrimeSpectrum.vanishingIdeal T

theorem radicalIdealOfClosedSubset_isRadical {R : Type u} [CommRing R]
    (T : Set (PrimeSpectrum R)) :
    (radicalIdealOfClosedSubset T).IsRadical := by
  exact PrimeSpectrum.isRadical_vanishingIdeal T

theorem closedSubset_eq_zeroLocus_radicalIdeal {R : Type u} [CommRing R]
    (T : Set (PrimeSpectrum R)) (hT : IsClosed T) :
    PrimeSpectrum.zeroLocus (radicalIdealOfClosedSubset T) = T := by
  sorry

def gluedIdeal (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) : Ideal R :=
  Ideal.comap (algebraMap R (ringLocalization R Set.univ))
    (radicalIdealOfClosedSubset (d.carrier ⟨Set.univ, univ_mem⟩))

abbrev gluedIdealAt (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) (A : primeUltrafilterMember U) :
    Ideal (ringLocalization R A.1) :=
  Ideal.map (algebraMap R (ringLocalization R A.1)) (gluedIdeal R U d)

theorem gluedIdeal_localizes_to_each_closed_ideal
    (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) (A : primeUltrafilterMember U) :
    closedSubsetIdeal R U d A ≤ gluedIdealAt R U d A := by
  sorry

abbrev gluedIdealQuotientSubgroup (R : Type u) [CommRing R]
    (U : Ultrafilter primeNumber) (d : ClosedSubsetGlueData R U)
    (A : primeUltrafilterMember U) :
    AddSubgroup (gluedIdealAt R U d A) :=
  (closedSubsetIdeal R U d A).toAddSubgroup.comap
    (gluedIdealAt R U d A).toAddSubgroup.subtype

abbrev gluedIdealQuotient (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) (A : primeUltrafilterMember U) :=
  (gluedIdealAt R U d A) ⧸ gluedIdealQuotientSubgroup R U d A

theorem gluedIdeal_quotient_is_integerTorsion
    (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) (A : primeUltrafilterMember U) :
    IsIntegerTorsionModule (gluedIdealQuotient R U d A) := by
  sorry

theorem claimII_compatible_closed_subsets
    (R : Type u) [CommRing R] (U : Ultrafilter primeNumber)
    (d : ClosedSubsetGlueData R U) :
    ∃ T : Set (PrimeSpectrum R), IsClosed T ∧
      ∀ A : primeUltrafilterMember U,
        (PrimeSpectrum.comap (algebraMap R (ringLocalization R A.1))) ⁻¹' T = d.carrier A := by
  sorry

/-! ## The canonical-topology conclusion -/

def UniversallyEffectiveEpiFamily {B : Scheme} {ι : Type v}
    (X : ι → Scheme) (f : ∀ i, X i ⟶ B) : Prop :=
  EffectiveEpiFamily X f ∧
    ∀ {Y : Scheme} (g : Y ⟶ B),
      EffectiveEpiFamily (fun i => pullback (f i) g)
        (fun i => pullback.snd (f i) g)

def RefinesFamily {B : Scheme} {ι : Type*} {κ : Type*}
    (X : ι → Scheme) (f : ∀ i, X i ⟶ B)
    (Y : κ → Scheme) (g : ∀ j, Y j ⟶ B) (α : κ → ι) : Prop :=
  ∀ j, ∃ h : Y j ⟶ X (α j), h ≫ f (α j) = g j

def CanonicalCoverFamily {B : Scheme} {ι : Type v}
    (X : ι → Scheme) (f : ∀ i, X i ⟶ B) : Prop :=
  Sieve.generate (Presieve.ofArrows X f) ∈ Sheaf.canonicalTopology Scheme B

def IsQuasiCompactCanonicalObject (B : Scheme) : Prop :=
  ∀ {ι : Type v} (X : ι → Scheme) (f : ∀ i, X i ⟶ B),
    CanonicalCoverFamily X f →
      ∃ (κ : Type v) (Y : κ → Scheme) (g : ∀ j, Y j ⟶ B) (α : κ → ι),
        CanonicalCoverFamily Y g ∧ Set.Finite (Set.range α) ∧
          RefinesFamily X f Y g α

def integerLocalizationCoverFamily (U : Ultrafilter primeNumber) :
    primeUltrafilterMember U → Scheme :=
  fun A => integerLocalizationScheme A.1

def integerLocalizationCoverMaps (U : Ultrafilter primeNumber) :
    ∀ A : primeUltrafilterMember U,
      integerLocalizationCoverFamily U A ⟶ integerSpectrumScheme :=
  fun A => integerLocalizationToIntegerSpectrum A.1

def integerLocalizationFiniteFamily (U : Ultrafilter primeNumber)
    {κ : Type v} (j : κ → primeUltrafilterMember U) : κ → Scheme :=
  fun i => integerLocalizationScheme (j i).1

def integerLocalizationFiniteFamilyMaps (U : Ultrafilter primeNumber)
    {κ : Type v} (j : κ → primeUltrafilterMember U) :
    ∀ i, integerLocalizationFiniteFamily U j i ⟶ integerSpectrumScheme :=
  fun i => integerLocalizationToIntegerSpectrum (j i).1

theorem universallyEffectiveEpiFamily_isCanonicalCover
    {B : Scheme} {ι : Type v} (X : ι → Scheme)
    (f : ∀ i, X i ⟶ B) (h : UniversallyEffectiveEpiFamily X f) :
    CanonicalCoverFamily X f := by
  sorry

theorem integerLocalization_family_isUniversallyEffectiveEpi
    (U : Ultrafilter primeNumber) (hU : IsNonprincipalUltrafilter U) :
    UniversallyEffectiveEpiFamily
      (integerLocalizationCoverFamily U) (integerLocalizationCoverMaps U) := by
  sorry

theorem integerLocalization_family_isCanonicalCover
    (U : Ultrafilter primeNumber) (hU : IsNonprincipalUltrafilter U) :
    CanonicalCoverFamily (integerLocalizationCoverFamily U)
      (integerLocalizationCoverMaps U) := by
  exact universallyEffectiveEpiFamily_isCanonicalCover _ _
    (integerLocalization_family_isUniversallyEffectiveEpi U hU)

theorem integerLocalization_family_has_no_finite_refinement
    (U : Ultrafilter primeNumber) :
    ¬∃ (κ : Type v) (_ : Fintype κ) (j : κ → primeUltrafilterMember U)
      (ι : Type v) (Y : ι → Scheme) (g : ∀ i, Y i ⟶ integerSpectrumScheme)
      (α : ι → κ),
      UniversallyEffectiveEpiFamily Y g ∧
        @RefinesFamily integerSpectrumScheme κ ι
          (integerLocalizationFiniteFamily U j)
          (integerLocalizationFiniteFamilyMaps U j) Y g α := by
  sorry

theorem lemma_Z_not_quasi_compact :
    ¬IsQuasiCompactCanonicalObject integerSpectrumScheme := by
  sorry

end Formalization.«Books.Examples».Unit82
