import Mathlib.AlgebraicGeometry.Sites.Proetale
import Mathlib.CategoryTheory.Sites.LocallySurjective

/-!
# Pro-étale Cohomology, Chapter 1: Introduction

The source section contains the chapter's goals, historical discussion, and
motivation.  Those paragraphs do not introduce formal data.  Its precise
mathematical roadmap assertion is recorded below using Mathlib's canonical
pro-étale site and locally-surjective sheaf interfaces.
-/

universe u v

open CategoryTheory CategoryTheory.GrothendieckTopology Opposite
open AlgebraicGeometry
open AlgebraicGeometry.Scheme

namespace Formalization.Books.Proetale.Unit01

/--
An object of a site is weakly contractible when sections over it lift along
every locally surjective morphism of sheaves of types.

This is the sheaf-theoretic formulation used in the source's definition of a
weakly contractible object; `Sheaf.IsLocallySurjective` is Mathlib's canonical
form of a surjective map of sheaves.
-/
def IsWeaklyContractible {C : Type u} [Category.{v} C]
    (J : GrothendieckTopology C) (U : C) : Prop :=
  ∀ {F G : Sheaf J (Type (max u v))} (f : F ⟶ G),
    Sheaf.IsLocallySurjective f →
      Function.Surjective (f.hom.app (op U))

/--
The site `S.ProEt` has enough quasi-compact weakly contractible objects when
every object admits a covering sieve generated by a family of such objects.
The quasi-compact condition is Mathlib's `CompactSpace` property on the
underlying scheme of a pro-étale object.
-/
def HasEnoughQuasiCompactWeaklyContractibleObjects (S : Scheme.{u}) : Prop :=
  ∀ U : S.ProEt,
    ∃ (ι : Type (u + 1)) (V : ι → S.ProEt) (f : ∀ i, V i ⟶ U),
        Sieve.ofArrows V f ∈ ProEt.topology S U ∧
        ∀ i, CompactSpace (V i).left ∧
          IsWeaklyContractible (ProEt.topology S) (V i)

/--
The small pro-étale site of a scheme has enough quasi-compact weakly
contractible objects.  This is the precise assertion announced in the
Introduction; its proof belongs to the later construction of such objects.
-/
theorem smallProEtale_hasEnoughQuasiCompactWeaklyContractibleObjects
    (S : Scheme.{u}) : HasEnoughQuasiCompactWeaklyContractibleObjects S := by
  -- TODO: import the later pro-etale construction and apply its two key lemmas:
  -- (1) every `U : S.ProEt` admits a jointly covering family `V i ⟶ U`
  --     whose sources are quasi-compact and weakly contractible, and
  -- (2) the sieve generated by a jointly covering pro-etale family belongs to
  --     `ProEt.topology S U`.  Unpacking those conclusions proves this goal.
  sorry

end Formalization.Books.Proetale.Unit01
