import Mathlib.AlgebraicGeometry.Sites.Proetale
import Mathlib.CategoryTheory.Sites.LocallySurjective

/-!
# Pro-étale Cohomology, Chapter 1: Introduction

The source section contains the chapter's goals, historical discussion, and
motivation.  Those paragraphs do not introduce formal data.  Its precise
mathematical roadmap assertion is recorded below using Mathlib's canonical
pro-étale site and locally-surjective sheaf interfaces.
-/

universe u v

open CategoryTheory CategoryTheory.GrothendieckTopology Opposite
open AlgebraicGeometry
open AlgebraicGeometry.Scheme

namespace Formalization.Books.Proetale.Unit01

/--
An object of a site is weakly contractible when sections over it lift along
every locally surjective morphism of sheaves of types.

This is the sheaf-theoretic formulation used in the source's definition of a
weakly contractible object; `Sheaf.IsLocallySurjective` is Mathlib's canonical
form of a surjective map of sheaves.
-/
def IsWeaklyContractible {C : Type u} [Category.{v} C]
    (J : GrothendieckTopology C) (U : C) : Prop :=
  ∀ {F G : Sheaf J (Type (max u v))} (f : F ⟶ G),
    Sheaf.IsLocallySurjective f →
      Function.Surjective (f.hom.app (op U))

/--
The site `S.ProEt` has enough quasi-compact weakly contractible objects when
every object admits a covering sieve generated by a family of such objects.
The quasi-compact condition is Mathlib's `CompactSpace` property on the
underlying scheme of a pro-étale object.
-/
def HasEnoughQuasiCompactWeaklyContractibleObjects (S : Scheme.{u}) : Prop :=
  ∀ U : S.ProEt,
    ∃ (ι : Type (u + 1)) (V : ι → S.ProEt) (f : ∀ i, V i ⟶ U),
        Sieve.ofArrows V f ∈ ProEt.topology S U ∧
        ∀ i, CompactSpace (V i).left ∧
          IsWeaklyContractible (ProEt.topology S) (V i)

/-!
## Roadmap for the later existence theorem

The Introduction only announces that the small pro-étale site has enough
quasi-compact weakly contractible objects.  The named theorem must be stated
and proved in the later unit formalizing `books/proetale.tex`, Section
`section-weakly-contractible`, after the ring construction in Section
`section-w-contractible` and the pro-étale-site section.  In particular,
Unit 01 must not import those later units.

The eventual theorem should have the signature
`(S : Scheme.{u}) : HasEnoughQuasiCompactWeaklyContractibleObjects S` and can
be assembled as follows.

1. First complete the ring-side prerequisites in the units corresponding to
   Sections `section-weakly-etale` and `section-w-contractible`.

   * Reuse `IsIndEtale` and `indEtale_isWeaklyEtale` from
     `Formalization/Books/Proetale/Unit07/IndEtale.lean`, together with
     `WLocalAlgebraicResidueExtension` and
     `exists_wLocalAlgebraicResidueExtension` from
     `Formalization/Books/Proetale/Unit08/ConstructingIndEtale.lean`, to prove
     the source's factorization of a weakly étale ring map through a
     faithfully flat ind-étale map.
   * In the future unit for Section `section-w-contractible`, define the
     source predicate saying that every faithfully flat weakly étale map out
     of `A` retracts, prove its equivalent ind-étale formulation, and prove
     that every `A` has a faithfully flat ind-étale map `A →+* D` with `D`
     w-contractible.  The construction also uses
     `exists_minimalStoneanCover` from
     `Formalization/Books/Topology/Unit25/ExtremallyDisconnectedSpaces.lean`
     and the ind-Zariski API `IsIndZariski`, `isIndZariski_comp`, and
     `isIndZariski_identifiesLocalRings` from
     `Formalization/Books/Proetale/Unit04/IndZariski.lean`.
   * Supply an explicit affine bridge between ring weak étaleness and
     `AlgebraicGeometry.WeaklyEtale (Scheme.Spec.map φ)`.  This bridge is not
     currently provided by
     `Mathlib/AlgebraicGeometry/Morphisms/WeaklyEtale.lean` (that file records
     it as a TODO), so `indEtale_isWeaklyEtale` alone cannot construct an
     object of `S.ProEt`.  Faithful flatness gives flatness and surjectivity
     on spectra via `AlgebraicGeometry.flat_and_surjective_SpecMap_iff` in
     `Mathlib/AlgebraicGeometry/Morphisms/Flat.lean`.

2. Prove the affine site bridge in the future weakly-contractible-objects
   unit: if `T : S.ProEt` is affine and its coordinate ring is
   w-contractible, then
   `IsWeaklyContractible (ProEt.topology S) T`.

   * Given `f : F ⟶ G`, a proof of `Sheaf.IsLocallySurjective f`, and an
     `s` in the codomain of `f.hom.app (op T)`, install the local-surjectivity
     proof as an instance.
     Then `Presheaf.imageSieve_mem` in
     `Mathlib/CategoryTheory/Sites/LocallySurjective.lean` says that
     `Presheaf.imageSieve f.hom s` covers `T`.
   * Apply
     `Precoverage.mem_toGrothendieck_iff_of_isStableUnderComposition` from
     `Mathlib/CategoryTheory/Sites/PrecoverageToGrothendieck.lean` to extract
     a `ProEt.precoverage S`-presieve contained in that image sieve, and turn
     it into a zero-hypercover with
     `Precoverage.mem_iff_exists_zeroHypercover`.  Map its arrows along
     `ProEt.forget S ⋙ Over.forget S`; by `Precoverage.mem_comap_iff` they
     form a `Scheme.Cover` for `proetalePrecoverage`.  Use
     `Scheme.Cover.forgetQc` and then `QuasiCompactCover.exists_hom` from
     `Mathlib/AlgebraicGeometry/Cover/QuasiCompact.lean` to refine this, over
     the affine scheme `T.left`, by a finite affine weakly étale cover.  Keep
     the refinement morphism: it proves that every refined arrow is still in
     `Presheaf.imageSieve f.hom s`.
   * Collapse that finite cover with `Scheme.Cover.sigma` from
     `Mathlib/AlgebraicGeometry/Cover/Sigma.lean`.  Its source is affine by
     the finite-coproduct instance in
     `Mathlib/AlgebraicGeometry/Limits.lean`.  Convert the resulting affine
     faithfully flat weakly étale map to a ring map, split it using
     w-contractibility, and translate the retraction back to a section of
     schemes.  For each component, obtain a section of `F` from its image-
     sieve membership using `Presheaf.localPreimage` and
     `Presheaf.app_localPreimage`.  Lift the component cover and its finite
     coproduct to `S.ProEt`, glue these sections over the disjoint components
     with `Presieve.IsSheafFor.amalgamate` from
     `Mathlib/CategoryTheory/Sites/IsSheafFor.lean` (compatibility on distinct
     components reduces to the empty-object cover
     `ProEt.bot_mem_topology`), and finally pull the glued section back along
     the splitting section.  Naturality and
     `Presheaf.app_localPreimage` show that it maps to `s`.

3. Construct the covering family of an arbitrary `U : S.ProEt`.

   * Start from `U.left.affineCover` in
     `Mathlib/AlgebraicGeometry/Cover/Open.lean`.  Each source is affine by
     `Scheme.isAffine_affineCover` in
     `Mathlib/AlgebraicGeometry/AffineScheme.lean`.
   * For every affine member `Spec A`, choose the faithfully flat ind-étale
     w-contractible extension `A →+* D` from Step 1.  Compose
     `Spec D ⟶ Spec A` with the affine-open arrow and `U.hom`; use the affine
     weakly-étale bridge and multiplicativity to construct an object with
     `ProEt.mk`, and use `MorphismProperty.Over.homMk` from
     `Mathlib/CategoryTheory/MorphismProperty/Comma.lean` for its arrow to
     `U`.
   * Each source has `CompactSpace` by
     `Scheme.compactSpace_of_isAffine` in
     `Mathlib/AlgebraicGeometry/AffineScheme.lean`, and is weakly
     contractible by Step 2.
   * Prove the family belongs to `ProEt.precoverage S` using
     `Precoverage.mem_comap_iff` and `Presieve.map_ofArrows`; the underlying
     scheme family is quasi-compact and jointly surjective.  Then
     `Precoverage.generate_mem_toGrothendieck` gives
     `Sieve.ofArrows V f ∈ ProEt.topology S U`.  Package the index type,
     objects, arrows, covering proof, compactness, and Step 2 into the tuple
     required by `HasEnoughQuasiCompactWeaklyContractibleObjects`.

The identity family cannot work for a general `U`, since it would require
`U` itself to be compact and weakly contractible.  The empty family covers
only an object with empty underlying scheme (`ProEt.bot_mem_topology`).  An
affine cover supplies compact sources but not weak contractibility.  Finally,
local surjectivity supplies only the covering image sieve and local lifts;
using it directly for a global lift is circular until the w-contractible
refinement and splitting argument in Step 2 has been established.
-/

end Formalization.Books.Proetale.Unit01
