import Mathlib.AlgebraicGeometry.Sites.Proetale
import Mathlib.CategoryTheory.Sites.LocallySurjective

/-!
# Pro-étale Cohomology, Chapter 1: Introduction

The source section contains the chapter's goals, historical discussion, and
motivation.  Those paragraphs do not introduce formal data.  Its precise
mathematical roadmap assertion is recorded below using Mathlib's canonical
pro-étale site and locally-surjective sheaf interfaces.
-/

universe u v

open CategoryTheory CategoryTheory.GrothendieckTopology Opposite
open AlgebraicGeometry
open AlgebraicGeometry.Scheme

namespace Formalization.Books.Proetale.Unit01

/--
An object of a site is weakly contractible when sections over it lift along
every locally surjective morphism of sheaves of types.

This is the sheaf-theoretic formulation used in the source's definition of a
weakly contractible object; `Sheaf.IsLocallySurjective` is Mathlib's canonical
form of a surjective map of sheaves.
-/
def IsWeaklyContractible {C : Type u} [Category.{v} C]
    (J : GrothendieckTopology C) (U : C) : Prop :=
  ∀ {F G : Sheaf J (Type (max u v))} (f : F ⟶ G),
    Sheaf.IsLocallySurjective f →
      Function.Surjective (f.hom.app (op U))

/--
The site `S.ProEt` has enough quasi-compact weakly contractible objects when
every object admits a covering sieve generated by a family of such objects.
The quasi-compact condition is Mathlib's `CompactSpace` property on the
underlying scheme of a pro-étale object.
-/
def HasEnoughQuasiCompactWeaklyContractibleObjects (S : Scheme.{u}) : Prop :=
  ∀ U : S.ProEt,
    ∃ (ι : Type (u + 1)) (V : ι → S.ProEt) (f : ∀ i, V i ⟶ U),
        Sieve.ofArrows V f ∈ ProEt.topology S U ∧
        ∀ i, CompactSpace (V i).left ∧
          IsWeaklyContractible (ProEt.topology S) (V i)

/--
The small pro-étale site of a scheme has enough quasi-compact weakly
contractible objects.  This is the precise assertion announced in the
Introduction; its proof belongs to the later construction of such objects.

Proof roadmap:

1. Import the later weakly-contractible-cover theorem and apply it to each
   `U : S.ProEt`, obtaining a family `V i ⟶ U` with quasi-compact sources.
2. Translate the later theorem's lifting statement into
   `IsWeaklyContractible (ProEt.topology S) (V i)` by evaluating a locally
   surjective sheaf morphism on each `V i`.
3. Use the pro-étale pretopology/topology comparison to show that the sieve
   `Sieve.ofArrows V f` generated by the family belongs to
   `ProEt.topology S U`.
4. Package the same index type, objects, arrows, covering proof, compactness,
   and lifting proofs into the existential tuple in
   `HasEnoughQuasiCompactWeaklyContractibleObjects`.

Steps 1 and 2 depend on the later construction, which is not yet formalized
or imported into this chapter.
-/
theorem smallProEtale_hasEnoughQuasiCompactWeaklyContractibleObjects
    (S : Scheme.{u}) : HasEnoughQuasiCompactWeaklyContractibleObjects S := by
  sorry

end Formalization.Books.Proetale.Unit01
