import Formalization.Books.Dpa.Unit03.DividedPowerRings
import Mathlib.RingTheory.DividedPowerAlgebra.Init
import Mathlib.RingTheory.RingHom.Flat

/-!
# Divided Power Algebra, Chapter 5: Divided power polynomial algebras

This file uses Mathlib's `DividedPowerAlgebra` for the polynomial algebra
construction. For a finite set of variables, the free module on the variables
is represented by `Fin t →₀ A`; for an arbitrary set it is `W →₀ A`.
-/

namespace Formalization.Books.Dpa.Unit05

open CategoryTheory CategoryTheory.Limits
open Formalization.Books.Dpa.Unit02
open Formalization.Books.Dpa.Unit03
open Formalization.Books.Dpa.Unit03.DividedPowerRing

universe u

noncomputable section

/-! ## Finite divided power polynomial algebras -/

/-- The divided power polynomial algebra on `t` finite variables. -/
abbrev dividedPowerPolynomialAlgebra (A : Type u) [CommRing A] (t : ℕ) : Type u :=
  DividedPowerAlgebra A (Fin t →₀ A)

/-- The divided power `x_i^[n]` in the finite-variable algebra. -/
def dividedPowerVariable {A : Type u} [CommRing A] (t : ℕ) (i : Fin t)
    (n : ℕ) : dividedPowerPolynomialAlgebra A t :=
  DividedPowerAlgebra.dp A n (Finsupp.single i 1)

/-- The degree-one generator `x_i`. -/
abbrev dividedPowerGenerator {A : Type u} [CommRing A] (t : ℕ) (i : Fin t) :=
  dividedPowerVariable (A := A) t i 1

/-- The monomial `∏ i, x_i^[n_i]`. -/
def dividedPowerMonomial {A : Type u} [CommRing A] (t : ℕ)
    (n : Fin t → ℕ) : dividedPowerPolynomialAlgebra A t :=
  ∏ i : Fin t, dividedPowerVariable t i (n i)

/-- The zero multi-index gives the multiplicative unit. -/
theorem dividedPowerMonomial_zero {A : Type u} [CommRing A] (t : ℕ) :
    dividedPowerMonomial (A := A) t (fun _ ↦ 0) =
      (1 : dividedPowerPolynomialAlgebra A t) := by
  classical
  simp [dividedPowerMonomial, dividedPowerVariable,
    DividedPowerAlgebra.dp_zero]

/-- The monomials give the direct-sum `A`-module basis indexed by tuples of
nonnegative exponents. -/
theorem dividedPowerPolynomialAlgebra_monomial_basis
    {A : Type u} [CommRing A] (t : ℕ) :
    ∃ b : Module.Basis (Fin t → ℕ) A (dividedPowerPolynomialAlgebra A t),
      ∀ n, b n = dividedPowerMonomial t n := by
  sorry

/-- Multiplication of two divided powers of one variable. -/
theorem dividedPowerVariable_mul {A : Type u} [CommRing A] (t : ℕ)
    (i : Fin t) (n m : ℕ) :
    dividedPowerVariable t i n * dividedPowerVariable t i m =
      (Nat.choose (n + m) n : dividedPowerPolynomialAlgebra A t) *
        dividedPowerVariable t i (n + m) := by
  simpa [dividedPowerVariable, nsmul_eq_mul] using
    (DividedPowerAlgebra.dp_mul (R := A) (M := Fin t →₀ A)
      (n := n) (p := m) (m := Finsupp.single i 1))

/-- The canonical augmentation, sending every positive divided-power variable
to zero. -/
noncomputable def dividedPowerAugmentation {A : Type u} [CommRing A] (t : ℕ) :
    dividedPowerPolynomialAlgebra A t →ₐ[A] A :=
  DividedPowerAlgebra.lift (dividedPowersBot A)
    (0 : (Fin t →₀ A) →ₗ[A] A) (by simp)

/-- The augmentation ideal `A⟨x₁, …, xₜ⟩₊`. -/
def dividedPowerAugmentationIdeal {A : Type u} [CommRing A] (t : ℕ) :
    Ideal (dividedPowerPolynomialAlgebra A t) :=
  RingHom.ker (dividedPowerAugmentation t).toRingHom

/-- The augmentation kills every positive divided power of every variable. -/
theorem dividedPowerAugmentation_variable {A : Type u} [CommRing A] (t : ℕ)
    (i : Fin t) (n : ℕ) (hn : n ≠ 0) :
    dividedPowerAugmentation (A := A) t (dividedPowerVariable (A := A) t i n) =
      (0 : A) := by
  simp [dividedPowerAugmentation, dividedPowerVariable, hn, dividedPowersBot]

/-- The positive ideal in the one-variable algebra is generated by the
positive divided-power variables. -/
def oneVariablePositiveDividedPowerGenerators {A : Type u} [CommRing A] :
    Set (dividedPowerPolynomialAlgebra A 1) :=
  Set.range (fun n : {n : ℕ // n ≠ 0} =>
    dividedPowerVariable (A := A) 1 0 n.1)

theorem dividedPowerAugmentationIdeal_one_eq_span
    {A : Type u} [CommRing A] :
    dividedPowerAugmentationIdeal (A := A) 1 =
      Ideal.span (oneVariablePositiveDividedPowerGenerators (A := A)) := by
  classical
  let P : Ideal (dividedPowerPolynomialAlgebra A 1) :=
    Ideal.span (oneVariablePositiveDividedPowerGenerators (A := A))
  have hPker : P ≤ dividedPowerAugmentationIdeal (A := A) 1 := by
    change Ideal.span (oneVariablePositiveDividedPowerGenerators (A := A)) ≤ _
    apply Ideal.span_le.mpr
    rintro z ⟨n, rfl⟩
    change dividedPowerAugmentation (A := A) 1
        (dividedPowerVariable (A := A) 1 0 n.1) = 0
    exact dividedPowerAugmentation_variable (A := A) 1 0 n.1 n.2
  have hdecomp : ∀ z : dividedPowerPolynomialAlgebra A 1,
      ∃ a : A, ∃ q : dividedPowerPolynomialAlgebra A 1,
        z = algebraMap A _ a + q ∧ q ∈ P := by
    intro z
    induction z using DividedPowerAlgebra.induction_on with
    | C a =>
        exact ⟨a, 0, by simp, P.zero_mem⟩
    | add x y hx hy =>
        rcases hx with ⟨a, q, hq, hqmem⟩
        rcases hy with ⟨b, r, hr, hrmem⟩
        refine ⟨a + b, q + r, ?_, P.add_mem hqmem hrmem⟩
        rw [hq, hr]
        simp [add_assoc, add_left_comm, add_comm]
    | dp x n m hx =>
        rcases hx with ⟨a, q, hq, hqmem⟩
        by_cases hn : n = 0
        · subst n
          refine ⟨a, q, ?_, hqmem⟩
          simpa [DividedPowerAlgebra.dp_zero] using hq
        · have hm : m = m 0 • Finsupp.single (0 : Fin 1) 1 := by
            apply Finsupp.ext
            intro j
            have hj : j = 0 := Fin.eq_zero j
            subst j
            simp
          have hdp : dividedPowerVariable (A := A) 1 0 n ∈ P := by
            exact Ideal.subset_span ⟨⟨n, hn⟩, rfl⟩
          have hdp' : DividedPowerAlgebra.dp A n m ∈ P := by
            rw [hm, DividedPowerAlgebra.dp_smul, Algebra.smul_def, map_pow]
            rw [← map_pow]
            exact P.mul_mem_left _ hdp
          refine ⟨0, x * DividedPowerAlgebra.dp A n m, ?_, P.mul_mem_left x hdp'⟩
          rw [hq]
          simp
  apply le_antisymm
  · intro z hz
    change dividedPowerAugmentation (A := A) 1 z = 0 at hz
    change z ∈ P
    rcases hdecomp z with ⟨a, q, hq, hqmem⟩
    have hqker : q ∈ dividedPowerAugmentationIdeal (A := A) 1 := hPker hqmem
    change dividedPowerAugmentation (A := A) 1 q = 0 at hqker
    have ha : a = 0 := by
      have heq := congrArg (dividedPowerAugmentation (A := A) 1) hq
      simpa [hz, hqker] using heq.symm
    rw [hq, ha]
    simpa using hqmem
  · exact hPker

/-- The divided-power ideal in the polynomial algebra: the coefficient ideal
extended to the algebra plus the positive-degree augmentation ideal. -/
def dividedPowerPolynomialIdeal (A : Type u) [CommRing A]
    (I : Ideal A) (t : ℕ) : Ideal (dividedPowerPolynomialAlgebra A t) :=
  Ideal.map (algebraMap A (dividedPowerPolynomialAlgebra A t)) I ⊔
    dividedPowerAugmentationIdeal t

/-- In the one-variable construction, the coefficient ideal and the positive
degree ideal intersect in their product, as used in the source proof. -/
theorem coefficientIdeal_inf_augmentationIdeal_eq_mul
    {A : Type u} [CommRing A] (I : Ideal A) :
    Ideal.map (algebraMap A (dividedPowerPolynomialAlgebra A 1)) I ⊓
        dividedPowerAugmentationIdeal 1 =
      Ideal.map (algebraMap A (dividedPowerPolynomialAlgebra A 1)) I *
        dividedPowerAugmentationIdeal 1 := by
  let K : Ideal (dividedPowerPolynomialAlgebra A 1) :=
    dividedPowerAugmentationIdeal (A := A) 1
  let J : Ideal (dividedPowerPolynomialAlgebra A 1) :=
    Ideal.map (algebraMap A (dividedPowerPolynomialAlgebra A 1)) I
  let L : Ideal (dividedPowerPolynomialAlgebra A 1) := J * K
  have hscalar (r : dividedPowerPolynomialAlgebra A 1) :
      r - algebraMap A (dividedPowerPolynomialAlgebra A 1)
          (dividedPowerAugmentation (A := A) 1 r) ∈ K := by
    change dividedPowerAugmentation (A := A) 1
        (r - algebraMap A (dividedPowerPolynomialAlgebra A 1)
          (dividedPowerAugmentation (A := A) 1 r)) = 0
    simp
  have hmain : ∀ {x : dividedPowerPolynomialAlgebra A 1}, x ∈ J →
      x - algebraMap A (dividedPowerPolynomialAlgebra A 1)
          (dividedPowerAugmentation (A := A) 1 x) ∈ L := by
    intro x hx
    change x ∈ Ideal.map (algebraMap A (dividedPowerPolynomialAlgebra A 1)) I at hx
    rw [Ideal.map] at hx
    refine Submodule.span_induction (p := fun x _ => x -
      algebraMap A (dividedPowerPolynomialAlgebra A 1)
        (dividedPowerAugmentation (A := A) 1 x) ∈ L) ?_ ?_ ?_ ?_ hx
    · rintro z ⟨i, hi, rfl⟩
      have hi' : dividedPowerAugmentation (A := A) 1
          (algebraMap A (dividedPowerPolynomialAlgebra A 1) i) = i := by
        simp
      rw [hi']
      simpa only [sub_self] using L.zero_mem
    · simpa only [map_zero, sub_zero] using L.zero_mem
    · intro x y hx hy hpx hpy
      simpa [map_add, sub_eq_add_neg, add_assoc, add_left_comm, add_comm] using
        L.add_mem hpx hpy
    · intro a x hx hpx
      have hq := hscalar a
      have hfirst :
          algebraMap A (dividedPowerPolynomialAlgebra A 1)
              (dividedPowerAugmentation (A := A) 1 a) *
            (x - algebraMap A (dividedPowerPolynomialAlgebra A 1)
              (dividedPowerAugmentation (A := A) 1 x)) ∈ L :=
        L.mul_mem_left _ hpx
      have hxJ : x ∈ J := by
        exact hx
      have hsecond :
          (a - algebraMap A (dividedPowerPolynomialAlgebra A 1)
              (dividedPowerAugmentation (A := A) 1 a)) * x ∈ L := by
        rw [mul_comm]
        exact Ideal.mul_mem_mul hxJ hq
      have hsum := L.add_mem hfirst hsecond
      convert hsum using 1
      calc
        a • x - algebraMap A (dividedPowerPolynomialAlgebra A 1)
            (dividedPowerAugmentation (A := A) 1 (a • x)) =
            a * x - algebraMap A (dividedPowerPolynomialAlgebra A 1)
              (dividedPowerAugmentation (A := A) 1 a) *
              algebraMap A (dividedPowerPolynomialAlgebra A 1)
                (dividedPowerAugmentation (A := A) 1 x) := by
          simp [map_mul]
        _ = algebraMap A (dividedPowerPolynomialAlgebra A 1)
              (dividedPowerAugmentation (A := A) 1 a) *
            (x - algebraMap A (dividedPowerPolynomialAlgebra A 1)
              (dividedPowerAugmentation (A := A) 1 x)) +
            (a - algebraMap A (dividedPowerPolynomialAlgebra A 1)
              (dividedPowerAugmentation (A := A) 1 a)) * x := by
          rw [mul_sub, sub_mul]
          abel
  apply le_antisymm
  · intro z hz
    have hzJ : z ∈ J := hz.1
    have hzK : z ∈ K := hz.2
    have hdiff := hmain hzJ
    change dividedPowerAugmentation (A := A) 1 z = 0 at hzK
    simpa [hzK] using hdiff
  · change J * K ≤ J ⊓ K
    exact Ideal.mul_le_inf

/-- The coefficient inclusion into a divided-power polynomial algebra is
flat, as used in the existence argument for the coefficient ideal. -/
theorem dividedPowerPolynomialAlgebra_flat
    {A : Type u} [CommRing A] (t : ℕ) :
    (algebraMap A (dividedPowerPolynomialAlgebra A t)).Flat := by
  rw [RingHom.flat_algebraMap_iff]
  obtain ⟨b, _⟩ := dividedPowerPolynomialAlgebra_monomial_basis (A := A) t
  let _hfree : Module.Free A (dividedPowerPolynomialAlgebra A t) :=
    Module.Free.of_basis b
  exact Module.Flat.of_free

/-- The polynomial algebra equipped with a divided-power structure on its
coefficient-plus-positive-degree ideal. -/
def dividedPowerPolynomialRing (A : DividedPowerRing.{u}) (t : ℕ)
    (δ : DividedPowers (dividedPowerPolynomialIdeal (A : Type u) A.ideal t)) :
    DividedPowerRing.{u} :=
  { toCommRing := CommRingCat.of (dividedPowerPolynomialAlgebra (A : Type u) t)
    ideal := dividedPowerPolynomialIdeal (A : Type u) A.ideal t
    dividedPowers := δ }

/-- Compatibility of a divided-power structure on the polynomial ideal with
the canonical coefficient map. -/
def CoefficientDpowCompatible (A : DividedPowerRing.{u}) (t : ℕ)
    (δ : DividedPowers (dividedPowerPolynomialIdeal (A : Type u) A.ideal t)) : Prop :=
  ∀ {n : ℕ} {x : A}, x ∈ A.ideal →
    δ.dpow n (algebraMap (A : Type u) (dividedPowerPolynomialAlgebra (A : Type u) t) x) =
      algebraMap (A : Type u) (dividedPowerPolynomialAlgebra (A : Type u) t)
        (A.dividedPowers.dpow n x)

/-- The coefficient homomorphism once divided-power compatibility has been
specified. -/
def dividedPowerPolynomialCoefficientHom (A : DividedPowerRing.{u}) (t : ℕ)
    (δ : DividedPowers (dividedPowerPolynomialIdeal (A : Type u) A.ideal t))
    (hδ : CoefficientDpowCompatible A t δ) :
    DividedPowerRing.Hom A (dividedPowerPolynomialRing A t δ) :=
  { hom := algebraMap (A : Type u) (dividedPowerPolynomialAlgebra (A : Type u) t)
    ideal_map := by
      intro x hx
      exact Ideal.mem_sup_left (Ideal.mem_map_of_mem
        (algebraMap (A : Type u) (dividedPowerPolynomialAlgebra (A : Type u) t)) hx)
    dpow_comm := hδ }

/-- Data on the target of the universal property: a divided-power-ring map
from the coefficient ring and one element of the target ideal per variable. -/
def DividedPowerPolynomialTargetData (A C : DividedPowerRing.{u}) (t : ℕ) : Type u :=
  DividedPowerRing.Hom A C × { k : Fin t → C // ∀ i, k i ∈ C.ideal }

/-- The two conditions characterizing the divided-power structure in the
finite-variable construction. -/
def IsDividedPowerPolynomialStructure
    (A : DividedPowerRing.{u}) (t : ℕ)
    (δ : DividedPowers (dividedPowerPolynomialIdeal (A : Type u) A.ideal t)) :
    Prop :=
  CoefficientDpowCompatible A t δ ∧
    ∀ (i : Fin t) (n : ℕ),
      δ.dpow n (dividedPowerVariable t i 1) =
        dividedPowerVariable t i n

/-- The universal mapping property for the finite-variable structure. -/
def IsDividedPowerPolynomialUniversal
    (A : DividedPowerRing.{u}) (t : ℕ)
    (δ : DividedPowers (dividedPowerPolynomialIdeal (A : Type u) A.ideal t)) :
    Prop :=
  ∀ C : DividedPowerRing.{u},
    Nonempty ((dividedPowerPolynomialRing A t δ ⟶ C) ≃
      DividedPowerPolynomialTargetData A C t)

/-- The finite-variable divided-power polynomial algebra has the source's
existence and uniqueness statement. -/
theorem exists_unique_dividedPowerPolynomialDividedPowers
    (A : DividedPowerRing.{u}) (t : ℕ) (ht : 1 ≤ t) :
    ∃! δ : DividedPowers (dividedPowerPolynomialIdeal (A : Type u) A.ideal t),
      IsDividedPowerPolynomialStructure A t δ := by
  sorry

/-- The universal mapping property of the unique finite-variable structure. -/
theorem dividedPowerPolynomial_universal
    (A : DividedPowerRing.{u}) (t : ℕ) (ht : 1 ≤ t)
    (δ : DividedPowers (dividedPowerPolynomialIdeal (A : Type u) A.ideal t))
    (hδ : IsDividedPowerPolynomialStructure A t δ) :
    IsDividedPowerPolynomialUniversal A t δ := by
  sorry

/-! ## Infinitely many variables -/

/-- The divided power polynomial algebra on an arbitrary (same-universe) set
of variables. -/
abbrev infiniteDividedPowerPolynomialAlgebra (A : Type u) [CommRing A]
    (W : Type u) : Type u :=
  DividedPowerAlgebra A (W →₀ A)

/-- The variable `x_w^[n]` in the infinite-variable algebra. -/
def infiniteDividedPowerVariable {A : Type u} [CommRing A] (W : Type u)
    (w : W) (n : ℕ) : infiniteDividedPowerPolynomialAlgebra A W :=
  DividedPowerAlgebra.dp A n (Finsupp.single w 1)

/-- The augmentation for the infinitely generated divided-power polynomial
algebra. -/
noncomputable def infiniteDividedPowerAugmentation
    {A : Type u} [CommRing A] (W : Type u) :
    infiniteDividedPowerPolynomialAlgebra A W →ₐ[A] A :=
  DividedPowerAlgebra.lift (dividedPowersBot A)
    (0 : (W →₀ A) →ₗ[A] A) (by simp)

/-- The positive-degree ideal in the infinitely generated algebra. -/
def infiniteDividedPowerAugmentationIdeal
    {A : Type u} [CommRing A] (W : Type u) :
    Ideal (infiniteDividedPowerPolynomialAlgebra A W) :=
  RingHom.ker (infiniteDividedPowerAugmentation W).toRingHom

/-- The coefficient-plus-positive-degree ideal in the infinitely generated
divided-power polynomial algebra. -/
def infiniteDividedPowerPolynomialIdeal (A : Type u) [CommRing A]
    (I : Ideal A) (W : Type u) :
    Ideal (infiniteDividedPowerPolynomialAlgebra A W) :=
  Ideal.map (algebraMap A (infiniteDividedPowerPolynomialAlgebra A W)) I ⊔
    infiniteDividedPowerAugmentationIdeal W

/-- The infinitely generated polynomial algebra equipped with a specified
divided-power structure on its coefficient-plus-positive-degree ideal. -/
def infiniteDividedPowerPolynomialRing (A : DividedPowerRing.{u}) (W : Type u)
    (δ : DividedPowers
      (infiniteDividedPowerPolynomialIdeal (A : Type u) A.ideal W)) :
    DividedPowerRing.{u} :=
  { toCommRing := CommRingCat.of
      (infiniteDividedPowerPolynomialAlgebra (A : Type u) W)
    ideal := infiniteDividedPowerPolynomialIdeal (A : Type u) A.ideal W
    dividedPowers := δ }

/-- Compatibility of infinitely generated polynomial divided powers with the
coefficient ring. -/
def InfiniteCoefficientDpowCompatible (A : DividedPowerRing.{u}) (W : Type u)
    (δ : DividedPowers
      (infiniteDividedPowerPolynomialIdeal (A : Type u) A.ideal W)) : Prop :=
  ∀ {n : ℕ} {x : A}, x ∈ A.ideal →
    δ.dpow n
        (algebraMap (A : Type u)
          (infiniteDividedPowerPolynomialAlgebra (A : Type u) W) x) =
      algebraMap (A : Type u)
        (infiniteDividedPowerPolynomialAlgebra (A : Type u) W)
        (A.dividedPowers.dpow n x)

/-- Data on the target of the infinitely generated universal property. -/
def InfiniteDividedPowerPolynomialTargetData (A C : DividedPowerRing.{u})
    (W : Type u) : Type u :=
  DividedPowerRing.Hom A C × { k : W → C // ∀ w, k w ∈ C.ideal }

/-- The two conditions inherited by the infinitely generated divided-power
polynomial structure. -/
def IsInfiniteDividedPowerPolynomialStructure
    (A : DividedPowerRing.{u}) (W : Type u)
    (δ : DividedPowers
      (infiniteDividedPowerPolynomialIdeal (A : Type u) A.ideal W)) : Prop :=
  InfiniteCoefficientDpowCompatible A W δ ∧
    ∀ (w : W) (n : ℕ),
      δ.dpow n (infiniteDividedPowerVariable W w 1) =
        infiniteDividedPowerVariable W w n

/-- The infinitely generated structure has the analogous existence and
uniqueness statement. -/
theorem exists_unique_infiniteDividedPowerPolynomialDividedPowers
    (A : DividedPowerRing.{u}) (W : Type u) :
    ∃! δ : DividedPowers
        (infiniteDividedPowerPolynomialIdeal (A : Type u) A.ideal W),
      IsInfiniteDividedPowerPolynomialStructure A W δ := by
  sorry

/-- The infinitely generated divided-power polynomial algebra has the same
universal property as the finite-variable algebra. -/
def IsInfiniteDividedPowerPolynomialUniversal
    (A : DividedPowerRing.{u}) (W : Type u)
    (δ : DividedPowers
      (infiniteDividedPowerPolynomialIdeal (A : Type u) A.ideal W)) : Prop :=
  ∀ C : DividedPowerRing.{u},
    Nonempty ((infiniteDividedPowerPolynomialRing A W δ ⟶ C) ≃
      InfiniteDividedPowerPolynomialTargetData A C W)

theorem infiniteDividedPowerPolynomial_universal
    (A : DividedPowerRing.{u}) (W : Type u)
    (δ : DividedPowers
      (infiniteDividedPowerPolynomialIdeal (A : Type u) A.ideal W))
    (hδ : IsInfiniteDividedPowerPolynomialStructure A W δ) :
    IsInfiniteDividedPowerPolynomialUniversal A W δ := by
  sorry

/-- The linear map inserting `s` finite variables into `t` finite variables. -/
def finiteVariableModuleMap {A : Type u} [CommRing A] {s t : ℕ}
    (h : s ≤ t) : (Fin s →₀ A) →ₗ[A] (Fin t →₀ A) :=
  Finsupp.lmapDomain A A (Fin.castLE h)

/-- The canonical algebra map for an inclusion of finite variable sets. -/
def finiteVariableAlgebraMap {A : Type u} [CommRing A] {s t : ℕ}
    (h : s ≤ t) :
    dividedPowerPolynomialAlgebra A s →ₐ[A] dividedPowerPolynomialAlgebra A t :=
  DividedPowerAlgebra.map A (finiteVariableModuleMap h)

/-- The canonical map sends each source divided-power variable to the
corresponding target variable. -/
theorem finiteVariableAlgebraMap_variable {A : Type u} [CommRing A]
    {s t : ℕ} (h : s ≤ t) (i : Fin s) (n : ℕ) :
    finiteVariableAlgebraMap (A := A) h (dividedPowerVariable (A := A) s i n) =
      dividedPowerVariable (A := A) t (Fin.castLE h i) n := by
  simp [finiteVariableAlgebraMap, dividedPowerVariable,
    finiteVariableModuleMap]

/-- The module map associated to an inclusion of finite subsets of a variable
set. -/
def finiteSubsetVariableModuleMap {A : Type u} [CommRing A] {W : Type u}
    {E F : Finset W} (h : E ≤ F) : (E →₀ A) →ₗ[A] (F →₀ A) :=
  Finsupp.lmapDomain A A (fun x : E ↦ ⟨x, h x.property⟩)

/-- The canonical divided-power algebra map between finite subset stages. -/
def finiteSubsetVariableAlgebraMap {A : Type u} [CommRing A] {W : Type u}
    {E F : Finset W} (h : E ≤ F) :
    DividedPowerAlgebra A (E →₀ A) →ₐ[A] DividedPowerAlgebra A (F →₀ A) :=
  DividedPowerAlgebra.map A (finiteSubsetVariableModuleMap h)

/-- Objectwise identifications of a finite-variable diagram with the finite
stages from the source. -/
abbrev FiniteVariableStageEquivalences (A : DividedPowerRing.{u}) (W : Type u)
    (F : (Finset W) ⥤ CommRingCat.{u}) : Type u :=
  ∀ E : Finset W,
    F.obj E ≅ CommRingCat.of
      (DividedPowerAlgebra (A : Type u) (E →₀ (A : Type u)))

/-- The colimit assertion in the infinite-variable remark, stated with the
finite-variable stages and their canonical transition maps. -/
def IsFiniteVariableColimit (A : DividedPowerRing.{u}) (W : Type u)
    (B : Type u) [CommRing B] : Prop :=
  ∃ (F : (Finset W) ⥤ CommRingCat.{u}) (c : Cocone F),
    c.pt = CommRingCat.of B ∧
      (∃ e : FiniteVariableStageEquivalences A W F,
        (∀ {E G : Finset W} (h : E ≤ G),
          (e E).hom ≫
              CommRingCat.ofHom (finiteSubsetVariableAlgebraMap h).toRingHom =
            F.map h.hom ≫ (e G).hom) ∧
      Nonempty (IsColimit c))

/-- The infinite-variable algebra is the colimit of its finite-variable
subalgebras, as asserted in the source. -/
theorem infiniteDividedPowerPolynomial_isFiniteVariableColimit
    (A : DividedPowerRing.{u}) (W : Type u) :
    IsFiniteVariableColimit A W (infiniteDividedPowerPolynomialAlgebra (A : Type u) W) := by
  sorry

/-! ## Detection of divided powers at a prime -/

/-- Every factorial below a prime is a unit in a `Z_(p)`-algebra. -/
theorem factorial_isUnit_of_lt_prime
    (p : ℕ) (hp : Nat.Prime p) {A : Type u} [CommRing A]
    (hA : IsZLocalizedAtPrime p A) {n : ℕ} (hn : n < p) :
    IsUnit (Nat.factorial n : A) := by
  sorry

/-- The inverse of a unit, viewed back in the ring. -/
noncomputable def localizedUnitInverse {A : Type u} [CommRing A]
    {a : A} (ha : IsUnit a) : A :=
  (↑(ha.unit⁻¹) : A)

/-- The canonical inverse of a factorial below a fixed prime. -/
noncomputable def primeLocalizedFactorialInverse
    (p : ℕ) (hp : Nat.Prime p) {A : Type u} [CommRing A]
    (hA : IsZLocalizedAtPrime p A) (n : ℕ) : A :=
  if hn : n < p then
    localizedUnitInverse (factorial_isUnit_of_lt_prime p hp hA hn)
  else 0

/-- The divided-power operation on the ideal itself, for a positive index. -/
def dividedPowerOnIdeal {A : Type u} [CommRing A] {I : Ideal A}
    (γ : DividedPowers I) (n : ℕ) (hn : n ≠ 0) : I → I :=
  fun x ↦ ⟨γ.dpow n x, γ.dpow_mem hn x.property⟩

/-- The source's prime-local coefficient in the addition formula. -/
noncomputable def primeDividedPowerCrossTerm {A : Type u} [CommRing A]
    (p : ℕ) (hp : Nat.Prime p) (hA : IsZLocalizedAtPrime p A)
    (x y : A) : A := by
  classical
  exact (Finset.antidiagonal p).filter
      (fun k ↦ k.1 ≠ 0 ∧ k.2 ≠ 0) |>.sum
    (fun k ↦ (primeLocalizedFactorialInverse p hp hA k.1 *
      primeLocalizedFactorialInverse p hp hA k.2) *
      x ^ k.1 * y ^ k.2)

/-- An operation on an ideal with the three conditions in the prime-local
criterion. -/
structure PrimeDividedPowerOperation {A : Type u} [CommRing A]
    (p : ℕ) (I : Ideal A) where
  op : A → A
  op_mem : ∀ {x : A}, x ∈ I → op x ∈ I

/-- The three source conditions for a prime-local divided-power operation. -/
def IsPrimeDividedPowerOperation {A : Type u} [CommRing A]
    (p : ℕ) (hp : Nat.Prime p) (hA : IsZLocalizedAtPrime p A)
    (I : Ideal A) (δ : PrimeDividedPowerOperation p I) : Prop :=
  (∀ {x : A}, x ∈ I →
    (Nat.factorial p : A) * δ.op x = x ^ p) ∧
  (∀ (a : A) {x : A}, x ∈ I →
    δ.op (a * x) = a ^ p * δ.op x) ∧
  (∀ {x y : A}, x ∈ I → y ∈ I →
    δ.op (x + y) = δ.op x + primeDividedPowerCrossTerm p hp hA x y + δ.op y)

/-- The prime-local criterion determines a divided-power structure from its
`p`-th operation. -/
theorem dividedPowers_eq_iff_prime_operation_eq
    (p : ℕ) (hp : Nat.Prime p) {A : Type u} [CommRing A]
    (hA : IsZLocalizedAtPrime p A) {I : Ideal A}
    (γ γ' : DividedPowers I) :
    γ = γ' ↔
      dividedPowerOnIdeal γ p hp.ne_zero = dividedPowerOnIdeal γ' p hp.ne_zero := by
  sorry

/-- Existence and uniqueness of divided powers from an operation satisfying
the three prime-local conditions. -/
theorem exists_unique_dividedPowers_of_prime_operation
    (p : ℕ) (hp : Nat.Prime p) {A : Type u} [CommRing A]
    (hA : IsZLocalizedAtPrime p A) {I : Ideal A}
    (δ : PrimeDividedPowerOperation p I)
    (hδ : IsPrimeDividedPowerOperation p hp hA I δ) :
    ∃! γ : DividedPowers I,
      dividedPowerOnIdeal γ p hp.ne_zero =
        (fun x ↦ ⟨δ.op x, δ.op_mem x.property⟩) := by
  sorry

/-! ## The Ryo--Suzuki observation -/

/-- The second and third conditions in the prime-local criterion. -/
def IsPrimeDividedPowerOperationWithoutPower {A : Type u} [CommRing A]
    (p : ℕ) (hp : Nat.Prime p) (hA : IsZLocalizedAtPrime p A)
    (I : Ideal A) (δ : PrimeDividedPowerOperation p I) : Prop :=
  (∀ (a : A) {x : A}, x ∈ I →
    δ.op (a * x) = a ^ p * δ.op x) ∧
  (∀ {x y : A}, x ∈ I → y ∈ I →
    δ.op (x + y) = δ.op x + primeDividedPowerCrossTerm p hp hA x y + δ.op y)

/-- Scalar homogeneity, one of the two assumptions used in the follow-up
remark. -/
theorem primeOperation_nat_smul
    {p : ℕ} (hp : Nat.Prime p) {A : Type u} [CommRing A]
    (hA : IsZLocalizedAtPrime p A) {I : Ideal A}
    {δ : PrimeDividedPowerOperation p I}
    (hδ : IsPrimeDividedPowerOperationWithoutPower p hp hA I δ)
    (n : ℕ) {x : A} (hx : x ∈ I) :
    δ.op (n • x) = n ^ p • δ.op x := by
  simpa [nsmul_eq_mul] using hδ.1 (n : A) hx

/-- The integer-multiple identity displayed in the proof of the follow-up
remark. -/
theorem primeOperation_nat_multiple_formula
    (p : ℕ) (hp : Nat.Prime p) {A : Type u} [CommRing A]
    (hA : IsZLocalizedAtPrime p A) {I : Ideal A}
    (δ : PrimeDividedPowerOperation p I)
    (hδ : IsPrimeDividedPowerOperationWithoutPower p hp hA I δ)
    (n : ℕ) (hn : 1 ≤ n) {x : A} (hx : x ∈ I) :
    δ.op (n • x) = n • δ.op x +
      ((Nat.div (n ^ p - n) (Nat.factorial p) : A) * x ^ p) := by
  sorry

/-- For a prime `p`, some integer fails the congruence `n^p = n mod p^2`. -/
theorem exists_nat_not_primeSquare_dvd_pow_sub_self
    (p : ℕ) (hp : Nat.Prime p) :
    ∃ n : ℕ, ¬ p ^ 2 ∣ n ^ p - n := by
  sorry

/-- The cyclic-unit-group fact used in the number-theoretic argument of the
follow-up remark. -/
theorem units_mod_primeSquare_additive_cyclic
    (p : ℕ) (hp : Nat.Prime p) :
    Nonempty ((ZMod (p ^ 2))ˣ ≃*
      Multiplicative (ZMod (p * (p - 1)))) := by
  sorry

/-- The first condition of the prime-local criterion follows from the other
two conditions. -/
theorem primeOperation_power_formula
    (p : ℕ) (hp : Nat.Prime p) {A : Type u} [CommRing A]
    (hA : IsZLocalizedAtPrime p A) {I : Ideal A}
    (δ : PrimeDividedPowerOperation p I)
    (hδ : IsPrimeDividedPowerOperationWithoutPower p hp hA I δ) :
    ∀ {x : A}, x ∈ I →
      (Nat.factorial p : A) * δ.op x = x ^ p := by
  sorry

end

end Formalization.Books.Dpa.Unit05
