import Mathlib.Data.Complex.Basic
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Spectrum.Prime.Basic

import Formalization.Books.Exercises.Unit21.Core

/-!
# Exercises, Chapter 61: Making primes

The family `y - x^(n+1)` gives explicit prime hypersurface ideals in
`ℂ[x,y]`.  Every member contains both specified points in its vanishing set.
The proofs of primality and infinitude are deferred, but the family and all
of its source-facing properties are present in the interface.
-/

namespace Formalization.Books.Exercises.Unit61

open Set
open Formalization.Books.Exercises.Unit21

universe u

noncomputable section

/-- The equation `y - x^(n+1)` in the complex affine plane. -/
def makingPrimeEquation (n : ℕ) : twoVariablePolynomialRing ℂ :=
  MvPolynomial.X (1 : Fin 2) - MvPolynomial.X (0 : Fin 2) ^ (n + 1)

/-- The principal ideal generated by `y - x^(n+1)`. -/
def makingPrimeIdeal (n : ℕ) : Ideal (twoVariablePolynomialRing ℂ) :=
  Ideal.span {makingPrimeEquation n}

/-- Each member of the explicit family is prime. -/
theorem makingPrimeIdeal_isPrime (n : ℕ) :
    (makingPrimeIdeal n).IsPrime := by
  sorry

/-- Each explicit prime is contained in the origin point ideal, equivalently
the origin lies in its vanishing set. -/
theorem makingPrimeIdeal_le_origin :
    ∀ n, makingPrimeIdeal n ≤ twoVariablePointIdeal ℂ 0 0 := by
  sorry

/-- Each explicit prime is contained in the point ideal at `(1,1)`. -/
theorem makingPrimeIdeal_le_one_one :
    ∀ n, makingPrimeIdeal n ≤ twoVariablePointIdeal ℂ 1 1 := by
  sorry

/-- Different exponents give different principal prime ideals. -/
theorem makingPrimeIdeal_injective :
    Function.Injective makingPrimeIdeal := by
  sorry

/-- The family of explicit prime ideals is infinite. -/
theorem makingPrimeIdeal_range_infinite :
    Set.Infinite (Set.range makingPrimeIdeal) := by
  sorry

/-- There are infinitely many distinct prime ideals whose vanishing sets
contain both `(0,0)` and `(1,1)`. -/
theorem infinitely_many_prime_ideals_through_two_points :
    Set.Infinite
      {p : Ideal (twoVariablePolynomialRing ℂ) |
        p.IsPrime ∧
          p ≤ twoVariablePointIdeal ℂ 0 0 ∧
          p ≤ twoVariablePointIdeal ℂ 1 1} := by
  sorry

end

end Formalization.Books.Exercises.Unit61
