import Mathlib.Algebra.Homology.ShortComplex.ShortExact
import Mathlib.CategoryTheory.Abelian.Subobject
import Mathlib.CategoryTheory.Noetherian
import Mathlib.CategoryTheory.RegularCategory.Basic
import Mathlib.Order.JordanHolder
import Mathlib.Order.RelSeries

/-!
# Homological Algebra, Chapter 9: Jordan-Hölder

The source's notions of simple objects, Artinian objects, and Noetherian objects
are represented by Mathlib's `Simple`, `IsArtinianObject`, and
`IsNoetherianObject`.  The remaining interfaces below record the source's
finite filtrations and Jordan-Hölder statement for abelian categories.
-/

noncomputable section

open CategoryTheory
open CategoryTheory.Limits

universe v u

namespace Formalization.Books.Homology.Unit09

/-! ## Simple, Artinian, and Noetherian objects and categories -/

/- The source's definition of a simple object is Mathlib's `CategoryTheory.Simple`.
   In an abelian category, `CategoryTheory.simple_iff_subobject_isSimpleOrder`
   identifies it with the source formulation that the only subobjects are zero
   and the whole object; the nonzero clause is built into `Simple`. -/

/- Mathlib's `IsArtinianObject` and `IsNoetherianObject` are the source's
   descending and ascending chain conditions on subobjects. -/

/- Mathlib's `CategoryTheory.Artinian` and `CategoryTheory.Noetherian` also
   require essential smallness.  The source only says that every object has
   the corresponding chain condition, so these predicates retain exactly the
   source's hypothesis. -/

def IsArtinianCategory (C : Type u) [Category.{v} C] : Prop :=
  ∀ X : C, IsArtinianObject X

def IsNoetherianCategory (C : Type u) [Category.{v} C] : Prop :=
  ∀ X : C, IsNoetherianObject X

/-! ## Local bridges for short exact sequences and Jordan-Hölder lattices -/

/- The abelian subobject lattice is modular.  This is the categorical
   counterpart of the modular law behind the second (diamond) isomorphism;
   Mathlib's `JordanHolderLattice` instance is then available for
   `Subobject A`. -/
instance subobject_isModularLattice
    {C : Type u} [Category.{v} C] [Abelian C] (A : C) :
    IsModularLattice (Subobject A) := by
  sorry

/- The two quotient-closure interfaces are kept separate from the
   short-exact equivalences below.  This lets their users reuse the
   categorical quotient argument without duplicating a chain-condition proof. -/
theorem isArtinianObject_of_shortExact_quotient
    {C : Type u} [Category.{v} C] [Abelian C]
    (S : ShortComplex C) (hS : S.ShortExact)
    (h₂ : IsArtinianObject S.X₂) :
    IsArtinianObject S.X₃ := by
  sorry

theorem isNoetherianObject_of_shortExact_quotient
    {C : Type u} [Category.{v} C] [Abelian C]
    (S : ShortComplex C) (hS : S.ShortExact)
    (h₂ : IsNoetherianObject S.X₂) :
    IsNoetherianObject S.X₃ := by
  sorry

/- These are the checked subobject halves of the same two interfaces.  In
   particular, retain `hS.mono_f` as the explicit monomorphism argument to
   Mathlib's subobject chain-condition lemmas. -/
theorem isArtinianObject_of_shortExact_subobject
    {C : Type u} [Category.{v} C] [Abelian C]
    (S : ShortComplex C) (hS : S.ShortExact)
    (h₂ : IsArtinianObject S.X₂) :
    IsArtinianObject S.X₁ := by
  letI : IsArtinianObject S.X₂ := h₂
  letI : Mono S.f := hS.mono_f
  exact isArtinianObject_of_mono S.f

theorem isNoetherianObject_of_shortExact_subobject
    {C : Type u} [Category.{v} C] [Abelian C]
    (S : ShortComplex C) (hS : S.ShortExact)
    (h₂ : IsNoetherianObject S.X₂) :
    IsNoetherianObject S.X₁ := by
  letI : IsNoetherianObject S.X₂ := h₂
  letI : Mono S.f := hS.mono_f
  exact isNoetherianObject_of_mono S.f

/-! ## Stability under short exact sequences -/

theorem isArtinianObject_iff_of_shortExact
    {C : Type u} [Category.{v} C] [Abelian C]
    (S : ShortComplex C) (hS : S.ShortExact) :
    IsArtinianObject S.X₂ ↔
      IsArtinianObject S.X₁ ∧ IsArtinianObject S.X₃ := by
  sorry

theorem isNoetherianObject_iff_of_shortExact
    {C : Type u} [Category.{v} C] [Abelian C]
    (S : ShortComplex C) (hS : S.ShortExact) :
    IsNoetherianObject S.X₂ ↔
      IsNoetherianObject S.X₁ ∧ IsNoetherianObject S.X₃ := by
  sorry

/-! ## Finite-length filtrations -/

noncomputable def subobjectQuotient
    {C : Type u} [Category.{v} C] [Abelian C] {A : C}
    (P Q : Subobject A) (h : P ≤ Q) : C :=
  cokernel (Subobject.ofLE P Q h)

/- A simple categorical quotient is exactly a cover in the subobject
   lattice.  This is the relation conversion required by
   `CompositionSeries`. -/
theorem simple_subobjectQuotient_iff_covBy
    {C : Type u} [Category.{v} C] [Abelian C] {A : C}
    {P Q : Subobject A} (hPQ : P ≤ Q) :
    Simple (subobjectQuotient P Q hPQ) ↔ P ⋖ Q := by
  sorry

/- The diamond relation generated by Mathlib's `JordanHolderLattice` is
   interpreted as an isomorphism of the corresponding categorical
   subobject quotients. -/
theorem jordanHolderLattice_iso_subobjectQuotient
    {C : Type u} [Category.{v} C] [Abelian C] {A : C}
    {P Q R T : Subobject A} (hPQ : P ≤ Q) (hRT : R ≤ T)
    (h : JordanHolderLattice.Iso (P, Q) (R, T)) :
    Nonempty (subobjectQuotient P Q hPQ ≅ subobjectQuotient R T hRT) := by
  sorry

structure FiniteLengthFiltration
    {C : Type u} [Category.{v} C] [Abelian C] (A : C) where
  series : RelSeries {(P, Q) : (Subobject A) × (Subobject A) | P < Q}
  head_eq_bot : series.head = ⊥
  last_eq_top : series.last = ⊤
  simple_factor :
    ∀ i : Fin series.length,
      Simple (subobjectQuotient (series (Fin.castSucc i)) (series i.succ)
        (le_of_lt (by simpa using series.step i)))

namespace FiniteLengthFiltration

variable {C : Type u} [Category.{v} C] [Abelian C] {A : C}

noncomputable def factor (F : FiniteLengthFiltration A) (i : Fin F.series.length) : C :=
  subobjectQuotient (F.series (Fin.castSucc i)) (F.series i.succ)
    (le_of_lt (by simpa using F.series.step i))

/- Reinterpret a finite-length filtration as the composition series whose
   adjacent relation is `CovBy`; the relation is supplied by the preceding
   simple-quotient bridge. -/
noncomputable def toCompositionSeries (F : FiniteLengthFiltration A) :
    CompositionSeries (Subobject A) where
  length := F.series.length
  toFun := F.series
  step := fun i =>
    (simple_subobjectQuotient_iff_covBy
      (le_of_lt (by simpa using F.series.step i))).mp (F.simple_factor i)

end FiniteLengthFiltration

theorem finite_length_iff
    {C : Type u} [Category.{v} C] [Abelian C] (A : C) :
    IsArtinianObject A ∧ IsNoetherianObject A ↔
      Nonempty (FiniteLengthFiltration A) := by
  sorry

/-! ## Jordan-Hölder uniqueness -/

theorem jordan_holder
    {C : Type u} [Category.{v} C] [Abelian C] {A : C}
    (_hA : IsArtinianObject A ∧ IsNoetherianObject A)
    (F G : FiniteLengthFiltration A) :
    F.series.length = G.series.length ∧
      ∃ σ : Fin F.series.length ≃ Fin G.series.length,
        ∀ i, Nonempty (F.factor i ≅ G.factor (σ i)) := by
  sorry

end Formalization.Books.Homology.Unit09
