import Formalization.Books.Algebra.Unit37.NormalRings
import Formalization.Books.Algebra.Unit36.FiniteIntegralRingExtensions
import Formalization.Books.Algebra.Unit78.FiniteProjectiveModules
import Mathlib.RingTheory.DedekindDomain.Basic
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.Ideal.UFD
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Polynomial.UniqueFactorization
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.UniqueFactorizationDomain.GCDMonoid

/-!
# Commutative Algebra, Chapter 120: Factorization

The standard element notions in this section use Mathlib's canonical
`Associated`, `Irreducible`, and `Prime` predicates.  A unique factorization
domain is represented by `IsDomain R` together with
`UniqueFactorizationMonoid R`; a principal ideal domain is represented by
`IsDomain R` together with `IsPrincipalIdealRing R`.  Dedekind domains use
Mathlib's `IsDedekindDomain` class.
-/

namespace Formalization.Books.Algebra.Unit120

open Set
open scoped Polynomial BigOperators

universe u v

noncomputable section

/-! ## Associates, irreducibles, primes, and existence of factorization -/

/- The source's definition of associates is exactly `Associated`; the
   following theorem exposes its principal-ideal formulation. -/
theorem associated_iff_equal_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R] (x y : R) :
    Associated x y ↔
      Ideal.span ({x} : Set R) = Ideal.span ({y} : Set R) := by
  exact Ideal.span_singleton_eq_span_singleton.symm

/- The source's phrase “has a factorization into irreducibles” is recorded
   with a finite multiset, which retains the finite product and permutation
   content of the displayed list. -/
def HasIrreducibleFactorizations
    (R : Type u) [CommRing R] : Prop :=
  ∀ a : R, a ≠ 0 → ¬ IsUnit a →
    ∃ f : Multiset R,
      (∀ b ∈ f, Irreducible b) ∧ f.prod = a ∧ f ≠ 0

theorem factorization_exists_of_acc_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R] [WfDvdMonoid R]
    {a : R} (ha : a ≠ 0) (haunit : ¬ IsUnit a) :
    ∃ f : Multiset R,
      (∀ b ∈ f, Irreducible b) ∧ f.prod = a ∧ f ≠ 0 := by
  exact (WfDvdMonoid.not_isUnit_iff_exists_factors_eq a ha).mp haunit

/- The source defines primality by the ideal `Ideal.span {x}` being prime.
   For the nonzero elements used in the factorization arguments, this agrees
   with Mathlib's canonical `Prime x`. -/
theorem prime_iff_principal_ideal_isPrime
    {R : Type u} [CommRing R] [IsDomain R] {x : R} (hx : x ≠ 0) :
    Prime x ↔ (Ideal.span ({x} : Set R)).IsPrime := by
  exact (Ideal.span_singleton_prime hx).symm

theorem ufd_iff_irreducibles_are_prime
    {R : Type u} [CommRing R] [IsDomain R]
    (hfactor : HasIrreducibleFactorizations R) :
    UniqueFactorizationMonoid R ↔
      ∀ x : R, Irreducible x → Prime x := by
  constructor
  · intro hU x hx
    exact hU.irreducible_iff_prime.mp hx
  · intro hprime
    apply UniqueFactorizationMonoid.of_exists_prime_factors
    intro a ha
    by_cases hau : IsUnit a
    · refine ⟨0, ?_, ?_⟩
      · simp
      · simpa using (associated_one_iff_isUnit.mpr hau).symm
    · obtain ⟨f, hf, hfa, _⟩ := hfactor a ha hau
      refine ⟨f, fun b hb => hprime b (hf b hb), ?_⟩
      exact Associated.of_eq hfa

private theorem has_irreducible_factorizations_of_ufd
    {R : Type u} [CommRing R] [IsDomain R] [UniqueFactorizationMonoid R] :
    HasIrreducibleFactorizations R := by
  intro a ha haunit
  exact factorization_exists_of_acc_principal_ideals ha haunit

private theorem localization_ufd_of_ufd
    {R : Type u} [CommRing R] [IsDomain R] [UniqueFactorizationMonoid R]
    (S : Submonoid R) [IsDomain (Localization S)] :
    UniqueFactorizationMonoid (Localization S) := by
  infer_instance

private theorem irreducible_is_prime_of_ufd
    {R : Type u} [CommRing R] [IsDomain R] [UniqueFactorizationMonoid R]
    {x : R} (hx : Irreducible x) : Prime x :=
  UniqueFactorizationMonoid.irreducible_iff_prime.mp hx

/-! ## Criteria for unique factorization -/

theorem ufd_iff_height_one_prime_ideals_principal
    {R : Type u} [CommRing R] [IsDomain R] [IsNoetherianRing R] :
    UniqueFactorizationMonoid R ↔
      ∀ (p : Ideal R) [p.IsPrime], p.height = 1 → p.IsPrincipal := by
  exact UniqueFactorizationMonoid.iff_forall_isPrincipal_of_height_eq_one

/- A multiplicative subset generated by prime elements is represented by the
   submonoid closure of a set of prime elements. -/
def IsGeneratedByPrimeElements
    {A : Type u} [CommRing A] (S : Submonoid A) : Prop :=
  ∃ T : Set A, (∀ p ∈ T, Prime p) ∧ Submonoid.closure T = S

theorem nagata_irreducible_or_unit
    {A : Type u} [CommRing A] [IsDomain A]
    (S : Submonoid A) (hS : IsGeneratedByPrimeElements S)
    {x : A} (hx : Irreducible x) :
    Irreducible (algebraMap A (Localization S) x) ∨
      IsUnit (algebraMap A (Localization S) x) := by
  rcases hS with ⟨T, hT, hTS⟩
  by_cases hzero : (0 : A) ∈ S
  · have hz : IsUnit (0 : Localization S) := by
      rw [← map_zero (algebraMap A (Localization S))]
      exact IsLocalization.map_units (R := A) (S := Localization S) (M := S)
        ⟨0, hzero⟩
    exact Or.inr
      (@isUnit_of_subsingleton (Localization S) _
        (subsingleton_of_zero_eq_one (isUnit_zero_iff.mp hz)) _)
  · have hinj : Function.Injective (algebraMap A (Localization S)) := by
      intro a b hab
      obtain ⟨c, hc⟩ :=
        (IsLocalization.eq_iff_exists (M := S) (S := Localization S)).mp hab
      apply mul_left_cancel₀
      · intro hc0
        exact hzero (hc0 ▸ c.property)
      · exact hc
    have hmem : ∀ d : S, ∃ f : Multiset A,
        (∀ p ∈ f, p ∈ T) ∧ f.prod = (d : A) := by
      intro d
      apply Submonoid.exists_multiset_of_mem_closure
      exact hTS ▸ d.property
    have hstrip : ∀ (f : Multiset A),
        (∀ p ∈ f, Prime p) → (∀ p ∈ f, p ∈ S) →
          ∀ a b : A, f.prod * x = a * b →
            ∃ a' b' s t : A, s ∈ S ∧ t ∈ S ∧
              a = s * a' ∧ b = t * b' ∧ x = a' * b' := by
      intro f hf hfs
      induction f using Multiset.induction_on with
      | empty =>
          intro a b hab
          refine ⟨a, b, 1, 1, Submonoid.one_mem _, Submonoid.one_mem _, by simp,
            by simp, ?_⟩
          simpa using hab
      | @cons p f ih =>
          intro a b hab
          have hpab : p ∣ a * b := by
            rw [← hab, Multiset.prod_cons]
            exact ⟨f.prod * x, by simp [mul_assoc]⟩
          rcases (hf p (Multiset.mem_cons_self _ _)).dvd_or_dvd hpab with hpa | hpb
          · obtain ⟨a₁, ha₁⟩ := hpa
            have htail : f.prod * x = a₁ * b := by
              apply mul_left_cancel₀ (hf p (Multiset.mem_cons_self _ _)).ne_zero
              calc
                p * (f.prod * x) = (p * f.prod) * x := by rw [mul_assoc]
                _ = a * b := by simpa [Multiset.prod_cons] using hab
                _ = (p * a₁) * b := by rw [ha₁]
                _ = p * (a₁ * b) := by rw [mul_assoc]
            obtain ⟨a', b', s, t, hs, ht, ha', hb', hx'⟩ :=
              ih (fun q hq => hf q (by simp [hq]))
                (fun q hq => hfs q (by simp [hq])) a₁ b htail
            refine ⟨a', b', p * s, t, S.mul_mem
              (hfs p (Multiset.mem_cons_self _ _)) hs, ht, ?_, hb', hx'⟩
            calc
              a = p * a₁ := ha₁
              _ = p * (s * a') := by rw [ha']
              _ = (p * s) * a' := by rw [mul_assoc]
          · obtain ⟨b₁, hb₁⟩ := hpb
            have htail : f.prod * x = a * b₁ := by
              apply mul_left_cancel₀ (hf p (Multiset.mem_cons_self _ _)).ne_zero
              calc
                p * (f.prod * x) = (p * f.prod) * x := by rw [mul_assoc]
                _ = a * b := by simpa [Multiset.prod_cons] using hab
                _ = a * (p * b₁) := by rw [hb₁]
                _ = p * (a * b₁) := by rw [mul_comm, mul_assoc, mul_comm a]
            obtain ⟨a', b', s, t, hs, ht, ha', hb', hx'⟩ :=
              ih (fun q hq => hf q (by simp [hq]))
                (fun q hq => hfs q (by simp [hq])) a b₁ htail
            refine ⟨a', b', s, p * t, hs, S.mul_mem
              (hfs p (Multiset.mem_cons_self _ _)) ht,
              ha', ?_, hx'⟩
            calc
              b = p * b₁ := hb₁
              _ = p * (t * b') := by rw [hb']
              _ = (p * t) * b' := by rw [mul_assoc]
    by_cases hunit : IsUnit (algebraMap A (Localization S) x)
    · exact Or.inr hunit
    · left
      refine ⟨hunit, ?_⟩
      intro y z hxyz
      obtain ⟨a, b, d, ha, hb⟩ := IsLocalization.surj₂ S (Localization S) y z
      obtain ⟨f, hfT, hfd⟩ := hmem d
      have heq : (d : A) * (d : A) * x = a * b := by
        apply hinj
        calc
          algebraMap A (Localization S) ((d : A) * (d : A) * x) =
              (algebraMap A (Localization S) d * y) *
                (algebraMap A (Localization S) d * z) := by
                  simp only [map_mul]
                  rw [hxyz]
                  ac_rfl
          _ = algebraMap A (Localization S) a *
                algebraMap A (Localization S) b := by
                  rw [show algebraMap A (Localization S) d * y =
                    algebraMap A (Localization S) a by simpa [mul_comm] using ha]
                  rw [show algebraMap A (Localization S) d * z =
                    algebraMap A (Localization S) b by simpa [mul_comm] using hb]
          _ = algebraMap A (Localization S) (a * b) := by rw [map_mul]
      have hfp : ∀ p ∈ f + f, Prime p := by
        intro p hp
        rw [Multiset.mem_add] at hp
        rcases hp with hp | hp
        · exact hT p (hfT p hp)
        · exact hT p (hfT p hp)
      have hfs : ∀ p ∈ f + f, p ∈ S := by
        intro p hp
        rw [Multiset.mem_add] at hp
        rcases hp with hp | hp
        · rw [← hTS]
          exact Submonoid.subset_closure (hfT p hp)
        · rw [← hTS]
          exact Submonoid.subset_closure (hfT p hp)
      obtain ⟨a', b', s, t, hs, ht, ha', hb', hx'⟩ := hstrip (f + f) hfp hfs a b (by
        rw [Multiset.prod_add, hfd]
        exact heq)
      rcases hx.isUnit_or_isUnit hx' with haunit | hbunit
      · left
        have hu : IsUnit (algebraMap A (Localization S) a) := by
          rw [ha', map_mul]
          exact IsUnit.mul
            (IsLocalization.map_units (R := A) (S := Localization S) (M := S) ⟨s, hs⟩)
            (IsUnit.map (algebraMap A (Localization S)) haunit)
        exact isUnit_of_mul_isUnit_left (ha ▸ hu)
      · right
        have hu : IsUnit (algebraMap A (Localization S) b) := by
          rw [hb', map_mul]
          exact IsUnit.mul
            (IsLocalization.map_units (R := A) (S := Localization S) (M := S) ⟨t, ht⟩)
            (IsUnit.map (algebraMap A (Localization S)) hbunit)
        exact isUnit_of_mul_isUnit_left (hb ▸ hu)

theorem nagata_prime_iff_prime_or_unit
    {A : Type u} [CommRing A] [IsDomain A]
    (S : Submonoid A) (hS : IsGeneratedByPrimeElements S)
    {x : A} (hx : Irreducible x) :
    Prime x ↔
      Prime (algebraMap A (Localization S) x) ∨
        IsUnit (algebraMap A (Localization S) x) := by
  rcases hS with ⟨T, hT, hTS⟩
  have hzero : (0 : A) ∉ S := by
    intro h0
    let N : Submonoid A :=
      { carrier := {a | a ≠ 0}
        one_mem' := one_ne_zero
        mul_mem' := fun ha hb => mul_ne_zero ha hb }
    have hTN : T ⊆ N := fun p hp => hT p hp |>.ne_zero
    have hclosure : Submonoid.closure T ≤ N := Submonoid.closure_le.mpr hTN
    have : (0 : A) ∈ N := by
      exact hclosure (hTS.symm ▸ h0)
    exact (show (0 : A) ≠ 0 from this) rfl
  have hinj : Function.Injective (algebraMap A (Localization S)) := by
    intro a b hab
    obtain ⟨c, hc⟩ :=
      (IsLocalization.eq_iff_exists (M := S) (S := Localization S)).mp hab
    apply mul_left_cancel₀
    · intro hc0
      exact hzero (hc0 ▸ c.property)
    · exact hc
  have hmem : ∀ d : S, ∃ f : Multiset A,
      (∀ p ∈ f, p ∈ T) ∧ f.prod = (d : A) := by
    intro d
    apply Submonoid.exists_multiset_of_mem_closure
    exact hTS ▸ d.property
  constructor
  · intro hpx
    by_cases hunit : IsUnit (algebraMap A (Localization S) x)
    · exact Or.inr hunit
    · left
      apply Submonoid.LocalizationMap.map_prime
        (IsLocalization.toLocalizationMap S (Localization S)) hpx
      · intro hx0
        apply hx.ne_zero
        apply hinj
        change algebraMap A (Localization S) x = 0 at hx0
        simpa only [map_zero] using hx0
      · exact hunit
  · intro hright
    rcases hright with hpx | hunit
    · have hpull : ∀ (f : Multiset A),
          (∀ p ∈ f, Prime p) → (∀ p ∈ f, p ∈ S) →
            ∀ a y : A, f.prod * a = x * y → x ∣ a := by
        intro f hf hfs
        induction f using Multiset.induction_on with
        | empty =>
            intro a y hab
            exact ⟨y, by simpa using hab⟩
        | @cons p f ih =>
            intro a y hab
            have hpdiv : p ∣ x * y := by
              rw [← hab, Multiset.prod_cons]
              exact ⟨f.prod * a, by simp [mul_assoc]⟩
            rcases (hf p (Multiset.mem_cons_self _ _)).dvd_or_dvd hpdiv with
              hpx' | hpy
            · have hassoc : Associated p x :=
                ((hf p (Multiset.mem_cons_self _ _)).irreducible).associated_of_dvd hx hpx'
              have hmapassoc : Associated
                  (algebraMap A (Localization S) p)
                  (algebraMap A (Localization S) x) :=
                Associated.map (algebraMap A (Localization S)) hassoc
              have hmapunitp : IsUnit (algebraMap A (Localization S) p) :=
                IsLocalization.map_units (Localization S) ⟨p,
                  hfs p (Multiset.mem_cons_self _ _)⟩
              exact (hpx.not_isUnit (hmapassoc.isUnit hmapunitp)).elim
            · obtain ⟨y₁, hy₁⟩ := hpy
              have htail : f.prod * a = x * y₁ := by
                apply mul_left_cancel₀ (hf p (Multiset.mem_cons_self _ _)).ne_zero
                calc
                  p * (f.prod * a) = (p * f.prod) * a := by rw [mul_assoc]
                  _ = x * y := by simpa [Multiset.prod_cons] using hab
                  _ = x * (p * y₁) := by rw [hy₁]
                  _ = p * (x * y₁) := by rw [mul_comm, mul_assoc, mul_comm x]
              exact ih (fun q hq => hf q (by simp [hq]))
                (fun q hq => hfs q (by simp [hq])) a y₁ htail
      have hpull_of_dvd : ∀ {a : A},
          algebraMap A (Localization S) x ∣ algebraMap A (Localization S) a → x ∣ a := by
        intro a hdiv
        rcases hdiv with ⟨c, hc⟩
        obtain ⟨⟨y, d⟩, hcd⟩ := IsLocalization.surj S c
        have hcd' : c * algebraMap A (Localization S) d =
            algebraMap A (Localization S) y := by simpa using hcd
        have heq : a * (d : A) = x * y := by
          apply hinj
          calc
            algebraMap A (Localization S) (a * (d : A)) =
                algebraMap A (Localization S) a *
                  algebraMap A (Localization S) d := by rw [map_mul]
            _ = (algebraMap A (Localization S) x * c) *
                  algebraMap A (Localization S) d := by rw [hc]
            _ = algebraMap A (Localization S) x *
                  (c * algebraMap A (Localization S) d) := by rw [mul_assoc]
            _ = algebraMap A (Localization S) x *
                  algebraMap A (Localization S) y := by rw [hcd']
            _ = algebraMap A (Localization S) (x * y) := by rw [map_mul]
        obtain ⟨f, hfT, hfd⟩ := hmem d
        have hfP : ∀ p ∈ f, Prime p := fun p hp => hT p (hfT p hp)
        have hfS : ∀ p ∈ f, p ∈ S := by
          intro p hp
          rw [← hTS]
          exact Submonoid.subset_closure (hfT p hp)
        exact hpull f hfP hfS a y (by simpa [hfd, mul_comm] using heq)
      refine ⟨hx.ne_zero, hx.not_isUnit, ?_⟩
      intro a b hab
      have hmapdvd : algebraMap A (Localization S) x ∣
          algebraMap A (Localization S) a * algebraMap A (Localization S) b := by
        rcases hab with ⟨c, hc⟩
        refine ⟨algebraMap A (Localization S) c, ?_⟩
        simpa [map_mul] using congrArg (algebraMap A (Localization S)) hc
      rcases hpx.dvd_or_dvd hmapdvd with h | h
      · exact Or.inl (hpull_of_dvd h)
      · exact Or.inr (hpull_of_dvd h)
    · have hunit_inv : ∃ c : Localization S,
          algebraMap A (Localization S) x * c = 1 := hunit.exists_right_inv
      obtain ⟨c, hc⟩ := hunit_inv
      obtain ⟨⟨a, d⟩, hca⟩ := IsLocalization.surj S c
      have hca' : c * algebraMap A (Localization S) d =
          algebraMap A (Localization S) a := by simpa using hca
      have hxa : x * a = (d : A) := by
        apply hinj
        calc
          algebraMap A (Localization S) (x * a) =
              algebraMap A (Localization S) x *
                algebraMap A (Localization S) a := by rw [map_mul]
          _ = algebraMap A (Localization S) x *
                (c * algebraMap A (Localization S) d) := by rw [hca']
          _ = (algebraMap A (Localization S) x * c) *
                algebraMap A (Localization S) d := by rw [mul_assoc]
          _ = algebraMap A (Localization S) d := by rw [hc, one_mul]
      obtain ⟨f, hfT, hfd⟩ := hmem d
      have hprime_factor : ∀ (f : Multiset A),
          (∀ p ∈ f, Prime p) → ∀ y : A, f.prod = x * y → Prime x := by
        intro f hf
        induction f using Multiset.induction_on with
        | empty =>
            intro y hy
            exact (hx.not_isUnit (IsUnit.of_mul_eq_one y hy.symm)).elim
        | @cons p f ih =>
            intro y hy
            have hpdiv : p ∣ x * y := by
              rw [← hy, Multiset.prod_cons]
              exact ⟨f.prod, by simp⟩
            rcases (hf p (Multiset.mem_cons_self _ _)).dvd_or_dvd hpdiv with
              hpx' | hpy
            · have hassoc : Associated p x :=
                ((hf p (Multiset.mem_cons_self _ _)).irreducible).associated_of_dvd hx hpx'
              exact hassoc.prime (hf p (Multiset.mem_cons_self _ _))
            · obtain ⟨y₁, hy₁⟩ := hpy
              have htail : f.prod = x * y₁ := by
                apply mul_left_cancel₀ (hf p (Multiset.mem_cons_self _ _)).ne_zero
                calc
                  p * f.prod = (p * f.prod) := rfl
                  _ = x * y := by simpa [Multiset.prod_cons] using hy
                  _ = x * (p * y₁) := by rw [hy₁]
                  _ = p * (x * y₁) := by rw [mul_comm, mul_assoc, mul_comm x]
              exact ih (fun q hq => hf q (by simp [hq])) y₁ htail
      apply hprime_factor f (fun p hp => hT p (hfT p hp)) a
      exact hfd.trans hxa.symm

theorem nagata_factorization_criterion
    {A : Type u} [CommRing A] [IsDomain A]
    (S : Submonoid A) (hS : IsGeneratedByPrimeElements S) :
    UniqueFactorizationMonoid A ↔
      HasIrreducibleFactorizations A ∧
        IsDomain (Localization S) ∧
          UniqueFactorizationMonoid (Localization S) := by
  rcases hS with ⟨T, hT, hTS⟩
  have hzero : (0 : A) ∉ S := by
    intro h0
    let N : Submonoid A :=
      { carrier := {a | a ≠ 0}
        one_mem' := one_ne_zero
        mul_mem' := fun ha hb => mul_ne_zero ha hb }
    have hTN : T ⊆ N := fun p hp => hT p hp |>.ne_zero
    have hclosure : Submonoid.closure T ≤ N := Submonoid.closure_le.mpr hTN
    have : (0 : A) ∈ N := hclosure (hTS.symm ▸ h0)
    exact (show (0 : A) ≠ 0 from this) rfl
  have hLocDomain : IsDomain (Localization S) :=
    IsLocalization.isDomain_localization (le_nonZeroDivisors_of_noZeroDivisors hzero)
  constructor
  · intro hU
    have hfactor : HasIrreducibleFactorizations A :=
      @has_irreducible_factorizations_of_ufd A _ _ hU
    exact ⟨hfactor, hLocDomain,
      @localization_ufd_of_ufd A _ _ hU S hLocDomain⟩
  · rintro ⟨hfactor, hLocDomain', hUloc⟩
    apply (ufd_iff_irreducibles_are_prime hfactor).2
    intro x hx
    apply (nagata_prime_iff_prime_or_unit S (by exact ⟨T, hT, hTS⟩) hx).2
    rcases nagata_irreducible_or_unit S (by exact ⟨T, hT, hTS⟩) hx with hi | hu
    · exact Or.inl
        (@irreducible_is_prime_of_ufd (Localization S) _ hLocDomain' hUloc _ hi)
    · exact Or.inr hu

theorem ufd_has_acc_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R]
    [UniqueFactorizationMonoid R] :
    WfDvdMonoid R := by
  infer_instance

theorem polynomial_has_acc_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R] [WfDvdMonoid R] :
    WfDvdMonoid R[X] := by
  infer_instance

theorem polynomial_ring_over_ufd_is_ufd
    {R : Type u} [CommRing R] [IsDomain R]
    [UniqueFactorizationMonoid R] :
    UniqueFactorizationMonoid R[X] := by
  infer_instance

theorem multivariable_polynomial_ring_over_field_is_ufd
    (k : Type u) [Field k] (n : ℕ) :
    UniqueFactorizationMonoid (MvPolynomial (Fin n) k) := by
  infer_instance

theorem ufd_is_normal_domain
    {R : Type u} [CommRing R] [IsDomain R]
    [UniqueFactorizationMonoid R] :
    Formalization.Books.Algebra.Unit37.IsNormalDomain R := by
  exact ⟨inferInstance, inferInstance⟩

/-! ## Principal ideal and Dedekind domains -/

theorem principal_ideal_domain_is_ufd
    {R : Type u} [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R] :
    UniqueFactorizationMonoid R := by
  infer_instance

theorem principal_ideal_domain_is_dedekind
    {R : Type u} [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R] :
    IsDedekindDomain R := by
  infer_instance

private theorem finite_ideal_of_product_principal
    {A : Type u} [CommRing A]
    (I J : Ideal A) {f : A}
    (hprod : I * J = Ideal.span ({f} : Set A)) (hf : IsRegular f) :
    ∃ T : Finset A, (T : Set A) ⊆ I ∧
      I = Submodule.span A (T : Set A) := by
  classical
  have hfmem : f ∈ I * J := by
    rw [hprod]
    exact Ideal.mem_span_singleton_self f
  obtain ⟨T, T', hT, hT', hfspan⟩ :=
    Submodule.mem_span_mul_finite_of_mem_mul hfmem
  obtain ⟨U, hU, hfU⟩ := Submodule.mem_span_finite_of_mem_span hfspan
  have hqdata (q : A) (hq : q ∈ U) :
      ∃ t ∈ T, ∃ u ∈ T', t * u = q := by
    obtain ⟨t, ht, u, hu, htu⟩ := Set.mem_mul.mp (hU hq)
    exact ⟨t, ht, u, hu, htu⟩
  choose t ht u hu htu using hqdata
  obtain ⟨c, hc, hcf⟩ :=
    (Submodule.mem_span_finset (R := A) (s := U)).mp hfU
  have hcf' : ∑ q ∈ U, c q * q = f := by
    simpa [smul_eq_mul] using hcf
  let t0 : A → A := fun q => if hq : q ∈ U then t q hq else 0
  have hspan : I ≤ Submodule.span A (T : Set A) := by
    intro x hx
    have hxd (q : A) (hq : q ∈ U) :
        ∃ d : A, d * f = x * u q hq := by
      have hxu : x * u q hq ∈ I * J :=
        Ideal.mul_mem_mul hx (hT' (hu q hq))
      obtain ⟨d, hd⟩ := Ideal.mem_span_singleton'.mp (hprod ▸ hxu)
      exact ⟨d, hd⟩
    choose d hd using hxd
    let d0 : A → A := fun q => if hq : q ∈ U then d q hq else 0
    have hxf : x * f =
        (∑ q ∈ U, (c q * d0 q * t0 q)) * f := by
      calc
        x * f = x * (∑ q ∈ U, c q * q) := by rw [hcf']
        _ = ∑ q ∈ U, x * (c q * q) := by rw [Finset.mul_sum]
        _ = ∑ q ∈ U,
            (c q * d0 q * t0 q) * f := by
          apply Finset.sum_congr rfl
          intro q hq
          calc
            x * (c q * q) = c q * (x * q) := by ac_rfl
            _ = c q * (x * (t q hq * u q hq)) := by rw [htu q hq]
            _ = c q * (t q hq * (x * u q hq)) := by ac_rfl
            _ = c q * (t q hq * (d q hq * f)) := by rw [hd q hq]
            _ = (c q * d q hq * t q hq) * f := by ac_rfl
            _ = (c q * d0 q * t0 q) * f := by
              simp [d0, t0, hq]
        _ = (∑ q ∈ U,
            c q * d0 q * t0 q) * f := by
          rw [Finset.sum_mul]
    have hxsum : x =
        ∑ q ∈ U, c q * d0 q * t0 q :=
      hf.right hxf
    rw [hxsum]
    exact Submodule.sum_mem _ fun q hq => by
      simpa [smul_eq_mul, t0, hq] using
        (Submodule.smul_mem (Submodule.span A (T : Set A))
          (c q * d0 q) (Submodule.subset_span (ht q hq)))
  refine ⟨T, hT, le_antisymm hspan (Submodule.span_le.mpr hT)⟩

private theorem product_coefficients_span_top
    {A : Type u} [CommRing A]
    (I J : Ideal A) {f : A}
    (hprod : I * J = Ideal.span ({f} : Set A)) (hf : IsRegular f) :
    Ideal.span {a : A | ∃ x ∈ I, ∃ y ∈ J, x * y = a * f} = ⊤ := by
  classical
  have hfmem : f ∈ I * J := by
    rw [hprod]
    exact Ideal.mem_span_singleton_self f
  obtain ⟨T, T', hT, hT', hfspan⟩ :=
    Submodule.mem_span_mul_finite_of_mem_mul hfmem
  obtain ⟨U, hU, hfU⟩ := Submodule.mem_span_finite_of_mem_span hfspan
  have hqdata (q : A) (hq : q ∈ U) :
      ∃ t ∈ T, ∃ u ∈ T', ∃ b : A, t * u = q ∧ t * u = b * f := by
    obtain ⟨t, ht, u, hu, htu⟩ := Set.mem_mul.mp (hU hq)
    have hqu : t * u ∈ I * J := Ideal.mul_mem_mul (hT ht) (hT' hu)
    obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp (hprod ▸ hqu)
    exact ⟨t, ht, u, hu, b, htu, hb.symm⟩
  choose t ht u hu b htu hb using hqdata
  obtain ⟨c, hc, hcf⟩ :=
    (Submodule.mem_span_finset (R := A) (s := U)).mp hfU
  have hcf' : ∑ q ∈ U, c q * q = f := by
    simpa [smul_eq_mul] using hcf
  let b0 : A → A := fun q => if hq : q ∈ U then b q hq else 0
  have hsum : (∑ q ∈ U, c q * b0 q) * f = f := by
    calc
      (∑ q ∈ U, c q * b0 q) * f =
          ∑ q ∈ U, c q * (b0 q * f) := by
            rw [Finset.sum_mul]
            apply Finset.sum_congr rfl
            intro q hq
            ac_rfl
      _ = ∑ q ∈ U, c q * q := by
        apply Finset.sum_congr rfl
        intro q hq
        have hqb : q = b q hq * f :=
          (htu q hq).symm.trans (hb q hq)
        have hb0 : b0 q = b q hq := by
          dsimp [b0]
          rw [dif_pos hq]
        calc
          c q * (b0 q * f) = c q * (b q hq * f) := by rw [hb0]
          _ = c q * q := congrArg (fun z => c q * z) hqb.symm
      _ = f := hcf'
  have hone : ∑ q ∈ U, c q * b0 q = 1 := by
    apply hf.right
    simpa using hsum
  have h1 : (1 : A) ∈ Ideal.span
      {a : A | ∃ x ∈ I, ∃ y ∈ J, x * y = a * f} := by
    rw [← hone]
    exact Submodule.sum_mem _ fun q hq =>
      Submodule.smul_mem _ (c q) (by
        have hb0 : b0 q = b q hq := by
          dsimp [b0]
          rw [dif_pos hq]
        rw [hb0]
        exact Submodule.subset_span
          (⟨t q hq, hT (ht q hq), u q hq, hT' (hu q hq), hb q hq⟩ :
            b q hq ∈ {a : A | ∃ x ∈ I, ∃ y ∈ J, x * y = a * f}))
  apply top_unique
  intro a ha
  rw [← mul_one a]
  exact (Ideal.span _).mul_mem_left a h1

private theorem localized_ideal_is_span_singleton
    {A : Type u} [CommRing A]
    (I J : Ideal A) {f a x y : A}
    (hprod : I * J = Ideal.span ({f} : Set A))
    (hf : IsRegular f) (hx : x ∈ I) (hy : y ∈ J)
    (hxy : x * y = a * f) :
    (I : Submodule A A).localized' (Localization.Away a)
        (Submonoid.powers a) (LocalizedModule.mkLinearMap (Submonoid.powers a) A) =
      Submodule.span (Localization.Away a)
        ({algebraMap A (Localization.Away a) x} : Set (Localization.Away a)) := by
  rw [← Submodule.span_eq I, Submodule.localized'_span]
  apply Submodule.span_eq_span
  · rintro _ ⟨z, hz, rfl⟩
    apply Submodule.mem_span_singleton.mpr
    have hfreq : IsRegular (algebraMap A (Localization.Away a) f) :=
      Submonoid.LocalizationMap.map_isRegular
        (IsLocalization.toLocalizationMap (Submonoid.powers a)
          (Localization.Away a)) hf
    let s : Submonoid.powers a := ⟨a, by exact ⟨1, by simp⟩⟩
    have hau : IsUnit (algebraMap A (Localization.Away a) a) :=
      IsLocalization.map_units (R := A) (S := Localization.Away a)
        (M := Submonoid.powers a) s
    have hxyreg : IsRegular
        (algebraMap A (Localization.Away a) x *
          algebraMap A (Localization.Away a) y) := by
      rw [← map_mul, hxy, map_mul]
      exact (IsUnit.isRegular hau).mul hfreq
    have hyreg : IsRegular (algebraMap A (Localization.Away a) y) :=
      hxyreg.of_mul_right
    have hzy : (z : A) * y ∈ I * J := Ideal.mul_mem_mul hz hy
    have hzy' : (z : A) * y ∈ Ideal.span ({f} : Set A) := hprod ▸ hzy
    obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp hzy'
    have hcancel : algebraMap A (Localization.Away a) a *
          algebraMap A (Localization.Away a) z =
        algebraMap A (Localization.Away a) b *
          algebraMap A (Localization.Away a) x := by
      apply hyreg.right
      change (algebraMap A (Localization.Away a) a *
          algebraMap A (Localization.Away a) z) *
            algebraMap A (Localization.Away a) y =
        (algebraMap A (Localization.Away a) b *
          algebraMap A (Localization.Away a) x) *
            algebraMap A (Localization.Away a) y
      calc
        (algebraMap A (Localization.Away a) a *
            algebraMap A (Localization.Away a) z) *
              algebraMap A (Localization.Away a) y =
            algebraMap A (Localization.Away a) a *
              algebraMap A (Localization.Away a) (z * y) := by
                rw [mul_assoc, ← map_mul]
        _ = algebraMap A (Localization.Away a) a *
              algebraMap A (Localization.Away a) (b * f) := by rw [hb]
        _ = algebraMap A (Localization.Away a) a *
              (algebraMap A (Localization.Away a) b *
                algebraMap A (Localization.Away a) f) := by rw [map_mul]
        _ = algebraMap A (Localization.Away a) b *
              (algebraMap A (Localization.Away a) a *
                algebraMap A (Localization.Away a) f) := by ac_rfl
        _ = algebraMap A (Localization.Away a) b *
              algebraMap A (Localization.Away a) (a * f) := by rw [map_mul]
        _ = algebraMap A (Localization.Away a) b *
              algebraMap A (Localization.Away a) (x * y) := by rw [hxy]
        _ = (algebraMap A (Localization.Away a) b *
              algebraMap A (Localization.Away a) x) *
                algebraMap A (Localization.Away a) y := by
                  rw [map_mul, mul_assoc]
    have hloc : IsLocalization.mk' (Localization.Away a) (b * x) s =
        algebraMap A (Localization.Away a) z := by
      apply IsLocalization.mk'_eq_iff_eq_mul.mpr
      simpa [s, map_mul, mul_comm] using hcancel.symm
    have hloc'' : IsLocalization.mk' (Localization.Away a) (b * x) s =
        IsLocalization.mk' (Localization.Away a) z (1 : Submonoid.powers a) := by
      simpa only [IsLocalization.mk'_one] using hloc
    have hloc' : IsLocalizedModule.mk'
        (LocalizedModule.mkLinearMap (Submonoid.powers a) A) (b * x) s =
        LocalizedModule.mkLinearMap (Submonoid.powers a) A z := by
      rw [← IsLocalizedModule.mk'_one (Submonoid.powers a)
        (LocalizedModule.mkLinearMap (Submonoid.powers a) A) z]
      apply (IsLocalizedModule.mk'_eq_mk'_iff (S := Submonoid.powers a)
        (f := LocalizedModule.mkLinearMap (Submonoid.powers a) A) (b * x) z s 1).2
      obtain ⟨c, hc⟩ :=
        (IsLocalization.eq (M := Submonoid.powers a)
          (S := Localization.Away a)).mp hloc''
      refine ⟨c, ?_⟩
      simpa [Submonoid.smul_def] using hc.symm
    have hsmul : IsLocalization.mk' (Localization.Away a) b s •
        algebraMap A (Localization.Away a) x =
        IsLocalizedModule.mk' (LocalizedModule.mkLinearMap (Submonoid.powers a) A)
          (b * x) s := by
      change IsLocalization.mk' (Localization.Away a) b s •
        LocalizedModule.mkLinearMap (Submonoid.powers a) A x = _
      rw [← IsLocalizedModule.mk'_one (Submonoid.powers a)
        (LocalizedModule.mkLinearMap (Submonoid.powers a) A) x]
      simpa using (IsLocalizedModule.mk'_smul_mk' (Localization.Away a)
        (LocalizedModule.mkLinearMap (Submonoid.powers a) A) b x s 1)
    refine ⟨IsLocalization.mk' (Localization.Away a) b s, ?_⟩
    exact hsmul.trans hloc'
  · intro q hq
    rcases hq with rfl
    exact Submodule.subset_span ⟨x, hx, rfl⟩

private theorem localized_ideal_is_free_rank_one
    {A : Type u} [CommRing A]
    (I J : Ideal A) {f a x y : A}
    (hprod : I * J = Ideal.span ({f} : Set A))
    (hf : IsRegular f) (hx : x ∈ I) (hy : y ∈ J)
    (hxy : x * y = a * f) :
    Module.Finite (Localization.Away a)
        (LocalizedModule.Away a (I : Type u)) ∧
      Module.Free (Localization.Away a)
        (LocalizedModule.Away a (I : Type u)) ∧
      Nonempty
        (LocalizedModule.Away a (I : Type u) ≃ₗ[Localization.Away a]
          (Fin 1 →₀ Localization.Away a)) := by
  classical
  let S := Localization.Away a
  let p := Submonoid.powers a
  let g : S := algebraMap A S x
  have hau : IsUnit (algebraMap A S a) :=
    IsLocalization.map_units (R := A) (S := S) (M := p)
      ⟨a, by exact ⟨1, by simp⟩⟩
  have hfreq : IsRegular (algebraMap A S f) :=
    Submonoid.LocalizationMap.map_isRegular
      (IsLocalization.toLocalizationMap p S) hf
  have hxyreg : IsRegular (algebraMap A S x * algebraMap A S y) := by
    rw [← map_mul, hxy, map_mul]
    exact (IsUnit.isRegular hau).mul hfreq
  have hxreg : IsRegular g := hxyreg.of_mul_left
  have hloc := localized_ideal_is_span_singleton I J hprod hf hx hy hxy
  let P : Submodule S S := Submodule.span S ({g} : Set S)
  have hlocP :
      (I : Submodule A A).localized' S p
          (LocalizedModule.mkLinearMap p A) = P := by
    simpa [P, S, p, g] using hloc
  let l : S →ₗ[S] P :=
    (LinearMap.toSpanSingleton S S g).codRestrict P (fun z =>
      Submodule.smul_mem P z (Submodule.subset_span (by simp)))
  have linj : Function.Injective l := by
    intro r s hrs
    apply hxreg.right
    exact congrArg Subtype.val hrs
  have lsurj : Function.Surjective l := by
    intro z
    obtain ⟨r, hr⟩ := Submodule.mem_span_singleton.mp z.property
    refine ⟨r, Subtype.ext ?_⟩
    exact hr
  let eSpan : S ≃ₗ[S] P := LinearEquiv.ofBijective l ⟨linj, lsurj⟩
  have eLoc : P ≃ₗ[S] LocalizedModule p (I : Type u) := by
    rw [← hlocP]
    simpa [S, p] using
      (Submodule.localizedEquiv p (I : Submodule A A))
  let eRank : LocalizedModule p (I : Type u) ≃ₗ[S] (Fin 1 →₀ S) :=
    eLoc.symm.trans (eSpan.symm.trans
      (Finsupp.uniqueLinearEquiv S S (0 : Fin 1)).symm)
  refine ⟨?_, ?_, ⟨eRank⟩⟩
  · exact Module.Finite.of_surjective eRank.symm.toLinearMap eRank.symm.surjective
  · exact Module.Free.of_equiv' (P := Fin 1 →₀ S) inferInstance eRank.symm

/- The source's “finitely locally free of rank 1” is expressed with the
   earlier chapter's basic-open cover and fixed-rank predicates. -/
theorem product_ideals_principal_is_finite_locally_free_rank_one
    {A : Type u} [CommRing A]
    (I J : Ideal A) (hI : I ≠ ⊥) (hJ : J ≠ ⊥)
    {f : A} (hprod : I * J = Ideal.span ({f} : Set A))
    (hf : IsRegular f) :
    Module.Finite A (I : Type u) ∧
        Module.Finite A (J : Type u) ∧
          Formalization.Books.Algebra.Unit78.FiniteLocallyFree A
              (I : Type u) ∧
            Formalization.Books.Algebra.Unit78.FiniteLocallyFree A
              (J : Type u) ∧
              Formalization.Books.Algebra.Unit78.FiniteLocallyFreeOfRank A
                (I : Type u) 1 ∧
                Formalization.Books.Algebra.Unit78.FiniteLocallyFreeOfRank A
                  (J : Type u) 1 := by
  classical
  let S : Set A := {a : A | ∃ x ∈ I, ∃ y ∈ J, x * y = a * f}
  have hS : Ideal.span S = ⊤ := by
    simpa [S] using product_coefficients_span_top I J hprod hf
  obtain ⟨TI, hTI, hspanI⟩ := finite_ideal_of_product_principal I J hprod hf
  have hprodJ : J * I = Ideal.span ({f} : Set A) := by
    simpa [mul_comm] using hprod
  obtain ⟨TJ, hTJ, hspanJ⟩ :=
    finite_ideal_of_product_principal J I hprodJ hf
  have hfinI : Module.Finite A (I : Type u) := by
    apply Module.Finite.of_fg
    exact ⟨TI, hspanI.symm⟩
  have hfinJ : Module.Finite A (J : Type u) := by
    apply Module.Finite.of_fg
    exact ⟨TJ, hspanJ.symm⟩
  have hflfI : Formalization.Books.Algebra.Unit78.FiniteLocallyFree A
      (I : Type u) := by
    refine ⟨S, hS, ?_⟩
    intro a ha
    rcases ha with ⟨x, hx, y, hy, hxy⟩
    have hlocal := localized_ideal_is_free_rank_one I J hprod hf hx hy hxy
    exact ⟨hlocal.1, hlocal.2.1⟩
  have hflfJ : Formalization.Books.Algebra.Unit78.FiniteLocallyFree A
      (J : Type u) := by
    refine ⟨S, hS, ?_⟩
    intro a ha
    rcases ha with ⟨x, hx, y, hy, hxy⟩
    have hxy' : y * x = a * f := by simpa [mul_comm] using hxy
    have hlocal := localized_ideal_is_free_rank_one J I hprodJ hf hy hx hxy'
    exact ⟨hlocal.1, hlocal.2.1⟩
  have hrankI : Formalization.Books.Algebra.Unit78.FiniteLocallyFreeOfRank A
      (I : Type u) 1 := by
    refine ⟨S, hS, ?_⟩
    intro a ha
    rcases ha with ⟨x, hx, y, hy, hxy⟩
    exact (localized_ideal_is_free_rank_one I J hprod hf hx hy hxy).2.2
  have hrankJ : Formalization.Books.Algebra.Unit78.FiniteLocallyFreeOfRank A
      (J : Type u) 1 := by
    refine ⟨S, hS, ?_⟩
    intro a ha
    rcases ha with ⟨x, hx, y, hy, hxy⟩
    have hxy' : y * x = a * f := by simpa [mul_comm] using hxy
    exact (localized_ideal_is_free_rank_one J I hprodJ hf hy hx hxy').2.2
  exact ⟨hfinI, hfinJ, hflfI, hflfJ, hrankI, hrankJ⟩

/- The first condition in the source's Dedekind-domain definition is
   represented by `IsDedekindDomain`; the second uses the canonical DVR
   formulation, and the third is the canonical normal, one-dimensional
   formulation. -/
def DedekindDomainConditions
    (R : Type u) [CommRing R] : List Prop :=
  [ IsDedekindDomain R,
    ∃ hR : IsDomain R,
      letI : IsDomain R := hR
      IsNoetherianRing R ∧ IsDedekindDomainDvr R,
    IsNoetherianRing R ∧
      Formalization.Books.Algebra.Unit37.IsNormalDomain R ∧
        Ring.DimensionLEOne R ]

theorem dedekind_domain_characterization
    {R : Type u} [CommRing R] :
    List.TFAE (DedekindDomainConditions R) := by
  sorry

/-! ## Integral closures in finite extensions -/

theorem integral_closure_of_one_dimensional_domain_is_dedekind
    {A K L : Type u} [CommRing A] [IsDomain A] [IsNoetherianRing A]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    [Module.Finite K L] (hdim : ringKrullDim A = 1) :
    ∃ hB : IsDedekindDomain (integralClosure A L),
      letI : IsDedekindDomain (integralClosure A L) := hB
      Function.Surjective
          (PrimeSpectrum.comap
            (algebraMap A (integralClosure A L))) ∧
        ∀ p : PrimeSpectrum A,
          Set.Finite
              {q : PrimeSpectrum (integralClosure A L) |
                PrimeSpectrum.comap
                    (algebraMap A (integralClosure A L)) q = p} ∧
            ∀ q : PrimeSpectrum (integralClosure A L),
              PrimeSpectrum.comap
                  (algebraMap A (integralClosure A L)) q = p →
                ∃ φ : p.asIdeal.ResidueField →+* q.asIdeal.ResidueField,
                  (∀ a : A,
                    φ (algebraMap A p.asIdeal.ResidueField a) =
                      algebraMap (integralClosure A L) q.asIdeal.ResidueField
                        (algebraMap A (integralClosure A L) a)) ∧
                  (letI : Algebra p.asIdeal.ResidueField q.asIdeal.ResidueField :=
                      φ.toAlgebra
                   Module.Finite p.asIdeal.ResidueField q.asIdeal.ResidueField) := by
  sorry

end

end Formalization.Books.Algebra.Unit120
