import Formalization.Books.Algebra.Unit37.NormalRings
import Formalization.Books.Algebra.Unit36.FiniteIntegralRingExtensions
import Formalization.Books.Algebra.Unit78.FiniteProjectiveModules
import Mathlib.RingTheory.DedekindDomain.Basic
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.Ideal.UFD
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Polynomial.UniqueFactorization
import Mathlib.RingTheory.PrincipalIdealDomain
import Mathlib.RingTheory.UniqueFactorizationDomain.GCDMonoid

/-!
# Commutative Algebra, Chapter 120: Factorization

The standard element notions in this section use Mathlib's canonical
`Associated`, `Irreducible`, and `Prime` predicates.  A unique factorization
domain is represented by `IsDomain R` together with
`UniqueFactorizationMonoid R`; a principal ideal domain is represented by
`IsDomain R` together with `IsPrincipalIdealRing R`.  Dedekind domains use
Mathlib's `IsDedekindDomain` class.
-/

namespace Formalization.Books.Algebra.Unit120

open Set
open scoped Polynomial

universe u v

noncomputable section

/-! ## Associates, irreducibles, primes, and existence of factorization -/

/- The source's definition of associates is exactly `Associated`; the
   following theorem exposes its principal-ideal formulation. -/
theorem associated_iff_equal_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R] (x y : R) :
    Associated x y ↔
      Ideal.span ({x} : Set R) = Ideal.span ({y} : Set R) := by
  exact Ideal.span_singleton_eq_span_singleton.symm

/- The source's phrase “has a factorization into irreducibles” is recorded
   with a finite multiset, which retains the finite product and permutation
   content of the displayed list. -/
def HasIrreducibleFactorizations
    (R : Type u) [CommRing R] : Prop :=
  ∀ a : R, a ≠ 0 → ¬ IsUnit a →
    ∃ f : Multiset R,
      (∀ b ∈ f, Irreducible b) ∧ f.prod = a ∧ f ≠ 0

theorem factorization_exists_of_acc_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R] [WfDvdMonoid R]
    {a : R} (ha : a ≠ 0) (haunit : ¬ IsUnit a) :
    ∃ f : Multiset R,
      (∀ b ∈ f, Irreducible b) ∧ f.prod = a ∧ f ≠ 0 := by
  exact (WfDvdMonoid.not_isUnit_iff_exists_factors_eq a ha).mp haunit

/- The source defines primality by the ideal `Ideal.span {x}` being prime.
   For the nonzero elements used in the factorization arguments, this agrees
   with Mathlib's canonical `Prime x`. -/
theorem prime_iff_principal_ideal_isPrime
    {R : Type u} [CommRing R] [IsDomain R] {x : R} (hx : x ≠ 0) :
    Prime x ↔ (Ideal.span ({x} : Set R)).IsPrime := by
  exact (Ideal.span_singleton_prime hx).symm

theorem ufd_iff_irreducibles_are_prime
    {R : Type u} [CommRing R] [IsDomain R]
    (hfactor : HasIrreducibleFactorizations R) :
    UniqueFactorizationMonoid R ↔
      ∀ x : R, Irreducible x → Prime x := by
  sorry

/-! ## Criteria for unique factorization -/

theorem ufd_iff_height_one_prime_ideals_principal
    {R : Type u} [CommRing R] [IsDomain R] [IsNoetherianRing R] :
    UniqueFactorizationMonoid R ↔
      ∀ (p : Ideal R) [p.IsPrime], p.height = 1 → p.IsPrincipal := by
  exact UniqueFactorizationMonoid.iff_forall_isPrincipal_of_height_eq_one

/- A multiplicative subset generated by prime elements is represented by the
   submonoid closure of a set of prime elements. -/
def IsGeneratedByPrimeElements
    {A : Type u} [CommRing A] (S : Submonoid A) : Prop :=
  ∃ T : Set A, (∀ p ∈ T, Prime p) ∧ Submonoid.closure T = S

theorem nagata_irreducible_or_unit
    {A : Type u} [CommRing A] [IsDomain A]
    (S : Submonoid A) (hS : IsGeneratedByPrimeElements S)
    {x : A} (hx : Irreducible x) :
    Irreducible (algebraMap A (Localization S) x) ∨
      IsUnit (algebraMap A (Localization S) x) := by
  sorry

theorem nagata_prime_iff_prime_or_unit
    {A : Type u} [CommRing A] [IsDomain A]
    (S : Submonoid A) (hS : IsGeneratedByPrimeElements S)
    {x : A} (hx : Irreducible x) :
    Prime x ↔
      Prime (algebraMap A (Localization S) x) ∨
        IsUnit (algebraMap A (Localization S) x) := by
  sorry

theorem nagata_factorization_criterion
    {A : Type u} [CommRing A] [IsDomain A]
    (S : Submonoid A) (hS : IsGeneratedByPrimeElements S) :
    UniqueFactorizationMonoid A ↔
      HasIrreducibleFactorizations A ∧
        IsDomain (Localization S) ∧
          UniqueFactorizationMonoid (Localization S) := by
  sorry

theorem ufd_has_acc_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R]
    [UniqueFactorizationMonoid R] :
    WfDvdMonoid R := by
  sorry

theorem polynomial_has_acc_principal_ideals
    {R : Type u} [CommRing R] [IsDomain R] [WfDvdMonoid R] :
    WfDvdMonoid R[X] := by
  sorry

theorem polynomial_ring_over_ufd_is_ufd
    {R : Type u} [CommRing R] [IsDomain R]
    [UniqueFactorizationMonoid R] :
    UniqueFactorizationMonoid R[X] := by
  sorry

theorem multivariable_polynomial_ring_over_field_is_ufd
    (k : Type u) [Field k] (n : ℕ) :
    UniqueFactorizationMonoid (MvPolynomial (Fin n) k) := by
  sorry

theorem ufd_is_normal_domain
    {R : Type u} [CommRing R] [IsDomain R]
    [UniqueFactorizationMonoid R] :
    Formalization.Books.Algebra.Unit37.IsNormalDomain R := by
  sorry

/-! ## Principal ideal and Dedekind domains -/

theorem principal_ideal_domain_is_ufd
    {R : Type u} [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R] :
    UniqueFactorizationMonoid R := by
  sorry

theorem principal_ideal_domain_is_dedekind
    {R : Type u} [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R] :
    IsDedekindDomain R := by
  sorry

/- The source's “finitely locally free of rank 1” is expressed with the
   earlier chapter's basic-open cover and fixed-rank predicates. -/
theorem product_ideals_principal_is_finite_locally_free_rank_one
    {A : Type u} [CommRing A]
    (I J : Ideal A) (hI : I ≠ ⊥) (hJ : J ≠ ⊥)
    {f : A} (hprod : I * J = Ideal.span ({f} : Set A))
    (hf : IsRegular f) :
    Module.Finite A (I : Type u) ∧
        Module.Finite A (J : Type u) ∧
          Formalization.Books.Algebra.Unit78.FiniteLocallyFree A
              (I : Type u) ∧
            Formalization.Books.Algebra.Unit78.FiniteLocallyFree A
              (J : Type u) ∧
              Formalization.Books.Algebra.Unit78.FiniteLocallyFreeOfRank A
                (I : Type u) 1 ∧
                Formalization.Books.Algebra.Unit78.FiniteLocallyFreeOfRank A
                  (J : Type u) 1 := by
  sorry

/- The first condition in the source's Dedekind-domain definition is
   represented by `IsDedekindDomain`; the second uses the canonical DVR
   formulation, and the third is the canonical normal, one-dimensional
   formulation. -/
def DedekindDomainConditions
    (R : Type u) [CommRing R] : List Prop :=
  [ IsDedekindDomain R,
    ∃ hR : IsDomain R,
      letI : IsDomain R := hR
      IsNoetherianRing R ∧ IsDedekindDomainDvr R,
    IsNoetherianRing R ∧
      Formalization.Books.Algebra.Unit37.IsNormalDomain R ∧
        Ring.DimensionLEOne R ]

theorem dedekind_domain_characterization
    {R : Type u} [CommRing R] :
    List.TFAE (DedekindDomainConditions R) := by
  sorry

/-! ## Integral closures in finite extensions -/

theorem integral_closure_of_one_dimensional_domain_is_dedekind
    {A K L : Type u} [CommRing A] [IsDomain A] [IsNoetherianRing A]
    [Field K] [Algebra A K] [IsFractionRing A K]
    [Field L] [Algebra K L] [Algebra A L] [IsScalarTower A K L]
    [Module.Finite K L] (hdim : ringKrullDim A = 1) :
    ∃ hB : IsDedekindDomain (integralClosure A L),
      letI : IsDedekindDomain (integralClosure A L) := hB
      Function.Surjective
          (PrimeSpectrum.comap
            (algebraMap A (integralClosure A L))) ∧
        ∀ p : PrimeSpectrum A,
          Set.Finite
              {q : PrimeSpectrum (integralClosure A L) |
                PrimeSpectrum.comap
                    (algebraMap A (integralClosure A L)) q = p} ∧
            ∀ q : PrimeSpectrum (integralClosure A L),
              PrimeSpectrum.comap
                  (algebraMap A (integralClosure A L)) q = p →
                ∃ φ : p.asIdeal.ResidueField →+* q.asIdeal.ResidueField,
                  (∀ a : A,
                    φ (algebraMap A p.asIdeal.ResidueField a) =
                      algebraMap (integralClosure A L) q.asIdeal.ResidueField
                        (algebraMap A (integralClosure A L) a)) ∧
                  (letI : Algebra p.asIdeal.ResidueField q.asIdeal.ResidueField :=
                      φ.toAlgebra
                   Module.Finite p.asIdeal.ResidueField q.asIdeal.ResidueField) := by
  sorry

end

end Formalization.Books.Algebra.Unit120
