import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.Algebra.MonoidAlgebra.NoZeroDivisors
import Mathlib.Algebra.Field.ZMod
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.Algebra.Algebra.Epi
import Mathlib.Algebra.Algebra.Rat
import Mathlib.Algebra.Module.LinearMap.Rat
import Mathlib.Algebra.TrivSqZeroExt.Ideal
import Mathlib.Algebra.DualNumber
import Mathlib.RingTheory.Ideal.Cotangent
import Mathlib.RingTheory.Extension.ExtendScalars
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.Smooth.Basic
import Mathlib.RingTheory.RingHom.Smooth

/-!
# Examples, Chapter 41: A formally smooth non-flat ring map

This file formalizes the group-algebra example from the source section.  The
quotient `J / J²` is represented by Mathlib's canonical `Ideal.Cotangent`.
The infinitesimal lifting diagram in the source is represented by
`RingHom.FormallySmooth`; its square-zero quotient interface is already
provided by `Algebra.FormallySmooth.iff_comp_surjective`.
-/

noncomputable section

open scoped TensorProduct

namespace Formalization.Books.Examples.Unit41

universe u v

/-! ## The group algebra and its augmentation -/

/-- The group algebra `k[ℚ]`, using the additive group structure on `ℚ`. -/
abbrev rationalGroupAlgebra (k : Type u) [Field k] := AddMonoidAlgebra k ℚ

/-- The basis element `x_α` of `k[ℚ]`. -/
def rationalGroupAlgebraBasisElement (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebra k :=
  AddMonoidAlgebra.of' k ℚ α

/-- The homomorphism `k[ℚ] → k` sending every basis element to `1`. -/
def rationalGroupAlgebraAugmentation (k : Type u) [Field k] :
    rationalGroupAlgebra k →ₐ[k] k :=
  AddMonoidAlgebra.lift k k ℚ (1 : Multiplicative ℚ →* k)

@[simp]
theorem rationalGroupAlgebraAugmentation_basisElement (k : Type u) [Field k]
    (α : ℚ) :
    rationalGroupAlgebraAugmentation k (rationalGroupAlgebraBasisElement k α) = 1 := by
  simp [rationalGroupAlgebraAugmentation, rationalGroupAlgebraBasisElement]

@[simp]
theorem rationalGroupAlgebra_basisElement_zero (k : Type u) [Field k] :
    rationalGroupAlgebraBasisElement k 0 = 1 := by
  rfl

theorem rationalGroupAlgebraBasisElement_mul (k : Type u) [Field k]
    (α β : ℚ) :
    rationalGroupAlgebraBasisElement k α * rationalGroupAlgebraBasisElement k β =
      rationalGroupAlgebraBasisElement k (α + β) := by
  simp [rationalGroupAlgebraBasisElement]

/-- The augmentation is surjective. -/
theorem rationalGroupAlgebraAugmentation_surjective (k : Type u) [Field k] :
    Function.Surjective (rationalGroupAlgebraAugmentation k).toRingHom := by
  intro y
  refine ⟨y • rationalGroupAlgebraBasisElement k 0, ?_⟩
  simp [rationalGroupAlgebraAugmentation]

/-! ## The kernel and its cotangent space -/

/-- The kernel `J` of the augmentation. -/
def rationalGroupAlgebraKernel (k : Type u) [Field k] : Ideal (rationalGroupAlgebra k) :=
  RingHom.ker (rationalGroupAlgebraAugmentation k).toRingHom

/-- The displayed generators `x_α - 1` of the augmentation kernel. -/
def rationalGroupAlgebraKernelGenerators (k : Type u) [Field k] :
    Set (rationalGroupAlgebra k) :=
  Set.range (fun α : ℚ => rationalGroupAlgebraBasisElement k α - 1)

theorem rationalGroupAlgebra_basisElement_sub_one_mem_kernel
    (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebraBasisElement k α - 1 ∈ rationalGroupAlgebraKernel k := by
  change
    (rationalGroupAlgebraAugmentation k).toRingHom
        (rationalGroupAlgebraBasisElement k α - 1) = 0
  simp [rationalGroupAlgebraAugmentation, rationalGroupAlgebraBasisElement]

/-- The kernel is generated by the elements `x_α - 1`. -/
theorem rationalGroupAlgebraKernel_eq_span_generators (k : Type u) [Field k] :
    rationalGroupAlgebraKernel k =
      Ideal.span (rationalGroupAlgebraKernelGenerators k) := by
  classical
  apply le_antisymm
  · intro x hx
    change (rationalGroupAlgebraAugmentation k).toRingHom x = 0 at hx
    have hsum : x.coeff.sum (fun _ a => a) = 0 := by
      simpa [rationalGroupAlgebraAugmentation, AddMonoidAlgebra.lift_apply] using hx
    have hsum_smul : ∀ f : ℚ →₀ k,
        f.sum (fun _ a => a • (1 : rationalGroupAlgebra k)) =
          (f.sum (fun _ a => a)) • (1 : rationalGroupAlgebra k) := by
      intro f
      induction f using Finsupp.induction with
      | zero => simp
      | @single_add i a f h ha ih =>
          rw [Finsupp.sum_add_index'
            (h := fun _ b => b • (1 : rationalGroupAlgebra k))
            (fun _ => by simp)
            (fun _ _ _ => by simp [add_smul]),
            Finsupp.sum_add_index'
            (h := fun _ b => b)
            (fun _ => by simp)
            (fun _ _ _ => by simp)]
          rw [ih]
          simp [add_smul]
    have hmem : x.coeff.sum (fun i a =>
        a • (rationalGroupAlgebraBasisElement k i - 1)) ∈
        Ideal.span (rationalGroupAlgebraKernelGenerators k) := by
      apply Ideal.sum_mem
      intro i hi
      have hi' : rationalGroupAlgebraBasisElement k i - 1 ∈
          rationalGroupAlgebraKernelGenerators k := ⟨i, rfl⟩
      simpa [Algebra.smul_def] using
        Ideal.mul_mem_left (Ideal.span (rationalGroupAlgebraKernelGenerators k))
          (algebraMap k (rationalGroupAlgebra k) (x.coeff i))
          (b := rationalGroupAlgebraBasisElement k i - 1)
          (Ideal.subset_span hi')
    have h_eq : x = x.coeff.sum (fun i a =>
        a • (rationalGroupAlgebraBasisElement k i - 1)) := by
      calc
        x = x.coeff.sum (fun i a => AddMonoidAlgebra.single i a) :=
          x.sum_coeff_single.symm
        _ = x.coeff.sum (fun i a =>
            a • (AddMonoidAlgebra.single i 1)) := by
          simp
        _ = (x.coeff.sum (fun i a =>
              a • (AddMonoidAlgebra.single i 1) -
                a • (1 : rationalGroupAlgebra k))) +
            x.coeff.sum (fun i a => a • (1 : rationalGroupAlgebra k)) := by
          rw [Finsupp.sum_sub]
          exact (sub_add_cancel _ _).symm
        _ = x.coeff.sum (fun i a =>
            a • (rationalGroupAlgebraBasisElement k i - 1)) +
            x.coeff.sum (fun i a => a • (1 : rationalGroupAlgebra k)) := by
          simp [rationalGroupAlgebraBasisElement, smul_sub]
        _ = x.coeff.sum (fun i a =>
            a • (rationalGroupAlgebraBasisElement k i - 1)) := by
          rw [hsum_smul, hsum]
          simp
    exact h_eq ▸ hmem
  · apply Ideal.span_le.mpr
    rintro x ⟨α, rfl⟩
    change rationalGroupAlgebraBasisElement k α - 1 ∈ rationalGroupAlgebraKernel k
    exact rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α

/-- The conormal module `J / J²`. -/
abbrev rationalGroupAlgebraCotangent (k : Type u) [Field k] :=
  Ideal.Cotangent (rationalGroupAlgebraKernel k)

/-- The class `z_α` of `x_α - 1` in `J / J²`. -/
noncomputable def rationalGroupAlgebraCotangentGenerator
    (k : Type u) [Field k] (α : ℚ) : rationalGroupAlgebraCotangent k :=
  Ideal.toCotangent (rationalGroupAlgebraKernel k)
    ⟨rationalGroupAlgebraBasisElement k α - 1,
      rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α⟩

theorem rationalGroupAlgebraBasisElement_sub_one_mul_sub_one
    (k : Type u) [Field k] (α β : ℚ) :
    (rationalGroupAlgebraBasisElement k α - 1) *
        (rationalGroupAlgebraBasisElement k β - 1) =
      (rationalGroupAlgebraBasisElement k (α + β) - 1) -
        (rationalGroupAlgebraBasisElement k α - 1) -
        (rationalGroupAlgebraBasisElement k β - 1) := by
  calc
    (rationalGroupAlgebraBasisElement k α - 1) *
        (rationalGroupAlgebraBasisElement k β - 1) =
      rationalGroupAlgebraBasisElement k α *
          rationalGroupAlgebraBasisElement k β -
        rationalGroupAlgebraBasisElement k α -
        rationalGroupAlgebraBasisElement k β + 1 := by ring
    _ = _ := by rw [rationalGroupAlgebraBasisElement_mul]; ring

/-- The image of `x_α` in the residue ring `k[ℚ] / J`. -/
def rationalGroupAlgebraBasisElementResidue (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebra k ⧸ rationalGroupAlgebraKernel k :=
  Ideal.Quotient.mk (rationalGroupAlgebraKernel k)
    (rationalGroupAlgebraBasisElement k α)

/-!
The following statements record the elementary calculation in the source:
the residue of every `x_α` is `1`, hence multiplication by it on `J / J²`
is the identity; the `z_α` generate and satisfy the additive relation.
-/

theorem rationalGroupAlgebraBasisElementResidue_eq_one
    (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebraBasisElementResidue k α = 1 := by
  change Ideal.Quotient.mk (rationalGroupAlgebraKernel k)
    (rationalGroupAlgebraBasisElement k α) = 1
  rw [show (1 : rationalGroupAlgebra k ⧸ rationalGroupAlgebraKernel k) =
      Ideal.Quotient.mk (rationalGroupAlgebraKernel k) 1 by rfl,
    Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α

theorem rationalGroupAlgebraBasisElementResidue_smul_cotangent
    (k : Type u) [Field k] (α : ℚ) (z : rationalGroupAlgebraCotangent k) :
    rationalGroupAlgebraBasisElementResidue k α • z = z := by
  rw [rationalGroupAlgebraBasisElementResidue_eq_one]
  exact one_smul _ z

theorem rationalGroupAlgebraCotangentGenerator_add
    (k : Type u) [Field k] (α β : ℚ) :
    rationalGroupAlgebraCotangentGenerator k (α + β) =
      rationalGroupAlgebraCotangentGenerator k α +
        rationalGroupAlgebraCotangentGenerator k β := by
  unfold rationalGroupAlgebraCotangentGenerator
  rw [← LinearMap.map_add]
  apply (Ideal.toCotangent_eq (rationalGroupAlgebraKernel k)).2
  change (rationalGroupAlgebraBasisElement k (α + β) - 1) -
      ((rationalGroupAlgebraBasisElement k α - 1) +
        (rationalGroupAlgebraBasisElement k β - 1)) ∈
    rationalGroupAlgebraKernel k ^ 2
  have hmem :
      (rationalGroupAlgebraBasisElement k (α + β) - 1) -
          (rationalGroupAlgebraBasisElement k α - 1) -
          (rationalGroupAlgebraBasisElement k β - 1) ∈
        rationalGroupAlgebraKernel k ^ 2 := by
    rw [← rationalGroupAlgebraBasisElement_sub_one_mul_sub_one]
    rw [pow_two]
    exact Ideal.mul_mem_mul
      (rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α)
      (rationalGroupAlgebra_basisElement_sub_one_mem_kernel k β)
  convert hmem using 1
  · abel

private theorem rationalGroupAlgebra_smul_cotangent_eq_augmentation_smul
    (k : Type u) [Field k] (a : rationalGroupAlgebra k)
    (z : rationalGroupAlgebraCotangent k) :
    a • z = rationalGroupAlgebraAugmentation k a • z := by
  induction a using AddMonoidAlgebra.induction_on with
  | of α =>
      change rationalGroupAlgebraBasisElementResidue k α • z =
        rationalGroupAlgebraAugmentation k
            (rationalGroupAlgebraBasisElement k α) • z
      rw [rationalGroupAlgebraBasisElementResidue_eq_one,
        rationalGroupAlgebraAugmentation_basisElement]
      simp
  | add a b ha hb =>
      rw [add_smul, map_add, add_smul, ha, hb]
  | smul c a ha =>
      rw [Algebra.smul_def c a]
      rw [map_mul, (rationalGroupAlgebraAugmentation k).commutes,
        mul_smul, ha]
      change (algebraMap k (rationalGroupAlgebra k) c) •
          (rationalGroupAlgebraAugmentation k a • z) =
        (c * rationalGroupAlgebraAugmentation k a) • z
      rw [IsScalarTower.algebraMap_smul]
      simpa [Algebra.smul_def] using
        (smul_assoc c (rationalGroupAlgebraAugmentation k a) z).symm

theorem rationalGroupAlgebraCotangent_span_generators (k : Type u) [Field k] :
    Submodule.span k (Set.range (rationalGroupAlgebraCotangentGenerator k)) = ⊤ := by
  let P : Submodule k (rationalGroupAlgebraCotangent k) :=
    Submodule.span k (Set.range (rationalGroupAlgebraCotangentGenerator k))
  have hspan_le :
      Ideal.span (rationalGroupAlgebraKernelGenerators k) ≤
        rationalGroupAlgebraKernel k := by
    rw [rationalGroupAlgebraKernel_eq_span_generators]
  apply top_unique
  intro z hz
  obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective
    (rationalGroupAlgebraKernel k) z
  have hx : (x : rationalGroupAlgebra k) ∈
      Ideal.span (rationalGroupAlgebraKernelGenerators k) := by
    simpa only [rationalGroupAlgebraKernel_eq_span_generators] using x.property
  refine Submodule.span_induction
    (p := fun y hy =>
      Ideal.toCotangent (rationalGroupAlgebraKernel k)
          ⟨y, hspan_le hy⟩ ∈ P)
    ?_ ?_ ?_ ?_ hx
  · rintro y ⟨α, rfl⟩
    exact Submodule.subset_span ⟨α, rfl⟩
  · have hzero :
        (⟨0, hspan_le (Submodule.zero_mem _)⟩ : rationalGroupAlgebraKernel k) = 0 := by
      rfl
    rw [hzero, map_zero]
    exact P.zero_mem
  · intro y₁ y₂ hy₁ hy₂ ih₁ ih₂
    have hsub :
        (⟨y₁ + y₂, hspan_le (Submodule.add_mem _ hy₁ hy₂)⟩ :
          rationalGroupAlgebraKernel k) =
          (⟨y₁, hspan_le hy₁⟩ : rationalGroupAlgebraKernel k) +
            ⟨y₂, hspan_le hy₂⟩ := by
      rfl
    rw [hsub, map_add]
    exact P.add_mem ih₁ ih₂
  · intro a y hy ih
    have hsub :
        (⟨a • y, hspan_le (Submodule.smul_mem _ a hy)⟩ :
          rationalGroupAlgebraKernel k) =
          a • (⟨y, hspan_le hy⟩ : rationalGroupAlgebraKernel k) := by
      rfl
    rw [hsub, map_smul,
      rationalGroupAlgebra_smul_cotangent_eq_augmentation_smul]
    exact P.smul_mem _ ih

/-- Every cotangent vector is a finite `k`-linear combination of the `z_α`. -/
theorem rationalGroupAlgebraCotangent_exists_finite_linear_combination
    (k : Type u) [Field k] (z : rationalGroupAlgebraCotangent k) :
    ∃ c : ℚ →₀ k,
      z = c.sum (fun α a => a • rationalGroupAlgebraCotangentGenerator k α) := by
  have hz : z ∈ Submodule.span k (Set.range (rationalGroupAlgebraCotangentGenerator k)) := by
    rw [rationalGroupAlgebraCotangent_span_generators]
    exact Submodule.mem_top
  obtain ⟨c, hc⟩ :=
    (Finsupp.mem_span_range_iff_exists_finsupp).mp hz
  exact ⟨c, hc.symm⟩

/-! ## Characteristic computations -/

private theorem rationalGroupAlgebraCotangentGenerator_nsmul
    (k : Type u) [Field k] (n : ℕ) (β : ℚ) :
    n • rationalGroupAlgebraCotangentGenerator k β =
      rationalGroupAlgebraCotangentGenerator k (n • β) := by
  induction n with
  | zero =>
      unfold rationalGroupAlgebraCotangentGenerator
      have hzero :
          (⟨rationalGroupAlgebraBasisElement k 0 - 1,
            rationalGroupAlgebra_basisElement_sub_one_mem_kernel k 0⟩ :
              rationalGroupAlgebraKernel k) = 0 := by
        simp
      rw [zero_nsmul, zero_nsmul, hzero, map_zero]
  | succ n ih =>
      rw [succ_nsmul, ih, succ_nsmul,
        rationalGroupAlgebraCotangentGenerator_add]

/-- The displayed characteristic-`p` step, with `p > 0`. -/
theorem rationalGroupAlgebraCotangentGenerator_charP_step
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] (α : ℚ) :
    (p : k) • rationalGroupAlgebraCotangentGenerator k (α / (p : ℚ)) =
      rationalGroupAlgebraCotangentGenerator k α := by
  have hpq : (p : ℚ) ≠ 0 := by
    exact_mod_cast hp.ne'
  have hdiv : p • (α / (p : ℚ)) = α := by
    rw [nsmul_eq_mul]
    field_simp [hpq]
  rw [Nat.cast_smul_eq_nsmul,
    rationalGroupAlgebraCotangentGenerator_nsmul, hdiv]

/- The source's chain `0 = p z_(α/p) = z_α` is covered by this step
   together with the next vanishing theorem and `CharP.cast_eq_zero`. -/

theorem rationalGroupAlgebraCotangentGenerator_eq_zero_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] (α : ℚ) :
    rationalGroupAlgebraCotangentGenerator k α = 0 := by
  rw [← rationalGroupAlgebraCotangentGenerator_charP_step k p hp α,
    CharP.cast_eq_zero, zero_smul]

/-- In positive characteristic, `J / J²` is the zero module. -/
theorem rationalGroupAlgebraCotangent_subsingleton_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] :
    Subsingleton (rationalGroupAlgebraCotangent k) := by
  have hzero : ∀ z : rationalGroupAlgebraCotangent k, z = 0 := by
    intro z
    obtain ⟨c, hc⟩ :=
      rationalGroupAlgebraCotangent_exists_finite_linear_combination k z
    calc
      z = c.sum (fun α a => a • rationalGroupAlgebraCotangentGenerator k α) := hc
      _ = 0 := by
        simp [rationalGroupAlgebraCotangentGenerator_eq_zero_of_charP k p hp]
  exact ⟨fun z₁ z₂ => (hzero z₁).trans (hzero z₂).symm⟩

/-- The tensor-product model appearing in characteristic zero. -/
/- By symmetry of the tensor product, this is the source's `ℚ ⊗[ℤ] k` model
   with the factors ordered so that its canonical scalar action is by `k`. -/
abbrev rationalGroupAlgebraCharZeroTensor (k : Type u) [Field k] := k ⊗[ℤ] ℚ

private noncomputable def rationalGroupAlgebraCharZeroTensorEquivFieldAux
    (k : Type u) [Field k] [CharZero k] :
    rationalGroupAlgebraCharZeroTensor k ≃ₗ[k] k := by
  letI := Algebra.TensorProduct.rightAlgebra (R := ℤ) (A := ℚ) (B := k)
  let eQ : (ℚ ⊗[ℤ] k) ≃ₗ[k] k :=
    { toFun := TensorProduct.lid' ℤ ℚ k
      invFun := (TensorProduct.lid' ℤ ℚ k).symm
      left_inv := (TensorProduct.lid' ℤ ℚ k).left_inv
      right_inv := (TensorProduct.lid' ℤ ℚ k).right_inv
      map_add' := (TensorProduct.lid' ℤ ℚ k).map_add
      map_smul' := by
        intro c x
        induction x using TensorProduct.induction_on with
        | zero => simp
        | add x y hx hy =>
            simp only [map_add, smul_add, hx, hy, RingHom.id_apply]
        | tmul q x =>
            simp [Algebra.smul_def, Algebra.TensorProduct.right_algebraMap_apply,
              mul_comm, mul_assoc] }
  exact (Algebra.TensorProduct.commRight ℤ k ℚ).toLinearEquiv.trans eQ

private def rationalGroupAlgebraCharZeroDualNumberHom
    (k : Type u) [Field k] [CharZero k] : Multiplicative ℚ →* DualNumber k :=
  { toFun := fun a => 1 + (a.toAdd : k) • (DualNumber.eps : DualNumber k)
    map_one' := by simp
    map_mul' := by
      intro a b
      change 1 + ((a.toAdd + b.toAdd : ℚ) : k) • (DualNumber.eps : DualNumber k) =
        (1 + (a.toAdd : k) • (DualNumber.eps : DualNumber k)) *
          (1 + (b.toAdd : k) • (DualNumber.eps : DualNumber k))
      apply TrivSqZeroExt.ext
      · simp
      · simp [TrivSqZeroExt.snd_mul]
        simpa only [Rat.cast_add] using
          congrArg (fun q : ℚ => (q : k)) (add_comm a.toAdd b.toAdd) }

private def rationalGroupAlgebraCharZeroDualNumberMap
    (k : Type u) [Field k] [CharZero k] : rationalGroupAlgebra k →ₐ[k] DualNumber k :=
  AddMonoidAlgebra.lift k (DualNumber k) ℚ
    (rationalGroupAlgebraCharZeroDualNumberHom k)

private theorem rationalGroupAlgebraCharZeroDualNumberMap_fst
    (k : Type u) [Field k] [CharZero k] :
    (TrivSqZeroExt.fstHom k k k).comp
        (rationalGroupAlgebraCharZeroDualNumberMap k) =
      rationalGroupAlgebraAugmentation k := by
  apply AddMonoidAlgebra.algHom_ext
  · intro α
    simp [rationalGroupAlgebraCharZeroDualNumberMap,
      rationalGroupAlgebraAugmentation,
      rationalGroupAlgebraCharZeroDualNumberHom]
  · apply AlgHom.ext
    intro c
    simp [rationalGroupAlgebraCharZeroDualNumberMap,
      rationalGroupAlgebraAugmentation]

private theorem rationalGroupAlgebraCotangentGenerator_one_ne_zero
    (k : Type u) [Field k] [CharZero k] :
    rationalGroupAlgebraCotangentGenerator k 1 ≠ 0 := by
  intro hzero
  let φ := rationalGroupAlgebraCharZeroDualNumberMap k
  have hkernel : ∀ x : rationalGroupAlgebra k,
      x ∈ rationalGroupAlgebraKernel k →
        φ x ∈ TrivSqZeroExt.kerIdeal k k := by
    intro x hx
    change (TrivSqZeroExt.fstHom k k k) (φ x) = 0
    calc
      (TrivSqZeroExt.fstHom k k k) (φ x) =
          ((TrivSqZeroExt.fstHom k k k).comp φ) x := rfl
      _ = (rationalGroupAlgebraAugmentation k) x :=
        DFunLike.congr_fun (rationalGroupAlgebraCharZeroDualNumberMap_fst k) x
      _ = 0 := hx
  have hsq : ∀ x : rationalGroupAlgebra k,
      x ∈ rationalGroupAlgebraKernel k ^ 2 → φ x = 0 := by
    intro x hx
    rw [pow_two] at hx
    induction hx using Submodule.mul_induction_on' with
    | mem_mul_mem y hy z hz =>
        rw [map_mul]
        have hmem : φ y * φ z ∈
            TrivSqZeroExt.kerIdeal k k * TrivSqZeroExt.kerIdeal k k :=
          Ideal.mul_mem_mul (hkernel y hy) (hkernel z hz)
        have hsqmem : φ y * φ z ∈ TrivSqZeroExt.kerIdeal k k ^ 2 := by
          rw [pow_two]
          exact hmem
        rw [TrivSqZeroExt.kerIdeal_sq, Submodule.mem_bot] at hsqmem
        exact hsqmem
    | add y hy z hz hyz hzz =>
        rw [map_add, hyz, hzz, add_zero]
  have hmem :
      (rationalGroupAlgebraBasisElement k 1 - 1) ∈
        rationalGroupAlgebraKernel k ^ 2 := by
    exact (Ideal.toCotangent_eq_zero
      (rationalGroupAlgebraKernel k)
      ⟨rationalGroupAlgebraBasisElement k 1 - 1,
        rationalGroupAlgebra_basisElement_sub_one_mem_kernel k 1⟩).mp hzero
  have hφzero : φ (rationalGroupAlgebraBasisElement k 1 - 1) = 0 :=
    hsq _ hmem
  have hφeq : φ (rationalGroupAlgebraBasisElement k 1 - 1) =
      (DualNumber.eps : DualNumber k) := by
    simp [φ, rationalGroupAlgebraCharZeroDualNumberMap,
      rationalGroupAlgebraCharZeroDualNumberHom,
      rationalGroupAlgebraBasisElement]
  rw [hφeq] at hφzero
  have hε : (DualNumber.eps : DualNumber k) ≠ 0 := by
    intro hε
    have hsnd := congrArg TrivSqZeroExt.snd hε
    have hsnd' : (1 : k) = 0 := by
      simpa only [DualNumber.snd_eps, TrivSqZeroExt.snd_zero] using hsnd
    exact one_ne_zero hsnd'
  exact hε hφzero

private theorem rationalGroupAlgebraCotangentGenerator_eq_rat_smul
    (k : Type u) [Field k] [CharZero k] (α : ℚ) :
    rationalGroupAlgebraCotangentGenerator k α =
      (α : k) • rationalGroupAlgebraCotangentGenerator k 1 := by
  let zHom : ℚ →+ rationalGroupAlgebraCotangent k :=
    { toFun := rationalGroupAlgebraCotangentGenerator k
      map_zero' := by
        unfold rationalGroupAlgebraCotangentGenerator
        have hzero :
            (⟨rationalGroupAlgebraBasisElement k 0 - 1,
              rationalGroupAlgebra_basisElement_sub_one_mem_kernel k 0⟩ :
                rationalGroupAlgebraKernel k) = 0 := by
          simp
        rw [hzero, map_zero]
      map_add' := rationalGroupAlgebraCotangentGenerator_add k }
  have h := map_rat_smul zHom α (1 : ℚ)
  simpa [zHom, Rat.cast_smul_eq_qsmul k α
    (rationalGroupAlgebraCotangentGenerator k 1)] using h

private noncomputable def rationalGroupAlgebraCotangentEquivFieldAux
    (k : Type u) [Field k] [CharZero k] :
    rationalGroupAlgebraCotangent k ≃ₗ[k] k := by
  letI : Module ℚ (rationalGroupAlgebraCotangent k) :=
    Module.compHom (rationalGroupAlgebraCotangent k) (algebraMap ℚ k)
  let z₁ := rationalGroupAlgebraCotangentGenerator k 1
  let i : k →ₗ[k] rationalGroupAlgebraCotangent k :=
    { toFun := fun c => c • z₁
      map_add' := fun c d => add_smul c d z₁
      map_smul' := by
        intro c d
        simp [smul_smul] }
  have hsurj : Function.Surjective i := by
    intro z
    have hz : z ∈ Submodule.span k
        (Set.range (rationalGroupAlgebraCotangentGenerator k)) := by
      rw [rationalGroupAlgebraCotangent_span_generators]
      exact Submodule.mem_top
    have hle : Submodule.span k
        (Set.range (rationalGroupAlgebraCotangentGenerator k)) ≤
        LinearMap.range i := by
      apply Submodule.span_le.mpr
      rintro _ ⟨α, rfl⟩
      exact ⟨(α : k), (rationalGroupAlgebraCotangentGenerator_eq_rat_smul k α).symm⟩
    rcases hle hz with ⟨c, hc⟩
    exact ⟨c, hc⟩
  have hinj : Function.Injective i := by
    intro c d hcd
    have hzero : (c - d) • z₁ = 0 := by
      simpa [i, sub_smul] using sub_eq_zero.mpr hcd
    have hcd' : c - d = 0 :=
      (smul_eq_zero.mp hzero).resolve_right
        (rationalGroupAlgebraCotangentGenerator_one_ne_zero k)
    exact sub_eq_zero.mp hcd'
  exact (LinearEquiv.ofBijective i ⟨hinj, hsurj⟩).symm

/- Linear equivalences are data rather than propositions, so the source's
   isomorphism statements are recorded as `Nonempty` theorems. -/
/-- In characteristic zero, `J / J²` is modeled by `ℚ ⊗_ℤ k`. -/
theorem rationalGroupAlgebraCotangent_equiv_charZeroTensor
    (k : Type u) [Field k] [CharZero k] :
    Nonempty (rationalGroupAlgebraCotangent k ≃ₗ[k]
      rationalGroupAlgebraCharZeroTensor k) := by
  exact ⟨(rationalGroupAlgebraCotangentEquivFieldAux k).trans
    (rationalGroupAlgebraCharZeroTensorEquivFieldAux k).symm⟩

/-- The characteristic-zero tensor-product model is isomorphic to `k`. -/
theorem rationalGroupAlgebraCharZeroTensor_equiv_field
    (k : Type u) [Field k] [CharZero k] :
    Nonempty (rationalGroupAlgebraCharZeroTensor k ≃ₗ[k] k) := by
  exact ⟨rationalGroupAlgebraCharZeroTensorEquivFieldAux k⟩

/-- In characteristic zero, `J / J²` is nonzero. -/
theorem rationalGroupAlgebraCotangent_nontrivial_of_charZero
    (k : Type u) [Field k] [CharZero k] :
    Nontrivial (rationalGroupAlgebraCotangent k) := by
  exact ⟨⟨rationalGroupAlgebraCotangentGenerator k 1, 0,
    rationalGroupAlgebraCotangentGenerator_one_ne_zero k⟩⟩

/-! ## Formal smoothness and failure of flatness -/

section AugmentationFormallySmooth

variable (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p]

local instance rationalGroupAlgebraAugmentationAlgebra :
    Algebra (rationalGroupAlgebra k) k :=
  (rationalGroupAlgebraAugmentation k).toRingHom.toAlgebra

private theorem rationalGroupAlgebraAugmentation_formallySmooth_aux
    (p : ℕ) (hp : 0 < p) [CharP k p] :
    RingHom.FormallySmooth (rationalGroupAlgebraAugmentation k).toRingHom := by
  let f := (rationalGroupAlgebraAugmentation k).toRingHom
  let fAlg : rationalGroupAlgebra k →ₐ[rationalGroupAlgebra k] k :=
    { toRingHom := f
      commutes' := by intro r; rfl }
  let P := Algebra.Extension.ofSurjective fAlg
    (by simpa [f, fAlg] using rationalGroupAlgebraAugmentation_surjective k)
  have hsurj : Function.Surjective (algebraMap (rationalGroupAlgebra k) k) := by
    change Function.Surjective f
    exact rationalGroupAlgebraAugmentation_surjective k
  have hΩ : Subsingleton (KaehlerDifferential (rationalGroupAlgebra k) k) :=
    KaehlerDifferential.subsingleton_of_surjective
      (rationalGroupAlgebra k) k hsurj
  let i : KaehlerDifferential (rationalGroupAlgebra k) k →ₗ[k] k := 0
  let s : k →ₗ[k] KaehlerDifferential (rationalGroupAlgebra k) k := 0
  have his : s.comp i = LinearMap.id := by
    ext x
    exact Subsingleton.elim _ _
  have hprojective :
      Module.Projective k (KaehlerDifferential (rationalGroupAlgebra k) k) :=
    Module.Projective.of_split i s his
  have hcot : Subsingleton P.Cotangent := by
    change Subsingleton (rationalGroupAlgebraCotangent k)
    exact rationalGroupAlgebraCotangent_subsingleton_of_charP k p hp
  have hh1 : Subsingleton
      (Algebra.H1Cotangent (rationalGroupAlgebra k) k) := by
    let e := P.h1CotangentEquivCotangent
    constructor
    intro x y
    apply e.injective
    exact Subsingleton.elim _ _
  exact ⟨hprojective, hh1⟩

end AugmentationFormallySmooth

/-- The augmentation is formally smooth in positive characteristic. -/
theorem rationalGroupAlgebraAugmentation_formallySmooth_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] :
    RingHom.FormallySmooth (rationalGroupAlgebraAugmentation k).toRingHom := by
  exact rationalGroupAlgebraAugmentation_formallySmooth_aux k p hp

/-!
The source's square-zero lifting diagram is the standard lifting criterion
for the preceding declaration.  Mathlib's `Algebra.FormallySmooth` API
provides that criterion through `Algebra.FormallySmooth.iff_comp_surjective`,
so no parallel diagram structure is introduced here.
-/

/-- The element `x_2 - 1` used to witness non-flatness. -/
def rationalGroupAlgebraNonflatWitness (k : Type u) [Field k] : rationalGroupAlgebra k :=
  rationalGroupAlgebraBasisElement k (2 : ℚ) - 1

/-- The non-flatness witness is a nonzerodivisor. -/
private theorem rationalGroupAlgebraNonflatWitness_ne_zero_aux
    (k : Type u) [Field k] :
    rationalGroupAlgebraNonflatWitness k ≠ 0 := by
  intro h
  have h' := congrArg (fun x => x.coeff (2 : ℚ)) h
  simp [rationalGroupAlgebraNonflatWitness, rationalGroupAlgebraBasisElement,
    AddMonoidAlgebra.one_def, Finsupp.single_eq_of_ne] at h'

theorem rationalGroupAlgebraNonflatWitness_isRegular
    (k : Type u) [Field k] :
    IsRegular (rationalGroupAlgebraNonflatWitness k) := by
  exact IsRegular.of_ne_zero' (rationalGroupAlgebraNonflatWitness_ne_zero_aux k)

theorem rationalGroupAlgebraNonflatWitness_ne_zero
    (k : Type u) [Field k] :
    rationalGroupAlgebraNonflatWitness k ≠ 0 := by
  exact rationalGroupAlgebraNonflatWitness_ne_zero_aux k

/-- The non-flatness witness maps to zero under the augmentation. -/
theorem rationalGroupAlgebraNonflatWitness_maps_to_zero
    (k : Type u) [Field k] :
    (rationalGroupAlgebraAugmentation k).toRingHom
        (rationalGroupAlgebraNonflatWitness k) = 0 := by
  exact rationalGroupAlgebra_basisElement_sub_one_mem_kernel k (2 : ℚ)

/-- The augmentation is not flat. -/
theorem rationalGroupAlgebraAugmentation_not_flat (k : Type u) [Field k] :
    ¬ RingHom.Flat (rationalGroupAlgebraAugmentation k).toRingHom := by
  exact
    letI : Algebra (rationalGroupAlgebra k) k :=
      (rationalGroupAlgebraAugmentation k).toRingHom.toAlgebra
    fun hflat =>
      have hreg : IsSMulRegular k (rationalGroupAlgebraNonflatWitness k) :=
        @Module.Flat.isSMulRegular_of_isRegular
          (rationalGroupAlgebra k) k _ _ _ (rationalGroupAlgebraNonflatWitness k)
          (rationalGroupAlgebraNonflatWitness_isRegular k) hflat
      have hone : (1 : k) = 0 := hreg (by
        simpa only [Algebra.smul_def, mul_one, mul_zero,
          RingHom.algebraMap_toAlgebra] using
          (rationalGroupAlgebraNonflatWitness_maps_to_zero k))
      one_ne_zero hone

/-- A concrete instance of the formally smooth, non-flat ring map. -/
theorem exists_formallySmooth_nonflat_ringMap :
    ∃ f : rationalGroupAlgebra (ZMod 2) →+* ZMod 2,
      RingHom.FormallySmooth f ∧ ¬ RingHom.Flat f := by
  refine ⟨(rationalGroupAlgebraAugmentation (ZMod 2)).toRingHom, ?_, ?_⟩
  · exact rationalGroupAlgebraAugmentation_formallySmooth_of_charP
      (ZMod 2) 2 (Nat.zero_lt_succ 1)
  · exact rationalGroupAlgebraAugmentation_not_flat (ZMod 2)

end Formalization.Books.Examples.Unit41
