import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.Algebra.MonoidAlgebra.NoZeroDivisors
import Mathlib.Algebra.Field.ZMod
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.RingTheory.Ideal.Cotangent
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.Smooth.Basic
import Mathlib.RingTheory.RingHom.Smooth

/-!
# Examples, Chapter 41: A formally smooth non-flat ring map

This file formalizes the group-algebra example from the source section.  The
quotient `J / J²` is represented by Mathlib's canonical `Ideal.Cotangent`.
The infinitesimal lifting diagram in the source is represented by
`RingHom.FormallySmooth`; its square-zero quotient interface is already
provided by `Algebra.FormallySmooth.iff_comp_surjective`.
-/

noncomputable section

open scoped TensorProduct

namespace Formalization.Books.Examples.Unit41

universe u v

/-! ## The group algebra and its augmentation -/

/-- The group algebra `k[ℚ]`, using the additive group structure on `ℚ`. -/
abbrev rationalGroupAlgebra (k : Type u) [Field k] := AddMonoidAlgebra k ℚ

/-- The basis element `x_α` of `k[ℚ]`. -/
def rationalGroupAlgebraBasisElement (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebra k :=
  AddMonoidAlgebra.of' k ℚ α

/-- The homomorphism `k[ℚ] → k` sending every basis element to `1`. -/
def rationalGroupAlgebraAugmentation (k : Type u) [Field k] :
    rationalGroupAlgebra k →ₐ[k] k :=
  AddMonoidAlgebra.lift k k ℚ (1 : Multiplicative ℚ →* k)

@[simp]
theorem rationalGroupAlgebraAugmentation_basisElement (k : Type u) [Field k]
    (α : ℚ) :
    rationalGroupAlgebraAugmentation k (rationalGroupAlgebraBasisElement k α) = 1 := by
  simp [rationalGroupAlgebraAugmentation, rationalGroupAlgebraBasisElement]

@[simp]
theorem rationalGroupAlgebra_basisElement_zero (k : Type u) [Field k] :
    rationalGroupAlgebraBasisElement k 0 = 1 := by
  rfl

theorem rationalGroupAlgebraBasisElement_mul (k : Type u) [Field k]
    (α β : ℚ) :
    rationalGroupAlgebraBasisElement k α * rationalGroupAlgebraBasisElement k β =
      rationalGroupAlgebraBasisElement k (α + β) := by
  simp [rationalGroupAlgebraBasisElement]

/-- The augmentation is surjective. -/
theorem rationalGroupAlgebraAugmentation_surjective (k : Type u) [Field k] :
    Function.Surjective (rationalGroupAlgebraAugmentation k).toRingHom := by
  intro y
  refine ⟨y • rationalGroupAlgebraBasisElement k 0, ?_⟩
  simp [rationalGroupAlgebraAugmentation]

/-! ## The kernel and its cotangent space -/

/-- The kernel `J` of the augmentation. -/
def rationalGroupAlgebraKernel (k : Type u) [Field k] : Ideal (rationalGroupAlgebra k) :=
  RingHom.ker (rationalGroupAlgebraAugmentation k).toRingHom

/-- The displayed generators `x_α - 1` of the augmentation kernel. -/
def rationalGroupAlgebraKernelGenerators (k : Type u) [Field k] :
    Set (rationalGroupAlgebra k) :=
  Set.range (fun α : ℚ => rationalGroupAlgebraBasisElement k α - 1)

theorem rationalGroupAlgebra_basisElement_sub_one_mem_kernel
    (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebraBasisElement k α - 1 ∈ rationalGroupAlgebraKernel k := by
  change
    (rationalGroupAlgebraAugmentation k).toRingHom
        (rationalGroupAlgebraBasisElement k α - 1) = 0
  simp [rationalGroupAlgebraAugmentation, rationalGroupAlgebraBasisElement]

/-- The kernel is generated by the elements `x_α - 1`. -/
theorem rationalGroupAlgebraKernel_eq_span_generators (k : Type u) [Field k] :
    rationalGroupAlgebraKernel k =
      Ideal.span (rationalGroupAlgebraKernelGenerators k) := by
  classical
  apply le_antisymm
  · intro x hx
    change (rationalGroupAlgebraAugmentation k).toRingHom x = 0 at hx
    have hsum : x.coeff.sum (fun _ a => a) = 0 := by
      simpa [rationalGroupAlgebraAugmentation, AddMonoidAlgebra.lift_apply] using hx
    have hsum_smul : ∀ f : ℚ →₀ k,
        f.sum (fun _ a => a • (1 : rationalGroupAlgebra k)) =
          (f.sum (fun _ a => a)) • (1 : rationalGroupAlgebra k) := by
      intro f
      induction f using Finsupp.induction with
      | zero => simp
      | @single_add i a f h ha ih =>
          rw [Finsupp.sum_add_index'
            (h := fun _ b => b • (1 : rationalGroupAlgebra k))
            (fun _ => by simp)
            (fun _ _ _ => by simp [add_smul]),
            Finsupp.sum_add_index'
            (h := fun _ b => b)
            (fun _ => by simp)
            (fun _ _ _ => by simp)]
          rw [ih]
          simp [add_smul]
    have hmem : x.coeff.sum (fun i a =>
        a • (rationalGroupAlgebraBasisElement k i - 1)) ∈
        Ideal.span (rationalGroupAlgebraKernelGenerators k) := by
      apply Ideal.sum_mem
      intro i hi
      have hi' : rationalGroupAlgebraBasisElement k i - 1 ∈
          rationalGroupAlgebraKernelGenerators k := ⟨i, rfl⟩
      simpa [Algebra.smul_def] using
        Ideal.mul_mem_left (Ideal.span (rationalGroupAlgebraKernelGenerators k))
          (algebraMap k (rationalGroupAlgebra k) (x.coeff i))
          (b := rationalGroupAlgebraBasisElement k i - 1)
          (Ideal.subset_span hi')
    have h_eq : x = x.coeff.sum (fun i a =>
        a • (rationalGroupAlgebraBasisElement k i - 1)) := by
      calc
        x = x.coeff.sum (fun i a => AddMonoidAlgebra.single i a) :=
          x.sum_coeff_single.symm
        _ = x.coeff.sum (fun i a =>
            a • (AddMonoidAlgebra.single i 1)) := by
          simp
        _ = (x.coeff.sum (fun i a =>
              a • (AddMonoidAlgebra.single i 1) -
                a • (1 : rationalGroupAlgebra k))) +
            x.coeff.sum (fun i a => a • (1 : rationalGroupAlgebra k)) := by
          rw [Finsupp.sum_sub]
          exact (sub_add_cancel _ _).symm
        _ = x.coeff.sum (fun i a =>
            a • (rationalGroupAlgebraBasisElement k i - 1)) +
            x.coeff.sum (fun i a => a • (1 : rationalGroupAlgebra k)) := by
          simp [rationalGroupAlgebraBasisElement, smul_sub]
        _ = x.coeff.sum (fun i a =>
            a • (rationalGroupAlgebraBasisElement k i - 1)) := by
          rw [hsum_smul, hsum]
          simp
    exact h_eq ▸ hmem
  · apply Ideal.span_le.mpr
    rintro x ⟨α, rfl⟩
    change rationalGroupAlgebraBasisElement k α - 1 ∈ rationalGroupAlgebraKernel k
    exact rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α

/-- The conormal module `J / J²`. -/
abbrev rationalGroupAlgebraCotangent (k : Type u) [Field k] :=
  Ideal.Cotangent (rationalGroupAlgebraKernel k)

/-- The class `z_α` of `x_α - 1` in `J / J²`. -/
noncomputable def rationalGroupAlgebraCotangentGenerator
    (k : Type u) [Field k] (α : ℚ) : rationalGroupAlgebraCotangent k :=
  Ideal.toCotangent (rationalGroupAlgebraKernel k)
    ⟨rationalGroupAlgebraBasisElement k α - 1,
      rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α⟩

theorem rationalGroupAlgebraBasisElement_sub_one_mul_sub_one
    (k : Type u) [Field k] (α β : ℚ) :
    (rationalGroupAlgebraBasisElement k α - 1) *
        (rationalGroupAlgebraBasisElement k β - 1) =
      (rationalGroupAlgebraBasisElement k (α + β) - 1) -
        (rationalGroupAlgebraBasisElement k α - 1) -
        (rationalGroupAlgebraBasisElement k β - 1) := by
  calc
    (rationalGroupAlgebraBasisElement k α - 1) *
        (rationalGroupAlgebraBasisElement k β - 1) =
      rationalGroupAlgebraBasisElement k α *
          rationalGroupAlgebraBasisElement k β -
        rationalGroupAlgebraBasisElement k α -
        rationalGroupAlgebraBasisElement k β + 1 := by ring
    _ = _ := by rw [rationalGroupAlgebraBasisElement_mul]; ring

/-- The image of `x_α` in the residue ring `k[ℚ] / J`. -/
def rationalGroupAlgebraBasisElementResidue (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebra k ⧸ rationalGroupAlgebraKernel k :=
  Ideal.Quotient.mk (rationalGroupAlgebraKernel k)
    (rationalGroupAlgebraBasisElement k α)

/-!
The following statements record the elementary calculation in the source:
the residue of every `x_α` is `1`, hence multiplication by it on `J / J²`
is the identity; the `z_α` generate and satisfy the additive relation.
-/

theorem rationalGroupAlgebraBasisElementResidue_eq_one
    (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebraBasisElementResidue k α = 1 := by
  change Ideal.Quotient.mk (rationalGroupAlgebraKernel k)
    (rationalGroupAlgebraBasisElement k α) = 1
  rw [show (1 : rationalGroupAlgebra k ⧸ rationalGroupAlgebraKernel k) =
      Ideal.Quotient.mk (rationalGroupAlgebraKernel k) 1 by rfl,
    Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α

theorem rationalGroupAlgebraBasisElementResidue_smul_cotangent
    (k : Type u) [Field k] (α : ℚ) (z : rationalGroupAlgebraCotangent k) :
    rationalGroupAlgebraBasisElementResidue k α • z = z := by
  rw [rationalGroupAlgebraBasisElementResidue_eq_one]
  exact one_smul _ z

theorem rationalGroupAlgebraCotangentGenerator_add
    (k : Type u) [Field k] (α β : ℚ) :
    rationalGroupAlgebraCotangentGenerator k (α + β) =
      rationalGroupAlgebraCotangentGenerator k α +
        rationalGroupAlgebraCotangentGenerator k β := by
  unfold rationalGroupAlgebraCotangentGenerator
  rw [← LinearMap.map_add]
  apply (Ideal.toCotangent_eq (rationalGroupAlgebraKernel k)).2
  change (rationalGroupAlgebraBasisElement k (α + β) - 1) -
      ((rationalGroupAlgebraBasisElement k α - 1) +
        (rationalGroupAlgebraBasisElement k β - 1)) ∈
    rationalGroupAlgebraKernel k ^ 2
  have hmem :
      (rationalGroupAlgebraBasisElement k (α + β) - 1) -
          (rationalGroupAlgebraBasisElement k α - 1) -
          (rationalGroupAlgebraBasisElement k β - 1) ∈
        rationalGroupAlgebraKernel k ^ 2 := by
    rw [← rationalGroupAlgebraBasisElement_sub_one_mul_sub_one]
    rw [pow_two]
    exact Ideal.mul_mem_mul
      (rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α)
      (rationalGroupAlgebra_basisElement_sub_one_mem_kernel k β)
  convert hmem using 1
  · abel

private theorem rationalGroupAlgebra_smul_cotangent_eq_augmentation_smul
    (k : Type u) [Field k] (a : rationalGroupAlgebra k)
    (z : rationalGroupAlgebraCotangent k) :
    a • z = rationalGroupAlgebraAugmentation k a • z := by
  induction a using AddMonoidAlgebra.induction_on with
  | of α =>
      change rationalGroupAlgebraBasisElementResidue k α • z =
        rationalGroupAlgebraAugmentation k
            (rationalGroupAlgebraBasisElement k α) • z
      rw [rationalGroupAlgebraBasisElementResidue_eq_one,
        rationalGroupAlgebraAugmentation_basisElement]
      simp
  | add a b ha hb =>
      rw [add_smul, map_add, add_smul, ha, hb]
  | smul c a ha =>
      rw [Algebra.smul_def c a]
      rw [map_mul, (rationalGroupAlgebraAugmentation k).commutes,
        mul_smul, ha]
      change (algebraMap k (rationalGroupAlgebra k) c) •
          (rationalGroupAlgebraAugmentation k a • z) =
        (c * rationalGroupAlgebraAugmentation k a) • z
      rw [IsScalarTower.algebraMap_smul]
      simpa [Algebra.smul_def] using
        (smul_assoc c (rationalGroupAlgebraAugmentation k a) z).symm

theorem rationalGroupAlgebraCotangent_span_generators (k : Type u) [Field k] :
    Submodule.span k (Set.range (rationalGroupAlgebraCotangentGenerator k)) = ⊤ := by
  let P : Submodule k (rationalGroupAlgebraCotangent k) :=
    Submodule.span k (Set.range (rationalGroupAlgebraCotangentGenerator k))
  have hspan_le :
      Ideal.span (rationalGroupAlgebraKernelGenerators k) ≤
        rationalGroupAlgebraKernel k := by
    rw [rationalGroupAlgebraKernel_eq_span_generators]
  apply top_unique
  intro z hz
  obtain ⟨x, rfl⟩ := Ideal.toCotangent_surjective
    (rationalGroupAlgebraKernel k) z
  have hx : (x : rationalGroupAlgebra k) ∈
      Ideal.span (rationalGroupAlgebraKernelGenerators k) := by
    simpa only [rationalGroupAlgebraKernel_eq_span_generators] using x.property
  refine Submodule.span_induction
    (p := fun y hy =>
      Ideal.toCotangent (rationalGroupAlgebraKernel k)
          ⟨y, hspan_le hy⟩ ∈ P)
    ?_ ?_ ?_ ?_ hx
  · rintro y ⟨α, rfl⟩
    exact Submodule.subset_span ⟨α, rfl⟩
  · have hzero :
        (⟨0, hspan_le (Submodule.zero_mem _)⟩ : rationalGroupAlgebraKernel k) = 0 := by
      rfl
    rw [hzero, map_zero]
    exact P.zero_mem
  · intro y₁ y₂ hy₁ hy₂ ih₁ ih₂
    have hsub :
        (⟨y₁ + y₂, hspan_le (Submodule.add_mem _ hy₁ hy₂)⟩ :
          rationalGroupAlgebraKernel k) =
          (⟨y₁, hspan_le hy₁⟩ : rationalGroupAlgebraKernel k) +
            ⟨y₂, hspan_le hy₂⟩ := by
      rfl
    rw [hsub, map_add]
    exact P.add_mem ih₁ ih₂
  · intro a y hy ih
    have hsub :
        (⟨a • y, hspan_le (Submodule.smul_mem _ a hy)⟩ :
          rationalGroupAlgebraKernel k) =
          a • (⟨y, hspan_le hy⟩ : rationalGroupAlgebraKernel k) := by
      rfl
    rw [hsub, map_smul,
      rationalGroupAlgebra_smul_cotangent_eq_augmentation_smul]
    exact P.smul_mem _ ih

/-- Every cotangent vector is a finite `k`-linear combination of the `z_α`. -/
theorem rationalGroupAlgebraCotangent_exists_finite_linear_combination
    (k : Type u) [Field k] (z : rationalGroupAlgebraCotangent k) :
    ∃ c : ℚ →₀ k,
      z = c.sum (fun α a => a • rationalGroupAlgebraCotangentGenerator k α) := by
  have hz : z ∈ Submodule.span k (Set.range (rationalGroupAlgebraCotangentGenerator k)) := by
    rw [rationalGroupAlgebraCotangent_span_generators]
    exact Submodule.mem_top
  obtain ⟨c, hc⟩ :=
    (Finsupp.mem_span_range_iff_exists_finsupp).mp hz
  exact ⟨c, hc.symm⟩

/-! ## Characteristic computations -/

private theorem rationalGroupAlgebraCotangentGenerator_nsmul
    (k : Type u) [Field k] (n : ℕ) (β : ℚ) :
    n • rationalGroupAlgebraCotangentGenerator k β =
      rationalGroupAlgebraCotangentGenerator k (n • β) := by
  induction n with
  | zero =>
      unfold rationalGroupAlgebraCotangentGenerator
      have hzero :
          (⟨rationalGroupAlgebraBasisElement k 0 - 1,
            rationalGroupAlgebra_basisElement_sub_one_mem_kernel k 0⟩ :
              rationalGroupAlgebraKernel k) = 0 := by
        simp
      rw [zero_nsmul, hzero, map_zero]
  | succ n ih =>
      rw [succ_nsmul, ih, succ_nsmul,
        rationalGroupAlgebraCotangentGenerator_add]

/-- The displayed characteristic-`p` step, with `p > 0`. -/
theorem rationalGroupAlgebraCotangentGenerator_charP_step
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] (α : ℚ) :
    (p : k) • rationalGroupAlgebraCotangentGenerator k (α / (p : ℚ)) =
      rationalGroupAlgebraCotangentGenerator k α := by
  have hpq : (p : ℚ) ≠ 0 := by
    exact_mod_cast hp.ne'
  have hdiv : p • (α / (p : ℚ)) = α := by
    rw [nsmul_eq_mul]
    field_simp [hpq]
  rw [Nat.cast_smul_eq_nsmul,
    rationalGroupAlgebraCotangentGenerator_nsmul, hdiv]

/- The source's chain `0 = p z_(α/p) = z_α` is covered by this step
   together with the next vanishing theorem and `CharP.cast_eq_zero`. -/

theorem rationalGroupAlgebraCotangentGenerator_eq_zero_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] (α : ℚ) :
    rationalGroupAlgebraCotangentGenerator k α = 0 := by
  rw [← rationalGroupAlgebraCotangentGenerator_charP_step k p hp α,
    CharP.cast_eq_zero, zero_smul]

/-- In positive characteristic, `J / J²` is the zero module. -/
theorem rationalGroupAlgebraCotangent_subsingleton_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] :
    Subsingleton (rationalGroupAlgebraCotangent k) := by
  have hzero : ∀ z : rationalGroupAlgebraCotangent k, z = 0 := by
    intro z
    obtain ⟨c, hc⟩ :=
      rationalGroupAlgebraCotangent_exists_finite_linear_combination k z
    calc
      z = c.sum (fun α a => a • rationalGroupAlgebraCotangentGenerator k α) := hc
      _ = 0 := by
        simp [rationalGroupAlgebraCotangentGenerator_eq_zero_of_charP k p hp]
  exact ⟨fun z₁ z₂ => (hzero z₁).trans (hzero z₂).symm⟩

/-- The tensor-product model appearing in characteristic zero. -/
/- By symmetry of the tensor product, this is the source's `ℚ ⊗[ℤ] k` model
   with the factors ordered so that its canonical scalar action is by `k`. -/
abbrev rationalGroupAlgebraCharZeroTensor (k : Type u) [Field k] := k ⊗[ℤ] ℚ

/- Linear equivalences are data rather than propositions, so the source's
   isomorphism statements are recorded as `Nonempty` theorems. -/
/-- In characteristic zero, `J / J²` is modeled by `ℚ ⊗_ℤ k`. -/
theorem rationalGroupAlgebraCotangent_equiv_charZeroTensor
    (k : Type u) [Field k] [CharZero k] :
    Nonempty (rationalGroupAlgebraCotangent k ≃ₗ[k]
      rationalGroupAlgebraCharZeroTensor k) := by
  sorry

/-- The characteristic-zero tensor-product model is isomorphic to `k`. -/
theorem rationalGroupAlgebraCharZeroTensor_equiv_field
    (k : Type u) [Field k] [CharZero k] :
    Nonempty (rationalGroupAlgebraCharZeroTensor k ≃ₗ[k] k) := by
  sorry

/-- In characteristic zero, `J / J²` is nonzero. -/
theorem rationalGroupAlgebraCotangent_nontrivial_of_charZero
    (k : Type u) [Field k] [CharZero k] :
    Nontrivial (rationalGroupAlgebraCotangent k) := by
  sorry

/-! ## Formal smoothness and failure of flatness -/

/-- The augmentation is formally smooth in positive characteristic. -/
theorem rationalGroupAlgebraAugmentation_formallySmooth_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] :
    RingHom.FormallySmooth (rationalGroupAlgebraAugmentation k).toRingHom := by
  sorry

/-!
The source's square-zero lifting diagram is the standard lifting criterion
for the preceding declaration.  Mathlib's `Algebra.FormallySmooth` API
provides that criterion through `Algebra.FormallySmooth.iff_comp_surjective`,
so no parallel diagram structure is introduced here.
-/

/-- The element `x_2 - 1` used to witness non-flatness. -/
def rationalGroupAlgebraNonflatWitness (k : Type u) [Field k] : rationalGroupAlgebra k :=
  rationalGroupAlgebraBasisElement k (2 : ℚ) - 1

/-- The non-flatness witness is a nonzerodivisor. -/
theorem rationalGroupAlgebraNonflatWitness_isRegular
    (k : Type u) [Field k] :
    IsRegular (rationalGroupAlgebraNonflatWitness k) := by
  sorry

theorem rationalGroupAlgebraNonflatWitness_ne_zero
    (k : Type u) [Field k] :
    rationalGroupAlgebraNonflatWitness k ≠ 0 := by
  sorry

/-- The non-flatness witness maps to zero under the augmentation. -/
theorem rationalGroupAlgebraNonflatWitness_maps_to_zero
    (k : Type u) [Field k] :
    (rationalGroupAlgebraAugmentation k).toRingHom
        (rationalGroupAlgebraNonflatWitness k) = 0 := by
  sorry

/-- The augmentation is not flat. -/
theorem rationalGroupAlgebraAugmentation_not_flat (k : Type u) [Field k] :
    ¬ RingHom.Flat (rationalGroupAlgebraAugmentation k).toRingHom := by
  sorry

/-- A concrete instance of the formally smooth, non-flat ring map. -/
theorem exists_formallySmooth_nonflat_ringMap :
    ∃ f : rationalGroupAlgebra (ZMod 2) →+* ZMod 2,
      RingHom.FormallySmooth f ∧ ¬ RingHom.Flat f := by
  refine ⟨(rationalGroupAlgebraAugmentation (ZMod 2)).toRingHom, ?_, ?_⟩
  · exact rationalGroupAlgebraAugmentation_formallySmooth_of_charP
      (ZMod 2) 2 (Nat.zero_lt_succ 1)
  · exact rationalGroupAlgebraAugmentation_not_flat (ZMod 2)

end Formalization.Books.Examples.Unit41
