import Mathlib.Topology.Constructible
import Mathlib.Topology.LocallyClosed
import Mathlib.Topology.Sets.OpenCover
import Mathlib.Topology.Sober

/-!
# Topology, Chapter 15: Constructible sets

The source's constructible and locally constructible sets are represented by
Mathlib's canonical `Topology.IsConstructible` and
`Topology.IsLocallyConstructible` predicates.  Retrocompact subsets are
represented by `IsRetrocompact`; quasi-compact spaces, compact-open bases, and
the finite-intersection condition use `CompactSpace`, `PrespectralSpace`, and
`QuasiSeparatedSpace`, respectively.
-/

namespace Formalization.Books.Topology.Unit15

open Set Function _root_.Topology TopologicalSpace

universe u v

section ConstructibleSets

variable {X : Type u} [TopologicalSpace X]

/-! ### Definitions -/

/-
  `Topology.IsConstructible` is the Boolean subalgebra generated by open
  retrocompact subsets.  This is equivalent to the source's finite-union
  normal form, which is recorded below as a source-facing interface.
-/

theorem isConstructible_iff_finite_union_open_retrocompact_sdiff {E : Set X} :
    IsConstructible E ↔
      ∃ n : ℕ, ∃ U V : Fin n → Set X,
        (∀ i, IsOpen (U i) ∧ IsRetrocompact (U i)) ∧
          (∀ i, IsOpen (V i) ∧ IsRetrocompact (V i)) ∧
            E = ⋃ i, U i ∩ (V i)ᶜ := by
  sorry

/-
  `Topology.IsLocallyConstructible` is Mathlib's pointwise-neighborhood
  formulation.  The following equivalence records the source's equivalent
  open-cover formulation, where constructibility is taken in each open
  subspace.
-/

theorem isLocallyConstructible_iff_exists_isOpenCover {E : Set X} :
    IsLocallyConstructible E ↔
      ∃ (ι : Type v) (V : ι → Opens X),
        IsOpenCover V ∧
          ∀ i, IsConstructible ((Subtype.val : ↥(V i) → X) ⁻¹' E) := by
  sorry

/-! ### Boolean operations and inverse images -/

theorem isConstructible_inter_union_compl {E F : Set X}
    (hE : IsConstructible E) (hF : IsConstructible F) :
    IsConstructible (E ∩ F) ∧
      IsConstructible (E ∪ F) ∧
        IsConstructible Eᶜ := by
  sorry

theorem isConstructible_preimage_of_continuous
    {Y : Type v} [TopologicalSpace Y] (f : X → Y) (hf : Continuous f)
    {E : Set Y} (hE : IsConstructible E)
    (hpre : ∀ V : Set Y, IsOpen V → IsRetrocompact V →
      IsRetrocompact (f ⁻¹' V)) :
    IsConstructible (f ⁻¹' E) := by
  sorry

/-! ### Open and closed subspaces -/

theorem isConstructible_preimage_of_open_subspace {U : Set X}
    (hU : IsOpen U) {E : Set X} (hE : IsConstructible E) :
    IsConstructible ((Subtype.val : U → X) ⁻¹' E) := by
  sorry

theorem isConstructible_image_of_retrocompact_open {U : Set X}
    (hUopen : IsOpen U) (hUretro : IsRetrocompact U) {E : Set U}
    (hE : IsConstructible E) :
    IsConstructible (Subtype.val '' E) := by
  sorry

theorem isConstructible_iff_preimage_of_finite_retrocompact_open_cover
    {ι : Type v} [Finite ι] (V : ι → Set X)
    (hVopen : ∀ i, IsOpen (V i))
    (hVretro : ∀ i, IsRetrocompact (V i))
    (hcover : ⋃ i, V i = (Set.univ : Set X)) {E : Set X} :
    IsConstructible E ↔
      ∀ i, IsConstructible ((Subtype.val : ↥(V i) → X) ⁻¹' E) := by
  sorry

theorem isConstructible_preimage_of_closed_subspace {Z : Set X}
    (hZclosed : IsClosed Z) (hZcomp : IsCompact Zᶜ)
    {E : Set X} (hE : IsConstructible E) :
    IsConstructible ((Subtype.val : Z → X) ⁻¹' E) := by
  sorry

theorem isConstructible_preimage_of_retrocompact
    [PrespectralSpace X] {T : Set X} (hT : IsRetrocompact T)
    {E : Set X} (hE : IsConstructible E) :
    IsConstructible ((Subtype.val : T → X) ⁻¹' E) := by
  sorry

theorem isConstructible_image_of_closed_subspace {Z : Set X}
    (hZclosed : IsClosed Z) (hZcomp : IsRetrocompact Zᶜ) {E : Set Z}
    (hE : IsConstructible E) :
    IsConstructible (Subtype.val '' E) := by
  sorry

/-! ### Retrocompactness and constructible subspaces -/

theorem isRetrocompact_of_isConstructible {E : Set X}
    (hE : IsConstructible E) :
    IsRetrocompact E := by
  sorry

/-
  The source asks whether the preceding closed-subspace restriction lemma
  remains true when the ambient space is only assumed quasi-compact.  It is a
  question in the source, rather than an assertion, so no theorem is added.
-/

theorem isConstructible_preimage_of_constructible_subspace
    [PrespectralSpace X] {E E' : Set X}
    (hE : IsConstructible E) (hE' : IsConstructible E') :
    IsConstructible ((Subtype.val : E → X) ⁻¹' E') := by
  sorry

theorem isConstructible_image_of_constructible_subspace
    [PrespectralSpace X] {E : Set X} (hE : IsConstructible E)
    {F : Set E} (hF : IsConstructible F) :
    IsConstructible (Subtype.val '' F) := by
  sorry

theorem isConstructible_of_isLocallyClosed_of_isCompact_of_isRetrocompact_compl
    [CompactSpace X] [PrespectralSpace X] [QuasiSeparatedSpace X]
    {T : Set X} (hTlocallyClosed : IsLocallyClosed T)
    (hTcompact : IsCompact T) (hTcomp : IsRetrocompact Tᶜ) :
    IsConstructible T := by
  sorry

theorem isConstructible_iff_preimage_of_finite_constructible_cover
    [PrespectralSpace X] {ι : Type v} [Finite ι] (V : ι → Set X)
    (hVconstructible : ∀ i, IsConstructible (V i))
    (hcover : ⋃ i, V i = (Set.univ : Set X)) {E : Set X} :
    IsConstructible E ↔
      ∀ i, IsConstructible ((Subtype.val : ↥(V i) → X) ⁻¹' E) := by
  sorry

/-! ### Irreducible subsets and generic points -/

theorem isConstructible_isFiniteUnion_isLocallyClosed {E : Set X}
    (hE : IsConstructible E) :
    ∃ S : Set (Set X), S.Finite ∧
      (∀ T ∈ S, IsLocallyClosed T) ∧ E = ⋃₀ S := by
  sorry

theorem dense_preimage_of_finite_locallyClosed_union_iff
    {Z E : Set X} (hZ : IsIrreducible Z)
    (hE : ∃ S : Set (Set X), S.Finite ∧
      (∀ T ∈ S, IsLocallyClosed T) ∧ E = ⋃₀ S) :
    (∃ U : Set Z,
      IsOpen U ∧ Dense U ∧
        U ⊆ (Subtype.val : Z → X) ⁻¹' E) ↔
      Dense ((Subtype.val : Z → X) ⁻¹' E) := by
  sorry

theorem dense_preimage_of_finite_locallyClosed_union_iff_mem_genericPoint
    {Z E : Set X} (hZ : IsIrreducible Z)
    (hE : ∃ S : Set (Set X), S.Finite ∧
      (∀ T ∈ S, IsLocallyClosed T) ∧ E = ⋃₀ S)
    {ξ : X} (hξ : IsGenericPoint ξ Z) :
    Dense ((Subtype.val : Z → X) ⁻¹' E) ↔ ξ ∈ E := by
  sorry

end ConstructibleSets

end Formalization.Books.Topology.Unit15
