import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.LinearAlgebra.Determinant
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.RingTheory.FinitePresentation
import Formalization.Books.Algebra.Unit03.BasicNotions
import Formalization.Books.Smoothing.Unit02.SingularIdeals
import Formalization.Books.Smoothing.Unit06.LiftingLemma

/-!
# Smoothing Ring Maps, Chapter 7: The desingularization lemma

The quotient maps and polynomial construction below record the data used in
the source proofs.  The three source lemmas are stated with the canonical
`singularIdeal`, `IsStrictlyStandard`, finite-presentation, localization, and
annihilator interfaces from the preceding chapters.
-/

namespace Formalization.Books.Smoothing.Unit07

open Set
open Formalization.Books.Algebra.Unit03
open Formalization.Books.Smoothing.Unit02
open Formalization.Books.Smoothing.Unit06
open scoped BigOperators

noncomputable section

universe u v

/-! ## Quotients and the section/factorization diagrams -/

/-- The quotient of a ring by the principal ideal generated by `s ^ n`. -/
abbrev powerQuotient (S : Type u) [CommRing S] (s : S) (n : ℕ) : Type u :=
  piQuotient S (s ^ n)

/-- The quotient map to `S/(s^n)`. -/
def powerQuotientMk {S : Type u} [CommRing S] (s : S) (n : ℕ) :
    S →+* powerQuotient S s n :=
  piQuotientMk (s ^ n)

/-- The map induced on principal-power quotients by a ring map carrying `s` to
`t`.  This is the canonical quotient-map construction, rather than a second
quotient-ring API. -/
def powerQuotientMap
    {S T : Type u} [CommRing S] [CommRing T]
    {s : S} {t : T} (f : S →+* T) (h : f s = t) (n : ℕ) :
    powerQuotient S s n →+* powerQuotient T t n :=
  Ideal.quotientMap (Ideal.span ({t ^ n} : Set T)) f (by
    apply Ideal.span_le.2
    intro x hx
    have hx' : x = s ^ n := Set.mem_singleton_iff.mp hx
    subst x
    exact Ideal.mem_span_singleton'.2 ⟨1, by simp [h]⟩)

/-- The quotient of an `R`-algebra induced by its structure map. -/
def powerQuotientAlgebraMap
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
    (π : R) (n : ℕ) :
    powerQuotient R π n →+* powerQuotient A (algebraMap R A π) n :=
  powerQuotientMap (algebraMap R A) (by rfl) n

/-- The quotient map induced by an `R`-algebra map. -/
def powerQuotientAlgMap
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (φ : A →ₐ[R] Λ) (π : R) (n : ℕ) :
    powerQuotient A (algebraMap R A π) n →+*
      powerQuotient Λ (algebraMap R Λ π) n :=
  powerQuotientMap φ.toRingHom (by simp) n

/- The source's `Ann_R(Ann_R(π²)/Ann_R(π))` is the annihilator of the
canonical quotient module.  The lower annihilator is included in the upper
one; using `Submodule.comap` makes the quotient type explicit. -/
abbrev annihilatorPowerQuotient
    (R : Type u) [CommRing R] (π : R) : Type u :=
  let I₂ : Submodule R R := annihilatorOf (R := R) (M := R) (π ^ 2)
  let I₁ : Submodule R R := annihilatorOf (R := R) (M := R) π
  I₂ ⧸ Submodule.comap I₂.subtype I₁

theorem annihilatorOf_mem_pow_two
    {R : Type u} [CommRing R] (π : R) :
    annihilatorOf (R := R) (M := R) π ≤
      annihilatorOf (R := R) (M := R) (π ^ 2) := by
  intro x hx
  rw [annihilatorOf_mem_iff] at hx ⊢
  simpa [smul_eq_mul, pow_two, mul_assoc] using congrArg (fun y : R => y * π) hx

/-- The ideal `Ann_R(Ann_R(π²)/Ann_R(π))` appearing in the lemma. -/
def desingularizationAnnihilatorIdeal
    (R : Type u) [CommRing R] (π : R) : Ideal R :=
  Module.annihilator R (annihilatorPowerQuotient R π)

/-- A section of `R/(π^n) → A/(π^n A)` compatible with a map to `Λ/(π^nΛ)`.
The word “section” records the left-inverse equation explicitly. -/
structure DesingularizationSection
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (π : R) (φ : A →ₐ[R] Λ) (n : ℕ) where
  sectionMap :
    powerQuotient A (algebraMap R A π) n →+* powerQuotient R π n
  isSection :
    sectionMap.comp (powerQuotientAlgebraMap π n) =
      RingHom.id (powerQuotient R π n)
  compatible :
    powerQuotientAlgMap φ π n =
      (powerQuotientAlgebraMap (R := R) (A := Λ) π n).comp sectionMap

/-- A map between two principal-power quotients compatible with the two maps
to `Λ/(π^nΛ)`. -/
structure DesingularizationModPowerMap
    {R A D Λ : Type u} [CommRing R] [CommRing A] [CommRing D] [CommRing Λ]
    [Algebra R A] [Algebra R D] [Algebra R Λ]
    (π : R) (φA : A →ₐ[R] Λ) (φD : D →ₐ[R] Λ) (n : ℕ) where
  quotientMap :
    powerQuotient A (algebraMap R A π) n →+*
      powerQuotient D (algebraMap R D π) n
  compatibleWithBase :
    quotientMap.comp (powerQuotientAlgebraMap (R := R) (A := A) π n) =
      powerQuotientAlgebraMap (R := R) (A := D) π n
  compatibleWithLambda :
    powerQuotientAlgMap φA π n =
      (powerQuotientAlgMap φD π n).comp quotientMap

/-- The factorization `A/(π^nA) → Cbar → Λ/(π^nΛ)` used in the last lemma,
with the base-ring and original-map compatibilities written as equations of
ring homomorphisms. -/
structure DesingularizationModPowerFactorization
    {R A C Λ : Type u} [CommRing R] [CommRing A] [CommRing C] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (π : R) (φ : A →ₐ[R] Λ) (n : ℕ)
    [Algebra (powerQuotient R π n) C] where
  toC : powerQuotient A (algebraMap R A π) n →+* C
  toC_over_base :
    toC.comp (powerQuotientAlgebraMap (R := R) (A := A) π n) =
      algebraMap (powerQuotient R π n) C
  toLambda : C →+* powerQuotient Λ (algebraMap R Λ π) n
  toLambda_over_base :
    toLambda.comp (algebraMap (powerQuotient R π n) C) =
      powerQuotientAlgebraMap (R := R) (A := Λ) π n
  factorization :
    toLambda.comp toC = powerQuotientAlgMap φ π n

/-- The index `c+j` of an unselected relation in a presentation with `m`
relations and `c` selected ones. -/
def desingularizationUnselectedIndex
    {m c : ℕ} (hcm : c ≤ m) (j : Fin (m - c)) : Fin m :=
  Fin.cast (Nat.add_sub_of_le hcm) (Fin.natAdd c j)

/-- The ideal generated by the selected first `c` relations. -/
def desingularizationSelectedRelationIdeal
    {A : Type u} [CommRing A] {m c : ℕ} (hcm : c ≤ m)
    (relations : Fin m → A) : Ideal A :=
  Ideal.span (Set.range (fun j : Fin c => relations (Fin.castLE hcm j)))

/- The source's displayed `(★)` condition in the presentation ring.  The
relations are polynomials before passing to the quotient presenting `A`; using
their classes in `A` would make both sides of the condition vanish. -/
def DesingularizationStarCondition
    {R P : Type u} [CommRing R] [CommRing P] [Algebra R P]
    {m c : ℕ} (hcm : c ≤ m) (π : R) (relations : Fin m → P) : Prop :=
  ∀ j : Fin (m - c),
    algebraMap R P π * relations (desingularizationUnselectedIndex hcm j) ∈
      desingularizationSelectedRelationIdeal hcm relations +
        (Ideal.span (Set.range relations)) ^ 2

/-! ## The polynomial construction in the proof of the first lemma -/

/-- The polynomial ring in the `x`, `v`, and `w` variables of the source
construction. -/
abbrev desingularizationPolynomial (R : Type u) [CommRing R]
    (n c : ℕ) : Type u :=
  MvPolynomial (Fin n ⊕ (Fin c ⊕ Fin n)) R

/-- Inclusion of the `x`-polynomial ring into the auxiliary polynomial ring. -/
def desingularizationLiftX
    {R : Type u} [CommRing R] {n c : ℕ}
    (f : MvPolynomial (Fin n) R) : desingularizationPolynomial R n c :=
  MvPolynomial.rename (fun i => Sum.inl i) f

/-- Inclusion of the `v,w`-polynomial ring into the auxiliary polynomial ring. -/
def desingularizationLiftVW
    {R : Type u} [CommRing R] {n c : ℕ}
    (f : MvPolynomial (Fin c ⊕ Fin n) R) : desingularizationPolynomial R n c :=
  MvPolynomial.rename (fun i => Sum.inr i) f

/-- The relation `h_i = x_i - π² Σ_j s_{ij}v_j - π³w_i`. -/
def desingularizationAuxiliaryRelation
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (s : Fin n → Fin c → R) (i : Fin n) :
    desingularizationPolynomial R n c :=
  desingularizationLiftX (MvPolynomial.X i) -
      MvPolynomial.C (π ^ 2) *
        ∑ j : Fin c,
          MvPolynomial.C (s i j) *
            MvPolynomial.X (Sum.inr (Sum.inl j)) -
      MvPolynomial.C (π ^ 3) *
        MvPolynomial.X (Sum.inr (Sum.inr i))

/-- The quotient of the full polynomial ring by the auxiliary relations
`h_i`.  The source identifies this ring with the polynomial ring in `v,w`. -/
abbrev desingularizationAuxiliaryRelationQuotient
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (s : Fin n → Fin c → R) : Type u :=
  desingularizationPolynomial R n c ⧸
    Ideal.span (Set.range (desingularizationAuxiliaryRelation π s))

/-- The ideal generated by the original relations, the `h_i`, and the
chosen `g_j` relations. -/
def desingularizationDefiningIdeal
    {R : Type u} [CommRing R] {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) :
    Ideal (desingularizationPolynomial R n c) :=
  Ideal.span
    (Set.range (fun j : Fin m => desingularizationLiftX (relations j)) ∪
      Set.range (desingularizationAuxiliaryRelation π s) ∪
      Set.range (fun j : Fin c => desingularizationLiftVW (corrections j)))

/-- The auxiliary ring `B' = R[v,w]/(g_1, ..., g_c)` used in the local
smoothness argument. -/
abbrev desingularizationAuxiliaryRing
    {R : Type u} [CommRing R] {n c : ℕ}
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) : Type u :=
  MvPolynomial (Fin c ⊕ Fin n) R ⧸ Ideal.span (Set.range corrections)

/-- Modulo `π`, the auxiliary ring is a polynomial ring in the `w` variables;
the displayed equivalence is the source's `B'/πB'` calculation. -/
theorem desingularizationAuxiliaryRing_mod_pi_equiv
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R)
    (linearCoefficients : Fin c → Fin n → R)
    (hmod : ∀ j : Fin c,
      corrections j -
          (MvPolynomial.X (Sum.inl j) +
            ∑ i : Fin n,
              MvPolynomial.C (linearCoefficients j i) *
                MvPolynomial.X (Sum.inr i)) ∈
        Ideal.span ({MvPolynomial.C π} :
          Set (MvPolynomial (Fin c ⊕ Fin n) R))) :
    Nonempty
      (powerQuotient (desingularizationAuxiliaryRing corrections)
          (algebraMap R (desingularizationAuxiliaryRing corrections) π) 1 ≃+*
        MvPolynomial (Fin n) (powerQuotient R π 1)) := by
  classical
  let P := MvPolynomial (Fin c ⊕ Fin n) R
  let A := powerQuotient R π 1
  let W := MvPolynomial (Fin n) A
  let I : Ideal P := Ideal.span (Set.range corrections)
  let coeff : R →+* W :=
    (MvPolynomial.C : A →+* W).comp (show R →+* A from powerQuotientMk π 1)
  let vars : Fin c ⊕ Fin n → W := fun z => match z with
    | Sum.inl j =>
        -∑ i : Fin n,
          MvPolynomial.C (powerQuotientMk π 1 (linearCoefficients j i)) *
            MvPolynomial.X i
    | Sum.inr i => MvPolynomial.X i
  let pmap : P →+* W := MvPolynomial.eval₂Hom coeff vars
  have pmap_C (r : R) : pmap (MvPolynomial.C r) = coeff r := by
    change MvPolynomial.eval₂Hom coeff vars (MvPolynomial.C r) = coeff r
    exact MvPolynomial.eval₂Hom_C coeff vars r
  have pmap_X (z : Fin c ⊕ Fin n) : pmap (MvPolynomial.X z) = vars z := by
    change MvPolynomial.eval₂Hom coeff vars (MvPolynomial.X z) = vars z
    exact MvPolynomial.eval₂Hom_X' coeff vars z
  have hp_pi : pmap (MvPolynomial.C π) = 0 := by
    rw [pmap_C]
    have hq : (powerQuotientMk π 1) π = 0 := by
      apply Ideal.Quotient.eq_zero_iff_mem.2
      change π ∈ Ideal.span ({π ^ 1} : Set R)
      rw [pow_one]
      exact Ideal.subset_span (Set.mem_singleton π)
    change (MvPolynomial.C : A →+* W) ((powerQuotientMk π 1) π) = 0
    rw [hq]
    exact (MvPolynomial.C : A →+* W).map_zero
  have hp_linear (j : Fin c) :
      pmap (MvPolynomial.X (Sum.inl j) +
        ∑ i : Fin n,
          MvPolynomial.C (linearCoefficients j i) *
            MvPolynomial.X (Sum.inr i)) = 0 := by
    rw [map_add, pmap_X]
    simp_rw [map_sum, map_mul, pmap_C, pmap_X]
    simp only [vars]
    change -(∑ i : Fin n,
        MvPolynomial.C (powerQuotientMk π 1 (linearCoefficients j i)) *
          MvPolynomial.X i) +
      ∑ i : Fin n,
        MvPolynomial.C (powerQuotientMk π 1 (linearCoefficients j i)) *
          MvPolynomial.X i = 0
    exact neg_add_cancel _
  have hp_correction : ∀ j : Fin c, pmap (corrections j) = 0 := by
    intro j
    have hzero := show pmap (corrections j -
        (MvPolynomial.X (Sum.inl j) +
          ∑ i : Fin n,
            MvPolynomial.C (linearCoefficients j i) *
              MvPolynomial.X (Sum.inr i))) = 0 from by
      apply (show Ideal.span ({MvPolynomial.C π} : Set P) ≤
          RingHom.ker pmap from ?_) (hmod j)
      apply Ideal.span_le.2
      rintro _ ⟨rfl⟩
      exact hp_pi
    rw [map_sub] at hzero
    exact (sub_eq_zero.mp hzero).trans (hp_linear j)
  have hpI : ∀ a : P, a ∈ I → pmap a = 0 := by
    intro a ha
    apply (show I ≤ RingHom.ker pmap from ?_) ha
    apply Ideal.span_le.2
    rintro _ ⟨j, rfl⟩
    exact hp_correction j
  let fB : (P ⧸ I) →+* W := Ideal.Quotient.lift I pmap hpI
  have hfB_pi : fB (algebraMap R (P ⧸ I) π) = 0 := by
    change fB (Ideal.Quotient.mk I (MvPolynomial.C π)) = 0
    rw [Ideal.Quotient.lift_mk]
    exact hp_pi
  let fQ : powerQuotient (P ⧸ I) (algebraMap R (P ⧸ I) π) 1 →+* W :=
    Ideal.Quotient.lift _ fB (by
      intro a ha
      rw [Ideal.mem_span_singleton'] at ha
      rcases ha with ⟨r, rfl⟩
      simp only [map_mul, pow_one]
      simp [hfB_pi])
  let coeffA : A →+*
      powerQuotient (P ⧸ I) (algebraMap R (P ⧸ I) π) 1 :=
    powerQuotientAlgebraMap (R := R) (A := P ⧸ I) π 1
  let gmap : W →+*
      powerQuotient (P ⧸ I) (algebraMap R (P ⧸ I) π) 1 :=
    MvPolynomial.eval₂Hom coeffA
      (fun i => Ideal.Quotient.mk _
        (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inr i))))
  have gmap_C (a : A) : gmap (MvPolynomial.C a) = coeffA a := by
    change MvPolynomial.eval₂Hom coeffA _ (MvPolynomial.C a) = coeffA a
    exact MvPolynomial.eval₂Hom_C coeffA _ a
  have gmap_X (i : Fin n) :
      gmap (MvPolynomial.X i) =
        Ideal.Quotient.mk _ (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inr i))) := by
    change MvPolynomial.eval₂Hom coeffA _ (MvPolynomial.X i) = _
    exact MvPolynomial.eval₂Hom_X' coeffA _ i
  refine ⟨(RingEquiv.ofRingHom fQ gmap ?_ ?_)⟩
  · apply MvPolynomial.ringHom_ext'
    · apply RingHom.ext
      intro a
      change fQ (gmap (MvPolynomial.C a)) =
        (MvPolynomial.C : A →+* W) a
      rw [gmap_C]
      exact Quotient.inductionOn' a (fun r => by
        change fQ (coeffA ((powerQuotientMk π 1) r)) =
          (MvPolynomial.C : A →+* W) ((powerQuotientMk π 1) r)
        change fQ (Ideal.Quotient.mk _
          (Ideal.Quotient.mk I (MvPolynomial.C r))) = _
        rw [Ideal.Quotient.lift_mk, Ideal.Quotient.lift_mk, pmap_C]
        rfl)
    · intro i
      change fQ (gmap (MvPolynomial.X i)) = MvPolynomial.X i
      rw [gmap_X]
      rw [Ideal.Quotient.lift_mk, Ideal.Quotient.lift_mk, pmap_X]
  · apply Ideal.Quotient.ringHom_ext
    · apply Ideal.Quotient.ringHom_ext
      apply MvPolynomial.ringHom_ext'
      · apply RingHom.ext
        intro r
        change gmap (fQ (Ideal.Quotient.mk _
          (Ideal.Quotient.mk I (MvPolynomial.C r)))) =
          Ideal.Quotient.mk _ (Ideal.Quotient.mk I (MvPolynomial.C r))
        rw [Ideal.Quotient.lift_mk, Ideal.Quotient.lift_mk, pmap_C]
        change gmap (MvPolynomial.C (powerQuotientMk π 1 r)) = _
        rw [gmap_C]
        rfl
      · intro z
        cases z with
        | inl j =>
            change gmap (fQ (Ideal.Quotient.mk _
              (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inl j))))) =
              Ideal.Quotient.mk _ (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inl j)))
            rw [Ideal.Quotient.lift_mk, Ideal.Quotient.lift_mk, pmap_X]
            have hzero : Ideal.Quotient.mk
                (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                (Ideal.Quotient.mk I
                (corrections j -
                  (MvPolynomial.X (Sum.inl j) +
                    ∑ i : Fin n,
                      MvPolynomial.C (linearCoefficients j i) *
                        MvPolynomial.X (Sum.inr i)))) = 0 := by
              rcases Ideal.mem_span_singleton'.1 (hmod j) with ⟨r, hr⟩
              apply Ideal.Quotient.eq_zero_iff_mem.2
              rw [← hr, Ideal.mem_span_singleton']
              refine ⟨Ideal.Quotient.mk I r, ?_⟩
              rw [map_mul]
              rw [show Ideal.Quotient.mk I (MvPolynomial.C π) =
                algebraMap R (P ⧸ I) π by rfl]
              simp [pow_one, mul_comm]
            have hcorrection :
                Ideal.Quotient.mk
                    (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                    (Ideal.Quotient.mk I (corrections j)) = 0 := by
              have hcorrection0 : Ideal.Quotient.mk I (corrections j) = 0 := by
                apply Ideal.Quotient.eq_zero_iff_mem.2
                exact Ideal.subset_span (Set.mem_range_self j)
              rw [hcorrection0]
              exact map_zero _
            have hsum :
                Ideal.Quotient.mk
                    (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                    (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inl j))) +
                  ∑ i : Fin n,
                    Ideal.Quotient.mk
                      (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                      (Ideal.Quotient.mk I
                      (MvPolynomial.C (linearCoefficients j i) *
                        MvPolynomial.X (Sum.inr i))) = 0 := by
              have h := hzero
              simp only [map_sub, map_add, map_sum] at h
              rw [hcorrection] at h
              have h' : 0 -
                  (Ideal.Quotient.mk
                      (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                      (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inl j))) +
                    ∑ i : Fin n,
                      Ideal.Quotient.mk
                        (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                        (Ideal.Quotient.mk I
                          (MvPolynomial.C (linearCoefficients j i) *
                            MvPolynomial.X (Sum.inr i)))) = 0 := by
                simpa only [hcorrection] using h
              have h'' : -
                  (Ideal.Quotient.mk
                      (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                      (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inl j))) +
                    ∑ i : Fin n,
                      Ideal.Quotient.mk
                        (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                        (Ideal.Quotient.mk I
                          (MvPolynomial.C (linearCoefficients j i) *
                            MvPolynomial.X (Sum.inr i)))) = 0 := by
                simpa only [zero_sub] using h'
              exact neg_eq_zero.mp h''
            have hmap :
                gmap (vars (Sum.inl j)) =
                  -∑ i : Fin n,
                    Ideal.Quotient.mk
                      (Ideal.span ({(algebraMap R (P ⧸ I) π) ^ 1} : Set (P ⧸ I)))
                      (Ideal.Quotient.mk I
                        (MvPolynomial.C (linearCoefficients j i) *
                          MvPolynomial.X (Sum.inr i))) := by
              change gmap (-∑ i : Fin n,
                MvPolynomial.C (powerQuotientMk π 1 (linearCoefficients j i)) *
                  MvPolynomial.X i) = _
              rw [map_neg, map_sum]
              simp_rw [map_mul, gmap_C, gmap_X]
              rfl
            rw [hmap]
            symm
            apply sub_eq_zero.mp
            simpa [sub_eq_add_neg] using hsum
        | inr i =>
            change gmap (fQ (Ideal.Quotient.mk _
              (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inr i))))) =
              Ideal.Quotient.mk _ (Ideal.Quotient.mk I (MvPolynomial.X (Sum.inr i)))
            rw [Ideal.Quotient.lift_mk, Ideal.Quotient.lift_mk, pmap_X]
            change gmap (MvPolynomial.X i) = _
            rw [gmap_X]

/-- Every prime of `B'` containing `π` is a smooth point of `B'` over `R`.
This is the source's smoothness-on-`V(π)` assertion. -/
theorem desingularizationAuxiliaryRing_smoothAt_of_pi_mem
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R)
    (linearCoefficients : Fin c → Fin n → R)
    (hmod : ∀ j : Fin c,
      corrections j -
          (MvPolynomial.X (Sum.inl j) +
            ∑ i : Fin n,
              MvPolynomial.C (linearCoefficients j i) *
                MvPolynomial.X (Sum.inr i)) ∈
        Ideal.span ({MvPolynomial.C π} :
          Set (MvPolynomial (Fin c ⊕ Fin n) R))) :
    ∀ q : PrimeSpectrum (desingularizationAuxiliaryRing corrections),
      algebraMap R (desingularizationAuxiliaryRing corrections) π ∈ q.asIdeal →
      Formalization.Books.Algebra.Unit137.IsSmoothAt R
        (desingularizationAuxiliaryRing corrections) q := by
  classical
  intro q hq
  let P := MvPolynomial (Fin c ⊕ Fin n) R
  let I : Ideal P := Ideal.span (Set.range corrections)
  let ρ : P →+* (P ⧸ I) := Ideal.Quotient.mk I
  let K : Ideal P := Ideal.comap ρ q.asIdeal
  have hCπ : MvPolynomial.C π ∈ K := by
    change ρ (MvPolynomial.C π) ∈ q.asIdeal
    change algebraMap R (P ⧸ I) π ∈ q.asIdeal
    exact hq
  have hderiv (j i : Fin c) :
      MvPolynomial.pderiv (Sum.inl i) (corrections j) -
          (if i = j then 1 else 0) ∈ K := by
    rcases Ideal.mem_span_singleton'.1 (hmod j) with ⟨r, hr⟩
    have hdiff :
        MvPolynomial.pderiv (Sum.inl i) (r * MvPolynomial.C π) =
          MvPolynomial.pderiv (Sum.inl i) (corrections j) -
            MvPolynomial.pderiv (Sum.inl i)
              (MvPolynomial.X (Sum.inl j) +
                ∑ k : Fin n,
                  MvPolynomial.C (linearCoefficients j k) *
                    MvPolynomial.X (Sum.inr k)) := by
      simpa only [map_sub] using
        congrArg (fun f => MvPolynomial.pderiv (Sum.inl i) f) hr
    have hlinear :
        MvPolynomial.pderiv (Sum.inl i)
            (MvPolynomial.X (Sum.inl j) +
              ∑ k : Fin n,
                MvPolynomial.C (linearCoefficients j k) *
                  MvPolynomial.X (Sum.inr k)) =
          (if i = j then 1 else 0) := by
      simp [Pi.single_apply, eq_comm]
    have hprod : MvPolynomial.pderiv (Sum.inl i) (r * MvPolynomial.C π) ∈ K := by
      rw [MvPolynomial.pderiv_mul, MvPolynomial.pderiv_C, mul_zero, add_zero]
      exact K.mul_mem_left _ hCπ
    rw [← hlinear, ← hdiff]
    exact hprod
  let P₀ : Algebra.PreSubmersivePresentation R
      (MvPolynomial (Fin c ⊕ Fin n) R ⧸
        Ideal.span (Set.range corrections)) (Fin c ⊕ Fin n) (Fin c) :=
    Algebra.PreSubmersivePresentation.naive (v := corrections)
      (fun j : Fin c => Sum.inl j) (by
        intro j k h
        exact Sum.inl.inj h)
  let g : desingularizationAuxiliaryRing corrections := P₀.jacobian
  let κ : (P ⧸ I) →+* q.asIdeal.ResidueField :=
    algebraMap (P ⧸ I) q.asIdeal.ResidueField
  have hmatrix :
      (fun j i => κ (ρ (MvPolynomial.pderiv (Sum.inl i) (corrections j)))) =
        (1 : Matrix (Fin c) (Fin c) q.asIdeal.ResidueField) := by
    ext j i
    rw [Matrix.one_apply]
    have hz :
        κ (ρ (MvPolynomial.pderiv (Sum.inl i) (corrections j) -
          (if i = j then 1 else 0))) = 0 := by
      apply Ideal.algebraMap_residueField_eq_zero.mpr
      change ρ (MvPolynomial.pderiv (Sum.inl i) (corrections j) -
        (if i = j then 1 else 0)) ∈ q.asIdeal
      exact hderiv j i
    rw [map_sub, map_sub] at hz
    have hh := sub_eq_zero.mp hz
    by_cases hji : j = i
    · subst j
      have hconst : (if i = i then (1 : P) else 0) = 1 := if_pos rfl
      rw [hconst] at hh
      rw [if_pos rfl]
      calc
        _ = κ (ρ 1) := hh
        _ = κ 1 := by rw [map_one]
        _ = 1 := κ.map_one
    · have hij : ¬ i = j := by
        intro h
        exact hji h.symm
      have hconst : (if i = j then (1 : P) else 0) = 0 := if_neg hij
      rw [hconst] at hh
      rw [if_neg hji]
      calc
        _ = κ (ρ 0) := hh
        _ = κ 0 := by rw [map_zero]
        _ = 0 := κ.map_zero
  have hgmod : κ g = 1 := by
    rw [show g = P₀.jacobian by rfl]
    rw [P₀.jacobian_eq_jacobiMatrix_det]
    have hmat :
        (κ.comp (algebraMap P₀.Ring
          (desingularizationAuxiliaryRing corrections))).mapMatrix P₀.jacobiMatrix =
          (1 : Matrix (Fin c) (Fin c)
            q.asIdeal.ResidueField) := by
      ext j i
      change κ (algebraMap P₀.Ring
        (desingularizationAuxiliaryRing corrections) (P₀.jacobiMatrix j i)) =
        (1 : Matrix (Fin c) (Fin c) q.asIdeal.ResidueField) j i
      rw [Algebra.PreSubmersivePresentation.jacobiMatrix_apply]
      change κ (ρ (MvPolynomial.pderiv (Sum.inl j) (corrections i))) =
        if j = i then 1 else 0
      by_cases hji : j = i
      · subst j
        simpa only [Matrix.one_apply, if_pos rfl] using
          congrFun (congrFun hmatrix i) i
      · have hij : ¬ i = j := by
          intro h
          exact hji h.symm
        have hh := congrFun (congrFun hmatrix i) j
        rw [Matrix.one_apply, if_neg hij] at hh
        simpa only [if_neg hji] using hh
    change (κ.comp (algebraMap P₀.Ring
      (desingularizationAuxiliaryRing corrections))) P₀.jacobiMatrix.det = 1
    calc
      _ = ((κ.comp (algebraMap P₀.Ring
          (desingularizationAuxiliaryRing corrections))).mapMatrix
            P₀.jacobiMatrix).det := by
        exact RingHom.map_det
          (κ.comp (algebraMap P₀.Ring
            (desingularizationAuxiliaryRing corrections))) P₀.jacobiMatrix
      _ = 1 := by rw [hmat, Matrix.det_one]
  have hg : g ∉ q.asIdeal := by
    intro h
    have hz : κ g = 0 := Ideal.algebraMap_residueField_eq_zero.mpr h
    rw [hgmod] at hz
    exact one_ne_zero hz
  let Q₀ : Algebra.PreSubmersivePresentation
      (desingularizationAuxiliaryRing corrections) (Localization.Away g) Unit Unit :=
    Algebra.PreSubmersivePresentation.localizationAway
      (S := Localization.Away g) g
  let C₀ := Q₀.comp P₀
  let C : Algebra.SubmersivePresentation R (Localization.Away g)
      (Unit ⊕ (Fin c ⊕ Fin n)) (Unit ⊕ Fin c) := {
    toPreSubmersivePresentation := C₀
    jacobian_isUnit := by
      rw [Algebra.PreSubmersivePresentation.comp_jacobian_eq_jacobian_smul_jacobian]
      rw [Algebra.smul_def]
      have hu : IsUnit
          (algebraMap (desingularizationAuxiliaryRing corrections)
            (Localization.Away g) g) :=
        IsLocalization.Away.algebraMap_isUnit (S := Localization.Away g) g
      have hu' : IsUnit
          (algebraMap (desingularizationAuxiliaryRing corrections)
            (Localization.Away g) P₀.jacobian) := by
        simpa [g] using hu
      have hQ : IsUnit Q₀.jacobian := by
        have hQeq : Q₀.jacobian =
            algebraMap (desingularizationAuxiliaryRing corrections)
              (Localization.Away g) g := by
          change (Algebra.PreSubmersivePresentation.localizationAway
            (S := Localization.Away g) g).jacobian = _
          exact Algebra.PreSubmersivePresentation.localizationAway_jacobian
            (S := Localization.Away g) g
        rw [hQeq]
        exact hu
      exact hu'.mul hQ
  }
  exact ⟨g, hg, @Formalization.Books.Algebra.Unit137.standard_smooth_is_smooth
    R (Localization.Away g) _ _ _ C.isStandardSmooth⟩

/-- The finitely presented ring `B` displayed in the proof. -/
abbrev desingularizationConstructionRing
    {R : Type u} [CommRing R] {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) : Type u :=
  desingularizationPolynomial R n c ⧸
    desingularizationDefiningIdeal π relations s corrections

/-- The presented algebra `A = R[x]/(f)` used in the construction. -/
abbrev desingularizationPresentedAlgebra
    {R : Type u} [CommRing R] {n m : ℕ}
    (relations : Fin m → MvPolynomial (Fin n) R) : Type u :=
  MvPolynomial (Fin n) R ⧸ Ideal.span (Set.range relations)

/-- The finite-index form of the determinant identity after applying the
section to the strict-standard identity.  Embeddings encode the selected
variable subsets used by the source. -/
structure DesingularizationJacobianWitness
    (R : Type u) [CommRing R] (π : R) (n c : ℕ) where
  c_le_n : c ≤ n
  linearCoefficients : Fin c → Fin n → R
  coefficient : (Fin c ↪ Fin n) → R
  unit : R
  unit_congruent : ∃ t : R, unit = 1 + π ^ 3 * t
  jacobian_identity :
    unit * π =
      ∑ e : Fin c ↪ Fin n,
        coefficient e *
          Matrix.det (fun j i => linearCoefficients j (e i))
  inverse_coefficients : Fin n → Fin c → R
  matrix_left_inverse :
    ∀ j k : Fin c,
      unit * π * (if j = k then 1 else 0) =
        ∑ i : Fin n,
          linearCoefficients j i * inverse_coefficients i k

/-- The relation and correction identities used after introducing `v,w`. -/
structure DesingularizationPolynomialData
    (R : Type u) [CommRing R] (π : R) (n m c : ℕ) where
  relations : Fin m → MvPolynomial (Fin n) R
  c_le_m : c ≤ m
  /-- The source's displayed (★) condition for the unselected relations. -/
  starCondition :
    DesingularizationStarCondition c_le_m π relations
  witness : DesingularizationJacobianWitness R π n c
  corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R
  relation_identity :
    ∀ j : Fin c,
      desingularizationLiftX (relations (Fin.castLE c_le_m j)) -
          MvPolynomial.C (π ^ 3) * desingularizationLiftVW (corrections j) ∈
        Ideal.span (Set.range
          (desingularizationAuxiliaryRelation π
            (fun i j => witness.inverse_coefficients i j)))
  correction_identity_mod_pi :
    ∀ j : Fin c,
      corrections j -
          (MvPolynomial.X (Sum.inl j) +
            ∑ i : Fin n,
              MvPolynomial.C (witness.linearCoefficients j i) *
                MvPolynomial.X (Sum.inr i)) ∈
        Ideal.span ({MvPolynomial.C π} :
          Set (MvPolynomial (Fin c ⊕ Fin n) R))

/-- The evaluation values `x_i ↦ π⁴λ_i`, `v_j ↦ 0`, and
`w_i ↦ πλ_i` from the map `B → Λ` in the proof. -/
def desingularizationEvaluationValues
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {n c : ℕ} (π : R) (lambdaValues : Fin n → Λ) :
    Fin n ⊕ (Fin c ⊕ Fin n) → Λ
  | Sum.inl i => (algebraMap R Λ π) ^ 4 * lambdaValues i
  | Sum.inr (Sum.inl _) => 0
  | Sum.inr (Sum.inr i) => algebraMap R Λ π * lambdaValues i

/-- The polynomial evaluation attached to those values. -/
def desingularizationEvaluation
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {n c : ℕ} (π : R) (lambdaValues : Fin n → Λ) :
    desingularizationPolynomial R n c →ₐ[R] Λ :=
  MvPolynomial.aeval (desingularizationEvaluationValues π lambdaValues)

/-- The quotient by the `h_i` is the polynomial ring in the remaining
`v,w` variables, as used in the first displayed simplification in the proof.
The equivalence is recorded in the direction that exposes those variables. -/
theorem desingularizationAuxiliaryRelationQuotient_equiv
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (s : Fin n → Fin c → R) :
    Nonempty
      (desingularizationAuxiliaryRelationQuotient π s ≃+*
        MvPolynomial (Fin c ⊕ Fin n) R) := by
  classical
  let P := desingularizationPolynomial R n c
  let Q := MvPolynomial (Fin c ⊕ Fin n) R
  let I : Ideal P := Ideal.span (Set.range (desingularizationAuxiliaryRelation π s))
  let pmap : P →ₐ[R] Q := MvPolynomial.aeval (fun z : Fin n ⊕ (Fin c ⊕ Fin n) =>
    match z with
    | Sum.inl i =>
        MvPolynomial.C (π ^ 2) *
            ∑ j : Fin c, MvPolynomial.C (s i j) * MvPolynomial.X (Sum.inl j) +
          MvPolynomial.C (π ^ 3) * MvPolynomial.X (Sum.inr i)
    | Sum.inr z => MvPolynomial.X z)
  have hpmap : ∀ a : P, a ∈ I → pmap a = 0 := by
    intro a ha
    apply (show I ≤ RingHom.ker pmap.toRingHom from ?_) ha
    apply Ideal.span_le.2
    rintro _ ⟨i, rfl⟩
    change MvPolynomial.aeval _ (desingularizationAuxiliaryRelation π s i) = 0
    simp only [desingularizationAuxiliaryRelation, desingularizationLiftX,
      MvPolynomial.rename_X, map_sub, map_mul, map_sum, MvPolynomial.aeval_X,
      MvPolynomial.aeval_C]
    rw [show algebraMap R Q = MvPolynomial.C from
      MvPolynomial.algebraMap_eq R (Fin c ⊕ Fin n)]
    simp only [map_pow]
    ring
  let qmap : P ⧸ I →ₐ[R] Q := Ideal.Quotient.liftₐ I pmap hpmap
  let gmap : Q →ₐ[R] P ⧸ I := MvPolynomial.aeval (fun z : Fin c ⊕ Fin n =>
    Ideal.Quotient.mkₐ R I (desingularizationLiftVW (n := n) (MvPolynomial.X z)))
  have hqg : qmap.comp gmap = AlgHom.id R Q := by
    have hqcomp : qmap.comp (Ideal.Quotient.mkₐ R I) = pmap :=
      Ideal.Quotient.liftₐ_comp I pmap hpmap
    apply MvPolynomial.algHom_ext
    intro z
    change qmap (gmap (MvPolynomial.X z)) = MvPolynomial.X z
    rw [show gmap (MvPolynomial.X z) =
      Ideal.Quotient.mkₐ R I (desingularizationLiftVW (n := n) (MvPolynomial.X z)) by
        change MvPolynomial.aeval _ (MvPolynomial.X z) = _
        rw [MvPolynomial.aeval_X]]
    calc
      qmap (Ideal.Quotient.mkₐ R I (desingularizationLiftVW (n := n) (MvPolynomial.X z))) =
          pmap (desingularizationLiftVW (n := n) (MvPolynomial.X z)) :=
        AlgHom.congr_fun hqcomp _
      _ = MvPolynomial.X z := by
        change MvPolynomial.aeval _ (desingularizationLiftVW (n := n) (MvPolynomial.X z)) = _
        rw [desingularizationLiftVW, MvPolynomial.rename_X, MvPolynomial.aeval_X]
  have hleft : gmap.comp qmap = AlgHom.id R (P ⧸ I) := by
    apply Ideal.Quotient.algHom_ext R
    simp only [AlgHom.comp_assoc, qmap, Ideal.Quotient.liftₐ_comp]
    apply MvPolynomial.algHom_ext
    intro z
    cases z with
    | inr z =>
        change gmap (pmap (MvPolynomial.X (Sum.inr z))) =
          Ideal.Quotient.mkₐ R I (MvPolynomial.X (Sum.inr z))
        change gmap (MvPolynomial.aeval _ (MvPolynomial.X (Sum.inr z))) = _
        rw [MvPolynomial.aeval_X]
        change MvPolynomial.aeval _ (MvPolynomial.X z) = _
        rw [MvPolynomial.aeval_X]
        rw [desingularizationLiftVW, MvPolynomial.rename_X]
    | inl i =>
        let exprP : P :=
          MvPolynomial.C (π ^ 2) *
              ∑ j : Fin c, MvPolynomial.C (s i j) *
                MvPolynomial.X (Sum.inr (Sum.inl j)) +
            MvPolynomial.C (π ^ 3) *
              MvPolynomial.X (Sum.inr (Sum.inr i))
        let exprQ : Q :=
          MvPolynomial.C (π ^ 2) *
              ∑ j : Fin c, MvPolynomial.C (s i j) * MvPolynomial.X (Sum.inl j) +
            MvPolynomial.C (π ^ 3) * MvPolynomial.X (Sum.inr i)
        change gmap (pmap (MvPolynomial.X (Sum.inl i))) =
          Ideal.Quotient.mkₐ R I (MvPolynomial.X (Sum.inl i))
        have hpX : pmap (MvPolynomial.X (Sum.inl i)) = exprQ := by
          change MvPolynomial.aeval _ (MvPolynomial.X (Sum.inl i)) = exprQ
          rw [MvPolynomial.aeval_X]
        have hi' : Ideal.Quotient.mk I (MvPolynomial.X (Sum.inl i)) =
            Ideal.Quotient.mk I exprP := by
          apply sub_eq_zero.mp
          rw [← map_sub]
          apply Ideal.Quotient.eq_zero_iff_mem.2
          rw [show MvPolynomial.X (Sum.inl i) - exprP =
              desingularizationAuxiliaryRelation π s i by
            dsimp [exprP, desingularizationAuxiliaryRelation, desingularizationLiftX,
              desingularizationLiftVW]
            rw [MvPolynomial.rename_X]
            ring]
          exact Ideal.subset_span (Set.mem_range_self i)
        have hgexpr : gmap exprQ = Ideal.Quotient.mk I exprP := by
          change MvPolynomial.aeval _ (
              MvPolynomial.C (π ^ 2) *
                  ∑ j : Fin c, MvPolynomial.C (s i j) * MvPolynomial.X (Sum.inl j) +
                MvPolynomial.C (π ^ 3) * MvPolynomial.X (Sum.inr i)) =
            (Ideal.Quotient.mk I exprP)
          simp only [map_add, map_mul, map_sum, MvPolynomial.aeval_C,
            MvPolynomial.aeval_X, desingularizationLiftVW, MvPolynomial.rename_X]
          simp only [exprP, MvPolynomial.C_eq_algebraMap]
          simp only [map_add, map_mul, map_sum]
          have hmk (r : R) :
              Ideal.Quotient.mk I (algebraMap R P r) = algebraMap R (P ⧸ I) r :=
            Ideal.Quotient.mk_algebraMap R I r
          rw [hmk (π ^ 2), hmk (π ^ 3)]
          have hcoeff (x : Fin c) :
              Ideal.Quotient.mk I
                  ((algebraMap R (MvPolynomial (Fin n ⊕ (Fin c ⊕ Fin n)) R)) (s i x)) =
                algebraMap R (P ⧸ I) (s i x) := by
            exact Ideal.Quotient.mk_algebraMap R I (s i x)
          simp_rw [hcoeff]
          simp only [Ideal.Quotient.mkₐ_eq_mk]
        rw [hpX]
        exact hgexpr.trans hi'.symm
  exact ⟨(AlgEquiv.ofAlgHom qmap gmap hqg hleft).toRingEquiv⟩

/-- The polynomial evaluation descends to the constructed ring when the
original, auxiliary, and correction relations all evaluate to zero. -/
theorem desingularizationEvaluation_descends
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R)
    (lambdaValues : Fin n → Λ)
    (hrelations : ∀ j,
      desingularizationEvaluation (c := c) π lambdaValues
        (desingularizationLiftX (c := c) (relations j)) = 0)
    (hauxiliary : ∀ i,
      desingularizationEvaluation (c := c) π lambdaValues
        (desingularizationAuxiliaryRelation π s i) = 0)
    (hcorrections : ∀ j,
      desingularizationEvaluation (c := c) π lambdaValues
        (desingularizationLiftVW (n := n) (corrections j)) = 0) :
    ∃ φ : desingularizationConstructionRing π relations s corrections →ₐ[R] Λ,
      ∀ p,
        φ (Ideal.Quotient.mk
          (desingularizationDefiningIdeal π relations s corrections) p) =
          desingularizationEvaluation π lambdaValues p := by
  let F := desingularizationEvaluation (c := c) π lambdaValues
  have hFideal : desingularizationDefiningIdeal π relations s corrections ≤
      RingHom.ker F.toRingHom := by
    rw [desingularizationDefiningIdeal]
    apply Ideal.span_le.2
    intro x hx
    rcases hx with hx | hx
    · rcases hx with hx | hx
      · obtain ⟨j, rfl⟩ := hx
        exact hrelations j
      · obtain ⟨i, rfl⟩ := hx
        exact hauxiliary i
    · obtain ⟨j, rfl⟩ := hx
      exact hcorrections j
  have hF : ∀ a, a ∈ desingularizationDefiningIdeal π relations s corrections → F a = 0 := by
    intro a ha
    exact hFideal ha
  let φ : desingularizationConstructionRing π relations s corrections →ₐ[R] Λ :=
    Ideal.Quotient.liftₐ (desingularizationDefiningIdeal π relations s corrections) F hF
  refine ⟨φ, ?_⟩
  intro p
  have hcomp := Ideal.Quotient.liftₐ_comp
    (desingularizationDefiningIdeal π relations s corrections) F hF
  exact congrArg (fun f => f p) hcomp

/-- The displayed polynomial quotient `B` is of finite presentation over any
commutative base. -/
theorem desingularizationConstruction_finitePresentation
    {R : Type u} [CommRing R]
    {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) :
    Algebra.FinitePresentation R
      (desingularizationConstructionRing π relations s corrections) := by
  have hfinite : Set.Finite
      (Set.range (fun j : Fin m => desingularizationLiftX (relations j)) ∪
        Set.range (desingularizationAuxiliaryRelation π s) ∪
        Set.range (fun j : Fin c => desingularizationLiftVW (corrections j))) := by
    apply Set.Finite.union
    · apply Set.Finite.union
      · exact Set.finite_range _
      · exact Set.finite_range _
    · exact Set.finite_range _
  have hfg : (desingularizationDefiningIdeal π relations s corrections).FG := by
    rw [desingularizationDefiningIdeal]
    exact Submodule.fg_span hfinite
  exact Algebra.FinitePresentation.quotient hfg

/-- After inverting `π`, the `h_i` and `g_j` equations give the polynomial
description `B_π ≅ A_π[v_1, ..., v_c]` used in the proof. -/
theorem desingularizationConstruction_localization_equiv
    {R : Type u} [CommRing R] {n m c : ℕ} (π : R)
    (d : DesingularizationPolynomialData R π n m c) :
    Nonempty
      (Localization.Away
          (algebraMap R
            (desingularizationConstructionRing π d.relations
              (fun i j => d.witness.inverse_coefficients i j) d.corrections)
            π) ≃+*
        MvPolynomial (Fin c)
          (Localization.Away
            (algebraMap R (desingularizationPresentedAlgebra d.relations) π))) := by
  sorry

/-- The canonical map `R_π → B_π` induced by an `R`-algebra map. -/
noncomputable def desingularizationLocalizedMap
    {R B : Type u} [CommRing R] [CommRing B] [Algebra R B]
    (π : R) :
    Localization.Away π →+* Localization.Away (algebraMap R B π) := by
  exact Localization.awayLift
    ((algebraMap B (Localization.Away (algebraMap R B π))).comp
      (algebraMap R B)) π (by
        change IsUnit
          (algebraMap B (Localization.Away (algebraMap R B π))
            (algebraMap R B π))
        exact IsLocalization.Away.algebraMap_isUnit
          (S := Localization.Away (algebraMap R B π))
          (algebraMap R B π))

/-! ## The three source lemmas -/

/-- The conclusion of the first source lemma: a finite-presentation
factorization whose singular ideal contains the extended annihilator ideal. -/
def HasDesingularizationFactorization
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (φ : A →ₐ[R] Λ) (a : Ideal R) : Prop :=
  ∃ (B : Type u) (hB : CommRing B) (hRB : Algebra R B),
    letI : CommRing B := hB
    letI : Algebra R B := hRB
    ∃ (_hfp : Algebra.FinitePresentation R B)
      (AtoB : A →ₐ[R] B) (BtoΛ : B →ₐ[R] Λ),
      BtoΛ.comp AtoB = φ ∧
        Ideal.map (algebraMap R B) a ≤ singularIdeal R B

/-- The desingularization lemma. -/
theorem desingularize
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [IsNoetherianRing R]
    [Algebra.FinitePresentation R A]
    (π : R) (φ : A →ₐ[R] Λ)
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2))
    (hstandard :
      IsStrictlyStandard R A (algebraMap R A π))
    (hsection : DesingularizationSection π φ 4) :
    HasDesingularizationFactorization φ
      (desingularizationAnnihilatorIdeal R π) := by
  sorry

/-- The conclusion of the second source lemma, including both singular-ideal
inclusions. -/
def HasCommonDesingularizationFactorization
    {R A D Λ : Type u} [CommRing R] [CommRing A] [CommRing D] [CommRing Λ]
    [Algebra R A] [Algebra R D] [Algebra R Λ]
    (φA : A →ₐ[R] Λ) (φD : D →ₐ[R] Λ) : Prop :=
  ∃ (B : Type u) (hB : CommRing B) (hRB : Algebra R B),
    letI : CommRing B := hB
    letI : Algebra R B := hRB
    ∃ (_hfp : Algebra.FinitePresentation R B)
      (AtoB : A →ₐ[R] B) (DtoB : D →ₐ[R] B) (BtoΛ : B →ₐ[R] Λ),
      letI : Algebra D B := DtoB.toRingHom.toAlgebra
      BtoΛ.comp AtoB = φA ∧
        BtoΛ.comp DtoB = φD ∧
        Ideal.map (algebraMap D B) (singularIdeal R D) ≤ singularIdeal D B ∧
        Ideal.map (algebraMap D B) (singularIdeal R D) ≤ singularIdeal R B

/-- The strictly-standard desingularization lemma used after applying the
lifting lemma. -/
theorem desingularize_strictly_standard
    {R A D Λ : Type u} [CommRing R] [CommRing A] [CommRing D] [CommRing Λ]
    [Algebra R A] [Algebra R D] [Algebra R Λ] [IsNoetherianRing R]
    [Algebra.FinitePresentation R A] [Algebra.FinitePresentation R D]
    (π : R) (φA : A →ₐ[R] Λ) (φD : D →ₐ[R] Λ)
    (hAnnR :
      annihilatorOf (R := R) (M := R) π =
        annihilatorOf (R := R) (M := R) (π ^ 2))
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2))
    (hstandard : IsStrictlyStandard R A (algebraMap R A π))
    (hmap : DesingularizationModPowerMap π φA φD 4) :
    HasCommonDesingularizationFactorization φA φD := by
  sorry

/-- The source's lifting application: after a finite-presentation factorization
modulo `π⁸`, one obtains a finite-presentation lift, smooth after inverting
`π`, and the displayed singular-ideal inclusion modulo `π⁸Λ`. -/
theorem desingularize_lifting_apply
    {R A C Λ : Type u} [CommRing R] [CommRing A] [CommRing C] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [IsNoetherianRing R]
    [Algebra.FinitePresentation R A]
    (π : R) (φ : A →ₐ[R] Λ)
    (hAnnR :
      annihilatorOf (R := R) (M := R) π =
        annihilatorOf (R := R) (M := R) (π ^ 2))
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2))
    [Algebra (powerQuotient R π 8) C]
    [Algebra.FinitePresentation (powerQuotient R π 8) C]
    (hstandard : IsStrictlyStandard R A (algebraMap R A π))
    (factor : DesingularizationModPowerFactorization π φ 8) :
    ∃ (B : Type u) (hB : CommRing B) (hRB : Algebra R B),
      letI : CommRing B := hB
      letI : Algebra R B := hRB
      ∃ (_hfp : Algebra.FinitePresentation R B)
        (AtoB : A →ₐ[R] B) (BtoΛ : B →ₐ[R] Λ),
        letI : Algebra (Localization.Away π)
            (Localization.Away (algebraMap R B π)) :=
          (desingularizationLocalizedMap π).toAlgebra
        BtoΛ.comp AtoB = φ ∧
          Algebra.Smooth (Localization.Away π)
            (Localization.Away (algebraMap R B π)) ∧
          Ideal.map factor.toLambda
              (singularIdeal (powerQuotient R π 8) C) ≤
            Ideal.map (powerQuotientMk (algebraMap R Λ π) 8)
              (Ideal.map BtoΛ.toRingHom (singularIdeal R B)).radical := by
  sorry

end

end Formalization.Books.Smoothing.Unit07
