import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.LinearAlgebra.Determinant
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Noetherian.Basic
import Formalization.Books.Smoothing.Unit02.SingularIdeals
import Formalization.Books.Smoothing.Unit06.LiftingLemma

/-!
# Smoothing Ring Maps, Chapter 7: The desingularization lemma

The quotient maps and polynomial construction below record the data used in
the source proofs.  The three source lemmas are stated with the canonical
`singularIdeal`, `IsStrictlyStandard`, finite-presentation, localization, and
annihilator interfaces from the preceding chapters.
-/

namespace Formalization.Books.Smoothing.Unit07

open Set
open Formalization.Books.Algebra.Unit03
open Formalization.Books.Smoothing.Unit02
open Formalization.Books.Smoothing.Unit06
open scoped BigOperators TensorProduct

noncomputable section

universe u v

/-! ## Quotients and the section/factorization diagrams -/

/-- The quotient of a ring by the principal ideal generated by `s ^ n`. -/
abbrev powerQuotient (S : Type u) [CommRing S] (s : S) (n : ℕ) : Type u :=
  piQuotient S (s ^ n)

/-- The quotient map to `S/(s^n)`. -/
def powerQuotientMk {S : Type u} [CommRing S] (s : S) (n : ℕ) :
    S →+* powerQuotient S s n :=
  piQuotientMk (s ^ n)

/-- The map induced on principal-power quotients by a ring map carrying `s` to
`t`.  This is the canonical quotient-map construction, rather than a second
quotient-ring API. -/
def powerQuotientMap
    {S T : Type u} [CommRing S] [CommRing T]
    {s : S} {t : T} (f : S →+* T) (h : f s = t) (n : ℕ) :
    powerQuotient S s n →+* powerQuotient T t n :=
  Ideal.quotientMap (Ideal.span ({t ^ n} : Set T)) f (by
    apply Ideal.span_le.2
    intro x hx
    have hx' : x = s ^ n := Set.mem_singleton_iff.mp hx
    subst x
    exact Ideal.mem_span_singleton'.2 ⟨1, by simp [h]⟩)

/-- The quotient of an `R`-algebra induced by its structure map. -/
def powerQuotientAlgebraMap
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
    (π : R) (n : ℕ) :
    powerQuotient R π n →+* powerQuotient A (algebraMap R A π) n :=
  powerQuotientMap (algebraMap R A) (by rfl) n

/-- The quotient map induced by an `R`-algebra map. -/
def powerQuotientAlgMap
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (φ : A →ₐ[R] Λ) (π : R) (n : ℕ) :
    powerQuotient A (algebraMap R A π) n →+*
      powerQuotient Λ (algebraMap R Λ π) n :=
  powerQuotientMap φ.toRingHom (by simp) n

/- The source's `Ann_R(Ann_R(π²)/Ann_R(π))` is the annihilator of the
canonical quotient module.  The lower annihilator is included in the upper
one; using `Submodule.comap` makes the quotient type explicit. -/
abbrev annihilatorPowerQuotient
    (R : Type u) [CommRing R] (π : R) : Type u :=
  let I₂ : Submodule R R := annihilatorOf (R := R) (M := R) (π ^ 2)
  let I₁ : Submodule R R := annihilatorOf (R := R) (M := R) π
  I₂ ⧸ Submodule.comap I₂.subtype I₁

theorem annihilatorOf_mem_pow_two
    {R : Type u} [CommRing R] (π : R) :
    annihilatorOf (R := R) (M := R) π ≤
      annihilatorOf (R := R) (M := R) (π ^ 2) := by
  sorry

/-- The ideal `Ann_R(Ann_R(π²)/Ann_R(π))` appearing in the lemma. -/
def desingularizationAnnihilatorIdeal
    (R : Type u) [CommRing R] (π : R) : Ideal R :=
  Module.annihilator R (annihilatorPowerQuotient R π)

/-- A section of `R/(π^n) → A/(π^n A)` compatible with a map to `Λ/(π^nΛ)`.
The word “section” records the left-inverse equation explicitly. -/
structure DesingularizationSection
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (π : R) (φ : A →ₐ[R] Λ) (n : ℕ) where
  sectionMap :
    powerQuotient A (algebraMap R A π) n →+* powerQuotient R π n
  isSection :
    sectionMap.comp (powerQuotientAlgebraMap π n) =
      RingHom.id (powerQuotient R π n)
  compatible :
    powerQuotientAlgMap φ π n =
      (powerQuotientAlgebraMap (R := R) (A := Λ) π n).comp sectionMap

/-- A map between two principal-power quotients compatible with the two maps
to `Λ/(π^nΛ)`. -/
structure DesingularizationModPowerMap
    {R A D Λ : Type u} [CommRing R] [CommRing A] [CommRing D] [CommRing Λ]
    [Algebra R A] [Algebra R D] [Algebra R Λ]
    (π : R) (φA : A →ₐ[R] Λ) (φD : D →ₐ[R] Λ) (n : ℕ) where
  quotientMap :
    powerQuotient A (algebraMap R A π) n →+*
      powerQuotient D (algebraMap R D π) n
  compatibleWithBase :
    quotientMap.comp (powerQuotientAlgebraMap (R := R) (A := A) π n) =
      powerQuotientAlgebraMap (R := R) (A := D) π n
  compatibleWithLambda :
    powerQuotientAlgMap φA π n =
      (powerQuotientAlgMap φD π n).comp quotientMap

/-- The factorization `A/(π^nA) → Cbar → Λ/(π^nΛ)` used in the last lemma,
with the base-ring and original-map compatibilities written as equations of
ring homomorphisms. -/
structure DesingularizationModPowerFactorization
    {R A C Λ : Type u} [CommRing R] [CommRing A] [CommRing C] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (π : R) (φ : A →ₐ[R] Λ) (n : ℕ)
    [Algebra (powerQuotient R π n) C] where
  toC : powerQuotient A (algebraMap R A π) n →+* C
  toC_over_base :
    toC.comp (powerQuotientAlgebraMap (R := R) (A := A) π n) =
      algebraMap (powerQuotient R π n) C
  toLambda : C →+* powerQuotient Λ (algebraMap R Λ π) n
  toLambda_over_base :
    toLambda.comp (algebraMap (powerQuotient R π n) C) =
      powerQuotientAlgebraMap (R := R) (A := Λ) π n
  factorization :
    toLambda.comp toC = powerQuotientAlgMap φ π n

/-- The index `c+j` of an unselected relation in a presentation with `m`
relations and `c` selected ones. -/
def desingularizationUnselectedIndex
    {m c : ℕ} (hcm : c ≤ m) (j : Fin (m - c)) : Fin m :=
  Fin.cast (Nat.add_sub_of_le hcm) (Fin.natAdd c j)

/-- The ideal generated by the selected first `c` relations. -/
def desingularizationSelectedRelationIdeal
    {A : Type u} [CommRing A] {m c : ℕ} (hcm : c ≤ m)
    (relations : Fin m → A) : Ideal A :=
  Ideal.span (Set.range (fun j : Fin c => relations (Fin.castLE hcm j)))

/-- The source's displayed `(★)` condition, written in the presented algebra. -/
def DesingularizationStarCondition
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
    {m c : ℕ} (hcm : c ≤ m) (π : R) (relations : Fin m → A) : Prop :=
  ∀ j : Fin (m - c),
    algebraMap R A π * relations (desingularizationUnselectedIndex hcm j) ∈
      desingularizationSelectedRelationIdeal hcm relations +
        (Ideal.span (Set.range relations)) ^ 2

/-! ## The polynomial construction in the proof of the first lemma -/

/-- The polynomial ring in the `x`, `v`, and `w` variables of the source
construction. -/
abbrev desingularizationPolynomial (R : Type u) [CommRing R]
    (n c : ℕ) : Type u :=
  MvPolynomial (Fin n ⊕ (Fin c ⊕ Fin n)) R

/-- Inclusion of the `x`-polynomial ring into the auxiliary polynomial ring. -/
def desingularizationLiftX
    {R : Type u} [CommRing R] {n c : ℕ}
    (f : MvPolynomial (Fin n) R) : desingularizationPolynomial R n c :=
  MvPolynomial.rename (fun i => Sum.inl i) f

/-- Inclusion of the `v,w`-polynomial ring into the auxiliary polynomial ring. -/
def desingularizationLiftVW
    {R : Type u} [CommRing R] {n c : ℕ}
    (f : MvPolynomial (Fin c ⊕ Fin n) R) : desingularizationPolynomial R n c :=
  MvPolynomial.rename (fun i => Sum.inr i) f

/-- The relation `h_i = x_i - π² Σ_j s_{ij}v_j - π³w_i`. -/
def desingularizationAuxiliaryRelation
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (s : Fin n → Fin c → R) (i : Fin n) :
    desingularizationPolynomial R n c :=
  desingularizationLiftX (MvPolynomial.X i) -
      MvPolynomial.C (π ^ 2) *
        ∑ j : Fin c,
          MvPolynomial.C (s i j) *
            MvPolynomial.X (Sum.inr (Sum.inl j)) -
      MvPolynomial.C (π ^ 3) *
        MvPolynomial.X (Sum.inr (Sum.inr i))

/-- The quotient of the full polynomial ring by the auxiliary relations
`h_i`.  The source identifies this ring with the polynomial ring in `v,w`. -/
abbrev desingularizationAuxiliaryRelationQuotient
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (s : Fin n → Fin c → R) : Type u :=
  desingularizationPolynomial R n c ⧸
    Ideal.span (Set.range (desingularizationAuxiliaryRelation π s))

/-- The ideal generated by the original relations, the `h_i`, and the
chosen `g_j` relations. -/
def desingularizationDefiningIdeal
    {R : Type u} [CommRing R] {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) :
    Ideal (desingularizationPolynomial R n c) :=
  Ideal.span
    (Set.range (fun j : Fin m => desingularizationLiftX (relations j)) ∪
      Set.range (desingularizationAuxiliaryRelation π s) ∪
      Set.range (fun j : Fin c => desingularizationLiftVW (corrections j)))

/-- The auxiliary ring `B' = R[v,w]/(g_1, ..., g_c)` used in the local
smoothness argument. -/
abbrev desingularizationAuxiliaryRing
    {R : Type u} [CommRing R] {n c : ℕ}
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) : Type u :=
  MvPolynomial (Fin c ⊕ Fin n) R ⧸ Ideal.span (Set.range corrections)

/-- Modulo `π`, the auxiliary ring is a polynomial ring in the `w` variables;
the displayed equivalence is the source's `B'/πB'` calculation. -/
theorem desingularizationAuxiliaryRing_mod_pi_equiv
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R)
    (linearCoefficients : Fin c → Fin n → R)
    (hmod : ∀ j : Fin c,
      corrections j -
          (MvPolynomial.X (Sum.inl j) +
            ∑ i : Fin n,
              MvPolynomial.C (linearCoefficients j i) *
                MvPolynomial.X (Sum.inr i)) ∈
        Ideal.span ({MvPolynomial.C π} :
          Set (MvPolynomial (Fin c ⊕ Fin n) R))) :
    Nonempty
      (powerQuotient (desingularizationAuxiliaryRing corrections)
          (algebraMap R (desingularizationAuxiliaryRing corrections) π) 1 ≃+*
        MvPolynomial (Fin n) (powerQuotient R π 1)) := by
  sorry

/-- Every prime of `B'` containing `π` is a smooth point of `B'` over `R`.
This is the source's smoothness-on-`V(π)` assertion. -/
theorem desingularizationAuxiliaryRing_smoothAt_of_pi_mem
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R)
    (linearCoefficients : Fin c → Fin n → R)
    (hmod : ∀ j : Fin c,
      corrections j -
          (MvPolynomial.X (Sum.inl j) +
            ∑ i : Fin n,
              MvPolynomial.C (linearCoefficients j i) *
                MvPolynomial.X (Sum.inr i)) ∈
        Ideal.span ({MvPolynomial.C π} :
          Set (MvPolynomial (Fin c ⊕ Fin n) R))) :
    ∀ q : PrimeSpectrum (desingularizationAuxiliaryRing corrections),
      algebraMap R (desingularizationAuxiliaryRing corrections) π ∈ q.asIdeal →
      Formalization.Books.Algebra.Unit137.IsSmoothAt R
        (desingularizationAuxiliaryRing corrections) q := by
  sorry

/-- The finitely presented ring `B` displayed in the proof. -/
abbrev desingularizationConstructionRing
    {R : Type u} [CommRing R] {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) : Type u :=
  desingularizationPolynomial R n c ⧸
    desingularizationDefiningIdeal π relations s corrections

/-- The presented algebra `A = R[x]/(f)` used in the construction. -/
abbrev desingularizationPresentedAlgebra
    {R : Type u} [CommRing R] {n m : ℕ}
    (relations : Fin m → MvPolynomial (Fin n) R) : Type u :=
  MvPolynomial (Fin n) R ⧸ Ideal.span (Set.range relations)

/-- The finite-index form of the determinant identity after applying the
section to the strict-standard identity.  Embeddings encode the selected
variable subsets used by the source. -/
structure DesingularizationJacobianWitness
    (R : Type u) [CommRing R] (π : R) (n c : ℕ) where
  c_le_n : c ≤ n
  linearCoefficients : Fin c → Fin n → R
  coefficient : (Fin c ↪ Fin n) → R
  unit : R
  unit_congruent : ∃ t : R, unit = 1 + π ^ 3 * t
  jacobian_identity :
    unit * π =
      ∑ e : Fin c ↪ Fin n,
        coefficient e *
          Matrix.det (fun j i => linearCoefficients j (e i))
  inverse_coefficients : Fin n → Fin c → R
  matrix_left_inverse :
    ∀ j k : Fin c,
      unit * π * (if j = k then 1 else 0) =
        ∑ i : Fin n,
          linearCoefficients j i * inverse_coefficients i k

/-- The relation and correction identities used after introducing `v,w`. -/
structure DesingularizationPolynomialData
    (R : Type u) [CommRing R] (π : R) (n m c : ℕ) where
  relations : Fin m → MvPolynomial (Fin n) R
  c_le_m : c ≤ m
  witness : DesingularizationJacobianWitness R π n c
  corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R
  relation_identity :
    ∀ j : Fin c,
      desingularizationLiftX (relations (Fin.castLE c_le_m j)) -
          MvPolynomial.C (π ^ 3) * desingularizationLiftVW (corrections j) ∈
        Ideal.span (Set.range
          (desingularizationAuxiliaryRelation π
            (fun i j => witness.inverse_coefficients i j)))
  correction_identity_mod_pi :
    ∀ j : Fin c,
      corrections j -
          (MvPolynomial.X (Sum.inl j) +
            ∑ i : Fin n,
              MvPolynomial.C (witness.linearCoefficients j i) *
                MvPolynomial.X (Sum.inr i)) ∈
        Ideal.span ({MvPolynomial.C π} :
          Set (MvPolynomial (Fin c ⊕ Fin n) R))

/-- The evaluation values `x_i ↦ π⁴λ_i`, `v_j ↦ 0`, and
`w_i ↦ πλ_i` from the map `B → Λ` in the proof. -/
def desingularizationEvaluationValues
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {n c : ℕ} (π : R) (lambdaValues : Fin n → Λ) :
    Fin n ⊕ (Fin c ⊕ Fin n) → Λ
  | Sum.inl i => (algebraMap R Λ π) ^ 4 * lambdaValues i
  | Sum.inr (Sum.inl _) => 0
  | Sum.inr (Sum.inr i) => algebraMap R Λ π * lambdaValues i

/-- The polynomial evaluation attached to those values. -/
def desingularizationEvaluation
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {n c : ℕ} (π : R) (lambdaValues : Fin n → Λ) :
    desingularizationPolynomial R n c →ₐ[R] Λ :=
  MvPolynomial.aeval (desingularizationEvaluationValues π lambdaValues)

/-- The quotient by the `h_i` is the polynomial ring in the remaining
`v,w` variables, as used in the first displayed simplification in the proof.
The equivalence is recorded in the direction that exposes those variables. -/
theorem desingularizationAuxiliaryRelationQuotient_equiv
    {R : Type u} [CommRing R] {n c : ℕ} (π : R)
    (s : Fin n → Fin c → R) :
    Nonempty
      (desingularizationAuxiliaryRelationQuotient π s ≃+*
        MvPolynomial (Fin c ⊕ Fin n) R) := by
  sorry

/-- The polynomial evaluation descends to the constructed ring when the
original, auxiliary, and correction relations all evaluate to zero. -/
theorem desingularizationEvaluation_descends
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R)
    (lambdaValues : Fin n → Λ)
    (hrelations : ∀ j,
      desingularizationEvaluation (c := c) π lambdaValues
        (desingularizationLiftX (c := c) (relations j)) = 0)
    (hauxiliary : ∀ i,
      desingularizationEvaluation (c := c) π lambdaValues
        (desingularizationAuxiliaryRelation π s i) = 0)
    (hcorrections : ∀ j,
      desingularizationEvaluation (c := c) π lambdaValues
        (desingularizationLiftVW (n := n) (corrections j)) = 0) :
    ∃ φ : desingularizationConstructionRing π relations s corrections →ₐ[R] Λ,
      ∀ p,
        φ (Ideal.Quotient.mk
          (desingularizationDefiningIdeal π relations s corrections) p) =
          desingularizationEvaluation π lambdaValues p := by
  sorry

/-- The displayed polynomial quotient `B` is of finite presentation over a
Noetherian base. -/
theorem desingularizationConstruction_finitePresentation
    {R : Type u} [CommRing R] [IsNoetherianRing R]
    {n m c : ℕ} (π : R)
    (relations : Fin m → MvPolynomial (Fin n) R)
    (s : Fin n → Fin c → R)
    (corrections : Fin c → MvPolynomial (Fin c ⊕ Fin n) R) :
    Algebra.FinitePresentation R
      (desingularizationConstructionRing π relations s corrections) := by
  sorry

/-- After inverting `π`, the `h_i` and `g_j` equations give the polynomial
description `B_π ≅ A_π[v_1, ..., v_c]` used in the proof. -/
theorem desingularizationConstruction_localization_equiv
    {R : Type u} [CommRing R] {n m c : ℕ} (π : R)
    (d : DesingularizationPolynomialData R π n m c) :
    Nonempty
      (Localization.Away
          (algebraMap R
            (desingularizationConstructionRing π d.relations
              (fun i j => d.witness.inverse_coefficients i j) d.corrections)
            π) ≃+*
        MvPolynomial (Fin c)
          (Localization.Away
            (algebraMap R (desingularizationPresentedAlgebra d.relations) π))) := by
  sorry

/-- The canonical map `R_π → B_π` induced by an `R`-algebra map. -/
noncomputable def desingularizationLocalizedMap
    {R B : Type u} [CommRing R] [CommRing B] [Algebra R B]
    (π : R) :
    Localization.Away π →+* Localization.Away (algebraMap R B π) := by
  exact Localization.awayLift
    ((algebraMap B (Localization.Away (algebraMap R B π))).comp
      (algebraMap R B)) π (by
        change IsUnit
          (algebraMap B (Localization.Away (algebraMap R B π))
            (algebraMap R B π))
        exact IsLocalization.Away.algebraMap_isUnit
          (S := Localization.Away (algebraMap R B π))
          (algebraMap R B π))

/-! ## The three source lemmas -/

/-- The conclusion of the first source lemma: a finite-presentation
factorization whose singular ideal contains the extended annihilator ideal. -/
def HasDesingularizationFactorization
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (φ : A →ₐ[R] Λ) (a : Ideal R) : Prop :=
  ∃ (B : Type u) (hB : CommRing B) (hRB : Algebra R B),
    letI : CommRing B := hB
    letI : Algebra R B := hRB
    ∃ (_hfp : Algebra.FinitePresentation R B)
      (AtoB : A →ₐ[R] B) (BtoΛ : B →ₐ[R] Λ),
      BtoΛ.comp AtoB = φ ∧
        Ideal.map (algebraMap R B) a ≤ singularIdeal R B

/-- The desingularization lemma. -/
theorem desingularize
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [IsNoetherianRing R]
    [Algebra.FinitePresentation R A]
    (π : R) (φ : A →ₐ[R] Λ)
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2))
    (hstandard :
      IsStrictlyStandard R A (algebraMap R A π))
    (hsection : DesingularizationSection π φ 4) :
    HasDesingularizationFactorization φ
      (desingularizationAnnihilatorIdeal R π) := by
  sorry

/-- The conclusion of the second source lemma, including both singular-ideal
inclusions. -/
def HasCommonDesingularizationFactorization
    {R A D Λ : Type u} [CommRing R] [CommRing A] [CommRing D] [CommRing Λ]
    [Algebra R A] [Algebra R D] [Algebra R Λ]
    (φA : A →ₐ[R] Λ) (φD : D →ₐ[R] Λ) : Prop :=
  ∃ (B : Type u) (hB : CommRing B) (hRB : Algebra R B),
    letI : CommRing B := hB
    letI : Algebra R B := hRB
    ∃ (_hfp : Algebra.FinitePresentation R B)
      (AtoB : A →ₐ[R] B) (DtoB : D →ₐ[R] B) (BtoΛ : B →ₐ[R] Λ),
      letI : Algebra D B := DtoB.toRingHom.toAlgebra
      BtoΛ.comp AtoB = φA ∧
        BtoΛ.comp DtoB = φD ∧
        Ideal.map (algebraMap D B) (singularIdeal R D) ≤ singularIdeal D B ∧
        Ideal.map (algebraMap D B) (singularIdeal R D) ≤ singularIdeal R B

/-- The strictly-standard desingularization lemma used after applying the
lifting lemma. -/
theorem desingularize_strictly_standard
    {R A D Λ : Type u} [CommRing R] [CommRing A] [CommRing D] [CommRing Λ]
    [Algebra R A] [Algebra R D] [Algebra R Λ] [IsNoetherianRing R]
    [Algebra.FinitePresentation R A] [Algebra.FinitePresentation R D]
    (π : R) (φA : A →ₐ[R] Λ) (φD : D →ₐ[R] Λ)
    (hAnnR :
      annihilatorOf (R := R) (M := R) π =
        annihilatorOf (R := R) (M := R) (π ^ 2))
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2))
    (hstandard : IsStrictlyStandard R A (algebraMap R A π))
    (hmap : DesingularizationModPowerMap π φA φD 4) :
    HasCommonDesingularizationFactorization φA φD := by
  sorry

/-- The source's lifting application: after a finite-presentation factorization
modulo `π⁸`, one obtains a finite-presentation lift, smooth after inverting
`π`, and the displayed singular-ideal inclusion modulo `π⁸Λ`. -/
theorem desingularize_lifting_apply
    {R A C Λ : Type u} [CommRing R] [CommRing A] [CommRing C] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [IsNoetherianRing R]
    [Algebra.FinitePresentation R A]
    (π : R) (φ : A →ₐ[R] Λ)
    (hAnnR :
      annihilatorOf (R := R) (M := R) π =
        annihilatorOf (R := R) (M := R) (π ^ 2))
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2))
    [Algebra (powerQuotient R π 8) C]
    [Algebra.FinitePresentation (powerQuotient R π 8) C]
    (hstandard : IsStrictlyStandard R A (algebraMap R A π))
    (factor : DesingularizationModPowerFactorization π φ 8) :
    ∃ (B : Type u) (hB : CommRing B) (hRB : Algebra R B),
      letI : CommRing B := hB
      letI : Algebra R B := hRB
      ∃ (_hfp : Algebra.FinitePresentation R B)
        (AtoB : A →ₐ[R] B) (BtoΛ : B →ₐ[R] Λ),
        letI : Algebra (Localization.Away π)
            (Localization.Away (algebraMap R B π)) :=
          (desingularizationLocalizedMap π).toAlgebra
        BtoΛ.comp AtoB = φ ∧
          Algebra.Smooth (Localization.Away π)
            (Localization.Away (algebraMap R B π)) ∧
          Ideal.map factor.toLambda
              (singularIdeal (powerQuotient R π 8) C) ≤
            Ideal.map (powerQuotientMk (algebraMap R Λ π) 8)
              (Ideal.map BtoΛ.toRingHom (singularIdeal R B)).radical := by
  sorry

end

end Formalization.Books.Smoothing.Unit07
