import Mathlib.Algebra.MvPolynomial.PDeriv
import Mathlib.LinearAlgebra.Determinant
import Mathlib.RingTheory.Extension.Presentation.Basic
import Mathlib.RingTheory.Extension.Presentation.Submersive
import Mathlib.RingTheory.Smooth.Locus
import Mathlib.RingTheory.Spectrum.Prime.Topology
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.TensorProduct.Maps
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Formalization.Books.Algebra.Unit137.SmoothRingMaps

/-!
# Smoothing Ring Maps, Chapter 2: Singular ideals

This file uses Mathlib's presentations, cotangent modules, and Jacobian
primitives together with the source-facing smooth-locus interface from the
earlier smooth-ring-maps chapter.  The two element predicates below are the
presentation-dependent notions from the source; their relation condition is
expressed in the canonical conormal module, which is the invariant form of
membership in (f₁, ..., f_c) + (f₁, ..., f_m)^2.
-/

namespace Formalization.Books.Smoothing.Unit02

open Set
open scoped BigOperators TensorProduct

noncomputable section

universe u v w

/-! ## The singular ideal -/

/-- The vanishing ideal of the nonsmooth locus of an algebra. -/
def singularIdeal (R A : Type*) [CommRing R] [CommRing A] [Algebra R A] : Ideal A :=
  PrimeSpectrum.vanishingIdeal
    ((Formalization.Books.Algebra.Unit137.SmoothLocus R A)ᶜ)

theorem singularIdeal_isRadical (R A : Type*) [CommRing R] [CommRing A] [Algebra R A] :
    (singularIdeal R A).IsRadical := by
  exact PrimeSpectrum.isRadical_vanishingIdeal _

/-- The source-facing smooth locus is open, since smoothness at a prime is
defined by smoothness on a basic localization around that prime. -/
theorem isOpen_smoothLocus
    (R A : Type*) [CommRing R] [CommRing A] [Algebra R A] :
    IsOpen (Formalization.Books.Algebra.Unit137.SmoothLocus R A) := by
  sorry

/-- The singular ideal cuts out exactly the complement of the source-facing
smooth locus. -/
theorem singularIdeal_zeroLocus (R A : Type*) [CommRing R] [CommRing A] [Algebra R A] :
    PrimeSpectrum.zeroLocus (singularIdeal R A) =
      (Formalization.Books.Algebra.Unit137.SmoothLocus R A)ᶜ := by
  sorry

/-- The radical ideal with this zero locus is unique. -/
theorem singularIdeal_unique (R A : Type*) [CommRing R] [CommRing A] [Algebra R A]
    {I : Ideal A} (hI : I.IsRadical)
    (hzero : PrimeSpectrum.zeroLocus I =
      (Formalization.Books.Algebra.Unit137.SmoothLocus R A)ᶜ) :
    I = singularIdeal R A := by
  sorry

/-! ## Presentation-level standard elements -/

/-- The class in the conormal module represented by a relation of a
presentation. -/
def presentationRelationCotangent
    {R A ι σ : Type*} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (j : σ) :
    P.toExtension.Cotangent :=
  Algebra.Extension.Cotangent.mk ⟨P.relation j, P.relation_mem_ker j⟩

/-- The conormal submodule generated by a selected family of relations. -/
def presentationRelationSpan
    {R A ι σ : Type*} {c : ℕ} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (v : Fin c ↪ σ) :
    Submodule A P.toExtension.Cotangent :=
  Submodule.span A (Set.range (fun i : Fin c => presentationRelationCotangent P (v i)))

/-- A Jacobian minor, evaluated in the presented algebra.  Rows are indexed
by selected relations and columns by selected variables. -/
noncomputable def presentationJacobianMinor
    {R A ι σ : Type*} {c : ℕ} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (u : Fin c ↪ ι) (v : Fin c ↪ σ) : A :=
  algebraMap P.Ring A
    (Matrix.det (fun j i : Fin c =>
      MvPolynomial.pderiv (u i) (P.relation (v j))))

/-- The relation part of the standard-element condition, written in the
conormal module so that the square of the relation ideal is quotiented out. -/
def presentationRelationCondition
    {R A ι σ : Type*} {c : ℕ} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (a : A) (v : Fin c ↪ σ) : Prop :=
  ∀ j : σ, j ∉ Set.range v →
    a • presentationRelationCotangent P j ∈ presentationRelationSpan P v

/-- The full witness in the source's smooth-prime/Jacobian lemma.

An embedding of a finite `Fin` type records a chosen subset together with an
ordering.  The ordering only changes a determinant by a unit, which is
absorbed by `a'`; this is the canonical finite-index form of the source's
subsets `U` and `V`. -/
theorem exists_jacobianWitness_not_mem_of_isSmoothAt
    {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
    [Algebra.FinitePresentation R A] (q : PrimeSpectrum A)
    (hq : Formalization.Books.Algebra.Unit137.IsSmoothAt R A q) :
    ∃ (a : A) (n m c : ℕ),
      ∃ P : Algebra.Presentation R A (Fin n) (Fin m),
        a ∉ q.asIdeal ∧ c ≤ n ∧ c ≤ m ∧
          ∃ (u : Fin c ↪ Fin n) (v : Fin c ↪ Fin m) (a' : A),
            a = a' * presentationJacobianMinor P u v ∧
              presentationRelationCondition P a v := by
  sorry

/-- The ideal generated by all Jacobian minors for a fixed selected relation
family.  Membership in this ideal is the canonical finite-sum form of the
strictly-standard Jacobian identity. -/
def presentationJacobianIdeal
    {R A ι σ : Type*} {c : ℕ} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (v : Fin c ↪ σ) : Ideal A :=
  Ideal.span (Set.range (fun u : Fin c ↪ ι => presentationJacobianMinor P u v))

/-- An elementary standard element: one Jacobian minor, together with the
relation condition on all unselected relations. -/
def IsElementaryStandard (R A : Type*) [CommRing R] [CommRing A] [Algebra R A]
    (a : A) : Prop :=
  ∃ n m c : ℕ,
    ∃ P : Algebra.Presentation R A (Fin n) (Fin m),
      c ≤ n ∧ c ≤ m ∧
        ∃ (u : Fin c ↪ Fin n) (v : Fin c ↪ Fin m) (a' : A),
          a = a' * presentationJacobianMinor P u v ∧
            presentationRelationCondition P a v

/-- A strictly standard element: an A-linear combination of all Jacobian
minors using one fixed selected relation family, together with the same
relation condition. -/
def IsStrictlyStandard (R A : Type*) [CommRing R] [CommRing A] [Algebra R A]
    (a : A) : Prop :=
  ∃ n m c : ℕ,
    ∃ P : Algebra.Presentation R A (Fin n) (Fin m),
      c ≤ n ∧ c ≤ m ∧
        ∃ (v : Fin c ↪ Fin m),
          presentationRelationCondition P a v ∧
            a ∈ presentationJacobianIdeal P v

theorem elementaryStandard_isStrictlyStandard
    {R A : Type*} [CommRing R] [CommRing A] [Algebra R A] {a : A}
    (ha : IsElementaryStandard R A a) :
    IsStrictlyStandard R A a := by
  sorry

/-! ## Parsing the Jacobian identity -/

/-- The conormal map sending the standard basis of A^c to the selected
relation classes. -/
noncomputable def presentationRelationMap
    {R A ι σ : Type*} {c : ℕ} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (v : Fin c ↪ σ) :
    (Fin c → A) →ₗ[A] P.toExtension.Cotangent :=
  (Pi.basisFun A (Fin c)).constr A
    (fun i => presentationRelationCotangent P (v i))

/-- The strictly-standard Jacobian identity yields the split map from the
cotangent space to A^c whose composite with the conormal differential is
multiplication by a. -/
theorem strictlyStandard_jacobian_gives_split
    {R A ι σ : Type*} {c : ℕ} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (a : A) (v : Fin c ↪ σ)
    (ha : a ∈ presentationJacobianIdeal P v) :
    ∃ ψ : P.toExtension.CotangentSpace →ₗ[A] (Fin c → A),
      (ψ ∘ₗ P.toExtension.cotangentComplex ∘ₗ presentationRelationMap P v) =
        a • LinearMap.id := by
  sorry

/-- Conversely, a split composite forces the c-th power of a to satisfy
the strictly-standard Jacobian identity. -/
theorem split_gives_strictlyStandard_jacobian_power
    {R A ι σ : Type*} {c : ℕ} [CommRing R] [CommRing A] [Algebra R A]
    (P : Algebra.Presentation R A ι σ) (a : A) (v : Fin c ↪ σ)
    (hψ : ∃ ψ : P.toExtension.CotangentSpace →ₗ[A] (Fin c → A),
      (ψ ∘ₗ P.toExtension.cotangentComplex ∘ₗ presentationRelationMap P v) =
        a • LinearMap.id) :
    a ^ c ∈ presentationJacobianIdeal P v := by
  sorry

/-! ## Elkik's description -/

/-- Smoothness at a prime admits an elementary standard element outside that
prime.  The finite presentation is represented by Mathlib's canonical class;
the presentation and the bounds on c are carried by the conclusion. -/
theorem exists_elementaryStandard_not_mem_of_isSmoothAt
    {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
    [Algebra.FinitePresentation R A] (q : PrimeSpectrum A)
    (hq : Formalization.Books.Algebra.Unit137.IsSmoothAt R A q) :
    ∃ a : A, a ∉ q.asIdeal ∧ IsElementaryStandard R A a := by
  obtain ⟨a, n, m, c, P, ha, hcn, hcm, u, v, a', hdet, hcond⟩ :=
    exists_jacobianWitness_not_mem_of_isSmoothAt (R := R) (A := A) q hq
  exact ⟨a, ha, n, m, c, P, hcn, hcm, u, v, a', hdet, hcond⟩

/-- A strictly standard element becomes a smooth localization. -/
theorem smooth_localization_of_strictlyStandard
    {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
    [Algebra.FinitePresentation R A] {a : A}
    (ha : IsStrictlyStandard R A a) :
    Algebra.Smooth R (Localization.Away a) := by
  sorry

/-- Elkik's theorem: the singular ideal is the radical generated by either
kind of standard element. -/
theorem elkik_singularIdeal
    (R A : Type*) [CommRing R] [CommRing A] [Algebra R A]
    [Algebra.FinitePresentation R A] :
    singularIdeal R A =
        (Ideal.span {a : A | IsStrictlyStandard R A a}).radical ∧
      singularIdeal R A =
        (Ideal.span {a : A | IsElementaryStandard R A a}).radical := by
  sorry

/-! ## The non-quasi-compact example -/

/-- The base ring in the source's infinitely generated example. -/
abbrev nonQuasiCompactBase (k : Type*) [CommRing k] :=
  MvPolynomial (Option ℕ) k ⧸
    Ideal.span (Set.range (fun i : ℕ =>
      (MvPolynomial.X (none : Option ℕ) * MvPolynomial.X (some i) :
        MvPolynomial (Option ℕ) k)))

/-- The image of x in the example base ring. -/
def nonQuasiCompactX (k : Type*) [CommRing k] : nonQuasiCompactBase k :=
  Ideal.Quotient.mk _
    (MvPolynomial.X (none : Option ℕ) : MvPolynomial (Option ℕ) k)

/-- The image of y_i in the example base ring. -/
def nonQuasiCompactY (k : Type*) [CommRing k] (i : ℕ) : nonQuasiCompactBase k :=
  Ideal.Quotient.mk _
    (MvPolynomial.X (some i) : MvPolynomial (Option ℕ) k)

/-- The target R/(x) in the example. -/
abbrev nonQuasiCompactTarget (k : Type*) [CommRing k] :=
  nonQuasiCompactBase k ⧸
    Ideal.span ({nonQuasiCompactX k} : Set (nonQuasiCompactBase k))

/-- The map in the example is finitely presented: it is the quotient by the
principal ideal generated by the image of `x`. -/
theorem nonQuasiCompact_map_isFinitePresentation
    (k : Type*) [CommRing k] :
    RingHom.FinitePresentation
      (algebraMap (nonQuasiCompactBase k) (nonQuasiCompactTarget k)) := by
  sorry

/-- In the example, the smooth locus is the union of the basic opens D(y_i). -/
theorem nonQuasiCompact_smoothLocus_eq_iUnion_basicOpen
    (k : Type*) [Field k] :
    Formalization.Books.Algebra.Unit137.SmoothLocus
        (nonQuasiCompactBase k) (nonQuasiCompactTarget k) =
      ⋃ i : ℕ,
        (PrimeSpectrum.basicOpen
          (Ideal.Quotient.mk
            (Ideal.span ({nonQuasiCompactX k} : Set (nonQuasiCompactBase k)))
            (nonQuasiCompactY k i)) :
            Set (PrimeSpectrum (nonQuasiCompactTarget k))) := by
  sorry

/-- The smooth locus in the example is open but not quasi-compact. -/
theorem nonQuasiCompact_smoothLocus_isOpen
    (k : Type*) [Field k] :
    IsOpen (Formalization.Books.Algebra.Unit137.SmoothLocus
      (nonQuasiCompactBase k) (nonQuasiCompactTarget k)) := by
  sorry

theorem nonQuasiCompact_smoothLocus_not_isCompact
    (k : Type*) [Field k] :
    ¬ IsCompact (Formalization.Books.Algebra.Unit137.SmoothLocus
      (nonQuasiCompactBase k) (nonQuasiCompactTarget k)) := by
  sorry

/-! ## Base change -/

/-- The canonical representative of a ⊗ 1 in Mathlib's base-change order
R' ⊗[R] A; it is 1 ⊗ a in that order. -/
def baseChangeElement
    {R A R' : Type*} [CommRing R] [CommRing A] [CommRing R']
    [Algebra R A] [Algebra R R'] (a : A) : R' ⊗[R] A :=
  1 ⊗ₜ[R] a

theorem elementaryStandard_baseChange
    {R A R' : Type*} [CommRing R] [CommRing A] [CommRing R']
    [Algebra R A] [Algebra R R'] [Algebra.FinitePresentation R A]
    {a : A} (ha : IsElementaryStandard R A a) :
    IsElementaryStandard R' (R' ⊗[R] A) (baseChangeElement a) := by
  sorry

theorem strictlyStandard_baseChange
    {R A R' : Type*} [CommRing R] [CommRing A] [CommRing R']
    [Algebra R A] [Algebra R R'] [Algebra.FinitePresentation R A]
    {a : A} (ha : IsStrictlyStandard R A a) :
    IsStrictlyStandard R' (R' ⊗[R] A) (baseChangeElement a) := by
  sorry

/-! ## The final smooth factorization -/

/-- The relation used in the standard affine modification
A[x_i]/(Σ f_i x_i - 1). -/
noncomputable def finalSolveRelation
    {A : Type*} [CommRing A] {r : ℕ} (f : Fin r → A) :
    MvPolynomial (Fin r) A :=
  (∑ i : Fin r, MvPolynomial.C (f i) * MvPolynomial.X i) - 1

/-- The algebra A[x_i]/(Σ f_i x_i - 1) used in the final-solve lemma. -/
abbrev finalSolveRing
    (A : Type*) [CommRing A] {r : ℕ} (f : Fin r → A) :=
  MvPolynomial (Fin r) A ⧸ Ideal.span ({finalSolveRelation f} :
    Set (MvPolynomial (Fin r) A))

/-- The image of the auxiliary variable x_i in finalSolveRing. -/
def finalSolveGenerator
    {A : Type*} [CommRing A] {r : ℕ} (f : Fin r → A) (i : Fin r) :
    finalSolveRing A f :=
  Ideal.Quotient.mk _ (MvPolynomial.X i)

/-- The canonical R-algebra structure on the final-solve algebra, obtained
by composing the maps R → A → B. -/
noncomputable instance finalSolveRing.algebraR
    {R A : Type*} [CommRing R] [CommRing A] [Algebra R A]
    {r : ℕ} (f : Fin r → A) : Algebra R (finalSolveRing A f) :=
  ((algebraMap A (finalSolveRing A f)).comp (algebraMap R A)).toAlgebra

/-- If the singular ideal becomes the unit ideal in Λ, the specified
final-solve algebra is smooth over R and maps to Λ, with the variables
sent to coefficients witnessing the unit-ideal relation. -/
theorem exists_smooth_finalSolve_factorization
    {R A Λ : Type*} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra A Λ] [Algebra R Λ] [IsScalarTower R A Λ]
    [Algebra.FinitePresentation R A]
    (hH : Ideal.map (algebraMap A Λ) (singularIdeal R A) = ⊤) :
    ∃ r : ℕ, ∃ f : Fin r → A, ∃ lambdaVals : Fin r → Λ,
      (∀ i, f i ∈ singularIdeal R A) ∧
      (∑ i : Fin r, algebraMap A Λ (f i) * lambdaVals i = 1) ∧
      Algebra.Smooth R (finalSolveRing A f) ∧
      ∃ φ : finalSolveRing A f →ₐ[A] Λ,
        ∀ i, φ (finalSolveGenerator f i) = lambdaVals i := by
  sorry

end

end Formalization.Books.Smoothing.Unit02
