import Mathlib.CategoryTheory.Limits.Shapes.Countable
import Mathlib.CategoryTheory.Limits.Shapes.Products
import Mathlib.Algebra.Category.Grp.Colimits
import Formalization.Books.Derived.Unit33.DerivedColimits
import Formalization.Books.Derived.Unit36.GeneratorsOfTriangulatedCategories

/-!
# Derived Categories, Chapter 37: compact objects

The source's compactness condition is expressed by the canonical coproduct
comparison for a representable additive functor.  Homotopy colimits use the
`IsDerivedColimit` interface from Chapter 33, while finite generated
subcategories and weak generators use the Chapter 36 interfaces.
-/

noncomputable section

open CategoryTheory
open CategoryTheory.Limits
open CategoryTheory.Preadditive
open CategoryTheory.Pretriangulated
open CategoryTheory.Triangulated
open Formalization.Books.Derived.Unit06
open Formalization.Books.Derived.Unit33
open Formalization.Books.Derived.Unit36
open Formalization.Books.Homology.Unit03
open scoped CategoryTheory.Pretriangulated.Opposite ZeroObject

universe v u

namespace Formalization.Books.Derived.Unit37

section CompactObjects

variable {C : Type u} [Category.{v} C] [AdditiveCategory C]
  [HasCoproducts.{v} C]

/-! The coproduct comparison formulation of a compact object. -/
def IsCompactObject (K : C) : Prop :=
  ∀ (I : Type v) (E : I → C),
    IsIso (sigmaComparison (preadditiveCoyoneda.obj (Opposite.op K)) E)

/-! The object property cut out by compact objects. -/
def compactObjects : ObjectProperty C :=
  fun K => IsCompactObject K

/-!
The all-coproduct compactness condition implies the countable version used by
the Chapter 33 homotopy-colimit interface.
-/
theorem isCountablyCompact_of_isCompactObject
    [HasCountableCoproducts C] (K : C) (hK : IsCompactObject K) :
    IsCountablyCompact K := by
  sorry

variable [HasShift C ℤ] [∀ n : ℤ, (shiftFunctor C n).Additive]
  [Pretriangulated C]

/-!
Compact objects form the source's strictly full, saturated,
(pre-)triangulated subcategory.  `IsSaturated` is the established
object-property encoding of closure under direct summands (the Karoubian
part of the source's terminology).
-/
theorem compactObjects_is_strictlyFull_saturated_pretriangulated :
    (compactObjects (C := C)).IsClosedUnderIsomorphisms ∧
      (compactObjects (C := C)).IsTriangulated ∧
      IsSaturated (compactObjects (C := C)) := by
  sorry

/-! The full subcategory of compact objects is Karoubian. -/
theorem compactObjects_fullSubcategory_isKaroubian :
    IsIdempotentComplete (compactObjects (C := C)).FullSubcategory := by
  sorry

/-!
An object obtained as an arbitrary direct sum of shifts of a family `E`.
The index `0` is not singled out: an empty family is allowed, as in the
canonical zero coproduct.
-/
def IsDirectSumOfShifts {I : Type v} (E : I → C) (X : C) : Prop :=
  ∃ (J : Type v) (ι : J → I) (n : J → ℤ),
    Nonempty ((∐ fun j => (E (ι j))⟦n j⟧) ≅ X)

/-! A transition in the source's successive extension construction. -/
def IsGeneratedTransition {I : Type v} (E : I → C)
    (F : SequentialSystem C) (n : ℕ) : Prop :=
  ∃ (Y : C) (a : Y ⟶ F.obj n)
    (c : F.obj (n + 1) ⟶ Y⟦(1 : ℤ)⟧),
    IsDirectSumOfShifts E Y ∧
      Triangle.mk a (sequentialTransition F n) c ∈ distTriang C

/-!
A sequential system with the source's indexing convention: `F.obj 0` is
`X₁`, and `F.obj (n + 1)` is `Xₙ₊₂`.
-/
def IsShiftGeneratedSequence {I : Type v} (E : I → C)
    (F : SequentialSystem C) : Prop :=
  IsDirectSumOfShifts E (F.obj 0) ∧
    ∀ n : ℕ, IsGeneratedTransition E F n

section HomotopyColimitPresentation

variable [CategoryTheory.IsTriangulated C]
  [HasCountableCoproducts C]

/-!
Every object admits the source's homotopy-colimit presentation from a
compact generating family.  `IsDerivedColimit` is Chapter 33's chosen
interface for the displayed homotopy-colimit triangle.
-/
theorem exists_homotopyColimit_of_compact_generators
    {I : Type v} (E : I → C)
    (hE : ∀ i, IsCompactObject (E i))
    (hgen : IsGenerator (∐ E)) (X : C) :
    ∃ F : SequentialSystem C,
      IsDerivedColimit F X ∧ IsShiftGeneratedSequence E F := by
  sorry

end HomotopyColimitPresentation

/-!
Membership in the finitely generated subcategory used by the factorization
lemma.  The finite coproduct is the canonical finite direct sum in the
additive category, and `generatedSubcategory` is the Chapter 36 thick
subcategory generated by that finite sum.
-/
def IsInFiniteGeneratedSubcategory {I : Type v} (E : I → C) (X : C) : Prop :=
  ∃ (n : ℕ) (ι : Fin n → I),
    generatedSubcategory (∐ fun j => E (ι j)) X

/-!
Maps from a compact object into a stage of a shift-generated sequence factor
through an object generated by a finite direct sum of members of the family.
-/
theorem compact_map_factors_through_finite_generated
    {I : Type v} (E : I → C) (F : SequentialSystem C)
    (hF : IsShiftGeneratedSequence E F)
    {K : C} (hK : IsCompactObject K) {n : ℕ} (f : K ⟶ F.obj n) :
    ∃ (G : C) (g : K ⟶ G) (h : G ⟶ F.obj n),
      f = g ≫ h ∧ IsInFiniteGeneratedSubcategory E G := by
  sorry

/-! Compact generation by a set of compact objects. -/
def IsCompactlyGenerated : Prop :=
  ∃ (I : Type v) (E : I → C),
    (∀ i, IsCompactObject (E i)) ∧ IsGenerator (∐ E)

/-! Classical generation of the compact-object subcategory by one object. -/
def IsClassicalGeneratorForCompactObjects
    (E : C) : Prop :=
  compactObjects (C := C) = generatedSubcategory E

/-!
For a compact object `E`, being a classical generator of the compact
subcategory together with compact generation of the ambient category is
equivalent to being a weak generator of the ambient category.
-/
theorem generator_iff_classical_generator_for_compact_objects
    (E : C) (hE : IsCompactObject E) :
    (IsClassicalGeneratorForCompactObjects E ∧
      IsCompactlyGenerated (C := C)) ↔ IsGenerator E := by
  sorry

end CompactObjects

end Formalization.Books.Derived.Unit37
