import Formalization.Books.Modules.Unit03.AbelianCategory
import Formalization.Books.Sheaves.Unit17.Modules
import Mathlib.Algebra.Category.ModuleCat.Presheaf.Monoidal
import Mathlib.Algebra.Category.ModuleCat.Presheaf.Submodule
import Mathlib.Algebra.Category.ModuleCat.Sheaf.Generators
import Mathlib.CategoryTheory.Subobject.Limits

/-!
# Modules, Chapter 4: Sections of sheaves of modules

This file formalizes the precise definitions and statements in the section
`Sections of sheaves of modules`.  The canonical Mathlib free-sheaf and
generating-sections interfaces are used for global generation.  Subsheaves are
represented by categorical subobjects, and local sections are represented by
their domain together with their value on that domain.
-/

namespace Formalization.Books.Modules.Unit04

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open Formalization.Books.Modules.Unit03
open Formalization.Books.Sheaves.Unit10
open Formalization.Books.Sheaves.Unit17

universe v

noncomputable section

/-! ## A global section and its associated morphism -/

/-- The morphism of sheaves of modules associated to a global section. -/
noncomputable def globalSectionMap {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (s : F.sections) :
    SheafOfModules.unit O ⟶ F :=
  F.unitHomEquiv.symm s

/-- The associated morphism has the prescribed global section. -/
theorem globalSectionMap_section {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (s : F.sections) :
    F.unitHomEquiv (globalSectionMap s) = s := by
  exact F.unitHomEquiv.apply_symm_apply s

/-- On an open set, the associated morphism sends `f` to `f • s|_U`. -/
theorem globalSectionMap_app {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (s : F.sections)
    (U : Opens X) (f : O.obj.obj (op U)) :
    ((globalSectionMap s).val.app (op U)).hom f = f • s.eval (op U) := by
  change (LinearMap.ringLmapEquivSelf (O.obj.obj (op U)) ℤ
    (F.val.obj (op U))).symm (s.val (op U)) f = f • s.eval (op U)
  simp [LinearMap.ringLmapEquivSelf]

/-- Every morphism out of the rank-one sheaf is the morphism associated to
the global section obtained by evaluating it at `1`. -/
theorem globalSectionMap_unique {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (φ : SheafOfModules.unit O ⟶ F) :
    globalSectionMap (F.unitHomEquiv φ) = φ := by
  exact F.unitHomEquiv.symm_apply_apply φ

/-! ## Global generation -/

/-- The canonical map from a free sheaf indexed by `I` to a sheaf of modules,
associated to a family of global sections. -/
noncomputable def globalGenerationMap {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} {I : Type v}
    (s : I → F.sections) : SheafOfModules.free I ⟶ F :=
  F.freeHomEquiv.symm s

/-- A family of global sections generates when its canonical free-sheaf map is
an epimorphism. -/
def globallyGenerates {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} {I : Type v}
    (s : I → F.sections) : Prop :=
  Epi (globalGenerationMap s)

/-- A sheaf is globally generated when it has a Mathlib generating family. -/
def globallyGenerated {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} (F : Mod O) : Prop :=
  Nonempty F.GeneratingSections

/-- The source definition of global generation, expressed using the canonical
`GeneratingSections` structure. -/
theorem globallyGenerated_iff {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} (F : Mod O) :
    globallyGenerated F ↔
      ∃ (I : Type v) (s : I → F.sections), globallyGenerates s := by
  constructor
  · rintro ⟨σ⟩
    exact ⟨σ.I, σ.s, σ.epi⟩
  · rintro ⟨I, s, hs⟩
    exact ⟨{ I := I, s := s, epi := hs }⟩

/-! ## Global sections and stalks -/

/-- The germ at `x` of a global section. -/
noncomputable def globalSectionGerm {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (s : F.sections) (x : X) :
    (sheafModuleStalkFunctor O x).obj F :=
  TopCat.Presheaf.Γgerm (C := AddCommGrpCat.{v}) F.val.presheaf x
    (s.val (op ⊤))

/-- The stalk submodule generated by the germs of a family of global
sections. -/
def globalSectionGermSubmodule {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} {I : Type v}
    (s : I → F.sections) (x : X) :
    Submodule (TopCat.Presheaf.stalk (C := RingCat.{v}) O.obj x)
      ((sheafModuleStalkFunctor O x).obj F) :=
  Submodule.span _ (Set.range (fun i => globalSectionGerm (s i) x))

/-- A family of global sections generates if and only if its germs generate
every stalk. -/
theorem globallyGenerates_iff_stalks {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} {I : Type v}
    (s : I → F.sections) :
    globallyGenerates s ↔
      ∀ x : X, globalSectionGermSubmodule s x = ⊤ := by
  sorry

/-! ## Local sections and the generated subsheaf -/

/-- A local section of a sheaf of modules, including the open on which it is
defined. -/
structure LocalSection {X : TopCat.{v}} (O : RingSheaf.{v, v} X)
    (F : Mod O) where
  U : Opens X
  s : F.val.obj (op U)

/-- A local section is defined at a point when the point lies in its domain. -/
def LocalSection.isDefinedAt {X : TopCat.{v}} {O : RingSheaf.{v, v} X}
    {F : Mod O} (t : LocalSection O F) (x : X) : Prop :=
  x ∈ t.U

/-- The stalk germ of a local section at a point of its domain. -/
noncomputable def localSectionGerm {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (t : LocalSection O F)
    (x : X) (hx : t.isDefinedAt x) :
    (sheafModuleStalkFunctor O x).obj F :=
  TopCat.Presheaf.germ (C := AddCommGrpCat.{v}) F.val.presheaf t.U x hx t.s

/-- A local section belongs to a categorical subsheaf when it has a lift to
that subsheaf on its domain. -/
def localSectionInSubobject {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (P : Subobject F)
    (t : LocalSection O F) : Prop :=
  ∃ u : (P : Mod O).val.obj (op t.U),
    P.arrow.val.app (op t.U) u = t.s

/-- The property that a presheaf submodule contains a given set of local
sections on their domains. -/
def localSectionPresheafContains {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F))
    (N : PresheafOfModules.Submodule F.val) : Prop :=
  ∀ t ∈ S, t.s ∈ N.obj (op t.U)

/-- The smallest presheaf submodule containing a given set of local sections.
The complete lattice of presheaf submodules supplies the intersection, so the
restriction-map stability is built into the construction. -/
noncomputable def localSectionPresheafSubmodule {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) : PresheafOfModules.Submodule F.val :=
  sInf {N | localSectionPresheafContains S N}

/-- Every supplied local section belongs to the smallest presheaf submodule. -/
theorem localSectionPresheafSubmodule_contains {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) (t : LocalSection O F) (ht : t ∈ S) :
    t.s ∈ (localSectionPresheafSubmodule S).obj (op t.U) := by
  change t.s ∈ (sInf {N | localSectionPresheafContains S N}).obj (op t.U)
  change t.s ∈ ⨅ N ∈ {N | localSectionPresheafContains S N}, N.obj (op t.U)
  rw [Submodule.mem_iInf]
  intro N
  rw [Submodule.mem_iInf]
  intro hN
  exact hN t ht

/-- The sheafification of the smallest presheaf submodule, mapped into the
ambient sheaf. -/
noncomputable def sheafifiedLocalSectionMap {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) :
    (PresheafOfModules.sheafification (𝟙 O.obj)).obj
        (localSectionPresheafSubmodule S).toPresheafOfModules ⟶ F :=
  (PresheafOfModules.sheafificationHomEquiv (𝟙 O.obj)).symm
    (localSectionPresheafSubmodule S).ι

/-- The categorical subobject obtained by sheafifying the smallest presheaf
submodule containing a given set of local sections. -/
noncomputable def generatedSubsheaf {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) : Subobject F := by
  exact imageSubobject (sheafifiedLocalSectionMap S)

/-- Every supplied local section belongs to the generated subsheaf. -/
theorem generatedSubsheaf_contains {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) (t : LocalSection O F) (ht : t ∈ S) :
    localSectionInSubobject (generatedSubsheaf S) t := by
  sorry

/-- The generated subsheaf is contained in every subsheaf containing the
supplied local sections. -/
theorem generatedSubsheaf_le {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) (P : Subobject F)
    (hP : ∀ t ∈ S, localSectionInSubobject P t) :
    generatedSubsheaf S ≤ P := by
  sorry

/-- The subsheaf generated by local sections, in the source's terminology. -/
abbrev subsheafGeneratedByLocalSections {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) : Subobject F :=
  generatedSubsheaf S

/-- The submodule of a stalk generated by all supplied local-section germs
which are defined at the point. -/
def localSectionGermSubmodule {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) (x : X) :
    Submodule (TopCat.Presheaf.stalk (C := RingCat.{v}) O.obj x)
      ((sheafModuleStalkFunctor O x).obj F) :=
  Submodule.span _
    {m | ∃ t ∈ S, ∃ hx : t.isDefinedAt x, localSectionGerm t x hx = m}

/-- The image in a stalk of a categorical subsheaf inclusion. -/
noncomputable def subobjectStalkImage {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O} (P : Subobject F) (x : X) :
    Submodule (TopCat.Presheaf.stalk (C := RingCat.{v}) O.obj x)
      ((sheafModuleStalkFunctor O x).obj F) :=
  LinearMap.range ((sheafModuleStalkFunctor O x).map P.arrow).hom

/-- The stalk of the generated subsheaf is generated by the germs of exactly
the local sections defined at that point.  The left-hand side is the
canonical stalk image of the categorical subobject. -/
theorem generatedSubsheaf_stalk {X : TopCat.{v}}
    {O : RingSheaf.{v, v} X} {F : Mod O}
    (S : Set (LocalSection O F)) (x : X) :
    subobjectStalkImage (generatedSubsheaf S) x =
      localSectionGermSubmodule S x := by
  sorry

/-! ## Tensor products -/

/-- The tensor product sheaf of two modules over a commutative structure
sheaf, obtained by sheafifying the presheaf tensor product. -/
noncomputable def tensorProductSheaf {X : TopCat.{v}}
    (O : CommRingSheaf X) (F G : CommRingSheafModule O) :
    CommRingSheafModule O :=
  (PresheafOfModules.sheafification (𝟙 (commRingSheafToRingSheaf O).obj)).obj
    (PresheafOfModules.Monoidal.tensorObj F.val G.val)

/-- The tensor product of globally generated sheaves is globally generated. -/
theorem tensorProductSheaf_globallyGenerated {X : TopCat.{v}}
    (O : CommRingSheaf X) {F G : CommRingSheafModule O}
    (hF : globallyGenerated F) (hG : globallyGenerated G) :
    globallyGenerated (tensorProductSheaf O F G) := by
  sorry

end
end Formalization.Books.Modules.Unit04
