import Formalization.Books.Algebra.Unit92.CountablyGeneratedMittagLeffler
import Mathlib.Algebra.DirectSum.Module
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.RingTheory.PowerSeries.Basic

/-!
# Commutative Algebra, Chapter 93: Characterizing projective modules

This file formalizes the first source section.  Projectivity, flatness,
countable generation, direct sums, Mittag--Lefflerness, and universal
injectivity use the canonical interfaces from earlier chapters.
-/

namespace Formalization.Books.Algebra.Unit93

open Formalization.Books.Algebra.Unit82
open Formalization.Books.Algebra.Unit84
open Formalization.Books.Algebra.Unit88
open scoped DirectSum TensorProduct

universe u v

noncomputable section

/-! ## Countably generated projective modules -/

/-- A flat, Mittag--Leffler, countably generated module is projective. -/
theorem projective_of_flat_of_mittagLeffler_of_countablyGenerated
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M]
    (hflat : Module.Flat R M)
    (hML : IsMittagLefflerModule (ModuleCat.of R M))
    (hcountable : Module.IsCountablyGenerated R M) :
    Module.Projective R M := by
  sorry

/-! ## The power-series warning -/

/-- The coefficient condition defining the submodule used in the source's
integer power-series counterexample. -/
def integerPowerSeriesCondition (p : ℕ) (f : PowerSeries ℤ) : Prop :=
  ∀ m : ℕ, 1 ≤ m →
    ∀ᶠ i in Filter.cofinite, (p : ℤ) ^ m ∣ PowerSeries.coeff i f

/-- The submodule of power series whose coefficients are eventually divisible
by every positive power of `p`.  The carrier characterization is recorded by
`integerPowerSeriesSubmodule_carrier` below. -/
def integerPowerSeriesSubmodule (p : ℕ) : Submodule ℤ (PowerSeries ℤ) :=
  Submodule.span ℤ {f : PowerSeries ℤ | integerPowerSeriesCondition p f}

/-- The span construction has exactly the coefficient condition from the
source. -/
theorem integerPowerSeriesSubmodule_carrier (p : ℕ) (f : PowerSeries ℤ) :
    f ∈ integerPowerSeriesSubmodule p ↔ integerPowerSeriesCondition p f := by
  sorry

/-- The power series with coefficients `aᵢ pⁱ` used to show that the witness
submodule is uncountable. -/
def integerPowerSeriesWitness (p : ℕ) (a : ℕ → ℤ) : PowerSeries ℤ :=
  PowerSeries.mk (fun i => a i * (p : ℤ) ^ i)

/-- Every displayed power series belongs to the source's submodule. -/
theorem integerPowerSeriesWitness_mem (p : ℕ) (a : ℕ → ℤ) :
    integerPowerSeriesWitness p a ∈ integerPowerSeriesSubmodule p := by
  sorry

/-- For a prime `p`, the source's power-series submodule is uncountable. -/
theorem integerPowerSeriesSubmodule_not_countable
    (p : ℕ) (hp : p.Prime) :
    ¬ (integerPowerSeriesSubmodule p : Set (PowerSeries ℤ)).Countable := by
  sorry

/-- The quotient `N / pN` appearing in the source's non-freeness argument. -/
abbrev integerPowerSeriesModP (p : ℕ) : Type :=
  (integerPowerSeriesSubmodule p : Type) ⧸
    (Ideal.span ({(p : ℤ)} : Set ℤ) •
      (⊤ : Submodule ℤ (integerPowerSeriesSubmodule p : Type)))

/-- The quotient `N / pN` is countably generated by the classes of the
monomials. -/
theorem integerPowerSeriesModP_countablyGenerated
    (p : ℕ) (hp : p.Prime) :
    Module.IsCountablyGenerated
      (ℤ ⧸ Ideal.span ({(p : ℤ)} : Set ℤ))
      (integerPowerSeriesModP p) := by
  sorry

/-- The power-series submodule in the warning is not free. -/
theorem integerPowerSeriesSubmodule_not_free
    (p : ℕ) (hp : p.Prime) :
    ¬ Module.Free ℤ (integerPowerSeriesSubmodule p : Type) := by
  sorry

/-- The warning example: `ℤ[[x]]` is flat and Mittag--Leffler but not
projective. -/
theorem integerPowerSeries_flat_mittagLeffler_not_projective :
    Module.Flat ℤ (PowerSeries ℤ) ∧
      IsMittagLefflerModule (ModuleCat.of ℤ (PowerSeries ℤ)) ∧
        ¬ Module.Projective ℤ (PowerSeries ℤ) := by
  sorry

/-! ## The projectivity characterization -/

/-- Projectivity is equivalent to flatness, Mittag--Lefflerness, and being a
direct sum of countably generated modules. -/
theorem projectivity_characterization
    {R : Type u} {M : Type v} [CommRing R]
    [AddCommGroup M] [Module R M] :
    Module.Projective R M ↔
      Module.Flat R M ∧
        IsMittagLefflerModule (ModuleCat.of R M) ∧
          IsDirectSumOfCountablyGeneratedModules (ModuleCat.of R M) := by
  sorry

/-! ## Universally injective descent -/

/-- A universally injective map into a flat Mittag--Leffler module descends
projectivity to a countable direct sum of modules. -/
theorem projective_of_universallyInjective_of_directSumOfCountablyGenerated
    {R : Type u} {M N : Type v} [CommRing R]
    [AddCommGroup M] [Module R M]
    [AddCommGroup N] [Module R N]
    (f : M →ₗ[R] N) (hf : universallyInjective f)
    (hM : IsDirectSumOfCountablyGeneratedModules (ModuleCat.of R M))
    (hNflat : Module.Flat R N)
    (hNML : IsMittagLefflerModule (ModuleCat.of R N)) :
    Module.Projective R M := by
  sorry

/-- If a direct sum of countably generated modules over a Noetherian ring maps
universally injectively into a finite-variable formal power-series module, it
is projective. -/
theorem projective_of_universallyInjective_to_mvPowerSeries
    {R : Type u} {M : Type v} [CommRing R] [IsNoetherianRing R]
    [AddCommGroup M] [Module R M]
    (hM : IsDirectSumOfCountablyGeneratedModules (ModuleCat.of R M))
    {n : ℕ} (f : M →ₗ[R] MvPowerSeries (Fin n) R)
    (hf : universallyInjective f) :
    Module.Projective R M := by
  sorry

end

end Formalization.Books.Algebra.Unit93
