import Formalization.Books.Algebra.Unit93.AscendingProperties
import Mathlib.Algebra.DirectSum.Module
import Mathlib.LinearAlgebra.TensorProduct.Map

/-!
# Supporting interface for Commutative Algebra, Chapter 95

This file is retained as the implementation imported by Chapter 95's
chapter-facing wrapper.  It is not imported by the Chapter 93 top-level file.
The faithfully flat hypotheses use Mathlib's canonical
`Module.FaithfullyFlat` predicate.  Base change is written as
`S ⊗[R] M`, and the auxiliary maps below make the source's images and direct
sum decompositions explicit without introducing parallel module predicates.
-/

namespace Formalization.Books.Algebra.Unit93

open Formalization.Books.Algebra.Unit84
open Formalization.Books.Algebra.Unit88
open scoped DirectSum TensorProduct

universe u v w

noncomputable section

/-! ## Canonical base-change images -/

/-- The canonical map from the base change of an `R`-submodule to the base
change of the ambient module.  It is recorded as an `R`-linear map, which is
enough to describe its image and avoids choosing a second, parallel tensor
product construction. -/
def baseChangeSubmoduleMap
    {R S : Type u} {M : Type v} [CommRing R] [CommRing S]
    [Algebra R S] [AddCommGroup M] [Module R M]
    (P : Submodule R M) :
    TensorProduct R S (P : Type v) →ₗ[R] TensorProduct R S M :=
  TensorProduct.map (LinearMap.id : S →ₗ[R] S) P.subtype

/-- The submodule of a direct sum generated by the summands indexed by a
specified subset. -/
def selectedDirectSumSubmodule
    {S : Type u} [CommRing S] {I : Type v}
    (Q : I → ModuleCat.{w} S)
    (I' : Set I) : Submodule S (⨁ i, (Q i : Type w)) :=
  by
    classical
    exact Submodule.span S
      {x | ∃ i, i ∈ I' ∧ ∃ q : (Q i : Type w),
        DirectSum.lof S I (fun i => (Q i : Type w)) i q = x}

/-! ## Faithfully flat descent of the basic properties -/

/-- Mittag--Lefflerness descends along faithfully flat base change. -/
theorem mittagLeffler_descends_of_faithfullyFlat
    {R S : Type u} {M : Type v} [CommRing R] [CommRing S]
    [Algebra R S] [AddCommGroup M] [Module R M]
    [Module.FaithfullyFlat R S]
    (hML : IsMittagLefflerModule
      (ModuleCat.of S (S ⊗[R] M))) :
    IsMittagLefflerModule (ModuleCat.of R M) := by
  sorry

/-- Countable generation descends along faithfully flat base change. -/
theorem countablyGenerated_descends_of_faithfullyFlat
    {R S : Type u} {M : Type v} [CommRing R] [CommRing S]
    [Algebra R S] [AddCommGroup M] [Module R M]
    [Module.FaithfullyFlat R S]
    (hcountable : Module.IsCountablyGenerated S (S ⊗[R] M)) :
    Module.IsCountablyGenerated R M := by
  sorry

/-- Countably generated projectivity descends along faithfully flat base
change. -/
theorem countablyGenerated_projective_descends_of_faithfullyFlat
    {R S : Type u} {M : Type v} [CommRing R] [CommRing S]
    [Algebra R S] [AddCommGroup M] [Module R M]
    [Module.FaithfullyFlat R S]
    (hcountable : Module.IsCountablyGenerated S (S ⊗[R] M))
    (hprojective : Module.Projective S (S ⊗[R] M)) :
    Module.IsCountablyGenerated R M ∧ Module.Projective R M := by
  sorry

/-! ## Lifting and adapting countably generated submodules -/

/-- A countably generated `S`-submodule of a base change is contained in the
image of the base change of a countably generated `R`-submodule. -/
theorem exists_countablyGenerated_submodule_lifting
    {R S : Type u} {M : Type v} [CommRing R] [CommRing S]
    [Algebra R S] [AddCommGroup M] [Module R M]
    (Q : Submodule S (S ⊗[R] M))
    (hQ : Module.IsCountablyGenerated S (Q : Type (max u v))) :
    ∃ P : Submodule R M,
      Module.IsCountablyGenerated R (P : Type v) ∧
        (Q : Set (S ⊗[R] M)) ≤ Set.range (baseChangeSubmoduleMap P) := by
  sorry

/-- The adapted-submodule lemma from the source, with a chosen direct-sum
decomposition and the canonical base-change image made explicit. -/
theorem exists_adapted_submodule
    {R S : Type u} {M : Type v} [CommRing R] [CommRing S]
    [Algebra R S] [AddCommGroup M] [Module R M]
    (I : Type v) (Q : I → ModuleCat.{max u v} S)
    (hQ : ∀ i, Module.IsCountablyGenerated S (Q i : Type (max u v)))
    (e : (S ⊗[R] M) ≃ₗ[S]
      (⨁ i, (Q i : Type (max u v))))
    (N : Submodule R M)
    (hN : Module.IsCountablyGenerated R (N : Type v)) :
    ∃ N' : Submodule R M,
      N ≤ N' ∧ Module.IsCountablyGenerated R (N' : Type v) ∧
        ∃ I' : Set I,
          Set.range (baseChangeSubmoduleMap N') =
            (Submodule.comap e.toLinearMap
              (selectedDirectSumSubmodule Q I') :
                Set (S ⊗[R] M)) := by
  sorry

/-! ## Faithfully flat descent of projectivity -/

/-- Projectivity descends along faithfully flat base change without a
countability hypothesis. -/
theorem projective_descends_of_faithfullyFlat
    {R S : Type u} {M : Type v} [CommRing R] [CommRing S]
    [Algebra R S] [AddCommGroup M] [Module R M]
    [Module.FaithfullyFlat R S]
    (hprojective : Module.Projective S (S ⊗[R] M)) :
    Module.Projective R M := by
  sorry

end

end Formalization.Books.Algebra.Unit93
