import Formalization.Books.Algebra.Unit159.ConstructingFlatRingMaps
import Formalization.Books.Algebra.Unit105.CatenaryRings
import Mathlib.RingTheory.AdicCompletion.LocalRing
import Mathlib.RingTheory.Artinian.Defs
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.LocalRing.ResidueField.Basic
import Mathlib.RingTheory.PowerSeries.Basic
import Mathlib.RingTheory.RegularLocalRing.Defs
import Mathlib.RingTheory.RingHom.Smooth
import Mathlib.RingTheory.Smooth.Basic

/-!
# Commutative Algebra, Chapter 160: The Cohen structure theorem

This file records the complete-local, coefficient-ring, and Cohen-ring
interfaces used in the chapter.  The substantial existence and structure
theorems are intentionally left for the proof stage.
-/

namespace Formalization.Books.Algebra.Unit160

open scoped BigOperators

universe u v

noncomputable section

/-! ## Complete local rings -/

/-- A local ring is complete when it is complete for its maximal-ideal
adic topology.  This is equivalent to bijectivity of the canonical map to the
adic completion. -/
def IsCompleteLocalRing (R : Type u) [CommRing R] [IsLocalRing R] : Prop :=
  IsAdicComplete (IsLocalRing.maximalIdeal R) R

/-- Artinian local rings are complete because a power of the maximal ideal is
zero. -/
theorem artinianLocalRing_isCompleteLocalRing
    (R : Type u) [CommRing R] [IsLocalRing R] [IsArtinianRing R] :
    IsCompleteLocalRing R := by
  sorry

/-- A proper quotient of a Noetherian complete local ring is again Noetherian
and complete local.  The properness hypothesis records the nontriviality
convention in Mathlib's `IsLocalRing` class. -/
theorem quotient_isNoetherian_completeLocalRing
    (R : Type u) [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    (hR : IsCompleteLocalRing R) (I : Ideal R) (hI : I ≠ ⊤) :
    IsNoetherianRing (R ⧸ I) ∧
      ∃ hS : IsLocalRing (R ⧸ I),
        @IsCompleteLocalRing (R ⧸ I) inferInstance hS := by
  sorry

/-- A finite family of complete local rings, packaged with its product ring.
The explicit class witnesses make the predicate usable when the family is
introduced existentially. -/
def IsFiniteProductOfCompleteLocalRings
    (S : Type u) [CommRing S] : Prop :=
  ∃ (n : ℕ) (A : Fin n → CommRingCat.{u}),
    Nonempty (S ≃+* ∀ i, A i) ∧
      ∀ i, ∃ hA : IsLocalRing (A i),
        @IsCompleteLocalRing (A i) inferInstance hA ∧
          IsNoetherianRing (A i)

/-- A finite algebra over a Noetherian complete local ring is a finite product
of Noetherian complete local rings. -/
theorem finiteAlgebra_isFiniteProductOfCompleteLocalRings
    (R : Type u) [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    (hR : IsCompleteLocalRing R) (S : Type v) [CommRing S]
    [Algebra R S] [Module.Finite R S] :
    IsFiniteProductOfCompleteLocalRings S := by
  sorry

/-- A complete local ring with finitely generated maximal ideal is
Noetherian. -/
theorem completeLocalRing_isNoetherian_of_maximalIdeal_fg
    (R : Type u) [CommRing R] [IsLocalRing R]
    (hR : IsCompleteLocalRing R)
    (hfg : (IsLocalRing.maximalIdeal R).FG) :
    IsNoetherianRing R := by
  sorry

/-! ## Coefficient rings and Cohen rings -/

/-- A subring is a coefficient ring when its maximal ideal is the contraction
of the ambient maximal ideal, it is adically complete, its residue map is an
isomorphism, and that maximal ideal is generated by the characteristic. -/
def IsCoefficientRing
    (R : Type u) [CommRing R] [IsLocalRing R] (Λ : Subring R) : Prop :=
  ∃ hΛ : IsLocalRing (Λ : Type u),
    letI : IsLocalRing (Λ : Type u) := hΛ
    ∃ m : Ideal Λ,
      m.IsMaximal ∧
        IsAdicComplete m Λ ∧
        m = IsLocalRing.maximalIdeal Λ ∧
        m = (IsLocalRing.maximalIdeal R).comap Λ.subtype ∧
        (∃ f : (Λ ⧸ m) →+* IsLocalRing.ResidueField R,
          f.comp (Ideal.Quotient.mk m) =
              (IsLocalRing.residue R).comp Λ.subtype ∧
            Function.Bijective f) ∧
        ∃ p : ℕ, CharP (IsLocalRing.ResidueField R) p ∧
          m = Ideal.span ({(p : Λ)} : Set Λ)

/-- A Cohen ring is a complete discrete valuation ring whose uniformizer is
the prime number giving the characteristic of its residue field. -/
def IsCohenRing
    (Λ : Type u) [CommRing Λ] [IsLocalRing Λ] : Prop :=
  IsCompleteLocalRing Λ ∧
    ∃ hΛ : IsDomain Λ,
      ∃ _ : @IsDiscreteValuationRing Λ inferInstance hΛ,
        ∃ p : ℕ,
          Nat.Prime p ∧
            CharP (IsLocalRing.ResidueField Λ) p ∧
              Ideal.span ({(p : Λ)} : Set Λ) = IsLocalRing.maximalIdeal Λ

/-- A coefficient ring of either equal or mixed characteristic is a field or
a Cohen ring. -/
def IsCohenStructureBase
    (Λ : Type u) [CommRing Λ] [IsLocalRing Λ] : Prop :=
  IsField Λ ∨ IsCohenRing Λ

/-- Every field of prime characteristic occurs as the residue field of a
Cohen ring. -/
theorem exists_cohenRing
    (k : Type u) [Field k] (p : ℕ) [CharP k p] (hp : Nat.Prime p) :
    ∃ (Λ : Type u) (hΛ : CommRing Λ) (hLocal : IsLocalRing Λ),
      letI : CommRing Λ := hΛ
      letI : IsLocalRing Λ := hLocal
      IsCohenRing Λ ∧
        Nonempty (IsLocalRing.ResidueField Λ ≃+* k) ∧
          CharP (IsLocalRing.ResidueField Λ) p := by
  sorry

/-- The reduction map from `ℤ / p^n ℤ` to the corresponding quotient of a
Cohen ring. -/
def cohenReductionMap
    (Λ : Type u) [CommRing Λ] (p n : ℕ) :
    (ℤ ⧸ Ideal.span ({((p ^ n : ℕ) : ℤ)} : Set ℤ)) →+*
      (Λ ⧸ Ideal.span ({((p ^ n : ℕ) : Λ)} : Set Λ)) :=
  Ideal.quotientMap
    (Ideal.span ({((p ^ n : ℕ) : Λ)} : Set Λ)) (Int.castRingHom Λ) (by
      refine Ideal.span_le.2 ?_
      rintro x rfl
      simpa using
        (Ideal.mem_span_singleton_self ((p ^ n : ℕ) : Λ)))

/-- The finite-level reductions of a Cohen ring are formally smooth over the
corresponding truncated integers. -/
theorem cohenReductionMap_formallySmooth
    (Λ : Type u) [CommRing Λ] [IsLocalRing Λ]
    (hΛ : IsCohenRing Λ) (p n : ℕ) (hp : Nat.Prime p)
    (hchar : CharP (IsLocalRing.ResidueField Λ) p) (hn : 1 ≤ n) :
    RingHom.FormallySmooth (cohenReductionMap Λ p n) := by
  sorry

/-! ## The Cohen structure theorem -/

/-- Cohen's structure theorem: every complete local ring has a coefficient
ring, and a Noetherian one is a quotient of a power-series ring over a field
or a Cohen ring. -/
theorem cohen_structure_theorem
    (R : Type u) [CommRing R] [IsLocalRing R]
    (hR : IsCompleteLocalRing R) :
    (∃ Λ : Subring R, IsCoefficientRing R Λ) ∧
      ((IsLocalRing.maximalIdeal R).FG →
        ∃ (Λ : Type u) (hΛ : CommRing Λ) (hLocal : IsLocalRing Λ),
          letI : CommRing Λ := hΛ
          letI : IsLocalRing Λ := hLocal
          IsCohenStructureBase Λ ∧
            ∃ n : ℕ, ∃ I : Ideal (MvPowerSeries (Fin n) Λ),
              Nonempty (R ≃+* (MvPowerSeries (Fin n) Λ ⧸ I))) := by
  sorry

/-! ## The regular power-series consequence -/

/-- A convenient interface for the regular, complete local power-series rings
appearing in the chapter's remark. -/
def IsNoetherianCompleteRegularLocalRingOfDimension
    (R : Type u) [CommRing R] (d : ℕ) : Prop :=
  ∃ hLocal : IsLocalRing R,
    letI : IsLocalRing R := hLocal
    ∃ hNoetherian : IsNoetherianRing R,
      letI : IsNoetherianRing R := hNoetherian
      ∃ hRegular : IsRegularLocalRing R,
        letI : IsRegularLocalRing R := hRegular
        @IsCompleteLocalRing R inferInstance hLocal ∧
          ringKrullDim R = (d : WithBot ℕ∞)

/-- A power-series ring over a field is Noetherian, complete local, regular,
and has the expected dimension. -/
theorem fieldPowerSeries_isNoetherianCompleteRegularLocalRing
    (k : Type u) [Field k] (d : ℕ) :
    IsNoetherianCompleteRegularLocalRingOfDimension
      (MvPowerSeries (Fin d) k) d := by
  sorry

/-- A power-series ring over a Cohen ring is Noetherian, complete local,
regular, and has dimension one larger than the number of variables. -/
theorem cohenPowerSeries_isNoetherianCompleteRegularLocalRing
    (Λ : Type u) [CommRing Λ] [IsLocalRing Λ]
    (hΛ : IsCohenRing Λ) (d : ℕ) :
    IsNoetherianCompleteRegularLocalRingOfDimension
      (MvPowerSeries (Fin d) Λ) (d + 1) := by
  sorry

/-- The Cohen structure theorem makes every Noetherian complete local ring
universally catenary. -/
theorem noetherianCompleteLocalRing_isUniversallyCatenary
    (R : Type u) [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    (hR : IsCompleteLocalRing R) :
    Formalization.Books.Algebra.Unit105.IsUniversallyCatenary R := by
  sorry

/-! ## Regular complete local rings -/

/-- The source's “contains either `𝔽ₚ` or `ℚ`” hypothesis. -/
def ContainsPrimeFieldOrRationals
    (R : Type u) [CommRing R] : Prop :=
  (∃ p : ℕ, Nat.Prime p ∧ Nonempty (ZMod p →+* R)) ∨
    Nonempty (ℚ →+* R)

/-- A regular Noetherian complete local ring containing its prime field or the
rationals is a power-series ring over its residue field. -/
theorem regularCompleteLocalRing_powerSeries_of_containsPrimeFieldOrRationals
    (R : Type u) [CommRing R] [IsRegularLocalRing R]
    (hR : IsCompleteLocalRing R)
    (hcontains : ContainsPrimeFieldOrRationals R) :
    ∃ n : ℕ,
      Nonempty (R ≃+* MvPowerSeries (Fin n) (IsLocalRing.ResidueField R)) := by
  sorry

/-- The residue-field version of the power-series presentation of a regular
complete local ring. -/
theorem regularCompleteLocalRing_powerSeries_over_field
    (R : Type u) [CommRing R] [IsRegularLocalRing R]
    (hR : IsCompleteLocalRing R) (k : Type v) [Field k]
    (f : k →+* R)
    (hres : ∃ e : k ≃+* IsLocalRing.ResidueField R,
      e.toRingHom = (IsLocalRing.residue R).comp f) :
    ∃ n : ℕ, Nonempty (R ≃+* MvPowerSeries (Fin n) k) := by
  sorry

/-- The data of a finite regular complete local subring, including its
power-series description over a field or a Cohen ring. -/
def IsFiniteRegularCompleteLocalSubring
    (R : Type u) [CommRing R] [IsLocalRing R] (R₀ : Subring R) : Prop :=
  ∃ hR₀ : IsRegularLocalRing (R₀ : Type u),
    letI : IsRegularLocalRing (R₀ : Type u) := hR₀
    @IsCompleteLocalRing (R₀ : Type u) inferInstance inferInstance ∧
      (letI : Algebra (R₀ : Type u) R := R₀.subtype.toAlgebra
       Module.Finite (R₀ : Type u) R) ∧
      (∃ e : IsLocalRing.ResidueField (R₀ : Type u) ≃+*
          IsLocalRing.ResidueField R,
        e.toRingHom.comp (IsLocalRing.residue (R₀ : Type u)) =
          (IsLocalRing.residue R).comp R₀.subtype) ∧
      ∃ (Λ : Type u) (hΛ : CommRing Λ) (hLocal : IsLocalRing Λ),
        letI : CommRing Λ := hΛ
        letI : IsLocalRing Λ := hLocal
        IsCohenStructureBase Λ ∧
          ∃ n : ℕ,
            Nonempty ((R₀ : Type u) ≃+* MvPowerSeries (Fin n) Λ)

/-- A Noetherian complete local domain contains a finite regular complete
local subring with the power-series form supplied by Cohen's theorem. -/
theorem completeLocalDomain_exists_finiteRegularCompleteLocalSubring
    (R : Type u) [CommRing R] [IsLocalRing R] [IsNoetherianRing R]
    [IsDomain R] (hR : IsCompleteLocalRing R) :
    ∃ R₀ : Subring R, IsFiniteRegularCompleteLocalSubring R R₀ := by
  sorry

end

end Formalization.Books.Algebra.Unit160
