import Mathlib.AlgebraicTopology.SimplexCategory.GeneratorsRelations.Basic
import Mathlib.SetTheory.Cardinal.NatCard

/-!
# Simplicial Methods, Chapter 2: The category of finite ordered sets

The canonical model of the simplex category is already provided by Mathlib.
This file records the source-facing assertions which are not single existing
declarations, while referring directly to Mathlib's objects, morphisms, face
maps, degeneracy maps, and simplicial identities.
-/

namespace Formalization.Books.Simplicial.Unit02

open CategoryTheory

/-!
The source's category `Δ`, its objects `[n]`, and its nondecreasing maps are
Mathlib's `SimplexCategory`, `⦋n⦌`, and `SimplexCategory.Hom`.  The underlying
hom equivalence is `SimplexCategory.homEquivOrderHom`.  The assertion that
this is equivalent to the category of nonempty finite linearly ordered sets
is provided by `SimplexCategory.skeletalEquivalence`.

The source's face and degeneracy maps are exactly
`SimplexCategory.δ` and `SimplexCategory.σ`; both have real definitions in
Mathlib.  Their index types `Fin (n + 2)` and `Fin (n + 1)` express the bounds
on the source indices.
-/

/-! ### The small hom-set cardinalities -/

theorem hom_card_zero_to (n : ℕ) :
    Nat.card (SimplexCategory.mk 0 ⟶ SimplexCategory.mk n) = n + 1 := by
  sorry

theorem hom_card_to_zero (n : ℕ) :
    Nat.card (SimplexCategory.mk n ⟶ SimplexCategory.mk 0) = 1 := by
  sorry

theorem hom_card_one_to (n : ℕ) :
    Nat.card (SimplexCategory.mk 1 ⟶ SimplexCategory.mk n) = (n + 1) * (n + 2) / 2 := by
  sorry

theorem hom_card_to_one (n : ℕ) :
    Nat.card (SimplexCategory.mk n ⟶ SimplexCategory.mk 1) = n + 2 := by
  sorry

/-!
The factorization assertion in the source is represented using Mathlib's
canonical generators-and-relations presentation.  Its
`generators.multiplicativeClosure` is precisely the predicate that a
morphism is an identity or a composition of face and degeneracy generators.
-/

theorem every_simplex_morphism_is_generated
    {n m : ℕ} (f : SimplexCategory.mk n ⟶ SimplexCategory.mk m) :
    ∃ g : SimplexCategoryGenRel.mk n ⟶ SimplexCategoryGenRel.mk m,
      SimplexCategoryGenRel.toSimplexCategory.map g = f ∧
        SimplexCategoryGenRel.generators.multiplicativeClosure g := by
  sorry

/-!
The five displayed source diagrams are already covered by the stronger,
source-faithful Mathlib identities:

* source (1): `SimplexCategory.δ_comp_δ`;
* source (2): `SimplexCategory.δ_comp_σ_of_le`;
* source (3): `SimplexCategory.δ_comp_σ_self` and
  `SimplexCategory.δ_comp_σ_succ`;
* source (4): `SimplexCategory.δ_comp_σ_of_gt`;
* source (5): `SimplexCategory.σ_comp_σ`.

The `Fin.castSucc` and `Fin.succ` indices in those declarations are the
canonical typed form of the source's integer index bounds, so no parallel
face/degeneracy identities are introduced here.
-/

/-!
The presentation category and its canonical functor are also existing
definitions: `SimplexCategoryGenRel` is generated by the six typed families
of relation constructors, and
`SimplexCategoryGenRel.multiplicativeClosure_isGenerator_eq_top` records that
all of its morphisms are generated by faces and degeneracies.  The remaining
universal-category assertion from the source is the equivalence statement
below; its proof is left for the proof stage.
-/

theorem toSimplexCategory_is_equivalence :
    Functor.IsEquivalence SimplexCategoryGenRel.toSimplexCategory := by
  sorry

end Formalization.Books.Simplicial.Unit02
