import Formalization.Books.Dpa.Unit03
import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.DividedPowers.SubDPIdeal
import Mathlib.RingTheory.RingHom.Flat

/-!
# Divided Power Algebra, Chapter 4: Extending divided powers

This file formalizes the source section “Extending divided powers”.  The
divided-power structures are Mathlib's `DividedPowers`; the definitions below
record extension along an ordinary ring homomorphism, sub-divided-power ideals,
and the adic-completion statement using Mathlib's inverse-limit completion.
-/

namespace Formalization.Books.Dpa.Unit04

open CategoryTheory CategoryTheory.Limits

universe u

noncomputable section

open Formalization.Books.Dpa.Unit03
open Formalization.Books.Dpa.Unit03.DividedPowerRing

/-! ## Extending a divided power structure -/

/-- A divided power structure on `I` extends along `f : A →+* B` when the
induced structure on the extended ideal `I.map f` makes `f` preserve all
divided powers. -/
def DpExtends (A : DividedPowerRing.{u}) {B : Type u} [CommRing B]
    (f : (A : Type u) →+* B) : Prop :=
  ∃ δ : DividedPowers (Ideal.map f A.ideal),
    ∀ {n : ℕ} {x : A}, x ∈ A.ideal →
      δ.dpow n (f x) = f (A.dividedPowers.dpow n x)

/-- The property of a specified structure being an extension. -/
def IsDpExtension (A : DividedPowerRing.{u}) {B : Type u} [CommRing B]
    (f : (A : Type u) →+* B) (δ : DividedPowers (Ideal.map f A.ideal)) : Prop :=
  ∀ {n : ℕ} {x : A}, x ∈ A.ideal →
    δ.dpow n (f x) = f (A.dividedPowers.dpow n x)

theorem dpExtension_unique {A : DividedPowerRing.{u}} {B : Type u} [CommRing B]
    (f : (A : Type u) →+* B) (h : DpExtends A f) :
    ∃! δ : DividedPowers (Ideal.map f A.ideal), IsDpExtension A f δ := by
  sorry

/-- Extension exists if the extended ideal is zero, the source ideal is
principal, or the ring map is flat.  Principality is written as generation by
one element, which is the source's hypothesis and avoids adding a parallel
notion of principal ideal. -/
theorem dpExtension_exists
    (A : DividedPowerRing.{u}) {B : Type u} [CommRing B]
    (f : (A : Type u) →+* B) :
    (Ideal.map f A.ideal = ⊥ ∨
      (∃ x : A, A.ideal = Ideal.span ({x} : Set A)) ∨ f.Flat) →
    DpExtends A f := by
  sorry

/-! ## Kernels and quotients -/

/-- The intersection of the kernel with the divided-power ideal is a
sub-divided-power ideal. -/
theorem kernel_inf_isSubDPIdeal {A B : DividedPowerRing.{u}}
    (φ : A ⟶ B) :
    A.dividedPowers.IsSubDPIdeal (RingHom.ker φ.hom ⊓ A.ideal) := by
  sorry

/-- For a quotient by an ideal `𝔞`, preservation of `I ∩ 𝔞`, extension to the
quotient, and preservation on a set of ideal generators are equivalent. -/
theorem quotient_extension_iff
    (A : DividedPowerRing.{u}) (𝔞 : Ideal (A : Type u)) :
    (A.dividedPowers.IsSubDPIdeal (A.ideal ⊓ 𝔞) ↔
      DpExtends A (Ideal.Quotient.mk 𝔞)) ∧
      (DpExtends A (Ideal.Quotient.mk 𝔞) ↔
      ∃ S : Set A, Ideal.span S = A.ideal ⊓ 𝔞 ∧
        ∀ x ∈ S, ∀ n : ℕ, n ≠ 0 →
          A.dividedPowers.dpow n x ∈ A.ideal ⊓ 𝔞) := by
  sorry

/-! ## The smallest sub-divided-power ideal -/

/-- The carrier of Mathlib's smallest sub-divided-power ideal containing `E`.
The hypothesis `hE` is the source's assumption that `E ⊆ I`. -/
noncomputable def generatedSubDPIdeal {A : Type u} [CommRing A] {I : Ideal A}
    (hI : DividedPowers I) (E : Set A) (_hE : E ⊆ I) : Ideal A :=
  by
    classical
    simpa [_hE] using (DividedPowers.SubDPIdeal.span hI E).carrier

theorem generatedSubDPIdeal_isSmallest
    {A : Type u} [CommRing A] {I : Ideal A} (hI : DividedPowers I)
    (E : Set A) (hE : E ⊆ I) :
    IsLeast {J : Ideal A | hI.IsSubDPIdeal J ∧ E ⊆ J}
      (generatedSubDPIdeal hI E hE) := by
  sorry

/-- The smallest sub-divided-power ideal is generated by all positive divided
powers of the elements of `E`. -/
theorem generatedSubDPIdeal_eq_span_dpow
    {A : Type u} [CommRing A] {I : Ideal A} (hI : DividedPowers I)
    (E : Set A) (hE : E ⊆ I) :
    generatedSubDPIdeal hI E hE =
      Ideal.span {y : A | ∃ n : ℕ, ∃ (_ : n ≠ 0), ∃ x : A, ∃ (_ : x ∈ E),
        y = hI.dpow n x} := by
  simpa [generatedSubDPIdeal, hE] using
    (DividedPowers.SubDPIdeal.span_carrier_eq_dpow_span hI hE)

/-! ## Adic completion -/

/-- The ideal defining the `p`-adic completion. -/
def pAdicIdeal (A : Type u) [CommRing A] (p : ℕ) : Ideal A :=
  Ideal.span ({(p : A)} : Set A)

/-- Mathlib's inverse-limit model for the `p`-adic completion of a ring. -/
abbrev pAdicCompletion (A : Type u) [CommRing A] (p : ℕ) : Type u :=
  AdicCompletion (pAdicIdeal A p) A

/-- The `p`-adic completion of the ideal `I`, viewed as an `A`-module. -/
abbrev pAdicIdealCompletion (A : Type u) [CommRing A] (I : Ideal A) (p : ℕ) : Type u :=
  AdicCompletion (pAdicIdeal A p) I

/-- A division-power operation is continuous for the `p`-adic topology,
expressed by the equivalent congruence criterion. -/
def DpowPadicContinuous {A : Type u} [CommRing A] {I : Ideal A}
    (hI : DividedPowers I) (p n : ℕ) : Prop :=
  ∀ e : ℕ, ∃ d : ℕ, ∀ {x y : A}, x ∈ I → y ∈ I →
    x - y ∈ pAdicIdeal A p ^ d →
      hI.dpow n x - hI.dpow n y ∈ pAdicIdeal A p ^ e

/-- The linear equivalence identifying the completed ideal with the kernel of
the completion map to `A/I`. -/
def KernelIsPAdicIdealCompletion {A : Type u} [CommRing A] {I : Ideal A}
    (p : ℕ) (q : pAdicCompletion A p →+* (A ⧸ I)) : Prop :=
  Nonempty (pAdicIdealCompletion A I p ≃ₗ[A] (RingHom.ker q : Type u))

/-- Compatibility of a divided power structure on the completion kernel with
the original positive divided powers.  The restriction to `n ≠ 0` is forced by
the source convention `γ₀(x) = 1`, which is not generally an element of `I`. -/
def DpowExtendsToPAdicCompletion {A : Type u} [CommRing A] {I : Ideal A}
    (hI : DividedPowers I) (p : ℕ)
    (q : pAdicCompletion A p →+* (A ⧸ I))
    (δ : DividedPowers (RingHom.ker q))
    (e : pAdicIdealCompletion A I p ≃ₗ[A] (RingHom.ker q : Type u)) : Prop :=
  ∀ n : ℕ, (hn : n ≠ 0) → ∀ x : I,
    δ.dpow n (e (AdicCompletion.of (pAdicIdeal A p) I x) : pAdicCompletion A p) =
      (e (AdicCompletion.of (pAdicIdeal A p) I
        ⟨hI.dpow n x, hI.dpow_mem hn x.property⟩) : pAdicCompletion A p)

/-- The first three assertions of the completion lemma, bundled for reuse in
the version with the additional localization hypothesis. -/
def PAdicCompletionCoreData {A : Type u} [CommRing A] {I : Ideal A}
    (hI : DividedPowers I) (p : ℕ)
    (q : pAdicCompletion A p →+* (A ⧸ I))
    (δ : DividedPowers (RingHom.ker q))
    (e : pAdicIdealCompletion A I p ≃ₗ[A] (RingHom.ker q : Type u)) : Prop :=
  Function.Surjective q ∧
    (∀ n : ℕ, n ≠ 0 → DpowPadicContinuous hI p n) ∧
    DpowExtendsToPAdicCompletion hI p q δ e

/-- A limit witness for the eventual quotients carrying their induced divided
power structures.  The functor records the transition maps, while the
objectwise equivalences identify its terms with the explicit quotients. -/
def IsPAdicQuotientLimit {A : Type u} [CommRing A] {I : Ideal A}
    (hI : DividedPowers I) (p e₀ : ℕ)
    (hpres : ∀ e : ℕ, e₀ ≤ e →
      hI.IsSubDPIdeal (pAdicIdeal A p ^ e ⊓ I))
    (C : DividedPowerRing.{u}) : Prop :=
  ∃ F : (Set.Ici e₀)ᵒᵖ ⥤ DividedPowerRing.{u},
    ∃ c : Cone F,
      c.pt = C ∧ Nonempty (IsLimit c) ∧
      ∀ e : Set.Ici e₀,
          Nonempty (F.obj (Opposite.op e) ≅
            { toCommRing := CommRingCat.of (A ⧸ pAdicIdeal A p ^ e.1)
              ideal := Ideal.map (Ideal.Quotient.mk (pAdicIdeal A p ^ e.1)) I
              dividedPowers :=
                DividedPowers.Quotient.dividedPowers hI (hpres e.1 e.2) })

/-- The divided-power ring carried by a completion kernel and its extended
divided powers. -/
def completionDividedPowerRing {A : Type u} [CommRing A] {I : Ideal A}
    (p : ℕ) (q : pAdicCompletion A p →+* (A ⧸ I))
    (δ : DividedPowers (RingHom.ker q)) : DividedPowerRing.{u} :=
  { toCommRing := CommRingCat.of (pAdicCompletion A p)
    ideal := RingHom.ker q
    dividedPowers := δ }

/-- If `p` is nilpotent modulo a divided-power ideal, the divided powers extend
to the `p`-adic completion, and the eventual quotient system has that
completion as its limit. -/
theorem extend_to_pAdic_completion
    (A : DividedPowerRing.{u}) (p : ℕ)
    : IsNilpotent
      (Ideal.Quotient.mk A.ideal (p : (A : Type u))) →
    Nat.Prime p →
    ∃ (q : pAdicCompletion (A : Type u) p →+* ((A : Type u) ⧸ A.ideal))
      (δ : DividedPowers (RingHom.ker q))
      (e : pAdicIdealCompletion (A : Type u) A.ideal p ≃ₗ[(A : Type u)]
        (RingHom.ker q : Type u)),
      PAdicCompletionCoreData A.dividedPowers p q δ e := by
  intro hpnil hp
  sorry

/-- In the presence of the source's `\mathbf Z_(p)`-algebra hypothesis, the
eventual powers of `p` are sub-divided-power ideals and the completed
divided-power ring is the limit of the eventual quotient system. -/
theorem extend_to_pAdic_completion_over_ZLocalized
    (A : DividedPowerRing.{u}) (p : ℕ)
    : IsNilpotent
      (Ideal.Quotient.mk A.ideal (p : (A : Type u))) →
    Nat.Prime p →
      Formalization.Books.Dpa.Unit02.IsZLocalizedAtPrime p (A : Type u) →
    ∃ (q : pAdicCompletion (A : Type u) p →+* ((A : Type u) ⧸ A.ideal))
      (δ : DividedPowers (RingHom.ker q))
      (e : pAdicIdealCompletion (A : Type u) A.ideal p ≃ₗ[(A : Type u)]
        (RingHom.ker q : Type u)),
      PAdicCompletionCoreData A.dividedPowers p q δ e ∧
      ∃ e₀ : ℕ,
        (∀ e' : ℕ, e₀ ≤ e' →
          A.dividedPowers.IsSubDPIdeal (pAdicIdeal (A : Type u) p ^ e')) ∧
        ∃ hpres : ∀ e' : ℕ, e₀ ≤ e' →
            A.dividedPowers.IsSubDPIdeal
              (pAdicIdeal (A : Type u) p ^ e' ⊓ A.ideal),
          IsPAdicQuotientLimit A.dividedPowers p e₀ hpres
            (completionDividedPowerRing p q δ) := by
  intro hpnil hp hloc
  sorry

end
end Formalization.Books.Dpa.Unit04
