import Mathlib.AlgebraicGeometry.Sites.Fpqc
import Mathlib.CategoryTheory.Sites.LeftExact
import Mathlib.CategoryTheory.Sites.Limits
import Mathlib.CategoryTheory.Sites.LocallyInjective
import Mathlib.CategoryTheory.Sites.LocallySurjective
import Mathlib.CategoryTheory.Sites.Over
import Mathlib.CategoryTheory.Sites.Subcanonical
import Mathlib.Logic.Relation

/-!
# Groupoids in Algebraic Spaces, Chapter 19: quotient sheaves

The source works with algebraic spaces through their functors of points.  In
this file the corresponding Mathlib interface is a sheaf of types on a site.
The geometric predicate saying that such a sheaf is an algebraic space is
kept as an explicit parameter in the representability definition below:
Mathlib has no separate algebraic-space object in this version.
-/

noncomputable section

universe u v

open CategoryTheory CategoryTheory.Limits Opposite
open AlgebraicGeometry AlgebraicGeometry.Scheme

namespace Formalization.«Books.SpacesGroupoids».Unit19

variable {C : Type u} [Category.{v} C]

/-! ## The site and the functor-of-points interface -/

/-- The sheaf-of-points interface used for an algebraic space on `J`. -/
abbrev AlgebraicSpace (J : GrothendieckTopology C) :=
  Sheaf J (Type (max u v))

/-- The relative fppf site of schemes over a fixed base scheme. -/
abbrev RelativeFppfTopology (S : Scheme.{u}) :
    GrothendieckTopology (Over S) :=
  Scheme.fppfTopology.over S

/-- A pre-relation `R → U ×_B U`, together with the structure map `U → B`.

The two projections are named `source` and `target` so that the convention
`j = (target, source)` agrees with the source text. -/
structure PreRelation (J : GrothendieckTopology C)
    (B U R : AlgebraicSpace J) where
  structureMap : U ⟶ B
  j : R ⟶ pullback structureMap structureMap

namespace PreRelation

variable {J : GrothendieckTopology C}
variable {B U R : AlgebraicSpace J}

/- These field-like abbreviations retain the source spaces as usable
projections even though they are parameters of `PreRelation`, rather than
stored fields. -/
abbrev baseSpace (_P : PreRelation J B U R) : AlgebraicSpace J := B
abbrev carrier (_P : PreRelation J B U R) : AlgebraicSpace J := U
abbrev relation (_P : PreRelation J B U R) : AlgebraicSpace J := R

/-- The source map of a pre-relation. -/
def source (P : PreRelation J B U R) : P.relation ⟶ P.carrier :=
  P.j ≫ pullback.snd P.structureMap P.structureMap

/-- The target map of a pre-relation. -/
def target (P : PreRelation J B U R) : P.relation ⟶ P.carrier :=
  P.j ≫ pullback.fst P.structureMap P.structureMap

/-! ### The objectwise generated equivalence relation -/

/-- The relation on `U(X)` obtained directly from the image of `R(X)`. -/
def rawRelation (P : PreRelation J B U R) (X : Cᵒᵖ) :
    P.carrier.obj.obj X → P.carrier.obj.obj X → Prop :=
  fun a b =>
    ∃ r : P.relation.obj.obj X,
      P.source.hom.app X r = a ∧ P.target.hom.app X r = b

/-- The equivalence relation generated by the image of `R(X)`. -/
def pointSetoid (P : PreRelation J B U R) (X : Cᵒᵖ) :
    Setoid (P.carrier.obj.obj X) :=
  Relation.EqvGen.setoid (P.rawRelation X)

/-- A pre-equivalence relation is a pre-relation whose pointwise image is an
equivalence relation on every test object. -/
def IsPreEquivalenceRelation (P : PreRelation J B U R) : Prop :=
  ∀ X : C, Equivalence (P.rawRelation (op X))

lemma eqvGen_map_of_map {α β : Type*} {r : α → α → Prop} {s : β → β → Prop}
    (f : α → β) (hf : ∀ a b, r a b → s (f a) (f b)) {a b : α}
    (h : Relation.EqvGen r a b) : Relation.EqvGen s (f a) (f b) := by
  induction h with
  | rel a b h => exact Relation.EqvGen.rel _ _ (hf a b h)
  | refl a => exact Relation.EqvGen.refl _
  | symm a b h ih => exact Relation.EqvGen.symm _ _ ih
  | trans a b c h₁ h₂ ih₁ ih₂ => exact Relation.EqvGen.trans _ _ _ ih₁ ih₂

lemma rawRelation_map (P : PreRelation J B U R) {X Y : Cᵒᵖ} (f : X ⟶ Y)
    {a b : P.carrier.obj.obj X} (h : P.rawRelation X a b) :
    P.rawRelation Y (P.carrier.obj.map f a) (P.carrier.obj.map f b) := by
  rcases h with ⟨r, hs, ht⟩
  refine ⟨P.relation.obj.map f r, ?_, ?_⟩
  · rw [NatTrans.naturality_apply, hs]
  · rw [NatTrans.naturality_apply, ht]

/- The objectwise map between the generated quotients. -/
def quotientMap (P : PreRelation J B U R) {X Y : Cᵒᵖ} (f : X ⟶ Y) :
    Quotient (P.pointSetoid X) ⟶ Quotient (P.pointSetoid Y) :=
  TypeCat.ofHom (Quotient.map'
    (s₁ := P.pointSetoid X) (s₂ := P.pointSetoid Y)
    (P.carrier.obj.map f) (fun _a _b h =>
      eqvGen_map_of_map (r := P.rawRelation X) (s := P.rawRelation Y)
        (P.carrier.obj.map f) (fun _a _b h => P.rawRelation_map f h) h))

lemma quotientMap_id (P : PreRelation J B U R) (X : Cᵒᵖ) :
    P.quotientMap (𝟙 X) = 𝟙 _ := by
  ext q
  refine Quotient.inductionOn' q ?_
  intro a
  simp [quotientMap]

lemma quotientMap_comp (P : PreRelation J B U R)
    {X Y Z : Cᵒᵖ} (f : X ⟶ Y) (g : Y ⟶ Z) :
    P.quotientMap (f ≫ g) = P.quotientMap f ≫ P.quotientMap g := by
  sorry

/- The quotient presheaf in the source display, constructed objectwise. -/
def quotientPresheaf (P : PreRelation J B U R) : Cᵒᵖ ⥤ Type (max u v) where
  obj X := Quotient (P.pointSetoid X)
  map f := P.quotientMap f
  map_id := P.quotientMap_id
  map_comp := P.quotientMap_comp

/-- The canonical map from the original presheaf to its quotient presheaf. -/
def quotientProjection (P : PreRelation J B U R) :
    P.carrier.obj ⟶ P.quotientPresheaf := by
  refine
    { app := fun X => TypeCat.ofHom (fun a =>
        Quotient.mk'' (s₁ := P.pointSetoid X) a)
      naturality := ?_ }
  intro X Y f
  ext a
  rfl

/-! ### Maps out of the quotient -/

/-- A map out of `U` equalizes the two maps of a pre-relation. -/
def Equalizes (P : PreRelation J B U R) {M : AlgebraicSpace J}
    (f : P.carrier ⟶ M) : Prop :=
  P.source ≫ f = P.target ≫ f

lemma equalizes_app (P : PreRelation J B U R) {M : AlgebraicSpace J}
    {f : P.carrier ⟶ M} (hf : P.Equalizes f) (X : Cᵒᵖ)
    (r : P.relation.obj.obj X) :
      f.hom.app X (P.source.hom.app X r) =
      f.hom.app X (P.target.hom.app X r) := by
  change P.source ≫ f = P.target ≫ f at hf
  have h : (P.source ≫ f).hom = (P.target ≫ f).hom :=
    congrArg (fun k => k.hom) hf
  exact congrArg (fun k => k r) (congr_app h X)

/-- The structure map to `B` equalizes the relation, because `j` lands in
the fiber product over `B`. -/
lemma structureMap_equalizes (P : PreRelation J B U R) :
    P.Equalizes P.structureMap := by
  sorry

lemma quotientPresheafMapOf_wellDefined (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (f : P.carrier ⟶ M) (hf : P.Equalizes f)
    (X : Cᵒᵖ) {a b : P.carrier.obj.obj X} :
    Relation.EqvGen (P.rawRelation X) a b →
      f.hom.app X a = f.hom.app X b := by
  intro h
  induction h with
  | rel a b h =>
      rcases h with ⟨r, hs, ht⟩
      rw [← hs, ← ht, P.equalizes_app hf X r]
  | refl a => rfl
  | symm a b h ih => exact ih.symm
  | trans a b c h₁ h₂ ih₁ ih₂ => exact ih₁.trans ih₂

def quotientPresheafMapOfApp (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (f : P.carrier ⟶ M) (hf : P.Equalizes f)
    (X : Cᵒᵖ) : P.quotientPresheaf.obj X ⟶ M.obj.obj X :=
  TypeCat.ofHom (fun q : Quotient (P.pointSetoid X) =>
    Quotient.liftOn' q (f.hom.app X)
      (fun a b h => P.quotientPresheafMapOf_wellDefined f hf X
        (show Relation.EqvGen (P.rawRelation X) a b from h)))

lemma quotientPresheafMapOf_naturality (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (f : P.carrier ⟶ M) (hf : P.Equalizes f)
    {X Y : Cᵒᵖ} (g : X ⟶ Y) :
    P.quotientPresheaf.map g ≫ P.quotientPresheafMapOfApp f hf Y =
      P.quotientPresheafMapOfApp f hf X ≫ M.obj.map g := by
  sorry

/- The map out of the quotient presheaf induced by an equalizing map. -/
def quotientPresheafMapOf (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (f : P.carrier ⟶ M) (hf : P.Equalizes f) :
    P.quotientPresheaf ⟶ M.obj where
  app X := P.quotientPresheafMapOfApp f hf X
  naturality := by
    intro X Y g
    exact P.quotientPresheafMapOf_naturality f hf g

/-- The canonical transformation of presheaves from the quotient presheaf to
`B`. -/
def quotientPresheafToBase (P : PreRelation J B U R) :
    P.quotientPresheaf ⟶ P.baseSpace.obj :=
  P.quotientPresheafMapOf P.structureMap P.structureMap_equalizes

/-! ### Sheafification and the coequalizer -/

/-- The quotient sheaf `U/R`, obtained by sheafifying the quotient presheaf. -/
noncomputable def quotientSheaf (P : PreRelation J B U R) : AlgebraicSpace J :=
  (presheafToSheaf J (Type (max u v))).obj P.quotientPresheaf

/-- The quotient map `U → U/R` in the category of sheaves. -/
noncomputable def quotientSheafProjection (P : PreRelation J B U R) :
    P.carrier ⟶ P.quotientSheaf :=
  Sheaf.homEquiv.symm
    (P.quotientProjection ≫ toSheafify J P.quotientPresheaf)

/-- A map from `U/R` to a sheaf `M`, induced by an equalizing map `U → M`. -/
noncomputable def quotientSheafMapOf (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (f : P.carrier ⟶ M) (hf : P.Equalizes f) :
    P.quotientSheaf ⟶ M :=
  Sheaf.homEquiv.symm
    (sheafifyLift J
      (P.quotientPresheafMapOf f hf)
      M.property)

/-- The canonical map `U/R → B`. -/
noncomputable def quotientSheafToBase (P : PreRelation J B U R) :
    P.quotientSheaf ⟶ P.baseSpace :=
  P.quotientSheafMapOf P.structureMap P.structureMap_equalizes

lemma quotientSheafProjection_equalizes (P : PreRelation J B U R) :
    P.source ≫ P.quotientSheafProjection =
      P.target ≫ P.quotientSheafProjection := by
  sorry

/-- The cofork displayed in the source. -/
noncomputable def quotientSheafCofork (P : PreRelation J B U R) :
    Cofork P.source P.target :=
  Cofork.ofπ P.quotientSheafProjection P.quotientSheafProjection_equalizes

/-- The quotient sheaf is the coequalizer of the two relation maps. -/
theorem quotientSheaf_isColimit_exists (P : PreRelation J B U R) :
    Nonempty (IsColimit P.quotientSheafCofork) := by
  sorry

noncomputable def quotientSheaf_isColimit (P : PreRelation J B U R) :
    IsColimit P.quotientSheafCofork :=
  Classical.choice (P.quotientSheaf_isColimit_exists)

/-!
The source also records a variant formed on the site of algebraic spaces over
`B`.  Its comparison with the construction above depends on the later
identification of the two sites; the missing future reference in the source
is recorded in the report for this formalization.  No second quotient object
is introduced here, since it would be definitionally unrelated without that
comparison equivalence.  Thus the variant is explicitly accounted for as a
comparison assertion, while the common quotient construction is represented
by `quotientSheaf` above.
-/

/- The notation `U/G` for a relation induced by a group action is represented
by the following book-facing alias; the input pre-relation is the relation
coming from the action. -/
noncomputable def quotientByGroupAction (P : PreRelation J B U R) : AlgebraicSpace J :=
  P.quotientSheaf

/-! ### Representability -/

/-- A representable sheaf of points for an object of the underlying site. -/
noncomputable def representableSheaf (J : GrothendieckTopology C)
    [J.Subcanonical] (X : C) : AlgebraicSpace J :=
  J.uliftYoneda.{u}.obj X

/-- The source's scheme-representability predicate. -/
def HasRepresentableQuotient (P : PreRelation J B U R) [J.Subcanonical] : Prop :=
  ∃ M : C, Nonempty (P.quotientSheaf ≅ representableSheaf J M)

/-- The geometric predicate “is an algebraic space” is supplied by the
earlier algebraic-space development; this definition applies it to `U/R`. -/
def HasQuotientRepresentableByAlgebraicSpace
    (isAlgebraicSpace : AlgebraicSpace J → Prop)
    (P : PreRelation J B U R) : Prop :=
  isAlgebraicSpace P.quotientSheaf

/-- A structure map to `B` transported across a chosen representing
isomorphism. -/
def structureMapOfRepresentation (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (e : P.quotientSheaf ≅ M) : M ⟶ P.baseSpace :=
  e.inv ≫ P.quotientSheafToBase

/-! ### The criterion for a quotient to be represented -/

/-- The map `R → U ×_M U` induced by an equalizing map `U → M`. -/
def comparisonToPullback (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (f : P.carrier ⟶ M) (hf : P.Equalizes f) :
    P.relation ⟶ pullback f f :=
  pullback.lift P.source P.target hf

/-- The usual criterion for `M` to represent the quotient sheaf. -/
theorem quotient_representation_criterion (P : PreRelation J B U R)
    {M : AlgebraicSpace J} (f : P.carrier ⟶ M) (hf : P.Equalizes f)
    (hU : Presheaf.IsLocallySurjective J f.hom)
    (hR : Presheaf.IsLocallySurjective J
      (P.comparisonToPullback f hf).hom) :
    Nonempty (P.quotientSheaf ≅ M) := by
  sorry

/- The source's geometric example—`U → M` flat, finitely presented, and
surjective, with `R ≅ U ×_M U`—is a specialization of this criterion.  The
site-level interface used here has no separate algebraic-space morphism API,
so the exact example is accounted for by the hypotheses above rather than by
inventing parallel flatness or finite-presentation predicates. -/

/-! ### The pointwise pre-equivalence criterion -/

/-- Two sections of `U` are locally related by the pre-relation. -/
def LocallyRelated (P : PreRelation J B U R) (X : C)
    (a b : P.carrier.obj.obj (op X)) : Prop :=
  ∃ S : Sieve X, S ∈ J X ∧
    ∀ {Y : C} (f : Y ⟶ X), S f →
      ∃ r : P.relation.obj.obj (op Y),
        P.source.hom.app (op Y) r = P.carrier.obj.map f.op a ∧
          P.target.hom.app (op Y) r = P.carrier.obj.map f.op b

/-- For a pre-equivalence relation, equality in the quotient sheaf is exactly
local relatedness on the test object. -/
theorem quotient_section_eq_iff_locallyRelated
    (P : PreRelation J B U R) (hP : P.IsPreEquivalenceRelation)
    (X : C) (a b : P.carrier.obj.obj (op X)) :
    P.quotientSheafProjection.hom.app (op X) a =
        P.quotientSheafProjection.hom.app (op X) b ↔
      P.LocallyRelated X a b := by
  sorry

/-- The comparison from the relation to the fiber product over the quotient. -/
def relationToQuotientPullback (P : PreRelation J B U R) :
    P.relation ⟶ pullback P.quotientSheafProjection P.quotientSheafProjection :=
  pullback.lift P.source P.target P.quotientSheafProjection_equalizes

/-- Equivalently, the relation covers pairs of sections with the same
quotient image. -/
theorem quotient_preEquivalence_comparison_isLocallySurjective
    (P : PreRelation J B U R) (hP : P.IsPreEquivalenceRelation) :
    Presheaf.IsLocallySurjective J (P.relationToQuotientPullback).hom := by
  sorry

/-! ### Restriction -/

variable {U' : AlgebraicSpace J}

/-- The map between the two fiber products induced by `g : U' → U` over `B`. -/
lemma restrictionPairMap_condition (P : PreRelation J B U R)
    (g : U' ⟶ P.carrier) (structureMap' : U' ⟶ P.baseSpace)
    (_hg : structureMap' = g ≫ P.structureMap) :
    (pullback.fst structureMap' structureMap' ≫ g) ≫ P.structureMap =
      (pullback.snd structureMap' structureMap' ≫ g) ≫ P.structureMap := by
  sorry

def restrictionPairMap (P : PreRelation J B U R) (g : U' ⟶ P.carrier)
    (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap) :
    pullback structureMap' structureMap' ⟶
      pullback P.structureMap P.structureMap :=
  pullback.lift
    (pullback.fst structureMap' structureMap' ≫ g)
    (pullback.snd structureMap' structureMap' ≫ g)
    (P.restrictionPairMap_condition g structureMap' hg)

/-- The restriction of a pre-relation to `U'`. -/
def restrict (P : PreRelation J B U R) (g : U' ⟶ P.carrier)
    (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap) :
    PreRelation J P.baseSpace U'
      (pullback (P.restrictionPairMap g structureMap' hg) P.j) where
  structureMap := structureMap'
  j := pullback.fst (P.restrictionPairMap g structureMap' hg) P.j

/-- A morphism of pre-relations, used to transport quotient presheaves. -/
structure Hom
    {B₁ U₁ R₁ B₂ U₂ R₂ : AlgebraicSpace J}
    (P : PreRelation J B₁ U₁ R₁) (Q : PreRelation J B₂ U₂ R₂) where
  onU : P.carrier ⟶ Q.carrier
  onR : P.relation ⟶ Q.relation
  source_naturality : ∀ (X : Cᵒᵖ) (r : P.relation.obj.obj X),
    onU.hom.app X (P.source.hom.app X r) =
      Q.source.hom.app X (onR.hom.app X r)
  target_naturality : ∀ (X : Cᵒᵖ) (r : P.relation.obj.obj X),
    onU.hom.app X (P.target.hom.app X r) =
      Q.target.hom.app X (onR.hom.app X r)

lemma Hom.rawRelation_map (φ : Hom P Q) {X : Cᵒᵖ}
    {a b : P.carrier.obj.obj X} (h : P.rawRelation X a b) :
    Q.rawRelation X (φ.onU.hom.app X a) (φ.onU.hom.app X b) := by
  rcases h with ⟨r, hs, ht⟩
  refine ⟨φ.onR.hom.app X r, ?_, ?_⟩
  · rw [← φ.source_naturality, hs]
  · rw [← φ.target_naturality, ht]

def Hom.quotientPresheafMapApp (φ : Hom P Q) (X : Cᵒᵖ) :
    P.quotientPresheaf.obj X ⟶ Q.quotientPresheaf.obj X :=
  TypeCat.ofHom (Quotient.map'
    (s₁ := P.pointSetoid X) (s₂ := Q.pointSetoid X)
    (φ.onU.hom.app X) (fun _a _b h =>
      eqvGen_map_of_map (r := P.rawRelation X) (s := Q.rawRelation X)
        (φ.onU.hom.app X) (fun _a _b h => φ.rawRelation_map h) h))

lemma Hom.quotientPresheafMap_naturality (φ : Hom P Q)
    {X Y : Cᵒᵖ} (f : X ⟶ Y) :
    P.quotientPresheaf.map f ≫ φ.quotientPresheafMapApp Y =
      φ.quotientPresheafMapApp X ≫ Q.quotientPresheaf.map f := by
  sorry

/- The quotient-presheaf map induced by a morphism of pre-relations. -/
def quotientPresheafMap
    {B₁ U₁ R₁ B₂ U₂ R₂ : AlgebraicSpace J}
    {P : PreRelation J B₁ U₁ R₁} {Q : PreRelation J B₂ U₂ R₂}
    (φ : Hom P Q) :
    P.quotientPresheaf ⟶ Q.quotientPresheaf where
  app X := φ.quotientPresheafMapApp X
  naturality := by
    intro X Y f
    exact φ.quotientPresheafMap_naturality f

/-- The quotient-sheaf map induced by a morphism of pre-relations. -/
noncomputable def quotientSheafMap
    {B₁ U₁ R₁ B₂ U₂ R₂ : AlgebraicSpace J}
    {P : PreRelation J B₁ U₁ R₁} {Q : PreRelation J B₂ U₂ R₂}
    (φ : Hom P Q) :
    P.quotientSheaf ⟶ Q.quotientSheaf :=
  Sheaf.homEquiv.symm (sheafifyMap J (quotientPresheafMap φ))

/-- The existence of the canonical morphism of pre-relations induced by a
restriction. -/
theorem restrictionHom_exists (P : PreRelation J B U R)
    (g : U' ⟶ P.carrier) (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap) :
    Nonempty (Hom (P.restrict g structureMap' hg) P) := by
  sorry

noncomputable def restrictionHom (P : PreRelation J B U R)
    (g : U' ⟶ P.carrier) (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap) :
    Hom (P.restrict g structureMap' hg) P :=
  Classical.choice (P.restrictionHom_exists g structureMap' hg)

/- The canonical map from the quotient of a restriction to the original
quotient. -/
noncomputable def restrictQuotientMap (P : PreRelation J B U R)
    (g : U' ⟶ P.carrier) (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap) :
    (P.restrict g structureMap' hg).quotientSheaf ⟶ P.quotientSheaf :=
  quotientSheafMap (P := P.restrict g structureMap' hg) (Q := P)
    (P.restrictionHom g structureMap' hg)

/-- Restriction preserves the pre-equivalence-relation property. -/
theorem restrict_isPreEquivalenceRelation (P : PreRelation J B U R)
    (g : U' ⟶ P.carrier) (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap)
    (hP : P.IsPreEquivalenceRelation) :
    (P.restrict g structureMap' hg).IsPreEquivalenceRelation := by
  sorry

/-- The restriction quotient map is injective as a map of sheaves. -/
theorem restrictQuotientMap_isLocallyInjective
    (P : PreRelation J B U R) (g : U' ⟶ P.carrier)
    (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap)
    (hP : P.IsPreEquivalenceRelation) :
    Presheaf.IsLocallyInjective J
      (P.restrictQuotientMap g structureMap' hg).hom := by
  sorry

/-- If the restriction map on `U` is locally surjective, the quotient map is
an isomorphism. -/
theorem restrictQuotientMap_isIso_of_isLocallySurjective
    (P : PreRelation J B U R) (g : U' ⟶ P.carrier)
    (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap)
    (hP : P.IsPreEquivalenceRelation)
    (hg_surj : Presheaf.IsLocallySurjective J g.hom) :
    IsIso (P.restrictQuotientMap g structureMap' hg) := by
  sorry

/-! ### Groupoid restriction -/

/-- The orbit map `U' ×_{g,U,t} R → U` used in the groupoid restriction
lemma. -/
def orbitMap (P : PreRelation J B U R) (g : U' ⟶ P.carrier) :
    pullback g P.target ⟶ P.carrier :=
  pullback.snd g P.target ≫ P.source

/-- The groupoid restriction conclusion, expressed through the
pointwise pre-equivalence consequence of a groupoid. -/
theorem groupoid_restrictQuotientMap_isLocallyInjective
    (P : PreRelation J B U R) (g : U' ⟶ P.carrier)
    (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap)
    (hGroupoid : P.IsPreEquivalenceRelation) :
    Presheaf.IsLocallyInjective J
      (P.restrictQuotientMap g structureMap' hg).hom := by
  exact P.restrictQuotientMap_isLocallyInjective g structureMap' hg hGroupoid

/-- If the orbit map is locally surjective, the groupoid restriction quotient
map is an isomorphism. -/
theorem groupoid_restrictQuotientMap_isIso_of_orbitMap
    (P : PreRelation J B U R) (g : U' ⟶ P.carrier)
    (structureMap' : U' ⟶ P.baseSpace)
    (hg : structureMap' = g ≫ P.structureMap)
    (hGroupoid : P.IsPreEquivalenceRelation)
    (horbit : Presheaf.IsLocallySurjective J (P.orbitMap g).hom) :
    IsIso (P.restrictQuotientMap g structureMap' hg) := by
  sorry

/-- The orbit map is locally surjective when `g` is locally surjective and
the source map has the identity section supplied by a groupoid. -/
theorem orbitMap_isLocallySurjective_of_isLocallySurjective
    (P : PreRelation J B U R) (g : U' ⟶ P.carrier)
    (hidentity : ∃ e : P.carrier ⟶ P.relation,
      e ≫ P.source = 𝟙 P.carrier)
    (hg : Presheaf.IsLocallySurjective J g.hom) :
    Presheaf.IsLocallySurjective J (P.orbitMap g).hom := by
  sorry

end PreRelation

/-! ## Relative fppf reading and source-level aliases -/

variable {J : GrothendieckTopology C}
variable {B U R : AlgebraicSpace J}

/-- In the source, “surjective as a map of fppf sheaves” is the local
surjectivity predicate on the corresponding sheaf morphism. -/
abbrev IsFppfSheafSurjective {X Y : AlgebraicSpace J} (f : X ⟶ Y) : Prop :=
  Presheaf.IsLocallySurjective J f.hom

/-- A groupoid's quotient declarations use the same quotient construction;
the groupoid supplies its underlying pre-relation `j = (target, source)`. -/
def GroupoidHasRepresentableQuotient (P : PreRelation J B U R)
    [J.Subcanonical] : Prop :=
  P.HasRepresentableQuotient

end Formalization.«Books.SpacesGroupoids».Unit19
