import Mathlib.AlgebraicGeometry.AffineScheme
import Mathlib.AlgebraicGeometry.Gluing
import Mathlib.AlgebraicGeometry.OpenImmersion
import Mathlib.AlgebraicGeometry.Morphisms.QuasiSeparated
import Mathlib.AlgebraicGeometry.Morphisms.Separated
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.MvPolynomial.Basic
import Mathlib.Topology.QuasiSeparated
import Mathlib.Topology.Sober

/-!
# Examples, Chapter 27: Nonexistence of suitable opens

This file records the two affine counterexamples and the doubled-affine-scheme
construction from the source section.  The geometric counterexample statements
are theorem interfaces for the proving stage; the rings, points, basic opens,
and gluing datum are defined using Mathlib's canonical constructions.
-/

noncomputable section

universe u

open CategoryTheory CategoryTheory.Limits
open TopologicalSpace
open AlgebraicGeometry

namespace Formalization.«Books.Examples».Unit27

/-! ## Common topological interfaces -/

/-- The punctured underlying space of a scheme. -/
abbrev PuncturedSpace (X : Scheme.{u}) (s : X) := {x : X // x ≠ s}

/-- A quasi-compact dense open in a topological space. -/
def HasQuasiCompactDenseOpen (X : Type u) [TopologicalSpace X] : Prop :=
  ∃ V : Set X, IsOpen V ∧ IsCompact V ∧ Dense V

/-- A subset whose open subscheme is separated. -/
def IsSeparatedOpen (X : Scheme.{u}) (W : Set X) : Prop :=
  ∃ hW : IsOpen W, Scheme.IsSeparated
    (Scheme.Opens.toScheme (X := X) (⟨W, hW⟩ : X.Opens))

/-! ## The first affine scheme -/

/-- The polynomial ring in the variables `z_i`. -/
abbrev FirstPolynomialRing (k : Type u) [Field k] := MvPolynomial ℕ k

/-- The pairwise products generating the first relation ideal. -/
def firstRelationGenerators (k : Type u) [Field k] : Set (FirstPolynomialRing k) :=
  Set.range (fun p : {p : ℕ × ℕ // p.1 ≠ p.2} =>
    MvPolynomial.X p.1.1 * MvPolynomial.X p.1.2)

/-- The ideal generated by all pairwise products `z_i z_j`, `i ≠ j`. -/
def firstRelationIdeal (k : Type u) [Field k] : Ideal (FirstPolynomialRing k) :=
  Ideal.span (firstRelationGenerators k)

/-- The quotient ring `A = k[z_1, z_2, …]/(z_i z_j)_{i ≠ j}`. -/
abbrev FirstRing (k : Type u) [Field k] :=
  FirstPolynomialRing k ⧸ firstRelationIdeal k

/-- The quotient map from the first polynomial ring. -/
def firstRingMk (k : Type u) [Field k] :
    FirstPolynomialRing k →+* FirstRing k :=
  Ideal.Quotient.mk (firstRelationIdeal k)

/-- The image of `z_i` in `A`. -/
def firstVariable (k : Type u) [Field k] (i : ℕ) : FirstRing k :=
  firstRingMk k (MvPolynomial.X i)

/-- Evaluation of the first polynomial ring at `z_i = 0`. -/
def firstZeroEvaluation (k : Type u) [Field k] :
    FirstPolynomialRing k →+* k :=
  MvPolynomial.eval₂Hom (RingHom.id k) (fun _ => 0)

private lemma firstZeroEvaluation_mem_ker (k : Type u) [Field k]
    (r : FirstPolynomialRing k) (hr : r ∈ firstRelationIdeal k) :
    firstZeroEvaluation k r = 0 := by
  have hle : firstRelationIdeal k ≤ RingHom.ker (firstZeroEvaluation k) := by
    refine Ideal.span_le.2 ?_
    intro r hr
    rcases Set.mem_range.mp hr with ⟨p, rfl⟩
    simp [firstZeroEvaluation]
  exact hle hr

/-- Evaluation at zero descends to the quotient ring `A`. -/
def firstZeroRingHom (k : Type u) [Field k] : FirstRing k →+* k :=
  Ideal.Quotient.lift (firstRelationIdeal k) (firstZeroEvaluation k)
    (fun r hr => firstZeroEvaluation_mem_ker k r hr)

/-- The ideal `(z_1, z_2, …)` in `A`, represented as the kernel of evaluation at zero. -/
def firstSpecialIdeal (k : Type u) [Field k] : Ideal (FirstRing k) :=
  RingHom.ker (firstZeroRingHom k)

/-- The ideal generated by the first `n` variables in the first quotient ring. -/
def firstFiniteVariableIdeal (k : Type u) [Field k] (n : ℕ) : Ideal (FirstRing k) :=
  Ideal.span (Set.range (fun i : Fin n => firstVariable k i))

/-- The affine scheme `S = Spec(A)`. -/
abbrev FirstScheme (k : Type u) [Field k] : Scheme :=
  Spec (CommRingCat.of (FirstRing k))

/-- The closed point corresponding to `(z_i)`. -/
def firstSpecialPoint (k : Type u) [Field k] : FirstScheme k :=
  ⟨firstSpecialIdeal k, by
    change (RingHom.ker (firstZeroRingHom k)).IsPrime
    exact RingHom.ker_isPrime (firstZeroRingHom k)⟩

/-- The distinguished point is closed. -/
theorem firstSpecialPoint_isClosed (k : Type u) [Field k] :
    IsClosed ({firstSpecialPoint k} : Set (FirstScheme k)) := by
  sorry

/-- The principal open `D(z_i)`. -/
def firstBasicOpen (k : Type u) [Field k] (i : ℕ) : (FirstScheme k).Opens :=
  PrimeSpectrum.basicOpen (R := FirstRing k) (firstVariable k i)

/-- The principal open `D(f)` in the first affine scheme. -/
def firstPrincipalOpen (k : Type u) [Field k] (f : FirstRing k) :
    (FirstScheme k).Opens :=
  PrimeSpectrum.basicOpen (R := FirstRing k) f

/-- Every displayed principal open is affine. -/
theorem firstPrincipalOpen_isAffineOpen (k : Type u) [Field k] (f : FirstRing k) :
    IsAffineOpen (firstPrincipalOpen k f) := by
  sorry

/-- The punctured version of `D(z_i)`. -/
def firstPuncturedBasicOpen (k : Type u) [Field k] (i : ℕ) :
    Set (PuncturedSpace (FirstScheme k) (firstSpecialPoint k)) :=
  {x | (x : FirstScheme k) ∈ (firstBasicOpen k i : Set (FirstScheme k))}

/-- The punctured version of `D(f)`. -/
def firstPuncturedPrincipalOpen (k : Type u) [Field k] (f : FirstRing k) :
    Set (PuncturedSpace (FirstScheme k) (firstSpecialPoint k)) :=
  {x | (x : FirstScheme k) ∈ (firstPrincipalOpen k f : Set (FirstScheme k))}

/-- The complement of the distinguished point is the union of the displayed
basic opens. -/
theorem firstScheme_complement_specialPoint_eq_iUnion_basicOpen (k : Type u) [Field k] :
    (Set.univ : Set (FirstScheme k)) \ {firstSpecialPoint k} =
      ⋃ i : ℕ, (firstBasicOpen k i : Set (FirstScheme k)) := by
  sorry

/-- The punctured spectrum is covered by the opens `D(z_i)`. -/
theorem firstPuncturedSpace_eq_iUnion_basicOpen (k : Type u) [Field k] :
    (Set.univ : Set (PuncturedSpace (FirstScheme k) (firstSpecialPoint k))) =
      ⋃ i : ℕ, firstPuncturedBasicOpen k i := by
  sorry

/-- Each `D(z_i)` is irreducible. -/
theorem firstBasicOpen_isIrreducible (k : Type u) [Field k] (i : ℕ) :
    IsIrreducible (Set.univ : Set (firstBasicOpen k i)) := by
  sorry

/-- Each `D(z_i)` has a generic point. -/
theorem firstBasicOpen_exists_genericPoint (k : Type u) [Field k] (i : ℕ) :
    ∃ η : firstBasicOpen k i, IsGenericPoint η (Set.univ : Set (firstBasicOpen k i)) := by
  sorry

/-- A chosen generic point of `D(z_i)`. -/
noncomputable def firstGenericPoint (k : Type u) [Field k] (i : ℕ) : firstBasicOpen k i :=
  Classical.choose (firstBasicOpen_exists_genericPoint k i)

theorem firstGenericPoint_isGenericPoint (k : Type u) [Field k] (i : ℕ) :
    IsGenericPoint (firstGenericPoint k i) (Set.univ : Set (firstBasicOpen k i)) :=
  Classical.choose_spec (firstBasicOpen_exists_genericPoint k i)

/-- The generic point of `D(z_i)` is different from the distinguished point. -/
theorem firstGenericPoint_ne_specialPoint (k : Type u) [Field k] (i : ℕ) :
    (firstGenericPoint k i : FirstScheme k) ≠ firstSpecialPoint k := by
  sorry

/-- The chosen generic point as a point of the punctured spectrum. -/
noncomputable def firstPuncturedGenericPoint (k : Type u) [Field k] (i : ℕ) :
    PuncturedSpace (FirstScheme k) (firstSpecialPoint k) :=
  ⟨(firstGenericPoint k i : FirstScheme k), firstGenericPoint_ne_specialPoint k i⟩

/-- A dense open in the punctured spectrum contains every displayed generic point. -/
theorem firstPuncturedDenseOpen_contains_genericPoint
    (k : Type u) [Field k]
    (V : Set (PuncturedSpace (FirstScheme k) (firstSpecialPoint k)))
    (hVopen : IsOpen V) (hVdense : Dense V) (i : ℕ) :
    firstPuncturedGenericPoint k i ∈ V := by
  sorry

/-- A principal open contained in the punctured spectrum is defined by an element of `(z_i)`. -/
theorem firstPrincipalOpen_subset_punctured_of_mem_specialIdeal
    (k : Type u) [Field k] (f : FirstRing k) (hf : f ∈ firstSpecialIdeal k) :
    (firstPrincipalOpen k f : Set (FirstScheme k)) ⊆
      {x : FirstScheme k | x ≠ firstSpecialPoint k} := by
  sorry

/-- Every element of `(z_1, z_2, …)` belongs to an ideal generated by finitely
many of the variables. -/
theorem firstSpecialIdeal_mem_firstFiniteVariableIdeal
    (k : Type u) [Field k] (f : FirstRing k) (hf : f ∈ firstSpecialIdeal k) :
    ∃ n : ℕ, f ∈ firstFiniteVariableIdeal k n := by
  sorry

/-- Only finitely many displayed generic points lie in `D(f)` for `f ∈ (z_i)`. -/
theorem firstPrincipalOpen_genericPoints_finite
    (k : Type u) [Field k] (f : FirstRing k) (hf : f ∈ firstSpecialIdeal k) :
    {i : ℕ | firstPuncturedGenericPoint k i ∈ firstPuncturedPrincipalOpen k f}.Finite := by
  sorry

/-- The punctured first spectrum has no quasi-compact dense open. -/
theorem firstPuncturedSpectrum_has_no_quasiCompact_dense_open
    (k : Type u) [Field k] :
    ¬ HasQuasiCompactDenseOpen
      (PuncturedSpace (FirstScheme k) (firstSpecialPoint k)) := by
  sorry

/-! ## The second affine scheme -/

/-- The polynomial variables `x,z_1,z_2,…`, with `x` indexed by `none`. -/
abbrev SecondPolynomialVariable := Option ℕ

abbrev SecondPolynomialRing (k : Type u) [Field k] :=
  MvPolynomial SecondPolynomialVariable k

/-- The products generating the second relation ideal. -/
def secondRelationGenerators (k : Type u) [Field k] : Set (SecondPolynomialRing k) :=
  Set.range (fun i : ℕ =>
      MvPolynomial.X none * MvPolynomial.X (some i)) ∪
    Set.range (fun p : {p : ℕ × ℕ // p.1 ≠ p.2} =>
      MvPolynomial.X (some p.1.1) * MvPolynomial.X (some p.1.2))

/-- The ideal generated by `xz_i` and by `z_i z_j`, `i ≠ j`. -/
def secondRelationIdeal (k : Type u) [Field k] : Ideal (SecondPolynomialRing k) :=
  Ideal.span (secondRelationGenerators k)

/-- The quotient ring `B = k[x,z_1,z_2,…]/J`. -/
abbrev SecondRing (k : Type u) [Field k] :=
  SecondPolynomialRing k ⧸ secondRelationIdeal k

/-- The quotient map from the second polynomial ring. -/
def secondRingMk (k : Type u) [Field k] :
    SecondPolynomialRing k →+* SecondRing k :=
  Ideal.Quotient.mk (secondRelationIdeal k)

/-- The image of `x` in `B`. -/
def secondX (k : Type u) [Field k] : SecondRing k :=
  secondRingMk k (MvPolynomial.X none)

/-- The image of `z_i` in `B`. -/
def secondZ (k : Type u) [Field k] (i : ℕ) : SecondRing k :=
  secondRingMk k (MvPolynomial.X (some i))

/-- Evaluation of the second polynomial ring at `x=z_i=0`. -/
def secondZeroEvaluation (k : Type u) [Field k] :
    SecondPolynomialRing k →+* k :=
  MvPolynomial.eval₂Hom (RingHom.id k) (fun _ => 0)

private lemma secondZeroEvaluation_mem_ker (k : Type u) [Field k]
    (r : SecondPolynomialRing k) (hr : r ∈ secondRelationIdeal k) :
    secondZeroEvaluation k r = 0 := by
  have hle : secondRelationIdeal k ≤ RingHom.ker (secondZeroEvaluation k) := by
    refine Ideal.span_le.2 ?_
    intro r hr
    rcases hr with hr | hr
    · rcases Set.mem_range.mp hr with ⟨i, rfl⟩
      simp [secondZeroEvaluation]
    · rcases Set.mem_range.mp hr with ⟨p, rfl⟩
      simp [secondZeroEvaluation]
  exact hle hr

/-- Evaluation at zero descends to the quotient ring `B`. -/
def secondZeroRingHom (k : Type u) [Field k] : SecondRing k →+* k :=
  Ideal.Quotient.lift (secondRelationIdeal k) (secondZeroEvaluation k)
    (fun r hr => secondZeroEvaluation_mem_ker k r hr)

/-- The ideal `(x,z_i)` in `B`, represented as the kernel of evaluation at zero. -/
def secondSpecialIdeal (k : Type u) [Field k] : Ideal (SecondRing k) :=
  RingHom.ker (secondZeroRingHom k)

/-- The affine scheme `T = Spec(B)`. -/
abbrev SecondScheme (k : Type u) [Field k] : Scheme :=
  Spec (CommRingCat.of (SecondRing k))

/-- The closed point `t` corresponding to `(x,z_i)`. -/
def secondSpecialPoint (k : Type u) [Field k] : SecondScheme k :=
  ⟨secondSpecialIdeal k, by
    change (RingHom.ker (secondZeroRingHom k)).IsPrime
    exact RingHom.ker_isPrime (secondZeroRingHom k)⟩

/-- The principal open `U = D(x)`. -/
def secondOpen (k : Type u) [Field k] : (SecondScheme k).Opens :=
  PrimeSpectrum.basicOpen (R := SecondRing k) (secondX k)

/-- The principal open `D(z_i)` in `T`. -/
def secondZBasicOpen (k : Type u) [Field k] (i : ℕ) : (SecondScheme k).Opens :=
  PrimeSpectrum.basicOpen (R := SecondRing k) (secondZ k i)

/-- The displayed principal open is affine. -/
theorem secondOpen_isAffineOpen (k : Type u) [Field k] :
    IsAffineOpen (secondOpen k) := by
  sorry

/-- The distinguished point `t` is closed. -/
theorem secondSpecialPoint_isClosed (k : Type u) [Field k] :
    IsClosed ({secondSpecialPoint k} : Set (SecondScheme k)) := by
  sorry

/-- The closure of `U` is `U ∪ {t}`. -/
theorem secondOpen_closure (k : Type u) [Field k] :
    closure (secondOpen k : Set (SecondScheme k)) =
      (secondOpen k : Set (SecondScheme k)) ∪ {secondSpecialPoint k} := by
  sorry

/-- The union of the `D(z_i)` contains the complement of `U ∪ {t}`. -/
theorem second_open_complement_subset_iUnion_zBasicOpen (k : Type u) [Field k] :
    ((Set.univ : Set (SecondScheme k)) \ ((secondOpen k : Set (SecondScheme k)) ∪
      {secondSpecialPoint k})) ⊆
      ⋃ i : ℕ, (secondZBasicOpen k i : Set (SecondScheme k)) := by
  sorry

/-- An open disjoint from `U` is contained in the union of the `D(z_i)`. -/
theorem second_open_disjoint_subset_iUnion_zBasicOpen
    (k : Type u) [Field k] (V : Set (SecondScheme k))
    (hVopen : IsOpen V) (hVU : Disjoint V (secondOpen k : Set (SecondScheme k))) :
    V ⊆ ⋃ i : ℕ, (secondZBasicOpen k i : Set (SecondScheme k)) := by
  sorry

/-- The second affine example admits no quasi-compact open disjoint from `U`
whose union with `U` is dense. -/
theorem secondAffineExample_no_quasiCompact_complement_dense_open
    (k : Type u) [Field k] :
    ¬ ∃ V : Set (SecondScheme k),
      IsOpen V ∧ IsCompact V ∧
        Disjoint V (secondOpen k : Set (SecondScheme k)) ∧
        Dense ((secondOpen k : Set (SecondScheme k)) ∪ V) := by
  sorry

/-! ## The affine-scheme lemma -/

/-- The first assertion of the source lemma, with the concrete second example. -/
theorem exists_affine_scheme_affine_open_without_complementing_dense_qc_open
    (k : Type u) [Field k] :
    ∃ (S : Scheme.{u}) (U : S.Opens),
      IsAffine S ∧ IsAffineOpen U ∧
        ¬ ∃ V : Set S,
          IsOpen V ∧ IsCompact V ∧ Disjoint V (U : Set S) ∧ Dense ((U : Set S) ∪ V) := by
  sorry

/-- The second assertion of the source lemma, with the concrete first example. -/
theorem exists_affine_scheme_punctured_without_quasiCompact_dense_open
    (k : Type u) [Field k] :
    ∃ (S : Scheme.{u}) (s : S),
      IsAffine S ∧ IsClosed ({s} : Set S) ∧
        ¬ HasQuasiCompactDenseOpen (PuncturedSpace S s) := by
  sorry

/-! ## Gluing two copies of `T` along `U` -/

private theorem no_three_distinct_ulift_bool
    (i j l : ULift.{u} Bool) (hij : i ≠ j) (hil : i ≠ l) (hjl : j ≠ l) : False := by
  rcases i with ⟨i⟩
  rcases j with ⟨j⟩
  rcases l with ⟨l⟩
  cases i <;> cases j <;> cases l
  all_goals first | exact hij rfl | exact hil rfl | exact hjl rfl

/-- The off-diagonal gluing data for two copies of `T` along `U`.

`GlueData'` is Mathlib's canonical interface for gluing data whose diagonal
overlaps are the copies themselves. -/
noncomputable def doubleGlueData' (k : Type u) [Field k] :
    CategoryTheory.GlueData' Scheme.{u} where
  J := ULift.{u} Bool
  U := fun _ => SecondScheme k
  V := fun _ _ _ => (secondOpen k).toScheme
  f := fun _ _ _ => (secondOpen k).ι
  f_mono := by
    intro i j hij
    infer_instance
  f_hasPullback := by
    intro i j l hij hil
    infer_instance
  t := fun _ _ _ => 𝟙 (secondOpen k).toScheme
  t' := by
    intro i j l hij hil hjl
    exact (no_three_distinct_ulift_bool i j l hij hil hjl).elim
  t_fac := by
    intro i j l hij hil hjl
    exact (no_three_distinct_ulift_bool i j l hij hil hjl).elim
  t_inv := by
    intro i j hij
    simp
  cocycle := by
    intro i j l hij hil hjl
    exact (no_three_distinct_ulift_bool i j l hij hil hjl).elim

/-- The full gluing datum, including the diagonal copies. -/
noncomputable abbrev doubleGlueData (k : Type u) [Field k] : Scheme.GlueData.{u} :=
  { toGlueData := CategoryTheory.GlueData.ofGlueData' (doubleGlueData' k)
    f_open := by
      intro i j
      classical
      change IsOpenImmersion ((doubleGlueData' k).f' i j)
      dsimp [CategoryTheory.GlueData'.f']
      split_ifs with h
      · infer_instance
      · exact @IsOpenImmersion.comp _ _ _
          (eqToHom (dif_neg h)) ((doubleGlueData' k).f i j h)
          (by infer_instance)
          (by
            change IsOpenImmersion ((secondOpen k).ι)
            infer_instance) }

private theorem doubleGlueData_compatibility (k : Type u) [Field k]
    (i j : (doubleGlueData k).J) :
    (doubleGlueData k).diagram.fst ⟨i, j⟩ ≫ 𝟙 (SecondScheme k) =
      (doubleGlueData k).diagram.snd ⟨i, j⟩ ≫ 𝟙 (SecondScheme k) := by
  sorry

/-- The universe-lifted two-element index used by the gluing API. -/
abbrev DoubleIndex : Type u := ULift.{u} Bool

/-- Embed the source-facing Boolean index into the gluing index. -/
def doubleIndex (i : Bool) : DoubleIndex := ULift.up i

/-- The scheme obtained by gluing two copies of `T` along `U`. -/
abbrev doubleScheme (k : Type u) [Field k] : Scheme :=
  (doubleGlueData k).glued

/-- The two open immersions of the copies of `T` into the glued scheme. -/
abbrev doubleComponentEmbedding (k : Type u) [Field k] (i : DoubleIndex) :
    SecondScheme k ⟶ doubleScheme k :=
  (doubleGlueData k).ι i

instance doubleComponentEmbedding_isOpenImmersion
    (k : Type u) [Field k] (i : DoubleIndex) :
    IsOpenImmersion (doubleComponentEmbedding k i) := by
  change IsOpenImmersion ((doubleGlueData k).ι i)
  exact Scheme.GlueData.ι_isOpenImmersion (D := doubleGlueData k) i

/-- The open subscheme underlying the `i`-th copy. -/
def doubleComponentOpen (k : Type u) [Field k] (i : Bool) :
    (doubleScheme k).Opens :=
  (doubleComponentEmbedding k (doubleIndex i)).opensRange

/-- The two component opens cover the glued scheme. -/
theorem doubleComponents_cover (k : Type u) [Field k] :
    (Set.univ : Set (doubleScheme k)) =
      Set.range (fun x : SecondScheme k =>
        doubleComponentEmbedding k (doubleIndex false) x) ∪
      Set.range (fun x : SecondScheme k =>
        doubleComponentEmbedding k (doubleIndex true) x) := by
  sorry

/-- The glued scheme is quasi-compact. -/
theorem doubleScheme_is_quasi_compact (k : Type u) [Field k] :
    IsCompact (Set.univ : Set (doubleScheme k)) := by
  sorry

/-- The glued scheme is quasi-separated. -/
theorem doubleScheme_is_quasi_separated (k : Type u) [Field k] :
    QuasiSeparatedSpace (doubleScheme k) := by
  sorry

/-- The overlap is the displayed copy of `U`. -/
abbrev doubleOverlapScheme (k : Type u) [Field k] := (secondOpen k).toScheme

/-- The overlap diagram is a pullback in the glued scheme. -/
noncomputable def doubleOverlap_is_pullback (k : Type u) [Field k] :
    IsLimit ((doubleGlueData k).vPullbackCone (doubleIndex false) (doubleIndex true)) := by
  exact (doubleGlueData k).vPullbackConeIsLimit (doubleIndex false) (doubleIndex true)

/-- The overlap maps openly into both copies and into the glued scheme. -/
theorem doubleOverlap_isOpenImmersion (k : Type u) [Field k] :
    IsOpenImmersion
      ((doubleGlueData k).f (doubleIndex false) (doubleIndex true) ≫
        (doubleComponentEmbedding k (doubleIndex false))) := by
  change IsOpenImmersion
    ((doubleGlueData k).f (doubleIndex false) (doubleIndex true) ≫
      (doubleGlueData k).ι (doubleIndex false))
  exact @IsOpenImmersion.comp _ _ _
    ((doubleGlueData k).f (doubleIndex false) (doubleIndex true))
    ((doubleGlueData k).ι (doubleIndex false))
    ((doubleGlueData k).f_open _ _)
    (Scheme.GlueData.ι_isOpenImmersion (D := doubleGlueData k) _)

/-- The overlap maps openly into the second copy as well. -/
theorem doubleOverlap_isOpenImmersion_in_second (k : Type u) [Field k] :
    IsOpenImmersion
      ((doubleGlueData k).f (doubleIndex true) (doubleIndex false) ≫
        (doubleComponentEmbedding k (doubleIndex true))) := by
  change IsOpenImmersion
    ((doubleGlueData k).f (doubleIndex true) (doubleIndex false) ≫
      (doubleGlueData k).ι (doubleIndex true))
  exact @IsOpenImmersion.comp _ _ _
    ((doubleGlueData k).f (doubleIndex true) (doubleIndex false))
    ((doubleGlueData k).ι (doubleIndex true))
    ((doubleGlueData k).f_open _ _)
    (Scheme.GlueData.ι_isOpenImmersion (D := doubleGlueData k) _)

/-- The projection from the gluing back to `T`. -/
noncomputable def doubleProjection (k : Type u) [Field k] :
  doubleScheme k ⟶ SecondScheme k :=
  haveI : HasMulticoequalizer (doubleGlueData k).diagram :=
    Scheme.GlueData.instHasMulticoequalizerDiagram (doubleGlueData k)
  Multicoequalizer.desc (doubleGlueData k).diagram _ (fun _ => 𝟙 (SecondScheme k)) (by
    rintro ⟨i, j⟩
    exact doubleGlueData_compatibility k i j)

/-- The projection restricts to the identity on each copy of `T`. -/
theorem doubleProjection_on_component (k : Type u) [Field k] (i : Bool) :
    doubleComponentEmbedding k (doubleIndex i) ≫ doubleProjection k =
      𝟙 (SecondScheme k) := by
  have hD : HasMulticoequalizer (doubleGlueData k).diagram :=
    Scheme.GlueData.instHasMulticoequalizerDiagram (doubleGlueData k)
  exact @Multicoequalizer.π_desc _ _ _ (doubleGlueData k).diagram hD _ _ _ _

theorem doubleProjection_on_component_isIso (k : Type u) [Field k] (i : Bool) :
    IsIso (doubleComponentEmbedding k (doubleIndex i) ≫ doubleProjection k) := by
  rw [doubleProjection_on_component]
  infer_instance

/-- The map induced by the projection on the open `i`-th component. -/
def doubleProjection_restrict (k : Type u) [Field k] (W : (doubleScheme k).Opens) :
    W.toScheme ⟶ SecondScheme k :=
  W.ι ≫ doubleProjection k

/-- A separated open subscheme has separated restriction of the projection. -/
theorem doubleProjection_restrict_isSeparated
    (k : Type u) [Field k] (W : (doubleScheme k).Opens)
    (hW : Scheme.IsSeparated W.toScheme) :
    IsSeparated (doubleProjection_restrict k W) := by
  sorry

theorem doubleComponent_preimage_of_quasiCompact_dense_open
    (k : Type u) [Field k] (W : (doubleScheme k).Opens)
    (hWcompact : IsCompact (W : Set (doubleScheme k)))
    (hWdense : Dense (W : Set (doubleScheme k))) (i : Bool) :
    let f := doubleComponentEmbedding k (doubleIndex i)
    IsOpen (f ⁻¹' (W : Set (doubleScheme k))) ∧
      IsCompact (f ⁻¹' (W : Set (doubleScheme k))) ∧
        Dense (f ⁻¹' (W : Set (doubleScheme k))) := by
  sorry

/-- The two copies of the closed point `t`. -/
def doubleClosedPoint (k : Type u) [Field k] (i : Bool) : doubleScheme k :=
  doubleComponentEmbedding k (doubleIndex i) (secondSpecialPoint k)

/-- Both copied closed points map to `t`. -/
theorem doubleClosedPoint_maps_to_t (k : Type u) [Field k] (i : Bool) :
    doubleProjection k (doubleClosedPoint k i) = secondSpecialPoint k := by
  rw [doubleClosedPoint, ← Scheme.Hom.comp_apply, doubleProjection_on_component]
  rfl

/-- The two copied closed points are distinct. -/
theorem doubleClosedPoint_false_ne_true (k : Type u) [Field k] :
    doubleClosedPoint k false ≠ doubleClosedPoint k true := by
  sorry

/-- The copied points are closed points of the glued scheme. -/
theorem doubleClosedPoint_isClosed (k : Type u) [Field k] (i : Bool) :
    IsClosed ({doubleClosedPoint k i} : Set (doubleScheme k)) := by
  sorry

/- A generic point of the irreducible open `U`, viewed as a point of `U`. -/
theorem secondOpen_exists_genericPoint (k : Type u) [Field k] :
    ∃ η : secondOpen k, IsGenericPoint η (Set.univ : Set (secondOpen k)) := by
  sorry

noncomputable def secondOpenGenericPointInOpen (k : Type u) [Field k] : secondOpen k :=
  Classical.choose (secondOpen_exists_genericPoint k)

theorem secondOpenGenericPointInOpen_isGenericPoint (k : Type u) [Field k] :
    IsGenericPoint (secondOpenGenericPointInOpen k) (Set.univ : Set (secondOpen k)) :=
  Classical.choose_spec (secondOpen_exists_genericPoint k)

/-- The generic point of `U`, viewed as a point of `T`. -/
def secondOpenGenericPoint (k : Type u) [Field k] : SecondScheme k :=
  (secondOpenGenericPointInOpen k : SecondScheme k)

theorem secondOpenGenericPoint_isGenericPoint (k : Type u) [Field k] :
    IsGenericPoint (secondOpenGenericPointInOpen k) (Set.univ : Set (secondOpen k)) :=
  secondOpenGenericPointInOpen_isGenericPoint k

/- The generic point of `U` is unique. -/
theorem secondOpen_genericPoint_unique (k : Type u) [Field k]
    (η : secondOpen k)
    (hη : IsGenericPoint η (Set.univ : Set (secondOpen k))) :
    η = secondOpenGenericPointInOpen k := by
  sorry

/- The generic point of `U` specializes to the closed point `t`. -/
theorem secondOpenGenericPoint_specializes_t (k : Type u) [Field k] :
    secondOpenGenericPoint k ⤳ secondSpecialPoint k := by
  sorry

/- The generic point in the overlap, viewed in the glued scheme. -/
theorem exists_doubleOverlapGenericPoint (k : Type u) [Field k] :
    ∃ η : doubleScheme k,
      η ∈ doubleComponentOpen k false ∧
        η ∈ doubleComponentOpen k true ∧
        doubleProjection k η = secondOpenGenericPoint k ∧
        η ⤳ doubleClosedPoint k false ∧
        η ⤳ doubleClosedPoint k true := by
  sorry

noncomputable def doubleOverlapGenericPoint (k : Type u) [Field k] : doubleScheme k :=
  Classical.choose (exists_doubleOverlapGenericPoint k)

theorem doubleOverlapGenericPoint_spec (k : Type u) [Field k] :
    doubleOverlapGenericPoint k ∈ doubleComponentOpen k false ∧
      doubleOverlapGenericPoint k ∈ doubleComponentOpen k true ∧
      doubleProjection k (doubleOverlapGenericPoint k) = secondOpenGenericPoint k ∧
      doubleOverlapGenericPoint k ⤳ doubleClosedPoint k false ∧
      doubleOverlapGenericPoint k ⤳ doubleClosedPoint k true :=
  Classical.choose_spec (exists_doubleOverlapGenericPoint k)

/- The overlap generic point lies in both component opens and maps to the generic point of `U`. -/
theorem doubleOverlapGenericPoint_mem_components (k : Type u) [Field k] :
    doubleOverlapGenericPoint k ∈ doubleComponentOpen k false ∧
      doubleOverlapGenericPoint k ∈ doubleComponentOpen k true ∧
      doubleProjection k (doubleOverlapGenericPoint k) = secondOpenGenericPoint k := by
  rcases doubleOverlapGenericPoint_spec k with ⟨h₀, h₁, hπ, _, _⟩
  exact ⟨h₀, h₁, hπ⟩

/- The overlap generic point specializes to both copied closed points. -/
theorem doubleOverlapGenericPoint_specializes_closedPoints (k : Type u) [Field k] :
    doubleOverlapGenericPoint k ⤳ doubleClosedPoint k false ∧
      doubleOverlapGenericPoint k ⤳ doubleClosedPoint k true := by
  rcases doubleOverlapGenericPoint_spec k with ⟨_, _, _, h₀, h₁⟩
  exact ⟨h₀, h₁⟩

theorem separated_open_cannot_contain_both_closedPoints
    (k : Type u) [Field k] (W : (doubleScheme k).Opens)
    (hW : Scheme.IsSeparated W.toScheme) :
    ¬ (doubleClosedPoint k false ∈ (W : Set (doubleScheme k)) ∧
      doubleClosedPoint k true ∈ (W : Set (doubleScheme k))) := by
  sorry

/-- The pointed schemes `(T,t)` and `(S,s)` are isomorphic by reindexing the variables. -/
theorem second_first_pointed_scheme_iso_exists (k : Type u) [Field k] :
    ∃ e : SecondScheme k ≅ FirstScheme k,
      e.hom (secondSpecialPoint k) = firstSpecialPoint k := by
  sorry

/-- The doubled affine scheme has no separated quasi-compact dense open. -/
theorem doubleScheme_has_no_separated_quasiCompact_dense_open
    (k : Type u) [Field k] :
    ¬ ∃ W : Set (doubleScheme k),
      IsSeparatedOpen (doubleScheme k) W ∧ IsCompact W ∧ Dense W := by
  sorry

/-- The final existence statement of the source lemma. -/
theorem exists_quasiCompact_quasiSeparated_scheme_without_separated_dense_open
    (k : Type u) [Field k] :
    ∃ X : Scheme.{u},
      IsCompact (Set.univ : Set X) ∧ QuasiSeparatedSpace X ∧
        ¬ ∃ W : Set X,
          IsSeparatedOpen X W ∧ IsCompact W ∧ Dense W := by
  exact ⟨doubleScheme k, doubleScheme_is_quasi_compact k,
    doubleScheme_is_quasi_separated k,
    doubleScheme_has_no_separated_quasiCompact_dense_open k⟩

end Formalization.«Books.Examples».Unit27
