import Formalization.Books.Topology.Unit24.LimitsOfSpectralSpaces
import Mathlib.CategoryTheory.Limits.Shapes.Pullback.IsPullback.Basic
import Mathlib.RingTheory.Spectrum.Prime.Topology
import Mathlib.Topology.Category.TopCat.Basic
import Mathlib.Topology.JacobsonSpace
import Mathlib.Topology.Sets.OpenCover

/-!
# Pro-étale Cohomology, Chapter 2: Some topology

The source uses the standard spectral-space, specialization, profinite-space,
and connected-components constructions.  Those are represented by the
canonical Mathlib and earlier Topology-chapter interfaces.  This file adds the
chapter-specific w-local predicates and records the statements in source
order.
-/

namespace Formalization.Books.Proetale.Unit02

open Set Function CategoryTheory CategoryTheory.Limits
open TopologicalSpace _root_.Topology
open Formalization.Books.Topology.Unit22
open Formalization.Books.Topology.Unit23
open Formalization.Books.Topology.Unit24

universe u v

/-! ## Spectral spaces with disjoint clopen refinements -/

/- The introductory assertion about spectra is already an instance in
   Mathlib; this declaration records it without introducing a parallel
   spectral-space predicate. -/
theorem primeSpectrum_isSpectralSpace (R : Type u) [CommRing R] :
    SpectralSpace (PrimeSpectrum R) := by
  infer_instance

/- A finite disjoint union refinement of an open cover is represented by a
   finite family of clopen subsets, pairwise disjoint and covering `univ`. -/
def HasFiniteClopenRefinement (X : Type u) [TopologicalSpace X] : Prop :=
  ∀ {ι : Type v} (U : ι → Opens X), IsOpenCover U →
    ∃ (n : ℕ) (V : Fin n → Set X),
      (∀ j, IsOpen (V j) ∧ IsClosed (V j)) ∧
        Pairwise (fun i j => Disjoint (V i) (V j)) ∧
          (⋃ j, V j) = (Set.univ : Set X) ∧
            ∀ j, ∃ i, V j ⊆ (U i : Set X)

/- The canonical map from the closed-point subspace to the quotient by
   connected components. -/
def closedPointComponentMap {X : Type u} [TopologicalSpace X] :
    closedPoints X → ConnectedComponents X :=
  fun x => ConnectedComponents.mk (x : X)

/-- The first lemma of the section: a spectral space has the source's finite
disjoint clopen refinement property exactly when every connected component has
one closed point. -/
theorem spectralSplit_iff_closedPointComponentMap_bijective
    {X : Type u} [TopologicalSpace X] [SpectralSpace X] :
    HasFiniteClopenRefinement X ↔
      Function.Bijective (closedPointComponentMap (X := X)) := by
  sorry

/-- The final sufficient condition in the spectral-splitting lemma. -/
theorem spectralSplit_of_closedPoints_closed_of_unique_specialization
    {X : Type u} [TopologicalSpace X] [SpectralSpace X]
    (hclosed : IsClosed (closedPoints X))
    (hspecializes : ∀ x : X, ∃! x₀ : closedPoints X, x ⤳ (x₀ : X)) :
    HasFiniteClopenRefinement X ∧
      Function.Bijective (closedPointComponentMap (X := X)) := by
  sorry

/-! ## The profinite counterexample -/

/- The source's carrier is a copy of `T × {0, 1}`.  A structure keeps the
   generated topology separate from the pre-existing product topology on a
   literal product type, while retaining the two coordinates used by the
   construction. -/
structure NotWLocalExamplePoint (T : Type u) (t : T) where
  base : T
  component : Bool

/-- The subbasis specified in the source example. -/
def notWLocalExampleSubbasis {T : Type u} [TopologicalSpace T] (t : T) :
    Set (Set (NotWLocalExamplePoint T t)) :=
  Set.range (fun U : Opens T =>
      {x | x.base ∈ (U : Set T)}) ∪
    {Set.univ \ ({⟨t, false⟩} : Set (NotWLocalExamplePoint T t))} ∪
      Set.range (fun U : {U : Opens T // t ∉ (U : Set T)} =>
        {x | x.base ∈ (U.1 : Set T) ∧ x.component = true})

/-- The topology generated by the source's subbasis. -/
instance notWLocalExampleTopologicalSpace
    {T : Type u} [TopologicalSpace T] (t : T) :
    TopologicalSpace (NotWLocalExamplePoint T t) :=
  TopologicalSpace.generateFrom (notWLocalExampleSubbasis t)

/-- The subset `T × {0}` in the source example. -/
def notWLocalExampleClosedPointSet {T : Type u} [TopologicalSpace T] (t : T) :
    Set (NotWLocalExamplePoint T t) :=
  {x | x.component = false}

/-- The point `(t, 1)` whose closure witnesses that the closed-point set is
not closed. -/
def notWLocalExampleDistinguishedPoint {T : Type u} [TopologicalSpace T] (t : T) :
    NotWLocalExamplePoint T t :=
  ⟨t, true⟩

/-- The source's profinite example has the two properties in the spectral
splitting lemma, but its closed-point set is not closed. -/
theorem notWLocalExample_properties
    {T : Type u} [TopologicalSpace T] (hT : IsProfiniteSpace T) (t : T)
    (hnotcompact : ¬ IsCompact (({t} : Set T)ᶜ)) :
    closedPoints (NotWLocalExamplePoint T t) =
        notWLocalExampleClosedPointSet t ∧
      notWLocalExampleDistinguishedPoint t ∈
        closure (notWLocalExampleClosedPointSet t) ∧
      HasFiniteClopenRefinement (NotWLocalExamplePoint T t) ∧
      Function.Bijective
        (closedPointComponentMap (X := NotWLocalExamplePoint T t)) ∧
      ¬ IsClosed (closedPoints (NotWLocalExamplePoint T t)) := by
  sorry

/-! ## W-local spaces -/

/-- A spectral space is w-local when its closed points form a closed subset
and every point specializes to exactly one closed point. -/
def IsWLocalSpace (X : Type u) [TopologicalSpace X] : Prop :=
  SpectralSpace X ∧
    IsClosed (closedPoints X) ∧
      ∀ x : X, ∃! x₀ : closedPoints X, x ⤳ (x₀ : X)

/-- A map between w-local spaces is w-local when it is spectral and maps
closed points to closed points. -/
def IsWLocalMap {X : Type u} {Y : Type v}
    [TopologicalSpace X] [TopologicalSpace Y] (f : X → Y) : Prop :=
  IsWLocalSpace X ∧ IsWLocalSpace Y ∧
    IsSpectralMap f ∧ MapsTo f (closedPoints X) (closedPoints Y)

/-- The example is not w-local once the w-local definition has been made
explicit: its closed-point set is not closed. -/
theorem notWLocalExample_not_isWLocalSpace
    {T : Type u} [TopologicalSpace T] (hT : IsProfiniteSpace T) (t : T)
    (hnotcompact : ¬ IsCompact (({t} : Set T)ᶜ)) :
    ¬ IsWLocalSpace (NotWLocalExamplePoint T t) := by
  sorry

/-- The assertions immediately following the definition of w-locality. -/
theorem isWLocalSpace_properties
    {X : Type u} [TopologicalSpace X] (hX : IsWLocalSpace X) :
    IsHomeomorph (closedPointComponentMap (X := X)) ∧
      IsProfiniteSpace (closedPoints X) ∧
        IsProfiniteSpace (ConnectedComponents X) ∧
          ∀ x₀ : closedPoints X,
            connectedComponent (x₀ : X) =
              pointsSpecializingTo ({(x₀ : X)} : Set X) := by
  sorry

/-- A closed subspace of a w-local spectral space is w-local. -/
theorem isWLocalSpace_subtype_of_isClosed
    {X : Type u} [TopologicalSpace X] (hX : IsWLocalSpace X)
    {Y : Set X} (hY : IsClosed Y) :
    IsWLocalSpace Y := by
  sorry

/-! ## The cartesian base-change lemma -/

/- The connected-components quotient map, bundled as a morphism in `TopCat`,
is the bottom map in the source diagram. -/
def connectedComponentsMapHom {X : Type u} [TopologicalSpace X] :
    TopCat.of X ⟶ TopCat.of (ConnectedComponents X) :=
  TopCat.ofHom ⟨ConnectedComponents.mk, ConnectedComponents.continuous_coe⟩

/-- A cartesian square over the connected-components quotient of `X`. -/
structure CartesianComponentSquare
    (X : Type u) [TopologicalSpace X] where
  Y : TopCat.{u}
  T : TopCat.{u}
  toT : Y ⟶ T
  toX : Y ⟶ TopCat.of X
  toPi0 : T ⟶ TopCat.of (ConnectedComponents X)
  isPullback :
    IsPullback toT toX toPi0 (connectedComponentsMapHom (X := X))

/-- The last lemma of the section: the cartesian pullback over a profinite
space has the asserted spectral and w-local properties.  The identification
`T = π₀(Y)` is represented by a homeomorphism, since a pullback object is only
canonically determined up to homeomorphism in `TopCat`. -/
theorem cartesianComponentSquare_silly
    {X : Type u} [TopologicalSpace X] [SpectralSpace X]
    (sq : CartesianComponentSquare X)
    (hT : IsProfiniteSpace (sq.T : Type u)) :
    SpectralSpace (sq.Y : Type u) ∧
      Nonempty ((sq.T : Type u) ≃ₜ ConnectedComponents (sq.Y : Type u)) ∧
        (IsWLocalSpace X →
          IsWLocalSpace (sq.Y : Type u) ∧
            IsWLocalMap sq.toX.hom ∧
              closedPoints (sq.Y : Type u) =
                sq.toX.hom ⁻¹' closedPoints X) := by
  sorry

end Formalization.Books.Proetale.Unit02
