import Formalization.Books.Algebra.Unit105.CatenaryRings
import Formalization.Books.Algebra.Unit112.HomomorphismsAndDimension
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.LocalRing.ResidueField.Ideal
import Mathlib.RingTheory.LocalRing.ResidueField.Polynomial
import Mathlib.SetTheory.Cardinal.ENat

/-!
# Commutative Algebra, Chapter 113: The dimension formula

The source's heights use Mathlib's `Ideal.height`.  Since Mathlib's
transcendence degree is cardinal-valued while heights are `ℕ∞`-valued, the
dimension formula below uses the canonical `Cardinal.toENat` projection; under
the finite-type hypotheses this records the same finite transcendence degrees.
The residue-field and fraction-field maps are the canonical maps supplied by
Mathlib, packaged only where the source-facing hypotheses need them.
-/

namespace Formalization.Books.Algebra.Unit113

universe u v

noncomputable section

/-! ## Canonical maps used by the source statements -/

/- The source's residue-field extension `κ(p) ⟶ κ(q)` is Mathlib's canonical
   residue-field map, with the displayed equality of primes used to put the
   source prime `p` at the left-hand side. -/
noncomputable def residueFieldMapAt
    {R S : Type*} [CommRing R] [CommRing S]
    (f : R →+* S) (p : PrimeSpectrum R) (q : PrimeSpectrum S)
    (hq : PrimeSpectrum.comap f q = p) :
    p.asIdeal.ResidueField →+* q.asIdeal.ResidueField :=
  Ideal.ResidueField.map p.asIdeal q.asIdeal f (by
    simpa [PrimeSpectrum.comap_asIdeal] using
      (congrArg PrimeSpectrum.asIdeal hq).symm)

/- The source's induced extension of fraction fields is represented by the
   canonical localization map between the fraction rings of the two domains. -/
noncomputable def fractionFieldMap
    {A B : Type*} [CommRing A] [CommRing B] [IsDomain A] [IsDomain B]
    (f : A →+* B) (hinj : Function.Injective f) :
    FractionRing A →+* FractionRing B :=
  IsFractionRing.map (j := f) hinj

/-! ## The dimension formula -/

/-- The dimension formula for a finite-type inclusion of Noetherian domains.

The displayed source inequality is expressed with Mathlib's `ℕ∞` heights and
the canonical `Cardinal.toENat` conversion of its cardinal-valued
transcendence degrees. -/
theorem dimension_formula
    {R S : Type*} [CommRing R] [CommRing S]
    [IsNoetherianRing R] [IsDomain R] [IsDomain S]
    (f : R →+* S) (hfinite : RingHom.FiniteType f)
    (hinj : Function.Injective f)
    (p : PrimeSpectrum R) (q : PrimeSpectrum S)
    (hq : PrimeSpectrum.comap f q = p) :
    letI : Algebra R S := f.toAlgebra
    letI : Algebra p.asIdeal.ResidueField q.asIdeal.ResidueField :=
      (residueFieldMapAt f p q hq).toAlgebra
    q.asIdeal.height ≤
        p.asIdeal.height + Cardinal.toENat (Algebra.trdeg R S) -
          Cardinal.toENat
            (Algebra.trdeg p.asIdeal.ResidueField q.asIdeal.ResidueField) ∧
      (Formalization.Books.Algebra.Unit105.IsUniversallyCatenary R →
        q.asIdeal.height =
          p.asIdeal.height + Cardinal.toENat (Algebra.trdeg R S) -
            Cardinal.toENat
              (Algebra.trdeg p.asIdeal.ResidueField q.asIdeal.ResidueField)) := by
  /-
  Proof roadmap (the interface above has been checked; in particular the two
  finite-type transcendence degrees are finite, so `Cardinal.toENat` is the
  intended `ℕ∞` value rather than an accidental loss of information).

  1. Install `f.toAlgebra`, the `Algebra.FiniteType R S` proof `hfinite`, and
     `Algebra.FiniteType.isNoetherianRing R S`.  First prove two local order
     helpers for quotient primes; these are the missing height constructions,
     not declarations currently supplied by Mathlib:

       * if `n ≤ Q` are prime ideals of a Noetherian domain and `n ≠ ⊥`, then
         `(Q.map (Ideal.Quotient.mk n)).height + 1 ≤ Q.height`;
       * if moreover `n.height = 1` and
         `Formalization.Books.Algebra.Unit105.IsCatenaryRing T`, replace that
         inequality by equality.

     Build the first helper by taking an arbitrary `LTSeries` below the image
     of `Q`, lifting it with
     `PrimeSpectrum.comap (Ideal.Quotient.mk n)` and
     `RingHom.strictMono_comap_of_surjective Ideal.Quotient.mk_surjective`,
     and prepending the strict prime step `⊥ < n`.  For the equality helper,
     use `Ideal.exists_ltSeries_length_eq_height` and compare the resulting
     maximal chains with
     `Formalization.Books.Algebra.Unit105.IsPrimeChainBetween` and
     `Formalization.Books.Topology.Unit11.IsMaximalChainBetween`, which are
     exactly the predicates quantified by
     `Formalization.Books.Algebra.Unit105.IsCatenaryRing` in
     `Formalization/Books/Algebra/Unit105/CatenaryRings.lean`.

  2. Prove the one-generator step for an injective finite-type map whose target
     is generated by `x`.  Put
     `e : R[X] →ₐ[R] S := Polynomial.aeval x`; surjectivity is
     `Algebra.adjoin_singleton_eq_range_aeval` plus `AlgHom.range_eq_top` from
     `Mathlib/RingTheory/Adjoin/Polynomial/Basic.lean`.  For
     `Q := q.asIdeal.comap e.toRingHom`, use the polynomial fibre over `p`:
     `Polynomial.fiberEquivQuotient` from
     `Mathlib/RingTheory/LocalRing/ResidueField/Polynomial.lean`, together with
     `Ideal.height_eq_height_add_of_liesOver_of_hasGoingDown` from
     `Mathlib/RingTheory/Ideal/KrullsHeightTheorem.lean` (polynomial algebras
     are flat, hence have going down).  In the fibre `κ(p)[X]` there are only
     two cases.  The zero prime has height zero and residue field
     transcendence degree one; use `Polynomial.residueFieldMapCAlgEquiv` and
     `Polynomial.trdeg_of_isDomain`, then `IsLocalization.isAlgebraic` and
     `trdeg_add_eq` to pass from the polynomial ring to its fraction field.  A
     nonzero prime is maximal in the PID and has height one by
     `Ideal.IsPrime.to_maximal_ideal` and
     `IsPrincipalIdealRing.height_eq_one_of_isMaximal`.  Choose its principal
     generator, replace it by the monic associate
     `Polynomial.monic_mul_leadingCoeff_inv`, and use
     `Polynomial.Monic.finite_quotient` plus
     `Algebra.IsAlgebraic.of_finite`; the residue-field localization remains
     algebraic by `IsLocalization.isAlgebraic`, so its transcendence degree is
     zero by `trdeg_eq_zero`.

     If `e` is injective, this proves the displayed formula with equality.  If
     it is not injective, set `n := RingHom.ker e.toRingHom`; then `n` is a
     nonzero prime contracting to `⊥`, and `Algebra.trdeg R S = 0` by
     `transcendental_iff_injective` and `trdeg_eq_zero`.  Show
     `n.height = 1` by localizing constants:
     `Polynomial.isLocalization (nonZeroDivisors R) (FractionRing R)` and
     `IsLocalization.height_map_of_disjoint` reduce to the nonzero prime
     `n.map (algebraMap R[X] (FractionRing R)[X])` of the PID
     `(FractionRing R)[X]`; use `Ideal.IsPrime.to_maximal_ideal` and
     `IsPrincipalIdealRing.height_eq_one_of_isMaximal`.  Apply the quotient
     helper from step 1 to compare `q.height` with `Q.height`, transporting the
     quotient prime through `Ideal.quotientKerAlgEquivOfSurjective e_surj` and
     `RingEquiv.height_map`; in the universally catenary branch use
     `hUC.2 (Polynomial R)` to supply catenarity and obtain equality.

  3. Extract `s : Finset S` with `Algebra.adjoin R (s : Set S) = ⊤` from
     `Algebra.FiniteType.out`, and induct on `s`.  At an insertion step take
     `T := Algebra.adjoin R (t : Set S)` and
     `U := Algebra.adjoin R ((insert x t : Finset S) : Set S)`, contract `q`
     successively to `U` and `T`, apply the induction hypothesis to `R → T`
     and step 2 to `T → U`, then transport from `U = ⊤` back to `S`.
     The empty case is the equivalence
     `Algebra.botEquivOfInjective hinj : R ≃ₐ[R] (⊥ : Subalgebra R S)`;
     the final transport uses `Algebra.topEquiv` together with
     `Subalgebra.equivOfEq` for the generator equality.
     Give `R`, `T`, and `U` their inclusion algebras, the `FaithfulSMul`
     instances obtained from injectivity of the inclusions, and an explicit
     `IsScalarTower R T U`.  Do the same for
     `p.ResidueField → κ(q|T) → κ(q|U)` using
     `residueFieldMapAt`; the equality of the two composites follows by
     `Ideal.ResidueField.ringHom_ext` (or ext followed by simp on the canonical
     maps).

     Now rewrite both transcendence-degree sums with
     `trdeg_add_eq R T U` and its residue-field instance from
     `Mathlib/RingTheory/AlgebraicIndependent/TranscendenceBasis.lean`.
     Here `T` and `U` are subtypes of `S` and therefore have the same universe,
     exactly as required by the non-lifted theorem; use
     `lift_trdeg_add_eq` only if a residue-field transport introduces a
     different universe.  `trdeg_lt_aleph0` proves finiteness for the
     finite-type ring extensions.  Do not try to synthesize
     `Algebra.FiniteType p.ResidueField q.ResidueField`: at a generic point the
     residue field is only essentially finite type as an algebra.  Its
     transcendence degree is finite here because each one-generator residue
     step in step 2 is exactly zero or one and the residue-field
     `trdeg_add_eq` adds those steps.  Convert all these finitely valued
     `ℕ∞` terms to naturals (and the prime heights using their
     `Ideal.FiniteHeight` instances) before the final truncated-subtraction
     arithmetic, so that the two step inequalities/equalities combine without
     an invalid distributivity rewrite.

  4. For the equality induction, an intermediate `T` is again universally
     catenary: apply
     `Formalization.Books.Algebra.Unit105.isUniversallyCatenary_of_essFiniteType R T hUC
       (Algebra.EssFiniteType.of_finiteType (R := R) (S := T))`.
     Assemble the inequality unconditionally and the equality under `hUC`,
     yielding the required conjunction.
  -/
  sorry

/-! ## Finite maps in codimension one -/

/-- A generically finite finite-type map has finitely many height-one primes
over a height-one prime, and every prime in that fibre has height one. -/
theorem finite_in_codimension_one
    {A B : Type*} [CommRing A] [CommRing B]
    [IsNoetherianRing A] [IsDomain A] [IsDomain B]
    (f : A →+* B) (hinj : Function.Injective f)
    (hfraction :
      letI : Algebra (FractionRing A) (FractionRing B) :=
        (fractionFieldMap f hinj).toAlgebra
      FiniteDimensional (FractionRing A) (FractionRing B))
    (hfinite : RingHom.FiniteType f)
    (p : PrimeSpectrum A) (hp : p.asIdeal.height = 1) :
    Set.Finite {q : PrimeSpectrum B | PrimeSpectrum.comap f q = p} ∧
      ∀ q : PrimeSpectrum B, PrimeSpectrum.comap f q = p →
        q.asIdeal.height = 1 := by
  /-
  Proof roadmap (no global `Algebra.QuasiFinite A B` instance is needed, and
  trying to use `Algebra.QuasiFinite.finite_comap_preimage_singleton` is a dead
  end: the hypotheses only control this codimension-one fibre, not every
  fibre).

  1. Install `f.toAlgebra`, `hfinite : Algebra.FiniteType A B`, and the target
     Noetherian instance `Algebra.FiniteType.isNoetherianRing A B`; install
     `FaithfulSMul A B` with
     `(faithfulSMul_iff_algebraMap_injective A B).mpr hinj`.  First show
     `Algebra.trdeg A B = 0`.  On `FractionRing B` use the `A`-algebra whose map
     is `(algebraMap B (FractionRing B)).comp f`; use
     `(fractionFieldMap f hinj).toAlgebra` for
     `FractionRing A → FractionRing B`.  Create both scalar towers explicitly
     with `IsScalarTower.of_algebraMap_eq'`; the required compatibility for
     `fractionFieldMap` is `IsLocalization.map`/`IsLocalization.map_mk'` and is
     discharged by ext and simp.  Install the remaining `FaithfulSMul`
     instances from the injective localization maps and from injectivity of
     the ring homomorphism between the two fraction fields.

     The hypothesis `hfraction` gives
     `Algebra.IsAlgebraic (FractionRing A) (FractionRing B)` via
     `Algebra.IsAlgebraic.of_finite`, hence fraction-field transcendence degree
     zero by `trdeg_eq_zero`.  Also
     `IsLocalization.isAlgebraic` gives zero transcendence degree from `A` to
     `FractionRing A` and from `B` to `FractionRing B`.  Apply
     `lift_trdeg_add_eq A (FractionRing A) (FractionRing B)` (the two
     fraction fields may live in different universes) and then
     `trdeg_add_eq A B (FractionRing B)` (here `B` and its fraction
     ring have the same universe).  Simplifying the zero terms and cancelling
     `Cardinal.lift` proves the claim.

  2. For any `q` over `p`, apply `dimension_formula f hfinite hinj p q hq` and
     rewrite with `hp` and step 1.  Since truncated subtraction is bounded by
     its left operand, obtain `q.asIdeal.height ≤ 1`.  On the other hand
     `p.asIdeal ≠ ⊥` by `Ideal.ne_bot_of_height_eq_one`; injectivity and
     the contraction equality imply `q.asIdeal ≠ ⊥`.  Thus
     `Ideal.height_eq_zero_iff_eq_bot` makes the height nonzero, and
     `le_antisymm` with `(Order.one_le_iff_ne_zero).mpr` gives height exactly
     one.  This is the second conjunct.

  3. For finiteness choose `a ∈ p.asIdeal`, `a ≠ 0`, using the same
     non-bottom fact, and put `I := Ideal.span {f a}`.  If `f a` is a unit then
     the fibre is empty, because every prime over `p` would contain that unit.
     Otherwise `f a` is a non-zero-divisor (domain plus `hinj`), so
     `Ideal.height_span_singleton_eq_one_of_mem_nonZeroDivisors` from
     `Mathlib/RingTheory/Ideal/KrullsHeightTheorem.lean` gives `I.height = 1`.
     Every fibre prime contains `I` and has height one by step 2; consequently
     `Ideal.mem_minimalPrimes_of_height_le` places it in `I.minimalPrimes`.

  4. `Ideal.finite_minimalPrimes_of_isNoetherianRing B I` from
     `Mathlib/RingTheory/Ideal/MinimalPrime/Noetherian.lean` makes that target
     set finite.  Apply `Set.Finite.of_finite_image` to
     `fun q : PrimeSpectrum B => q.asIdeal`; its injectivity is
     `PrimeSpectrum.ext`.  The image of the fibre is a subset of
     `I.minimalPrimes` by step 3, which proves the first conjunct.  Pair it with
     the height statement from step 2.
  -/
  let : Algebra A B := f.toAlgebra
  let : Algebra.FiniteType A B := hfinite
  let : IsNoetherianRing B := Algebra.FiniteType.isNoetherianRing A B

  have htrdeg : Algebra.trdeg A B = 0 := by
    let : Algebra (FractionRing A) (FractionRing B) :=
      (fractionFieldMap f hinj).toAlgebra
    let : FiniteDimensional (FractionRing A) (FractionRing B) := hfraction
    let : Algebra A (FractionRing B) :=
      ((algebraMap B (FractionRing B)).comp f).toAlgebra
    let : SMul A (FractionRing B) := Algebra.toSMul
    let : SMul B (FractionRing B) := Algebra.toSMul
    let : SMul (FractionRing A) (FractionRing B) := Algebra.toSMul
    let : IsScalarTower A B (FractionRing B) :=
      IsScalarTower.of_algebraMap_eq' rfl
    let : IsScalarTower A (FractionRing A) (FractionRing B) :=
      IsScalarTower.of_algebraMap_eq' (by
        ext x
        change algebraMap B (FractionRing B) (f x) =
          IsLocalization.map (M := nonZeroDivisors A) (T := nonZeroDivisors B)
            (FractionRing B) f (nonZeroDivisors_le_comap_nonZeroDivisors_of_injective f hinj)
            (algebraMap A (FractionRing A) x)
        rw [IsLocalization.map_eq])
    let : Algebra.IsAlgebraic A (FractionRing A) :=
      IsLocalization.isAlgebraic (FractionRing A) (nonZeroDivisors A)
    let : Algebra.IsAlgebraic (FractionRing A) (FractionRing B) :=
      Algebra.IsAlgebraic.of_finite (FractionRing A) (FractionRing B)
    let : Algebra.IsAlgebraic A (FractionRing B) :=
      Algebra.IsAlgebraic.trans A (FractionRing A) (FractionRing B)
    let : Algebra.IsAlgebraic A B :=
      Algebra.IsAlgebraic.of_injective
        (IsScalarTower.toAlgHom A B (FractionRing B))
        (FaithfulSMul.algebraMap_injective B (FractionRing B))
    exact trdeg_eq_zero

  have hpne : p.asIdeal ≠ (⊥ : Ideal A) :=
    Ideal.ne_bot_of_height_eq_one hp

  have hheight : ∀ q : PrimeSpectrum B,
      PrimeSpectrum.comap f q = p → q.asIdeal.height = 1 := by
    intro q hq
    let : Algebra p.asIdeal.ResidueField q.asIdeal.ResidueField :=
      (residueFieldMapAt f p q hq).toAlgebra
    have hdim := (dimension_formula f hfinite hinj p q hq).1
    have hdim' : q.asIdeal.height ≤ 1 := by
      have hdim'' : q.asIdeal.height ≤ 1 -
          Cardinal.toENat (Algebra.trdeg p.asIdeal.ResidueField q.asIdeal.ResidueField) := by
        simpa [htrdeg, hp] using hdim
      exact hdim''.trans tsub_le_self
    have hqne : q.asIdeal ≠ (⊥ : Ideal B) := by
      intro hqbot
      have hpc : q.asIdeal.comap f = p.asIdeal := by
        simpa [PrimeSpectrum.comap_asIdeal] using
          congrArg PrimeSpectrum.asIdeal hq
      apply hpne
      rw [← hpc, hqbot, Ideal.comap_bot_of_injective f hinj]
    apply le_antisymm hdim'
    exact (Order.one_le_iff_ne_zero.mpr (by
      simpa [Ideal.height_eq_zero_iff_eq_bot] using hqne))

  obtain ⟨a, ha, ha0⟩ :=
    Submodule.exists_mem_ne_zero_of_ne_bot hpne
  let I : Ideal B := Ideal.span {f a}
  have hfa0 : f a ≠ 0 := by
    intro h
    apply ha0
    apply hinj
    simpa using h
  have hfa_mem (q : PrimeSpectrum B) (hq : PrimeSpectrum.comap f q = p) :
      f a ∈ q.asIdeal := by
    have hpc : q.asIdeal.comap f = p.asIdeal := by
      simpa [PrimeSpectrum.comap_asIdeal] using
        congrArg PrimeSpectrum.asIdeal hq
    exact Ideal.mem_comap.mp (hpc.symm ▸ ha)
  by_cases hunit : IsUnit (f a)
  · have hfinite_fibre : {q : PrimeSpectrum B | PrimeSpectrum.comap f q = p} = ∅ := by
      ext q
      constructor
      · intro hq
        have hIq : I ≤ q.asIdeal := by
          apply Ideal.span_le.2
          simpa [I] using hfa_mem q hq
        have hItop : I = ⊤ := by
          simpa [I] using (Ideal.span_singleton_eq_top.mpr hunit)
        exact q.isPrime.ne_top (top_unique (hItop ▸ hIq))
      · simp
    exact ⟨hfinite_fibre ▸ Set.finite_empty, hheight⟩
  · have hIheight : I.height = 1 := by
      dsimp [I]
      exact Ideal.height_span_singleton_eq_one_of_mem_nonZeroDivisors
        (mem_nonZeroDivisors_of_ne_zero hfa0) hunit
    have hminimal (q : PrimeSpectrum B)
        (hq : PrimeSpectrum.comap f q = p) : q.asIdeal ∈ I.minimalPrimes := by
      let := q.isPrime
      apply Ideal.mem_minimalPrimes_of_height_le
        (Ideal.span_le.2 (by simpa [I] using hfa_mem q hq))
      rw [hheight q hq, hIheight]
    have himage : (fun q : PrimeSpectrum B => q.asIdeal) ''
        {q : PrimeSpectrum B | PrimeSpectrum.comap f q = p} ⊆ I.minimalPrimes := by
      rintro _ ⟨q, hq, rfl⟩
      exact hminimal q hq
    have himage_finite : ((fun q : PrimeSpectrum B => q.asIdeal) ''
        {q : PrimeSpectrum B | PrimeSpectrum.comap f q = p}).Finite :=
      I.finite_minimalPrimes_of_isNoetherianRing.subset himage
    refine ⟨Set.Finite.of_finite_image himage_finite ?_, hheight⟩
    intro q hq q' hq' heq
    exact PrimeSpectrum.ext heq

end

end Formalization.Books.Algebra.Unit113
