import Formalization.Books.Modules.Unit05.Supports
import Mathlib.Algebra.Category.ModuleCat.Sheaf.Generators
import Mathlib.Algebra.Homology.ShortComplex.ShortExact

/-!
# Sheaves of Modules, Chapter 9: Modules of finite type

This file formalizes the source section `Modules of finite type` (the
definition and Lemmas `pullback-finite-type`, `extension-finite-type`,
`finite-type-surjective-on-stalk`, `finite-type-stalk-zero`,
`support-finite-type-closed`, `finite-type-quasi-compact-colimit`, and
`set-isomorphism-classes-finite-type-modules`).  The finite-type condition is
Mathlib's canonical `SheafOfModules.IsFiniteType` class, whose local-generator
data is exactly the source definition.  The statements below use the project
interfaces for ringed-space pullback, open restriction, stalks, support,
colimits, and short exact complexes.  The source's final equality in the
injective-colimit clause is represented by the canonical categorical
isomorphism, since colimits are not definitionally fixed representatives.
-/

namespace Formalization.Books.Modules.Unit09

open CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace
open Formalization.Books.Modules.Unit03
open Formalization.Books.Modules.Unit05
open Formalization.Books.Sheaves.Unit10
open Formalization.Books.Sheaves.Unit22

universe v

noncomputable section

/-! ## Definition `definition-finite-type` -/

/-- A sheaf of modules is of finite type when it is locally generated by
finitely many sections.  This is Mathlib's canonical source-faithful
definition, via `SheafOfModules.LocalGeneratorsData.IsFiniteType`. -/
abbrev finiteType {X : RingedSpace.{v}} (F : Mod X.structureSheaf) : Prop :=
  SheafOfModules.IsFiniteType F

/-! ## Lemmas `pullback-finite-type` and `extension-finite-type` -/

/-- Pullback along a morphism of ringed spaces preserves finite type. -/
theorem finiteType_pullback
    {X Y : RingedSpace.{v}} (f : RingedSpaceHom X Y)
    (G : Mod Y.structureSheaf) (hG : finiteType G)
    [((SheafOfModules.pushforward (F := Opens.map f.continuous)
      f.sharp).IsRightAdjoint)] :
    finiteType ((sheafModuleRingedSpacePullback f).obj G) := by
  sorry

/-- The image of a morphism out of a finite-type module is finite type. -/
theorem finiteType_image
    {X : RingedSpace.{v}} {F G : Mod X.structureSheaf}
    (φ : F ⟶ G) (hF : finiteType F) :
    finiteType (image φ) := by
  sorry

/-- In a short exact sequence, finite type of the ends implies finite type of
the middle term. -/
theorem finiteType_of_shortExact
    {X : RingedSpace.{v}}
    {F₁ F₂ F₃ : Mod X.structureSheaf}
    (f : F₁ ⟶ F₂) (g : F₂ ⟶ F₃) (hfg : f ≫ g = 0)
    (hS : (sheafModuleShortComplex X.structureSheaf f g hfg).ShortExact)
    (h₁ : finiteType F₁) (h₃ : finiteType F₃) :
    finiteType F₂ := by
  sorry

/-! ## Lemmas `finite-type-surjective-on-stalk`, `finite-type-stalk-zero`, and
`support-finite-type-closed` -/

/-- A map to a finite-type module which is surjective on one stalk is
surjective on some neighbourhood of that point. -/
theorem finiteType_surjective_on_stalk
    {X : RingedSpace.{v}} {G F : Mod X.structureSheaf}
    (φ : G ⟶ F) (x : X) (hF : finiteType F)
    (hφx : Function.Surjective
      ((sheafModuleStalkFunctor X.structureSheaf x).map φ).hom) :
    ∃ U : Opens X.carrier, x ∈ U ∧
      Epi ((openModuleRestrictionFunctor X U).map φ) := by
  sorry

/-- A finite-type module whose stalk vanishes at a point vanishes on a
neighbourhood of that point. -/
theorem finiteType_stalk_zero
    {X : RingedSpace.{v}} {F : Mod X.structureSheaf} (x : X)
    (hF : finiteType F)
    (hx : IsZero ((sheafModuleStalkFunctor X.structureSheaf x).obj F)) :
    ∃ U : Opens X.carrier, x ∈ U ∧
      IsZero ((openModuleRestrictionFunctor X U).obj F) := by
  sorry

/-- A finite-type sheaf of modules has closed support. -/
theorem finiteType_support_isClosed
    {X : RingedSpace.{v}} (F : Mod X.structureSheaf)
    (hF : finiteType F) :
    IsClosed (moduleSupport (O := X.structureSheaf) F) := by
  sorry

/-! ## Lemma `finite-type-quasi-compact-colimit` -/

/-- A directed colimit which is finite type on a quasi-compact ringed space is
already covered by one stage. -/
theorem finiteType_directedColimit_epi
    {X : RingedSpace.{v}} [CompactSpace X]
    {I : Type v} [Preorder I] [Nonempty I] [IsDirectedOrder I]
    (F : I ⥤ Mod X.structureSheaf) (hF : finiteType (colimit F)) :
    ∃ i : I, Epi (colimit.ι F i) := by
  sorry

/-- If all transition maps in the directed system are monomorphisms, the
finite-type colimit is one of the stages up to isomorphism.  The source writes
this conclusion as equality; in the categorical formulation the canonical
statement is an isomorphism. -/
theorem finiteType_directedColimit_of_mono
    {X : RingedSpace.{v}} [CompactSpace X]
    {I : Type v} [Preorder I] [Nonempty I] [IsDirectedOrder I]
    (F : I ⥤ Mod X.structureSheaf) (hF : finiteType (colimit F))
    (hmono : ∀ {i j : I} (hij : i ≤ j),
      Mono (F.map (homOfLE hij))) :
    ∃ i : I, Nonempty (F.obj i ≅ colimit F) := by
  sorry

/-! ## Lemma `set-isomorphism-classes-finite-type-modules` -/

/-- The class of finite-type modules on a fixed ringed space has a set of
isomorphism-class representatives. -/
theorem finiteType_isomorphismClass_representatives
    (X : RingedSpace.{v}) :
    ∃ S : Set (Mod X.structureSheaf),
      (∀ F ∈ S, finiteType F) ∧
        ∀ F, finiteType F →
          ∃! G, G ∈ S ∧ Nonempty (F ≅ G) := by
  sorry

end

end Formalization.Books.Modules.Unit09
