import Formalization.Books.Sheaves.Unit17.Modules
import Mathlib.Algebra.Category.ModuleCat.Presheaf.Pullback
import Mathlib.Topology.Sheaves.CommRingCat

/-!
# Sheaves of Modules, Chapter 27: Localizing sheaves of rings

The source section is `books/modules.tex:4599-4700`.  Mathlib already has the
canonical `TopCat.Presheaf.SubmonoidPresheaf` and its localization, so the
presheaf of localized rings below is an alias to that construction.  The
module localization is represented by the canonical presheaf change-of-rings
(`PresheafOfModules.pullback`); its sectionwise object is canonically the
usual `LocalizedModule`.

The textbook writes several canonical identifications as equalities.  They
are stated here as category-theoretic isomorphisms where the two Lean objects
need not be definitionally equal.
-/

namespace Formalization.Books.Modules.Unit27

open CategoryTheory Opposite TopologicalSpace

universe u

noncomputable section

/-! ## Presheaves of commutative rings and their localizations -/

/-- A presheaf of commutative rings on a topological space. -/
abbrev CommRingPresheaf (X : TopCat.{u}) :=
  TopCat.Presheaf (CommRingCat.{u}) X

/-- The canonical multiplicative presheaf datum used by Mathlib. -/
abbrev MultiplicativePresheaf {X : TopCat.{u}} (O : CommRingPresheaf X) :=
  O.SubmonoidPresheaf

/-- The presheaf `S⁻¹ O`, sectionwise localized at `S`. -/
noncomputable abbrev localizedRingPresheaf
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) : CommRingPresheaf X :=
  S.localizationPresheaf

/-- The canonical map `O ⟶ S⁻¹ O`. -/
noncomputable abbrev localizationPresheafMap
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) : O ⟶ localizedRingPresheaf S :=
  S.toLocalizationPresheaf

/-- Restriction of a fraction is the fraction of the restrictions. -/
theorem localizationPresheaf_fraction_restriction
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O)
    {U V : (Opens X)ᵒᵖ} (i : U ⟶ V)
    (f : O.obj U) (s : S.obj U) :
    (localizedRingPresheaf S).map i
        (IsLocalization.mk' (Localization (S.obj U)) f s) =
      IsLocalization.mk' (Localization (S.obj V)) ((O.map i).hom f)
        ⟨(O.map i).hom s, S.map i s.property⟩ := by
  change IsLocalization.map (Localization (S.obj V)) (O.map i).hom (S.map i)
      (IsLocalization.mk' (Localization (S.obj U)) f s) = _
  exact IsLocalization.map_mk' (S.map i) f s

/-! ## Stalks and the sheafified localization -/

/-- The multiplicative subset `S_x`, generated by germs of local sections of
`S` at `x`.  This is the source's stalkwise multiplicative subset. -/
noncomputable def stalkSubmonoid
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (x : X) : Submonoid (O.stalk x) :=
  Submonoid.closure (Set.range fun p :
      Σ U : {U : Opens X // x ∈ U}, S.obj (op U.1) =>
        (O.germ p.1.1 x p.1.2).hom (p.2 : O.obj (op p.1.1)))

/-- The commutative-ring sheafification used for the source's `#` notation. -/
noncomputable def ringSheafification
    {X : TopCat.{u}} (O : CommRingPresheaf X) :
    Sheaf (Opens.grothendieckTopology X) CommRingCat.{u} :=
  (CategoryTheory.presheafToSheaf (Opens.grothendieckTopology X)
    CommRingCat).obj O

/-- The canonical map from a presheaf to its commutative-ring sheafification. -/
noncomputable def ringSheafificationUnit
    {X : TopCat.{u}} (O : CommRingPresheaf X) :
    O ⟶ (ringSheafification O).obj :=
  CategoryTheory.toSheafify (Opens.grothendieckTopology X) O

/-- The map obtained by sheafifying `O ⟶ S⁻¹ O`. -/
noncomputable def sheafifiedLocalizationMap
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) :
    ringSheafification O ⟶ ringSheafification (localizedRingPresheaf S) :=
  (CategoryTheory.presheafToSheaf (Opens.grothendieckTopology X)
    CommRingCat).map (localizationPresheafMap S)

/-- A presheaf map inverting all local sections of `S`. -/
def PresheafMapInverts
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O)
    {A : CommRingPresheaf X} (φ : O ⟶ A) : Prop :=
  ∀ U (s : S.obj U), IsUnit ((φ.app U).hom s)

/-- A map from the sheafification of `O` inverts the local sections of `S`. -/
def SheafMapInverts
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O)
    {A : Sheaf (Opens.grothendieckTopology X) CommRingCat.{u}}
    (φ : ringSheafification O ⟶ A) : Prop :=
  PresheafMapInverts S (ringSheafificationUnit O ≫ φ.hom)

/-- The five assertions in the source's universal localization lemma. -/
structure SimpleInvertAssertions
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) : Prop where
  /-- The canonical map sends every section of `S` to a unit. -/
  canonical_map_inverts :
    PresheafMapInverts S (localizationPresheafMap S)
  /-- The presheaf localization has the universal factorization property. -/
  presheaf_universal :
    ∀ {A : CommRingPresheaf X} (φ : O ⟶ A),
      PresheafMapInverts S φ →
        ∃! ψ : localizedRingPresheaf S ⟶ A,
          localizationPresheafMap S ≫ ψ = φ
  /-- The stalk of the presheaf localization is the localization of the
  stalk ring at the germs of `S`. -/
  stalk_iso :
    ∀ x : X, Nonempty
      ((localizedRingPresheaf S).stalk x ≅
        CommRingCat.of (Localization (stalkSubmonoid S x)))
  /-- The sheafification has the corresponding universal factorization
  property among sheaves of commutative rings. -/
  sheaf_universal :
    ∀ {A : Sheaf (Opens.grothendieckTopology X) CommRingCat.{u}}
      (φ : ringSheafification O ⟶ A),
      SheafMapInverts S φ →
        ∃! ψ : ringSheafification (localizedRingPresheaf S) ⟶ A,
          sheafifiedLocalizationMap S ≫ ψ = φ
  /-- Sheafification does not change the stalk comparison. -/
  sheaf_stalk_iso :
    ∀ x : X, Nonempty
      (TopCat.Presheaf.stalk
          (ringSheafification (localizedRingPresheaf S)).obj x ≅
        CommRingCat.of (Localization (stalkSubmonoid S x)))

/-- Mathlib's localization presheaf satisfies all five source assertions. -/
theorem simple_invert
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) :
    SimpleInvertAssertions S := by
  constructor
  · intro U s
    change IsUnit (algebraMap (O.obj U) (Localization (S.obj U)) s)
    exact IsLocalization.map_units (Localization (S.obj U)) s
  · intro A φ hφ
    let ψ : localizedRingPresheaf S ⟶ A := {
      app U := CommRingCat.ofHom <| IsLocalization.lift (fun s => hφ U s)
      naturality := by
        intro U V i
        apply CommRingCat.hom_ext
        apply IsLocalization.ringHom_ext (S.obj U)
        ext a
        change
          (IsLocalization.lift (fun s => hφ V s))
              (IsLocalization.map (Localization (S.obj V)) (O.map i).hom
                (S.map i) (algebraMap (O.obj U) (Localization (S.obj U)) a)) =
            (A.map i).hom
              ((IsLocalization.lift (fun s => hφ U s))
                (algebraMap (O.obj U) (Localization (S.obj U)) a))
        rw [IsLocalization.map_eq, IsLocalization.lift_eq,
          IsLocalization.lift_eq]
        have h := congrArg (fun z => z a) (φ.naturality i)
        change (φ.app V).hom ((O.map i).hom a) =
          (A.map i).hom ((φ.app U).hom a) at h
        exact h
    }
    refine ⟨ψ, ?_, ?_⟩
    · apply NatTrans.ext
      funext U
      induction U with
      | op U =>
        ext a
        change (IsLocalization.lift (fun s => hφ (op U) s))
            (algebraMap (O.obj (op U)) (Localization (S.obj (op U))) a) =
          (φ.app (op U)).hom a
        rw [IsLocalization.lift_eq]
    · intro ψ' hψ'
      apply NatTrans.ext
      funext U
      induction U with
      | op U =>
        apply CommRingCat.hom_ext
        apply IsLocalization.ringHom_ext (S.obj (op U))
        ext a
        have h := congr_app hψ' (op U)
        have ha := congrArg (fun z => z a) h
        change (ψ'.app (op U)).hom
            (algebraMap (O.obj (op U)) (Localization (S.obj (op U))) a) =
          (φ.app (op U)).hom a at ha
        change (ψ'.app (op U)).hom
            (algebraMap (O.obj (op U)) (Localization (S.obj (op U))) a) =
          (IsLocalization.lift (fun s => hφ (op U) s))
            (algebraMap (O.obj (op U)) (Localization (S.obj (op U))) a)
        rw [IsLocalization.lift_eq]
        exact ha
  · intro x
    let fU (U : (OpenNhds x)ᵒᵖ) :
        ((OpenNhds.inclusion x).op ⋙ localizedRingPresheaf S).obj U ⟶
          CommRingCat.of (Localization (stalkSubmonoid S x)) :=
      by
        let jU : (Opens X)ᵒᵖ := (OpenNhds.inclusion x).op.obj U
        let hxU : x ∈ jU.unop := U.unop.2
        letI : Algebra (O.obj jU) (((OpenNhds.inclusion x).op ⋙
            localizedRingPresheaf S).obj U) := by
          change Algebra (O.obj jU) (Localization (S.obj jU))
          infer_instance
        letI : IsLocalization (S.obj jU)
            (((OpenNhds.inclusion x).op ⋙ localizedRingPresheaf S).obj U) := by
          change IsLocalization (S.obj jU) (Localization (S.obj jU))
          infer_instance
        change CommRingCat.of (Localization (S.obj jU)) ⟶
          CommRingCat.of (Localization (stalkSubmonoid S x))
        exact CommRingCat.ofHom <|
          IsLocalization.lift
            (g := (algebraMap (O.stalk x) (Localization (stalkSubmonoid S x))).comp
              (O.germ jU.unop x hxU).hom)
            (fun s => by
              change IsUnit ((algebraMap (O.stalk x)
                (Localization (stalkSubmonoid S x))) ((O.germ jU.unop x hxU).hom s))
              let p : Σ V : {V : Opens X // x ∈ V}, S.obj (op V.1) :=
                ⟨⟨jU.unop, hxU⟩, s⟩
              apply IsLocalization.map_units (M := stalkSubmonoid S x)
                (Localization (stalkSubmonoid S x))
                ⟨(O.germ jU.unop x hxU).hom s, by
                  apply Submonoid.subset_closure
                  exact ⟨p, rfl⟩⟩)
    let χ : CategoryTheory.Limits.Cocone
        ((OpenNhds.inclusion x).op ⋙ localizedRingPresheaf S) :=
      CategoryTheory.Limits.Cocone.mk (CommRingCat.of (Localization (stalkSubmonoid S x)))
        { app := fun U => fU U
          naturality := by
            intro U V i
            let jU : (Opens X)ᵒᵖ := (OpenNhds.inclusion x).op.obj U
            let jV : (Opens X)ᵒᵖ := (OpenNhds.inclusion x).op.obj V
            let j := (OpenNhds.inclusion x).op.map i
            letI : Algebra (O.obj jU) (((OpenNhds.inclusion x).op ⋙
                localizedRingPresheaf S).obj U) := by
              change Algebra (O.obj jU) (Localization (S.obj jU))
              infer_instance
            letI : IsLocalization (S.obj jU)
                (((OpenNhds.inclusion x).op ⋙ localizedRingPresheaf S).obj U) := by
              change IsLocalization (S.obj jU) (Localization (S.obj jU))
              infer_instance
            letI : Algebra (O.obj jV) (((OpenNhds.inclusion x).op ⋙
                localizedRingPresheaf S).obj V) := by
              change Algebra (O.obj jV) (Localization (S.obj jV))
              infer_instance
            letI : IsLocalization (S.obj jV)
                (((OpenNhds.inclusion x).op ⋙ localizedRingPresheaf S).obj V) := by
              change IsLocalization (S.obj jV) (Localization (S.obj jV))
              infer_instance
            apply CommRingCat.hom_ext
            apply IsLocalization.ringHom_ext
              (S.obj ((OpenNhds.inclusion x).op.obj U))
            ext a
            let hxU : x ∈ jU.unop := U.unop.2
            let hxV : x ∈ jV.unop := V.unop.2
            change
              (IsLocalization.lift
                  (g := (algebraMap (O.stalk x)
                    (Localization (stalkSubmonoid S x))).comp
                    (O.germ jV.unop x hxV).hom) _)
                (IsLocalization.map (Localization (S.obj jV))
                  (O.map j).hom (S.map j)
                  (algebraMap (O.obj jU) (Localization (S.obj jU)) a)) =
              (IsLocalization.lift
                  (g := (algebraMap (O.stalk x)
                    (Localization (stalkSubmonoid S x))).comp
                    (O.germ jU.unop x hxU).hom) _)
                (algebraMap (O.obj jU) (Localization (S.obj jU)) a)
            rw [IsLocalization.map_eq, IsLocalization.lift_eq,
              IsLocalization.lift_eq]
            exact congrArg (fun z => (algebraMap (O.stalk x)
              (Localization (stalkSubmonoid S x))) z)
              (O.germ_res_apply' j x hxV a) }
    let f : (localizedRingPresheaf S).stalk x ⟶
        CommRingCat.of (Localization (stalkSubmonoid S x)) :=
      CategoryTheory.Limits.colimit.desc _ χ
    have hf_germ (U : Opens X) (hx : x ∈ U) :
        (localizedRingPresheaf S).germ U x hx ≫ f =
          fU (op ⟨U, hx⟩) := by
      exact CategoryTheory.Limits.colimit.ι_desc _ _
    let q : O.stalk x ⟶ (localizedRingPresheaf S).stalk x :=
      (TopCat.Presheaf.stalkFunctor CommRingCat x).map
        (localizationPresheafMap S)
    have hq_gen (U : Opens X) (hx : x ∈ U) (s : S.obj (op U)) :
        IsUnit (q.hom ((O.germ U x hx).hom s)) := by
      have h := TopCat.Presheaf.stalkFunctor_map_germ_apply
        U x hx (localizationPresheafMap S) s
      change IsUnit (((TopCat.Presheaf.stalkFunctor CommRingCat x).map
        (localizationPresheafMap S)).hom ((O.germ U x hx).hom s))
      rw [h]
      exact IsUnit.map ((localizedRingPresheaf S).germ U x hx).hom
        (IsLocalization.map_units (Localization (S.obj (op U))) s)
    let unitPreimage : Submonoid (O.stalk x) :=
      { carrier := {z | IsUnit (q.hom z)}
        one_mem' := by simpa using
          (isUnit_one : IsUnit (1 : (localizedRingPresheaf S).stalk x))
        mul_mem' := by
          intro a b ha hb
          change IsUnit (q.hom (a * b))
          simpa only [map_mul] using ha.mul hb }
    have hunit_le : stalkSubmonoid S x ≤ unitPreimage := by
      apply Submonoid.closure_le.2
      rintro y ⟨p, rfl⟩
      rcases p with ⟨U, s⟩
      exact hq_gen U.1 U.2 s
    have hq : ∀ z : stalkSubmonoid S x, IsUnit (q.hom z.1) := by
      intro z
      exact hunit_le z.2
    let g : Localization (stalkSubmonoid S x) →+* (localizedRingPresheaf S).stalk x :=
      IsLocalization.lift (g := q.hom) (fun z => hq z)
    have hqf : q ≫ f = CommRingCat.ofHom
        (algebraMap (O.stalk x) (Localization (stalkSubmonoid S x))) := by
      apply O.stalk_hom_ext
      intro U hx
      change (O.germ U x hx ≫ q) ≫ f = _
      have hmap := TopCat.Presheaf.stalkFunctor_map_germ
        U x hx (localizationPresheafMap S)
      have hmap' : O.germ U x hx ≫ q =
          (localizationPresheafMap S).app (op U) ≫
            (localizedRingPresheaf S).germ U x hx := by
        change O.germ U x hx ≫
          (TopCat.Presheaf.stalkFunctor CommRingCat x).map
            (localizationPresheafMap S) = _
        exact hmap
      rw [← Category.assoc, hmap', hf_germ]
      apply CommRingCat.hom_ext
      ext a
      change (fU (op ⟨U, hx⟩)).hom
          (((localizationPresheafMap S).app (op U)).hom ((O.germ U x hx).hom a)) = _
      simp [fU]
    have hfg : CommRingCat.ofHom g ≫ f = 𝟙 _ := by
      apply CommRingCat.hom_ext
      apply IsLocalization.ringHom_ext (stalkSubmonoid S x)
      ext z
      change f.hom (g (algebraMap (O.stalk x)
        (Localization (stalkSubmonoid S x)) z)) = _
      rw [IsLocalization.lift_eq]
      exact congrArg (fun h => h z) hqf
    have hfgU (U : (OpenNhds x)ᵒᵖ) :
        fU U ≫ CommRingCat.ofHom g =
          (localizedRingPresheaf S).germ U.unop.1 x U.unop.2 := by
      let jU : (Opens X)ᵒᵖ := (OpenNhds.inclusion x).op.obj U
      let hxU : x ∈ jU.unop := U.unop.2
      letI : Algebra (O.obj jU) (((OpenNhds.inclusion x).op ⋙
          localizedRingPresheaf S).obj U) := by
        change Algebra (O.obj jU) (Localization (S.obj jU))
        infer_instance
      letI : IsLocalization (S.obj jU)
          (((OpenNhds.inclusion x).op ⋙ localizedRingPresheaf S).obj U) := by
        change IsLocalization (S.obj jU) (Localization (S.obj jU))
        infer_instance
      apply CommRingCat.hom_ext
      apply IsLocalization.ringHom_ext
        (S.obj jU)
      ext a
      change
        g
            ((IsLocalization.lift
              (g := (algebraMap (O.stalk x)
                (Localization (stalkSubmonoid S x))).comp
                (O.germ jU.unop x hxU).hom) _)
              (algebraMap (O.obj jU) (Localization (S.obj jU)) a)) =
          (localizedRingPresheaf S).germ jU.unop x hxU
            (algebraMap (O.obj jU) (Localization (S.obj jU)) a)
      rw [IsLocalization.lift_eq]
      have hgcomp : g.comp (algebraMap (O.stalk x)
          (Localization (stalkSubmonoid S x))) = q.hom := by
        exact IsLocalization.lift_comp _
      change g (algebraMap (O.stalk x)
        (Localization (stalkSubmonoid S x))
        ((O.germ jU.unop x hxU).hom a)) = _
      rw [← RingHom.comp_apply, hgcomp]
      change q.hom ((O.germ jU.unop x hxU).hom a) =
        ((localizedRingPresheaf S).germ jU.unop x hxU).hom
          (((localizationPresheafMap S).app (op jU.unop)).hom a)
      simpa [q] using
        TopCat.Presheaf.stalkFunctor_map_germ_apply jU.unop x hxU
          (localizationPresheafMap S) a
    have hgf : f ≫ CommRingCat.ofHom g = 𝟙 _ := by
      apply (localizedRingPresheaf S).stalk_hom_ext
      intro U hx
      rw [← Category.assoc, hf_germ]
      convert hfgU (op ⟨U, hx⟩) using 1 <;>
        simp [TopCat.Presheaf.germ, OpenNhds.inclusion]
    let e : (localizedRingPresheaf S).stalk x ≅
        CommRingCat.of (Localization (stalkSubmonoid S x)) :=
      { hom := f, inv := CommRingCat.ofHom g,
        hom_inv_id := hgf, inv_hom_id := hfg }
    exact ⟨e⟩
  · sorry
  · sorry

/-! ## Localization of presheaves of modules -/

/-- The `RingCat` presheaf underlying a commutative-ring presheaf. -/
abbrev ringPresheaf {X : TopCat.{u}} (O : CommRingPresheaf X) :=
  O ⋙ (forget₂ CommRingCat RingCat)

/-- A presheaf of modules over a commutative-ring presheaf. -/
abbrev ModulePresheaf {X : TopCat.{u}} (O : CommRingPresheaf X) :=
  PresheafOfModules (ringPresheaf O)

/-- The underlying `RingCat` map of a commutative-ring presheaf map. -/
abbrev ringPresheafMap
    {X : TopCat.{u}} {O O' : CommRingPresheaf X} (φ : O ⟶ O') :
    ringPresheaf O ⟶ ringPresheaf O' :=
  Functor.whiskerRight φ (forget₂ CommRingCat RingCat)

/-- Sheafify a map of commutative-ring presheaves after forgetting
commutativity, for the module tensor-product interface. -/
noncomputable def ringSheafificationMap
    {X : TopCat.{u}} {O O' : CommRingPresheaf X} (φ : O ⟶ O') :
    Formalization.Books.Sheaves.Unit17.ringSheafification (ringPresheaf O) ⟶
      Formalization.Books.Sheaves.Unit17.ringSheafification (ringPresheaf O') :=
  Formalization.Books.Sheaves.Unit17.ringSheafificationMap (ringPresheafMap φ)

/-- The source's `S⁻¹ F`, represented by canonical presheaf extension of
scalars along `O ⟶ S⁻¹ O`. -/
noncomputable abbrev localizedModulePresheaf
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :
    ModulePresheaf (localizedRingPresheaf S) :=
  (Formalization.Books.Sheaves.Unit06.changeOfRingsCore
    (ringPresheafMap (localizationPresheafMap S))).obj F

/-- Under the sectionwise localized-module identifications, restriction sends
`t/s` to the fraction of the restricted numerator and denominator. -/
theorem localizedModulePresheaf_fraction_restriction
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O)
    {U V : (Opens X)ᵒᵖ} (i : U ⟶ V) :
    ∃ eU : (localizedModulePresheaf S F).obj U ≅
        ModuleCat.of (Localization (S.obj U))
          (LocalizedModule (S.obj U) (F.obj U)),
      ∃ eV : (localizedModulePresheaf S F).obj V ≅
        ModuleCat.of (Localization (S.obj V))
          (LocalizedModule (S.obj V) (F.obj V)),
        ∀ (t : F.obj U) (s : S.obj U),
              eV.hom.hom ((localizedModulePresheaf S F).map i
                (eU.inv.hom (LocalizedModule.mk t s))) =
            LocalizedModule.mk (F.map i t)
              ⟨(O.map i).hom s, S.map i s.property⟩ := by
  sorry

/- This is the remaining algebraic transport after the generic sectionwise
   comparison in Sheaves 6.  Unfold `localizedRingPresheaf` and identify the
   target ring action with the canonical `Localization (S.obj U)` action;
   the resulting tensor product is carried to `LocalizedModule` by
   `LocalizedModule.equivTensorProduct`.  Keeping this coercion-heavy step
   separate lets the presheaf proof use ordinary composition of isomorphisms. -/
theorem extendScalars_localization_iso
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O)
    (U : (Opens X)ᵒᵖ) :
    Nonempty
      ((ModuleCat.extendScalars ((localizationPresheafMap S).app U).hom).obj
          (ModuleCat.of (O.obj U) (F.obj U)) ≅
        ModuleCat.of (Localization (S.obj U))
          (LocalizedModule (S.obj U) (F.obj U))) := by
  sorry

/-- The sectionwise object of `S⁻¹ F` is canonically the usual localized
module. -/
theorem localizedModulePresheaf_section_iso
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O)
    (U : (Opens X)ᵒᵖ) :
    Nonempty
      ((localizedModulePresheaf S F).obj U ≅
        ModuleCat.of (Localization (S.obj U))
          (LocalizedModule (S.obj U) (F.obj U))) := by
  obtain ⟨e⟩ :=
    Formalization.Books.Sheaves.Unit06.tensorProductPresheaf_obj_iso
      (localizationPresheafMap S) F U
  obtain ⟨e'⟩ := extendScalars_localization_iso S F U
  exact ⟨e.symm ≪≫ e'⟩

/-- The first displayed module identity in the source is definitionally the
canonical `changeOfRingsCore`/tensor-product presheaf. -/
theorem localizedModulePresheaf_eq_tensorProduct
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :
    localizedModulePresheaf S F =
      Formalization.Books.Sheaves.Unit06.tensorProductPresheaf
        (ringPresheafMap (localizationPresheafMap S)) F := by
  rfl

/-- The sheafification of the localized module presheaf. -/
noncomputable abbrev localizedModuleSheafification
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :=
  Formalization.Books.Sheaves.Unit17.moduleSheafification
    (localizedModulePresheaf S F)

/-- The sheaf-level tensor product corresponding to `S⁻¹ O ⊗_O F`. -/
noncomputable abbrev localizedModuleTensorProductSheaf
    {X : TopCat.{u}} {O : CommRingPresheaf X}
  (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :=
  Formalization.Books.Sheaves.Unit17.tensorProductSheaf
    (ringSheafificationMap (localizationPresheafMap S))
    (Formalization.Books.Sheaves.Unit17.moduleSheafification F)

/-- The sheafified localization identity from the source.  No sheaf
hypothesis on `O` or `F` is needed: both sides are formed by the canonical
module-sheafification construction. -/
theorem simple_invert_module
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :
    Nonempty
      (localizedModuleSheafification S F ≅
        localizedModuleTensorProductSheaf S F) := by
  exact Formalization.Books.Sheaves.Unit17.moduleSheafification_changeOfRings_iso
    (ringPresheafMap (localizationPresheafMap S)) F

end

end Formalization.Books.Modules.Unit27
