import Formalization.Books.Sheaves.Unit17.Modules
import Mathlib.Algebra.Category.ModuleCat.Presheaf.Pullback
import Mathlib.Topology.Sheaves.CommRingCat

/-!
# Sheaves of Modules, Chapter 27: Localizing sheaves of rings

The source section is `books/modules.tex:4599-4700`.  Mathlib already has the
canonical `TopCat.Presheaf.SubmonoidPresheaf` and its localization, so the
presheaf of localized rings below is an alias to that construction.  The
module localization is represented by the canonical presheaf change-of-rings
(`PresheafOfModules.pullback`); its sectionwise object is canonically the
usual `LocalizedModule`.

The textbook writes several canonical identifications as equalities.  They
are stated here as category-theoretic isomorphisms where the two Lean objects
need not be definitionally equal.
-/

namespace Formalization.Books.Modules.Unit27

open CategoryTheory Opposite TopologicalSpace

universe u

noncomputable section

/-! ## Presheaves of commutative rings and their localizations -/

/-- A presheaf of commutative rings on a topological space. -/
abbrev CommRingPresheaf (X : TopCat.{u}) :=
  TopCat.Presheaf (CommRingCat.{u}) X

/-- The canonical multiplicative presheaf datum used by Mathlib. -/
abbrev MultiplicativePresheaf {X : TopCat.{u}} (O : CommRingPresheaf X) :=
  O.SubmonoidPresheaf

/-- The presheaf `S⁻¹ O`, sectionwise localized at `S`. -/
noncomputable abbrev localizedRingPresheaf
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) : CommRingPresheaf X :=
  S.localizationPresheaf

/-- The canonical map `O ⟶ S⁻¹ O`. -/
noncomputable abbrev localizationPresheafMap
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) : O ⟶ localizedRingPresheaf S :=
  S.toLocalizationPresheaf

/-- Restriction of a fraction is the fraction of the restrictions. -/
theorem localizationPresheaf_fraction_restriction
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O)
    {U V : (Opens X)ᵒᵖ} (i : U ⟶ V)
    (f : O.obj U) (s : S.obj U) :
    (localizedRingPresheaf S).map i
        (IsLocalization.mk' (Localization (S.obj U)) f s) =
      IsLocalization.mk' (Localization (S.obj V)) ((O.map i).hom f)
        ⟨(O.map i).hom s, S.map i s.property⟩ := by
  change IsLocalization.map (Localization (S.obj V)) (O.map i).hom (S.map i)
      (IsLocalization.mk' (Localization (S.obj U)) f s) = _
  exact IsLocalization.map_mk' (S.map i) f s

/-! ## Stalks and the sheafified localization -/

/-- The multiplicative subset `S_x`, generated by germs of local sections of
`S` at `x`.  This is the source's stalkwise multiplicative subset. -/
noncomputable def stalkSubmonoid
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (x : X) : Submonoid (O.stalk x) :=
  Submonoid.closure (Set.range fun p :
      Σ U : {U : Opens X // x ∈ U}, S.obj (op U.1) =>
        (O.germ p.1.1 x p.1.2).hom (p.2 : O.obj (op p.1.1)))

/-- The commutative-ring sheafification used for the source's `#` notation. -/
noncomputable def ringSheafification
    {X : TopCat.{u}} (O : CommRingPresheaf X) :
    Sheaf (Opens.grothendieckTopology X) CommRingCat.{u} :=
  (CategoryTheory.presheafToSheaf (Opens.grothendieckTopology X)
    CommRingCat).obj O

/-- The canonical map from a presheaf to its commutative-ring sheafification. -/
noncomputable def ringSheafificationUnit
    {X : TopCat.{u}} (O : CommRingPresheaf X) :
    O ⟶ (ringSheafification O).obj :=
  CategoryTheory.toSheafify (Opens.grothendieckTopology X) O

/-- The map obtained by sheafifying `O ⟶ S⁻¹ O`. -/
noncomputable def sheafifiedLocalizationMap
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) :
    ringSheafification O ⟶ ringSheafification (localizedRingPresheaf S) :=
  (CategoryTheory.presheafToSheaf (Opens.grothendieckTopology X)
    CommRingCat).map (localizationPresheafMap S)

/-- A presheaf map inverting all local sections of `S`. -/
def PresheafMapInverts
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O)
    {A : CommRingPresheaf X} (φ : O ⟶ A) : Prop :=
  ∀ U (s : S.obj U), IsUnit ((φ.app U).hom s)

/-- A map from the sheafification of `O` inverts the local sections of `S`. -/
def SheafMapInverts
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O)
    {A : Sheaf (Opens.grothendieckTopology X) CommRingCat.{u}}
    (φ : ringSheafification O ⟶ A) : Prop :=
  PresheafMapInverts S (ringSheafificationUnit O ≫ φ.hom)

/-- The five assertions in the source's universal localization lemma. -/
structure SimpleInvertAssertions
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) : Prop where
  /-- The canonical map sends every section of `S` to a unit. -/
  canonical_map_inverts :
    PresheafMapInverts S (localizationPresheafMap S)
  /-- The presheaf localization has the universal factorization property. -/
  presheaf_universal :
    ∀ {A : CommRingPresheaf X} (φ : O ⟶ A),
      PresheafMapInverts S φ →
        ∃! ψ : localizedRingPresheaf S ⟶ A,
          localizationPresheafMap S ≫ ψ = φ
  /-- The stalk of the presheaf localization is the localization of the
  stalk ring at the germs of `S`. -/
  stalk_iso :
    ∀ x : X, Nonempty
      ((localizedRingPresheaf S).stalk x ≅
        CommRingCat.of (Localization (stalkSubmonoid S x)))
  /-- The sheafification has the corresponding universal factorization
  property among sheaves of commutative rings. -/
  sheaf_universal :
    ∀ {A : Sheaf (Opens.grothendieckTopology X) CommRingCat.{u}}
      (φ : ringSheafification O ⟶ A),
      SheafMapInverts S φ →
        ∃! ψ : ringSheafification (localizedRingPresheaf S) ⟶ A,
          sheafifiedLocalizationMap S ≫ ψ = φ
  /-- Sheafification does not change the stalk comparison. -/
  sheaf_stalk_iso :
    ∀ x : X, Nonempty
      (TopCat.Presheaf.stalk
          (ringSheafification (localizedRingPresheaf S)).obj x ≅
        CommRingCat.of (Localization (stalkSubmonoid S x)))

/-- Mathlib's localization presheaf satisfies all five source assertions. -/
theorem simple_invert
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) :
    SimpleInvertAssertions S := by
  sorry

/-! ## Localization of presheaves of modules -/

/-- The `RingCat` presheaf underlying a commutative-ring presheaf. -/
abbrev ringPresheaf {X : TopCat.{u}} (O : CommRingPresheaf X) :=
  O ⋙ (forget₂ CommRingCat RingCat)

/-- A presheaf of modules over a commutative-ring presheaf. -/
abbrev ModulePresheaf {X : TopCat.{u}} (O : CommRingPresheaf X) :=
  PresheafOfModules (ringPresheaf O)

/-- The underlying `RingCat` map of a commutative-ring presheaf map. -/
abbrev ringPresheafMap
    {X : TopCat.{u}} {O O' : CommRingPresheaf X} (φ : O ⟶ O') :
    ringPresheaf O ⟶ ringPresheaf O' :=
  Functor.whiskerRight φ (forget₂ CommRingCat RingCat)

/-- Sheafify a map of commutative-ring presheaves after forgetting
commutativity, for the module tensor-product interface. -/
noncomputable def ringSheafificationMap
    {X : TopCat.{u}} {O O' : CommRingPresheaf X} (φ : O ⟶ O') :
    Formalization.Books.Sheaves.Unit17.ringSheafification (ringPresheaf O) ⟶
      Formalization.Books.Sheaves.Unit17.ringSheafification (ringPresheaf O') :=
  (CategoryTheory.presheafToSheaf (Opens.grothendieckTopology X)
    RingCat).map (ringPresheafMap φ)

/-- The source's `S⁻¹ F`, represented by canonical presheaf extension of
scalars along `O ⟶ S⁻¹ O`. -/
noncomputable abbrev localizedModulePresheaf
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :
    ModulePresheaf (localizedRingPresheaf S) :=
  (Formalization.Books.Sheaves.Unit06.changeOfRingsCore
    (ringPresheafMap (localizationPresheafMap S))).obj F

/-- Under the sectionwise localized-module identifications, restriction sends
`t/s` to the fraction of the restricted numerator and denominator. -/
theorem localizedModulePresheaf_fraction_restriction
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O)
    {U V : (Opens X)ᵒᵖ} (i : U ⟶ V) :
    ∃ eU : (localizedModulePresheaf S F).obj U ≅
        ModuleCat.of (Localization (S.obj U))
          (LocalizedModule (S.obj U) (F.obj U)),
      ∃ eV : (localizedModulePresheaf S F).obj V ≅
        ModuleCat.of (Localization (S.obj V))
          (LocalizedModule (S.obj V) (F.obj V)),
        ∀ (t : F.obj U) (s : S.obj U),
          eV.hom.hom ((localizedModulePresheaf S F).map i
            (eU.inv.hom (LocalizedModule.mk t s))) =
            LocalizedModule.mk (F.map i t)
              ⟨(O.map i).hom s, S.map i s.property⟩ := by
  sorry

/-- The sectionwise object of `S⁻¹ F` is canonically the usual localized
module. -/
theorem localizedModulePresheaf_section_iso
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O)
    (U : (Opens X)ᵒᵖ) :
    Nonempty
      ((localizedModulePresheaf S F).obj U ≅
        ModuleCat.of (Localization (S.obj U))
          (LocalizedModule (S.obj U) (F.obj U))) := by
  let e₁ := Classical.choice
    (Formalization.Books.Sheaves.Unit06.tensorProductPresheaf_section_iso
      (localizationPresheafMap S) F U.unop)
  let e₂ :
      Formalization.Books.Sheaves.Unit06.sectionwiseExtensionOfScalars
          (localizationPresheafMap S) F U.unop ≅
        ModuleCat.of (Localization (S.obj U))
          (LocalizedModule (S.obj U) (F.obj U)) :=
    (LocalizedModule.equivTensorProduct (S.obj U) (F.obj U)).symm.toModuleIso
  exact ⟨e₁ ≪≫ e₂⟩

/-- The first displayed module identity in the source is definitionally the
canonical `changeOfRingsCore`/tensor-product presheaf. -/
theorem localizedModulePresheaf_eq_tensorProduct
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :
    localizedModulePresheaf S F =
      Formalization.Books.Sheaves.Unit06.tensorProductPresheaf
        (ringPresheafMap (localizationPresheafMap S)) F := by
  rfl

/-- The sheafification of the localized module presheaf. -/
noncomputable abbrev localizedModuleSheafification
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :=
  Formalization.Books.Sheaves.Unit17.moduleSheafification
    (localizedModulePresheaf S F)

/-- The sheaf-level tensor product corresponding to `S⁻¹ O ⊗_O F`. -/
noncomputable abbrev localizedModuleTensorProductSheaf
    {X : TopCat.{u}} {O : CommRingPresheaf X}
  (S : MultiplicativePresheaf O) (F : ModulePresheaf O) :=
  Formalization.Books.Sheaves.Unit17.tensorProductSheaf
    (ringSheafificationMap (localizationPresheafMap S))
    (Formalization.Books.Sheaves.Unit17.moduleSheafification F)

/-- The two displayed module identities from the source. -/
theorem simple_invert_module
    {X : TopCat.{u}} {O : CommRingPresheaf X}
    (S : MultiplicativePresheaf O) (F : ModulePresheaf O)
    (hO : Presheaf.IsSheaf (Opens.grothendieckTopology X) O)
    (hF : Presheaf.IsSheaf (Opens.grothendieckTopology X) F.presheaf) :
    Nonempty
      (localizedModuleSheafification S F ≅
        localizedModuleTensorProductSheaf S F) := by
  sorry

end

end Formalization.Books.Modules.Unit27
