import Mathlib.Algebra.Colimit.Module
import Mathlib.Algebra.Field.Rat
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Examples, Chapter 35: Zero dimensional local ring with nonzero flat ideal

This file records the explicit quotient-ring construction, its candidate
maximal and flat ideals, and the direct-limit module from the source section.
The example-specific algebraic calculations and the flatness proofs belong to
the proof stage.

The source indexes its variables by the positive integers.  We reindex by
`ℕ`, so source index `i + 1` is represented here by `i`.
-/

noncomputable section

open scoped BigOperators

universe u

namespace Formalization.Books.Examples.Unit35

/-! ## The quotient ring and its displayed elements -/

/-- The two countable families of variables, with `false` for `X` and `true`
for `Y`. -/
abbrev zeroDimensionalFlatIdealVariables := ℕ × Bool

/-- The variable `X_i` (with the source's positive indexing reindexed by `ℕ`). -/
def zeroDimensionalFlatIdealXVar (i : ℕ) : zeroDimensionalFlatIdealVariables :=
  (i, false)

/-- The variable `Y_i` (with the source's positive indexing reindexed by `ℕ`). -/
def zeroDimensionalFlatIdealYVar (i : ℕ) : zeroDimensionalFlatIdealVariables :=
  (i, true)

/-- The ambient polynomial ring in all the `X_i` and `Y_i`. -/
abbrev zeroDimensionalFlatIdealPolynomial (k : Type u) [Field k] :=
  MvPolynomial zeroDimensionalFlatIdealVariables k

/-- The relation `X_i - Y_i X_(i+1)`. -/
def zeroDimensionalFlatIdealRelation (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealPolynomial k :=
  MvPolynomial.X (zeroDimensionalFlatIdealXVar i) -
    MvPolynomial.X (zeroDimensionalFlatIdealYVar i) *
      MvPolynomial.X (zeroDimensionalFlatIdealXVar (i + 1))

/-- The relation `Y_i²`. -/
def zeroDimensionalFlatIdealSquareRelation (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealPolynomial k :=
  MvPolynomial.X (zeroDimensionalFlatIdealYVar i) ^ 2

/-- The ideal generated by all the displayed relations. -/
def zeroDimensionalFlatIdealRelationsIdeal (k : Type u) [Field k] :
    Ideal (zeroDimensionalFlatIdealPolynomial k) :=
  Ideal.span
    (Set.range (zeroDimensionalFlatIdealRelation k) ∪
      Set.range (zeroDimensionalFlatIdealSquareRelation k))

/-- The ring `k[X_i,Y_i]/(X_i - Y_i X_(i+1), Y_i²)`. -/
abbrev zeroDimensionalFlatIdealRing (k : Type u) [Field k] :=
  zeroDimensionalFlatIdealPolynomial k ⧸ zeroDimensionalFlatIdealRelationsIdeal k

/-- The image `x_i` of `X_i` in the quotient ring. -/
def zeroDimensionalFlatIdealX (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealRing k :=
  Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k)
    (MvPolynomial.X (zeroDimensionalFlatIdealXVar i))

/-- The image `y_i` of `Y_i` in the quotient ring. -/
def zeroDimensionalFlatIdealY (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealRing k :=
  Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k)
    (MvPolynomial.X (zeroDimensionalFlatIdealYVar i))

/-!
The first displayed calculation in the source is recorded in a form that
also handles an arbitrary finite segment of the chain.
-/

/-- The defining relation `x_i = y_i x_(i+1)`. -/
theorem zeroDimensionalFlatIdeal_x_eq_y_mul_next_x
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealX k i =
      zeroDimensionalFlatIdealY k i * zeroDimensionalFlatIdealX k (i + 1) := by
  change Ideal.Quotient.mk _ _ = Ideal.Quotient.mk _ _
  rw [Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact Ideal.subset_span (Or.inl ⟨i, rfl⟩)

@[simp]
theorem zeroDimensionalFlatIdeal_y_sq_eq_zero
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealY k i ^ 2 = 0 := by
  change (Ideal.Quotient.mk _ (MvPolynomial.X (zeroDimensionalFlatIdealYVar i))) ^ 2 = 0
  rw [← map_pow, Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span (Or.inr ⟨i, rfl⟩)

/-- The product of the `y`-variables from `i` up to, but excluding, `j`. -/
def zeroDimensionalFlatIdealTransitionProduct
    (k : Type u) [Field k] (i j : ℕ) : zeroDimensionalFlatIdealRing k :=
  ∏ n ∈ Finset.Ico i j, zeroDimensionalFlatIdealY k n

/-- The finite form of the source's chain identity for the `x_i`. -/
theorem zeroDimensionalFlatIdeal_x_eq_transitionProduct_mul_x
    (k : Type u) [Field k] (i j : ℕ) (hij : i ≤ j) :
    zeroDimensionalFlatIdealX k i =
      zeroDimensionalFlatIdealTransitionProduct k i j *
        zeroDimensionalFlatIdealX k j := by
  refine Nat.le_induction ?_ ?_ j hij
  · simp [zeroDimensionalFlatIdealTransitionProduct]
  · intro n hn ih
    calc
      zeroDimensionalFlatIdealX k i =
          zeroDimensionalFlatIdealTransitionProduct k i n *
            zeroDimensionalFlatIdealX k n := ih
      _ = zeroDimensionalFlatIdealTransitionProduct k i n *
            (zeroDimensionalFlatIdealY k n *
              zeroDimensionalFlatIdealX k (n + 1)) := by
        rw [zeroDimensionalFlatIdeal_x_eq_y_mul_next_x k n]
      _ = zeroDimensionalFlatIdealTransitionProduct k i (n + 1) *
            zeroDimensionalFlatIdealX k (n + 1) := by
        simp only [zeroDimensionalFlatIdealTransitionProduct]
        rw [Finset.prod_Ico_succ_top hn]
        ring

/-! ## The unique prime and the candidate flat ideal -/

/-- The ideal `(x_i, y_i)` proposed in the source as the unique prime ideal. -/
def zeroDimensionalFlatIdealMaximalIdeal (k : Type u) [Field k] :
    Ideal (zeroDimensionalFlatIdealRing k) :=
  Ideal.span
    (Set.range (zeroDimensionalFlatIdealX k) ∪
      Set.range (zeroDimensionalFlatIdealY k))

/-- The ideal `I = (x_i)` from the source. -/
def zeroDimensionalFlatIdeal (k : Type u) [Field k] :
    Ideal (zeroDimensionalFlatIdealRing k) :=
  Ideal.span (Set.range (zeroDimensionalFlatIdealX k))

/-- The proposed maximal ideal is prime. -/
theorem zeroDimensionalFlatIdeal_maximalIdeal_isPrime
    (k : Type u) [Field k] :
    (zeroDimensionalFlatIdealMaximalIdeal k).IsPrime := by
  let J : Ideal (zeroDimensionalFlatIdealPolynomial k) :=
    Ideal.span (MvPolynomial.X '' (Set.univ : Set zeroDimensionalFlatIdealVariables))
  have hJker :
      J = RingHom.ker
        (MvPolynomial.constantCoeff :
          zeroDimensionalFlatIdealPolynomial k →+* k) := by
    ext p
    rw [RingHom.mem_ker, MvPolynomial.mem_ideal_span_X_image]
    constructor
    · intro hp
      rw [MvPolynomial.constantCoeff_eq]
      by_contra h
      have h0 : (0 : zeroDimensionalFlatIdealVariables →₀ ℕ) ∈ p.support := by
        simpa [MvPolynomial.mem_support_iff] using h
      obtain ⟨v, hv, hv0⟩ := hp 0 h0
      exact hv0 (by simp)
    · rw [MvPolynomial.constantCoeff_eq]
      intro hp m hm
      by_contra h
      push Not at h
      have hm0 : m = 0 := Finsupp.ext (fun i => h i (Set.mem_univ _))
      have hm' : MvPolynomial.coeff m p ≠ 0 := by
        simpa [MvPolynomial.mem_support_iff] using hm
      exact hm' (hm0 ▸ hp)
  have hJprime : J.IsPrime := by
    rw [hJker]
    exact RingHom.ker_isPrime _
  have hmem (v : zeroDimensionalFlatIdealVariables) :
      MvPolynomial.X v ∈ J :=
    Ideal.subset_span ⟨v, Set.mem_univ _, rfl⟩
  have hLJ : zeroDimensionalFlatIdealRelationsIdeal k ≤ J := by
    rw [zeroDimensionalFlatIdealRelationsIdeal]
    apply Ideal.span_le.2
    rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
    · simpa [zeroDimensionalFlatIdealRelation] using
        J.sub_mem (hmem _) (J.mul_mem_left _ (hmem _))
    · simpa [zeroDimensionalFlatIdealSquareRelation, pow_two] using
        J.mul_mem_left _ (hmem _)
  let q : zeroDimensionalFlatIdealPolynomial k →+*
      zeroDimensionalFlatIdealRing k :=
    Ideal.Quotient.mk _
  have hmap : Ideal.map q J = zeroDimensionalFlatIdealMaximalIdeal k := by
    apply le_antisymm
    · rw [Ideal.map_le_iff_le_comap]
      apply Ideal.span_le.2
      rintro z ⟨v, -, rfl⟩
      cases v with
      | mk n b =>
        cases b with
        | false =>
          change zeroDimensionalFlatIdealX k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inl ⟨n, rfl⟩)
        | true =>
          change zeroDimensionalFlatIdealY k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inr ⟨n, rfl⟩)
    · rw [zeroDimensionalFlatIdealMaximalIdeal]
      apply Ideal.span_le.2
      rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealXVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (hmem _)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealYVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (hmem _)
  rw [← hmap]
  apply Ideal.map_isPrime_of_surjective (f := q) (I := J) (H := hJprime)
    Ideal.Quotient.mk_surjective
  simpa [q] using hLJ

private theorem zeroDimensionalFlatIdeal_maximalIdeal_isMaximal
    (k : Type u) [Field k] :
    (zeroDimensionalFlatIdealMaximalIdeal k).IsMaximal := by
  let J : Ideal (zeroDimensionalFlatIdealPolynomial k) :=
    Ideal.span (MvPolynomial.X '' (Set.univ : Set zeroDimensionalFlatIdealVariables))
  have hJker :
      J = RingHom.ker
        (MvPolynomial.constantCoeff :
          zeroDimensionalFlatIdealPolynomial k →+* k) := by
    ext p
    rw [RingHom.mem_ker, MvPolynomial.mem_ideal_span_X_image]
    constructor
    · intro hp
      rw [MvPolynomial.constantCoeff_eq]
      by_contra h
      have h0 : (0 : zeroDimensionalFlatIdealVariables →₀ ℕ) ∈ p.support := by
        simpa [MvPolynomial.mem_support_iff] using h
      obtain ⟨v, hv, hv0⟩ := hp 0 h0
      exact hv0 (by simp)
    · rw [MvPolynomial.constantCoeff_eq]
      intro hp m hm
      by_contra h
      push Not at h
      have hm0 : m = 0 := Finsupp.ext (fun i => h i (Set.mem_univ _))
      have hm' : MvPolynomial.coeff m p ≠ 0 := by
        simpa [MvPolynomial.mem_support_iff] using hm
      exact hm' (hm0 ▸ hp)
  have hLJ : zeroDimensionalFlatIdealRelationsIdeal k ≤ J := by
    rw [zeroDimensionalFlatIdealRelationsIdeal]
    apply Ideal.span_le.2
    rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
    · simpa [zeroDimensionalFlatIdealRelation] using
        J.sub_mem (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
          (J.mul_mem_left _ (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩))
    · simpa [zeroDimensionalFlatIdealSquareRelation, pow_two] using
        J.mul_mem_left _ (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
  let q : zeroDimensionalFlatIdealPolynomial k →+*
      zeroDimensionalFlatIdealRing k :=
    Ideal.Quotient.mk _
  let φ : zeroDimensionalFlatIdealRing k →+* k :=
    Ideal.Quotient.lift (zeroDimensionalFlatIdealRelationsIdeal k)
      (MvPolynomial.constantCoeff : zeroDimensionalFlatIdealPolynomial k →+* k) (by
        intro z hz
        have hzJ : z ∈ J := hLJ hz
        rw [hJker] at hzJ
        exact RingHom.mem_ker.mp hzJ)
  have hφsurj : Function.Surjective φ := by
    intro a
    refine ⟨Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k)
      (MvPolynomial.C a), ?_⟩
    simp [φ]
  have hmap : Ideal.map q J = zeroDimensionalFlatIdealMaximalIdeal k := by
    apply le_antisymm
    · rw [Ideal.map_le_iff_le_comap]
      apply Ideal.span_le.2
      rintro z ⟨v, -, rfl⟩
      cases v with
      | mk n b =>
        cases b with
        | false =>
          change zeroDimensionalFlatIdealX k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inl ⟨n, rfl⟩)
        | true =>
          change zeroDimensionalFlatIdealY k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inr ⟨n, rfl⟩)
    · rw [zeroDimensionalFlatIdealMaximalIdeal]
      apply Ideal.span_le.2
      rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealXVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealYVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
  have hker : RingHom.ker φ = zeroDimensionalFlatIdealMaximalIdeal k := by
    apply le_antisymm
    · intro z hz
      induction z using Quotient.inductionOn' with | _ z =>
        have hz' : MvPolynomial.constantCoeff z = 0 := by
          rw [RingHom.mem_ker] at hz
          change φ (Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k) z) = 0 at hz
          dsimp [φ] at hz
          exact hz
        have hzJ : z ∈ J := by
          rw [hJker, RingHom.mem_ker]
          exact hz'
        have : q z ∈ Ideal.map q J := Ideal.mem_map_of_mem q hzJ
        rw [hmap] at this
        exact this
    · rw [zeroDimensionalFlatIdealMaximalIdeal]
      apply Ideal.span_le.2
      rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
      · change φ (q (MvPolynomial.X (zeroDimensionalFlatIdealXVar n))) = 0
        simp [φ, q]
      · change φ (q (MvPolynomial.X (zeroDimensionalFlatIdealYVar n))) = 0
        simp [φ, q]
  rw [← hker]
  exact RingHom.ker_isMaximal_of_surjective φ hφsurj

/-- Every prime ideal is the displayed ideal `(x_i,y_i)`. -/
theorem zeroDimensionalFlatIdeal_unique_prime
    (k : Type u) [Field k] (p : Ideal (zeroDimensionalFlatIdealRing k))
    (hp : p.IsPrime) :
    p = zeroDimensionalFlatIdealMaximalIdeal k := by
  have hmax : (zeroDimensionalFlatIdealMaximalIdeal k).IsMaximal :=
    zeroDimensionalFlatIdeal_maximalIdeal_isMaximal k
  have hle : zeroDimensionalFlatIdealMaximalIdeal k ≤ p := by
    rw [zeroDimensionalFlatIdealMaximalIdeal]
    apply Ideal.span_le.2
    rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
    · have hyn : zeroDimensionalFlatIdealY k n ∈ p := hp.mem_of_pow_mem 2 (by
        rw [show zeroDimensionalFlatIdealY k n ^ 2 = 0 by
          exact zeroDimensionalFlatIdeal_y_sq_eq_zero k n]
        exact p.zero_mem)
      rw [zeroDimensionalFlatIdeal_x_eq_y_mul_next_x k n]
      simpa [mul_comm] using
        p.mul_mem_left (zeroDimensionalFlatIdealX k (n + 1)) hyn
    · exact hp.mem_of_pow_mem 2 (by
        rw [show zeroDimensionalFlatIdealY k n ^ 2 = 0 by
          exact zeroDimensionalFlatIdeal_y_sq_eq_zero k n]
        exact p.zero_mem)
  exact (hmax.eq_of_le hp.ne_top hle).symm

/-- The quotient ring is zero-dimensional in the Krull-dimension sense. -/
theorem zeroDimensionalFlatIdeal_ring_krullDimLE_zero
    (k : Type u) [Field k] :
    Ring.KrullDimLE 0 (zeroDimensionalFlatIdealRing k) := by
  apply Ring.KrullDimLE.mk₀
  intro p hp
  rw [zeroDimensionalFlatIdeal_unique_prime k p hp]
  exact zeroDimensionalFlatIdeal_maximalIdeal_isMaximal k

/-- A local-ring instance for the constructed quotient. -/
instance zeroDimensionalFlatIdeal_ring_isLocalRing_instance
    (k : Type u) [Field k] : IsLocalRing (zeroDimensionalFlatIdealRing k) := by
  apply IsLocalRing.of_unique_max_ideal
  refine ⟨zeroDimensionalFlatIdealMaximalIdeal k,
    zeroDimensionalFlatIdeal_maximalIdeal_isMaximal k, ?_⟩
  intro I hI
  exact zeroDimensionalFlatIdeal_unique_prime k I hI.isPrime

/-- The local-ring assertion for the constructed quotient. -/
theorem zeroDimensionalFlatIdeal_ring_isLocalRing
    (k : Type u) [Field k] : IsLocalRing (zeroDimensionalFlatIdealRing k) := by
  infer_instance

/-- The source's displayed ideal is below the unique prime ideal. -/
theorem zeroDimensionalFlatIdeal_le_maximalIdeal
    (k : Type u) [Field k] :
    zeroDimensionalFlatIdeal k ≤ zeroDimensionalFlatIdealMaximalIdeal k := by
  rw [zeroDimensionalFlatIdeal, zeroDimensionalFlatIdealMaximalIdeal]
  apply Ideal.span_le.2
  rintro z ⟨n, rfl⟩
  exact Ideal.subset_span (Or.inl ⟨n, rfl⟩)

/-- The source's ideal `I` is nonzero. -/
theorem zeroDimensionalFlatIdeal_ne_bot
    (k : Type u) [Field k] : zeroDimensionalFlatIdeal k ≠ ⊥ := by
  sorry

/-! ## The annihilator computation for `x_i` -/

/-- The ideal generated by all `x_j` and by `y_j` for `j ≥ i`. -/
def zeroDimensionalFlatIdealXAnnihilatorCandidate
    (k : Type u) [Field k] (i : ℕ) : Ideal (zeroDimensionalFlatIdealRing k) :=
  Ideal.span
    (Set.range (zeroDimensionalFlatIdealX k) ∪
      Set.range (fun j : {j : ℕ // i ≤ j} => zeroDimensionalFlatIdealY k j.1))

/-- The annihilator of `x_i` is the ideal displayed in the source. -/
theorem zeroDimensionalFlatIdeal_x_annihilator
    (k : Type u) [Field k] (i : ℕ) :
    (Submodule.span (zeroDimensionalFlatIdealRing k)
        ({zeroDimensionalFlatIdealX k i} : Set (zeroDimensionalFlatIdealRing k))).annihilator =
      zeroDimensionalFlatIdealXAnnihilatorCandidate k i := by
  sorry

/-! ## The flat direct-limit module -/

/-- The `R`-linear transition map from stage `i` to stage `j`, multiplying by
`y_i ··· y_(j-1)`. -/
def zeroDimensionalFlatIdealTransitionMap
    (k : Type u) [Field k] (i j : ℕ) (_hij : i ≤ j) :
    zeroDimensionalFlatIdealRing k →ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdealRing k :=
  LinearMap.mulRight (zeroDimensionalFlatIdealRing k)
    (zeroDimensionalFlatIdealTransitionProduct k i j)

/-- The adjacent transition is multiplication by `y_i`, as in the source. -/
theorem zeroDimensionalFlatIdeal_transitionMap_succ
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealTransitionMap k i (i + 1) (Nat.le_succ i) =
      LinearMap.mulRight (zeroDimensionalFlatIdealRing k)
        (zeroDimensionalFlatIdealY k i) := by
  sorry

/-- The source module `M`, represented by Mathlib's module direct limit. -/
abbrev zeroDimensionalFlatIdealModule (k : Type u) [Field k] :=
  Module.DirectLimit
    (R := zeroDimensionalFlatIdealRing k) (ι := ℕ)
    (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
    (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h)

/-- The generator `e_i` coming from the unit of the `i`-th copy of `R`. -/
def zeroDimensionalFlatIdealModuleGenerator
    (k : Type u) [Field k] (i : ℕ) : zeroDimensionalFlatIdealModule k :=
  Module.DirectLimit.of (zeroDimensionalFlatIdealRing k) ℕ
    (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
    (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h) i 1

/-- The defining relation `e_i = y_i e_(i+1)`. -/
theorem zeroDimensionalFlatIdeal_moduleGenerator_relation
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealModuleGenerator k i =
      zeroDimensionalFlatIdealY k i •
        zeroDimensionalFlatIdealModuleGenerator k (i + 1) := by
  sorry

/-- Every element of `M` is represented by a scalar times one displayed
generator. -/
theorem zeroDimensionalFlatIdeal_module_element_representation
    (k : Type u) [Field k] (m : zeroDimensionalFlatIdealModule k) :
    ∃ (i : ℕ) (f : zeroDimensionalFlatIdealRing k),
      m = f • zeroDimensionalFlatIdealModuleGenerator k i := by
  sorry

/-- The module direct limit is flat over the quotient ring. -/
theorem zeroDimensionalFlatIdeal_module_flat
    (k : Type u) [Field k] :
    Module.Flat (zeroDimensionalFlatIdealRing k)
      (zeroDimensionalFlatIdealModule k) := by
  sorry

/-! ## The map from the direct limit to `I` -/

/-- The copy of `x_i` as an element of the ideal `I`. -/
def zeroDimensionalFlatIdealGenerator
    (k : Type u) [Field k] (i : ℕ) : zeroDimensionalFlatIdeal k :=
  ⟨zeroDimensionalFlatIdealX k i,
    Ideal.subset_span (Set.mem_range_self i)⟩

/-- Every element of `I` is represented by a scalar times one displayed
ideal generator. -/
theorem zeroDimensionalFlatIdeal_element_representation
    (k : Type u) [Field k] (a : zeroDimensionalFlatIdeal k) :
    ∃ (i : ℕ) (h : zeroDimensionalFlatIdealRing k),
      a = h • zeroDimensionalFlatIdealGenerator k i := by
  sorry

/-- The map from the `i`-th copy of `R` to `I`, sending `f` to `f x_i`. -/
def zeroDimensionalFlatIdealModuleStageMap
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealRing k →ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdeal k :=
  (LinearMap.mulRight (zeroDimensionalFlatIdealRing k)
      (zeroDimensionalFlatIdealX k i)).codRestrict
    (zeroDimensionalFlatIdeal k)
    (fun f =>
      Ideal.mul_mem_left (zeroDimensionalFlatIdeal k) f
        (Ideal.subset_span (Set.mem_range_self i)))

/-- The stage maps respect the direct-system transition maps. -/
theorem zeroDimensionalFlatIdealModuleStageMap_compatibility
    (k : Type u) [Field k] (i j : ℕ) (hij : i ≤ j)
    (f : zeroDimensionalFlatIdealRing k) :
    zeroDimensionalFlatIdealModuleStageMap k j
        (zeroDimensionalFlatIdealTransitionMap k i j hij f) =
      zeroDimensionalFlatIdealModuleStageMap k i f := by
  sorry

/-- The canonical map `M → I` whose value on `e_i` is `x_i`. -/
noncomputable def zeroDimensionalFlatIdealModuleToIdeal
    (k : Type u) [Field k] :
    zeroDimensionalFlatIdealModule k →ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdeal k :=
  Module.DirectLimit.lift (zeroDimensionalFlatIdealRing k) ℕ
    (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
    (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h)
    (fun i => zeroDimensionalFlatIdealModuleStageMap k i)
    (fun i j h f => zeroDimensionalFlatIdealModuleStageMap_compatibility k i j h f)

@[simp]
theorem zeroDimensionalFlatIdealModuleToIdeal_generator
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealModuleToIdeal k
        (zeroDimensionalFlatIdealModuleGenerator k i) =
      zeroDimensionalFlatIdealGenerator k i := by
  sorry

/-- The canonical map from the direct limit to `I` is bijective. -/
theorem zeroDimensionalFlatIdealModuleToIdeal_bijective
    (k : Type u) [Field k] :
    Function.Bijective (zeroDimensionalFlatIdealModuleToIdeal k) := by
  sorry

/-- The source's isomorphism `M ≅ I`, made available as a linear equivalence. -/
noncomputable def zeroDimensionalFlatIdealModuleToIdealEquiv
    (k : Type u) [Field k] :
    zeroDimensionalFlatIdealModule k ≃ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdeal k :=
  LinearEquiv.ofBijective (zeroDimensionalFlatIdealModuleToIdeal k)
    (zeroDimensionalFlatIdealModuleToIdeal_bijective k)

theorem zeroDimensionalFlatIdealModuleToIdealEquiv_generator
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealModuleToIdealEquiv k
        (zeroDimensionalFlatIdealModuleGenerator k i) =
      zeroDimensionalFlatIdealGenerator k i := by
  sorry

/-- The ideal `I` is flat over the constructed ring. -/
theorem zeroDimensionalFlatIdeal_flat
    (k : Type u) [Field k] :
    Module.Flat (zeroDimensionalFlatIdealRing k) (zeroDimensionalFlatIdeal k) := by
  sorry

/-! ## The annihilator computation for `e_i` and the final example -/

/-- The annihilator of `e_i` is the same displayed ideal as the annihilator of
`x_i`. -/
theorem zeroDimensionalFlatIdeal_moduleGenerator_annihilator
    (k : Type u) [Field k] (i : ℕ) :
    (Submodule.span (zeroDimensionalFlatIdealRing k)
        ({zeroDimensionalFlatIdealModuleGenerator k i} :
          Set (zeroDimensionalFlatIdealModule k))).annihilator =
      zeroDimensionalFlatIdealXAnnihilatorCandidate k i := by
  sorry

/-- The source's final existence statement. -/
theorem exists_local_ring_unique_prime_nonzero_flat_ideal :
    ∃ (R : Type) (_ : CommRing R) (_ : IsLocalRing R)
      (m I : Ideal R),
      m.IsPrime ∧
        (∀ p : Ideal R, p.IsPrime → p = m) ∧
        I ≠ ⊥ ∧ Module.Flat R I := by
  refine ⟨zeroDimensionalFlatIdealRing ℚ, inferInstance,
    zeroDimensionalFlatIdeal_ring_isLocalRing ℚ,
    zeroDimensionalFlatIdealMaximalIdeal ℚ, zeroDimensionalFlatIdeal ℚ, ?_, ?_, ?_, ?_⟩
  · exact zeroDimensionalFlatIdeal_maximalIdeal_isPrime ℚ
  · intro p hp
    exact zeroDimensionalFlatIdeal_unique_prime ℚ p hp
  · exact zeroDimensionalFlatIdeal_ne_bot ℚ
  · exact zeroDimensionalFlatIdeal_flat ℚ

end Formalization.Books.Examples.Unit35
