import Mathlib.Algebra.Colimit.Module
import Mathlib.Algebra.Field.Rat
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.MvPolynomial.Ideal

/-!
# Examples, Chapter 35: Zero dimensional local ring with nonzero flat ideal

This file records the explicit quotient-ring construction, its candidate
maximal and flat ideals, and the direct-limit module from the source section.
The example-specific algebraic calculations and the flatness proofs belong to
the proof stage.

The source indexes its variables by the positive integers.  We reindex by
`ℕ`, so source index `i + 1` is represented here by `i`.
-/

noncomputable section

open scoped BigOperators

universe u

namespace Formalization.Books.Examples.Unit35

/-! ## The quotient ring and its displayed elements -/

/-- The two countable families of variables, with `false` for `X` and `true`
for `Y`. -/
abbrev zeroDimensionalFlatIdealVariables := ℕ × Bool

/-- The variable `X_i` (with the source's positive indexing reindexed by `ℕ`). -/
def zeroDimensionalFlatIdealXVar (i : ℕ) : zeroDimensionalFlatIdealVariables :=
  (i, false)

/-- The variable `Y_i` (with the source's positive indexing reindexed by `ℕ`). -/
def zeroDimensionalFlatIdealYVar (i : ℕ) : zeroDimensionalFlatIdealVariables :=
  (i, true)

/-- The ambient polynomial ring in all the `X_i` and `Y_i`. -/
abbrev zeroDimensionalFlatIdealPolynomial (k : Type u) [Field k] :=
  MvPolynomial zeroDimensionalFlatIdealVariables k

/-- The relation `X_i - Y_i X_(i+1)`. -/
def zeroDimensionalFlatIdealRelation (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealPolynomial k :=
  MvPolynomial.X (zeroDimensionalFlatIdealXVar i) -
    MvPolynomial.X (zeroDimensionalFlatIdealYVar i) *
      MvPolynomial.X (zeroDimensionalFlatIdealXVar (i + 1))

/-- The relation `Y_i²`. -/
def zeroDimensionalFlatIdealSquareRelation (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealPolynomial k :=
  MvPolynomial.X (zeroDimensionalFlatIdealYVar i) ^ 2

/-- The ideal generated by all the displayed relations. -/
def zeroDimensionalFlatIdealRelationsIdeal (k : Type u) [Field k] :
    Ideal (zeroDimensionalFlatIdealPolynomial k) :=
  Ideal.span
    (Set.range (zeroDimensionalFlatIdealRelation k) ∪
      Set.range (zeroDimensionalFlatIdealSquareRelation k))

/-- The ring `k[X_i,Y_i]/(X_i - Y_i X_(i+1), Y_i²)`. -/
abbrev zeroDimensionalFlatIdealRing (k : Type u) [Field k] :=
  zeroDimensionalFlatIdealPolynomial k ⧸ zeroDimensionalFlatIdealRelationsIdeal k

/-- The image `x_i` of `X_i` in the quotient ring. -/
def zeroDimensionalFlatIdealX (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealRing k :=
  Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k)
    (MvPolynomial.X (zeroDimensionalFlatIdealXVar i))

/-- The image `y_i` of `Y_i` in the quotient ring. -/
def zeroDimensionalFlatIdealY (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealRing k :=
  Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k)
    (MvPolynomial.X (zeroDimensionalFlatIdealYVar i))

/-!
The first displayed calculation in the source is recorded in a form that
also handles an arbitrary finite segment of the chain.
-/

/-- The defining relation `x_i = y_i x_(i+1)`. -/
theorem zeroDimensionalFlatIdeal_x_eq_y_mul_next_x
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealX k i =
      zeroDimensionalFlatIdealY k i * zeroDimensionalFlatIdealX k (i + 1) := by
  change Ideal.Quotient.mk _ _ = Ideal.Quotient.mk _ _
  rw [Ideal.Quotient.mk_eq_mk_iff_sub_mem]
  exact Ideal.subset_span (Or.inl ⟨i, rfl⟩)

@[simp]
theorem zeroDimensionalFlatIdeal_y_sq_eq_zero
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealY k i ^ 2 = 0 := by
  change (Ideal.Quotient.mk _ (MvPolynomial.X (zeroDimensionalFlatIdealYVar i))) ^ 2 = 0
  rw [← map_pow, Ideal.Quotient.eq_zero_iff_mem]
  exact Ideal.subset_span (Or.inr ⟨i, rfl⟩)

/-- The product of the `y`-variables from `i` up to, but excluding, `j`. -/
def zeroDimensionalFlatIdealTransitionProduct
    (k : Type u) [Field k] (i j : ℕ) : zeroDimensionalFlatIdealRing k :=
  ∏ n ∈ Finset.Ico i j, zeroDimensionalFlatIdealY k n

/-- The finite form of the source's chain identity for the `x_i`. -/
theorem zeroDimensionalFlatIdeal_x_eq_transitionProduct_mul_x
    (k : Type u) [Field k] (i j : ℕ) (hij : i ≤ j) :
    zeroDimensionalFlatIdealX k i =
      zeroDimensionalFlatIdealTransitionProduct k i j *
        zeroDimensionalFlatIdealX k j := by
  refine Nat.le_induction ?_ ?_ j hij
  · simp [zeroDimensionalFlatIdealTransitionProduct]
  · intro n hn ih
    calc
      zeroDimensionalFlatIdealX k i =
          zeroDimensionalFlatIdealTransitionProduct k i n *
            zeroDimensionalFlatIdealX k n := ih
      _ = zeroDimensionalFlatIdealTransitionProduct k i n *
            (zeroDimensionalFlatIdealY k n *
              zeroDimensionalFlatIdealX k (n + 1)) := by
        rw [zeroDimensionalFlatIdeal_x_eq_y_mul_next_x k n]
      _ = zeroDimensionalFlatIdealTransitionProduct k i (n + 1) *
            zeroDimensionalFlatIdealX k (n + 1) := by
        simp only [zeroDimensionalFlatIdealTransitionProduct]
        rw [Finset.prod_Ico_succ_top hn]
        ring

/-! ## The unique prime and the candidate flat ideal -/

/-- The ideal `(x_i, y_i)` proposed in the source as the unique prime ideal. -/
def zeroDimensionalFlatIdealMaximalIdeal (k : Type u) [Field k] :
    Ideal (zeroDimensionalFlatIdealRing k) :=
  Ideal.span
    (Set.range (zeroDimensionalFlatIdealX k) ∪
      Set.range (zeroDimensionalFlatIdealY k))

/-- The ideal `I = (x_i)` from the source. -/
def zeroDimensionalFlatIdeal (k : Type u) [Field k] :
    Ideal (zeroDimensionalFlatIdealRing k) :=
  Ideal.span (Set.range (zeroDimensionalFlatIdealX k))

/-- The proposed maximal ideal is prime. -/
theorem zeroDimensionalFlatIdeal_maximalIdeal_isPrime
    (k : Type u) [Field k] :
    (zeroDimensionalFlatIdealMaximalIdeal k).IsPrime := by
  let J : Ideal (zeroDimensionalFlatIdealPolynomial k) :=
    Ideal.span (MvPolynomial.X '' (Set.univ : Set zeroDimensionalFlatIdealVariables))
  have hJker :
      J = RingHom.ker
        (MvPolynomial.constantCoeff :
          zeroDimensionalFlatIdealPolynomial k →+* k) := by
    ext p
    rw [RingHom.mem_ker, MvPolynomial.mem_ideal_span_X_image]
    constructor
    · intro hp
      rw [MvPolynomial.constantCoeff_eq]
      by_contra h
      have h0 : (0 : zeroDimensionalFlatIdealVariables →₀ ℕ) ∈ p.support := by
        simpa [MvPolynomial.mem_support_iff] using h
      obtain ⟨v, hv, hv0⟩ := hp 0 h0
      exact hv0 (by simp)
    · rw [MvPolynomial.constantCoeff_eq]
      intro hp m hm
      by_contra h
      push Not at h
      have hm0 : m = 0 := Finsupp.ext (fun i => h i (Set.mem_univ _))
      have hm' : MvPolynomial.coeff m p ≠ 0 := by
        simpa [MvPolynomial.mem_support_iff] using hm
      exact hm' (hm0 ▸ hp)
  have hJprime : J.IsPrime := by
    rw [hJker]
    exact RingHom.ker_isPrime _
  have hmem (v : zeroDimensionalFlatIdealVariables) :
      MvPolynomial.X v ∈ J :=
    Ideal.subset_span ⟨v, Set.mem_univ _, rfl⟩
  have hLJ : zeroDimensionalFlatIdealRelationsIdeal k ≤ J := by
    rw [zeroDimensionalFlatIdealRelationsIdeal]
    apply Ideal.span_le.2
    rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
    · simpa [zeroDimensionalFlatIdealRelation] using
        J.sub_mem (hmem _) (J.mul_mem_left _ (hmem _))
    · simpa [zeroDimensionalFlatIdealSquareRelation, pow_two] using
        J.mul_mem_left _ (hmem _)
  let q : zeroDimensionalFlatIdealPolynomial k →+*
      zeroDimensionalFlatIdealRing k :=
    Ideal.Quotient.mk _
  have hmap : Ideal.map q J = zeroDimensionalFlatIdealMaximalIdeal k := by
    apply le_antisymm
    · rw [Ideal.map_le_iff_le_comap]
      apply Ideal.span_le.2
      rintro z ⟨v, -, rfl⟩
      cases v with
      | mk n b =>
        cases b with
        | false =>
          change zeroDimensionalFlatIdealX k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inl ⟨n, rfl⟩)
        | true =>
          change zeroDimensionalFlatIdealY k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inr ⟨n, rfl⟩)
    · rw [zeroDimensionalFlatIdealMaximalIdeal]
      apply Ideal.span_le.2
      rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealXVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (hmem _)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealYVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (hmem _)
  rw [← hmap]
  apply Ideal.map_isPrime_of_surjective (f := q) (I := J) (H := hJprime)
    Ideal.Quotient.mk_surjective
  simpa [q] using hLJ

private theorem zeroDimensionalFlatIdeal_maximalIdeal_isMaximal
    (k : Type u) [Field k] :
    (zeroDimensionalFlatIdealMaximalIdeal k).IsMaximal := by
  let J : Ideal (zeroDimensionalFlatIdealPolynomial k) :=
    Ideal.span (MvPolynomial.X '' (Set.univ : Set zeroDimensionalFlatIdealVariables))
  have hJker :
      J = RingHom.ker
        (MvPolynomial.constantCoeff :
          zeroDimensionalFlatIdealPolynomial k →+* k) := by
    ext p
    rw [RingHom.mem_ker, MvPolynomial.mem_ideal_span_X_image]
    constructor
    · intro hp
      rw [MvPolynomial.constantCoeff_eq]
      by_contra h
      have h0 : (0 : zeroDimensionalFlatIdealVariables →₀ ℕ) ∈ p.support := by
        simpa [MvPolynomial.mem_support_iff] using h
      obtain ⟨v, hv, hv0⟩ := hp 0 h0
      exact hv0 (by simp)
    · rw [MvPolynomial.constantCoeff_eq]
      intro hp m hm
      by_contra h
      push Not at h
      have hm0 : m = 0 := Finsupp.ext (fun i => h i (Set.mem_univ _))
      have hm' : MvPolynomial.coeff m p ≠ 0 := by
        simpa [MvPolynomial.mem_support_iff] using hm
      exact hm' (hm0 ▸ hp)
  have hLJ : zeroDimensionalFlatIdealRelationsIdeal k ≤ J := by
    rw [zeroDimensionalFlatIdealRelationsIdeal]
    apply Ideal.span_le.2
    rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
    · simpa [zeroDimensionalFlatIdealRelation] using
        J.sub_mem (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
          (J.mul_mem_left _ (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩))
    · simpa [zeroDimensionalFlatIdealSquareRelation, pow_two] using
        J.mul_mem_left _ (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
  let q : zeroDimensionalFlatIdealPolynomial k →+*
      zeroDimensionalFlatIdealRing k :=
    Ideal.Quotient.mk _
  let φ : zeroDimensionalFlatIdealRing k →+* k :=
    Ideal.Quotient.lift (zeroDimensionalFlatIdealRelationsIdeal k)
      (MvPolynomial.constantCoeff : zeroDimensionalFlatIdealPolynomial k →+* k) (by
        intro z hz
        have hzJ : z ∈ J := hLJ hz
        rw [hJker] at hzJ
        exact RingHom.mem_ker.mp hzJ)
  have hφsurj : Function.Surjective φ := by
    intro a
    refine ⟨Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k)
      (MvPolynomial.C a), ?_⟩
    simp [φ]
  have hmap : Ideal.map q J = zeroDimensionalFlatIdealMaximalIdeal k := by
    apply le_antisymm
    · rw [Ideal.map_le_iff_le_comap]
      apply Ideal.span_le.2
      rintro z ⟨v, -, rfl⟩
      cases v with
      | mk n b =>
        cases b with
        | false =>
          change zeroDimensionalFlatIdealX k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inl ⟨n, rfl⟩)
        | true =>
          change zeroDimensionalFlatIdealY k n ∈
            zeroDimensionalFlatIdealMaximalIdeal k
          exact Ideal.subset_span (Or.inr ⟨n, rfl⟩)
    · rw [zeroDimensionalFlatIdealMaximalIdeal]
      apply Ideal.span_le.2
      rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealXVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
      · change q (MvPolynomial.X (zeroDimensionalFlatIdealYVar n)) ∈
          Ideal.map q J
        exact Ideal.mem_map_of_mem q (Ideal.subset_span ⟨_, Set.mem_univ _, rfl⟩)
  have hker : RingHom.ker φ = zeroDimensionalFlatIdealMaximalIdeal k := by
    apply le_antisymm
    · intro z hz
      induction z using Quotient.inductionOn' with | _ z =>
        have hz' : MvPolynomial.constantCoeff z = 0 := by
          rw [RingHom.mem_ker] at hz
          change φ (Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k) z) = 0 at hz
          dsimp [φ] at hz
          exact hz
        have hzJ : z ∈ J := by
          rw [hJker, RingHom.mem_ker]
          exact hz'
        have : q z ∈ Ideal.map q J := Ideal.mem_map_of_mem q hzJ
        rw [hmap] at this
        exact this
    · rw [zeroDimensionalFlatIdealMaximalIdeal]
      apply Ideal.span_le.2
      rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
      · change φ (q (MvPolynomial.X (zeroDimensionalFlatIdealXVar n))) = 0
        simp [φ, q]
      · change φ (q (MvPolynomial.X (zeroDimensionalFlatIdealYVar n))) = 0
        simp [φ, q]
  rw [← hker]
  exact RingHom.ker_isMaximal_of_surjective φ hφsurj

/-- Every prime ideal is the displayed ideal `(x_i,y_i)`. -/
theorem zeroDimensionalFlatIdeal_unique_prime
    (k : Type u) [Field k] (p : Ideal (zeroDimensionalFlatIdealRing k))
    (hp : p.IsPrime) :
    p = zeroDimensionalFlatIdealMaximalIdeal k := by
  have hmax : (zeroDimensionalFlatIdealMaximalIdeal k).IsMaximal :=
    zeroDimensionalFlatIdeal_maximalIdeal_isMaximal k
  have hle : zeroDimensionalFlatIdealMaximalIdeal k ≤ p := by
    rw [zeroDimensionalFlatIdealMaximalIdeal]
    apply Ideal.span_le.2
    rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
    · have hyn : zeroDimensionalFlatIdealY k n ∈ p := hp.mem_of_pow_mem 2 (by
        rw [show zeroDimensionalFlatIdealY k n ^ 2 = 0 by
          exact zeroDimensionalFlatIdeal_y_sq_eq_zero k n]
        exact p.zero_mem)
      rw [zeroDimensionalFlatIdeal_x_eq_y_mul_next_x k n]
      simpa [mul_comm] using
        p.mul_mem_left (zeroDimensionalFlatIdealX k (n + 1)) hyn
    · exact hp.mem_of_pow_mem 2 (by
        rw [show zeroDimensionalFlatIdealY k n ^ 2 = 0 by
          exact zeroDimensionalFlatIdeal_y_sq_eq_zero k n]
        exact p.zero_mem)
  simpa only [eq_comm] using hmax.eq_of_le hp.ne_top hle

/-- The quotient ring is zero-dimensional in the Krull-dimension sense. -/
theorem zeroDimensionalFlatIdeal_ring_krullDimLE_zero
    (k : Type u) [Field k] :
    Ring.KrullDimLE 0 (zeroDimensionalFlatIdealRing k) := by
  apply Ring.KrullDimLE.mk₀
  intro p hp
  rw [zeroDimensionalFlatIdeal_unique_prime k p hp]
  exact zeroDimensionalFlatIdeal_maximalIdeal_isMaximal k

/-- A local-ring instance for the constructed quotient. -/
instance zeroDimensionalFlatIdeal_ring_isLocalRing_instance
    (k : Type u) [Field k] : IsLocalRing (zeroDimensionalFlatIdealRing k) := by
  apply IsLocalRing.of_unique_max_ideal
  refine ⟨zeroDimensionalFlatIdealMaximalIdeal k,
    zeroDimensionalFlatIdeal_maximalIdeal_isMaximal k, ?_⟩
  intro I hI
  exact zeroDimensionalFlatIdeal_unique_prime k I hI.isPrime

/-- The local-ring assertion for the constructed quotient. -/
theorem zeroDimensionalFlatIdeal_ring_isLocalRing
    (k : Type u) [Field k] : IsLocalRing (zeroDimensionalFlatIdealRing k) := by
  infer_instance

/-- The source's displayed ideal is below the unique prime ideal. -/
theorem zeroDimensionalFlatIdeal_le_maximalIdeal
    (k : Type u) [Field k] :
    zeroDimensionalFlatIdeal k ≤ zeroDimensionalFlatIdealMaximalIdeal k := by
  rw [zeroDimensionalFlatIdeal, zeroDimensionalFlatIdealMaximalIdeal]
  apply Ideal.span_le.2
  rintro z ⟨n, rfl⟩
  exact Ideal.subset_span (Or.inl ⟨n, rfl⟩)

private abbrev zeroDimensionalFlatIdealTailMonoid := Option (Set ℕ)

private noncomputable instance zeroDimensionalFlatIdealTailDecidableDisjoint
    (a b : Set ℕ) : Decidable (Disjoint a b) := Classical.propDecidable (Disjoint a b)

private noncomputable def zeroDimensionalFlatIdealTailMul
    (a b : zeroDimensionalFlatIdealTailMonoid) :
    zeroDimensionalFlatIdealTailMonoid :=
  by
    classical
    exact match a, b with
    | some a, some b => if Disjoint a b then some (a ∪ b) else none
    | _, _ => none

private theorem zeroDimensionalFlatIdealTailMul_none_left (a :
    zeroDimensionalFlatIdealTailMonoid) :
    zeroDimensionalFlatIdealTailMul none a = none := by
  rfl

private theorem zeroDimensionalFlatIdealTailMul_none_right (a :
    zeroDimensionalFlatIdealTailMonoid) :
    zeroDimensionalFlatIdealTailMul a none = none := by
  cases a <;> rfl

private noncomputable instance :
    CommMonoid zeroDimensionalFlatIdealTailMonoid where
  mul := zeroDimensionalFlatIdealTailMul
  one := some ∅
  mul_assoc := by
    classical
    intro a b c
    change zeroDimensionalFlatIdealTailMul
        (zeroDimensionalFlatIdealTailMul a b) c =
      zeroDimensionalFlatIdealTailMul a
        (zeroDimensionalFlatIdealTailMul b c)
    cases a with
    | none => rfl
    | some a =>
      cases b with
      | none => rfl
      | some b =>
        cases c with
        | none =>
          simp only [zeroDimensionalFlatIdealTailMul_none_right]
        | some c =>
          by_cases hab : Disjoint a b
          · by_cases hbc : Disjoint b c
            · by_cases hac : Disjoint a c
              · have hac' : Disjoint (a ∪ b) c :=
                  Set.disjoint_union_left.2 ⟨hac, hbc⟩
                have hab' : Disjoint a (b ∪ c) :=
                  Set.disjoint_union_right.2 ⟨hab, hac⟩
                simp [zeroDimensionalFlatIdealTailMul, hab, hbc, hac, hac', hab',
                  Set.union_assoc]
              · have hac' : ¬ Disjoint (a ∪ b) c := by
                  intro h
                  exact hac (h.mono_left Set.subset_union_left)
                have hab' : ¬ Disjoint a (b ∪ c) := by
                  intro h
                  exact hac (h.mono_right Set.subset_union_right)
                simp [zeroDimensionalFlatIdealTailMul, hab, hbc, hac, hac', hab']
            · have hbc' : ¬ Disjoint (a ∪ b) c := by
                intro h
                exact hbc (h.mono_left Set.subset_union_right)
              simp [zeroDimensionalFlatIdealTailMul, hab, hbc, hbc']
          · have hab' : ¬ Disjoint a (b ∪ c) := by
              intro h
              exact hab (h.mono_right Set.subset_union_left)
            by_cases hbc : Disjoint b c
            · simp [zeroDimensionalFlatIdealTailMul, hab, hab', hbc]
            · simp [zeroDimensionalFlatIdealTailMul, hab, hab', hbc]
  one_mul := by
    classical
    intro a
    cases a with
    | none => rfl
    | some a =>
      change (if Disjoint (∅ : Set ℕ) a then some ((∅ : Set ℕ) ∪ a) else none) = some a
      simp
  mul_one := by
    classical
    intro a
    cases a with
    | none => rfl
    | some a =>
      change (if Disjoint a (∅ : Set ℕ) then some (a ∪ (∅ : Set ℕ)) else none) = some a
      simp
  mul_comm := by
    classical
    intro a b
    change zeroDimensionalFlatIdealTailMul a b =
      zeroDimensionalFlatIdealTailMul b a
    cases a with
    | none =>
      cases b with
      | none => rfl
      | some b =>
        rw [zeroDimensionalFlatIdealTailMul_none_left,
          zeroDimensionalFlatIdealTailMul_none_right]
    | some a =>
      cases b with
      | none =>
        rw [zeroDimensionalFlatIdealTailMul_none_right,
          zeroDimensionalFlatIdealTailMul_none_left]
      | some b =>
        by_cases h : Disjoint a b
        · have h' : Disjoint b a := h.symm
          simp [zeroDimensionalFlatIdealTailMul, h, h', Set.union_comm]
        · have h' : ¬ Disjoint b a := by
            intro hba
            exact h hba.symm
          simp [zeroDimensionalFlatIdealTailMul, h, h']

private noncomputable def zeroDimensionalFlatIdealTailMul_some_some
    (a b : Set ℕ) :
    (some a : zeroDimensionalFlatIdealTailMonoid) * some b =
      if Disjoint a b then some (a ∪ b) else none := by
  classical
  change zeroDimensionalFlatIdealTailMul (some a) (some b) = _
  rfl

private noncomputable def zeroDimensionalFlatIdealTailMulOp_none_right
    (a : zeroDimensionalFlatIdealTailMonoid) :
      a * (none : zeroDimensionalFlatIdealTailMonoid) =
        (none : zeroDimensionalFlatIdealTailMonoid) := by
  change zeroDimensionalFlatIdealTailMul a none = none
  exact zeroDimensionalFlatIdealTailMul_none_right a

/-- The source's ideal `I` is nonzero. -/
theorem zeroDimensionalFlatIdeal_ne_bot
    (k : Type u) [Field k] : zeroDimensionalFlatIdeal k ≠ ⊥ := by
  intro hI
  classical
  let A := MonoidAlgebra k zeroDimensionalFlatIdealTailMonoid
  let N : Ideal A := Ideal.span
    ({MonoidAlgebra.single none 1} : Set A)
  let Q := A ⧸ N
  let q : A →+* Q := Ideal.Quotient.mk N
  let t : Set ℕ → Q := fun s => q (MonoidAlgebra.single (some s) 1)
  have hmul (a b : Set ℕ) :
      t a * t b = if Disjoint a b then t (a ∪ b) else 0 := by
    by_cases h : Disjoint a b
    · simp only [t]
      rw [← q.map_mul, MonoidAlgebra.single_mul_single]
      rw [if_pos h]
      rw [zeroDimensionalFlatIdealTailMul_some_some]
      rw [if_pos h]
      simp [h]
    · have hzero :
          q (MonoidAlgebra.single none (1 : k)) = 0 := by
        rw [Ideal.Quotient.eq_zero_iff_mem]
        exact Ideal.subset_span (Set.mem_singleton _)
      simp only [t]
      rw [← q.map_mul, MonoidAlgebra.single_mul_single]
      rw [if_neg h]
      rw [zeroDimensionalFlatIdealTailMul_some_some, if_neg h]
      simpa using hzero
  have hdisjoint (n : ℕ) :
      Disjoint ({n} : Set ℕ) (Set.Ici (n + 1)) := by
    rw [Set.disjoint_singleton_left]
    simp only [Set.mem_Ici]
    omega
  have hunion (n : ℕ) :
      ({n} : Set ℕ) ∪ Set.Ici (n + 1) = Set.Ici n := by
    ext m
    simp only [Set.mem_union, Set.mem_singleton_iff, Set.mem_Ici]
    omega
  have hxy (n : ℕ) :
      t ({n} : Set ℕ) * t (Set.Ici (n + 1)) = t (Set.Ici n) := by
    rw [hmul, if_pos (hdisjoint n), hunion]
  have hnotdisjoint (n : ℕ) : ¬ Disjoint ({n} : Set ℕ) ({n} : Set ℕ) := by
    rw [Set.disjoint_singleton]
    simp
  have hyy (n : ℕ) : t ({n} : Set ℕ) ^ 2 = 0 := by
    rw [pow_two, hmul, if_neg (hnotdisjoint n)]
  let c : k →+* Q := (q.comp (algebraMap k A))
  let v : zeroDimensionalFlatIdealVariables → Q := fun z =>
    match z with
    | (n, false) => t (Set.Ici n)
    | (n, true) => t {n}
  let φ : zeroDimensionalFlatIdealPolynomial k →+* Q :=
    MvPolynomial.eval₂Hom c v
  have hrel (n : ℕ) :
      φ (zeroDimensionalFlatIdealRelation k n) = 0 := by
    simp [φ, zeroDimensionalFlatIdealRelation, zeroDimensionalFlatIdealXVar,
      zeroDimensionalFlatIdealYVar, v, hxy]
  have hsq (n : ℕ) :
      φ (zeroDimensionalFlatIdealSquareRelation k n) = 0 := by
    simp [φ, zeroDimensionalFlatIdealSquareRelation, zeroDimensionalFlatIdealYVar,
      v, hyy]
  have hker : zeroDimensionalFlatIdealRelationsIdeal k ≤ RingHom.ker φ := by
    rw [zeroDimensionalFlatIdealRelationsIdeal]
    apply Ideal.span_le.2
    rintro z (⟨n, rfl⟩ | ⟨n, rfl⟩)
    · exact hrel n
    · exact hsq n
  have hker' : ∀ a, a ∈ zeroDimensionalFlatIdealRelationsIdeal k → φ a = 0 := by
    intro a ha
    exact RingHom.mem_ker.mp (hker ha)
  let ψ : zeroDimensionalFlatIdealRing k →+* Q :=
    Ideal.Quotient.lift (zeroDimensionalFlatIdealRelationsIdeal k) φ hker'
  have hprop : ∀ p : A, p ∈ N →
      ∀ s : zeroDimensionalFlatIdealTailMonoid, s ≠ none → p.coeff s = 0 := by
    intro p hp
    change p ∈ Ideal.span ({MonoidAlgebra.single none 1} : Set A) at hp
    induction hp using Submodule.span_induction with
    | mem p hp =>
        intro s hs
        rw [Set.mem_singleton_iff] at hp
        subst p
        simp [hs]
    | zero =>
        intro s hs
        simp
    | add p q hp hq hp' hq' =>
        intro s hs
        rw [MonoidAlgebra.coeff_add]
        simp [hp' s hs, hq' s hs]
    | smul r p hp hp' =>
        intro s hs
        classical
        rw [smul_eq_mul]
        rw [MonoidAlgebra.coeff_mul]
        rw [Finsupp.sum]
        apply Finset.sum_eq_zero
        intro m₁ hm₁
        rw [Finsupp.sum]
        apply Finset.sum_eq_zero
        intro m₂ hm₂
        by_cases hm₂none : m₂ = none
        · subst m₂
          have hprod : m₁ * (none : zeroDimensionalFlatIdealTailMonoid) ≠ s := by
            rw [zeroDimensionalFlatIdealTailMulOp_none_right]
            exact Ne.symm hs
          rw [if_neg hprod]
        · simp [hp' m₂ hm₂none]
  have hq_nonzero (s : Set ℕ) :
      q (MonoidAlgebra.single (some s) 1) ≠ 0 := by
    intro hzero
    have hm : MonoidAlgebra.single (some s) (1 : k) ∈ N := by
      rw [← Ideal.Quotient.eq_zero_iff_mem]
      exact hzero
    have hc := hprop _ hm (some s) (by simp)
    simpa using hc
  have hxzero : zeroDimensionalFlatIdealX k 0 = 0 := by
    have hxmem : zeroDimensionalFlatIdealX k 0 ∈ (⊥ : Ideal (zeroDimensionalFlatIdealRing k)) := by
      rw [← hI]
      exact Ideal.subset_span (Set.mem_range_self 0)
    exact hxmem
  have hψx : ψ (zeroDimensionalFlatIdealX k 0) =
      q (MonoidAlgebra.single (some (Set.Ici 0)) 1) := by
    change ψ (Ideal.Quotient.mk (zeroDimensionalFlatIdealRelationsIdeal k)
      (MvPolynomial.X (zeroDimensionalFlatIdealXVar 0))) = _
    dsimp [ψ]
    change (MvPolynomial.eval₂Hom c v)
        (MvPolynomial.X (zeroDimensionalFlatIdealXVar 0)) = _
    rw [MvPolynomial.eval₂Hom_X']
    simp [v, t, zeroDimensionalFlatIdealXVar]
  exact hq_nonzero (Set.Ici 0) (by
    rw [← hψx, hxzero, map_zero])

/-! ## The annihilator computation for `x_i` -/

/-- The ideal generated by all `x_j` and by `y_j` for `j ≥ i`. -/
def zeroDimensionalFlatIdealXAnnihilatorCandidate
    (k : Type u) [Field k] (i : ℕ) : Ideal (zeroDimensionalFlatIdealRing k) :=
  Ideal.span
    (Set.range (zeroDimensionalFlatIdealX k) ∪
      Set.range (fun j : {j : ℕ // i ≤ j} => zeroDimensionalFlatIdealY k j.1))

/-- The annihilator of `x_i` is the ideal displayed in the source. -/
theorem zeroDimensionalFlatIdeal_x_annihilator
    (k : Type u) [Field k] (i : ℕ) :
    (Submodule.span (zeroDimensionalFlatIdealRing k)
        ({zeroDimensionalFlatIdealX k i} : Set (zeroDimensionalFlatIdealRing k))).annihilator =
      zeroDimensionalFlatIdealXAnnihilatorCandidate k i := by
  apply le_antisymm
  · sorry
  · rw [zeroDimensionalFlatIdealXAnnihilatorCandidate]
    apply Ideal.span_le.2
    rintro z (⟨j, rfl⟩ | ⟨j, rfl⟩)
    · change zeroDimensionalFlatIdealX k j ∈
        (Submodule.span (zeroDimensionalFlatIdealRing k)
          ({zeroDimensionalFlatIdealX k i} : Set (zeroDimensionalFlatIdealRing k))).annihilator
      rw [Submodule.mem_annihilator_span_singleton]
      change zeroDimensionalFlatIdealX k j * zeroDimensionalFlatIdealX k i = 0
      have hxx (n : ℕ) : zeroDimensionalFlatIdealX k n *
          zeroDimensionalFlatIdealX k n = 0 := by
        calc
          zeroDimensionalFlatIdealX k n * zeroDimensionalFlatIdealX k n =
              (zeroDimensionalFlatIdealY k n *
                zeroDimensionalFlatIdealX k (n + 1)) *
                (zeroDimensionalFlatIdealY k n *
                  zeroDimensionalFlatIdealX k (n + 1)) := by
                    rw [← zeroDimensionalFlatIdeal_x_eq_y_mul_next_x k n]
          _ = zeroDimensionalFlatIdealY k n ^ 2 *
                (zeroDimensionalFlatIdealX k (n + 1) ^ 2) := by ring
          _ = 0 := by simp
      rcases le_total j i with hji | hij
      · rw [zeroDimensionalFlatIdeal_x_eq_transitionProduct_mul_x k j i hji]
        rw [show zeroDimensionalFlatIdealTransitionProduct k j i *
            zeroDimensionalFlatIdealX k i * zeroDimensionalFlatIdealX k i =
            zeroDimensionalFlatIdealTransitionProduct k j i *
              (zeroDimensionalFlatIdealX k i * zeroDimensionalFlatIdealX k i) by ring]
        rw [hxx i, mul_zero]
      · rw [zeroDimensionalFlatIdeal_x_eq_transitionProduct_mul_x k i j hij]
        rw [show zeroDimensionalFlatIdealX k j *
            (zeroDimensionalFlatIdealTransitionProduct k i j *
              zeroDimensionalFlatIdealX k j) =
            (zeroDimensionalFlatIdealX k j * zeroDimensionalFlatIdealX k j) *
              zeroDimensionalFlatIdealTransitionProduct k i j by ring]
        rw [hxx j, zero_mul]
    · change zeroDimensionalFlatIdealY k j.1 ∈
        (Submodule.span (zeroDimensionalFlatIdealRing k)
          ({zeroDimensionalFlatIdealX k i} : Set (zeroDimensionalFlatIdealRing k))).annihilator
      rw [Submodule.mem_annihilator_span_singleton]
      change zeroDimensionalFlatIdealY k j.1 * zeroDimensionalFlatIdealX k i = 0
      have hyx (n : ℕ) : zeroDimensionalFlatIdealY k n *
          zeroDimensionalFlatIdealX k n = 0 := by
        calc
          zeroDimensionalFlatIdealY k n * zeroDimensionalFlatIdealX k n =
              zeroDimensionalFlatIdealY k n *
                (zeroDimensionalFlatIdealY k n *
                  zeroDimensionalFlatIdealX k (n + 1)) := by
                    rw [zeroDimensionalFlatIdeal_x_eq_y_mul_next_x k n]
          _ = zeroDimensionalFlatIdealY k n ^ 2 *
                zeroDimensionalFlatIdealX k (n + 1) := by ring
          _ = 0 := by simp
      rw [zeroDimensionalFlatIdeal_x_eq_transitionProduct_mul_x k i j.1 j.2]
      rw [show zeroDimensionalFlatIdealY k j.1 *
          (zeroDimensionalFlatIdealTransitionProduct k i j.1 *
            zeroDimensionalFlatIdealX k j.1) =
          zeroDimensionalFlatIdealTransitionProduct k i j.1 *
            (zeroDimensionalFlatIdealY k j.1 *
              zeroDimensionalFlatIdealX k j.1) by ring]
      rw [hyx, mul_zero]

/-! ## The flat direct-limit module -/

/-- The `R`-linear transition map from stage `i` to stage `j`, multiplying by
`y_i ··· y_(j-1)`. -/
def zeroDimensionalFlatIdealTransitionMap
    (k : Type u) [Field k] (i j : ℕ) (_hij : i ≤ j) :
    zeroDimensionalFlatIdealRing k →ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdealRing k :=
  LinearMap.mulRight (zeroDimensionalFlatIdealRing k)
    (zeroDimensionalFlatIdealTransitionProduct k i j)

/-- The adjacent transition is multiplication by `y_i`, as in the source. -/
theorem zeroDimensionalFlatIdeal_transitionMap_succ
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealTransitionMap k i (i + 1) (Nat.le_succ i) =
      LinearMap.mulRight (zeroDimensionalFlatIdealRing k)
        (zeroDimensionalFlatIdealY k i) := by
  apply LinearMap.ext
  intro f
  change f * (∏ n ∈ Finset.Ico i (i + 1), zeroDimensionalFlatIdealY k n) =
    f * zeroDimensionalFlatIdealY k i
  rw [Finset.prod_Ico_succ_top (Nat.le_refl i)]
  simp

/-- The source module `M`, represented by Mathlib's module direct limit. -/
abbrev zeroDimensionalFlatIdealModule (k : Type u) [Field k] :=
  Module.DirectLimit
    (R := zeroDimensionalFlatIdealRing k) (ι := ℕ)
    (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
    (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h)

/-- The generator `e_i` coming from the unit of the `i`-th copy of `R`. -/
def zeroDimensionalFlatIdealModuleGenerator
    (k : Type u) [Field k] (i : ℕ) : zeroDimensionalFlatIdealModule k :=
  Module.DirectLimit.of (zeroDimensionalFlatIdealRing k) ℕ
    (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
    (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h) i 1

/-- The defining relation `e_i = y_i e_(i+1)`. -/
theorem zeroDimensionalFlatIdeal_moduleGenerator_relation
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealModuleGenerator k i =
      zeroDimensionalFlatIdealY k i •
        zeroDimensionalFlatIdealModuleGenerator k (i + 1) := by
  change Module.DirectLimit.of (zeroDimensionalFlatIdealRing k) ℕ
      (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
      (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h) i 1 =
    zeroDimensionalFlatIdealY k i •
      Module.DirectLimit.of (zeroDimensionalFlatIdealRing k) ℕ
        (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
        (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h) (i + 1) 1
  rw [← Module.DirectLimit.of_f (R := zeroDimensionalFlatIdealRing k)
      (ι := ℕ) (G := fun _ : ℕ => zeroDimensionalFlatIdealRing k)
      (f := fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h)
      (i := i) (j := i + 1) (hij := Nat.le_succ i) (x := 1)]
  have htransition :
      zeroDimensionalFlatIdealTransitionMap k i (i + 1) (Nat.le_succ i) 1 =
        zeroDimensionalFlatIdealY k i • (1 : zeroDimensionalFlatIdealRing k) := by
    simp [zeroDimensionalFlatIdealTransitionMap, zeroDimensionalFlatIdealTransitionProduct]
  rw [htransition, map_smul]

/-- Every element of `M` is represented by a scalar times one displayed
generator. -/
theorem zeroDimensionalFlatIdeal_module_element_representation
    (k : Type u) [Field k] (m : zeroDimensionalFlatIdealModule k) :
    ∃ (i : ℕ) (f : zeroDimensionalFlatIdealRing k),
      m = f • zeroDimensionalFlatIdealModuleGenerator k i := by
  sorry

/-- The module direct limit is flat over the quotient ring. -/
theorem zeroDimensionalFlatIdeal_module_flat
    (k : Type u) [Field k] :
    Module.Flat (zeroDimensionalFlatIdealRing k)
      (zeroDimensionalFlatIdealModule k) := by
  sorry

/-! ## The map from the direct limit to `I` -/

/-- The copy of `x_i` as an element of the ideal `I`. -/
def zeroDimensionalFlatIdealGenerator
    (k : Type u) [Field k] (i : ℕ) : zeroDimensionalFlatIdeal k :=
  ⟨zeroDimensionalFlatIdealX k i,
    Ideal.subset_span (Set.mem_range_self i)⟩

/-- Every element of `I` is represented by a scalar times one displayed
ideal generator. -/
theorem zeroDimensionalFlatIdeal_element_representation
    (k : Type u) [Field k] (a : zeroDimensionalFlatIdeal k) :
    ∃ (i : ℕ) (h : zeroDimensionalFlatIdealRing k),
      a = h • zeroDimensionalFlatIdealGenerator k i := by
  sorry

/-- The map from the `i`-th copy of `R` to `I`, sending `f` to `f x_i`. -/
def zeroDimensionalFlatIdealModuleStageMap
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealRing k →ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdeal k :=
  (LinearMap.mulRight (zeroDimensionalFlatIdealRing k)
      (zeroDimensionalFlatIdealX k i)).codRestrict
    (zeroDimensionalFlatIdeal k)
    (fun f =>
      Ideal.mul_mem_left (zeroDimensionalFlatIdeal k) f
        (Ideal.subset_span (Set.mem_range_self i)))

/-- The stage maps respect the direct-system transition maps. -/
theorem zeroDimensionalFlatIdealModuleStageMap_compatibility
    (k : Type u) [Field k] (i j : ℕ) (hij : i ≤ j)
    (f : zeroDimensionalFlatIdealRing k) :
    zeroDimensionalFlatIdealModuleStageMap k j
        (zeroDimensionalFlatIdealTransitionMap k i j hij f) =
      zeroDimensionalFlatIdealModuleStageMap k i f := by
  sorry

/-- The canonical map `M → I` whose value on `e_i` is `x_i`. -/
noncomputable def zeroDimensionalFlatIdealModuleToIdeal
    (k : Type u) [Field k] :
    zeroDimensionalFlatIdealModule k →ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdeal k :=
  Module.DirectLimit.lift (zeroDimensionalFlatIdealRing k) ℕ
    (fun _ : ℕ => zeroDimensionalFlatIdealRing k)
    (fun i j h => zeroDimensionalFlatIdealTransitionMap k i j h)
    (fun i => zeroDimensionalFlatIdealModuleStageMap k i)
    (fun i j h f => zeroDimensionalFlatIdealModuleStageMap_compatibility k i j h f)

@[simp]
theorem zeroDimensionalFlatIdealModuleToIdeal_generator
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealModuleToIdeal k
        (zeroDimensionalFlatIdealModuleGenerator k i) =
      zeroDimensionalFlatIdealGenerator k i := by
  sorry

/-- The canonical map from the direct limit to `I` is bijective. -/
theorem zeroDimensionalFlatIdealModuleToIdeal_bijective
    (k : Type u) [Field k] :
    Function.Bijective (zeroDimensionalFlatIdealModuleToIdeal k) := by
  sorry

/-- The source's isomorphism `M ≅ I`, made available as a linear equivalence. -/
noncomputable def zeroDimensionalFlatIdealModuleToIdealEquiv
    (k : Type u) [Field k] :
    zeroDimensionalFlatIdealModule k ≃ₗ[zeroDimensionalFlatIdealRing k]
      zeroDimensionalFlatIdeal k :=
  LinearEquiv.ofBijective (zeroDimensionalFlatIdealModuleToIdeal k)
    (zeroDimensionalFlatIdealModuleToIdeal_bijective k)

theorem zeroDimensionalFlatIdealModuleToIdealEquiv_generator
    (k : Type u) [Field k] (i : ℕ) :
    zeroDimensionalFlatIdealModuleToIdealEquiv k
        (zeroDimensionalFlatIdealModuleGenerator k i) =
      zeroDimensionalFlatIdealGenerator k i := by
  sorry

/-- The ideal `I` is flat over the constructed ring. -/
theorem zeroDimensionalFlatIdeal_flat
    (k : Type u) [Field k] :
    Module.Flat (zeroDimensionalFlatIdealRing k) (zeroDimensionalFlatIdeal k) := by
  sorry

/-! ## The annihilator computation for `e_i` and the final example -/

/-- The annihilator of `e_i` is the same displayed ideal as the annihilator of
`x_i`. -/
theorem zeroDimensionalFlatIdeal_moduleGenerator_annihilator
    (k : Type u) [Field k] (i : ℕ) :
    (Submodule.span (zeroDimensionalFlatIdealRing k)
        ({zeroDimensionalFlatIdealModuleGenerator k i} :
          Set (zeroDimensionalFlatIdealModule k))).annihilator =
      zeroDimensionalFlatIdealXAnnihilatorCandidate k i := by
  sorry

/-- The source's final existence statement. -/
theorem exists_local_ring_unique_prime_nonzero_flat_ideal :
    ∃ (R : Type) (_ : CommRing R) (_ : IsLocalRing R)
      (m I : Ideal R),
      m.IsPrime ∧
        (∀ p : Ideal R, p.IsPrime → p = m) ∧
        I ≠ ⊥ ∧ Module.Flat R I := by
  refine ⟨zeroDimensionalFlatIdealRing ℚ, inferInstance,
    zeroDimensionalFlatIdeal_ring_isLocalRing ℚ,
    zeroDimensionalFlatIdealMaximalIdeal ℚ, zeroDimensionalFlatIdeal ℚ, ?_, ?_, ?_, ?_⟩
  · exact zeroDimensionalFlatIdeal_maximalIdeal_isPrime ℚ
  · intro p hp
    exact zeroDimensionalFlatIdeal_unique_prime ℚ p hp
  · exact zeroDimensionalFlatIdeal_ne_bot ℚ
  · exact zeroDimensionalFlatIdeal_flat ℚ

end Formalization.Books.Examples.Unit35
