import Mathlib.Data.Nat.Prime.Basic
import Mathlib.RingTheory.Spectrum.Prime.Topology
import Mathlib.Topology.Separation.Hausdorff

/-!
# Exercises, Chapter 6: The Spectrum of a ring

This file records the spectrum-of-`ℤ`, Zariski-basis, closed-set, compactness,
and separation exercises.  The source's `D(f)`, `V(I)`, quasi-compactness,
`T₀`, and Hausdorff notions are represented by Mathlib's canonical spectrum
and topology APIs.
-/

noncomputable section

universe u

open Set Topology

namespace Formalization.Books.Exercises.Unit06

/-! ## `Spec(ℤ)` -/

/-- The generic point of the spectrum of the integers. -/
def integerGenericPoint : PrimeSpectrum ℤ :=
  ⟨⊥, by infer_instance⟩

/-- Every prime of `ℤ` is the zero ideal or is generated by a rational prime. -/
theorem integer_spectrum_prime_ideals :
    ∀ p : PrimeSpectrum ℤ,
      p = integerGenericPoint ∨
        ∃ q : Nat.Primes, p.asIdeal = Ideal.span {(q.1 : ℤ)} := by
  sorry

/-- The closed subsets of `Spec(ℤ)` are the whole space and finite sets of
closed points. -/
theorem integer_spectrum_closed_sets (Z : Set (PrimeSpectrum ℤ)) :
    IsClosed Z ↔
      Z = Set.univ ∨ (Z.Finite ∧ integerGenericPoint ∉ Z) := by
  sorry

/-! ## Standard opens, radical ideals, and compactness -/

/-- The standard opens `D(f)` form the Zariski basis of an affine spectrum. -/
theorem standard_opens_form_basis {A : Type u} [CommRing A] :
    TopologicalSpace.IsTopologicalBasis
      (Set.range fun f : A => (PrimeSpectrum.basicOpen f : Set (PrimeSpectrum A))) := by
  exact PrimeSpectrum.isTopologicalBasis_basic_opens

/-- The map from radical ideals to their vanishing sets is a bijection onto
the closed subsets of the spectrum. -/
theorem radical_ideal_closed_bijection {A : Type u} [CommRing A] :
    Function.Bijective
      (fun I : {I : Ideal A // I.IsRadical} =>
        (⟨PrimeSpectrum.zeroLocus (I.1 : Set A),
          PrimeSpectrum.isClosed_zeroLocus (I.1 : Set A)⟩ :
          {Z : Set (PrimeSpectrum A) // IsClosed Z})) := by
  sorry

/-- `Spec(A)` is quasi-compact, with quasi-compactness expressed by
`IsCompact` of the whole space. -/
theorem spectrum_is_quasi_compact {A : Type u} [CommRing A] :
    IsCompact (Set.univ : Set (PrimeSpectrum A)) := by
  exact isCompact_univ

/-! ## Separation -/

/-- The spectrum of the integers supplies a concrete non-Hausdorff spectrum. -/
theorem integer_spectrum_not_hausdorff :
    ¬ T2Space (PrimeSpectrum ℤ) := by
  sorry

/-- Every affine spectrum is `T₀`. -/
theorem spectrum_is_t0 {A : Type u} [CommRing A] :
    T0Space (PrimeSpectrum A) := by
  infer_instance

/-- The two-point indiscrete space is a concrete space which is not `T₀`.
The topology is supplied explicitly so this theorem does not install a
global alternative topology on `Bool`. -/
theorem indiscrete_bool_not_t0 :
    ¬ @T0Space Bool (⊥ : TopologicalSpace Bool) := by
  sorry

end Formalization.Books.Exercises.Unit06
