import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Noetherian.Basic
import Formalization.Books.Algebra.Unit03.BasicNotions
import Formalization.Books.Algebra.Unit137.SmoothRingMaps

/-!
# Smoothing Ring Maps, Chapter 6: The lifting lemma

The chapter's proof is presentation based.  The explicit polynomial
construction below records the auxiliary choices and the equations used in
the proof, while the final theorem uses the intrinsic finite-presentation and
smoothness interfaces from the preceding algebra chapters.
-/

namespace Formalization.Books.Smoothing.Unit06

open Set
open Formalization.Books.Algebra.Unit03
open scoped BigOperators

noncomputable section

universe u

/-! ## Quotients by a principal element -/

/-- The quotient by the principal ideal generated by an element. -/
abbrev piQuotient (A : Type u) [CommRing A] (a : A) : Type u :=
  A ⧸ Ideal.span ({a} : Set A)

/-- The quotient map onto `A / aA`. -/
def piQuotientMk {A : Type u} [CommRing A] (a : A) : A →+* piQuotient A a :=
  Ideal.Quotient.mk _

/-- The canonical reduction map `A / a²A → A / aA`. -/
def piSquaredToPi {A : Type u} [CommRing A] (a : A) :
    piQuotient A (a ^ 2) →+* piQuotient A a :=
  Ideal.quotientMap (Ideal.span ({a} : Set A)) (RingHom.id A) (by
    apply Ideal.span_le.2
    intro x hx
    rcases Set.mem_singleton_iff.mp hx with rfl
    exact Ideal.mem_span_singleton'.2 ⟨a, by simp [pow_two]⟩)

/-- The ring map to an algebra which factors through a quotient of the base. -/
def quotientAlgebraMap
    {R A : Type u} [CommRing R] [CommRing A]
    (I : Ideal R) [Algebra (R ⧸ I) A] : R →+* A :=
  (algebraMap (R ⧸ I) A).comp (Ideal.Quotient.mk I)

/-! ## The polynomial data in the proof -/

/-- The polynomial ring containing the `x` and `z` variables of the proof. -/
abbrev liftingPolynomial (R : Type u) [CommRing R] (n m : ℕ) : Type u :=
  MvPolynomial (Fin n ⊕ Fin m) R

/-- Inclusion of the `x`-polynomial ring into the ring with `x` and `z`. -/
def liftLiftingPolynomial
    {R : Type u} [CommRing R] {n m : ℕ}
    (f : MvPolynomial (Fin n) R) : liftingPolynomial R n m :=
  MvPolynomial.rename Sum.inl f

/-- The lifted relation `f_ℓ - π z_ℓ`. -/
def liftingBaseRelation
    {R : Type u} [CommRing R] {n m : ℕ} (π : R)
    (f : Fin m → MvPolynomial (Fin n) R) (ℓ : Fin m) :
    liftingPolynomial R n m :=
  liftLiftingPolynomial (f ℓ) -
    MvPolynomial.C π * MvPolynomial.X (Sum.inr ℓ)

/-- The correction relation `p_{k,ℓ}` from the proof. -/
def liftingCorrectionRelation
    {R : Type u} [CommRing R] {n m r : ℕ} {e : Fin r → ℕ}
    (π : R) (a : Fin r → MvPolynomial (Fin n) R)
    (h : ∀ k : Fin r, Fin m → Fin (e k) → MvPolynomial (Fin n) R)
    (g : ∀ _k : Fin r, Fin m → MvPolynomial (Fin n) R)
    (E : ∀ k : Fin r, Fin (e k) ↪ Fin m) (k : Fin r) (ℓ : Fin m) :
    liftingPolynomial R n m :=
  liftLiftingPolynomial (a k) * MvPolynomial.X (Sum.inr ℓ) -
      ∑ j : Fin (e k),
        liftLiftingPolynomial (h k ℓ j) *
          MvPolynomial.X (Sum.inr (E k j)) -
    MvPolynomial.C π * liftLiftingPolynomial (g k ℓ)

/-- The finite presentation and coefficient data used to construct `D`. -/
structure LiftingConstructionData (R : Type u) [CommRing R] (π : R) where
  n : ℕ
  m : ℕ
  r : ℕ
  e : Fin r → ℕ
  relations : Fin m → MvPolynomial (Fin n) R
  selected : ∀ k : Fin r, Fin (e k) ↪ Fin m
  a : Fin r → MvPolynomial (Fin n) R
  h : ∀ k : Fin r, Fin m → Fin (e k) → MvPolynomial (Fin n) R
  g : ∀ _k : Fin r, Fin m → MvPolynomial (Fin n) R
  relation_identity :
    ∀ k : Fin r, ∀ ℓ : Fin m,
      a k * relations ℓ =
        (∑ j : Fin (e k), h k ℓ j * relations (selected k j)) +
          MvPolynomial.C (π ^ 2) * g k ℓ
  selected_h :
    ∀ k : Fin r, ∀ j : Fin (e k), ∀ j' : Fin (e k),
      h k (selected k j) j' = if j' = j then a k else 0
  selected_g : ∀ k : Fin r, ∀ j : Fin (e k), g k (selected k j) = 0

/-- The ideal `I = (f_1, ..., f_m)` in the polynomial presentation. -/
def liftingRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Ideal (MvPolynomial (Fin d.n) R) :=
  Ideal.span (Set.range d.relations)

/-- The ideal `I_k = (f_j : j ∈ E_k)` used at a smooth basic open. -/
def liftingSelectedRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (MvPolynomial (Fin d.n) R) :=
  Ideal.span (Set.range (fun j : Fin (d.e k) => d.relations (d.selected k j)))

/-- The image `\bar I` of the presentation ideal modulo `π²`. -/
def liftingReducedRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Ideal (MvPolynomial (Fin d.n) (piQuotient R (π ^ 2))) :=
  Ideal.map
    (MvPolynomial.map (piQuotientMk (π ^ 2)) :
      MvPolynomial (Fin d.n) R →+*
        MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)))
    (liftingRelationIdeal d)

/-- The image `\bar I_k` of the selected relation ideal modulo `π²`. -/
def liftingReducedSelectedRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (MvPolynomial (Fin d.n) (piQuotient R (π ^ 2))) :=
  Ideal.map
    (MvPolynomial.map (piQuotientMk (π ^ 2)) :
      MvPolynomial (Fin d.n) R →+*
        MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)))
    (liftingSelectedRelationIdeal d k)

/-- The defining ideal of the ring `D` in the proof. -/
def liftingDefiningIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Ideal (liftingPolynomial R d.n d.m) :=
  Ideal.span
    (Set.range (fun ℓ : Fin d.m => liftingBaseRelation π d.relations ℓ) ∪
      ⋃ k : Fin d.r, Set.range (fun ℓ : Fin d.m =>
        liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ))

/-- The ring `D` constructed in the proof. -/
abbrev liftingRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Type u :=
  liftingPolynomial R d.n d.m ⧸ liftingDefiningIdeal d

/-- The image in `D` of a polynomial in the `x` variables. -/
def liftingElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π)
    (f : MvPolynomial (Fin d.n) R) : liftingRing d :=
  Ideal.Quotient.mk _ (liftLiftingPolynomial f)

/-- The auxiliary ring `D_k`, where only the selected `f_j - π z_j` are used. -/
def liftingAuxiliaryDefiningIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (liftingPolynomial R d.n d.m) :=
  Ideal.span
    (Set.range (fun j : Fin (d.e k) =>
        liftingBaseRelation π d.relations (d.selected k j)) ∪
      Set.range (fun ℓ : Fin d.m =>
        liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ))

/-- The auxiliary ring `D_k` used in the local smoothness argument. -/
abbrev liftingAuxiliaryRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) : Type u :=
  liftingPolynomial R d.n d.m ⧸ liftingAuxiliaryDefiningIdeal d k

/-- The image of `a_k` in `D_k`. -/
def liftingAuxiliaryElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) : liftingAuxiliaryRing d k :=
  Ideal.Quotient.mk _ (liftLiftingPolynomial (d.a k))

/-- The quotient map `D_k → D` supplied by inclusion of defining ideals. -/
noncomputable def liftingAuxiliaryToLiftingRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
  liftingAuxiliaryRing d k →+* liftingRing d :=
  Ideal.Quotient.factor (show
    liftingAuxiliaryDefiningIdeal d k ≤ liftingDefiningIdeal d from by
      apply Ideal.span_le.2
      intro x hx
      rcases hx with hx | hx
      · rcases hx with ⟨j, rfl⟩
        exact Ideal.subset_span (Or.inl ⟨d.selected k j, rfl⟩)
      · rcases hx with ⟨ℓ, rfl⟩
        exact Ideal.subset_span
          (Or.inr (Set.mem_iUnion.2 ⟨k, ⟨ℓ, rfl⟩⟩)))

/-! ## Identities and local calculations in the construction -/

/-- The chosen relations in `E_k` give zero correction equations. -/
theorem liftingCorrectionRelation_selected
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) (j : Fin (d.e k)) :
    liftingCorrectionRelation π d.a d.h d.g d.selected k (d.selected k j) = 0 := by
  sorry

/-- The key equality expressing `π p_{k,ℓ}` in the base relations. -/
theorem liftingKeyIdentity
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) (ℓ : Fin d.m) :
    MvPolynomial.C π *
        liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ =
      -liftLiftingPolynomial (d.a k) *
          liftingBaseRelation π d.relations ℓ +
        ∑ j : Fin (d.e k),
          liftLiftingPolynomial (d.h k ℓ j) *
            liftingBaseRelation π d.relations (d.selected k j) := by
  sorry

/-- The polynomial presentation model for `\bar C`. -/
abbrev liftingPresentationModel
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Type u :=
  MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)) ⧸
    liftingReducedRelationIdeal d


noncomputable instance liftingPresentationModel.algebraR
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Algebra R (liftingPresentationModel d) :=
  Algebra.compHom (liftingPresentationModel d) (piQuotientMk (π ^ 2))

/-- The image of `a_k` in the presentation model of `\bar C`. -/
def liftingPresentationElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    liftingPresentationModel d :=
  Ideal.Quotient.mk _
    ((MvPolynomial.map (piQuotientMk (π ^ 2)) :
      MvPolynomial (Fin d.n) R →+*
        MvPolynomial (Fin d.n) (piQuotient R (π ^ 2))) (d.a k))

/-- The base map from `R` to the presentation model. -/
def liftingPresentationModelMap
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : R →+* liftingPresentationModel d :=
  (algebraMap (piQuotient R (π ^ 2)) (liftingPresentationModel d)).comp
    (piQuotientMk (π ^ 2))

def liftingPresentationModPiIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Ideal (liftingPresentationModel d) :=
  Ideal.map (liftingPresentationModelMap d) (Ideal.span ({π} : Set R))

/-- The mod-`π` presentation model for `\bar C / π\bar C`. -/
abbrev liftingPresentationModPiModel
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Type u :=
  liftingPresentationModel d ⧸
    liftingPresentationModPiIdeal d

/-- The image of `a_k` in the mod-`π` presentation model. -/
def liftingPresentationModPiElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
  liftingPresentationModPiModel d :=
  Ideal.Quotient.mk (liftingPresentationModPiIdeal d) (liftingPresentationElement d k)

def liftingAuxiliaryModPiIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (liftingAuxiliaryRing d k) :=
  Ideal.map (algebraMap R (liftingAuxiliaryRing d k))
    (Ideal.span ({π} : Set R))

/-- The mod-`π` auxiliary ring `D_k / π D_k`. -/
abbrev liftingAuxiliaryModPiRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) : Type u :=
  liftingAuxiliaryRing d k ⧸
    liftingAuxiliaryModPiIdeal d k

/-- The image of `a_k` in `D_k / π D_k`. -/
def liftingAuxiliaryModPiElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
  liftingAuxiliaryModPiRing d k :=
  (Ideal.Quotient.mk (liftingAuxiliaryModPiIdeal d k))
    (Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k)
      (liftLiftingPolynomial (d.a k)))

/-- The localized polynomial calculation for the auxiliary ring. -/
theorem liftingAuxiliary_modPi_localized_equiv
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Nonempty
      (Localization.Away (liftingAuxiliaryModPiElement d k) ≃+*
        MvPolynomial (Fin (d.e k))
          (Localization.Away (liftingPresentationModPiElement d k))) := by
  sorry

/-- The localized mod-`π` auxiliary ring is smooth over the presentation model. -/
theorem liftingAuxiliary_modPi_localized_smooth
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Algebra.Smooth (Localization.Away (liftingPresentationModPiElement d k))
      (MvPolynomial (Fin (d.e k))
        (Localization.Away (liftingPresentationModPiElement d k))) := by
  sorry

/-- The finite-presentation assertion for the explicit ring `D`. -/
theorem liftingRing_finitePresentation
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Algebra.FinitePresentation R (liftingRing d) := by
  sorry

/-- Inverting `π` identifies `D` with a polynomial algebra over `R[1/π]`. -/
theorem liftingRing_localization_smooth
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Algebra.Smooth R
      (Localization.Away (algebraMap R (liftingRing d) π)) := by
  sorry

/-- The source's property (b) for the explicit construction. -/
theorem liftingRing_smoothAt_of_pi_not_mem
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (q : PrimeSpectrum (liftingRing d))
    (hq : algebraMap R (liftingRing d) π ∉ q.asIdeal) :
    Formalization.Books.Algebra.Unit137.IsSmoothAt R (liftingRing d) q := by
  sorry

/-- The source's local smoothness conclusion for the auxiliary ring. -/
theorem liftingAuxiliaryRing_smoothAt_of_good_prime
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r)
    (q : PrimeSpectrum (liftingAuxiliaryRing d k))
    (hπ : algebraMap R (liftingAuxiliaryRing d k) π ∈ q.asIdeal)
    (ha : liftingAuxiliaryElement d k ∉ q.asIdeal) :
    Formalization.Books.Algebra.Unit137.IsSmoothAt R
      (liftingAuxiliaryRing d k) q := by
  sorry

/-- The final local-ring identification `D_{q} = (D_k)_{q_k}`. -/
theorem liftingAuxiliary_localRing_equiv
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r)
    (q : PrimeSpectrum (liftingRing d))
    (qk : PrimeSpectrum (liftingAuxiliaryRing d k))
    (hcomap : PrimeSpectrum.comap (liftingAuxiliaryToLiftingRing d k) q = qk)
    (hπ : algebraMap R (liftingRing d) π ∈ q.asIdeal)
    (ha : liftingElement d (d.a k) ∉ q.asIdeal) :
    Nonempty
      (Localization.AtPrime qk.asIdeal ≃+*
        Localization.AtPrime q.asIdeal) := by
  sorry

/-! ## The intrinsic lifting diagram -/

/-- The quotient maps and commutativities in the lifting diagram. -/
structure LiftingDiagram
    {R Λ Cbar D : Type u} [CommRing R] [CommRing Λ] [CommRing Cbar]
    [CommRing D] [Algebra R Λ] [Algebra R D]
    (π : R) [Algebra (piQuotient R (π ^ 2)) Cbar]
    (hbar : Cbar →+* piQuotient Λ ((algebraMap R Λ π) ^ 2))
    (φ : D →ₐ[R] Λ) where
  rToD : piQuotient R π →+* piQuotient D (algebraMap R D π)
  cbarToD : Cbar →+* piQuotient D (algebraMap R D π)
  cbarModToD :
    piQuotient Cbar
        (quotientAlgebraMap (R := R) (A := Cbar)
          (Ideal.span ({π ^ 2} : Set R)) π) →+*
      piQuotient D (algebraMap R D π)
  dToLambda :
    piQuotient D (algebraMap R D π) →+* piQuotient Λ (algebraMap R Λ π)
  rToD_fac :
    rToD.comp (piQuotientMk π) =
      (piQuotientMk (algebraMap R D π)).comp (algebraMap R D)
  cbarModToD_fac :
    cbarModToD.comp
        (piQuotientMk
          (quotientAlgebraMap (R := R) (A := Cbar)
            (Ideal.span ({π ^ 2} : Set R)) π)) =
      cbarToD
  dToLambda_fac :
    dToLambda.comp (piQuotientMk (algebraMap R D π)) =
      (piQuotientMk (algebraMap R Λ π)).comp φ.toRingHom
  left_commutes :
    cbarToD.comp (algebraMap (piQuotient R (π ^ 2)) Cbar) =
      rToD.comp (piSquaredToPi π)
  right_commutes :
    dToLambda.comp cbarToD =
      (piSquaredToPi (algebraMap R Λ π)).comp hbar

/-- A prime of `D` lies over a prime of `\bar C` through the mod-`π` diagram. -/
def LiftingPrimeOver
    {R Λ Cbar D : Type u} [CommRing R] [CommRing Λ] [CommRing Cbar]
    [CommRing D] [Algebra R Λ] [Algebra R D]
    {π : R} [Algebra (piQuotient R (π ^ 2)) Cbar]
    {hbar : Cbar →+* piQuotient Λ ((algebraMap R Λ π) ^ 2)}
    {φ : D →ₐ[R] Λ}
    (diagram : LiftingDiagram π hbar φ)
    (p : PrimeSpectrum Cbar) (q : PrimeSpectrum D) : Prop :=
  quotientAlgebraMap (R := R) (A := Cbar)
      (Ideal.span ({π ^ 2} : Set R)) π ∈ p.asIdeal ∧
    algebraMap R D π ∈ q.asIdeal ∧
    ∃ (pbar : PrimeSpectrum
        (piQuotient Cbar
          (quotientAlgebraMap (R := R) (A := Cbar)
            (Ideal.span ({π ^ 2} : Set R)) π)))
      (qbar : PrimeSpectrum (piQuotient D (algebraMap R D π))),
      PrimeSpectrum.comap
          (piQuotientMk
            (quotientAlgebraMap (R := R) (A := Cbar)
              (Ideal.span ({π ^ 2} : Set R)) π)) pbar = p ∧
        PrimeSpectrum.comap (piQuotientMk (algebraMap R D π)) qbar = q ∧
        PrimeSpectrum.comap diagram.cbarModToD qbar = pbar

/-- Smoothness at a prime of a ring map, using its canonical algebra structure. -/
def IsSmoothAtRingHom
    {A B : Type u} [CommRing A] [CommRing B] (f : A →+* B)
    (q : PrimeSpectrum B) : Prop :=
  letI : Algebra A B := f.toAlgebra
  Formalization.Books.Algebra.Unit137.IsSmoothAt A B q

/-! ## The lifting lemma -/

/-- Elkik's lifting lemma, including its commutative quotient diagram and all
four local properties stated in the source. -/
theorem lifting_lemma
    {R Λ Cbar : Type u} [CommRing R] [CommRing Λ] [CommRing Cbar]
    [Algebra R Λ] [IsNoetherianRing R]
    (π : R) [Algebra (piQuotient R (π ^ 2)) Cbar]
    [Algebra.FinitePresentation (piQuotient R (π ^ 2)) Cbar]
    (hAnnR :
      annihilatorOf (R := R) (M := R) π =
        annihilatorOf (R := R) (M := R) (π ^ 2))
    (hAnnΛ :
      annihilatorOf (algebraMap R Λ π) =
        annihilatorOf ((algebraMap R Λ π) ^ 2))
    (hbar : Cbar →+* piQuotient Λ ((algebraMap R Λ π) ^ 2))
    (hbar_algebra :
      hbar.comp
          (quotientAlgebraMap (R := R) (A := Cbar)
            (Ideal.span ({π ^ 2} : Set R))) =
        (piQuotientMk ((algebraMap R Λ π) ^ 2)).comp (algebraMap R Λ)) :
    ∃ (D : Type u) (hD : CommRing D) (hRD : Algebra R D),
      letI : CommRing D := hD
      letI : Algebra R D := hRD
      ∃ (φ : D →ₐ[R] Λ),
        ∃ (diagram : LiftingDiagram π hbar φ),
          Algebra.FinitePresentation R D ∧
          (∀ q : PrimeSpectrum D,
            algebraMap R D π ∉ q.asIdeal →
              Formalization.Books.Algebra.Unit137.IsSmoothAt R D q) ∧
          (∀ (p : PrimeSpectrum Cbar) (q : PrimeSpectrum D),
            LiftingPrimeOver diagram p q →
              Formalization.Books.Algebra.Unit137.IsSmoothAt
                (piQuotient R (π ^ 2)) Cbar p →
                Formalization.Books.Algebra.Unit137.IsSmoothAt R D q) ∧
          (∀ (pbar : PrimeSpectrum
              (piQuotient Cbar
                (quotientAlgebraMap (R := R) (A := Cbar)
                  (Ideal.span ({π ^ 2} : Set R)) π)))
              (qbar : PrimeSpectrum (piQuotient D (algebraMap R D π))),
            PrimeSpectrum.comap diagram.cbarModToD qbar = pbar →
            Formalization.Books.Algebra.Unit137.IsSmoothAt
              (piQuotient R (π ^ 2)) Cbar
              (PrimeSpectrum.comap
                (piQuotientMk
                  (quotientAlgebraMap (R := R) (A := Cbar)
                    (Ideal.span ({π ^ 2} : Set R)) π)) pbar) →
            IsSmoothAtRingHom diagram.cbarModToD qbar) := by
  sorry

end

end Formalization.Books.Smoothing.Unit06
