import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Noetherian.Basic
import Formalization.Books.Algebra.Unit03.BasicNotions
import Formalization.Books.Algebra.Unit137.SmoothRingMaps

/-!
# Smoothing Ring Maps, Chapter 6: The lifting lemma

The chapter's proof is presentation based.  The explicit polynomial
construction below records the auxiliary choices and the equations used in
the proof, while the final theorem uses the intrinsic finite-presentation and
smoothness interfaces from the preceding algebra chapters.
-/

namespace Formalization.Books.Smoothing.Unit06

open Set
open Formalization.Books.Algebra.Unit03
open scoped BigOperators

noncomputable section

universe u

/-! ## Quotients by a principal element -/

/-- The quotient by the principal ideal generated by an element. -/
abbrev piQuotient (A : Type u) [CommRing A] (a : A) : Type u :=
  A ⧸ Ideal.span ({a} : Set A)

/-- The quotient map onto `A / aA`. -/
def piQuotientMk {A : Type u} [CommRing A] (a : A) : A →+* piQuotient A a :=
  Ideal.Quotient.mk _

/-- The canonical reduction map `A / a²A → A / aA`. -/
def piSquaredToPi {A : Type u} [CommRing A] (a : A) :
    piQuotient A (a ^ 2) →+* piQuotient A a :=
  Ideal.quotientMap (Ideal.span ({a} : Set A)) (RingHom.id A) (by
    apply Ideal.span_le.2
    intro x hx
    rcases Set.mem_singleton_iff.mp hx with rfl
    exact Ideal.mem_span_singleton'.2 ⟨a, by simp [pow_two]⟩)

/-- The ring map to an algebra which factors through a quotient of the base. -/
def quotientAlgebraMap
    {R A : Type u} [CommRing R] [CommRing A]
    (I : Ideal R) [Algebra (R ⧸ I) A] : R →+* A :=
  (algebraMap (R ⧸ I) A).comp (Ideal.Quotient.mk I)

/-! ## The polynomial data in the proof -/

/-- The polynomial ring containing the `x` and `z` variables of the proof. -/
abbrev liftingPolynomial (R : Type u) [CommRing R] (n m : ℕ) : Type u :=
  MvPolynomial (Fin n ⊕ Fin m) R

/-- Inclusion of the `x`-polynomial ring into the ring with `x` and `z`. -/
def liftLiftingPolynomial
    {R : Type u} [CommRing R] {n m : ℕ}
    (f : MvPolynomial (Fin n) R) : liftingPolynomial R n m :=
  MvPolynomial.rename Sum.inl f

/-- The lifted relation `f_ℓ - π z_ℓ`. -/
def liftingBaseRelation
    {R : Type u} [CommRing R] {n m : ℕ} (π : R)
    (f : Fin m → MvPolynomial (Fin n) R) (ℓ : Fin m) :
    liftingPolynomial R n m :=
  liftLiftingPolynomial (f ℓ) -
    MvPolynomial.C π * MvPolynomial.X (Sum.inr ℓ)

/-- The correction relation `p_{k,ℓ}` from the proof. -/
def liftingCorrectionRelation
    {R : Type u} [CommRing R] {n m r : ℕ} {e : Fin r → ℕ}
    (π : R) (a : Fin r → MvPolynomial (Fin n) R)
    (h : ∀ k : Fin r, Fin m → Fin (e k) → MvPolynomial (Fin n) R)
    (g : ∀ _k : Fin r, Fin m → MvPolynomial (Fin n) R)
    (E : ∀ k : Fin r, Fin (e k) ↪ Fin m) (k : Fin r) (ℓ : Fin m) :
    liftingPolynomial R n m :=
  liftLiftingPolynomial (a k) * MvPolynomial.X (Sum.inr ℓ) -
      ∑ j : Fin (e k),
        liftLiftingPolynomial (h k ℓ j) *
          MvPolynomial.X (Sum.inr (E k j)) -
    MvPolynomial.C π * liftLiftingPolynomial (g k ℓ)

/-- Evaluation of the `x`-polynomial presentation at elements of an algebra. -/
def liftingEvaluation
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {n : ℕ} (lambda : Fin n → Λ) :
    MvPolynomial (Fin n) R →ₐ[R] Λ :=
  MvPolynomial.aeval lambda

/-- The finite presentation and coefficient data used to construct `D`. -/
structure LiftingConstructionData (R : Type u) [CommRing R] (π : R) where
  n : ℕ
  m : ℕ
  r : ℕ
  e : Fin r → ℕ
  relations : Fin m → MvPolynomial (Fin n) R
  selected : ∀ k : Fin r, Fin (e k) ↪ Fin m
  a : Fin r → MvPolynomial (Fin n) R
  h : ∀ k : Fin r, Fin m → Fin (e k) → MvPolynomial (Fin n) R
  g : ∀ _k : Fin r, Fin m → MvPolynomial (Fin n) R
  relation_identity :
    ∀ k : Fin r, ∀ ℓ : Fin m,
      a k * relations ℓ =
        (∑ j : Fin (e k), h k ℓ j * relations (selected k j)) +
          MvPolynomial.C (π ^ 2) * g k ℓ
  selected_h :
    ∀ k : Fin r, ∀ j : Fin (e k), ∀ j' : Fin (e k),
      h k (selected k j) j' = if j' = j then a k else 0
  selected_g : ∀ k : Fin r, ∀ j : Fin (e k), g k (selected k j) = 0

/-- The ideal `I = (f_1, ..., f_m)` in the polynomial presentation. -/
def liftingRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Ideal (MvPolynomial (Fin d.n) R) :=
  Ideal.span (Set.range d.relations)

/-- The ideal `I_k = (f_j : j ∈ E_k)` used at a smooth basic open. -/
def liftingSelectedRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (MvPolynomial (Fin d.n) R) :=
  Ideal.span (Set.range (fun j : Fin (d.e k) => d.relations (d.selected k j)))

/-- The image `\bar I` of the presentation ideal modulo `π²`. -/
def liftingReducedRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Ideal (MvPolynomial (Fin d.n) (piQuotient R (π ^ 2))) :=
  Ideal.map
    (MvPolynomial.map (piQuotientMk (π ^ 2)) :
      MvPolynomial (Fin d.n) R →+*
        MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)))
    (liftingRelationIdeal d)

/-- The image `\bar I_k` of the selected relation ideal modulo `π²`. -/
def liftingReducedSelectedRelationIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (MvPolynomial (Fin d.n) (piQuotient R (π ^ 2))) :=
  Ideal.map
    (MvPolynomial.map (piQuotientMk (π ^ 2)) :
      MvPolynomial (Fin d.n) R →+*
        MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)))
    (liftingSelectedRelationIdeal d k)

/-- The defining ideal of the ring `D` in the proof. -/
def liftingDefiningIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Ideal (liftingPolynomial R d.n d.m) :=
  Ideal.span
    (Set.range (fun ℓ : Fin d.m => liftingBaseRelation π d.relations ℓ) ∪
      ⋃ k : Fin d.r, Set.range (fun ℓ : Fin d.m =>
        liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ))

/-- The ring `D` constructed in the proof. -/
abbrev liftingRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Type u :=
  liftingPolynomial R d.n d.m ⧸ liftingDefiningIdeal d

/-- The image in `D` of a polynomial in the `x` variables. -/
def liftingElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π)
    (f : MvPolynomial (Fin d.n) R) : liftingRing d :=
  Ideal.Quotient.mk _ (liftLiftingPolynomial f)

/-- The auxiliary ring `D_k`, where only the selected `f_j - π z_j` are used. -/
def liftingAuxiliaryDefiningIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (liftingPolynomial R d.n d.m) :=
  Ideal.span
    (Set.range (fun j : Fin (d.e k) =>
        liftingBaseRelation π d.relations (d.selected k j)) ∪
      Set.range (fun ℓ : Fin d.m =>
        liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ))

/-- The auxiliary ring `D_k` used in the local smoothness argument. -/
abbrev liftingAuxiliaryRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) : Type u :=
  liftingPolynomial R d.n d.m ⧸ liftingAuxiliaryDefiningIdeal d k

/-- The image of `a_k` in `D_k`. -/
def liftingAuxiliaryElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) : liftingAuxiliaryRing d k :=
  Ideal.Quotient.mk _ (liftLiftingPolynomial (d.a k))

/-- The values used in the proof to define the map from `D` to `Λ`. -/
structure LiftingEvaluationData
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {π : R} (d : LiftingConstructionData R π) where
  lambda : Fin d.n → Λ
  mu : Fin d.m → Λ
  relation_evaluation :
    ∀ ℓ : Fin d.m,
      liftingEvaluation lambda (d.relations ℓ) =
        (algebraMap R Λ π) ^ 2 * mu ℓ

/-- The polynomial evaluation sending `x_i` to `λ_i` and `z_j` to `π μ_j`. -/
def liftingEvaluationPolynomial
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {π : R} (d : LiftingConstructionData R π)
    (ev : LiftingEvaluationData (Λ := Λ) d) :
    liftingPolynomial R d.n d.m →ₐ[R] Λ :=
  MvPolynomial.aeval (fun v =>
    match v with
    | Sum.inl i => ev.lambda i
    | Sum.inr j => algebraMap R Λ π * ev.mu j)

/-- The evaluation descends through the defining equations of `D`. -/
theorem liftingRing_evaluation_descends
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {π : R} (d : LiftingConstructionData R π)
    (ev : LiftingEvaluationData (Λ := Λ) d)
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2)) :
    ∃ φ : liftingRing d →ₐ[R] Λ,
      ∀ v : Fin d.n ⊕ Fin d.m,
        φ (Ideal.Quotient.mk (liftingDefiningIdeal d) (MvPolynomial.X v)) =
          liftingEvaluationPolynomial d ev (MvPolynomial.X v) := by
  let F := liftingEvaluationPolynomial d ev
  have hIdeal : liftingDefiningIdeal d ≤ Ideal.comap F.toRingHom (⊥ : Ideal Λ) := by
    apply Ideal.span_le.2
    intro p hp
    rcases hp with hp | hp
    · rcases hp with ⟨ℓ, rfl⟩
      simp [F, liftingEvaluationPolynomial, liftingBaseRelation,
        liftLiftingPolynomial, MvPolynomial.aeval_rename]
      change liftingEvaluation ev.lambda (d.relations ℓ) -
        (algebraMap R Λ π) * ((algebraMap R Λ π) * ev.mu ℓ) = 0
      rw [ev.relation_evaluation]
      simp [pow_two, mul_assoc]
    · rcases Set.mem_iUnion.1 hp with ⟨k, hp⟩
      rcases hp with ⟨ℓ, rfl⟩
      simp [F, liftingEvaluationPolynomial, liftingCorrectionRelation,
        liftLiftingPolynomial, MvPolynomial.aeval_rename]
      change liftingEvaluation ev.lambda (d.a k) *
          ((algebraMap R Λ π) * ev.mu ℓ) -
        ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
          ((algebraMap R Λ π) * ev.mu (d.selected k x)) -
        (algebraMap R Λ π) * liftingEvaluation ev.lambda (d.g k ℓ) = 0
      have hrel :=
        congrArg (liftingEvaluation ev.lambda) (d.relation_identity k ℓ)
      simp only [map_mul, map_add, map_sum, map_pow]
        at hrel
      simp only [MvPolynomial.algHom_C] at hrel
      simp [mul_comm] at hrel
      simp only [ev.relation_evaluation] at hrel
      have hsum :
          (∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
            ((algebraMap R Λ π) ^ 2 * ev.mu (d.selected k x))) =
            (algebraMap R Λ π) ^ 2 *
              ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
                ev.mu (d.selected k x) := by
        calc
          (∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
              ((algebraMap R Λ π) ^ 2 * ev.mu (d.selected k x))) =
              ∑ x, (algebraMap R Λ π) ^ 2 *
                (liftingEvaluation ev.lambda (d.h k ℓ x) *
                  ev.mu (d.selected k x)) := by
                apply Finset.sum_congr rfl
                intro x hx
                ring
          _ = (algebraMap R Λ π) ^ 2 *
                ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
                  ev.mu (d.selected k x) := by
                rw [Finset.mul_sum]
      rw [hsum] at hrel
      have hq2 : (algebraMap R Λ π) ^ 2 *
          (liftingEvaluation ev.lambda (d.a k) * ev.mu ℓ -
            ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
              ev.mu (d.selected k x) -
            liftingEvaluation ev.lambda (d.g k ℓ)) = 0 := by
        linear_combination hrel
      have hcancel : ∀ x : Λ,
          (algebraMap R Λ π) ^ 2 * x = 0 →
            (algebraMap R Λ π) * x = 0 := by
        intro x hx
        have hx' : x ∈ annihilatorOf (R := Λ) (M := Λ)
            ((algebraMap R Λ π) ^ 2) := by
          apply (annihilatorOf_mem_iff
            (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2) x).2
          simpa [smul_eq_mul, mul_comm] using hx
        rw [← hAnnΛ] at hx'
        have hx'' := (annihilatorOf_mem_iff
          (R := Λ) (M := Λ) (algebraMap R Λ π) x).1 hx'
        simpa [smul_eq_mul, mul_comm] using hx''
      have hsum' :
          (∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
            ((algebraMap R Λ π) * ev.mu (d.selected k x))) =
            (algebraMap R Λ π) *
              ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
                ev.mu (d.selected k x) := by
        calc
          (∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
              ((algebraMap R Λ π) * ev.mu (d.selected k x))) =
              ∑ x, (algebraMap R Λ π) *
                (liftingEvaluation ev.lambda (d.h k ℓ x) *
                  ev.mu (d.selected k x)) := by
                apply Finset.sum_congr rfl
                intro x hx
                ring
          _ = (algebraMap R Λ π) *
                ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
                  ev.mu (d.selected k x) := by
                rw [Finset.mul_sum]
      calc
        liftingEvaluation ev.lambda (d.a k) *
              ((algebraMap R Λ π) * ev.mu ℓ) -
            ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
              ((algebraMap R Λ π) * ev.mu (d.selected k x)) -
            (algebraMap R Λ π) * liftingEvaluation ev.lambda (d.g k ℓ) =
          (algebraMap R Λ π) *
            (liftingEvaluation ev.lambda (d.a k) * ev.mu ℓ -
              ∑ x, liftingEvaluation ev.lambda (d.h k ℓ x) *
                ev.mu (d.selected k x) -
              liftingEvaluation ev.lambda (d.g k ℓ)) := by
          rw [hsum']
          ring
        _ = 0 := hcancel _ hq2
  have hF : ∀ p : liftingPolynomial R d.n d.m,
      p ∈ liftingDefiningIdeal d → F p = 0 := fun p hp => hIdeal hp
  refine ⟨Ideal.Quotient.liftₐ (liftingDefiningIdeal d) F hF, ?_⟩
  intro v
  change F (MvPolynomial.X v) = F (MvPolynomial.X v)
  rfl

/-- The quotient map `D_k → D` supplied by inclusion of defining ideals. -/
noncomputable def liftingAuxiliaryToLiftingRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
  liftingAuxiliaryRing d k →+* liftingRing d :=
  Ideal.Quotient.factor (show
    liftingAuxiliaryDefiningIdeal d k ≤ liftingDefiningIdeal d from by
      apply Ideal.span_le.2
      intro x hx
      rcases hx with hx | hx
      · rcases hx with ⟨j, rfl⟩
        exact Ideal.subset_span (Or.inl ⟨d.selected k j, rfl⟩)
      · rcases hx with ⟨ℓ, rfl⟩
        exact Ideal.subset_span
          (Or.inr (Set.mem_iUnion.2 ⟨k, ⟨ℓ, rfl⟩⟩)))

/-! ## Identities and local calculations in the construction -/

/-- The chosen relations in `E_k` give zero correction equations. -/
theorem liftingCorrectionRelation_selected
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) (j : Fin (d.e k)) :
    liftingCorrectionRelation π d.a d.h d.g d.selected k (d.selected k j) = 0 := by
  classical
  unfold liftingCorrectionRelation
  rw [Finset.sum_eq_single j]
  · simp [d.selected_h, d.selected_g, liftLiftingPolynomial]
  · intro b hb hbj
    simp [d.selected_h, hbj, liftLiftingPolynomial]
  · intro hj
    exact (hj (Finset.mem_univ j)).elim

/-- The key equality expressing `π p_{k,ℓ}` in the base relations. -/
theorem liftingKeyIdentity
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) (ℓ : Fin d.m) :
    MvPolynomial.C π *
        liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ =
      -liftLiftingPolynomial (d.a k) *
          liftingBaseRelation π d.relations ℓ +
        ∑ j : Fin (d.e k),
          liftLiftingPolynomial (d.h k ℓ j) *
            liftingBaseRelation π d.relations (d.selected k j) := by
  have hrel :=
    congrArg (fun p : MvPolynomial (Fin d.n) R =>
      liftLiftingPolynomial (m := d.m) p) (d.relation_identity k ℓ)
  simp only [liftLiftingPolynomial, map_mul, map_add, map_sum, map_pow] at hrel
  rw [MvPolynomial.rename_C] at hrel
  change liftLiftingPolynomial (d.a k) * liftLiftingPolynomial (d.relations ℓ) =
      (∑ j : Fin (d.e k),
        liftLiftingPolynomial (d.h k ℓ j) *
          liftLiftingPolynomial (d.relations (d.selected k j))) +
        (MvPolynomial.C π) ^ 2 * liftLiftingPolynomial (d.g k ℓ) at hrel
  have hsumX :
      (∑ j : Fin (d.e k),
        liftLiftingPolynomial (d.h k ℓ j) *
          (MvPolynomial.C π * MvPolynomial.X (Sum.inr (d.selected k j)))) =
        MvPolynomial.C π *
          ∑ j : Fin (d.e k),
            liftLiftingPolynomial (d.h k ℓ j) *
              MvPolynomial.X (Sum.inr (d.selected k j)) := by
    calc
      (∑ j : Fin (d.e k),
          liftLiftingPolynomial (d.h k ℓ j) *
            (MvPolynomial.C π * MvPolynomial.X (Sum.inr (d.selected k j)))) =
          ∑ j : Fin (d.e k), MvPolynomial.C π *
            (liftLiftingPolynomial (d.h k ℓ j) *
              MvPolynomial.X (Sum.inr (d.selected k j))) := by
            apply Finset.sum_congr rfl
            intro j hj
            ring
      _ = MvPolynomial.C π *
          ∑ j : Fin (d.e k),
            liftLiftingPolynomial (d.h k ℓ j) *
              MvPolynomial.X (Sum.inr (d.selected k j)) := by
            rw [Finset.mul_sum]
  have hsumSub :
      (∑ j : Fin (d.e k),
        liftLiftingPolynomial (d.h k ℓ j) *
          (liftLiftingPolynomial (d.relations (d.selected k j)) -
            MvPolynomial.C π * MvPolynomial.X (Sum.inr (d.selected k j)))) =
        (∑ j : Fin (d.e k),
          liftLiftingPolynomial (d.h k ℓ j) *
            liftLiftingPolynomial (d.relations (d.selected k j))) -
          ∑ j : Fin (d.e k),
            liftLiftingPolynomial (d.h k ℓ j) *
              (MvPolynomial.C π * MvPolynomial.X (Sum.inr (d.selected k j))) := by
    calc
      (∑ j : Fin (d.e k),
          liftLiftingPolynomial (d.h k ℓ j) *
            (liftLiftingPolynomial (d.relations (d.selected k j)) -
              MvPolynomial.C π * MvPolynomial.X (Sum.inr (d.selected k j)))) =
          ∑ j : Fin (d.e k),
            (liftLiftingPolynomial (d.h k ℓ j) *
              liftLiftingPolynomial (d.relations (d.selected k j)) -
            liftLiftingPolynomial (d.h k ℓ j) *
              (MvPolynomial.C π * MvPolynomial.X (Sum.inr (d.selected k j)))) := by
            apply Finset.sum_congr rfl
            intro j hj
            rw [mul_sub]
      _ = _ := by rw [Finset.sum_sub_distrib]
  simp [liftingCorrectionRelation, liftingBaseRelation]
  rw [hsumSub, hsumX]
  linear_combination hrel

/-- The polynomial presentation model for `\bar C`. -/
abbrev liftingPresentationModel
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Type u :=
  MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)) ⧸
    liftingReducedRelationIdeal d

noncomputable instance liftingPresentationModel.commRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    CommRing (liftingPresentationModel d) :=
  Ideal.Quotient.commRing (liftingReducedRelationIdeal d)

noncomputable instance liftingPresentationModel.algebraR
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Algebra R (liftingPresentationModel d) :=
  Algebra.compHom (liftingPresentationModel d) (piQuotientMk (π ^ 2))

/-- The image of `a_k` in the presentation model of `\bar C`. -/
def liftingPresentationElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    liftingPresentationModel d :=
  Ideal.Quotient.mk _
    ((MvPolynomial.map (piQuotientMk (π ^ 2)) :
      MvPolynomial (Fin d.n) R →+*
        MvPolynomial (Fin d.n) (piQuotient R (π ^ 2))) (d.a k))

/-- The base map from `R` to the presentation model. -/
def liftingPresentationModelMap
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : R →+* liftingPresentationModel d :=
  (algebraMap (piQuotient R (π ^ 2)) (liftingPresentationModel d)).comp
    (piQuotientMk (π ^ 2))

def liftingPresentationModPiIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Ideal (liftingPresentationModel d) :=
  Ideal.map (liftingPresentationModelMap d) (Ideal.span ({π} : Set R))

noncomputable instance liftingPresentationModPiIdeal.isTwoSided
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    (liftingPresentationModPiIdeal d).IsTwoSided := by
  refine ⟨fun {a} b ha => ?_⟩
  have h := (liftingPresentationModPiIdeal d).smul_mem b ha
  rw [smul_eq_mul] at h
  rw [mul_comm b a] at h
  exact h

/-- The mod-`π` presentation model for `\bar C / π\bar C`. -/
abbrev liftingPresentationModPiModel
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) : Type u :=
  liftingPresentationModel d ⧸
    liftingPresentationModPiIdeal d

/-- The image of `a_k` in the mod-`π` presentation model. -/
def liftingPresentationModPiElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
  liftingPresentationModPiModel d :=
  Ideal.Quotient.mk (liftingPresentationModPiIdeal d) (liftingPresentationElement d k)

def liftingAuxiliaryModPiIdeal
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Ideal (liftingAuxiliaryRing d k) :=
  Ideal.map (algebraMap R (liftingAuxiliaryRing d k))
    (Ideal.span ({π} : Set R))

/-- The mod-`π` auxiliary ring `D_k / π D_k`. -/
abbrev liftingAuxiliaryModPiRing
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) : Type u :=
  liftingAuxiliaryRing d k ⧸
    liftingAuxiliaryModPiIdeal d k

/-- The image of `a_k` in `D_k / π D_k`. -/
def liftingAuxiliaryModPiElement
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
  liftingAuxiliaryModPiRing d k :=
  (Ideal.Quotient.mk (liftingAuxiliaryModPiIdeal d k))
    (Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k)
      (liftLiftingPolynomial (d.a k)))

private structure liftingAuxiliaryModPiLocalizedBaseSetup
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r)
    [hA : CommRing (liftingAuxiliaryModPiRing d k)] where
  qmk : liftingPolynomial R d.n d.m →+*
    liftingAuxiliaryModPiRing d k
  rmapU : R →+* Localization.Away (liftingAuxiliaryModPiElement d k)
  qvar : (Fin d.n ⊕ Fin d.m) →
    Localization.Away (liftingAuxiliaryModPiElement d k)
  qmap : liftingPolynomial R d.n d.m →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  qkill : ∀ p : liftingPolynomial R d.n d.m,
    p ∈ liftingAuxiliaryDefiningIdeal d k → qmap p = 0
  hpi : qmap (MvPolynomial.C π) = 0
  hrpi : rmapU π = 0
  hbase : ∀ ℓ : Fin d.m,
    qmap (liftLiftingPolynomial (d.relations ℓ)) = 0
  rmap2 : piQuotient R (π ^ 2) →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  hrmap2 : ∀ r : R,
    rmap2 (piQuotientMk (π ^ 2) r) = rmapU r
  xvar : Fin d.n → Localization.Away (liftingAuxiliaryModPiElement d k)
  pmap : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)) →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  pmap_eq : pmap = MvPolynomial.eval₂Hom rmap2 xvar
  pmap_lift : ∀ p : MvPolynomial (Fin d.n) R,
    pmap ((MvPolynomial.map (piQuotientMk (π ^ 2))) p) =
      qmap (liftLiftingPolynomial p)
  hred : ∀ p : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)),
    p ∈ liftingReducedRelationIdeal d → pmap p = 0
  qmap_spec : ∀ p : liftingPolynomial R d.n d.m,
    qmap p = algebraMap (liftingAuxiliaryModPiRing d k)
      (Localization.Away (liftingAuxiliaryModPiElement d k))
      (qmk p)
  qmk_spec : ∀ p : liftingPolynomial R d.n d.m,
    qmk p = (Ideal.Quotient.mk (liftingAuxiliaryModPiIdeal d k))
      ((Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k)) p)

private structure liftingAuxiliaryModPiLocalizedSetup
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r)
    [hA : CommRing (liftingAuxiliaryModPiRing d k)] where
  qmk : liftingPolynomial R d.n d.m →+*
    liftingAuxiliaryModPiRing d k
  rmapU : R →+* Localization.Away (liftingAuxiliaryModPiElement d k)
  qvar : (Fin d.n ⊕ Fin d.m) → Localization.Away (liftingAuxiliaryModPiElement d k)
  qmap : liftingPolynomial R d.n d.m →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  qkill : ∀ p : liftingPolynomial R d.n d.m,
    p ∈ liftingAuxiliaryDefiningIdeal d k → qmap p = 0
  hpi : qmap (MvPolynomial.C π) = 0
  qmap_spec : ∀ p : liftingPolynomial R d.n d.m,
    qmap p = algebraMap (liftingAuxiliaryModPiRing d k)
      (Localization.Away (liftingAuxiliaryModPiElement d k)) (qmk p)
  rmap2 : piQuotient R (π ^ 2) →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  xvar : Fin d.n → Localization.Away (liftingAuxiliaryModPiElement d k)
  pmap : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)) →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  pmap_eq : pmap = MvPolynomial.eval₂Hom rmap2 xvar
  qmk_spec : ∀ p : liftingPolynomial R d.n d.m,
    qmk p = (Ideal.Quotient.mk (liftingAuxiliaryModPiIdeal d k))
      ((Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k)) p)
  smap : liftingPresentationModel d →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  smap_spec : ∀ p : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)),
    smap (Ideal.Quotient.mk (liftingReducedRelationIdeal d) p) = pmap p
  smap2 : liftingPresentationModPiModel d →+*
    Localization.Away (liftingAuxiliaryModPiElement d k)
  smap2_spec : ∀ p : liftingPresentationModel d,
    smap2 (Ideal.Quotient.mk (liftingPresentationModPiIdeal d) p) = smap p
  smap2_element :
    smap2 (liftingPresentationModPiElement d k) =
      algebraMap (liftingAuxiliaryModPiRing d k)
        (Localization.Away (liftingAuxiliaryModPiElement d k))
        (liftingAuxiliaryModPiElement d k)

private opaque liftingAuxiliary_modPi_localized_base_setup
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    liftingAuxiliaryModPiLocalizedBaseSetup d k := by
  classical
  let A := liftingAuxiliaryModPiRing d k
  let U := Localization.Away (liftingAuxiliaryModPiElement d k)
  letI : CommRing A := Ideal.Quotient.commRing _
  let qmk : liftingPolynomial R d.n d.m →+* A :=
    (Ideal.Quotient.mk (liftingAuxiliaryModPiIdeal d k)).comp
      (Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k))
  let rmapU : R →+* U :=
    (algebraMap A U).comp (qmk.comp MvPolynomial.C)
  let qvar : (Fin d.n ⊕ Fin d.m) → U := fun v =>
    algebraMap A U (qmk (MvPolynomial.X v))
  let qmap : liftingPolynomial R d.n d.m →+* U :=
    MvPolynomial.eval₂Hom rmapU qvar
  have qmap_eq : qmap = (algebraMap A U).comp qmk := by
    apply MvPolynomial.ringHom_ext'
    · ext r
      simp [qmap, rmapU]
    · intro v
      simp [qmap, qvar]
  have qkill : ∀ p : liftingPolynomial R d.n d.m,
      p ∈ liftingAuxiliaryDefiningIdeal d k → qmap p = 0 := by
    intro p hp
    rw [qmap_eq]
    have hp' : Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k) p = 0 :=
      (Ideal.Quotient.eq_zero_iff_mem).2 hp
    simp [qmk, hp']
  have hpi : qmap (MvPolynomial.C π) = 0 := by
    rw [qmap_eq]
    change algebraMap A U
      (Ideal.Quotient.mk (liftingAuxiliaryModPiIdeal d k)
        (algebraMap R (liftingAuxiliaryRing d k) π)) = 0
    have hzero : Ideal.Quotient.mk (liftingAuxiliaryModPiIdeal d k)
        (algebraMap R (liftingAuxiliaryRing d k) π) = 0 := by
      apply Ideal.Quotient.eq_zero_iff_mem.2
      exact Ideal.mem_map_of_mem (algebraMap R (liftingAuxiliaryRing d k))
        (Ideal.subset_span (by simp))
    rw [hzero]
    simp
  have hrpi : rmapU π = 0 := by
    simpa [qmap] using hpi
  have hsel : ∀ j : Fin (d.e k),
      qmap (liftingBaseRelation π d.relations (d.selected k j)) = 0 := by
    intro j
    apply qkill
    exact Ideal.subset_span (Or.inl ⟨j, rfl⟩)
  have haunit : IsUnit (qmap (liftLiftingPolynomial (d.a k))) := by
    rw [qmap_eq]
    change IsUnit (algebraMap A U (liftingAuxiliaryModPiElement d k))
    exact IsLocalization.Away.algebraMap_isUnit _
  have hbase : ∀ ℓ : Fin d.m,
      qmap (liftLiftingPolynomial (d.relations ℓ)) = 0 := by
    intro ℓ
    have hid := congrArg
      (fun p : MvPolynomial (Fin d.n) R => qmap (liftLiftingPolynomial p))
      (d.relation_identity k ℓ)
    simp only [qmap, liftLiftingPolynomial, MvPolynomial.eval₂Hom_rename,
      map_mul, map_add, map_sum, map_pow] at hid
    have hsel' : ∀ j : Fin (d.e k),
        (MvPolynomial.eval₂Hom rmapU (qvar ∘ Sum.inl))
            (d.relations (d.selected k j)) = 0 := by
      intro j
      simpa [qmap, liftingBaseRelation, liftLiftingPolynomial,
        MvPolynomial.eval₂Hom_rename, MvPolynomial.eval₂_rename, hrpi] using hsel j
    simp only [hsel', MvPolynomial.eval₂Hom_C, hrpi] at hid
    apply haunit.mul_left_cancel
    simpa [qmap, liftLiftingPolynomial, MvPolynomial.eval₂Hom_rename] using hid
  let rmap2 : piQuotient R (π ^ 2) →+* U :=
    Ideal.Quotient.lift (Ideal.span ({π ^ 2} : Set R)) rmapU (by
      intro x hx
      change x ∈ Ideal.comap rmapU ⊥
      have hle : Ideal.span ({π ^ 2} : Set R) ≤ Ideal.comap rmapU ⊥ :=
        (Ideal.map_le_iff_le_comap).1
          (show Ideal.map rmapU (Ideal.span ({π ^ 2} : Set R)) ≤ ⊥ by
            apply Ideal.map_le_iff_le_comap.2
            apply Ideal.span_le.2
            intro y hy
            rcases Set.mem_singleton_iff.mp hy with rfl
            simp [hrpi])
      exact hle hx)
  let xvar : Fin d.n → U := fun i => qvar (Sum.inl i)
  let pmap : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)) →+* U :=
    MvPolynomial.eval₂Hom rmap2 xvar
  have hrmap2 : ∀ r : R,
      rmap2 (piQuotientMk (π ^ 2) r) = rmapU r := by
    intro r
    simp [rmap2, piQuotientMk]
  have hrmap2_hom : rmap2.comp (piQuotientMk (π ^ 2)) = rmapU := by
    ext r
    exact hrmap2 r
  have hpmap_lift : ∀ p : MvPolynomial (Fin d.n) R,
      pmap ((MvPolynomial.map (piQuotientMk (π ^ 2))) p) =
        qmap (liftLiftingPolynomial p) := by
    intro p
    change MvPolynomial.eval₂Hom rmap2 xvar
        ((MvPolynomial.map (piQuotientMk (π ^ 2))) p) =
      MvPolynomial.eval₂Hom rmapU qvar (liftLiftingPolynomial p)
    rw [MvPolynomial.eval₂Hom_map_hom, hrmap2_hom]
    change MvPolynomial.eval₂Hom rmapU (qvar ∘ Sum.inl) p =
      MvPolynomial.eval₂Hom rmapU qvar (MvPolynomial.rename Sum.inl p)
    rw [MvPolynomial.eval₂Hom_rename]
  have hred : ∀ p : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)),
      p ∈ liftingReducedRelationIdeal d → pmap p = 0 := by
    intro p hp
    have hle : liftingReducedRelationIdeal d ≤ Ideal.comap pmap ⊥ := by
      unfold liftingReducedRelationIdeal
      rw [Ideal.map_le_iff_le_comap]
      apply Ideal.span_le.2
      rintro _ ⟨ℓ, rfl⟩
      change pmap
        ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.relations ℓ)) = 0
      change MvPolynomial.eval₂Hom rmap2 xvar
        ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.relations ℓ)) = 0
      rw [MvPolynomial.eval₂Hom_map_hom, hrmap2_hom]
      have hb := hbase ℓ
      change MvPolynomial.eval₂Hom rmapU qvar
        (MvPolynomial.rename Sum.inl (d.relations ℓ)) = 0 at hb
      rw [MvPolynomial.eval₂Hom_rename] at hb
      change MvPolynomial.eval₂Hom rmapU (qvar ∘ Sum.inl)
        (d.relations ℓ) = 0
      exact hb
    exact hle hp
  exact
    { qmk := qmk
      rmapU := rmapU
      qvar := qvar
      qmap := qmap
      qkill := qkill
      hpi := hpi
      hrpi := hrpi
      hbase := hbase
      rmap2 := rmap2
      hrmap2 := hrmap2
      xvar := xvar
      pmap := pmap
      pmap_eq := rfl
      pmap_lift := hpmap_lift
      hred := hred
      qmap_spec := by
        intro p
        exact RingHom.congr_fun qmap_eq p
      qmk_spec := by
        intro p
        rfl }

private theorem liftingAuxiliary_modPi_span_kernel
    {R C U : Type u} [CommRing R] [CommRing C] [CommRing U] {π : R}
    (f : R →+* C) (g : C →+* U) (hπ : g (f π) = 0) :
    ∀ p : C, p ∈ Ideal.map f (Ideal.span ({π} : Set R)) → g p = 0 := by
  intro p hp
  have hle : Ideal.map f (Ideal.span ({π} : Set R)) ≤ Ideal.comap g ⊥ := by
    rw [Ideal.map_le_iff_le_comap]
    apply Ideal.span_le.2
    intro x hx
    rcases Set.mem_singleton_iff.mp hx with rfl
    simpa [Ideal.mem_comap] using hπ
  exact hle hp

private opaque liftingAuxiliary_modPi_localized_smap2_kernel
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r)
    (pmap : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)) →+*
      Localization.Away (liftingAuxiliaryModPiElement d k))
    (rmapU : R →+* Localization.Away (liftingAuxiliaryModPiElement d k))
    (rmap2 : piQuotient R (π ^ 2) →+*
      Localization.Away (liftingAuxiliaryModPiElement d k))
    (xvar : Fin d.n → Localization.Away (liftingAuxiliaryModPiElement d k))
    (pmap_eq : pmap = MvPolynomial.eval₂Hom rmap2 xvar)
    (hrmap2 : ∀ r : R, rmap2 (piQuotientMk (π ^ 2) r) =
      rmapU r)
    (hrpi : rmapU π = 0)
    (smap : liftingPresentationModel d →+*
      Localization.Away (liftingAuxiliaryModPiElement d k))
    (smap_spec : ∀ p : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)),
      smap (Ideal.Quotient.mk (liftingReducedRelationIdeal d) p) = pmap p) :
    ∀ p : liftingPresentationModel d,
      p ∈ liftingPresentationModPiIdeal d → smap p = 0 := by
  intro p hp
  have hp' : p ∈ Ideal.map (liftingPresentationModelMap d)
      (Ideal.span ({π} : Set R)) := hp
  have hpiS : smap (liftingPresentationModelMap d π) = 0 := by
    change smap (Ideal.Quotient.mk (liftingReducedRelationIdeal d)
      (MvPolynomial.C (piQuotientMk (π ^ 2) π))) = 0
    rw [smap_spec]
    rw [pmap_eq]
    rw [MvPolynomial.eval₂Hom_C, hrmap2]
    exact hrpi
  exact liftingAuxiliary_modPi_span_kernel
    (liftingPresentationModelMap d) smap hpiS p hp'

private opaque liftingAuxiliary_modPi_localized_setup
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    liftingAuxiliaryModPiLocalizedSetup d k := by
  classical
  let A := liftingAuxiliaryModPiRing d k
  let U := Localization.Away (liftingAuxiliaryModPiElement d k)
  letI : CommRing A := Ideal.Quotient.commRing _
  let base := liftingAuxiliary_modPi_localized_base_setup d k
  let qmk := base.qmk
  let rmapU := base.rmapU
  let qvar := base.qvar
  let qmap := base.qmap
  let qkill := base.qkill
  let hpi := base.hpi
  let rmap2 := base.rmap2
  let hrmap2 := base.hrmap2
  let xvar := base.xvar
  let pmap := base.pmap
  let hred := base.hred
  let qmap_eq : qmap = (algebraMap A U).comp qmk := by
    apply RingHom.ext
    intro p
    simpa only [RingHom.comp_apply] using base.qmap_spec p
  let qmk_spec := base.qmk_spec
  let smap : liftingPresentationModel d →+* U :=
    Ideal.Quotient.lift (liftingReducedRelationIdeal d) pmap (by
      intro p hp
      exact hred p hp)
  let smap_spec : ∀ p : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)),
      smap (Ideal.Quotient.mk (liftingReducedRelationIdeal d) p) = pmap p := by
    intro p
    rfl
  let smap2 : liftingPresentationModPiModel d →+* U :=
    Ideal.Quotient.lift (liftingPresentationModPiIdeal d) smap (by
      exact liftingAuxiliary_modPi_localized_smap2_kernel d k pmap rmapU rmap2 xvar
        base.pmap_eq hrmap2 base.hrpi smap (by
          intro p
          rfl))
  let smap2_spec : ∀ p : liftingPresentationModel d,
      smap2 (Ideal.Quotient.mk (liftingPresentationModPiIdeal d) p) = smap p := by
    intro p
    rfl
  have hsmap2_element :
      smap2 (liftingPresentationModPiElement d k) =
        algebraMap A U (liftingAuxiliaryModPiElement d k) := by
    have hsmap_spec : ∀ p : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)),
        smap (Ideal.Quotient.mk (liftingReducedRelationIdeal d) p) = pmap p := by
      intro p
      rfl
    have hsmap2_spec : ∀ p : liftingPresentationModel d,
        smap2 (Ideal.Quotient.mk (liftingPresentationModPiIdeal d) p) = smap p := by
      intro p
      rfl
    calc
      smap2 (liftingPresentationModPiElement d k) =
          smap (liftingPresentationElement d k) := by
        exact hsmap2_spec (liftingPresentationElement d k)
      _ = pmap ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.a k)) := by
        exact hsmap_spec
          ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.a k))
      _ = qmap (liftLiftingPolynomial (d.a k)) := by
        exact base.pmap_lift (d.a k)
      _ = algebraMap A U (liftingAuxiliaryModPiElement d k) := by
        rw [qmap_eq]
        simp only [RingHom.comp_apply]
        rw [qmk_spec]
        rfl
  exact
    { qmk := qmk
      rmapU := rmapU
      qvar := qvar
      qmap := qmap
      qkill := qkill
      hpi := hpi
      qmap_spec := by
        intro p
        exact RingHom.congr_fun qmap_eq p
      rmap2 := rmap2
      xvar := xvar
      pmap := pmap
      pmap_eq := base.pmap_eq
      qmk_spec := qmk_spec
      smap := smap
      smap_spec := smap_spec
      smap2 := smap2
      smap2_spec := smap2_spec
      smap2_element := hsmap2_element }

/-- The localized polynomial calculation for the auxiliary ring. -/
theorem liftingAuxiliary_modPi_localized_equiv
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Nonempty
      (Localization.Away (liftingAuxiliaryModPiElement d k) ≃+*
        MvPolynomial (Fin (d.e k))
      (Localization.Away (liftingPresentationModPiElement d k))) := by
  classical
  let A := liftingAuxiliaryModPiRing d k
  let U := Localization.Away (liftingAuxiliaryModPiElement d k)
  let _ : CommRing A := Ideal.Quotient.commRing _
  let setup := liftingAuxiliary_modPi_localized_setup d k
  let qmk := setup.qmk
  let qmk_spec := setup.qmk_spec
  let rmapU := setup.rmapU
  let qvar := setup.qvar
  let qmap := setup.qmap
  let qkill := setup.qkill
  let hpi := setup.hpi
  have qmap_eq : qmap = (algebraMap A U).comp qmk := by
    apply RingHom.ext
    intro p
    simpa only [RingHom.comp_apply] using setup.qmap_spec p
  let rmap2 := setup.rmap2
  let xvar := setup.xvar
  let pmap := setup.pmap
  let pmap_eq := setup.pmap_eq
  let smap := setup.smap
  let smap_spec := setup.smap_spec
  let smap2 := setup.smap2
  let smap2_spec := setup.smap2_spec
  let T := Localization.Away (liftingPresentationModPiElement d k)
  let B := MvPolynomial (Fin (d.e k)) T
  let p2mk : MvPolynomial (Fin d.n) (piQuotient R (π ^ 2)) →+*
      liftingPresentationModPiModel d :=
    (Ideal.Quotient.mk (liftingPresentationModPiIdeal d)).comp
      (Ideal.Quotient.mk (liftingReducedRelationIdeal d))
  let evalx : MvPolynomial (Fin d.n) R →+* T :=
    (algebraMap (liftingPresentationModPiModel d) T).comp p2mk |>.comp
      (MvPolynomial.map (piQuotientMk (π ^ 2)))
  let pmod : R →+* T := evalx.comp MvPolynomial.C
  let pX : Fin d.n → T := fun i => evalx (MvPolynomial.X i)
  let bcoeff : R →+* B := MvPolynomial.C.comp pmod
  let ainv : T := IsLocalization.Away.invSelf (liftingPresentationModPiElement d k)
  let bvar : (Fin d.n ⊕ Fin d.m) → B := fun v =>
    match v with
    | Sum.inl i => MvPolynomial.C (pX i)
    | Sum.inr ℓ =>
        MvPolynomial.C ainv * ∑ j : Fin (d.e k),
          MvPolynomial.C (evalx (d.h k ℓ j)) *
            MvPolynomial.X j
  let bmap : liftingPolynomial R d.n d.m →+* B :=
    MvPolynomial.eval₂Hom bcoeff bvar
  have bmap_lift : ∀ p : MvPolynomial (Fin d.n) R,
      bmap (liftLiftingPolynomial p) = MvPolynomial.C (evalx p) := by
    have hbmap : bmap.comp (MvPolynomial.rename Sum.inl).toRingHom =
        MvPolynomial.C.comp evalx := by
      apply MvPolynomial.ringHom_ext'
      · ext r
        simp [bmap, bcoeff, pmod, evalx]
      · intro i
        simp [bmap, bvar, pX, evalx]
    intro p
    exact RingHom.congr_fun hbmap p
  have hpiModel :
      p2mk (MvPolynomial.C (piQuotientMk (π ^ 2) π)) = 0 := by
    change Ideal.Quotient.mk (liftingPresentationModPiIdeal d)
      (liftingPresentationModelMap d π) = 0
    apply Ideal.Quotient.eq_zero_iff_mem.2
    exact Ideal.mem_map_of_mem (liftingPresentationModelMap d)
      (Ideal.subset_span (by simp))
  have bpi : bcoeff π = 0 := by
    change MvPolynomial.C (evalx (MvPolynomial.C π)) = 0
    change MvPolynomial.C
      ((algebraMap (liftingPresentationModPiModel d) T)
        (p2mk ((MvPolynomial.map (piQuotientMk (π ^ 2)))
          (MvPolynomial.C π)))) = 0
    rw [MvPolynomial.map_C, hpiModel]
    simp
  have hevalbase : ∀ ℓ : Fin d.m, evalx (d.relations ℓ) = 0 := by
    intro ℓ
    have hmem :
        (MvPolynomial.map (piQuotientMk (π ^ 2))) (d.relations ℓ) ∈
          liftingReducedRelationIdeal d :=
      Ideal.mem_map_of_mem (MvPolynomial.map (piQuotientMk (π ^ 2)))
        (Ideal.subset_span ⟨ℓ, rfl⟩)
    have hzero' :
        Ideal.Quotient.mk (liftingReducedRelationIdeal d)
          ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.relations ℓ)) = 0 :=
      Ideal.Quotient.eq_zero_iff_mem.2 hmem
    have hzero : p2mk
        ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.relations ℓ)) = 0 := by
      change Ideal.Quotient.mk (liftingPresentationModPiIdeal d)
        (Ideal.Quotient.mk (liftingReducedRelationIdeal d)
          ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.relations ℓ))) = 0
      rw [hzero']
      simp
    change (algebraMap (liftingPresentationModPiModel d) T)
        (p2mk ((MvPolynomial.map (piQuotientMk (π ^ 2)))
          (d.relations ℓ))) = 0
    rw [hzero]
    simp
  have bbase : ∀ ℓ : Fin d.m,
      bmap (liftingBaseRelation π d.relations ℓ) = 0 := by
    intro ℓ
    change bmap (liftLiftingPolynomial (d.relations ℓ) -
      MvPolynomial.C π * MvPolynomial.X (Sum.inr ℓ)) = 0
    rw [map_sub, bmap_lift, map_mul]
    have hcoeff : bmap (MvPolynomial.C π) = bcoeff π := by
      simp [bmap]
    rw [hcoeff, bpi]
    rw [hevalbase ℓ]
    simp
  have haT : evalx (d.a k) * ainv = 1 := by
    change (algebraMap (liftingPresentationModPiModel d) T)
        (liftingPresentationModPiElement d k) *
        IsLocalization.Away.invSelf (liftingPresentationModPiElement d k) = 1
    exact IsLocalization.Away.mul_invSelf _
  have bcorr : ∀ ℓ : Fin d.m,
      bmap (liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ) = 0 := by
    have hX : ∀ t : Fin d.m,
        bmap (MvPolynomial.X (Sum.inr t)) =
          MvPolynomial.C ainv * ∑ j : Fin (d.e k),
            MvPolynomial.C (evalx (d.h k t j)) * MvPolynomial.X j := by
      intro t
      simp [bmap, bvar]
    have hXsel : ∀ j : Fin (d.e k),
        bmap (MvPolynomial.X (Sum.inr (d.selected k j))) =
          MvPolynomial.C ainv * MvPolynomial.C (evalx (d.a k)) *
            MvPolynomial.X j := by
      intro j
      rw [hX]
      rw [Finset.sum_eq_single j]
      · rw [d.selected_h]
        simp only [if_true]
        ring
      · intro b hb hbj
        rw [d.selected_h]
        simp [hbj]
      · intro hj
        exact (hj (Finset.mem_univ j)).elim
    have hCpi : bmap (MvPolynomial.C π) = 0 := by
      have hcoeff : bmap (MvPolynomial.C π) = bcoeff π := by
        simp [bmap]
      rw [hcoeff, bpi]
    intro ℓ
    have hrel :
        bmap (liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ) =
          MvPolynomial.C (evalx (d.a k)) *
              (MvPolynomial.C ainv *
                ∑ j : Fin (d.e k),
                  MvPolynomial.C (evalx (d.h k ℓ j)) *
                    MvPolynomial.X j) -
            (∑ j : Fin (d.e k),
              MvPolynomial.C (evalx (d.h k ℓ j)) *
                (MvPolynomial.C ainv * MvPolynomial.C (evalx (d.a k)) *
                  MvPolynomial.X j)) - 0 := by
      change bmap (liftLiftingPolynomial (d.a k) *
          MvPolynomial.X (Sum.inr ℓ) -
        ∑ j : Fin (d.e k),
          liftLiftingPolynomial (d.h k ℓ j) *
            MvPolynomial.X (Sum.inr (d.selected k j)) -
        MvPolynomial.C π * liftLiftingPolynomial (d.g k ℓ)) = _
      calc
        bmap (liftLiftingPolynomial (d.a k) *
            MvPolynomial.X (Sum.inr ℓ) -
          ∑ j : Fin (d.e k),
            liftLiftingPolynomial (d.h k ℓ j) *
              MvPolynomial.X (Sum.inr (d.selected k j)) -
          MvPolynomial.C π * liftLiftingPolynomial (d.g k ℓ)) =
            bmap (liftLiftingPolynomial (d.a k)) *
                bmap (MvPolynomial.X (Sum.inr ℓ)) -
              (∑ j : Fin (d.e k),
                bmap (liftLiftingPolynomial (d.h k ℓ j)) *
                  bmap (MvPolynomial.X (Sum.inr (d.selected k j)))) -
              bmap (MvPolynomial.C π) *
                bmap (liftLiftingPolynomial (d.g k ℓ)) := by
          rw [map_sub, map_sub, map_mul, map_sum]
          simp only [map_mul]
        _ = _ := by
          simp only [bmap_lift, hXsel, hX, hCpi, map_zero, zero_mul,
            sub_zero]
    rw [hrel]
    simp only [sub_zero]
    have hscalar :
        (MvPolynomial.C : T →+* B) (evalx (d.a k)) *
          (MvPolynomial.C : T →+* B) ainv = 1 := by
      rw [← map_mul, haT, map_one]
    have hleft :
        MvPolynomial.C (evalx (d.a k)) *
            (MvPolynomial.C ainv *
              ∑ j : Fin (d.e k),
                MvPolynomial.C (evalx (d.h k ℓ j)) *
                  MvPolynomial.X j) =
          ∑ j : Fin (d.e k),
            (MvPolynomial.C (evalx (d.a k)) * MvPolynomial.C ainv) *
              (MvPolynomial.C (evalx (d.h k ℓ j)) *
                MvPolynomial.X j) := by
      rw [← mul_assoc, Finset.mul_sum]
    have hright :
        (∑ j : Fin (d.e k),
          MvPolynomial.C (evalx (d.h k ℓ j)) *
            (MvPolynomial.C ainv * MvPolynomial.C (evalx (d.a k)) *
              MvPolynomial.X j)) =
          ∑ j : Fin (d.e k),
            (MvPolynomial.C (evalx (d.a k)) * MvPolynomial.C ainv) *
              (MvPolynomial.C (evalx (d.h k ℓ j)) *
                MvPolynomial.X j) := by
      apply Finset.sum_congr rfl
      intro j hj
      ring
    rw [hleft, hright, hscalar]
    simp
  have hDideal : ∀ p : liftingPolynomial R d.n d.m,
      p ∈ liftingAuxiliaryDefiningIdeal d k → bmap p = 0 := by
    intro p hp
    have hle : liftingAuxiliaryDefiningIdeal d k ≤ Ideal.comap bmap ⊥ := by
      apply Ideal.span_le.2
      intro x hx
      rcases hx with hx | hx
      · rcases hx with ⟨j, rfl⟩
        exact bbase (d.selected k j)
      · rcases hx with ⟨ℓ, rfl⟩
        exact bcorr ℓ
    exact hle hp
  let fD : liftingAuxiliaryRing d k →+* B :=
    Ideal.Quotient.lift (liftingAuxiliaryDefiningIdeal d k) bmap (by
      intro p hp
      exact hDideal p hp)
  have fD_pi : fD (algebraMap R (liftingAuxiliaryRing d k) π) = 0 := by
    change bmap (MvPolynomial.C π) = 0
    simp [bmap, bcoeff, bpi]
  let f0 : A →+* B :=
    Ideal.Quotient.lift (liftingAuxiliaryModPiIdeal d k) fD (by
      intro p hp
      have hle : liftingAuxiliaryModPiIdeal d k ≤ Ideal.comap fD ⊥ := by
        rw [liftingAuxiliaryModPiIdeal, Ideal.map_le_iff_le_comap]
        apply Ideal.span_le.2
        intro x hx
        rcases Set.mem_singleton_iff.mp hx with rfl
        simpa [Ideal.mem_comap] using fD_pi
      exact hle hp)
  have hfunit : IsUnit (f0 (liftingAuxiliaryModPiElement d k)) := by
    have hfD_a :
        fD (Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k)
            (liftLiftingPolynomial (d.a k))) =
          (MvPolynomial.C : T →+* B) (evalx (d.a k)) := by
      change bmap (liftLiftingPolynomial (d.a k)) =
        (MvPolynomial.C : T →+* B) (evalx (d.a k))
      exact bmap_lift (d.a k)
    have hf : f0 (liftingAuxiliaryModPiElement d k) =
        (MvPolynomial.C : T →+* B) (evalx (d.a k)) := by
      change fD (Ideal.Quotient.mk (liftingAuxiliaryDefiningIdeal d k)
        (liftLiftingPolynomial (d.a k))) =
        (MvPolynomial.C : T →+* B) (evalx (d.a k))
      exact hfD_a
    have hevalxa :
        (MvPolynomial.C : T →+* B) (evalx (d.a k)) =
          (MvPolynomial.C : T →+* B)
            ((algebraMap (liftingPresentationModPiModel d) T)
              (liftingPresentationModPiElement d k)) := by
      change (MvPolynomial.C : T →+* B)
          ((algebraMap (liftingPresentationModPiModel d) T)
            (p2mk ((MvPolynomial.map (piQuotientMk (π ^ 2))) (d.a k)))) = _
      rfl
    rw [hf]
    rw [hevalxa]
    exact IsUnit.map (MvPolynomial.C : T →+* B)
      (IsLocalization.Away.algebraMap_isUnit _)
  let f : U →+* B :=
    IsLocalization.Away.lift (liftingAuxiliaryModPiElement d k) hfunit
  have hsunit : IsUnit
      (smap2 (liftingPresentationModPiElement d k)) := by
    have hs : smap2 (liftingPresentationModPiElement d k) =
        algebraMap A U (liftingAuxiliaryModPiElement d k) :=
      setup.smap2_element
    rw [hs]
    exact IsLocalization.Away.algebraMap_isUnit _
  let tmap : T →+* U :=
    IsLocalization.Away.lift (liftingPresentationModPiElement d k) hsunit
  let gvar : Fin (d.e k) → U := fun j =>
    algebraMap A U (qmk (MvPolynomial.X (Sum.inr (d.selected k j))))
  let gmap : B →+* U :=
    MvPolynomial.eval₂Hom tmap gvar
  have qcorr : ∀ ℓ : Fin d.m,
      qmap (liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ) = 0 := by
    intro ℓ
    apply qkill
    exact Ideal.subset_span (Or.inr ⟨ℓ, rfl⟩)
  have hqa : qmap (liftLiftingPolynomial (d.a k)) =
      algebraMap A U (liftingAuxiliaryModPiElement d k) := by
    rw [qmap_eq]
    simp only [RingHom.comp_apply]
    rw [qmk_spec]
    rfl
  have hqainv : qmap (liftLiftingPolynomial (d.a k)) *
      IsLocalization.Away.invSelf (liftingAuxiliaryModPiElement d k) = 1 := by
    rw [hqa]
    exact IsLocalization.Away.mul_invSelf _
  have qsolve : ∀ ℓ : Fin d.m,
      qmap (MvPolynomial.X (Sum.inr ℓ)) =
        IsLocalization.Away.invSelf (liftingAuxiliaryModPiElement d k) *
          ∑ j : Fin (d.e k),
            qmap (liftLiftingPolynomial (d.h k ℓ j)) *
              qmap (MvPolynomial.X (Sum.inr (d.selected k j))) := by
    intro ℓ
    have h := qcorr ℓ
    change qmap (liftLiftingPolynomial (d.a k) *
        MvPolynomial.X (Sum.inr ℓ) -
      ∑ j : Fin (d.e k),
        liftLiftingPolynomial (d.h k ℓ j) *
          MvPolynomial.X (Sum.inr (d.selected k j)) -
      MvPolynomial.C π * liftLiftingPolynomial (d.g k ℓ)) = 0 at h
    simp only [map_sub, map_mul, map_sum] at h
    rw [hpi] at h
    have hmul : qmap (liftLiftingPolynomial (d.a k)) *
          qmap (MvPolynomial.X (Sum.inr ℓ)) =
        ∑ j : Fin (d.e k),
          qmap (liftLiftingPolynomial (d.h k ℓ j)) *
            qmap (MvPolynomial.X (Sum.inr (d.selected k j))) := by
      simpa [Finset.mul_sum, Finset.sum_mul, mul_assoc, mul_comm,
        mul_left_comm] using h
    calc
      qmap (MvPolynomial.X (Sum.inr ℓ)) =
          1 * qmap (MvPolynomial.X (Sum.inr ℓ)) := by simp
      _ = (IsLocalization.Away.invSelf
          (liftingAuxiliaryModPiElement d k) *
          qmap (liftLiftingPolynomial (d.a k))) *
          qmap (MvPolynomial.X (Sum.inr ℓ)) := by
            rw [mul_comm, hqainv]
            simp
      _ = IsLocalization.Away.invSelf
          (liftingAuxiliaryModPiElement d k) *
          (qmap (liftLiftingPolynomial (d.a k)) *
            qmap (MvPolynomial.X (Sum.inr ℓ))) := by ring
      _ = _ := by rw [hmul]
  have htmap_pmod : ∀ r : R, tmap (pmod r) = qmap (MvPolynomial.C r) := by
    intro r
    simp [tmap, pmod, pmod, smap2, smap, p2mk, qmap, qvar, qmk,
      rmapU, pmap, evalx]
  have htmap_pX : ∀ i : Fin d.n, tmap (pX i) =
      qmap (MvPolynomial.X (Sum.inl i)) := by
    intro i
    simp [tmap, pX, evalx, p2mk, smap2, smap, qmap, qvar, qmk,
      rmapU, pmap]
  have htmap_evalx : ∀ p : MvPolynomial (Fin d.n) R,
      tmap (evalx p) = qmap (liftLiftingPolynomial p) := by
    have hh : tmap.comp evalx =
        qmap.comp (MvPolynomial.rename Sum.inl).toRingHom := by
      apply MvPolynomial.ringHom_ext'
      · ext r
        simpa [MvPolynomial.rename_C] using htmap_pmod r
      · intro i
        simpa [liftLiftingPolynomial] using htmap_pX i
    intro p
    exact RingHom.congr_fun hh p
  have htmap_ainv : tmap ainv =
      IsLocalization.Away.invSelf (liftingAuxiliaryModPiElement d k) := by
    have hta : qmap (liftLiftingPolynomial (d.a k)) * tmap ainv = 1 := by
      have h := IsLocalization.Away.mul_invSelf
        (liftingPresentationModPiElement d k)
      have h' := congrArg tmap h
      simpa [tmap, smap2, smap, p2mk, evalx, qmap, qvar, qmk,
        rmapU, pmap, hqa] using h'
    calc
      tmap ainv = 1 * tmap ainv := by simp
      _ = (IsLocalization.Away.invSelf
          (liftingAuxiliaryModPiElement d k) *
          qmap (liftLiftingPolynomial (d.a k))) * tmap ainv := by
            rw [mul_comm, hqainv]
            simp
      _ = IsLocalization.Away.invSelf
          (liftingAuxiliaryModPiElement d k) *
          (qmap (liftLiftingPolynomial (d.a k)) * tmap ainv) := by ring
      _ = _ := by rw [hta]; simp
  have gf_base : gmap.comp bmap = qmap := by
    apply MvPolynomial.ringHom_ext'
    · ext r
      simp [gmap, bmap, bcoeff, htmap_pmod]
    · intro v
      rcases v with i | ℓ
      · simp [gmap, bmap, bvar, bcoeff, pX, htmap_pX]
      · simp [gmap, bmap, bvar, bcoeff, htmap_ainv, htmap_evalx]
        rw [qsolve ℓ]
  have gf0 : gmap.comp f0 = algebraMap A U := by
    apply Ideal.Quotient.ringHom_ext
    apply Ideal.Quotient.ringHom_ext
    simpa [f0, fD, qmk] using gf_base
  have gf : gmap.comp f = RingHom.id U := by
    apply IsLocalization.ringHom_ext (Submonoid.powers
      (liftingAuxiliaryModPiElement d k))
    simpa [f, gf0]
  have fqmap : f.comp qmap = bmap := by
    simpa [qmap_eq, f, f0, fD, qmk] 
  have fsbase : f.comp smap2 =
      (algebraMap T B).comp (algebraMap
        (liftingPresentationModPiModel d) T) := by
    apply Ideal.Quotient.ringHom_ext
    apply Ideal.Quotient.ringHom_ext
    apply MvPolynomial.ringHom_ext'
    · ext r
      simp [smap2, smap, p2mk, pmap, rmap2, f, f0, fD, qmk,
        qmap, qvar, rmapU, bmap, bcoeff, pmod]
    · intro i
      simp [smap2, smap, p2mk, pmap, rmap2, f, f0, fD, qmk,
        qmap, qvar, rmapU, bmap, bcoeff, bvar, pX, pmod, evalx]
  have ft : f.comp tmap = algebraMap T B := by
    apply IsLocalization.ringHom_ext (Submonoid.powers
      (liftingPresentationModPiElement d k))
    simpa [tmap, fsbase]
  have fgvar : ∀ j : Fin (d.e k), f (gvar j) = MvPolynomial.X j := by
    intro j
    simp [gvar, f, f0, fD, qmk, bmap, bvar, d.selected_h,
      haT, Finset.mul_sum, Finset.sum_mul, mul_assoc, mul_comm,
      mul_left_comm]
  have fg : f.comp gmap = RingHom.id B := by
    apply MvPolynomial.ringHom_ext'
    · ext s
      simpa [gmap, ft]
    · intro j
      simpa [gmap, fgvar]
  refine ⟨RingEquiv.ofBijective f ⟨?_, ?_⟩⟩
  · intro x y hxy
    have := congrArg gmap hxy
    simpa [gf] using this
  · intro y
    refine ⟨gmap y, ?_⟩
    simpa [fg] using rfl

/-- The polynomial algebra in the localized mod-`π` presentation is smooth
over its coefficient ring; the preceding equivalence identifies it with the
localized auxiliary quotient. -/
theorem liftingAuxiliary_modPi_localized_smooth
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r) :
    Algebra.Smooth (Localization.Away (liftingPresentationModPiElement d k))
      (MvPolynomial (Fin (d.e k))
        (Localization.Away (liftingPresentationModPiElement d k))) := by
  let hfp : Algebra.FinitePresentation
      (Localization.Away (liftingPresentationModPiElement d k))
      (Localization.Away (liftingPresentationModPiElement d k)) :=
    Algebra.FinitePresentation.self _
  refine ⟨?_, ?_⟩
  · exact Algebra.instFormallySmoothMvPolynomial
      (R := Localization.Away (liftingPresentationModPiElement d k)) (Fin (d.e k))
  · exact @Algebra.FinitePresentation.mvPolynomial
      (Localization.Away (liftingPresentationModPiElement d k))
      (Localization.Away (liftingPresentationModPiElement d k))
      _ _ _ hfp (Fin (d.e k)) inferInstance

/-- The finite-presentation assertion for the explicit ring `D`. -/
theorem liftingRing_finitePresentation
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Algebra.FinitePresentation R (liftingRing d) := by
  have hfinite :
      Set.Finite
        (Set.range (fun ℓ : Fin d.m =>
            liftingBaseRelation π d.relations ℓ) ∪
          ⋃ k : Fin d.r, Set.range (fun ℓ : Fin d.m =>
            liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ)) := by
    apply Set.Finite.union
    · exact Set.finite_range _
    · exact Set.finite_iUnion (fun k => Set.finite_range _)
  have hfg : (liftingDefiningIdeal d).FG := by
    rw [liftingDefiningIdeal]
    exact Submodule.fg_span hfinite
  exact Algebra.FinitePresentation.quotient hfg

/-- Inverting `π` identifies `D` with a polynomial algebra over `R[1/π]`. -/
theorem liftingRing_localization_smooth
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Algebra.Smooth R
      (Localization.Away (algebraMap R (liftingRing d) π)) := by
  classical
  let D := liftingRing d
  let L := Localization.Away (algebraMap R D π)
  let S := Localization.Away π
  let P := MvPolynomial (Fin d.n) S
  let _ : Algebra R P := Algebra.compHom P (algebraMap R S)
  let _ : IsScalarTower R S P :=
    IsScalarTower.of_algebraMap_eq (fun r => rfl)
  let gR : R →+* L := (algebraMap D L).comp (algebraMap R D)
  have hgR : IsUnit (gR π) := by
    exact IsLocalization.Away.algebraMap_isUnit (S := L) (algebraMap R D π)
  let smapL : S →+* L :=
    IsLocalization.Away.lift (R := R) (S := S) (g := gR) π hgR
  let xeval : MvPolynomial (Fin d.n) R →+* P :=
    MvPolynomial.eval₂Hom (algebraMap R P) (fun i => MvPolynomial.X i)
  let sinv : P := (algebraMap S P) (IsLocalization.Away.invSelf π)
  let zvar : Fin d.m → P := fun ℓ =>
    sinv * xeval (d.relations ℓ)
  let pmap : liftingPolynomial R d.n d.m →+* P :=
    MvPolynomial.eval₂Hom (algebraMap R P) (fun v =>
      match v with
      | Sum.inl i => MvPolynomial.X i
      | Sum.inr ℓ => zvar ℓ)
  have hpmap_lift : ∀ p : MvPolynomial (Fin d.n) R,
      pmap (liftLiftingPolynomial p) = xeval p := by
    have h : pmap.comp (MvPolynomial.rename Sum.inl).toRingHom = xeval := by
      apply MvPolynomial.ringHom_ext'
      · ext r
        simp [pmap, xeval]
      · intro i
        simp [pmap, xeval]
    intro p
    exact RingHom.congr_fun h p
  have hpi : (algebraMap R P) π * sinv = 1 := by
    change (algebraMap S P) (algebraMap R S π) *
      (algebraMap S P) (IsLocalization.Away.invSelf π) = 1
    rw [← map_mul, IsLocalization.Away.mul_invSelf]
    simp
  have hpmap_base : ∀ ℓ : Fin d.m,
      pmap (liftingBaseRelation π d.relations ℓ) = 0 := by
    intro ℓ
    rw [liftingBaseRelation, map_sub, hpmap_lift]
    simp [pmap, zvar, hpi, mul_assoc]
    rw [← mul_assoc, hpi]
    simp
  have hidentity : ∀ k : Fin d.r, ∀ ℓ : Fin d.m,
      xeval (d.a k) * xeval (d.relations ℓ) =
        (∑ j : Fin (d.e k),
          xeval (d.h k ℓ j) * xeval (d.relations (d.selected k j))) +
          (algebraMap R P) (π ^ 2) * xeval (d.g k ℓ) := by
    intro k ℓ
    have h := congrArg xeval (d.relation_identity k ℓ)
    have hC : xeval (MvPolynomial.C (π ^ 2)) = (algebraMap R P) (π ^ 2) := by
      simp [xeval]
    simpa only [map_mul, map_add, map_sum, hC] using h
  have hpi2 : sinv * (algebraMap R P) (π ^ 2) = (algebraMap R P) π := by
    rw [map_pow]
    calc
      sinv * ((algebraMap R P) π) ^ 2 =
          sinv * ((algebraMap R P) π * (algebraMap R P) π) := by rw [pow_two]
      _ =
          (sinv * (algebraMap R P) π) * (algebraMap R P) π := by ring
      _ = (algebraMap R P) π := by
        rw [show sinv * (algebraMap R P) π = 1 by simpa [mul_comm] using hpi]
        simp
  have hpmap_corr : ∀ k : Fin d.r, ∀ ℓ : Fin d.m,
      pmap (liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ) = 0 := by
    intro k ℓ
    have hrel :
        pmap (liftingCorrectionRelation π d.a d.h d.g d.selected k ℓ) =
          sinv *
            (xeval (d.a k) * xeval (d.relations ℓ) -
              (∑ j : Fin (d.e k),
                xeval (d.h k ℓ j) * xeval (d.relations (d.selected k j))) -
              (algebraMap R P) (π ^ 2) * xeval (d.g k ℓ)) := by
      simp only [liftingCorrectionRelation, map_sub, map_mul, map_sum]
      simp only [hpmap_lift]
      simp [pmap, zvar, Finset.sum_mul, Finset.mul_sum]
      have hpi2' : sinv * ((algebraMap R P) π) ^ 2 = (algebraMap R P) π := by
        simpa only [map_pow] using hpi2
      have hlast := congrArg (fun t : P => t * xeval (d.g k ℓ)) hpi2'.symm
      have hsum :
          (∑ j : Fin (d.e k),
            xeval (d.h k ℓ j) *
              (sinv * xeval (d.relations (d.selected k j)))) =
            sinv * ∑ j : Fin (d.e k),
              xeval (d.h k ℓ j) * xeval (d.relations (d.selected k j)) := by
        calc
          _ = ∑ j : Fin (d.e k), sinv *
              (xeval (d.h k ℓ j) * xeval (d.relations (d.selected k j))) := by
                apply Finset.sum_congr rfl
                intro j hj
                ring
          _ = _ := by rw [Finset.mul_sum]
      rw [hsum]
      rw [hlast]
      ring
    rw [hrel, hidentity k ℓ]
    ring
  have hkill : ∀ p ∈ liftingDefiningIdeal d, pmap p = 0 := by
    intro p hp
    have hle : liftingDefiningIdeal d ≤ Ideal.comap pmap ⊥ := by
      rw [liftingDefiningIdeal]
      apply Ideal.span_le.2
      intro x hx
      rcases hx with hx | hx
      · rcases hx with ⟨ℓ, rfl⟩
        simpa [Ideal.mem_comap] using hpmap_base ℓ
      · rcases Set.mem_iUnion.mp hx with ⟨k, hx⟩
        rcases hx with ⟨ℓ, rfl⟩
        simpa [Ideal.mem_comap] using hpmap_corr k ℓ
    exact hle hp
  let qmap : D →+* P :=
    Ideal.Quotient.lift (liftingDefiningIdeal d) pmap (by
      intro p hp
      exact hkill p hp)
  have hq_pi_eq : qmap (algebraMap R D π) = (algebraMap R P) π := by
    change pmap (MvPolynomial.C π) = _
    simp [pmap]
  have hq_pi : IsUnit (qmap (algebraMap R D π)) := by
    rw [hq_pi_eq]
    rw [IsScalarTower.algebraMap_apply R S P]
    exact IsUnit.map (algebraMap S P)
      (IsLocalization.Away.algebraMap_isUnit (R := R) (S := S) π)
  let f : L →+* P :=
    IsLocalization.Away.lift (R := D) (S := L) (g := qmap)
      (algebraMap R D π) hq_pi
  let gvar : Fin d.n → L := fun i =>
    algebraMap D L
      (Ideal.Quotient.mk (liftingDefiningIdeal d)
        (MvPolynomial.X (Sum.inl i)))
  let gmap : P →+* L := MvPolynomial.eval₂Hom smapL gvar
  have hgmap_xeval : ∀ p : MvPolynomial (Fin d.n) R,
      gmap (xeval p) =
        algebraMap D L
          (Ideal.Quotient.mk (liftingDefiningIdeal d)
            (liftLiftingPolynomial p)) := by
    have h : gmap.comp xeval =
        (algebraMap D L).comp
          ((Ideal.Quotient.mk (liftingDefiningIdeal d)).comp
            (MvPolynomial.rename Sum.inl).toRingHom) := by
      apply MvPolynomial.ringHom_ext'
      · ext r
        simp only [RingHom.comp_apply]
        have hx : xeval (MvPolynomial.C r) =
            MvPolynomial.C ((algebraMap R S) r) := by
          simp [xeval]
          change (algebraMap S P) ((algebraMap R S) r) = _
          rw [MvPolynomial.algebraMap_apply]
          simp
        rw [hx]
        change MvPolynomial.eval₂Hom smapL gvar
            (MvPolynomial.C ((algebraMap R S) r)) = _
        rw [MvPolynomial.eval₂Hom_C, IsLocalization.Away.lift_eq]
        simp [gR, D, liftingRing, MvPolynomial.rename_C,
          MvPolynomial.algebraMap_eq]
        have hmk :
            Ideal.Quotient.mk (liftingDefiningIdeal d) (MvPolynomial.C r) =
              algebraMap R D r := by
          rw [← MvPolynomial.algebraMap_eq]
          exact Ideal.Quotient.mk_algebraMap R (liftingDefiningIdeal d) r
        rw [hmk]
      · intro i
        simp only [RingHom.comp_apply]
        have hx : xeval (MvPolynomial.X i) = MvPolynomial.X i := by
          simp [xeval]
        rw [hx]
        change MvPolynomial.eval₂Hom smapL gvar (MvPolynomial.X i) = _
        rw [MvPolynomial.eval₂Hom_X']
        simp [gvar, MvPolynomial.rename_X]
    intro p
    exact RingHom.congr_fun h p
  have hpiL :
      smapL (IsLocalization.Away.invSelf π) *
          algebraMap D L (algebraMap R D π) = 1 := by
    have h := congrArg smapL
      (IsLocalization.Away.mul_invSelf (R := R) (S := S) π)
    rw [map_mul] at h
    rw [IsLocalization.Away.lift_eq π hgR _] at h
    simpa [gR, mul_comm] using h
  have hbaseD : ∀ ℓ : Fin d.m,
      algebraMap D L
          (Ideal.Quotient.mk (liftingDefiningIdeal d)
            (liftLiftingPolynomial (d.relations ℓ))) =
        algebraMap D L
          ((algebraMap R D π) *
            Ideal.Quotient.mk (liftingDefiningIdeal d)
              (MvPolynomial.X (Sum.inr ℓ))) := by
    intro ℓ
    have hzero :
        Ideal.Quotient.mk (liftingDefiningIdeal d)
            (liftingBaseRelation π d.relations ℓ) = 0 := by
      apply Ideal.Quotient.eq_zero_iff_mem.2
      rw [liftingDefiningIdeal]
      exact Ideal.subset_span (Or.inl ⟨ℓ, rfl⟩)
    have hsub := congrArg (algebraMap D L) hzero
    have hπ : (algebraMap R D) π =
        Ideal.Quotient.mk (liftingDefiningIdeal d) (MvPolynomial.C π) := by
      rw [← Ideal.Quotient.mk_algebraMap R (liftingDefiningIdeal d) π]
      rfl
    have hmk :
        (algebraMap R D π) *
            Ideal.Quotient.mk (liftingDefiningIdeal d)
              (MvPolynomial.X (Sum.inr ℓ)) =
          Ideal.Quotient.mk (liftingDefiningIdeal d)
              (MvPolynomial.C π * MvPolynomial.X (Sum.inr ℓ)) := by
      rw [hπ, ← map_mul]
    rw [hmk]
    apply sub_eq_zero.mp
    simpa [liftingBaseRelation, map_sub] using hsub
  have hgq : gmap.comp qmap = algebraMap D L := by
    apply Ideal.Quotient.ringHom_ext
    apply MvPolynomial.ringHom_ext'
    · ext r
      have h := hgmap_xeval (MvPolynomial.C r)
      simpa [qmap, pmap, xeval, liftLiftingPolynomial,
        MvPolynomial.algebraMap_apply, MvPolynomial.algebraMap_eq] using h
    · intro v
      rcases v with i | ℓ
      · have h := hgmap_xeval (MvPolynomial.X i)
        simpa [qmap, pmap, xeval, liftLiftingPolynomial,
          MvPolynomial.rename_X] using h
      · have hsinv : gmap sinv = smapL (IsLocalization.Away.invSelf π) := by
          change MvPolynomial.eval₂Hom smapL gvar
              (MvPolynomial.C (IsLocalization.Away.invSelf π)) = _
          rw [MvPolynomial.eval₂Hom_C]
        have h := hgmap_xeval (d.relations ℓ)
        change gmap (pmap (MvPolynomial.X (Sum.inr ℓ))) = _
        simp [pmap, zvar]
        rw [hsinv, h]
        rw [hbaseD]
        calc
          smapL (IsLocalization.Away.invSelf π) *
                algebraMap D L
                  ((algebraMap R D) π *
                    Ideal.Quotient.mk (liftingDefiningIdeal d)
                      (MvPolynomial.X (Sum.inr ℓ))) =
              smapL (IsLocalization.Away.invSelf π) *
                (algebraMap D L (algebraMap R D π) *
                  algebraMap D L
                    (Ideal.Quotient.mk (liftingDefiningIdeal d)
                      (MvPolynomial.X (Sum.inr ℓ)))) := by rw [map_mul]
          _ =
              (smapL (IsLocalization.Away.invSelf π) *
                algebraMap D L (algebraMap R D π)) *
                  algebraMap D L
                    (Ideal.Quotient.mk (liftingDefiningIdeal d)
                      (MvPolynomial.X (Sum.inr ℓ))) := by ring
          _ = _ := by rw [hpiL]; simp
  have hfbase : f.comp (algebraMap D L) = qmap := by
    apply RingHom.ext
    intro x
    simp only [RingHom.comp_apply]
    rw [IsLocalization.Away.lift_eq (algebraMap R D π) hq_pi x]
  have hgf : gmap.comp f = RingHom.id L := by
    apply IsLocalization.ringHom_ext (Submonoid.powers
      (algebraMap R D π))
    change gmap.comp (f.comp (algebraMap D L)) = algebraMap D L
    rw [hfbase]
    exact hgq
  have hfS : f.comp smapL = algebraMap S P := by
    apply IsLocalization.ringHom_ext (Submonoid.powers π)
    apply RingHom.ext
    intro r
    simp only [RingHom.comp_apply]
    rw [IsLocalization.Away.lift_eq π hgR r]
    change f (gR r) = _
    rw [show gR r = algebraMap D L (algebraMap R D r) by rfl]
    rw [IsLocalization.Away.lift_eq (algebraMap R D π) hq_pi
      (algebraMap R D r)]
    change qmap (algebraMap R D r) = _
    change pmap (MvPolynomial.C r) = _
    simp [pmap]
    exact IsScalarTower.algebraMap_apply R S P r
  have hfg : f.comp gmap = RingHom.id P := by
    apply MvPolynomial.ringHom_ext'
    · apply RingHom.ext
      intro s
      simp only [RingHom.comp_apply]
      change f (gmap (MvPolynomial.C s)) = MvPolynomial.C s
      have hgC : gmap (MvPolynomial.C s) = smapL s := by
        change MvPolynomial.eval₂Hom smapL gvar
          (MvPolynomial.C s) = _
        rw [MvPolynomial.eval₂Hom_C]
      rw [hgC]
      have hs := congrArg (fun h => h s) hfS
      change f (smapL s) = (algebraMap S P) s at hs
      rw [MvPolynomial.algebraMap_apply] at hs
      exact hs
    · intro i
      have hfvar : f (gvar i) = MvPolynomial.X i := by
        change f (algebraMap D L
          (Ideal.Quotient.mk (liftingDefiningIdeal d)
            (MvPolynomial.X (Sum.inl i)))) = _
        rw [IsLocalization.Away.lift_eq (algebraMap R D π) hq_pi]
        change qmap (Ideal.Quotient.mk (liftingDefiningIdeal d)
          (MvPolynomial.X (Sum.inl i))) = _
        change pmap (MvPolynomial.X (Sum.inl i)) = _
        simp [pmap]
      simp only [RingHom.comp_apply]
      change f (gmap (MvPolynomial.X i)) = MvPolynomial.X i
      rw [MvPolynomial.eval₂Hom_X']
      exact hfvar
  let e : L ≃+* P := RingEquiv.ofBijective f ⟨by
    intro x y hxy
    calc
      x = gmap (f x) := by
        have h := congrArg (fun h => h x) hgf
        simpa using h.symm
      _ = gmap (f y) := by rw [hxy]
      _ = y := by
        have h := congrArg (fun h => h y) hgf
        simpa using h, by
    intro y
    refine ⟨gmap y, ?_⟩
    have h := congrArg (fun h => h y) hfg
    simpa using h⟩
  have hcomm : ∀ r : R,
      e (algebraMap R L r) = (algebraMap R P) r := by
    intro r
    change f (algebraMap R L r) = _
    change f (algebraMap D L (algebraMap R D r)) = _
    rw [IsLocalization.Away.lift_eq (algebraMap R D π) hq_pi
      (algebraMap R D r)]
    change qmap (algebraMap R D r) = _
    change pmap (MvPolynomial.C r) = _
    simp [pmap]
  let ae : L ≃ₐ[R] P := AlgEquiv.ofRingEquiv (f := e) hcomm
  have hSR : Algebra.Smooth R S := by
    exact Formalization.Books.Algebra.Unit137.smooth_localization
      (R := R) (S := R) π
  have hSP : Algebra.Smooth S P := by
    let hfp : Algebra.FinitePresentation S S :=
      Algebra.FinitePresentation.self _
    exact ⟨Algebra.instFormallySmoothMvPolynomial
        (R := S) (Fin d.n),
      @Algebra.FinitePresentation.mvPolynomial
        S S _ _ _ hfp (Fin d.n) inferInstance⟩
  have hRP : Algebra.Smooth R P := by
    exact @Algebra.Smooth.comp R _ S P _ _ _ _ _ _ hSR hSP
  have hformL : Algebra.FormallySmooth R L :=
    @Algebra.FormallySmooth.of_equiv R _ P L _ _ _ _ hRP.1 ae.symm
  have hfpL : Algebra.FinitePresentation R L :=
    @Algebra.FinitePresentation.equiv R P L _ _ _ _ _ hRP.2 ae.symm
  exact { formallySmooth := hformL, finitePresentation := hfpL }

/-- The explicit polynomial presentation of `D[1/π]` used in the proof of (b). -/
theorem liftingRing_localization_equiv
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) :
    Nonempty
      (Localization.Away (algebraMap R (liftingRing d) π) ≃+*
        MvPolynomial (Fin d.n) (Localization.Away π)) := by
  sorry

/-- The source's property (b) for the explicit construction. -/
theorem liftingRing_smoothAt_of_pi_not_mem
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (q : PrimeSpectrum (liftingRing d))
    (hq : algebraMap R (liftingRing d) π ∉ q.asIdeal) :
    Formalization.Books.Algebra.Unit137.IsSmoothAt R (liftingRing d) q := by
  sorry

/-- The source's local smoothness conclusion for the auxiliary ring, assuming
the selected basic open of the presented `\bar C` is smooth. -/
theorem liftingAuxiliaryRing_smoothAt_of_good_prime
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r)
    (q : PrimeSpectrum (liftingAuxiliaryRing d k))
    (hbase :
      Algebra.Smooth (piQuotient R (π ^ 2))
        (Localization.Away (liftingPresentationElement d k)))
    (hπ : algebraMap R (liftingAuxiliaryRing d k) π ∈ q.asIdeal)
    (ha : liftingAuxiliaryElement d k ∉ q.asIdeal) :
    Formalization.Books.Algebra.Unit137.IsSmoothAt R
      (liftingAuxiliaryRing d k) q := by
  sorry

/-- The final local-ring identification `D_{q} = (D_k)_{q_k}`.  The
annihilator equality and smoothness of `Dₖ` supply the flatness used in the
source's cancellation argument. -/
theorem liftingAuxiliary_localRing_equiv
    {R : Type u} [CommRing R] {π : R}
    (d : LiftingConstructionData R π) (k : Fin d.r)
    (q : PrimeSpectrum (liftingRing d))
    (qk : PrimeSpectrum (liftingAuxiliaryRing d k))
    (hcomap : PrimeSpectrum.comap (liftingAuxiliaryToLiftingRing d k) q = qk)
    (hAnnR :
      annihilatorOf (R := R) (M := R) π =
        annihilatorOf (R := R) (M := R) (π ^ 2))
    (hSmoothK :
      Formalization.Books.Algebra.Unit137.IsSmoothAt R
        (liftingAuxiliaryRing d k) qk)
    (hπ : algebraMap R (liftingRing d) π ∈ q.asIdeal)
    (ha : liftingElement d (d.a k) ∉ q.asIdeal) :
    Nonempty
      (Localization.AtPrime qk.asIdeal ≃+*
        Localization.AtPrime q.asIdeal) := by
  sorry

/-! ## The intrinsic lifting diagram -/

/-- The quotient maps and commutativities in the lifting diagram. -/
structure LiftingDiagram
    {R Λ Cbar D : Type u} [CommRing R] [CommRing Λ] [CommRing Cbar]
    [CommRing D] [Algebra R Λ] [Algebra R D]
    (π : R) [Algebra (piQuotient R (π ^ 2)) Cbar]
    (hbar : Cbar →+* piQuotient Λ ((algebraMap R Λ π) ^ 2))
    (φ : D →ₐ[R] Λ) where
  rToD : piQuotient R π →+* piQuotient D (algebraMap R D π)
  cbarToD : Cbar →+* piQuotient D (algebraMap R D π)
  cbarModToD :
    piQuotient Cbar
        (quotientAlgebraMap (R := R) (A := Cbar)
          (Ideal.span ({π ^ 2} : Set R)) π) →+*
      piQuotient D (algebraMap R D π)
  dToLambda :
    piQuotient D (algebraMap R D π) →+* piQuotient Λ (algebraMap R Λ π)
  rToD_fac :
    rToD.comp (piQuotientMk π) =
      (piQuotientMk (algebraMap R D π)).comp (algebraMap R D)
  cbarModToD_fac :
    cbarModToD.comp
        (piQuotientMk
          (quotientAlgebraMap (R := R) (A := Cbar)
            (Ideal.span ({π ^ 2} : Set R)) π)) =
      cbarToD
  dToLambda_fac :
    dToLambda.comp (piQuotientMk (algebraMap R D π)) =
      (piQuotientMk (algebraMap R Λ π)).comp φ.toRingHom
  left_commutes :
    cbarToD.comp (algebraMap (piQuotient R (π ^ 2)) Cbar) =
      rToD.comp (piSquaredToPi π)
  right_commutes :
    dToLambda.comp cbarToD =
      (piSquaredToPi (algebraMap R Λ π)).comp hbar

/-- A prime of `D` lies over a prime of `\bar C` through the mod-`π` diagram. -/
def LiftingPrimeOver
    {R Λ Cbar D : Type u} [CommRing R] [CommRing Λ] [CommRing Cbar]
    [CommRing D] [Algebra R Λ] [Algebra R D]
    {π : R} [Algebra (piQuotient R (π ^ 2)) Cbar]
    {hbar : Cbar →+* piQuotient Λ ((algebraMap R Λ π) ^ 2)}
    {φ : D →ₐ[R] Λ}
    (diagram : LiftingDiagram π hbar φ)
    (p : PrimeSpectrum Cbar) (q : PrimeSpectrum D) : Prop :=
  quotientAlgebraMap (R := R) (A := Cbar)
      (Ideal.span ({π ^ 2} : Set R)) π ∈ p.asIdeal ∧
    algebraMap R D π ∈ q.asIdeal ∧
    ∃ (pbar : PrimeSpectrum
        (piQuotient Cbar
          (quotientAlgebraMap (R := R) (A := Cbar)
            (Ideal.span ({π ^ 2} : Set R)) π)))
      (qbar : PrimeSpectrum (piQuotient D (algebraMap R D π))),
      PrimeSpectrum.comap
          (piQuotientMk
            (quotientAlgebraMap (R := R) (A := Cbar)
              (Ideal.span ({π ^ 2} : Set R)) π)) pbar = p ∧
        PrimeSpectrum.comap (piQuotientMk (algebraMap R D π)) qbar = q ∧
        PrimeSpectrum.comap diagram.cbarModToD qbar = pbar

/-- Smoothness at a prime of a ring map, using its canonical algebra structure. -/
def IsSmoothAtRingHom
    {A B : Type u} [CommRing A] [CommRing B] (f : A →+* B)
    (q : PrimeSpectrum B) : Prop :=
  letI : Algebra A B := f.toAlgebra
  Formalization.Books.Algebra.Unit137.IsSmoothAt A B q

/-! ## The lifting lemma -/

/-- Elkik's lifting lemma, including its commutative quotient diagram and all
four local properties stated in the source. -/
theorem lifting_lemma
    {R Λ Cbar : Type u} [CommRing R] [CommRing Λ] [CommRing Cbar]
    [Algebra R Λ] [IsNoetherianRing R]
    (π : R) [Algebra (piQuotient R (π ^ 2)) Cbar]
    [Algebra.FinitePresentation (piQuotient R (π ^ 2)) Cbar]
    (hAnnR :
      annihilatorOf (R := R) (M := R) π =
        annihilatorOf (R := R) (M := R) (π ^ 2))
    (hAnnΛ :
      annihilatorOf (R := Λ) (M := Λ) (algebraMap R Λ π) =
        annihilatorOf (R := Λ) (M := Λ) ((algebraMap R Λ π) ^ 2))
    (hbar : Cbar →+* piQuotient Λ ((algebraMap R Λ π) ^ 2))
    (hbar_algebra :
      hbar.comp
          (quotientAlgebraMap (R := R) (A := Cbar)
            (Ideal.span ({π ^ 2} : Set R))) =
        (piQuotientMk ((algebraMap R Λ π) ^ 2)).comp (algebraMap R Λ)) :
    ∃ (D : Type u) (hD : CommRing D) (hRD : Algebra R D),
      letI : CommRing D := hD
      letI : Algebra R D := hRD
      ∃ (φ : D →ₐ[R] Λ),
        ∃ (diagram : LiftingDiagram π hbar φ),
          Algebra.FinitePresentation R D ∧
          (∀ q : PrimeSpectrum D,
            algebraMap R D π ∉ q.asIdeal →
              Formalization.Books.Algebra.Unit137.IsSmoothAt R D q) ∧
          (∀ (p : PrimeSpectrum Cbar) (q : PrimeSpectrum D),
            LiftingPrimeOver diagram p q →
              Formalization.Books.Algebra.Unit137.IsSmoothAt
                (piQuotient R (π ^ 2)) Cbar p →
                Formalization.Books.Algebra.Unit137.IsSmoothAt R D q) ∧
          (∀ (pbar : PrimeSpectrum
              (piQuotient Cbar
                (quotientAlgebraMap (R := R) (A := Cbar)
                  (Ideal.span ({π ^ 2} : Set R)) π)))
              (qbar : PrimeSpectrum (piQuotient D (algebraMap R D π))),
            PrimeSpectrum.comap diagram.cbarModToD qbar = pbar →
            Formalization.Books.Algebra.Unit137.IsSmoothAt
              (piQuotient R (π ^ 2)) Cbar
              (PrimeSpectrum.comap
                (piQuotientMk
                  (quotientAlgebraMap (R := R) (A := Cbar)
                    (Ideal.span ({π ^ 2} : Set R)) π)) pbar) →
            IsSmoothAtRingHom diagram.cbarModToD qbar) := by
  sorry

end

end Formalization.Books.Smoothing.Unit06
