import Formalization.Books.Exercises.Unit31.Core

import Mathlib.Algebra.Algebra.Subalgebra.Basic
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.LinearAlgebra.Dimension.Finite
import Mathlib.NumberTheory.Padics.PadicNumbers

/-!
# Exercises, Chapter 31: Regular functions

The declarations below follow the five numbered exercises in the source.  The
proofs are deferred to the proving stage; the named examples and polynomial
data are retained so that the theorem interfaces expose the source's actual
objects.
-/

namespace Formalization.Books.Exercises.Unit31

open Set

universe u

noncomputable section

/-! ## Exercise `extra-function` -/

/-- The equation `t² = s⁵ + 8` in the two-variable complex affine space. -/
def affineCurveEquation : MvPolynomial (Fin 2) ℂ :=
  MvPolynomial.X (1 : Fin 2) ^ 2 -
    (MvPolynomial.X (0 : Fin 2) ^ 5 + MvPolynomial.C (8 : ℂ))

/-- The affine curve cut out by `affineCurveEquation`. -/
def affineCurve : Set (Fin 2 → ℂ) :=
  MvPolynomial.zeroLocus ℂ (Ideal.span {affineCurveEquation})

/-- The point `(1, 3)` on `affineCurve`. -/
def affineCurvePoint : Fin 2 → ℂ := ![(1 : ℂ), 3]

/-- The punctured curve from the first exercise. -/
def affineCurvePunctured : Set (Fin 2 → ℂ) :=
  affineCurve \ {affineCurvePoint}

/-- The polynomial `s - 1`. -/
def affineCurveSMinusOne : MvPolynomial (Fin 2) ℂ :=
  MvPolynomial.X (0 : Fin 2) - MvPolynomial.C (1 : ℂ)

/-- The polynomial `t + 3`. -/
def affineCurveTPlusThree : MvPolynomial (Fin 2) ℂ :=
  MvPolynomial.X (1 : Fin 2) + MvPolynomial.C (3 : ℂ)

/-- The polynomial `t - 3`. -/
def affineCurveTMinusThree : MvPolynomial (Fin 2) ℂ :=
  MvPolynomial.X (1 : Fin 2) - MvPolynomial.C (3 : ℂ)

/-- The quotient polynomial `(s⁵ - 1)/(s - 1)`. -/
def affineCurveQuotient : MvPolynomial (Fin 2) ℂ :=
  MvPolynomial.X (0 : Fin 2) ^ 4 + MvPolynomial.X (0 : Fin 2) ^ 3 +
    MvPolynomial.X (0 : Fin 2) ^ 2 + MvPolynomial.X (0 : Fin 2) + 1

/-- The extra regular function, written using the two local expressions
`(t + 3)/(s - 1)` and `affineCurveQuotient/(t - 3)`. -/
def affineCurveExtraFunction (z : ↥affineCurvePunctured) : ℂ :=
  if MvPolynomial.aeval z.1 affineCurveSMinusOne ≠ 0 then
    MvPolynomial.aeval z.1 affineCurveTPlusThree /
      MvPolynomial.aeval z.1 affineCurveSMinusOne
  else
    MvPolynomial.aeval z.1 affineCurveQuotient /
      MvPolynomial.aeval z.1 affineCurveTMinusThree

/-- The displayed point lies on the displayed curve. -/
theorem affine_curve_point_mem : affineCurvePoint ∈ affineCurve := by
  sorry

/-- The displayed equation defines an affine variety over `ℂ`. -/
theorem affine_curve_is_affine_variety :
    IsAffineVariety ℂ 2 affineCurve := by
  sorry

/-- The local quotient construction is a regular function on the punctured
curve. -/
theorem affine_curve_extra_function_is_regular :
    IsRegularFunction affineCurvePunctured affineCurveExtraFunction := by
  sorry

/-- The extra function is not induced by an ambient polynomial. -/
theorem affine_curve_extra_function_not_polynomial :
    ¬ IsPolynomialRestriction affineCurvePunctured affineCurveExtraFunction := by
  sorry

/-- There is a regular function on the punctured curve which is not the
restriction of a polynomial in the ambient coordinates. -/
theorem extra_function_on_affine_curve :
    ∃ φ : affineCurvePunctured → ℂ,
      IsRegularFunction affineCurvePunctured φ ∧
        ¬ IsPolynomialRestriction affineCurvePunctured φ := by
  exact ⟨affineCurveExtraFunction,
    affine_curve_extra_function_is_regular,
    affine_curve_extra_function_not_polynomial⟩

/-! ## Exercise `no-extra-function` -/

/-- A regular function on the complement of a finite subset of complex affine
`n`-space is induced by an ambient polynomial when `n ≥ 2`. -/
theorem regular_function_on_finite_complement_is_polynomial
    {n : ℕ} (hn : 2 ≤ n) (E : Set (Fin n → ℂ)) (hE : E.Finite)
    (φ : ↥(Set.univ \ E) → ℂ)
    (hφ : IsRegularFunction (Set.univ \ E) φ) :
    IsPolynomialRestriction (Set.univ \ E) φ := by
  sorry

/-! ## Exercise `cone` -/

/-- An ideal generated by homogeneous polynomials cuts out a cone. -/
theorem homogeneous_generated_zero_locus_is_cone
    {n : ℕ} (p : Ideal (MvPolynomial (Fin n) ℂ))
    (hp : ∃ S : Set (MvPolynomial (Fin n) ℂ), p = Ideal.span S ∧
      ∀ f ∈ S, ∃ d : ℕ, MvPolynomial.IsHomogeneous f d) :
    IsCone (MvPolynomial.zeroLocus ℂ p) := by
  sorry

/-- The prime ideal of a complex affine cone is generated by homogeneous
polynomials. -/
theorem cone_prime_ideal_is_homogeneous_generated
    {n : ℕ} (p : Ideal (MvPolynomial (Fin n) ℂ)) (hp : p.IsPrime)
    (hcone : IsCone (MvPolynomial.zeroLocus ℂ p)) :
    ∃ S : Set (MvPolynomial (Fin n) ℂ), p = Ideal.span S ∧
      ∀ f ∈ S, ∃ d : ℕ, MvPolynomial.IsHomogeneous f d := by
  sorry

/-! ## Exercise `extra-function-cone` -/

/-- The coordinate line `y = 0`, viewed as a cone in complex affine 2-space. -/
def affineLineCone : Set (Fin 2 → ℂ) :=
  MvPolynomial.zeroLocus ℂ
    (Ideal.span ({MvPolynomial.X (1 : Fin 2)} : Set (MvPolynomial (Fin 2) ℂ)))

/-- The punctured coordinate line. -/
def affineLineConePunctured : Set (Fin 2 → ℂ) :=
  affineLineCone \ ({0} : Set (Fin 2 → ℂ))

/-- The inverse of the first coordinate on the punctured coordinate line. -/
def affineLineConeInverse (z : ↥affineLineConePunctured) : ℂ :=
  (z.1 0)⁻¹

/-- The coordinate line is an affine variety. -/
theorem affine_line_cone_is_affine_variety :
    IsAffineVariety ℂ 2 affineLineCone := by
  sorry

/-- The coordinate line is a cone. -/
theorem affine_line_cone_is_cone : IsCone affineLineCone := by
  sorry

/-- The inverse coordinate function is regular on the punctured coordinate
line. -/
theorem affine_line_cone_inverse_is_regular :
    IsRegularFunction affineLineConePunctured affineLineConeInverse := by
  sorry

/-- The inverse coordinate function is not induced by an ambient polynomial. -/
theorem affine_line_cone_inverse_not_polynomial :
    ¬ IsPolynomialRestriction affineLineConePunctured affineLineConeInverse := by
  sorry

/-- An explicit affine cone with a regular function on its puncture which is
not induced by an ambient polynomial. -/
theorem extra_function_on_affine_cone :
    IsAffineVariety ℂ 2 affineLineCone ∧
      IsCone affineLineCone ∧
        IsRegularFunction affineLineConePunctured affineLineConeInverse ∧
          ¬ IsPolynomialRestriction affineLineConePunctured affineLineConeInverse := by
  exact ⟨affine_line_cone_is_affine_variety, affine_line_cone_is_cone,
    affine_line_cone_inverse_is_regular, affine_line_cone_inverse_not_polynomial⟩

/-! ## Exercise `regular-functions` -/

/-- Regular functions are closed under addition. -/
theorem isRegularFunction_add
    {k : Type u} [Field k] {n : ℕ} {Z : Set (Fin n → k)}
    {φ ψ : Z → k} (hφ : IsRegularFunction Z φ)
    (hψ : IsRegularFunction Z ψ) :
    IsRegularFunction Z (φ + ψ) := by
  sorry

/-- Regular functions are closed under multiplication. -/
theorem isRegularFunction_mul
    {k : Type u} [Field k] {n : ℕ} {Z : Set (Fin n → k)}
    {φ ψ : Z → k} (hφ : IsRegularFunction Z φ)
    (hψ : IsRegularFunction Z ψ) :
    IsRegularFunction Z (φ * ψ) := by
  sorry

/-- Constant functions are regular. -/
theorem isRegularFunction_algebraMap
    {k : Type u} [Field k] {n : ℕ} (Z : Set (Fin n → k)) (c : k) :
    IsRegularFunction Z (algebraMap k (Z → k) c) := by
  sorry

/-- The ring of regular functions, with its canonical `k`-algebra structure. -/
def regularFunctionAlgebra {k : Type u} [Field k] {n : ℕ}
    (Z : Set (Fin n → k)) : Subalgebra k (Z → k) where
  carrier := {φ | IsRegularFunction Z φ}
  add_mem' := by
    intro φ ψ hφ hψ
    exact isRegularFunction_add hφ hψ
  mul_mem' := by
    intro φ ψ hφ hψ
    exact isRegularFunction_mul hφ hψ
  algebraMap_mem' c := isRegularFunction_algebraMap Z c

/-! ### Algebraically closed fields -/

/-- On affine space over an algebraically closed field, every regular function
is induced by a polynomial. -/
theorem regular_function_on_affine_space_is_polynomial
    (k : Type u) [Field k] [IsAlgClosed k] (n : ℕ)
    (φ : ↥(Set.univ : Set (Fin n → k)) → k)
    (hφ : IsRegularFunction (Set.univ : Set (Fin n → k)) φ) :
    IsPolynomialRestriction (Set.univ : Set (Fin n → k)) φ := by
  sorry

/-! ### Finite fields -/

/-- Every function on a locally closed subset of affine space over a finite
field is regular. -/
theorem finite_field_every_function_is_regular
    (k : Type u) [Field k] [Finite k] {n : ℕ}
    (Z : Set (Fin n → k)) (hZ : IsZariskiLocallyClosed k n Z)
    (φ : Z → k) :
    IsRegularFunction Z φ := by
  sorry

/-- The ring of regular functions on a locally closed finite affine set is
finite-dimensional over its finite ground field. -/
theorem finite_field_regular_functions_moduleFinite
    (k : Type u) [Field k] [Finite k] {n : ℕ}
    (Z : Set (Fin n → k)) (hZ : IsZariskiLocallyClosed k n Z) :
    Module.Finite k (regularFunctionAlgebra Z) := by
  sorry

/-! ### The real example -/

/-- The everywhere-defined real function `x ↦ 1/(x²+1)` on the affine line.
The affine line is represented by `Fin 1 → ℝ`. -/
def realQuadraticInverse
    (x : ↥(Set.univ : Set (Fin 1 → ℝ))) : ℝ :=
  ((x.1 0) ^ 2 + 1)⁻¹

/-- The polynomial `x² + 1` for the real example. -/
def realQuadratic : MvPolynomial (Fin 1) ℝ :=
  MvPolynomial.X (0 : Fin 1) ^ 2 + MvPolynomial.C (1 : ℝ)

/-- The real quadratic inverse is regular everywhere. -/
theorem real_quadratic_inverse_is_regular :
    IsRegularFunction (Set.univ : Set (Fin 1 → ℝ)) realQuadraticInverse := by
  sorry

/-- The real quadratic inverse is not a polynomial function. -/
theorem real_quadratic_inverse_not_polynomial :
    ¬ IsPolynomialRestriction (Set.univ : Set (Fin 1 → ℝ)) realQuadraticInverse := by
  sorry

/-- A regular function on the real affine line which is not a polynomial. -/
theorem exists_real_regular_function_not_polynomial :
    ∃ φ : ↥(Set.univ : Set (Fin 1 → ℝ)) → ℝ,
      IsRegularFunction (Set.univ : Set (Fin 1 → ℝ)) φ ∧
        ¬ IsPolynomialRestriction (Set.univ : Set (Fin 1 → ℝ)) φ := by
  exact ⟨realQuadraticInverse, real_quadratic_inverse_is_regular,
    real_quadratic_inverse_not_polynomial⟩

/-! ### The p-adic example -/

/-- The everywhere-defined p-adic function `x ↦ 1/(x²-p)` on the affine line.
Here `p` is prime and `ℚ_[p]` is Mathlib's p-adic field. -/
def padicQuadraticInverse (p : ℕ) [Fact p.Prime]
    (x : ↥(Set.univ : Set (Fin 1 → ℚ_[p]))) : ℚ_[p] :=
  ((x.1 0) ^ 2 - (p : ℚ_[p]))⁻¹

/-- The polynomial `x²-p` for the p-adic example. -/
def padicQuadratic (p : ℕ) [Fact p.Prime] :
    MvPolynomial (Fin 1) ℚ_[p] :=
  MvPolynomial.X (0 : Fin 1) ^ 2 - MvPolynomial.C (p : ℚ_[p])

/-- The p-adic quadratic inverse is regular everywhere. -/
theorem padic_quadratic_inverse_is_regular
    (p : ℕ) [Fact p.Prime] :
    IsRegularFunction (Set.univ : Set (Fin 1 → ℚ_[p]))
      (padicQuadraticInverse p) := by
  sorry

/-- The p-adic quadratic inverse is not a polynomial function. -/
theorem padic_quadratic_inverse_not_polynomial
    (p : ℕ) [Fact p.Prime] :
    ¬ IsPolynomialRestriction (Set.univ : Set (Fin 1 → ℚ_[p]))
      (padicQuadraticInverse p) := by
  sorry

/-- A regular function on the p-adic affine line which is not a polynomial. -/
theorem exists_padic_regular_function_not_polynomial
    (p : ℕ) [Fact p.Prime] :
    ∃ φ : ↥(Set.univ : Set (Fin 1 → ℚ_[p])) → ℚ_[p],
      IsRegularFunction (Set.univ : Set (Fin 1 → ℚ_[p])) φ ∧
        ¬ IsPolynomialRestriction (Set.univ : Set (Fin 1 → ℚ_[p])) φ := by
  exact ⟨padicQuadraticInverse p, padic_quadratic_inverse_is_regular p,
    padic_quadratic_inverse_not_polynomial p⟩

end

end Formalization.Books.Exercises.Unit31
