import Mathlib.RingTheory.Finiteness.Ideal
import Mathlib.AlgebraicGeometry.Noetherian
import Mathlib.RingTheory.Ideal.Quotient.Nilpotent
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.Ideal
import Mathlib.RingTheory.MvPolynomial
import Mathlib.RingTheory.Spectrum.Prime.Noetherian
import Mathlib.RingTheory.Spectrum.Prime.Topology
import Mathlib.Algebra.Algebra.Subalgebra.Lattice

/-!
# Examples, Chapter 22: Underlying space Noetherian not Noetherian

This file records the two examples in the source section.  The ring
constructions and the canonical localization correspondence are exposed
directly; the example-specific algebraic and topological facts are theorem
interfaces for the proof stage.
-/

noncomputable section

universe u

open TopologicalSpace

namespace Formalization.«Books.Examples».Unit22

open AlgebraicGeometry

/-!
## The ring with infinitely many square-zero variables
-/

/-- The polynomial ring in the variables indexed by `ℕ`. -/
abbrev ManyVariablesPolynomial (k : Type u) [Field k] := MvPolynomial ℕ k

/-- The ideal generated by the squares of all variables. -/
def manyVariablesSquareIdeal (k : Type u) [Field k] :
    Ideal (ManyVariablesPolynomial k) :=
  Ideal.span (Set.range fun i : ℕ =>
    (MvPolynomial.X i : ManyVariablesPolynomial k) ^ 2)

/-- The quotient ring `k[x₁, x₂, …]/(x₁², x₂², …)`. -/
abbrev ManyVariablesRing (k : Type u) [Field k] :=
  ManyVariablesPolynomial k ⧸ manyVariablesSquareIdeal k

/-- The affine scheme associated to the infinitely-variable quotient. -/
abbrev ManyVariablesScheme (k : Type u) [Field k] : Scheme :=
  Spec (.of (ManyVariablesRing k))

/-- The image of the `i`-th variable in the square-zero quotient. -/
def manyVariablesVariable (k : Type u) [Field k] (i : ℕ) : ManyVariablesRing k :=
  Ideal.Quotient.mk (manyVariablesSquareIdeal k) (MvPolynomial.X i)

/-- The ideal generated by all the quotient variables. -/
def manyVariablesNilIdeal (k : Type u) [Field k] : Ideal (ManyVariablesRing k) :=
  Ideal.span (Set.range (manyVariablesVariable k))

/-- Every displayed variable is square-zero in the quotient. -/
theorem manyVariables_variable_sq_eq_zero (k : Type u) [Field k] (i : ℕ) :
    manyVariablesVariable k i ^ 2 = 0 := by
  sorry

/-- Every prime ideal contains every square-zero variable. -/
theorem manyVariables_variable_mem_of_prime
    (k : Type u) [Field k] (p : Ideal (ManyVariablesRing k))
    (hp : p.IsPrime) (i : ℕ) :
    manyVariablesVariable k i ∈ p := by
  sorry

/-- The ideal generated by all variables is prime. -/
theorem manyVariables_nilIdeal_isPrime (k : Type u) [Field k] :
    (manyVariablesNilIdeal k).IsPrime := by
  sorry

/-- The displayed ideal is the unique prime ideal of the quotient. -/
theorem manyVariables_prime_eq_nilIdeal
    (k : Type u) [Field k] (p : Ideal (ManyVariablesRing k))
    (hp : p.IsPrime) :
    p = manyVariablesNilIdeal k := by
  sorry

/-- The prime spectrum is nonempty and has at most one point. -/
theorem manyVariables_primeSpectrum_is_singleton (k : Type u) [Field k] :
    Nonempty (PrimeSpectrum (ManyVariablesRing k)) ∧
      Subsingleton (PrimeSpectrum (ManyVariablesRing k)) := by
  sorry

/-- The underlying space of the spectrum is Noetherian. -/
theorem manyVariables_primeSpectrum_is_noetherian (k : Type u) [Field k] :
    NoetherianSpace (PrimeSpectrum (ManyVariablesRing k)) := by
  sorry

/-- The unique prime ideal is not finitely generated. -/
theorem manyVariables_nilIdeal_not_fg (k : Type u) [Field k] :
    ¬ (manyVariablesNilIdeal k).FG := by
  sorry

/-- The quotient ring is not Noetherian. -/
theorem manyVariables_ring_not_noetherian (k : Type u) [Field k] :
    ¬ IsNoetherianRing (ManyVariablesRing k) := by
  sorry

/-- The affine scheme is not Noetherian even though its underlying space is. -/
theorem manyVariables_scheme_not_noetherian (k : Type u) [Field k] :
    ¬ IsNoetherian (ManyVariablesScheme k) := by
  sorry

/-!
## The subring generated by the monomials `x y^i`
-/

/-- The ambient polynomial ring in two variables. -/
abbrev ManyMonomialsPolynomial (k : Type u) [Field k] :=
  MvPolynomial (Fin 2) k

/-- The ambient monomial `x y^i`, with variables indexed by `0` and `1`. -/
def manyMonomial (k : Type u) [Field k] (i : ℕ) : ManyMonomialsPolynomial k :=
  MvPolynomial.X (0 : Fin 2) * MvPolynomial.X (1 : Fin 2) ^ i

/-- The `k`-subalgebra generated by all monomials `x y^i`. -/
def manyMonomialsSubalgebra (k : Type u) [Field k] :
    Subalgebra k (ManyMonomialsPolynomial k) :=
  Algebra.adjoin k (Set.range (manyMonomial k))

/-- The source ring `A`, represented by the carrier of its generated subalgebra. -/
abbrev ManyMonomialsRing (k : Type u) [Field k] := manyMonomialsSubalgebra k

/-- The affine scheme associated to the monomial subring. -/
abbrev ManyMonomialsScheme (k : Type u) [Field k] : Scheme :=
  Spec (.of (ManyMonomialsRing k))

/-- The copy in `A` of the generator `x y^i`. -/
def manyMonomialsGenerator (k : Type u) [Field k] (i : ℕ) : ManyMonomialsRing k :=
  ⟨manyMonomial k i, Algebra.subset_adjoin (Set.mem_range_self i)⟩

/-- The element `x = x y^0` in `A`. -/
def manyMonomialsX (k : Type u) [Field k] : ManyMonomialsRing k :=
  manyMonomialsGenerator k 0

/-- The localization `A_x`. -/
abbrev ManyMonomialsLocalization (k : Type u) [Field k] :=
  Localization.Away (manyMonomialsX k)

/-- The ring `k[x, x⁻¹, y]`, represented as the localization of `k[x,y]` at `x`. -/
abbrev ManyMonomialsLaurentPolynomial (k : Type u) [Field k] :=
  Localization.Away (MvPolynomial.X (0 : Fin 2) : ManyMonomialsPolynomial k)

/-- For a prime of `A`, avoiding the powers of `x` means not containing `x`. -/
theorem manyMonomials_prime_disjoint_powers_iff_not_mem
    (k : Type u) [Field k] (p : PrimeSpectrum (ManyMonomialsRing k)) :
    Disjoint (Submonoid.powers (manyMonomialsX k) : Set (ManyMonomialsRing k))
        p.asIdeal ↔ manyMonomialsX k ∉ p.asIdeal := by
  exact @Ideal.disjoint_powers_iff_notMem_of_isPrime
    (ManyMonomialsRing k) _ p.asIdeal p.isPrime (manyMonomialsX k)

/-- Prime spectra of `A_x` and of primes of `A` not containing `x`.

This is Mathlib's canonical localization correspondence, transported across
the standard prime-ideal formulation of avoiding the powers of `x`.
-/
noncomputable def manyMonomials_away_primeSpectrum_orderIso (k : Type u) [Field k] :
    PrimeSpectrum (ManyMonomialsLocalization k) ≃o
      {p : PrimeSpectrum (ManyMonomialsRing k) //
        manyMonomialsX k ∉ p.asIdeal} :=
  (IsLocalization.primeSpectrumOrderIso
      (Submonoid.powers (manyMonomialsX k)) (ManyMonomialsLocalization k)).trans
    { toFun := fun p =>
        ⟨p.1, (manyMonomials_prime_disjoint_powers_iff_not_mem k p.1).mp p.2⟩
      invFun := fun p =>
        ⟨p.1, (manyMonomials_prime_disjoint_powers_iff_not_mem k p.1).mpr p.2⟩
      left_inv := by intro p; rfl
      right_inv := by intro p; rfl
      map_rel_iff' := by intro p q; rfl }

/-- The localization `A_x` is isomorphic to `k[x,x⁻¹,y]`. -/
theorem manyMonomials_localization_equiv_laurent (k : Type u) [Field k] :
    Nonempty (ManyMonomialsLocalization k ≃+* ManyMonomialsLaurentPolynomial k) := by
  sorry

/-- The Laurent polynomial ring occurring in the localization is Noetherian. -/
theorem manyMonomials_laurentPolynomial_is_noetherian (k : Type u) [Field k] :
    IsNoetherianRing (ManyMonomialsLaurentPolynomial k) := by
  sorry

/-- The spectrum of the Laurent polynomial ring is Noetherian. -/
theorem manyMonomials_laurent_primeSpectrum_is_noetherian
    (k : Type u) [Field k] :
    NoetherianSpace (PrimeSpectrum (ManyMonomialsLaurentPolynomial k)) := by
  sorry

/-- The ideal generated by all monomials `x y^i`. -/
def manyMonomialsContainingXIdeal (k : Type u) [Field k] :
    Ideal (ManyMonomialsRing k) :=
  Ideal.span (Set.range (manyMonomialsGenerator k))

/-- The square identity used to force all generators into a prime containing `x`. -/
theorem manyMonomials_generator_square_eq (k : Type u) [Field k] (i : ℕ) :
    manyMonomialsGenerator k i ^ 2 =
      manyMonomialsX k * manyMonomialsGenerator k (2 * i) := by
  sorry

/-- The ideal generated by all monomials is prime. -/
theorem manyMonomials_containingXIdeal_isPrime (k : Type u) [Field k] :
    (manyMonomialsContainingXIdeal k).IsPrime := by
  sorry

/-- A prime containing `x` contains every monomial `x y^i`. -/
theorem manyMonomials_generator_mem_of_prime_of_x_mem
    (k : Type u) [Field k] (p : Ideal (ManyMonomialsRing k))
    (hp : p.IsPrime) (hx : manyMonomialsX k ∈ p) (i : ℕ) :
    manyMonomialsGenerator k i ∈ p := by
  sorry

/-- A prime containing `x` is the ideal generated by all the monomials. -/
theorem manyMonomials_prime_eq_containingXIdeal_of_x_mem
    (k : Type u) [Field k] (p : Ideal (ManyMonomialsRing k))
    (hp : p.IsPrime) (hx : manyMonomialsX k ∈ p) :
    p = manyMonomialsContainingXIdeal k := by
  sorry

/-- The distinguished prime point containing `x`. -/
def manyMonomialsSpecialPrime (k : Type u) [Field k] :
    PrimeSpectrum (ManyMonomialsRing k) :=
  ⟨manyMonomialsContainingXIdeal k, manyMonomials_containingXIdeal_isPrime k⟩

/-- The spectrum consists of the localization part and the distinguished point. -/
theorem manyMonomials_primeSpectrum_eq_away_union_specialPrime
    (k : Type u) [Field k] :
    (Set.univ : Set (PrimeSpectrum (ManyMonomialsRing k))) =
      Set.range (PrimeSpectrum.comap
        (algebraMap (ManyMonomialsRing k) (ManyMonomialsLocalization k))) ∪
        {manyMonomialsSpecialPrime k} := by
  sorry

/-- The underlying space of `Spec A` is Noetherian. -/
theorem manyMonomials_primeSpectrum_is_noetherian (k : Type u) [Field k] :
    NoetherianSpace (PrimeSpectrum (ManyMonomialsRing k)) := by
  sorry

/-- The distinguished prime ideal is not finitely generated. -/
theorem manyMonomials_containingXIdeal_not_fg (k : Type u) [Field k] :
    ¬ (manyMonomialsContainingXIdeal k).FG := by
  sorry

/-- The monomial subring is not Noetherian. -/
theorem manyMonomials_ring_not_noetherian (k : Type u) [Field k] :
    ¬ IsNoetherianRing (ManyMonomialsRing k) := by
  sorry

/-- The affine monomial scheme is not Noetherian. -/
theorem manyMonomials_scheme_not_noetherian (k : Type u) [Field k] :
    ¬ IsNoetherian (ManyMonomialsScheme k) := by
  sorry

/-- The monomial subring is a domain. -/
theorem manyMonomials_ring_is_domain (k : Type u) [Field k] :
    IsDomain (ManyMonomialsRing k) := by
  infer_instance

end Formalization.«Books.Examples».Unit22
