import Formalization.Books.Smoothing.Unit09.LocalTricks
import Mathlib.FieldTheory.Separable
import Mathlib.RingTheory.RegularLocalRing.Defs

/-!
# Smoothing Ring Maps, Chapter 10: Separable residue fields

This file records the three precise statements in the source section.  The
kernel statements use scalar multiplication endomorphisms, while the
resolution statement reuses Chapter 9's local situation and resolution
interfaces.
-/

namespace Formalization.Books.Smoothing.Unit10

open Formalization.Books.Algebra.Unit03
open Formalization.Books.Smoothing.Unit09

noncomputable section

universe u v

/-! ## Kernel stabilization -/

/- The kernel of multiplication by an element on a module.  This is the
   canonical scalar action map, rather than a parallel notion of annihilator. -/
def scalarKernel
    {R : Type u} {M : Type v} [CommRing R] [AddCommGroup M] [Module R M]
    (r : R) : Submodule R M :=
  LinearMap.ker (algebraMap R (Module.End R M) r)

/- The localized version of `scalarKernel`, with the scalar first mapped to
   the canonical ring localization. -/
noncomputable def localizedScalarKernel
    {R : Type u} {M : Type v} [CommRing R] [AddCommGroup M] [Module R M]
    (S : Submonoid R) (r : R) :
    Submodule (Localization S) (LocalizedModule S M) :=
  LinearMap.ker
    (algebraMap (Localization S)
      (Module.End (Localization S) (LocalizedModule S M))
      (algebraMap R (Localization S) r))

/-! Ogoma's kernel-stabilization lemma. -/

theorem ogoma_kernel_stabilization
    {A : Type u} {M : Type v} [CommRing A] [AddCommGroup M]
    [Module A M] [IsNoetherianRing A] [Module.Finite A M]
    (S : Submonoid A) (π : A)
    (hker : localizedScalarKernel (R := A) (M := M) S π =
      localizedScalarKernel (R := A) (M := M) S (π ^ 2)) :
    ∃ s : S, ∀ n : ℕ, 0 < n →
      scalarKernel (R := A) (M := M) ((s : A) ^ n * π) =
        scalarKernel (R := A) (M := M) (((s : A) ^ n * π) ^ 2) := by
  sorry

/-! ## Sequences in a regular local ring -/

/- The ideal generated by the `e`-th powers preceding the index `i`. -/
def priorPowerIdeal
    {Λ : Type u} [CommRing Λ] {d : ℕ} (π : Fin d → Λ) (e : ℕ) (i : Fin d) :
    Ideal Λ :=
  Ideal.span {x | ∃ j : Fin d, j.val < i.val ∧ x = (π j) ^ e}

/- The annihilator of an element in the quotient by the preceding powers. -/
def priorPowerAnnihilator
    {Λ : Type u} [CommRing Λ] {d : ℕ} (π : Fin d → Λ) (e : ℕ) (i : Fin d)
    (x : Λ) : Ideal (Λ ⧸ priorPowerIdeal π e i) :=
  annihilatorOf (R := Λ ⧸ priorPowerIdeal π e i)
    (M := Λ ⧸ priorPowerIdeal π e i) (Ideal.Quotient.mk _ x)

/-! The sequence-selection lemma in the source. -/

theorem exists_sequence_in_regular_localization
    {Λ : Type u} [CommRing Λ] [IsNoetherianRing Λ]
    (I q : Ideal Λ) [hq : q.IsPrime]
    (n e d : ℕ) (hn : 0 < n) (he : 0 < e)
    (hIq : I ≤ q)
    (hqn : Ideal.map (algebraMap Λ (Localization.AtPrime q)) (q ^ n) ≤
      Ideal.map (algebraMap Λ (Localization.AtPrime q)) I)
    (hdim : ringKrullDim (Localization.AtPrime q) = d)
    (hregular : IsRegularLocalRing (Localization.AtPrime q)) :
    ∃ π : Fin d → Λ,
      Ideal.span (Set.range (fun i : Fin d =>
        algebraMap Λ (Localization.AtPrime q) (π i))) =
          Ideal.map (algebraMap Λ (Localization.AtPrime q)) q ∧
      (∀ i : Fin d, (π i) ^ n ∈ I) ∧
      (∀ i : Fin d,
        priorPowerAnnihilator π e i (π i) =
          priorPowerAnnihilator π e i ((π i) ^ 2)) := by
  sorry

/-! ## Resolution with separable residue field -/

/-! The local resolution lemma for a separable residue-field extension. -/

theorem resolve_special
    {k A Λ : Type u} [Field k] [CommRing A] [CommRing Λ]
    [Algebra k A] [Algebra k Λ] [IsNoetherianRing Λ]
    (s : LocalSituation k A Λ)
    (hq : Ideal.IsMinimalPrime (localDefect s) s.q.asIdeal)
    (hregular : IsRegularLocalRing (Localization.AtPrime s.q.asIdeal))
    [Algebra.IsSeparable k s.q.asIdeal.ResidueField] :
    CanBeResolved s := by
  sorry

end

end Formalization.Books.Smoothing.Unit10
