import Mathlib.RingTheory.AdicCompletion.Algebra
import Mathlib.RingTheory.AdicCompletion.Completeness
import Mathlib.RingTheory.Ideal.IsPrincipal
import Mathlib.RingTheory.MvPolynomial
import Mathlib.Data.PNat.Notation

/-!
# Examples, Chapter 8: Noncomplete quotient

This file formalizes the explicit example in the source section
“Noncomplete quotient”.  The normal-form and non-completeness arguments are
recorded as theorem interfaces; the ring, ideals, completion, and the
distinguished Cauchy element use Mathlib's concrete constructions.
-/

noncomputable section

universe u

open scoped BigOperators

namespace Formalization.«Books.Examples».Unit08

/-- The countable family of variables used in the quotient-ring example. -/
inductive NoncompleteQuotientVariable where
  | t
  | z (i : ℕ+)
  | w (i : ℕ+)
  | x
deriving DecidableEq

/-- The polynomial ring before imposing the relations from the source. -/
abbrev NoncompleteQuotientPolynomial (k : Type u) [Field k] :=
  MvPolynomial NoncompleteQuotientVariable k

/-- The two families of relations defining the quotient ring. -/
def noncompleteQuotientRelationSet (k : Type u) [Field k] :
    Set (NoncompleteQuotientPolynomial k) :=
  Set.range (fun i : ℕ+ =>
    MvPolynomial.X (.z i) * MvPolynomial.X .t -
      MvPolynomial.X .x ^ (i : ℕ) * MvPolynomial.X (.w i)) ∪
    Set.range (fun ij : ℕ+ × ℕ+ =>
      MvPolynomial.X (.z ij.1) * MvPolynomial.X (.w ij.2))

/-- The ideal generated by `zᵢ t - xⁱ wᵢ` and `zᵢ wⱼ`. -/
def noncompleteQuotientRelationIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientPolynomial k) :=
  Ideal.span (noncompleteQuotientRelationSet k)

/-- The ring `k[t,z₁,z₂,…,w₁,w₂,…,x]/(zᵢt-xⁱwᵢ,zᵢwⱼ)`. -/
abbrev NoncompleteQuotientRing (k : Type u) [Field k] :=
  NoncompleteQuotientPolynomial k ⧸ noncompleteQuotientRelationIdeal k

/-- The quotient map on polynomials. -/
def quotientOfPolynomial {k : Type u} [Field k]
    (p : NoncompleteQuotientPolynomial k) : NoncompleteQuotientRing k :=
  Ideal.Quotient.mk (noncompleteQuotientRelationIdeal k) p

/-- The image in the quotient ring of a polynomial variable. -/
def quotientVariable {k : Type u} [Field k]
    (v : NoncompleteQuotientVariable) : NoncompleteQuotientRing k :=
  quotientOfPolynomial (MvPolynomial.X v)

def tElement (k : Type u) [Field k] : NoncompleteQuotientRing k :=
  quotientVariable (.t : NoncompleteQuotientVariable)

def xElement (k : Type u) [Field k] : NoncompleteQuotientRing k :=
  quotientVariable (.x : NoncompleteQuotientVariable)

def zElement (k : Type u) [Field k] (i : ℕ+) : NoncompleteQuotientRing k :=
  quotientVariable (.z i)

def wElement (k : Type u) [Field k] (i : ℕ+) : NoncompleteQuotientRing k :=
  quotientVariable (.w i)

/-- The defining relation `zᵢt = xⁱwᵢ` in the quotient. -/
theorem zElement_mul_tElement (k : Type u) [Field k] (i : ℕ+) :
    zElement k i * tElement k = xElement k ^ (i : ℕ) * wElement k i := by
  sorry

/-- The defining relation `zᵢwⱼ = 0` in the quotient. -/
theorem zElement_mul_wElement (k : Type u) [Field k] (i j : ℕ+) :
    zElement k i * wElement k j = 0 := by
  sorry

/-- The further relation `zᵢzⱼt = 0` noted in the source. -/
theorem zElement_mul_zElement_mul_tElement (k : Type u) [Field k] (i j : ℕ+) :
    zElement k i * zElement k j * tElement k = 0 := by
  sorry

/-- A monomial has no `x`, `zᵢt`, or `zᵢwⱼ` factor. -/
def IsReducedNoncompleteQuotientMonomial
    (m : NoncompleteQuotientVariable →₀ ℕ) : Prop :=
  m .x = 0 ∧
    (m .t = 0 ∨ ∀ i, m (.z i) = 0) ∧
    ∀ i, m (.z i) = 0 ∨ ∀ j, m (.w j) = 0

/-- A coefficient polynomial in the source's canonical normal form. -/
def IsReducedNoncompleteQuotientCoefficient
    {k : Type u} [Field k] (p : NoncompleteQuotientPolynomial k) : Prop :=
  ∀ m ∈ p.support, IsReducedNoncompleteQuotientMonomial m

/-- The value of a finite coefficient expansion in the quotient ring. -/
def noncompleteQuotientFiniteExpansionValue
    {k : Type u} [Field k] (coeff : ℕ → NoncompleteQuotientPolynomial k)
    (s : Finset ℕ) : NoncompleteQuotientRing k :=
  ∑ i ∈ s, quotientOfPolynomial (coeff i) * xElement k ^ i

/-- The source's canonical finite expansion predicate. -/
def HasCanonicalNoncompleteQuotientFiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientRing k)
    (coeff : ℕ → NoncompleteQuotientPolynomial k) : Prop :=
  (∀ i, IsReducedNoncompleteQuotientCoefficient (coeff i)) ∧
    ∃ s : Finset ℕ,
      (∀ i, coeff i ≠ 0 ↔ i ∈ s) ∧
        f = noncompleteQuotientFiniteExpansionValue coeff s

/-- Every element has a unique finite expansion in the source's normal form. -/
theorem existsUnique_canonicalNoncompleteQuotientFiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientRing k) :
    ∃! coeff : ℕ → NoncompleteQuotientPolynomial k,
      HasCanonicalNoncompleteQuotientFiniteExpansion f coeff := by
  sorry

/-- The principal ideal `(x)` and its powers in the quotient ring. -/
def noncompleteQuotientXIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientRing k) :=
  Ideal.span {xElement k}

def noncompleteQuotientXIdealPow (k : Type u) [Field k] (n : ℕ) :
    Ideal (NoncompleteQuotientRing k) :=
  noncompleteQuotientXIdeal k ^ n

/-- The principal ideal `(t)` in the quotient ring. -/
def noncompleteQuotientTIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientRing k) :=
  Ideal.span {tElement k}

/-- Membership in `(xⁿ)` is detected by the first `n` canonical coefficients. -/
theorem mem_noncompleteQuotientXIdealPow_iff
    {k : Type u} [Field k] {f : NoncompleteQuotientRing k}
    {coeff : ℕ → NoncompleteQuotientPolynomial k}
    (hcoeff : HasCanonicalNoncompleteQuotientFiniteExpansion f coeff) (n : ℕ) :
    f ∈ noncompleteQuotientXIdealPow k n ↔ ∀ i < n, coeff i = 0 := by
  sorry

/-- The element `x` is a nonzerodivisor. -/
theorem noncompleteQuotientX_isRegular (k : Type u) [Field k] :
    IsRegular (xElement k) := by
  sorry

/-- The quotient ring is `(x)`-adically separated. -/
theorem iInf_noncompleteQuotientXIdealPow_eq_bot (k : Type u) [Field k] :
    (⨅ n : ℕ, noncompleteQuotientXIdealPow k n) = ⊥ := by
  sorry

/-- The `(x)`-adic completion of the quotient ring. -/
abbrev NoncompleteQuotientCompletion (k : Type u) [Field k] :=
  AdicCompletion (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k)

/-- The image of a base-ring element in its adic completion. -/
def noncompleteQuotientCompletionOf {k : Type u} [Field k]
    (r : NoncompleteQuotientRing k) : NoncompleteQuotientCompletion k :=
  AdicCompletion.of (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k) r

/-- The `(x)` ideal of the completed ring. -/
def noncompleteQuotientCompletionXIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientCompletion k) :=
  (noncompleteQuotientXIdeal k).map
    (algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k))

/-- The image of `(t)` in the completed ring. -/
def noncompleteQuotientCompletionTIdeal (k : Type u) [Field k] :
    Ideal (NoncompleteQuotientCompletion k) :=
  (noncompleteQuotientTIdeal k).map
    (algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k))

/-- A finite partial sum of the source's infinite expansion. -/
def noncompleteQuotientFinitePartialSum
    {k : Type u} [Field k] (coeff : ℕ → NoncompleteQuotientPolynomial k)
    (n : ℕ) : NoncompleteQuotientRing k :=
  ∑ i ∈ Finset.range n, quotientOfPolynomial (coeff i) * xElement k ^ i

/-- An element of the completion is represented by a compatible infinite expansion. -/
def HasCanonicalNoncompleteQuotientInfiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientCompletion k)
    (coeff : ℕ → NoncompleteQuotientPolynomial k) : Prop :=
  (∀ i, IsReducedNoncompleteQuotientCoefficient (coeff i)) ∧
    ∀ n,
      AdicCompletion.evalₐ (noncompleteQuotientXIdeal k) n f =
        Ideal.Quotient.mk (noncompleteQuotientXIdeal k ^ n)
          (noncompleteQuotientFinitePartialSum coeff n)

/-- Every completed element has a unique infinite expansion in canonical form. -/
theorem existsUnique_canonicalNoncompleteQuotientInfiniteExpansion
    {k : Type u} [Field k] (f : NoncompleteQuotientCompletion k) :
    ∃! coeff : ℕ → NoncompleteQuotientPolynomial k,
      HasCanonicalNoncompleteQuotientInfiniteExpansion f coeff := by
  sorry

/-- The finite partial sums defining `Σ i≥1, xⁱwᵢ`. -/
def noncompleteQuotientBadPartialSum (k : Type u) [Field k] (n : ℕ) :
    NoncompleteQuotientRing k :=
  ∑ i ∈ Finset.range n,
    xElement k ^ (i + 1) * wElement k ⟨i + 1, Nat.succ_pos i⟩

/-- The partial sums form an `x`-adic Cauchy sequence. -/
theorem noncompleteQuotientBadPartialSum_isAdicCauchy
    (k : Type u) [Field k] :
    AdicCompletion.IsAdicCauchy (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k)
      (noncompleteQuotientBadPartialSum k) := by
  sorry

/-- The Cauchy sequence of partial sums as a Mathlib adic Cauchy sequence. -/
def noncompleteQuotientBadCauchySequence (k : Type u) [Field k] :
    AdicCompletion.AdicCauchySequence (noncompleteQuotientXIdeal k)
      (NoncompleteQuotientRing k) :=
  ⟨noncompleteQuotientBadPartialSum k,
    noncompleteQuotientBadPartialSum_isAdicCauchy k⟩

/-- The completed element `f = xw₁ + x²w₂ + x³w₃ + ⋯`. -/
def noncompleteQuotientBadElement (k : Type u) [Field k] :
    NoncompleteQuotientCompletion k :=
  AdicCompletion.mk (noncompleteQuotientXIdeal k) (NoncompleteQuotientRing k)
    (noncompleteQuotientBadCauchySequence k)

/-- The coefficients `f₀ = 0` and `fₙ = wₙ` for `n ≥ 1`. -/
def noncompleteQuotientBadCoefficient (k : Type u) [Field k] (n : ℕ) :
    NoncompleteQuotientPolynomial k :=
  if h : n = 0 then 0 else MvPolynomial.X (.w ⟨n, Nat.pos_of_ne_zero h⟩)

/-- The displayed infinite sum has the expected canonical coefficients. -/
theorem noncompleteQuotientBadElement_has_infinite_expansion
    (k : Type u) [Field k] :
    HasCanonicalNoncompleteQuotientInfiniteExpansion
      (noncompleteQuotientBadElement k) (noncompleteQuotientBadCoefficient k) := by
  sorry

/-- Each summand `xⁱwᵢ` belongs to `(t)`, by the relation `zᵢt = xⁱwᵢ`. -/
theorem noncompleteQuotientX_pow_mul_w_mem_t (k : Type u) [Field k] (i : ℕ+) :
    xElement k ^ (i : ℕ) * wElement k i ∈ noncompleteQuotientTIdeal k := by
  sorry

/-- The bad element lies in `(t, xⁿ)` for every `n`. -/
def noncompleteQuotientCompletionMixedIdeal (k : Type u) [Field k] (n : ℕ) :
    Ideal (NoncompleteQuotientCompletion k) :=
  noncompleteQuotientCompletionTIdeal k ⊔
    noncompleteQuotientCompletionXIdeal k ^ n

theorem noncompleteQuotientBadElement_mem_completionMixedIdeal
    (k : Type u) [Field k] (n : ℕ) :
    noncompleteQuotientBadElement k ∈ noncompleteQuotientCompletionMixedIdeal k n := by
  sorry

/-- The bad element is not in `(t)` in the completed ring. -/
theorem noncompleteQuotientBadElement_not_mem_completionTIdeal
    (k : Type u) [Field k] :
    noncompleteQuotientBadElement k ∉ noncompleteQuotientCompletionTIdeal k := by
  sorry

/-- The completion is complete for the image of `(x)`. -/
theorem noncompleteQuotientCompletion_isAdicComplete
    (k : Type u) [Field k] :
    IsAdicComplete (noncompleteQuotientCompletionXIdeal k)
      (NoncompleteQuotientCompletion k) := by
  change IsAdicComplete
    ((noncompleteQuotientXIdeal k).map
      (algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k)))
    (NoncompleteQuotientCompletion k)
  exact (IsAdicComplete.map_algebraMap_iff
      (I := noncompleteQuotientXIdeal k)
      (M := NoncompleteQuotientCompletion k)).mpr
    (AdicCompletion.isAdicComplete
      (I := noncompleteQuotientXIdeal k)
      (M := NoncompleteQuotientRing k)
      (show Submodule.IsPrincipal
          (noncompleteQuotientXIdeal k :
            Submodule (NoncompleteQuotientRing k) (NoncompleteQuotientRing k)) from
        ⟨xElement k, rfl⟩).fg)

/-- The quotient by `(t)` is not complete for the image of `(x)`. -/
theorem noncompleteQuotientCompletion_quotient_not_isAdicComplete
    (k : Type u) [Field k] :
    ¬ IsAdicComplete (noncompleteQuotientCompletionXIdeal k)
      (NoncompleteQuotientCompletion k ⧸ noncompleteQuotientCompletionTIdeal k) := by
  sorry

theorem noncompleteQuotientCompletionXIdeal_isPrincipal
    (k : Type u) [Field k] :
    Submodule.IsPrincipal
      (noncompleteQuotientCompletionXIdeal k :
        Submodule (NoncompleteQuotientCompletion k) (NoncompleteQuotientCompletion k)) := by
  refine ⟨algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k)
      (xElement k), ?_⟩
  simp [noncompleteQuotientCompletionXIdeal, noncompleteQuotientXIdeal, Ideal.map_span]

theorem noncompleteQuotientCompletionTIdeal_isPrincipal
    (k : Type u) [Field k] :
    Submodule.IsPrincipal
      (noncompleteQuotientCompletionTIdeal k :
        Submodule (NoncompleteQuotientCompletion k) (NoncompleteQuotientCompletion k)) := by
  refine ⟨algebraMap (NoncompleteQuotientRing k) (NoncompleteQuotientCompletion k)
      (tElement k), ?_⟩
  simp [noncompleteQuotientCompletionTIdeal, noncompleteQuotientTIdeal, Ideal.map_span]

/-- A reusable witness for the final existential statement of the source. -/
structure PrincipalNoncompleteQuotientExample (R : Type u) [CommRing R] where
  ideal : Ideal R
  quotientIdeal : Ideal R
  ideal_principal : Submodule.IsPrincipal (ideal : Submodule R R)
  quotientIdeal_principal : Submodule.IsPrincipal (quotientIdeal : Submodule R R)
  complete : IsAdicComplete ideal R
  quotient_not_complete : ¬ IsAdicComplete ideal (R ⧸ quotientIdeal)

/-- There is a complete ring with principal `I` and `J` whose quotient is not complete. -/
theorem exists_principal_noncomplete_quotient_example
    (k : Type u) [Field k] :
    Nonempty (PrincipalNoncompleteQuotientExample (NoncompleteQuotientCompletion k)) := by
  refine ⟨{
    ideal := noncompleteQuotientCompletionXIdeal k
    quotientIdeal := noncompleteQuotientCompletionTIdeal k
    ideal_principal := noncompleteQuotientCompletionXIdeal_isPrincipal k
    quotientIdeal_principal := noncompleteQuotientCompletionTIdeal_isPrincipal k
    complete := noncompleteQuotientCompletion_isAdicComplete k
    quotient_not_complete := noncompleteQuotientCompletion_quotient_not_isAdicComplete k
  }⟩

end Formalization.«Books.Examples».Unit08
