import Formalization.«Books.Brauer».Unit01.Wedderburn
import Mathlib.Algebra.Algebra.Subalgebra.Centralizer
import Mathlib.Algebra.Central.Matrix
import Mathlib.Algebra.Central.TensorProduct
import Mathlib.Algebra.Module.LinearMap.Basic
import Mathlib.LinearAlgebra.Matrix.Ideal
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.RingTheory.Morita.Matrix
import Mathlib.RingTheory.SimpleModule.Isotypic
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.RingTheory.TwoSidedIdeal.Operations

/-!
# Lemmas on algebras

This file records the centralizer, tensor-product, matrix-module, and
endomorphism-ring interfaces used in Section 4 of the source.
-/

namespace Formalization.Books.Brauer

universe u v

open scoped TensorProduct Matrix.Module

section TensorSubspaces

variable (k V K : Type*)

/-- Left multiplication by an element of the second tensor factor. -/
def tensorLeftMultiply [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [SMulCommClass k K K]
    (c : K) : V ⊗[k] K →ₗ[k] V ⊗[k] K :=
  TensorProduct.map (LinearMap.id : V →ₗ[k] V) (LinearMap.mulLeft k c)

/-- Right multiplication by an element of the second tensor factor. -/
def tensorRightMultiply [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [IsScalarTower k K K]
    (c : K) : V ⊗[k] K →ₗ[k] V ⊗[k] K :=
  TensorProduct.map (LinearMap.id : V →ₗ[k] V) (LinearMap.mulRight k c)

/-- The source's notion of a two-sided `K`-subspace. -/
def TwoSidedKSubspace [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [SMulCommClass k K K] [IsScalarTower k K K]
    (W : Submodule k (V ⊗[k] K)) : Prop :=
  (∀ c x, x ∈ W → tensorLeftMultiply k V K c x ∈ W) ∧
    ∀ c x, x ∈ W → tensorRightMultiply k V K c x ∈ W

/-- The left `K`-span of a set in a tensor product. -/
def leftKSpan [CommSemiring k] [AddCommGroup V] [Module k V]
    [Semiring K] [Module k K] [SMulCommClass k K K]
    (s : Set (V ⊗[k] K)) : Submodule k (V ⊗[k] K) :=
  Submodule.span k {z | ∃ c : K, ∃ x ∈ s, z = tensorLeftMultiply k V K c x}

end TensorSubspaces

section TensorIdeals

variable (k A K : Type*)

/-- The two-sided ideal generated by pure tensors from a two-sided ideal. -/
def tensorTwoSidedIdeal [CommRing k] [Ring A] [Algebra k A]
    [DivisionRing K] [Algebra k K] (J : TwoSidedIdeal A) :
    TwoSidedIdeal (A ⊗[k] K) :=
  TwoSidedIdeal.span {z | ∃ a : A, a ∈ J ∧ ∃ c : K, z = a ⊗ₜ[k] c}

end TensorIdeals

section Centralizers

theorem centralizer_tensor_product (k A A' : Type*) [CommSemiring k]
    [Semiring A] [Algebra k A] [Semiring A'] [Algebra k A']
    (B : Subalgebra k A) (B' : Subalgebra k A') :
    Subalgebra.centralizer k
        (Algebra.TensorProduct.map B.val B'.val).range =
      (Algebra.TensorProduct.map
        (Subalgebra.centralizer k (B : Set A)).val
        (Subalgebra.centralizer k (B' : Set A')).val).range := by
  sorry

theorem center_finite_simple_is_finite_field_extension (k A : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A] :
    Nonempty (Field (Subalgebra.center k A)) ∧
      FiniteDimensional k (Subalgebra.center k A) := by
  sorry

end Centralizers

section GeneratedSubspaces

theorem two_sided_subspace_generated (k V K : Type*) [Field k]
    [AddCommGroup V] [Module k V] [DivisionRing K] [Algebra k K]
    [Algebra.IsCentral k K] (W : Submodule k (V ⊗[k] K))
    (hW : TwoSidedKSubspace k V K W) :
    W = leftKSpan k V K
      {z | ∃ v : V, z = v ⊗ₜ[k] (1 : K) ∧ z ∈ W} := by
  sorry

theorem two_sided_ideal_tensor (k A K : Type*) [Field k] [Ring A]
    [Algebra k A] [DivisionRing K] [Algebra k K] [Algebra.IsCentral k K] :
    ∀ I : TwoSidedIdeal (A ⊗[k] K),
      ∃ J : TwoSidedIdeal A, I = tensorTwoSidedIdeal k A K J := by
  sorry

theorem tensor_product_simple_of_simple (k A K : Type*) [Field k] [Ring A]
    [Algebra k A] [IsSimpleRing A] [DivisionRing K] [Algebra k K]
    [Algebra.IsCentral k K] : IsSimpleRing (A ⊗[k] K) := by
  sorry

theorem tensor_product_simple_of_simple_algebras (k A A' : Type*) [Field k]
    [Ring A] [Algebra k A] [IsSimpleRing A]
    [Ring A'] [Algebra k A'] [IsSimpleRing A']
    [FiniteDimensional k A'] [Algebra.IsCentral k A'] :
    IsSimpleRing (A ⊗[k] A') := by
  sorry

theorem tensor_product_simple_of_simple_algebras_left (k A A' : Type*)
    [Field k] [Ring A] [Algebra k A] [IsSimpleRing A]
    [FiniteDimensional k A] [Algebra.IsCentral k A]
    [Ring A'] [Algebra k A'] [IsSimpleRing A'] :
    IsSimpleRing (A ⊗[k] A') := by
  sorry

end GeneratedSubspaces

section MatrixAlgebras

def matrix_module_category_equivalence (R : Type*) (n : ℕ) [Ring R]
    (i : Fin n) :
    ModuleCat R ≌ ModuleCat (Matrix (Fin n) (Fin n) R) := by
  classical
  exact ModuleCat.matrixEquivalence R i

def matrix_two_sided_ideal_order_iso (R : Type*) (n : ℕ) [Ring R]
    [NeZero n] :
    TwoSidedIdeal R ≃o TwoSidedIdeal (Matrix (Fin n) (Fin n) R) := by
  classical
  exact TwoSidedIdeal.orderIsoMatrix (R := R) (n := Fin n)

theorem matrix_center_eq_scalar_image (R : Type*) (n : ℕ) [Semiring R]
    : Set.center (Matrix (Fin n) (Fin n) R) =
      Matrix.scalar (Fin n) '' Set.center R := by
  exact Matrix.center_eq_scalar_image

theorem matrix_standard_module_is_simple (K : Type*) (n : ℕ) [DivisionRing K]
    [NeZero n] :
    IsSimpleModule (Matrix (Fin n) (Fin n) K) (Fin n → K) := by
  sorry

theorem matrix_standard_module_end (K : Type*) (n : ℕ) [DivisionRing K]
    [NeZero n] :
    Nonempty
      (Module.End (Matrix (Fin n) (Fin n) K) (Fin n → K) ≃+* Kᵐᵒᵖ) := by
  sorry

end MatrixAlgebras

section SimpleModules

theorem finite_simple_algebra_unique_simple_modules (k A M N : Type*)
    [Field k] [Ring A] [Algebra k A] [FiniteDimensional k A]
    [IsSimpleRing A] [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [AddCommGroup N] [Module A N] [IsSimpleModule A N] :
    Nonempty (M ≃ₗ[A] N) := by
  sorry

theorem finite_simple_algebra_module_isotypic (k A M : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [Module k M] [IsScalarTower k A M]
    [FiniteDimensional k M] :
    IsSemisimpleModule A M ∧ IsIsotypic A M := by
  sorry

theorem finite_module_is_direct_sum_of_simple (k A M S : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [Module k M] [IsScalarTower k A M]
    [Module.Finite A M] [AddCommGroup S] [Module A S]
    [IsSimpleModule A S] :
    ∃ n : ℕ, Nonempty (M ≃ₗ[A] (Fin n → S)) := by
  sorry

theorem finite_simple_algebra_modules_classified_by_dimension
    (k A M N : Type*) [Field k] [Ring A] [Algebra k A]
    [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [Module k M] [IsScalarTower k A M]
    [FiniteDimensional k M] [AddCommGroup N] [Module A N] [Module k N]
    [IsScalarTower k A N] [FiniteDimensional k N] :
    Nonempty (M ≃ₗ[A] N) ↔ Module.finrank k M = Module.finrank k N := by
  sorry

theorem simple_module_double_commutant (k A M : Type*) [Field k] [Ring A]
    [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [Module k M] [IsScalarTower k A M] :
    Nonempty (A ≃+* Module.End (Module.End A M) M) := by
  sorry

theorem simple_module_center_and_dimension (k A M : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [Module k M] [IsScalarTower k A M]
    [Algebra k (Module.End A M)] :
    Nonempty (Subalgebra.center k A ≃+* Subalgebra.center k (Module.End A M)) ∧
      FiniteDimensional k (Module.End A M) ∧
      Module.finrank k A * Module.finrank k (Module.End A M) =
        Module.finrank k M ^ 2 := by
  sorry

theorem simple_module_end_is_finite (k A M : Type*) [Field k] [Ring A]
    [Algebra k A] [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup M] [Module A M] [IsSimpleModule A M]
    [Module k M] [IsScalarTower k A M]
    [Algebra k (Module.End A M)] :
    Nonempty (DivisionRing (Module.End A M)) ∧
      FiniteDimensional k (Module.End A M) := by
  sorry

theorem finite_module_end_is_matrix_and_double_commutant
    (k A N : Type*) [Field k] [Ring A] [Algebra k A]
    [FiniteDimensional k A] [IsSimpleRing A]
    [AddCommGroup N] [Module A N] [Module k N] [IsScalarTower k A N]
    [FiniteDimensional k N] :
    ∃ (n : ℕ) (L : Type*) (_ : DivisionRing L) (_ : Algebra k L)
      (_ : FiniteDimensional k L),
      Nonempty (Module.End A N ≃+* Matrix (Fin n) (Fin n) L) ∧
        Nonempty (Module.End (Module.End A N) N ≃+* A) := by
  sorry

end SimpleModules

section TensorProducts

theorem tensor_product_finite_central_simple (k A B : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [Algebra.IsCentral k A]
    [IsSimpleRing A] [Ring B] [Algebra k B] [FiniteDimensional k B]
    [Algebra.IsCentral k B] [IsSimpleRing B] :
    FiniteDimensional k (A ⊗[k] B) ∧
      Algebra.IsCentral k (A ⊗[k] B) ∧ IsSimpleRing (A ⊗[k] B) := by
  sorry

theorem base_change_finite_central_simple (k A k' : Type*) [Field k]
    [Ring A] [Algebra k A] [FiniteDimensional k A] [Algebra.IsCentral k A]
    [IsSimpleRing A] [Field k'] [Algebra k k'] :
    letI : Algebra k' (A ⊗[k] k') :=
      Algebra.TensorProduct.rightAlgebra
    FiniteDimensional k' (A ⊗[k] k') ∧
      Algebra.IsCentral k' (A ⊗[k] k') ∧ IsSimpleRing (A ⊗[k] k') := by
  sorry

theorem inverse_of_finite_central_simple (k A : Type*) [Field k] [Ring A]
    [Algebra k A] [FiniteDimensional k A] [Algebra.IsCentral k A]
    [IsSimpleRing A] :
    Nonempty
      ((A ⊗[k] Aᵐᵒᵖ) ≃ₐ[k]
        Matrix (Fin (Module.finrank k A)) (Fin (Module.finrank k A)) k) := by
  sorry

end TensorProducts

end Formalization.Books.Brauer
