import Formalization.Books.Algebra.Unit40.SupportsAndAnnihilators
import Formalization.Books.Algebra.Unit78.FiniteProjectiveModules
import Mathlib.Algebra.Category.ModuleCat.ProjectiveDimension
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.RingTheory.Finiteness.Prod
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Support
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.Data.Matrix.Block

/-!
# More on Algebra, Chapter 8: Fitting ideals

The Fitting ideals are defined from the minors of a presentation by a finite
free module.  The independence of the chosen presentation is recorded as a
theorem, so the definition can use Mathlib's canonical finite-free
surjection supplied by `Module.Finite.exists_fin'`.
-/

namespace Formalization.Books.MoreAlgebra.Unit08

open Formalization.Books.Algebra.Unit78
open Set
open scoped TensorProduct

noncomputable section

/-! ## Minors and the presentation-independent construction -/

/-- The determinant of the `r × r` submatrix indexed by two finite sets. -/
noncomputable def matrixMinor
    {R : Type*} [CommRing R] {n m r : ℕ}
    (A : Matrix (Fin n) (Fin m) R)
    (rows : Finset (Fin n)) (cols : Finset (Fin m))
    (hrows : rows.card = r) (hcols : cols.card = r) : R :=
  (A.submatrix
      (fun i => (rows.orderIsoOfFin hrows i : Fin n))
      (fun j => (cols.orderIsoOfFin hcols j : Fin m))).det

/-- The set of all `r × r` minors of a matrix. -/
noncomputable def matrixMinorSet
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) : Set R :=
  {x | ∃ (rows : Finset (Fin n)) (cols : Finset (Fin m))
      (hrows : rows.card = r) (hcols : cols.card = r),
      x = matrixMinor A rows cols hrows hcols}

/-- The ideal generated by all `r × r` minors of a matrix. -/
noncomputable def minorIdeal
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) : Ideal R :=
  Ideal.span (matrixMinorSet A r)

theorem minorIdeal_mono_succ
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) :
    minorIdeal A (r + 1) ≤ minorIdeal A r := by
  classical
  apply Ideal.span_le.2
  rintro x ⟨rows, cols, hrows, hcols, rfl⟩
  let erows : Fin (r + 1) → Fin n := fun i => rows.orderIsoOfFin hrows i
  let ecols : Fin (r + 1) → Fin m := fun i => cols.orderIsoOfFin hcols i
  let row0 : Fin n := erows 0
  let rows' := rows.erase row0
  have hrow0 : row0 ∈ rows := Finset.orderEmbOfFin_mem rows hrows 0
  have hrows' : rows'.card = r := by
    dsimp [rows']
    rw [Finset.card_erase_of_mem hrow0]
    omega
  have herows : (fun i : Fin r => erows (Fin.succ i)) =
      (fun i => (rows'.orderIsoOfFin hrows' i : Fin n)) := by
    apply Finset.orderEmbOfFin_unique hrows'
    · intro i
      apply Finset.mem_erase.mpr
      constructor
      · intro h
        apply (Fin.succ_ne_zero i)
        apply (rows.orderIsoOfFin hrows).injective
        apply Subtype.ext
        exact (show erows (Fin.succ i) = erows 0 from h)
      · exact Finset.orderEmbOfFin_mem rows hrows (Fin.succ i)
    · intro i k hik
      exact (rows.orderIsoOfFin hrows).strictMono (by simpa using hik)
  change (A.submatrix erows ecols).det ∈ minorIdeal A r
  rw [Matrix.det_succ_row_zero]
  apply Ideal.sum_mem
  intro j hj
  let cols' := cols.erase (ecols j)
  have hcolj : ecols j ∈ cols := Finset.orderEmbOfFin_mem cols hcols j
  have hcols' : cols'.card = r := by
    dsimp [cols']
    rw [Finset.card_erase_of_mem hcolj]
    omega
  have hecols : (fun i : Fin r => ecols (j.succAbove i)) =
      (fun i => (cols'.orderIsoOfFin hcols' i : Fin m)) := by
    apply Finset.orderEmbOfFin_unique hcols'
    · intro i
      apply Finset.mem_erase.mpr
      constructor
      · intro h
        apply (Fin.succAbove_ne j i)
        apply (cols.orderIsoOfFin hcols).injective
        apply Subtype.ext
        exact (show ecols (j.succAbove i) = ecols j from h)
      · exact Finset.orderEmbOfFin_mem cols hcols (j.succAbove i)
    · intro i k hik
      exact (cols.orderIsoOfFin hcols).strictMono
        ((Fin.succAboveOrderEmb j).strictMono hik)
  apply Ideal.mul_mem_left
  apply Ideal.subset_span
  refine ⟨rows', cols', hrows', hcols', ?_⟩
  dsimp [matrixMinor]
  rw [Matrix.submatrix_submatrix]
  apply congrArg Matrix.det
  congr 1

theorem minorIdeal_firstRows
    {R : Type*} [CommRing R] {n n' m r : ℕ}
    (B : Matrix (Fin (n + n')) (Fin m) R) :
    minorIdeal B (r + n') ≤
      minorIdeal (B.submatrix (Fin.castAdd n') id) r := by
  have oneRow :
      ∀ {q m r : ℕ} (D : Matrix (Fin (q + 1)) (Fin m) R),
        minorIdeal D (r + 1) ≤
          minorIdeal (D.submatrix (Fin.castAdd 1) id) r := by
    intro q m r D
    apply Ideal.span_le.2
    rintro x ⟨rows, cols, hrows, hcols, rfl⟩
    let erows : Fin (r + 1) → Fin (q + 1) :=
      fun i => rows.orderIsoOfFin hrows i
    let ecols : Fin (r + 1) → Fin m :=
      fun i => cols.orderIsoOfFin hcols i
    have hrows_ne : rows.Nonempty := by
      exact ⟨erows 0, Finset.orderEmbOfFin_mem rows hrows 0⟩
    let rowMax : Fin (q + 1) := rows.max' hrows_ne
    let rows0 := rows.erase rowMax
    have hrowMax : rowMax ∈ rows := Finset.max'_mem rows hrows_ne
    have hrows0 : rows0.card = r := by
      dsimp [rows0]
      rw [Finset.card_erase_of_mem hrowMax]
      omega
    have hrowlast : erows (Fin.last r) = rowMax := by
      convert Finset.orderEmbOfFin_last hrows (by omega : 0 < r + 1) using 1
      apply congrArg (fun z : Fin (r + 1) => (rows.orderEmbOfFin hrows) z)
      apply Fin.ext
      rfl
    let rowsA := rows0.preimage Fin.castSucc (Fin.castSucc_injective _).injOn
    have hmap : rowsA.map Fin.castSuccEmb = rows0 := by
      apply Finset.ext
      intro i
      constructor
      · intro hi
        rcases Finset.mem_map.mp hi with ⟨a, ha, rfl⟩
        simpa [rowsA] using ha
      · intro hi
        have hlt : i.val < q := by
          by_contra hq
          have hiq : q ≤ i.val := Nat.le_of_not_gt hq
          have hi_last : i = Fin.last q := by
            apply Fin.ext
            have : i.val = q := by omega
            exact this
          subst i
          have hle : Fin.last q ≤ rowMax :=
            Finset.le_max' rows _ (Finset.erase_subset rowMax rows hi)
          have heq : rowMax = Fin.last q :=
            Fin.le_antisymm (Fin.le_last _) hle
          exact (Finset.mem_erase.mp hi).1 heq.symm
        refine Finset.mem_map.mpr ⟨⟨i.val, hlt⟩, ?_, ?_⟩
        · simpa [rowsA] using hi
        · apply Fin.ext
          rfl
    have hrowsA : rowsA.card = r := by
      have hcardmap : rowsA.card = rows0.card := by
        simpa using congrArg Finset.card hmap
      exact hcardmap.trans hrows0
    have hrowdel :
        (fun i : Fin r => erows ((Fin.last r).succAbove i)) =
          (fun i => (rows0.orderIsoOfFin hrows0 i : Fin (q + 1))) := by
      apply Finset.orderEmbOfFin_unique hrows0
      · intro i
        apply Finset.mem_erase.mpr
        constructor
        · intro h
          apply (Fin.succAbove_ne (Fin.last r) i)
          apply (rows.orderIsoOfFin hrows).injective
          have hh : erows ((Fin.last r).succAbove i) = erows (Fin.last r) := by
            rw [hrowlast]
            exact h
          dsimp [erows] at hh ⊢
          exact Subtype.ext hh
        · exact Finset.orderEmbOfFin_mem rows hrows
            ((Fin.last r).succAbove i)
      · intro i k hik
        exact (rows.orderIsoOfFin hrows).strictMono
          ((Fin.succAboveOrderEmb (Fin.last r)).strictMono hik)
    have hrowA :
        (fun i : Fin r => (Fin.castSucc (rowsA.orderIsoOfFin hrowsA i) :
          Fin (q + 1))) =
          (fun i => (rows0.orderIsoOfFin hrows0 i : Fin (q + 1))) := by
      apply Finset.orderEmbOfFin_unique hrows0
      · intro i
        rw [← hmap]
        exact Finset.mem_map.mpr ⟨_, Finset.orderEmbOfFin_mem rowsA hrowsA i, rfl⟩
      · intro i k hik
        exact Fin.castSuccOrderEmb.strictMono
          ((rowsA.orderIsoOfFin hrowsA).strictMono hik)
    have hrow :
        (fun i : Fin r => erows ((Fin.last r).succAbove i)) =
          (fun i : Fin r =>
            (Fin.castSucc (rowsA.orderIsoOfFin hrowsA i) : Fin (q + 1))) :=
      hrowdel.trans hrowA.symm
    change (D.submatrix erows ecols).det ∈
      minorIdeal (D.submatrix (Fin.castAdd 1) id) r
    rw [Matrix.det_succ_row (n := r) _ (Fin.last r)]
    apply Ideal.sum_mem
    intro j hj
    let cols' := cols.erase (ecols j)
    have hcolj : ecols j ∈ cols :=
      Finset.orderEmbOfFin_mem cols hcols j
    have hcols' : cols'.card = r := by
      dsimp [cols']
      rw [Finset.card_erase_of_mem hcolj]
      omega
    have hecols : (fun i : Fin r => ecols (j.succAbove i)) =
        (fun i => (cols'.orderIsoOfFin hcols' i : Fin m)) := by
      apply Finset.orderEmbOfFin_unique hcols'
      · intro i
        apply Finset.mem_erase.mpr
        constructor
        · intro h
          apply (Fin.succAbove_ne j i)
          apply (cols.orderIsoOfFin hcols).injective
          apply Subtype.ext
          exact (show ecols (j.succAbove i) = ecols j from h)
        · exact Finset.orderEmbOfFin_mem cols hcols (j.succAbove i)
      · intro i k hik
        exact (cols.orderIsoOfFin hcols).strictMono
          ((Fin.succAboveOrderEmb j).strictMono hik)
    apply Ideal.mul_mem_left
    apply Ideal.subset_span
    refine ⟨rowsA, cols', hrowsA, hcols', ?_⟩
    dsimp [matrixMinor]
    rw [Matrix.submatrix_submatrix]
    apply congrArg Matrix.det
    apply Matrix.ext
    intro i k
    simp only [Matrix.submatrix_apply, Function.comp_apply]
    exact congrArg₂ D (congrFun hrow i) (congrFun hecols k)
  induction n' generalizing n r with
  | zero =>
      exact le_refl _
  | succ n' ih =>
      have h₁ :
          minorIdeal B (r + (n' + 1)) ≤
            minorIdeal (B.submatrix (Fin.castAdd 1) id) (r + n') := by
        convert oneRow (q := n + n') (m := m) (r := r + n') B using 1;
          simp [Nat.add_assoc]
      have h₂ :
          minorIdeal (B.submatrix (Fin.castAdd 1) id) (r + n') ≤
            minorIdeal
              ((B.submatrix (Fin.castAdd 1) id).submatrix (Fin.castAdd n') id) r := by
        exact ih (B := B.submatrix (Fin.castAdd 1) id)
      have hmat :
          ((B.submatrix (Fin.castAdd 1) id).submatrix (Fin.castAdd n') id) =
            B.submatrix (Fin.castAdd (n' + 1)) id := by
        apply Matrix.ext
        intro i j
        rfl
      exact h₁.trans (hmat ▸ h₂)

theorem minorIdeal_left_mul
    {R : Type*} [CommRing R] {n m r : ℕ}
    (C : Matrix (Fin n) (Fin n) R) (A : Matrix (Fin n) (Fin m) R) :
    minorIdeal (C * A) r ≤ minorIdeal A r := by
  classical
  apply Ideal.span_le.2
  rintro x ⟨rows, cols, hrows, hcols, rfl⟩
  let erows : Fin r → Fin n := fun i => rows.orderIsoOfFin hrows i
  let ecols : Fin r → Fin m := fun j => cols.orderIsoOfFin hcols j
  have hprod :
      (C * A).submatrix erows ecols =
        (C.submatrix erows id) * (A.submatrix id ecols) := by
    apply Matrix.ext
    intro i j
    simp [Matrix.mul_apply, Matrix.submatrix_apply, erows, ecols]
  change ((C * A).submatrix erows ecols).det ∈ minorIdeal A r
  rw [hprod, Formalization.Books.Algebra.Unit03.cauchyBinet]
  apply Ideal.sum_mem
  intro S hS
  apply Ideal.mul_mem_left
  apply Ideal.subset_span
  refine ⟨S.1, cols, S.2, hcols, ?_⟩
  rfl

theorem minorIdeal_blockDiagonal
    {R : Type*} [CommRing R] {n₁ n₂ m₁ m₂ r : ℕ}
    (A₁ : Matrix (Fin n₁) (Fin m₁) R)
    (A₂ : Matrix (Fin n₂) (Fin m₂) R) :
    minorIdeal
        (Matrix.reindex finSumFinEquiv finSumFinEquiv
          (Matrix.fromBlocks A₁
            (0 : Matrix (Fin n₁) (Fin m₂) R)
            (0 : Matrix (Fin n₂) (Fin m₁) R) A₂)) r =
      ⨆ r₁ : ℕ, ⨆ r₂ : ℕ, ⨆ (_h : r₁ + r₂ = r),
      minorIdeal A₁ r₁ * minorIdeal A₂ r₂ := by
  sorry

/-- The matrix whose columns are a chosen finite family of relations. -/
def relationMatrix
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n k : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (z : Fin (n - k) → LinearMap.ker p) :
    Matrix (Fin n) (Fin (n - k)) R :=
  fun i j => (z j).1 i

/-- The Fitting ideal computed from a fixed finite-free surjection. -/
noncomputable def fittingIdealOfSurjection
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (_hp : Function.Surjective p) (k : ℕ) : Ideal R :=
  ⨆ z : Fin (n - k) → LinearMap.ker p,
    minorIdeal (relationMatrix p z) (n - k)

/-- The Fitting ideal of a finite module. -/
noncomputable def fittingIdeal
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) : Ideal R :=
  let h := Module.Finite.exists_fin' R M
  fittingIdealOfSurjection h.choose_spec.choose h.choose_spec.choose_spec k

/-- The Fitting ideal at the book's extra index `-1`. -/
def fittingIdealNegOne
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] : Ideal R :=
  ⊥

/-- A signed-index extension of the Fitting ideals, with all negative indices
set equal to zero.  This is used only to state the source's `r - 1` cases. -/
noncomputable def fittingIdealInt
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℤ) : Ideal R :=
  if 0 ≤ k then fittingIdeal R M k.toNat else ⊥

theorem fittingIdealInt_ofNat
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) :
    fittingIdealInt R M k = fittingIdeal R M k := by
  rfl

theorem fittingIdealInt_negOne
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdealInt R M (-1) = fittingIdealNegOne R M := by
  rfl

private def stabilize
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (t : ℕ) :
    (Fin (n + t) → R) →ₗ[R] M :=
  { toFun := fun x => p (x ∘ Fin.castAdd t)
    map_add' := by sorry
    map_smul' := by sorry }

private theorem stabilize_surjective
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p) (t : ℕ) :
    Function.Surjective (stabilize p t) := by
  intro y
  obtain ⟨x, rfl⟩ := hp y
  refine ⟨Fin.addCases x (fun _ => 0), ?_⟩
  simp [stabilize, Function.comp_def]

private theorem minorIdeal_relationMatrix_cols_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (r : ℕ) (z : Fin (n - r) → LinearMap.ker p) :
    minorIdeal (relationMatrix p z) r ≤
      ⨆ w : Fin (n - r) → LinearMap.ker p,
        minorIdeal (relationMatrix p w) r := by
  sorry

private theorem fittingIdealOfSurjection_stabilize_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p)
    (t k : ℕ) (hk : k ≤ n) :
    fittingIdealOfSurjection (stabilize p t) (stabilize_surjective p hp t) k ≤
      fittingIdealOfSurjection p hp k := by
  sorry
/-
  let z' : Fin (n + t - k) → LinearMap.ker p := fun j =>
    ⟨fun i => (z j).1 (Fin.castAdd t i), by
      apply LinearMap.mem_ker.mpr
      change stabilize p t (z j).1 = 0
      exact (z j).property⟩
  have hrel :
      (relationMatrix (stabilize p t) z).submatrix (Fin.castAdd t) id =
        relationMatrix p z' := by
    ext i j
    rfl
  have hindex : n - k + t = n + t - k := by omega
  calc
    minorIdeal (relationMatrix (stabilize p t) z) (n + t - k) =
        minorIdeal (relationMatrix (stabilize p t) z) (n - k + t) := by
          rw [hindex]
    _ ≤ minorIdeal
        ((relationMatrix (stabilize p t) z).submatrix (Fin.castAdd t) id) (n - k) :=
      minorIdeal_firstRows (relationMatrix (stabilize p t) z)
    _ = minorIdeal (relationMatrix p z') (n - k) := by rw [hrel]
    _ ≤ ⨆ w : Fin (n - k) → LinearMap.ker p,
        minorIdeal (relationMatrix p w) (n - k) :=
      minorIdeal_relationMatrix_cols_le p z' (n - k) -/

private theorem minorIdeal_identity_top
    {R : Type*} [CommRing R] (t : ℕ) :
    minorIdeal (1 : Matrix (Fin t) (Fin t) R) t = ⊤ := by
  sorry

private theorem fittingIdealOfSurjection_stabilize_ge
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p)
    (t k : ℕ) (hk : k ≤ n) :
    fittingIdealOfSurjection p hp k ≤
      fittingIdealOfSurjection (stabilize p t) (stabilize_surjective p hp t) k := by
  sorry

private theorem fittingIdealOfSurjection_factor
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p q : (Fin n → R) →ₗ[R] M)
    (hp : Function.Surjective p) (hq : Function.Surjective q)
    (u : (Fin n → R) →ₗ[R] (Fin n → R)) (hu : q.comp u = p) (k : ℕ) :
    fittingIdealOfSurjection p hp k ≤ fittingIdealOfSurjection q hq k := by
  sorry

/-- Independence of the Fitting ideal from the chosen finite-free surjection. -/
theorem fittingIdealOfSurjection_eq
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n m : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (q : (Fin m → R) →ₗ[R] M)
    (hp : Function.Surjective p) (hq : Function.Surjective q) (k : ℕ) :
    fittingIdealOfSurjection p hp k = fittingIdealOfSurjection q hq k := by
  sorry

theorem fittingIdeal_negOne_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdealNegOne R M ≤ fittingIdeal R M 0 := by
  exact bot_le

theorem fittingIdeal_mono_succ
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) :
    fittingIdeal R M k ≤ fittingIdeal R M (k + 1) := by
  classical
  have minorIdeal_zero
      {n m : ℕ} (A : Matrix (Fin n) (Fin m) R) : minorIdeal A 0 = ⊤ := by
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨∅, ∅, by simp, by simp, ?_⟩
    simp [matrixMinor]
  let h := Module.Finite.exists_fin' R M
  let n := h.choose
  let p := h.choose_spec.choose
  let hp := h.choose_spec.choose_spec
  unfold fittingIdeal
  dsimp
  refine iSup_le fun z => ?_
  by_cases hkn : k < n
  · unfold fittingIdealOfSurjection
    let t := h.choose - (k + 1)
    have hst : t + 1 = n - k := by
      dsimp [t, n]
      omega
    have hmono :
        minorIdeal (relationMatrix p z) (n - k) ≤
          minorIdeal (relationMatrix p z) t := by
      simpa only [hst] using minorIdeal_mono_succ (relationMatrix p z) t
    refine hmono.trans ?_
    apply Ideal.span_le.2
    rintro x ⟨rows, cols, hrows, hcols, rfl⟩
    let z' : Fin t → LinearMap.ker p :=
      fun j => z (cols.orderIsoOfFin hcols j)
    refine (le_iSup (fun w : Fin t → LinearMap.ker p =>
      minorIdeal (relationMatrix p w) t) z') ?_
    apply Ideal.subset_span
    refine ⟨rows, Finset.univ, hrows, by simp [t], ?_⟩
    dsimp [matrixMinor, relationMatrix, z']
    apply congrArg Matrix.det
    apply Matrix.ext
    intro i j
    dsimp [relationMatrix, z']
    have hj : (Finset.univ.orderEmbOfFin (by simp) j : Fin t) = j := by
      apply Fin.ext
      simp [Finset.orderEmbOfFin_apply, Fin.sort_univ]
    have hc :
        cols.orderEmbOfFin hcols
            ((Finset.univ.orderEmbOfFin (by simp) j : Fin t)) =
          cols.orderEmbOfFin hcols j := by
      rw [hj]
    rw [hc]
  · unfold fittingIdealOfSurjection
    have hnk : h.choose ≤ k := by
      exact Nat.le_of_not_gt (by simpa [n] using hkn)
    have hk0 : h.choose - k = 0 := Nat.sub_eq_zero_of_le hnk
    have hk1 : h.choose - (k + 1) = 0 :=
      Nat.sub_eq_zero_of_le (le_trans hnk (Nat.le_succ _))
    let z0 : Fin (h.choose - (k + 1)) → LinearMap.ker p :=
      fun i => Fin.elim0 (hk1 ▸ i)
    have hleft :
        minorIdeal (relationMatrix p z) (h.choose - k) = ⊤ := by
      calc
        minorIdeal (relationMatrix p z) (h.choose - k) =
            minorIdeal (relationMatrix p z) 0 :=
          congrArg (fun s => minorIdeal (relationMatrix p z) s) hk0
        _ = ⊤ := minorIdeal_zero _
    have hright :
        minorIdeal (relationMatrix p z0) (h.choose - (k + 1)) = ⊤ := by
      calc
        minorIdeal (relationMatrix p z0) (h.choose - (k + 1)) =
            minorIdeal (relationMatrix p z0) 0 :=
          congrArg (fun s => minorIdeal (relationMatrix p z0) s) hk1
        _ = ⊤ := minorIdeal_zero _
    calc
      minorIdeal (relationMatrix p z) (h.choose - k) = ⊤ := hleft
      _ = minorIdeal (relationMatrix p z0) (h.choose - (k + 1)) := hright.symm
      _ ≤ ⨆ w : Fin (h.choose - (k + 1)) → LinearMap.ker p,
          minorIdeal (relationMatrix p w) (h.choose - (k + 1)) :=
        le_iSup (fun w : Fin (h.choose - (k + 1)) → LinearMap.ker p =>
          minorIdeal (relationMatrix p w) (h.choose - (k + 1))) z0

theorem exists_fittingIdeal_eq_top
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    ∃ t : ℕ, fittingIdeal R M t = ⊤ := by
  have minorIdeal_zero
      {n m : ℕ} (A : Matrix (Fin n) (Fin m) R) : minorIdeal A 0 = ⊤ := by
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨∅, ∅, by simp, by simp, ?_⟩
    simp [matrixMinor]
  let h := Module.Finite.exists_fin' R M
  refine ⟨h.choose, ?_⟩
  unfold fittingIdeal
  dsimp
  change fittingIdealOfSurjection h.choose_spec.choose h.choose_spec.choose_spec h.choose = ⊤
  unfold fittingIdealOfSurjection
  apply top_unique
  let z0 : Fin (h.choose - h.choose) → LinearMap.ker h.choose_spec.choose :=
    fun i => Fin.elim0 ((Nat.sub_self h.choose) ▸ i)
  refine le_iSup_of_le z0 ?_
  have hz : minorIdeal (relationMatrix h.choose_spec.choose z0) (h.choose - h.choose) = ⊤ := by
    simpa only [Nat.sub_self] using (minorIdeal_zero (relationMatrix h.choose_spec.choose z0))
  rw [hz]

/-! ## Basic properties -/

theorem fittingIdeal_eq_top_of_surjective
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] {n : ℕ}
    (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p) :
    fittingIdeal R M n = ⊤ := by
  have minorIdeal_zero
      {n m : ℕ} (A : Matrix (Fin n) (Fin m) R) : minorIdeal A 0 = ⊤ := by
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨∅, ∅, by simp, by simp, ?_⟩
    simp [matrixMinor]
  let h := Module.Finite.exists_fin' R M
  unfold fittingIdeal
  dsimp
  rw [← fittingIdealOfSurjection_eq p h.choose_spec.choose hp h.choose_spec.choose_spec n]
  unfold fittingIdealOfSurjection
  apply top_unique
  let z0 : Fin (n - n) → LinearMap.ker p :=
    fun i => Fin.elim0 ((Nat.sub_self n) ▸ i)
  refine le_iSup_of_le z0 ?_
  have hz : minorIdeal (relationMatrix p z0) (n - n) = ⊤ := by
    simpa only [Nat.sub_self] using (minorIdeal_zero (relationMatrix p z0))
  rw [hz]

theorem fittingIdeal_prod_zero
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N] :
    fittingIdeal R (M × N) 0 = fittingIdeal R M 0 * fittingIdeal R N 0 := by
  sorry

theorem fittingIdeal_prod
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N] (l : ℕ) :
    fittingIdeal R (M × N) l =
      ⨆ k : ℕ, ⨆ k' : ℕ, ⨆ (_h : k + k' = l),
        fittingIdeal R M k * fittingIdeal R N k' := by
  sorry

theorem fittingIdeal_baseChange
    {R S M : Type*} [CommRing R] [CommRing S] [Algebra R S]
    [AddCommGroup M] [Module R M] [Module.Finite R M] (k : ℕ) :
    fittingIdeal S (S ⊗[R] M) k =
      Ideal.map (algebraMap R S) (fittingIdeal R M k) := by
  sorry

theorem fittingIdeal_fg
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.FinitePresentation R M] (k : ℕ) :
    (fittingIdeal R M k).FG := by
  sorry

theorem fittingIdeal_mono_of_surjective
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    (φ : M →ₗ[R] N) (hφ : Function.Surjective φ) (k : ℕ) :
    fittingIdeal R M k ≤ fittingIdeal R N k := by
  sorry

theorem fittingIdeal_zero_le_annihilator
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdeal R M 0 ≤ Module.annihilator R M := by
  sorry

theorem zeroLocus_fittingIdeal_zero_eq_support
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    PrimeSpectrum.zeroLocus (fittingIdeal R M 0 : Set R) = Module.support R M := by
  sorry

theorem fittingIdeal_quotient_zero
    {R : Type*} [CommRing R] (I : Ideal R) :
    fittingIdeal R (R ⧸ I) 0 = I := by
  sorry

/-! ## Examples -/

theorem fittingIdeal_fin_free
    {R : Type*} [CommRing R] (n : ℕ) :
    (∀ k : ℕ, k < n → fittingIdeal R (Fin n → R) k = ⊥) ∧
      (∀ k : ℕ, n ≤ k → fittingIdeal R (Fin n → R) k = ⊤) := by
  sorry

theorem fittingIdeal_laurent
    {R : Type*} [CommRing R] (I J : Ideal R) :
    fittingIdeal R (R ⧸ I) 0 = I ∧
      fittingIdeal R ((R ⧸ I) × (R ⧸ J)) 0 = I * J ∧
        fittingIdeal R ((R ⧸ I) × (R ⧸ J)) 1 = I + J := by
  sorry

/-! ## Local generation and finite locally free modules -/

theorem fittingIdeal_generate_locally
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) (p : PrimeSpectrum R) :
    List.TFAE [
      ¬ fittingIdeal R M k ≤ p.asIdeal,
      Module.finrank p.asIdeal.ResidueField (p.asIdeal.Fiber M) ≤ k,
      ∃ g : (Fin k → Localization.AtPrime p.asIdeal) →ₗ[Localization.AtPrime p.asIdeal]
          LocalizedModule p.asIdeal.primeCompl M, Function.Surjective g,
      ∃ f : R, f ∉ p.asIdeal ∧
        ∃ g : (Fin k → Localization.Away f) →ₗ[Localization.Away f]
            LocalizedModule.Away f M, Function.Surjective g] := by
  sorry

theorem fittingIdeal_finiteLocallyFreeOfRank
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (r : ℕ) :
    List.TFAE [
      FiniteLocallyFreeOfRank R M r,
      fittingIdealInt R M ((r : ℤ) - 1) = ⊥ ∧ fittingIdeal R M r = ⊤,
      (∀ k : ℕ, k < r → fittingIdeal R M k = ⊥) ∧
        (∀ k : ℕ, r ≤ k → fittingIdeal R M k = ⊤)] := by
  sorry

/-! ## Principal Fitting ideals and the projective-dimension statement -/

/- The source-facing names below retain the interfaces consumed by later
   chapters, while their implementations use Mathlib's canonical torsion
   submodules. -/
/-- The submodule annihilated by multiplication by a scalar. -/
abbrev scalarTorsionSubmodule
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) : Submodule R M :=
  Submodule.torsionBy R M f

/-- The submodule of elements killed by some power of a scalar. -/
abbrev scalarPowerTorsionSubmodule
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) : Submodule R M :=
  Submodule.torsion' R M (Submonoid.powers f)

theorem quotient_by_principal_fitting_torsion_generated
    {R M : Type*} [CommRing R] [IsLocalRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (k : ℕ) (f : R) (hfit : fittingIdeal R M k = Ideal.span {f}) :
    ∃ g : (Fin k → R) →ₗ[R]
          (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f),
      Function.Surjective g := by
  sorry

theorem fittingIdeal_principal_nonzerodivisor
    {R M : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.FinitePresentation R M]
    (k : ℕ) (f : R) (hf : f ∈ nonZeroDivisors R)
    (hfit : fittingIdeal R M k = Ideal.span {f})
    (hprev : fittingIdealInt R M ((k : ℤ) - 1) = ⊥) :
    CategoryTheory.HasProjectiveDimensionLE (ModuleCat.of R M) 1 ∧
      scalarTorsionSubmodule (R := R) (M := M) f =
          scalarPowerTorsionSubmodule (R := R) (M := M) f ∧
        CategoryTheory.HasProjectiveDimensionLE
            (ModuleCat.of R
              (scalarTorsionSubmodule (R := R) (M := M) f : Type _)) 1 ∧
          FiniteLocallyFreeOfRank R
            (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f) k ∧
            Nonempty
              (M ≃ₗ[R]
                (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f) ×
                  (scalarTorsionSubmodule (R := R) (M := M) f : Type _)) := by
  sorry

end

end Formalization.Books.MoreAlgebra.Unit08
