import Formalization.Books.Algebra.Unit40.SupportsAndAnnihilators
import Formalization.Books.Algebra.Unit78.FiniteProjectiveModules
import Mathlib.Algebra.Category.ModuleCat.ChangeOfRings
import Mathlib.Algebra.Category.ModuleCat.ProjectiveDimension
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.RingTheory.Finiteness.Prod
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Support
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.Data.Matrix.Block

/-!
# More on Algebra, Chapter 8: Fitting ideals

The Fitting ideals are defined from the minors of a presentation by a finite
free module.  The independence of the chosen presentation is recorded as a
theorem, so the definition can use Mathlib's canonical finite-free
surjection supplied by `Module.Finite.exists_fin'`.
-/

namespace Formalization.Books.MoreAlgebra.Unit08

open Formalization.Books.Algebra.Unit78
open Set
open scoped TensorProduct

noncomputable section

/-! ## Minors and the presentation-independent construction -/

/-- The determinant of the `r × r` submatrix indexed by two finite sets. -/
noncomputable def matrixMinor
    {R : Type*} [CommRing R] {n m r : ℕ}
    (A : Matrix (Fin n) (Fin m) R)
    (rows : Finset (Fin n)) (cols : Finset (Fin m))
    (hrows : rows.card = r) (hcols : cols.card = r) : R :=
  (A.submatrix
      (fun i => (rows.orderIsoOfFin hrows i : Fin n))
      (fun j => (cols.orderIsoOfFin hcols j : Fin m))).det

/-- The set of all `r × r` minors of a matrix. -/
noncomputable def matrixMinorSet
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) : Set R :=
  {x | ∃ (rows : Finset (Fin n)) (cols : Finset (Fin m))
      (hrows : rows.card = r) (hcols : cols.card = r),
      x = matrixMinor A rows cols hrows hcols}

/-- The ideal generated by all `r × r` minors of a matrix. -/
noncomputable def minorIdeal
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) : Ideal R :=
  Ideal.span (matrixMinorSet A r)

theorem minorIdeal_mono_succ
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) :
    minorIdeal A (r + 1) ≤ minorIdeal A r := by
  classical
  apply Ideal.span_le.2
  rintro x ⟨rows, cols, hrows, hcols, rfl⟩
  let erows : Fin (r + 1) → Fin n := fun i => rows.orderIsoOfFin hrows i
  let ecols : Fin (r + 1) → Fin m := fun i => cols.orderIsoOfFin hcols i
  let row0 : Fin n := erows 0
  let rows' := rows.erase row0
  have hrow0 : row0 ∈ rows := Finset.orderEmbOfFin_mem rows hrows 0
  have hrows' : rows'.card = r := by
    dsimp [rows']
    rw [Finset.card_erase_of_mem hrow0]
    omega
  have herows : (fun i : Fin r => erows (Fin.succ i)) =
      (fun i => (rows'.orderIsoOfFin hrows' i : Fin n)) := by
    apply Finset.orderEmbOfFin_unique hrows'
    · intro i
      apply Finset.mem_erase.mpr
      constructor
      · intro h
        apply (Fin.succ_ne_zero i)
        apply (rows.orderIsoOfFin hrows).injective
        apply Subtype.ext
        exact (show erows (Fin.succ i) = erows 0 from h)
      · exact Finset.orderEmbOfFin_mem rows hrows (Fin.succ i)
    · intro i k hik
      exact (rows.orderIsoOfFin hrows).strictMono (by simpa using hik)
  change (A.submatrix erows ecols).det ∈ minorIdeal A r
  rw [Matrix.det_succ_row_zero]
  apply Ideal.sum_mem
  intro j hj
  let cols' := cols.erase (ecols j)
  have hcolj : ecols j ∈ cols := Finset.orderEmbOfFin_mem cols hcols j
  have hcols' : cols'.card = r := by
    dsimp [cols']
    rw [Finset.card_erase_of_mem hcolj]
    omega
  have hecols : (fun i : Fin r => ecols (j.succAbove i)) =
      (fun i => (cols'.orderIsoOfFin hcols' i : Fin m)) := by
    apply Finset.orderEmbOfFin_unique hcols'
    · intro i
      apply Finset.mem_erase.mpr
      constructor
      · intro h
        apply (Fin.succAbove_ne j i)
        apply (cols.orderIsoOfFin hcols).injective
        apply Subtype.ext
        exact (show ecols (j.succAbove i) = ecols j from h)
      · exact Finset.orderEmbOfFin_mem cols hcols (j.succAbove i)
    · intro i k hik
      exact (cols.orderIsoOfFin hcols).strictMono
        ((Fin.succAboveOrderEmb j).strictMono hik)
  apply Ideal.mul_mem_left
  apply Ideal.subset_span
  refine ⟨rows', cols', hrows', hcols', ?_⟩
  dsimp [matrixMinor]
  rw [Matrix.submatrix_submatrix]
  apply congrArg Matrix.det
  congr 1

theorem minorIdeal_firstRows
    {R : Type*} [CommRing R] {n n' m r : ℕ}
    (B : Matrix (Fin (n + n')) (Fin m) R) :
    minorIdeal B (r + n') ≤
      minorIdeal (B.submatrix (Fin.castAdd n') id) r := by
  have oneRow :
      ∀ {q m r : ℕ} (D : Matrix (Fin (q + 1)) (Fin m) R),
        minorIdeal D (r + 1) ≤
          minorIdeal (D.submatrix (Fin.castAdd 1) id) r := by
    intro q m r D
    apply Ideal.span_le.2
    rintro x ⟨rows, cols, hrows, hcols, rfl⟩
    let erows : Fin (r + 1) → Fin (q + 1) :=
      fun i => rows.orderIsoOfFin hrows i
    let ecols : Fin (r + 1) → Fin m :=
      fun i => cols.orderIsoOfFin hcols i
    have hrows_ne : rows.Nonempty := by
      exact ⟨erows 0, Finset.orderEmbOfFin_mem rows hrows 0⟩
    let rowMax : Fin (q + 1) := rows.max' hrows_ne
    let rows0 := rows.erase rowMax
    have hrowMax : rowMax ∈ rows := Finset.max'_mem rows hrows_ne
    have hrows0 : rows0.card = r := by
      dsimp [rows0]
      rw [Finset.card_erase_of_mem hrowMax]
      omega
    have hrowlast : erows (Fin.last r) = rowMax := by
      convert Finset.orderEmbOfFin_last hrows (by omega : 0 < r + 1) using 1
      apply congrArg (fun z : Fin (r + 1) => (rows.orderEmbOfFin hrows) z)
      apply Fin.ext
      rfl
    let rowsA := rows0.preimage Fin.castSucc (Fin.castSucc_injective _).injOn
    have hmap : rowsA.map Fin.castSuccEmb = rows0 := by
      apply Finset.ext
      intro i
      constructor
      · intro hi
        rcases Finset.mem_map.mp hi with ⟨a, ha, rfl⟩
        simpa [rowsA] using ha
      · intro hi
        have hlt : i.val < q := by
          by_contra hq
          have hiq : q ≤ i.val := Nat.le_of_not_gt hq
          have hi_last : i = Fin.last q := by
            apply Fin.ext
            have : i.val = q := by omega
            exact this
          subst i
          have hle : Fin.last q ≤ rowMax :=
            Finset.le_max' rows _ (Finset.erase_subset rowMax rows hi)
          have heq : rowMax = Fin.last q :=
            Fin.le_antisymm (Fin.le_last _) hle
          exact (Finset.mem_erase.mp hi).1 heq.symm
        refine Finset.mem_map.mpr ⟨⟨i.val, hlt⟩, ?_, ?_⟩
        · simpa [rowsA] using hi
        · apply Fin.ext
          rfl
    have hrowsA : rowsA.card = r := by
      have hcardmap : rowsA.card = rows0.card := by
        simpa using congrArg Finset.card hmap
      exact hcardmap.trans hrows0
    have hrowdel :
        (fun i : Fin r => erows ((Fin.last r).succAbove i)) =
          (fun i => (rows0.orderIsoOfFin hrows0 i : Fin (q + 1))) := by
      apply Finset.orderEmbOfFin_unique hrows0
      · intro i
        apply Finset.mem_erase.mpr
        constructor
        · intro h
          apply (Fin.succAbove_ne (Fin.last r) i)
          apply (rows.orderIsoOfFin hrows).injective
          have hh : erows ((Fin.last r).succAbove i) = erows (Fin.last r) := by
            rw [hrowlast]
            exact h
          dsimp [erows] at hh ⊢
          exact Subtype.ext hh
        · exact Finset.orderEmbOfFin_mem rows hrows
            ((Fin.last r).succAbove i)
      · intro i k hik
        exact (rows.orderIsoOfFin hrows).strictMono
          ((Fin.succAboveOrderEmb (Fin.last r)).strictMono hik)
    have hrowA :
        (fun i : Fin r => (Fin.castSucc (rowsA.orderIsoOfFin hrowsA i) :
          Fin (q + 1))) =
          (fun i => (rows0.orderIsoOfFin hrows0 i : Fin (q + 1))) := by
      apply Finset.orderEmbOfFin_unique hrows0
      · intro i
        rw [← hmap]
        exact Finset.mem_map.mpr ⟨_, Finset.orderEmbOfFin_mem rowsA hrowsA i, rfl⟩
      · intro i k hik
        exact Fin.castSuccOrderEmb.strictMono
          ((rowsA.orderIsoOfFin hrowsA).strictMono hik)
    have hrow :
        (fun i : Fin r => erows ((Fin.last r).succAbove i)) =
          (fun i : Fin r =>
            (Fin.castSucc (rowsA.orderIsoOfFin hrowsA i) : Fin (q + 1))) :=
      hrowdel.trans hrowA.symm
    change (D.submatrix erows ecols).det ∈
      minorIdeal (D.submatrix (Fin.castAdd 1) id) r
    rw [Matrix.det_succ_row (n := r) _ (Fin.last r)]
    apply Ideal.sum_mem
    intro j hj
    let cols' := cols.erase (ecols j)
    have hcolj : ecols j ∈ cols :=
      Finset.orderEmbOfFin_mem cols hcols j
    have hcols' : cols'.card = r := by
      dsimp [cols']
      rw [Finset.card_erase_of_mem hcolj]
      omega
    have hecols : (fun i : Fin r => ecols (j.succAbove i)) =
        (fun i => (cols'.orderIsoOfFin hcols' i : Fin m)) := by
      apply Finset.orderEmbOfFin_unique hcols'
      · intro i
        apply Finset.mem_erase.mpr
        constructor
        · intro h
          apply (Fin.succAbove_ne j i)
          apply (cols.orderIsoOfFin hcols).injective
          apply Subtype.ext
          exact (show ecols (j.succAbove i) = ecols j from h)
        · exact Finset.orderEmbOfFin_mem cols hcols (j.succAbove i)
      · intro i k hik
        exact (cols.orderIsoOfFin hcols).strictMono
          ((Fin.succAboveOrderEmb j).strictMono hik)
    apply Ideal.mul_mem_left
    apply Ideal.subset_span
    refine ⟨rowsA, cols', hrowsA, hcols', ?_⟩
    dsimp [matrixMinor]
    rw [Matrix.submatrix_submatrix]
    apply congrArg Matrix.det
    apply Matrix.ext
    intro i k
    simp only [Matrix.submatrix_apply, Function.comp_apply]
    exact congrArg₂ D (congrFun hrow i) (congrFun hecols k)
  induction n' generalizing n r with
  | zero =>
      exact le_refl _
  | succ n' ih =>
      have h₁ :
          minorIdeal B (r + (n' + 1)) ≤
            minorIdeal (B.submatrix (Fin.castAdd 1) id) (r + n') := by
        convert oneRow (q := n + n') (m := m) (r := r + n') B using 1;
          simp [Nat.add_assoc]
      have h₂ :
          minorIdeal (B.submatrix (Fin.castAdd 1) id) (r + n') ≤
            minorIdeal
              ((B.submatrix (Fin.castAdd 1) id).submatrix (Fin.castAdd n') id) r := by
        exact ih (B := B.submatrix (Fin.castAdd 1) id)
      have hmat :
          ((B.submatrix (Fin.castAdd 1) id).submatrix (Fin.castAdd n') id) =
            B.submatrix (Fin.castAdd (n' + 1)) id := by
        apply Matrix.ext
        intro i j
        rfl
      exact h₁.trans (hmat ▸ h₂)

theorem minorIdeal_left_mul
    {R : Type*} [CommRing R] {n m r : ℕ}
    (C : Matrix (Fin n) (Fin n) R) (A : Matrix (Fin n) (Fin m) R) :
    minorIdeal (C * A) r ≤ minorIdeal A r := by
  classical
  apply Ideal.span_le.2
  rintro x ⟨rows, cols, hrows, hcols, rfl⟩
  let erows : Fin r → Fin n := fun i => rows.orderIsoOfFin hrows i
  let ecols : Fin r → Fin m := fun j => cols.orderIsoOfFin hcols j
  have hprod :
      (C * A).submatrix erows ecols =
        (C.submatrix erows id) * (A.submatrix id ecols) := by
    apply Matrix.ext
    intro i j
    simp [Matrix.mul_apply, Matrix.submatrix_apply, erows, ecols]
  change ((C * A).submatrix erows ecols).det ∈ minorIdeal A r
  rw [hprod, Formalization.Books.Algebra.Unit03.cauchyBinet]
  apply Ideal.sum_mem
  intro S hS
  apply Ideal.mul_mem_left
  apply Ideal.subset_span
  refine ⟨S.1, cols, S.2, hcols, ?_⟩
  rfl

theorem minorIdeal_blockDiagonal
    {R : Type*} [CommRing R] {n₁ n₂ m₁ m₂ r : ℕ}
    (A₁ : Matrix (Fin n₁) (Fin m₁) R)
    (A₂ : Matrix (Fin n₂) (Fin m₂) R) :
    minorIdeal
        (Matrix.reindex finSumFinEquiv finSumFinEquiv
          (Matrix.fromBlocks A₁
            (0 : Matrix (Fin n₁) (Fin m₂) R)
            (0 : Matrix (Fin n₂) (Fin m₁) R) A₂)) r =
      ⨆ r₁ : ℕ, ⨆ r₂ : ℕ, ⨆ (_h : r₁ + r₂ = r),
      minorIdeal A₁ r₁ * minorIdeal A₂ r₂ := by
  sorry

/-- The matrix whose columns are a chosen finite family of relations. -/
def relationMatrix
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n k : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (z : Fin (n - k) → LinearMap.ker p) :
    Matrix (Fin n) (Fin (n - k)) R :=
  fun i j => (z j).1 i

/-- The Fitting ideal computed from a fixed finite-free surjection. -/
noncomputable def fittingIdealOfSurjection
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (_hp : Function.Surjective p) (k : ℕ) : Ideal R :=
  ⨆ z : Fin (n - k) → LinearMap.ker p,
    minorIdeal (relationMatrix p z) (n - k)

/-- The Fitting ideal of a finite module. -/
noncomputable def fittingIdeal
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) : Ideal R :=
  let h := Module.Finite.exists_fin' R M
  fittingIdealOfSurjection h.choose_spec.choose h.choose_spec.choose_spec k

/-- The Fitting ideal at the book's extra index `-1`. -/
def fittingIdealNegOne
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] : Ideal R :=
  ⊥

/-- A signed-index extension of the Fitting ideals, with all negative indices
set equal to zero.  This is used only to state the source's `r - 1` cases. -/
noncomputable def fittingIdealInt
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℤ) : Ideal R :=
  if 0 ≤ k then fittingIdeal R M k.toNat else ⊥

theorem fittingIdealInt_ofNat
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) :
    fittingIdealInt R M k = fittingIdeal R M k := by
  rfl

theorem fittingIdealInt_negOne
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdealInt R M (-1) = fittingIdealNegOne R M := by
  rfl

private def stabilize
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (t : ℕ) :
    (Fin (n + t) → R) →ₗ[R] M :=
  { toFun := fun x => p (x ∘ Fin.castAdd t)
    map_add' := by
      intro x y
      rw [show (x + y) ∘ Fin.castAdd t =
          (x ∘ Fin.castAdd t) + (y ∘ Fin.castAdd t) by
        funext i
        rfl]
      exact p.map_add _ _
    map_smul' := by
      intro c x
      rw [show (c • x) ∘ Fin.castAdd t =
          c • (x ∘ Fin.castAdd t) by
        funext i
        rfl]
      exact p.map_smul _ _ }

private theorem stabilize_surjective
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p) (t : ℕ) :
    Function.Surjective (stabilize p t) := by
  intro y
  obtain ⟨x, rfl⟩ := hp y
  refine ⟨Fin.addCases x (fun _ => 0), ?_⟩
  simp [stabilize, Function.comp_def]

private theorem minorIdeal_relationMatrix_cols_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (r : ℕ) (z : Fin (n - r) → LinearMap.ker p) :
    minorIdeal (relationMatrix p z) r ≤
      ⨆ w : Fin (n - r) → LinearMap.ker p,
        minorIdeal (relationMatrix p w) r := by
  exact le_iSup (fun w : Fin (n - r) → LinearMap.ker p =>
    minorIdeal (relationMatrix p w) r) z

private theorem minorIdeal_kerMatrix_subfamily_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n m r : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (z : Fin m → LinearMap.ker p) :
    minorIdeal (fun i j => (z j).1 i) r ≤
      ⨆ w : Fin r → LinearMap.ker p,
        minorIdeal (fun i j => (w j).1 i) r := by
  classical
  apply Ideal.span_le.2
  rintro x ⟨rows, cols, hrows, hcols, rfl⟩
  let w : Fin r → LinearMap.ker p := fun j =>
    z (cols.orderIsoOfFin hcols j : Fin m)
  apply (le_iSup (fun w : Fin r → LinearMap.ker p =>
    minorIdeal (fun i j => (w j).1 i) r) w)
  apply Ideal.subset_span
  refine ⟨rows, Finset.univ, hrows, Finset.card_fin r, ?_⟩
  dsimp [matrixMinor, w, relationMatrix]
  apply congrArg Matrix.det
  apply Matrix.ext
  intro i j
  have huniv :
      (fun j : Fin r =>
        (Finset.univ.orderEmbOfFin (Finset.card_fin r) j : Fin r)) = id := by
    have h := Finset.orderEmbOfFin_unique
      (s := (Finset.univ : Finset (Fin r))) (Finset.card_fin r)
      (f := (id : Fin r → Fin r)) (fun _ => Finset.mem_univ _) strictMono_id
    exact h.symm
  change (z (cols.orderEmbOfFin hcols j)).1
      ((rows.orderEmbOfFin hrows) i) =
    (z (cols.orderEmbOfFin hcols
      ((Finset.univ.orderEmbOfFin (Finset.card_fin r) j : Fin r)))).1
        ((rows.orderEmbOfFin hrows) i)
  rw [congrFun huniv j]
  rfl

private theorem fittingIdealOfSurjection_stabilize_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p)
    (t k : ℕ) (hk : k ≤ n) :
    fittingIdealOfSurjection (stabilize p t) (stabilize_surjective p hp t) k ≤
      fittingIdealOfSurjection p hp k := by
  unfold fittingIdealOfSurjection
  refine iSup_le ?_
  intro z
  let z' : Fin (n + t - k) → LinearMap.ker p := fun j =>
    ⟨fun i => (z j).1 (Fin.castAdd t i), by
      apply LinearMap.mem_ker.mpr
      change stabilize p t (z j).1 = 0
      exact (z j).property⟩
  have hrel :
      (relationMatrix (stabilize p t) z).submatrix (Fin.castAdd t) id =
        (fun i j => (z' j).1 i) := by
    ext i j
    rfl
  have hindex : n - k + t = n + t - k := by omega
  calc
    minorIdeal (relationMatrix (stabilize p t) z) (n + t - k) =
        minorIdeal (relationMatrix (stabilize p t) z) (n - k + t) := by
          rw [hindex]
    _ ≤ minorIdeal
        ((relationMatrix (stabilize p t) z).submatrix (Fin.castAdd t) id) (n - k) :=
      minorIdeal_firstRows (relationMatrix (stabilize p t) z)
    _ = minorIdeal (fun i j => (z' j).1 i) (n - k) := by rw [hrel]
    _ ≤ ⨆ w : Fin (n - k) → LinearMap.ker p,
        minorIdeal (relationMatrix p w) (n - k) :=
      by
        change minorIdeal (fun i j => (z' j).1 i) (n - k) ≤
          ⨆ w : Fin (n - k) → LinearMap.ker p,
            minorIdeal (fun i j => (w j).1 i) (n - k)
        exact minorIdeal_kerMatrix_subfamily_le (p := p) (z := z')
          (r := n - k)
/-
  let z' : Fin (n + t - k) → LinearMap.ker p := fun j =>
    ⟨fun i => (z j).1 (Fin.castAdd t i), by
      apply LinearMap.mem_ker.mpr
      change stabilize p t (z j).1 = 0
      exact (z j).property⟩
  have hrel :
      (relationMatrix (stabilize p t) z).submatrix (Fin.castAdd t) id =
        relationMatrix p z' := by
    ext i j
    rfl
  have hindex : n - k + t = n + t - k := by omega
  calc
    minorIdeal (relationMatrix (stabilize p t) z) (n + t - k) =
        minorIdeal (relationMatrix (stabilize p t) z) (n - k + t) := by
          rw [hindex]
    _ ≤ minorIdeal
        ((relationMatrix (stabilize p t) z).submatrix (Fin.castAdd t) id) (n - k) :=
      minorIdeal_firstRows (relationMatrix (stabilize p t) z)
    _ = minorIdeal (relationMatrix p z') (n - k) := by rw [hrel]
    _ ≤ ⨆ w : Fin (n - k) → LinearMap.ker p,
        minorIdeal (relationMatrix p w) (n - k) :=
      minorIdeal_relationMatrix_cols_le p z' (n - k) -/

private theorem minorIdeal_identity_top
    {R : Type*} [CommRing R] (t : ℕ) :
    minorIdeal (1 : Matrix (Fin t) (Fin t) R) t = ⊤ := by
  apply (Ideal.eq_top_iff_one _).mpr
  apply Ideal.subset_span
  refine ⟨Finset.univ, Finset.univ, Finset.card_fin t, Finset.card_fin t, ?_⟩
  have h : (fun i : Fin t =>
      (Finset.univ.orderEmbOfFin (Finset.card_fin t) i : Fin t)) = id := by
    have h := Finset.orderEmbOfFin_unique
      (s := (Finset.univ : Finset (Fin t))) (Finset.card_fin t)
      (f := (id : Fin t → Fin t)) (fun _ => Finset.mem_univ _) strictMono_id
    exact h.symm
  dsimp [matrixMinor]
  rw [h]
  simp

private theorem minorIdeal_append_identity_le
    {R : Type*} [CommRing R] {n m r t l : ℕ} (hcast : m + t = l)
    (A : Matrix (Fin n) (Fin m) R) :
    minorIdeal A r ≤
      minorIdeal
        (Matrix.reindex finSumFinEquiv
          (finSumFinEquiv.trans (Equiv.cast (congrArg Fin hcast)))
          (Matrix.fromBlocks A
            (0 : Matrix (Fin n) (Fin t) R)
            (0 : Matrix (Fin t) (Fin m) R)
            (1 : Matrix (Fin t) (Fin t) R))) (r + t) := by
  classical
  subst l
  apply Ideal.span_le.2
  rintro x ⟨rows, cols, hrows, hcols, rfl⟩
  let erows : Fin (r + t) → Fin (n + t) :=
    Fin.addCases (fun i => Fin.castAdd t (rows.orderIsoOfFin hrows i))
      (fun j => Fin.natAdd n j)
  let ecols0 : Fin (r + t) → Fin (m + t) :=
    Fin.addCases (fun i => Fin.castAdd t (cols.orderIsoOfFin hcols i))
      (fun j => Fin.natAdd m j)
  let ecols : Fin (r + t) → Fin (m + t) := ecols0
  have herows : StrictMono erows := by
    intro i j hij
    induction i using Fin.addCases with
    | left i =>
        induction j using Fin.addCases with
        | left j =>
            simp only [erows, Fin.addCases_left]
            exact Fin.strictMono_castAdd t
              ((rows.orderIsoOfFin hrows).strictMono hij)
        | right j =>
            simp only [erows, Fin.addCases_left, Fin.addCases_right]
            apply Fin.lt_def.mpr
            change ((rows.orderIsoOfFin hrows i : Fin n).val) < n + j.val
            have hi := ((rows.orderIsoOfFin hrows i : Fin n)).isLt
            omega
    | right i =>
        induction j using Fin.addCases with
        | left j =>
            exfalso
            have hij' := Fin.lt_def.mp hij
            simp only [Fin.val_natAdd, Fin.val_castAdd] at hij'
            have hi := i.isLt
            have hj := j.isLt
            omega
        | right j =>
            simp only [erows, Fin.addCases_right]
            exact Fin.strictMono_natAdd n
              ((Fin.natAdd_lt_natAdd_iff r).mp hij)
  have hecols0 : StrictMono ecols0 := by
    intro i j hij
    induction i using Fin.addCases with
    | left i =>
        induction j using Fin.addCases with
        | left j =>
            simp only [ecols0, Fin.addCases_left]
            exact Fin.strictMono_castAdd t
              ((cols.orderIsoOfFin hcols).strictMono hij)
        | right j =>
            simp only [ecols0, Fin.addCases_left, Fin.addCases_right]
            apply Fin.lt_def.mpr
            change ((cols.orderIsoOfFin hcols i : Fin m).val) < m + j.val
            have hi := ((cols.orderIsoOfFin hcols i : Fin m)).isLt
            omega
    | right i =>
        induction j using Fin.addCases with
        | left j =>
            exfalso
            have hij' := Fin.lt_def.mp hij
            simp only [Fin.val_natAdd, Fin.val_castAdd] at hij'
            have hi := i.isLt
            have hj := j.isLt
            omega
        | right j =>
            simp only [ecols0, Fin.addCases_right]
            exact Fin.strictMono_natAdd m
              ((Fin.natAdd_lt_natAdd_iff r).mp hij)
  have hecols : StrictMono ecols := by
    exact hecols0
  let rows' : Finset (Fin (n + t)) :=
    Finset.univ.map ⟨erows, herows.injective⟩
  let cols' : Finset (Fin (m + t)) :=
    Finset.univ.map ⟨ecols, hecols.injective⟩
  have hrows' : rows'.card = r + t := by
    simp [rows']
  have hcols' : cols'.card = r + t := by
    simp [cols']
  have hrow : (fun i : Fin (r + t) =>
      (rows'.orderEmbOfFin hrows' i : Fin (n + t))) = erows := by
    have h := Finset.orderEmbOfFin_unique hrows'
      (f := erows) (fun i => Finset.mem_map.mpr ⟨i, Finset.mem_univ _, rfl⟩)
      herows
    exact h.symm
  have hcol : (fun i : Fin (r + t) =>
      (cols'.orderEmbOfFin hcols' i : Fin (m + t))) = ecols := by
    have h := Finset.orderEmbOfFin_unique hcols'
      (f := ecols) (fun i => Finset.mem_map.mpr ⟨i, Finset.mem_univ _, rfl⟩)
      hecols
    exact h.symm
  apply Ideal.subset_span
  refine ⟨rows', cols', hrows', hcols', ?_⟩
  dsimp [matrixMinor]
  rw [hrow, hcol]
  have hsub :
      ((Matrix.fromBlocks A
            (0 : Matrix (Fin n) (Fin t) R)
            (0 : Matrix (Fin t) (Fin m) R)
            (1 : Matrix (Fin t) (Fin t) R)).submatrix
          finSumFinEquiv.symm
            finSumFinEquiv.symm).submatrix erows ecols =
        Matrix.reindex finSumFinEquiv finSumFinEquiv
          (Matrix.fromBlocks
            (show Matrix (Fin r) (Fin r) R from
              A.submatrix
                (fun i : Fin r => (rows.orderEmbOfFin hrows i : Fin n))
                (fun j : Fin r => (cols.orderEmbOfFin hcols j : Fin m)))
            (0 : Matrix (Fin r) (Fin t) R)
            (0 : Matrix (Fin t) (Fin r) R)
            (1 : Matrix (Fin t) (Fin t) R)) := by
    apply Matrix.ext
    intro i j
    induction i using Fin.addCases with
    | left i =>
        induction j using Fin.addCases with
        | left j =>
            simp only [Matrix.submatrix_apply]
            simp [erows, ecols, ecols0, Matrix.reindex_apply]
        | right j =>
            simp only [Matrix.submatrix_apply]
            simp [erows, ecols, ecols0, Matrix.reindex_apply]
    | right i =>
        induction j using Fin.addCases with
        | left j =>
            simp only [Matrix.submatrix_apply]
            simp [erows, ecols, ecols0, Matrix.reindex_apply]
        | right j =>
            simp only [Matrix.submatrix_apply]
            simp [erows, ecols, ecols0, Matrix.reindex_apply]
  rw [hsub, Matrix.det_reindex_self]
  rw [Matrix.det_fromBlocks_zero₂₁]
  simp

private theorem fittingIdealOfSurjection_stabilize_ge
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p)
    (t k : ℕ) (hk : k ≤ n) :
    fittingIdealOfSurjection p hp k ≤
      fittingIdealOfSurjection (stabilize p t) (stabilize_surjective p hp t) k := by
  classical
  have hindex : n - k + t = n + t - k := by omega
  unfold fittingIdealOfSurjection
  refine iSup_le ?_
  intro z
  let oldCol : Fin (n - k) → Fin (n + t) → R := fun j =>
    Fin.addCases (z j).1 (fun _ : Fin t => 0)
  let stdCol : Fin t → Fin (n + t) → R := fun j =>
    Fin.addCases (fun _ : Fin n => 0) (Pi.single j 1)
  have hold : ∀ j, oldCol j ∈ LinearMap.ker (stabilize p t) := by
    intro j
    apply LinearMap.mem_ker.mpr
    change p (oldCol j ∘ Fin.castAdd t) = 0
    have hcol : oldCol j ∘ Fin.castAdd t = (z j).1 := by
      funext i
      simp [oldCol]
    rw [hcol]
    exact (z j).property
  have hstd : ∀ j, stdCol j ∈ LinearMap.ker (stabilize p t) := by
    intro j
    apply LinearMap.mem_ker.mpr
    change p (stdCol j ∘ Fin.castAdd t) = 0
    have hcol : stdCol j ∘ Fin.castAdd t = 0 := by
      funext i
      simp [stdCol]
    rw [hcol]
    simp
  let z'' : Fin (n - k + t) → LinearMap.ker (stabilize p t) :=
    Fin.addCases (fun j => ⟨oldCol j, hold j⟩)
      (fun j => ⟨stdCol j, hstd j⟩)
  let ecols : Fin (n - k) ⊕ Fin t ≃ Fin (n + t - k) :=
    finSumFinEquiv.trans (Equiv.cast (congrArg Fin hindex))
  let z' : Fin (n + t - k) → LinearMap.ker (stabilize p t) := fun j =>
    z'' (finSumFinEquiv (ecols.symm j))
  have hrel : relationMatrix (stabilize p t) z' =
      Matrix.reindex finSumFinEquiv ecols
        (Matrix.fromBlocks (relationMatrix p z)
          (0 : Matrix (Fin n) (Fin t) R)
          (0 : Matrix (Fin t) (Fin (n - k)) R)
          (1 : Matrix (Fin t) (Fin t) R)) := by
    apply Matrix.ext
    intro i j
    obtain ⟨j, rfl⟩ := ecols.surjective j
    induction i using Fin.addCases with
    | left i =>
        cases j with
        | inl j =>
            simp [relationMatrix, z', z'', oldCol, ecols, stabilize,
            Equiv.trans_apply, Equiv.cast]
        | inr j =>
            simp [relationMatrix, z', z'', stdCol, ecols, stabilize,
            Equiv.trans_apply, Equiv.cast]
    | right i =>
        cases j with
        | inl j =>
            simp [relationMatrix, z', z'', oldCol, ecols, stabilize,
              Equiv.trans_apply, Equiv.cast]
        | inr j =>
            simp [relationMatrix, z', z'', stdCol, ecols, stabilize,
              Equiv.trans_apply, Equiv.cast, Matrix.one_apply,
              Pi.single_apply]
  calc
    minorIdeal (relationMatrix p z) (n - k) ≤
        minorIdeal (relationMatrix p z) (n - k) := le_rfl
    _ ≤ minorIdeal
        (Matrix.reindex finSumFinEquiv ecols
          (Matrix.fromBlocks (relationMatrix p z)
            (0 : Matrix (Fin n) (Fin t) R)
            (0 : Matrix (Fin t) (Fin (n - k)) R)
            (1 : Matrix (Fin t) (Fin t) R))) (n - k + t) :=
      (by
        simpa [ecols] using
          (minorIdeal_append_identity_le (R := R) (n := n) (m := n - k)
            (r := n - k) (t := t) (l := n + t - k) hindex
            (relationMatrix p z)))
    _ = minorIdeal (relationMatrix (stabilize p t) z') (n + t - k) := by
      rw [hrel]
      rw [hindex]
    _ ≤ fittingIdealOfSurjection (stabilize p t)
        (stabilize_surjective p hp t) k :=
      le_iSup (fun w : Fin (n + t - k) → LinearMap.ker (stabilize p t) =>
        minorIdeal (relationMatrix (stabilize p t) w) (n + t - k)) z'

private theorem fittingIdealOfSurjection_factor
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p q : (Fin n → R) →ₗ[R] M)
    (hp : Function.Surjective p) (hq : Function.Surjective q)
    (u : (Fin n → R) →ₗ[R] (Fin n → R)) (hu : q.comp u = p) (k : ℕ) :
    fittingIdealOfSurjection p hp k ≤ fittingIdealOfSurjection q hq k := by
  classical
  obtain ⟨v, hv⟩ := Module.projective_lifting_property p q hp
  let split : (Fin (n + n) → R) ≃ₗ[R]
      ((Fin n → R) × (Fin n → R)) :=
    { toFun := fun x => (x ∘ Fin.castAdd n, x ∘ Fin.natAdd n)
      invFun := fun x => Fin.addCases x.1 x.2
      left_inv := by
        intro x
        funext i
        exact Fin.addCases_castAdd_natAdd x i
      right_inv := by
        rintro ⟨x, y⟩
        apply Prod.ext
        · funext i
          simp [Fin.addCases_left]
        · funext i
          change Fin.addCases x y (Fin.natAdd n i) = y i
          rw [Fin.addCases_right]
      map_add' := by
        intro x y
        apply Prod.ext <;> funext i <;> simp [Function.comp_def]
      map_smul' := by
        intro c x
        apply Prod.ext <;> funext i <;> simp [Function.comp_def] }
  let Cprod : ((Fin n → R) × (Fin n → R)) →ₗ[R]
      ((Fin n → R) × (Fin n → R)) :=
    LinearMap.prod
      ((u.comp (LinearMap.fst R (Fin n → R) (Fin n → R))) +
        (LinearMap.snd R (Fin n → R) (Fin n → R)) -
        ((u.comp v).comp (LinearMap.snd R (Fin n → R) (Fin n → R))))
      ((LinearMap.fst R (Fin n → R) (Fin n → R)) -
        (v.comp (LinearMap.snd R (Fin n → R) (Fin n → R))))
  let Dprod : ((Fin n → R) × (Fin n → R)) →ₗ[R]
      ((Fin n → R) × (Fin n → R)) :=
    LinearMap.prod
      ((v.comp (LinearMap.fst R (Fin n → R) (Fin n → R))) +
        (LinearMap.snd R (Fin n → R) (Fin n → R)) -
        ((v.comp u).comp (LinearMap.snd R (Fin n → R) (Fin n → R))))
      ((LinearMap.fst R (Fin n → R) (Fin n → R)) -
        (u.comp (LinearMap.snd R (Fin n → R) (Fin n → R))))
  have hDCprod : Dprod.comp Cprod =
      LinearMap.id := by
    ext ⟨x, y⟩ <;>
      simp [Cprod, Dprod, LinearMap.comp_apply, sub_eq_add_neg,
        add_assoc, add_comm, add_left_comm]
  let C : (Fin (n + n) → R) →ₗ[R] (Fin (n + n) → R) :=
    split.symm.toLinearMap.comp (Cprod.comp split.toLinearMap)
  let D : (Fin (n + n) → R) →ₗ[R] (Fin (n + n) → R) :=
    split.symm.toLinearMap.comp (Dprod.comp split.toLinearMap)
  have hDC : D.comp C = LinearMap.id := by
    apply LinearMap.ext
    intro x
    simp only [LinearMap.comp_apply, LinearMap.id_apply]
    apply split.injective
    calc
      split (D (C x)) = Dprod (split (C x)) := by
        change split (split.symm (Dprod (split (C x)))) = _
        exact split.apply_symm_apply _
      _ = Dprod (Cprod (split x)) := by
        congr 1
        change split (split.symm (Cprod (split x))) = _
        exact split.apply_symm_apply _
      _ = split x := by
        rw [← LinearMap.comp_apply, hDCprod]
        rfl
  have hCfirst (x : Fin (n + n) → R) :
      (C x) ∘ Fin.castAdd n =
        u (x ∘ Fin.castAdd n) + x ∘ Fin.natAdd n -
          u (v (x ∘ Fin.natAdd n)) := by
    funext i
    simp [C, Cprod, split, Function.comp_def, Fin.addCases_left]
  have hfactor : stabilize p n = (stabilize q n).comp C := by
    apply LinearMap.ext
    intro x
    change p (x ∘ Fin.castAdd n) = q ((C x) ∘ Fin.castAdd n)
    rw [hCfirst]
    simp only [map_sub, map_add]
    have hu' (x : Fin n → R) : q (u x) = p x := by
      simpa [LinearMap.comp_apply] using congrArg (fun f : (Fin n → R) →ₗ[R] M => f x) hu
    have hv' (x : Fin n → R) : p (v x) = q x := by
      simpa [LinearMap.comp_apply] using congrArg (fun f : (Fin n → R) →ₗ[R] M => f x) hv
    rw [hu', hu', hv']
    abel
  have hDC_apply (x : Fin (n + n) → R) : D (C x) = x := by
    rw [← LinearMap.comp_apply, hDC]
    rfl
  have hstable :
      fittingIdealOfSurjection (stabilize p n)
          (stabilize_surjective p hp n) k ≤
        fittingIdealOfSurjection (stabilize q n)
          (stabilize_surjective q hq n) k := by
    unfold fittingIdealOfSurjection
    refine iSup_le ?_
    intro z
    let w : Fin (n + n - k) → LinearMap.ker (stabilize q n) := fun j =>
      ⟨C (z j).1, by
        apply LinearMap.mem_ker.mpr
        have hmap : (stabilize q n) (C (z j).1) =
            (stabilize p n) (z j).1 := by
          simpa [LinearMap.comp_apply] using
            congrArg (fun f : (Fin (n + n) → R) →ₗ[R] M => f (z j).1)
              hfactor.symm
        rw [hmap]
        exact (z j).property⟩
    have hrel :
        relationMatrix (stabilize p n) z =
          LinearMap.toMatrix' D * relationMatrix (stabilize q n) w := by
      apply Matrix.ext
      intro i j
      change (z j).1 i =
        Matrix.mulVec (LinearMap.toMatrix' D) (C (z j).1) i
      rw [LinearMap.toMatrix'_mulVec, hDC_apply]
    calc
      minorIdeal (relationMatrix (stabilize p n) z) (n + n - k) ≤
          minorIdeal (relationMatrix (stabilize q n) w) (n + n - k) := by
        rw [hrel]
        exact minorIdeal_left_mul (n := n + n) (m := n + n - k)
          (r := n + n - k) (LinearMap.toMatrix' D)
          (relationMatrix (stabilize q n) w)
      _ ≤ ⨆ y : Fin (n + n - k) → LinearMap.ker (stabilize q n),
          minorIdeal (relationMatrix (stabilize q n) y) (n + n - k) :=
        le_iSup (fun y : Fin (n + n - k) → LinearMap.ker (stabilize q n) =>
          minorIdeal (relationMatrix (stabilize q n) y) (n + n - k)) w
  have minorIdeal_zero
      {r m : ℕ} (A : Matrix (Fin r) (Fin m) R) : minorIdeal A 0 = ⊤ := by
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨∅, ∅, by simp, by simp, ?_⟩
    simp [matrixMinor]
  have fittingIdeal_zero_of_le
      {r : ℕ} (a : (Fin r → R) →ₗ[R] M)
      (ha : Function.Surjective a) (hrk : r ≤ k) :
      fittingIdealOfSurjection a ha k = ⊤ := by
    apply le_antisymm le_top
    unfold fittingIdealOfSurjection
    have hsub : r - k = 0 := Nat.sub_eq_zero_of_le hrk
    let z0 : Fin (r - k) → LinearMap.ker a := fun i => Fin.elim0 (hsub ▸ i)
    have hz : minorIdeal (relationMatrix a z0) (r - k) = ⊤ := by
      simpa [hsub] using minorIdeal_zero (relationMatrix a z0)
    calc
      ⊤ = minorIdeal (relationMatrix a z0) (r - k) := hz.symm
      _ ≤ ⨆ z : Fin (r - k) → LinearMap.ker a,
          minorIdeal (relationMatrix a z) (r - k) :=
        le_iSup (fun z : Fin (r - k) → LinearMap.ker a =>
          minorIdeal (relationMatrix a z) (r - k)) z0
  by_cases hk : k ≤ n
  · exact (fittingIdealOfSurjection_stabilize_ge p hp n k hk).trans
      (hstable.trans (fittingIdealOfSurjection_stabilize_le q hq n k hk))
  · have hnk : n ≤ k := Nat.le_of_not_ge hk
    rw [fittingIdeal_zero_of_le p hp hnk, fittingIdeal_zero_of_le q hq hnk]

/-- Independence of the Fitting ideal from the chosen finite-free surjection. -/
theorem fittingIdealOfSurjection_eq
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n m : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (q : (Fin m → R) →ₗ[R] M)
    (hp : Function.Surjective p) (hq : Function.Surjective q) (k : ℕ) :
    fittingIdealOfSurjection p hp k = fittingIdealOfSurjection q hq k := by
  sorry

theorem fittingIdeal_negOne_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdealNegOne R M ≤ fittingIdeal R M 0 := by
  exact bot_le

theorem fittingIdeal_mono_succ
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) :
    fittingIdeal R M k ≤ fittingIdeal R M (k + 1) := by
  classical
  have minorIdeal_zero
      {n m : ℕ} (A : Matrix (Fin n) (Fin m) R) : minorIdeal A 0 = ⊤ := by
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨∅, ∅, by simp, by simp, ?_⟩
    simp [matrixMinor]
  let h := Module.Finite.exists_fin' R M
  let n := h.choose
  let p := h.choose_spec.choose
  let hp := h.choose_spec.choose_spec
  unfold fittingIdeal
  dsimp
  refine iSup_le fun z => ?_
  by_cases hkn : k < n
  · unfold fittingIdealOfSurjection
    let t := h.choose - (k + 1)
    have hst : t + 1 = n - k := by
      dsimp [t, n]
      omega
    have hmono :
        minorIdeal (relationMatrix p z) (n - k) ≤
          minorIdeal (relationMatrix p z) t := by
      simpa only [hst] using minorIdeal_mono_succ (relationMatrix p z) t
    refine hmono.trans ?_
    apply Ideal.span_le.2
    rintro x ⟨rows, cols, hrows, hcols, rfl⟩
    let z' : Fin t → LinearMap.ker p :=
      fun j => z (cols.orderIsoOfFin hcols j)
    refine (le_iSup (fun w : Fin t → LinearMap.ker p =>
      minorIdeal (relationMatrix p w) t) z') ?_
    apply Ideal.subset_span
    refine ⟨rows, Finset.univ, hrows, by simp [t], ?_⟩
    dsimp [matrixMinor, relationMatrix, z']
    apply congrArg Matrix.det
    apply Matrix.ext
    intro i j
    dsimp [relationMatrix, z']
    have hj : (Finset.univ.orderEmbOfFin (by simp) j : Fin t) = j := by
      apply Fin.ext
      simp [Finset.orderEmbOfFin_apply, Fin.sort_univ]
    have hc :
        cols.orderEmbOfFin hcols
            ((Finset.univ.orderEmbOfFin (by simp) j : Fin t)) =
          cols.orderEmbOfFin hcols j := by
      rw [hj]
    rw [hc]
  · unfold fittingIdealOfSurjection
    have hnk : h.choose ≤ k := by
      exact Nat.le_of_not_gt (by simpa [n] using hkn)
    have hk0 : h.choose - k = 0 := Nat.sub_eq_zero_of_le hnk
    have hk1 : h.choose - (k + 1) = 0 :=
      Nat.sub_eq_zero_of_le (le_trans hnk (Nat.le_succ _))
    let z0 : Fin (h.choose - (k + 1)) → LinearMap.ker p :=
      fun i => Fin.elim0 (hk1 ▸ i)
    have hleft :
        minorIdeal (relationMatrix p z) (h.choose - k) = ⊤ := by
      calc
        minorIdeal (relationMatrix p z) (h.choose - k) =
            minorIdeal (relationMatrix p z) 0 :=
          congrArg (fun s => minorIdeal (relationMatrix p z) s) hk0
        _ = ⊤ := minorIdeal_zero _
    have hright :
        minorIdeal (relationMatrix p z0) (h.choose - (k + 1)) = ⊤ := by
      calc
        minorIdeal (relationMatrix p z0) (h.choose - (k + 1)) =
            minorIdeal (relationMatrix p z0) 0 :=
          congrArg (fun s => minorIdeal (relationMatrix p z0) s) hk1
        _ = ⊤ := minorIdeal_zero _
    calc
      minorIdeal (relationMatrix p z) (h.choose - k) = ⊤ := hleft
      _ = minorIdeal (relationMatrix p z0) (h.choose - (k + 1)) := hright.symm
      _ ≤ ⨆ w : Fin (h.choose - (k + 1)) → LinearMap.ker p,
          minorIdeal (relationMatrix p w) (h.choose - (k + 1)) :=
        le_iSup (fun w : Fin (h.choose - (k + 1)) → LinearMap.ker p =>
          minorIdeal (relationMatrix p w) (h.choose - (k + 1))) z0

theorem exists_fittingIdeal_eq_top
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    ∃ t : ℕ, fittingIdeal R M t = ⊤ := by
  have minorIdeal_zero
      {n m : ℕ} (A : Matrix (Fin n) (Fin m) R) : minorIdeal A 0 = ⊤ := by
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨∅, ∅, by simp, by simp, ?_⟩
    simp [matrixMinor]
  let h := Module.Finite.exists_fin' R M
  refine ⟨h.choose, ?_⟩
  unfold fittingIdeal
  dsimp
  change fittingIdealOfSurjection h.choose_spec.choose h.choose_spec.choose_spec h.choose = ⊤
  unfold fittingIdealOfSurjection
  apply top_unique
  let z0 : Fin (h.choose - h.choose) → LinearMap.ker h.choose_spec.choose :=
    fun i => Fin.elim0 ((Nat.sub_self h.choose) ▸ i)
  refine le_iSup_of_le z0 ?_
  have hz : minorIdeal (relationMatrix h.choose_spec.choose z0) (h.choose - h.choose) = ⊤ := by
    simpa only [Nat.sub_self] using (minorIdeal_zero (relationMatrix h.choose_spec.choose z0))
  rw [hz]

/-! ## Basic properties -/

theorem fittingIdeal_eq_top_of_surjective
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] {n : ℕ}
    (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p) :
    fittingIdeal R M n = ⊤ := by
  have minorIdeal_zero
      {n m : ℕ} (A : Matrix (Fin n) (Fin m) R) : minorIdeal A 0 = ⊤ := by
    apply (Ideal.eq_top_iff_one _).mpr
    apply Ideal.subset_span
    refine ⟨∅, ∅, by simp, by simp, ?_⟩
    simp [matrixMinor]
  let h := Module.Finite.exists_fin' R M
  unfold fittingIdeal
  dsimp
  rw [← fittingIdealOfSurjection_eq p h.choose_spec.choose hp h.choose_spec.choose_spec n]
  unfold fittingIdealOfSurjection
  apply top_unique
  let z0 : Fin (n - n) → LinearMap.ker p :=
    fun i => Fin.elim0 ((Nat.sub_self n) ▸ i)
  refine le_iSup_of_le z0 ?_
  have hz : minorIdeal (relationMatrix p z0) (n - n) = ⊤ := by
    simpa only [Nat.sub_self] using (minorIdeal_zero (relationMatrix p z0))
  rw [hz]

theorem fittingIdeal_prod_zero
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N] :
    fittingIdeal R (M × N) 0 = fittingIdeal R M 0 * fittingIdeal R N 0 := by
  sorry

theorem fittingIdeal_prod
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N] (l : ℕ) :
    fittingIdeal R (M × N) l =
      ⨆ k : ℕ, ⨆ k' : ℕ, ⨆ (_h : k + k' = l),
        fittingIdeal R M k * fittingIdeal R N k' := by
  sorry

theorem fittingIdeal_baseChange
    {R S M : Type*} [CommRing R] [CommRing S] [Algebra R S]
    [AddCommGroup M] [Module R M] [Module.Finite R M] (k : ℕ) :
    fittingIdeal S (S ⊗[R] M) k =
      Ideal.map (algebraMap R S) (fittingIdeal R M k) := by
  classical
  let h := Module.Finite.exists_fin' R M
  let p := h.choose_spec.choose
  let hp := h.choose_spec.choose_spec
  let e := TensorProduct.piScalarRight R S S (Fin h.choose)
  let pS := (p.baseChange S).comp e.symm.toLinearMap
  have hpS : Function.Surjective pS := by
    intro y
    obtain ⟨y', rfl⟩ := LinearMap.baseChange_surjective S hp y
    exact ⟨e y', by simp [pS, p]⟩
  let zS : (Fin (h.choose - k) → LinearMap.ker p) →
      (Fin (h.choose - k) → LinearMap.ker pS) := fun z j =>
    ⟨e (1 ⊗ₜ[R] (z j).1), by
      apply LinearMap.mem_ker.mpr
      change (p.baseChange S) (e.symm (e (1 ⊗ₜ[R] (z j).1))) = 0
      rw [e.symm_apply_apply, LinearMap.baseChange_tmul]
      simp⟩
  have hsmul (r : R) : r • (1 : S) = algebraMap R S r := by
    rw [Algebra.smul_def]
    simp
  have hrel (z : Fin (h.choose - k) → LinearMap.ker p) :
      relationMatrix pS (zS z) =
        (relationMatrix p z).map (algebraMap R S) := by
    ext i j
    simp [zS, relationMatrix, e, hsmul]
  have minorIdeal_map_le {n m r : ℕ} (A : Matrix (Fin n) (Fin m) R) :
      Ideal.map (algebraMap R S) (minorIdeal A r) ≤
        minorIdeal (A.map (algebraMap R S)) r := by
    apply Ideal.map_le_iff_le_comap.mpr
    apply Ideal.span_le.2
    rintro x ⟨rows, cols, hrows, hcols, rfl⟩
    apply Ideal.subset_span
    refine ⟨rows, cols, hrows, hcols, ?_⟩
    dsimp [matrixMinor]
    rw [RingHom.map_det]
    rfl
  have hmap_le :
      Ideal.map (algebraMap R S)
          (fittingIdealOfSurjection p hp k) ≤
        fittingIdealOfSurjection pS hpS k := by
    apply Ideal.map_le_iff_le_comap.mpr
    unfold fittingIdealOfSurjection
    refine iSup_le fun z => ?_
    apply (Ideal.map_le_iff_le_comap).mp
    calc
      Ideal.map (algebraMap R S) (minorIdeal (relationMatrix p z) (h.choose - k)) ≤
          minorIdeal ((relationMatrix p z).map (algebraMap R S)) (h.choose - k) :=
        minorIdeal_map_le (relationMatrix p z)
      _ = minorIdeal (relationMatrix pS (zS z)) (h.choose - k) := by
        rw [hrel z]
      _ ≤ ⨆ w : Fin (h.choose - k) → LinearMap.ker pS,
          minorIdeal (relationMatrix pS w) (h.choose - k) :=
        le_iSup (fun w : Fin (h.choose - k) → LinearMap.ker pS =>
          minorIdeal (relationMatrix pS w) (h.choose - k)) (zS z)
  let g : S ⊗[R] LinearMap.ker p →ₗ[S] (Fin h.choose → S) :=
    e.toLinearMap.comp ((LinearMap.ker p).subtype.baseChange S)
  have g_tmul (s : S) (v : LinearMap.ker p) :
      g (s ⊗ₜ[R] v) = s • (fun i => algebraMap R S (v.1 i)) := by
    ext i
    simp [g, e, Algebra.smul_def, mul_comm]
  have hpreimage (z : LinearMap.ker pS) :
      ∃ w : S ⊗[R] LinearMap.ker p, g w = z.1 := by
    have hz0 : pS z.1 = 0 := z.2
    have hz : e.symm z.1 ∈ LinearMap.ker (LinearMap.lTensor S p) := by
      rw [LinearMap.mem_ker]
      rw [← LinearMap.baseChange_eq_ltensor]
      change (p.baseChange S) (e.symm z.1) = 0
      exact hz0
    have hz' : e.symm z.1 ∈
        LinearMap.range (LinearMap.lTensor S (LinearMap.ker p).subtype) := by
      rw [← (lTensor_exact S p.exact_subtype_ker_map hp).linearMap_ker_eq]
      exact hz
    obtain ⟨w, hw⟩ := LinearMap.mem_range.mp hz'
    refine ⟨w, ?_⟩
    change e ((LinearMap.ker p).subtype.baseChange S w) = z.1
    rw [LinearMap.baseChange_eq_ltensor, hw]
    exact e.apply_symm_apply _
  have det_tensor_mem (w : Fin (h.choose - k) → S ⊗[R] LinearMap.ker p)
      (rows : Fin (h.choose - k) → Fin h.choose)
      (hdet : ∀ v : Fin (h.choose - k) → LinearMap.ker p,
        Matrix.det ((relationMatrix (k := k) p v).submatrix rows id) ∈
          fittingIdealOfSurjection p hp k) :
      Matrix.det (fun i j => g (w j) (rows i)) ∈
        Ideal.map (algebraMap R S) (fittingIdealOfSurjection p hp k) := by
    let J : Ideal S := Ideal.map (algebraMap R S) (fittingIdealOfSurjection p hp k)
    have aux : ∀ s : Finset (Fin (h.choose - k)),
        ∀ A : Matrix (Fin (h.choose - k)) (Fin (h.choose - k)) S,
        (∀ j ∈ s, ∀ i, A i j = g (w j) (rows i)) →
        (∀ j ∉ s, ∃ v : LinearMap.ker p,
          ∀ i, A i j = g (1 ⊗ₜ[R] v) (rows i)) →
        Matrix.det A ∈ J := by
      intro s
      induction s using Finset.strongInductionOn with
      | _ s ih =>
          intro A hA hpure
          classical
          by_cases hs : s.Nonempty
          · obtain ⟨a, ha⟩ := hs
            let A₀ : Matrix (Fin (h.choose - k)) (Fin (h.choose - k)) S :=
              A.updateCol a 0
            let F : (S ⊗[R] LinearMap.ker p) →ₗ[S] S :=
              { toFun := fun x =>
                  Matrix.det (A₀.updateCol a (fun i => g x (rows i)))
                map_add' := by
                  intro x y
                  have hxy : (fun i => g (x + y) (rows i)) =
                      (fun i => g x (rows i)) + (fun i => g y (rows i)) := by
                    funext i
                    simp
                  rw [hxy, Matrix.det_updateCol_add]
                map_smul' := by
                  intro c x
                  have hcx : (fun i => g (c • x) (rows i)) =
                      c • (fun i => g x (rows i)) := by
                    funext i
                    simp
                  rw [hcx, Matrix.det_updateCol_smul]
                  simp [smul_eq_mul] }
            have hFA : F (w a) = Matrix.det A := by
              apply congrArg Matrix.det
              ext i j
              by_cases hja : j = a
              · subst j
                simp [A₀]
                exact (hA a ha i).symm
              · simp [A₀, hja]
            rw [← hFA]
            induction w a using TensorProduct.induction_on with
            | zero =>
                simp [F, A₀, Matrix.det_eq_zero_of_column_eq_zero a]
            | add x y hx hy =>
                rw [map_add]
                exact J.add_mem hx hy
            | tmul c v =>
                let B : Matrix (Fin (h.choose - k)) (Fin (h.choose - k)) S :=
                  A₀.updateCol a (fun i => g (1 ⊗ₜ[R] v) (rows i))
                have hB : Matrix.det B ∈ J := by
                  apply ih (s.erase a) (Finset.erase_ssubset ha) B
                  · intro j hj i
                    have hj' : j ∈ s := Finset.mem_of_mem_erase hj
                    have hja : j ≠ a := Finset.ne_of_mem_erase hj
                    simpa [B, A₀, hja] using hA j hj' i
                  · intro j hj
                    by_cases hja : j = a
                    · subst j
                      exact ⟨v, by simp [B, A₀]⟩
                    · have hjs : j ∉ s := by
                        intro hjs
                        exact hj (Finset.mem_erase.mpr ⟨hja, hjs⟩)
                      obtain ⟨v', hv'⟩ := hpure j hjs
                      refine ⟨v', ?_⟩
                      simpa [B, A₀, hja] using hv' 
                have hgc : (fun i => g (c ⊗ₜ[R] v) (rows i)) =
                    c • (fun i => g (1 ⊗ₜ[R] v) (rows i)) := by
                  funext i
                  rw [g_tmul, g_tmul]
                  simp
                rw [show F (c ⊗ₜ[R] v) =
                      Matrix.det (A₀.updateCol a
                        (c • (fun i => g (1 ⊗ₜ[R] v) (rows i)))) by
                    simp [F, hgc], Matrix.det_updateCol_smul]
                exact J.mul_mem_left c hB
          · have hs0 : s = ∅ := Finset.not_nonempty_iff_eq_empty.mp hs
            subst s
            let v : Fin (h.choose - k) → LinearMap.ker p := fun j =>
              Classical.choose (hpure j (by simp))
            have hv (j : Fin (h.choose - k)) :
                ∀ i, A i j = g (1 ⊗ₜ[R] v j) (rows i) :=
              Classical.choose_spec (hpure j (by simp))
            have hAeq : A =
                ((relationMatrix (k := k) p v).submatrix rows id).map
                  (algebraMap R S) := by
              ext i j
              rw [hv j i]
              simp [g, e, relationMatrix, hsmul]
            rw [hAeq]
            have hmem := Ideal.mem_map_of_mem (algebraMap R S) (hdet v)
            rw [RingHom.map_det] at hmem
            exact hmem
    apply aux (Finset.univ : Finset (Fin (h.choose - k)))
    · intro j hj i
      rfl
    · intro j hj
      exact False.elim (hj (Finset.mem_univ j))
  have hrev :
      fittingIdealOfSurjection pS hpS k ≤
        Ideal.map (algebraMap R S) (fittingIdealOfSurjection p hp k) := by
    unfold fittingIdealOfSurjection
    refine iSup_le fun z => ?_
    apply Ideal.span_le.2
    rintro x ⟨rowsSet, colsSet, hrows, hcols, rfl⟩
    have hcols_eq : colsSet = (Finset.univ : Finset (Fin (h.choose - k))) :=
      Finset.eq_univ_of_card colsSet (by simpa using hcols)
    subst colsSet
    let rows : Fin (h.choose - k) → Fin h.choose :=
      fun i => Finset.orderEmbOfFin rowsSet hrows i
    let w : Fin (h.choose - k) → S ⊗[R] LinearMap.ker p := fun j =>
      Classical.choose (hpreimage (z j))
    have hw (j : Fin (h.choose - k)) : g (w j) = (z j).1 :=
      Classical.choose_spec (hpreimage (z j))
    have hdet (v : Fin (h.choose - k) → LinearMap.ker p) :
          Matrix.det ((relationMatrix (k := k) p v).submatrix rows id) ∈
          fittingIdealOfSurjection p hp k := by
      unfold fittingIdealOfSurjection
      apply (le_iSup (fun v : Fin (h.choose - k) → LinearMap.ker p =>
        minorIdeal (relationMatrix p v) (h.choose - k)) v)
      apply Ideal.subset_span
      refine ⟨rowsSet, Finset.univ, hrows, Finset.card_fin _, ?_⟩
      dsimp [matrixMinor, rows]
      apply congrArg Matrix.det
      apply Matrix.ext
      intro i j
      have huniv :
          (fun j : Fin (h.choose - k) =>
            (Finset.univ.orderEmbOfFin (Finset.card_fin (h.choose - k)) j :
              Fin (h.choose - k))) = id := by
        have h := Finset.orderEmbOfFin_unique
          (s := (Finset.univ : Finset (Fin (h.choose - k))))
          (Finset.card_fin (h.choose - k))
          (f := (id : Fin (h.choose - k) → Fin (h.choose - k)))
          (fun _ => Finset.mem_univ _) strictMono_id
        exact h.symm
      change (relationMatrix p v)
          (Finset.orderEmbOfFin rowsSet hrows i) j =
        (relationMatrix p v)
          (Finset.orderEmbOfFin rowsSet hrows i)
          ((Finset.univ.orderEmbOfFin (Finset.card_fin (h.choose - k)) j :
            Fin (h.choose - k)))
      rw [congrFun huniv j]
      rfl
    have hmatrix :
        (relationMatrix pS z).submatrix rows id =
          fun i j => g (w j) (rows i) := by
      ext i j
      change (z j).1 (rows i) = g (w j) (rows i)
      exact (congrFun (hw j) (rows i)).symm
    rw [show matrixMinor (relationMatrix pS z) rowsSet Finset.univ hrows hcols =
        Matrix.det ((relationMatrix pS z).submatrix rows id) by
          dsimp [matrixMinor, rows]
          apply congrArg Matrix.det
          apply Matrix.ext
          intro i j
          have huniv :
              (fun j : Fin (h.choose - k) =>
                (Finset.univ.orderEmbOfFin hcols j :
                  Fin (h.choose - k))) = id := by
            have h := Finset.orderEmbOfFin_unique
              (s := (Finset.univ : Finset (Fin (h.choose - k))))
              hcols
              (f := (id : Fin (h.choose - k) → Fin (h.choose - k)))
              (fun _ => Finset.mem_univ _) strictMono_id
            exact h.symm
          simp only [Matrix.submatrix_apply]
          rw [congrFun huniv j]]
    rw [hmatrix]
    exact det_tensor_mem w rows hdet
  let hS := Module.Finite.exists_fin' S (S ⊗[R] M)
  let q := hS.choose_spec.choose
  let hq := hS.choose_spec.choose_spec
  have hfit :
      fittingIdealOfSurjection pS hpS k =
        Ideal.map (algebraMap R S) (fittingIdealOfSurjection p hp k) :=
    le_antisymm hrev hmap_le
  have hpresentation : fittingIdeal R M k = fittingIdealOfSurjection p hp k := by
    unfold fittingIdeal
    rfl
  calc
    fittingIdeal S (S ⊗[R] M) k = fittingIdealOfSurjection q hq k := by
      rfl
    _ = fittingIdealOfSurjection pS hpS k :=
      fittingIdealOfSurjection_eq q pS hq hpS k
    _ = Ideal.map (algebraMap R S) (fittingIdealOfSurjection p hp k) := hfit
    _ = Ideal.map (algebraMap R S) (fittingIdeal R M k) := by
      rw [hpresentation]

theorem fittingIdeal_linearEquiv
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    (e : M ≃ₗ[R] N) (k : ℕ) :
    fittingIdeal R M k = fittingIdeal R N k := by
  let hM := Module.Finite.exists_fin' R M
  let hN := Module.Finite.exists_fin' R N
  let p := hM.choose_spec.choose
  let hp := hM.choose_spec.choose_spec
  let q := e.toLinearMap.comp p
  have hq : Function.Surjective q := by
    intro y
    obtain ⟨x, hx⟩ := hp (e.symm y)
    refine ⟨x, ?_⟩
    dsimp [q]
    rw [hx]
    exact e.apply_symm_apply y
  have htransport :
      fittingIdealOfSurjection p hp k =
        fittingIdealOfSurjection q hq k := by
    unfold fittingIdealOfSurjection
    apply le_antisymm
    · refine iSup_le ?_
      intro z
      let z' : Fin (hM.choose - k) → LinearMap.ker q := fun j =>
        ⟨(z j).1, by
          apply LinearMap.mem_ker.mpr
          change e (p (z j).1) = 0
          rw [(z j).property]
          simp⟩
      have hz : relationMatrix q z' = relationMatrix p z := by
        ext i j
        rfl
      rw [← hz]
      exact le_iSup (fun w : Fin (hM.choose - k) → LinearMap.ker q =>
        minorIdeal (relationMatrix q w) (hM.choose - k)) z'
    · refine iSup_le ?_
      intro z
      let z' : Fin (hM.choose - k) → LinearMap.ker p := fun j =>
        ⟨(z j).1, by
          apply LinearMap.mem_ker.mpr
          apply e.injective
          simpa [q] using (z j).property⟩
      have hz : relationMatrix p z' = relationMatrix q z := by
        ext i j
        rfl
      rw [← hz]
      exact le_iSup (fun w : Fin (hM.choose - k) → LinearMap.ker p =>
        minorIdeal (relationMatrix p w) (hM.choose - k)) z'
  calc
    fittingIdeal R M k = fittingIdealOfSurjection p hp k := by
      rfl
    _ = fittingIdealOfSurjection q hq k := htransport
    _ = fittingIdealOfSurjection hN.choose_spec.choose
        hN.choose_spec.choose_spec k :=
      fittingIdealOfSurjection_eq q hN.choose_spec.choose hq
        hN.choose_spec.choose_spec k
    _ = fittingIdeal R N k := by
      rfl

/-- Fitting ideals are unchanged by a finite module which is isomorphic to its
    extension of scalars along an endomorphism of the base ring. -/
theorem fittingIdeal_extendScalars
    {R M : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (f : R →+* R)
    (e : ((ModuleCat.extendScalars f).obj (ModuleCat.of R M)) ≃ₗ[R] M)
    (k : ℕ) :
    fittingIdeal R M k = Ideal.map f (fittingIdeal R M k) := by
  let _ : Algebra R R := f.toAlgebra
  let _ : Module.Finite R
      ((ModuleCat.extendScalars f).obj (ModuleCat.of R M) : Type _) :=
    Module.Finite.equiv e.symm
  have hbase := fittingIdeal_baseChange (R := R) (S := R) (M := M) k
  have hequiv := fittingIdeal_linearEquiv
    (R := R) (M := ((ModuleCat.extendScalars f).obj (ModuleCat.of R M) : Type _))
    (N := M) e k
  simpa only [RingHom.algebraMap_toAlgebra] using hequiv.symm.trans hbase

theorem fittingIdeal_fg
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.FinitePresentation R M] (k : ℕ) :
    (fittingIdeal R M k).FG := by
  sorry

theorem fittingIdeal_mono_of_surjective
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    (φ : M →ₗ[R] N) (hφ : Function.Surjective φ) (k : ℕ) :
    fittingIdeal R M k ≤ fittingIdeal R N k := by
  sorry

theorem fittingIdeal_zero_le_annihilator
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdeal R M 0 ≤ Module.annihilator R M := by
  sorry

theorem zeroLocus_fittingIdeal_zero_eq_support
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    PrimeSpectrum.zeroLocus (fittingIdeal R M 0 : Set R) = Module.support R M := by
  sorry

theorem fittingIdeal_quotient_zero
    {R : Type*} [CommRing R] (I : Ideal R) :
    fittingIdeal R (R ⧸ I) 0 = I := by
  sorry

/-! ## Examples -/

theorem fittingIdeal_fin_free
    {R : Type*} [CommRing R] (n : ℕ) :
    (∀ k : ℕ, k < n → fittingIdeal R (Fin n → R) k = ⊥) ∧
      (∀ k : ℕ, n ≤ k → fittingIdeal R (Fin n → R) k = ⊤) := by
  sorry

theorem fittingIdeal_laurent
    {R : Type*} [CommRing R] (I J : Ideal R) :
    fittingIdeal R (R ⧸ I) 0 = I ∧
      fittingIdeal R ((R ⧸ I) × (R ⧸ J)) 0 = I * J ∧
        fittingIdeal R ((R ⧸ I) × (R ⧸ J)) 1 = I + J := by
  sorry

/-! ## Local generation and finite locally free modules -/

theorem fittingIdeal_generate_locally
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) (p : PrimeSpectrum R) :
    List.TFAE [
      ¬ fittingIdeal R M k ≤ p.asIdeal,
      Module.finrank p.asIdeal.ResidueField (p.asIdeal.Fiber M) ≤ k,
      ∃ g : (Fin k → Localization.AtPrime p.asIdeal) →ₗ[Localization.AtPrime p.asIdeal]
          LocalizedModule p.asIdeal.primeCompl M, Function.Surjective g,
      ∃ f : R, f ∉ p.asIdeal ∧
        ∃ g : (Fin k → Localization.Away f) →ₗ[Localization.Away f]
            LocalizedModule.Away f M, Function.Surjective g] := by
  sorry

theorem fittingIdeal_finiteLocallyFreeOfRank
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (r : ℕ) :
    List.TFAE [
      FiniteLocallyFreeOfRank R M r,
      fittingIdealInt R M ((r : ℤ) - 1) = ⊥ ∧ fittingIdeal R M r = ⊤,
      (∀ k : ℕ, k < r → fittingIdeal R M k = ⊥) ∧
        (∀ k : ℕ, r ≤ k → fittingIdeal R M k = ⊤)] := by
  sorry

/-! ## Principal Fitting ideals and the projective-dimension statement -/

/- The source-facing names below retain the interfaces consumed by later
   chapters, while their implementations use Mathlib's canonical torsion
   submodules. -/
/-- The submodule annihilated by multiplication by a scalar. -/
abbrev scalarTorsionSubmodule
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) : Submodule R M :=
  Submodule.torsionBy R M f

/-- The submodule of elements killed by some power of a scalar. -/
abbrev scalarPowerTorsionSubmodule
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) : Submodule R M :=
  Submodule.torsion' R M (Submonoid.powers f)

theorem quotient_by_principal_fitting_torsion_generated
    {R M : Type*} [CommRing R] [IsLocalRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (k : ℕ) (f : R) (hfit : fittingIdeal R M k = Ideal.span {f}) :
    ∃ g : (Fin k → R) →ₗ[R]
          (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f),
      Function.Surjective g := by
  sorry

theorem fittingIdeal_principal_nonzerodivisor
    {R M : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.FinitePresentation R M]
    (k : ℕ) (f : R) (hf : f ∈ nonZeroDivisors R)
    (hfit : fittingIdeal R M k = Ideal.span {f})
    (hprev : fittingIdealInt R M ((k : ℤ) - 1) = ⊥) :
    CategoryTheory.HasProjectiveDimensionLE (ModuleCat.of R M) 1 ∧
      scalarTorsionSubmodule (R := R) (M := M) f =
          scalarPowerTorsionSubmodule (R := R) (M := M) f ∧
        CategoryTheory.HasProjectiveDimensionLE
            (ModuleCat.of R
              (scalarTorsionSubmodule (R := R) (M := M) f : Type _)) 1 ∧
          FiniteLocallyFreeOfRank R
            (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f) k ∧
            Nonempty
              (M ≃ₗ[R]
                (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f) ×
                  (scalarTorsionSubmodule (R := R) (M := M) f : Type _)) := by
  sorry

end

end Formalization.Books.MoreAlgebra.Unit08
