import Formalization.Books.Algebra.Unit40.SupportsAndAnnihilators
import Formalization.Books.Algebra.Unit78.FiniteProjectiveModules
import Mathlib.Algebra.Category.ModuleCat.ProjectiveDimension
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.RingTheory.Finiteness.Prod
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Support
import Mathlib.RingTheory.TensorProduct.Finite
import Mathlib.Data.Matrix.Block

/-!
# More on Algebra, Chapter 8: Fitting ideals

The Fitting ideals are defined from the minors of a presentation by a finite
free module.  The independence of the chosen presentation is recorded as a
theorem, so the definition can use Mathlib's canonical finite-free
surjection supplied by `Module.Finite.exists_fin'`.
-/

namespace Formalization.Books.MoreAlgebra.Unit08

open Formalization.Books.Algebra.Unit78
open Set
open scoped TensorProduct

noncomputable section

/-! ## Minors and the presentation-independent construction -/

/-- The determinant of the `r × r` submatrix indexed by two finite sets. -/
noncomputable def matrixMinor
    {R : Type*} [CommRing R] {n m r : ℕ}
    (A : Matrix (Fin n) (Fin m) R)
    (rows : Finset (Fin n)) (cols : Finset (Fin m))
    (hrows : rows.card = r) (hcols : cols.card = r) : R :=
  (A.submatrix
      (fun i => (rows.orderIsoOfFin hrows i : Fin n))
      (fun j => (cols.orderIsoOfFin hcols j : Fin m))).det

/-- The set of all `r × r` minors of a matrix. -/
noncomputable def matrixMinorSet
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) : Set R :=
  {x | ∃ (rows : Finset (Fin n)) (cols : Finset (Fin m))
      (hrows : rows.card = r) (hcols : cols.card = r),
      x = matrixMinor A rows cols hrows hcols}

/-- The ideal generated by all `r × r` minors of a matrix. -/
noncomputable def minorIdeal
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) : Ideal R :=
  Ideal.span (matrixMinorSet A r)

theorem minorIdeal_mono_succ
    {R : Type*} [CommRing R] {n m : ℕ}
    (A : Matrix (Fin n) (Fin m) R) (r : ℕ) :
    minorIdeal A (r + 1) ≤ minorIdeal A r := by
  sorry

theorem minorIdeal_firstRows
    {R : Type*} [CommRing R] {n n' m r : ℕ}
    (B : Matrix (Fin (n + n')) (Fin m) R) :
    minorIdeal B (r + n') ≤
      minorIdeal (B.submatrix (Fin.castAdd n') id) r := by
  sorry

theorem minorIdeal_left_mul
    {R : Type*} [CommRing R] {n m r : ℕ}
    (C : Matrix (Fin n) (Fin n) R) (A : Matrix (Fin n) (Fin m) R) :
    minorIdeal (C * A) r ≤ minorIdeal A r := by
  sorry

theorem minorIdeal_blockDiagonal
    {R : Type*} [CommRing R] {n₁ n₂ m₁ m₂ r : ℕ}
    (A₁ : Matrix (Fin n₁) (Fin m₁) R)
    (A₂ : Matrix (Fin n₂) (Fin m₂) R) :
    minorIdeal
        (Matrix.reindex finSumFinEquiv finSumFinEquiv
          (Matrix.fromBlocks A₁
            (0 : Matrix (Fin n₁) (Fin m₂) R)
            (0 : Matrix (Fin n₂) (Fin m₁) R) A₂)) r =
      ⨆ r₁ : ℕ, ⨆ r₂ : ℕ, ⨆ (_h : r₁ + r₂ = r),
        minorIdeal A₁ r₁ * minorIdeal A₂ r₂ := by
  sorry

/-- The matrix whose columns are a chosen finite family of relations. -/
def relationMatrix
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n k : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (z : Fin (n - k) → LinearMap.ker p) :
    Matrix (Fin n) (Fin (n - k)) R :=
  fun i j => (z j).1 i

/-- The Fitting ideal computed from a fixed finite-free surjection. -/
noncomputable def fittingIdealOfSurjection
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (_hp : Function.Surjective p) (k : ℕ) : Ideal R :=
  ⨆ z : Fin (n - k) → LinearMap.ker p,
    minorIdeal (relationMatrix p z) (n - k)

/-- The Fitting ideal of a finite module. -/
noncomputable def fittingIdeal
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) : Ideal R :=
  let h := Module.Finite.exists_fin' R M
  fittingIdealOfSurjection h.choose_spec.choose h.choose_spec.choose_spec k

/-- The Fitting ideal at the book's extra index `-1`. -/
def fittingIdealNegOne
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] : Ideal R :=
  ⊥

/-- A signed-index extension of the Fitting ideals, with all negative indices
set equal to zero.  This is used only to state the source's `r - 1` cases. -/
noncomputable def fittingIdealInt
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℤ) : Ideal R :=
  if 0 ≤ k then fittingIdeal R M k.toNat else ⊥

theorem fittingIdealInt_ofNat
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) :
    fittingIdealInt R M k = fittingIdeal R M k := by
  sorry

theorem fittingIdealInt_negOne
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdealInt R M (-1) = fittingIdealNegOne R M := by
  sorry

/-- Independence of the Fitting ideal from the chosen finite-free surjection. -/
theorem fittingIdealOfSurjection_eq
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    {n m : ℕ} (p : (Fin n → R) →ₗ[R] M)
    (q : (Fin m → R) →ₗ[R] M)
    (hp : Function.Surjective p) (hq : Function.Surjective q) (k : ℕ) :
    fittingIdealOfSurjection p hp k = fittingIdealOfSurjection q hq k := by
  sorry

theorem fittingIdeal_negOne_le
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdealNegOne R M ≤ fittingIdeal R M 0 := by
  sorry

theorem fittingIdeal_mono_succ
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) :
    fittingIdeal R M k ≤ fittingIdeal R M (k + 1) := by
  sorry

theorem exists_fittingIdeal_eq_top
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    ∃ t : ℕ, fittingIdeal R M t = ⊤ := by
  sorry

/-! ## Basic properties -/

theorem fittingIdeal_eq_top_of_surjective
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] {n : ℕ}
    (p : (Fin n → R) →ₗ[R] M) (hp : Function.Surjective p) :
    fittingIdeal R M n = ⊤ := by
  sorry

theorem fittingIdeal_prod_zero
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N] :
    fittingIdeal R (M × N) 0 = fittingIdeal R M 0 * fittingIdeal R N 0 := by
  sorry

theorem fittingIdeal_prod
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N] (l : ℕ) :
    fittingIdeal R (M × N) l =
      ⨆ k : ℕ, ⨆ k' : ℕ, ⨆ (_h : k + k' = l),
        fittingIdeal R M k * fittingIdeal R N k' := by
  sorry

theorem fittingIdeal_baseChange
    {R S M : Type*} [CommRing R] [CommRing S] [Algebra R S]
    [AddCommGroup M] [Module R M] [Module.Finite R M] (k : ℕ) :
    fittingIdeal S (S ⊗[R] M) k =
      Ideal.map (algebraMap R S) (fittingIdeal R M k) := by
  sorry

theorem fittingIdeal_fg
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.FinitePresentation R M] (k : ℕ) :
    (fittingIdeal R M k).FG := by
  sorry

theorem fittingIdeal_mono_of_surjective
    {R M N : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    (φ : M →ₗ[R] N) (hφ : Function.Surjective φ) (k : ℕ) :
    fittingIdeal R M k ≤ fittingIdeal R N k := by
  sorry

theorem fittingIdeal_zero_le_annihilator
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    fittingIdeal R M 0 ≤ Module.annihilator R M := by
  sorry

theorem zeroLocus_fittingIdeal_zero_eq_support
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] :
    PrimeSpectrum.zeroLocus (fittingIdeal R M 0 : Set R) = Module.support R M := by
  sorry

theorem fittingIdeal_quotient_zero
    {R : Type*} [CommRing R] (I : Ideal R) :
    fittingIdeal R (R ⧸ I) 0 = I := by
  sorry

/-! ## Examples -/

theorem fittingIdeal_fin_free
    {R : Type*} [CommRing R] (n : ℕ) :
    (∀ k : ℕ, k < n → fittingIdeal R (Fin n → R) k = ⊥) ∧
      (∀ k : ℕ, n ≤ k → fittingIdeal R (Fin n → R) k = ⊤) := by
  sorry

theorem fittingIdeal_laurent
    {R : Type*} [CommRing R] (I J : Ideal R) :
    fittingIdeal R (R ⧸ I) 0 = I ∧
      fittingIdeal R ((R ⧸ I) × (R ⧸ J)) 0 = I * J ∧
        fittingIdeal R ((R ⧸ I) × (R ⧸ J)) 1 = I + J := by
  sorry

/-! ## Local generation and finite locally free modules -/

theorem fittingIdeal_generate_locally
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (k : ℕ) (p : PrimeSpectrum R) :
    List.TFAE [
      ¬ fittingIdeal R M k ≤ p.asIdeal,
      Module.finrank p.asIdeal.ResidueField (p.asIdeal.Fiber M) ≤ k,
      ∃ g : (Fin k → Localization.AtPrime p.asIdeal) →ₗ[Localization.AtPrime p.asIdeal]
          LocalizedModule p.asIdeal.primeCompl M, Function.Surjective g,
      ∃ f : R, f ∉ p.asIdeal ∧
        ∃ g : (Fin k → Localization.Away f) →ₗ[Localization.Away f]
            LocalizedModule.Away f M, Function.Surjective g] := by
  sorry

theorem fittingIdeal_finiteLocallyFreeOfRank
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    [Module.Finite R M] (r : ℕ) :
    List.TFAE [
      FiniteLocallyFreeOfRank R M r,
      fittingIdealInt R M ((r : ℤ) - 1) = ⊥ ∧ fittingIdeal R M r = ⊤,
      (∀ k : ℕ, k < r → fittingIdeal R M k = ⊥) ∧
        (∀ k : ℕ, r ≤ k → fittingIdeal R M k = ⊤)] := by
  sorry

/-! ## Principal Fitting ideals and the projective-dimension statement -/

/- The source-facing names below retain the interfaces consumed by later
   chapters, while their implementations use Mathlib's canonical torsion
   submodules. -/
/-- The submodule annihilated by multiplication by a scalar. -/
abbrev scalarTorsionSubmodule
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) : Submodule R M :=
  Submodule.torsionBy R M f

/-- The submodule of elements killed by some power of a scalar. -/
abbrev scalarPowerTorsionSubmodule
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (f : R) : Submodule R M :=
  Submodule.torsion' R M (Submonoid.powers f)

theorem quotient_by_principal_fitting_torsion_generated
    {R M : Type*} [CommRing R] [IsLocalRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (k : ℕ) (f : R) (hfit : fittingIdeal R M k = Ideal.span {f}) :
    ∃ g : (Fin k → R) →ₗ[R]
          (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f),
      Function.Surjective g := by
  sorry

theorem fittingIdeal_principal_nonzerodivisor
    {R M : Type*} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.FinitePresentation R M]
    (k : ℕ) (f : R) (hf : f ∈ nonZeroDivisors R)
    (hfit : fittingIdeal R M k = Ideal.span {f})
    (hprev : fittingIdealInt R M ((k : ℤ) - 1) = ⊥) :
    CategoryTheory.HasProjectiveDimensionLE (ModuleCat.of R M) 1 ∧
      scalarTorsionSubmodule (R := R) (M := M) f =
          scalarPowerTorsionSubmodule (R := R) (M := M) f ∧
        CategoryTheory.HasProjectiveDimensionLE
            (ModuleCat.of R
              (scalarTorsionSubmodule (R := R) (M := M) f : Type _)) 1 ∧
          FiniteLocallyFreeOfRank R
            (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f) k ∧
            Nonempty
              (M ≃ₗ[R]
                (M ⧸ scalarTorsionSubmodule (R := R) (M := M) f) ×
                  (scalarTorsionSubmodule (R := R) (M := M) f : Type _)) := by
  sorry

end

end Formalization.Books.MoreAlgebra.Unit08
