import Formalization.Books.Algebra.Unit52.Length
import Formalization.Books.Algebra.Unit53.ArtinianRings
import Mathlib.Algebra.Colimit.Module
import Mathlib.Algebra.Module.PID
import Mathlib.Algebra.Module.Projective
import Mathlib.Algebra.Polynomial.Eval.Algebra
import Mathlib.GroupTheory.Congruence.Hom
import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.LinearAlgebra.FreeModule.Finite.Basic
import Mathlib.LinearAlgebra.DirectSum.Finite
import Mathlib.LinearAlgebra.Dimension.Torsion.Finite
import Mathlib.RingTheory.EuclideanDomain
import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.Finiteness.Cardinality
import Mathlib.RingTheory.Finiteness.Prod
import Mathlib.RingTheory.LocalRing.Module

/-!
# Commutative Algebra, Chapter 55: K-groups

The two Grothendieck groups in this chapter are presented using finite
quotients of finite free modules.  This is the set-sized version of the
book's presentation by all finite modules.
-/

namespace Formalization.Books.Algebra.Unit55

open scoped BigOperators

universe u v

noncomputable section

/-- A finite presentation of a finite module by a quotient of a finite free
module. -/
structure FiniteModulePresentation (R : Type u) [CommRing R] where
  rank : ℕ
  relations : Submodule R (Fin rank → R)

namespace FiniteModulePresentation

variable {R : Type u} [CommRing R]

/-- The module represented by a finite presentation. -/
abbrev module (P : FiniteModulePresentation R) : Type u :=
  (Fin P.rank → R) ⧸ P.relations

instance finite (P : FiniteModulePresentation R) :
    Module.Finite R P.module := by
  infer_instance

end FiniteModulePresentation

/-- Every finite module has one of the finite presentations used below. -/
theorem exists_finite_module_presentation
    {R : Type u} [CommRing R] {M : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M] :
    ∃ P : FiniteModulePresentation R, Nonempty (P.module ≃ₗ[R] M) := by
  rcases Module.Finite.exists_fin_quot_equiv R M with ⟨n, K, ⟨e⟩⟩
  exact ⟨⟨n, K⟩, ⟨e⟩⟩

/-- A short exact sequence of finite modules, with all three terms given by
finite presentations. -/
structure FiniteModuleShortExact (R : Type u) [CommRing R] where
  left : FiniteModulePresentation R
  middle : FiniteModulePresentation R
  right : FiniteModulePresentation R
  leftToMiddle : left.module →ₗ[R] middle.module
  middleToRight : middle.module →ₗ[R] right.module
  left_injective : Function.Injective leftToMiddle
  middle_surjective : Function.Surjective middleToRight
  exact : Function.Exact leftToMiddle middleToRight

abbrev KPrimeZeroFree (R : Type u) [CommRing R] :=
  FreeAbelianGroup (FiniteModulePresentation R)

/-- The generator corresponding to a finite module presentation. -/
def kPrimeZeroGenerator
    {R : Type u} [CommRing R] (P : FiniteModulePresentation R) :
    KPrimeZeroFree R :=
  FreeAbelianGroup.of P

/-- The elementary exact-sequence relation in the free group on finite
presentations. -/
def kPrimeZeroRelation
    {R : Type u} [CommRing R] (S : FiniteModuleShortExact R)
    (x y : KPrimeZeroFree R) : Prop :=
  x = kPrimeZeroGenerator S.middle ∧
    y = kPrimeZeroGenerator S.left + kPrimeZeroGenerator S.right

/-- The congruence generated by all exact-sequence relations. -/
def kPrimeZeroCon (R : Type u) [CommRing R] : AddCon (KPrimeZeroFree R) :=
  addConGen (fun x y => ∃ S : FiniteModuleShortExact R,
    kPrimeZeroRelation S x y)

/-- The K′₀ group.  The quotient is a set-sized model for the book's group
generated by classes of all finite modules. -/
abbrev KPrimeZero (R : Type u) [CommRing R] :=
  (kPrimeZeroCon R).Quotient

/-- The class of a chosen finite-module presentation. -/
def kPrimeZeroClassOfPresentation
    {R : Type u} [CommRing R] (P : FiniteModulePresentation R) :
    KPrimeZero R :=
  (kPrimeZeroCon R).mk' (kPrimeZeroGenerator P)

/-- The class of an arbitrary finite module, using a chosen finite
presentation. -/
noncomputable def kPrimeZeroClass
    {R : Type u} [CommRing R] {M : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M] :
    KPrimeZero R :=
  let P := Classical.choose
    (exists_finite_module_presentation (R := R) (M := M))
  kPrimeZeroClassOfPresentation P

private theorem kPrimeZeroClassOfPresentation_eq_of_linearEquiv
    {R : Type u} [CommRing R]
    (P Q : FiniteModulePresentation R) (ePQ : P.module ≃ₗ[R] Q.module) :
    kPrimeZeroClassOfPresentation P =
      kPrimeZeroClassOfPresentation Q := by
  let Z : FiniteModulePresentation R := ⟨0, ⊥⟩
  let S : FiniteModuleShortExact R :=
    { left := P
      middle := Q
      right := Z
      leftToMiddle := ePQ.toLinearMap
      middleToRight := 0
      left_injective := ePQ.injective
      middle_surjective := by
        intro z
        exact ⟨0, Subsingleton.elim _ _⟩
      exact :=
        (LinearMap.exact_zero_iff_surjective Z.module ePQ.toLinearMap).2
          ePQ.surjective }
  have hrel : kPrimeZeroCon R
      (kPrimeZeroGenerator Q)
      (kPrimeZeroGenerator P + kPrimeZeroGenerator Z) := by
    change AddConGen.Rel
      (fun x y : KPrimeZeroFree R =>
        ∃ S : FiniteModuleShortExact R, kPrimeZeroRelation S x y)
      (kPrimeZeroGenerator Q)
      (kPrimeZeroGenerator P + kPrimeZeroGenerator Z)
    exact AddConGen.Rel.of _ _ ⟨S, rfl, rfl⟩
  have hq :
      kPrimeZeroClassOfPresentation Q =
        kPrimeZeroClassOfPresentation P +
          kPrimeZeroClassOfPresentation Z := by
    change (kPrimeZeroGenerator Q : KPrimeZero R) =
      (kPrimeZeroGenerator P + kPrimeZeroGenerator Z : KPrimeZero R)
    exact (kPrimeZeroCon R).eq.mpr hrel
  let T : FiniteModuleShortExact R :=
    { left := Z
      middle := Z
      right := Z
      leftToMiddle := 0
      middleToRight := 0
      left_injective := by
        intro z₁ z₂ _
        exact Subsingleton.elim _ _
      middle_surjective := by
        intro z
        exact ⟨0, Subsingleton.elim _ _⟩
      exact :=
        (LinearMap.exact_zero_iff_surjective Z.module
          (0 : Z.module →ₗ[R] Z.module)).2 (by
            intro z
            exact ⟨0, Subsingleton.elim _ _⟩) }
  have hrelZ : kPrimeZeroCon R
      (kPrimeZeroGenerator Z)
      (kPrimeZeroGenerator Z + kPrimeZeroGenerator Z) := by
    change AddConGen.Rel
      (fun x y : KPrimeZeroFree R =>
        ∃ S : FiniteModuleShortExact R, kPrimeZeroRelation S x y)
      (kPrimeZeroGenerator Z)
      (kPrimeZeroGenerator Z + kPrimeZeroGenerator Z)
    exact AddConGen.Rel.of _ _ ⟨T, rfl, rfl⟩
  have hqZ :
      kPrimeZeroClassOfPresentation Z =
        kPrimeZeroClassOfPresentation Z +
          kPrimeZeroClassOfPresentation Z := by
    change (kPrimeZeroGenerator Z : KPrimeZero R) =
      (kPrimeZeroGenerator Z + kPrimeZeroGenerator Z : KPrimeZero R)
    exact (kPrimeZeroCon R).eq.mpr hrelZ
  have hzero : kPrimeZeroClassOfPresentation Z = 0 := by
    have hqZ' :
        kPrimeZeroClassOfPresentation Z +
            kPrimeZeroClassOfPresentation Z =
          kPrimeZeroClassOfPresentation Z := hqZ.symm
    calc
      kPrimeZeroClassOfPresentation Z =
          kPrimeZeroClassOfPresentation Z + 0 := (add_zero _).symm
      _ = kPrimeZeroClassOfPresentation Z +
            (kPrimeZeroClassOfPresentation Z -
              kPrimeZeroClassOfPresentation Z) := by
            rw [sub_self, add_zero]
      _ = (kPrimeZeroClassOfPresentation Z +
            kPrimeZeroClassOfPresentation Z) -
            kPrimeZeroClassOfPresentation Z := by abel
      _ = kPrimeZeroClassOfPresentation Z -
            kPrimeZeroClassOfPresentation Z := by rw [hqZ']
      _ = 0 := sub_self _
  rw [hq, hzero, add_zero]

/-- The chosen presentation does not affect the class, up to the
linear-equivalence invariance supplied by the exact-sequence relations. -/
theorem kPrimeZeroClass_eq_of_linearEquiv
    {R : Type u} [CommRing R] {M N : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    (e : M ≃ₗ[R] N) :
    kPrimeZeroClass (R := R) (M := M) =
      kPrimeZeroClass (R := R) (M := N) := by
  let P := Classical.choose
    (exists_finite_module_presentation (R := R) (M := M))
  let Q := Classical.choose
    (exists_finite_module_presentation (R := R) (M := N))
  let eP := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := R) (M := M)))
  let eQ := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := R) (M := N)))
  let ePQ : P.module ≃ₗ[R] Q.module :=
    eP.trans (e.trans eQ.symm)
  exact kPrimeZeroClassOfPresentation_eq_of_linearEquiv P Q ePQ

/-- Every class in K′₀ is an integer linear combination of module classes.
The definition of the relation congruence records that the only imposed
relations are the exact-sequence relations. -/
theorem kPrimeZero_generated
    {R : Type u} [CommRing R] (x : KPrimeZero R) :
    ∃ n : ℕ, ∃ P : Fin n → FiniteModulePresentation R,
      ∃ z : Fin n → ℤ,
        x = ∑ i, z i • kPrimeZeroClassOfPresentation (P i) := by
  refine AddCon.induction_on x ?_
  intro y
  induction y using FreeAbelianGroup.induction_on with
  | zero =>
      refine ⟨0, (fun i => Fin.elim0 i), (fun i => Fin.elim0 i), ?_⟩
      simp [kPrimeZeroClassOfPresentation]
  | of P =>
      refine ⟨1, (fun _ => P), (fun _ => 1), ?_⟩
      simp only [Fin.sum_univ_one, one_smul]
      exact (kPrimeZeroCon R).eq.mpr
        ((kPrimeZeroCon R).refl (FreeAbelianGroup.of P))
  | neg P ih =>
      refine ⟨1, (fun _ => P), (fun _ => -1), ?_⟩
      change (-(FreeAbelianGroup.of P) : KPrimeZero R) = _
      simp [kPrimeZeroClassOfPresentation, kPrimeZeroGenerator]
  | add y z ihy ihz =>
      rcases ihy with ⟨n, P, a, hP⟩
      rcases ihz with ⟨m, Q, b, hQ⟩
      refine ⟨n + m, Fin.addCases P Q, Fin.addCases a b, ?_⟩
      change (y : KPrimeZero R) + (z : KPrimeZero R) = _
      rw [hP, hQ]
      simp [Fin.sum_univ_add]

/-- The exact-sequence relation for the classes of arbitrary finite modules. -/
theorem kPrimeZeroClass_exact
    {R : Type u} [CommRing R] {M' M M'' : Type v}
    [AddCommGroup M'] [Module R M'] [Module.Finite R M']
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup M''] [Module R M''] [Module.Finite R M'']
    (f : M' →ₗ[R] M) (g : M →ₗ[R] M'')
    (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) :
    kPrimeZeroClass (R := R) (M := M) =
      kPrimeZeroClass (R := R) (M := M') +
        kPrimeZeroClass (R := R) (M := M'') := by
  let P' := Classical.choose
    (exists_finite_module_presentation (R := R) (M := M'))
  let P := Classical.choose
    (exists_finite_module_presentation (R := R) (M := M))
  let P'' := Classical.choose
    (exists_finite_module_presentation (R := R) (M := M''))
  let eP' := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := R) (M := M')))
  let eP := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := R) (M := M)))
  let eP'' := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := R) (M := M'')))
  let f' : P'.module →ₗ[R] P.module :=
    eP.symm.toLinearMap.comp (f.comp eP'.toLinearMap)
  let g' : P.module →ₗ[R] P''.module :=
    eP''.symm.toLinearMap.comp (g.comp eP.toLinearMap)
  have hf' : Function.Injective f' := by
    intro x y hxy
    apply eP'.injective
    apply hf
    simpa [f'] using congrArg (fun t => eP t) hxy
  have hg' : Function.Surjective g' := by
    intro y
    obtain ⟨x, hx⟩ := hg (eP'' y)
    refine ⟨eP.symm x, ?_⟩
    simpa [g'] using congrArg (fun t => eP''.symm t) hx
  have hcomm₁₂ :
      f'.comp eP'.symm.toLinearMap =
        eP.symm.toLinearMap.comp f := by
    ext x
    simp [f']
  have hcomm₂₃ :
      g'.comp eP.symm.toLinearMap =
        eP''.symm.toLinearMap.comp g := by
    ext x
    simp [g']
  have hfg' : Function.Exact f' g' :=
    (LinearMap.exact_iff_of_surjective_of_bijective_of_injective
      f g f' g' eP'.symm.toLinearMap eP.symm.toLinearMap
      eP''.symm.toLinearMap hcomm₁₂ hcomm₂₃ eP'.symm.surjective
      ⟨eP.symm.injective, eP.symm.surjective⟩ eP''.symm.injective).mp hfg
  let S : FiniteModuleShortExact R :=
    { left := P'
      middle := P
      right := P''
      leftToMiddle := f'
      middleToRight := g'
      left_injective := hf'
      middle_surjective := hg'
      exact := hfg' }
  have hrel : kPrimeZeroCon R
      (kPrimeZeroGenerator P)
      (kPrimeZeroGenerator P' + kPrimeZeroGenerator P'') := by
    change AddConGen.Rel
      (fun x y : KPrimeZeroFree R =>
        ∃ S : FiniteModuleShortExact R, kPrimeZeroRelation S x y)
      (kPrimeZeroGenerator P)
      (kPrimeZeroGenerator P' + kPrimeZeroGenerator P'')
    exact AddConGen.Rel.of _ _ ⟨S, rfl, rfl⟩
  change kPrimeZeroClassOfPresentation P =
    kPrimeZeroClassOfPresentation P' +
      kPrimeZeroClassOfPresentation P''
  exact (kPrimeZeroCon R).eq.mpr hrel

/-- A finite projective module presentation. -/
structure FiniteProjectivePresentation (R : Type u) [CommRing R] where
  presentation : FiniteModulePresentation R
  projective : Module.Projective R presentation.module

namespace FiniteProjectivePresentation

variable {R : Type u} [CommRing R]

instance finite (P : FiniteProjectivePresentation R) :
    Module.Finite R P.presentation.module := by
  infer_instance

instance isProjective (P : FiniteProjectivePresentation R) :
    Module.Projective R P.presentation.module :=
  P.projective

end FiniteProjectivePresentation

/-- Every finite projective module has a finite projective presentation. -/
theorem exists_finite_projective_presentation
    {R : Type u} [CommRing R] {M : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M] :
    ∃ P : FiniteProjectivePresentation R,
      Nonempty (P.presentation.module ≃ₗ[R] M) := by
  rcases exists_finite_module_presentation (R := R) (M := M) with ⟨P, ⟨e⟩⟩
  let hP : Module.Projective R P.module :=
    Module.Projective.of_equiv' e.symm
  exact ⟨⟨P, hP⟩, ⟨e⟩⟩

/-- A short exact sequence of finite projective modules. -/
structure FiniteProjectiveShortExact (R : Type u) [CommRing R] where
  left : FiniteProjectivePresentation R
  middle : FiniteProjectivePresentation R
  right : FiniteProjectivePresentation R
  leftToMiddle :
    left.presentation.module →ₗ[R] middle.presentation.module
  middleToRight :
    middle.presentation.module →ₗ[R] right.presentation.module
  left_injective : Function.Injective leftToMiddle
  middle_surjective : Function.Surjective middleToRight
  exact : Function.Exact leftToMiddle middleToRight

/-- Forget the projective structure in a projective exact sequence. -/
def FiniteProjectiveShortExact.toFiniteModuleShortExact
    {R : Type u} [CommRing R] (S : FiniteProjectiveShortExact R) :
    FiniteModuleShortExact R :=
  { left := S.left.presentation
    middle := S.middle.presentation
    right := S.right.presentation
    leftToMiddle := S.leftToMiddle
    middleToRight := S.middleToRight
    left_injective := S.left_injective
    middle_surjective := S.middle_surjective
    exact := S.exact }

abbrev KZeroFree (R : Type u) [CommRing R] :=
  FreeAbelianGroup (FiniteProjectivePresentation R)

/-- The generator corresponding to a finite projective presentation. -/
def kZeroGenerator
    {R : Type u} [CommRing R] (P : FiniteProjectivePresentation R) :
    KZeroFree R :=
  FreeAbelianGroup.of P

/-- The elementary exact-sequence relation in the free group on finite
projective presentations. -/
def kZeroRelation
    {R : Type u} [CommRing R] (S : FiniteProjectiveShortExact R)
    (x y : KZeroFree R) : Prop :=
  x = kZeroGenerator S.middle ∧
    y = kZeroGenerator S.left + kZeroGenerator S.right

/-- The congruence generated by all exact-sequence relations. -/
def kZeroCon (R : Type u) [CommRing R] : AddCon (KZeroFree R) :=
  addConGen (fun x y => ∃ S : FiniteProjectiveShortExact R,
    kZeroRelation S x y)

/-- The K₀ group. -/
abbrev KZero (R : Type u) [CommRing R] :=
  (kZeroCon R).Quotient

/-- The class of a finite projective presentation. -/
def kZeroClassOfPresentation
    {R : Type u} [CommRing R] (P : FiniteProjectivePresentation R) :
    KZero R :=
  (kZeroCon R).mk' (kZeroGenerator P)

/-- The class of an arbitrary finite projective module. -/
noncomputable def kZeroClass
    {R : Type u} [CommRing R] {M : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M] :
    KZero R :=
  let P := Classical.choose
    (exists_finite_projective_presentation (R := R) (M := M))
  kZeroClassOfPresentation P

/-- Every class in K₀ is an integer linear combination of projective-module
classes, and the defining relations are exactly the projective exact-sequence
relations. -/
theorem kZero_generated
    {R : Type u} [CommRing R] (x : KZero R) :
    ∃ n : ℕ, ∃ P : Fin n → FiniteProjectivePresentation R,
      ∃ z : Fin n → ℤ,
        x = ∑ i, z i • kZeroClassOfPresentation (P i) := by
  refine AddCon.induction_on x ?_
  intro y
  induction y using FreeAbelianGroup.induction_on with
  | zero =>
      refine ⟨0, (fun i => Fin.elim0 i), (fun i => Fin.elim0 i), ?_⟩
      simp [kZeroClassOfPresentation]
  | of P =>
      refine ⟨1, (fun _ => P), (fun _ => 1), ?_⟩
      simp only [Fin.sum_univ_one, one_smul]
      exact (kZeroCon R).eq.mpr
        ((kZeroCon R).refl (FreeAbelianGroup.of P))
  | neg P ih =>
      refine ⟨1, (fun _ => P), (fun _ => -1), ?_⟩
      change (-(FreeAbelianGroup.of P) : KZero R) = _
      simp [kZeroClassOfPresentation, kZeroGenerator]
  | add y z ihy ihz =>
      rcases ihy with ⟨n, P, a, hP⟩
      rcases ihz with ⟨m, Q, b, hQ⟩
      refine ⟨n + m, Fin.addCases P Q, Fin.addCases a b, ?_⟩
      change (y : KZero R) + (z : KZero R) = _
      rw [hP, hQ]
      simp [Fin.sum_univ_add]

/-- The exact-sequence relation in K₀. -/
theorem kZeroClass_exact
    {R : Type u} [CommRing R] {M' M M'' : Type v}
    [AddCommGroup M'] [Module R M'] [Module.Finite R M']
    [Module.Projective R M']
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M]
    [AddCommGroup M''] [Module R M''] [Module.Finite R M'']
    [Module.Projective R M'']
    (f : M' →ₗ[R] M) (g : M →ₗ[R] M'')
    (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) :
    kZeroClass (R := R) (M := M) =
      kZeroClass (R := R) (M := M') +
        kZeroClass (R := R) (M := M'') := by
  let P' := Classical.choose
    (exists_finite_projective_presentation (R := R) (M := M'))
  let P := Classical.choose
    (exists_finite_projective_presentation (R := R) (M := M))
  let P'' := Classical.choose
    (exists_finite_projective_presentation (R := R) (M := M''))
  let eP' := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation (R := R) (M := M')))
  let eP := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation (R := R) (M := M)))
  let eP'' := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation (R := R) (M := M'')))
  let f' : P'.presentation.module →ₗ[R] P.presentation.module :=
    eP.symm.toLinearMap.comp (f.comp eP'.toLinearMap)
  let g' : P.presentation.module →ₗ[R] P''.presentation.module :=
    eP''.symm.toLinearMap.comp (g.comp eP.toLinearMap)
  have hf' : Function.Injective f' := by
    intro x y hxy
    apply eP'.injective
    apply hf
    simpa [f'] using congrArg (fun t => eP t) hxy
  have hg' : Function.Surjective g' := by
    intro y
    obtain ⟨x, hx⟩ := hg (eP'' y)
    refine ⟨eP.symm x, ?_⟩
    simpa [g'] using congrArg (fun t => eP''.symm t) hx
  have hcomm₁₂ :
      f'.comp eP'.symm.toLinearMap =
        eP.symm.toLinearMap.comp f := by
    ext x
    simp [f']
  have hcomm₂₃ :
      g'.comp eP.symm.toLinearMap =
        eP''.symm.toLinearMap.comp g := by
    ext x
    simp [g']
  have hfg' : Function.Exact f' g' :=
    (LinearMap.exact_iff_of_surjective_of_bijective_of_injective
      f g f' g' eP'.symm.toLinearMap eP.symm.toLinearMap
      eP''.symm.toLinearMap hcomm₁₂ hcomm₂₃ eP'.symm.surjective
      ⟨eP.symm.injective, eP.symm.surjective⟩ eP''.symm.injective).mp hfg
  let S : FiniteProjectiveShortExact R :=
    { left := P'
      middle := P
      right := P''
      leftToMiddle := f'
      middleToRight := g'
      left_injective := hf'
      middle_surjective := hg'
      exact := hfg' }
  have hrel : kZeroCon R
      (kZeroGenerator P)
      (kZeroGenerator P' + kZeroGenerator P'') := by
    change AddConGen.Rel
      (fun x y : KZeroFree R =>
        ∃ S : FiniteProjectiveShortExact R, kZeroRelation S x y)
      (kZeroGenerator P)
      (kZeroGenerator P' + kZeroGenerator P'')
    exact AddConGen.Rel.of _ _ ⟨S, rfl, rfl⟩
  change kZeroClassOfPresentation P =
    kZeroClassOfPresentation P' +
      kZeroClassOfPresentation P''
  exact (kZeroCon R).eq.mpr hrel

private theorem kPrimeZeroClass_eq_of_presentation
    {R : Type u} [CommRing R] (P : FiniteModulePresentation R) :
    kPrimeZeroClass (R := R) (M := P.module) =
      kPrimeZeroClassOfPresentation P := by
  let Q := Classical.choose
    (exists_finite_module_presentation (R := R) (M := P.module))
  let eQ := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := R) (M := P.module)))
  change kPrimeZeroClassOfPresentation Q =
    kPrimeZeroClassOfPresentation P
  exact kPrimeZeroClassOfPresentation_eq_of_linearEquiv Q P
    (eQ.trans (LinearEquiv.refl R P.module))

/-- The homomorphism from the free K₀ generators to K′₀. -/
def kZeroFreeToKPrime
    {R : Type u} [CommRing R] :
    KZeroFree R →+ KPrimeZero R :=
  FreeAbelianGroup.lift (fun P =>
    kPrimeZeroClassOfPresentation P.presentation)

/-- The K₀ generator map respects the exact-sequence relations. -/
theorem kZeroFreeToKPrime_respects_relations
    {R : Type u} [CommRing R] :
    kZeroCon R ≤ AddCon.ker (kZeroFreeToKPrime (R := R)) := by
  refine AddCon.addConGen_le.2 ?_
  rintro x y ⟨S, rfl, rfl⟩
  simp only [kZeroFreeToKPrime]
  calc
    kPrimeZeroClassOfPresentation S.middle.presentation =
        kPrimeZeroClass (R := R) (M := S.middle.presentation.module) :=
      (kPrimeZeroClass_eq_of_presentation S.middle.presentation).symm
    _ = kPrimeZeroClass (R := R) (M := S.left.presentation.module) +
        kPrimeZeroClass (R := R) (M := S.right.presentation.module) :=
      kPrimeZeroClass_exact S.leftToMiddle S.middleToRight
        S.left_injective S.middle_surjective S.exact
    _ = kPrimeZeroClassOfPresentation S.left.presentation +
        kPrimeZeroClassOfPresentation S.right.presentation := by
      rw [kPrimeZeroClass_eq_of_presentation S.left.presentation,
        kPrimeZeroClass_eq_of_presentation S.right.presentation]

/-- The canonical homomorphism K₀(R) → K′₀(R). -/
noncomputable def kZeroToKPrime
    {R : Type u} [CommRing R] :
    KZero R →+ KPrimeZero R :=
  (kZeroCon R).lift (kZeroFreeToKPrime (R := R))
    (kZeroFreeToKPrime_respects_relations (R := R))

@[simp]
theorem kZeroToKPrime_apply_class
    {R : Type u} [CommRing R] (P : FiniteProjectivePresentation R) :
    kZeroToKPrime (R := R) (kZeroClassOfPresentation P) =
      kPrimeZeroClassOfPresentation P.presentation := by
  change kZeroFreeToKPrime (R := R) (kZeroGenerator P) =
    kPrimeZeroClassOfPresentation P.presentation
  simp [kZeroFreeToKPrime, kZeroGenerator]

/-- The length of a finite presented module over an Artinian ring. -/
def finitePresentationLength
    {R : Type u} [CommRing R] [IsArtinianRing R]
    (P : FiniteModulePresentation R) : ℕ :=
  (Module.length R P.module).toNat

/-- Length on the free abelian group of finite-module generators. -/
def kPrimeZeroLengthOnFree
    {R : Type u} [CommRing R] [IsArtinianRing R] :
    KPrimeZeroFree R →+ ℤ :=
  FreeAbelianGroup.lift (fun P => (finitePresentationLength P : ℤ))

/-- Exact-sequence relations preserve length. -/
theorem kPrimeZeroLengthOnFree_respects_relations
    {R : Type u} [CommRing R] [IsArtinianRing R] :
    kPrimeZeroCon R ≤
      AddCon.ker (kPrimeZeroLengthOnFree (R := R)) := by
  refine AddCon.addConGen_le.2 ?_
  rintro x y ⟨S, rfl, rfl⟩
  simp only [kPrimeZeroLengthOnFree]
  change (finitePresentationLength S.middle : ℤ) =
    (finitePresentationLength S.left : ℤ) +
      (finitePresentationLength S.right : ℤ)
  have hleftFin : IsFiniteLength R S.left.module :=
    ((IsArtinianRing.tfae R S.left.module).out 0 3).mp
      (inferInstance : Module.Finite R S.left.module)
  have hrightFin : IsFiniteLength R S.right.module :=
    ((IsArtinianRing.tfae R S.right.module).out 0 3).mp
      (inferInstance : Module.Finite R S.right.module)
  have hleft : Module.length R S.left.module ≠ ⊤ :=
    Module.length_ne_top_iff.mpr hleftFin
  have hright : Module.length R S.right.module ≠ ⊤ :=
    Module.length_ne_top_iff.mpr hrightFin
  have hlen := Module.length_eq_add_of_exact S.leftToMiddle S.middleToRight
    S.left_injective S.middle_surjective S.exact
  have hnat := congrArg ENat.toNat hlen
  rw [ENat.toNat_add hleft hright] at hnat
  exact_mod_cast hnat

/-- The length homomorphism K′₀(R) → ℤ. -/
noncomputable def kPrimeZeroLength
    {R : Type u} [CommRing R] [IsArtinianRing R] :
    KPrimeZero R →+ ℤ :=
  (kPrimeZeroCon R).lift (kPrimeZeroLengthOnFree (R := R))
    (kPrimeZeroLengthOnFree_respects_relations (R := R))

@[simp]
theorem kPrimeZeroLength_apply_class
    {R : Type u} [CommRing R] [IsArtinianRing R]
    (P : FiniteModulePresentation R) :
    kPrimeZeroLength (R := R) (kPrimeZeroClassOfPresentation P) =
      finitePresentationLength P := by
  rfl

/-- Over a local ring, a finite projective module has a finite free basis. -/
theorem finite_projective_is_free_over_local
    {R M : Type u} [CommRing R] [IsLocalRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M] :
    Module.Free R M := by
  exact Module.free_of_flat_of_isLocalRing

/-- A finite free presentation of a finite projective module over a local
ring. -/
theorem finite_projective_is_finite_free_over_local
    {R M : Type u} [CommRing R] [IsLocalRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M] :
    ∃ n : ℕ, Nonempty (M ≃ₗ[R] (Fin n → R)) := by
  have hfree : Module.Free R M := finite_projective_is_free_over_local
  exact ⟨Fintype.card (@Module.Free.ChooseBasisIndex R M _ _ _ hfree),
    ⟨((@Module.Free.chooseBasis R M _ _ _ hfree).reindex (Fintype.equivFin _)).equivFun⟩⟩

/-- The finite free rank of a projective presentation over a local ring. -/
noncomputable def finiteProjectiveRank
    {R : Type u} [CommRing R] [IsLocalRing R]
    (P : FiniteProjectivePresentation R) : ℕ :=
  Classical.choose
    (finite_projective_is_finite_free_over_local
      (R := R) (M := P.presentation.module))

/-- Rank on the free abelian group of projective generators. -/
def kZeroRankOnFree
    {R : Type u} [CommRing R] [IsLocalRing R] :
    KZeroFree R →+ ℤ :=
  FreeAbelianGroup.lift (fun P => (finiteProjectiveRank P : ℤ))

/-- Exact-sequence relations preserve rank over a local ring. -/
theorem kZeroRankOnFree_respects_relations
    {R : Type u} [CommRing R] [IsLocalRing R] :
    kZeroCon R ≤ AddCon.ker (kZeroRankOnFree (R := R)) := by
  refine AddCon.addConGen_le.2 ?_
  rintro x y ⟨S, rfl, rfl⟩
  simp only [kZeroRankOnFree]
  change (finiteProjectiveRank S.middle : ℤ) =
    (finiteProjectiveRank S.left : ℤ) + (finiteProjectiveRank S.right : ℤ)
  have hrank (P : FiniteProjectivePresentation R) :
      finiteProjectiveRank P = Module.finrank R P.presentation.module := by
    let e := Classical.choice
      (Classical.choose_spec
        (finite_projective_is_finite_free_over_local
          (R := R) (M := P.presentation.module)))
    have he := e.finrank_eq
    simpa [finiteProjectiveRank, Module.finrank_pi] using he.symm
  let hleft : Module.Free R S.left.presentation.module :=
    finite_projective_is_free_over_local
  let hright : Module.Free R S.right.presentation.module :=
    finite_projective_is_free_over_local
  have hsplit :
      ∃ l : S.right.presentation.module →ₗ[R] S.middle.presentation.module,
        S.middleToRight ∘ₗ l = LinearMap.id :=
    (Module.Projective.iff_split_of_projective
      S.middleToRight S.middle_surjective).mp S.right.projective
  obtain ⟨l, hl⟩ := hsplit
  let hs :
      { l : S.right.presentation.module →ₗ[R] S.middle.presentation.module //
        S.middleToRight ∘ₗ l = LinearMap.id } :=
    ⟨l, hl⟩
  let e := (S.exact.splitSurjectiveEquiv S.left_injective hs).1
  have hprod :
      Module.finrank R (S.left.presentation.module × S.right.presentation.module) =
        Module.finrank R S.left.presentation.module +
          Module.finrank R S.right.presentation.module :=
    @Module.finrank_prod R S.left.presentation.module S.right.presentation.module
      _ _ _ _ _ _ hleft hright inferInstance inferInstance
  have hdim :
      Module.finrank R S.middle.presentation.module =
        Module.finrank R S.left.presentation.module +
          Module.finrank R S.right.presentation.module :=
    e.finrank_eq.trans hprod
  have hnat :
      finiteProjectiveRank S.middle =
        finiteProjectiveRank S.left + finiteProjectiveRank S.right := by
    calc
      finiteProjectiveRank S.middle =
          Module.finrank R S.middle.presentation.module := hrank S.middle
      _ = Module.finrank R S.left.presentation.module +
          Module.finrank R S.right.presentation.module := hdim
      _ = finiteProjectiveRank S.left + finiteProjectiveRank S.right := by
        rw [hrank S.left, hrank S.right]
  exact_mod_cast hnat

/-- The rank homomorphism K₀(R) → ℤ over a local ring. -/
noncomputable def kZeroRank
    {R : Type u} [CommRing R] [IsLocalRing R] :
    KZero R →+ ℤ :=
  (kZeroCon R).lift (kZeroRankOnFree (R := R))
    (kZeroRankOnFree_respects_relations (R := R))

@[simp]
theorem kZeroRank_apply_class
    {R : Type u} [CommRing R] [IsLocalRing R]
    (P : FiniteProjectivePresentation R) :
    kZeroRank (R := R) (kZeroClassOfPresentation P) =
      finiteProjectiveRank P := by
  rfl

/-- For a field, the K′₀ length is the vector-space dimension. -/
theorem kPrimeZeroLength_field_eq_finrank
    {k : Type u} [Field k] {M : Type v}
    [AddCommGroup M] [Module k M] [Module.Finite k M] :
    kPrimeZeroLength (R := k) (kPrimeZeroClass (R := k) (M := M)) =
      Module.finrank k M := by
  let P := Classical.choose
    (exists_finite_module_presentation (R := k) (M := M))
  let eP := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := k) (M := M)))
  change kPrimeZeroLength (R := k) (kPrimeZeroClassOfPresentation P) =
    Module.finrank k M
  rw [kPrimeZeroLength_apply_class, finitePresentationLength]
  have hlen : Module.length k P.module = Module.finrank k P.module :=
    Module.length_eq_finrank k P.module
  rw [hlen]
  simpa using eP.finrank_eq

/-! ## The PID calculation -/

/- A finite free module has a finite basis, represented here by a linear
equivalence with a finite free module. -/
theorem exists_finite_free_equiv
    {R : Type u} [CommRing R] {M : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M] [Module.Free R M] :
    ∃ n : ℕ, Nonempty (M ≃ₗ[R] (Fin n → R)) := by
  exact ⟨Fintype.card (@Module.Free.ChooseBasisIndex R M _ _ _ inferInstance),
    ⟨((@Module.Free.chooseBasis R M _ _ _ inferInstance).reindex
      (Fintype.equivFin _)).equivFun⟩⟩

/- The rank is the cardinality of any finite free basis. -/
noncomputable def finiteFreeRank
    {R : Type u} [CommRing R] {M : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M] [Module.Free R M] :
    ℕ :=
  Classical.choose (exists_finite_free_equiv (R := R) (M := M))

theorem finiteFreeRank_eq_of_linearEquiv
    {R : Type u} [CommRing R] [Nontrivial R] {M : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M] [Module.Free R M]
    {n : ℕ} (e : M ≃ₗ[R] (Fin n → R)) :
    finiteFreeRank (R := R) (M := M) = n := by
  let q := Classical.choose (exists_finite_free_equiv (R := R) (M := M))
  have hq : Module.finrank R M = Module.finrank R (Fin q → R) :=
    (Classical.choice (Classical.choose_spec
      (exists_finite_free_equiv (R := R) (M := M)))).finrank_eq
  have hn : Module.finrank R M = Module.finrank R (Fin n → R) := e.finrank_eq
  have hfin : Module.finrank R (Fin q → R) = Module.finrank R (Fin n → R) :=
    hq.symm.trans hn
  change q = n
  simpa [Module.finrank_pi] using hfin

/- A finite projective module over a PID is finite free. -/
theorem finite_projective_is_free_pid
    {R M : Type u} [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M] :
    Module.Free R M := by
  obtain ⟨F, _, _, _, i, s, his⟩ :=
    Module.Projective.iff_split.mp (inferInstance : Module.Projective R M)
  let _ : Module.IsTorsionFree R M :=
    (LinearMap.injective_of_comp_eq_id i s his).moduleIsTorsionFree i
      (fun r x => i.map_smul r x)
  exact Module.free_iff_isTorsionFree.mpr inferInstance

/- A short exact sequence of finite free modules splits, so its middle term
is the direct sum of its outer terms.  A binary product is the additive
direct-sum model used for this source-facing statement. -/
theorem finite_free_short_exact_splits_pid
    {R M' M M'' : Type u} [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R]
    [AddCommGroup M'] [Module R M'] [Module.Finite R M'] [Module.Free R M']
    [AddCommGroup M] [Module R M] [Module.Finite R M] [Module.Free R M]
    [AddCommGroup M''] [Module R M''] [Module.Finite R M''] [Module.Free R M'']
    (f : M' →ₗ[R] M) (g : M →ₗ[R] M'')
    (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) :
    Nonempty (M ≃ₗ[R] M' × M'') := by
  obtain ⟨l, hl⟩ :=
    (Module.Projective.iff_split_of_projective g hg).mp
      (inferInstance : Module.Projective R M'')
  let hs : { l : M'' →ₗ[R] M // g ∘ₗ l = LinearMap.id } := ⟨l, hl⟩
  exact ⟨(hfg.splitSurjectiveEquiv hf hs).1⟩

theorem finite_free_rank_add_of_short_exact_pid
    {R M' M M'' : Type u} [CommRing R] [IsDomain R]
    [IsPrincipalIdealRing R]
    [AddCommGroup M'] [Module R M'] [Module.Finite R M'] [Module.Free R M']
    [AddCommGroup M] [Module R M] [Module.Finite R M] [Module.Free R M]
    [AddCommGroup M''] [Module R M''] [Module.Finite R M''] [Module.Free R M'']
    (f : M' →ₗ[R] M) (g : M →ₗ[R] M'')
    (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) :
    finiteFreeRank (R := R) (M := M) =
      finiteFreeRank (R := R) (M := M') +
        finiteFreeRank (R := R) (M := M'') := by
  have hrank (N : Type u) [AddCommGroup N] [Module R N]
      [Module.Finite R N] [Module.Free R N] :
      finiteFreeRank (R := R) (M := N) = Module.finrank R N := by
    let e := Classical.choice
      (Classical.choose_spec
        (exists_finite_free_equiv (R := R) (M := N)))
    have he := e.finrank_eq
    simpa [finiteFreeRank, Module.finrank_pi] using he.symm
  obtain ⟨e⟩ := finite_free_short_exact_splits_pid f g hf hg hfg
  have hdim : Module.finrank R M = Module.finrank R (M' × M'') :=
    e.finrank_eq
  have hprod :
      Module.finrank R (M' × M'') =
        Module.finrank R M' + Module.finrank R M'' :=
    Module.finrank_prod
  calc
    finiteFreeRank (R := R) (M := M) = Module.finrank R M := hrank M
    _ = Module.finrank R M' + Module.finrank R M'' := hdim.trans hprod
    _ = finiteFreeRank (R := R) (M := M') +
        finiteFreeRank (R := R) (M := M'') := by
      rw [hrank M', hrank M'']

/- The structure theorem for finitely generated modules over a PID.  The
finite direct sum is represented by DirectSum. -/
abbrev pidTorsionSummand (R : Type u) [CommRing R] (d : R) :=
  R ⧸ Ideal.span ({d} : Set R)

theorem finite_module_structure_pid
    {R M : Type u} [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M] :
    ∃ r k : ℕ, ∃ d : Fin k → R,
      Nonempty (M ≃ₗ[R]
        (Fin r → R) × DirectSum (Fin k) (fun i => pidTorsionSummand R (d i))) := by
  obtain ⟨r, ι, _, p, _hp, e, ⟨h⟩⟩ :=
    Module.equiv_free_prod_directSum (R := R) (M := M)
  let eι := Fintype.equivFin ι
  let d : Fin (Fintype.card ι) → R :=
    fun j => p (eι.symm j) ^ e (eι.symm j)
  refine ⟨r, Fintype.card ι, d, ?_⟩
  exact ⟨h.trans
    ((Finsupp.linearEquivFunOnFinite R R (Fin r)).prodCongr
      (DirectSum.lequivCongrLeft R eι))⟩

private theorem kZeroClassOfPresentation_eq_of_linearEquiv
    {R : Type u} [CommRing R]
    (P Q : FiniteProjectivePresentation R)
    (ePQ : P.presentation.module ≃ₗ[R] Q.presentation.module) :
    kZeroClassOfPresentation P =
      kZeroClassOfPresentation Q := by
  let Z : FiniteProjectivePresentation R :=
    { presentation := ⟨0, ⊥⟩
      projective := by infer_instance }
  let S : FiniteProjectiveShortExact R :=
    { left := P
      middle := Q
      right := Z
      leftToMiddle := ePQ.toLinearMap
      middleToRight := 0
      left_injective := ePQ.injective
      middle_surjective := by
        intro z
        exact ⟨0, Subsingleton.elim _ _⟩
      exact :=
        (LinearMap.exact_zero_iff_surjective Z.presentation.module
          ePQ.toLinearMap).2 ePQ.surjective }
  have hrel : kZeroCon R
      (kZeroGenerator Q)
      (kZeroGenerator P + kZeroGenerator Z) := by
    change AddConGen.Rel
      (fun x y : KZeroFree R =>
        ∃ S : FiniteProjectiveShortExact R, kZeroRelation S x y)
      (kZeroGenerator Q)
      (kZeroGenerator P + kZeroGenerator Z)
    exact AddConGen.Rel.of _ _ ⟨S, rfl, rfl⟩
  have hq :
      kZeroClassOfPresentation Q =
        kZeroClassOfPresentation P + kZeroClassOfPresentation Z := by
    change (kZeroGenerator Q : KZero R) =
      (kZeroGenerator P + kZeroGenerator Z : KZero R)
    exact (kZeroCon R).eq.mpr hrel
  let T : FiniteProjectiveShortExact R :=
    { left := Z
      middle := Z
      right := Z
      leftToMiddle := 0
      middleToRight := 0
      left_injective := by
        intro z₁ z₂ _
        exact Subsingleton.elim _ _
      middle_surjective := by
        intro z
        exact ⟨0, Subsingleton.elim _ _⟩
      exact :=
        (LinearMap.exact_zero_iff_surjective Z.presentation.module
          (0 : Z.presentation.module →ₗ[R] Z.presentation.module)).2 (by
            intro z
            exact ⟨0, Subsingleton.elim _ _⟩) }
  have hrelZ : kZeroCon R
      (kZeroGenerator Z)
      (kZeroGenerator Z + kZeroGenerator Z) := by
    change AddConGen.Rel
      (fun x y : KZeroFree R =>
        ∃ S : FiniteProjectiveShortExact R, kZeroRelation S x y)
      (kZeroGenerator Z)
      (kZeroGenerator Z + kZeroGenerator Z)
    exact AddConGen.Rel.of _ _ ⟨T, rfl, rfl⟩
  have hqZ :
      kZeroClassOfPresentation Z =
        kZeroClassOfPresentation Z + kZeroClassOfPresentation Z := by
    change (kZeroGenerator Z : KZero R) =
      (kZeroGenerator Z + kZeroGenerator Z : KZero R)
    exact (kZeroCon R).eq.mpr hrelZ
  have hzero : kZeroClassOfPresentation Z = 0 := by
    have hqZ' :
        kZeroClassOfPresentation Z + kZeroClassOfPresentation Z =
          kZeroClassOfPresentation Z := hqZ.symm
    calc
      kZeroClassOfPresentation Z =
          kZeroClassOfPresentation Z + 0 := (add_zero _).symm
      _ = kZeroClassOfPresentation Z +
            (kZeroClassOfPresentation Z - kZeroClassOfPresentation Z) := by
            rw [sub_self, add_zero]
      _ = (kZeroClassOfPresentation Z +
            kZeroClassOfPresentation Z) -
            kZeroClassOfPresentation Z := by abel
      _ = kZeroClassOfPresentation Z -
            kZeroClassOfPresentation Z := by rw [hqZ']
      _ = 0 := sub_self _
  rw [hq, hzero, add_zero]

private theorem kZeroClass_eq_of_linearEquiv
    {R : Type u} [CommRing R] {M N : Type v}
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    [Module.Projective R N]
    (e : M ≃ₗ[R] N) :
    kZeroClass (R := R) (M := M) =
      kZeroClass (R := R) (M := N) := by
  let P := Classical.choose
    (exists_finite_projective_presentation (R := R) (M := M))
  let Q := Classical.choose
    (exists_finite_projective_presentation (R := R) (M := N))
  let eP := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation (R := R) (M := M)))
  let eQ := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation (R := R) (M := N)))
  let ePQ : P.presentation.module ≃ₗ[R] Q.presentation.module :=
    eP.trans (e.trans eQ.symm)
  change kZeroClassOfPresentation P = kZeroClassOfPresentation Q
  exact kZeroClassOfPresentation_eq_of_linearEquiv P Q ePQ

private theorem kZeroClass_eq_of_presentation
    {R : Type u} [CommRing R] (P : FiniteProjectivePresentation R) :
    kZeroClass (R := R) (M := P.presentation.module) =
      kZeroClassOfPresentation P := by
  let Q := Classical.choose
    (exists_finite_projective_presentation
      (R := R) (M := P.presentation.module))
  let eQ := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation
        (R := R) (M := P.presentation.module)))
  change kZeroClassOfPresentation Q = kZeroClassOfPresentation P
  exact kZeroClassOfPresentation_eq_of_linearEquiv Q P
    (eQ.trans (LinearEquiv.refl R P.presentation.module))

private theorem kPrimeZeroClass_prod
    {R : Type u} [CommRing R]
    {M N : Type u} [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N] :
    kPrimeZeroClass (R := R) (M := M × N) =
      kPrimeZeroClass (R := R) (M := M) +
        kPrimeZeroClass (R := R) (M := N) := by
  exact kPrimeZeroClass_exact (LinearMap.inl R M N) (LinearMap.snd R M N)
    LinearMap.inl_injective LinearMap.snd_surjective (by exact .inl_snd)

/-- For a field, both K-groups are identified with ℤ by dimension. -/
private theorem kZeroClass_prod
    {R : Type u} [CommRing R]
    {M N : Type u} [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M]
    [AddCommGroup N] [Module R N] [Module.Finite R N]
    [Module.Projective R N] :
    kZeroClass (R := R) (M := M × N) =
      kZeroClass (R := R) (M := M) +
        kZeroClass (R := R) (M := N) := by
  exact kZeroClass_exact (LinearMap.inl R M N) (LinearMap.snd R M N)
    LinearMap.inl_injective LinearMap.snd_surjective (by exact .inl_snd)

private theorem kPrimeZeroClass_subsingleton
    {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Subsingleton M] :
    kPrimeZeroClass (R := R) (M := M) = 0 := by
  have hs : Function.Surjective (0 : M →ₗ[R] M) := by
    intro x
    exact ⟨0, Subsingleton.elim _ _⟩
  have hi : Function.Injective (0 : M →ₗ[R] M) := by
    intro x y _
    exact Subsingleton.elim _ _
  have h := kPrimeZeroClass_exact (0 : M →ₗ[R] M) (0 : M →ₗ[R] M)
    hi hs ((LinearMap.exact_zero_iff_surjective M (0 : M →ₗ[R] M)).2 hs)
  have h' : kPrimeZeroClass (R := R) (M := M) +
      kPrimeZeroClass (R := R) (M := M) =
      kPrimeZeroClass (R := R) (M := M) := h.symm
  calc
    kPrimeZeroClass (R := R) (M := M) =
        kPrimeZeroClass (R := R) (M := M) + 0 := (add_zero _).symm
    _ = kPrimeZeroClass (R := R) (M := M) +
        (kPrimeZeroClass (R := R) (M := M) -
          kPrimeZeroClass (R := R) (M := M)) := by rw [sub_self, add_zero]
    _ = (kPrimeZeroClass (R := R) (M := M) +
          kPrimeZeroClass (R := R) (M := M)) -
        kPrimeZeroClass (R := R) (M := M) := by abel
    _ = kPrimeZeroClass (R := R) (M := M) -
        kPrimeZeroClass (R := R) (M := M) := by rw [h']
    _ = 0 := sub_self _

private theorem kZeroClass_subsingleton
    {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [Module.Projective R M] [Subsingleton M] :
    kZeroClass (R := R) (M := M) = 0 := by
  have hs : Function.Surjective (0 : M →ₗ[R] M) := by
    intro x
    exact ⟨0, Subsingleton.elim _ _⟩
  have hi : Function.Injective (0 : M →ₗ[R] M) := by
    intro x y _
    exact Subsingleton.elim _ _
  have h := kZeroClass_exact (0 : M →ₗ[R] M) (0 : M →ₗ[R] M)
    hi hs ((LinearMap.exact_zero_iff_surjective M (0 : M →ₗ[R] M)).2 hs)
  have h' : kZeroClass (R := R) (M := M) + kZeroClass (R := R) (M := M) =
      kZeroClass (R := R) (M := M) := h.symm
  calc
    kZeroClass (R := R) (M := M) = kZeroClass (R := R) (M := M) + 0 :=
      (add_zero _).symm
    _ = kZeroClass (R := R) (M := M) +
        (kZeroClass (R := R) (M := M) - kZeroClass (R := R) (M := M)) := by
      rw [sub_self, add_zero]
    _ = (kZeroClass (R := R) (M := M) + kZeroClass (R := R) (M := M)) -
        kZeroClass (R := R) (M := M) := by abel
    _ = kZeroClass (R := R) (M := M) - kZeroClass (R := R) (M := M) := by rw [h']
    _ = 0 := sub_self _

theorem kGroups_field
    (k : Type u) [Field k] :
    ∃ e₀ : KZero k ≃+ ℤ, ∃ e₀' : KPrimeZero k ≃+ ℤ,
      (∀ x, e₀ x = kZeroRank x) ∧
      (∀ x, e₀' x = kPrimeZeroLength x) ∧
      (∀ x, e₀' (kZeroToKPrime x) = e₀ x) := by
  have hfiniteProjectiveRank (P : FiniteProjectivePresentation k) :
      finiteProjectiveRank P = Module.finrank k P.presentation.module := by
    let e := Classical.choice
      (Classical.choose_spec
        (finite_projective_is_finite_free_over_local
          (R := k) (M := P.presentation.module)))
    have he := e.finrank_eq
    simpa [finiteProjectiveRank, Module.finrank_pi] using he.symm
  have hfreeZero (n : ℕ) :
      kZeroClass (R := k) (M := Fin n → k) =
        (n : ℤ) • kZeroClass (R := k) (M := k) := by
    induction n with
    | zero =>
        simpa using
          (kZeroClass_subsingleton (R := k) (M := Fin 0 → k))
    | succ n ih =>
        let e :=
          LinearEquiv.piCongrLeft k (fun _ : Option (Fin n) => k)
            (finSuccEquiv n) ≪≫ₗ LinearEquiv.piOptionEquivProd k
        rw [kZeroClass_eq_of_linearEquiv e, kZeroClass_prod, ih]
        simp [add_smul, add_comm]
  have hfreePrime (n : ℕ) :
      kPrimeZeroClass (R := k) (M := Fin n → k) =
        (n : ℤ) • kPrimeZeroClass (R := k) (M := k) := by
    induction n with
    | zero =>
        simpa using
          (kPrimeZeroClass_subsingleton (R := k) (M := Fin 0 → k))
    | succ n ih =>
        let e :=
          LinearEquiv.piCongrLeft k (fun _ : Option (Fin n) => k)
            (finSuccEquiv n) ≪≫ₗ LinearEquiv.piOptionEquivProd k
        rw [kPrimeZeroClass_eq_of_linearEquiv e, kPrimeZeroClass_prod, ih]
        simp [add_smul, add_comm]
  have hclassZero (P : FiniteProjectivePresentation k) :
      kZeroClassOfPresentation P =
        (finiteProjectiveRank P : ℤ) •
          kZeroClass (R := k) (M := k) := by
    let _ : Module.Free k P.presentation.module :=
      finite_projective_is_free_pid
    let n := Classical.choose
      (exists_finite_free_equiv (R := k) (M := P.presentation.module))
    let e := Classical.choice
      (Classical.choose_spec
        (exists_finite_free_equiv (R := k) (M := P.presentation.module)))
    have hn : finiteProjectiveRank P = n := by
      rw [hfiniteProjectiveRank]
      have he := e.finrank_eq
      simpa [Module.finrank_pi] using he
    calc
      kZeroClassOfPresentation P =
          kZeroClass (R := k) (M := P.presentation.module) :=
        (kZeroClass_eq_of_presentation P).symm
      _ = kZeroClass (R := k) (M := Fin n → k) :=
        kZeroClass_eq_of_linearEquiv e
      _ = (n : ℤ) • kZeroClass (R := k) (M := k) := hfreeZero n
      _ = (finiteProjectiveRank P : ℤ) •
          kZeroClass (R := k) (M := k) := by rw [hn]
  have hclassPrime (P : FiniteModulePresentation k) :
      kPrimeZeroClassOfPresentation P =
        (Classical.choose
          (exists_finite_free_equiv (R := k) (M := P.module)) : ℕ) •
          kPrimeZeroClass (R := k) (M := k) := by
    let _ : Module.Free k P.module := inferInstance
    let n := Classical.choose
      (exists_finite_free_equiv (R := k) (M := P.module))
    let e := Classical.choice
      (Classical.choose_spec
        (exists_finite_free_equiv (R := k) (M := P.module)))
    calc
      kPrimeZeroClassOfPresentation P =
          kPrimeZeroClass (R := k) (M := P.module) :=
        (kPrimeZeroClass_eq_of_presentation P).symm
      _ = kPrimeZeroClass (R := k) (M := Fin n → k) :=
        kPrimeZeroClass_eq_of_linearEquiv e
      _ = (n : ℤ) • kPrimeZeroClass (R := k) (M := k) := hfreePrime n
  let P₀ := Classical.choose
    (exists_finite_projective_presentation (R := k) (M := k))
  let eP₀ := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation (R := k) (M := k)))
  let c : KZero k := kZeroClassOfPresentation P₀
  have hc : kZeroRank (R := k) c = 1 := by
    rw [kZeroRank_apply_class, hfiniteProjectiveRank]
    simpa using eP₀.finrank_eq
  let P₀' := Classical.choose
    (exists_finite_module_presentation (R := k) (M := k))
  let eP₀' := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := k) (M := k)))
  let c' : KPrimeZero k := kPrimeZeroClassOfPresentation P₀'
  have hc' : kPrimeZeroLength (R := k) c' = 1 := by
    change kPrimeZeroLength (R := k)
      (kPrimeZeroClassOfPresentation P₀') = 1
    rw [← kPrimeZeroClass_eq_of_presentation P₀',
      kPrimeZeroLength_field_eq_finrank]
    simpa using eP₀'.finrank_eq
  have hcZero : kZeroClass (R := k) (M := k) = c := by
    calc
      kZeroClass (R := k) (M := k) =
          kZeroClass (R := k) (M := P₀.presentation.module) :=
        kZeroClass_eq_of_linearEquiv eP₀.symm
      _ = c := kZeroClass_eq_of_presentation (R := k) P₀
  have hcPrime : kPrimeZeroClass (R := k) (M := k) = c' := by
    calc
      kPrimeZeroClass (R := k) (M := k) =
          kPrimeZeroClass (R := k) (M := P₀'.module) :=
        kPrimeZeroClass_eq_of_linearEquiv eP₀'.symm
      _ = c' := kPrimeZeroClass_eq_of_presentation (R := k) P₀'
  have hclassZero' (P : FiniteProjectivePresentation k) :
      kZeroClassOfPresentation P =
        (finiteProjectiveRank P : ℤ) • c := by
    rw [hclassZero, hcZero]
  have hclassPrime' (P : FiniteModulePresentation k) :
      kPrimeZeroClassOfPresentation P =
        (Classical.choose
          (exists_finite_free_equiv (R := k) (M := P.module)) : ℕ) • c' := by
    rw [hclassPrime, hcPrime]
  have hreprZero (x : KZero k) :
      x = (kZeroRank (R := k) x) • c := by
    rcases kZero_generated x with ⟨n, P, z, hx⟩
    have hrank : kZeroRank (R := k) x =
        ∑ i, z i * (finiteProjectiveRank (P i) : ℤ) := by
      rw [hx]
      simp only [map_sum, map_zsmul, kZeroRank_apply_class, smul_eq_mul]
    calc
      x = ∑ i, z i • kZeroClassOfPresentation (P i) := hx
      _ = ∑ i, z i • ((finiteProjectiveRank (P i) : ℤ) • c) := by
        apply Finset.sum_congr rfl
        intro i hi
        rw [hclassZero' (P i)]
      _ = (∑ i, z i * (finiteProjectiveRank (P i) : ℤ)) • c := by
        simp_rw [smul_smul]
        rw [Finset.sum_smul]
      _ = (kZeroRank (R := k) x) • c := by rw [hrank]
  have hreprPrime (x : KPrimeZero k) :
      x = (kPrimeZeroLength (R := k) x) • c' := by
    rcases kPrimeZero_generated x with ⟨n, P, z, hx⟩
    let q (i : Fin n) := Classical.choose
      (exists_finite_free_equiv (R := k) (M := (P i).module))
    have hlength : kPrimeZeroLength (R := k) x =
        ∑ i, z i * (q i : ℤ) := by
      rw [hx]
      simp only [map_sum, map_zsmul]
      apply Finset.sum_congr rfl
      intro i hi
      rw [kPrimeZeroLength_apply_class]
      let e := Classical.choice
        (Classical.choose_spec
          (exists_finite_free_equiv (R := k) (M := (P i).module)))
      have he := e.finrank_eq
      have hlen : Module.finrank k (P i).module = q i := by
        simpa [Module.finrank_pi] using he
      have hfield := kPrimeZeroLength_field_eq_finrank
        (k := k) (M := (P i).module)
      rw [kPrimeZeroClass_eq_of_presentation (P i),
        kPrimeZeroLength_apply_class] at hfield
      rw [hfield, hlen]
      rfl
    calc
      x = ∑ i, z i • kPrimeZeroClassOfPresentation (P i) := hx
      _ = ∑ i, z i • ((q i : ℤ) • c') := by
        apply Finset.sum_congr rfl
        intro i hi
        simpa [q] using congrArg (fun y => z i • y) (hclassPrime' (P i))
      _ = (∑ i, z i * (q i : ℤ)) • c' := by
        simp_rw [smul_smul]
        rw [Finset.sum_smul]
      _ = (kPrimeZeroLength (R := k) x) • c' := by rw [hlength]
  have hinjZero : Function.Injective (kZeroRank (R := k)) := by
    intro x y hxy
    rw [hreprZero x, hreprZero y, hxy]
  have hsurjZero : Function.Surjective (kZeroRank (R := k)) := by
    intro z
    refine ⟨z • c, ?_⟩
    simp [hc]
  have hinjPrime : Function.Injective (kPrimeZeroLength (R := k)) := by
    intro x y hxy
    rw [hreprPrime x, hreprPrime y, hxy]
  have hsurjPrime : Function.Surjective (kPrimeZeroLength (R := k)) := by
    intro z
    refine ⟨z • c', ?_⟩
    simp [hc']
  let e₀ : KZero k ≃+ ℤ :=
    AddEquiv.ofBijective (kZeroRank (R := k)) ⟨hinjZero, hsurjZero⟩
  let e₀' : KPrimeZero k ≃+ ℤ :=
    AddEquiv.ofBijective (kPrimeZeroLength (R := k))
      ⟨hinjPrime, hsurjPrime⟩
  have hcompatClass (P : FiniteProjectivePresentation k) :
      kPrimeZeroLength (R := k)
          (kZeroToKPrime (R := k) (kZeroClassOfPresentation P)) =
        kZeroRank (R := k) (kZeroClassOfPresentation P) := by
    rw [kZeroToKPrime_apply_class, kPrimeZeroLength_apply_class,
      kZeroRank_apply_class]
    rw [hfiniteProjectiveRank]
    have hfield := kPrimeZeroLength_field_eq_finrank
      (k := k) (M := P.presentation.module)
    rw [kPrimeZeroClass_eq_of_presentation P.presentation,
      kPrimeZeroLength_apply_class] at hfield
    simpa using hfield
  have hcompat (x : KZero k) :
      kPrimeZeroLength (R := k) (kZeroToKPrime (R := k) x) =
        kZeroRank (R := k) x := by
    rcases kZero_generated x with ⟨n, P, z, hx⟩
    rw [hx]
    simp only [map_sum, map_zsmul]
    apply Finset.sum_congr rfl
    intro i hi
    rw [hcompatClass]
  refine ⟨e₀, e₀', ?_, ?_, ?_⟩
  · intro x
    rfl
  · intro x
    rfl
  · intro x
    exact hcompat x

/-- Finite modules over a domain have additive finrank on products. -/
private theorem finite_module_finrank_prod_pid
    {R A B : Type u} [CommRing R] [IsDomain R]
    [AddCommGroup A] [Module R A] [Module.Finite R A]
    [AddCommGroup B] [Module R B] [Module.Finite R B] :
    Module.finrank R (A × B) = Module.finrank R A + Module.finrank R B := by
  have hfg : Function.Exact (LinearMap.inl R A B) (LinearMap.snd R A B) := by
    exact .inl_snd
  have hrank : Module.rank R (A × B) =
      Module.rank R A + Module.rank R B := by
    calc
      Module.rank R (A × B) =
          Module.rank R (LinearMap.range (LinearMap.snd R A B)) +
            Module.rank R (LinearMap.ker (LinearMap.snd R A B)) :=
        (LinearMap.rank_range_add_rank_ker (LinearMap.snd R A B)).symm
      _ = Module.rank R B +
          Module.rank R (LinearMap.range (LinearMap.inl R A B)) := by
        rw [rank_range_of_surjective (LinearMap.snd R A B)
          LinearMap.snd_surjective, hfg.linearMap_ker_eq]
      _ = Module.rank R (LinearMap.range (LinearMap.inl R A B)) +
          Module.rank R B := add_comm _ _
      _ = Module.rank R A + Module.rank R B := by
        rw [rank_range_of_injective (LinearMap.inl R A B)
          LinearMap.inl_injective]
  rw [← Nat.cast_inj (R := Cardinal), Module.finrank_eq_rank,
    Nat.cast_add, Module.finrank_eq_rank, Module.finrank_eq_rank]
  exact hrank

/-- Torsion finite modules over a PID have zero K′₀ class. -/
theorem kPrimeZeroClass_torsion_pid
    {R M : Type u} [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    (hM : Module.IsTorsion R M) :
    kPrimeZeroClass (R := R) (M := M) = 0 := by
  have hsummand (d : R) (hd : d ≠ 0) :
      kPrimeZeroClass (R := R)
          (M := pidTorsionSummand R d) = 0 := by
    let I : Ideal R := Ideal.span ({d} : Set R)
    let f : R →ₗ[R] I :=
      { toFun := fun r =>
          ⟨r * d, I.mul_mem_left r (Ideal.mem_span_singleton_self d)⟩
        map_add' := by
          intro x y
          ext
          simp [add_mul]
        map_smul' := by
          intro r x
          ext
          change (r * x) * d = r * (x * d)
          ring }
    have hf : Function.Surjective f := by
      intro x
      obtain ⟨r, hr⟩ := (Ideal.mem_span_singleton' (x := (x : R)) (y := d)).mp x.property
      exact ⟨r, Subtype.ext hr⟩
    let _ : Module.Finite R I := Module.Finite.of_surjective f hf
    have hi : Function.Injective f := by
      intro x y hxy
      apply mul_right_cancel₀ hd
      exact congrArg Subtype.val hxy
    let eI : R ≃ₗ[R] I := LinearEquiv.ofBijective f ⟨hi, hf⟩
    have hI : kPrimeZeroClass (R := R) (M := R) =
        kPrimeZeroClass (R := R) (M := I) :=
      kPrimeZeroClass_eq_of_linearEquiv eI
    have hseq := kPrimeZeroClass_exact I.subtype I.mkQ
      I.subtype_injective I.mkQ_surjective
      (LinearMap.exact_subtype_mkQ I)
    change kPrimeZeroClass (R := R)
      (M := R ⧸ I) = 0
    rw [hI] at hseq
    have hq : kPrimeZeroClass (R := R) (M := R ⧸ I) = 0 := by
      calc
        kPrimeZeroClass (R := R) (M := R ⧸ I) =
            (kPrimeZeroClass (R := R) (M := I) +
              kPrimeZeroClass (R := R) (M := R ⧸ I)) -
              kPrimeZeroClass (R := R) (M := I) := by abel
        _ = kPrimeZeroClass (R := R) (M := I) -
            kPrimeZeroClass (R := R) (M := I) := by rw [hseq.symm]
        _ = 0 := sub_self _
    exact hq
  have hdirect (n : ℕ) (d : Fin n → R)
      (hd : ∀ i, d i ≠ 0) :
      kPrimeZeroClass (R := R)
          (M := DirectSum (Fin n) (fun i => pidTorsionSummand R (d i))) = 0 := by
    induction n with
    | zero =>
        simpa using
          (kPrimeZeroClass_subsingleton (R := R)
            (M := DirectSum (Fin 0) (fun i => pidTorsionSummand R (d i))))
    | succ n ih =>
        let e :
            DirectSum (Fin (n + 1)) (fun i => pidTorsionSummand R (d i)) ≃ₗ[R]
              (pidTorsionSummand R (d 0) ×
                DirectSum (Fin n) (fun i => pidTorsionSummand R (d i.succ))) :=
          (DirectSum.lequivCongrLeft R (finSuccEquiv n)).trans
            (DirectSum.lequivProdDirectSum R)
        rw [kPrimeZeroClass_eq_of_linearEquiv e, kPrimeZeroClass_prod]
        rw [hsummand (d 0) (hd 0)]
        have hi := ih (fun i => d i.succ) (fun i => hd i.succ)
        simpa using hi
  obtain ⟨r, ι, _, p, hp, exp, ⟨h⟩⟩ :=
    Module.equiv_free_prod_directSum (R := R) (M := M)
  let eι := Fintype.equivFin ι
  let d : Fin (Fintype.card ι) → R :=
    fun j => p (eι.symm j) ^ exp (eι.symm j)
  let eM := h.trans
    ((Finsupp.linearEquivFunOnFinite R R (Fin r)).prodCongr
      (DirectSum.lequivCongrLeft R eι))
  have hfin : Module.finrank R M = 0 := Module.IsTorsion.finrank_eq_zero hM
  rw [eM.finrank_eq, finite_module_finrank_prod_pid, Module.finrank_pi] at hfin
  have hr : r + Module.finrank R
      (DirectSum (Fin (Fintype.card ι))
        (fun i => pidTorsionSummand R (d i))) = 0 := by
    simpa [pidTorsionSummand, d, Module.finrank_pi] using hfin
  have hr0 : r = 0 := by omega
  subst r
  have hd (i : Fin (Fintype.card ι)) : d i ≠ 0 := by
    dsimp [d]
    exact pow_ne_zero _ (hp (eι.symm i)).ne_zero
  rw [kPrimeZeroClass_eq_of_linearEquiv eM, kPrimeZeroClass_prod,
    kPrimeZeroClass_subsingleton]
  exact hdirect _ d hd

/-- For a PID, both K-groups are identified with ℤ by rank. -/
private theorem pidTorsionSummand_isTorsion
    {R : Type u} [CommRing R] [IsDomain R]
    (d : R) (hd : d ≠ 0) :
    Module.IsTorsion R (pidTorsionSummand R d) := by
  intro x
  refine ⟨⟨d, mem_nonZeroDivisors_of_ne_zero hd⟩, ?_⟩
  obtain ⟨y, rfl⟩ := (Ideal.span ({d} : Set R)).mkQ_surjective x
  change (Ideal.span ({d} : Set R)).mkQ (d * y) = 0
  apply (Submodule.Quotient.mk_eq_zero (Ideal.span ({d} : Set R))).2
  exact (Ideal.mem_span_singleton' (x := d * y) (y := d)).2
    ⟨y, mul_comm y d⟩

private theorem finite_directSum_isTorsion
    {R : Type u} [CommRing R] [IsDomain R]
    (n : ℕ) (M : Fin n → Type u)
    [∀ i, AddCommGroup (M i)] [∀ i, Module R (M i)]
    (hM : ∀ i, Module.IsTorsion R (M i)) :
    Module.IsTorsion R (DirectSum (Fin n) M) := by
  induction n with
  | zero =>
      intro x
      refine ⟨⟨(1 : R), mem_nonZeroDivisors_of_ne_zero one_ne_zero⟩, ?_⟩
      exact Subsingleton.elim _ _
  | succ n ih =>
      let e : DirectSum (Fin (n + 1)) M ≃ₗ[R]
          (M 0 × DirectSum (Fin n) (fun i => M i.succ)) :=
        (DirectSum.lequivCongrLeft R (finSuccEquiv n)).trans
          (DirectSum.lequivProdDirectSum R)
      have hprod : Module.IsTorsion R
          (M 0 × DirectSum (Fin n) (fun i => M i.succ)) := by
        rintro ⟨x, y⟩
        obtain ⟨a, ha⟩ := hM 0 (x := x)
        obtain ⟨b, hb⟩ :=
          ih (M := fun i => M i.succ) (fun i => hM i.succ) (x := y)
        have ha' : (a : R) • x = 0 := by
          simpa only [Submonoid.smul_def] using ha
        have hb' : (b : R) • y = 0 := by
          simpa only [Submonoid.smul_def] using hb
        refine ⟨⟨(a : R) * (b : R),
          mul_mem_nonZeroDivisors.2 ⟨a.2, b.2⟩⟩, ?_⟩
        apply Prod.ext
        · change ((a : R) * (b : R)) • x = 0
          calc
            ((a : R) * (b : R)) • x = ((b : R) * (a : R)) • x := by
              rw [mul_comm]
            _ = (b : R) • ((a : R) • x) := by rw [mul_smul]
            _ = 0 := by rw [ha', smul_zero]
        · change ((a : R) * (b : R)) • y = 0
          calc
            ((a : R) * (b : R)) • y = (a : R) • ((b : R) • y) := by
              rw [mul_smul]
            _ = 0 := by rw [hb', smul_zero]
      intro x
      obtain ⟨a, ha⟩ := hprod (x := e x)
      refine ⟨a, ?_⟩
      apply e.injective
      calc
        e (a • x) = a • e x := e.map_smul a x
        _ = 0 := ha
        _ = e 0 := (e.map_zero).symm

private theorem kPrimeZeroClass_free_pid
    {R : Type u} [CommRing R] [IsDomain R]
    (n : ℕ) :
    kPrimeZeroClass (R := R) (M := Fin n → R) =
      (n : ℤ) • kPrimeZeroClass (R := R) (M := R) := by
  induction n with
  | zero =>
      simpa using
        (kPrimeZeroClass_subsingleton (R := R) (M := Fin 0 → R))
  | succ n ih =>
      let e : (Fin (n + 1) → R) ≃ₗ[R] R × (Fin n → R) :=
        LinearEquiv.piCongrLeft R (fun _ : Option (Fin n) => R)
          (finSuccEquiv n) ≪≫ₗ LinearEquiv.piOptionEquivProd R
      rw [kPrimeZeroClass_eq_of_linearEquiv e, kPrimeZeroClass_prod, ih]
      simp [add_smul, add_comm, add_left_comm, add_assoc]

private theorem kZeroClass_free_pid
    {R : Type u} [CommRing R] [IsDomain R]
    (n : ℕ) :
    kZeroClass (R := R) (M := Fin n → R) =
      (n : ℤ) • kZeroClass (R := R) (M := R) := by
  induction n with
  | zero =>
      simpa using
        (kZeroClass_subsingleton (R := R) (M := Fin 0 → R))
  | succ n ih =>
      let e : (Fin (n + 1) → R) ≃ₗ[R] R × (Fin n → R) :=
        LinearEquiv.piCongrLeft R (fun _ : Option (Fin n) => R)
          (finSuccEquiv n) ≪≫ₗ LinearEquiv.piOptionEquivProd R
      rw [kZeroClass_eq_of_linearEquiv e, kZeroClass_prod, ih]
      simp [add_smul, add_comm, add_left_comm, add_assoc]

private theorem kPrimeZeroClass_eq_free_rank_pid
    {R M : Type u} [CommRing R] [IsDomain R] [IsPrincipalIdealRing R]
    [AddCommGroup M] [Module R M] [Module.Finite R M] :
    kPrimeZeroClass (R := R) (M := M) =
      (Module.finrank R M : ℤ) • kPrimeZeroClass (R := R) (M := R) := by
  obtain ⟨r, ι, _, p, hp, exp, ⟨h⟩⟩ :=
    Module.equiv_free_prod_directSum (R := R) (M := M)
  let eι := Fintype.equivFin ι
  let d : Fin (Fintype.card ι) → R :=
    fun j => p (eι.symm j) ^ exp (eι.symm j)
  let eM := h.trans
    ((Finsupp.linearEquivFunOnFinite R R (Fin r)).prodCongr
      (DirectSum.lequivCongrLeft R eι))
  have hd (i : Fin (Fintype.card ι)) : d i ≠ 0 := by
    dsimp [d]
    exact pow_ne_zero _ (hp (eι.symm i)).ne_zero
  have hT : Module.IsTorsion R
      (DirectSum (Fin (Fintype.card ι))
        (fun i => pidTorsionSummand R (d i))) :=
    finite_directSum_isTorsion _ _ fun i =>
      pidTorsionSummand_isTorsion (d i) (hd i)
  have hzeroT : kPrimeZeroClass (R := R)
      (M := DirectSum (Fin (Fintype.card ι))
        (fun i => pidTorsionSummand R (d i))) = 0 :=
    kPrimeZeroClass_torsion_pid hT
  have hfin : Module.finrank R M = r := by
    rw [eM.finrank_eq, finite_module_finrank_prod_pid, Module.finrank_pi,
      Module.IsTorsion.finrank_eq_zero hT, add_zero]
    simp
  calc
    kPrimeZeroClass (R := R) (M := M) =
        kPrimeZeroClass (R := R) (M := (Fin r → R)) +
          kPrimeZeroClass (R := R)
            (M := DirectSum (Fin (Fintype.card ι))
              (fun i => pidTorsionSummand R (d i))) := by
      rw [kPrimeZeroClass_eq_of_linearEquiv eM, kPrimeZeroClass_prod]
    _ = kPrimeZeroClass (R := R) (M := Fin r → R) := by rw [hzeroT, add_zero]
    _ = (r : ℤ) • kPrimeZeroClass (R := R) (M := R) :=
      kPrimeZeroClass_free_pid r
    _ = (Module.finrank R M : ℤ) • kPrimeZeroClass (R := R) (M := R) := by
      rw [hfin]

private theorem finite_module_rank_add_of_short_exact_pid
    {R M' M M'' : Type u} [CommRing R] [IsDomain R]
    [AddCommGroup M'] [Module R M'] [Module.Finite R M']
    [AddCommGroup M] [Module R M] [Module.Finite R M]
    [AddCommGroup M''] [Module R M''] [Module.Finite R M'']
    (f : M' →ₗ[R] M) (g : M →ₗ[R] M'')
    (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) :
    Module.finrank R M =
      Module.finrank R M' + Module.finrank R M'' := by
  have hrank : Module.rank R M =
      Module.rank R M' + Module.rank R M'' := by
    calc
      Module.rank R M = Module.rank R (LinearMap.range g) +
          Module.rank R (LinearMap.ker g) :=
        (LinearMap.rank_range_add_rank_ker g).symm
      _ = Module.rank R M'' + Module.rank R (LinearMap.range f) := by
        rw [rank_range_of_surjective g hg, hfg.linearMap_ker_eq]
      _ = Module.rank R (LinearMap.range f) + Module.rank R M'' := add_comm _ _
      _ = Module.rank R M' + Module.rank R M'' := by
        rw [rank_range_of_injective f hf]
  rw [← Nat.cast_inj (R := Cardinal), Module.finrank_eq_rank,
    Nat.cast_add, Module.finrank_eq_rank, Module.finrank_eq_rank]
  exact hrank

theorem kGroups_pid
    (R : Type u) [CommRing R] [IsDomain R] [IsPrincipalIdealRing R] :
    ∃ e₀ : KZero R ≃+ ℤ, ∃ e₀' : KPrimeZero R ≃+ ℤ,
      (∀ x, e₀' (kZeroToKPrime x) = e₀ x) := by
  let projectiveRank (P : FiniteProjectivePresentation R) : ℕ :=
    let _ : Module.Free R P.presentation.module := finite_projective_is_free_pid
    finiteFreeRank (R := R) (M := P.presentation.module)
  have hprojectiveRank (P : FiniteProjectivePresentation R) :
      projectiveRank P = Module.finrank R P.presentation.module := by
    dsimp [projectiveRank]
    let _ : Module.Free R P.presentation.module := finite_projective_is_free_pid
    let e := Classical.choice
      (Classical.choose_spec
        (exists_finite_free_equiv (R := R) (M := P.presentation.module)))
    have he := e.finrank_eq
    simpa [finiteFreeRank, Module.finrank_pi] using he.symm
  let rankFree : KZeroFree R →+ ℤ :=
    FreeAbelianGroup.lift (fun P => (projectiveRank P : ℤ))
  have rankFree_rel : kZeroCon R ≤ AddCon.ker rankFree := by
    refine AddCon.addConGen_le.2 ?_
    rintro x y ⟨S, rfl, rfl⟩
    simp only [rankFree]
    change (projectiveRank S.middle : ℤ) =
      (projectiveRank S.left : ℤ) + (projectiveRank S.right : ℤ)
    have hrank := finite_module_rank_add_of_short_exact_pid
      S.leftToMiddle S.middleToRight S.left_injective
      S.middle_surjective S.exact
    rw [hprojectiveRank S.middle, hprojectiveRank S.left,
      hprojectiveRank S.right]
    exact_mod_cast hrank
  let rankPid : KZero R →+ ℤ :=
    (kZeroCon R).lift rankFree rankFree_rel
  have rankPid_apply (P : FiniteProjectivePresentation R) :
      rankPid (kZeroClassOfPresentation P) = projectiveRank P := by
    rfl
  let primeFree : KPrimeZeroFree R →+ ℤ :=
    FreeAbelianGroup.lift
      (fun P => (Module.finrank R P.module : ℤ))
  have primeFree_rel : kPrimeZeroCon R ≤ AddCon.ker primeFree := by
    refine AddCon.addConGen_le.2 ?_
    rintro x y ⟨S, rfl, rfl⟩
    simp only [primeFree]
    change (Module.finrank R S.middle.module : ℤ) =
      (Module.finrank R S.left.module : ℤ) +
        (Module.finrank R S.right.module : ℤ)
    exact_mod_cast finite_module_rank_add_of_short_exact_pid
      S.leftToMiddle S.middleToRight S.left_injective
      S.middle_surjective S.exact
  let primeRank : KPrimeZero R →+ ℤ :=
    (kPrimeZeroCon R).lift primeFree primeFree_rel
  have primeRank_apply (P : FiniteModulePresentation R) :
      primeRank (kPrimeZeroClassOfPresentation P) = Module.finrank R P.module := by
    rfl
  have hfreeZero (n : ℕ) :
      kZeroClass (R := R) (M := Fin n → R) =
        (n : ℤ) • kZeroClass (R := R) (M := R) :=
    kZeroClass_free_pid n
  let P₀ := Classical.choose
    (exists_finite_projective_presentation (R := R) (M := R))
  let eP₀ := Classical.choice
    (Classical.choose_spec
      (exists_finite_projective_presentation (R := R) (M := R)))
  let c : KZero R := kZeroClassOfPresentation P₀
  have hc : rankPid c = 1 := by
    rw [rankPid_apply, hprojectiveRank]
    simpa using eP₀.finrank_eq
  have hcZero : kZeroClass (R := R) (M := R) = c := by
    calc
      kZeroClass (R := R) (M := R) =
          kZeroClass (R := R) (M := P₀.presentation.module) :=
        kZeroClass_eq_of_linearEquiv eP₀.symm
      _ = c := kZeroClass_eq_of_presentation (R := R) P₀
  have hclassZero (P : FiniteProjectivePresentation R) :
      kZeroClassOfPresentation P = (projectiveRank P : ℤ) • c := by
    let _ : Module.Free R P.presentation.module := finite_projective_is_free_pid
    let n := Classical.choose
      (exists_finite_free_equiv (R := R) (M := P.presentation.module))
    let e := Classical.choice
      (Classical.choose_spec
        (exists_finite_free_equiv (R := R) (M := P.presentation.module)))
    have hn : projectiveRank P = n := by
      rw [hprojectiveRank]
      simpa [Module.finrank_pi] using e.finrank_eq
    calc
      kZeroClassOfPresentation P =
          kZeroClass (R := R) (M := P.presentation.module) :=
        (kZeroClass_eq_of_presentation P).symm
      _ = kZeroClass (R := R) (M := Fin n → R) :=
        kZeroClass_eq_of_linearEquiv e
      _ = (n : ℤ) • kZeroClass (R := R) (M := R) := hfreeZero n
      _ = (projectiveRank P : ℤ) • c := by rw [hn, hcZero]
  have hclassPrime (P : FiniteModulePresentation R) :
      kPrimeZeroClassOfPresentation P =
        (Module.finrank R P.module : ℤ) •
          kPrimeZeroClass (R := R) (M := R) := by
    calc
      kPrimeZeroClassOfPresentation P =
          kPrimeZeroClass (R := R) (M := P.module) :=
        (kPrimeZeroClass_eq_of_presentation P).symm
      _ = (Module.finrank R P.module : ℤ) •
          kPrimeZeroClass (R := R) (M := R) :=
        kPrimeZeroClass_eq_free_rank_pid
  let P₀' := Classical.choose
    (exists_finite_module_presentation (R := R) (M := R))
  let eP₀' := Classical.choice
    (Classical.choose_spec
      (exists_finite_module_presentation (R := R) (M := R)))
  let c' : KPrimeZero R := kPrimeZeroClassOfPresentation P₀'
  have hcPrime : kPrimeZeroClass (R := R) (M := R) = c' := by
    calc
      kPrimeZeroClass (R := R) (M := R) =
          kPrimeZeroClass (R := R) (M := P₀'.module) :=
        kPrimeZeroClass_eq_of_linearEquiv eP₀'.symm
      _ = c' := kPrimeZeroClass_eq_of_presentation (R := R) P₀'
  have hclassPrime' (P : FiniteModulePresentation R) :
      kPrimeZeroClassOfPresentation P =
        (Module.finrank R P.module : ℤ) • c' := by
    rw [hclassPrime, hcPrime]
  have hreprZero (x : KZero R) :
      x = (rankPid x) • c := by
    rcases kZero_generated x with ⟨n, P, z, hx⟩
    have hrank : rankPid x =
        ∑ i, z i * (projectiveRank (P i) : ℤ) := by
      rw [hx]
      simp only [map_sum, map_zsmul, rankPid_apply, smul_eq_mul]
    calc
      x = ∑ i, z i • kZeroClassOfPresentation (P i) := hx
      _ = ∑ i, z i • ((projectiveRank (P i) : ℤ) • c) := by
        apply Finset.sum_congr rfl
        intro i hi
        rw [hclassZero (P i)]
      _ = (∑ i, z i * (projectiveRank (P i) : ℤ)) • c := by
        simp_rw [smul_smul]
        rw [Finset.sum_smul]
      _ = (rankPid x) • c := by rw [hrank]
  have hreprPrime (x : KPrimeZero R) :
      x = (primeRank x) • c' := by
    rcases kPrimeZero_generated x with ⟨n, P, z, hx⟩
    have hrank : primeRank x =
        ∑ i, z i * (Module.finrank R (P i).module : ℤ) := by
      rw [hx]
      simp only [map_sum, map_zsmul, primeRank_apply, smul_eq_mul]
    calc
      x = ∑ i, z i • kPrimeZeroClassOfPresentation (P i) := hx
      _ = ∑ i, z i • ((Module.finrank R (P i).module : ℤ) • c') := by
        apply Finset.sum_congr rfl
        intro i hi
        rw [hclassPrime' (P i)]
      _ = (∑ i, z i * (Module.finrank R (P i).module : ℤ)) • c' := by
        simp_rw [smul_smul]
        rw [Finset.sum_smul]
      _ = (primeRank x) • c' := by rw [hrank]
  have hinjZero : Function.Injective rankPid := by
    intro x y hxy
    rw [hreprZero x, hreprZero y, hxy]
  have hsurjZero : Function.Surjective rankPid := by
    intro z
    refine ⟨z • c, ?_⟩
    simp [hc]
  have hinjPrime : Function.Injective primeRank := by
    intro x y hxy
    rw [hreprPrime x, hreprPrime y, hxy]
  have hc' : primeRank c' = 1 := by
    change primeRank (kPrimeZeroClassOfPresentation P₀') = 1
    rw [primeRank_apply]
    simpa using eP₀'.finrank_eq
  have hsurjPrime : Function.Surjective primeRank := by
    intro z
    refine ⟨z • c', ?_⟩
    simp [hc']
  let e₀ : KZero R ≃+ ℤ :=
    AddEquiv.ofBijective rankPid ⟨hinjZero, hsurjZero⟩
  let e₀' : KPrimeZero R ≃+ ℤ :=
    AddEquiv.ofBijective primeRank ⟨hinjPrime, hsurjPrime⟩
  have hcompatClass (P : FiniteProjectivePresentation R) :
      primeRank (kZeroToKPrime (R := R) (kZeroClassOfPresentation P)) =
        rankPid (kZeroClassOfPresentation P) := by
    rw [kZeroToKPrime_apply_class, primeRank_apply,
      rankPid_apply, hprojectiveRank]
  have hcompat (x : KZero R) :
      primeRank (kZeroToKPrime (R := R) x) = rankPid x := by
    rcases kZero_generated x with ⟨n, P, z, hx⟩
    rw [hx]
    simp only [map_sum, map_zsmul]
    apply Finset.sum_congr rfl
    intro i hi
    rw [hcompatClass]
  refine ⟨e₀, e₀', ?_⟩
  intro x
  exact hcompat x

/-- The polynomial-ring example, obtained by applying the PID example to
the polynomial ring. -/
theorem kGroups_polynomial
    (k : Type u) [Field k] :
    ∃ e₀ : KZero (Polynomial k) ≃+ ℤ,
      ∃ e₀' : KPrimeZero (Polynomial k) ≃+ ℤ,
        ∀ x, e₀' (kZeroToKPrime x) = e₀ x := by
  simpa using kGroups_pid (Polynomial k)

/-- The coordinate ring of the node in the source's example. -/
def nodeRing (k : Type u) [Field k] : Subalgebra k (Polynomial k) :=
  AlgHom.equalizer (Polynomial.aeval (0 : k)) (Polynomial.aeval (1 : k))

/-- The node example: the projective K-group has an extra unit-class
summand, while the finite-module K-group is ℤ. -/
theorem kGroups_node
    (k : Type u) [Field k] :
    Nonempty (KZero (nodeRing k) ≃+ (Additive (kˣ) × ℤ)) ∧
      Nonempty (KPrimeZero (nodeRing k) ≃+ ℤ) := by
  sorry

/-- The canonical map need not be an isomorphism; the node example gives a
concrete failure whenever the field is infinite. -/
theorem kZeroToKPrime_node_not_bijective
    (k : Type u) [Field k] [Infinite k] :
    ¬ Function.Bijective (kZeroToKPrime (R := nodeRing k)) := by
  sorry

/-- Product decomposition for both K-groups. -/
theorem kGroups_prod
    {R₁ R₂ : Type u} [CommRing R₁] [CommRing R₂] :
    Nonempty (KZero (R₁ × R₂) ≃+ (KZero R₁ × KZero R₂)) ∧
      Nonempty (KPrimeZero (R₁ × R₂) ≃+
        (KPrimeZero R₁ × KPrimeZero R₂)) := by
  sorry

private theorem kPrimeZeroClass_eq_length_smul_artinian_local
    (R : Type u) [CommRing R] [IsArtinianRing R] [IsLocalRing R]
    {M : Type u} [AddCommGroup M] [Module R M] [Module.Finite R M] :
    kPrimeZeroClass (R := R) (M := M) =
      ((Module.length R M).toNat : ℤ) •
        kPrimeZeroClass (R := R) (M := R ⧸ IsLocalRing.maximalIdeal R) := by
  let c : KPrimeZero R :=
    kPrimeZeroClass (R := R) (M := R ⧸ IsLocalRing.maximalIdeal R)
  have hfinite : IsFiniteLength R M := by
    apply ((IsArtinianRing.tfae R M).out 0 3).mp
    infer_instance
  obtain ⟨s, hsbot, hstop⟩ :=
    isFiniteLength_iff_exists_compositionSeries.mp hfinite
  have hseries : ∀ (t : CompositionSeries (Submodule R M)),
      t.head = ⊥ →
        kPrimeZeroClass (R := R) (M := t.last) =
          (t.length : ℤ) • c := by
    intro t
    induction t using RelSeries.inductionOn' with
    | singleton x =>
        intro hx
        change kPrimeZeroClass (R := R) (M := x) = _
        have hx' : x = (⊥ : Submodule R M) := by simpa using hx
        rw [hx']
        simpa [c] using (kPrimeZeroClass_subsingleton (R := R)
          (M := (⊥ : Submodule R M)))
    | snoc t x htx ih =>
        intro ht
        have ht' : t.head = ⊥ := by simpa using ht
        let f : t.last →ₗ[R] x := Submodule.inclusion htx.le
        let q : x →ₗ[R] (x ⧸ f.range) := f.range.mkQ
        have hfrange : f.range = t.last.comap x.subtype := by
          ext y
          constructor
          · rintro ⟨z, rfl⟩
            exact z.property
          · intro hy
            exact ⟨⟨y, hy⟩, rfl⟩
        have hexact :
            kPrimeZeroClass (R := R) (M := x) =
              kPrimeZeroClass (R := R) (M := t.last) +
                kPrimeZeroClass (R := R) (M := x ⧸ f.range) :=
          kPrimeZeroClass_exact f q
            (Submodule.inclusion_injective _) f.range.mkQ_surjective
            (LinearMap.exact_map_mkQ_range f)
        have hsimple : IsSimpleModule R (x ⧸ f.range) := by
          rw [hfrange]
          exact (covBy_iff_quot_is_simple htx.le).mp htx
        obtain ⟨I, hI, ⟨e⟩⟩ := isSimpleModule_iff_quot_maximal.mp hsimple
        rw [IsLocalRing.eq_maximalIdeal hI] at e
        have hres : kPrimeZeroClass (R := R) (M := x ⧸ f.range) = c := by
          exact (kPrimeZeroClass_eq_of_linearEquiv e).trans (by rfl)
        have hstep :
            kPrimeZeroClass (R := R) (M := x) =
              (t.snoc x htx).length • c := by
          rw [hexact, ih ht', hres]
          simp [RelSeries.snoc_length, add_smul, add_comm, add_left_comm,
            add_assoc]
        have hlast : (t.snoc x htx).last = x :=
          RelSeries.last_snoc t x htx
        exact (kPrimeZeroClass_eq_of_linearEquiv
          (LinearEquiv.ofEq _ _ hlast)).trans hstep
  have hlen := Module.length_compositionSeries s hsbot hstop
  have hlenNat : s.length = (Module.length R M).toNat := by
    simpa using congrArg ENat.toNat hlen
  calc
    kPrimeZeroClass (R := R) (M := M) =
        kPrimeZeroClass (R := R) (M := s.last) := by
      rw [hstop]
      exact (kPrimeZeroClass_eq_of_linearEquiv
        (Submodule.topEquiv : (⊤ : Submodule R M) ≃ₗ[R] M)).symm
    _ = (s.length : ℤ) • c := hseries s hsbot
    _ = ((Module.length R M).toNat : ℤ) • c := by rw [hlenNat]
    _ = ((Module.length R M).toNat : ℤ) •
        kPrimeZeroClass (R := R) (M := IsLocalRing.ResidueField R) := by
      rfl

/-- The length map is an isomorphism for an Artinian local ring. -/
theorem kPrimeZeroLength_artinian_local_bijective
    (R : Type u) [CommRing R] [IsArtinianRing R] [IsLocalRing R] :
    Function.Bijective (kPrimeZeroLength (R := R)) := by
  let c : KPrimeZero R :=
    kPrimeZeroClass (R := R) (M := R ⧸ IsLocalRing.maximalIdeal R)
  have hc : kPrimeZeroLength (R := R) c = 1 := by
    let P := Classical.choose
      (exists_finite_module_presentation
        (R := R) (M := IsLocalRing.ResidueField R))
    let e := Classical.choice
      (Classical.choose_spec
        (exists_finite_module_presentation
          (R := R) (M := IsLocalRing.ResidueField R)))
    change kPrimeZeroLength (R := R)
      (kPrimeZeroClassOfPresentation P) = 1
    rw [kPrimeZeroLength_apply_class, finitePresentationLength]
    rw [e.length_eq]
    rw [Module.length_eq_one_iff.mpr]
    · rfl
    apply (isSimpleModule_iff_quot_maximal).2
    exact ⟨IsLocalRing.maximalIdeal R,
      IsLocalRing.maximalIdeal.isMaximal R,
      ⟨LinearEquiv.refl R (R ⧸ IsLocalRing.maximalIdeal R)⟩⟩
  have hrepr (x : KPrimeZero R) :
      x = (kPrimeZeroLength (R := R) x) • c := by
    rcases kPrimeZero_generated x with ⟨n, P, z, hx⟩
    calc
      x = ∑ i, z i • kPrimeZeroClassOfPresentation (P i) := hx
      _ = ∑ i, z i •
          (((Module.length R (P i).module).toNat : ℤ) • c) := by
        apply Finset.sum_congr rfl
        intro i hi
        rw [← kPrimeZeroClass_eq_of_presentation (P i),
          kPrimeZeroClass_eq_length_smul_artinian_local]
      _ = (∑ i, z i * (Module.length R (P i).module).toNat) • c := by
        simp_rw [smul_smul]
        rw [Finset.sum_smul]
      _ = (kPrimeZeroLength (R := R) x) • c := by
        rw [hx]
        simp only [map_sum, map_zsmul, kPrimeZeroLength_apply_class,
          finitePresentationLength, smul_eq_mul]
  have hinj : Function.Injective (kPrimeZeroLength (R := R)) := by
    intro x y hxy
    rw [hrepr x, hrepr y, hxy]
  have hsurj : Function.Surjective (kPrimeZeroLength (R := R)) := by
    intro z
    refine ⟨z • c, ?_⟩
    simp [hc]
  exact ⟨hinj, hsurj⟩

/-- The rank map is an isomorphism for a local ring. -/
theorem kZeroRank_local_bijective
    (R : Type u) [CommRing R] [IsLocalRing R] :
    Function.Bijective (kZeroRank (R := R)) := by
  sorry

/-- Multiplication by an integer, as an additive homomorphism. -/
def intMul (n : ℤ) : ℤ →+ ℤ where
  toFun z := n * z
  map_zero' := by simp
  map_add' x y := by simp [mul_add]

/-- The rank/length square for an Artinian local ring. -/
theorem kZero_kPrimeZero_artinian_local
    (R : Type u) [CommRing R] [IsArtinianRing R] [IsLocalRing R] :
    (∀ x : KZero R,
        kPrimeZeroLength (R := R) (kZeroToKPrime (R := R) x) =
          intMul (Module.length R R).toNat (kZeroRank (R := R) x)) ∧
      Function.Bijective (kZeroRank (R := R)) ∧
      Function.Bijective (kPrimeZeroLength (R := R)) := by
  sorry

end

end Formalization.Books.Algebra.Unit55
