import Formalization.Books.Algebra.Unit03.BasicNotions
import Formalization.Books.Smoothing.Unit02.SingularIdeals
import Mathlib.RingTheory.FinitePresentation
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
import Mathlib.RingTheory.KrullDimension.Basic
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Noetherian.Basic

/-!
# Smoothing Ring Maps, Chapter 9: Local tricks

The source's local-resolution arguments are recorded here using the canonical
singular ideal, strict-standard predicate, quotient, localization, finite
presentation, and Krull-dimension APIs.  The proofs of the three source
lemmas are deferred to the proof stage.
-/

namespace Formalization.Books.Smoothing.Unit09

open Formalization.Books.Algebra.Unit03
open Formalization.Books.Smoothing.Unit02

noncomputable section

universe u

/-! ## The local situation and its resolution -/

/-- The local situation from the source.  The map is stored as a ring map
because the singular ideal is extended along its underlying map; the
`map_base` field records that it is an `R`-algebra map. -/
structure LocalSituation
    (R A Λ : Type u) [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] where
  map : A →+* Λ
  map_base : map.comp (algebraMap R A) = algebraMap R Λ
  q : PrimeSpectrum Λ
  finitePresentation : Algebra.FinitePresentation R A

/-- The contracted prime `p = R ∩ q` in the source situation. -/
abbrev LocalSituation.p
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (s : LocalSituation R A Λ) : Ideal R :=
  s.q.asIdeal.comap (algebraMap R Λ)

/-- The extension of the singular ideal of `A` to the target. -/
def localSingularIdeal
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (φ : A →+* Λ) : Ideal Λ :=
  (Ideal.map φ (singularIdeal R A)).radical

/-- A finite-presentation factorization in the local situation.  The two
base-compatibility equations make the displayed factorization an
`R`-algebra factorization without introducing a parallel algebra-map API. -/
structure LocalFactorization
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (s : LocalSituation R A Λ) where
  B : Type u
  [commRingB : CommRing B]
  [algebraRB : Algebra R B]
  AtoB : A →+* B
  BtoΛ : B →+* Λ
  AtoB_base : AtoB.comp (algebraMap R A) = algebraMap R B
  BtoΛ_base : BtoΛ.comp (algebraMap R B) = algebraMap R Λ
  factorization : BtoΛ.comp AtoB = s.map
  finitePresentation : Algebra.FinitePresentation R B

/-- The source's `\mathfrak h_A`, namely the radical of the extended
singular ideal in `Λ`. -/
abbrev localDefect
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (s : LocalSituation R A Λ) : Ideal Λ :=
  localSingularIdeal (R := R) (A := A) (Λ := Λ) s.map

/-- The resolution predicate in Situation 9. -/
def CanBeResolved
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (s : LocalSituation R A Λ) : Prop :=
  ∃ d : LocalFactorization s,
    letI : CommRing d.B := d.commRingB
    letI : Algebra R d.B := d.algebraRB
    localDefect s ≤
        localSingularIdeal d.BtoΛ (R := R) (A := d.B) (Λ := Λ) ∧
      ¬ localSingularIdeal d.BtoΛ (R := R) (A := d.B) (Λ := Λ) ≤ s.q.asIdeal

/-! ## Quotients by the powers of a finite sequence -/

/-- The ideal generated by the eighth powers of the first `n` members of a
finite sequence. -/
def prefixPowerIdeal
    {R : Type u} [CommRing R] {r : ℕ} (π : Fin r → R) (n : ℕ) : Ideal R :=
  Ideal.span {x | ∃ i : Fin r, i.val < n ∧ x = π i ^ 8}

/-- The base quotient by the eighth powers in a finite sequence. -/
abbrev prefixPowerQuotient
    (R : Type u) [CommRing R] {r : ℕ} (π : Fin r → R) (n : ℕ) : Type u :=
  R ⧸ prefixPowerIdeal π n

/-- The corresponding quotient of an `R`-algebra. -/
abbrev prefixPowerAlgebraQuotient
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    {r : ℕ} (π : Fin r → R) (n : ℕ) : Type u :=
  S ⧸ Ideal.map (algebraMap R S) (prefixPowerIdeal π n)

noncomputable instance prefixPowerAlgebraQuotient.algebraQuotient
    {R S : Type u} [CommRing R] [CommRing S] [Algebra R S]
    {r : ℕ} (π : Fin r → R) (n : ℕ) :
    Algebra (prefixPowerQuotient R π n)
      (prefixPowerAlgebraQuotient (R := R) (S := S) π n) :=
  Ideal.Quotient.algebraQuotientOfLEComap Ideal.le_comap_map

/-- The quotient map induced by an `R`-algebra map. -/
def prefixPowerMap
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] {r : ℕ} (π : Fin r → R) (n : ℕ)
    (φ : A →+* Λ)
    (hφ : φ.comp (algebraMap R A) = algebraMap R Λ) :
    prefixPowerAlgebraQuotient (R := R) (S := A) π n →+*
      prefixPowerAlgebraQuotient (R := R) (S := Λ)
        π n := by
  let I := prefixPowerIdeal π n
  let K := Ideal.map (algebraMap R Λ) I
  apply Ideal.quotientMap K φ
  change Ideal.map (algebraMap R A) I ≤ Ideal.comap φ K
  rw [Ideal.map_le_iff_le_comap]
  simpa only [Ideal.comap_comap, hφ] using
    (Ideal.le_comap_map : I ≤ Ideal.comap (algebraMap R Λ) K)

/-- The quotient situation appearing in the lifting lemma, with its map tied
to the canonical quotient map induced by the original situation. -/
def CanBeResolvedModuloPowers
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] {r : ℕ} (s : LocalSituation R A Λ)
    (π : Fin r → R) : Prop :=
  ∃ t : LocalSituation
      (prefixPowerQuotient R π r)
      (prefixPowerAlgebraQuotient (R := R) (S := A) π r)
      (prefixPowerAlgebraQuotient (R := R) (S := Λ) π r),
    t.q.asIdeal =
        Ideal.map (Ideal.Quotient.mk
          (Ideal.map (algebraMap R Λ) (prefixPowerIdeal π r))) s.q.asIdeal ∧
      t.map = prefixPowerMap π r s.map s.map_base ∧ CanBeResolved t

/-- The annihilator equality for one member of a sequence after quotienting by
the preceding eighth powers. -/
def PrefixAnnihilatorEquality
    {R : Type u} [CommRing R] {r : ℕ} (π : Fin r → R) (i : Fin r) : Prop :=
  let Q := prefixPowerQuotient R π i.val
  let x : Q := Ideal.Quotient.mk _ (π i)
  annihilatorOf (R := Q) (M := Q) x =
    annihilatorOf (R := Q) (M := Q) (x ^ 2)

/-- The same annihilator equality in the target quotient. -/
def TargetPrefixAnnihilatorEquality
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    {r : ℕ} (π : Fin r → R) (i : Fin r) : Prop :=
  let Q := prefixPowerAlgebraQuotient (R := R) (S := Λ) π i.val
  let x : Q := Ideal.Quotient.mk _ (algebraMap R Λ (π i))
  annihilatorOf (R := Q) (M := Q) x =
    annihilatorOf (R := Q) (M := Q) (x ^ 2)

/-! ## The lifting lemma -/

/-- Lifting a resolution from the quotient by a finite sequence of eighth
powers. -/
theorem lift_solution
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [IsNoetherianRing R]
    {r : ℕ} (hr : 1 ≤ r) (s : LocalSituation R A Λ)
    (π : Fin r → R)
    (hπq : ∀ i : Fin r, algebraMap R Λ (π i) ∈ s.q.asIdeal)
    (hAnnR : ∀ i : Fin r, PrefixAnnihilatorEquality π i)
    (hAnnΛ : ∀ i : Fin r,
      TargetPrefixAnnihilatorEquality (R := R) (Λ := Λ) π i)
    (hstandard : ∀ i : Fin r, IsStrictlyStandard R A (algebraMap R A (π i)))
    (hquot : CanBeResolvedModuloPowers s π) :
    CanBeResolved s := by
  sorry

/-! ## Localizing at the prime -/

/-- The canonical map from `R_p` to the localization of an `R`-algebra at
the image of `p`. -/
noncomputable def baseLocalizationMap
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
    (p : Ideal R) [p.IsPrime] :
    Localization.AtPrime p →+*
      Localization (p.primeCompl.map (algebraMap R A)) :=
  IsLocalization.map _ (algebraMap R A) p.primeCompl.le_comap_map

/-- The canonical map from `A_p` to `Λ_q` induced by a local situation. -/
noncomputable def localLocalizationMap
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (s : LocalSituation R A Λ) :
      Localization (s.p.primeCompl.map
      (algebraMap R A)) →+* Localization.AtPrime s.q.asIdeal := by
  let p := s.p
  letI : s.q.asIdeal.IsPrime := s.q.2
  letI : p.IsPrime := Ideal.comap_isPrime (algebraMap R Λ) s.q.asIdeal
  apply IsLocalization.map (Q := Localization.AtPrime s.q.asIdeal)
    (R := A) (P := Λ)
    (M := p.primeCompl.map (algebraMap R A))
    (T := s.q.asIdeal.primeCompl) s.map
  intro x hx
  rcases (Submonoid.mem_map).1 hx with ⟨r, hr, rfl⟩
  have hrq : algebraMap R Λ r ∉ s.q.asIdeal := by
    intro hq
    exact hr hq
  have hmap : s.map (algebraMap R A r) = algebraMap R Λ r := by
    simpa [RingHom.comp_apply] using DFunLike.congr_fun s.map_base r
  simpa [hmap] using hrq

/-- The canonical map from `R_p` to `Λ_q`, used to install the local
algebra structure on the target localization. -/
noncomputable def targetLocalizationMap
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    (q : PrimeSpectrum Λ) :
    Localization.AtPrime (q.asIdeal.comap (algebraMap R Λ)) →+*
      Localization.AtPrime q.asIdeal := by
  letI : q.asIdeal.IsPrime := q.2
  letI : (q.asIdeal.comap (algebraMap R Λ)).IsPrime :=
    Ideal.comap_isPrime (algebraMap R Λ) q.asIdeal
  exact Localization.localRingHom _ _ (algebraMap R Λ) rfl

noncomputable instance baseLocalizationAlgebra
    {R A : Type u} [CommRing R] [CommRing A] [Algebra R A]
    (p : Ideal R) [p.IsPrime] :
    Algebra (Localization.AtPrime p)
      (Localization (p.primeCompl.map (algebraMap R A))) :=
  (baseLocalizationMap p).toAlgebra

noncomputable instance targetLocalizationAlgebra
    {R Λ : Type u} [CommRing R] [CommRing Λ] [Algebra R Λ]
    (q : PrimeSpectrum Λ) :
    Algebra (Localization.AtPrime (q.asIdeal.comap (algebraMap R Λ)))
      (Localization.AtPrime q.asIdeal) :=
  (targetLocalizationMap q).toAlgebra

/-- A localized local situation at `p = R ∩ q`. -/
structure LocalizedSituation
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ]
    (s : LocalSituation R A Λ) where
  map : Localization (s.p.primeCompl.map
      (algebraMap R A)) →+* Localization.AtPrime s.q.asIdeal
  map_base :
    map.comp (baseLocalizationMap s.p) =
      targetLocalizationMap s.q
  q : PrimeSpectrum (Localization.AtPrime s.q.asIdeal)
  q_eq_maximal :
    q.asIdeal = IsLocalRing.maximalIdeal (Localization.AtPrime s.q.asIdeal)
  finitePresentation :
    Algebra.FinitePresentation
      (Localization.AtPrime s.p)
      (Localization (s.p.primeCompl.map
        (algebraMap R A)))

/-- The local situation represented by a `LocalizedSituation`. -/
def LocalizedSituation.toLocalSituation
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] {s : LocalSituation R A Λ}
    (t : LocalizedSituation s) :
    LocalSituation
      (Localization.AtPrime s.p)
      (Localization (s.p.primeCompl.map
        (algebraMap R A)))
      (Localization.AtPrime s.q.asIdeal) :=
  { map := t.map
    map_base := t.map_base
    q := t.q
    finitePresentation := t.finitePresentation }

/-- The localized resolution hypothesis in the two delocalization lemmas;
the equality identifies its map with the canonical map of the source. -/
def CanBeResolvedLocally
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] (s : LocalSituation R A Λ) : Prop :=
  ∃ t : LocalizedSituation s,
    t.map = localLocalizationMap s ∧ CanBeResolved t.toLocalSituation

/-! ## Delocalization -/

/-- A weak delocalization conclusion: the extension of the singular ideal
of the new finite-presentation algebra is not contained in `q`. -/
def HasWeakDelocalization
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] (s : LocalSituation R A Λ) : Prop :=
  ∃ d : LocalFactorization s,
    letI : CommRing d.B := d.commRingB
    letI : Algebra R d.B := d.algebraRB
    ¬ Ideal.map d.BtoΛ (singularIdeal R d.B) ≤ s.q.asIdeal

/-- Weak delocalization from a minimal prime of the singular ideal. -/
theorem delocalize_weak
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [IsNoetherianRing R]
    (s : LocalSituation R A Λ)
    (hq : Ideal.IsMinimalPrime (localDefect s) s.q.asIdeal)
    (hloc : CanBeResolvedLocally s) :
    HasWeakDelocalization s := by
  sorry

/-- The height-zero hypothesis used in the final delocalization lemma. -/
def HasZeroDimensionalLocalTarget
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] (s : LocalSituation R A Λ) : Prop :=
  ringKrullDim (Localization.AtPrime s.q.asIdeal) = 0

/-- Delocalization at a zero-dimensional local target. -/
theorem delocalize_height_zero
    {R A Λ : Type u} [CommRing R] [CommRing A] [CommRing Λ]
    [Algebra R A] [Algebra R Λ] [IsNoetherianRing R]
    (s : LocalSituation R A Λ)
    (hq : Ideal.IsMinimalPrime (localDefect s) s.q.asIdeal)
    (hloc : CanBeResolvedLocally s)
    (hdim : HasZeroDimensionalLocalTarget s) :
    CanBeResolved s := by
  sorry

end

end Formalization.Books.Smoothing.Unit09
