import Mathlib.RingTheory.Ideal.IdempotentFG
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.Topology.Connected.Basic
import Formalization.Books.Algebra.Unit17.Spectrum
import Formalization.Books.Algebra.Unit20.Nakayama

/-!
# Commutative Algebra, Chapter 21: Open and closed subsets of spectra

The spectrum, standard opens, zero loci, and the Zariski topology use
Mathlib's canonical `PrimeSpectrum` interfaces.  In particular, Mathlib
already supplies the product-spectrum homeomorphism, the clopen/idempotent
equivalence, and the finitely generated idempotent-ideal criterion.
-/

namespace Formalization.Books.Algebra.Unit21

universe u v

noncomputable section

open Set

/-! ## Idempotent decompositions of spectra -/

/-- An idempotent decomposes the spectrum into the two complementary standard
opens associated to it and to its complement. -/
theorem idempotent_spec_partition
    {R : Type u} [CommRing R] (e : R) (he : IsIdempotentElem e) :
    Disjoint (PrimeSpectrum.basicOpen e : Set (PrimeSpectrum R))
        (PrimeSpectrum.basicOpen (1 - e) : Set (PrimeSpectrum R)) ∧
      (PrimeSpectrum.basicOpen e : Set (PrimeSpectrum R)) ∪
          (PrimeSpectrum.basicOpen (1 - e) : Set (PrimeSpectrum R)) = Set.univ := by
  sorry

/-! ## Products of rings -/

/-- The map on spectra induced by the first projection of a product ring. -/
def productSpectrumMapLeft {R₁ : Type u} {R₂ : Type v}
    [CommRing R₁] [CommRing R₂] :
    PrimeSpectrum R₁ → PrimeSpectrum (R₁ × R₂) :=
  PrimeSpectrum.comap (RingHom.fst R₁ R₂)

/-- The map on spectra induced by the second projection of a product ring. -/
def productSpectrumMapRight {R₁ : Type u} {R₂ : Type v}
    [CommRing R₁] [CommRing R₂] :
    PrimeSpectrum R₂ → PrimeSpectrum (R₁ × R₂) :=
  PrimeSpectrum.comap (RingHom.snd R₁ R₂)

theorem continuous_productSpectrumMapLeft {R₁ : Type u} {R₂ : Type v}
    [CommRing R₁] [CommRing R₂] :
    Continuous (productSpectrumMapLeft (R₁ := R₁) (R₂ := R₂)) := by
  exact PrimeSpectrum.continuous_comap _

theorem continuous_productSpectrumMapRight {R₁ : Type u} {R₂ : Type v}
    [CommRing R₁] [CommRing R₂] :
    Continuous (productSpectrumMapRight (R₁ := R₁) (R₂ := R₂)) := by
  exact PrimeSpectrum.continuous_comap _

/-- The spectrum of a product is homeomorphic to the disjoint union of the
spectra of its factors. -/
noncomputable def productSpectrumHomeomorph {R₁ : Type u} {R₂ : Type v}
    [CommRing R₁] [CommRing R₂] :
    PrimeSpectrum R₁ ⊕ PrimeSpectrum R₂ ≃ₜ PrimeSpectrum (R₁ × R₂) :=
  (PrimeSpectrum.primeSpectrumProdHomeo (R := R₁) (S := R₂)).symm

theorem productSpectrumHomeomorph_inl_apply {R₁ : Type u} {R₂ : Type v}
    [CommRing R₁] [CommRing R₂] (p : PrimeSpectrum R₁) :
    productSpectrumHomeomorph (R₁ := R₁) (R₂ := R₂) (Sum.inl p) =
      productSpectrumMapLeft (R₁ := R₁) (R₂ := R₂) p := by
  sorry

theorem productSpectrumHomeomorph_inr_apply {R₁ : Type u} {R₂ : Type v}
    [CommRing R₁] [CommRing R₂] (p : PrimeSpectrum R₂) :
    productSpectrumHomeomorph (R₁ := R₁) (R₂ := R₂) (Sum.inr p) =
      productSpectrumMapRight (R₁ := R₁) (R₂ := R₂) p := by
  sorry

/-! ## Clopen subsets and idempotents -/

/-- Every clopen subset of a spectrum is a unique standard open defined by an
idempotent. -/
theorem existsUnique_idempotent_basicOpen_eq_of_isClopen
    {R : Type u} [CommRing R] {U : Set (PrimeSpectrum R)} (hU : IsClopen U) :
    ∃! e : R, IsIdempotentElem e ∧
      U = (PrimeSpectrum.basicOpen e : Set (PrimeSpectrum R)) := by
  exact PrimeSpectrum.existsUnique_idempotent_basicOpen_eq_of_isClopen hU

/-- The source's one-to-one correspondence between idempotents and clopen
subsets is Mathlib's canonical order equivalence. -/
noncomputable def idempotentClopenEquiv {R : Type u} [CommRing R] :
    {e : R // IsIdempotentElem e} ≃o
      TopologicalSpace.Clopens (PrimeSpectrum R) :=
  PrimeSpectrum.isIdempotentElemEquivClopens

/-! ## Connected spectra -/

/-- A nonzero ring has connected spectrum exactly when it has no nontrivial
idempotents. -/
theorem primeSpectrum_connected_iff_no_nontrivial_idempotents
    (R : Type u) [CommRing R] [Nontrivial R] :
    ConnectedSpace (PrimeSpectrum R) ↔
      ∀ e : R, IsIdempotentElem e → e = 0 ∨ e = 1 := by
  sorry

/-! ## Finitely generated idempotent ideals -/

/-- A finitely generated ideal satisfying `I = I²` is generated by an
idempotent; its quotient, complementary localization, and vanishing locus
have the forms stated in the source. -/
theorem fg_idempotent_ideal_components
    {R : Type u} [CommRing R] (I : Ideal R) (hI_fg : I.FG)
    (hI_sq : I = I ^ 2) :
    ∃ e : R, IsIdempotentElem e ∧
      I = Ideal.span ({e} : Set R) ∧
      Nonempty ((R ⧸ I) ≃+* Localization.Away (1 - e)) ∧
      IsClopen (PrimeSpectrum.zeroLocus (I : Set R)) := by
  sorry

/- The source announces a later reproof of the clopen/idempotent statement
   after the glueing-of-functions lemma.  The canonical equivalence above is
   the single chapter interface, so no duplicate declaration is needed here. -/

end

end Formalization.Books.Algebra.Unit21
