import Formalization.Books.Algebra.Unit144.LocalStructureEtaleRingMaps
import Mathlib.RingTheory.Ideal.Quotient.Basic
import Mathlib.RingTheory.LocalRing.ResidueField.Basic
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.RingHom.FaithfullyFlat

/-!
# Commutative Algebra, Chapter 146: Local homomorphisms

This file records the two source lemmas in the section.  Local rings,
local homomorphisms, residue fields, étale maps, localizations, and
faithfully flat maps use Mathlib's canonical interfaces.
-/

namespace Formalization.Books.Algebra.Unit146

open Set

noncomputable section

universe u v

/-! ## Localization witnesses -/

/-- A witness that `f` presents its target as a localization at a prime of
an étale algebra over its source. -/
structure EtaleLocalizationWitness
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) where
  T : Type u
  [commRingT : CommRing T]
  g : R →+* T
  p : Ideal T
  [prime : p.IsPrime]
  q : T →+* S
  etale : RingHom.Etale g
  comp : q.comp g = f
  localization :
    letI : Algebra T S := q.toAlgebra
    IsLocalization.AtPrime S p

/-- The source hypothesis that the target is a localization of an étale
extension of the source. -/
def IsLocalizationOfEtale
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) : Prop :=
  Nonempty (EtaleLocalizationWitness f)

/-! ## Quotients by powers of one element -/

/-- The quotient map induced by `f` from `R/t^nR` to `S/t^nS`.  The target
ideal is written as the ideal map, which is the canonical extension of the
principal ideal generated by `t^n`. -/
def powerQuotientMap
    {R S : Type u} [CommRing R] [CommRing S]
    (f : R →+* S) (t : R) (n : ℕ) :
    R ⧸ Ideal.span ({t ^ n} : Set R) →+*
      S ⧸ Ideal.map f (Ideal.span ({t ^ n} : Set R)) :=
  Ideal.Quotient.lift (Ideal.span ({t ^ n} : Set R))
    ((Ideal.Quotient.mk (Ideal.map f (Ideal.span ({t ^ n} : Set R)))).comp f)
    (by
      intro a ha
      change Ideal.Quotient.mk (Ideal.map f (Ideal.span ({t ^ n} : Set R))) (f a) = 0
      rw [Ideal.Quotient.eq_zero_iff_mem]
      exact Ideal.mem_map_of_mem f ha)

/-! ## The two source lemmas -/

/-- Lindel's lemma: an étale local map with identical residue fields is an
isomorphism modulo every positive power of one element of the maximal ideal. -/
theorem lindel
    {R S : Type u} [CommRing R] [CommRing S]
    [IsLocalRing R] [IsLocalRing S]
    (f : R →+* S) [IsLocalHom f]
    (hlocalization : IsLocalizationOfEtale f)
    (hresidue : Function.Bijective (IsLocalRing.ResidueField.map f)) :
    ∃ t : R, t ∈ IsLocalRing.maximalIdeal R ∧
      ∀ n : ℕ, 1 ≤ n →
        ∃ e :
            (R ⧸ Ideal.span ({t ^ n} : Set R)) ≃+*
              (S ⧸ Ideal.map f (Ideal.span ({t ^ n} : Set R))),
          e.toRingHom = powerQuotientMap f t n := by
  sorry

/-- The finite faithfully flat refinement of a localized étale map. -/
structure FiniteFlatLocalFactorData
    {R S : Type u} [CommRing R] [CommRing S] (f : R →+* S) where
  S' : Type v
  [commRingS' : CommRing S']
  [algebraRS' : Algebra R S']
  finite : RingHom.Finite (algebraMap R S')
  finitePresentation : RingHom.FinitePresentation (algebraMap R S')
  faithfullyFlat : RingHom.FaithfullyFlat (algebraMap R S')
  localFactor :
    ∀ m' : {m : Ideal S' // m.IsMaximal},
      letI : m'.1.IsMaximal := m'.2
      ∃ φ : S →+* Localization.AtPrime m'.1,
        φ.comp f =
          (algebraMap S' (Localization.AtPrime m'.1)).comp
            (algebraMap R S')

/-- If a local map is a localization of an étale extension, it factors locally
through a finite, finitely presented, faithfully flat extension of the base. -/
theorem etale_under_finite_flat
    {R S : Type u} [CommRing R] [CommRing S]
    [IsLocalRing R] [IsLocalRing S]
    (f : R →+* S) [IsLocalHom f]
    (hlocalization : IsLocalizationOfEtale f) :
    Nonempty (FiniteFlatLocalFactorData f) := by
  sorry

end

end Formalization.Books.Algebra.Unit146
