import Mathlib.Algebra.Field.Rat
import Mathlib.Algebra.MvPolynomial.Equiv
import Mathlib.Algebra.Module.LocalizedModule.Submodule
import Mathlib.Algebra.Regular.Basic
import Mathlib.LinearAlgebra.SymmetricAlgebra.Basis
import Mathlib.RingTheory.Ideal.Prime
import Mathlib.RingTheory.Localization.Algebra
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Noetherian.Basic
import Mathlib.RingTheory.PicardGroup
import Mathlib.RingTheory.Polynomial.Basic

/-!
# Examples, Chapter 32: A noninvertible ideal invertible in stalks

This file records the constructions and theorem interfaces in the source
section.  The mathematical proofs belong to the proof stage.
-/

noncomputable section

namespace Formalization.Books.Examples.Unit32

/-! ## The fractional module over `ℚ[x]` -/

/-- The polynomial ring `R = ℚ[x]` used in the example. -/
abbrev exampleBaseRing := Polynomial ℚ

/-- The fraction ring containing the displayed fractional generators. -/
abbrev exampleFractionRing := FractionRing exampleBaseRing

/-- The denominator `x - n` in `ℚ[x]`. -/
def exampleDenominator (n : ℕ) : exampleBaseRing :=
  Polynomial.X - Polynomial.C (n : ℚ)

/-- The element `1 / (x - n)` in the fraction ring of `ℚ[x]`. -/
def exampleFractionalGenerator (n : ℕ) : exampleFractionRing :=
  (algebraMap exampleBaseRing exampleFractionRing (exampleDenominator n))⁻¹

/-- The `ℚ[x]`-submodule `M = ∑ₙ (1 / (x - n)) R` in the fraction ring. -/
def exampleModule : Submodule exampleBaseRing exampleFractionRing :=
  Submodule.span exampleBaseRing (Set.range exampleFractionalGenerator)

abbrev ExampleModule := (exampleModule : Type)

/-- The module `M` is not finitely generated over `ℚ[x]`. -/
theorem exampleModule_not_finite :
    ¬ Module.Finite exampleBaseRing ExampleModule := by
  sorry

/-- Every prime localization of `M` is a free rank-one module. -/
theorem exampleModule_localized_equiv
    (p : Ideal exampleBaseRing) [p.IsPrime] :
    Nonempty
      (LocalizedModule p.primeCompl ExampleModule ≃ₗ[Localization p.primeCompl]
        Localization p.primeCompl) := by
  sorry

/-! ## The symmetric algebra and its module-generated ideal -/

/-- The ring `A = SymmetricAlgebra_R(M)`. -/
abbrev exampleAlgebra := SymmetricAlgebra exampleBaseRing ExampleModule

/-- The ideal generated by the image of `M` in its symmetric algebra.

The source writes this ideal as `M A` and as the direct sum of the positive
graded pieces.  `Ideal.span` of the canonical map is the ideal-level form of
that same construction available in Mathlib's ungraded symmetric-algebra API.
-/
def exampleIdeal : Ideal exampleAlgebra :=
  Ideal.span (Set.range (SymmetricAlgebra.ι exampleBaseRing ExampleModule))

/-- The ideal `I` is nonzero. -/
theorem exampleIdeal_ne_bot : exampleIdeal ≠ ⊥ := by
  sorry

/-- The ideal `I` is not finitely generated as an ideal of `A`. -/
theorem exampleIdeal_not_finitely_generated : ¬ exampleIdeal.FG := by
  sorry

/-- The ideal `I` is not invertible as an `A`-module. -/
theorem exampleIdeal_not_invertible :
    ¬ Module.Invertible exampleAlgebra exampleIdeal := by
  sorry

/-! ## The local computations -/

/-- The localization of `R` at a prime `p`. -/
abbrev exampleBaseRingAtPrime (p : Ideal exampleBaseRing) [p.IsPrime] :=
  Localization p.primeCompl

/-- The localization of `M` at the same prime. -/
abbrev exampleModuleAtPrime (p : Ideal exampleBaseRing) [p.IsPrime] :=
  LocalizedModule p.primeCompl ExampleModule

/-- The localization `Aₚ` obtained by inverting the image of `R \ p` in `A`. -/
abbrev exampleAlgebraAtBasePrime (p : Ideal exampleBaseRing) [p.IsPrime] :=
  Localization (Algebra.algebraMapSubmonoid exampleAlgebra p.primeCompl)

/-- The localization `Iₚ` of `I` in `Aₚ`. -/
def exampleIdealAtBasePrime
    (p : Ideal exampleBaseRing) [p.IsPrime] :
    Ideal (exampleAlgebraAtBasePrime p) :=
  exampleIdeal.map (algebraMap exampleAlgebra (exampleAlgebraAtBasePrime p))

/-- The symmetric-algebra identification after localizing at `p`. -/
theorem exampleAlgebraAtBasePrime_equiv_symmetricAlgebra
    (p : Ideal exampleBaseRing) [p.IsPrime] :
    Nonempty
      (exampleAlgebraAtBasePrime p ≃ₐ[exampleBaseRingAtPrime p]
        SymmetricAlgebra (exampleBaseRingAtPrime p) (exampleModuleAtPrime p)) := by
  sorry

/-- The one-variable symmetric algebra is a polynomial ring. -/
noncomputable def symmetricAlgebraSelfPolynomialEquiv
    (S : Type*) [CommSemiring S] :
    SymmetricAlgebra S S ≃ₐ[S] Polynomial S :=
  (SymmetricAlgebra.equivMvPolynomial (Module.Basis.singleton Unit S)).trans
    (MvPolynomial.uniqueAlgEquiv S Unit)

/-- The local symmetric algebra is therefore identified with `Rₚ[T]`. -/
theorem exampleAlgebraAtBasePrime_equiv_polynomial
    (p : Ideal exampleBaseRing) [p.IsPrime] :
    Nonempty
      (exampleAlgebraAtBasePrime p ≃ₐ[exampleBaseRingAtPrime p]
        Polynomial (exampleBaseRingAtPrime p)) := by
  sorry

/-- At a base prime, `Iₚ` is generated by a regular element `T`. -/
theorem exampleIdealAtBasePrime_isPrincipal_regular
    (p : Ideal exampleBaseRing) [p.IsPrime] :
    ∃ T : exampleAlgebraAtBasePrime p,
      exampleIdealAtBasePrime p = Ideal.span {T} ∧ IsRegular T := by
  sorry

/-- The localization of `I` at a prime ideal `q` of `A`. -/
def exampleIdealAtPrime (q : Ideal exampleAlgebra) [q.IsPrime] :
    Ideal (Localization q.primeCompl) :=
  exampleIdeal.map (algebraMap exampleAlgebra (Localization q.primeCompl))

/-- Every prime stalk of `I` is a principal ideal. -/
theorem exampleIdealAtPrime_isPrincipal
    (q : Ideal exampleAlgebra) [q.IsPrime] :
    (exampleIdealAtPrime q).IsPrincipal := by
  sorry

/-! ## The ring-theoretic properties of the example -/

/-- The ring `A` is a domain. -/
theorem exampleAlgebra_isDomain : IsDomain exampleAlgebra := by
  sorry

/-- Every prime stalk of `I` is generated by a nonzero element. -/
theorem exampleIdealAtPrime_isPrincipal_nonzero
    (q : Ideal exampleAlgebra) [q.IsPrime] :
    ∃ f : Localization q.primeCompl,
      exampleIdealAtPrime q = Ideal.span {f} ∧ f ≠ 0 := by
  sorry

/-- The ring `A` is not Noetherian. -/
theorem exampleAlgebra_not_noetherian : ¬ IsNoetherianRing exampleAlgebra := by
  sorry

/-- Every prime localization of `A` is Noetherian. -/
theorem exampleAlgebra_prime_localizations_noetherian :
    ∀ (q : Ideal exampleAlgebra) (hq : q.IsPrime),
      letI : q.IsPrime := hq
      IsNoetherianRing (Localization q.primeCompl) := by
  sorry

/-! ## A source-facing predicate and the final example -/

/-- An ideal is principal after localization at every prime.

This name records the prime-local condition without using the source's
potentially misleading shorthand “locally principal”.
-/
def PrincipalAtEveryPrime {A : Type*} [CommRing A] (I : Ideal A) : Prop :=
  ∀ (q : Ideal A) (hq : q.IsPrime),
    letI : q.IsPrime := hq
    (I.map (algebraMap A (Localization q.primeCompl))).IsPrincipal

/-- The constructed ideal satisfies the source's all-primes principal condition. -/
theorem exampleIdeal_principalAtEveryPrime :
    PrincipalAtEveryPrime exampleIdeal := by
  intro q hq
  exact @exampleIdealAtPrime_isPrincipal q hq

/-- There is a domain with a nonzero ideal principal in every prime localization
but not invertible as a module. -/
theorem exists_domain_nonzeroIdeal_principalAtEveryPrime_not_invertible :
    ∃ (A : Type) (_ : CommRing A) (_ : IsDomain A) (I : Ideal A),
      I ≠ ⊥ ∧ PrincipalAtEveryPrime I ∧ ¬ Module.Invertible A I := by
  sorry

end Formalization.Books.Examples.Unit32
