import Mathlib.Algebra.Colimit.Ring
import Mathlib.Algebra.Category.Grp.Basic
import Mathlib.Algebra.DirectSum.Module
import Mathlib.Algebra.Module.LinearMap.End
import Mathlib.Algebra.Module.Projective
import Mathlib.Data.ZMod.Basic
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.RingTheory.Finiteness.Projective
import Mathlib.RingTheory.Ideal.Basic
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.Basic
import Mathlib.RingTheory.PicardGroup

/-!
# Examples, Chapter 34: A projective module which is not locally free

This file records the definitions and theorem interfaces in the source
section.  The mathematical proofs belong to the proof stage.
-/

noncomputable section

open scoped DirectSum
open CategoryTheory

namespace Formalization.Books.Examples.Unit34

universe u

/-! ## Local freeness and the idempotent-generated ideal argument -/

/-- A module is locally free on a basic-open cover of `Spec R`.

Mathlib's `Module.freeLocus` records freeness at prime stalks.  The source
uses the stronger open-cover notion, so this definition keeps the basic-open
cover explicit.
-/
def IsLocallyFreeModule (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] : Prop :=
  ∃ s : Set R, Ideal.span s = ⊤ ∧
    ∀ f ∈ s, Module.Free (Localization.Away f) (LocalizedModule.Away f M)

/-- A finite locally free module, with no fixed rank. -/
def IsFiniteLocallyFreeModule (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] : Prop :=
  Module.Finite R M ∧ IsLocallyFreeModule R M

/-- Local freeness with all local free parts of rank at most `N`. -/
def IsLocallyFreeModuleOfRankAtMost
    (R M : Type*) [CommRing R] [AddCommGroup M] [Module R M] (N : ℕ) : Prop :=
  ∃ s : Set R, Ideal.span s = ⊤ ∧
    ∀ f ∈ s, ∃ n : ℕ, n ≤ N ∧
      Nonempty (Module.Basis (Fin n) (Localization.Away f)
        (LocalizedModule.Away f M))

/-- The assertion that `M` is generated by at most `N` elements. -/
def HasGeneratorBound (R M : Type*) [Semiring R] [AddCommMonoid M] [Module R M]
    (N : ℕ) : Prop :=
  ∃ x : Fin N → M, Submodule.span R (Set.range x) = ⊤

/-! The normalized chain used in the proof of the first lemma. -/

/-- A countable increasing family of idempotents, written in absorbing form. -/
structure IdempotentChain (R : Type*) [CommRing R] where
  elem : ℕ → R
  idempotent : ∀ n, IsIdempotentElem (elem n)
  absorb : ∀ n, elem n * elem (n + 1) = elem n

/-- An ideal generated by a countable family of idempotents. -/
def IsCountablyIdempotentGenerated {R : Type*} [CommRing R] (I : Ideal R) : Prop :=
  ∃ e : ℕ → R, (∀ n, IsIdempotentElem (e n)) ∧ I = Ideal.span (Set.range e)

namespace IdempotentChain

/-- The ideal generated by all members of an idempotent chain. -/
def ideal {R : Type*} [CommRing R] (c : IdempotentChain R) : Ideal R :=
  Ideal.span (Set.range c.elem)

/-- The principal ideal generated by the `n`-th idempotent. -/
def principalIdeal {R : Type*} [CommRing R] (c : IdempotentChain R) (n : ℕ) : Ideal R :=
  Ideal.span {c.elem n}

/-- The `eM` appearing in the proof: the image of multiplication by an idempotent.

For an idempotent this fixed-point presentation is equal to the linear-map range,
and makes the transition map multiplication by `eₙ` definitional.
-/
def image {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (c : IdempotentChain R) (n : ℕ) : Submodule R M :=
  { carrier := {m | c.elem n • m = m}
    zero_mem' := by simp
    add_mem' := by
      intro x y hx hy
      change c.elem n • (x + y) = x + y
      rw [smul_add, hx, hy]
    smul_mem' := by
      intro r x hx
      change c.elem n • (r • x) = r • x
      simpa [smul_smul, mul_comm] using congrArg (fun z => r • z) hx }

/-- Multiplication by `eₙ` gives the transition `eₙ₊₁M → eₙM`. -/
def transition {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (c : IdempotentChain R) (n : ℕ) :
    image (M := M) c n.succ →ₗ[R] image (M := M) c n :=
  { toFun := fun x =>
      ⟨c.elem n • (x : M), by
        change c.elem n • (c.elem n • (x : M)) = c.elem n • (x : M)
        rw [smul_smul, (c.idempotent n).eq]⟩
    map_add' := by
      intro x y
      apply Subtype.ext
      simp [smul_add]
    map_smul' := by
      intro r x
      apply Subtype.ext
      simp [smul_smul, mul_comm] }

/-- The inverse limit of the modules `eₙM` with the displayed transitions. -/
def inverseLimitSubmodule {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (c : IdempotentChain R) :
    Submodule R (∀ n, image (M := M) c n) :=
  { carrier := {x | ∀ n, transition c n (x (n + 1)) = x n}
    zero_mem' := by
      intro n
      simp
    add_mem' := by
      intro x y hx hy n
      change transition c n (x (n + 1) + y (n + 1)) = x n + y n
      rw [(transition c n).map_add, hx n, hy n]
    smul_mem' := by
      intro r x hx n
      change transition c n (r • x (n + 1)) = r • x n
      rw [(transition c n).map_smul, hx n] }

/-- The carrier of the inverse limit of the `eₙM`. -/
abbrev inverseLimit {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (c : IdempotentChain R) : Type _ := inverseLimitSubmodule (M := M) c

theorem transition_surjective {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (c : IdempotentChain R) (n : ℕ) :
    Function.Surjective (transition (M := M) c n) := by
  intro x
  let y : image c (n + 1) :=
    ⟨c.elem (n + 1) • (x : M), by
      change c.elem (n + 1) • (c.elem (n + 1) • (x : M)) = c.elem (n + 1) • (x : M)
      rw [smul_smul, (c.idempotent (n + 1)).eq]⟩
  refine ⟨y, ?_⟩
  apply Subtype.ext
  change c.elem n • (c.elem (n + 1) • (x : M)) = (x : M)
  rw [smul_smul, c.absorb n, x.property]

theorem ideal_eq_iSup_principalIdeals {R : Type*} [CommRing R]
    (c : IdempotentChain R) :
    c.ideal = ⨆ n, c.principalIdeal n := by
  sorry

end IdempotentChain

/-- The normalized nested idempotent family obtained from countable generators. -/
theorem exists_idempotentChain_of_countablyIdempotentGenerated
    {R : Type*} [CommRing R] (I : Ideal R)
    (hI : IsCountablyIdempotentGenerated I) :
    ∃ c : IdempotentChain R, c.ideal = I := by
  sorry

/-- The displayed identification `Hom_R(I, M) ≅ limₙ eₙM`. -/
theorem linearEquiv_idealHom_inverseLimit
    {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
    (c : IdempotentChain R) :
    Nonempty ((c.ideal →ₗ[R] M) ≃ₗ[R] IdempotentChain.inverseLimit (M := M) c) := by
  sorry

/-- A countable idempotent-generated ideal is projective. -/
theorem ideal_projective_of_countablyIdempotentGenerated
    {R : Type*} [CommRing R] (I : Ideal R)
    (hI : IsCountablyIdempotentGenerated I) :
    Module.Projective R I := by
  sorry

/-- A locally free submodule of an `N`-generated finite module is finite locally free,
with local free ranks bounded by `N`. -/
theorem locallyFreeSubmodule_of_finite_of_generatorBound
    {R Q : Type*} [CommRing R] [AddCommGroup Q] [Module R Q]
    [Module.Finite R Q] (P : Submodule R Q) (N : ℕ)
    (hQ : HasGeneratorBound R Q N)
    (hP : IsLocallyFreeModule R P) :
    IsFiniteLocallyFreeModule R P ∧ IsLocallyFreeModuleOfRankAtMost R P N := by
  sorry

/-! ## The product of countably many copies of `𝔽₂` -/

/-- The ring `R = ∏ₙ 𝔽₂` in the first example. -/
abbrev ExampleProductRing := ℕ → ZMod 2

/-- The idempotent whose first `n` coordinates are `1` and the rest are `0`. -/
def exampleProductIdempotent (n : ℕ) : ExampleProductRing :=
  fun k => if k < n then 1 else 0

/-- The ideal generated by the displayed countable family of idempotents. -/
def exampleProductIdeal : Ideal ExampleProductRing :=
  Ideal.span (Set.range exampleProductIdempotent)

theorem exampleProductIdempotent_isIdempotent (n : ℕ) :
    IsIdempotentElem (exampleProductIdempotent n) := by
  sorry

theorem exampleProductIdeal_isCountablyIdempotentGenerated :
    IsCountablyIdempotentGenerated exampleProductIdeal := by
  refine ⟨exampleProductIdempotent, ?_, rfl⟩
  exact exampleProductIdempotent_isIdempotent

/-- The explicit ideal is not finitely generated. -/
theorem exampleProductIdeal_not_finite :
    ¬ Module.Finite ExampleProductRing exampleProductIdeal := by
  sorry

/-- The explicit ideal is projective. -/
theorem exampleProductIdeal_projective :
    Module.Projective ExampleProductRing exampleProductIdeal :=
  ideal_projective_of_countablyIdempotentGenerated exampleProductIdeal
    exampleProductIdeal_isCountablyIdempotentGenerated

/-- The explicit ideal is not locally free in the open-cover sense. -/
theorem ideal_not_locallyFree_of_not_finite
    {R : Type*} [CommRing R] (I : Ideal R)
    (hI : ¬ Module.Finite R I) :
    ¬ IsLocallyFreeModule R I := by
  sorry

theorem exampleProductIdeal_not_locallyFree :
    ¬ IsLocallyFreeModule ExampleProductRing exampleProductIdeal :=
  ideal_not_locallyFree_of_not_finite exampleProductIdeal exampleProductIdeal_not_finite

/-- The first example gives a projective ideal which is not locally free. -/
theorem exists_projective_ideal_not_locallyFree :
    ∃ (R : Type*) (_ : CommRing R) (I : Ideal R),
      Module.Projective R I ∧ ¬ IsLocallyFreeModule R I := by
  sorry

/-! ## The finite dual in the first example -/

/-- The dual of the explicit ideal. -/
abbrev exampleProductIdealDual := Module.Dual ExampleProductRing exampleProductIdeal

/-- The dual of the explicit ideal is isomorphic to the base ring. -/
theorem exampleProductIdeal_dual_equiv :
    Nonempty (exampleProductIdealDual ≃ₗ[ExampleProductRing] ExampleProductRing) := by
  sorry

/-- In particular, the dual is finite free. -/
theorem exampleProductIdeal_dual_finite_free :
    Module.Finite ExampleProductRing exampleProductIdealDual ∧
      Module.Free ExampleProductRing exampleProductIdealDual := by
  sorry

/-! ## The Chow-group obstruction -/

/-- A quadratic extension in the sense used by the source's degree-two points. -/
def IsQuadraticExtension (K L : Type*) [Field K] [Field L] [Algebra K L]
    [FiniteDimensional K L] : Prop :=
  Module.finrank K L = 2

/-- The part of a Chow group argument that is available without a Mathlib Chow-group API.

`pointClass P` has degree one, while every boundary class has even degree.  This
is the exact obstruction used in the source proof.
-/
structure QuadraticBoundaryChowData where
  point : Type u
  chowZero : Type u
  chowZeroAddCommGroup : AddCommGroup chowZero
  pointClass : point → chowZero
  degree : chowZero →+ ℤ
  distinguished : point
  boundary : point → Prop
  boundary_degree_even : ∀ z, boundary z → Even (degree (pointClass z))
  distinguished_degree_one : degree (pointClass distinguished) = 1

/-- The canonical zero in the Chow-group interface. -/
def QuadraticBoundaryChowData.zero (D : QuadraticBoundaryChowData) : D.chowZero :=
  letI : AddCommGroup D.chowZero := D.chowZeroAddCommGroup
  0

/-- A degree-one point class cannot vanish when all boundary classes have even degree. -/
theorem QuadraticBoundaryChowData.distinguished_class_ne_zero
    (D : QuadraticBoundaryChowData) :
    D.pointClass D.distinguished ≠ D.zero := by
  sorry

/-- The source's `CH₀` product lemma, expressed through its degree/boundary interface. -/
theorem chow_group_product_rational_point_ne_zero
    (D : QuadraticBoundaryChowData) :
    D.pointClass D.distinguished ≠ D.zero :=
  QuadraticBoundaryChowData.distinguished_class_ne_zero D

/-! ## The second construction -/

/-- A countable commutative ring bundled with its countability witness. -/
structure CountableCommRing where
  carrier : Type*
  commRing : CommRing carrier
  countable : Countable carrier

namespace CountableCommRing

instance (D : CountableCommRing) : CommRing D.carrier := D.commRing

end CountableCommRing

/-- A countable direct system of commutative rings, with its colimit maps. -/
structure DirectedCommRingSequence (B : ℕ → Type*) [∀ n, CommRing (B n)] where
  map : ∀ i j, i ≤ j → B i →+* B j
  map_self : ∀ i x, map i i le_rfl x = x
  map_comp : ∀ i j k (hij : i ≤ j) (hjk : j ≤ k) (x : B i),
    map j k hjk (map i j hij x) = map i k (hij.trans hjk) x

namespace DirectedCommRingSequence

variable {B : ℕ → Type*} [∀ n, CommRing (B n)]

instance (D : DirectedCommRingSequence B) :
    DirectedSystem B (fun i j h => D.map i j h) where
  map_self := D.map_self
  map_map := by
    intro k j i hij hjk x
    exact D.map_comp i j k hij hjk x

/-- The colimit ring `B∞ = colimₙ Bₙ`. -/
noncomputable abbrev colimit (D : DirectedCommRingSequence B) : Type _ :=
  Ring.DirectLimit B (fun i j h => D.map i j h)

/-- The canonical map from `Bₙ` to `B∞`. -/
noncomputable def colimitMap (D : DirectedCommRingSequence B) (n : ℕ) :
    B n →+* D.colimit :=
  Ring.DirectLimit.of B (fun i j h => D.map i j h) n

theorem colimitMap_compatible (D : DirectedCommRingSequence B)
    (i j : ℕ) (hij : i ≤ j) (x : B i) :
    D.colimitMap j (D.map i j hij x) = D.colimitMap i x := by
  sorry

end DirectedCommRingSequence

/-- A family of modules over a ring, each carrying the canonical rank-one
`Module.Invertible` interface. -/
structure CountableRankOneModuleFamily where
  base : CommRingCat.{u}
  base_countable : Countable base
  L : ℕ → Type u
  addCommGroup : ∀ i, AddCommGroup (L i)
  module : ∀ i, Module base (L i)
  invertible : ∀ i, Module.Invertible base (L i)

namespace CountableRankOneModuleFamily

instance addCommGroup_inst (D : CountableRankOneModuleFamily) (i : ℕ) :
    AddCommGroup (D.L i) := D.addCommGroup i

instance module_inst (D : CountableRankOneModuleFamily) (i : ℕ) :
    Module D.base (D.L i) := D.module i

instance invertible_inst (D : CountableRankOneModuleFamily) (i : ℕ) :
    Module.Invertible D.base (D.L i) := D.invertible i

/-- The direct sum `M = ⨁ᵢ Lᵢ`. -/
abbrev directSum (D : CountableRankOneModuleFamily) : Type _ := ⨁ i, D.L i

/-- The direct sum is projective because every summand is invertible. -/
theorem directSum_projective (D : CountableRankOneModuleFamily) :
    Module.Projective D.base D.directSum := inferInstance

/-- Local freeness of the direct sum in the source's open-cover sense. -/
def isLocallyFree (D : CountableRankOneModuleFamily) : Prop :=
  IsLocallyFreeModule D.base D.directSum

end CountableRankOneModuleFamily

/-! An additive universal-property interface for the varying-ring colimits. -/

/-- A cocone with the universal property of a directed colimit in abelian groups. -/
structure AdditiveDirectedColimit (ι : Type*) [Preorder ι]
    (X : ι → AddCommGrpCat.{u})
    (f : ∀ i j, (i ≤ j) → (X i ⟶ X j)) (L : AddCommGrpCat.{u}) where
  cocone : ∀ i, X i ⟶ L
  cocone_naturality : ∀ i j (hij : i ≤ j), (f i j hij) ≫ cocone j = cocone i
  desc : ∀ (Y : AddCommGrpCat.{u}) (g : ∀ i, X i ⟶ Y),
    (∀ i j (hij : i ≤ j), (f i j hij) ≫ g j = g i) → (L ⟶ Y)
  fac : ∀ (Y : AddCommGrpCat.{u}) (g : ∀ i, X i ⟶ Y)
    (hg : ∀ i j (hij : i ≤ j), (f i j hij) ≫ g j = g i) (i : ι),
    cocone i ≫ desc Y g hg = g i
  uniq : ∀ (Y : AddCommGrpCat.{u}) (g : ∀ i, X i ⟶ Y)
    (hg : ∀ i j (hij : i ≤ j), (f i j hij) ≫ g j = g i)
    (d : L ⟶ Y), (∀ i, cocone i ≫ d = g i) → d = desc Y g hg

/-- The indices at which the `i`-th stage module exists. -/
abbrev CurveStageIndex (i : ℕ) := {n : ℕ // i ≤ n}

/-- The stage data used in the second construction.

The stage rings and rank-one modules are supplied as the tensor-product
stages `Bₙ` and `Lₙ,ᵢ`; the colimit maps are bundled separately because the
varying scalar rings make the generic module-colimit API inapplicable without
additional base-change data.
-/
structure CurveProductTower where
  baseField : Type u
  [baseField_isField : Field baseField]
  A : ℕ → CommRingCat.{u}
  A_algebra : ∀ n, Algebra baseField (A n)
  A_countable : ∀ n, Countable (A n)
  L : ℕ → Type u
  L_addCommGroup : ∀ n, AddCommGroup (L n)
  L_module : ∀ n, Module (A n) (L n)
  L_invertible : ∀ n, Module.Invertible (A n) (L n)
  B : ℕ → CommRingCat.{u}
  B_algebra : ∀ n, Algebra baseField (B n)
  B_countable : ∀ n, Countable (B n)
  B_map : ∀ i j, i ≤ j → (B i) →+* (B j)
  B_map_self : ∀ i x, B_map i i le_rfl x = x
  B_map_comp : ∀ i j k (hij : i ≤ j) (hjk : j ≤ k) (x : B i),
    B_map j k hjk (B_map i j hij x) = B_map i k (hij.trans hjk) x
  B_infinity_countable : Countable
    (Ring.DirectLimit (fun n => B n) (fun i j h => B_map i j h))
  L_stage : ∀ _n _i, AddCommGrpCat.{u}
  L_stage_module : ∀ n i (_h : i ≤ n),
    @Module (B n) (L_stage n i) (inferInstance : Semiring (B n))
      (inferInstance : AddCommMonoid (L_stage n i))
  L_stage_invertible : ∀ n i (h : i ≤ n),
    @Module.Invertible (B n) (L_stage n i) (inferInstance : CommSemiring (B n))
      (inferInstance : AddCommMonoid (L_stage n i)) (L_stage_module n i h)
  L_stage_map : ∀ n m (_h : n ≤ m) i (_hi : i ≤ n),
    L_stage n i ⟶ L_stage m i
  L_stage_map_self : ∀ n i (hi : i ≤ n),
    L_stage_map n n le_rfl i hi = 𝟙 (L_stage n i)
  L_stage_map_comp : ∀ n m k (hnm : n ≤ m) (hmk : m ≤ k) i (hi : i ≤ n),
    L_stage_map n m hnm i hi ≫ L_stage_map m k hmk i (hi.trans hnm) =
      L_stage_map n k (hnm.trans hmk) i hi
  L_infinity : ℕ → AddCommGrpCat.{u}
  L_infinity_module : ∀ i, Module
    (Ring.DirectLimit (fun n => B n) (fun i j h => B_map i j h)) (L_infinity i)
  L_infinity_invertible : ∀ i, Module.Invertible
    (Ring.DirectLimit (fun n => B n) (fun i j h => B_map i j h)) (L_infinity i)
  L_infinity_is_colimit : ∀ i, AdditiveDirectedColimit (CurveStageIndex i)
    (fun n : CurveStageIndex i => L_stage n.1 i)
    (fun n m h => L_stage_map n.1 m.1 h i n.2)
    (L_infinity i)

namespace CurveProductTower

/-- The directed ring system formed by the rings `Bₙ`. -/
noncomputable def ringSequence (T : CurveProductTower) :
    DirectedCommRingSequence (fun n => T.B n) where
  map := T.B_map
  map_self := T.B_map_self
  map_comp := by
    intro i j k hij hjk x
    exact T.B_map_comp i j k hij hjk x

/-- The ring `B∞ = colimₙ Bₙ` in the second construction. -/
noncomputable abbrev BInfinity (T : CurveProductTower) : Type _ :=
  (T.ringSequence).colimit

/-- The `n`-th stage module `Lₙ,ᵢ`, for `i ≤ n`. -/
abbrev LStage (T : CurveProductTower) (n i : ℕ) : Type := T.L_stage n i

/-- The colimit module `L∞,ᵢ` supplied by the tower data. -/
abbrev LInfinity (T : CurveProductTower) (i : ℕ) : Type := T.L_infinity i

instance infinity_addCommGroup (T : CurveProductTower) (i : ℕ) :
    AddCommGroup (T.L_infinity i) := inferInstance

instance infinity_module (T : CurveProductTower) (i : ℕ) :
    Module (BInfinity T) (T.L_infinity i) := T.L_infinity_module i

/-- The direct sum of the modules `L∞,ᵢ`. -/
abbrev module (T : CurveProductTower) : Type _ := ⨁ i, T.L_infinity i

instance module_addCommGroup (T : CurveProductTower) :
    AddCommGroup T.module := inferInstance

instance module_module (T : CurveProductTower) :
    Module (BInfinity T) T.module := inferInstance

/-- The zero element supplied by an explicit additive-group structure. -/
def additiveGroupZero {X : Type*} (g : AddCommGroup X) : X :=
  letI : AddCommGroup X := g
  0

/-- The Chern-class obstruction data used in the non-local-freeness argument.

The obstruction index represents the class `c_{m-n}` after restriction to the
product of the remaining curves.  The two class equations are the source's
nonvanishing Chow-group input and the vanishing forced by a hypothetical local
free basis.
-/
structure ChernClassObstructionData (T : CurveProductTower) where
  chowZero : Type u
  chowZeroAddCommGroup : AddCommGroup chowZero
  chernClass : ℕ → chowZero
  obstructionIndex : ℕ
  distinguishedClass : chowZero
  distinguishedClass_ne_zero :
    distinguishedClass ≠ additiveGroupZero chowZeroAddCommGroup
  distinguishedClass_eq_chern :
    chernClass obstructionIndex = distinguishedClass
  chernClass_zero_of_localFree :
    IsLocallyFreeModule (BInfinity T) T.module →
      chernClass obstructionIndex = additiveGroupZero chowZeroAddCommGroup

/-- The source's projectivity/non-local-freeness assertion for the tower. -/
def IsProjectiveNotLocallyFree (T : CurveProductTower) : Prop :=
  Module.Projective (BInfinity T) T.module ∧
    ¬ IsLocallyFreeModule (BInfinity T) T.module

theorem module_projective (T : CurveProductTower)
    (hL : ∀ i, Module.Projective (BInfinity T) (T.L_infinity i)) :
    Module.Projective (BInfinity T) T.module := by
  sorry

theorem cern_classes_vanish_under_localFreeness (T : CurveProductTower)
    (D : ChernClassObstructionData T)
    (hF : IsLocallyFreeModule (BInfinity T) T.module) :
    D.chernClass D.obstructionIndex = additiveGroupZero D.chowZeroAddCommGroup :=
  D.chernClass_zero_of_localFree hF

theorem cern_class_obstruction (T : CurveProductTower)
    (D : ChernClassObstructionData T) :
    ¬ IsLocallyFreeModule (BInfinity T) T.module := by
  sorry

end CurveProductTower

/-- The final example: a countable ring and a projective direct sum of
countably many locally free rank-one modules which is not locally free. -/
theorem exists_countable_ring_projective_directSum_rankOne_not_locallyFree :
    ∃ D : CountableRankOneModuleFamily,
      Module.Projective D.base D.directSum ∧
        ¬ CountableRankOneModuleFamily.isLocallyFree D := by
  sorry

end Formalization.Books.Examples.Unit34
