import Mathlib.Order.Directed
import Mathlib.Topology.Bases
import Mathlib.Topology.Category.TopCat.Limits.Basic
import Mathlib.Topology.Compactness.Compact

/-!
# Examples, Chapter 4: Non-quasi-compact inverse limit of quasi-compact spaces

The source constructs a decreasing family of topologies on `ℕ`.  The
topologies below use the canonical `Set.Ioi` notation for the tails.  Since
Lean's `ℕ` contains `0`, the finite singleton part of the basis is indexed by
`k ≤ n`; this is the corresponding version of the source's
`{1}, ..., {n}` basis when natural numbers are taken to start at `1`.
The inverse system and its limit are expressed in Mathlib's category `TopCat`.
-/

open CategoryTheory CategoryTheory.Limits
open Set TopologicalSpace
open Opposite

namespace Formalization.Books.Examples.Unit04

/-! ## The finite-tail topologies -/

/-- The tail `Iₙ = {k | n < k}` from the source. -/
def tailSet (n : ℕ) : Set ℕ := Set.Ioi n

/-- The singleton-and-tail basis used to generate `Tₙ`. -/
def basicOpen (n : ℕ) : Set (Set ℕ) :=
  {U | ∃ k ≤ n, U = ({k} : Set ℕ)} ∪ {tailSet n}

/-! The topology generated by the singleton-and-tail basis. -/
@[instance_reducible]
def topologyAt (n : ℕ) : TopologicalSpace ℕ :=
  TopologicalSpace.generateFrom (basicOpen n)

/-- The source's assertion that the displayed family is a topological basis. -/
theorem topologyAt_has_basis (n : ℕ) :
    @TopologicalSpace.IsTopologicalBasis ℕ (topologyAt n) (basicOpen n) := by
  refine @TopologicalSpace.IsTopologicalBasis.mk ℕ (topologyAt n) (basicOpen n) ?_ ?_ ?_
  · intro s hs t ht x hx
    rcases hs with (⟨k, hk, rfl⟩ | rfl)
    · rcases ht with (⟨l, hl, rfl⟩ | rfl)
      · simp only [mem_inter_iff, mem_singleton_iff] at hx
        have hkl : k = l := hx.1.symm.trans hx.2
        subst l
        exact ⟨{k}, Or.inl ⟨k, hk, rfl⟩, by simp [hx.1], by simp⟩
      · simp only [mem_inter_iff, mem_singleton_iff] at hx
        exact False.elim ((Nat.not_lt_of_ge hk) (by simpa [tailSet, hx.1] using hx.2))
    · rcases ht with (⟨l, hl, rfl⟩ | rfl)
      · simp only [mem_inter_iff, mem_singleton_iff] at hx
        exact False.elim ((Nat.not_lt_of_ge hl) (by simpa [tailSet, hx.2] using hx.1))
      · exact ⟨tailSet n, Or.inr rfl, hx.2, by simp⟩
  · rw [eq_univ_iff_forall]
    intro x
    by_cases h : x ≤ n
    · exact mem_sUnion.2 ⟨{x}, Or.inl ⟨x, h, rfl⟩, by simp⟩
    · exact mem_sUnion.2 ⟨tailSet n, Or.inr rfl,
        by simpa [tailSet] using Nat.lt_of_not_ge h⟩
  · rfl

/-- The displayed basis determines `topologyAt n` uniquely. -/
theorem topologyAt_unique (n : ℕ) {t : TopologicalSpace ℕ}
    (h : @TopologicalSpace.IsTopologicalBasis ℕ t (basicOpen n)) :
    t = topologyAt n := by
  simpa [topologyAt] using h.eq_generateFrom

/-- Every singleton occurring in the finite part of the basis is open. -/
theorem basic_singleton_open (n k : ℕ) (hk : k ≤ n) :
    @IsOpen ℕ (topologyAt n) ({k} : Set ℕ) := by
  rw [topologyAt]
  exact isOpen_generateFrom_of_mem (Or.inl ⟨k, hk, rfl⟩)

/-- The tail is open in its corresponding topology. -/
theorem tailSet_open (n : ℕ) :
    @IsOpen ℕ (topologyAt n) (tailSet n) := by
  rw [topologyAt]
  exact isOpen_generateFrom_of_mem (Or.inr rfl)

/-! The topologies become finer as the index increases.  The order on
`TopologicalSpace` is the reverse of inclusion of open sets. -/
theorem topologyAt_antitone {m n : ℕ} (h : m ≤ n) :
    topologyAt n ≤ topologyAt m := by
  rw [topologyAt, topologyAt]
  apply le_generateFrom
  intro s hs
  rcases hs with (⟨k, hk, rfl⟩ | rfl)
  · exact basic_singleton_open n k (hk.trans h)
  · change @IsOpen ℕ (topologyAt n) (tailSet m)
    apply (@TopologicalSpace.IsTopologicalBasis.isOpen_iff ℕ (topologyAt n)
      (tailSet m) (basicOpen n) (topologyAt_has_basis n)).2
    intro a ha
    simp only [tailSet, mem_Ioi] at ha
    by_cases han : n < a
    · exact ⟨tailSet n, Or.inr rfl, by simpa [tailSet] using han,
        by intro x hx; exact lt_of_le_of_lt h hx⟩
    · exact ⟨{a}, Or.inl ⟨a, Nat.le_of_not_gt han, rfl⟩, by simp,
        by simpa [tailSet] using ha⟩

/-- The identity map from a later stage to an earlier stage is continuous. -/
theorem identity_continuous {m n : ℕ} (h : m ≤ n) :
    @Continuous ℕ ℕ (topologyAt n) (topologyAt m) id := by
  rw [continuous_iff_le_induced]
  simpa only [induced_id] using topologyAt_antitone h

/-- The topological space `Xₙ = (ℕ, Tₙ)`. -/
def X (n : ℕ) : TopCat :=
  @TopCat.of ℕ (topologyAt n)

/-! ## The inverse system -/

/-- The identity transition map `Xₙ → Xₘ` for `m ≤ n`. -/
def transition {m n : ℕ} (h : m ≤ n) : X n ⟶ X m :=
  @TopCat.ofHom ℕ ℕ (topologyAt n) (topologyAt m)
    (@ContinuousMap.mk ℕ ℕ (topologyAt n) (topologyAt m) id (identity_continuous h))

/-- The strict-index version of the source's transition maps `fₙ,ₘ`. -/
def f (n m : ℕ) (h : m < n) : X n ⟶ X m :=
  transition (Nat.le_of_lt h)

/-- The strict transition maps are continuous identity maps. -/
theorem f_continuous (n m : ℕ) (h : m < n) :
    Continuous ((f n m h : X n ⟶ X m) : X n → X m) := by
  exact (f n m h).hom.2

/-- The transition maps satisfy the composition law of the source. -/
theorem transition_comp {k j i : ℕ} (hkj : k ≤ j) (hji : j ≤ i) :
    transition hji ≫ transition hkj = transition (hkj.trans hji) := by
  apply TopCat.ext
  intro x
  change (transition hkj : X j → X k) ((transition hji : X i → X j) x) =
    (transition (hkj.trans hji) : X i → X k) x
  rfl

/-- The strict-index form of the transition composition identity. -/
theorem f_comp {m n p : ℕ} (hmn : m < n) (hnp : n < p) :
    f p n hnp ≫ f n m hmn = f p m (hmn.trans hnp) := by
  apply TopCat.ext
  intro x
  change (f n m hmn : X n → X m) ((f p n hnp : X p → X n) x) =
    (f p m (hmn.trans hnp) : X p → X m) x
  rfl

/-- The directed inverse system of the spaces `Xₙ`. -/
def inverseSystem : ℕᵒᵖ ⥤ TopCat where
  obj i := X i.unop
  map {i j} p := transition p.unop.le
  map_id := by
    intro i
    apply TopCat.ext
    intro x
    change (transition (m := i.unop) (n := i.unop) (le_refl _) :
      X i.unop → X i.unop) x = x
    rfl
  map_comp := by
    intro i j k p q
    apply TopCat.ext
    intro x
    change (transition (p ≫ q).unop.le : X i.unop → X k.unop) x =
      (transition q.unop.le : X j.unop → X k.unop)
        ((transition p.unop.le : X i.unop → X j.unop) x)
    rfl

/-- Each stage is quasi-compact in the sense of Mathlib's `CompactSpace`. -/
theorem X_is_quasiCompact (n : ℕ) : CompactSpace (X n : Type) := by
  change @CompactSpace ℕ (topologyAt n)
  apply compactSpace_generateFrom (T := topologyAt n) (S := basicOpen n) rfl
  intro P hP hcover
  have htail : tailSet n ∈ P := by
    have hn1 : n + 1 ∈ ⋃₀ P := by
      rw [hcover]
      exact mem_univ _
    rcases mem_sUnion.1 hn1 with ⟨s, hsP, hs⟩
    rcases hP hsP with (⟨k, hk, hsk⟩ | hsk)
    · have hnk : n + 1 = k := by simpa [hsk] using hs
      have hkn : n + 1 ≤ n := by simpa [hnk] using hk
      exact False.elim ((Nat.not_succ_le_self n) hkn)
    · have hsk' : s = tailSet n := by simpa using hsk
      rw [hsk'] at hsP
      exact hsP
  have hsingleton : ∀ k ≤ n, ({k} : Set ℕ) ∈ P := by
    intro k hk
    have hkcover : k ∈ ⋃₀ P := by
      rw [hcover]
      exact mem_univ _
    rcases mem_sUnion.1 hkcover with ⟨s, hsP, hs⟩
    rcases hP hsP with (⟨l, hl, hsl⟩ | hsl)
    · have hkl : k = l := by simpa [hsl] using hs
      have hsl' : s = ({l} : Set ℕ) := by simpa using hsl
      rw [hsl'] at hsP
      simpa [hkl] using hsP
    · have hsl' : s = tailSet n := by simpa using hsl
      rw [hsl'] at hs
      have hnk : n < k := by simpa [tailSet] using hs
      exact False.elim ((Nat.not_lt_of_ge hk) hnk)
  let Q : Set (Set ℕ) :=
    {tailSet n} ∪ (fun k : ℕ => ({k} : Set ℕ)) '' Set.Iic n
  refine ⟨Q, ?_, ?_, ?_⟩
  · intro s hs
    rcases hs with (rfl | ⟨k, hk, rfl⟩)
    · exact htail
    · exact hsingleton k hk
  · exact (Set.finite_singleton (tailSet n)).union ((Set.finite_Iic n).image _)
  · rw [eq_univ_iff_forall]
    intro k
    by_cases hk : k ≤ n
    · exact mem_sUnion.2 ⟨{k}, Or.inr ⟨k, hk, rfl⟩, by simp⟩
    · exact mem_sUnion.2 ⟨tailSet n, Or.inl rfl,
        by simpa [tailSet] using Nat.lt_of_not_ge hk⟩

/-- The index order is directed, and every object of `inverseSystem` is quasi-compact. -/
theorem inverseSystem_is_directed_quasiCompact :
    IsDirectedOrder ℕ ∧ ∀ n : ℕ, CompactSpace (X n : Type) := by
  refine ⟨inferInstance, ?_⟩
  intro n
  exact X_is_quasiCompact n

/-! ## The discrete limit and the universal property -/

/-- The discrete space `X = (ℕ, T)` from the source. -/
abbrev limitSpace : TopCat := TopCat.discrete.obj ℕ

/-- Every map from the discrete topology to a stage is continuous. -/
theorem discrete_to_stage_continuous (n : ℕ) :
    @Continuous ℕ ℕ (⊥ : TopologicalSpace ℕ) (topologyAt n) id := by
  exact @continuous_of_discreteTopology ℕ (⊥ : TopologicalSpace ℕ) inferInstance
    ℕ (topologyAt n) id

/-- The identity map from the discrete space to the `n`-th stage. -/
def limitProjection (n : ℕ) : limitSpace ⟶ X n :=
  @TopCat.ofHom ℕ ℕ (⊥ : TopologicalSpace ℕ) (topologyAt n)
    (@ContinuousMap.mk ℕ ℕ (⊥ : TopologicalSpace ℕ) (topologyAt n)
      id (discrete_to_stage_continuous n))

/-- The projections are the identity functions on the underlying set. -/
theorem limitProjection_apply (n : ℕ) (x : limitSpace) :
    limitProjection n x = x := by
  change (id : ℕ → ℕ) x = x
  rfl

/-- The cone with point `limitSpace` and the identity projections. -/
def limitCone : Cone inverseSystem where
  pt := limitSpace
  π :=
    { app := fun i => limitProjection i.unop
      naturality := by
        intro i j p
        apply TopCat.ext
        intro x
        change (limitProjection j.unop : limitSpace → X j.unop) x =
          (transition p.unop.le : X i.unop → X j.unop)
            ((limitProjection i.unop : limitSpace → X i.unop) x)
        rfl }

/-- The discrete space is a categorical inverse limit of the system. -/
theorem limitCone_isLimit_exists : Nonempty (IsLimit limitCone) := by
  let hc : IsLimit ((forget TopCat).mapCone limitCone) :=
    Classical.choice ((Types.isLimit_iff _).2 (by
      intro s hs
      refine ⟨s (op 0), ?_, ?_⟩
      · intro j
        let p : j ⟶ op 0 := (homOfLE (Nat.zero_le j.unop)).op
        have hp := hs p
        change s (op 0) = s j
        change s j = s (op 0) at hp
        exact hp.symm
      · intro y hy
        have hy0 := hy (op 0)
        change y = s (op 0) at hy0
        exact hy0))
  have hInf : (⨅ i : ℕᵒᵖ, topologyAt i.unop) = (⊥ : TopologicalSpace ℕ) := by
    apply le_antisymm
    · rw [TopologicalSpace.le_def]
      intro U _
      rw [← biUnion_of_singleton U]
      exact @isOpen_biUnion ℕ ℕ (⨅ i : ℕᵒᵖ, topologyAt i.unop) U
        (fun x => ({x} : Set ℕ)) (fun x _ => by
        have hi : (⨅ i : ℕᵒᵖ, topologyAt i.unop) ≤ topologyAt x :=
          iInf_le (fun i : ℕᵒᵖ => topologyAt i.unop) (op x)
        have hsx : @IsOpen ℕ (topologyAt x) ({x} : Set ℕ) :=
          basic_singleton_open x x le_rfl
        exact hi ({x} : Set ℕ) hsx)
    · exact bot_le
  have htop :
      (⊥ : TopologicalSpace ℕ) =
        ⨅ i : ℕᵒᵖ, (inverseSystem.obj i).str.induced
          (limitCone.π.app i) := by
    change (⊥ : TopologicalSpace ℕ) =
      ⨅ i : ℕᵒᵖ, (topologyAt i.unop).induced (id : ℕ → ℕ)
    simpa only [induced_id] using hInf.symm
  exact (TopCat.nonempty_isLimit_iff_eq_induced limitCone hc).2 htop

/-- A chosen limit proof for `limitCone`. -/
noncomputable def limitCone_isLimit : IsLimit limitCone :=
  Classical.choice limitCone_isLimit_exists

/-- Strict compatibility of a family of maps into the stages. -/
def StrictlyCompatible {Y : TopCat} (g : ∀ n : ℕ, Y ⟶ X n) : Prop :=
  ∀ ⦃m n : ℕ⦄ (h : m < n), g n ≫ f n m h = g m

/-- The common underlying set map of a compatible family. -/
def commonMap {Y : TopCat} (g : ∀ n : ℕ, Y ⟶ X n) : Y → ℕ :=
  fun y => g 0 y

/-- Compatibility forces all underlying maps to be the common set map. -/
theorem compatible_commonMap {Y : TopCat} (g : ∀ n : ℕ, Y ⟶ X n)
    (hg : StrictlyCompatible g) (n : ℕ) :
    (g n : Y → ℕ) = commonMap g := by
  funext y
  by_cases hn : n = 0
  · subst n
    rfl
  · have hcompat := hg (Nat.pos_of_ne_zero hn)
    have hvalue := congrArg (fun q : Y ⟶ X 0 => q y) hcompat
    change (g n : Y → ℕ) y = commonMap g y at hvalue
    exact hvalue

/-- In particular, the singleton `{n}` is open in `Xₙ`. -/
theorem singleton_open_in_X (n : ℕ) :
    @IsOpen ℕ (topologyAt n) ({n} : Set ℕ) := by
  exact basic_singleton_open n n le_rfl

/-- The preimage of a singleton under the common map agrees with the stagewise preimage. -/
theorem commonMap_preimage_singleton {Y : TopCat}
    (g : ∀ n : ℕ, Y ⟶ X n) (hg : StrictlyCompatible g) (n : ℕ) :
    commonMap g ⁻¹' ({n} : Set ℕ) =
      (g n : Y → ℕ) ⁻¹' ({n} : Set ℕ) := by
  rw [compatible_commonMap g hg n]
  rfl

/-- Each singleton preimage of the common map is open in `Y`. -/
theorem commonMap_preimage_singleton_isOpen {Y : TopCat}
    (g : ∀ n : ℕ, Y ⟶ X n) (hg : StrictlyCompatible g) (n : ℕ) :
    IsOpen (commonMap g ⁻¹' ({n} : Set ℕ)) := by
  rw [commonMap_preimage_singleton g hg n]
  exact (g n).hom.2.isOpen_preimage _ (singleton_open_in_X n)

/-- The common set map is continuous to the discrete topology. -/
theorem commonMap_continuous {Y : TopCat}
    (g : ∀ n : ℕ, Y ⟶ X n) (hg : StrictlyCompatible g) :
    @Continuous Y ℕ Y.str (⊥ : TopologicalSpace ℕ) (commonMap g) := by
  exact (@continuous_discrete_rng ℕ Y Y.str (⊥ : TopologicalSpace ℕ)
    (discreteTopology_bot ℕ) (commonMap g)).2
      (fun n => commonMap_preimage_singleton_isOpen g hg n)

/-- The continuous map to the discrete limit induced by a compatible family. -/
def commonMapHom {Y : TopCat} (g : ∀ n : ℕ, Y ⟶ X n)
    (hg : StrictlyCompatible g) : Y ⟶ limitSpace :=
  TopCat.ofHom ⟨commonMap g, commonMap_continuous g hg⟩

/-- The induced map has the prescribed stagewise components. -/
theorem commonMapHom_comp_projection {Y : TopCat}
    (g : ∀ n : ℕ, Y ⟶ X n) (hg : StrictlyCompatible g) (n : ℕ) :
    commonMapHom g hg ≫ limitProjection n = g n := by
  apply TopCat.ext
  intro y
  change commonMap g y = (g n : Y → ℕ) y
  exact (congrFun (compatible_commonMap g hg n) y).symm

/-- The induced map is the unique map with those prescribed components. -/
theorem commonMapHom_unique {Y : TopCat}
    (g : ∀ n : ℕ, Y ⟶ X n) (hg : StrictlyCompatible g)
    (l : Y ⟶ limitSpace)
    (hl : ∀ n : ℕ, l ≫ limitProjection n = g n) :
    l = commonMapHom g hg := by
  apply TopCat.ext
  intro y
  have hzero := congrArg (fun q : Y ⟶ X 0 => q y) (hl 0)
  change (l : Y → ℕ) y = commonMap g y at hzero
  exact hzero

/-! ## The singleton cover and non-quasi-compactness -/

/-- The open-cover family of singleton subsets of the discrete limit. -/
def singletonCover (n : ℕ) : Set ℕ := {n}

/-- Every member of the singleton cover is open in the discrete limit. -/
theorem singletonCover_isOpen (n : ℕ) :
    @IsOpen ℕ (⊥ : TopologicalSpace ℕ) (singletonCover n) := by
  change @IsOpen ℕ (⊥ : TopologicalSpace ℕ) ({n} : Set ℕ)
  exact isOpen_discrete _

/-- The singleton family covers the whole underlying set. -/
theorem singletonCover_covers :
    (Set.univ : Set ℕ) ⊆ ⋃ n : ℕ, singletonCover n := by
  intro n _
  exact mem_iUnion.2 ⟨n, by simp [singletonCover]⟩

/-- No finite subfamily of the singleton cover covers `ℕ`. -/
theorem singletonCover_no_finite_subcover :
    ¬ ∃ t : Finset ℕ, (Set.univ : Set ℕ) ⊆ ⋃ n ∈ t, singletonCover n := by
  rintro ⟨t, ht⟩
  rcases Finset.bddAbove t with ⟨N, hN⟩
  let n := N + 1
  have hncover : n ∈ ⋃ k ∈ t, singletonCover k := ht (mem_univ n)
  rcases mem_iUnion.1 hncover with ⟨k, hkcover⟩
  rcases mem_iUnion.1 hkcover with ⟨hk, hmem⟩
  have hnk : n = k := by simpa [singletonCover] using hmem
  have hle : k ≤ N := hN hk
  have hnle : n ≤ N := by
    rw [hnk]
    exact hle
  exact (Nat.not_succ_le_self N) (by simpa [n] using hnle)

/-- The discrete inverse-limit space is not quasi-compact. -/
theorem limitSpace_not_quasiCompact : ¬ CompactSpace (limitSpace : Type) := by
  change ¬ @CompactSpace ℕ (⊥ : TopologicalSpace ℕ)
  intro hcompact
  have hfinite :
      ∃ t : Finset ℕ, (Set.univ : Set ℕ) ⊆ ⋃ n ∈ t, singletonCover n := by
    exact
      (@isCompact_univ ℕ (⊥ : TopologicalSpace ℕ) hcompact).elim_finite_subcover
        singletonCover
        (fun n => singletonCover_isOpen n) singletonCover_covers
  exact singletonCover_no_finite_subcover hfinite

/-! ## The chapter lemma -/

/-- There is an inverse system of quasi-compact spaces over `ℕ` with a
non-quasi-compact limit cone. -/
lemma exists_nonQuasiCompact_inverse_limit :
    ∃ F : ℕᵒᵖ ⥤ TopCat,
      (∀ n : ℕ, CompactSpace (F.obj (op n) : Type)) ∧
        ∃ C : Cone F, Nonempty (IsLimit C) ∧ ¬ CompactSpace (C.pt : Type) := by
  refine ⟨inverseSystem, ?_, limitCone, ⟨limitCone_isLimit⟩, ?_⟩
  · intro n
    change CompactSpace (X n : Type)
    exact X_is_quasiCompact n
  · exact limitSpace_not_quasiCompact

end Formalization.Books.Examples.Unit04
