import Formalization.Books.Fields.Unit08.AlgebraicExtensions
import Mathlib.FieldTheory.Minpoly.Field
import Mathlib.FieldTheory.IntermediateField.Adjoin.Basic
import Mathlib.RingTheory.PrincipalIdealDomain

/-!
# Fields, Chapter 9: Minimal polynomials

The source's minimal polynomial is Mathlib's canonical `minpoly`.  A field
extension is represented by an `Algebra`, the annihilating polynomials form the
kernel of `Polynomial.aeval`, and the simple extension `k(α)` is represented by
`IntermediateField.adjoin k ({α} : Set E)`.  Mathlib's `AdjoinRoot` is the
quotient of `k[X]` by the ideal generated by a polynomial, so it supplies the
quotient presentation used at the end of the section.
-/

namespace Formalization.Books.Fields.Unit09

noncomputable section

/-! ## The annihilator ideal and the minimal polynomial -/

/- The source's evaluation map `k[X] → E`, `X ↦ α`, is Mathlib's canonical
   algebra homomorphism `Polynomial.aeval α`. -/
def annihilatorIdeal (F E : Type*) [Field F] [Field E] [Algebra F E] (α : E) :
    Ideal (Polynomial F) :=
  RingHom.ker (Polynomial.aeval α).toRingHom

/-- Membership in the annihilator ideal is exactly vanishing at `α`. -/
theorem mem_annihilatorIdeal_iff
    {F E : Type*} [Field F] [Field E] [Algebra F E] (α : E) (p : Polynomial F) :
    p ∈ annihilatorIdeal F E α ↔ Polynomial.aeval α p = 0 := by
  exact RingHom.mem_ker

/- The opening algebraicity hypothesis in the source says that the
   annihilator ideal is not the zero ideal.  The preceding chapter already
   supplies the equivalent nonzero-polynomial formulation of `IsAlgebraic`. -/
/-- The annihilator ideal of an algebraic element is nonzero. -/
theorem annihilatorIdeal_ne_bot
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    annihilatorIdeal F E α ≠ ⊥ := by
  obtain ⟨p, hp, hpa⟩ :=
    (Formalization.Books.Fields.Unit08.algebraic_element_iff_exists_nonzero_polynomial α).mp hα
  intro hbot
  have hp_mem : p ∈ annihilatorIdeal F E α :=
    (mem_annihilatorIdeal_iff α p).2 hpa
  rw [hbot] at hp_mem
  exact hp (Ideal.mem_bot.mp hp_mem)

/-- The annihilating polynomials form a principal ideal because `F[X]` is a PID. -/
theorem annihilatorIdeal_is_principal
    {F E : Type*} [Field F] [Field E] [Algebra F E] (α : E) :
    (annihilatorIdeal F E α).IsPrincipal := by
  infer_instance

/- The kernel description and the canonical minimal-polynomial API identify the
   ideal's generator.  The notation `Polynomial F ∙ p` is the ideal span of
   the singleton `{p}`. -/
/-- The annihilator ideal is generated by the minimal polynomial. -/
theorem annihilatorIdeal_eq_span_minpoly
    {F E : Type*} [Field F] [Field E] [Algebra F E] (α : E) :
    annihilatorIdeal F E α = Polynomial F ∙ minpoly F α := by
  exact minpoly.ker_aeval_eq_span_minpoly (A := F) (B := E) α

/- The source's definition is already supplied by `minpoly`; no parallel
   minimal-polynomial definition is introduced. -/

/-- An algebraic element has a nonzero monic minimal polynomial. -/
theorem minimal_polynomial_is_monic
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    (minpoly F α).Monic :=
  minpoly.monic hα.isIntegral

/-- The minimal polynomial of an algebraic element is nonzero. -/
theorem minimal_polynomial_ne_zero
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    minpoly F α ≠ 0 :=
  minpoly.ne_zero hα.isIntegral

/-- The minimal polynomial annihilates the element over the base field. -/
theorem minimal_polynomial_aeval_eq_zero
    {F E : Type*} [Field F] [Field E] [Algebra F E] (α : E) :
    Polynomial.aeval α (minpoly F α) = 0 :=
  minpoly.aeval F α

/-- The minimal polynomial has no larger degree than any monic annihilator. -/
theorem minimal_polynomial_has_minimal_degree
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (_hα : IsAlgebraic F α) {p : Polynomial F} (hp : p.Monic)
    (hpa : Polynomial.aeval α p = 0) :
    (minpoly F α).degree ≤ p.degree := by
  exact minpoly.min F α hp hpa

/-- A monic annihilator of minimal degree is the minimal polynomial. -/
theorem monic_annihilator_eq_minimal_polynomial
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    {p : Polynomial F} (hp : p.Monic) (hpa : Polynomial.aeval α p = 0)
    (hmin : ∀ q : Polynomial F, q.Monic → Polynomial.aeval α q = 0 →
      p.degree ≤ q.degree) :
    p = minpoly F α := by
  exact minpoly.unique F α hp hpa hmin

/-- Every polynomial annihilating an algebraic element is divisible by its
    minimal polynomial. -/
theorem minimal_polynomial_dvd_of_aeval_eq_zero
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (_hα : IsAlgebraic F α) {p : Polynomial F}
    (hpa : Polynomial.aeval α p = 0) :
    minpoly F α ∣ p := by
  exact minpoly.dvd F α hpa

/-- A nonconstant multiple of the minimal polynomial has strictly larger
    polynomial degree. -/
theorem minimal_polynomial_nonconstant_multiple_degree
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) {q : Polynomial F} (hq : 0 < q.natDegree) :
    (minpoly F α).degree < (q * minpoly F α).degree := by
  sorry

/-! ## Irreducibility and the prime ideal -/

/-- The minimal polynomial of an algebraic element is irreducible. -/
theorem minimal_polynomial_irreducible
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    Irreducible (minpoly F α) :=
  minpoly.irreducible hα.isIntegral

/-- The annihilator ideal is prime because evaluation maps into a field. -/
theorem annihilatorIdeal_is_prime
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (_hα : IsAlgebraic F α) :
    (annihilatorIdeal F E α).IsPrime := by
  exact RingHom.ker_isPrime (Polynomial.aeval α).toRingHom

/-- In the algebraic case, irreducibility of the minimal polynomial and
    primality of its annihilator ideal are equivalent source formulations. -/
theorem minimal_polynomial_irreducible_iff_annihilatorIdeal_is_prime
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    Irreducible (minpoly F α) ↔
      (annihilatorIdeal F E α).IsPrime := by
  constructor
  · intro _
    exact annihilatorIdeal_is_prime hα
  · intro _
    exact minimal_polynomial_irreducible hα

/-! ## The degree and quotient presentation -/

/- The source's field degree `[k(α) : k]` is represented by the earlier
   chapter's cardinal-valued `fieldExtensionDegree`; the finite-dimensional
   form is recorded separately because `IntermediateField.adjoin.finrank` is
   the exact Mathlib theorem. -/
/-- The finite dimension of `k(α)` equals the natural degree of the minimal
    polynomial. -/
theorem simple_extension_finrank_eq_minimal_polynomial_natDegree
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    Module.finrank F (IntermediateField.adjoin F ({α} : Set E)) =
      (minpoly F α).natDegree := by
  exact IntermediateField.adjoin.finrank hα.isIntegral

/-- The field degree of `k(α)` equals the degree of its minimal polynomial. -/
theorem minimal_polynomial_degree
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    Formalization.Books.Fields.Unit07.fieldExtensionDegree
        F (IntermediateField.adjoin F ({α} : Set E)) =
      ((minpoly F α).natDegree : Cardinal) := by
  sorry

/- `AdjoinRoot P` is definitionally `F[X] / (P)`, and the preceding chapter's
   equivalence is the canonical quotient presentation of `k(α)`. -/
/-- The quotient by the minimal polynomial is isomorphic to the simple field
    extension generated by the algebraic element. -/
noncomputable def minimal_polynomial_quotient_isomorphic_to_simple_extension
    {F E : Type*} [Field F] [Field E] [Algebra F E] {α : E}
    (hα : IsAlgebraic F α) :
    AdjoinRoot (minpoly F α) ≃ₐ[F]
      IntermediateField.adjoin F ({α} : Set E) :=
  Formalization.Books.Fields.Unit08.simple_extension_adjoinRoot_equiv hα

end

end Formalization.Books.Fields.Unit09
