import Formalization.Books.Exercises.Unit20.Core

import Mathlib.Algebra.Algebra.Operations
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.RingTheory.AlgebraicIndependent.TranscendenceBasis
import Mathlib.RingTheory.EssentialFiniteness

/-!
# Exercises, Chapter 20: Transcendence degree

This file records the theorem interfaces for the two numbered exercises.
Proofs are deferred to the proving stage.
-/

namespace Formalization.Books.Exercises.Unit20

universe u

noncomputable section

/-! ## Exercise 1: algebraic extensions -/

/-- An algebraic extension of fields does not change transcendence degree over
the bottom field. -/
theorem transcendence_degree_eq_of_algebraic_extension
    {k K K' : Type u} [Field k] [Field K] [Field K']
    [Algebra k K] [Algebra K K'] [Algebra k K'] [IsScalarTower k K K']
    (hK' : Algebra.IsAlgebraic K K') :
    Algebra.trdeg k K = Algebra.trdeg k K' := by
  sorry

/-! ## Exercise 2: growth of powers of subvector spaces -/

/-- The product of two finite-dimensional subvector spaces is
finite-dimensional.  This uses Mathlib's canonical `Submodule.mul`, whose
carrier is the subspace generated by the finite sums of products described
in the source. -/
theorem finiteDimensional_subvectorSpace_product
    {k K : Type u} [Field k] [Field K] [Algebra k K]
    (V W : Submodule k K) [FiniteDimensional k V] [FiniteDimensional k W] :
    FiniteDimensional k (V * W) := by
  sorry

/-- The lower polynomial-growth bound for a finitely generated field extension
of transcendence degree `d`. -/
theorem exists_subvectorSpace_power_growth_lower_bound
    {k K : Type u} [Field k] [Field K] [Algebra k K]
    (hK : Algebra.EssFiniteType k K) (d : ℕ)
    (htrdeg : Algebra.trdeg k K = d) :
    ∃ V : Submodule k K, FiniteDimensional k V ∧
      ∃ ε : ℝ, 0 < ε ∧
        ∀ n : ℕ, 1 ≤ n →
          (Module.finrank k ((V ^ n : Submodule k K) : Type u) : ℝ) ≥
            ε * (n : ℝ) ^ d := by
  sorry

/-- The upper polynomial-growth bound for every finite-dimensional subvector
space in a finitely generated field extension of transcendence degree `d`. -/
theorem subvectorSpace_power_growth_upper_bound
    {k K : Type u} [Field k] [Field K] [Algebra k K]
    (hK : Algebra.EssFiniteType k K) (d : ℕ)
    (htrdeg : Algebra.trdeg k K = d) :
    ∀ V : Submodule k K, FiniteDimensional k V →
      ∃ C : ℝ, 0 < C ∧
        ∀ n : ℕ, 1 ≤ n →
          (Module.finrank k ((V ^ n : Submodule k K) : Type u) : ℝ) ≤
            C * (n : ℝ) ^ d := by
  sorry

/-- The preceding lower and upper bounds characterize the transcendence
degree among finitely generated field extensions. -/
theorem power_growth_characterizes_transcendence_degree
    {k K : Type u} [Field k] [Field K] [Algebra k K]
    (hK : Algebra.EssFiniteType k K) (d : ℕ) :
    HasSubvectorSpacePowerGrowth k K d ↔ Algebra.trdeg k K = d := by
  sorry

end

end Formalization.Books.Exercises.Unit20
