import Mathlib.Algebra.Module.LocalizedModule.AtPrime
import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.LocalProperties.Submodule
import Mathlib.RingTheory.Spectrum.Maximal.Defs
import Mathlib.RingTheory.Spectrum.Prime.Basic

/-!
# Exercises, Chapter 7: Localization

This file records the criteria for detecting zero elements and zero modules
after localization.  The source's annihilator of an element is the canonical
span-annihilator ideal `(Submodule.span A {m}).annihilator`.
-/

noncomputable section

universe u v

namespace Formalization.Books.Exercises.Unit07

/-! ## Annihilators and localization at primes -/

/-- The canonical annihilator ideal of the cyclic submodule generated by an
element has the expected membership criterion. -/
theorem annihilator_of_element_mem_iff
    {A : Type u} [CommRing A]
    {M : Type v} [AddCommGroup M] [Module A M]
    (m : M) (a : A) :
    a ∈ (Submodule.span A ({m} : Set M)).annihilator ↔ a • m = 0 := by
  exact Submodule.mem_annihilator_span_singleton m a

/-- An element vanishes in the localization at a prime exactly when its
annihilator is not contained in that prime. -/
theorem localize_at_prime_eq_zero_iff_annihilator_not_le
    {A : Type u} [CommRing A]
    {M : Type v} [AddCommGroup M] [Module A M]
    (p : PrimeSpectrum A) (m : M) :
    (LocalizedModule.mkLinearMap p.asIdeal.primeCompl M) m = 0 ↔
      ¬ (Submodule.span A ({m} : Set M)).annihilator ≤ p.asIdeal := by
  rw [← LinearMap.mem_ker]
  rw [LocalizedModule.mem_ker_mkLinearMap_iff]
  constructor
  · rintro ⟨r, hr, hrm⟩ hle
    exact hr (hle ((annihilator_of_element_mem_iff m r).mpr hrm))
  · intro h
    by_contra hzero
    apply h
    intro r hr
    by_contra hrp
    exact hzero ⟨r, hrp, (annihilator_of_element_mem_iff m r).mp hr⟩

/-- An element is zero exactly when all of its prime-localized images are
zero. -/
theorem element_eq_zero_iff_all_prime_localizations_eq_zero
    {A : Type u} [CommRing A]
    {M : Type v} [AddCommGroup M] [Module A M]
    (m : M) :
    m = 0 ↔
      ∀ p : PrimeSpectrum A,
        (LocalizedModule.mkLinearMap p.asIdeal.primeCompl M) m = 0 := by
  constructor
  · rintro rfl p
    simp
  · intro h
    refine Module.eq_zero_of_localization_maximal
      (fun (P : Ideal A) _ ↦ LocalizedModule P.primeCompl M)
      (fun (P : Ideal A) _ ↦ LocalizedModule.mkLinearMap P.primeCompl M) m ?_
    intro P hP
    exact h ⟨P, hP.isPrime⟩

/-- An element is zero exactly when all of its maximal-localized images are
zero. -/
theorem element_eq_zero_iff_all_maximal_localizations_eq_zero
    {A : Type u} [CommRing A]
    {M : Type v} [AddCommGroup M] [Module A M]
    (m : M) :
    m = 0 ↔
      ∀ p : MaximalSpectrum A,
        (LocalizedModule.mkLinearMap p.asIdeal.primeCompl M) m = 0 := by
  constructor
  · rintro rfl p
    simp
  · intro h
    exact Module.eq_zero_of_localization_maximal
      (fun P _ ↦ LocalizedModule P.primeCompl M)
      (fun P _ ↦ LocalizedModule.mkLinearMap P.primeCompl M) m
      (fun P hP ↦ h ⟨P, hP⟩)

/-- A module is zero exactly when all of its maximal-localized modules are
zero. -/
theorem module_subsingleton_iff_all_maximal_localizations_subsingleton
    {A : Type u} [CommRing A]
    {M : Type v} [AddCommGroup M] [Module A M] :
    Subsingleton M ↔
      ∀ p : MaximalSpectrum A,
        Subsingleton (LocalizedModule.AtPrime p.asIdeal M) := by
  constructor
  · intro h p
    let := h
    infer_instance
  · intro h
    exact Module.subsingleton_of_localization_maximal
      (fun P _ ↦ LocalizedModule P.primeCompl M)
      (fun P _ ↦ LocalizedModule.mkLinearMap P.primeCompl M)
      (fun P hP ↦ h ⟨P, hP⟩)

end Formalization.Books.Exercises.Unit07
