import Mathlib.Algebra.Ring.Prod
import Mathlib.RingTheory.Ideal.Prod
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Localization.Basic

/-!
# Exercises, Chapter 7: Localization

This file records the quotient-localization example.  The product ring
`ℤ × ℤ` localized at the idempotent `(1, 0)` becomes its first factor, which
is also the quotient by the ideal `0 × ℤ`.
-/

noncomputable section

namespace Formalization.Books.Exercises.Unit07

/-! ## A quotient which is a localization -/

/-- The product ring used in the example. -/
abbrev localizationQuotientExampleRing : Type := ℤ × ℤ

/-- The nonzero proper ideal `0 × ℤ`. -/
def localizationQuotientExampleIdeal :
    Ideal localizationQuotientExampleRing :=
  Ideal.prod (⊥ : Ideal ℤ) (⊤ : Ideal ℤ)

/-- The multiplicative subset generated by the idempotent `(1, 0)`. -/
def localizationQuotientExampleSubmonoid :
    Submonoid localizationQuotientExampleRing :=
  Submonoid.powers (1, 0)

/-- The quotient in the example. -/
abbrev localizationQuotientExampleQuotient : Type :=
  localizationQuotientExampleRing ⧸ localizationQuotientExampleIdeal

/-- The localization in the example. -/
abbrev localizationQuotientExampleLocalization : Type :=
  Localization localizationQuotientExampleSubmonoid

/-- The displayed proper nonzero ideal and multiplicative subset give the
quotient-localization example as an equivalence of `A`-algebras. -/
theorem localization_is_quotient_example :
    localizationQuotientExampleIdeal ≠ (⊥ : Ideal localizationQuotientExampleRing) ∧
      localizationQuotientExampleIdeal ≠ (⊤ : Ideal localizationQuotientExampleRing) ∧
        Nonempty
          (localizationQuotientExampleQuotient ≃ₐ[localizationQuotientExampleRing]
            localizationQuotientExampleLocalization) := by
  sorry

end Formalization.Books.Exercises.Unit07
