import Formalization.Books.Algebra.Unit54.EssentiallyFiniteType
import Formalization.Books.Algebra.Unit68.RegularSequences
import Formalization.Books.Algebra.Unit104.CohenMacaulayRings
import Formalization.Books.Algebra.Unit114.DimensionFiniteTypeAlgebras
import Formalization.Books.Algebra.Unit116.DimensionFiniteTypeAlgebrasReprise
import Formalization.Books.Algebra.Unit134.NaiveCotangentComplex
import Mathlib.RingTheory.Ideal.Cotangent
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.RingHom.FiniteType
import Mathlib.RingTheory.RegularLocalRing.Defs

/-!
# Commutative Algebra, Chapter 135: Local complete intersections

The chapter's polynomial presentations use the canonical `Algebra.Generators`
interface exposed in Chapter 134.  Ideals generated by a finite family are
written with `Ideal.span`, regular sequences use Mathlib's
`RingTheory.Sequence.IsRegular`, and conormal modules use `Ideal.Cotangent`.
For a presentation localized at a prime, `Ideal.Cotangent` is naturally a
module over the quotient of the localized polynomial ring; this is the
canonical presentation of the source's localized `S_q`-module.

The source writes dimension differences as natural numbers.  Since Mathlib's
Krull dimensions have type `WithBot ℕ∞`, the declarations below expose the
equivalent equation `dim A = dim C + n`.
-/

namespace Formalization.Books.Algebra.Unit135

open Set
open IsLocalRing
open Formalization.Books.Topology.Unit10
open scoped TensorProduct

noncomputable section

universe u v

/-! ## Finite generation and dimension bookkeeping -/

abbrev PolynomialPresentation (k S : Type*) [CommRing k] [CommRing S]
    [Algebra k S] (n : ℕ) :=
  Formalization.Books.Algebra.Unit134.Presentation k S (Fin n)

def IsIdealGeneratedByElements
    {R : Type u} [CommRing R] (I : Ideal R) (n : ℕ) : Prop :=
  ∃ x : Fin n → R, Ideal.span (Set.range x) = I

def IsModuleGeneratedByElements
    (R : Type u) (M : Type v) [Semiring R] [AddCommMonoid M] [Module R M]
    (n : ℕ) : Prop :=
  ∃ x : Fin n → M, Submodule.span R (Set.range x) = ⊤

def IsIdealGeneratedByRegularSequence
    {R : Type u} [CommRing R] (I : Ideal R) : Prop :=
  ∃ xs : List R, Ideal.ofList xs = I ∧
    RingTheory.Sequence.IsRegular R xs

def IsGeneratedByDimensionDifference
    (A C : Type u) [CommRing A] [CommRing C] (I : Ideal A) : Prop :=
  ∃ n : ℕ,
    ringKrullDim A = ringKrullDim C + (((n : ℕ∞) : WithBot ℕ∞)) ∧
      IsIdealGeneratedByElements I n

def IsFreeOfRank
    (R : Type u) (M : Type v) [Semiring R] [AddCommGroup M] [Module R M]
    (n : ℕ) : Prop :=
  Nonempty (M ≃ₗ[R] (Fin n →₀ R))

/-! ## Global and local complete intersections over a field -/

def IsGlobalCompleteIntersection
    (k S : Type u) [Field k] [CommRing S] [Algebra k S] : Prop :=
  RingHom.FiniteType (algebraMap k S) ∧
    (Subsingleton S ∨
      ∃ (n c : ℕ) (P : PolynomialPresentation k S n)
        (f : Fin c → P.Ring),
        P.ker = Ideal.ofList (List.ofFn f) ∧
          c ≤ n ∧
          ringKrullDim S = (((n - c : ℕ) : ℕ∞) : WithBot ℕ∞))

def IsLocalCompleteIntersection
    (k S : Type u) [Field k] [CommRing S] [Algebra k S] : Prop :=
  RingHom.FiniteType (algebraMap k S) ∧
    ∃ (n : ℕ) (g : Fin n → S),
      (⋃ i : Fin n,
          (PrimeSpectrum.basicOpen (g i) : Set (PrimeSpectrum S))) = Set.univ ∧
        ∀ i, IsGlobalCompleteIntersection k (Localization.Away (g i))

/- The paragraph following the definition is recorded with a chosen
   presentation: every maximal localization has the displayed dimension and
   the spectrum is equidimensional.  The polynomial-local dimension input is
   the earlier `Unit114.dim_affine_space` theorem. -/
theorem global_complete_intersection_maximal_localizations
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    (n c : ℕ) (P : PolynomialPresentation k S n)
    (f : Fin c → P.Ring)
    (hker : P.ker = Ideal.ofList (List.ofFn f))
    (hc : c ≤ n)
    (hdim : ringKrullDim S = (((n - c : ℕ) : ℕ∞) : WithBot ℕ∞))
    (m : MaximalSpectrum S) :
    ringKrullDim (Localization.AtPrime m.asIdeal) =
        (((n - c : ℕ) : ℕ∞) : WithBot ℕ∞) ∧
      Formalization.Books.Topology.Unit10.Equidimensional
        (X := PrimeSpectrum S) := by
  sorry

theorem presentation_codimension_eq_local_dimension
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    {n : ℕ} (P : PolynomialPresentation k S n)
    (q : PrimeSpectrum S) (q' : PrimeSpectrum P.Ring)
    (hcorresponding :
      PrimeSpectrum.comap (algebraMap P.Ring S) q = q')
    (c : ℕ)
    (hc : q'.asIdeal.height = q.asIdeal.height + (c : ℕ∞)) :
    krullDimensionAt q = (((n - c : ℕ) : ℕ∞) : WithBot ℕ∞) := by
  let _ : Algebra.FiniteType k S := P.finiteType
  letI : IsNoetherianRing S := Algebra.FiniteType.isNoetherianRing k S
  have hglobal : topologicalKrullDim (PrimeSpectrum P.Ring) =
      (((n : ℕ∞) : WithBot ℕ∞)) := by
    rw [PrimeSpectrum.topologicalKrullDim_eq_ringKrullDim,
      MvPolynomial.ringKrullDim_of_isNoetherianRing,
      ringKrullDim_eq_zero_of_field]
    simp
  have huniv : topologicalKrullDim (Set.univ : Set (PrimeSpectrum P.Ring)) =
      topologicalKrullDim (PrimeSpectrum P.Ring) :=
    IsHomeomorph.topologicalKrullDim_eq _
      (Homeomorph.Set.univ (PrimeSpectrum P.Ring)).isHomeomorph
  have hpoly : krullDimensionAt q' = (((n : ℕ∞) : WithBot ℕ∞)) := by
    have hpoint :=
      Formalization.Books.Algebra.Unit114.dimension_at_a_point_finite_type_over_field
        (k := k) (S := P.Ring) (p := q'.asIdeal) (hp := q'.2)
    dsimp at hpoint
    obtain ⟨d, hdx, hdcomp, _⟩ := hpoint
    have hle : krullDimensionAt q' ≤ (((n : ℕ∞) : WithBot ℕ∞)) := by
      exact (krullDimensionAt_le q' isOpen_univ (mem_univ q')).trans_eq
        (huniv.trans hglobal)
    have hmem : (((n : ℕ∞) : WithBot ℕ∞)) ∈
        Formalization.Books.Algebra.Unit114.componentDimensionsAtPoint q' := by
      refine ⟨Set.univ, ?_, mem_univ q', ?_⟩
      · rw [irreducibleComponents_eq_singleton]
        simp
      · exact huniv.trans hglobal
    have hge : (((n : ℕ∞) : WithBot ℕ∞)) ≤ d := hdcomp.2 hmem
    have hle' : d ≤ (((n : ℕ∞) : WithBot ℕ∞)) := by
      simpa [← hdx] using hle
    calc
      krullDimensionAt q' = d := hdx
      _ = (((n : ℕ∞) : WithBot ℕ∞)) := le_antisymm hle' hge
  have hcodim :=
    Formalization.Books.Algebra.Unit116.codimension
      (k := k) (S' := P.Ring) (S := S)
      (f := MvPolynomial.aeval P.val) (hf := P.aeval_val_surjective) (p := q)
  have halg : algebraMap P.Ring S =
      MvPolynomial.aeval (R := k) P.val := P.algebraMap_eq
  have hcomp :
      PrimeSpectrum.comap (MvPolynomial.aeval P.val).toRingHom q = q' := by
    rw [AlgHom.toRingHom_eq_coe, ← halg]
    exact hcorresponding
  rw [hcomp] at hcodim
  have hcodim0 :
      WithBot.unbotD 0 (krullDimensionAt q') -
          WithBot.unbotD 0 (krullDimensionAt q) =
        q'.asIdeal.height - q.asIdeal.height := by
    simpa using hcodim
  have hcodim' :
      WithBot.unbotD 0 (krullDimensionAt q') -
          WithBot.unbotD 0 (krullDimensionAt q) = (c : ℕ∞) := by
    calc
      _ = q'.asIdeal.height - q.asIdeal.height := hcodim0
      _ = (c : ℕ∞) := by
        have hqheight : q.asIdeal.height ≠ (⊤ : ℕ∞) :=
          Ideal.height_ne_top_of_isPrime
        rw [hc, add_comm]
        exact (ENat.addLECancellable_of_ne_top hqheight).add_tsub_cancel_right
  rw [hpoly] at hcodim'
  simp only [WithBot.unbotD_coe] at hcodim'
  have hnonneg : 0 ≤ krullDimensionAt q := by
    rw [Formalization.Books.Topology.Unit10.krullDimensionAt]
    refine le_iInf fun U => ?_
    change 0 ≤ topologicalKrullDim (U : Set (PrimeSpectrum S))
    rw [topologicalKrullDim, Order.krullDim_nonneg_iff]
    let x : (U : Set (PrimeSpectrum S)) := ⟨q, U.mem⟩
    exact ⟨⟨closure ({x} : Set (U : Set (PrimeSpectrum S))),
      isIrreducible_singleton.closure,
      isClosed_closure⟩⟩
  have hnebot : krullDimensionAt q ≠ (⊥ : WithBot ℕ∞) := by
    exact ne_of_gt (lt_of_lt_of_le (WithBot.bot_lt_coe 0) hnonneg)
  obtain ⟨x, hx⟩ := WithBot.ne_bot_iff_exists.mp hnebot
  have hupper : krullDimensionAt q ≤ (((n : ℕ∞) : WithBot ℕ∞)) := by
    have hdim : ringKrullDim S ≤ ringKrullDim P.Ring :=
      ringKrullDim_le_of_surjective (algebraMap P.Ring S) P.algebraMap_surjective
    have hdim_top : topologicalKrullDim (PrimeSpectrum S) ≤
        (((n : ℕ∞) : WithBot ℕ∞)) := by
      calc
        topologicalKrullDim (PrimeSpectrum S) = ringKrullDim S :=
          PrimeSpectrum.topologicalKrullDim_eq_ringKrullDim S
        _ ≤ ringKrullDim P.Ring := hdim
        _ = topologicalKrullDim (PrimeSpectrum P.Ring) :=
          (PrimeSpectrum.topologicalKrullDim_eq_ringKrullDim P.Ring).symm
        _ = (((n : ℕ∞) : WithBot ℕ∞)) := hglobal
    have hunivS : topologicalKrullDim (Set.univ : Set (PrimeSpectrum S)) =
        topologicalKrullDim (PrimeSpectrum S) :=
      IsHomeomorph.topologicalKrullDim_eq _
        (Homeomorph.Set.univ (PrimeSpectrum S)).isHomeomorph
    apply (krullDimensionAt_le q isOpen_univ (mem_univ q)).trans
    rw [hunivS]
    exact hdim_top
  have hxle : x ≤ (n : ℕ∞) := by
    apply WithBot.coe_le_coe.mp
    simpa [hx] using hupper
  have hxtop : x ≠ (⊤ : ℕ∞) :=
    ne_of_lt (lt_of_le_of_lt hxle (WithTop.coe_lt_top n))
  obtain ⟨y, hy⟩ := ENat.ne_top_iff_exists.mp hxtop
  have hy_le : y ≤ n := by
    rw [← hy] at hxle
    exact WithTop.coe_le_coe.mp hxle
  rw [← hx, WithBot.unbotD_coe] at hcodim'
  rw [← hy] at hcodim'
  have hnat : n - y = c := by
    apply Nat.cast_injective (R := ℕ∞)
    simpa only [← ENat.natCast_sub] using hcodim'
  have hy_eq : y = n - c := by omega
  rw [← hx, ← hy, hy_eq]

theorem global_complete_intersection_localize
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    (hS : IsGlobalCompleteIntersection k S) (g : S) :
    IsGlobalCompleteIntersection k (Localization.Away g) := by
  sorry

theorem local_complete_intersection_localize
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    (hS : IsLocalCompleteIntersection k S) (g : S) :
    IsLocalCompleteIntersection k (Localization.Away g) := by
  sorry

theorem local_complete_intersection_isCohenMacaulay
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    (hS : IsLocalCompleteIntersection k S) :
    letI : Algebra.FiniteType k S :=
      (RingHom.finiteType_algebraMap.mp hS.1)
    letI : IsNoetherianRing S := Algebra.FiniteType.isNoetherianRing k S
    Formalization.Books.Algebra.Unit104.IsCohenMacaulayRing S := by
  sorry

/-! ## The local presentation and its conormal module -/

abbrev LocalizedPresentationRing
    {k S : Type u} [Field k] [CommRing S] [Algebra k S] {n : ℕ}
    (P : PolynomialPresentation k S n) (q' : PrimeSpectrum P.Ring) :=
  Localization.AtPrime q'.asIdeal

def LocalizedPresentationIdeal
    {k S : Type u} [Field k] [CommRing S] [Algebra k S] {n : ℕ}
    (P : PolynomialPresentation k S n) (q' : PrimeSpectrum P.Ring) :
    Ideal (LocalizedPresentationRing P q') :=
  Ideal.map (algebraMap P.Ring (LocalizedPresentationRing P q')) P.ker

abbrev LocalizedPresentationQuotient
    {k S : Type u} [Field k] [CommRing S] [Algebra k S] {n : ℕ}
    (P : PolynomialPresentation k S n) (q' : PrimeSpectrum P.Ring) :=
  LocalizedPresentationRing P q' ⧸ LocalizedPresentationIdeal P q'

abbrev LocalizedPresentationConormal
    {k S : Type u} [Field k] [CommRing S] [Algebra k S] {n : ℕ}
    (P : PolynomialPresentation k S n) (q' : PrimeSpectrum P.Ring) :=
  Ideal.Cotangent (LocalizedPresentationIdeal P q')

def GeneratesModuloMaximalIdeal
    {R : Type u} [CommRing R] [IsLocalRing R]
    (I : Ideal R) (n : ℕ) (x : Fin n → R) : Prop :=
  (∀ i, x i ∈ I) ∧
    Ideal.span (Set.range x) ⊔ IsLocalRing.maximalIdeal R * I = I

/- The five conditions in Lemma `lemma-lci` are kept as a reusable list. -/
def PresentationLocalCompleteIntersectionConditions
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    {n : ℕ} (P : PolynomialPresentation k S n)
    (q : PrimeSpectrum S) (q' : PrimeSpectrum P.Ring) (c : ℕ) : Prop :=
  List.TFAE
    [ (∃ g : S, g ∉ q.asIdeal ∧
          IsGlobalCompleteIntersection k (Localization.Away g)),
      IsIdealGeneratedByElements (LocalizedPresentationIdeal P q') c,
      IsModuleGeneratedByElements (LocalizedPresentationQuotient P q')
        (LocalizedPresentationConormal P q') c,
      IsFreeOfRank (LocalizedPresentationQuotient P q')
        (LocalizedPresentationConormal P q') c,
      IsIdealGeneratedByRegularSequence (LocalizedPresentationIdeal P q') ]

theorem local_complete_intersection_at_presentation_prime
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    {n : ℕ} (P : PolynomialPresentation k S n)
    (q : PrimeSpectrum S) (q' : PrimeSpectrum P.Ring)
    (hcorresponding :
      PrimeSpectrum.comap (algebraMap P.Ring S) q = q')
    (c : ℕ)
    (hc : q'.asIdeal.height = q.asIdeal.height + (c : ℕ∞)) :
    PresentationLocalCompleteIntersectionConditions P q q' c := by
  sorry

theorem regular_sequence_of_minimal_conormal_generators
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    {n : ℕ} (P : PolynomialPresentation k S n)
    (q : PrimeSpectrum S) (q' : PrimeSpectrum P.Ring)
    (hcorresponding :
      PrimeSpectrum.comap (algebraMap P.Ring S) q = q')
    (c : ℕ)
    (hc : q'.asIdeal.height = q.asIdeal.height + (c : ℕ∞))
    (hlocal : ∃ g : S, g ∉ q.asIdeal ∧
      IsGlobalCompleteIntersection k (Localization.Away g))
    (x : Fin c → LocalizedPresentationRing P q')
    (hx : GeneratesModuloMaximalIdeal
      (LocalizedPresentationIdeal P q') c x) :
    RingTheory.Sequence.IsRegular (LocalizedPresentationRing P q')
      (List.ofFn x) := by
  sorry

/-! ## Complete intersections as local rings -/

def IsCompleteIntersection
    (k S : Type u) [Field k] [CommRing S] [Algebra k S]
    [IsLocalRing S] : Prop :=
  RingHom.EssFiniteType (algebraMap k S) ∧
    ∃ (R : Type u) (hR : CommRing R) (hA : Algebra k R)
      (hreg : @IsRegularLocalRing R hR),
      letI : CommRing R := hR
      letI : Algebra k R := hA
      letI : IsRegularLocalRing R := hreg
      ∃ fs : List R,
        RingHom.EssFiniteType (algebraMap k R) ∧
          (∀ f ∈ fs, f ∈ IsLocalRing.maximalIdeal R) ∧
          RingTheory.Sequence.IsRegular R fs ∧
            Nonempty (S ≃ₐ[k] (R ⧸ Ideal.ofList fs))

/- The Cohen structure theorem is a cited prerequisite for extending this
   essentially-finite-type definition to complete Noetherian local rings; the
   chapter does not introduce a separate Lean completion presentation here. -/

theorem complete_intersection_well_defined
    {A B C : Type u} [CommRing A] [CommRing B] [CommRing C]
    [IsLocalRing C]
    [IsRegularLocalRing A] [IsRegularLocalRing B]
    (f : A →+* B) (g : B →+* C)
    [IsLocalHom f] [IsLocalHom g]
    (hf : Function.Surjective f) (hg : Function.Surjective g) :
    List.TFAE
      [ IsIdealGeneratedByRegularSequence (RingHom.ker (g.comp f)),
        IsGeneratedByDimensionDifference A C (RingHom.ker (g.comp f)),
        IsIdealGeneratedByRegularSequence (RingHom.ker g),
        IsGeneratedByDimensionDifference B C (RingHom.ker g) ] := by
  sorry

def ExistsRegularLocalSurjectionWithRegularKernel
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [IsLocalRing S] : Prop :=
  ∃ (R : Type u) (hR : CommRing R) (hA : Algebra k R)
    (hreg : @IsRegularLocalRing R hR),
    letI : CommRing R := hR
    letI : Algebra k R := hA
    letI : IsRegularLocalRing R := hreg
    ∃ f : R →ₐ[k] S,
      Formalization.Books.Algebra.Unit54.RingHom.EssFinitePresentation
        (algebraMap k R) ∧
        Function.Surjective f ∧
          IsIdealGeneratedByRegularSequence (RingHom.ker f.toRingHom)

def ExistsRegularLocalSurjectionWithDimensionKernel
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [IsLocalRing S] : Prop :=
  ∃ (R : Type u) (hR : CommRing R) (hA : Algebra k R)
    (hreg : @IsRegularLocalRing R hR),
    letI : CommRing R := hR
    letI : Algebra k R := hA
    letI : IsRegularLocalRing R := hreg
    ∃ f : R →ₐ[k] S,
      Formalization.Books.Algebra.Unit54.RingHom.EssFinitePresentation
        (algebraMap k R) ∧
        Function.Surjective f ∧
          IsGeneratedByDimensionDifference R S (RingHom.ker f.toRingHom)

def ExistsGlobalCompleteIntersectionLocalization
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [IsLocalRing S] : Prop :=
  ∃ (A : Type u) (hA : CommRing A) (hAk : Algebra k A),
    letI : CommRing A := hA
    letI : Algebra k A := hAk
    ∃ a : PrimeSpectrum A,
      Nonempty (S ≃ₐ[k] Localization.AtPrime a.asIdeal) ∧
        IsGlobalCompleteIntersection k A

def ExistsLocalCompleteIntersectionLocalization
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [IsLocalRing S] : Prop :=
  ∃ (A : Type u) (hA : CommRing A) (hAk : Algebra k A),
    letI : CommRing A := hA
    letI : Algebra k A := hAk
    ∃ a : PrimeSpectrum A,
      Nonempty (S ≃ₐ[k] Localization.AtPrime a.asIdeal) ∧
        IsLocalCompleteIntersection k A

theorem local_complete_intersection_characterization
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [IsLocalRing S] :
    List.TFAE
      [ IsCompleteIntersection k S,
        (∀ (R : Type u) [CommRing R] [Algebra k R]
            [IsRegularLocalRing R] (f : R →ₐ[k] S),
          Formalization.Books.Algebra.Unit54.RingHom.EssFinitePresentation
              (algebraMap k R) →
            Function.Surjective f →
              IsIdealGeneratedByRegularSequence (RingHom.ker f.toRingHom)),
        ExistsRegularLocalSurjectionWithDimensionKernel (k := k) (S := S),
        ExistsGlobalCompleteIntersectionLocalization (k := k) (S := S),
        ExistsLocalCompleteIntersectionLocalization (k := k) (S := S) ] := by
  sorry

/-! ## Points of a finite-type algebra -/

def PresentationIsLocalCompleteIntersectionAtPrime
    (k S : Type u) [Field k] [CommRing S] [Algebra k S]
    (q : PrimeSpectrum S) : Prop :=
  ∀ (n : ℕ) (P : PolynomialPresentation k S n)
    (q' : PrimeSpectrum P.Ring),
    PrimeSpectrum.comap (algebraMap P.Ring S) q = q' →
      ∃ c : ℕ,
        q'.asIdeal.height = q.asIdeal.height + (c : ℕ∞) ∧
          PresentationLocalCompleteIntersectionConditions P q q' c ∧
            (∃ g : S, g ∉ q.asIdeal ∧
              IsGlobalCompleteIntersection k (Localization.Away g))

theorem local_complete_intersection_at_prime_characterization
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [Algebra.FiniteType k S]
    (q : PrimeSpectrum S) :
    List.TFAE
      [ IsCompleteIntersection k (Localization.AtPrime q.asIdeal),
        ∃ g : S, g ∉ q.asIdeal ∧
          IsLocalCompleteIntersection k (Localization.Away g),
        ∃ g : S, g ∉ q.asIdeal ∧
          IsGlobalCompleteIntersection k (Localization.Away g),
        PresentationIsLocalCompleteIntersectionAtPrime k S q ] := by
  sorry

theorem local_complete_intersection_global_characterization
    {k S : Type u} [Field k] [CommRing S] [Algebra k S]
    [Algebra.FiniteType k S] :
    List.TFAE
      [ IsLocalCompleteIntersection k S,
        (∀ q : PrimeSpectrum S,
          IsCompleteIntersection k (Localization.AtPrime q.asIdeal)),
        (∀ m : MaximalSpectrum S,
          IsCompleteIntersection k (Localization.AtPrime m.asIdeal)) ] := by
  sorry

/-! ## Change of the base field -/

theorem complete_intersection_at_prime_field_change
    {k K S : Type u} [Field k] [Field K] [CommRing S]
    [Algebra k S] [Algebra k K] [Algebra.FiniteType k S]
    (qK : PrimeSpectrum (K ⊗[k] S)) (q : PrimeSpectrum S)
    (hlying :
      PrimeSpectrum.comap
          (Algebra.TensorProduct.includeRight (R := k) (A := K) (B := S)).toRingHom qK =
        q) :
    IsCompleteIntersection k (Localization.AtPrime q.asIdeal) ↔
      IsCompleteIntersection K (Localization.AtPrime qK.asIdeal) := by
  sorry

theorem local_complete_intersection_field_change
    {k K S : Type u} [Field k] [Field K] [CommRing S]
    [Algebra k S] [Algebra k K] [Algebra.FiniteType k S] :
    IsLocalCompleteIntersection k S ↔
      IsLocalCompleteIntersection K (K ⊗[k] S) := by
  sorry

/-! ## The initial permanence lemma -/

abbrev SpecialFiber
    {R S : Type u} [CommRing R] [CommRing S] [IsLocalRing R]
    (rS : R →+* S) :=
  S ⧸ Ideal.map rS (IsLocalRing.maximalIdeal R)

def SpecialFiberIdeal
    {R S : Type u} [CommRing R] [CommRing S] [IsLocalRing R]
    (rS : R →+* S) (J : Ideal S) : Ideal (SpecialFiber rS) :=
  Ideal.map (Ideal.Quotient.mk _) J

theorem lci_permanence_initial
    {R S A B : Type u} [CommRing R] [CommRing S] [CommRing A] [CommRing B]
    [IsLocalRing S] [IsLocalRing A] [IsLocalRing B]
    [IsRegularLocalRing R]
    (rS : R →+* S) (rA : R →+* A) (sB : S →+* B) (aB : A →+* B)
    [IsLocalHom rS] [IsLocalHom rA] [IsLocalHom sB] [IsLocalHom aB]
    (hcomm : aB.comp rA = sB.comp rS)
    (I : Ideal R) (J : Ideal S)
    (hrA : Function.Surjective rA) (hsB : Function.Surjective sB)
    (hkerI : RingHom.ker rA = I) (hkerJ : RingHom.ker sB = J)
    (hSbar : IsRegularLocalRing (SpecialFiber rS))
    (hJ : IsIdealGeneratedByRegularSequence (SpecialFiberIdeal rS J))
    (hflatA : RingHom.Flat aB) (hflatS : RingHom.Flat rS) :
    IsIdealGeneratedByRegularSequence I := by
  sorry

end

end Formalization.Books.Algebra.Unit135
