import Mathlib.Algebra.DualNumber
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.Algebra.ZMod
import Mathlib.RingTheory.Flat.Basic
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Exercises, Chapter 5: Flat ring maps

This file records the three flat-deformation exercises.  The dual-number
construction uses Mathlib's canonical `DualNumber`; the polynomial quotients
and special fibres use the canonical ideal-quotient and `ZMod` APIs.
-/

noncomputable section

universe u v

namespace Formalization.Books.Exercises.Unit05

open scoped TensorProduct

/-! ## Dual-number deformations -/

/-- Mathlib's canonical implementation of the ring `k[ε] = k[x]/(x²)`. -/
abbrev dualNumberRing (k : Type u) [Field k] := DualNumber k

/-- The dual-number element `ε`. -/
def dualNumberEpsilon (k : Type u) [Field k] : dualNumberRing k :=
  DualNumber.eps

/-- The ideal `εB` in a `k[ε]`-algebra `B`. -/
def dualNumberIdeal
    (k B : Type u) [Field k] [CommRing B]
    [Algebra (dualNumberRing k) B] : Ideal B :=
  Ideal.span {algebraMap (dualNumberRing k) B (dualNumberEpsilon k)}

/-- The special fibre `B/εB`. -/
abbrev dualNumberSpecialFiber
    (k B : Type u) [Field k] [CommRing B]
    [Algebra (dualNumberRing k) B] [Algebra k B] :=
  B ⧸ dualNumberIdeal k B

/-- A flat `k[ε]`-deformation of a `k`-algebra `A`. -/
def IsFlatDualNumberDeformation
    (k A B : Type u) [Field k] [CommRing A] [CommRing B]
    [Algebra k A] [Algebra (dualNumberRing k) B] [Algebra k B]
    [IsScalarTower k (dualNumberRing k) B] : Prop :=
  Module.Flat (dualNumberRing k) B ∧
    Nonempty (A ≃ₐ[k] dualNumberSpecialFiber k B)

/-- The canonical base-change deformation `A ⊗[k] k[ε]`. -/
abbrev dualNumberBaseChange
    (k A : Type u) [Field k] [CommRing A] [Algebra k A] :=
  A ⊗[k] dualNumberRing k

/-- The `k[ε]`-algebra structure on the canonical base-change deformation. -/
@[instance_reducible] noncomputable def dualNumberBaseChangeAlgebra
    (k A : Type u) [Field k] [CommRing A] [Algebra k A] :
    Algebra (dualNumberRing k) (dualNumberBaseChange k A) :=
  Algebra.TensorProduct.rightAlgebra

/-- The base-change construction is a flat deformation with special fibre `A`.
-/
theorem dualNumber_baseChange_is_deformation
    (k A : Type u) [Field k] [CommRing A] [Algebra k A] :
    letI : Algebra (dualNumberRing k) (dualNumberBaseChange k A) :=
      dualNumberBaseChangeAlgebra k A
    IsFlatDualNumberDeformation k A (dualNumberBaseChange k A) := by
  sorry

/-! ## Polynomial lifts from `ℤ/p²ℤ` -/

/-- The quotient by the ideal generated by a scalar `r`; this is the source's
notation `B/rB`. -/
abbrev principalSpecialFiber
    {R : Type u} {B : Type v} [CommRing R] [CommRing B] [Algebra R B] (r : R) : Type v :=
  B ⧸ Ideal.span {algebraMap R B r}

/-- The ideal `(x₁^p, …, x₆^p)` in a six-variable polynomial ring. -/
def sixVariablePowerIdeal
    (p : ℕ) (R : Type u) [CommRing R] :
    Ideal (MvPolynomial (Fin 6) R) :=
  Ideal.span (Set.range (fun i : Fin 6 => (MvPolynomial.X i : MvPolynomial (Fin 6) R) ^ p))

/-- The characteristic-`p` algebra in the second deformation exercise. -/
abbrev sixVariablePowerAlgebra (p : ℕ) :=
  MvPolynomial (Fin 6) (ZMod p) ⧸ sixVariablePowerIdeal p (ZMod p)

/-- The evident lift of the characteristic-`p` algebra to `ℤ/p²ℤ`. -/
abbrev sixVariablePowerLift (p : ℕ) :=
  MvPolynomial (Fin 6) (ZMod (p ^ 2)) ⧸
    sixVariablePowerIdeal p (ZMod (p ^ 2))

/-- The special fibre of the evident lift. -/
abbrev sixVariablePowerLiftSpecialFiber (p : ℕ) :=
  principalSpecialFiber (R := ZMod (p ^ 2)) (B := sixVariablePowerLift p)
    (p : ZMod (p ^ 2))

/-- The displayed polynomial lift is flat over `ℤ/p²ℤ`. -/
theorem sixVariablePowerLift_flat (p : ℕ) (hp : Nat.Prime p) :
    Module.Flat (ZMod (p ^ 2)) (sixVariablePowerLift p) := by
  sorry

/-- Its reduction modulo `p` is the characteristic-`p` algebra in the source.
-/
theorem sixVariablePowerLift_specialFiber (p : ℕ) (hp : Nat.Prime p) :
    Nonempty (sixVariablePowerLiftSpecialFiber p ≃+* sixVariablePowerAlgebra p) := by
  sorry

/-- The second exercise supplies a flat `ℤ/p²ℤ`-algebra lifting the displayed
characteristic-`p` algebra. -/
theorem exists_flat_zmodSquare_lift (p : ℕ) (hp : Nat.Prime p) :
    ∃ (B : Type) (_ : CommRing B) (_ : Algebra (ZMod (p ^ 2)) B),
      Module.Flat (ZMod (p ^ 2)) B ∧
        Nonempty
          (principalSpecialFiber (R := ZMod (p ^ 2)) (B := B) (p : ZMod (p ^ 2))
            ≃+* sixVariablePowerAlgebra p) := by
  refine ⟨sixVariablePowerLift p, inferInstance, inferInstance, ?_⟩
  exact ⟨sixVariablePowerLift_flat p hp, sixVariablePowerLift_specialFiber p hp⟩

/-! ## The quadratic obstruction -/

/-- The six-variable quadratic relation from the third deformation exercise.
-/
def sixVariableQuadratic (R : Type u) [CommRing R] : MvPolynomial (Fin 6) R :=
  MvPolynomial.X (0 : Fin 6) * MvPolynomial.X (1 : Fin 6) +
    MvPolynomial.X (2 : Fin 6) * MvPolynomial.X (3 : Fin 6) +
      MvPolynomial.X (4 : Fin 6) * MvPolynomial.X (5 : Fin 6)

/-- The ideal `(x₁^p,…,x₆^p,x₁x₂+x₃x₄+x₅x₆)`. -/
def sixVariableQuadraticIdeal
    (p : ℕ) (R : Type u) [CommRing R] :
    Ideal (MvPolynomial (Fin 6) R) :=
  Ideal.span
    (Set.range (fun i : Fin 6 => (MvPolynomial.X i : MvPolynomial (Fin 6) R) ^ p) ∪
      {sixVariableQuadratic R})

/-- The characteristic-`p` algebra with the quadratic relation. -/
abbrev sixVariableQuadraticAlgebra (p : ℕ) :=
  MvPolynomial (Fin 6) (ZMod p) ⧸ sixVariableQuadraticIdeal p (ZMod p)

/-- No flat `ℤ/p²ℤ`-algebra has the quadratic algebra above as its special
fibre. -/
theorem no_flat_sixVariableQuadratic_lift
    (p : ℕ) (hp : Nat.Prime p) :
    ¬ ∃ (B : Type) (_ : CommRing B) (_ : Algebra (ZMod (p ^ 2)) B),
      Module.Flat (ZMod (p ^ 2)) B ∧
        Nonempty
          (principalSpecialFiber (R := ZMod (p ^ 2)) (B := B) (p : ZMod (p ^ 2))
            ≃+* sixVariableQuadraticAlgebra p) := by
  sorry

/-- In particular, the characteristic-two algebra in the source has no flat
lift to a `ℤ/4ℤ`-algebra. -/
theorem no_flat_zmodFour_sixVariableQuadratic_lift :
    ¬ ∃ (B : Type) (_ : CommRing B) (_ : Algebra (ZMod 4) B),
      Module.Flat (ZMod 4) B ∧
        Nonempty
          (principalSpecialFiber (R := ZMod 4) (B := B) (2 : ZMod 4)
            ≃+* sixVariableQuadraticAlgebra 2) := by
  exact no_flat_sixVariableQuadratic_lift 2 Nat.prime_two

end Formalization.Books.Exercises.Unit05
