import Mathlib.Algebra.Homology.Homotopy
import Mathlib.Data.Int.Interval
import Mathlib.Algebra.Homology.QuasiIso
import Mathlib.Algebra.Homology.DerivedCategory.Basic
import Mathlib.Algebra.Category.ModuleCat.Basic
import Mathlib.Algebra.Module.FinitePresentation
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.RingTheory.FinitePresentation
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.LinearAlgebra.Basis.Basic
import Mathlib.LinearAlgebra.Determinant
import Mathlib.RingTheory.Localization.Away.Basic
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.Localization.Module
import Mathlib.RingTheory.Spectrum.Prime.Basic

/-!
# More on Algebra, Chapter 97: perfect complexes and the eta operator

The source fixes bases on a bounded complex of finite free modules in order
to write the ideals generated by minors.  We retain that finite-free data
explicitly, so the determinant ideal below is a genuine construction rather
than an uninterpreted predicate.  The eta operator itself was constructed in
the immediately preceding source section; its small interface is recorded
here because that section has no assigned Lean file in this project.
-/

noncomputable section

open CategoryTheory
open CategoryTheory.Limits
open Module
open scoped BigOperators

universe u

namespace Formalization.Books.MoreAlgebra.Unit97

abbrev Comp (R : Type u) [CommRing R] :=
  CochainComplex (ModuleCat.{u} R) ℤ

def QuasiIsomorphicComplexes {R : Type u} [CommRing R]
    (M N : Comp R) : Prop :=
  ∃ (hM : ∀ i : ℤ, HomologicalComplex.HasHomology M i)
    (hN : ∀ i : ℤ, HomologicalComplex.HasHomology N i),
    letI : ∀ i : ℤ, HomologicalComplex.HasHomology M i := hM
    letI : ∀ i : ℤ, HomologicalComplex.HasHomology N i := hN
    ∃ q : M ⟶ N, QuasiIso q

def IsBoundedComplex {R : Type u} [CommRing R] (M : Comp R) : Prop :=
  ∃ a b : ℤ, ∀ i : ℤ, i < a ∨ b < i → IsZero (M.X i)

structure BoundedFiniteFreeComplex (R : Type u) [CommRing R] where
  complex : Comp R
  rank : ℤ → ℕ
  basis : ∀ i : ℤ, Basis (Fin (rank i)) R (complex.X i : Type u)
  bounded : IsBoundedComplex complex

abbrev term {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (i : ℤ) := M.complex.X i

def differentialMatrix {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (i : ℤ) :
    Matrix (Fin (M.rank (i + 1))) (Fin (M.rank i)) R :=
  LinearMap.toMatrix (M.basis i) (M.basis (i + 1))
    (M.complex.d i (i + 1)).hom

def augmentedMatrix {R : Type u} [CommRing R] {r s : ℕ} (f : R)
    (D : Matrix (Fin s) (Fin r) R) :
    Matrix (Fin (r + s)) (Fin r) R :=
  fun k j =>
    if hk : k.1 < r then
      if hkj : k.1 = j.1 then f else 0
    else
      D ⟨k.1 - r, by omega⟩ j

def matrixMinorIdeal {R : Type u} [CommRing R] {m n : ℕ}
    (T : Matrix (Fin m) (Fin n) R) (k : ℕ) :
    Ideal R :=
  Ideal.span (Set.range fun p : (Fin k → Fin m) × (Fin k → Fin n) =>
    (T.submatrix p.1 p.2).det)

def etaIdeal {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R) (i : ℤ) : Ideal R :=
  matrixMinorIdeal
    (augmentedMatrix f (differentialMatrix M i)) (M.rank i)

def alternatingRankSum {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (i b : ℤ) : ℤ :=
  Finset.sum (Finset.Icc i b) fun j =>
    (-1 : ℤ) ^ Int.toNat (j - i) * (M.rank j : ℤ)

theorem etaIdeal_well_defined {R : Type u} [CommRing R]
    (M N : BoundedFiniteFreeComplex R) (f : R) (i : ℤ)
    (_hMN : QuasiIsomorphicComplexes M.complex N.complex)
    (m n : ℕ) (b : ℤ)
    (hbalance : (m : ℤ) + alternatingRankSum M i b =
      (n : ℤ) + alternatingRankSum N i b) :
    Ideal.span {f ^ m} * etaIdeal M f i =
      Ideal.span {f ^ n} * etaIdeal N f i := by
  sorry

theorem etaIdeal_contains_power {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R) (i : ℤ) :
    f ^ M.rank i ∈ etaIdeal M f i := by
  sorry

def IsNonzerodivisor {R : Type u} [CommRing R] (f : R) : Prop :=
  Function.Injective (f • (LinearMap.id : R →ₗ[R] R))

def IsFTorsionFree {R : Type u} [CommRing R] (f : R)
    (M : Type u) [AddCommGroup M] [Module R M] : Prop :=
  Function.Injective (f • (LinearMap.id : M →ₗ[R] M))

def IsFTorsionFreeComplex {R : Type u} [CommRing R]
    (f : R) (M : Comp R) : Prop :=
  ∀ i : ℤ, IsFTorsionFree f (M.X i : Type u)

/- The output of the preceding construction, with its component comparison
made explicit.  `EtaOperatorData` is the dependency interface used below. -/
structure EtaOperatorData (R : Type u) [CommRing R] (f : R) where
  eta : ∀ (M : Comp R), IsFTorsionFreeComplex f M → Comp R

noncomputable def etaComplex {R : Type u} [CommRing R] {f : R}
    (E : EtaOperatorData R f) (M : Comp R)
    (hM : IsFTorsionFreeComplex f M) : Comp R :=
  E.eta M hM

noncomputable def localizedFUnit {R : Type u} [CommRing R] (f : R) :
    (Localization (Submonoid.powers f))ˣ :=
  (IsLocalization.map_units (Localization (Submonoid.powers f))
    (⟨f, 1, by simp⟩ : Submonoid.powers f)).unit

noncomputable def localizedFPower {R : Type u} [CommRing R]
    (f : R) (i : ℤ) : Localization (Submonoid.powers f) :=
  match i with
  | Int.ofNat n => (localizedFUnit f) ^ n
  | Int.negSucc n => (localizedFUnit f)⁻¹ ^ (n + 1)

noncomputable def localizedFPowerMap {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :
    (term M i : Type u) →ₗ[R]
      LocalizedModule (Submonoid.powers f) (term M i : Type u) :=
  ((LinearMap.lsmul (Localization (Submonoid.powers f))
      (LocalizedModule (Submonoid.powers f) (term M i : Type u))
      (localizedFPower f i)).restrictScalars R).comp
    (LocalizedModule.mkLinearMap (Submonoid.powers f) (term M i : Type u))

noncomputable def fPowerSubmodule {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :
    Submodule R (LocalizedModule (Submonoid.powers f) (term M i : Type u)) :=
  Submodule.map (localizedFPowerMap f M i) ⊤

noncomputable def localizedDifferential {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i j : ℤ) :
    LocalizedModule (Submonoid.powers f) (term M i : Type u) →ₗ[R]
      LocalizedModule (Submonoid.powers f) (term M j : Type u) :=
  (LocalizedModule.map (Submonoid.powers f) (M.complex.d i j).hom).restrictScalars R

noncomputable def etaTermSubmodule {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :
    Submodule R (LocalizedModule (Submonoid.powers f) (term M i : Type u)) :=
  fPowerSubmodule f M i ⊓
    (fPowerSubmodule f M (i + 1)).comap
      (localizedDifferential f M i (i + 1))

abbrev fPowerModule {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :=
  fPowerSubmodule f M i

abbrev etaTermModule {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :=
  (etaTermSubmodule f M i : Type u)

def IsSplitInjection {R M N : Type u} [CommRing R] [AddCommGroup M]
    [Module R M] [AddCommGroup N] [Module R N] (s : M →ₗ[R] N) : Prop :=
  Function.Injective s ∧ ∃ r : N →ₗ[R] M, r.comp s = LinearMap.id

noncomputable def etaTermInclusion {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :
    etaTermModule f M i →ₗ[R]
      fPowerModule f M i × fPowerModule f M (i + 1) :=
  { toFun := fun x =>
      ⟨⟨x.1, x.2.1⟩,
        ⟨localizedDifferential f M i (i + 1) x.1, x.2.2⟩⟩
    map_add' := by
      intro x y
      ext <;> simp
    map_smul' := by
      intro a x
      ext <;> simp }

def FiniteLocallyFreeOfRank (R M : Type u) [CommRing R]
    [AddCommGroup M] [Module R M] (r : ℕ) : Prop :=
  ∃ s : Set R, Ideal.span s = ⊤ ∧
    ∀ g ∈ s,
      Nonempty
        (LocalizedModule.Away g M ≃ₗ[Localization.Away g]
          (Fin r →₀ Localization.Away g))

theorem eta_change_unit {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R)
    (_hf : IsNonzerodivisor f) (u : Rˣ) (i : ℤ) :
    etaIdeal M f i = etaIdeal M ((u : R) * f) i := by
  sorry

def mapMatrix {R S : Type u} [CommRing R] [CommRing S]
    {m n : ℕ} (φ : R →+* S) (T : Matrix (Fin m) (Fin n) R) :
    Matrix (Fin m) (Fin n) S :=
  fun i j => φ (T i j)

def baseChangeEtaIdeal {R S : Type u} [CommRing R] [CommRing S]
    (M : BoundedFiniteFreeComplex R) (f : R) (φ : R →+* S) (i : ℤ) : Ideal S :=
  matrixMinorIdeal
    (mapMatrix φ (augmentedMatrix f (differentialMatrix M i))) (M.rank i)

theorem etaIdeal_base_change_pre {R S : Type u} [CommRing R] [CommRing S]
    (M : BoundedFiniteFreeComplex R) (f : R) (φ : R →+* S) (g : S)
    (_hφ : φ f = g) (_hg : IsNonzerodivisor g) (i : ℤ) :
    Ideal.map φ (etaIdeal M f i) = baseChangeEtaIdeal M f φ i := by
  sorry

def IsGeneratedByPower {R : Type u} [CommRing R]
    (I : Ideal R) (f : R) : Prop :=
  ∃ n : ℕ, I = Ideal.span {f ^ n}

structure CohomologyData {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) where
  module : ℤ → ModuleCat.{u} R

theorem etaIdeal_cohomology_free {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R) (_hf : IsNonzerodivisor f)
    (p : PrimeSpectrum R)
    (Coh : CohomologyData M)
    (_hcoh : ∀ i : ℤ, Module.Free R (Coh.module i : Type u)) (i : ℤ) :
    IsGeneratedByPower
      (Ideal.map (algebraMap R (Localization.AtPrime p.asIdeal)) (etaIdeal M f i))
      (algebraMap R (Localization.AtPrime p.asIdeal) f) := by
  sorry

theorem eta_locally_free {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R) (_hf : IsNonzerodivisor f)
    (_hprincipal : ∀ i : ℤ, (etaIdeal M f i).IsPrincipal) (i : ℤ) :
    FiniteLocallyFreeOfRank R (etaTermModule f M i) (M.rank i) ∧
      IsSplitInjection (etaTermInclusion f M i) := by
  sorry

structure EtaBaseChangeComparison {S : Type u} [CommRing S]
    {g : S} (E : EtaOperatorData S g)
    (N : BoundedFiniteFreeComplex S)
    (hN : IsFTorsionFreeComplex g N.complex) where
  baseChangedEta : Comp S
  comparison : Nonempty (baseChangedEta ≅ etaComplex E N.complex hN)

theorem eta_base_change {R S : Type u} [CommRing R] [CommRing S]
    {f : R} (g : S) (_E : EtaOperatorData R f) (E' : EtaOperatorData S g)
    (M : BoundedFiniteFreeComplex R)
    (_hM : IsFTorsionFreeComplex f M.complex) (_φ : R →+* S)
    (_hφ : _φ f = g) (_hbase : IsNonzerodivisor g)
    (N : BoundedFiniteFreeComplex S)
    (_hprincipal : ∀ i : ℤ, (etaIdeal M f i).IsPrincipal)
    (_hbaseM : IsFTorsionFreeComplex g N.complex) :
    Nonempty (EtaBaseChangeComparison E' N _hbaseM) := by
  sorry

/-! ## The direct-summand ideal and the `J_i` ideals -/

structure DirectSummandIdealData {R M N₁ N₂ : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] [AddCommGroup N₁] [Module R N₁]
    [AddCommGroup N₂] [Module R N₂]
    (s : M →ₗ[R] N₁ × N₂) where
  ideal : Ideal R
  finitelyGenerated : (ideal : Submodule R R).FG
  baseChangeProperty : ∀ {S : Type u} [CommRing S] (_φ : R →+* S), Prop
  universal : ∀ {S : Type u} [CommRing S] (φ : R →+* S),
    Ideal.map φ ideal = ⊥ ↔ baseChangeProperty φ

theorem directSummandIdeal_exists {R M N₁ N₂ : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] [AddCommGroup N₁] [Module R N₁]
    [AddCommGroup N₂] [Module R N₂]
    (s : M →ₗ[R] N₁ × N₂) (_hs : IsSplitInjection s) :
    Nonempty (DirectSummandIdealData s) := by
  sorry

noncomputable def directSummandIdeal {R M N₁ N₂ : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] [AddCommGroup N₁] [Module R N₁]
    [AddCommGroup N₂] [Module R N₂]
    (s : M →ₗ[R] N₁ × N₂) (hs : IsSplitInjection s) : Ideal R :=
  (Classical.choice (directSummandIdeal_exists s hs)).ideal

noncomputable def etaSummandIdeal {R : Type u} [CommRing R]
    {f : R} {M N₁ N₂ : Type u} [AddCommGroup M]
    [Module (R ⧸ Ideal.span {f}) M]
    [AddCommGroup N₁] [Module (R ⧸ Ideal.span {f}) N₁]
    [AddCommGroup N₂] [Module (R ⧸ Ideal.span {f}) N₂]
    (s : M →ₗ[R ⧸ Ideal.span {f}] N₁ × N₂)
    (hs : IsSplitInjection s) :
    Ideal (R ⧸ Ideal.span {f}) :=
  directSummandIdeal s hs

abbrev scalarQuotientModule {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) :=
  M ⧸ (Ideal.span {f} • (⊤ : Submodule R M))

noncomputable instance scalarQuotientModule.module {R M : Type u} [CommRing R]
    [AddCommGroup M] [Module R M] (f : R) :
    Module (R ⧸ Ideal.span {f})
      (scalarQuotientModule (R := R) (M := M) f) :=
  (Module.isTorsionBySet_quotient_ideal_smul
    (M := M) (I := Ideal.span {f})).module

abbrev etaReducedTermModule {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :=
  scalarQuotientModule (R := R) (M := etaTermModule f M i) f

abbrev etaReducedFirstTarget {R : Type u} [CommRing R]
    (f : R) (M : BoundedFiniteFreeComplex R) (i : ℤ) :=
  scalarQuotientModule (R := R) (M := fPowerModule f M i) f

structure EtaSummandIdealConstruction {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R) where
  injection : ∀ i : ℤ,
    etaReducedTermModule f M i →ₗ[R ⧸ Ideal.span {f}]
      (etaReducedFirstTarget f M i × etaReducedFirstTarget f M (i + 1))
  split : ∀ i : ℤ, IsSplitInjection (injection i)
  ideal : ∀ _i : ℤ, Ideal (R ⧸ Ideal.span {f})
  ideal_eq : ∀ i : ℤ,
    ideal i = etaSummandIdeal (injection i) (split i)

theorem eta_summand_ideal_exists {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R)
    (_hf : IsNonzerodivisor f)
    (_hprincipal : ∀ i : ℤ, (etaIdeal M f i).IsPrincipal) :
    Nonempty (EtaSummandIdealConstruction M f) := by
  sorry

def etaSummandIdealTotal {R : Type u} [CommRing R]
    (f : R)
    (J : ℤ → Ideal (R ⧸ Ideal.span {f})) :
    Ideal (R ⧸ Ideal.span {f}) :=
  sSup (Set.range J)

structure EtaBocksteinData {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R) where
  kernelLiftingAt : PrimeSpectrum R → ℤ → Prop
  bocksteinZeroAt : PrimeSpectrum R → ℤ → Prop
  summandIdealVanishesAt : PrimeSpectrum R → ℤ → Prop

def EtaVanishingLocus {R : Type u} [CommRing R]
  (M : BoundedFiniteFreeComplex R) (f : R)
    (β : EtaBocksteinData M f) : Set (PrimeSpectrum R) :=
  {p | f ∈ p.asIdeal ∧
    ∀ i : ℤ, β.kernelLiftingAt p i}

theorem eta_vanishing_locus_characterization {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R)
    (β : EtaBocksteinData M f) :
    EtaVanishingLocus M f β =
      {p | f ∈ p.asIdeal ∧ ∀ i : ℤ, β.bocksteinZeroAt p i} := by
  sorry

def IdealVanishesAtPrime {R : Type u} [CommRing R]
    (I : Ideal R) (p : PrimeSpectrum R) : Prop :=
  Ideal.map (algebraMap R (Localization.AtPrime p.asIdeal)) I = ⊥

abbrev etaQuotient {R : Type u} [CommRing R]
    (f : R) (J : ∀ _i : ℤ, Ideal (R ⧸ Ideal.span {f})) :=
  (R ⧸ Ideal.span {f}) ⧸ etaSummandIdealTotal f J

def etaQuotientMap {R : Type u} [CommRing R]
    (f : R) (J : ∀ _i : ℤ, Ideal (R ⧸ Ideal.span {f})) :
    (R ⧸ Ideal.span {f}) →+* etaQuotient f J :=
  Ideal.Quotient.mk (etaSummandIdealTotal f J)

structure EtaCohomologyData {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R)
    (J : ∀ _i : ℤ, Ideal (R ⧸ Ideal.span {f})) where
  module : ℤ → ModuleCat.{u} (etaQuotient f J)

def FiniteLocallyFreeCohomology {R : Type u} [CommRing R]
    (C : Type u) [CommRing C] (H : ℤ → ModuleCat.{u} C) : Prop :=
  ∀ i : ℤ, ∃ r : ℕ, FiniteLocallyFreeOfRank C (H i : Type u) r

theorem eta_summand_ideal_invariant {R : Type u} [CommRing R]
    (M N : BoundedFiniteFreeComplex R) (f : R)
    (_hMN : QuasiIsomorphicComplexes M.complex N.complex)
    (_hprincipal : ∀ i : ℤ, (etaIdeal M f i).IsPrincipal)
    (Jₘ : EtaSummandIdealConstruction M f)
    (Jₙ : EtaSummandIdealConstruction N f) (i : ℤ) :
    Jₘ.ideal i = Jₙ.ideal i := by
  sorry

theorem eta_vanishing_beta_plus {R : Type u} [CommRing R]
    (M : BoundedFiniteFreeComplex R) (f : R)
    (_hf : IsNonzerodivisor f)
    (_hprincipal : ∀ i : ℤ, (etaIdeal M f i).IsPrincipal)
    (J : EtaSummandIdealConstruction M f)
    (β : EtaBocksteinData M f)
    (Coh : CohomologyData M)
    (H : EtaCohomologyData M f J.ideal)
    (E : Set (PrimeSpectrum R))
    (_hE : E = EtaVanishingLocus M f β) :
    (etaSummandIdealTotal f J.ideal).FG ∧
      Function.Surjective (etaQuotientMap f J.ideal) ∧
      Algebra.FinitePresentation (R ⧸ Ideal.span {f}) (etaQuotient f J.ideal) ∧
      (∀ p ∈ E, ∀ i : ℤ, β.summandIdealVanishesAt p i) ∧
      (∀ p, f ∈ p.asIdeal →
        (∀ i : ℤ, Module.Free R (Coh.module i : Type u)) → p ∈ E) ∧
      FiniteLocallyFreeCohomology (R := R) (C := etaQuotient f J.ideal)
        (fun i => H.module i) := by
  sorry

end Formalization.Books.MoreAlgebra.Unit97
