import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.Algebra.MonoidAlgebra.NoZeroDivisors
import Mathlib.Algebra.Field.ZMod
import Mathlib.Data.ZMod.Basic
import Mathlib.LinearAlgebra.TensorProduct.Basic
import Mathlib.RingTheory.Ideal.Cotangent
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.Smooth.Basic
import Mathlib.RingTheory.RingHom.Smooth

/-!
# Examples, Chapter 41: A formally smooth non-flat ring map

This file formalizes the group-algebra example from the source section.  The
quotient `J / J²` is represented by Mathlib's canonical `Ideal.Cotangent`.
The infinitesimal lifting diagram in the source is represented by
`RingHom.FormallySmooth`; its square-zero quotient interface is already
provided by `Algebra.FormallySmooth.iff_comp_surjective`.
-/

noncomputable section

open scoped TensorProduct

namespace Formalization.«Books.Examples».Unit41

universe u v

/-! ## The group algebra and its augmentation -/

/-- The group algebra `k[ℚ]`, using the additive group structure on `ℚ`. -/
abbrev rationalGroupAlgebra (k : Type u) [Field k] := AddMonoidAlgebra k ℚ

/-- The basis element `x_α` of `k[ℚ]`. -/
def rationalGroupAlgebraBasisElement (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebra k :=
  AddMonoidAlgebra.of' k ℚ α

/-- The homomorphism `k[ℚ] → k` sending every basis element to `1`. -/
def rationalGroupAlgebraAugmentation (k : Type u) [Field k] :
    rationalGroupAlgebra k →ₐ[k] k :=
  AddMonoidAlgebra.lift k k ℚ (1 : Multiplicative ℚ →* k)

@[simp]
theorem rationalGroupAlgebraAugmentation_basisElement (k : Type u) [Field k]
    (α : ℚ) :
    rationalGroupAlgebraAugmentation k (rationalGroupAlgebraBasisElement k α) = 1 := by
  simp [rationalGroupAlgebraAugmentation, rationalGroupAlgebraBasisElement]

@[simp]
theorem rationalGroupAlgebra_basisElement_zero (k : Type u) [Field k] :
    rationalGroupAlgebraBasisElement k 0 = 1 := by
  rfl

theorem rationalGroupAlgebraBasisElement_mul (k : Type u) [Field k]
    (α β : ℚ) :
    rationalGroupAlgebraBasisElement k α * rationalGroupAlgebraBasisElement k β =
      rationalGroupAlgebraBasisElement k (α + β) := by
  sorry

/-- The augmentation is surjective. -/
theorem rationalGroupAlgebraAugmentation_surjective (k : Type u) [Field k] :
    Function.Surjective (rationalGroupAlgebraAugmentation k).toRingHom := by
  sorry

/-! ## The kernel and its cotangent space -/

/-- The kernel `J` of the augmentation. -/
def rationalGroupAlgebraKernel (k : Type u) [Field k] : Ideal (rationalGroupAlgebra k) :=
  RingHom.ker (rationalGroupAlgebraAugmentation k).toRingHom

/-- The displayed generators `x_α - 1` of the augmentation kernel. -/
def rationalGroupAlgebraKernelGenerators (k : Type u) [Field k] :
    Set (rationalGroupAlgebra k) :=
  Set.range (fun α : ℚ => rationalGroupAlgebraBasisElement k α - 1)

theorem rationalGroupAlgebra_basisElement_sub_one_mem_kernel
    (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebraBasisElement k α - 1 ∈ rationalGroupAlgebraKernel k := by
  change
    (rationalGroupAlgebraAugmentation k).toRingHom
        (rationalGroupAlgebraBasisElement k α - 1) = 0
  simp [rationalGroupAlgebraAugmentation, rationalGroupAlgebraBasisElement]

/-- The kernel is generated by the elements `x_α - 1`. -/
theorem rationalGroupAlgebraKernel_eq_span_generators (k : Type u) [Field k] :
    rationalGroupAlgebraKernel k =
      Ideal.span (rationalGroupAlgebraKernelGenerators k) := by
  sorry

/-- The conormal module `J / J²`. -/
abbrev rationalGroupAlgebraCotangent (k : Type u) [Field k] :=
  Ideal.Cotangent (rationalGroupAlgebraKernel k)

/-- The class `z_α` of `x_α - 1` in `J / J²`. -/
noncomputable def rationalGroupAlgebraCotangentGenerator
    (k : Type u) [Field k] (α : ℚ) : rationalGroupAlgebraCotangent k :=
  Ideal.toCotangent (rationalGroupAlgebraKernel k)
    ⟨rationalGroupAlgebraBasisElement k α - 1,
      rationalGroupAlgebra_basisElement_sub_one_mem_kernel k α⟩

theorem rationalGroupAlgebraBasisElement_sub_one_mul_sub_one
    (k : Type u) [Field k] (α β : ℚ) :
    (rationalGroupAlgebraBasisElement k α - 1) *
        (rationalGroupAlgebraBasisElement k β - 1) =
      (rationalGroupAlgebraBasisElement k (α + β) - 1) -
        (rationalGroupAlgebraBasisElement k α - 1) -
        (rationalGroupAlgebraBasisElement k β - 1) := by
  sorry

/-- The image of `x_α` in the residue ring `k[ℚ] / J`. -/
def rationalGroupAlgebraBasisElementResidue (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebra k ⧸ rationalGroupAlgebraKernel k :=
  Ideal.Quotient.mk (rationalGroupAlgebraKernel k)
    (rationalGroupAlgebraBasisElement k α)

/-!
The following statements record the elementary calculation in the source:
the residue of every `x_α` is `1`, hence multiplication by it on `J / J²`
is the identity; the `z_α` generate and satisfy the additive relation.
-/

theorem rationalGroupAlgebraBasisElementResidue_eq_one
    (k : Type u) [Field k] (α : ℚ) :
    rationalGroupAlgebraBasisElementResidue k α = 1 := by
  sorry

theorem rationalGroupAlgebraBasisElementResidue_smul_cotangent
    (k : Type u) [Field k] (α : ℚ) (z : rationalGroupAlgebraCotangent k) :
    rationalGroupAlgebraBasisElementResidue k α • z = z := by
  sorry

theorem rationalGroupAlgebraCotangentGenerator_add
    (k : Type u) [Field k] (α β : ℚ) :
    rationalGroupAlgebraCotangentGenerator k (α + β) =
      rationalGroupAlgebraCotangentGenerator k α +
        rationalGroupAlgebraCotangentGenerator k β := by
  sorry

theorem rationalGroupAlgebraCotangent_span_generators (k : Type u) [Field k] :
    Submodule.span k (Set.range (rationalGroupAlgebraCotangentGenerator k)) = ⊤ := by
  sorry

/-- Every cotangent vector is a finite `k`-linear combination of the `z_α`. -/
theorem rationalGroupAlgebraCotangent_exists_finite_linear_combination
    (k : Type u) [Field k] (z : rationalGroupAlgebraCotangent k) :
    ∃ c : ℚ →₀ k,
      z = c.sum (fun α a => a • rationalGroupAlgebraCotangentGenerator k α) := by
  sorry

/-! ## Characteristic computations -/

/-- The displayed characteristic-`p` step, with `p > 0`. -/
theorem rationalGroupAlgebraCotangentGenerator_charP_step
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] (α : ℚ) :
    (p : k) • rationalGroupAlgebraCotangentGenerator k (α / (p : ℚ)) =
      rationalGroupAlgebraCotangentGenerator k α := by
  sorry

/- The source's chain `0 = p z_(α/p) = z_α` is covered by this step
   together with the next vanishing theorem and `CharP.cast_eq_zero`. -/

theorem rationalGroupAlgebraCotangentGenerator_eq_zero_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] (α : ℚ) :
    rationalGroupAlgebraCotangentGenerator k α = 0 := by
  sorry

/-- In positive characteristic, `J / J²` is the zero module. -/
theorem rationalGroupAlgebraCotangent_subsingleton_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] :
    Subsingleton (rationalGroupAlgebraCotangent k) := by
  sorry

/-- The tensor-product model appearing in characteristic zero. -/
/- By symmetry of the tensor product, this is the source's `ℚ ⊗[ℤ] k` model
   with the factors ordered so that its canonical scalar action is by `k`. -/
abbrev rationalGroupAlgebraCharZeroTensor (k : Type u) [Field k] := k ⊗[ℤ] ℚ

/- Linear equivalences are data rather than propositions, so the source's
   isomorphism statements are recorded as `Nonempty` theorems. -/
/-- In characteristic zero, `J / J²` is modeled by `ℚ ⊗_ℤ k`. -/
theorem rationalGroupAlgebraCotangent_equiv_charZeroTensor
    (k : Type u) [Field k] [CharZero k] :
    Nonempty (rationalGroupAlgebraCotangent k ≃ₗ[k]
      rationalGroupAlgebraCharZeroTensor k) := by
  sorry

/-- The characteristic-zero tensor-product model is isomorphic to `k`. -/
theorem rationalGroupAlgebraCharZeroTensor_equiv_field
    (k : Type u) [Field k] [CharZero k] :
    Nonempty (rationalGroupAlgebraCharZeroTensor k ≃ₗ[k] k) := by
  sorry

/-- In characteristic zero, `J / J²` is nonzero. -/
theorem rationalGroupAlgebraCotangent_nontrivial_of_charZero
    (k : Type u) [Field k] [CharZero k] :
    Nontrivial (rationalGroupAlgebraCotangent k) := by
  sorry

/-! ## Formal smoothness and failure of flatness -/

/-- The augmentation is formally smooth in positive characteristic. -/
theorem rationalGroupAlgebraAugmentation_formallySmooth_of_charP
    (k : Type u) [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] :
    RingHom.FormallySmooth (rationalGroupAlgebraAugmentation k).toRingHom := by
  sorry

/-!
The source's square-zero lifting diagram is the standard lifting criterion
for the preceding declaration.  Mathlib's `Algebra.FormallySmooth` API
provides that criterion through `Algebra.FormallySmooth.iff_comp_surjective`,
so no parallel diagram structure is introduced here.
-/

/-- The element `x_2 - 1` used to witness non-flatness. -/
def rationalGroupAlgebraNonflatWitness (k : Type u) [Field k] : rationalGroupAlgebra k :=
  rationalGroupAlgebraBasisElement k (2 : ℚ) - 1

/-- The non-flatness witness is a nonzerodivisor. -/
theorem rationalGroupAlgebraNonflatWitness_isRegular
    (k : Type u) [Field k] :
    IsRegular (rationalGroupAlgebraNonflatWitness k) := by
  sorry

theorem rationalGroupAlgebraNonflatWitness_ne_zero
    (k : Type u) [Field k] :
    rationalGroupAlgebraNonflatWitness k ≠ 0 := by
  sorry

/-- The non-flatness witness maps to zero under the augmentation. -/
theorem rationalGroupAlgebraNonflatWitness_maps_to_zero
    (k : Type u) [Field k] :
    (rationalGroupAlgebraAugmentation k).toRingHom
        (rationalGroupAlgebraNonflatWitness k) = 0 := by
  sorry

/-- The augmentation is not flat. -/
theorem rationalGroupAlgebraAugmentation_not_flat (k : Type u) [Field k] :
    ¬ RingHom.Flat (rationalGroupAlgebraAugmentation k).toRingHom := by
  sorry

/-- A concrete instance of the formally smooth, non-flat ring map. -/
theorem exists_formallySmooth_nonflat_ringMap :
    ∃ f : rationalGroupAlgebra (ZMod 2) →+* ZMod 2,
      RingHom.FormallySmooth f ∧ ¬ RingHom.Flat f := by
  refine ⟨(rationalGroupAlgebraAugmentation (ZMod 2)).toRingHom, ?_, ?_⟩
  · exact rationalGroupAlgebraAugmentation_formallySmooth_of_charP
      (ZMod 2) 2 (Nat.zero_lt_succ 1)
  · exact rationalGroupAlgebraAugmentation_not_flat (ZMod 2)

end Formalization.«Books.Examples».Unit41
