import Mathlib.RingTheory.Etale.Basic
import Mathlib.FieldTheory.IsAlgClosed.Basic
import Mathlib.RingTheory.LocalRing.Basic
import Mathlib.RingTheory.RingHom.Flat
import Mathlib.RingTheory.RingHom.FinitePresentation
import Mathlib.RingTheory.Valuation.ValuationRing

/-!
# Examples, Chapter 42: A formally étale non-flat ring map

This file records the quotient construction, the square-zero lifting
interface, and the existence statement from the source section.  The
proposition proofs belong to the proving stage.  Quotients and image ideals
use Mathlib's canonical `Ideal.Quotient.mk` and `Ideal.map` constructions.
-/

namespace Formalization.«Books.Examples».Unit42

universe u v

/-! ## The local-ring quotient setup -/

/-- A nonzero proper idempotent ideal in a local ring is not finitely generated. -/
theorem nonzeroProperIdempotentIdeal_not_finitelyGenerated
    (A : Type u) [CommRing A] [IsLocalRing A] (J : Ideal A)
    (hJ0 : J ≠ ⊥) (hJtop : J ≠ ⊤) (hJid : J ^ 2 = J) :
    ¬ J.FG := by
  sorry

/-! ## The valuation-ring source example -/

/-- The valuation-integer ring of a nontrivially valued algebraically closed
field has a nonzero proper idempotent maximal ideal.

This records the concrete source mentioned in the text.  `v.integer` is the
canonical valuation ring supplied by Mathlib, and `v.IsNontrivial` expresses
that the valuation is nontrivial.
-/
theorem valuationInteger_maximalIdeal_nonzeroProperIdempotentIdeal
    (K : Type u) [Field K] [IsAlgClosed K]
    (Γ₀ : Type v) [LinearOrderedCommGroupWithZero Γ₀]
    (v : Valuation K Γ₀) [v.IsNontrivial] :
    (IsLocalRing.maximalIdeal v.integer ≠ ⊥) ∧
      (IsLocalRing.maximalIdeal v.integer ≠ ⊤) ∧
        (IsLocalRing.maximalIdeal v.integer) ^ 2 = IsLocalRing.maximalIdeal v.integer := by
  sorry

/-! ## Factoring through the quotient in a square-zero diagram -/

/-- The ideal-theoretic form of the displayed chain in the source diagram:
`φ(J) = φ(J²) ⊆ (φ(J)R)² ⊆ I² = 0`.

Here `Ideal.map φ J` is the ideal generated by the image of `J` in `R`;
this is the canonical interpretation of the source's `(φ(J)A)²`, corrected
to the ambient ring `R` because `φ(J) ⊆ R`.  The middle inclusion records
the consequence of commutativity of the square, while the final equality is
the square-zero hypothesis.
-/
theorem quotientDiagram_mapIdeal_chain
    {A R : Type*} [CommRing A] [CommRing R] (J : Ideal A)
    (hJ : J ^ 2 = J) (I : Ideal R) (hI : I ^ 2 = ⊥)
    (φ : A →+* R) (ψ : A ⧸ J →+* R ⧸ I)
    (hcomm : ψ.comp (Ideal.Quotient.mk J) = (Ideal.Quotient.mk I).comp φ) :
    Ideal.map φ J = Ideal.map φ (J ^ 2) ∧
      Ideal.map φ (J ^ 2) ≤ (Ideal.map φ J) ^ 2 ∧
        (Ideal.map φ J) ^ 2 ≤ I ^ 2 ∧ I ^ 2 = ⊥ := by
  sorry

/-- In the source diagram, the image of `J` in `R` is zero. -/
theorem quotientDiagram_mapIdeal_eq_bot
    {A R : Type*} [CommRing A] [CommRing R] (J : Ideal A)
    (hJ : J ^ 2 = J) (I : Ideal R) (hI : I ^ 2 = ⊥)
    (φ : A →+* R) (ψ : A ⧸ J →+* R ⧸ I)
    (hcomm : ψ.comp (Ideal.Quotient.mk J) = (Ideal.Quotient.mk I).comp φ) :
    Ideal.map φ J = ⊥ := by
  sorry

/-- The map `A → R` in a square-zero diagram factors uniquely through `A ⧸ J`. -/
theorem quotientDiagram_factorization_unique
    {A R : Type*} [CommRing A] [CommRing R] (J : Ideal A)
    (hJ : J ^ 2 = J) (I : Ideal R) (hI : I ^ 2 = ⊥)
    (φ : A →+* R) (ψ : A ⧸ J →+* R ⧸ I)
    (hcomm : ψ.comp (Ideal.Quotient.mk J) = (Ideal.Quotient.mk I).comp φ) :
    ∃! f : A ⧸ J →+* R, f.comp (Ideal.Quotient.mk J) = φ := by
  sorry


/-! ## The quotient map and the counterexample -/

/-- A quotient map is of finite type because it is surjective. -/
theorem quotientByIdealMap_finiteType
    (A : Type u) [CommRing A] (J : Ideal A) :
    RingHom.FiniteType (Ideal.Quotient.mk J) := by
  exact RingHom.FiniteType.of_surjective _ Ideal.Quotient.mk_surjective

/-- A quotient by a non-finitely-generated ideal is not finitely presented. -/
theorem quotientByIdealMap_not_finitePresentation_of_not_finitelyGenerated
    (A : Type u) [CommRing A] (J : Ideal A) (hJ : ¬ J.FG) :
    ¬ RingHom.FinitePresentation (Ideal.Quotient.mk J) := by
  sorry

/-- The quotient in the example is finite type but not finitely presented. -/
theorem quotientByIdealMap_finiteType_not_finitePresentation_of_nonzeroProperIdempotentIdeal
    (A : Type u) [CommRing A] [IsLocalRing A] (J : Ideal A)
    (hJ0 : J ≠ ⊥) (hJtop : J ≠ ⊤) (hJid : J ^ 2 = J) :
    RingHom.FiniteType (Ideal.Quotient.mk J) ∧
      ¬ RingHom.FinitePresentation (Ideal.Quotient.mk J) := by
  exact ⟨quotientByIdealMap_finiteType A J,
    quotientByIdealMap_not_finitePresentation_of_not_finitelyGenerated A J
      (nonzeroProperIdempotentIdeal_not_finitelyGenerated A J hJ0 hJtop hJid)⟩

/-- The quotient map by an idempotent ideal is formally étale. -/
theorem quotientByIdealMap_formallyEtale_of_idempotent
    (A : Type u) [CommRing A] (J : Ideal A) (hJ : J ^ 2 = J) :
    RingHom.FormallyEtale (Ideal.Quotient.mk J) := by
  sorry

/-- The quotient map by a nonzero proper idempotent ideal in a local ring is not flat. -/
theorem quotientByIdealMap_not_flat_of_nonzeroProperIdempotentIdeal
    (A : Type u) [CommRing A] [IsLocalRing A] (J : Ideal A)
    (hJ0 : J ≠ ⊥) (hJtop : J ≠ ⊤) (hJid : J ^ 2 = J) :
    ¬ RingHom.Flat (Ideal.Quotient.mk J) := by
  sorry

/-- The displayed quotient map is formally étale but non-flat. -/
theorem quotientByIdealMap_formallyEtale_not_flat
    (A : Type u) [CommRing A] [IsLocalRing A] (J : Ideal A)
    (hJ0 : J ≠ ⊥) (hJtop : J ≠ ⊤) (hJid : J ^ 2 = J) :
    RingHom.FormallyEtale (Ideal.Quotient.mk J) ∧
      ¬ RingHom.Flat (Ideal.Quotient.mk J) := by
  exact ⟨quotientByIdealMap_formallyEtale_of_idempotent A J hJid,
    quotientByIdealMap_not_flat_of_nonzeroProperIdempotentIdeal A J
      hJ0 hJtop hJid⟩

/-!
The existence result below is the mathematical counterexample asserted in
the source discussion: the quotient is finite type and formally étale but
not flat (and, because `J` is not finitely generated, not finitely
presented).  The source's references to the two EGA statements and to the
error in the proof of the first are bibliographic commentary, so they are
recorded here as context rather than as additional Lean propositions.
-/

/-- There is a local ring with a nonzero proper idempotent ideal. -/
theorem exists_localRing_nonzeroProperIdempotentIdeal :
    ∃ (A : Type) (_ : CommRing A) (_ : IsLocalRing A) (J : Ideal A),
      J ≠ ⊥ ∧ J ≠ ⊤ ∧ J ^ 2 = J := by
  sorry

/-- There exist formally étale non-flat quotient ring maps. -/
theorem exists_formallyEtale_nonflat_quotient_map :
    ∃ (A : Type) (_ : CommRing A) (_ : IsLocalRing A) (J : Ideal A),
      J ≠ ⊥ ∧ J ≠ ⊤ ∧ J ^ 2 = J ∧
        RingHom.FiniteType (Ideal.Quotient.mk J) ∧
          ¬ RingHom.FinitePresentation (Ideal.Quotient.mk J) ∧
            RingHom.FormallyEtale (Ideal.Quotient.mk J) ∧
              ¬ RingHom.Flat (Ideal.Quotient.mk J) := by
  sorry

/-- There exist formally étale non-flat ring maps. -/
theorem exists_formallyEtale_nonflat_ring_map :
    ∃ (A B : Type) (_ : CommRing A) (_ : CommRing B) (f : A →+* B),
      RingHom.FormallyEtale f ∧ ¬ RingHom.Flat f := by
  sorry

end Formalization.«Books.Examples».Unit42
