import Formalization.Books.Topology.Unit02.BasicNotions
import Mathlib.Topology.Bases

/-!
# Topology, Chapter 5: Bases

The source's notion of a base is Mathlib's canonical
`TopologicalSpace.IsTopologicalBasis`.  Its open-set, covering, intersection,
and generation fields express the two clauses in the source definition
without introducing a parallel predicate.  The relative open-cover statement
uses the cover and refinement interfaces from Chapter 2.
-/

namespace Formalization.Books.Topology.Unit05

open Set
open TopologicalSpace

universe u v

section Bases

/-! ## Bases -/

/-
The source's base definition is represented directly by
`TopologicalSpace.IsTopologicalBasis`.  In particular, for
`h : IsTopologicalBasis 𝔅`, `h.isOpen` gives that basis elements are open and
`h.exists_subset_of_mem_open` gives the local refinement clause.

The declarations below retain the source order: basis data, refinements,
subbases, and then the quotient construction.
-/

variable {X : Type u} [TopologicalSpace X]

theorem isTopologicalBasis_iff
    {𝔅 : Set (Set X)} :
    IsTopologicalBasis 𝔅 ↔
      (∀ U ∈ 𝔅, IsOpen U) ∧
        ∀ (U : Set X), IsOpen U → ∀ x ∈ U,
          ∃ B ∈ 𝔅, x ∈ B ∧ B ⊆ U := by
  constructor
  · intro h
    refine ⟨fun U hU => h.isOpen hU, ?_⟩
    intro U hU x hx
    exact h.exists_subset_of_mem_open hx hU
  · rintro ⟨hopen, hlocal⟩
    exact TopologicalSpace.isTopologicalBasis_of_isOpen_of_nhds hopen
      (fun x U hx hU => hlocal U hU x hx)

/- The topology generated by a covering family with the basis intersection
   property is unique. -/
theorem exists_unique_topology_of_basis_data
    (X : Type u) (𝔅 : Set (Set X))
    (hcover : ⋃₀ 𝔅 = (Set.univ : Set X))
    (hinter : ∀ ⦃B₁ B₂ : Set X⦄ ⦃x : X⦄,
      B₁ ∈ 𝔅 → B₂ ∈ 𝔅 → x ∈ B₁ ∩ B₂ →
        ∃ B₃ ∈ 𝔅, x ∈ B₃ ∧ B₃ ⊆ B₁ ∩ B₂) :
    ∃! t : TopologicalSpace X,
      @TopologicalSpace.IsTopologicalBasis X t 𝔅 := by
  let t : TopologicalSpace X := TopologicalSpace.generateFrom 𝔅
  have ht : @TopologicalSpace.IsTopologicalBasis X t 𝔅 :=
    { exists_subset_inter := by
        intro B₁ hB₁ B₂ hB₂ x hx
        exact hinter hB₁ hB₂ hx
      sUnion_eq := hcover
      eq_generateFrom := rfl }
  refine ⟨t, ht, ?_⟩
  intro t' ht'
  exact
    (TopologicalSpace.IsTopologicalBasis.eq_generateFrom (t := t') ht').trans
      (TopologicalSpace.IsTopologicalBasis.eq_generateFrom (t := t) ht).symm

/- The basis refinement lemma for a relative open cover. -/
theorem exists_basis_refinement
    {𝔅 : Set (Set X)} (h𝔅 : IsTopologicalBasis 𝔅)
    {U : Set X} {ι : Type v} (𝒰 : ι → Set X)
    (hu : Formalization.Books.Topology.Unit02.IsOpenCoverOf U 𝒰) :
    ∃ (κ : Type (max u v)) (v : κ → Set X),
      Formalization.Books.Topology.Unit02.IsOpenCoverRefinement U 𝒰 v ∧
        ∀ j, v j ∈ 𝔅 := by
  classical
  let κ := {p : ι × X // p.2 ∈ 𝒰 p.1}
  have hchoose : ∀ p : κ,
      ∃ V ∈ 𝔅, p.1.2 ∈ V ∧ V ⊆ 𝒰 p.1.1 := by
    intro p
    exact h𝔅.exists_subset_of_mem_open p.2 (hu.1 p.1.1)
  choose v hvB hvx hvsub using hchoose
  refine ⟨κ, v, ?_, hvB⟩
  refine ⟨hu, ?_, ?_⟩
  · constructor
    · intro p
      exact h𝔅.isOpen (hvB p)
    · ext x
      constructor
      · intro hx
        rcases mem_iUnion.1 hx with ⟨p, hxp⟩
        have hxu : x ∈ 𝒰 p.1.1 := hvsub p hxp
        have hxU : x ∈ ⋃ i, 𝒰 i := mem_iUnion.2 ⟨p.1.1, hxu⟩
        rw [hu.2] at hxU
        exact hxU
      · intro hx
        rw [← hu.2] at hx
        rcases mem_iUnion.1 hx with ⟨i, hxi⟩
        let p : κ := ⟨(i, x), hxi⟩
        exact mem_iUnion.2 ⟨p, by simpa [p] using hvx p⟩
  · intro p
    exact ⟨p.1.1, hvsub p⟩

/-! ## Subbases -/

/- The collection of all finite intersections, including the empty
   intersection `univ`, in a family of sets. -/
def finiteIntersections {X : Type u} (𝔅 : Set (Set X)) : Set (Set X) :=
  (fun F : Set (Set X) => ⋂₀ F) ''
    {F : Set (Set X) | F.Finite ∧ F ⊆ 𝔅}

/-!
Mathlib has no separate subbasis predicate.  This is the source-facing
interface whose body is exactly the canonical finite-intersection basis
condition; the topology remains Mathlib's `TopologicalSpace` instance.
-/
def IsSubbasis {X : Type u} [t : TopologicalSpace X]
    (𝔅 : Set (Set X)) : Prop :=
  @TopologicalSpace.IsTopologicalBasis X t (finiteIntersections 𝔅)

theorem IsSubbasis.isOpen_of_mem {𝔅 : Set (Set X)}
    (h𝔅 : IsSubbasis 𝔅) {U : Set X} (hU : U ∈ 𝔅) : IsOpen U := by
  apply h𝔅.isOpen
  change U ∈
    (fun F : Set (Set X) => ⋂₀ F) ''
      {F : Set (Set X) | F.Finite ∧ F ⊆ 𝔅}
  refine ⟨{U}, ⟨finite_singleton U, singleton_subset_iff.mpr hU⟩, ?_⟩
  simp

/- The topology generated by a subbasis is the unique topology for which its
   finite intersections form a topological basis. -/
theorem exists_unique_topology_of_subbasis
    (X : Type u) (𝔅 : Set (Set X)) :
    ∃! t : TopologicalSpace X, @IsSubbasis X t 𝔅 := by
  let t : TopologicalSpace X := TopologicalSpace.generateFrom 𝔅
  have ht : @IsSubbasis X t 𝔅 := by
    change @TopologicalSpace.IsTopologicalBasis X t (finiteIntersections 𝔅)
    exact TopologicalSpace.isTopologicalBasis_of_subbasis (t := t) rfl
  refine ⟨t, ht, ?_⟩
  intro t' ht'
  change @TopologicalSpace.IsTopologicalBasis X t' (finiteIntersections 𝔅) at ht'
  have hgen :
      @TopologicalSpace.IsTopologicalBasis X t (finiteIntersections 𝔅) := by
    exact TopologicalSpace.isTopologicalBasis_of_subbasis (t := t) rfl
  exact
    (TopologicalSpace.IsTopologicalBasis.eq_generateFrom (t := t') ht').trans
      (TopologicalSpace.IsTopologicalBasis.eq_generateFrom (t := t) hgen).symm

/-! ## The quotient map attached to a subcollection -/

/- The equivalence relation from the source identifies points having the same
   membership pattern in the chosen collection. -/
def basisMembershipSetoid {X : Type u} (𝔅 : Set (Set X)) : Setoid X where
  r x y := ∀ U ∈ 𝔅, x ∈ U ↔ y ∈ U
  iseqv :=
    { refl := fun _ _ _ => Iff.rfl
      symm := fun h U hU => (h U hU).symm
      trans := fun hxy hyz U hU => (hxy U hU).trans (hyz U hU) }

/-- The quotient of `X` by agreement on membership in `𝔅`. -/
def basisQuotient {X : Type u} (𝔅 : Set (Set X)) : Type u :=
  Quotient (basisMembershipSetoid 𝔅)

/-- The natural map to the quotient determined by `𝔅`. -/
def basisQuotientMap {X : Type u} (𝔅 : Set (Set X)) : X → basisQuotient 𝔅 :=
  @Quotient.mk' X (basisMembershipSetoid 𝔅)

/-- The images of the chosen subsets in the quotient. -/
def basisQuotientBasis {X : Type u} (𝔅 : Set (Set X)) :
    Set (Set (basisQuotient 𝔅)) :=
  Set.image (basisQuotientMap 𝔅) '' 𝔅

/- The topology generated by the quotient images of the chosen subsets. -/
@[instance_reducible]
def basisQuotientTopology {X : Type u} (𝔅 : Set (Set X)) :
    TopologicalSpace (basisQuotient 𝔅) :=
  TopologicalSpace.generateFrom (basisQuotientBasis 𝔅)

/-
The preceding definitions make the construction in the source explicit.  The
following interface records all three numbered conclusions: the quotient map
is continuous, each chosen image is open, its preimage is the original set,
and the chosen images form a basis for the displayed quotient topology.
-/
theorem basis_quotient_map_spec
    (𝔅 : Set (Set X))
    (hopen : ∀ U ∈ 𝔅, IsOpen U)
    (hcover : ⋃₀ 𝔅 = (Set.univ : Set X))
    (hinter : ∀ ⦃U V : Set X⦄,
      U ∈ 𝔅 → V ∈ 𝔅 →
        U ∩ V = ⋃₀ {W : Set X | W ∈ 𝔅 ∧ W ⊆ U ∩ V}) :
    letI : TopologicalSpace (basisQuotient 𝔅) := basisQuotientTopology 𝔅
    Continuous (basisQuotientMap 𝔅) ∧
      (∀ U ∈ 𝔅, IsOpen (basisQuotientMap 𝔅 '' U)) ∧
      (∀ U ∈ 𝔅,
          basisQuotientMap 𝔅 ⁻¹' (basisQuotientMap 𝔅 '' U) = U) ∧
          IsTopologicalBasis (basisQuotientBasis 𝔅) := by
  let _ : TopologicalSpace (basisQuotient 𝔅) := basisQuotientTopology 𝔅
  have map_eq_iff {x y : X} :
      basisQuotientMap 𝔅 x = basisQuotientMap 𝔅 y ↔
        ∀ U ∈ 𝔅, x ∈ U ↔ y ∈ U := by
    change
      @Quotient.mk' X (basisMembershipSetoid 𝔅) x =
          @Quotient.mk' X (basisMembershipSetoid 𝔅) y ↔
        (basisMembershipSetoid 𝔅).r x y
    exact @Quotient.eq' X (basisMembershipSetoid 𝔅) x y
  have hpreimage (U : Set X) (hU : U ∈ 𝔅) :
      basisQuotientMap 𝔅 ⁻¹' (basisQuotientMap 𝔅 '' U) = U := by
    ext x
    constructor
    · intro hx
      rcases hx with ⟨y, hy, hxy⟩
      exact (map_eq_iff.mp hxy U hU).mp hy
    · intro hx
      exact ⟨x, hx, rfl⟩
  have hsurjective : Function.Surjective (basisQuotientMap 𝔅) := by
    intro y
    exact (@Quotient.mk'_surjective X (basisMembershipSetoid 𝔅)) y
  have hquotient_cover :
      ⋃₀ basisQuotientBasis 𝔅 = (Set.univ : Set (basisQuotient 𝔅)) := by
    apply sUnion_eq_univ_iff.mpr
    intro y
    obtain ⟨x, rfl⟩ := hsurjective y
    rcases sUnion_eq_univ_iff.mp hcover x with ⟨U, hU, hxU⟩
    exact ⟨basisQuotientMap 𝔅 '' U, ⟨U, hU, rfl⟩, ⟨x, hxU, rfl⟩⟩
  have hquotient_basis :
      @TopologicalSpace.IsTopologicalBasis (basisQuotient 𝔅)
        (basisQuotientTopology 𝔅) (basisQuotientBasis 𝔅) := by
    refine
      { exists_subset_inter := ?_
        sUnion_eq := hquotient_cover
        eq_generateFrom := rfl }
    rintro _ ⟨U, hU, rfl⟩ _ ⟨V, hV, rfl⟩ y ⟨hyU, hyV⟩
    rcases hyU with ⟨x, hxU, hxyU⟩
    rcases hyV with ⟨z, hzV, hzyV⟩
    have hxV : x ∈ V := by
      have hxz : basisQuotientMap 𝔅 x = basisQuotientMap 𝔅 z :=
        hxyU.trans hzyV.symm
      exact (map_eq_iff.mp hxz V hV).mpr hzV
    have hxUV : x ∈ ⋃₀ {W : Set X | W ∈ 𝔅 ∧ W ⊆ U ∩ V} := by
      rw [← hinter hU hV]
      exact ⟨hxU, hxV⟩
    rcases mem_sUnion.mp hxUV with ⟨W, ⟨hW, hWUV⟩, hxW⟩
    refine
      ⟨basisQuotientMap 𝔅 '' W, ⟨W, hW, rfl⟩,
        ⟨x, hxW, hxyU⟩, ?_⟩
    rintro q ⟨w, hw, rfl⟩
    exact ⟨⟨w, (hWUV hw).1, rfl⟩, ⟨w, (hWUV hw).2, rfl⟩⟩
  have himage_open : ∀ U ∈ 𝔅,
      IsOpen (basisQuotientMap 𝔅 '' U) := by
    intro U hU
    exact hquotient_basis.isOpen ⟨U, hU, rfl⟩
  have hcontinuous : Continuous (basisQuotientMap 𝔅) := by
    apply continuous_generateFrom_iff.mpr
    rintro _ ⟨U, hU, rfl⟩
    rw [hpreimage U hU]
    exact hopen U hU
  exact ⟨hcontinuous, himage_open, hpreimage, hquotient_basis⟩

end Bases

end Formalization.Books.Topology.Unit05
