import Formalization.Books.Algebra.Unit71
import Mathlib.RingTheory.DualNumber
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Exercises, Chapter 11: Ext groups — infinitely many nonzero groups

The dual numbers over a field give the standard Noetherian example: the
residue field has a periodic free resolution, so its Ext groups with itself
are nonzero in every degree.
-/

namespace Formalization.Books.Exercises.Unit11

open Formalization.Books.Algebra.Unit71

universe u

noncomputable section

/-! ## A Noetherian example -/

/-- The dual-number ring `k[ε]`. -/
abbrev dualNumberRing (k : Type u) [Field k] := DualNumber k

/-- The nilpotent ideal generated by `ε` in the dual-number ring. -/
def dualNumberNilpotentIdeal (k : Type u) [Field k] :
    Ideal (dualNumberRing k) :=
  Ideal.span {DualNumber.eps}

/-- The residue module of the dual-number local ring. -/
abbrev dualNumberResidueModule (k : Type u) [Field k] :
    ModuleCat (dualNumberRing k) :=
  ModuleCat.of (dualNumberRing k)
    (dualNumberRing k ⧸ dualNumberNilpotentIdeal k)

/-- The dual-number residue module is finite, and all of its self-Ext groups
are nonzero. -/
theorem dual_number_residue_ext_nonzero (k : Type u) [Field k] :
    IsNoetherianRing (dualNumberRing k) ∧
      Module.Finite (dualNumberRing k) (dualNumberResidueModule k) ∧
      ∀ i : ℕ,
        Nonempty
          (ExtGroup (dualNumberResidueModule k)
            (dualNumberResidueModule k) i ≃+ k) := by
  sorry

end

end Formalization.Books.Exercises.Unit11
