import Formalization.Books.Algebra.Unit44.SeparableExtensionsContinued
import Formalization.Books.Algebra.Unit136.SyntomicMorphisms
import Formalization.Books.Algebra.Unit138.FormallySmoothMaps
import Formalization.Books.Algebra.Unit150.FormallyEtaleMaps
import Mathlib.Algebra.Algebra.ZMod
import Mathlib.Data.ZMod.Basic
import Mathlib.FieldTheory.Perfect
import Mathlib.LinearAlgebra.FiniteDimensional.Defs
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Smooth.Field

/-!
# Commutative Algebra, Chapter 158: Formal smoothness of fields

The source section is formalized using the canonical field-extension,
Kähler-differential, formal-smoothness, formal-étaleness, geometric
reducedness, syntomic, and directed-colimit interfaces already available in
Mathlib and earlier chapters.  The theorem proofs are intentionally deferred.
-/

namespace Formalization.Books.Algebra.Unit158

open Set
open scoped TensorProduct
open Formalization.Books.Algebra.Unit42
open Formalization.Books.Algebra.Unit43

noncomputable section

universe u v w

/-! ## Finitely generated extensions and differentials -/

/-- The six equivalent characterizations of a finitely generated separable
algebraic field extension from the source. -/
theorem characterize_finitelyGenerated_fieldExtension
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    [Algebra.EssFiniteType k K] :
    List.TFAE
      [ FiniteDimensional k K ∧ Algebra.IsSeparable k K,
        Subsingleton (KaehlerDifferential k K),
        Algebra.FormallyUnramified k K,
        Algebra.Unramified k K,
        Algebra.FormallyEtale k K,
        Algebra.Etale k K ] := by
  sorry

/- The source's notation `d a` is the canonical universal derivation. -/
abbrev differential
    {R : Type u} {S : Type v} [CommRing R] [CommRing S] [Algebra R S]
    (a : S) : KaehlerDifferential R S :=
  KaehlerDifferential.D R S a

/-- The prime characteristic supplied by a positive characteristic field. -/
theorem charPrimeFact
    {k : Type u} [Field k] (p : ℕ) (hp : 0 < p) [CharP k p] :
    Fact (Nat.Prime p) :=
  by exact ⟨CharP.char_prime_of_ne_zero (R := k) (Nat.ne_of_gt hp)⟩

/-- The characteristic of an extension field agrees with that of its base. -/
theorem extensionCharP
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (p : ℕ) (hp : 0 < p) [CharP k p] : CharP K p :=
  by
    exact CharP.of_ringHom_of_ne_zero (algebraMap k K) p
      (charPrimeFact (k := k) p hp).out.ne_zero

/-- Over a perfect field of characteristic `p`, the kernel of the universal
derivation consists exactly of the `p`-th powers. -/
theorem derivative_zero_iff_pthPower
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (p : ℕ) (hp : 0 < p) [CharP k p] [PerfectField k] (a : K) :
    differential (R := k) (S := K) a = 0 ↔ ∃ b : K, b ^ p = a := by
  sorry

/-- The degree of the field generated by independent `p`-th roots.  The
roots are represented by elements of an ambient field, and the generated
extension by `IntermediateField.adjoin`. -/
theorem size_extension_pthRoots
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (p n : ℕ) (hp : 0 < p) [CharP k p] (a : Fin n → k) (r : Fin n → K)
    (hr : ∀ i, r i ^ p = algebraMap k K (a i))
    : letI : Fact (Nat.Prime p) := charPrimeFact (k := k) p hp
      letI : Algebra (ZMod p) k :=
        @ZMod.algebra k _ p (inferInstance : CharP k p)
      LinearIndependent k
          (fun i => differential (R := ZMod p) (S := k) (a i)) →
        Module.finrank k (IntermediateField.adjoin k (range r)) = p ^ n := by
  sorry

/-- In positive characteristic, separability is equivalent to injectivity of
the base-change map on Kähler differentials. -/
theorem separable_differentials
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (p : ℕ) (hp : 0 < p) [CharP k p] :
    letI : Fact (Nat.Prime p) := charPrimeFact (k := k) p hp
    letI : Algebra (ZMod p) k :=
      @ZMod.algebra k _ p (inferInstance : CharP k p)
    letI : CharP K p := extensionCharP (k := k) (K := K) p hp
    letI : Algebra (ZMod p) K :=
      @ZMod.algebra K _ p (inferInstance : CharP K p)
    IsSeparableExtension k K ↔
        Function.Injective (KaehlerDifferential.mapBaseChange (ZMod p) k K) := by
  sorry

/-! ## Formal smoothness of field extensions -/

/-- Formal smoothness of a field extension implies separability. -/
theorem formallySmooth_implies_separable
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (h : Algebra.FormallySmooth k K) :
    IsSeparableExtension k K := by
  sorry

/-- For field extensions, formal smoothness is equivalent to vanishing of the
first cotangent homology module. -/
theorem formallySmooth_iff_h1Cotangent_subsingleton
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K] :
    Algebra.FormallySmooth k K ↔ Subsingleton (Algebra.H1Cotangent k K) := by
  sorry

/-- A purely transcendental extension is formally smooth. -/
theorem formallySmooth_of_purelyTranscendental
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    {ι : Type w} (x : ι → K)
    (hx : AlgebraicIndependent k x)
    (hgen : IntermediateField.adjoin k (range x) = ⊤) :
    Algebra.FormallySmooth k K := by
  exact Algebra.FormallySmooth.of_algebraicIndependent hx hgen

/-- A separable algebraic extension is formally smooth. -/
theorem formallySmooth_of_separableAlgebraic
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    [Algebra.IsAlgebraic k K] [Algebra.IsSeparable k K] :
    Algebra.FormallySmooth k K := by
  sorry

/-- Every separable extension is formally smooth. -/
theorem formallySmooth_of_separableExtension
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (hK : IsSeparableExtension k K) :
    Algebra.FormallySmooth k K := by
  sorry

/-- In characteristic zero every field extension is formally smooth. -/
theorem fields_formallySmooth_of_charZero
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    [CharZero k] :
    Algebra.FormallySmooth k K := by
  sorry

/-- In positive characteristic, formal smoothness of a field extension is
equivalent to separability. -/
theorem fields_formallySmooth_iff_separable_of_charP
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (p : ℕ) (hp : 0 < p) [CharP k p] :
    Algebra.FormallySmooth k K ↔ IsSeparableExtension k K := by
  sorry

/-! ## The combined characterizations -/

/-- The characteristic-zero list of equivalent separability criteria. -/
theorem characterize_separable_fieldExtension_charZero
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    [CharZero k] :
    IsSeparableExtension k K ∧
      IsGeometricallyReduced k K ∧
      Algebra.FormallySmooth k K ∧
      Subsingleton (Algebra.H1Cotangent k K) ∧
      Function.Injective (KaehlerDifferential.mapBaseChange ℤ k K) := by
  sorry

/-- The positive-characteristic list of equivalent separability criteria.  The
canonical `AdjoinPthRoots` construction represents the source's `k^{1/p}`. -/
theorem characterize_separable_fieldExtension_charP
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    (p : ℕ) (hp : 0 < p) [CharP k p] :
    letI : Fact (Nat.Prime p) := charPrimeFact (k := k) p hp
    letI : Algebra (ZMod p) k :=
      @ZMod.algebra k _ p (inferInstance : CharP k p)
    letI : CharP K p := extensionCharP (k := k) (K := K) p hp
    letI : Algebra (ZMod p) K :=
      @ZMod.algebra K _ p (inferInstance : CharP K p)
    List.TFAE
      [ IsSeparableExtension k K,
        IsReduced (K ⊗[k] AdjoinPthRoots k),
        IsGeometricallyReduced k K,
        Function.Injective (KaehlerDifferential.mapBaseChange (ZMod p) k K),
        Subsingleton (Algebra.H1Cotangent k K),
        Algebra.FormallySmooth k K ] := by
  sorry

/-! ## Smooth models and filtered colimits -/

/-- A source-facing package for a smooth domain whose fraction field is the
given field extension. -/
structure SmoothDomainLocalization
    (k : Type u) (K : Type v) [Field k] [Field K] [Algebra k K] where
  R : Type u
  [commRingR : CommRing R]
  M : Submonoid R
  [algebraKR : Algebra k R]
  [finiteType : Algebra.FiniteType k R]
  [smooth : Algebra.Smooth k R]
  [domain : IsDomain R]
  [algebraRK : Algebra R K]
  [tower : IsScalarTower k R K]
  [localization : IsLocalization M K]

/-- A finitely generated field extension is separable exactly when it is the
fraction field, hence a localization, of a smooth algebra over the base. -/
theorem localization_smooth_iff_separable
    {k : Type u} {K : Type v} [Field k] [Field K] [Algebra k K]
    [Algebra.EssFiniteType k K] :
    IsSeparableExtension k K ↔ Nonempty (SmoothDomainLocalization k K) := by
  sorry

/-- A field extension is a filtered colimit of relative global complete
intersections over its base. -/
theorem field_is_filteredColimit_of_globalCompleteIntersection
    {k K : Type u} [Field k] [Field K] [Algebra k K] :
    ∃ D : Formalization.Books.Algebra.Unit127.DirectedAlgebraColimit
        (algebraMap k K),
      ∀ i, letI : Preorder D.index := D.indexPreorder
        Formalization.Books.Algebra.Unit136.IsRelativeGlobalCompleteIntersection
          (D.diagram.obj i).hom.hom := by
  sorry

/-- A separable field extension is a filtered colimit of smooth algebras over
the base. -/
theorem separable_field_is_filteredColimit_of_smooth
    {k K : Type u} [Field k] [Field K] [Algebra k K]
    (hK : IsSeparableExtension k K) :
    ∃ D : Formalization.Books.Algebra.Unit127.DirectedAlgebraColimit
        (algebraMap k K),
      ∀ i, letI : Preorder D.index := D.indexPreorder
        letI : Algebra k (D.diagram.obj i).right :=
          (D.diagram.obj i).hom.hom.toAlgebra
        Algebra.Smooth k (D.diagram.obj i).right := by
  sorry

end

end Formalization.Books.Algebra.Unit158
